{"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"bindGroupEventsListener","kind":"identifier"},{"kind":"text","text":"("},{"text":"listener","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(pl)GroupServiceListener","text":"GroupServiceListener","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupServiceListener"},{"kind":"text","text":")"}],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":""},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupServiceListener"}],"type":"paragraph"}],"name":"listener"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupService\/bindGroupEventsListener(listener:)"},"kind":"symbol","metadata":{"roleHeading":"Instance Method","role":"symbol","required":true,"modules":[{"name":"ShengwangChatUIKit"}],"title":"bindGroupEventsListener(listener:)","symbolKind":"method","navigatorTitle":[{"text":"bindGroupEventsListenerWithListener:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"bindGroupEventsListener"},{"kind":"text","text":"("},{"kind":"externalParam","text":"listener"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(pl)GroupServiceListener","text":"GroupServiceListener","kind":"typeIdentifier"},{"kind":"text","text":")"}],"externalID":"c:@M@ShengwangChatUIKit@objc(pl)GroupService(im)bindGroupEventsListenerWithListener:"},"variants":[{"paths":["\/documentation\/shengwangchatuikit\/groupservice\/bindgroupeventslistener(listener:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/groupservice\/bindgroupeventslistener(listener:)"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupService"]]},"abstract":[{"type":"text","text":"Bind group event  changed listener"}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/GroupService":{"navigatorTitle":[{"text":"GroupService","kind":"identifier"}],"type":"topic","title":"GroupService","role":"symbol","url":"\/documentation\/shengwangchatuikit\/groupservice","kind":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupService","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GroupService","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/GroupService/bindGroupEventsListener(listener:)":{"required":true,"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"bindGroupEventsListener","kind":"identifier"},{"text":"(","kind":"text"},{"text":"listener","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"GroupServiceListener","kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(pl)GroupServiceListener"},{"kind":"text","text":")"}],"url":"\/documentation\/shengwangchatuikit\/groupservice\/bindgroupeventslistener(listener:)","abstract":[{"type":"text","text":"Bind group event  changed listener"}],"kind":"symbol","title":"bindGroupEventsListener(listener:)","type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupService\/bindGroupEventsListener(listener:)","navigatorTitle":[{"kind":"identifier","text":"bindGroupEventsListenerWithListener:"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/GroupServiceListener":{"url":"\/documentation\/shengwangchatuikit\/groupservicelistener","abstract":[],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"GroupServiceListener"}],"type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupServiceListener","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GroupServiceListener","kind":"identifier"}],"title":"GroupServiceListener"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"bindGroupEventsListenerWithListener:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"bindGroupEventsListenerWithListener:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"bindGroupEventsListenerWithListener:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"id<GroupServiceListener>","preciseIdentifier":"c:Qo@M@ShengwangChatUIKit@objc(pl)GroupServiceListener"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"listener"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"listener","content":[{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupServiceListener"}]}]}]}},{"value":"GroupService","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupService\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupService\/fragments","value":[{"text":"GroupService","kind":"identifier"}]},{"op":"replace","value":[{"text":"GroupService","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupService\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupService~1bindGroupEventsListener(listener:)\/title","value":"bindGroupEventsListenerWithListener:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupService~1bindGroupEventsListener(listener:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"bindGroupEventsListenerWithListener:","kind":"identifier"}]},{"value":"GroupServiceListener","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupServiceListener\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupServiceListener\/fragments","value":[{"text":"GroupServiceListener","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupServiceListener\/navigatorTitle","op":"replace","value":[{"text":"GroupServiceListener","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}