{"abstract":[{"text":"Decline the application of the user.","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/groupservice\/declinejoinapplication(groupid:userid:reason:completion:)"]},{"paths":["\/documentation\/shengwangchatuikit\/groupservice\/declinejoinapplication(groupid:userid:reason:completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"declineJoinApplication"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"groupId"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"userId","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"reason","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" ("},{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatGroup","preciseIdentifier":"s:18ShengwangChatUIKit0B5Groupa","kind":"typeIdentifier","text":"ChatGroup"},{"kind":"text","text":"?, "},{"text":"ChatError","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatError","kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit0B5Errora"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"content":[{"inlineContent":[{"text":"ID of the group.","type":"text"}],"type":"paragraph"}],"name":"groupId"},{"name":"userId","content":[{"inlineContent":[{"type":"text","text":"ID of the user."}],"type":"paragraph"}]},{"name":"reason","content":[{"inlineContent":[{"type":"text","text":"Reason for rejection."}],"type":"paragraph"}]},{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"text":"The request callback contains the group object and error information. If successful, a non-empty group object will be returned. If failed, a non-empty group object will be returned.","type":"text"}]}]}],"kind":"parameters"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupService\/declineJoinApplication(groupId:userId:reason:completion:)"},"sections":[],"metadata":{"externalID":"c:@M@ShengwangChatUIKit@objc(pl)GroupService(im)declineJoinApplicationWithGroupId:userId:reason:completion:","navigatorTitle":[{"text":"declineJoinApplicationWithGroupId:userId:reason:completion:","kind":"identifier"}],"role":"symbol","required":true,"modules":[{"name":"ShengwangChatUIKit"}],"title":"declineJoinApplication(groupId:userId:reason:completion:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"declineJoinApplication"},{"kind":"text","text":"("},{"kind":"externalParam","text":"groupId"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"userId"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"text":"reason","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"ChatGroup","kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit0B5Groupa"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"ChatError","preciseIdentifier":"s:18ShengwangChatUIKit0B5Errora"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"roleHeading":"Instance Method","symbolKind":"method"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupService"]]},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/GroupService/declineJoinApplication(groupId:userId:reason:completion:)":{"url":"\/documentation\/shengwangchatuikit\/groupservice\/declinejoinapplication(groupid:userid:reason:completion:)","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupService\/declineJoinApplication(groupId:userId:reason:completion:)","type":"topic","navigatorTitle":[{"kind":"identifier","text":"declineJoinApplicationWithGroupId:userId:reason:completion:"}],"role":"symbol","abstract":[{"type":"text","text":"Decline the application of the user."}],"required":true,"title":"declineJoinApplication(groupId:userId:reason:completion:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"declineJoinApplication"},{"kind":"text","text":"("},{"text":"groupId","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"userId"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"reason"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit0B5Groupa","text":"ChatGroup"},{"text":"?, ","kind":"text"},{"text":"ChatError","preciseIdentifier":"s:18ShengwangChatUIKit0B5Errora","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatError":{"fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChatError"}],"role":"symbol","navigatorTitle":[{"text":"ChatError","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatError","url":"\/documentation\/shengwangchatuikit\/chaterror","title":"ChatError","kind":"symbol","abstract":[]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/GroupService":{"navigatorTitle":[{"text":"GroupService","kind":"identifier"}],"type":"topic","title":"GroupService","role":"symbol","url":"\/documentation\/shengwangchatuikit\/groupservice","kind":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupService","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GroupService","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatGroup":{"type":"topic","role":"symbol","title":"ChatGroup","kind":"symbol","abstract":[],"navigatorTitle":[{"text":"ChatGroup","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/chatgroup","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatGroup","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"text":"ChatGroup","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"declineJoinApplicationWithGroupId:userId:reason:completion:","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"text":"- ","kind":"text"},{"text":"declineJoinApplicationWithGroupId:userId:reason:completion:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"text":"declineJoinApplicationWithGroupId:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"groupId","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"userId:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"userId","kind":"internalParam"},{"kind":"text","text":" "},{"text":"reason:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"reason","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"completion:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":" (^"},{"text":")(","kind":"text"},{"text":"AgoraChatGroup","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AgoraChatGroup"},{"text":" * ","kind":"text"},{"text":"","kind":"internalParam"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AgoraChatError","text":"AgoraChatError"},{"kind":"text","text":" * "},{"kind":"internalParam","text":""},{"kind":"text","text":")) "},{"kind":"internalParam","text":"completion"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"groupId","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"ID of the group."}]}]},{"name":"userId","content":[{"type":"paragraph","inlineContent":[{"text":"ID of the user.","type":"text"}]}]},{"name":"reason","content":[{"inlineContent":[{"text":"Reason for rejection.","type":"text"}],"type":"paragraph"}]},{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"text":"The request callback contains the group object and error information. If successful, a non-empty group object will be returned. If failed, a non-empty group object will be returned.","type":"text"}]}]}]},"op":"replace"},{"value":"declineJoinApplicationWithGroupId:userId:reason:completion:","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupService~1declineJoinApplication(groupId:userId:reason:completion:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupService~1declineJoinApplication(groupId:userId:reason:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"declineJoinApplicationWithGroupId:userId:reason:completion:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupService\/title","value":"GroupService","op":"replace"},{"value":[{"kind":"identifier","text":"GroupService"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupService\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupService\/navigatorTitle","value":[{"kind":"identifier","text":"GroupService"}],"op":"replace"}]}]}