{"sections":[],"variants":[{"paths":["\/documentation\/shengwangchatuikit\/groupservice\/removeadmin(userid:from:completion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/groupservice\/removeadmin(userid:from:completion:)"]}],"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupService\/removeAdmin(userId:from:completion:)","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Instance Method","title":"removeAdmin(userId:from:completion:)","modules":[{"name":"ShengwangChatUIKit"}],"symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"removeAdminWithUserId:from:completion:"}],"required":true,"role":"symbol","externalID":"c:@M@ShengwangChatUIKit@objc(pl)GroupService(im)removeAdminWithUserId:from:completion:","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"removeAdmin","kind":"identifier"},{"kind":"text","text":"("},{"text":"userId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"from"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit0B5Groupa","text":"ChatGroup"},{"kind":"text","text":"?, "},{"text":"ChatError","kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit0B5Errora"},{"text":"?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"removeAdmin","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"userId"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"from","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"groupId","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"text":": ","kind":"text"},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" ("},{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatGroup","kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit0B5Groupa","text":"ChatGroup"},{"text":"?, ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatError","kind":"typeIdentifier","text":"ChatError","preciseIdentifier":"s:18ShengwangChatUIKit0B5Errora"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"userId","content":[{"inlineContent":[{"text":"ID of the user.","type":"text"}],"type":"paragraph"}]},{"name":"groupId","content":[{"inlineContent":[{"type":"text","text":"ID of the group."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"The request callback contains the group object and error information. If successful, a non-empty group object will be returned. If failed, a non-empty group object will be returned."}],"type":"paragraph"}],"name":"completion"}]}],"abstract":[{"type":"text","text":"Remove an admin from the group."}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupService"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/GroupService":{"navigatorTitle":[{"text":"GroupService","kind":"identifier"}],"type":"topic","title":"GroupService","role":"symbol","url":"\/documentation\/shengwangchatuikit\/groupservice","kind":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupService","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GroupService","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatGroup":{"type":"topic","role":"symbol","title":"ChatGroup","kind":"symbol","abstract":[],"navigatorTitle":[{"text":"ChatGroup","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/chatgroup","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatGroup","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"text":"ChatGroup","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatError":{"fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChatError"}],"role":"symbol","navigatorTitle":[{"text":"ChatError","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatError","url":"\/documentation\/shengwangchatuikit\/chaterror","title":"ChatError","kind":"symbol","abstract":[]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/GroupService/removeAdmin(userId:from:completion:)":{"url":"\/documentation\/shengwangchatuikit\/groupservice\/removeadmin(userid:from:completion:)","abstract":[{"type":"text","text":"Remove an admin from the group."}],"kind":"symbol","navigatorTitle":[{"text":"removeAdminWithUserId:from:completion:","kind":"identifier"}],"type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupService\/removeAdmin(userId:from:completion:)","required":true,"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"removeAdmin","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"userId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"text":"ChatGroup","kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit0B5Groupa"},{"text":"?, ","kind":"text"},{"text":"ChatError","kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit0B5Errora"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"kind":"text","text":")"}],"title":"removeAdmin(userId:from:completion:)"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"value":"removeAdminWithUserId:from:completion:","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"removeAdminWithUserId:from:completion:"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"removeAdminWithUserId:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"userId","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"from:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"groupId","kind":"internalParam"},{"kind":"text","text":" "},{"text":"completion:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"text":" (^","kind":"text"},{"text":")(","kind":"text"},{"kind":"typeIdentifier","text":"AgoraChatGroup","preciseIdentifier":"c:objc(cs)AgoraChatGroup"},{"text":" * ","kind":"text"},{"kind":"internalParam","text":""},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"AgoraChatError","preciseIdentifier":"c:objc(cs)AgoraChatError"},{"text":" * ","kind":"text"},{"text":"","kind":"internalParam"},{"kind":"text","text":")) "},{"kind":"internalParam","text":"completion"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/primaryContentSections\/1","op":"replace","value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"ID of the user.","type":"text"}]}],"name":"userId"},{"name":"groupId","content":[{"type":"paragraph","inlineContent":[{"text":"ID of the group.","type":"text"}]}]},{"name":"completion","content":[{"inlineContent":[{"type":"text","text":"The request callback contains the group object and error information. If successful, a non-empty group object will be returned. If failed, a non-empty group object will be returned."}],"type":"paragraph"}]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupService\/title","value":"GroupService","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupService\/fragments","value":[{"text":"GroupService","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupService\/navigatorTitle","value":[{"kind":"identifier","text":"GroupService"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupService~1removeAdmin(userId:from:completion:)\/title","op":"replace","value":"removeAdminWithUserId:from:completion:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupService~1removeAdmin(userId:from:completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"removeAdminWithUserId:from:completion:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}