{"abstract":[{"text":"Unbind group chat thread event listener","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"unbindGroupChatThreadEventListener"},{"kind":"text","text":"("},{"text":"listener","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupChatThreadEventListener","text":"GroupChatThreadEventListener","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(pl)GroupChatThreadEventListener"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"parameters":[{"name":"listener","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupChatThreadEventListener"}]}]}],"kind":"parameters"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/groupservice\/unbindgroupchatthreadeventlistener(listener:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/groupservice\/unbindgroupchatthreadeventlistener(listener:)"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupService"]]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupService\/unbindGroupChatThreadEventListener(listener:)"},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"metadata":{"roleHeading":"Instance Method","role":"symbol","navigatorTitle":[{"text":"unbindGroupChatThreadEventListenerWithListener:","kind":"identifier"}],"externalID":"c:@M@ShengwangChatUIKit@objc(pl)GroupService(im)unbindGroupChatThreadEventListenerWithListener:","symbolKind":"method","required":true,"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"unbindGroupChatThreadEventListener","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"listener"},{"text":": ","kind":"text"},{"text":"GroupChatThreadEventListener","kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(pl)GroupChatThreadEventListener"},{"text":")","kind":"text"}],"title":"unbindGroupChatThreadEventListener(listener:)","modules":[{"name":"ShengwangChatUIKit"}]},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/GroupService/unbindGroupChatThreadEventListener(listener:)":{"url":"\/documentation\/shengwangchatuikit\/groupservice\/unbindgroupchatthreadeventlistener(listener:)","abstract":[{"text":"Unbind group chat thread event listener","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"unbindGroupChatThreadEventListenerWithListener:","kind":"identifier"}],"type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupService\/unbindGroupChatThreadEventListener(listener:)","required":true,"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"unbindGroupChatThreadEventListener"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"listener"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(pl)GroupChatThreadEventListener","text":"GroupChatThreadEventListener"},{"kind":"text","text":")"}],"title":"unbindGroupChatThreadEventListener(listener:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/GroupChatThreadEventListener":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupChatThreadEventListener","kind":"symbol","title":"GroupChatThreadEventListener","role":"symbol","url":"\/documentation\/shengwangchatuikit\/groupchatthreadeventlistener","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"GroupChatThreadEventListener"}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"GroupChatThreadEventListener","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/GroupService":{"navigatorTitle":[{"text":"GroupService","kind":"identifier"}],"type":"topic","title":"GroupService","role":"symbol","url":"\/documentation\/shengwangchatuikit\/groupservice","kind":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupService","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GroupService","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"unbindGroupChatThreadEventListenerWithListener:","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"unbindGroupChatThreadEventListenerWithListener:"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"unbindGroupChatThreadEventListenerWithListener:"},{"kind":"text","text":"("},{"text":"id<GroupChatThreadEventListener>","kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@ShengwangChatUIKit@objc(pl)GroupChatThreadEventListener"},{"kind":"text","text":") "},{"text":"listener","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"listener","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupChatThreadEventListener"}]}]}]},"op":"replace"},{"value":"unbindGroupChatThreadEventListenerWithListener:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupService~1unbindGroupChatThreadEventListener(listener:)\/title"},{"value":[{"kind":"text","text":"- "},{"text":"unbindGroupChatThreadEventListenerWithListener:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupService~1unbindGroupChatThreadEventListener(listener:)\/fragments","op":"replace"},{"value":"GroupChatThreadEventListener","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupChatThreadEventListener\/title"},{"value":[{"kind":"identifier","text":"GroupChatThreadEventListener"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupChatThreadEventListener\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupChatThreadEventListener\/navigatorTitle","value":[{"kind":"identifier","text":"GroupChatThreadEventListener"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupService\/title","value":"GroupService"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupService\/fragments","value":[{"text":"GroupService","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupService\/navigatorTitle","op":"replace","value":[{"text":"GroupService","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}