{"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupService\/unmute(userIds:groupId:completion:)","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"unmute","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"userIds"},{"kind":"text","text":": ["},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"], "},{"text":"groupId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"attribute"},{"text":" (","kind":"text"},{"kind":"typeIdentifier","text":"ChatGroup","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatGroup","preciseIdentifier":"s:18ShengwangChatUIKit0B5Groupa"},{"kind":"text","text":"?, "},{"text":"ChatError","kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit0B5Errora","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatError"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"ID of the user."}],"type":"paragraph"}],"name":"userIds"},{"name":"groupId","content":[{"inlineContent":[{"text":"ID of the group.","type":"text"}],"type":"paragraph"}]},{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"text":"The request callback contains the group object and error information. If successful, a non-empty group object will be returned. If failed, a non-empty group object will be returned.","type":"text"}]}]}]}],"sections":[],"metadata":{"symbolKind":"method","roleHeading":"Instance Method","title":"unmute(userIds:groupId:completion:)","navigatorTitle":[{"text":"unmuteWithUserIds:groupId:completion:","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"unmute","kind":"identifier"},{"text":"(","kind":"text"},{"text":"userIds","kind":"externalParam"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"], "},{"text":"groupId","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit0B5Groupa","text":"ChatGroup"},{"kind":"text","text":"?, "},{"preciseIdentifier":"s:18ShengwangChatUIKit0B5Errora","text":"ChatError","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")","kind":"text"}],"externalID":"c:@M@ShengwangChatUIKit@objc(pl)GroupService(im)unmuteWithUserIds:groupId:completion:","modules":[{"name":"ShengwangChatUIKit"}],"required":true},"kind":"symbol","abstract":[{"text":"Unmute a user.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupService"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/groupservice\/unmute(userids:groupid:completion:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/groupservice\/unmute(userids:groupid:completion:)"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/GroupService/unmute(userIds:groupId:completion:)":{"url":"\/documentation\/shengwangchatuikit\/groupservice\/unmute(userids:groupid:completion:)","abstract":[{"text":"Unmute a user.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"unmuteWithUserIds:groupId:completion:","kind":"identifier"}],"type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupService\/unmute(userIds:groupId:completion:)","required":true,"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"unmute","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"userIds"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"], "},{"text":"groupId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"text":"ChatGroup","kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit0B5Groupa"},{"text":"?, ","kind":"text"},{"preciseIdentifier":"s:18ShengwangChatUIKit0B5Errora","kind":"typeIdentifier","text":"ChatError"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"title":"unmute(userIds:groupId:completion:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/GroupService":{"navigatorTitle":[{"text":"GroupService","kind":"identifier"}],"type":"topic","title":"GroupService","role":"symbol","url":"\/documentation\/shengwangchatuikit\/groupservice","kind":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupService","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GroupService","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatGroup":{"type":"topic","role":"symbol","title":"ChatGroup","kind":"symbol","abstract":[],"navigatorTitle":[{"text":"ChatGroup","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/chatgroup","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatGroup","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"text":"ChatGroup","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatError":{"fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChatError"}],"role":"symbol","navigatorTitle":[{"text":"ChatError","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatError","url":"\/documentation\/shengwangchatuikit\/chaterror","title":"ChatError","kind":"symbol","abstract":[]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"unmuteWithUserIds:groupId:completion:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"unmuteWithUserIds:groupId:completion:"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"unmuteWithUserIds:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<NSString *>","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"userIds"},{"kind":"text","text":" "},{"kind":"identifier","text":"groupId:"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"groupId"},{"kind":"text","text":" "},{"kind":"identifier","text":"completion:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":" (^"},{"text":")(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AgoraChatGroup","text":"AgoraChatGroup"},{"text":" * ","kind":"text"},{"text":"","kind":"internalParam"},{"text":", ","kind":"text"},{"kind":"typeIdentifier","text":"AgoraChatError","preciseIdentifier":"c:objc(cs)AgoraChatError"},{"kind":"text","text":" * "},{"text":"","kind":"internalParam"},{"text":")) ","kind":"text"},{"text":"completion","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"value":{"kind":"parameters","parameters":[{"name":"userIds","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"ID of the user."}]}]},{"content":[{"inlineContent":[{"text":"ID of the group.","type":"text"}],"type":"paragraph"}],"name":"groupId"},{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The request callback contains the group object and error information. If successful, a non-empty group object will be returned. If failed, a non-empty group object will be returned."}]}]}]},"op":"replace","path":"\/primaryContentSections\/1"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupService~1unmute(userIds:groupId:completion:)\/title","op":"replace","value":"unmuteWithUserIds:groupId:completion:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"unmuteWithUserIds:groupId:completion:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupService~1unmute(userIds:groupId:completion:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupService\/title","value":"GroupService"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupService\/fragments","value":[{"text":"GroupService","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupService\/navigatorTitle","value":[{"text":"GroupService","kind":"identifier"}]}]}]}