{"metadata":{"role":"symbol","title":"createPreviewContent()","roleHeading":"Instance Method","navigatorTitle":[{"text":"createPreviewContent","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"createPreviewContent","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"URLPreviewResultView","kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)URLPreviewResultView"}],"externalID":"c:@M@ShengwangChatUIKit@objc(cs)TextMessageCell(im)createPreviewContent","symbolKind":"method","modules":[{"name":"ShengwangChatUIKit"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"@","kind":"attribute"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"createPreviewContent","kind":"identifier"},{"kind":"text","text":"() -> "},{"text":"URLPreviewResultView","kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)URLPreviewResultView","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/URLPreviewResultView"}]}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/TextMessageCell\/createPreviewContent()","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/TextMessageCell"]]},"variants":[{"paths":["\/documentation\/shengwangchatuikit\/textmessagecell\/createpreviewcontent()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/shengwangchatuikit\/textmessagecell\/createpreviewcontent()"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/TextMessageCell":{"navigatorTitle":[{"text":"TextMessageCell","kind":"identifier"}],"abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"TextMessageCell","kind":"identifier"}],"type":"topic","url":"\/documentation\/shengwangchatuikit\/textmessagecell","kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/TextMessageCell","title":"TextMessageCell"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/TextMessageCell/createPreviewContent()":{"title":"createPreviewContent()","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"createPreviewContent"}],"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"createPreviewContent","kind":"identifier"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)URLPreviewResultView","text":"URLPreviewResultView"}],"kind":"symbol","abstract":[],"url":"\/documentation\/shengwangchatuikit\/textmessagecell\/createpreviewcontent()","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/TextMessageCell\/createPreviewContent()"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/URLPreviewResultView":{"abstract":[],"url":"\/documentation\/shengwangchatuikit\/urlpreviewresultview","title":"URLPreviewResultView","navigatorTitle":[{"kind":"identifier","text":"URLPreviewResultView"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"URLPreviewResultView"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/URLPreviewResultView","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"createPreviewContent"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"text":"createPreviewContent","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"URLPreviewResultView","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)URLPreviewResultView","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/URLPreviewResultView","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"createPreviewContent","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"value":"TextMessageCell","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1TextMessageCell\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1TextMessageCell\/fragments","value":[{"kind":"identifier","text":"TextMessageCell"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1TextMessageCell\/navigatorTitle","value":[{"text":"TextMessageCell","kind":"identifier"}]},{"value":"createPreviewContent","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1TextMessageCell~1createPreviewContent()\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1TextMessageCell~1createPreviewContent()\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"createPreviewContent"}]},{"op":"replace","value":"URLPreviewResultView","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1URLPreviewResultView\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1URLPreviewResultView\/fragments","value":[{"kind":"identifier","text":"URLPreviewResultView"}],"op":"replace"},{"value":[{"text":"URLPreviewResultView","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1URLPreviewResultView\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}