{"variants":[{"paths":["\/documentation\/shengwangchatuikit\/textmessagecell\/onthemechanged()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/shengwangchatuikit\/textmessagecell\/onthemechanged()"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/TextMessageCell"]]},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"onThemeChanged"},{"kind":"text","text":"()"}]}],"kind":"declarations"}],"metadata":{"role":"symbol","symbolKind":"method","title":"onThemeChanged()","externalID":"c:@M@ShengwangChatUIKit@objc(cs)TextMessageCell(im)onThemeChanged","roleHeading":"Instance Method","navigatorTitle":[{"text":"onThemeChanged","kind":"identifier"}],"modules":[{"name":"ShengwangChatUIKit"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onThemeChanged","kind":"identifier"},{"kind":"text","text":"()"}]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/TextMessageCell\/onThemeChanged()"},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/TextMessageCell":{"navigatorTitle":[{"text":"TextMessageCell","kind":"identifier"}],"abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"TextMessageCell","kind":"identifier"}],"type":"topic","url":"\/documentation\/shengwangchatuikit\/textmessagecell","kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/TextMessageCell","title":"TextMessageCell"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/TextMessageCell/onThemeChanged()":{"type":"topic","role":"symbol","title":"onThemeChanged()","kind":"symbol","abstract":[],"navigatorTitle":[{"text":"onThemeChanged","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/textmessagecell\/onthemechanged()","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/TextMessageCell\/onThemeChanged()","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"onThemeChanged","kind":"identifier"},{"text":"()","kind":"text"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","value":"onThemeChanged","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"onThemeChanged","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"onThemeChanged","kind":"identifier"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1TextMessageCell\/title","value":"TextMessageCell","op":"replace"},{"value":[{"kind":"identifier","text":"TextMessageCell"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1TextMessageCell\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1TextMessageCell\/navigatorTitle","value":[{"kind":"identifier","text":"TextMessageCell"}]},{"value":"onThemeChanged","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1TextMessageCell~1onThemeChanged()\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1TextMessageCell~1onThemeChanged()\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"onThemeChanged"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}