{"sections":[],"metadata":{"externalID":"c:@CM@ShengwangChatUIKit@objc(cs)ForwardTargetViewController(im)tableView:willDisplayCell:forRowAtIndexPath:","role":"symbol","title":"tableView(_:willDisplay:forRowAt:)","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"tableView"},{"text":"(","kind":"text"},{"text":"UITableView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITableView"},{"text":", ","kind":"text"},{"text":"willDisplay","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UITableViewCell","preciseIdentifier":"c:objc(cs)UITableViewCell","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"forRowAt","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation9IndexPathV","text":"IndexPath","kind":"typeIdentifier"},{"kind":"text","text":")"}],"modules":[{"name":"ShengwangChatUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"tableView:willDisplayCell:forRowAtIndexPath:"}],"extendedModule":"ShengwangChatUIKit","roleHeading":"Instance Method"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ForwardTargetViewController","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ForwardTargetViewController\/UITableViewDelegate-Implementations"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ForwardTargetViewController\/tableView(_:willDisplay:forRowAt:)"},"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"UITableViewDelegate.tableView(_:willDisplay:forRowAt:)"},{"type":"text","text":"."}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"tableView"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"tableView","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UITableView","kind":"typeIdentifier","text":"UITableView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"willDisplay"},{"kind":"text","text":" "},{"kind":"internalParam","text":"cell"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UITableViewCell","text":"UITableViewCell","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"forRowAt","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"indexPath","kind":"internalParam"},{"kind":"text","text":": "},{"text":"IndexPath","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/forwardtargetviewcontroller\/tableview(_:willdisplay:forrowat:)"]},{"paths":["\/documentation\/shengwangchatuikit\/forwardtargetviewcontroller\/tableview(_:willdisplay:forrowat:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ForwardTargetViewController":{"navigatorTitle":[{"text":"ForwardTargetViewController","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/forwardtargetviewcontroller","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ForwardTargetViewController","kind":"identifier"}],"role":"symbol","title":"ForwardTargetViewController","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ForwardTargetViewController","kind":"symbol","abstract":[]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ForwardTargetViewController/tableView(_:willDisplay:forRowAt:)":{"type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"tableView:willDisplayCell:forRowAtIndexPath:"}],"kind":"symbol","title":"tableView(_:willDisplay:forRowAt:)","url":"\/documentation\/shengwangchatuikit\/forwardtargetviewcontroller\/tableview(_:willdisplay:forrowat:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"tableView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UITableView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITableView"},{"text":", ","kind":"text"},{"text":"willDisplay","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITableViewCell","text":"UITableViewCell"},{"kind":"text","text":", "},{"text":"forRowAt","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation9IndexPathV","text":"IndexPath","kind":"typeIdentifier"},{"kind":"text","text":")"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ForwardTargetViewController\/tableView(_:willDisplay:forRowAt:)","role":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ForwardTargetViewController/UITableViewDelegate-Implementations":{"url":"\/documentation\/shengwangchatuikit\/forwardtargetviewcontroller\/uitableviewdelegate-implementations","title":"UITableViewDelegate Implementations","kind":"article","role":"collectionGroup","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ForwardTargetViewController\/UITableViewDelegate-Implementations","abstract":[],"type":"topic"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"tableView:willDisplayCell:forRowAtIndexPath:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"tableView:willDisplayCell:forRowAtIndexPath:"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"kind":"identifier","text":"tableView:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"UITableView","preciseIdentifier":"c:objc(cs)UITableView"},{"text":" *) ","kind":"text"},{"text":"tableView","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"willDisplayCell:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UITableViewCell","kind":"typeIdentifier","text":"UITableViewCell"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"cell"},{"kind":"text","text":" "},{"text":"forRowAtIndexPath:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSIndexPath","preciseIdentifier":"c:objc(cs)NSIndexPath","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"indexPath"},{"kind":"text","text":";"}]}]}},{"op":"replace","value":"ForwardTargetViewController","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ForwardTargetViewController\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ForwardTargetViewController\/fragments","value":[{"text":"ForwardTargetViewController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ForwardTargetViewController\/navigatorTitle","value":[{"text":"ForwardTargetViewController","kind":"identifier"}]},{"op":"replace","value":"tableView:willDisplayCell:forRowAtIndexPath:","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ForwardTargetViewController~1tableView(_:willDisplay:forRowAt:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ForwardTargetViewController~1tableView(_:willDisplay:forRowAt:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"tableView:willDisplayCell:forRowAtIndexPath:","kind":"identifier"}]}]}]}