{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ForwardTargetViewController"]]},"topicSections":[{"anchor":"Instance-Methods","generated":true,"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ForwardTargetViewController\/searchBarCancelButtonClicked(_:)"]}],"variants":[{"paths":["\/documentation\/shengwangchatuikit\/forwardtargetviewcontroller\/uisearchbardelegate-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/shengwangchatuikit\/forwardtargetviewcontroller\/uisearchbardelegate-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ForwardTargetViewController\/UISearchBarDelegate-Implementations","interfaceLanguage":"swift"},"metadata":{"roleHeading":"API Collection","title":"UISearchBarDelegate Implementations","modules":[{"name":"ShengwangChatUIKit"}],"role":"collectionGroup"},"sections":[],"kind":"article","schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ForwardTargetViewController/searchBarCancelButtonClicked(_:)":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ForwardTargetViewController\/searchBarCancelButtonClicked(_:)","navigatorTitle":[{"kind":"identifier","text":"searchBarCancelButtonClicked:"}],"url":"\/documentation\/shengwangchatuikit\/forwardtargetviewcontroller\/searchbarcancelbuttonclicked(_:)","type":"topic","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"searchBarCancelButtonClicked","kind":"identifier"},{"kind":"text","text":"("},{"text":"UISearchBar","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UISearchBar"},{"text":")","kind":"text"}],"title":"searchBarCancelButtonClicked(_:)","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ForwardTargetViewController":{"navigatorTitle":[{"text":"ForwardTargetViewController","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/forwardtargetviewcontroller","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ForwardTargetViewController","kind":"identifier"}],"role":"symbol","title":"ForwardTargetViewController","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ForwardTargetViewController","kind":"symbol","abstract":[]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/topicSections","value":[{"title":"Instance Methods","anchor":"Instance-Methods","generated":true,"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ForwardTargetViewController\/searchBarCancelButtonClicked(_:)"]}],"op":"replace"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ForwardTargetViewController~1searchBarCancelButtonClicked(_:)\/title","value":"searchBarCancelButtonClicked:"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"searchBarCancelButtonClicked:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ForwardTargetViewController~1searchBarCancelButtonClicked(_:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ForwardTargetViewController\/title","value":"ForwardTargetViewController"},{"op":"replace","value":[{"kind":"identifier","text":"ForwardTargetViewController"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ForwardTargetViewController\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ForwardTargetViewController\/navigatorTitle","value":[{"kind":"identifier","text":"ForwardTargetViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}