{"sections":[],"abstract":[{"text":"Inherited from ","type":"text"},{"code":"UISearchControllerDelegate.willDismissSearchController(_:)","type":"codeVoice"},{"text":".","type":"text"}],"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ForwardTargetViewController\/willDismissSearchController(_:)","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"externalID":"c:@CM@ShengwangChatUIKit@objc(cs)ForwardTargetViewController(im)willDismissSearchController:","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"willDismissSearchController"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UISearchController","text":"UISearchController"},{"text":")","kind":"text"}],"symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"willDismissSearchController:"}],"title":"willDismissSearchController(_:)","extendedModule":"ShengwangChatUIKit","role":"symbol","modules":[{"name":"ShengwangChatUIKit"}],"roleHeading":"Instance Method"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ForwardTargetViewController","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ForwardTargetViewController\/UISearchControllerDelegate-Implementations"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"willDismissSearchController"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"searchController","kind":"internalParam"},{"kind":"text","text":": "},{"text":"UISearchController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UISearchController"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/shengwangchatuikit\/forwardtargetviewcontroller\/willdismisssearchcontroller(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/forwardtargetviewcontroller\/willdismisssearchcontroller(_:)"]}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ForwardTargetViewController/willDismissSearchController(_:)":{"kind":"symbol","type":"topic","url":"\/documentation\/shengwangchatuikit\/forwardtargetviewcontroller\/willdismisssearchcontroller(_:)","role":"symbol","abstract":[],"navigatorTitle":[{"text":"willDismissSearchController:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"willDismissSearchController"},{"kind":"text","text":"("},{"text":"UISearchController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UISearchController"},{"text":")","kind":"text"}],"title":"willDismissSearchController(_:)","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ForwardTargetViewController\/willDismissSearchController(_:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ForwardTargetViewController":{"navigatorTitle":[{"text":"ForwardTargetViewController","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/forwardtargetviewcontroller","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ForwardTargetViewController","kind":"identifier"}],"role":"symbol","title":"ForwardTargetViewController","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ForwardTargetViewController","kind":"symbol","abstract":[]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ForwardTargetViewController/UISearchControllerDelegate-Implementations":{"abstract":[],"title":"UISearchControllerDelegate Implementations","type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ForwardTargetViewController\/UISearchControllerDelegate-Implementations","url":"\/documentation\/shengwangchatuikit\/forwardtargetviewcontroller\/uisearchcontrollerdelegate-implementations","role":"collectionGroup","kind":"article"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"willDismissSearchController:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"willDismissSearchController:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"willDismissSearchController:"},{"kind":"text","text":"("},{"text":"UISearchController","preciseIdentifier":"c:objc(cs)UISearchController","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"searchController"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ForwardTargetViewController~1willDismissSearchController(_:)\/title","value":"willDismissSearchController:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ForwardTargetViewController~1willDismissSearchController(_:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"willDismissSearchController:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ForwardTargetViewController\/title","value":"ForwardTargetViewController"},{"op":"replace","value":[{"text":"ForwardTargetViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ForwardTargetViewController\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ForwardTargetViewController\/navigatorTitle","value":[{"kind":"identifier","text":"ForwardTargetViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}