{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupChatThreadEventType\/destroyed"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"destroyed","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupChatThreadEventType"]]},"sections":[],"metadata":{"role":"symbol","externalID":"c:@M@ShengwangChatUIKit@E@GroupChatThreadEventType@GroupChatThreadEventTypeDestroyed","roleHeading":"Case","title":"GroupChatThreadEventType.destroyed","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"destroyed","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"GroupChatThreadEventTypeDestroyed"}],"modules":[{"name":"ShengwangChatUIKit"}],"symbolKind":"case"},"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/groupchatthreadeventtype\/destroyed"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/groupchatthreadeventtype\/destroyed"]}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/GroupChatThreadEventType/destroyed":{"navigatorTitle":[{"text":"GroupChatThreadEventTypeDestroyed","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/shengwangchatuikit\/groupchatthreadeventtype\/destroyed","abstract":[],"type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"destroyed"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupChatThreadEventType\/destroyed","role":"symbol","title":"GroupChatThreadEventType.destroyed"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/GroupChatThreadEventType":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupChatThreadEventType","title":"GroupChatThreadEventType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"GroupChatThreadEventType","kind":"identifier"}],"type":"topic","abstract":[],"url":"\/documentation\/shengwangchatuikit\/groupchatthreadeventtype","navigatorTitle":[{"text":"GroupChatThreadEventType","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"GroupChatThreadEventTypeDestroyed"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"GroupChatThreadEventTypeDestroyed","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"GroupChatThreadEventTypeDestroyed","kind":"identifier"}],"platforms":["iOS"]}]},"op":"replace"},{"value":"GroupChatThreadEventTypeDestroyed","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupChatThreadEventType~1destroyed\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupChatThreadEventType~1destroyed\/fragments","value":[{"text":"GroupChatThreadEventTypeDestroyed","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupChatThreadEventType\/title","value":"GroupChatThreadEventType"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupChatThreadEventType\/fragments","value":[{"text":"GroupChatThreadEventType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupChatThreadEventType\/navigatorTitle","value":[{"kind":"identifier","text":"GroupChatThreadEventType"}]}]}]}