{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupChatThreadEventType"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupChatThreadEventType\/updated","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"updated"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"modules":[{"name":"ShengwangChatUIKit"}],"navigatorTitle":[{"text":"GroupChatThreadEventTypeUpdated","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"updated"}],"externalID":"c:@M@ShengwangChatUIKit@E@GroupChatThreadEventType@GroupChatThreadEventTypeUpdated","roleHeading":"Case","title":"GroupChatThreadEventType.updated","symbolKind":"case","role":"symbol"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/groupchatthreadeventtype\/updated"]},{"paths":["\/documentation\/shengwangchatuikit\/groupchatthreadeventtype\/updated"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/GroupChatThreadEventType":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupChatThreadEventType","title":"GroupChatThreadEventType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"GroupChatThreadEventType","kind":"identifier"}],"type":"topic","abstract":[],"url":"\/documentation\/shengwangchatuikit\/groupchatthreadeventtype","navigatorTitle":[{"text":"GroupChatThreadEventType","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/GroupChatThreadEventType/updated":{"abstract":[],"url":"\/documentation\/shengwangchatuikit\/groupchatthreadeventtype\/updated","title":"GroupChatThreadEventType.updated","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"GroupChatThreadEventTypeUpdated"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupChatThreadEventType\/updated","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"updated"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"GroupChatThreadEventTypeUpdated","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"value":[{"text":"GroupChatThreadEventTypeUpdated","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"GroupChatThreadEventTypeUpdated","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"value":"GroupChatThreadEventType","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupChatThreadEventType\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupChatThreadEventType\/fragments","value":[{"kind":"identifier","text":"GroupChatThreadEventType"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupChatThreadEventType\/navigatorTitle","value":[{"kind":"identifier","text":"GroupChatThreadEventType"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupChatThreadEventType~1updated\/title","op":"replace","value":"GroupChatThreadEventTypeUpdated"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupChatThreadEventType~1updated\/fragments","op":"replace","value":[{"kind":"identifier","text":"GroupChatThreadEventTypeUpdated"}]}]}]}