{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/userserviceprotocol\/binduserstatechangedlistener(listener:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/userserviceprotocol\/binduserstatechangedlistener(listener:)"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UserServiceProtocol"]]},"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"text":"Bind user state changed listener","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bindUserStateChangedListener"},{"text":"(","kind":"text"},{"text":"listener","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(pl)UserStateChangedListener","text":"UserStateChangedListener","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UserStateChangedListener"},{"text":")","kind":"text"}]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"UserStateChangedListener"}]}],"name":"listener"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UserServiceProtocol\/bindUserStateChangedListener(listener:)"},"metadata":{"symbolKind":"method","roleHeading":"Instance Method","title":"bindUserStateChangedListener(listener:)","navigatorTitle":[{"text":"bindUserStateChangedListenerWithListener:","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bindUserStateChangedListener"},{"text":"(","kind":"text"},{"text":"listener","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UserStateChangedListener","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(pl)UserStateChangedListener","kind":"typeIdentifier"},{"text":")","kind":"text"}],"externalID":"c:@M@ShengwangChatUIKit@objc(pl)UserServiceProtocol(im)bindUserStateChangedListenerWithListener:","modules":[{"name":"ShengwangChatUIKit"}],"required":true},"sections":[],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/UserServiceProtocol":{"abstract":[],"url":"\/documentation\/shengwangchatuikit\/userserviceprotocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"UserServiceProtocol"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UserServiceProtocol","role":"symbol","navigatorTitle":[{"text":"UserServiceProtocol","kind":"identifier"}],"title":"UserServiceProtocol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/UserStateChangedListener":{"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"UserStateChangedListener","kind":"identifier"}],"navigatorTitle":[{"text":"UserStateChangedListener","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/userstatechangedlistener","type":"topic","abstract":[],"title":"UserStateChangedListener","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UserStateChangedListener","role":"symbol","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/UserServiceProtocol/bindUserStateChangedListener(listener:)":{"role":"symbol","navigatorTitle":[{"text":"bindUserStateChangedListenerWithListener:","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/shengwangchatuikit\/userserviceprotocol\/binduserstatechangedlistener(listener:)","title":"bindUserStateChangedListener(listener:)","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UserServiceProtocol\/bindUserStateChangedListener(listener:)","required":true,"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"bindUserStateChangedListener","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"listener"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(pl)UserStateChangedListener","text":"UserStateChangedListener"},{"text":")","kind":"text"}],"type":"topic","abstract":[{"type":"text","text":"Bind user state changed listener"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"bindUserStateChangedListenerWithListener:","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"bindUserStateChangedListenerWithListener:","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"bindUserStateChangedListenerWithListener:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id<UserStateChangedListener>","kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@ShengwangChatUIKit@objc(pl)UserStateChangedListener"},{"kind":"text","text":") "},{"text":"listener","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"parameters":[{"content":[{"inlineContent":[{"text":"UserStateChangedListener","type":"text"}],"type":"paragraph"}],"name":"listener"}],"kind":"parameters"},"path":"\/primaryContentSections\/1","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1UserServiceProtocol\/title","op":"replace","value":"UserServiceProtocol"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1UserServiceProtocol\/fragments","value":[{"kind":"identifier","text":"UserServiceProtocol"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1UserServiceProtocol\/navigatorTitle","value":[{"kind":"identifier","text":"UserServiceProtocol"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1UserStateChangedListener\/title","value":"UserStateChangedListener"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1UserStateChangedListener\/fragments","value":[{"text":"UserStateChangedListener","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1UserStateChangedListener\/navigatorTitle","value":[{"kind":"identifier","text":"UserStateChangedListener"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1UserServiceProtocol~1bindUserStateChangedListener(listener:)\/title","op":"replace","value":"bindUserStateChangedListenerWithListener:"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1UserServiceProtocol~1bindUserStateChangedListener(listener:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"bindUserStateChangedListenerWithListener:"}]}]}]}