{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactCardCell\/createContent()"},"metadata":{"roleHeading":"Instance Method","title":"createContent()","externalID":"c:@M@ShengwangChatUIKit@objc(cs)ContactCardCell(im)createContent","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"createContent","kind":"identifier"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"symbolKind":"method","modules":[{"name":"ShengwangChatUIKit"}],"navigatorTitle":[{"text":"createContent","kind":"identifier"}],"role":"symbol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"@","kind":"attribute"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"createContent","kind":"identifier"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}]}]}],"variants":[{"paths":["\/documentation\/shengwangchatuikit\/contactcardcell\/createcontent()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/shengwangchatuikit\/contactcardcell\/createcontent()"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactCardCell"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ContactCardCell":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactCardCell","url":"\/documentation\/shengwangchatuikit\/contactcardcell","abstract":[],"title":"ContactCardCell","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ContactCardCell","kind":"identifier"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"ContactCardCell"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ContactCardCell/createContent()":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createContent","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"UIView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"createContent"}],"title":"createContent()","url":"\/documentation\/shengwangchatuikit\/contactcardcell\/createcontent()","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactCardCell\/createContent()","role":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"createContent","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"createContent","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView","text":"UIView"},{"text":" *) ","kind":"text"},{"text":"createContent","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"ContactCardCell","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactCardCell\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactCardCell\/fragments","op":"replace","value":[{"text":"ContactCardCell","kind":"identifier"}]},{"value":[{"text":"ContactCardCell","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactCardCell\/navigatorTitle"},{"op":"replace","value":"createContent","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactCardCell~1createContent()\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactCardCell~1createContent()\/fragments","value":[{"kind":"text","text":"- "},{"text":"createContent","kind":"identifier"}],"op":"replace"}]}]}