{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/DetailInfoHeaderExtensionCell\/icon"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"lazy","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"icon"},{"kind":"text","text":": "},{"text":"UIImageView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImageView"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"text":" }","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/DetailInfoHeaderExtensionCell"]]},"sections":[],"metadata":{"externalID":"s:18ShengwangChatUIKit29DetailInfoHeaderExtensionCellC4iconSo11UIImageViewCvp","role":"symbol","roleHeading":"Instance Property","title":"icon","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"icon"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIImageView","text":"UIImageView","kind":"typeIdentifier"}],"modules":[{"name":"ShengwangChatUIKit"}],"symbolKind":"property"},"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"paths":["\/documentation\/shengwangchatuikit\/detailinfoheaderextensioncell\/icon"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/DetailInfoHeaderExtensionCell/icon":{"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"icon","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImageView","text":"UIImageView"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/DetailInfoHeaderExtensionCell\/icon","type":"topic","abstract":[],"role":"symbol","title":"icon","url":"\/documentation\/shengwangchatuikit\/detailinfoheaderextensioncell\/icon"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/DetailInfoHeaderExtensionCell":{"abstract":[],"title":"DetailInfoHeaderExtensionCell","type":"topic","role":"symbol","url":"\/documentation\/shengwangchatuikit\/detailinfoheaderextensioncell","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DetailInfoHeaderExtensionCell"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/DetailInfoHeaderExtensionCell","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DetailInfoHeaderExtensionCell","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DetailInfoHeaderExtensionCell","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1DetailInfoHeaderExtensionCell\/title"},{"value":[{"kind":"identifier","text":"DetailInfoHeaderExtensionCell"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1DetailInfoHeaderExtensionCell\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1DetailInfoHeaderExtensionCell\/navigatorTitle","value":[{"text":"DetailInfoHeaderExtensionCell","kind":"identifier"}],"op":"replace"}]}]}