{"variants":[{"paths":["\/documentation\/shengwangchatuikit\/detailinfoheaderextensioncell\/themeswitchprotocol-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/shengwangchatuikit\/detailinfoheaderextensioncell\/themeswitchprotocol-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"article","hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/DetailInfoHeaderExtensionCell"]]},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"roleHeading":"API Collection","role":"collectionGroup","modules":[{"name":"ShengwangChatUIKit"}],"title":"ThemeSwitchProtocol Implementations"},"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/DetailInfoHeaderExtensionCell\/ThemeSwitchProtocol-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/DetailInfoHeaderExtensionCell\/switchTheme(style:)"],"generated":true}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/DetailInfoHeaderExtensionCell/switchTheme(style:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"switchTheme"},{"text":"(","kind":"text"},{"text":"style","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ThemeStyle","kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@E@ThemeStyle"},{"kind":"text","text":")"}],"role":"symbol","abstract":[{"text":"When some view Implement the protocol method,you can use ","type":"text"},{"type":"codeVoice","code":"Theme.switchTheme(style: .dark)"},{"text":" to switch theme.","type":"text"}],"type":"topic","url":"\/documentation\/shengwangchatuikit\/detailinfoheaderextensioncell\/switchtheme(style:)","navigatorTitle":[{"kind":"identifier","text":"switchThemeWithStyle:"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/DetailInfoHeaderExtensionCell\/switchTheme(style:)","title":"switchTheme(style:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/DetailInfoHeaderExtensionCell":{"abstract":[],"title":"DetailInfoHeaderExtensionCell","type":"topic","role":"symbol","url":"\/documentation\/shengwangchatuikit\/detailinfoheaderextensioncell","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DetailInfoHeaderExtensionCell"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/DetailInfoHeaderExtensionCell","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DetailInfoHeaderExtensionCell","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/topicSections","value":[{"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/DetailInfoHeaderExtensionCell\/switchTheme(style:)"],"generated":true}],"op":"replace"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":"switchThemeWithStyle:","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1DetailInfoHeaderExtensionCell~1switchTheme(style:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1DetailInfoHeaderExtensionCell~1switchTheme(style:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"switchThemeWithStyle:"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1DetailInfoHeaderExtensionCell\/title","value":"DetailInfoHeaderExtensionCell","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1DetailInfoHeaderExtensionCell\/fragments","value":[{"kind":"identifier","text":"DetailInfoHeaderExtensionCell"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1DetailInfoHeaderExtensionCell\/navigatorTitle","value":[{"text":"DetailInfoHeaderExtensionCell","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}