{"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/shengwangchatuikit\/conversationemergencylistener\/onresult(error:type:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/shengwangchatuikit\/conversationemergencylistener\/onresult(error:type:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationEmergencyListener\/onResult(error:type:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationEmergencyListener"]]},"kind":"symbol","metadata":{"roleHeading":"Instance Method","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"onResult"},{"text":"(","kind":"text"},{"text":"error","kind":"externalParam"},{"kind":"text","text":": "},{"text":"ChatError","kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit0B5Errora"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"type"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@E@ConversationEmergencyType","kind":"typeIdentifier","text":"ConversationEmergencyType"},{"text":")","kind":"text"}],"modules":[{"name":"ShengwangChatUIKit"}],"navigatorTitle":[{"text":"onResultWithError:type:","kind":"identifier"}],"title":"onResult(error:type:)","externalID":"c:@M@ShengwangChatUIKit@objc(pl)ConversationEmergencyListener(im)onResultWithError:type:","required":true,"symbolKind":"method"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"onResult","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"error"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit0B5Errora","text":"ChatError","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatError"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"type"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@E@ConversationEmergencyType","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationEmergencyType","text":"ConversationEmergencyType"},{"kind":"text","text":")"}]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":".Success "},{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatError","isActive":true,"type":"reference"},{"type":"text","text":" is nil."}]}],"name":"error"},{"name":"type","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationEmergencyType"}]}]}],"kind":"parameters"}],"abstract":[{"text":"You’ll receive the result on conversation service request successful or failure.","type":"text"}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ConversationEmergencyListener/onResult(error:type:)":{"type":"topic","kind":"symbol","title":"onResult(error:type:)","required":true,"role":"symbol","abstract":[{"type":"text","text":"You’ll receive the result on conversation service request successful or failure."}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"onResult","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"error"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit0B5Errora","text":"ChatError"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"type"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"ConversationEmergencyType","preciseIdentifier":"c:@M@ShengwangChatUIKit@E@ConversationEmergencyType"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"onResultWithError:type:"}],"url":"\/documentation\/shengwangchatuikit\/conversationemergencylistener\/onresult(error:type:)","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationEmergencyListener\/onResult(error:type:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ConversationEmergencyListener":{"kind":"symbol","url":"\/documentation\/shengwangchatuikit\/conversationemergencylistener","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationEmergencyListener","navigatorTitle":[{"text":"ConversationEmergencyListener","kind":"identifier"}],"type":"topic","abstract":[],"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"ConversationEmergencyListener","kind":"identifier"}],"title":"ConversationEmergencyListener"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatError":{"fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChatError"}],"role":"symbol","navigatorTitle":[{"text":"ChatError","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatError","url":"\/documentation\/shengwangchatuikit\/chaterror","title":"ChatError","kind":"symbol","abstract":[]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ConversationEmergencyType":{"url":"\/documentation\/shengwangchatuikit\/conversationemergencytype","kind":"symbol","title":"ConversationEmergencyType","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"ConversationEmergencyType","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationEmergencyType","abstract":[],"navigatorTitle":[{"text":"ConversationEmergencyType","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"onResultWithError:type:","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"onResultWithError:type:"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"onResultWithError:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraChatError","preciseIdentifier":"c:objc(cs)AgoraChatError"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"error"},{"kind":"text","text":" "},{"text":"type:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@E@ConversationEmergencyType","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationEmergencyType","text":"ConversationEmergencyType"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"type"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/primaryContentSections\/1","op":"replace","value":{"parameters":[{"name":"error","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":".Success "},{"isActive":true,"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatError","type":"reference"},{"type":"text","text":" is nil."}]}]},{"content":[{"inlineContent":[{"text":"","type":"text"},{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationEmergencyType","type":"reference","isActive":true}],"type":"paragraph"}],"name":"type"}],"kind":"parameters"}},{"value":"onResultWithError:type:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationEmergencyListener~1onResult(error:type:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationEmergencyListener~1onResult(error:type:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"onResultWithError:type:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationEmergencyListener\/title","value":"ConversationEmergencyListener"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationEmergencyListener\/fragments","value":[{"text":"ConversationEmergencyListener","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"ConversationEmergencyListener"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationEmergencyListener\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationEmergencyType\/title","value":"ConversationEmergencyType"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationEmergencyType\/fragments","value":[{"kind":"identifier","text":"ConversationEmergencyType"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationEmergencyType\/navigatorTitle","value":[{"text":"ConversationEmergencyType","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}