{"sections":[],"metadata":{"title":"init(custom:constraintsSize:canPanDismiss:)","externalID":"c:@M@ShengwangChatUIKit@objc(cs)DialogContainerViewController(im)initWithCustom:constraintsSize:canPanDismiss:","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"custom","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIView","kind":"typeIdentifier","text":"UIView"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"constraintsSize"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGSize","kind":"typeIdentifier","text":"CGSize"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"canPanDismiss"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"role":"symbol","symbolKind":"init","modules":[{"name":"ShengwangChatUIKit"}],"navigatorTitle":[{"text":"initWithCustom:constraintsSize:canPanDismiss:","kind":"identifier"}],"roleHeading":"Initializer"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/DialogContainerViewController\/init(custom:constraintsSize:canPanDismiss:)"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/DialogContainerViewController"]]},"abstract":[{"text":"Initializes a new ","type":"text"},{"type":"codeVoice","code":"DialogContainerViewController"},{"text":" instance with a custom view and optional constraints size.","type":"text"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"attribute","text":"@"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"text":"custom","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"constraintsSize"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize","text":"CGSize"},{"text":" = .zero, ","kind":"text"},{"text":"canPanDismiss","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":" = true)","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The custom view to be displayed in the dialog container."}]}],"name":"custom"},{"name":"constraintsSize","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The size of the constraints to be applied to the dialog container’s content view. Defaults to "},{"code":".zero","type":"codeVoice"},{"text":".","type":"text"}]}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/dialogcontainerviewcontroller\/init(custom:constraintssize:canpandismiss:)"]},{"paths":["\/documentation\/shengwangchatuikit\/dialogcontainerviewcontroller\/init(custom:constraintssize:canpandismiss:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/DialogContainerViewController":{"kind":"symbol","abstract":[{"type":"text","text":"A view controller that manages the presentation of a dialog container view and its content."}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DialogContainerViewController","kind":"identifier"}],"navigatorTitle":[{"text":"DialogContainerViewController","kind":"identifier"}],"role":"symbol","url":"\/documentation\/shengwangchatuikit\/dialogcontainerviewcontroller","title":"DialogContainerViewController","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/DialogContainerViewController"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/DialogContainerViewController/init(custom:constraintsSize:canPanDismiss:)":{"navigatorTitle":[{"text":"initWithCustom:constraintsSize:canPanDismiss:","kind":"identifier"}],"abstract":[{"text":"Initializes a new ","type":"text"},{"code":"DialogContainerViewController","type":"codeVoice"},{"type":"text","text":" instance with a custom view and optional constraints size."}],"title":"init(custom:constraintsSize:canPanDismiss:)","type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/DialogContainerViewController\/init(custom:constraintsSize:canPanDismiss:)","url":"\/documentation\/shengwangchatuikit\/dialogcontainerviewcontroller\/init(custom:constraintssize:canpandismiss:)","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"custom"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIView","text":"UIView","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"constraintsSize","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"},{"kind":"text","text":", "},{"text":"canPanDismiss","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":")","kind":"text"}],"role":"symbol","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithCustom:constraintsSize:canPanDismiss:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithCustom:constraintsSize:canPanDismiss:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","preciseIdentifier":"c:*Qo","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithCustom:"},{"kind":"text","text":"("},{"text":"UIView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView"},{"text":" *) ","kind":"text"},{"text":"custom","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"constraintsSize:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"},{"kind":"text","text":") "},{"text":"constraintsSize","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"canPanDismiss:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":") "},{"text":"canPanDismiss","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/primaryContentSections\/1","op":"replace","value":{"parameters":[{"name":"custom","content":[{"inlineContent":[{"type":"text","text":"The custom view to be displayed in the dialog container."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The size of the constraints to be applied to the dialog container’s content view. Defaults to "},{"type":"codeVoice","code":".zero"},{"text":".","type":"text"}]}],"name":"constraintsSize"}],"kind":"parameters"}},{"op":"add","path":"\/primaryContentSections\/2","value":{"content":[{"text":"Return Value","anchor":"return-value","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"text":"A new ","type":"text"},{"code":"DialogContainerViewController","type":"codeVoice"},{"text":" instance.","type":"text"}]}],"kind":"content"}},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1DialogContainerViewController\/title","op":"replace","value":"DialogContainerViewController"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1DialogContainerViewController\/fragments","value":[{"text":"DialogContainerViewController","kind":"identifier"}]},{"value":[{"text":"DialogContainerViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1DialogContainerViewController\/navigatorTitle","op":"replace"},{"value":"initWithCustom:constraintsSize:canPanDismiss:","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1DialogContainerViewController~1init(custom:constraintsSize:canPanDismiss:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1DialogContainerViewController~1init(custom:constraintsSize:canPanDismiss:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCustom:constraintsSize:canPanDismiss:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}