{"metadata":{"symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"presentedViewComponent","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:18ShengwangChatUIKit22PresentedViewComponentV","text":"PresentedViewComponent","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"role":"symbol","externalID":"s:18ShengwangChatUIKit29DialogContainerViewControllerC09presentedF9ComponentAA09PresentedfI0VSgvp","title":"presentedViewComponent","roleHeading":"Instance Property","modules":[{"name":"ShengwangChatUIKit"}]},"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/DialogContainerViewController\/presentedViewComponent","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/dialogcontainerviewcontroller\/presentedviewcomponent"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/DialogContainerViewController"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"presentedViewComponent","kind":"identifier"},{"text":": ","kind":"text"},{"text":"PresentedViewComponent","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PresentedViewComponent","preciseIdentifier":"s:18ShengwangChatUIKit22PresentedViewComponentV","kind":"typeIdentifier"},{"kind":"text","text":"?"}]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"PresentedViewType.presentedViewComponent"},{"type":"text","text":"."}],"sections":[],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/DialogContainerViewController/presentedViewComponent":{"url":"\/documentation\/shengwangchatuikit\/dialogcontainerviewcontroller\/presentedviewcomponent","kind":"symbol","type":"topic","abstract":[],"role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/DialogContainerViewController\/presentedViewComponent","title":"presentedViewComponent","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"presentedViewComponent","kind":"identifier"},{"text":": ","kind":"text"},{"text":"PresentedViewComponent","kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit22PresentedViewComponentV"},{"kind":"text","text":"?"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/DialogContainerViewController":{"kind":"symbol","abstract":[{"type":"text","text":"A view controller that manages the presentation of a dialog container view and its content."}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DialogContainerViewController","kind":"identifier"}],"navigatorTitle":[{"text":"DialogContainerViewController","kind":"identifier"}],"role":"symbol","url":"\/documentation\/shengwangchatuikit\/dialogcontainerviewcontroller","title":"DialogContainerViewController","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/DialogContainerViewController"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/PresentedViewComponent":{"url":"\/documentation\/shengwangchatuikit\/presentedviewcomponent","abstract":[{"type":"text","text":"presentedView setting"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"PresentedViewComponent"}],"type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PresentedViewComponent","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"PresentedViewComponent","kind":"identifier"}],"title":"PresentedViewComponent"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1DialogContainerViewController\/title","value":"DialogContainerViewController","op":"replace"},{"value":[{"kind":"identifier","text":"DialogContainerViewController"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1DialogContainerViewController\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1DialogContainerViewController\/navigatorTitle","value":[{"text":"DialogContainerViewController","kind":"identifier"}]}]}]}