{"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationEmergencyType\/delete","interfaceLanguage":"swift"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/conversationemergencytype\/delete"]},{"paths":["\/documentation\/shengwangchatuikit\/conversationemergencytype\/delete"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"delete","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationEmergencyType"]]},"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"delete"}],"symbolKind":"case","modules":[{"name":"ShengwangChatUIKit"}],"title":"ConversationEmergencyType.delete","navigatorTitle":[{"text":"ConversationEmergencyTypeDelete","kind":"identifier"}],"roleHeading":"Case","externalID":"c:@M@ShengwangChatUIKit@E@ConversationEmergencyType@ConversationEmergencyTypeDelete","role":"symbol"},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ConversationEmergencyType":{"url":"\/documentation\/shengwangchatuikit\/conversationemergencytype","kind":"symbol","title":"ConversationEmergencyType","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"ConversationEmergencyType","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationEmergencyType","abstract":[],"navigatorTitle":[{"text":"ConversationEmergencyType","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ConversationEmergencyType/delete":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"delete","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"ConversationEmergencyTypeDelete","kind":"identifier"}],"title":"ConversationEmergencyType.delete","url":"\/documentation\/shengwangchatuikit\/conversationemergencytype\/delete","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationEmergencyType\/delete","role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"ConversationEmergencyTypeDelete"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"ConversationEmergencyTypeDelete"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"ConversationEmergencyTypeDelete","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"ConversationEmergencyType","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationEmergencyType\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationEmergencyType\/fragments","op":"replace","value":[{"text":"ConversationEmergencyType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationEmergencyType\/navigatorTitle","value":[{"text":"ConversationEmergencyType","kind":"identifier"}]},{"value":"ConversationEmergencyTypeDelete","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationEmergencyType~1delete\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationEmergencyType~1delete\/fragments","value":[{"kind":"identifier","text":"ConversationEmergencyTypeDelete"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}