{"sections":[],"kind":"symbol","variants":[{"paths":["\/documentation\/shengwangchatuikit\/conversationemergencytype\/fetchsilent"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/conversationemergencytype\/fetchsilent"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationEmergencyType"]]},"metadata":{"roleHeading":"Case","externalID":"c:@M@ShengwangChatUIKit@E@ConversationEmergencyType@ConversationEmergencyTypeFetchSilent","symbolKind":"case","role":"symbol","modules":[{"name":"ShengwangChatUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"ConversationEmergencyTypeFetchSilent"}],"title":"ConversationEmergencyType.fetchSilent","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"fetchSilent"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fetchSilent","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationEmergencyType\/fetchSilent","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ConversationEmergencyType":{"url":"\/documentation\/shengwangchatuikit\/conversationemergencytype","kind":"symbol","title":"ConversationEmergencyType","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"ConversationEmergencyType","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationEmergencyType","abstract":[],"navigatorTitle":[{"text":"ConversationEmergencyType","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ConversationEmergencyType/fetchSilent":{"url":"\/documentation\/shengwangchatuikit\/conversationemergencytype\/fetchsilent","title":"ConversationEmergencyType.fetchSilent","navigatorTitle":[{"kind":"identifier","text":"ConversationEmergencyTypeFetchSilent"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationEmergencyType\/fetchSilent","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fetchSilent"}],"role":"symbol","kind":"symbol","abstract":[],"type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"ConversationEmergencyTypeFetchSilent"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"ConversationEmergencyTypeFetchSilent","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"ConversationEmergencyTypeFetchSilent","kind":"identifier"}]}]},"op":"replace"},{"value":"ConversationEmergencyType","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationEmergencyType\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationEmergencyType\/fragments","value":[{"kind":"identifier","text":"ConversationEmergencyType"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationEmergencyType\/navigatorTitle","value":[{"text":"ConversationEmergencyType","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"ConversationEmergencyTypeFetchSilent","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationEmergencyType~1fetchSilent\/title"},{"value":[{"kind":"identifier","text":"ConversationEmergencyTypeFetchSilent"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationEmergencyType~1fetchSilent\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}