{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationEmergencyType"]]},"variants":[{"paths":["\/documentation\/shengwangchatuikit\/conversationemergencytype\/unpin"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/conversationemergencytype\/unpin"]}],"sections":[],"metadata":{"title":"ConversationEmergencyType.unpin","roleHeading":"Case","modules":[{"name":"ShengwangChatUIKit"}],"role":"symbol","externalID":"c:@M@ShengwangChatUIKit@E@ConversationEmergencyType@ConversationEmergencyTypeUnpin","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unpin","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ConversationEmergencyTypeUnpin"}],"symbolKind":"case"},"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationEmergencyType\/unpin","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unpin"}],"platforms":["iOS"]}]}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ConversationEmergencyType":{"url":"\/documentation\/shengwangchatuikit\/conversationemergencytype","kind":"symbol","title":"ConversationEmergencyType","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"ConversationEmergencyType","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationEmergencyType","abstract":[],"navigatorTitle":[{"text":"ConversationEmergencyType","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ConversationEmergencyType/unpin":{"type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"unpin"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationEmergencyType\/unpin","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ConversationEmergencyTypeUnpin"}],"role":"symbol","title":"ConversationEmergencyType.unpin","url":"\/documentation\/shengwangchatuikit\/conversationemergencytype\/unpin","abstract":[]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"ConversationEmergencyTypeUnpin"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ConversationEmergencyTypeUnpin"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"ConversationEmergencyTypeUnpin","kind":"identifier"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"value":"ConversationEmergencyType","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationEmergencyType\/title"},{"value":[{"text":"ConversationEmergencyType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationEmergencyType\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationEmergencyType\/navigatorTitle","value":[{"text":"ConversationEmergencyType","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"ConversationEmergencyTypeUnpin","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationEmergencyType~1unpin\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationEmergencyType~1unpin\/fragments","op":"replace","value":[{"text":"ConversationEmergencyTypeUnpin","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}