{"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageAudioRecordView\/init(frame:sendClosure:trashClosure:)"},"abstract":[{"text":"Audio record view.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageAudioRecordView"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"@","kind":"attribute"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"required","kind":"keyword"},{"kind":"text","text":" "},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"frame","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CGRect","text":"CGRect","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"sendClosure","kind":"externalParam"},{"kind":"text","text":": "},{"text":"@escaping","kind":"attribute"},{"text":" (","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"kind":"text","text":") -> (), "},{"kind":"externalParam","text":"trashClosure"},{"text":": ","kind":"text"},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" () -> ())"}],"platforms":["iOS"],"languages":["swift"]}]},{"parameters":[{"content":[{"inlineContent":[{"text":"","type":"text"},{"code":"CGRect","type":"codeVoice"}],"type":"paragraph"}],"name":"frame"},{"name":"sendClosure","content":[{"inlineContent":[{"text":"Send closure,contain file url and audio duration.","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"Trash closure.","type":"text"}],"type":"paragraph"}],"name":"trashClosure"}],"kind":"parameters"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/messageaudiorecordview\/init(frame:sendclosure:trashclosure:)"]},{"paths":["\/documentation\/shengwangchatuikit\/messageaudiorecordview\/init(frame:sendclosure:trashclosure:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"roleHeading":"Initializer","externalID":"c:@M@ShengwangChatUIKit@objc(cs)MessageAudioRecordView(im)initWithFrame:sendClosure:trashClosure:","symbolKind":"init","navigatorTitle":[{"kind":"identifier","text":"initWithFrame:sendClosure:trashClosure:"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"frame","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CGRect","text":"CGRect","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"sendClosure","kind":"externalParam"},{"text":": (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":") -> (), "},{"kind":"externalParam","text":"trashClosure"},{"text":": () -> ())","kind":"text"}],"title":"init(frame:sendClosure:trashClosure:)","modules":[{"name":"ShengwangChatUIKit"}],"role":"symbol"},"kind":"symbol","references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageAudioRecordView":{"type":"topic","role":"symbol","title":"MessageAudioRecordView","kind":"symbol","abstract":[],"navigatorTitle":[{"text":"MessageAudioRecordView","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/messageaudiorecordview","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageAudioRecordView","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MessageAudioRecordView","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageAudioRecordView/init(frame:sendClosure:trashClosure:)":{"role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Audio record view."}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageAudioRecordView\/init(frame:sendClosure:trashClosure:)","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"frame","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect","text":"CGRect"},{"kind":"text","text":", "},{"kind":"externalParam","text":"sendClosure"},{"text":": (","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":", ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":") -> (), ","kind":"text"},{"text":"trashClosure","kind":"externalParam"},{"kind":"text","text":": () -> ())"}],"navigatorTitle":[{"kind":"identifier","text":"initWithFrame:sendClosure:trashClosure:"}],"type":"topic","title":"init(frame:sendClosure:trashClosure:)","url":"\/documentation\/shengwangchatuikit\/messageaudiorecordview\/init(frame:sendclosure:trashclosure:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"initWithFrame:sendClosure:trashClosure:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"initWithFrame:sendClosure:trashClosure:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"initWithFrame:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"CGRect","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"frame"},{"kind":"text","text":" "},{"kind":"identifier","text":"sendClosure:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":" (^"},{"text":")(","kind":"text"},{"kind":"typeIdentifier","text":"NSURL","preciseIdentifier":"c:objc(cs)NSURL"},{"text":" * ","kind":"text"},{"text":"","kind":"internalParam"},{"text":", ","kind":"text"},{"text":"NSInteger","preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier"},{"kind":"text","text":" "},{"text":"","kind":"internalParam"},{"kind":"text","text":")) "},{"text":"sendClosure","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"trashClosure:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":" (^","kind":"text"},{"kind":"text","text":")()) "},{"text":"trashClosure","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace"},{"op":"replace","value":{"kind":"parameters","parameters":[{"name":"frame","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"CGRect"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Send closure,contain file url and audio duration."}],"type":"paragraph"}],"name":"sendClosure"},{"content":[{"inlineContent":[{"type":"text","text":"Trash closure."}],"type":"paragraph"}],"name":"trashClosure"}]},"path":"\/primaryContentSections\/1"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageAudioRecordView\/title","value":"MessageAudioRecordView","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageAudioRecordView\/fragments","value":[{"kind":"identifier","text":"MessageAudioRecordView"}],"op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"MessageAudioRecordView"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageAudioRecordView\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageAudioRecordView~1init(frame:sendClosure:trashClosure:)\/title","value":"initWithFrame:sendClosure:trashClosure:"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithFrame:sendClosure:trashClosure:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageAudioRecordView~1init(frame:sendClosure:trashClosure:)\/fragments"}]}]}