{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UserStateChangedListener\/onUserTokenDidExpired()"},"abstract":[{"text":"User token expired,when you need to fetch chat token  re-login.","type":"text"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onUserTokenDidExpired","kind":"identifier"},{"kind":"text","text":"()"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UserStateChangedListener"]]},"sections":[],"metadata":{"externalID":"c:@M@ShengwangChatUIKit@objc(pl)UserStateChangedListener(im)onUserTokenDidExpired","roleHeading":"Instance Method","required":true,"role":"symbol","symbolKind":"method","modules":[{"name":"ShengwangChatUIKit"}],"title":"onUserTokenDidExpired()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onUserTokenDidExpired","kind":"identifier"},{"text":"()","kind":"text"}],"navigatorTitle":[{"text":"onUserTokenDidExpired","kind":"identifier"}]},"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/userstatechangedlistener\/onusertokendidexpired()"]},{"paths":["\/documentation\/shengwangchatuikit\/userstatechangedlistener\/onusertokendidexpired()"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/UserStateChangedListener/onUserTokenDidExpired()":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UserStateChangedListener\/onUserTokenDidExpired()","role":"symbol","required":true,"url":"\/documentation\/shengwangchatuikit\/userstatechangedlistener\/onusertokendidexpired()","type":"topic","title":"onUserTokenDidExpired()","navigatorTitle":[{"kind":"identifier","text":"onUserTokenDidExpired"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onUserTokenDidExpired","kind":"identifier"},{"text":"()","kind":"text"}],"abstract":[{"text":"User token expired,when you need to fetch chat token  re-login.","type":"text"}],"kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/UserStateChangedListener":{"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"UserStateChangedListener","kind":"identifier"}],"navigatorTitle":[{"text":"UserStateChangedListener","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/userstatechangedlistener","type":"topic","abstract":[],"title":"UserStateChangedListener","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UserStateChangedListener","role":"symbol","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","value":"onUserTokenDidExpired","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onUserTokenDidExpired"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"text":"onUserTokenDidExpired","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1UserStateChangedListener~1onUserTokenDidExpired()\/title","value":"onUserTokenDidExpired","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1UserStateChangedListener~1onUserTokenDidExpired()\/fragments","value":[{"kind":"text","text":"- "},{"text":"onUserTokenDidExpired","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1UserStateChangedListener\/title","value":"UserStateChangedListener"},{"op":"replace","value":[{"text":"UserStateChangedListener","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1UserStateChangedListener\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1UserStateChangedListener\/navigatorTitle","op":"replace","value":[{"text":"UserStateChangedListener","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}