{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UserStateChangedListener\/onUserLoginOtherDevice(device:)"},"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UserStateChangedListener"]]},"abstract":[{"text":"User login at other device","type":"text"}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/userstatechangedlistener\/onuserloginotherdevice(device:)"]},{"paths":["\/documentation\/shengwangchatuikit\/userstatechangedlistener\/onuserloginotherdevice(device:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","metadata":{"symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"onUserLoginOtherDevice","kind":"identifier"},{"text":"(","kind":"text"},{"text":"device","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"role":"symbol","required":true,"roleHeading":"Instance Method","navigatorTitle":[{"text":"onUserLoginOtherDeviceWithDevice:","kind":"identifier"}],"externalID":"c:@M@ShengwangChatUIKit@objc(pl)UserStateChangedListener(im)onUserLoginOtherDeviceWithDevice:","title":"onUserLoginOtherDevice(device:)","modules":[{"name":"ShengwangChatUIKit"}]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"onUserLoginOtherDevice"},{"kind":"text","text":"("},{"text":"device","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"name":"device","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Other device name"}]}]}],"kind":"parameters"}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/UserStateChangedListener/onUserLoginOtherDevice(device:)":{"abstract":[{"text":"User login at other device","type":"text"}],"url":"\/documentation\/shengwangchatuikit\/userstatechangedlistener\/onuserloginotherdevice(device:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"onUserLoginOtherDevice","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"device"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UserStateChangedListener\/onUserLoginOtherDevice(device:)","title":"onUserLoginOtherDevice(device:)","required":true,"role":"symbol","navigatorTitle":[{"text":"onUserLoginOtherDeviceWithDevice:","kind":"identifier"}],"kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/UserStateChangedListener":{"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"UserStateChangedListener","kind":"identifier"}],"navigatorTitle":[{"text":"UserStateChangedListener","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/userstatechangedlistener","type":"topic","abstract":[],"title":"UserStateChangedListener","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UserStateChangedListener","role":"symbol","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"onUserLoginOtherDeviceWithDevice:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"onUserLoginOtherDeviceWithDevice:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"onUserLoginOtherDeviceWithDevice:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"device"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace"},{"path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"device","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Other device name"}]}]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1UserStateChangedListener~1onUserLoginOtherDevice(device:)\/title","value":"onUserLoginOtherDeviceWithDevice:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1UserStateChangedListener~1onUserLoginOtherDevice(device:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"onUserLoginOtherDeviceWithDevice:","kind":"identifier"}]},{"op":"replace","value":"UserStateChangedListener","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1UserStateChangedListener\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1UserStateChangedListener\/fragments","value":[{"kind":"identifier","text":"UserStateChangedListener"}]},{"value":[{"text":"UserStateChangedListener","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1UserStateChangedListener\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}