{"variants":[{"paths":["\/documentation\/shengwangchatuikit\/chatuikitcontext\/groupprofileprovideroc"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/chatuikitcontext\/groupprofileprovideroc"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"groupProfileProviderOC","kind":"identifier"},{"kind":"text","text":": "},{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatGroupProfileProviderOC","kind":"typeIdentifier","text":"ChatGroupProfileProviderOC","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(pl)ChatGroupProfileProviderOC"},{"kind":"text","text":"?"}],"platforms":["iOS"]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"modules":[{"name":"ShengwangChatUIKit"}],"roleHeading":"Instance Property","navigatorTitle":[{"text":"groupProfileProviderOC","kind":"identifier"}],"externalID":"c:@M@ShengwangChatUIKit@objc(cs)ChatUIKitContext(py)groupProfileProviderOC","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"groupProfileProviderOC","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ChatGroupProfileProviderOC","kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(pl)ChatGroupProfileProviderOC"},{"text":"?","kind":"text"}],"title":"groupProfileProviderOC","role":"symbol"},"sections":[],"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatUIKitContext\/groupProfileProviderOC","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatUIKitContext"]]},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatUIKitContext/groupProfileProviderOC":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"groupProfileProviderOC","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ChatGroupProfileProviderOC","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(pl)ChatGroupProfileProviderOC","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"groupProfileProviderOC"}],"url":"\/documentation\/shengwangchatuikit\/chatuikitcontext\/groupprofileprovideroc","type":"topic","title":"groupProfileProviderOC","abstract":[],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatUIKitContext\/groupProfileProviderOC","role":"symbol","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatGroupProfileProviderOC":{"navigatorTitle":[{"text":"ChatGroupProfileProviderOC","kind":"identifier"}],"abstract":[],"type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"ChatGroupProfileProviderOC","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/chatgroupprofileprovideroc","role":"symbol","title":"ChatGroupProfileProviderOC","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatGroupProfileProviderOC"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatUIKitContext":{"url":"\/documentation\/shengwangchatuikit\/chatuikitcontext","kind":"symbol","type":"topic","navigatorTitle":[{"text":"ChatUIKitContext","kind":"identifier"}],"abstract":[],"role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatUIKitContext","title":"ChatUIKitContext","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ChatUIKitContext","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"groupProfileProviderOC"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"groupProfileProviderOC","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":") "},{"preciseIdentifier":"c:Qo@M@ShengwangChatUIKit@objc(pl)ChatGroupProfileProviderOC","text":"id<ChatGroupProfileProviderOC>","kind":"typeIdentifier"},{"kind":"text","text":" "},{"kind":"identifier","text":"groupProfileProviderOC"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","value":"groupProfileProviderOC","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatUIKitContext~1groupProfileProviderOC\/title"},{"value":[{"kind":"identifier","text":"groupProfileProviderOC"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatUIKitContext~1groupProfileProviderOC\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatGroupProfileProviderOC\/title","value":"ChatGroupProfileProviderOC"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatGroupProfileProviderOC\/fragments","value":[{"text":"ChatGroupProfileProviderOC","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatGroupProfileProviderOC\/navigatorTitle","value":[{"kind":"identifier","text":"ChatGroupProfileProviderOC"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatUIKitContext\/title","value":"ChatUIKitContext"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatUIKitContext\/fragments","value":[{"text":"ChatUIKitContext","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatUIKitContext\/navigatorTitle","value":[{"kind":"identifier","text":"ChatUIKitContext"}],"op":"replace"}]}]}