{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatUIKitContext"]]},"kind":"symbol","sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/chatuikitcontext\/groupprofileprovider"]}],"metadata":{"roleHeading":"Instance Property","title":"groupProfileProvider","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"groupProfileProvider"},{"kind":"text","text":": "},{"preciseIdentifier":"s:18ShengwangChatUIKit0B20GroupProfileProviderP","text":"ChatGroupProfileProvider","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"externalID":"s:18ShengwangChatUIKit0bC7ContextC20groupProfileProviderAA0b5GroupfG0_pSgvp","modules":[{"name":"ShengwangChatUIKit"}],"symbolKind":"property"},"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatUIKitContext\/groupProfileProvider","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"groupProfileProvider","kind":"identifier"},{"kind":"text","text":": "},{"text":"ChatGroupProfileProvider","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatGroupProfileProvider","preciseIdentifier":"s:18ShengwangChatUIKit0B20GroupProfileProviderP","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"languages":["swift"]}]}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatUIKitContext":{"url":"\/documentation\/shengwangchatuikit\/chatuikitcontext","kind":"symbol","type":"topic","navigatorTitle":[{"text":"ChatUIKitContext","kind":"identifier"}],"abstract":[],"role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatUIKitContext","title":"ChatUIKitContext","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ChatUIKitContext","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatUIKitContext/groupProfileProvider":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"groupProfileProvider","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:18ShengwangChatUIKit0B20GroupProfileProviderP","text":"ChatGroupProfileProvider","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"url":"\/documentation\/shengwangchatuikit\/chatuikitcontext\/groupprofileprovider","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatUIKitContext\/groupProfileProvider","abstract":[],"role":"symbol","type":"topic","kind":"symbol","title":"groupProfileProvider"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatGroupProfileProvider":{"title":"ChatGroupProfileProvider","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatGroupProfileProvider","url":"\/documentation\/shengwangchatuikit\/chatgroupprofileprovider","abstract":[],"kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ChatGroupProfileProvider"}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"ChatGroupProfileProvider","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatUIKitContext\/title","value":"ChatUIKitContext"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatUIKitContext\/fragments","value":[{"text":"ChatUIKitContext","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatUIKitContext\/navigatorTitle","op":"replace","value":[{"text":"ChatUIKitContext","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}