{"metadata":{"symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"pinnedCache"},{"text":": ","kind":"text"},{"text":"Dictionary","kind":"typeIdentifier","preciseIdentifier":"s:SD"},{"text":"<","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":">?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"pinnedCache"}],"role":"symbol","externalID":"c:@M@ShengwangChatUIKit@objc(cs)ChatUIKitContext(py)pinnedCache","title":"pinnedCache","roleHeading":"Instance Property","modules":[{"name":"ShengwangChatUIKit"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatUIKitContext"]]},"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatUIKitContext\/pinnedCache","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"pinnedCache","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Dictionary","kind":"typeIdentifier","preciseIdentifier":"s:SD"},{"text":"<","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"kind":"text","text":">?"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/shengwangchatuikit\/chatuikitcontext\/pinnedcache"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/shengwangchatuikit\/chatuikitcontext\/pinnedcache"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatUIKitContext/pinnedCache":{"kind":"symbol","type":"topic","title":"pinnedCache","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatUIKitContext\/pinnedCache","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"pinnedCache"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Dictionary","preciseIdentifier":"s:SD"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":">?"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"pinnedCache"}],"url":"\/documentation\/shengwangchatuikit\/chatuikitcontext\/pinnedcache","abstract":[]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatUIKitContext":{"url":"\/documentation\/shengwangchatuikit\/chatuikitcontext","kind":"symbol","type":"topic","navigatorTitle":[{"text":"ChatUIKitContext","kind":"identifier"}],"abstract":[],"role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatUIKitContext","title":"ChatUIKitContext","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ChatUIKitContext","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"value":"pinnedCache","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"value":[{"text":"pinnedCache","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSDictionary<NSString *,NSNumber *>","preciseIdentifier":"c:Q$objc(cs)NSDictionary","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"pinnedCache"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace"},{"value":"pinnedCache","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatUIKitContext~1pinnedCache\/title"},{"value":[{"kind":"identifier","text":"pinnedCache"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatUIKitContext~1pinnedCache\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatUIKitContext\/title","value":"ChatUIKitContext"},{"op":"replace","value":[{"kind":"identifier","text":"ChatUIKitContext"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatUIKitContext\/fragments"},{"value":[{"kind":"identifier","text":"ChatUIKitContext"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatUIKitContext\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}