{"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatUIKitContext\/userProfileProvider","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"ShengwangChatUIKit"}],"roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"userProfileProvider","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:18ShengwangChatUIKit0B19UserProfileProviderP","text":"ChatUserProfileProvider","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"title":"userProfileProvider","role":"symbol","externalID":"s:18ShengwangChatUIKit0bC7ContextC19userProfileProviderAA0b4UserfG0_pSgvp","symbolKind":"property"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/chatuikitcontext\/userprofileprovider"]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"userProfileProvider","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:18ShengwangChatUIKit0B19UserProfileProviderP","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatUserProfileProvider","kind":"typeIdentifier","text":"ChatUserProfileProvider"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatUIKitContext"]]},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatUserProfileProvider":{"type":"topic","role":"symbol","title":"ChatUserProfileProvider","kind":"symbol","abstract":[{"text":"Profile provider of the ChatUIKit.Only available in Swift language.","type":"text"}],"navigatorTitle":[{"text":"ChatUserProfileProvider","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/chatuserprofileprovider","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatUserProfileProvider","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"ChatUserProfileProvider","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatUIKitContext":{"url":"\/documentation\/shengwangchatuikit\/chatuikitcontext","kind":"symbol","type":"topic","navigatorTitle":[{"text":"ChatUIKitContext","kind":"identifier"}],"abstract":[],"role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatUIKitContext","title":"ChatUIKitContext","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ChatUIKitContext","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatUIKitContext/userProfileProvider":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"userProfileProvider"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit0B19UserProfileProviderP","text":"ChatUserProfileProvider"},{"text":"?","kind":"text"}],"url":"\/documentation\/shengwangchatuikit\/chatuikitcontext\/userprofileprovider","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatUIKitContext\/userProfileProvider","abstract":[],"role":"symbol","type":"topic","kind":"symbol","title":"userProfileProvider"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatUIKitContext\/title","op":"replace","value":"ChatUIKitContext"},{"value":[{"text":"ChatUIKitContext","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatUIKitContext\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatUIKitContext\/navigatorTitle","value":[{"text":"ChatUIKitContext","kind":"identifier"}]}]}]}