{"metadata":{"title":"initWithFrame:","roleHeading":"Instance Method","externalID":"c:@M@ShengwangChatUIKit@objc(cs)GradientEmojiView(im)initWithFrame:","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithFrame:"}],"symbolKind":"method","modules":[{"name":"ShengwangChatUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"initWithFrame:"}],"role":"symbol"},"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GradientEmojiView"]]},"variants":[{"paths":["\/documentation\/shengwangchatuikit\/gradientemojiview\/initwithframe:"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GradientEmojiView\/initWithFrame:","interfaceLanguage":"occ"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"text":") ","kind":"text"},{"text":"initWithFrame:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@S@CGRect","text":"CGRect","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"frame","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}],"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/GradientEmojiView/initWithFrame:":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GradientEmojiView\/initWithFrame:","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithFrame:"}],"kind":"symbol","url":"\/documentation\/shengwangchatuikit\/gradientemojiview\/initwithframe:","title":"initWithFrame:","role":"symbol","abstract":[],"navigatorTitle":[{"text":"initWithFrame:","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/GradientEmojiView":{"title":"GradientEmojiView","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GradientEmojiView","url":"\/documentation\/shengwangchatuikit\/gradientemojiview","abstract":[],"kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"text":"GradientEmojiView","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"GradientEmojiView","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GradientEmojiView\/title","op":"replace","value":"GradientEmojiView"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GradientEmojiView\/fragments","value":[{"text":"GradientEmojiView","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"text":"GradientEmojiView","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GradientEmojiView\/navigatorTitle"}]}]}