{"kind":"symbol","sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GradientEmojiView"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"text":") ","kind":"text"},{"text":"initWithImage:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"image","kind":"internalParam"},{"kind":"text","text":" "},{"text":"highlightedImage:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"highlightedImage"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/gradientemojiview\/initwithimage:highlightedimage:"]}],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GradientEmojiView\/initWithImage:highlightedImage:"},"metadata":{"roleHeading":"Instance Method","navigatorTitle":[{"text":"initWithImage:highlightedImage:","kind":"identifier"}],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithImage:highlightedImage:"}],"externalID":"c:@M@ShengwangChatUIKit@objc(cs)GradientEmojiView(im)initWithImage:highlightedImage:","platforms":[{"beta":false,"introducedAt":"3.0","deprecated":false,"unavailable":false,"name":"iOS"},{"beta":false,"deprecated":false,"name":"iPadOS","introducedAt":"3.0","unavailable":false},{"beta":false,"introducedAt":"3.0","deprecated":false,"name":"Mac Catalyst","unavailable":false}],"role":"symbol","title":"initWithImage:highlightedImage:","modules":[{"name":"ShengwangChatUIKit"}],"symbolKind":"method"},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/GradientEmojiView":{"title":"GradientEmojiView","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GradientEmojiView","url":"\/documentation\/shengwangchatuikit\/gradientemojiview","abstract":[],"kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"text":"GradientEmojiView","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"GradientEmojiView","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/GradientEmojiView/initWithImage:highlightedImage:":{"title":"initWithImage:highlightedImage:","type":"topic","url":"\/documentation\/shengwangchatuikit\/gradientemojiview\/initwithimage:highlightedimage:","kind":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GradientEmojiView\/initWithImage:highlightedImage:","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithImage:highlightedImage:"}],"navigatorTitle":[{"kind":"identifier","text":"initWithImage:highlightedImage:"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GradientEmojiView\/title","value":"GradientEmojiView","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GradientEmojiView\/fragments","op":"replace","value":[{"text":"GradientEmojiView","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GradientEmojiView\/navigatorTitle","value":[{"text":"GradientEmojiView","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}