{"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"role":"symbol","modules":[{"name":"ShengwangChatUIKit"}],"roleHeading":"Instance Method","externalID":"c:@M@ShengwangChatUIKit@objc(cs)GradientEmojiView(im)initWithCoder:","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithCoder:"}],"title":"initWithCoder:"},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GradientEmojiView\/initWithCoder:"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithCoder:"},{"kind":"text","text":"("},{"text":"NSCoder","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSCoder"},{"kind":"text","text":" *) "},{"text":"coder","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GradientEmojiView"]]},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/gradientemojiview\/initwithcoder:"]}],"sections":[],"kind":"symbol","references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/GradientEmojiView/initWithCoder:":{"abstract":[],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GradientEmojiView\/initWithCoder:","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"type":"topic","role":"symbol","url":"\/documentation\/shengwangchatuikit\/gradientemojiview\/initwithcoder:","kind":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}],"title":"initWithCoder:"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/GradientEmojiView":{"title":"GradientEmojiView","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GradientEmojiView","url":"\/documentation\/shengwangchatuikit\/gradientemojiview","abstract":[],"kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"text":"GradientEmojiView","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"GradientEmojiView","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"GradientEmojiView","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GradientEmojiView\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GradientEmojiView\/fragments","value":[{"kind":"identifier","text":"GradientEmojiView"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GradientEmojiView\/navigatorTitle","value":[{"text":"GradientEmojiView","kind":"identifier"}],"op":"replace"}]}]}