{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/DetailInfoHeader\/collectionView(_:didSelectItemAt:)"},"abstract":[{"type":"text","text":"Inherited from "},{"code":"UICollectionViewDelegate.collectionView(_:didSelectItemAt:)","type":"codeVoice"},{"text":".","type":"text"}],"metadata":{"symbolKind":"method","title":"collectionView(_:didSelectItemAt:)","roleHeading":"Instance Method","extendedModule":"ShengwangChatUIKit","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"collectionView"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UICollectionView","kind":"typeIdentifier","text":"UICollectionView"},{"text":", ","kind":"text"},{"text":"didSelectItemAt","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation9IndexPathV","text":"IndexPath"},{"text":")","kind":"text"}],"externalID":"c:@CM@ShengwangChatUIKit@objc(cs)DetailInfoHeader(im)collectionView:didSelectItemAtIndexPath:","modules":[{"name":"ShengwangChatUIKit"}],"navigatorTitle":[{"text":"collectionView:didSelectItemAtIndexPath:","kind":"identifier"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/detailinfoheader\/collectionview(_:didselectitemat:)"]},{"paths":["\/documentation\/shengwangchatuikit\/detailinfoheader\/collectionview(_:didselectitemat:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@","kind":"attribute"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"collectionView","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"collectionView"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UICollectionView","text":"UICollectionView"},{"kind":"text","text":", "},{"text":"didSelectItemAt","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"indexPath"},{"text":": ","kind":"text"},{"text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV","kind":"typeIdentifier"},{"kind":"text","text":")"}]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/DetailInfoHeader","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/DetailInfoHeader\/UICollectionViewDelegate-Implementations"]]},"sections":[],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/DetailInfoHeader":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DetailInfoHeader","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/DetailInfoHeader","title":"DetailInfoHeader","navigatorTitle":[{"kind":"identifier","text":"DetailInfoHeader"}],"url":"\/documentation\/shengwangchatuikit\/detailinfoheader","abstract":[],"type":"topic","kind":"symbol","role":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/DetailInfoHeader/UICollectionViewDelegate-Implementations":{"abstract":[],"role":"collectionGroup","type":"topic","url":"\/documentation\/shengwangchatuikit\/detailinfoheader\/uicollectionviewdelegate-implementations","title":"UICollectionViewDelegate Implementations","kind":"article","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/DetailInfoHeader\/UICollectionViewDelegate-Implementations"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/DetailInfoHeader/collectionView(_:didSelectItemAt:)":{"url":"\/documentation\/shengwangchatuikit\/detailinfoheader\/collectionview(_:didselectitemat:)","role":"symbol","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"collectionView"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UICollectionView","kind":"typeIdentifier","text":"UICollectionView"},{"kind":"text","text":", "},{"text":"didSelectItemAt","kind":"externalParam"},{"kind":"text","text":": "},{"text":"IndexPath","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation9IndexPathV"},{"text":")","kind":"text"}],"kind":"symbol","type":"topic","navigatorTitle":[{"text":"collectionView:didSelectItemAtIndexPath:","kind":"identifier"}],"title":"collectionView(_:didSelectItemAt:)","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/DetailInfoHeader\/collectionView(_:didSelectItemAt:)"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"collectionView:didSelectItemAtIndexPath:","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"collectionView:didSelectItemAtIndexPath:","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"collectionView:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UICollectionView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UICollectionView"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"collectionView"},{"text":" ","kind":"text"},{"text":"didSelectItemAtIndexPath:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSIndexPath","text":"NSIndexPath"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"indexPath"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1DetailInfoHeader\/title","value":"DetailInfoHeader"},{"value":[{"text":"DetailInfoHeader","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1DetailInfoHeader\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1DetailInfoHeader\/navigatorTitle","value":[{"kind":"identifier","text":"DetailInfoHeader"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1DetailInfoHeader~1collectionView(_:didSelectItemAt:)\/title","value":"collectionView:didSelectItemAtIndexPath:","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"collectionView:didSelectItemAtIndexPath:"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1DetailInfoHeader~1collectionView(_:didSelectItemAt:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}