{"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/DetailInfoHeader\/layout","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"text":" ","kind":"text"},{"text":"lazy","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"layout"},{"kind":"text","text":": "},{"text":"UICollectionViewFlowLayout","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UICollectionViewFlowLayout"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" "},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/DetailInfoHeader"]]},"sections":[],"metadata":{"externalID":"s:18ShengwangChatUIKit16DetailInfoHeaderC6layoutSo26UICollectionViewFlowLayoutCvp","role":"symbol","roleHeading":"Instance Property","title":"layout","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"layout"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UICollectionViewFlowLayout","kind":"typeIdentifier","text":"UICollectionViewFlowLayout"}],"modules":[{"name":"ShengwangChatUIKit"}],"symbolKind":"property"},"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/detailinfoheader\/layout"]}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/DetailInfoHeader/layout":{"role":"symbol","abstract":[],"kind":"symbol","title":"layout","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"layout","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UICollectionViewFlowLayout","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UICollectionViewFlowLayout"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/DetailInfoHeader\/layout","type":"topic","url":"\/documentation\/shengwangchatuikit\/detailinfoheader\/layout"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/DetailInfoHeader":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DetailInfoHeader","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/DetailInfoHeader","title":"DetailInfoHeader","navigatorTitle":[{"kind":"identifier","text":"DetailInfoHeader"}],"url":"\/documentation\/shengwangchatuikit\/detailinfoheader","abstract":[],"type":"topic","kind":"symbol","role":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1DetailInfoHeader\/title","op":"replace","value":"DetailInfoHeader"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1DetailInfoHeader\/fragments","value":[{"text":"DetailInfoHeader","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"DetailInfoHeader"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1DetailInfoHeader\/navigatorTitle"}]}]}