{"metadata":{"symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"navigationClick","kind":"identifier"},{"kind":"text","text":"("},{"text":"type","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@E@ChatNavigationBarClickEvent","text":"ChatNavigationBarClickEvent","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"indexPath"},{"text":": ","kind":"text"},{"text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"navigationClickWithType:indexPath:"}],"role":"symbol","externalID":"c:@M@ShengwangChatUIKit@objc(cs)SearchResultMessagesController(im)navigationClickWithType:indexPath:","title":"navigationClick(type:indexPath:)","roleHeading":"Instance Method","modules":[{"name":"ShengwangChatUIKit"}]},"sections":[],"abstract":[{"text":"Handles the navigation bar click events.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"text":" ","kind":"text"},{"text":"override","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"navigationClick"},{"kind":"text","text":"("},{"text":"type","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatNavigationBarClickEvent","text":"ChatNavigationBarClickEvent","preciseIdentifier":"c:@M@ShengwangChatUIKit@E@ChatNavigationBarClickEvent","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"indexPath","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"text":"?)","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"content":[{"type":"heading","anchor":"discussion","text":"Discussion","level":2},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"text":"type: The type of navigation bar click event.","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"indexPath: The index path associated with the event (optional).","type":"text"}]}]}]}],"kind":"content"}],"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/SearchResultMessagesController\/navigationClick(type:indexPath:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/SearchResultMessagesController"]]},"variants":[{"paths":["\/documentation\/shengwangchatuikit\/searchresultmessagescontroller\/navigationclick(type:indexpath:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/searchresultmessagescontroller\/navigationclick(type:indexpath:)"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatNavigationBarClickEvent":{"abstract":[],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatNavigationBarClickEvent","navigatorTitle":[{"kind":"identifier","text":"ChatNavigationBarClickEvent"}],"kind":"symbol","url":"\/documentation\/shengwangchatuikit\/chatnavigationbarclickevent","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatNavigationBarClickEvent"}],"title":"ChatNavigationBarClickEvent","type":"topic"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/SearchResultMessagesController":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SearchResultMessagesController","kind":"identifier"}],"type":"topic","abstract":[],"role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/SearchResultMessagesController","title":"SearchResultMessagesController","navigatorTitle":[{"text":"SearchResultMessagesController","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/searchresultmessagescontroller"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/SearchResultMessagesController/navigationClick(type:indexPath:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"navigationClick"},{"text":"(","kind":"text"},{"text":"type","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@E@ChatNavigationBarClickEvent","text":"ChatNavigationBarClickEvent"},{"text":", ","kind":"text"},{"text":"indexPath","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation9IndexPathV","text":"IndexPath"},{"text":"?)","kind":"text"}],"type":"topic","abstract":[{"text":"Handles the navigation bar click events.","type":"text"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/SearchResultMessagesController\/navigationClick(type:indexPath:)","title":"navigationClick(type:indexPath:)","navigatorTitle":[{"text":"navigationClickWithType:indexPath:","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/searchresultmessagescontroller\/navigationclick(type:indexpath:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","value":"navigationClickWithType:indexPath:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"navigationClickWithType:indexPath:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"navigationClickWithType:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatNavigationBarClickEvent","preciseIdentifier":"c:@M@ShengwangChatUIKit@E@ChatNavigationBarClickEvent","kind":"typeIdentifier","text":"ChatNavigationBarClickEvent"},{"kind":"text","text":") "},{"text":"type","kind":"internalParam"},{"kind":"text","text":" "},{"text":"indexPath:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSIndexPath","text":"NSIndexPath","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"indexPath","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatNavigationBarClickEvent\/title","value":"ChatNavigationBarClickEvent"},{"value":[{"kind":"identifier","text":"ChatNavigationBarClickEvent"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatNavigationBarClickEvent\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatNavigationBarClickEvent\/navigatorTitle","value":[{"kind":"identifier","text":"ChatNavigationBarClickEvent"}]},{"value":"SearchResultMessagesController","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1SearchResultMessagesController\/title"},{"value":[{"text":"SearchResultMessagesController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1SearchResultMessagesController\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1SearchResultMessagesController\/navigatorTitle","op":"replace","value":[{"text":"SearchResultMessagesController","kind":"identifier"}]},{"value":"navigationClickWithType:indexPath:","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1SearchResultMessagesController~1navigationClick(type:indexPath:)\/title","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"navigationClickWithType:indexPath:"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1SearchResultMessagesController~1navigationClick(type:indexPath:)\/fragments"}]}]}