{"abstract":[{"text":"This method is called to view the detail of a chat message.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"It determines the type of chat (individual or group) and presents the appropriate view controller accordingly."},{"type":"text","text":" "},{"type":"text","text":"If the previous view controller in the navigation stack is either "},{"code":"GroupInfoViewController","type":"codeVoice"},{"text":" or ","type":"text"},{"type":"codeVoice","code":"ContactInfoViewController"},{"type":"text","text":", it pops the current view controller."},{"text":" ","type":"text"},{"type":"text","text":"If the chat type is individual, it presents the "},{"type":"codeVoice","code":"ContactInfoController"},{"text":" with the given profile.","type":"text"},{"text":" ","type":"text"},{"text":"If the chat type is group, it presents the ","type":"text"},{"type":"codeVoice","code":"GroupInfoController"},{"type":"text","text":" with the given group ID and updates the navigation title with the group name."},{"type":"text","text":" "},{"type":"text","text":"If there is no previous view controller in the navigation stack, it checks if the presenting view controller is either "},{"code":"GroupInfoViewController","type":"codeVoice"},{"type":"text","text":" or "},{"type":"codeVoice","code":"ContactInfoViewController"},{"type":"text","text":" and dismisses it."},{"text":" ","type":"text"},{"text":"If the chat type is individual, it presents the ","type":"text"},{"code":"ContactInfoController","type":"codeVoice"},{"type":"text","text":" with the given profile."},{"text":" ","type":"text"},{"type":"text","text":"If the chat type is group, it presents the "},{"type":"codeVoice","code":"GroupInfoController"},{"type":"text","text":" with the given group ID and updates the navigation title with the group name."}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"text":"override","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"viewDetail","kind":"identifier"},{"kind":"text","text":"()"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/searchresultmessagescontroller\/viewdetail()"]},{"paths":["\/documentation\/shengwangchatuikit\/searchresultmessagescontroller\/viewdetail()"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/SearchResultMessagesController"]]},"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/SearchResultMessagesController\/viewDetail()","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"metadata":{"roleHeading":"Instance Method","modules":[{"name":"ShengwangChatUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"viewDetail"}],"externalID":"c:@M@ShengwangChatUIKit@objc(cs)SearchResultMessagesController(im)viewDetail","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDetail"},{"text":"()","kind":"text"}],"title":"viewDetail()","role":"symbol"},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/SearchResultMessagesController/viewDetail()":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"viewDetail","kind":"identifier"},{"text":"()","kind":"text"}],"navigatorTitle":[{"text":"viewDetail","kind":"identifier"}],"abstract":[{"text":"This method is called to view the detail of a chat message.","type":"text"},{"text":" ","type":"text"},{"text":"It determines the type of chat (individual or group) and presents the appropriate view controller accordingly.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"If the previous view controller in the navigation stack is either "},{"type":"codeVoice","code":"GroupInfoViewController"},{"text":" or ","type":"text"},{"code":"ContactInfoViewController","type":"codeVoice"},{"text":", it pops the current view controller.","type":"text"},{"text":" ","type":"text"},{"text":"If the chat type is individual, it presents the ","type":"text"},{"type":"codeVoice","code":"ContactInfoController"},{"type":"text","text":" with the given profile."},{"text":" ","type":"text"},{"text":"If the chat type is group, it presents the ","type":"text"},{"type":"codeVoice","code":"GroupInfoController"},{"type":"text","text":" with the given group ID and updates the navigation title with the group name."},{"type":"text","text":" "},{"text":"If there is no previous view controller in the navigation stack, it checks if the presenting view controller is either ","type":"text"},{"type":"codeVoice","code":"GroupInfoViewController"},{"text":" or ","type":"text"},{"type":"codeVoice","code":"ContactInfoViewController"},{"type":"text","text":" and dismisses it."},{"text":" ","type":"text"},{"text":"If the chat type is individual, it presents the ","type":"text"},{"type":"codeVoice","code":"ContactInfoController"},{"type":"text","text":" with the given profile."},{"text":" ","type":"text"},{"type":"text","text":"If the chat type is group, it presents the "},{"code":"GroupInfoController","type":"codeVoice"},{"type":"text","text":" with the given group ID and updates the navigation title with the group name."}],"url":"\/documentation\/shengwangchatuikit\/searchresultmessagescontroller\/viewdetail()","type":"topic","title":"viewDetail()","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/SearchResultMessagesController\/viewDetail()","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/SearchResultMessagesController":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SearchResultMessagesController","kind":"identifier"}],"type":"topic","abstract":[],"role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/SearchResultMessagesController","title":"SearchResultMessagesController","navigatorTitle":[{"text":"SearchResultMessagesController","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/searchresultmessagescontroller"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"value":"viewDetail","op":"replace","path":"\/metadata\/title"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"viewDetail","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"text":"viewDetail","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"viewDetail","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1SearchResultMessagesController~1viewDetail()\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1SearchResultMessagesController~1viewDetail()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDetail"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1SearchResultMessagesController\/title","value":"SearchResultMessagesController","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1SearchResultMessagesController\/fragments","value":[{"text":"SearchResultMessagesController","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"SearchResultMessagesController"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1SearchResultMessagesController\/navigatorTitle"}]}]}