{"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/SearchResultMessagesController\/viewContact(body:)","interfaceLanguage":"swift"},"kind":"symbol","abstract":[{"text":"Opens the contact view for the given custom message body.","type":"text"}],"sections":[],"metadata":{"navigatorTitle":[{"text":"viewContactWithBody:","kind":"identifier"}],"symbolKind":"method","externalID":"c:@M@ShengwangChatUIKit@objc(cs)SearchResultMessagesController(im)viewContactWithBody:","role":"symbol","modules":[{"name":"ShengwangChatUIKit"}],"roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewContact"},{"text":"(","kind":"text"},{"text":"body","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:18ShengwangChatUIKit0B17CustomMessageBodya","kind":"typeIdentifier","text":"ChatCustomMessageBody"},{"kind":"text","text":")"}],"title":"viewContact(body:)"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/SearchResultMessagesController"]]},"variants":[{"paths":["\/documentation\/shengwangchatuikit\/searchresultmessagescontroller\/viewcontact(body:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/searchresultmessagescontroller\/viewcontact(body:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"override"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"viewContact","kind":"identifier"},{"kind":"text","text":"("},{"text":"body","kind":"externalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatCustomMessageBody","preciseIdentifier":"s:18ShengwangChatUIKit0B17CustomMessageBodya","kind":"typeIdentifier","text":"ChatCustomMessageBody"},{"text":")","kind":"text"}],"platforms":["iOS"]}]},{"content":[{"text":"Discussion","anchor":"discussion","level":2,"type":"heading"},{"items":[{"content":[{"inlineContent":[{"type":"text","text":"body: The custom message body containing contact information."}],"type":"paragraph"}]}],"type":"unorderedList"}],"kind":"content"}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/SearchResultMessagesController/viewContact(body:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"viewContact","kind":"identifier"},{"text":"(","kind":"text"},{"text":"body","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ChatCustomMessageBody","kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit0B17CustomMessageBodya"},{"kind":"text","text":")"}],"type":"topic","abstract":[{"text":"Opens the contact view for the given custom message body.","type":"text"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/SearchResultMessagesController\/viewContact(body:)","title":"viewContact(body:)","navigatorTitle":[{"kind":"identifier","text":"viewContactWithBody:"}],"url":"\/documentation\/shengwangchatuikit\/searchresultmessagescontroller\/viewcontact(body:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatCustomMessageBody":{"url":"\/documentation\/shengwangchatuikit\/chatcustommessagebody","abstract":[],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ChatCustomMessageBody"}],"type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatCustomMessageBody","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatCustomMessageBody"}],"title":"ChatCustomMessageBody"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/SearchResultMessagesController":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SearchResultMessagesController","kind":"identifier"}],"type":"topic","abstract":[],"role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/SearchResultMessagesController","title":"SearchResultMessagesController","navigatorTitle":[{"text":"SearchResultMessagesController","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/searchresultmessagescontroller"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","value":"viewContactWithBody:","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"viewContactWithBody:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"viewContactWithBody:"},{"text":"(","kind":"text"},{"text":"AgoraChatCustomMessageBody","preciseIdentifier":"c:objc(cs)AgoraChatCustomMessageBody","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"body","kind":"internalParam"},{"kind":"text","text":";"}]}]}},{"op":"replace","value":"viewContactWithBody:","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1SearchResultMessagesController~1viewContact(body:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1SearchResultMessagesController~1viewContact(body:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"viewContactWithBody:"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1SearchResultMessagesController\/title","value":"SearchResultMessagesController","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1SearchResultMessagesController\/fragments","value":[{"text":"SearchResultMessagesController","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1SearchResultMessagesController\/navigatorTitle","value":[{"text":"SearchResultMessagesController","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}