{"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"id","preciseIdentifier":"c:*Qo","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"init"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}],"metadata":{"role":"symbol","title":"init","symbolKind":"method","externalID":"c:@M@ShengwangChatUIKit@objc(cs)DialogManager(im)init","roleHeading":"Instance Method","navigatorTitle":[{"text":"init","kind":"identifier"}],"modules":[{"name":"ShengwangChatUIKit"}],"fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}]},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/DialogManager\/init"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/DialogManager"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/dialogmanager\/init"]}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/DialogManager/init":{"type":"topic","role":"symbol","title":"init","kind":"symbol","abstract":[],"navigatorTitle":[{"text":"init","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/dialogmanager\/init","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/DialogManager\/init","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/DialogManager":{"url":"\/documentation\/shengwangchatuikit\/dialogmanager","navigatorTitle":[{"text":"DialogManager","kind":"identifier"}],"title":"DialogManager","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/DialogManager","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DialogManager","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[]}},"variantOverrides":[{"patch":[{"op":"replace","value":"DialogManager","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1DialogManager\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1DialogManager\/fragments","value":[{"text":"DialogManager","kind":"identifier"}],"op":"replace"},{"value":[{"text":"DialogManager","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1DialogManager\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}