{"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"showCustomDialog","kind":"identifier"},{"kind":"text","text":"("},{"text":"customView","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIView","preciseIdentifier":"c:objc(cs)UIView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"dismiss","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":" = true)","kind":"text"}]}],"kind":"declarations"}],"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"showCustomDialog"},{"kind":"text","text":"("},{"text":"customView","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UIView","preciseIdentifier":"c:objc(cs)UIView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"dismiss"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}],"externalID":"c:@M@ShengwangChatUIKit@objc(cs)DialogManager(im)showCustomDialogWithCustomView:dismiss:","modules":[{"name":"ShengwangChatUIKit"}],"roleHeading":"Instance Method","symbolKind":"method","title":"showCustomDialog(customView:dismiss:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"showCustomDialogWithCustomView:dismiss:"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/DialogManager\/showCustomDialog(customView:dismiss:)"},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/DialogManager"]]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/dialogmanager\/showcustomdialog(customview:dismiss:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/dialogmanager\/showcustomdialog(customview:dismiss:)"]}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/DialogManager/showCustomDialog(customView:dismiss:)":{"title":"showCustomDialog(customView:dismiss:)","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/DialogManager\/showCustomDialog(customView:dismiss:)","type":"topic","url":"\/documentation\/shengwangchatuikit\/dialogmanager\/showcustomdialog(customview:dismiss:)","abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"showCustomDialog","kind":"identifier"},{"kind":"text","text":"("},{"text":"customView","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"dismiss"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"showCustomDialogWithCustomView:dismiss:"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/DialogManager":{"url":"\/documentation\/shengwangchatuikit\/dialogmanager","navigatorTitle":[{"text":"DialogManager","kind":"identifier"}],"title":"DialogManager","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/DialogManager","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DialogManager","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"value":"showCustomDialogWithCustomView:dismiss:","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"text":"- ","kind":"text"},{"text":"showCustomDialogWithCustomView:dismiss:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"text":"showCustomDialogWithCustomView:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView","text":"UIView"},{"kind":"text","text":" *) "},{"text":"customView","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"dismiss:","kind":"identifier"},{"kind":"text","text":"("},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"dismiss","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1DialogManager~1showCustomDialog(customView:dismiss:)\/title","value":"showCustomDialogWithCustomView:dismiss:","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"showCustomDialogWithCustomView:dismiss:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1DialogManager~1showCustomDialog(customView:dismiss:)\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1DialogManager\/title","value":"DialogManager","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1DialogManager\/fragments","value":[{"text":"DialogManager","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"DialogManager"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1DialogManager\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}