{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/DialogManager\/showAlert(title:content:showCancel:showConfirm:showTextFiled:placeHolder:confirmClosure:cancelClosure:)"},"metadata":{"modules":[{"name":"ShengwangChatUIKit"}],"roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"showAlert","kind":"identifier"},{"text":"(","kind":"text"},{"text":"title","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"text":"content","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"text":"showCancel","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"showConfirm","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"showTextFiled","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"placeHolder"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"text":"confirmClosure","kind":"externalParam"},{"text":": (","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cancelClosure"},{"kind":"text","text":": (() -> "},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"kind":"text","text":")?)"}],"title":"showAlert(title:content:showCancel:showConfirm:showTextFiled:placeHolder:confirmClosure:cancelClosure:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"showAlertWithTitle:content:showCancel:showConfirm:showTextFiled:placeHolder:confirmClosure:cancelClosure:"}],"externalID":"c:@M@ShengwangChatUIKit@objc(cs)DialogManager(im)showAlertWithTitle:content:showCancel:showConfirm:showTextFiled:placeHolder:confirmClosure:cancelClosure:","symbolKind":"method"},"variants":[{"paths":["\/documentation\/shengwangchatuikit\/dialogmanager\/showalert(title:content:showcancel:showconfirm:showtextfiled:placeholder:confirmclosure:cancelclosure:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/dialogmanager\/showalert(title:content:showcancel:showconfirm:showtextfiled:placeholder:confirmclosure:cancelclosure:)"]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"showAlert","kind":"identifier"},{"text":"(","kind":"text"},{"text":"title","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"content","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"showCancel"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":", ","kind":"text"},{"text":"showConfirm","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"showTextFiled"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":" = false, ","kind":"text"},{"text":"placeHolder","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":" = \"\", "},{"text":"confirmClosure","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"attribute"},{"text":" (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":", "},{"text":"cancelClosure","kind":"externalParam"},{"text":": (() -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")? = nil)","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"title","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The alert title to display."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The alert content to display."}]}],"name":"content"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Whether to display the "},{"code":"Cancel","type":"codeVoice"},{"text":" button.","type":"text"}]}],"name":"showCancel"},{"content":[{"inlineContent":[{"text":"Whether to display the ","type":"text"},{"type":"codeVoice","code":"Confirm"},{"type":"text","text":" button."}],"type":"paragraph"}],"name":"showConfirm"},{"content":[{"inlineContent":[{"text":"","type":"text"},{"code":"TextField","type":"codeVoice"},{"type":"text","text":" placeholder."}],"type":"paragraph"}],"name":"placeHolder"},{"name":"confirmClosure","content":[{"type":"paragraph","inlineContent":[{"text":"Callback upon a click of the ","type":"text"},{"code":"Confirm","type":"codeVoice"},{"type":"text","text":" button.When text field was shown callback contain input text."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/DialogManager"]]},"sections":[],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/DialogManager":{"url":"\/documentation\/shengwangchatuikit\/dialogmanager","navigatorTitle":[{"text":"DialogManager","kind":"identifier"}],"title":"DialogManager","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/DialogManager","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DialogManager","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/DialogManager/showAlert(title:content:showCancel:showConfirm:showTextFiled:placeHolder:confirmClosure:cancelClosure:)":{"title":"showAlert(title:content:showCancel:showConfirm:showTextFiled:placeHolder:confirmClosure:cancelClosure:)","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/DialogManager\/showAlert(title:content:showCancel:showConfirm:showTextFiled:placeHolder:confirmClosure:cancelClosure:)","type":"topic","url":"\/documentation\/shengwangchatuikit\/dialogmanager\/showalert(title:content:showcancel:showconfirm:showtextfiled:placeholder:confirmclosure:cancelclosure:)","abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"showAlert","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"title"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"content"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"showCancel","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"showConfirm","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"text":"showTextFiled","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"placeHolder"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"text":"confirmClosure","kind":"externalParam"},{"text":": (","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":", "},{"text":"cancelClosure","kind":"externalParam"},{"kind":"text","text":": (() -> "},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")?)","kind":"text"}],"role":"symbol","navigatorTitle":[{"text":"showAlertWithTitle:content:showCancel:showConfirm:showTextFiled:placeHolder:confirmClosure:cancelClosure:","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"showAlertWithTitle:content:showCancel:showConfirm:showTextFiled:placeHolder:confirmClosure:cancelClosure:","op":"replace"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"showAlertWithTitle:content:showCancel:showConfirm:showTextFiled:placeHolder:confirmClosure:cancelClosure:"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"showAlertWithTitle:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"title","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"content:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"content","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"showCancel:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":") "},{"text":"showCancel","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"showConfirm:"},{"text":"(","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"text":"showConfirm","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"showTextFiled:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"showTextFiled"},{"text":" ","kind":"text"},{"text":"placeHolder:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"placeHolder","kind":"internalParam"},{"kind":"text","text":" "},{"text":"confirmClosure:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":" (^","kind":"text"},{"text":")(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"kind":"internalParam","text":""},{"text":")) ","kind":"text"},{"kind":"internalParam","text":"confirmClosure"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cancelClosure:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":" (^","kind":"text"},{"text":")()) ","kind":"text"},{"kind":"internalParam","text":"cancelClosure"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/primaryContentSections\/1","op":"replace","value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"The alert title to display.","type":"text"}],"type":"paragraph"}],"name":"title"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The alert content to display.","type":"text"}]}],"name":"content"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Whether to display the "},{"type":"codeVoice","code":"Cancel"},{"text":" button.","type":"text"}]}],"name":"showCancel"},{"name":"showConfirm","content":[{"inlineContent":[{"text":"Whether to display the ","type":"text"},{"code":"Confirm","type":"codeVoice"},{"type":"text","text":" button."}],"type":"paragraph"}]},{"name":"placeHolder","content":[{"inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"TextField"},{"type":"text","text":" placeholder."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"Callback upon a click of the "},{"type":"codeVoice","code":"Confirm"},{"type":"text","text":" button.When text field was shown callback contain input text."}],"type":"paragraph"}],"name":"confirmClosure"}]}},{"value":"DialogManager","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1DialogManager\/title","op":"replace"},{"value":[{"text":"DialogManager","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1DialogManager\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1DialogManager\/navigatorTitle","value":[{"text":"DialogManager","kind":"identifier"}]},{"value":"showAlertWithTitle:content:showCancel:showConfirm:showTextFiled:placeHolder:confirmClosure:cancelClosure:","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1DialogManager~1showAlert(title:content:showCancel:showConfirm:showTextFiled:placeHolder:confirmClosure:cancelClosure:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1DialogManager~1showAlert(title:content:showCancel:showConfirm:showTextFiled:placeHolder:confirmClosure:cancelClosure:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"showAlertWithTitle:content:showCancel:showConfirm:showTextFiled:placeHolder:confirmClosure:cancelClosure:"}],"op":"replace"}]}]}