{"kind":"symbol","metadata":{"externalID":"c:@M@ShengwangChatUIKit@objc(pl)ActionSheetItemProtocol(py)image","role":"symbol","roleHeading":"Instance Property","title":"image","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"image","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"image","kind":"identifier"}],"modules":[{"name":"ShengwangChatUIKit"}],"symbolKind":"property","required":true},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ActionSheetItemProtocol\/image"},"abstract":[{"type":"text","text":"The image of the action sheet item."}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"image"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"},{"kind":"text","text":"? { "},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/actionsheetitemprotocol\/image"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/actionsheetitemprotocol\/image"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ActionSheetItemProtocol"]]},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ActionSheetItemProtocol":{"navigatorTitle":[{"text":"ActionSheetItemProtocol","kind":"identifier"}],"abstract":[{"type":"text","text":"A protocol that defines properties and methods for an action sheet item."}],"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ActionSheetItemProtocol"}],"url":"\/documentation\/shengwangchatuikit\/actionsheetitemprotocol","role":"symbol","title":"ActionSheetItemProtocol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ActionSheetItemProtocol","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ActionSheetItemProtocol/image":{"type":"topic","title":"image","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ActionSheetItemProtocol\/image","abstract":[{"type":"text","text":"The image of the action sheet item."}],"url":"\/documentation\/shengwangchatuikit\/actionsheetitemprotocol\/image","kind":"symbol","required":true,"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"image","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"image"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"image"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"image","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"text":") ","kind":"text"},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"text":" * ","kind":"text"},{"text":"image","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}},{"op":"replace","value":"ActionSheetItemProtocol","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ActionSheetItemProtocol\/title"},{"value":[{"text":"ActionSheetItemProtocol","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ActionSheetItemProtocol\/fragments"},{"value":[{"kind":"identifier","text":"ActionSheetItemProtocol"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ActionSheetItemProtocol\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ActionSheetItemProtocol~1image\/title","value":"image","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ActionSheetItemProtocol~1image\/fragments","value":[{"kind":"identifier","text":"image"}],"op":"replace"}]}]}