{"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationService\/bindConversationEventsListener(listener:)","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bindConversationEventsListener"},{"text":"(","kind":"text"},{"text":"listener","kind":"externalParam"},{"kind":"text","text":": "},{"text":"ConversationServiceListener","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(pl)ConversationServiceListener","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationServiceListener"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":""},{"code":"ChannelServiceListener","type":"codeVoice"}],"type":"paragraph"}],"name":"listener"}]}],"abstract":[{"text":"Bind channel changed listener","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/conversationservice\/bindconversationeventslistener(listener:)"]},{"paths":["\/documentation\/shengwangchatuikit\/conversationservice\/bindconversationeventslistener(listener:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"externalID":"c:@M@ShengwangChatUIKit@objc(pl)ConversationService(im)bindConversationEventsListenerWithListener:","navigatorTitle":[{"kind":"identifier","text":"bindConversationEventsListenerWithListener:"}],"role":"symbol","required":true,"modules":[{"name":"ShengwangChatUIKit"}],"title":"bindConversationEventsListener(listener:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"bindConversationEventsListener"},{"kind":"text","text":"("},{"kind":"externalParam","text":"listener"},{"kind":"text","text":": "},{"text":"ConversationServiceListener","kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(pl)ConversationServiceListener"},{"kind":"text","text":")"}],"roleHeading":"Instance Method","symbolKind":"method"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationService"]]},"sections":[],"kind":"symbol","references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ConversationService/bindConversationEventsListener(listener:)":{"url":"\/documentation\/shengwangchatuikit\/conversationservice\/bindconversationeventslistener(listener:)","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationService\/bindConversationEventsListener(listener:)","type":"topic","navigatorTitle":[{"kind":"identifier","text":"bindConversationEventsListenerWithListener:"}],"role":"symbol","abstract":[{"text":"Bind channel changed listener","type":"text"}],"required":true,"title":"bindConversationEventsListener(listener:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"bindConversationEventsListener"},{"kind":"text","text":"("},{"kind":"externalParam","text":"listener"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(pl)ConversationServiceListener","text":"ConversationServiceListener"},{"kind":"text","text":")"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ConversationService":{"kind":"symbol","url":"\/documentation\/shengwangchatuikit\/conversationservice","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationService","navigatorTitle":[{"text":"ConversationService","kind":"identifier"}],"type":"topic","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"ConversationService","kind":"identifier"}],"title":"ConversationService"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ConversationServiceListener":{"url":"\/documentation\/shengwangchatuikit\/conversationservicelistener","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"ConversationServiceListener","kind":"identifier"}],"abstract":[],"title":"ConversationServiceListener","type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationServiceListener","role":"symbol","navigatorTitle":[{"text":"ConversationServiceListener","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"bindConversationEventsListenerWithListener:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"bindConversationEventsListenerWithListener:"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"bindConversationEventsListenerWithListener:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Qo@M@ShengwangChatUIKit@objc(pl)ConversationServiceListener","kind":"typeIdentifier","text":"id<ConversationServiceListener>"},{"kind":"text","text":") "},{"text":"listener","kind":"internalParam"},{"text":";","kind":"text"}]}]},"op":"replace"},{"value":{"parameters":[{"name":"listener","content":[{"inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"ChannelServiceListener"}],"type":"paragraph"}]}],"kind":"parameters"},"path":"\/primaryContentSections\/1","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationService~1bindConversationEventsListener(listener:)\/title","op":"replace","value":"bindConversationEventsListenerWithListener:"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationService~1bindConversationEventsListener(listener:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"bindConversationEventsListenerWithListener:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationService\/title","value":"ConversationService","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationService\/fragments","value":[{"text":"ConversationService","kind":"identifier"}]},{"op":"replace","value":[{"text":"ConversationService","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationService\/navigatorTitle"},{"value":"ConversationServiceListener","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationServiceListener\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationServiceListener\/fragments","value":[{"text":"ConversationServiceListener","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationServiceListener\/navigatorTitle","op":"replace","value":[{"text":"ConversationServiceListener","kind":"identifier"}]}]}]}