{"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/AudioTools\/audioPlayerDidFinishPlaying(_:successfully:)","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"audioPlayerDidFinishPlaying","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"player","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)AVAudioPlayer","text":"AVAudioPlayer","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"successfully"},{"text":" ","kind":"text"},{"text":"flag","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":")","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/AudioTools","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/AudioTools\/AVAudioPlayerDelegate-Implementations"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"audioPlayerDidFinishPlaying:successfully:"}],"extendedModule":"ShengwangChatUIKit","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"audioPlayerDidFinishPlaying","kind":"identifier"},{"text":"(","kind":"text"},{"text":"AVAudioPlayer","preciseIdentifier":"c:objc(cs)AVAudioPlayer","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"successfully"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":")"}],"externalID":"c:@CM@ShengwangChatUIKit@objc(cs)AudioTools(im)audioPlayerDidFinishPlaying:successfully:","role":"symbol","roleHeading":"Instance Method","symbolKind":"method","modules":[{"name":"ShengwangChatUIKit"}],"title":"audioPlayerDidFinishPlaying(_:successfully:)"},"variants":[{"paths":["\/documentation\/shengwangchatuikit\/audiotools\/audioplayerdidfinishplaying(_:successfully:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/shengwangchatuikit\/audiotools\/audioplayerdidfinishplaying(_:successfully:)"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"Inherited from ","type":"text"},{"code":"AVAudioPlayerDelegate.audioPlayerDidFinishPlaying(_:successfully:)","type":"codeVoice"},{"text":".","type":"text"}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/AudioTools/AVAudioPlayerDelegate-Implementations":{"kind":"article","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/AudioTools\/AVAudioPlayerDelegate-Implementations","role":"collectionGroup","title":"AVAudioPlayerDelegate Implementations","url":"\/documentation\/shengwangchatuikit\/audiotools\/avaudioplayerdelegate-implementations"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/AudioTools/audioPlayerDidFinishPlaying(_:successfully:)":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/AudioTools\/audioPlayerDidFinishPlaying(_:successfully:)","title":"audioPlayerDidFinishPlaying(_:successfully:)","role":"symbol","url":"\/documentation\/shengwangchatuikit\/audiotools\/audioplayerdidfinishplaying(_:successfully:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"audioPlayerDidFinishPlaying","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)AVAudioPlayer","text":"AVAudioPlayer","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"successfully"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":")"}],"type":"topic","abstract":[],"navigatorTitle":[{"text":"audioPlayerDidFinishPlaying:successfully:","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/AudioTools":{"abstract":[],"kind":"symbol","url":"\/documentation\/shengwangchatuikit\/audiotools","navigatorTitle":[{"text":"AudioTools","kind":"identifier"}],"title":"AudioTools","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/AudioTools","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AudioTools"}],"type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"audioPlayerDidFinishPlaying:successfully:"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"audioPlayerDidFinishPlaying:successfully:","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"audioPlayerDidFinishPlaying:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)AVAudioPlayer","text":"AVAudioPlayer","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"player","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"successfully:"},{"kind":"text","text":"("},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"flag","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"value":"audioPlayerDidFinishPlaying:successfully:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1AudioTools~1audioPlayerDidFinishPlaying(_:successfully:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"audioPlayerDidFinishPlaying:successfully:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1AudioTools~1audioPlayerDidFinishPlaying(_:successfully:)\/fragments"},{"op":"replace","value":"AudioTools","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1AudioTools\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1AudioTools\/fragments","value":[{"kind":"identifier","text":"AudioTools"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1AudioTools\/navigatorTitle","value":[{"kind":"identifier","text":"AudioTools"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}