{"sections":[],"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"AVAudioRecorderDelegate.audioRecorderDidFinishRecording(_:successfully:)"},{"type":"text","text":"."}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/AudioTools\/audioRecorderDidFinishRecording(_:successfully:)"},"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/AudioTools","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/AudioTools\/AVAudioRecorderDelegate-Implementations"]]},"metadata":{"navigatorTitle":[{"text":"audioRecorderDidFinishRecording:successfully:","kind":"identifier"}],"modules":[{"name":"ShengwangChatUIKit"}],"roleHeading":"Instance Method","symbolKind":"method","title":"audioRecorderDidFinishRecording(_:successfully:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"audioRecorderDidFinishRecording","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AVAudioRecorder","text":"AVAudioRecorder"},{"kind":"text","text":", "},{"text":"successfully","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":")"}],"extendedModule":"ShengwangChatUIKit","externalID":"c:@CM@ShengwangChatUIKit@objc(cs)AudioTools(im)audioRecorderDidFinishRecording:successfully:","role":"symbol"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"audioRecorderDidFinishRecording","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"recorder","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AVAudioRecorder","preciseIdentifier":"c:objc(cs)AVAudioRecorder"},{"text":", ","kind":"text"},{"text":"successfully","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"flag","kind":"internalParam"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/shengwangchatuikit\/audiotools\/audiorecorderdidfinishrecording(_:successfully:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/audiotools\/audiorecorderdidfinishrecording(_:successfully:)"]}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/AudioTools/audioRecorderDidFinishRecording(_:successfully:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"audioRecorderDidFinishRecording","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"AVAudioRecorder","preciseIdentifier":"c:objc(cs)AVAudioRecorder"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"successfully"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","role":"symbol","abstract":[],"kind":"symbol","navigatorTitle":[{"text":"audioRecorderDidFinishRecording:successfully:","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/AudioTools\/audioRecorderDidFinishRecording(_:successfully:)","url":"\/documentation\/shengwangchatuikit\/audiotools\/audiorecorderdidfinishrecording(_:successfully:)","title":"audioRecorderDidFinishRecording(_:successfully:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/AudioTools":{"abstract":[],"kind":"symbol","url":"\/documentation\/shengwangchatuikit\/audiotools","navigatorTitle":[{"text":"AudioTools","kind":"identifier"}],"title":"AudioTools","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/AudioTools","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AudioTools"}],"type":"topic"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/AudioTools/AVAudioRecorderDelegate-Implementations":{"type":"topic","role":"collectionGroup","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/AudioTools\/AVAudioRecorderDelegate-Implementations","title":"AVAudioRecorderDelegate Implementations","url":"\/documentation\/shengwangchatuikit\/audiotools\/avaudiorecorderdelegate-implementations","abstract":[],"kind":"article"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"audioRecorderDidFinishRecording:successfully:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"audioRecorderDidFinishRecording:successfully:","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"audioRecorderDidFinishRecording:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"AVAudioRecorder","preciseIdentifier":"c:objc(cs)AVAudioRecorder"},{"text":" *) ","kind":"text"},{"text":"recorder","kind":"internalParam"},{"kind":"text","text":" "},{"text":"successfully:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"flag","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1AudioTools~1audioRecorderDidFinishRecording(_:successfully:)\/title","value":"audioRecorderDidFinishRecording:successfully:"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1AudioTools~1audioRecorderDidFinishRecording(_:successfully:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"audioRecorderDidFinishRecording:successfully:"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1AudioTools\/title","op":"replace","value":"AudioTools"},{"op":"replace","value":[{"text":"AudioTools","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1AudioTools\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1AudioTools\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"AudioTools"}]}]}]}