{"kind":"article","topicSections":[{"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/AudioTools\/audioRecorderDidFinishRecording(_:successfully:)"],"generated":true}],"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/AudioTools\/AVAudioRecorderDelegate-Implementations","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/AudioTools"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"modules":[{"name":"ShengwangChatUIKit"}],"title":"AVAudioRecorderDelegate Implementations","roleHeading":"API Collection","role":"collectionGroup"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/audiotools\/avaudiorecorderdelegate-implementations"]},{"paths":["\/documentation\/shengwangchatuikit\/audiotools\/avaudiorecorderdelegate-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/AudioTools":{"abstract":[],"kind":"symbol","url":"\/documentation\/shengwangchatuikit\/audiotools","navigatorTitle":[{"text":"AudioTools","kind":"identifier"}],"title":"AudioTools","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/AudioTools","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AudioTools"}],"type":"topic"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/AudioTools/audioRecorderDidFinishRecording(_:successfully:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"audioRecorderDidFinishRecording","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"AVAudioRecorder","preciseIdentifier":"c:objc(cs)AVAudioRecorder"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"successfully"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","role":"symbol","abstract":[],"kind":"symbol","navigatorTitle":[{"text":"audioRecorderDidFinishRecording:successfully:","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/AudioTools\/audioRecorderDidFinishRecording(_:successfully:)","url":"\/documentation\/shengwangchatuikit\/audiotools\/audiorecorderdidfinishrecording(_:successfully:)","title":"audioRecorderDidFinishRecording(_:successfully:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/topicSections","value":[{"generated":true,"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/AudioTools\/audioRecorderDidFinishRecording(_:successfully:)"]}]},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1AudioTools\/title","value":"AudioTools"},{"value":[{"text":"AudioTools","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1AudioTools\/fragments","op":"replace"},{"value":[{"text":"AudioTools","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1AudioTools\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1AudioTools~1audioRecorderDidFinishRecording(_:successfully:)\/title","value":"audioRecorderDidFinishRecording:successfully:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1AudioTools~1audioRecorderDidFinishRecording(_:successfully:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"audioRecorderDidFinishRecording:successfully:"}],"op":"replace"}]}]}