{"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"navigatorTitle":[{"text":"canPlayWithUrl:","kind":"identifier"}],"externalID":"c:@M@ShengwangChatUIKit@objc(cs)AudioTools(cm)canPlayWithUrl:","title":"canPlay(url:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"canPlay","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"url"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"modules":[{"name":"ShengwangChatUIKit"}],"symbolKind":"method","role":"symbol","roleHeading":"Type Method"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"canPlay","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"url"},{"text":": ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"platforms":["iOS"],"languages":["swift"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/AudioTools\/canPlay(url:)"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/AudioTools"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/audiotools\/canplay(url:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/audiotools\/canplay(url:)"]}],"kind":"symbol","references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/AudioTools/canPlay(url:)":{"url":"\/documentation\/shengwangchatuikit\/audiotools\/canplay(url:)","navigatorTitle":[{"kind":"identifier","text":"canPlayWithUrl:"}],"kind":"symbol","title":"canPlay(url:)","type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"canPlay"},{"kind":"text","text":"("},{"text":"url","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/AudioTools\/canPlay(url:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/AudioTools":{"abstract":[],"kind":"symbol","url":"\/documentation\/shengwangchatuikit\/audiotools","navigatorTitle":[{"text":"AudioTools","kind":"identifier"}],"title":"AudioTools","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/AudioTools","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AudioTools"}],"type":"topic"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Method"},{"path":"\/metadata\/title","op":"replace","value":"canPlayWithUrl:"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"text":"canPlayWithUrl:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"text":") ","kind":"text"},{"kind":"identifier","text":"canPlayWithUrl:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSURL","kind":"typeIdentifier","text":"NSURL"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"url"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1AudioTools~1canPlay(url:)\/title","value":"canPlayWithUrl:"},{"value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"canPlayWithUrl:"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1AudioTools~1canPlay(url:)\/fragments","op":"replace"},{"value":"AudioTools","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1AudioTools\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1AudioTools\/fragments","value":[{"text":"AudioTools","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"AudioTools"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1AudioTools\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}