{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ComponentViewsActionHooker"]]},"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ComponentViewsActionHooker\/chat","interfaceLanguage":"swift"},"kind":"symbol","variants":[{"paths":["\/documentation\/shengwangchatuikit\/componentviewsactionhooker\/chat"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/componentviewsactionhooker\/chat"]}],"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"chat","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChatHooker","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)ChatHooker","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatHooker"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"roleHeading":"Instance Property","symbolKind":"property","role":"symbol","externalID":"c:@M@ShengwangChatUIKit@objc(cs)ComponentViewsActionHooker(py)chat","modules":[{"name":"ShengwangChatUIKit"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"chat"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)ChatHooker","text":"ChatHooker","kind":"typeIdentifier"}],"title":"chat","navigatorTitle":[{"kind":"identifier","text":"chat"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ComponentViewsActionHooker":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ComponentViewsActionHooker"}],"title":"ComponentViewsActionHooker","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ComponentViewsActionHooker","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ComponentViewsActionHooker"}],"type":"topic","url":"\/documentation\/shengwangchatuikit\/componentviewsactionhooker","abstract":[{"text":"A class that handles action events for various component views in the application.","type":"text"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ComponentViewsActionHooker/chat":{"abstract":[],"title":"chat","type":"topic","role":"symbol","url":"\/documentation\/shengwangchatuikit\/componentviewsactionhooker\/chat","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"chat"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ComponentViewsActionHooker\/chat","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"chat","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)ChatHooker","text":"ChatHooker"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatHooker":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatHooker","navigatorTitle":[{"text":"ChatHooker","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/chathooker","type":"topic","abstract":[{"text":"A class representing a chat component.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatHooker"}],"title":"ChatHooker","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"chat","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"chat"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"ChatHooker","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatHooker","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)ChatHooker","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"kind":"identifier","text":"chat"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}},{"value":"ComponentViewsActionHooker","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ComponentViewsActionHooker\/title"},{"op":"replace","value":[{"text":"ComponentViewsActionHooker","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ComponentViewsActionHooker\/fragments"},{"op":"replace","value":[{"text":"ComponentViewsActionHooker","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ComponentViewsActionHooker\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ComponentViewsActionHooker~1chat\/title","value":"chat"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ComponentViewsActionHooker~1chat\/fragments","op":"replace","value":[{"kind":"identifier","text":"chat"}]},{"value":"ChatHooker","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatHooker\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatHooker\/fragments","value":[{"text":"ChatHooker","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatHooker\/navigatorTitle","value":[{"text":"ChatHooker","kind":"identifier"}]}]}]}