{"metadata":{"modules":[{"name":"ShengwangChatUIKit"}],"fragments":[{"kind":"text","text":"- "},{"text":"init","kind":"identifier"}],"role":"symbol","title":"init","symbolKind":"method","roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"init"}],"externalID":"c:@M@ShengwangChatUIKit@objc(cs)ComponentViewsActionHooker(im)init"},"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ComponentViewsActionHooker\/init","interfaceLanguage":"occ"},"sections":[],"variants":[{"paths":["\/documentation\/shengwangchatuikit\/componentviewsactionhooker\/init"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"kind":"identifier","text":"init"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ComponentViewsActionHooker"]]},"kind":"symbol","references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ComponentViewsActionHooker":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ComponentViewsActionHooker"}],"title":"ComponentViewsActionHooker","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ComponentViewsActionHooker","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ComponentViewsActionHooker"}],"type":"topic","url":"\/documentation\/shengwangchatuikit\/componentviewsactionhooker","abstract":[{"text":"A class that handles action events for various component views in the application.","type":"text"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ComponentViewsActionHooker/init":{"abstract":[],"fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"init"}],"role":"symbol","type":"topic","url":"\/documentation\/shengwangchatuikit\/componentviewsactionhooker\/init","title":"init","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ComponentViewsActionHooker\/init","navigatorTitle":[{"kind":"identifier","text":"init"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"ComponentViewsActionHooker","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ComponentViewsActionHooker\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ComponentViewsActionHooker\/fragments","op":"replace","value":[{"kind":"identifier","text":"ComponentViewsActionHooker"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ComponentViewsActionHooker\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"ComponentViewsActionHooker"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}