{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChoiceItemCell"]]},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChoiceItemCell\/ThemeSwitchProtocol-Implementations","interfaceLanguage":"swift"},"kind":"article","topicSections":[{"generated":true,"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChoiceItemCell\/switchTheme(style:)"],"anchor":"Instance-Methods","title":"Instance Methods"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/choiceitemcell\/themeswitchprotocol-implementations"]},{"paths":["\/documentation\/shengwangchatuikit\/choiceitemcell\/themeswitchprotocol-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"modules":[{"name":"ShengwangChatUIKit"}],"title":"ThemeSwitchProtocol Implementations","role":"collectionGroup","roleHeading":"API Collection"},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChoiceItemCell/switchTheme(style:)":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChoiceItemCell\/switchTheme(style:)","navigatorTitle":[{"kind":"identifier","text":"switchThemeWithStyle:"}],"type":"topic","kind":"symbol","title":"switchTheme(style:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"switchTheme","kind":"identifier"},{"kind":"text","text":"("},{"text":"style","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@E@ThemeStyle","text":"ThemeStyle","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[{"type":"text","text":"When some view Implement the protocol method,you can use "},{"type":"codeVoice","code":"Theme.switchTheme(style: .dark)"},{"type":"text","text":" to switch theme."}],"url":"\/documentation\/shengwangchatuikit\/choiceitemcell\/switchtheme(style:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChoiceItemCell":{"abstract":[],"role":"symbol","title":"ChoiceItemCell","navigatorTitle":[{"text":"ChoiceItemCell","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChoiceItemCell","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/choiceitemcell","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChoiceItemCell","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/topicSections","op":"replace","value":[{"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChoiceItemCell\/switchTheme(style:)"],"anchor":"Instance-Methods","generated":true,"title":"Instance Methods"}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":"switchThemeWithStyle:","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChoiceItemCell~1switchTheme(style:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"switchThemeWithStyle:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChoiceItemCell~1switchTheme(style:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChoiceItemCell\/title","value":"ChoiceItemCell"},{"value":[{"kind":"identifier","text":"ChoiceItemCell"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChoiceItemCell\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChoiceItemCell\/navigatorTitle","value":[{"text":"ChoiceItemCell","kind":"identifier"}]}]}]}