{"kind":"symbol","metadata":{"modules":[{"name":"ShengwangChatUIKit"}],"role":"symbol","title":"bindConversationEventsListener(listener:)","navigatorTitle":[{"text":"bindConversationEventsListenerWithListener:","kind":"identifier"}],"extendedModule":"ShengwangChatUIKit","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"bindConversationEventsListener"},{"kind":"text","text":"("},{"kind":"externalParam","text":"listener"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(pl)ConversationServiceListener","text":"ConversationServiceListener","kind":"typeIdentifier"},{"text":")","kind":"text"}],"roleHeading":"Instance Method","externalID":"c:@CM@ShengwangChatUIKit@objc(cs)ConversationServiceImplement(im)bindConversationEventsListenerWithListener:"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/conversationserviceimplement\/bindconversationeventslistener(listener:)"]},{"paths":["\/documentation\/shengwangchatuikit\/conversationserviceimplement\/bindconversationeventslistener(listener:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationServiceImplement\/bindConversationEventsListener(listener:)"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationServiceImplement","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationServiceImplement\/ConversationService-Implementations"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"abstract":[{"text":"Bind channel changed listener","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bindConversationEventsListener","kind":"identifier"},{"text":"(","kind":"text"},{"text":"listener","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"ConversationServiceListener","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationServiceListener","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(pl)ConversationServiceListener"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"parameters":[{"name":"listener","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"code":"ChannelServiceListener","type":"codeVoice"}]}]}],"kind":"parameters"}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ConversationServiceListener":{"url":"\/documentation\/shengwangchatuikit\/conversationservicelistener","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"ConversationServiceListener","kind":"identifier"}],"abstract":[],"title":"ConversationServiceListener","type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationServiceListener","role":"symbol","navigatorTitle":[{"text":"ConversationServiceListener","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ConversationServiceImplement/bindConversationEventsListener(listener:)":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationServiceImplement\/bindConversationEventsListener(listener:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bindConversationEventsListener"},{"kind":"text","text":"("},{"text":"listener","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(pl)ConversationServiceListener","kind":"typeIdentifier","text":"ConversationServiceListener"},{"text":")","kind":"text"}],"kind":"symbol","url":"\/documentation\/shengwangchatuikit\/conversationserviceimplement\/bindconversationeventslistener(listener:)","title":"bindConversationEventsListener(listener:)","role":"symbol","abstract":[{"text":"Bind channel changed listener","type":"text"}],"navigatorTitle":[{"text":"bindConversationEventsListenerWithListener:","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ConversationServiceImplement/ConversationService-Implementations":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationServiceImplement\/ConversationService-Implementations","abstract":[],"role":"collectionGroup","type":"topic","url":"\/documentation\/shengwangchatuikit\/conversationserviceimplement\/conversationservice-implementations","title":"ConversationService Implementations","kind":"article"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ConversationServiceImplement":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationServiceImplement","navigatorTitle":[{"text":"ConversationServiceImplement","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/conversationserviceimplement","type":"topic","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ConversationServiceImplement"}],"title":"ConversationServiceImplement","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","value":"bindConversationEventsListenerWithListener:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"bindConversationEventsListenerWithListener:"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"bindConversationEventsListenerWithListener:"},{"text":"(","kind":"text"},{"text":"id<ConversationServiceListener>","preciseIdentifier":"c:Qo@M@ShengwangChatUIKit@objc(pl)ConversationServiceListener","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"listener","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"ConversationServiceListener","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationServiceListener\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationServiceListener\/fragments","value":[{"text":"ConversationServiceListener","kind":"identifier"}]},{"value":[{"text":"ConversationServiceListener","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationServiceListener\/navigatorTitle"},{"value":"bindConversationEventsListenerWithListener:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationServiceImplement~1bindConversationEventsListener(listener:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationServiceImplement~1bindConversationEventsListener(listener:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"bindConversationEventsListenerWithListener:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationServiceImplement\/title","value":"ConversationServiceImplement","op":"replace"},{"value":[{"kind":"identifier","text":"ConversationServiceImplement"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationServiceImplement\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationServiceImplement\/navigatorTitle","value":[{"text":"ConversationServiceImplement","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}