{"kind":"article","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationServiceImplement\/ConversationService-Implementations"},"topicSections":[{"generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationServiceImplement\/bindConversationEventsListener(listener:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationServiceImplement\/clearSilentMode(conversationId:completion:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationServiceImplement\/deleteConversation(conversationId:completion:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationServiceImplement\/fetchAllConversations(completion:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationServiceImplement\/fetchPinnedConversations(cursor:pageSize:completion:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationServiceImplement\/fetchSilentMode(conversationIds:completion:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationServiceImplement\/loadExistConversations()","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationServiceImplement\/loadIfNotExistCreate(conversationId:type:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationServiceImplement\/markAllMessagesAsRead(conversationId:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationServiceImplement\/pin(conversationId:completion:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationServiceImplement\/registerEmergencyListener(listener:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationServiceImplement\/setSilentMode(conversationId:completion:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationServiceImplement\/unbindConversationEventsListener(listener:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationServiceImplement\/unpin(conversationId:completion:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationServiceImplement\/unregisterEmergencyListener(listener:)"],"title":"Instance Methods"}],"sections":[],"variants":[{"paths":["\/documentation\/shengwangchatuikit\/conversationserviceimplement\/conversationservice-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/conversationserviceimplement\/conversationservice-implementations"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationServiceImplement"]]},"metadata":{"modules":[{"name":"ShengwangChatUIKit"}],"roleHeading":"API Collection","role":"collectionGroup","title":"ConversationService Implementations"},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ConversationServiceImplement/markAllMessagesAsRead(conversationId:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"markAllMessagesAsRead","kind":"identifier"},{"kind":"text","text":"("},{"text":"conversationId","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":")","kind":"text"}],"type":"topic","role":"symbol","abstract":[{"text":"Mark all of the history messages as already read.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"markAllMessagesAsReadWithConversationId:","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationServiceImplement\/markAllMessagesAsRead(conversationId:)","url":"\/documentation\/shengwangchatuikit\/conversationserviceimplement\/markallmessagesasread(conversationid:)","title":"markAllMessagesAsRead(conversationId:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ConversationServiceImplement/unregisterEmergencyListener(listener:)":{"navigatorTitle":[{"text":"unregisterEmergencyListenerWithListener:","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationServiceImplement\/unregisterEmergencyListener(listener:)","title":"unregisterEmergencyListener(listener:)","role":"symbol","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"unregisterEmergencyListener"},{"kind":"text","text":"("},{"text":"listener","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(pl)ConversationEmergencyListener","kind":"typeIdentifier","text":"ConversationEmergencyListener"},{"kind":"text","text":")"}],"type":"topic","abstract":[{"text":"Unregister emergency listener","type":"text"}],"url":"\/documentation\/shengwangchatuikit\/conversationserviceimplement\/unregisteremergencylistener(listener:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ConversationServiceImplement/unbindConversationEventsListener(listener:)":{"abstract":[{"type":"text","text":"Unbind channel changed listener"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"unbindConversationEventsListener","kind":"identifier"},{"kind":"text","text":"("},{"text":"listener","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(pl)ConversationServiceListener","text":"ConversationServiceListener","kind":"typeIdentifier"},{"kind":"text","text":")"}],"role":"symbol","type":"topic","url":"\/documentation\/shengwangchatuikit\/conversationserviceimplement\/unbindconversationeventslistener(listener:)","title":"unbindConversationEventsListener(listener:)","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationServiceImplement\/unbindConversationEventsListener(listener:)","navigatorTitle":[{"kind":"identifier","text":"unbindConversationEventsListenerWithListener:"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ConversationServiceImplement/clearSilentMode(conversationId:completion:)":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationServiceImplement\/clearSilentMode(conversationId:completion:)","abstract":[{"type":"text","text":"Clear the quiesce status of a session"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"clearSilentMode"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"conversationId"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit16SilentModeResulta","text":"SilentModeResult"},{"text":"?, ","kind":"text"},{"text":"ChatError","kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit0B5Errora"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"type":"topic","url":"\/documentation\/shengwangchatuikit\/conversationserviceimplement\/clearsilentmode(conversationid:completion:)","title":"clearSilentMode(conversationId:completion:)","navigatorTitle":[{"text":"clearSilentModeWithConversationId:completion:","kind":"identifier"}],"kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ConversationServiceImplement/fetchPinnedConversations(cursor:pageSize:completion:)":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationServiceImplement\/fetchPinnedConversations(cursor:pageSize:completion:)","navigatorTitle":[{"text":"fetchPinnedConversationsWithCursor:pageSize:completion:","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/conversationserviceimplement\/fetchpinnedconversations(cursor:pagesize:completion:)","type":"topic","abstract":[{"text":"Fetch pinned conversations from server.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"fetchPinnedConversations","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"cursor"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"pageSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5UInt8V","text":"UInt8"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"CursorResult","kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit12CursorResulta"},{"text":"<","kind":"text"},{"text":"ConversationInfo","kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)ConversationInfo"},{"kind":"text","text":">?, "},{"text":"ChatError","kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit0B5Errora"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"title":"fetchPinnedConversations(cursor:pageSize:completion:)","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ConversationServiceImplement/pin(conversationId:completion:)":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"pinWithConversationId:completion:"}],"title":"pin(conversationId:completion:)","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationServiceImplement\/pin(conversationId:completion:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"pin","kind":"identifier"},{"kind":"text","text":"("},{"text":"conversationId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit0B5Errora","text":"ChatError"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"type":"topic","url":"\/documentation\/shengwangchatuikit\/conversationserviceimplement\/pin(conversationid:completion:)","abstract":[{"text":"Pin a conversation to the top","type":"text"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ConversationServiceImplement/loadExistConversations()":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationServiceImplement\/loadExistConversations()","navigatorTitle":[{"kind":"identifier","text":"loadExistConversations"}],"url":"\/documentation\/shengwangchatuikit\/conversationserviceimplement\/loadexistconversations()","type":"topic","abstract":[{"type":"text","text":"Get all conversations from database."}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"loadExistConversations"},{"text":"()","kind":"text"}],"title":"loadExistConversations()","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ConversationServiceImplement/fetchSilentMode(conversationIds:completion:)":{"kind":"symbol","url":"\/documentation\/shengwangchatuikit\/conversationserviceimplement\/fetchsilentmode(conversationids:completion:)","role":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"fetchSilentMode","kind":"identifier"},{"text":"(","kind":"text"},{"text":"conversationIds","kind":"externalParam"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"], "},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","preciseIdentifier":"s:SD","text":"Dictionary"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"text":"SilentModeResult","kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit16SilentModeResulta"},{"text":">?, ","kind":"text"},{"text":"ChatError","preciseIdentifier":"s:18ShengwangChatUIKit0B5Errora","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationServiceImplement\/fetchSilentMode(conversationIds:completion:)","title":"fetchSilentMode(conversationIds:completion:)","navigatorTitle":[{"kind":"identifier","text":"fetchSilentModeWithConversationIds:completion:"}],"abstract":[{"type":"text","text":"Get the session where the server is set to silent state"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ConversationServiceImplement":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationServiceImplement","navigatorTitle":[{"text":"ConversationServiceImplement","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/conversationserviceimplement","type":"topic","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ConversationServiceImplement"}],"title":"ConversationServiceImplement","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ConversationServiceImplement/unpin(conversationId:completion:)":{"url":"\/documentation\/shengwangchatuikit\/conversationserviceimplement\/unpin(conversationid:completion:)","title":"unpin(conversationId:completion:)","role":"symbol","navigatorTitle":[{"text":"unpinWithConversationId:completion:","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationServiceImplement\/unpin(conversationId:completion:)","abstract":[{"type":"text","text":"Unpin a conversation."}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"unpin"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"conversationId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"text":": (","kind":"text"},{"preciseIdentifier":"s:18ShengwangChatUIKit0B5Errora","kind":"typeIdentifier","text":"ChatError"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ConversationServiceImplement/deleteConversation(conversationId:completion:)":{"url":"\/documentation\/shengwangchatuikit\/conversationserviceimplement\/deleteconversation(conversationid:completion:)","abstract":[{"type":"text","text":"Delete a conversation exist in db&server."}],"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationServiceImplement\/deleteConversation(conversationId:completion:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"deleteConversation","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"conversationId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit0B5Errora","text":"ChatError"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"deleteConversationWithConversationId:completion:","kind":"identifier"}],"role":"symbol","title":"deleteConversation(conversationId:completion:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ConversationServiceImplement/loadIfNotExistCreate(conversationId:type:)":{"abstract":[{"type":"text","text":"Load a session and create one if it does not exist"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"loadIfNotExistCreate","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"conversationId"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"type","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ChatConversationType","kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit0B16ConversationTypea"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit0B12Conversationa","text":"ChatConversation"},{"text":"?","kind":"text"}],"role":"symbol","type":"topic","url":"\/documentation\/shengwangchatuikit\/conversationserviceimplement\/loadifnotexistcreate(conversationid:type:)","title":"loadIfNotExistCreate(conversationId:type:)","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationServiceImplement\/loadIfNotExistCreate(conversationId:type:)","navigatorTitle":[{"text":"loadIfNotExistCreateWithConversationId:type:","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ConversationServiceImplement/fetchAllConversations(completion:)":{"navigatorTitle":[{"text":"fetchAllConversationsWithCompletion:","kind":"identifier"}],"abstract":[{"text":"Fetch conversations from server.","type":"text"}],"role":"symbol","kind":"symbol","type":"topic","title":"fetchAllConversations(completion:)","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationServiceImplement\/fetchAllConversations(completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fetchAllConversations"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": ((","kind":"text"},{"text":"CursorResult","kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit12CursorResulta"},{"text":"<","kind":"text"},{"text":"ConversationInfo","kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)ConversationInfo"},{"kind":"text","text":">?, "},{"preciseIdentifier":"s:18ShengwangChatUIKit0B5Errora","text":"ChatError","kind":"typeIdentifier"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"text":")?)","kind":"text"}],"url":"\/documentation\/shengwangchatuikit\/conversationserviceimplement\/fetchallconversations(completion:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ConversationServiceImplement/bindConversationEventsListener(listener:)":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationServiceImplement\/bindConversationEventsListener(listener:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bindConversationEventsListener"},{"kind":"text","text":"("},{"text":"listener","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(pl)ConversationServiceListener","kind":"typeIdentifier","text":"ConversationServiceListener"},{"text":")","kind":"text"}],"kind":"symbol","url":"\/documentation\/shengwangchatuikit\/conversationserviceimplement\/bindconversationeventslistener(listener:)","title":"bindConversationEventsListener(listener:)","role":"symbol","abstract":[{"text":"Bind channel changed listener","type":"text"}],"navigatorTitle":[{"text":"bindConversationEventsListenerWithListener:","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ConversationServiceImplement/setSilentMode(conversationId:completion:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"setSilentMode","kind":"identifier"},{"kind":"text","text":"("},{"text":"conversationId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"kind":"typeIdentifier","text":"SilentModeResult","preciseIdentifier":"s:18ShengwangChatUIKit16SilentModeResulta"},{"text":"?, ","kind":"text"},{"preciseIdentifier":"s:18ShengwangChatUIKit0B5Errora","text":"ChatError","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","role":"symbol","abstract":[{"text":"Set a session to silent state","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"setSilentModeWithConversationId:completion:","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationServiceImplement\/setSilentMode(conversationId:completion:)","url":"\/documentation\/shengwangchatuikit\/conversationserviceimplement\/setsilentmode(conversationid:completion:)","title":"setSilentMode(conversationId:completion:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ConversationServiceImplement/registerEmergencyListener(listener:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"registerEmergencyListener","kind":"identifier"},{"kind":"text","text":"("},{"text":"listener","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(pl)ConversationEmergencyListener","text":"ConversationEmergencyListener","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"registerEmergencyListenerWithListener:"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationServiceImplement\/registerEmergencyListener(listener:)","url":"\/documentation\/shengwangchatuikit\/conversationserviceimplement\/registeremergencylistener(listener:)","role":"symbol","title":"registerEmergencyListener(listener:)","kind":"symbol","abstract":[{"type":"text","text":"Register emergency listener"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationServiceImplement\/bindConversationEventsListener(listener:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationServiceImplement\/clearSilentMode(conversationId:completion:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationServiceImplement\/deleteConversation(conversationId:completion:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationServiceImplement\/fetchAllConversations(completion:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationServiceImplement\/fetchPinnedConversations(cursor:pageSize:completion:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationServiceImplement\/fetchSilentMode(conversationIds:completion:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationServiceImplement\/loadExistConversations()","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationServiceImplement\/loadIfNotExistCreate(conversationId:type:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationServiceImplement\/markAllMessagesAsRead(conversationId:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationServiceImplement\/pin(conversationId:completion:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationServiceImplement\/registerEmergencyListener(listener:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationServiceImplement\/setSilentMode(conversationId:completion:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationServiceImplement\/unbindConversationEventsListener(listener:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationServiceImplement\/unpin(conversationId:completion:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationServiceImplement\/unregisterEmergencyListener(listener:)"],"generated":true,"title":"Instance Methods","anchor":"Instance-Methods"}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":"markAllMessagesAsReadWithConversationId:","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationServiceImplement~1markAllMessagesAsRead(conversationId:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationServiceImplement~1markAllMessagesAsRead(conversationId:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"markAllMessagesAsReadWithConversationId:","kind":"identifier"}]},{"value":"unregisterEmergencyListenerWithListener:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationServiceImplement~1unregisterEmergencyListener(listener:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationServiceImplement~1unregisterEmergencyListener(listener:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"unregisterEmergencyListenerWithListener:","kind":"identifier"}]},{"value":"unbindConversationEventsListenerWithListener:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationServiceImplement~1unbindConversationEventsListener(listener:)\/title"},{"value":[{"kind":"text","text":"- "},{"text":"unbindConversationEventsListenerWithListener:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationServiceImplement~1unbindConversationEventsListener(listener:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationServiceImplement~1clearSilentMode(conversationId:completion:)\/title","value":"clearSilentModeWithConversationId:completion:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationServiceImplement~1clearSilentMode(conversationId:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"clearSilentModeWithConversationId:completion:"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationServiceImplement~1fetchPinnedConversations(cursor:pageSize:completion:)\/title","value":"fetchPinnedConversationsWithCursor:pageSize:completion:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"fetchPinnedConversationsWithCursor:pageSize:completion:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationServiceImplement~1fetchPinnedConversations(cursor:pageSize:completion:)\/fragments"},{"value":"pinWithConversationId:completion:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationServiceImplement~1pin(conversationId:completion:)\/title"},{"value":[{"kind":"text","text":"- "},{"text":"pinWithConversationId:completion:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationServiceImplement~1pin(conversationId:completion:)\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationServiceImplement~1loadExistConversations()\/title","value":"loadExistConversations","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"loadExistConversations"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationServiceImplement~1loadExistConversations()\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationServiceImplement~1fetchSilentMode(conversationIds:completion:)\/title","value":"fetchSilentModeWithConversationIds:completion:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationServiceImplement~1fetchSilentMode(conversationIds:completion:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"fetchSilentModeWithConversationIds:completion:"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationServiceImplement\/title","value":"ConversationServiceImplement","op":"replace"},{"value":[{"kind":"identifier","text":"ConversationServiceImplement"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationServiceImplement\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationServiceImplement\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"ConversationServiceImplement"}]},{"op":"replace","value":"unpinWithConversationId:completion:","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationServiceImplement~1unpin(conversationId:completion:)\/title"},{"value":[{"kind":"text","text":"- "},{"text":"unpinWithConversationId:completion:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationServiceImplement~1unpin(conversationId:completion:)\/fragments","op":"replace"},{"value":"deleteConversationWithConversationId:completion:","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationServiceImplement~1deleteConversation(conversationId:completion:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"deleteConversationWithConversationId:completion:"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationServiceImplement~1deleteConversation(conversationId:completion:)\/fragments","op":"replace"},{"value":"loadIfNotExistCreateWithConversationId:type:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationServiceImplement~1loadIfNotExistCreate(conversationId:type:)\/title"},{"value":[{"kind":"text","text":"- "},{"text":"loadIfNotExistCreateWithConversationId:type:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationServiceImplement~1loadIfNotExistCreate(conversationId:type:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationServiceImplement~1fetchAllConversations(completion:)\/title","value":"fetchAllConversationsWithCompletion:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"fetchAllConversationsWithCompletion:"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationServiceImplement~1fetchAllConversations(completion:)\/fragments"},{"value":"bindConversationEventsListenerWithListener:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationServiceImplement~1bindConversationEventsListener(listener:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"bindConversationEventsListenerWithListener:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationServiceImplement~1bindConversationEventsListener(listener:)\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationServiceImplement~1setSilentMode(conversationId:completion:)\/title","op":"replace","value":"setSilentModeWithConversationId:completion:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"setSilentModeWithConversationId:completion:"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationServiceImplement~1setSilentMode(conversationId:completion:)\/fragments"},{"op":"replace","value":"registerEmergencyListenerWithListener:","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationServiceImplement~1registerEmergencyListener(listener:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationServiceImplement~1registerEmergencyListener(listener:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"registerEmergencyListenerWithListener:","kind":"identifier"}]}]}]}