{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"loadIfNotExistCreate","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"conversationId"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"type","kind":"externalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatConversationType","preciseIdentifier":"s:18ShengwangChatUIKit0B16ConversationTypea","text":"ChatConversationType","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatConversation","text":"ChatConversation","preciseIdentifier":"s:18ShengwangChatUIKit0B12Conversationa"},{"text":"?","kind":"text"}]}],"kind":"declarations"},{"parameters":[{"name":"conversationId","content":[{"inlineContent":[{"type":"text","text":"The ID of the conversation."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"The ","type":"text"},{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatConversationType","isActive":true,"type":"reference"},{"text":" of the conversation.","type":"text"}]}],"name":"type"}],"kind":"parameters"}],"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationServiceImplement\/loadIfNotExistCreate(conversationId:type:)","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Instance Method","role":"symbol","navigatorTitle":[{"text":"loadIfNotExistCreateWithConversationId:type:","kind":"identifier"}],"extendedModule":"ShengwangChatUIKit","externalID":"c:@CM@ShengwangChatUIKit@objc(cs)ConversationServiceImplement(im)loadIfNotExistCreateWithConversationId:type:","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"loadIfNotExistCreate"},{"kind":"text","text":"("},{"text":"conversationId","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"type"},{"kind":"text","text":": "},{"preciseIdentifier":"s:18ShengwangChatUIKit0B16ConversationTypea","text":"ChatConversationType","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"ChatConversation","preciseIdentifier":"s:18ShengwangChatUIKit0B12Conversationa","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"title":"loadIfNotExistCreate(conversationId:type:)","modules":[{"name":"ShengwangChatUIKit"}]},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationServiceImplement","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationServiceImplement\/ConversationService-Implementations"]]},"sections":[],"abstract":[{"type":"text","text":"Load a session and create one if it does not exist"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/conversationserviceimplement\/loadifnotexistcreate(conversationid:type:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/conversationserviceimplement\/loadifnotexistcreate(conversationid:type:)"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ConversationServiceImplement/loadIfNotExistCreate(conversationId:type:)":{"abstract":[{"type":"text","text":"Load a session and create one if it does not exist"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"loadIfNotExistCreate","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"conversationId"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"type","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ChatConversationType","kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit0B16ConversationTypea"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit0B12Conversationa","text":"ChatConversation"},{"text":"?","kind":"text"}],"role":"symbol","type":"topic","url":"\/documentation\/shengwangchatuikit\/conversationserviceimplement\/loadifnotexistcreate(conversationid:type:)","title":"loadIfNotExistCreate(conversationId:type:)","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationServiceImplement\/loadIfNotExistCreate(conversationId:type:)","navigatorTitle":[{"text":"loadIfNotExistCreateWithConversationId:type:","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ConversationServiceImplement":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationServiceImplement","navigatorTitle":[{"text":"ConversationServiceImplement","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/conversationserviceimplement","type":"topic","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ConversationServiceImplement"}],"title":"ConversationServiceImplement","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatConversationType":{"type":"topic","role":"symbol","title":"ChatConversationType","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatConversationType","abstract":[],"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatConversationType"}],"url":"\/documentation\/shengwangchatuikit\/chatconversationtype","kind":"symbol","navigatorTitle":[{"text":"ChatConversationType","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatConversation":{"navigatorTitle":[{"text":"ChatConversation","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/chatconversation","type":"topic","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChatConversation","kind":"identifier"}],"role":"symbol","title":"ChatConversation","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatConversation","kind":"symbol","abstract":[]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ConversationServiceImplement/ConversationService-Implementations":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationServiceImplement\/ConversationService-Implementations","abstract":[],"role":"collectionGroup","type":"topic","url":"\/documentation\/shengwangchatuikit\/conversationserviceimplement\/conversationservice-implementations","title":"ConversationService Implementations","kind":"article"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"loadIfNotExistCreateWithConversationId:type:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"loadIfNotExistCreateWithConversationId:type:","kind":"identifier"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:objc(cs)AgoraChatConversation","kind":"typeIdentifier","text":"AgoraChatConversation"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"loadIfNotExistCreateWithConversationId:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"conversationId","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"type:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@AgoraChatConversationType","text":"AgoraChatConversationType"},{"kind":"text","text":") "},{"text":"type","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationServiceImplement~1loadIfNotExistCreate(conversationId:type:)\/title","op":"replace","value":"loadIfNotExistCreateWithConversationId:type:"},{"value":[{"kind":"text","text":"- "},{"text":"loadIfNotExistCreateWithConversationId:type:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationServiceImplement~1loadIfNotExistCreate(conversationId:type:)\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationServiceImplement\/title","value":"ConversationServiceImplement"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationServiceImplement\/fragments","op":"replace","value":[{"text":"ConversationServiceImplement","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"ConversationServiceImplement"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationServiceImplement\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}