{"relationshipsSections":[{"type":"inheritsFrom","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(cs)UITableViewCell"],"title":"Inherits From","kind":"relationships"},{"type":"conformsTo","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)NSCoding","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)NSObject","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)CALayerDelegate","doc:\/\/org.cocoapods.ShengwangChatUIKit\/s7CVarArgP","doc:\/\/org.cocoapods.ShengwangChatUIKit\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.ShengwangChatUIKit\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.ShengwangChatUIKit\/SQ","doc:\/\/org.cocoapods.ShengwangChatUIKit\/SH","doc:\/\/org.cocoapods.ShengwangChatUIKit\/s8SendableP","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIAccessibilityIdentification","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIAppearance","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIAppearanceContainer","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UICoordinateSpace","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIDynamicItem","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIFocusEnvironment","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIFocusItem","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIFocusItemContainer","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIGestureRecognizerDelegate","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UILargeContentViewerItem","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIResponderStandardEditActions","doc:\/\/org.cocoapods.ShengwangChatUIKit\/5UIKit23UITraitChangeObservableP","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UITraitEnvironment","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"@","kind":"attribute"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ActionSheetCell","kind":"identifier"}],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/shengwangchatuikit\/actionsheetcell"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/actionsheetcell"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit"]]},"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ActionSheetCell","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"metadata":{"roleHeading":"Class","modules":[{"name":"ShengwangChatUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"ActionSheetCell"}],"externalID":"c:@M@ShengwangChatUIKit@objc(cs)ActionSheetCell","symbolKind":"class","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ActionSheetCell","kind":"identifier"}],"title":"ActionSheetCell","role":"symbol"},"references":{"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UIFocusItemContainer":{"title":"UIKit.UIFocusItemContainer","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIFocusItemContainer"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UIFocusItem":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIFocusItem","title":"UIKit.UIFocusItem","type":"unresolvable"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ActionSheetCell/initWithCoder:":{"navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"fragments":[{"kind":"text","text":"- "},{"text":"initWithCoder:","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/actionsheetcell\/initwithcoder:","abstract":[],"role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ActionSheetCell\/initWithCoder:","title":"initWithCoder:","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UIPopoverPresentationControllerSourceItem":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIPopoverPresentationControllerSourceItem","title":"UIKit.UIPopoverPresentationControllerSourceItem","type":"unresolvable"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UIUserActivityRestoring":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIUserActivityRestoring","title":"UIKit.UIUserActivityRestoring","type":"unresolvable"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UIAppearanceContainer":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIAppearanceContainer","title":"UIKit.UIAppearanceContainer","type":"unresolvable"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UIResponderStandardEditActions":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIResponderStandardEditActions","title":"UIKit.UIResponderStandardEditActions","type":"unresolvable"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UIAccessibilityIdentification":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIAccessibilityIdentification","title":"UIKit.UIAccessibilityIdentification","type":"unresolvable"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UIDynamicItem":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIDynamicItem","title":"UIKit.UIDynamicItem","type":"unresolvable"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UITraitEnvironment":{"title":"UIKit.UITraitEnvironment","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UITraitEnvironment"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UIActivityItemsConfigurationProviding":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIActivityItemsConfigurationProviding","title":"UIKit.UIActivityItemsConfigurationProviding","type":"unresolvable"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)CALayerDelegate":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)CALayerDelegate","title":"QuartzCore.CALayerDelegate","type":"unresolvable"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UIAppearance":{"title":"UIKit.UIAppearance","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIAppearance"},"doc://org.cocoapods.ShengwangChatUIKit/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/SQ"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UILargeContentViewerItem":{"title":"UIKit.UILargeContentViewerItem","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UILargeContentViewerItem"},"doc://org.cocoapods.ShengwangChatUIKit/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/SH"},"doc://org.cocoapods.ShengwangChatUIKit/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/s28CustomDebugStringConvertibleP"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ActionSheetCell":{"type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ActionSheetCell"}],"url":"\/documentation\/shengwangchatuikit\/actionsheetcell","navigatorTitle":[{"text":"ActionSheetCell","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ActionSheetCell","title":"ActionSheetCell","abstract":[],"role":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)NSObject"},"doc://org.cocoapods.ShengwangChatUIKit/objc(cs)UITableViewCell":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(cs)UITableViewCell","title":"UITableViewCell","type":"unresolvable"},"doc://org.cocoapods.ShengwangChatUIKit/5UIKit23UITraitChangeObservableP":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/5UIKit23UITraitChangeObservableP","title":"UIKit.UITraitChangeObservable","type":"unresolvable"},"doc://org.cocoapods.ShengwangChatUIKit/s7CVarArgP":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UIFocusEnvironment":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIFocusEnvironment","title":"UIKit.UIFocusEnvironment","type":"unresolvable"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UICoordinateSpace":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UICoordinateSpace","title":"UIKit.UICoordinateSpace","type":"unresolvable"},"doc://org.cocoapods.ShengwangChatUIKit/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/s23CustomStringConvertibleP"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ActionSheetCell/initWithStyle:reuseIdentifier:":{"navigatorTitle":[{"kind":"identifier","text":"initWithStyle:reuseIdentifier:"}],"url":"\/documentation\/shengwangchatuikit\/actionsheetcell\/initwithstyle:reuseidentifier:","type":"topic","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithStyle:reuseIdentifier:"}],"role":"symbol","title":"initWithStyle:reuseIdentifier:","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ActionSheetCell\/initWithStyle:reuseIdentifier:","kind":"symbol","abstract":[]},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UIPasteConfigurationSupporting":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIPasteConfigurationSupporting","title":"UIKit.UIPasteConfigurationSupporting","type":"unresolvable"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)NSCoding":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)NSCoding","title":"Foundation.NSCoding","type":"unresolvable"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UIGestureRecognizerDelegate":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIGestureRecognizerDelegate","title":"UIKit.UIGestureRecognizerDelegate","type":"unresolvable"},"doc://org.cocoapods.ShengwangChatUIKit/s8SendableP":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/s8SendableP","title":"Swift.Sendable","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"ActionSheetCell"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"ActionSheetCell","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ActionSheetCell"}],"op":"replace"},{"value":[{"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ActionSheetCell\/initWithCoder:","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ActionSheetCell\/initWithStyle:reuseIdentifier:"],"generated":true}],"op":"add","path":"\/topicSections"},{"value":[{"type":"inheritsFrom","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(cs)UITableViewCell"],"kind":"relationships","title":"Inherits From"}],"op":"replace","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ActionSheetCell","kind":"identifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITableViewCell","text":"UITableViewCell"}]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ActionSheetCell\/title","value":"ActionSheetCell"},{"value":[{"text":"ActionSheetCell","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ActionSheetCell\/fragments"},{"value":[{"text":"ActionSheetCell","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ActionSheetCell\/navigatorTitle"}]}]}