{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"BlockContactsViewController","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/shengwangchatuikit\/blockcontactsviewcontroller"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/shengwangchatuikit\/blockcontactsviewcontroller"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/BlockContactsViewController"},"topicSections":[{"generated":true,"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/BlockContactsViewController\/blockListExist","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/BlockContactsViewController\/contactList","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/BlockContactsViewController\/navigation","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/BlockContactsViewController\/search"],"anchor":"Instance-Properties","title":"Instance Properties"},{"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/BlockContactsViewController\/createContactList()","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/BlockContactsViewController\/createNavigation()","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/BlockContactsViewController\/createSearch()","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/BlockContactsViewController\/fetchBlockList()","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/BlockContactsViewController\/mirrorIdsToProfiles(users:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/BlockContactsViewController\/pop()","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/BlockContactsViewController\/viewDidLoad()","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/BlockContactsViewController\/viewWillAppear(_:)"],"anchor":"Instance-Methods","generated":true,"title":"Instance Methods"},{"anchor":"Default-Implementations","generated":true,"title":"Default Implementations","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/BlockContactsViewController\/ThemeSwitchProtocol-Implementations"]}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"BlockContactsViewController"}],"modules":[{"name":"ShengwangChatUIKit"}],"externalID":"c:@M@ShengwangChatUIKit@objc(cs)BlockContactsViewController","title":"BlockContactsViewController","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"BlockContactsViewController","kind":"identifier"}],"symbolKind":"class","roleHeading":"Class","role":"symbol"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit"]]},"relationshipsSections":[{"type":"inheritsFrom","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(cs)UIViewController"],"title":"Inherits From","kind":"relationships"},{"kind":"relationships","type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)NSCoding","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)NSExtensionRequestHandling","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)NSObject","doc:\/\/org.cocoapods.ShengwangChatUIKit\/s7CVarArgP","doc:\/\/org.cocoapods.ShengwangChatUIKit\/s8CopyableP","doc:\/\/org.cocoapods.ShengwangChatUIKit\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.ShengwangChatUIKit\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.ShengwangChatUIKit\/SQ","doc:\/\/org.cocoapods.ShengwangChatUIKit\/SH","doc:\/\/org.cocoapods.ShengwangChatUIKit\/s8SendableP","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ThemeSwitchProtocol","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIAppearanceContainer","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIContentContainer","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIFocusEnvironment","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIResponderStandardEditActions","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIStateRestoring","doc:\/\/org.cocoapods.ShengwangChatUIKit\/5UIKit23UITraitChangeObservableP","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UITraitEnvironment","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIUserActivityRestoring","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIViewControllerTransitioningDelegate"]}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/BlockContactsViewController/initWithNibName:bundle:":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/BlockContactsViewController\/initWithNibName:bundle:","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithNibName:bundle:"}],"kind":"symbol","url":"\/documentation\/shengwangchatuikit\/blockcontactsviewcontroller\/initwithnibname:bundle:","title":"initWithNibName:bundle:","role":"symbol","abstract":[],"navigatorTitle":[{"text":"initWithNibName:bundle:","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/BlockContactsViewController/createContactList()":{"role":"symbol","abstract":[{"text":"Creates a contact list view.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"createContactList"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)ContactView","text":"ContactView","kind":"typeIdentifier"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/BlockContactsViewController\/createContactList()","url":"\/documentation\/shengwangchatuikit\/blockcontactsviewcontroller\/createcontactlist()","title":"createContactList()","navigatorTitle":[{"text":"createContactList","kind":"identifier"}],"kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/BlockContactsViewController/contactList":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/BlockContactsViewController\/contactList","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"contactList"},{"kind":"text","text":": "},{"text":"ContactView","kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)ContactView"}],"kind":"symbol","url":"\/documentation\/shengwangchatuikit\/blockcontactsviewcontroller\/contactlist","title":"contactList","role":"symbol","abstract":[],"type":"topic"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UIViewControllerTransitioningDelegate":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIViewControllerTransitioningDelegate","title":"UIKit.UIViewControllerTransitioningDelegate"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/BlockContactsViewController/ThemeSwitchProtocol-Implementations":{"abstract":[],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/BlockContactsViewController\/ThemeSwitchProtocol-Implementations","url":"\/documentation\/shengwangchatuikit\/blockcontactsviewcontroller\/themeswitchprotocol-implementations","kind":"article","title":"ThemeSwitchProtocol Implementations","role":"collectionGroup","type":"topic"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/SH":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/SH","title":"Swift.Hashable"},"doc://org.cocoapods.ShengwangChatUIKit/SQ":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/SQ","title":"Swift.Equatable"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIUserActivityRestoring","title":"UIKit.UIUserActivityRestoring"},"doc://org.cocoapods.ShengwangChatUIKit/s8SendableP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/s8SendableP","title":"Swift.Sendable"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/BlockContactsViewController/createSearch()":{"role":"symbol","abstract":[{"type":"text","text":"Creates a search button with a custom frame and appearance."}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"createSearch","kind":"identifier"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIButton","text":"UIButton"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/BlockContactsViewController\/createSearch()","url":"\/documentation\/shengwangchatuikit\/blockcontactsviewcontroller\/createsearch()","title":"createSearch()","navigatorTitle":[{"text":"createSearch","kind":"identifier"}],"kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UIResponderStandardEditActions":{"title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIResponderStandardEditActions","type":"unresolvable"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/BlockContactsViewController/pop()":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/BlockContactsViewController\/pop()","navigatorTitle":[{"kind":"identifier","text":"pop"}],"url":"\/documentation\/shengwangchatuikit\/blockcontactsviewcontroller\/pop()","type":"topic","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"pop"},{"kind":"text","text":"()"}],"title":"pop()","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/BlockContactsViewController":{"abstract":[],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/BlockContactsViewController","url":"\/documentation\/shengwangchatuikit\/blockcontactsviewcontroller","navigatorTitle":[{"text":"BlockContactsViewController","kind":"identifier"}],"kind":"symbol","title":"BlockContactsViewController","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BlockContactsViewController","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UIAppearanceContainer":{"title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIAppearanceContainer","type":"unresolvable"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UIActivityItemsConfigurationProviding":{"title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIActivityItemsConfigurationProviding","type":"unresolvable"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/BlockContactsViewController/createNavigation()":{"type":"topic","role":"symbol","title":"createNavigation()","kind":"symbol","abstract":[{"type":"text","text":"Creates and returns a navigation bar for the ContactViewController."}],"navigatorTitle":[{"kind":"identifier","text":"createNavigation"}],"url":"\/documentation\/shengwangchatuikit\/blockcontactsviewcontroller\/createnavigation()","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/BlockContactsViewController\/createNavigation()","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"createNavigation","kind":"identifier"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)ChatNavigationBar","text":"ChatNavigationBar"}]},"doc://org.cocoapods.ShengwangChatUIKit/5UIKit23UITraitChangeObservableP":{"title":"UIKit.UITraitChangeObservable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/5UIKit23UITraitChangeObservableP","type":"unresolvable"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UIContentContainer":{"title":"UIKit.UIContentContainer","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIContentContainer","type":"unresolvable"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/BlockContactsViewController/search":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/BlockContactsViewController\/search","url":"\/documentation\/shengwangchatuikit\/blockcontactsviewcontroller\/search","role":"symbol","title":"search","abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"search","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UIButton","preciseIdentifier":"c:objc(cs)UIButton"}]},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)NSExtensionRequestHandling":{"title":"Foundation.NSExtensionRequestHandling","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)NSExtensionRequestHandling","type":"unresolvable"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/BlockContactsViewController/viewWillAppear(_:)":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/BlockContactsViewController\/viewWillAppear(_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"viewWillAppear","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":")"}],"kind":"symbol","url":"\/documentation\/shengwangchatuikit\/blockcontactsviewcontroller\/viewwillappear(_:)","title":"viewWillAppear(_:)","role":"symbol","abstract":[],"navigatorTitle":[{"text":"viewWillAppear:","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)NSCoding":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)NSCoding","title":"Foundation.NSCoding"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/BlockContactsViewController/navigation":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/BlockContactsViewController\/navigation","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"navigation"},{"text":": ","kind":"text"},{"text":"ChatNavigationBar","kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)ChatNavigationBar"}],"kind":"symbol","url":"\/documentation\/shengwangchatuikit\/blockcontactsviewcontroller\/navigation","title":"navigation","role":"symbol","abstract":[],"type":"topic"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/BlockContactsViewController/viewDidLoad()":{"title":"viewDidLoad()","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"viewDidLoad","kind":"identifier"},{"kind":"text","text":"()"}],"type":"topic","navigatorTitle":[{"text":"viewDidLoad","kind":"identifier"}],"abstract":[],"url":"\/documentation\/shengwangchatuikit\/blockcontactsviewcontroller\/viewdidload()","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/BlockContactsViewController\/viewDidLoad()","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UIPasteConfigurationSupporting":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIPasteConfigurationSupporting","type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting"},"doc://org.cocoapods.ShengwangChatUIKit/s8CopyableP":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/s8CopyableP","type":"unresolvable","title":"Swift.Copyable"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/BlockContactsViewController/blockListExist":{"role":"symbol","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"blockListExist"},{"kind":"text","text":": ["},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":"]","kind":"text"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/BlockContactsViewController\/blockListExist","url":"\/documentation\/shengwangchatuikit\/blockcontactsviewcontroller\/blocklistexist","title":"blockListExist","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/BlockContactsViewController/initWithCoder:":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/BlockContactsViewController\/initWithCoder:","fragments":[{"text":"- ","kind":"text"},{"text":"initWithCoder:","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/shengwangchatuikit\/blockcontactsviewcontroller\/initwithcoder:","title":"initWithCoder:","role":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"type":"topic"},"doc://org.cocoapods.ShengwangChatUIKit/s23CustomStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/BlockContactsViewController/mirrorIdsToProfiles(users:)":{"title":"mirrorIdsToProfiles(users:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"mirrorIdsToProfilesWithUsers:"}],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"mirrorIdsToProfiles","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"users"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?)"}],"kind":"symbol","abstract":[],"url":"\/documentation\/shengwangchatuikit\/blockcontactsviewcontroller\/mirroridstoprofiles(users:)","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/BlockContactsViewController\/mirrorIdsToProfiles(users:)"},"doc://org.cocoapods.ShengwangChatUIKit/objc(cs)UIViewController":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(cs)UIViewController","type":"unresolvable","title":"UIViewController"},"doc://org.cocoapods.ShengwangChatUIKit/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://org.cocoapods.ShengwangChatUIKit/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/s7CVarArgP"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ThemeSwitchProtocol":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ThemeSwitchProtocol","abstract":[{"type":"text","text":"When the system theme changes, you can use this static method to switch between the light and dark themes of the ease chat UIKit."}],"url":"\/documentation\/shengwangchatuikit\/themeswitchprotocol","type":"topic","kind":"symbol","role":"symbol","title":"ThemeSwitchProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"ThemeSwitchProtocol","kind":"identifier"}],"navigatorTitle":[{"text":"ThemeSwitchProtocol","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UITraitEnvironment"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UIStateRestoring":{"title":"UIKit.UIStateRestoring","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIStateRestoring","type":"unresolvable"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UIFocusEnvironment":{"title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIFocusEnvironment","type":"unresolvable"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/BlockContactsViewController/fetchBlockList()":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/BlockContactsViewController\/fetchBlockList()","role":"symbol","abstract":[{"text":"Fetch block user list.","type":"text"}],"title":"fetchBlockList()","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"fetchBlockList","kind":"identifier"},{"text":"()","kind":"text"}],"type":"topic","kind":"symbol","navigatorTitle":[{"text":"fetchBlockList","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/blockcontactsviewcontroller\/fetchblocklist()"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"op":"replace","value":"BlockContactsViewController","path":"\/metadata\/title"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"BlockContactsViewController"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"BlockContactsViewController","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"generated":true,"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/BlockContactsViewController\/createContactList()","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/BlockContactsViewController\/createNavigation()","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/BlockContactsViewController\/createSearch()","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/BlockContactsViewController\/fetchBlockList()","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/BlockContactsViewController\/initWithCoder:","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/BlockContactsViewController\/initWithNibName:bundle:","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/BlockContactsViewController\/mirrorIdsToProfiles(users:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/BlockContactsViewController\/pop()","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/BlockContactsViewController\/viewDidLoad()","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/BlockContactsViewController\/viewWillAppear(_:)"]},{"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/BlockContactsViewController\/ThemeSwitchProtocol-Implementations"],"anchor":"Default-Implementations","generated":true,"title":"Default Implementations"}]},{"path":"\/relationshipsSections","op":"replace","value":[{"kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(cs)UIViewController"],"title":"Inherits From"},{"type":"conformsTo","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ThemeSwitchProtocol"],"title":"Conforms To","kind":"relationships"}]},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"BlockContactsViewController"},{"kind":"text","text":" : "},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1BlockContactsViewController~1createContactList()\/title","op":"replace","value":"createContactList"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1BlockContactsViewController~1createContactList()\/fragments","value":[{"kind":"text","text":"- "},{"text":"createContactList","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1BlockContactsViewController~1createSearch()\/title","op":"replace","value":"createSearch"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"createSearch","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1BlockContactsViewController~1createSearch()\/fragments"},{"op":"replace","value":"pop","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1BlockContactsViewController~1pop()\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"pop"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1BlockContactsViewController~1pop()\/fragments","op":"replace"},{"value":"BlockContactsViewController","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1BlockContactsViewController\/title"},{"op":"replace","value":[{"kind":"identifier","text":"BlockContactsViewController"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1BlockContactsViewController\/fragments"},{"op":"replace","value":[{"text":"BlockContactsViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1BlockContactsViewController\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1BlockContactsViewController~1createNavigation()\/title","op":"replace","value":"createNavigation"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1BlockContactsViewController~1createNavigation()\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"createNavigation"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1BlockContactsViewController~1viewWillAppear(_:)\/title","value":"viewWillAppear:"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1BlockContactsViewController~1viewWillAppear(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewWillAppear:"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1BlockContactsViewController~1viewDidLoad()\/title","value":"viewDidLoad"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1BlockContactsViewController~1viewDidLoad()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidLoad"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1BlockContactsViewController~1mirrorIdsToProfiles(users:)\/title","op":"replace","value":"mirrorIdsToProfilesWithUsers:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1BlockContactsViewController~1mirrorIdsToProfiles(users:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"mirrorIdsToProfilesWithUsers:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ThemeSwitchProtocol\/title","value":"ThemeSwitchProtocol"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ThemeSwitchProtocol\/fragments","value":[{"text":"ThemeSwitchProtocol","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ThemeSwitchProtocol\/navigatorTitle","value":[{"text":"ThemeSwitchProtocol","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"fetchBlockList","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1BlockContactsViewController~1fetchBlockList()\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"fetchBlockList","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1BlockContactsViewController~1fetchBlockList()\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}