{"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BubbleTowards"}]}]}],"relationshipsSections":[{"title":"Conforms To","type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/SQ","doc:\/\/org.cocoapods.ShengwangChatUIKit\/SH","doc:\/\/org.cocoapods.ShengwangChatUIKit\/SY"]}],"variants":[{"paths":["\/documentation\/shengwangchatuikit\/bubbletowards"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/bubbletowards"]}],"metadata":{"roleHeading":"Enumeration","externalID":"c:@M@ShengwangChatUIKit@E@BubbleTowards","symbolKind":"enum","role":"symbol","modules":[{"name":"ShengwangChatUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"BubbleTowards"}],"title":"BubbleTowards","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"BubbleTowards"}]},"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit"]]},"topicSections":[{"title":"Enumeration Cases","generated":true,"anchor":"Enumeration-Cases","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/BubbleTowards\/left","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/BubbleTowards\/right"]},{"generated":true,"anchor":"Initializers","title":"Initializers","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/BubbleTowards\/init(rawValue:)"]},{"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/BubbleTowards\/Equatable-Implementations","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/BubbleTowards\/RawRepresentable-Implementations"],"generated":true,"title":"Default Implementations","anchor":"Default-Implementations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/BubbleTowards"},"references":{"doc://org.cocoapods.ShengwangChatUIKit/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/SY"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/BubbleTowards/Equatable-Implementations":{"url":"\/documentation\/shengwangchatuikit\/bubbletowards\/equatable-implementations","abstract":[],"type":"topic","title":"Equatable Implementations","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/BubbleTowards\/Equatable-Implementations","role":"collectionGroup","kind":"article"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/BubbleTowards/init(rawValue:)":{"abstract":[],"url":"\/documentation\/shengwangchatuikit\/bubbletowards\/init(rawvalue:)","title":"init(rawValue:)","role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/BubbleTowards\/init(rawValue:)","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"rawValue"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Su","kind":"typeIdentifier","text":"UInt"},{"text":")","kind":"text"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/BubbleTowards":{"navigatorTitle":[{"kind":"identifier","text":"BubbleTowards"}],"abstract":[],"kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/BubbleTowards","url":"\/documentation\/shengwangchatuikit\/bubbletowards","title":"BubbleTowards","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"BubbleTowards"}]},"doc://org.cocoapods.ShengwangChatUIKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/SH"},"doc://org.cocoapods.ShengwangChatUIKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/SQ"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/BubbleTowards/RawRepresentable-Implementations":{"abstract":[],"kind":"article","role":"collectionGroup","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/BubbleTowards\/RawRepresentable-Implementations","url":"\/documentation\/shengwangchatuikit\/bubbletowards\/rawrepresentable-implementations","title":"RawRepresentable Implementations","type":"topic"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/BubbleTowards/left":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/BubbleTowards\/left","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"BubbleTowardsLeft"}],"type":"topic","role":"symbol","url":"\/documentation\/shengwangchatuikit\/bubbletowards\/left","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"left"}],"title":"BubbleTowards.left"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/BubbleTowards/right":{"url":"\/documentation\/shengwangchatuikit\/bubbletowards\/right","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"right","kind":"identifier"}],"navigatorTitle":[{"text":"BubbleTowardsRight","kind":"identifier"}],"type":"topic","abstract":[],"kind":"symbol","role":"symbol","title":"BubbleTowards.right","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/BubbleTowards\/right"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration"},{"value":"BubbleTowards","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"BubbleTowards","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"BubbleTowards"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","anchor":"Enumeration-Cases","generated":true,"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/BubbleTowards\/left","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/BubbleTowards\/right"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BubbleTowards","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSUInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSUInteger"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1BubbleTowards\/title","value":"BubbleTowards"},{"value":[{"text":"BubbleTowards","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1BubbleTowards\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1BubbleTowards\/navigatorTitle","value":[{"text":"BubbleTowards","kind":"identifier"}],"op":"replace"},{"value":"BubbleTowardsLeft","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1BubbleTowards~1left\/title","op":"replace"},{"value":[{"kind":"identifier","text":"BubbleTowardsLeft"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1BubbleTowards~1left\/fragments","op":"replace"},{"value":"BubbleTowardsRight","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1BubbleTowards~1right\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1BubbleTowards~1right\/fragments","value":[{"kind":"identifier","text":"BubbleTowardsRight"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}