{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatAppearance"},"kind":"symbol","variants":[{"paths":["\/documentation\/shengwangchatuikit\/chatappearance"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/shengwangchatuikit\/chatappearance"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"relationshipsSections":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(cs)NSObject"],"type":"inheritsFrom"},{"title":"Conforms To","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)NSObject","doc:\/\/org.cocoapods.ShengwangChatUIKit\/s7CVarArgP","doc:\/\/org.cocoapods.ShengwangChatUIKit\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.ShengwangChatUIKit\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.ShengwangChatUIKit\/SQ","doc:\/\/org.cocoapods.ShengwangChatUIKit\/SH"],"kind":"relationships","type":"conformsTo"}],"topicSections":[{"generated":true,"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatAppearance\/audioDuration","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatAppearance\/bubbleStyle","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatAppearance\/commonReactionMap","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatAppearance\/commonReactions","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatAppearance\/contentStyle","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatAppearance\/dateFormatOtherDay","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatAppearance\/dateFormatToday","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatAppearance\/descriptionPreviewPattern","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatAppearance\/enablePinMessage","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatAppearance\/enableTranslation","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatAppearance\/enableTyping","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatAppearance\/enableURLPreview","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatAppearance\/groupParticipantsLimitCount","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatAppearance\/imageMessageCorner","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatAppearance\/imagePlaceHolder","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatAppearance\/imagePreviewPattern","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatAppearance\/inputBarCorner","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatAppearance\/inputExtendActions","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatAppearance\/inputPlaceHolder","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatAppearance\/maxInputHeight","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatAppearance\/messageAttachmentMenuStyle","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatAppearance\/messageLongPressMenuStyle","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatAppearance\/messageLongPressedActions","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatAppearance\/moreMessageAlertPosition","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatAppearance\/newMessageSoundPath","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatAppearance\/recallExpiredTime","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatAppearance\/receiveAudioAnimationImages","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatAppearance\/receiveTextColor","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatAppearance\/receiveTranslationColor","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatAppearance\/reportSelectionReasons","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatAppearance\/reportSelectionTags","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatAppearance\/sendAudioAnimationImages","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatAppearance\/sendTextColor","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatAppearance\/sendTranslationColor","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatAppearance\/targetLanguage","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatAppearance\/titlePreviewPattern","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatAppearance\/videoPlaceHolder"],"anchor":"Instance-Properties","title":"Instance Properties"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit"]]},"metadata":{"role":"symbol","roleHeading":"Class","externalID":"c:@M@ShengwangChatUIKit@objc(cs)ChatAppearance","navigatorTitle":[{"kind":"identifier","text":"ChatAppearance"}],"modules":[{"name":"ShengwangChatUIKit"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ChatAppearance","kind":"identifier"}],"title":"ChatAppearance","symbolKind":"class"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objcMembers","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ChatAppearance","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatAppearance/descriptionPreviewPattern":{"role":"symbol","navigatorTitle":[{"text":"descriptionPreviewPattern","kind":"identifier"}],"abstract":[{"type":"text","text":"URL preview feature regular description expression."}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatAppearance\/descriptionPreviewPattern","url":"\/documentation\/shengwangchatuikit\/chatappearance\/descriptionpreviewpattern","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"descriptionPreviewPattern","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"type":"topic","title":"descriptionPreviewPattern"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatAppearance/imageMessageCorner":{"url":"\/documentation\/shengwangchatuikit\/chatappearance\/imagemessagecorner","navigatorTitle":[{"text":"imageMessageCorner","kind":"identifier"}],"title":"imageMessageCorner","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatAppearance\/imageMessageCorner","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"imageMessageCorner","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier"}],"type":"topic","kind":"symbol","abstract":[{"text":"The corner of the image message.","type":"text"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatAppearance/targetLanguage":{"role":"symbol","abstract":[{"text":"The mirror type of the language code of LanguageType.","type":"text"},{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/LanguageType","type":"reference","isActive":true}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatAppearance\/targetLanguage","url":"\/documentation\/shengwangchatuikit\/chatappearance\/targetlanguage","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"targetLanguage","kind":"identifier"},{"kind":"text","text":": "},{"text":"LanguageType","preciseIdentifier":"s:18ShengwangChatUIKit12LanguageTypeO","kind":"typeIdentifier"}],"type":"topic","title":"targetLanguage"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatAppearance/audioDuration":{"url":"\/documentation\/shengwangchatuikit\/chatappearance\/audioduration","navigatorTitle":[{"kind":"identifier","text":"audioDuration"}],"title":"audioDuration","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatAppearance\/audioDuration","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"audioDuration","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"type":"topic","kind":"symbol","abstract":[{"text":"Record audio limitation.","type":"text"}]},"doc://org.cocoapods.ShengwangChatUIKit/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/s23CustomStringConvertibleP"},"doc://org.cocoapods.ShengwangChatUIKit/SH":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatAppearance/sendAudioAnimationImages":{"role":"symbol","navigatorTitle":[{"text":"sendAudioAnimationImages","kind":"identifier"}],"abstract":[{"type":"text","text":"The resource image of the audio animation played after the sender of the audio message clicks"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatAppearance\/sendAudioAnimationImages","url":"\/documentation\/shengwangchatuikit\/chatappearance\/sendaudioanimationimages","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sendAudioAnimationImages","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier","text":"UIImage"},{"kind":"text","text":"]"}],"type":"topic","title":"sendAudioAnimationImages"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatAppearance/imagePlaceHolder":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"imagePlaceHolder","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"},{"kind":"text","text":"?"}],"type":"topic","role":"symbol","abstract":[{"text":"Default placeholder image for picture messages.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"imagePlaceHolder","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatAppearance\/imagePlaceHolder","url":"\/documentation\/shengwangchatuikit\/chatappearance\/imageplaceholder","title":"imagePlaceHolder"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageBubbleDisplayStyle":{"type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"MessageBubbleDisplayStyle","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageBubbleDisplayStyle","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MessageBubbleDisplayStyle"}],"role":"symbol","title":"MessageBubbleDisplayStyle","url":"\/documentation\/shengwangchatuikit\/messagebubbledisplaystyle","abstract":[]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatAppearance/messageLongPressMenuStyle":{"url":"\/documentation\/shengwangchatuikit\/chatappearance\/messagelongpressmenustyle","navigatorTitle":[{"text":"messageLongPressMenuStyle","kind":"identifier"}],"title":"messageLongPressMenuStyle","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatAppearance\/messageLongPressMenuStyle","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"messageLongPressMenuStyle","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MessageLongPressMenuStyle","preciseIdentifier":"c:@M@ShengwangChatUIKit@E@MessageLongPressMenuStyle","kind":"typeIdentifier"}],"type":"topic","kind":"symbol","abstract":[{"text":"Choose to show the message long press menu style.","type":"text"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatAppearance/sendTranslationColor":{"role":"symbol","navigatorTitle":[{"text":"sendTranslationColor","kind":"identifier"}],"abstract":[{"text":"The color of the sender of the text message.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatAppearance\/sendTranslationColor","url":"\/documentation\/shengwangchatuikit\/chatappearance\/sendtranslationcolor","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sendTranslationColor","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier","text":"UIColor"}],"type":"topic","title":"sendTranslationColor"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatAppearance/receiveTranslationColor":{"abstract":[{"type":"text","text":"The color of the recipient of the text message."}],"url":"\/documentation\/shengwangchatuikit\/chatappearance\/receivetranslationcolor","title":"receiveTranslationColor","role":"symbol","navigatorTitle":[{"text":"receiveTranslationColor","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatAppearance\/receiveTranslationColor","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"receiveTranslationColor"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatAppearance/dateFormatOtherDay":{"url":"\/documentation\/shengwangchatuikit\/chatappearance\/dateformatotherday","navigatorTitle":[{"text":"dateFormatOtherDay","kind":"identifier"}],"title":"dateFormatOtherDay","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatAppearance\/dateFormatOtherDay","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dateFormatOtherDay","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"type":"topic","kind":"symbol","abstract":[{"text":"Setting this property changes the date format displayed within a single session.","type":"text"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatAppearance/inputPlaceHolder":{"url":"\/documentation\/shengwangchatuikit\/chatappearance\/inputplaceholder","title":"inputPlaceHolder","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"inputPlaceHolder"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatAppearance\/inputPlaceHolder","abstract":[{"text":"The placeholder text in ","type":"text"},{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageInputBar","isActive":true,"type":"reference"},{"type":"text","text":"."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"inputPlaceHolder","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageContentDisplayStyle":{"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"MessageContentDisplayStyle"}],"title":"MessageContentDisplayStyle","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageContentDisplayStyle","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MessageContentDisplayStyle"}],"type":"topic","url":"\/documentation\/shengwangchatuikit\/messagecontentdisplaystyle","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatAppearance/moreMessageAlertPosition":{"navigatorTitle":[{"text":"moreMessageAlertPosition","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/chatappearance\/moremessagealertposition","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"moreMessageAlertPosition"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@E@MoreMessagePosition","text":"MoreMessagePosition"}],"role":"symbol","title":"moreMessageAlertPosition","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatAppearance\/moreMessageAlertPosition","kind":"symbol","abstract":[{"type":"text","text":"The alert position on received lots of messages."}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatAppearance/newMessageSoundPath":{"role":"symbol","navigatorTitle":[{"text":"newMessageSoundPath","kind":"identifier"}],"abstract":[{"text":"New message tone audio path","type":"text"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatAppearance\/newMessageSoundPath","url":"\/documentation\/shengwangchatuikit\/chatappearance\/newmessagesoundpath","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"newMessageSoundPath","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"type":"topic","title":"newMessageSoundPath"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatAppearance/bubbleStyle":{"url":"\/documentation\/shengwangchatuikit\/chatappearance\/bubblestyle","navigatorTitle":[{"text":"bubbleStyle","kind":"identifier"}],"title":"bubbleStyle","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatAppearance\/bubbleStyle","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bubbleStyle"},{"kind":"text","text":": "},{"text":"MessageBubbleDisplayStyle","preciseIdentifier":"c:@M@ShengwangChatUIKit@E@MessageBubbleDisplayStyle","kind":"typeIdentifier"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Message bubble display style."},{"isActive":true,"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageBubbleDisplayStyle","type":"reference"}]},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)NSObject","type":"unresolvable"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatAppearance/maxInputHeight":{"url":"\/documentation\/shengwangchatuikit\/chatappearance\/maxinputheight","navigatorTitle":[{"text":"maxInputHeight","kind":"identifier"}],"title":"maxInputHeight","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatAppearance\/maxInputHeight","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"maxInputHeight","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier"}],"type":"topic","kind":"symbol","abstract":[{"text":"The height limit of the input box in ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageInputBar"},{"type":"text","text":"."}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatAppearance/enablePinMessage":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"enablePinMessage"}],"abstract":[{"type":"text","text":"Whether enable pin message function or not"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatAppearance\/enablePinMessage","url":"\/documentation\/shengwangchatuikit\/chatappearance\/enablepinmessage","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"enablePinMessage","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"type":"topic","title":"enablePinMessage"},"doc://org.cocoapods.ShengwangChatUIKit/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/s7CVarArgP"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatAppearance/init":{"type":"topic","role":"symbol","title":"init","kind":"symbol","abstract":[],"navigatorTitle":[{"text":"init","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/chatappearance\/init","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatAppearance\/init","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/SQ","type":"unresolvable"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatAppearance":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ChatAppearance","kind":"identifier"}],"type":"topic","abstract":[],"role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatAppearance","title":"ChatAppearance","navigatorTitle":[{"kind":"identifier","text":"ChatAppearance"}],"url":"\/documentation\/shengwangchatuikit\/chatappearance"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatAppearance/enableTranslation":{"type":"topic","role":"symbol","title":"enableTranslation","kind":"symbol","abstract":[{"text":"You need to enable the translation function from the console first, and then set this property to true to experience the translation function.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"enableTranslation"}],"url":"\/documentation\/shengwangchatuikit\/chatappearance\/enabletranslation","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatAppearance\/enableTranslation","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"enableTranslation","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatAppearance/messageLongPressedActions":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"messageLongPressedActions"}],"title":"messageLongPressedActions","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatAppearance\/messageLongPressedActions","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"messageLongPressedActions","kind":"identifier"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(pl)ActionSheetItemProtocol","text":"ActionSheetItemProtocol","kind":"typeIdentifier"},{"kind":"text","text":"]"}],"type":"topic","url":"\/documentation\/shengwangchatuikit\/chatappearance\/messagelongpressedactions","abstract":[{"type":"text","text":"ActionSheet data source of the message being long pressed."},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ActionSheetItemProtocol"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatAppearance/inputBarCorner":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"inputBarCorner","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit12CornerRadiusO","text":"CornerRadius"}],"abstract":[{"text":"The corner radius of ","type":"text"},{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageInputBar","type":"reference","isActive":true},{"text":".","type":"text"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatAppearance\/inputBarCorner","title":"inputBarCorner","url":"\/documentation\/shengwangchatuikit\/chatappearance\/inputbarcorner","type":"topic","role":"symbol","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatAppearance/reportSelectionTags":{"type":"topic","role":"symbol","title":"reportSelectionTags","kind":"symbol","abstract":[{"type":"text","text":"The label for message reporting types."}],"navigatorTitle":[{"text":"reportSelectionTags","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/chatappearance\/reportselectiontags","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatAppearance\/reportSelectionTags","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"reportSelectionTags","kind":"identifier"},{"kind":"text","text":": ["},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"]","kind":"text"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatAppearance/titlePreviewPattern":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatAppearance\/titlePreviewPattern","role":"symbol","url":"\/documentation\/shengwangchatuikit\/chatappearance\/titlepreviewpattern","abstract":[{"text":"URL preview feature regular title expression.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"titlePreviewPattern","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"title":"titlePreviewPattern","type":"topic","navigatorTitle":[{"text":"titlePreviewPattern","kind":"identifier"}],"kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatAppearance/groupParticipantsLimitCount":{"url":"\/documentation\/shengwangchatuikit\/chatappearance\/groupparticipantslimitcount","navigatorTitle":[{"text":"groupParticipantsLimitCount","kind":"identifier"}],"title":"groupParticipantsLimitCount","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatAppearance\/groupParticipantsLimitCount","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"groupParticipantsLimitCount"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"type":"topic","kind":"symbol","abstract":[{"text":"The maximum number of participants in the group chat.","type":"text"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatAppearance/enableTyping":{"kind":"symbol","navigatorTitle":[{"text":"enableTyping","kind":"identifier"}],"title":"enableTyping","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatAppearance\/enableTyping","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"enableTyping","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"type":"topic","url":"\/documentation\/shengwangchatuikit\/chatappearance\/enabletyping","abstract":[{"text":"Whether show the typing status or not on other party input text.","type":"text"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatAppearance/videoPlaceHolder":{"type":"topic","role":"symbol","title":"videoPlaceHolder","kind":"symbol","abstract":[{"text":"Default placeholder image for video messages.","type":"text"}],"navigatorTitle":[{"text":"videoPlaceHolder","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/chatappearance\/videoplaceholder","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatAppearance\/videoPlaceHolder","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"videoPlaceHolder","kind":"identifier"},{"kind":"text","text":": "},{"text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatAppearance/imagePreviewPattern":{"kind":"symbol","navigatorTitle":[{"text":"imagePreviewPattern","kind":"identifier"}],"title":"imagePreviewPattern","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatAppearance\/imagePreviewPattern","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"imagePreviewPattern","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"type":"topic","url":"\/documentation\/shengwangchatuikit\/chatappearance\/imagepreviewpattern","abstract":[{"text":"URL preview feature regular image expression.","type":"text"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatAppearance/recallExpiredTime":{"type":"topic","role":"symbol","title":"recallExpiredTime","kind":"symbol","abstract":[{"text":"The maximum time limit for message withdrawal needs to be adjusted from the console before adjusting this configuration of the client.","type":"text"}],"navigatorTitle":[{"text":"recallExpiredTime","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/chatappearance\/recallexpiredtime","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatAppearance\/recallExpiredTime","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"recallExpiredTime","kind":"identifier"},{"kind":"text","text":": "},{"text":"UInt","preciseIdentifier":"s:Su","kind":"typeIdentifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/s28CustomDebugStringConvertibleP"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatAppearance/inputExtendActions":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"inputExtendActions","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(pl)ActionSheetItemProtocol","kind":"typeIdentifier","text":"ActionSheetItemProtocol"},{"kind":"text","text":"]"}],"abstract":[{"text":"A menu item pops up when you click the ","type":"text"},{"code":"+","type":"codeVoice"},{"type":"text","text":" button on the input box"}],"type":"topic","url":"\/documentation\/shengwangchatuikit\/chatappearance\/inputextendactions","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatAppearance\/inputExtendActions","navigatorTitle":[{"kind":"identifier","text":"inputExtendActions"}],"title":"inputExtendActions","kind":"symbol","role":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageInputBar":{"abstract":[],"title":"MessageInputBar","kind":"symbol","url":"\/documentation\/shengwangchatuikit\/messageinputbar","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MessageInputBar","kind":"identifier"}],"navigatorTitle":[{"text":"MessageInputBar","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageInputBar"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatAppearance/messageAttachmentMenuStyle":{"type":"topic","role":"symbol","title":"messageAttachmentMenuStyle","kind":"symbol","abstract":[{"text":"Choose to show the message attachment menu style.","type":"text"}],"navigatorTitle":[{"text":"messageAttachmentMenuStyle","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/chatappearance\/messageattachmentmenustyle","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatAppearance\/messageAttachmentMenuStyle","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"messageAttachmentMenuStyle"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@E@MessageAttachmentMenuStyle","text":"MessageAttachmentMenuStyle","kind":"typeIdentifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatAppearance/commonReactions":{"kind":"symbol","navigatorTitle":[{"text":"commonReactions","kind":"identifier"}],"title":"commonReactions","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatAppearance\/commonReactions","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"commonReactions","kind":"identifier"},{"kind":"text","text":": ["},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"]","kind":"text"}],"type":"topic","url":"\/documentation\/shengwangchatuikit\/chatappearance\/commonreactions","abstract":[{"type":"text","text":"Commonly used reaction emoticon responses"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatAppearance/receiveTextColor":{"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"receiveTextColor"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatAppearance\/receiveTextColor","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"receiveTextColor"}],"role":"symbol","title":"receiveTextColor","url":"\/documentation\/shengwangchatuikit\/chatappearance\/receivetextcolor","abstract":[{"type":"text","text":"The color of the recipient of the text message."}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ActionSheetItemProtocol":{"navigatorTitle":[{"text":"ActionSheetItemProtocol","kind":"identifier"}],"abstract":[{"type":"text","text":"A protocol that defines properties and methods for an action sheet item."}],"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ActionSheetItemProtocol"}],"url":"\/documentation\/shengwangchatuikit\/actionsheetitemprotocol","role":"symbol","title":"ActionSheetItemProtocol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ActionSheetItemProtocol","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatAppearance/reportSelectionReasons":{"type":"topic","role":"symbol","title":"reportSelectionReasons","kind":"symbol","abstract":[{"type":"text","text":"The label for message reporting reason."}],"navigatorTitle":[{"text":"reportSelectionReasons","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/chatappearance\/reportselectionreasons","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatAppearance\/reportSelectionReasons","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"reportSelectionReasons"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"]","kind":"text"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatAppearance/dateFormatToday":{"kind":"symbol","navigatorTitle":[{"text":"dateFormatToday","kind":"identifier"}],"title":"dateFormatToday","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatAppearance\/dateFormatToday","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dateFormatToday"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"type":"topic","url":"\/documentation\/shengwangchatuikit\/chatappearance\/dateformattoday","abstract":[{"type":"text","text":"Setting this property changes the date format displayed within a single session."}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/LanguageType":{"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"LanguageType"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/LanguageType","title":"LanguageType","navigatorTitle":[{"text":"LanguageType","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/languagetype","abstract":[{"text":"https:\/\/learn.microsoft.com\/en-us\/azure\/ai-services\/translator\/language-support#translation","type":"text"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatAppearance/sendTextColor":{"type":"topic","role":"symbol","title":"sendTextColor","kind":"symbol","abstract":[{"type":"text","text":"The color of the sender of the text message."}],"navigatorTitle":[{"text":"sendTextColor","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/chatappearance\/sendtextcolor","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatAppearance\/sendTextColor","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sendTextColor"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatAppearance/commonReactionMap":{"kind":"symbol","title":"commonReactionMap","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatAppearance\/commonReactionMap","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"commonReactionMap","kind":"identifier"},{"text":": [","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"},{"kind":"text","text":"?]"}],"type":"topic","url":"\/documentation\/shengwangchatuikit\/chatappearance\/commonreactionmap","abstract":[{"text":"Commonly used reaction emoticon responses map.","type":"text"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatAppearance/contentStyle":{"type":"topic","role":"symbol","title":"contentStyle","kind":"symbol","abstract":[{"text":"Message content display style.You can use these four styles to combine a style array you want. Bubbles are all provided by default, except for picture messages and video messages.","type":"text"},{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageContentDisplayStyle","isActive":true,"type":"reference"}],"url":"\/documentation\/shengwangchatuikit\/chatappearance\/contentstyle","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatAppearance\/contentStyle","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"contentStyle","kind":"identifier"},{"text":": [","kind":"text"},{"text":"MessageContentDisplayStyle","kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@E@MessageContentDisplayStyle"},{"kind":"text","text":"]"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatAppearance/receiveAudioAnimationImages":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"receiveAudioAnimationImages"}],"title":"receiveAudioAnimationImages","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatAppearance\/receiveAudioAnimationImages","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"receiveAudioAnimationImages","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"},{"kind":"text","text":"]"}],"type":"topic","url":"\/documentation\/shengwangchatuikit\/chatappearance\/receiveaudioanimationimages","abstract":[{"text":"The resource image of the audio animation played after the recipient of the audio message clicks","type":"text"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatAppearance/enableURLPreview":{"type":"topic","role":"symbol","title":"enableURLPreview","kind":"symbol","abstract":[{"text":"Whether enable URL preview or not.","type":"text"}],"navigatorTitle":[{"text":"enableURLPreview","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/chatappearance\/enableurlpreview","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatAppearance\/enableURLPreview","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"enableURLPreview","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(cs)NSObject"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"ChatAppearance","op":"replace"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"ChatAppearance","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"ChatAppearance"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"op":"replace","path":"\/topicSections","value":[{"anchor":"Instance-Properties","title":"Instance Properties","generated":true,"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatAppearance\/audioDuration","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatAppearance\/bubbleStyle","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatAppearance\/commonReactions","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatAppearance\/dateFormatOtherDay","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatAppearance\/dateFormatToday","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatAppearance\/descriptionPreviewPattern","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatAppearance\/enablePinMessage","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatAppearance\/enableTranslation","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatAppearance\/enableTyping","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatAppearance\/enableURLPreview","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatAppearance\/groupParticipantsLimitCount","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatAppearance\/imageMessageCorner","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatAppearance\/imagePlaceHolder","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatAppearance\/imagePreviewPattern","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatAppearance\/inputExtendActions","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatAppearance\/inputPlaceHolder","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatAppearance\/maxInputHeight","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatAppearance\/messageAttachmentMenuStyle","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatAppearance\/messageLongPressMenuStyle","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatAppearance\/messageLongPressedActions","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatAppearance\/moreMessageAlertPosition","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatAppearance\/newMessageSoundPath","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatAppearance\/recallExpiredTime","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatAppearance\/receiveAudioAnimationImages","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatAppearance\/receiveTextColor","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatAppearance\/receiveTranslationColor","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatAppearance\/reportSelectionReasons","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatAppearance\/reportSelectionTags","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatAppearance\/sendAudioAnimationImages","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatAppearance\/sendTextColor","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatAppearance\/sendTranslationColor","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatAppearance\/titlePreviewPattern","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatAppearance\/videoPlaceHolder"]},{"title":"Instance Methods","generated":true,"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatAppearance\/init"],"anchor":"Instance-Methods"}]},{"path":"\/relationshipsSections","op":"replace","value":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(cs)NSObject"]}]},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatAppearance"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}]}]},"op":"replace"},{"value":"descriptionPreviewPattern","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatAppearance~1descriptionPreviewPattern\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatAppearance~1descriptionPreviewPattern\/fragments","value":[{"text":"descriptionPreviewPattern","kind":"identifier"}]},{"value":"imageMessageCorner","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatAppearance~1imageMessageCorner\/title","op":"replace"},{"value":[{"text":"imageMessageCorner","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatAppearance~1imageMessageCorner\/fragments"},{"op":"replace","value":"audioDuration","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatAppearance~1audioDuration\/title"},{"value":[{"text":"audioDuration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatAppearance~1audioDuration\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatAppearance~1sendAudioAnimationImages\/title","value":"sendAudioAnimationImages","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatAppearance~1sendAudioAnimationImages\/fragments","value":[{"text":"sendAudioAnimationImages","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatAppearance~1imagePlaceHolder\/title","op":"replace","value":"imagePlaceHolder"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatAppearance~1imagePlaceHolder\/fragments","value":[{"text":"imagePlaceHolder","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"MessageBubbleDisplayStyle","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageBubbleDisplayStyle\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageBubbleDisplayStyle\/fragments","value":[{"kind":"identifier","text":"MessageBubbleDisplayStyle"}]},{"value":[{"kind":"identifier","text":"MessageBubbleDisplayStyle"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageBubbleDisplayStyle\/navigatorTitle"},{"op":"replace","value":"messageLongPressMenuStyle","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatAppearance~1messageLongPressMenuStyle\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatAppearance~1messageLongPressMenuStyle\/fragments","value":[{"kind":"identifier","text":"messageLongPressMenuStyle"}],"op":"replace"},{"value":"sendTranslationColor","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatAppearance~1sendTranslationColor\/title"},{"op":"replace","value":[{"text":"sendTranslationColor","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatAppearance~1sendTranslationColor\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatAppearance~1receiveTranslationColor\/title","value":"receiveTranslationColor"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatAppearance~1receiveTranslationColor\/fragments","value":[{"kind":"identifier","text":"receiveTranslationColor"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatAppearance~1dateFormatOtherDay\/title","value":"dateFormatOtherDay"},{"value":[{"kind":"identifier","text":"dateFormatOtherDay"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatAppearance~1dateFormatOtherDay\/fragments","op":"replace"},{"op":"replace","value":"inputPlaceHolder","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatAppearance~1inputPlaceHolder\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatAppearance~1inputPlaceHolder\/fragments","value":[{"text":"inputPlaceHolder","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageContentDisplayStyle\/title","value":"MessageContentDisplayStyle"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageContentDisplayStyle\/fragments","op":"replace","value":[{"kind":"identifier","text":"MessageContentDisplayStyle"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageContentDisplayStyle\/navigatorTitle","op":"replace","value":[{"text":"MessageContentDisplayStyle","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatAppearance~1moreMessageAlertPosition\/title","op":"replace","value":"moreMessageAlertPosition"},{"value":[{"kind":"identifier","text":"moreMessageAlertPosition"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatAppearance~1moreMessageAlertPosition\/fragments","op":"replace"},{"value":"newMessageSoundPath","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatAppearance~1newMessageSoundPath\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatAppearance~1newMessageSoundPath\/fragments","op":"replace","value":[{"kind":"identifier","text":"newMessageSoundPath"}]},{"value":"bubbleStyle","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatAppearance~1bubbleStyle\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatAppearance~1bubbleStyle\/fragments","value":[{"text":"bubbleStyle","kind":"identifier"}]},{"op":"replace","value":"maxInputHeight","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatAppearance~1maxInputHeight\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatAppearance~1maxInputHeight\/fragments","value":[{"text":"maxInputHeight","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"enablePinMessage","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatAppearance~1enablePinMessage\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatAppearance~1enablePinMessage\/fragments","value":[{"text":"enablePinMessage","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatAppearance\/title","value":"ChatAppearance","op":"replace"},{"value":[{"kind":"identifier","text":"ChatAppearance"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatAppearance\/fragments"},{"value":[{"kind":"identifier","text":"ChatAppearance"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatAppearance\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatAppearance~1enableTranslation\/title","value":"enableTranslation","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"enableTranslation"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatAppearance~1enableTranslation\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatAppearance~1messageLongPressedActions\/title","op":"replace","value":"messageLongPressedActions"},{"value":[{"text":"messageLongPressedActions","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatAppearance~1messageLongPressedActions\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatAppearance~1reportSelectionTags\/title","value":"reportSelectionTags","op":"replace"},{"value":[{"text":"reportSelectionTags","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatAppearance~1reportSelectionTags\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatAppearance~1titlePreviewPattern\/title","op":"replace","value":"titlePreviewPattern"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatAppearance~1titlePreviewPattern\/fragments","value":[{"text":"titlePreviewPattern","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatAppearance~1groupParticipantsLimitCount\/title","value":"groupParticipantsLimitCount","op":"replace"},{"value":[{"text":"groupParticipantsLimitCount","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatAppearance~1groupParticipantsLimitCount\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatAppearance~1enableTyping\/title","value":"enableTyping"},{"value":[{"kind":"identifier","text":"enableTyping"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatAppearance~1enableTyping\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatAppearance~1videoPlaceHolder\/title","value":"videoPlaceHolder","op":"replace"},{"value":[{"kind":"identifier","text":"videoPlaceHolder"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatAppearance~1videoPlaceHolder\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatAppearance~1imagePreviewPattern\/title","value":"imagePreviewPattern"},{"value":[{"text":"imagePreviewPattern","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatAppearance~1imagePreviewPattern\/fragments"},{"value":"recallExpiredTime","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatAppearance~1recallExpiredTime\/title"},{"value":[{"kind":"identifier","text":"recallExpiredTime"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatAppearance~1recallExpiredTime\/fragments"},{"op":"replace","value":"inputExtendActions","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatAppearance~1inputExtendActions\/title"},{"value":[{"text":"inputExtendActions","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatAppearance~1inputExtendActions\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageInputBar\/title","value":"MessageInputBar"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageInputBar\/fragments","op":"replace","value":[{"text":"MessageInputBar","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageInputBar\/navigatorTitle","value":[{"text":"MessageInputBar","kind":"identifier"}],"op":"replace"},{"value":"messageAttachmentMenuStyle","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatAppearance~1messageAttachmentMenuStyle\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatAppearance~1messageAttachmentMenuStyle\/fragments","value":[{"kind":"identifier","text":"messageAttachmentMenuStyle"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatAppearance~1commonReactions\/title","value":"commonReactions"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatAppearance~1commonReactions\/fragments","value":[{"text":"commonReactions","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatAppearance~1receiveTextColor\/title","op":"replace","value":"receiveTextColor"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatAppearance~1receiveTextColor\/fragments","op":"replace","value":[{"kind":"identifier","text":"receiveTextColor"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ActionSheetItemProtocol\/title","value":"ActionSheetItemProtocol"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ActionSheetItemProtocol\/fragments","value":[{"text":"ActionSheetItemProtocol","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"ActionSheetItemProtocol"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ActionSheetItemProtocol\/navigatorTitle"},{"value":"reportSelectionReasons","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatAppearance~1reportSelectionReasons\/title"},{"op":"replace","value":[{"text":"reportSelectionReasons","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatAppearance~1reportSelectionReasons\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatAppearance~1dateFormatToday\/title","value":"dateFormatToday"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatAppearance~1dateFormatToday\/fragments","value":[{"text":"dateFormatToday","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatAppearance~1sendTextColor\/title","value":"sendTextColor","op":"replace"},{"value":[{"text":"sendTextColor","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatAppearance~1sendTextColor\/fragments","op":"replace"},{"op":"replace","value":"receiveAudioAnimationImages","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatAppearance~1receiveAudioAnimationImages\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatAppearance~1receiveAudioAnimationImages\/fragments","value":[{"text":"receiveAudioAnimationImages","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatAppearance~1enableURLPreview\/title","op":"replace","value":"enableURLPreview"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatAppearance~1enableURLPreview\/fragments","op":"replace","value":[{"text":"enableURLPreview","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}