{"relationshipsSections":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(cs)UIViewController"]},{"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)NSCoding","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)NSExtensionRequestHandling","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)NSObject","doc:\/\/org.cocoapods.ShengwangChatUIKit\/s7CVarArgP","doc:\/\/org.cocoapods.ShengwangChatUIKit\/s8CopyableP","doc:\/\/org.cocoapods.ShengwangChatUIKit\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.ShengwangChatUIKit\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.ShengwangChatUIKit\/SQ","doc:\/\/org.cocoapods.ShengwangChatUIKit\/SH","doc:\/\/org.cocoapods.ShengwangChatUIKit\/s8SendableP","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ThemeSwitchProtocol","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIAppearanceContainer","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIContentContainer","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIFocusEnvironment","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIResponderStandardEditActions","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIScrollViewDelegate","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIStateRestoring","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UITableViewDataSource","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UITableViewDelegate","doc:\/\/org.cocoapods.ShengwangChatUIKit\/5UIKit23UITraitChangeObservableP","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UITraitEnvironment","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIUserActivityRestoring","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIViewControllerTransitioningDelegate"],"kind":"relationships","type":"conformsTo","title":"Conforms To"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/chatthreadlistcontroller"]},{"paths":["\/documentation\/shengwangchatuikit\/chatthreadlistcontroller"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objcMembers","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChatThreadListController","kind":"identifier"}],"languages":["swift"]}]}],"topicSections":[{"anchor":"Initializers","title":"Initializers","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadListController\/init(coder:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadListController\/init(groupId:)"],"generated":true},{"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadListController\/empty","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadListController\/groupId","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadListController\/loadingView","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadListController\/navigation","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadListController\/threads","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadListController\/topicList"],"generated":true,"anchor":"Instance-Properties","title":"Instance Properties"},{"generated":true,"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadListController\/createLoading()","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadListController\/handleThreadRequest(result:error:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadListController\/navigationClick(type:indexPath:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadListController\/pop()","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadListController\/requestThreadList()","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadListController\/viewDidLoad()"]},{"generated":true,"anchor":"Default-Implementations","title":"Default Implementations","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadListController\/ThemeSwitchProtocol-Implementations","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadListController\/UIScrollViewDelegate-Implementations","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadListController\/UITableViewDataSource-Implementations","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadListController\/UITableViewDelegate-Implementations"]}],"metadata":{"title":"ChatThreadListController","navigatorTitle":[{"kind":"identifier","text":"ChatThreadListController"}],"externalID":"c:@M@ShengwangChatUIKit@objc(cs)ChatThreadListController","roleHeading":"Class","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatThreadListController"}],"role":"symbol","symbolKind":"class","modules":[{"name":"ShengwangChatUIKit"}]},"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadListController","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UIScrollViewDelegate":{"type":"unresolvable","title":"UIKit.UIScrollViewDelegate","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIScrollViewDelegate"},"doc://org.cocoapods.ShengwangChatUIKit/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/s8SendableP"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatThreadListController/empty":{"title":"empty","url":"\/documentation\/shengwangchatuikit\/chatthreadlistcontroller\/empty","navigatorTitle":[{"text":"empty","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadListController\/empty","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"empty","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)EmptyStateView","text":"EmptyStateView","kind":"typeIdentifier"}],"role":"symbol","type":"topic","abstract":[],"kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatThreadListController/viewDidLoad()":{"abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"viewDidLoad"},{"text":"()","kind":"text"}],"role":"symbol","navigatorTitle":[{"text":"viewDidLoad","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/shengwangchatuikit\/chatthreadlistcontroller\/viewdidload()","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadListController\/viewDidLoad()","title":"viewDidLoad()"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UITableViewDataSource":{"type":"unresolvable","title":"UITableViewDataSource","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UITableViewDataSource"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatThreadListController/UITableViewDelegate-Implementations":{"url":"\/documentation\/shengwangchatuikit\/chatthreadlistcontroller\/uitableviewdelegate-implementations","abstract":[],"kind":"article","type":"topic","role":"collectionGroup","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadListController\/UITableViewDelegate-Implementations","title":"UITableViewDelegate Implementations"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)NSObject"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatThreadListController/ThemeSwitchProtocol-Implementations":{"title":"ThemeSwitchProtocol Implementations","abstract":[],"type":"topic","kind":"article","url":"\/documentation\/shengwangchatuikit\/chatthreadlistcontroller\/themeswitchprotocol-implementations","role":"collectionGroup","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadListController\/ThemeSwitchProtocol-Implementations"},"doc://org.cocoapods.ShengwangChatUIKit/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/s23CustomStringConvertibleP"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)NSExtensionRequestHandling":{"type":"unresolvable","title":"Foundation.NSExtensionRequestHandling","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)NSExtensionRequestHandling"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatThreadListController/loadingView":{"type":"topic","role":"symbol","title":"loadingView","abstract":[],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadListController\/loadingView","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"loadingView"},{"text":": ","kind":"text"},{"text":"LoadingView","kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)LoadingView"}],"url":"\/documentation\/shengwangchatuikit\/chatthreadlistcontroller\/loadingview","kind":"symbol","navigatorTitle":[{"text":"loadingView","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatThreadListController":{"type":"topic","title":"ChatThreadListController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChatThreadListController"}],"url":"\/documentation\/shengwangchatuikit\/chatthreadlistcontroller","navigatorTitle":[{"kind":"identifier","text":"ChatThreadListController"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadListController","kind":"symbol","abstract":[],"role":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/SQ"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatThreadListController/init(groupId:)":{"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"groupId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"init(groupId:)","abstract":[],"type":"topic","kind":"symbol","url":"\/documentation\/shengwangchatuikit\/chatthreadlistcontroller\/init(groupid:)","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadListController\/init(groupId:)","navigatorTitle":[{"text":"initWithGroupId:","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIUserActivityRestoring"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIFocusEnvironment"},"doc://org.cocoapods.ShengwangChatUIKit/objc(cs)UIViewController":{"type":"unresolvable","title":"UIViewController","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(cs)UIViewController"},"doc://org.cocoapods.ShengwangChatUIKit/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/s7CVarArgP"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatThreadListController/createLoading()":{"url":"\/documentation\/shengwangchatuikit\/chatthreadlistcontroller\/createloading()","title":"createLoading()","role":"symbol","navigatorTitle":[{"text":"createLoading","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadListController\/createLoading()","abstract":[{"type":"text","text":"Creates a loading view."}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"createLoading"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"LoadingView","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)LoadingView"}],"kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatThreadListController/navigation":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"navigation","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChatNavigationBar","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)ChatNavigationBar"}],"title":"navigation","url":"\/documentation\/shengwangchatuikit\/chatthreadlistcontroller\/navigation","abstract":[],"kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadListController\/navigation","navigatorTitle":[{"text":"navigation","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UIViewControllerTransitioningDelegate":{"type":"unresolvable","title":"UIKit.UIViewControllerTransitioningDelegate","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIViewControllerTransitioningDelegate"},"doc://org.cocoapods.ShengwangChatUIKit/5UIKit23UITraitChangeObservableP":{"type":"unresolvable","title":"UIKit.UITraitChangeObservable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/5UIKit23UITraitChangeObservableP"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIPasteConfigurationSupporting"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UITraitEnvironment"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIAppearanceContainer"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)NSCoding"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UIContentContainer":{"type":"unresolvable","title":"UIKit.UIContentContainer","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIContentContainer"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatThreadListController/requestThreadList()":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"requestThreadList","kind":"identifier"},{"text":"()","kind":"text"}],"title":"requestThreadList()","abstract":[],"type":"topic","kind":"symbol","url":"\/documentation\/shengwangchatuikit\/chatthreadlistcontroller\/requestthreadlist()","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadListController\/requestThreadList()","navigatorTitle":[{"text":"requestThreadList","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatThreadListController/navigationClick(type:indexPath:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"navigationClick","kind":"identifier"},{"text":"(","kind":"text"},{"text":"type","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ChatNavigationBarClickEvent","kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@E@ChatNavigationBarClickEvent"},{"kind":"text","text":", "},{"kind":"externalParam","text":"indexPath"},{"kind":"text","text":": "},{"text":"IndexPath","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":"?)"}],"url":"\/documentation\/shengwangchatuikit\/chatthreadlistcontroller\/navigationclick(type:indexpath:)","abstract":[{"type":"text","text":"Handles the navigation bar click events."}],"kind":"symbol","title":"navigationClick(type:indexPath:)","type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadListController\/navigationClick(type:indexPath:)","navigatorTitle":[{"kind":"identifier","text":"navigationClickWithType:indexPath:"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatThreadListController/threads":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadListController\/threads","url":"\/documentation\/shengwangchatuikit\/chatthreadlistcontroller\/threads","type":"topic","title":"threads","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"threads","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)EaseChatThread","text":"EaseChatThread","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"threads"}],"abstract":[]},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIResponderStandardEditActions"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatThreadListController/topicList":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"topicList","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UITableView","text":"UITableView","kind":"typeIdentifier"}],"title":"topicList","abstract":[],"type":"topic","kind":"symbol","url":"\/documentation\/shengwangchatuikit\/chatthreadlistcontroller\/topiclist","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadListController\/topicList","navigatorTitle":[{"text":"topicList","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/s8CopyableP":{"type":"unresolvable","title":"Swift.Copyable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/s8CopyableP"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ThemeSwitchProtocol":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ThemeSwitchProtocol","abstract":[{"type":"text","text":"When the system theme changes, you can use this static method to switch between the light and dark themes of the ease chat UIKit."}],"url":"\/documentation\/shengwangchatuikit\/themeswitchprotocol","type":"topic","kind":"symbol","role":"symbol","title":"ThemeSwitchProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"ThemeSwitchProtocol","kind":"identifier"}],"navigatorTitle":[{"text":"ThemeSwitchProtocol","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UIStateRestoring":{"type":"unresolvable","title":"UIKit.UIStateRestoring","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIStateRestoring"},"doc://org.cocoapods.ShengwangChatUIKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/s28CustomDebugStringConvertibleP"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatThreadListController/groupId":{"title":"groupId","url":"\/documentation\/shengwangchatuikit\/chatthreadlistcontroller\/groupid","navigatorTitle":[{"text":"groupId","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadListController\/groupId","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"groupId","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"role":"symbol","type":"topic","abstract":[],"kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatThreadListController/handleThreadRequest(result:error:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"handleThreadRequest","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"result"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit12CursorResulta","text":"CursorResult"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:18ShengwangChatUIKit05GroupB6Threada","kind":"typeIdentifier","text":"GroupChatThread"},{"text":">?, ","kind":"text"},{"text":"error","kind":"externalParam"},{"kind":"text","text":": "},{"text":"ChatError","preciseIdentifier":"s:18ShengwangChatUIKit0B5Errora","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"kind":"symbol","url":"\/documentation\/shengwangchatuikit\/chatthreadlistcontroller\/handlethreadrequest(result:error:)","type":"topic","title":"handleThreadRequest(result:error:)","abstract":[],"role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadListController\/handleThreadRequest(result:error:)","navigatorTitle":[{"text":"handleThreadRequestWithResult:error:","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/SH"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatThreadListController/pop()":{"url":"\/documentation\/shengwangchatuikit\/chatthreadlistcontroller\/pop()","navigatorTitle":[{"kind":"identifier","text":"pop"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadListController\/pop()","abstract":[],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"pop","kind":"identifier"},{"kind":"text","text":"()"}],"type":"topic","kind":"symbol","title":"pop()"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatThreadListController/UIScrollViewDelegate-Implementations":{"title":"UIScrollViewDelegate Implementations","url":"\/documentation\/shengwangchatuikit\/chatthreadlistcontroller\/uiscrollviewdelegate-implementations","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadListController\/UIScrollViewDelegate-Implementations","role":"collectionGroup","type":"topic","abstract":[],"kind":"article"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UITableViewDelegate":{"type":"unresolvable","title":"UITableViewDelegate","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UITableViewDelegate"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatThreadListController/init(coder:)":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadListController\/init(coder:)","kind":"symbol","title":"init(coder:)","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"coder"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSCoder","text":"NSCoder"},{"kind":"text","text":")"}],"abstract":[],"type":"topic","navigatorTitle":[{"text":"initWithCoder:","kind":"identifier"}],"role":"symbol","url":"\/documentation\/shengwangchatuikit\/chatthreadlistcontroller\/init(coder:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatThreadListController/UITableViewDataSource-Implementations":{"url":"\/documentation\/shengwangchatuikit\/chatthreadlistcontroller\/uitableviewdatasource-implementations","title":"UITableViewDataSource Implementations","role":"collectionGroup","type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadListController\/UITableViewDataSource-Implementations","abstract":[],"kind":"article"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"ChatThreadListController"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","value":[{"text":"ChatThreadListController","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"ChatThreadListController","kind":"identifier"}]},{"path":"\/topicSections","op":"replace","value":[{"title":"Instance Properties","generated":true,"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadListController\/empty","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadListController\/groupId","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadListController\/loadingView","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadListController\/navigation","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadListController\/threads","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadListController\/topicList"],"anchor":"Instance-Properties"},{"anchor":"Instance-Methods","title":"Instance Methods","generated":true,"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadListController\/createLoading()","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadListController\/handleThreadRequest(result:error:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadListController\/init(coder:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadListController\/init(groupId:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadListController\/navigationClick(type:indexPath:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadListController\/pop()","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadListController\/requestThreadList()","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadListController\/viewDidLoad()"]},{"anchor":"Default-Implementations","title":"Default Implementations","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadListController\/ThemeSwitchProtocol-Implementations","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadListController\/UIScrollViewDelegate-Implementations","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadListController\/UITableViewDataSource-Implementations","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadListController\/UITableViewDelegate-Implementations"],"generated":true}]},{"path":"\/relationshipsSections","op":"replace","value":[{"kind":"relationships","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(cs)UIViewController"],"type":"inheritsFrom","title":"Inherits From"},{"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ThemeSwitchProtocol","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UITableViewDataSource","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UITableViewDelegate"],"kind":"relationships","type":"conformsTo","title":"Conforms To"}]},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatThreadListController"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier","text":"UIViewController"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"empty","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadListController~1empty\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadListController~1empty\/fragments","value":[{"text":"empty","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadListController~1viewDidLoad()\/title","value":"viewDidLoad","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadListController~1viewDidLoad()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"viewDidLoad","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadListController~1loadingView\/title","value":"loadingView"},{"op":"replace","value":[{"kind":"identifier","text":"loadingView"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadListController~1loadingView\/fragments"},{"op":"replace","value":"ChatThreadListController","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadListController\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadListController\/fragments","value":[{"kind":"identifier","text":"ChatThreadListController"}]},{"value":[{"text":"ChatThreadListController","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadListController\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadListController~1init(groupId:)\/title","op":"replace","value":"initWithGroupId:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithGroupId:"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadListController~1init(groupId:)\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadListController~1createLoading()\/title","value":"createLoading","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"createLoading","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadListController~1createLoading()\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadListController~1navigation\/title","value":"navigation","op":"replace"},{"value":[{"kind":"identifier","text":"navigation"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadListController~1navigation\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadListController~1requestThreadList()\/title","value":"requestThreadList"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"requestThreadList"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadListController~1requestThreadList()\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadListController~1navigationClick(type:indexPath:)\/title","op":"replace","value":"navigationClickWithType:indexPath:"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadListController~1navigationClick(type:indexPath:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"navigationClickWithType:indexPath:"}]},{"value":"threads","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadListController~1threads\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadListController~1threads\/fragments","value":[{"text":"threads","kind":"identifier"}]},{"value":"topicList","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadListController~1topicList\/title"},{"op":"replace","value":[{"kind":"identifier","text":"topicList"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadListController~1topicList\/fragments"},{"value":"ThemeSwitchProtocol","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ThemeSwitchProtocol\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ThemeSwitchProtocol\/fragments","op":"replace","value":[{"text":"ThemeSwitchProtocol","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ThemeSwitchProtocol\/navigatorTitle","value":[{"text":"ThemeSwitchProtocol","kind":"identifier"}],"op":"replace"},{"value":"groupId","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadListController~1groupId\/title"},{"value":[{"text":"groupId","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadListController~1groupId\/fragments","op":"replace"},{"value":"handleThreadRequestWithResult:error:","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadListController~1handleThreadRequest(result:error:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadListController~1handleThreadRequest(result:error:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"handleThreadRequestWithResult:error:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadListController~1pop()\/title","value":"pop"},{"value":[{"text":"- ","kind":"text"},{"text":"pop","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadListController~1pop()\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadListController~1init(coder:)\/title","op":"replace","value":"initWithCoder:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadListController~1init(coder:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithCoder:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}