{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"ChatMessageStatus","kind":"identifier"}]}]}],"kind":"symbol","abstract":[{"text":"The status of ","type":"text"},{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatMessage","type":"reference","isActive":true},{"type":"text","text":"."}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/chatmessagestatus"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/chatmessagestatus"]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/SQ","doc:\/\/org.cocoapods.ShengwangChatUIKit\/SH","doc:\/\/org.cocoapods.ShengwangChatUIKit\/SY"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatMessageStatus","interfaceLanguage":"swift"},"metadata":{"externalID":"c:@M@ShengwangChatUIKit@E@ChatMessageStatus","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","modules":[{"name":"ShengwangChatUIKit"}],"title":"ChatMessageStatus","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatMessageStatus"}],"navigatorTitle":[{"text":"ChatMessageStatus","kind":"identifier"}]},"topicSections":[{"anchor":"Enumeration-Cases","title":"Enumeration Cases","generated":true,"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatMessageStatus\/delivered","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatMessageStatus\/failure","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatMessageStatus\/read","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatMessageStatus\/sending","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatMessageStatus\/succeed"]},{"generated":true,"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatMessageStatus\/init(rawValue:)"],"title":"Initializers","anchor":"Initializers"},{"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatMessageStatus\/Equatable-Implementations","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatMessageStatus\/RawRepresentable-Implementations"],"title":"Default Implementations","anchor":"Default-Implementations","generated":true}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatMessage":{"url":"\/documentation\/shengwangchatuikit\/chatmessage","abstract":[],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ChatMessage"}],"type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatMessage","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChatMessage"}],"title":"ChatMessage"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatMessageStatus/RawRepresentable-Implementations":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatMessageStatus\/RawRepresentable-Implementations","title":"RawRepresentable Implementations","role":"collectionGroup","kind":"article","type":"topic","abstract":[],"url":"\/documentation\/shengwangchatuikit\/chatmessagestatus\/rawrepresentable-implementations"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatMessageStatus":{"title":"ChatMessageStatus","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChatMessageStatus"}],"url":"\/documentation\/shengwangchatuikit\/chatmessagestatus","role":"symbol","abstract":[{"text":"The status of ","type":"text"},{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatMessage","type":"reference","isActive":true},{"type":"text","text":"."}],"type":"topic","navigatorTitle":[{"text":"ChatMessageStatus","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatMessageStatus"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatMessageStatus/sending":{"url":"\/documentation\/shengwangchatuikit\/chatmessagestatus\/sending","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"sending","kind":"identifier"}],"title":"ChatMessageStatus.sending","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatMessageStatus\/sending","abstract":[],"kind":"symbol","navigatorTitle":[{"text":"ChatMessageStatusSending","kind":"identifier"}],"role":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/SH"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatMessageStatus/delivered":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatMessageStatus\/delivered","url":"\/documentation\/shengwangchatuikit\/chatmessagestatus\/delivered","role":"symbol","title":"ChatMessageStatus.delivered","abstract":[],"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"delivered"}],"navigatorTitle":[{"text":"ChatMessageStatusDelivered","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatMessageStatus/init(rawValue:)":{"url":"\/documentation\/shengwangchatuikit\/chatmessagestatus\/init(rawvalue:)","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatMessageStatus\/init(rawValue:)","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"text":": ","kind":"text"},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"},{"text":")","kind":"text"}],"type":"topic","title":"init(rawValue:)","kind":"symbol","abstract":[]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatMessageStatus/Equatable-Implementations":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatMessageStatus\/Equatable-Implementations","url":"\/documentation\/shengwangchatuikit\/chatmessagestatus\/equatable-implementations","role":"collectionGroup","title":"Equatable Implementations","abstract":[],"kind":"article"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatMessageStatus/failure":{"url":"\/documentation\/shengwangchatuikit\/chatmessagestatus\/failure","type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatMessageStatus\/failure","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ChatMessageStatusFailure"}],"abstract":[],"kind":"symbol","title":"ChatMessageStatus.failure","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"failure","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/SQ"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatMessageStatus/succeed":{"navigatorTitle":[{"kind":"identifier","text":"ChatMessageStatusSucceed"}],"url":"\/documentation\/shengwangchatuikit\/chatmessagestatus\/succeed","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"succeed","kind":"identifier"}],"role":"symbol","title":"ChatMessageStatus.succeed","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatMessageStatus\/succeed","kind":"symbol","abstract":[]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatMessageStatus/read":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatMessageStatus\/read","url":"\/documentation\/shengwangchatuikit\/chatmessagestatus\/read","role":"symbol","title":"ChatMessageStatus.read","abstract":[],"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"read","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ChatMessageStatusRead"}]},"doc://org.cocoapods.ShengwangChatUIKit/SY":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/SY","title":"Swift.RawRepresentable","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration","op":"replace"},{"value":"ChatMessageStatus","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"enum","op":"replace"},{"op":"replace","value":[{"text":"ChatMessageStatus","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":[{"text":"ChatMessageStatus","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","op":"replace","value":[{"anchor":"Enumeration-Cases","title":"Enumeration Cases","generated":true,"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatMessageStatus\/delivered","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatMessageStatus\/failure","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatMessageStatus\/read","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatMessageStatus\/sending","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatMessageStatus\/succeed"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChatMessageStatus"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSUInteger","text":"NSUInteger"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatMessageStatus\/title","value":"ChatMessageStatus","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatMessageStatus\/fragments","value":[{"text":"ChatMessageStatus","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatMessageStatus\/navigatorTitle","value":[{"kind":"identifier","text":"ChatMessageStatus"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatMessageStatus~1sending\/title","value":"ChatMessageStatusSending","op":"replace"},{"value":[{"text":"ChatMessageStatusSending","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatMessageStatus~1sending\/fragments"},{"value":"ChatMessageStatusDelivered","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatMessageStatus~1delivered\/title"},{"value":[{"text":"ChatMessageStatusDelivered","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatMessageStatus~1delivered\/fragments"},{"value":"ChatMessageStatusFailure","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatMessageStatus~1failure\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatMessageStatus~1failure\/fragments","op":"replace","value":[{"text":"ChatMessageStatusFailure","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatMessageStatus~1succeed\/title","value":"ChatMessageStatusSucceed","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatMessageStatus~1succeed\/fragments","value":[{"kind":"identifier","text":"ChatMessageStatusSucceed"}],"op":"replace"},{"op":"replace","value":"ChatMessageStatusRead","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatMessageStatus~1read\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatMessageStatus~1read\/fragments","value":[{"text":"ChatMessageStatusRead","kind":"identifier"}]}]}]}