{"metadata":{"modules":[{"name":"ShengwangChatUIKit"}],"role":"symbol","symbolKind":"class","roleHeading":"Class","title":"ChatUIKitClient","navigatorTitle":[{"text":"ChatUIKitClient","kind":"identifier"}],"externalID":"c:@M@ShengwangChatUIKit@objc(cs)ChatUIKitClient","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChatUIKitClient","kind":"identifier"}]},"variants":[{"paths":["\/documentation\/shengwangchatuikit\/chatuikitclient"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/chatuikitclient"]}],"topicSections":[{"generated":true,"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatUIKitClient\/option","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatUIKitClient\/userService"],"title":"Instance Properties","anchor":"Instance-Properties"},{"generated":true,"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatUIKitClient\/login(user:token:completion:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatUIKitClient\/logout(unbindNotificationDeviceToken:completion:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatUIKitClient\/refreshToken(token:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatUIKitClient\/registerUserStateListener(_:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatUIKitClient\/setup(appId:option:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatUIKitClient\/unregisterThemes()","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatUIKitClient\/unregisterUserStateListener(_:)"]},{"title":"Type Properties","anchor":"Type-Properties","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatUIKitClient\/shared"],"generated":true},{"title":"Default Implementations","generated":true,"anchor":"Default-Implementations","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatUIKitClient\/AgoraChatContactManagerDelegate-Implementations"]}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatUIKitClient"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit"]]},"relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(cs)NSObject"],"type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)AgoraChatContactManagerDelegate","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)NSObject","doc:\/\/org.cocoapods.ShengwangChatUIKit\/s7CVarArgP","doc:\/\/org.cocoapods.ShengwangChatUIKit\/s8CopyableP","doc:\/\/org.cocoapods.ShengwangChatUIKit\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.ShengwangChatUIKit\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.ShengwangChatUIKit\/SQ","doc:\/\/org.cocoapods.ShengwangChatUIKit\/SH"],"kind":"relationships","type":"conformsTo","title":"Conforms To"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objcMembers","kind":"attribute"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChatUIKitClient","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://org.cocoapods.ShengwangChatUIKit/SQ":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/SQ","title":"Swift.Equatable"},"doc://org.cocoapods.ShengwangChatUIKit/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/s7CVarArgP","title":"Swift.CVarArg"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatUIKitClient/unregisterUserStateListener(_:)":{"navigatorTitle":[{"text":"unregisterUserStateListener:","kind":"identifier"}],"abstract":[{"type":"text","text":"Remove monitoring of user status changes."}],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"unregisterUserStateListener"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(pl)UserStateChangedListener","kind":"typeIdentifier","text":"UserStateChangedListener"},{"text":")","kind":"text"}],"url":"\/documentation\/shengwangchatuikit\/chatuikitclient\/unregisteruserstatelistener(_:)","role":"symbol","title":"unregisterUserStateListener(_:)","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatUIKitClient\/unregisterUserStateListener(_:)","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatUIKitClient/login(user:token:completion:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"login","kind":"identifier"},{"text":"(","kind":"text"},{"text":"user","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ChatUserProfileProtocol","kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(pl)ChatUserProfileProtocol"},{"text":", ","kind":"text"},{"text":"token","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit0B5Errora","text":"ChatError"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"role":"symbol","url":"\/documentation\/shengwangchatuikit\/chatuikitclient\/login(user:token:completion:)","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatUIKitClient\/login(user:token:completion:)","title":"login(user:token:completion:)","kind":"symbol","abstract":[{"type":"text","text":"Login user."}],"navigatorTitle":[{"kind":"identifier","text":"loginWithUser:token:completion:"}],"type":"topic"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatUIKitClient/init":{"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatUIKitClient\/init","url":"\/documentation\/shengwangchatuikit\/chatuikitclient\/init","navigatorTitle":[{"text":"init","kind":"identifier"}],"type":"topic","title":"init","abstract":[],"role":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatUIKitClient/refreshToken(token:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"refreshToken"},{"text":"(","kind":"text"},{"text":"token","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","url":"\/documentation\/shengwangchatuikit\/chatuikitclient\/refreshtoken(token:)","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatUIKitClient\/refreshToken(token:)","title":"refreshToken(token:)","kind":"symbol","abstract":[{"text":"Refreshes the user chat token when receiving the ","type":"text"},{"code":"ChatClientListener.onUserTokenWillExpired","type":"codeVoice"},{"type":"text","text":" callback."}],"navigatorTitle":[{"text":"refreshWithToken:","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.ShengwangChatUIKit/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/SH"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatUIKitClient/option":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"option","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)ChatUIKitOptions","text":"ChatUIKitOptions","kind":"typeIdentifier"}],"role":"symbol","url":"\/documentation\/shengwangchatuikit\/chatuikitclient\/option","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatUIKitClient\/option","title":"option","kind":"symbol","abstract":[{"type":"text","text":"Options function wrapper."}],"navigatorTitle":[{"text":"option","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatUIKitClient":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ChatUIKitClient","kind":"identifier"}],"type":"topic","abstract":[],"navigatorTitle":[{"text":"ChatUIKitClient","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatUIKitClient","role":"symbol","title":"ChatUIKitClient","url":"\/documentation\/shengwangchatuikit\/chatuikitclient"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatUIKitClient/AgoraChatContactManagerDelegate-Implementations":{"kind":"article","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatUIKitClient\/AgoraChatContactManagerDelegate-Implementations","url":"\/documentation\/shengwangchatuikit\/chatuikitclient\/agorachatcontactmanagerdelegate-implementations","type":"topic","title":"AgoraChatContactManagerDelegate Implementations","abstract":[],"role":"collectionGroup"},"doc://org.cocoapods.ShengwangChatUIKit/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(cs)NSObject"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)AgoraChatContactManagerDelegate":{"title":"AgoraChatContactManagerDelegate","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)AgoraChatContactManagerDelegate"},"doc://org.cocoapods.ShengwangChatUIKit/s8CopyableP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/s8CopyableP","title":"Swift.Copyable"},"doc://org.cocoapods.ShengwangChatUIKit/s23CustomStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)NSObject":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatUIKitClient/registerUserStateListener(_:)":{"url":"\/documentation\/shengwangchatuikit\/chatuikitclient\/registeruserstatelistener(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"text":"registerUserStateListener:","kind":"identifier"}],"abstract":[{"type":"text","text":"Register a user to listen for callbacks that monitor user status changes."}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatUIKitClient\/registerUserStateListener(_:)","title":"registerUserStateListener(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"registerUserStateListener"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(pl)UserStateChangedListener","text":"UserStateChangedListener","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatUIKitClient/unregisterThemes()":{"kind":"symbol","url":"\/documentation\/shengwangchatuikit\/chatuikitclient\/unregisterthemes()","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatUIKitClient\/unregisterThemes()","type":"topic","role":"symbol","title":"unregisterThemes()","navigatorTitle":[{"text":"unregisterThemes","kind":"identifier"}],"abstract":[{"text":"unregister theme.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"unregisterThemes"},{"text":"()","kind":"text"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatUIKitClient/userService":{"url":"\/documentation\/shengwangchatuikit\/chatuikitclient\/userservice","kind":"symbol","type":"topic","navigatorTitle":[{"text":"userService","kind":"identifier"}],"abstract":[{"text":"User-related protocol implementation class.","type":"text"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatUIKitClient\/userService","title":"userService","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"userService","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UserServiceProtocol","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(pl)UserServiceProtocol","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatUIKitClient/logout(unbindNotificationDeviceToken:completion:)":{"navigatorTitle":[{"kind":"identifier","text":"logoutWithUnbindNotificationDeviceToken:completion:"}],"abstract":[{"text":"Logout user","type":"text"}],"title":"logout(unbindNotificationDeviceToken:completion:)","type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatUIKitClient\/logout(unbindNotificationDeviceToken:completion:)","url":"\/documentation\/shengwangchatuikit\/chatuikitclient\/logout(unbindnotificationdevicetoken:completion:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"logout","kind":"identifier"},{"kind":"text","text":"("},{"text":"unbindNotificationDeviceToken","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"text":"ChatError","kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit0B5Errora"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")"}],"role":"symbol","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatUIKitClient/setup(appId:option:)":{"type":"topic","title":"setup(appId:option:)","kind":"symbol","abstract":[{"type":"text","text":"Initializes the ease chat UIKit."}],"role":"symbol","url":"\/documentation\/shengwangchatuikit\/chatuikitclient\/setup(appid:option:)","navigatorTitle":[{"text":"setupWithAppId:option:","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatUIKitClient\/setup(appId:option:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setup"},{"kind":"text","text":"("},{"kind":"externalParam","text":"appId"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"text":"option","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"ChatOptions","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)ChatOptions"},{"text":"?) -> ","kind":"text"},{"text":"ChatError","preciseIdentifier":"s:18ShengwangChatUIKit0B5Errora","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatUIKitClient/shared":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatUIKitClient\/shared","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"shared","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChatUIKitClient","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)ChatUIKitClient"}],"title":"shared","role":"symbol","url":"\/documentation\/shengwangchatuikit\/chatuikitclient\/shared","abstract":[],"type":"topic","kind":"symbol","navigatorTitle":[{"text":"shared","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"ChatUIKitClient"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"text":"ChatUIKitClient","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":[{"text":"ChatUIKitClient","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"op":"replace","path":"\/topicSections","value":[{"generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatUIKitClient\/option","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatUIKitClient\/userService"],"title":"Instance Properties"},{"title":"Instance Methods","generated":true,"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatUIKitClient\/init","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatUIKitClient\/login(user:token:completion:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatUIKitClient\/logout(unbindNotificationDeviceToken:completion:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatUIKitClient\/refreshToken(token:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatUIKitClient\/registerUserStateListener(_:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatUIKitClient\/setup(appId:option:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatUIKitClient\/unregisterThemes()","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatUIKitClient\/unregisterUserStateListener(_:)"],"anchor":"Instance-Methods"},{"anchor":"Type-Properties","generated":true,"title":"Type Properties","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatUIKitClient\/shared"]},{"generated":true,"title":"Default Implementations","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatUIKitClient\/AgoraChatContactManagerDelegate-Implementations"],"anchor":"Default-Implementations"}]},{"op":"replace","path":"\/relationshipsSections","value":[{"type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(cs)NSObject"],"title":"Inherits From"},{"title":"Conforms To","kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)AgoraChatContactManagerDelegate"]}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChatUIKitClient","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"value":"unregisterUserStateListener:","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatUIKitClient~1unregisterUserStateListener(_:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatUIKitClient~1unregisterUserStateListener(_:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"unregisterUserStateListener:"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatUIKitClient~1login(user:token:completion:)\/title","value":"loginWithUser:token:completion:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatUIKitClient~1login(user:token:completion:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"loginWithUser:token:completion:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatUIKitClient~1refreshToken(token:)\/title","value":"refreshWithToken:"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatUIKitClient~1refreshToken(token:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"refreshWithToken:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatUIKitClient~1option\/title","value":"option","op":"replace"},{"op":"replace","value":[{"text":"option","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatUIKitClient~1option\/fragments"},{"value":"ChatUIKitClient","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatUIKitClient\/title"},{"op":"replace","value":[{"text":"ChatUIKitClient","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatUIKitClient\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatUIKitClient\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"ChatUIKitClient"}]},{"op":"replace","value":"registerUserStateListener:","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatUIKitClient~1registerUserStateListener(_:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatUIKitClient~1registerUserStateListener(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"registerUserStateListener:"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatUIKitClient~1unregisterThemes()\/title","op":"replace","value":"unregisterThemes"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatUIKitClient~1unregisterThemes()\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"unregisterThemes"}]},{"value":"userService","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatUIKitClient~1userService\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatUIKitClient~1userService\/fragments","value":[{"kind":"identifier","text":"userService"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatUIKitClient~1logout(unbindNotificationDeviceToken:completion:)\/title","value":"logoutWithUnbindNotificationDeviceToken:completion:"},{"value":[{"text":"- ","kind":"text"},{"text":"logoutWithUnbindNotificationDeviceToken:completion:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatUIKitClient~1logout(unbindNotificationDeviceToken:completion:)\/fragments","op":"replace"},{"op":"replace","value":"setupWithAppId:option:","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatUIKitClient~1setup(appId:option:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatUIKitClient~1setup(appId:option:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"setupWithAppId:option:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatUIKitClient~1shared\/title","value":"shared","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatUIKitClient~1shared\/fragments","value":[{"kind":"identifier","text":"shared"}]}]}]}