{"kind":"symbol","topicSections":[{"title":"Initializers","generated":true,"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadParticipantsController\/init(chatThread:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadParticipantsController\/init(coder:)"],"anchor":"Initializers"},{"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadParticipantsController\/navigation","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadParticipantsController\/participants","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadParticipantsController\/participantsList","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadParticipantsController\/profile"],"generated":true},{"anchor":"Instance-Methods","generated":true,"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadParticipantsController\/cellForRowAt(indexPath:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadParticipantsController\/createNavigation()","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadParticipantsController\/fetchParticipants()","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadParticipantsController\/navigationClick(type:indexPath:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadParticipantsController\/pop()","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadParticipantsController\/removeMember(user:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadParticipantsController\/requestGroupDetail()","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadParticipantsController\/viewDidLoad()"],"title":"Instance Methods"},{"anchor":"Default-Implementations","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadParticipantsController\/ThemeSwitchProtocol-Implementations","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadParticipantsController\/UIScrollViewDelegate-Implementations","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadParticipantsController\/UITableViewDataSource-Implementations","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadParticipantsController\/UITableViewDelegate-Implementations"],"title":"Default Implementations","generated":true}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objcMembers","kind":"attribute"},{"kind":"text","text":" "},{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatThreadParticipantsController"}],"platforms":["iOS"],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadParticipantsController","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit"]]},"relationshipsSections":[{"type":"inheritsFrom","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(cs)UIViewController"],"title":"Inherits From","kind":"relationships"},{"type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)NSCoding","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)NSExtensionRequestHandling","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)NSObject","doc:\/\/org.cocoapods.ShengwangChatUIKit\/s7CVarArgP","doc:\/\/org.cocoapods.ShengwangChatUIKit\/s8CopyableP","doc:\/\/org.cocoapods.ShengwangChatUIKit\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.ShengwangChatUIKit\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.ShengwangChatUIKit\/SQ","doc:\/\/org.cocoapods.ShengwangChatUIKit\/SH","doc:\/\/org.cocoapods.ShengwangChatUIKit\/s8SendableP","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ThemeSwitchProtocol","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIAppearanceContainer","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIContentContainer","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIFocusEnvironment","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIResponderStandardEditActions","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIScrollViewDelegate","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIStateRestoring","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UITableViewDataSource","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UITableViewDelegate","doc:\/\/org.cocoapods.ShengwangChatUIKit\/5UIKit23UITraitChangeObservableP","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UITraitEnvironment","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIUserActivityRestoring","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIViewControllerTransitioningDelegate"],"title":"Conforms To"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/shengwangchatuikit\/chatthreadparticipantscontroller"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/shengwangchatuikit\/chatthreadparticipantscontroller"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"externalID":"c:@M@ShengwangChatUIKit@objc(cs)ChatThreadParticipantsController","symbolKind":"class","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ChatThreadParticipantsController","kind":"identifier"}],"navigatorTitle":[{"text":"ChatThreadParticipantsController","kind":"identifier"}],"role":"symbol","title":"ChatThreadParticipantsController","roleHeading":"Class","modules":[{"name":"ShengwangChatUIKit"}]},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatThreadParticipantsController/UITableViewDelegate-Implementations":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadParticipantsController\/UITableViewDelegate-Implementations","title":"UITableViewDelegate Implementations","kind":"article","abstract":[],"role":"collectionGroup","url":"\/documentation\/shengwangchatuikit\/chatthreadparticipantscontroller\/uitableviewdelegate-implementations"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatThreadParticipantsController/init(coder:)":{"url":"\/documentation\/shengwangchatuikit\/chatthreadparticipantscontroller\/init(coder:)","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"coder"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder"},{"kind":"text","text":")"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadParticipantsController\/init(coder:)","abstract":[],"kind":"symbol","title":"init(coder:)","role":"symbol","navigatorTitle":[{"text":"initWithCoder:","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIResponderStandardEditActions"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)NSObject"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatThreadParticipantsController/cellForRowAt(indexPath:)":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadParticipantsController\/cellForRowAt(indexPath:)","title":"cellForRowAt(indexPath:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cellForRowAt"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"indexPath"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation9IndexPathV","text":"IndexPath","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"UITableViewCell","preciseIdentifier":"c:objc(cs)UITableViewCell"}],"abstract":[],"role":"symbol","navigatorTitle":[{"text":"cellForRowAtIndexPath:","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/chatthreadparticipantscontroller\/cellforrowat(indexpath:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatThreadParticipantsController":{"title":"ChatThreadParticipantsController","kind":"symbol","type":"topic","abstract":[],"url":"\/documentation\/shengwangchatuikit\/chatthreadparticipantscontroller","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ChatThreadParticipantsController","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ChatThreadParticipantsController"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadParticipantsController"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatThreadParticipantsController/pop()":{"url":"\/documentation\/shengwangchatuikit\/chatthreadparticipantscontroller\/pop()","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"pop","kind":"identifier"},{"text":"()","kind":"text"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadParticipantsController\/pop()","abstract":[],"kind":"symbol","title":"pop()","role":"symbol","navigatorTitle":[{"text":"pop","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatThreadParticipantsController/participants":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadParticipantsController\/participants","title":"participants","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"participants"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(pl)ChatUserProfileProtocol","kind":"typeIdentifier","text":"ChatUserProfileProtocol"},{"text":"]","kind":"text"}],"abstract":[{"text":"The array of participants in the group.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"participants"}],"url":"\/documentation\/shengwangchatuikit\/chatthreadparticipantscontroller\/participants"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatThreadParticipantsController/profile":{"url":"\/documentation\/shengwangchatuikit\/chatthreadparticipantscontroller\/profile","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"profile","kind":"identifier"},{"kind":"text","text":": "},{"text":"GroupChatThread","kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit05GroupB6Threada"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadParticipantsController\/profile","abstract":[],"kind":"symbol","title":"profile","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"profile"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatThreadParticipantsController/UITableViewDataSource-Implementations":{"abstract":[],"title":"UITableViewDataSource Implementations","type":"topic","role":"collectionGroup","url":"\/documentation\/shengwangchatuikit\/chatthreadparticipantscontroller\/uitableviewdatasource-implementations","kind":"article","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadParticipantsController\/UITableViewDataSource-Implementations"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UITableViewDataSource":{"type":"unresolvable","title":"UITableViewDataSource","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UITableViewDataSource"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UIContentContainer":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIContentContainer","title":"UIKit.UIContentContainer"},"doc://org.cocoapods.ShengwangChatUIKit/SH":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/SH","title":"Swift.Hashable"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatThreadParticipantsController/fetchParticipants()":{"url":"\/documentation\/shengwangchatuikit\/chatthreadparticipantscontroller\/fetchparticipants()","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"fetchParticipants"},{"text":"()","kind":"text"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadParticipantsController\/fetchParticipants()","abstract":[],"kind":"symbol","title":"fetchParticipants()","role":"symbol","navigatorTitle":[{"text":"fetchParticipants","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UIStateRestoring":{"title":"UIKit.UIStateRestoring","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIStateRestoring","type":"unresolvable"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ThemeSwitchProtocol":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ThemeSwitchProtocol","abstract":[{"type":"text","text":"When the system theme changes, you can use this static method to switch between the light and dark themes of the ease chat UIKit."}],"url":"\/documentation\/shengwangchatuikit\/themeswitchprotocol","type":"topic","kind":"symbol","role":"symbol","title":"ThemeSwitchProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"ThemeSwitchProtocol","kind":"identifier"}],"navigatorTitle":[{"text":"ThemeSwitchProtocol","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UIPasteConfigurationSupporting":{"title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIPasteConfigurationSupporting","type":"unresolvable"},"doc://org.cocoapods.ShengwangChatUIKit/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatThreadParticipantsController/navigation":{"url":"\/documentation\/shengwangchatuikit\/chatthreadparticipantscontroller\/navigation","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"navigation"},{"kind":"text","text":": "},{"text":"ChatNavigationBar","kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)ChatNavigationBar"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadParticipantsController\/navigation","abstract":[],"kind":"symbol","title":"navigation","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"navigation"}]},"doc://org.cocoapods.ShengwangChatUIKit/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://org.cocoapods.ShengwangChatUIKit/s7CVarArgP":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatThreadParticipantsController/ThemeSwitchProtocol-Implementations":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadParticipantsController\/ThemeSwitchProtocol-Implementations","title":"ThemeSwitchProtocol Implementations","kind":"article","abstract":[],"role":"collectionGroup","url":"\/documentation\/shengwangchatuikit\/chatthreadparticipantscontroller\/themeswitchprotocol-implementations"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatThreadParticipantsController/UIScrollViewDelegate-Implementations":{"url":"\/documentation\/shengwangchatuikit\/chatthreadparticipantscontroller\/uiscrollviewdelegate-implementations","type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadParticipantsController\/UIScrollViewDelegate-Implementations","abstract":[],"kind":"article","title":"UIScrollViewDelegate Implementations","role":"collectionGroup"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UITraitEnvironment":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UITraitEnvironment","type":"unresolvable","title":"UIKit.UITraitEnvironment"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)NSCoding":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)NSCoding","type":"unresolvable","title":"Foundation.NSCoding"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatThreadParticipantsController/removeMember(user:)":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadParticipantsController\/removeMember(user:)","title":"removeMember(user:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"removeMember"},{"kind":"text","text":"("},{"text":"user","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ChatUserProfileProtocol","kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(pl)ChatUserProfileProtocol"},{"text":")","kind":"text"}],"abstract":[],"role":"symbol","navigatorTitle":[{"text":"removeMemberWithUser:","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/chatthreadparticipantscontroller\/removemember(user:)"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIFocusEnvironment"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatThreadParticipantsController/init(chatThread:)":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadParticipantsController\/init(chatThread:)","title":"init(chatThread:)","kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"chatThread","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:18ShengwangChatUIKit05GroupB6Threada","text":"GroupChatThread","kind":"typeIdentifier"},{"kind":"text","text":")"}],"abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithChatThread:"}],"url":"\/documentation\/shengwangchatuikit\/chatthreadparticipantscontroller\/init(chatthread:)"},"doc://org.cocoapods.ShengwangChatUIKit/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/s8SendableP"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UIViewControllerTransitioningDelegate":{"type":"unresolvable","title":"UIKit.UIViewControllerTransitioningDelegate","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIViewControllerTransitioningDelegate"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatThreadParticipantsController/createNavigation()":{"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Creates and returns a navigation bar for the ChatThreadParticipantsController."}],"url":"\/documentation\/shengwangchatuikit\/chatthreadparticipantscontroller\/createnavigation()","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadParticipantsController\/createNavigation()","title":"createNavigation()","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"createNavigation"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"createNavigation","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)ChatNavigationBar","kind":"typeIdentifier","text":"ChatNavigationBar"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatThreadParticipantsController/navigationClick(type:indexPath:)":{"url":"\/documentation\/shengwangchatuikit\/chatthreadparticipantscontroller\/navigationclick(type:indexpath:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"navigationClick","kind":"identifier"},{"text":"(","kind":"text"},{"text":"type","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ChatNavigationBarClickEvent","kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@E@ChatNavigationBarClickEvent"},{"kind":"text","text":", "},{"kind":"externalParam","text":"indexPath"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"text":"?)","kind":"text"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadParticipantsController\/navigationClick(type:indexPath:)","abstract":[{"type":"text","text":"Handles the navigation bar click events."}],"kind":"symbol","title":"navigationClick(type:indexPath:)","role":"symbol","navigatorTitle":[{"text":"navigationClickWithType:indexPath:","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UIAppearanceContainer":{"title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIAppearanceContainer","type":"unresolvable"},"doc://org.cocoapods.ShengwangChatUIKit/s8CopyableP":{"title":"Swift.Copyable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/s8CopyableP","type":"unresolvable"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UIActivityItemsConfigurationProviding":{"title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIActivityItemsConfigurationProviding","type":"unresolvable"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatThreadParticipantsController/viewDidLoad()":{"url":"\/documentation\/shengwangchatuikit\/chatthreadparticipantscontroller\/viewdidload()","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"viewDidLoad","kind":"identifier"},{"kind":"text","text":"()"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadParticipantsController\/viewDidLoad()","abstract":[],"kind":"symbol","title":"viewDidLoad()","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"viewDidLoad"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatThreadParticipantsController/participantsList":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadParticipantsController\/participantsList","title":"participantsList","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"participantsList","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UITableView","text":"UITableView","kind":"typeIdentifier"}],"abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"participantsList"}],"url":"\/documentation\/shengwangchatuikit\/chatthreadparticipantscontroller\/participantslist"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)NSExtensionRequestHandling":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)NSExtensionRequestHandling","title":"Foundation.NSExtensionRequestHandling"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UITableViewDelegate":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UITableViewDelegate","title":"UITableViewDelegate"},"doc://org.cocoapods.ShengwangChatUIKit/5UIKit23UITraitChangeObservableP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/5UIKit23UITraitChangeObservableP","title":"UIKit.UITraitChangeObservable"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UIScrollViewDelegate":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIScrollViewDelegate","title":"UIKit.UIScrollViewDelegate"},"doc://org.cocoapods.ShengwangChatUIKit/objc(cs)UIViewController":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(cs)UIViewController","title":"UIViewController"},"doc://org.cocoapods.ShengwangChatUIKit/SQ":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/SQ","title":"Swift.Equatable"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIUserActivityRestoring","title":"UIKit.UIUserActivityRestoring"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatThreadParticipantsController/requestGroupDetail()":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadParticipantsController\/requestGroupDetail()","title":"requestGroupDetail()","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"requestGroupDetail"},{"text":"()","kind":"text"}],"abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"requestGroupDetail"}],"url":"\/documentation\/shengwangchatuikit\/chatthreadparticipantscontroller\/requestgroupdetail()"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","value":"ChatThreadParticipantsController","path":"\/metadata\/title"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ChatThreadParticipantsController"}],"op":"replace"},{"value":[{"text":"ChatThreadParticipantsController","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"op":"replace","path":"\/topicSections","value":[{"generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadParticipantsController\/navigation","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadParticipantsController\/participants","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadParticipantsController\/participantsList","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadParticipantsController\/profile"],"title":"Instance Properties"},{"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadParticipantsController\/cellForRowAt(indexPath:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadParticipantsController\/createNavigation()","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadParticipantsController\/fetchParticipants()","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadParticipantsController\/init(chatThread:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadParticipantsController\/init(coder:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadParticipantsController\/navigationClick(type:indexPath:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadParticipantsController\/pop()","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadParticipantsController\/removeMember(user:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadParticipantsController\/requestGroupDetail()","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadParticipantsController\/viewDidLoad()"],"title":"Instance Methods","generated":true,"anchor":"Instance-Methods"},{"title":"Default Implementations","generated":true,"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadParticipantsController\/ThemeSwitchProtocol-Implementations","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadParticipantsController\/UIScrollViewDelegate-Implementations","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadParticipantsController\/UITableViewDataSource-Implementations","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadParticipantsController\/UITableViewDelegate-Implementations"],"anchor":"Default-Implementations"}]},{"value":[{"type":"inheritsFrom","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(cs)UIViewController"],"title":"Inherits From","kind":"relationships"},{"title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ThemeSwitchProtocol","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UITableViewDataSource","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UITableViewDelegate"],"type":"conformsTo"}],"path":"\/relationshipsSections","op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"text":"ChatThreadParticipantsController","kind":"identifier"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadParticipantsController~1init(coder:)\/title","op":"replace","value":"initWithCoder:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadParticipantsController~1init(coder:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithCoder:"}]},{"value":"cellForRowAtIndexPath:","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadParticipantsController~1cellForRowAt(indexPath:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadParticipantsController~1cellForRowAt(indexPath:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"cellForRowAtIndexPath:"}]},{"value":"ChatThreadParticipantsController","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadParticipantsController\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadParticipantsController\/fragments","value":[{"text":"ChatThreadParticipantsController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadParticipantsController\/navigatorTitle","value":[{"kind":"identifier","text":"ChatThreadParticipantsController"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadParticipantsController~1pop()\/title","op":"replace","value":"pop"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadParticipantsController~1pop()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"pop"}],"op":"replace"},{"op":"replace","value":"participants","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadParticipantsController~1participants\/title"},{"value":[{"text":"participants","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadParticipantsController~1participants\/fragments"},{"value":"profile","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadParticipantsController~1profile\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadParticipantsController~1profile\/fragments","value":[{"text":"profile","kind":"identifier"}],"op":"replace"},{"value":"fetchParticipants","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadParticipantsController~1fetchParticipants()\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadParticipantsController~1fetchParticipants()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"fetchParticipants","kind":"identifier"}],"op":"replace"},{"value":"ThemeSwitchProtocol","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ThemeSwitchProtocol\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ThemeSwitchProtocol\/fragments","value":[{"text":"ThemeSwitchProtocol","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"ThemeSwitchProtocol"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ThemeSwitchProtocol\/navigatorTitle","op":"replace"},{"value":"navigation","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadParticipantsController~1navigation\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadParticipantsController~1navigation\/fragments","value":[{"text":"navigation","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadParticipantsController~1removeMember(user:)\/title","op":"replace","value":"removeMemberWithUser:"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadParticipantsController~1removeMember(user:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"removeMemberWithUser:","kind":"identifier"}]},{"value":"initWithChatThread:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadParticipantsController~1init(chatThread:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadParticipantsController~1init(chatThread:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithChatThread:"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadParticipantsController~1createNavigation()\/title","op":"replace","value":"createNavigation"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"createNavigation"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadParticipantsController~1createNavigation()\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadParticipantsController~1navigationClick(type:indexPath:)\/title","value":"navigationClickWithType:indexPath:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadParticipantsController~1navigationClick(type:indexPath:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"navigationClickWithType:indexPath:"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadParticipantsController~1viewDidLoad()\/title","value":"viewDidLoad","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"viewDidLoad","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadParticipantsController~1viewDidLoad()\/fragments"},{"value":"participantsList","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadParticipantsController~1participantsList\/title","op":"replace"},{"value":[{"text":"participantsList","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadParticipantsController~1participantsList\/fragments"},{"value":"requestGroupDetail","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadParticipantsController~1requestGroupDetail()\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadParticipantsController~1requestGroupDetail()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"requestGroupDetail"}],"op":"replace"}]}]}