{"relationshipsSections":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(cs)NSObject"],"type":"inheritsFrom"},{"kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)NSObject","doc:\/\/org.cocoapods.ShengwangChatUIKit\/s7CVarArgP","doc:\/\/org.cocoapods.ShengwangChatUIKit\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.ShengwangChatUIKit\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.ShengwangChatUIKit\/SQ","doc:\/\/org.cocoapods.ShengwangChatUIKit\/SH"],"title":"Conforms To"}],"abstract":[{"type":"text","text":"An object containing UI components that are used through the EaseChatUIKit SDK."}],"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/componentsregister"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/componentsregister"]}],"topicSections":[{"anchor":"Instance-Properties","title":"Instance Properties","generated":true,"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ComponentsRegister\/ChatAlertCell","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ComponentsRegister\/ChatAudioMessageCell","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ComponentsRegister\/ChatCombineCell","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ComponentsRegister\/ChatContactMessageCell","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ComponentsRegister\/ChatCustomMessageCell","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ComponentsRegister\/ChatFileMessageCell","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ComponentsRegister\/ChatImageMessageCell","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ComponentsRegister\/ChatLocationCell","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ComponentsRegister\/ChatTextMessageCell","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ComponentsRegister\/ChatVideoMessageCell","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ComponentsRegister\/ContactInfoController","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ComponentsRegister\/ContactViewService","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ComponentsRegister\/ContactsCell","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ComponentsRegister\/ContactsController","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ComponentsRegister\/Conversation","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ComponentsRegister\/ConversationCell","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ComponentsRegister\/ConversationViewService","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ComponentsRegister\/ConversationsController","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ComponentsRegister\/GroupInfoController","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ComponentsRegister\/GroupParticipantController","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ComponentsRegister\/JoinedGroupsController","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ComponentsRegister\/MessageRenderEntity","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ComponentsRegister\/MessageViewController","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ComponentsRegister\/MessagesViewModel","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ComponentsRegister\/NewFriendRequestController","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ComponentsRegister\/RemoveGroupParticipantController","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ComponentsRegister\/ReportViewController","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ComponentsRegister\/customCellClasses","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ComponentsRegister\/customCellMaps"]},{"title":"Instance Methods","generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ComponentsRegister\/registerCustomCellClasses(cellType:identifier:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ComponentsRegister\/registerCustomizeCellClass(cellType:)"]},{"generated":true,"title":"Type Properties","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ComponentsRegister\/shared"],"anchor":"Type-Properties"}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objcMembers"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ComponentsRegister","kind":"identifier"}],"platforms":["iOS"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ComponentsRegister"},"metadata":{"externalID":"c:@M@ShengwangChatUIKit@objc(cs)ComponentsRegister","navigatorTitle":[{"kind":"identifier","text":"ComponentsRegister"}],"role":"symbol","modules":[{"name":"ShengwangChatUIKit"}],"title":"ComponentsRegister","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ComponentsRegister","kind":"identifier"}],"roleHeading":"Class","symbolKind":"class"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit"]]},"sections":[],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ComponentsRegister/ChatContactMessageCell":{"url":"\/documentation\/shengwangchatuikit\/componentsregister\/chatcontactmessagecell","type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ComponentsRegister\/ChatContactMessageCell","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ChatContactMessageCell"}],"role":"symbol","abstract":[],"title":"ChatContactMessageCell","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatContactMessageCell"},{"kind":"text","text":": "},{"text":"ContactCardCell","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)ContactCardCell","kind":"typeIdentifier"},{"kind":"text","text":".Type"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ComponentsRegister/ContactsCell":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"ContactsCell","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)ContactCell","text":"ContactCell"},{"kind":"text","text":".Type"}],"type":"topic","role":"symbol","abstract":[],"kind":"symbol","navigatorTitle":[{"text":"ContactsCell","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ComponentsRegister\/ContactsCell","url":"\/documentation\/shengwangchatuikit\/componentsregister\/contactscell","title":"ContactsCell"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ComponentsRegister/shared":{"abstract":[],"title":"shared","type":"topic","role":"symbol","url":"\/documentation\/shengwangchatuikit\/componentsregister\/shared","kind":"symbol","navigatorTitle":[{"text":"shared","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ComponentsRegister\/shared","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"shared"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"ComponentsRegister","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)ComponentsRegister"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ComponentsRegister/ChatTextMessageCell":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ComponentsRegister\/ChatTextMessageCell","abstract":[],"url":"\/documentation\/shengwangchatuikit\/componentsregister\/chattextmessagecell","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChatTextMessageCell"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)TextMessageCell","text":"TextMessageCell","kind":"typeIdentifier"},{"text":".Type","kind":"text"}],"role":"symbol","title":"ChatTextMessageCell","navigatorTitle":[{"text":"ChatTextMessageCell","kind":"identifier"}],"kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ComponentsRegister/ConversationViewService":{"abstract":[{"type":"text","text":"Conversation list view model."}],"kind":"symbol","url":"\/documentation\/shengwangchatuikit\/componentsregister\/conversationviewservice","navigatorTitle":[{"text":"ConversationViewService","kind":"identifier"}],"title":"ConversationViewService","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ComponentsRegister\/ConversationViewService","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationViewService"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)ConversationViewModel","text":"ConversationViewModel","kind":"typeIdentifier"},{"text":".Type","kind":"text"}],"type":"topic"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ComponentsRegister/ContactsController":{"url":"\/documentation\/shengwangchatuikit\/componentsregister\/contactscontroller","abstract":[{"text":"Contact list page controller.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"ContactsController","kind":"identifier"}],"type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ComponentsRegister\/ContactsController","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ContactsController","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)ContactViewController","kind":"typeIdentifier","text":"ContactViewController"},{"text":".Type","kind":"text"}],"title":"ContactsController"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ComponentsRegister/ChatLocationCell":{"navigatorTitle":[{"text":"ChatLocationCell","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ComponentsRegister\/ChatLocationCell","title":"ChatLocationCell","role":"symbol","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChatLocationCell","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)LocationMessageCell","text":"LocationMessageCell"},{"text":".Type","kind":"text"}],"type":"topic","abstract":[],"url":"\/documentation\/shengwangchatuikit\/componentsregister\/chatlocationcell"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ComponentsRegister/RemoveGroupParticipantController":{"abstract":[{"type":"text","text":"Remove participants controller of the group."}],"kind":"symbol","url":"\/documentation\/shengwangchatuikit\/componentsregister\/removegroupparticipantcontroller","navigatorTitle":[{"text":"RemoveGroupParticipantController","kind":"identifier"}],"title":"RemoveGroupParticipantController","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ComponentsRegister\/RemoveGroupParticipantController","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"RemoveGroupParticipantController","kind":"identifier"},{"text":": ","kind":"text"},{"text":"GroupParticipantsRemoveController","kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)GroupParticipantsRemoveController"},{"text":".Type","kind":"text"}],"type":"topic"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ComponentsRegister/ChatAudioMessageCell":{"navigatorTitle":[{"text":"ChatAudioMessageCell","kind":"identifier"}],"title":"ChatAudioMessageCell","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ComponentsRegister\/ChatAudioMessageCell","role":"symbol","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChatAudioMessageCell","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)AudioMessageCell","kind":"typeIdentifier","text":"AudioMessageCell"},{"kind":"text","text":".Type"}],"type":"topic","abstract":[],"url":"\/documentation\/shengwangchatuikit\/componentsregister\/chataudiomessagecell"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ComponentsRegister/ConversationCell":{"abstract":[],"kind":"symbol","url":"\/documentation\/shengwangchatuikit\/componentsregister\/conversationcell","navigatorTitle":[{"text":"ConversationCell","kind":"identifier"}],"title":"ConversationCell","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ComponentsRegister\/ConversationCell","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"ConversationCell","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ConversationListCell","kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)ConversationListCell"},{"text":".Type","kind":"text"}],"type":"topic"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ComponentsRegister/init":{"kind":"symbol","title":"init","navigatorTitle":[{"text":"init","kind":"identifier"}],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ComponentsRegister\/init","url":"\/documentation\/shengwangchatuikit\/componentsregister\/init","type":"topic","abstract":[]},"doc://org.cocoapods.ShengwangChatUIKit/SH":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ComponentsRegister/ContactInfoController":{"abstract":[{"text":"Contact detail info of the group.","type":"text"}],"kind":"symbol","url":"\/documentation\/shengwangchatuikit\/componentsregister\/contactinfocontroller","navigatorTitle":[{"text":"ContactInfoController","kind":"identifier"}],"title":"ContactInfoController","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ComponentsRegister\/ContactInfoController","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ContactInfoController","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)ContactInfoViewController","text":"ContactInfoViewController"},{"text":".Type","kind":"text"}],"type":"topic"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ComponentsRegister/MessagesViewModel":{"navigatorTitle":[{"text":"MessagesViewModel","kind":"identifier"}],"title":"MessagesViewModel","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ComponentsRegister\/MessagesViewModel","role":"symbol","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessagesViewModel"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)MessageListViewModel","text":"MessageListViewModel","kind":"typeIdentifier"},{"text":".Type","kind":"text"}],"type":"topic","abstract":[],"url":"\/documentation\/shengwangchatuikit\/componentsregister\/messagesviewmodel"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ComponentsRegister/Conversation":{"abstract":[],"kind":"symbol","url":"\/documentation\/shengwangchatuikit\/componentsregister\/conversation","navigatorTitle":[{"text":"Conversation","kind":"identifier"}],"title":"Conversation","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ComponentsRegister\/Conversation","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Conversation","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)ConversationInfo","text":"ConversationInfo"},{"text":".Type","kind":"text"}],"type":"topic"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ComponentsRegister/customCellClasses":{"navigatorTitle":[{"text":"customCellClasses","kind":"identifier"}],"title":"customCellClasses","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ComponentsRegister\/customCellClasses","role":"symbol","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"customCellClasses"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)MessageCell","text":"MessageCell","kind":"typeIdentifier"},{"text":".Type]","kind":"text"}],"type":"topic","abstract":[],"url":"\/documentation\/shengwangchatuikit\/componentsregister\/customcellclasses"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ComponentsRegister/customCellMaps":{"abstract":[],"kind":"symbol","url":"\/documentation\/shengwangchatuikit\/componentsregister\/customcellmaps","navigatorTitle":[{"text":"customCellMaps","kind":"identifier"}],"title":"customCellMaps","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ComponentsRegister\/customCellMaps","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"customCellMaps","kind":"identifier"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":" : ","kind":"text"},{"text":"MessageCell","kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)MessageCell"},{"text":".Type]","kind":"text"}],"type":"topic"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ComponentsRegister/ChatCombineCell":{"navigatorTitle":[{"text":"ChatCombineCell","kind":"identifier"}],"title":"ChatCombineCell","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ComponentsRegister\/ChatCombineCell","role":"symbol","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChatCombineCell","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)CombineMessageCell","kind":"typeIdentifier","text":"CombineMessageCell"},{"text":".Type","kind":"text"}],"type":"topic","abstract":[],"url":"\/documentation\/shengwangchatuikit\/componentsregister\/chatcombinecell"},"doc://org.cocoapods.ShengwangChatUIKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://org.cocoapods.ShengwangChatUIKit/SQ":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/SQ","title":"Swift.Equatable"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ComponentsRegister/NewFriendRequestController":{"abstract":[{"type":"text","text":"New friend request controller."}],"kind":"symbol","url":"\/documentation\/shengwangchatuikit\/componentsregister\/newfriendrequestcontroller","navigatorTitle":[{"text":"NewFriendRequestController","kind":"identifier"}],"title":"NewFriendRequestController","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ComponentsRegister\/NewFriendRequestController","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"NewFriendRequestController","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)NewContactRequestController","text":"NewContactRequestController","kind":"typeIdentifier"},{"text":".Type","kind":"text"}],"type":"topic"},"doc://org.cocoapods.ShengwangChatUIKit/s7CVarArgP":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ComponentsRegister/ContactViewService":{"abstract":[{"text":"Contact list view model.","type":"text"}],"kind":"symbol","url":"\/documentation\/shengwangchatuikit\/componentsregister\/contactviewservice","navigatorTitle":[{"text":"ContactViewService","kind":"identifier"}],"title":"ContactViewService","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ComponentsRegister\/ContactViewService","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ContactViewService","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)ContactViewModel","kind":"typeIdentifier","text":"ContactViewModel"},{"text":".Type","kind":"text"}],"type":"topic"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ComponentsRegister/ConversationsController":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationsController"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)ConversationListController","text":"ConversationListController","kind":"typeIdentifier"},{"text":".Type","kind":"text"}],"type":"topic","role":"symbol","abstract":[{"type":"text","text":"Conversation list page controller"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ConversationsController"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ComponentsRegister\/ConversationsController","url":"\/documentation\/shengwangchatuikit\/componentsregister\/conversationscontroller","title":"ConversationsController"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ComponentsRegister/MessageRenderEntity":{"navigatorTitle":[{"text":"MessageRenderEntity","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/componentsregister\/messagerenderentity","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageRenderEntity"},{"kind":"text","text":": "},{"text":"MessageEntity","kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)MessageEntity"},{"text":".Type","kind":"text"}],"role":"symbol","title":"MessageRenderEntity","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ComponentsRegister\/MessageRenderEntity","kind":"symbol","abstract":[{"text":"Message cell render entity.","type":"text"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ComponentsRegister/MessageViewController":{"navigatorTitle":[{"kind":"identifier","text":"MessageViewController"}],"url":"\/documentation\/shengwangchatuikit\/componentsregister\/messageviewcontroller","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ComponentsRegister\/MessageViewController","abstract":[{"type":"text","text":"Message list page controller."}],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MessageViewController"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)MessageListController","text":"MessageListController"},{"text":".Type","kind":"text"}],"title":"MessageViewController","type":"topic"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ComponentsRegister/GroupInfoController":{"abstract":[{"text":"Group detail info view controller.","type":"text"}],"kind":"symbol","url":"\/documentation\/shengwangchatuikit\/componentsregister\/groupinfocontroller","navigatorTitle":[{"text":"GroupInfoController","kind":"identifier"}],"title":"GroupInfoController","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ComponentsRegister\/GroupInfoController","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GroupInfoController"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)GroupInfoViewController","kind":"typeIdentifier","text":"GroupInfoViewController"},{"kind":"text","text":".Type"}],"type":"topic"},"doc://org.cocoapods.ShengwangChatUIKit/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ComponentsRegister/ChatAlertCell":{"abstract":[],"kind":"symbol","url":"\/documentation\/shengwangchatuikit\/componentsregister\/chatalertcell","navigatorTitle":[{"text":"ChatAlertCell","kind":"identifier"}],"title":"ChatAlertCell","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ComponentsRegister\/ChatAlertCell","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatAlertCell"},{"kind":"text","text":": "},{"text":"AlertMessageCell","kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)AlertMessageCell"},{"text":".Type","kind":"text"}],"type":"topic"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ComponentsRegister/registerCustomCellClasses(cellType:identifier:)":{"navigatorTitle":[{"text":"registerCustomCellClassesWithCellType:identifier:","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/componentsregister\/registercustomcellclasses(celltype:identifier:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"registerCustomCellClasses"},{"kind":"text","text":"("},{"kind":"externalParam","text":"cellType"},{"text":": ","kind":"text"},{"text":"CustomMessageCell","kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)CustomMessageCell"},{"text":".Type, ","kind":"text"},{"text":"identifier","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"role":"symbol","title":"registerCustomCellClasses(cellType:identifier:)","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ComponentsRegister\/registerCustomCellClasses(cellType:identifier:)","kind":"symbol","abstract":[{"type":"text","text":"Register custom cell class with identifier."}]},"doc://org.cocoapods.ShengwangChatUIKit/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(cs)NSObject"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ComponentsRegister/ChatFileMessageCell":{"navigatorTitle":[{"text":"ChatFileMessageCell","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/componentsregister\/chatfilemessagecell","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"ChatFileMessageCell","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)FileMessageCell","text":"FileMessageCell","kind":"typeIdentifier"},{"text":".Type","kind":"text"}],"role":"symbol","title":"ChatFileMessageCell","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ComponentsRegister\/ChatFileMessageCell","kind":"symbol","abstract":[]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ComponentsRegister/ChatVideoMessageCell":{"abstract":[],"kind":"symbol","url":"\/documentation\/shengwangchatuikit\/componentsregister\/chatvideomessagecell","navigatorTitle":[{"text":"ChatVideoMessageCell","kind":"identifier"}],"title":"ChatVideoMessageCell","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ComponentsRegister\/ChatVideoMessageCell","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChatVideoMessageCell","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)VideoMessageCell","text":"VideoMessageCell"},{"text":".Type","kind":"text"}],"type":"topic"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ComponentsRegister/GroupParticipantController":{"navigatorTitle":[{"text":"GroupParticipantController","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/componentsregister\/groupparticipantcontroller","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"GroupParticipantController","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)GroupParticipantsController","text":"GroupParticipantsController","kind":"typeIdentifier"},{"text":".Type","kind":"text"}],"role":"symbol","title":"GroupParticipantController","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ComponentsRegister\/GroupParticipantController","kind":"symbol","abstract":[{"type":"text","text":"Participants controller of the group."}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ComponentsRegister":{"navigatorTitle":[{"kind":"identifier","text":"ComponentsRegister"}],"url":"\/documentation\/shengwangchatuikit\/componentsregister","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ComponentsRegister","abstract":[{"type":"text","text":"An object containing UI components that are used through the EaseChatUIKit SDK."}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ComponentsRegister","kind":"identifier"}],"title":"ComponentsRegister","type":"topic"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ComponentsRegister/ReportViewController":{"abstract":[{"type":"text","text":"Report message controller."}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ComponentsRegister\/ReportViewController","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"ReportViewController","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)ReportOptionsController","text":"ReportOptionsController"},{"text":".Type","kind":"text"}],"type":"topic","role":"symbol","title":"ReportViewController","navigatorTitle":[{"text":"ReportViewController","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/componentsregister\/reportviewcontroller","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ComponentsRegister/JoinedGroupsController":{"abstract":[],"kind":"symbol","url":"\/documentation\/shengwangchatuikit\/componentsregister\/joinedgroupscontroller","navigatorTitle":[{"kind":"identifier","text":"JoinedGroupsController"}],"title":"JoinedGroupsController","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ComponentsRegister\/JoinedGroupsController","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JoinedGroupsController","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)JoinedGroupsViewController","text":"JoinedGroupsViewController","kind":"typeIdentifier"},{"text":".Type","kind":"text"}],"type":"topic"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ComponentsRegister/ChatCustomMessageCell":{"navigatorTitle":[{"kind":"identifier","text":"ChatCustomMessageCell"}],"url":"\/documentation\/shengwangchatuikit\/componentsregister\/chatcustommessagecell","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChatCustomMessageCell","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CustomMessageCell","kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)CustomMessageCell"},{"text":".Type","kind":"text"}],"role":"symbol","title":"ChatCustomMessageCell","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ComponentsRegister\/ChatCustomMessageCell","kind":"symbol","abstract":[]},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)NSObject"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ComponentsRegister/registerCustomizeCellClass(cellType:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"registerCustomizeCellClass","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"cellType"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)MessageCell","kind":"typeIdentifier","text":"MessageCell"},{"text":".Type)","kind":"text"}],"type":"topic","navigatorTitle":[{"text":"registerCustomizeCellClassWithCellType:","kind":"identifier"}],"title":"registerCustomizeCellClass(cellType:)","url":"\/documentation\/shengwangchatuikit\/componentsregister\/registercustomizecellclass(celltype:)","abstract":[{"type":"text","text":"Register customize table view cell method."}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ComponentsRegister\/registerCustomizeCellClass(cellType:)","role":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ComponentsRegister/ChatImageMessageCell":{"navigatorTitle":[{"kind":"identifier","text":"ChatImageMessageCell"}],"url":"\/documentation\/shengwangchatuikit\/componentsregister\/chatimagemessagecell","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChatImageMessageCell","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)ImageMessageCell","text":"ImageMessageCell","kind":"typeIdentifier"},{"text":".Type","kind":"text"}],"role":"symbol","title":"ChatImageMessageCell","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ComponentsRegister\/ChatImageMessageCell","kind":"symbol","abstract":[]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"ComponentsRegister","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"value":[{"text":"ComponentsRegister","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"ComponentsRegister","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ComponentsRegister\/ChatAlertCell","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ComponentsRegister\/ChatAudioMessageCell","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ComponentsRegister\/ChatCombineCell","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ComponentsRegister\/ChatContactMessageCell","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ComponentsRegister\/ChatCustomMessageCell","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ComponentsRegister\/ChatFileMessageCell","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ComponentsRegister\/ChatImageMessageCell","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ComponentsRegister\/ChatLocationCell","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ComponentsRegister\/ChatTextMessageCell","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ComponentsRegister\/ChatVideoMessageCell","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ComponentsRegister\/ContactInfoController","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ComponentsRegister\/ContactViewService","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ComponentsRegister\/ContactsCell","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ComponentsRegister\/ContactsController","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ComponentsRegister\/Conversation","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ComponentsRegister\/ConversationCell","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ComponentsRegister\/ConversationViewService","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ComponentsRegister\/ConversationsController","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ComponentsRegister\/GroupInfoController","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ComponentsRegister\/GroupParticipantController","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ComponentsRegister\/JoinedGroupsController","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ComponentsRegister\/MessageRenderEntity","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ComponentsRegister\/MessageViewController","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ComponentsRegister\/MessagesViewModel","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ComponentsRegister\/NewFriendRequestController","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ComponentsRegister\/RemoveGroupParticipantController","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ComponentsRegister\/ReportViewController","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ComponentsRegister\/customCellClasses","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ComponentsRegister\/customCellMaps"],"title":"Instance Properties","anchor":"Instance-Properties","generated":true},{"generated":true,"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ComponentsRegister\/init","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ComponentsRegister\/registerCustomCellClasses(cellType:identifier:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ComponentsRegister\/registerCustomizeCellClass(cellType:)"],"anchor":"Instance-Methods","title":"Instance Methods"},{"anchor":"Type-Properties","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ComponentsRegister\/shared"],"generated":true,"title":"Type Properties"}],"op":"replace","path":"\/topicSections"},{"value":[{"type":"inheritsFrom","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships"}],"op":"replace","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ComponentsRegister"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"op":"replace","value":"ChatContactMessageCell","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ComponentsRegister~1ChatContactMessageCell\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ComponentsRegister~1ChatContactMessageCell\/fragments","op":"replace","value":[{"kind":"identifier","text":"ChatContactMessageCell"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ComponentsRegister~1ContactsCell\/title","value":"ContactsCell","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ComponentsRegister~1ContactsCell\/fragments","value":[{"kind":"identifier","text":"ContactsCell"}],"op":"replace"},{"value":"shared","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ComponentsRegister~1shared\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ComponentsRegister~1shared\/fragments","value":[{"kind":"identifier","text":"shared"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ComponentsRegister~1ChatTextMessageCell\/title","value":"ChatTextMessageCell","op":"replace"},{"value":[{"text":"ChatTextMessageCell","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ComponentsRegister~1ChatTextMessageCell\/fragments","op":"replace"},{"value":"ConversationViewService","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ComponentsRegister~1ConversationViewService\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ComponentsRegister~1ConversationViewService\/fragments","value":[{"kind":"identifier","text":"ConversationViewService"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ComponentsRegister~1ContactsController\/title","value":"ContactsController","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ComponentsRegister~1ContactsController\/fragments","value":[{"text":"ContactsController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ComponentsRegister~1ChatLocationCell\/title","value":"ChatLocationCell"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ComponentsRegister~1ChatLocationCell\/fragments","op":"replace","value":[{"kind":"identifier","text":"ChatLocationCell"}]},{"value":"RemoveGroupParticipantController","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ComponentsRegister~1RemoveGroupParticipantController\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"RemoveGroupParticipantController"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ComponentsRegister~1RemoveGroupParticipantController\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ComponentsRegister~1ChatAudioMessageCell\/title","op":"replace","value":"ChatAudioMessageCell"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ComponentsRegister~1ChatAudioMessageCell\/fragments","value":[{"text":"ChatAudioMessageCell","kind":"identifier"}]},{"op":"replace","value":"ConversationCell","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ComponentsRegister~1ConversationCell\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ComponentsRegister~1ConversationCell\/fragments","value":[{"text":"ConversationCell","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ComponentsRegister~1ContactInfoController\/title","value":"ContactInfoController"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ComponentsRegister~1ContactInfoController\/fragments","value":[{"kind":"identifier","text":"ContactInfoController"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ComponentsRegister~1MessagesViewModel\/title","value":"MessagesViewModel","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"MessagesViewModel"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ComponentsRegister~1MessagesViewModel\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ComponentsRegister~1Conversation\/title","op":"replace","value":"Conversation"},{"value":[{"text":"Conversation","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ComponentsRegister~1Conversation\/fragments","op":"replace"},{"value":"customCellClasses","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ComponentsRegister~1customCellClasses\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ComponentsRegister~1customCellClasses\/fragments","op":"replace","value":[{"text":"customCellClasses","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ComponentsRegister~1customCellMaps\/title","value":"customCellMaps"},{"value":[{"kind":"identifier","text":"customCellMaps"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ComponentsRegister~1customCellMaps\/fragments"},{"op":"replace","value":"ChatCombineCell","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ComponentsRegister~1ChatCombineCell\/title"},{"op":"replace","value":[{"text":"ChatCombineCell","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ComponentsRegister~1ChatCombineCell\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ComponentsRegister~1NewFriendRequestController\/title","op":"replace","value":"NewFriendRequestController"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ComponentsRegister~1NewFriendRequestController\/fragments","value":[{"text":"NewFriendRequestController","kind":"identifier"}]},{"value":"ContactViewService","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ComponentsRegister~1ContactViewService\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ComponentsRegister~1ContactViewService\/fragments","value":[{"kind":"identifier","text":"ContactViewService"}]},{"value":"ConversationsController","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ComponentsRegister~1ConversationsController\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ComponentsRegister~1ConversationsController\/fragments","op":"replace","value":[{"kind":"identifier","text":"ConversationsController"}]},{"value":"MessageRenderEntity","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ComponentsRegister~1MessageRenderEntity\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ComponentsRegister~1MessageRenderEntity\/fragments","value":[{"text":"MessageRenderEntity","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ComponentsRegister~1MessageViewController\/title","value":"MessageViewController"},{"op":"replace","value":[{"text":"MessageViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ComponentsRegister~1MessageViewController\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ComponentsRegister~1GroupInfoController\/title","op":"replace","value":"GroupInfoController"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ComponentsRegister~1GroupInfoController\/fragments","value":[{"kind":"identifier","text":"GroupInfoController"}]},{"value":"ChatAlertCell","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ComponentsRegister~1ChatAlertCell\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ComponentsRegister~1ChatAlertCell\/fragments","op":"replace","value":[{"kind":"identifier","text":"ChatAlertCell"}]},{"op":"replace","value":"registerCustomCellClassesWithCellType:identifier:","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ComponentsRegister~1registerCustomCellClasses(cellType:identifier:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ComponentsRegister~1registerCustomCellClasses(cellType:identifier:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"registerCustomCellClassesWithCellType:identifier:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ComponentsRegister~1ChatFileMessageCell\/title","op":"replace","value":"ChatFileMessageCell"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ComponentsRegister~1ChatFileMessageCell\/fragments","value":[{"kind":"identifier","text":"ChatFileMessageCell"}]},{"op":"replace","value":"ChatVideoMessageCell","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ComponentsRegister~1ChatVideoMessageCell\/title"},{"value":[{"text":"ChatVideoMessageCell","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ComponentsRegister~1ChatVideoMessageCell\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ComponentsRegister~1GroupParticipantController\/title","op":"replace","value":"GroupParticipantController"},{"value":[{"text":"GroupParticipantController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ComponentsRegister~1GroupParticipantController\/fragments"},{"op":"replace","value":"ComponentsRegister","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ComponentsRegister\/title"},{"op":"replace","value":[{"text":"ComponentsRegister","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ComponentsRegister\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ComponentsRegister\/navigatorTitle","value":[{"text":"ComponentsRegister","kind":"identifier"}]},{"value":"ReportViewController","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ComponentsRegister~1ReportViewController\/title","op":"replace"},{"value":[{"kind":"identifier","text":"ReportViewController"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ComponentsRegister~1ReportViewController\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ComponentsRegister~1JoinedGroupsController\/title","value":"JoinedGroupsController","op":"replace"},{"value":[{"text":"JoinedGroupsController","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ComponentsRegister~1JoinedGroupsController\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ComponentsRegister~1ChatCustomMessageCell\/title","value":"ChatCustomMessageCell","op":"replace"},{"value":[{"kind":"identifier","text":"ChatCustomMessageCell"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ComponentsRegister~1ChatCustomMessageCell\/fragments"},{"value":"registerCustomizeCellClassWithCellType:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ComponentsRegister~1registerCustomizeCellClass(cellType:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ComponentsRegister~1registerCustomizeCellClass(cellType:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"registerCustomizeCellClassWithCellType:"}]},{"value":"ChatImageMessageCell","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ComponentsRegister~1ChatImageMessageCell\/title","op":"replace"},{"op":"replace","value":[{"text":"ChatImageMessageCell","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ComponentsRegister~1ChatImageMessageCell\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}