{"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit"]]},"sections":[],"metadata":{"title":"ContactDisplayStyle","navigatorTitle":[{"text":"ContactDisplayStyle","kind":"identifier"}],"symbolKind":"enum","modules":[{"name":"ShengwangChatUIKit"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"ContactDisplayStyle","kind":"identifier"}],"role":"symbol","externalID":"c:@M@ShengwangChatUIKit@E@ContactDisplayStyle","roleHeading":"Enumeration"},"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/SQ","doc:\/\/org.cocoapods.ShengwangChatUIKit\/SH","doc:\/\/org.cocoapods.ShengwangChatUIKit\/SY"],"title":"Conforms To","type":"conformsTo"}],"topicSections":[{"anchor":"Enumeration-Cases","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactDisplayStyle\/normal","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactDisplayStyle\/withCheckBox"],"title":"Enumeration Cases","generated":true},{"title":"Initializers","anchor":"Initializers","generated":true,"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactDisplayStyle\/init(rawValue:)"]},{"anchor":"Default-Implementations","generated":true,"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactDisplayStyle\/Equatable-Implementations","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactDisplayStyle\/RawRepresentable-Implementations"],"title":"Default Implementations"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"ContactDisplayStyle","kind":"identifier"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/contactdisplaystyle"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/contactdisplaystyle"]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactDisplayStyle"},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ContactDisplayStyle/Equatable-Implementations":{"type":"topic","role":"collectionGroup","kind":"article","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactDisplayStyle\/Equatable-Implementations","title":"Equatable Implementations","url":"\/documentation\/shengwangchatuikit\/contactdisplaystyle\/equatable-implementations","abstract":[]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ContactDisplayStyle/RawRepresentable-Implementations":{"abstract":[],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactDisplayStyle\/RawRepresentable-Implementations","type":"topic","role":"collectionGroup","url":"\/documentation\/shengwangchatuikit\/contactdisplaystyle\/rawrepresentable-implementations","kind":"article","title":"RawRepresentable Implementations"},"doc://org.cocoapods.ShengwangChatUIKit/SY":{"title":"Swift.RawRepresentable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/SY","type":"unresolvable"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ContactDisplayStyle/withCheckBox":{"abstract":[],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactDisplayStyle\/withCheckBox","navigatorTitle":[{"kind":"identifier","text":"ContactDisplayStyleWithCheckBox"}],"type":"topic","role":"symbol","url":"\/documentation\/shengwangchatuikit\/contactdisplaystyle\/withcheckbox","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"withCheckBox"}],"title":"ContactDisplayStyle.withCheckBox"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/SH","type":"unresolvable"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ContactDisplayStyle/init(rawValue:)":{"url":"\/documentation\/shengwangchatuikit\/contactdisplaystyle\/init(rawvalue:)","kind":"symbol","title":"init(rawValue:)","type":"topic","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"text":": ","kind":"text"},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"},{"text":")","kind":"text"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactDisplayStyle\/init(rawValue:)"},"doc://org.cocoapods.ShengwangChatUIKit/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/SQ","type":"unresolvable"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ContactDisplayStyle/normal":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactDisplayStyle\/normal","url":"\/documentation\/shengwangchatuikit\/contactdisplaystyle\/normal","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"normal"}],"abstract":[],"navigatorTitle":[{"text":"ContactDisplayStyleNormal","kind":"identifier"}],"type":"topic","role":"symbol","title":"ContactDisplayStyle.normal"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ContactDisplayStyle":{"navigatorTitle":[{"text":"ContactDisplayStyle","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactDisplayStyle","abstract":[],"url":"\/documentation\/shengwangchatuikit\/contactdisplaystyle","role":"symbol","kind":"symbol","type":"topic","title":"ContactDisplayStyle","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ContactDisplayStyle","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"ContactDisplayStyle"},{"value":"enum","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"ContactDisplayStyle"}]},{"value":[{"kind":"identifier","text":"ContactDisplayStyle"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"generated":true,"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactDisplayStyle\/normal","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactDisplayStyle\/withCheckBox"],"anchor":"Enumeration-Cases","title":"Enumeration Cases"}],"path":"\/topicSections","op":"replace"},{"path":"\/relationshipsSections","value":null,"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ContactDisplayStyle","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSUInteger","text":"NSUInteger","kind":"typeIdentifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"ContactDisplayStyleWithCheckBox","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactDisplayStyle~1withCheckBox\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactDisplayStyle~1withCheckBox\/fragments","value":[{"text":"ContactDisplayStyleWithCheckBox","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactDisplayStyle~1normal\/title","value":"ContactDisplayStyleNormal"},{"value":[{"text":"ContactDisplayStyleNormal","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactDisplayStyle~1normal\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactDisplayStyle\/title","value":"ContactDisplayStyle"},{"value":[{"text":"ContactDisplayStyle","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactDisplayStyle\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactDisplayStyle\/navigatorTitle","value":[{"text":"ContactDisplayStyle","kind":"identifier"}],"op":"replace"}]}]}