{"sections":[],"metadata":{"title":"ContactListItemActionClosure","symbolKind":"typealias","roleHeading":"Type Alias","navigatorTitle":[{"kind":"identifier","text":"ContactListItemActionClosure"}],"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ContactListItemActionClosure","kind":"identifier"}],"modules":[{"name":"ShengwangChatUIKit"}],"role":"symbol","externalID":"s:18ShengwangChatUIKit28ContactListItemActionClosurea"},"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactListItemActionClosure","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"ContactListItemActionClosure","kind":"identifier"},{"kind":"text","text":" = (("},{"text":"ContactListHeaderItemProtocol","kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(pl)ContactListHeaderItemProtocol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactListHeaderItemProtocol"},{"text":") -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/shengwangchatuikit\/contactlistitemactionclosure"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ContactListItemActionClosure":{"title":"ContactListItemActionClosure","navigatorTitle":[{"text":"ContactListItemActionClosure","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/contactlistitemactionclosure","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactListItemActionClosure","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"ContactListItemActionClosure","kind":"identifier"}],"abstract":[],"role":"symbol","kind":"symbol","type":"topic"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ContactListHeaderItemProtocol":{"navigatorTitle":[{"kind":"identifier","text":"ContactListHeaderItemProtocol"}],"title":"ContactListHeaderItemProtocol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactListHeaderItemProtocol","role":"symbol","abstract":[{"type":"text","text":"A protocol of the contact list item."}],"kind":"symbol","url":"\/documentation\/shengwangchatuikit\/contactlistheaderitemprotocol","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ContactListHeaderItemProtocol","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"ContactListHeaderItemProtocol","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactListHeaderItemProtocol\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactListHeaderItemProtocol\/fragments","value":[{"kind":"identifier","text":"ContactListHeaderItemProtocol"}]},{"value":[{"kind":"identifier","text":"ContactListHeaderItemProtocol"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactListHeaderItemProtocol\/navigatorTitle"}]}]}