{"topicSections":[{"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactEventsResponse\/friendRequestDidAgree(by:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactEventsResponse\/friendRequestDidDecline(by:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactEventsResponse\/friendRequestDidReceive(by:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactEventsResponse\/friendshipDidAddSuccessful(by:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactEventsResponse\/friendshipDidRemove(by:)"],"generated":true}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"ContactEventsResponse","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject","kind":"typeIdentifier"}],"platforms":["iOS"]}]}],"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)NSObject"],"type":"inheritsFrom","title":"Inherits From"},{"kind":"relationships","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactViewModel"],"type":"conformingTypes","title":"Conforming Types"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactEventsResponse"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/contacteventsresponse"]},{"paths":["\/documentation\/shengwangchatuikit\/contacteventsresponse"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit"]]},"metadata":{"role":"symbol","roleHeading":"Protocol","navigatorTitle":[{"text":"ContactEventsResponse","kind":"identifier"}],"title":"ContactEventsResponse","symbolKind":"protocol","externalID":"c:@M@ShengwangChatUIKit@objc(pl)ContactEventsResponse","modules":[{"name":"ShengwangChatUIKit"}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"ContactEventsResponse","kind":"identifier"}]},"kind":"symbol","references":{"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)NSObject":{"title":"NSObject","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)NSObject","type":"unresolvable"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ContactEventsResponse/friendshipDidAddSuccessful(by:)":{"title":"friendshipDidAddSuccessful(by:)","abstract":[{"type":"text","text":"Friend relationship added successfully"}],"navigatorTitle":[{"text":"friendshipDidAddSuccessfulBy:","kind":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactEventsResponse\/friendshipDidAddSuccessful(by:)","required":true,"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"friendshipDidAddSuccessful"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"by"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}],"url":"\/documentation\/shengwangchatuikit\/contacteventsresponse\/friendshipdidaddsuccessful(by:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ContactEventsResponse/friendRequestDidReceive(by:)":{"abstract":[{"text":"Received friend request","type":"text"}],"required":true,"title":"friendRequestDidReceive(by:)","type":"topic","role":"symbol","url":"\/documentation\/shengwangchatuikit\/contacteventsresponse\/friendrequestdidreceive(by:)","kind":"symbol","navigatorTitle":[{"text":"friendRequestDidReceiveBy:","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactEventsResponse\/friendRequestDidReceive(by:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"friendRequestDidReceive"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"by"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":")"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ContactEventsResponse/friendshipDidRemove(by:)":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactEventsResponse\/friendshipDidRemove(by:)","navigatorTitle":[{"text":"friendshipDidRemoveBy:","kind":"identifier"}],"type":"topic","abstract":[{"text":"The friend relationship was removed by the other party","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"friendshipDidRemove"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"by"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"title":"friendshipDidRemove(by:)","kind":"symbol","required":true,"url":"\/documentation\/shengwangchatuikit\/contacteventsresponse\/friendshipdidremove(by:)","role":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ContactEventsResponse/friendRequestDidDecline(by:)":{"navigatorTitle":[{"text":"friendRequestDidDeclineBy:","kind":"identifier"}],"abstract":[{"type":"text","text":"Friend request was rejected by the other party"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactEventsResponse\/friendRequestDidDecline(by:)","url":"\/documentation\/shengwangchatuikit\/contacteventsresponse\/friendrequestdiddecline(by:)","title":"friendRequestDidDecline(by:)","type":"topic","required":true,"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"friendRequestDidDecline"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"by"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":")"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ContactViewModel":{"abstract":[{"text":"Bind service and driver","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ContactViewModel","kind":"identifier"}],"navigatorTitle":[{"text":"ContactViewModel","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactViewModel","role":"symbol","title":"ContactViewModel","kind":"symbol","url":"\/documentation\/shengwangchatuikit\/contactviewmodel"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ContactEventsResponse/friendRequestDidAgree(by:)":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactEventsResponse\/friendRequestDidAgree(by:)","navigatorTitle":[{"text":"friendRequestDidAgreeBy:","kind":"identifier"}],"type":"topic","abstract":[{"text":"The friend request was accepted by the other party","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"friendRequestDidAgree"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"by"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"title":"friendRequestDidAgree(by:)","kind":"symbol","required":true,"url":"\/documentation\/shengwangchatuikit\/contacteventsresponse\/friendrequestdidagree(by:)","role":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ContactEventsResponse":{"abstract":[],"kind":"symbol","url":"\/documentation\/shengwangchatuikit\/contacteventsresponse","navigatorTitle":[{"text":"ContactEventsResponse","kind":"identifier"}],"title":"ContactEventsResponse","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactEventsResponse","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"ContactEventsResponse","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Protocol","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","value":"ContactEventsResponse","path":"\/metadata\/title"},{"value":"protocol","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"ContactEventsResponse"}]},{"path":"\/metadata\/navigatorTitle","value":[{"text":"ContactEventsResponse","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":[{"generated":true,"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactEventsResponse\/friendRequestDidAgree(by:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactEventsResponse\/friendRequestDidDecline(by:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactEventsResponse\/friendRequestDidReceive(by:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactEventsResponse\/friendshipDidAddSuccessful(by:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactEventsResponse\/friendshipDidRemove(by:)"]}],"op":"replace"},{"path":"\/relationshipsSections","op":"replace","value":[{"title":"Inherits From","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)NSObject"],"kind":"relationships","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactViewModel"],"kind":"relationships","type":"conformingTypes","title":"Conforming Types"}]},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@protocol"},{"text":" ","kind":"text"},{"text":"ContactEventsResponse","kind":"identifier"},{"text":" <","kind":"text"},{"preciseIdentifier":"c:objc(pl)NSObject","kind":"typeIdentifier","text":"NSObject"},{"kind":"text","text":">"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactEventsResponse~1friendshipDidAddSuccessful(by:)\/title","value":"friendshipDidAddSuccessfulBy:"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactEventsResponse~1friendshipDidAddSuccessful(by:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"friendshipDidAddSuccessfulBy:","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactEventsResponse~1friendRequestDidReceive(by:)\/title","value":"friendRequestDidReceiveBy:"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactEventsResponse~1friendRequestDidReceive(by:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"friendRequestDidReceiveBy:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactEventsResponse~1friendshipDidRemove(by:)\/title","value":"friendshipDidRemoveBy:"},{"value":[{"kind":"text","text":"- "},{"text":"friendshipDidRemoveBy:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactEventsResponse~1friendshipDidRemove(by:)\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactEventsResponse~1friendRequestDidDecline(by:)\/title","value":"friendRequestDidDeclineBy:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactEventsResponse~1friendRequestDidDecline(by:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"friendRequestDidDeclineBy:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactViewModel\/title","value":"ContactViewModel","op":"replace"},{"op":"replace","value":[{"text":"ContactViewModel","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactViewModel\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactViewModel\/navigatorTitle","value":[{"kind":"identifier","text":"ContactViewModel"}],"op":"replace"},{"value":"friendRequestDidAgreeBy:","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactEventsResponse~1friendRequestDidAgree(by:)\/title","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"friendRequestDidAgreeBy:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactEventsResponse~1friendRequestDidAgree(by:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactEventsResponse\/title","value":"ContactEventsResponse"},{"op":"replace","value":[{"text":"ContactEventsResponse","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactEventsResponse\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactEventsResponse\/navigatorTitle","value":[{"kind":"identifier","text":"ContactEventsResponse"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}