{"abstract":[{"type":"text","text":"Contact Module"}],"relationshipsSections":[{"type":"inheritsFrom","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships"},{"type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)NSObject","doc:\/\/org.cocoapods.ShengwangChatUIKit\/s7CVarArgP","doc:\/\/org.cocoapods.ShengwangChatUIKit\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.ShengwangChatUIKit\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.ShengwangChatUIKit\/SQ","doc:\/\/org.cocoapods.ShengwangChatUIKit\/SH"],"kind":"relationships"}],"topicSections":[{"title":"Instance Properties","anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactAppearance\/detailExtensionActionItems","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactAppearance\/enableBlock","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactAppearance\/headerRowHeight","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactAppearance\/listHeaderExtensionActions","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactAppearance\/moreActions","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactAppearance\/rowHeight"]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objcMembers","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ContactAppearance"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/shengwangchatuikit\/contactappearance"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/shengwangchatuikit\/contactappearance"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit"]]},"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactAppearance","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"metadata":{"role":"symbol","roleHeading":"Class","navigatorTitle":[{"text":"ContactAppearance","kind":"identifier"}],"externalID":"c:@M@ShengwangChatUIKit@objc(cs)ContactAppearance","symbolKind":"class","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ContactAppearance","kind":"identifier"}],"title":"ContactAppearance","modules":[{"name":"ShengwangChatUIKit"}]},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ContactAppearance/headerRowHeight":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactAppearance\/headerRowHeight","navigatorTitle":[{"text":"headerRowHeight","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/contactappearance\/headerrowheight","type":"topic","abstract":[{"type":"text","text":"Header of contact list list row height."}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"headerRowHeight","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier"}],"title":"headerRowHeight","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/s7CVarArgP","title":"Swift.CVarArg"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ContactAppearance/rowHeight":{"navigatorTitle":[{"kind":"identifier","text":"rowHeight"}],"title":"rowHeight","url":"\/documentation\/shengwangchatuikit\/contactappearance\/rowheight","type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rowHeight","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"Contact row height."}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactAppearance\/rowHeight","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ContactAppearance/init":{"role":"symbol","abstract":[],"kind":"symbol","title":"init","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"init"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactAppearance\/init","navigatorTitle":[{"text":"init","kind":"identifier"}],"type":"topic","url":"\/documentation\/shengwangchatuikit\/contactappearance\/init"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ContactAppearance":{"navigatorTitle":[{"kind":"identifier","text":"ContactAppearance"}],"abstract":[{"type":"text","text":"Contact Module"}],"title":"ContactAppearance","type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactAppearance","url":"\/documentation\/shengwangchatuikit\/contactappearance","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ContactAppearance"}],"role":"symbol","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/SQ":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/SQ","title":"Swift.Equatable"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ContactAppearance/moreActions":{"abstract":[{"type":"text","text":"ActionSheet menu configuration items after clicking more buttons in a single session side sliding menu."},{"type":"text","text":" "},{"type":"text","text":"How to use?"},{"text":" ","type":"text"},{"type":"codeVoice","code":"let translate = ActionSheetItem(title: \"translate\", type: .normal,tag: \"Translate\")"},{"type":"text","text":" "},{"code":"translate.action = { }","type":"codeVoice"},{"type":"text","text":" "},{"type":"codeVoice","code":"Appearance.conversation.moreActions.append(translate)"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"moreActions"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(pl)ActionSheetItemProtocol","kind":"typeIdentifier","text":"ActionSheetItemProtocol"},{"kind":"text","text":"]"}],"role":"symbol","type":"topic","url":"\/documentation\/shengwangchatuikit\/contactappearance\/moreactions","title":"moreActions","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactAppearance\/moreActions","navigatorTitle":[{"text":"moreActions","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ContactAppearance/enableBlock":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactAppearance\/enableBlock","navigatorTitle":[{"text":"enableBlock","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/contactappearance\/enableblock","type":"topic","abstract":[{"text":"Whether enable block some contact or not.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"enableBlock"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"title":"enableBlock","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ContactAppearance/listHeaderExtensionActions":{"abstract":[{"type":"text","text":"The header items of the contact list."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"listHeaderExtensionActions"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(pl)ContactListHeaderItemProtocol","text":"ContactListHeaderItemProtocol","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"role":"symbol","type":"topic","url":"\/documentation\/shengwangchatuikit\/contactappearance\/listheaderextensionactions","title":"listHeaderExtensionActions","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactAppearance\/listHeaderExtensionActions","navigatorTitle":[{"text":"listHeaderExtensionActions","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/SH"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)NSObject"},"doc://org.cocoapods.ShengwangChatUIKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/s28CustomDebugStringConvertibleP"},"doc://org.cocoapods.ShengwangChatUIKit/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/s23CustomStringConvertibleP"},"doc://org.cocoapods.ShengwangChatUIKit/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(cs)NSObject"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ContactAppearance/detailExtensionActionItems":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"detailExtensionActionItems","kind":"identifier"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(pl)ContactListHeaderItemProtocol","text":"ContactListHeaderItemProtocol","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"type":"topic","role":"symbol","abstract":[{"text":"The contact info header extension items.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"detailExtensionActionItems","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactAppearance\/detailExtensionActionItems","url":"\/documentation\/shengwangchatuikit\/contactappearance\/detailextensionactionitems","title":"detailExtensionActionItems"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"path":"\/metadata\/title","value":"ContactAppearance","op":"replace"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"ContactAppearance"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"ContactAppearance"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"title":"Instance Properties","anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactAppearance\/detailExtensionActionItems","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactAppearance\/enableBlock","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactAppearance\/headerRowHeight","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactAppearance\/listHeaderExtensionActions","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactAppearance\/moreActions","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactAppearance\/rowHeight"]},{"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactAppearance\/init"],"anchor":"Instance-Methods","generated":true,"title":"Instance Methods"}],"op":"replace","path":"\/topicSections"},{"value":[{"title":"Inherits From","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships"}],"path":"\/relationshipsSections","op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ContactAppearance","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactAppearance~1headerRowHeight\/title","value":"headerRowHeight"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactAppearance~1headerRowHeight\/fragments","value":[{"kind":"identifier","text":"headerRowHeight"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactAppearance~1rowHeight\/title","value":"rowHeight","op":"replace"},{"op":"replace","value":[{"text":"rowHeight","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactAppearance~1rowHeight\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactAppearance\/title","value":"ContactAppearance"},{"value":[{"text":"ContactAppearance","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactAppearance\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactAppearance\/navigatorTitle","value":[{"kind":"identifier","text":"ContactAppearance"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactAppearance~1moreActions\/title","value":"moreActions"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactAppearance~1moreActions\/fragments","value":[{"kind":"identifier","text":"moreActions"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactAppearance~1enableBlock\/title","value":"enableBlock"},{"value":[{"kind":"identifier","text":"enableBlock"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactAppearance~1enableBlock\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactAppearance~1listHeaderExtensionActions\/title","op":"replace","value":"listHeaderExtensionActions"},{"value":[{"kind":"identifier","text":"listHeaderExtensionActions"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactAppearance~1listHeaderExtensionActions\/fragments"},{"value":"detailExtensionActionItems","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactAppearance~1detailExtensionActionItems\/title","op":"replace"},{"value":[{"text":"detailExtensionActionItems","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactAppearance~1detailExtensionActionItems\/fragments","op":"replace"}]}]}