{"variants":[{"paths":["\/documentation\/shengwangchatuikit\/contactemergencylistener"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/shengwangchatuikit\/contactemergencylistener"],"traits":[{"interfaceLanguage":"occ"}]}],"topicSections":[{"generated":true,"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactEmergencyListener\/onResult(error:type:operatorId:)"]}],"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactEmergencyListener"},"metadata":{"modules":[{"name":"ShengwangChatUIKit"}],"roleHeading":"Protocol","navigatorTitle":[{"kind":"identifier","text":"ContactEmergencyListener"}],"externalID":"c:@M@ShengwangChatUIKit@objc(pl)ContactEmergencyListener","symbolKind":"protocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"ContactEmergencyListener","kind":"identifier"}],"title":"ContactEmergencyListener","role":"symbol"},"relationshipsSections":[{"type":"inheritsFrom","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)NSObject"],"title":"Inherits From","kind":"relationships"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ContactEmergencyListener"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(pl)NSObject","text":"NSObjectProtocol","kind":"typeIdentifier"}],"languages":["swift"]}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit"]]},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ContactEmergencyListener/onResult(error:type:operatorId:)":{"title":"onResult(error:type:operatorId:)","required":true,"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactEmergencyListener\/onResult(error:type:operatorId:)","navigatorTitle":[{"text":"onResultWithError:type:operatorId:","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"You’ll receive the result on conversation service request successful or failure."}],"url":"\/documentation\/shengwangchatuikit\/contactemergencylistener\/onresult(error:type:operatorid:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onResult"},{"kind":"text","text":"("},{"kind":"externalParam","text":"error"},{"text":": ","kind":"text"},{"text":"ChatError","kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit0B5Errora"},{"text":"?, ","kind":"text"},{"text":"type","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ContactEmergencyType","preciseIdentifier":"c:@M@ShengwangChatUIKit@E@ContactEmergencyType","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"operatorId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)NSObject":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)NSObject","title":"NSObject","type":"unresolvable"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ContactEmergencyListener":{"navigatorTitle":[{"kind":"identifier","text":"ContactEmergencyListener"}],"abstract":[],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ContactEmergencyListener"}],"type":"topic","url":"\/documentation\/shengwangchatuikit\/contactemergencylistener","kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactEmergencyListener","title":"ContactEmergencyListener"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Protocol","path":"\/metadata\/roleHeading","op":"replace"},{"value":"ContactEmergencyListener","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ContactEmergencyListener"}]},{"op":"replace","value":[{"kind":"identifier","text":"ContactEmergencyListener"}],"path":"\/metadata\/navigatorTitle"},{"value":[{"title":"Instance Methods","anchor":"Instance-Methods","generated":true,"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactEmergencyListener\/onResult(error:type:operatorId:)"]}],"op":"replace","path":"\/topicSections"},{"path":"\/relationshipsSections","value":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)NSObject"],"kind":"relationships"}],"op":"replace"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ContactEmergencyListener"},{"text":" <","kind":"text"},{"preciseIdentifier":"c:objc(pl)NSObject","text":"NSObject","kind":"typeIdentifier"},{"text":">","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactEmergencyListener~1onResult(error:type:operatorId:)\/title","value":"onResultWithError:type:operatorId:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactEmergencyListener~1onResult(error:type:operatorId:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"onResultWithError:type:operatorId:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactEmergencyListener\/title","value":"ContactEmergencyListener"},{"value":[{"kind":"identifier","text":"ContactEmergencyListener"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactEmergencyListener\/fragments"},{"value":[{"text":"ContactEmergencyListener","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactEmergencyListener\/navigatorTitle"}]}]}