{"variants":[{"paths":["\/documentation\/shengwangchatuikit\/conversationlistactioneventsdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/conversationlistactioneventsdelegate"]}],"sections":[],"relationshipsSections":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)NSObject"]},{"title":"Conforming Types","type":"conformingTypes","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationViewModel"]}],"abstract":[{"type":"text","text":"Session list touch event callback proxy"}],"metadata":{"modules":[{"name":"ShengwangChatUIKit"}],"roleHeading":"Protocol","navigatorTitle":[{"text":"ConversationListActionEventsDelegate","kind":"identifier"}],"externalID":"c:@M@ShengwangChatUIKit@objc(pl)ConversationListActionEventsDelegate","symbolKind":"protocol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"ConversationListActionEventsDelegate","kind":"identifier"}],"title":"ConversationListActionEventsDelegate","role":"symbol"},"kind":"symbol","topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationListActionEventsDelegate\/onConversationDidSelected(indexPath:info:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationListActionEventsDelegate\/onConversationListEndScrollNeededDisplayInfos(ids:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationListActionEventsDelegate\/onConversationListOccurErrorWhenFetchServer()","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationListActionEventsDelegate\/onConversationListRefresh()","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationListActionEventsDelegate\/onConversationLongPressed(indexPath:info:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationListActionEventsDelegate\/onConversationSwipe(type:info:)"],"anchor":"Instance-Methods","generated":true}],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationListActionEventsDelegate"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ConversationListActionEventsDelegate"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject","text":"NSObjectProtocol"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ConversationListActionEventsDelegate":{"title":"ConversationListActionEventsDelegate","abstract":[{"text":"Session list touch event callback proxy","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"ConversationListActionEventsDelegate"}],"url":"\/documentation\/shengwangchatuikit\/conversationlistactioneventsdelegate","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationListActionEventsDelegate"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationListActionEventsDelegate","type":"topic","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ConversationViewModel":{"url":"\/documentation\/shengwangchatuikit\/conversationviewmodel","type":"topic","role":"symbol","abstract":[{"text":"Bind service and driver","type":"text"}],"title":"ConversationViewModel","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ConversationViewModel","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationViewModel","navigatorTitle":[{"text":"ConversationViewModel","kind":"identifier"}],"kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ConversationListActionEventsDelegate/onConversationSwipe(type:info:)":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationListActionEventsDelegate\/onConversationSwipe(type:info:)","navigatorTitle":[{"kind":"identifier","text":"onConversationSwipeWithType:info:"}],"url":"\/documentation\/shengwangchatuikit\/conversationlistactioneventsdelegate\/onconversationswipe(type:info:)","type":"topic","abstract":[{"type":"text","text":"Callback on conversation was swiped."}],"required":true,"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"onConversationSwipe","kind":"identifier"},{"kind":"text","text":"("},{"text":"type","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@E@UIContextualActionType","text":"UIContextualActionType","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"info","kind":"externalParam"},{"kind":"text","text":": "},{"text":"ConversationInfo","kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)ConversationInfo"},{"text":")","kind":"text"}],"title":"onConversationSwipe(type:info:)","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ConversationListActionEventsDelegate/onConversationListRefresh()":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"onConversationListRefresh","kind":"identifier"},{"kind":"text","text":"()"}],"type":"topic","navigatorTitle":[{"text":"onConversationListRefresh","kind":"identifier"}],"title":"onConversationListRefresh()","required":true,"url":"\/documentation\/shengwangchatuikit\/conversationlistactioneventsdelegate\/onconversationlistrefresh()","abstract":[{"text":"Pull down to refresh","type":"text"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationListActionEventsDelegate\/onConversationListRefresh()","role":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)NSObject","title":"NSObject"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ConversationListActionEventsDelegate/onConversationListEndScrollNeededDisplayInfos(ids:)":{"type":"topic","abstract":[{"text":"The method will called on conversation list end scroll,then it will ask you for the session nickname and avatar data and then refresh it.","type":"text"}],"title":"onConversationListEndScrollNeededDisplayInfos(ids:)","url":"\/documentation\/shengwangchatuikit\/conversationlistactioneventsdelegate\/onconversationlistendscrollneededdisplayinfos(ids:)","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationListActionEventsDelegate\/onConversationListEndScrollNeededDisplayInfos(ids:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onConversationListEndScrollNeededDisplayInfos"},{"kind":"text","text":"("},{"kind":"externalParam","text":"ids"},{"text":": [","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"])","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"onConversationListEndScrollNeededDisplayInfosWithIds:"}],"required":true,"kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ConversationListActionEventsDelegate/onConversationDidSelected(indexPath:info:)":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationListActionEventsDelegate\/onConversationDidSelected(indexPath:info:)","navigatorTitle":[{"kind":"identifier","text":"onConversationDidSelectedWithIndexPath:info:"}],"type":"topic","abstract":[{"type":"text","text":"Callback on conversation was selected."}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onConversationDidSelected"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"indexPath"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation9IndexPathV","text":"IndexPath"},{"text":", ","kind":"text"},{"text":"info","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)ConversationInfo","text":"ConversationInfo","kind":"typeIdentifier"},{"kind":"text","text":")"}],"kind":"symbol","title":"onConversationDidSelected(indexPath:info:)","required":true,"url":"\/documentation\/shengwangchatuikit\/conversationlistactioneventsdelegate\/onconversationdidselected(indexpath:info:)","role":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ConversationListActionEventsDelegate/onConversationLongPressed(indexPath:info:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"onConversationLongPressed","kind":"identifier"},{"kind":"text","text":"("},{"text":"indexPath","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation9IndexPathV","text":"IndexPath","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"info","kind":"externalParam"},{"kind":"text","text":": "},{"text":"ConversationInfo","kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)ConversationInfo"},{"text":")","kind":"text"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"onConversationLongPressedWithIndexPath:info:"}],"title":"onConversationLongPressed(indexPath:info:)","required":true,"url":"\/documentation\/shengwangchatuikit\/conversationlistactioneventsdelegate\/onconversationlongpressed(indexpath:info:)","abstract":[{"text":"Callback on conversation was long pressed.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationListActionEventsDelegate\/onConversationLongPressed(indexPath:info:)","role":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ConversationListActionEventsDelegate/onConversationListOccurErrorWhenFetchServer()":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationListActionEventsDelegate\/onConversationListOccurErrorWhenFetchServer()","navigatorTitle":[{"text":"onConversationListOccurErrorWhenFetchServer","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/conversationlistactioneventsdelegate\/onconversationlistoccurerrorwhenfetchserver()","type":"topic","abstract":[{"text":"When fetch conversations list occur error.Empty view retry button on clicked.The method will call.","type":"text"}],"required":true,"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"onConversationListOccurErrorWhenFetchServer","kind":"identifier"},{"kind":"text","text":"()"}],"title":"onConversationListOccurErrorWhenFetchServer()","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"value":"ConversationListActionEventsDelegate","path":"\/metadata\/title","op":"replace"},{"value":"protocol","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"ConversationListActionEventsDelegate"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ConversationListActionEventsDelegate"}]},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationListActionEventsDelegate\/onConversationDidSelected(indexPath:info:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationListActionEventsDelegate\/onConversationListEndScrollNeededDisplayInfos(ids:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationListActionEventsDelegate\/onConversationListOccurErrorWhenFetchServer()","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationListActionEventsDelegate\/onConversationListRefresh()","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationListActionEventsDelegate\/onConversationLongPressed(indexPath:info:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationListActionEventsDelegate\/onConversationSwipe(type:info:)"],"anchor":"Instance-Methods","generated":true,"title":"Instance Methods"}]},{"path":"\/relationshipsSections","op":"replace","value":[{"title":"Inherits From","kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)NSObject"]},{"kind":"relationships","type":"conformingTypes","title":"Conforming Types","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationViewModel"]}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationListActionEventsDelegate","kind":"identifier"},{"text":" <","kind":"text"},{"preciseIdentifier":"c:objc(pl)NSObject","kind":"typeIdentifier","text":"NSObject"},{"kind":"text","text":">"}]}],"kind":"declarations"}},{"value":"ConversationListActionEventsDelegate","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationListActionEventsDelegate\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationListActionEventsDelegate\/fragments","op":"replace","value":[{"kind":"identifier","text":"ConversationListActionEventsDelegate"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationListActionEventsDelegate\/navigatorTitle","op":"replace","value":[{"text":"ConversationListActionEventsDelegate","kind":"identifier"}]},{"value":"ConversationViewModel","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationViewModel\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationViewModel\/fragments","value":[{"kind":"identifier","text":"ConversationViewModel"}],"op":"replace"},{"value":[{"text":"ConversationViewModel","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationViewModel\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationListActionEventsDelegate~1onConversationSwipe(type:info:)\/title","value":"onConversationSwipeWithType:info:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationListActionEventsDelegate~1onConversationSwipe(type:info:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onConversationSwipeWithType:info:"}],"op":"replace"},{"op":"replace","value":"onConversationListRefresh","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationListActionEventsDelegate~1onConversationListRefresh()\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationListActionEventsDelegate~1onConversationListRefresh()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"onConversationListRefresh","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationListActionEventsDelegate~1onConversationListEndScrollNeededDisplayInfos(ids:)\/title","op":"replace","value":"onConversationListEndScrollNeededDisplayInfosWithIds:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationListActionEventsDelegate~1onConversationListEndScrollNeededDisplayInfos(ids:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onConversationListEndScrollNeededDisplayInfosWithIds:"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationListActionEventsDelegate~1onConversationDidSelected(indexPath:info:)\/title","value":"onConversationDidSelectedWithIndexPath:info:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"onConversationDidSelectedWithIndexPath:info:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationListActionEventsDelegate~1onConversationDidSelected(indexPath:info:)\/fragments","op":"replace"},{"value":"onConversationLongPressedWithIndexPath:info:","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationListActionEventsDelegate~1onConversationLongPressed(indexPath:info:)\/title","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"onConversationLongPressedWithIndexPath:info:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationListActionEventsDelegate~1onConversationLongPressed(indexPath:info:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationListActionEventsDelegate~1onConversationListOccurErrorWhenFetchServer()\/title","value":"onConversationListOccurErrorWhenFetchServer"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationListActionEventsDelegate~1onConversationListOccurErrorWhenFetchServer()\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"onConversationListOccurErrorWhenFetchServer"}]}]}]}