{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/d_if_exit(_:)"]},{"paths":["\/documentation\/shengwangchatuikit\/d_if_exit(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"title":"D_IF_exit(_:)","roleHeading":"Function","externalID":"c:@F@D_IF_exit","symbolKind":"func","modules":[{"name":"ShengwangChatUIKit"}],"role":"symbol","navigatorTitle":[{"text":"D_IF_exit","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"D_IF_exit"},{"kind":"text","text":"("},{"preciseIdentifier":"s:Sv","text":"UnsafeMutableRawPointer","kind":"typeIdentifier"},{"kind":"text","text":"!)"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit"]]},"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/D_IF_exit(_:)","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"D_IF_exit"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"state","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sv","text":"UnsafeMutableRawPointer"},{"text":"!)","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/D_IF_exit(_:)":{"title":"D_IF_exit(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"D_IF_exit","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:Sv","text":"UnsafeMutableRawPointer"},{"text":"!)","kind":"text"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/D_IF_exit(_:)","abstract":[],"kind":"symbol","url":"\/documentation\/shengwangchatuikit\/d_if_exit(_:)","navigatorTitle":[{"text":"D_IF_exit","kind":"identifier"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Function","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"D_IF_exit"},{"path":"\/metadata\/symbolKind","op":"replace","value":"func"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"D_IF_exit"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"kind":"text","text":" "},{"text":"D_IF_exit","kind":"identifier"},{"kind":"text","text":"("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":" * "},{"kind":"internalParam","text":"state"},{"text":");","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"D_IF_exit","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1D_IF_exit(_:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1D_IF_exit(_:)\/fragments","value":[{"text":"D_IF_exit","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}