{"variants":[{"paths":["\/documentation\/shengwangchatuikit\/easechatuikitcachetype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/shengwangchatuikit\/easechatuikitcachetype"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"title":"Conforms To","type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/SQ","doc:\/\/org.cocoapods.ShengwangChatUIKit\/SH","doc:\/\/org.cocoapods.ShengwangChatUIKit\/SY"]}],"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/EaseChatUIKitCacheType","interfaceLanguage":"swift"},"sections":[],"metadata":{"modules":[{"name":"ShengwangChatUIKit"}],"symbolKind":"enum","navigatorTitle":[{"kind":"identifier","text":"EaseChatUIKitCacheType"}],"roleHeading":"Enumeration","title":"EaseChatUIKitCacheType","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"EaseChatUIKitCacheType","kind":"identifier"}],"externalID":"c:@M@ShengwangChatUIKit@E@EaseChatUIKitCacheType"},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit"]]},"topicSections":[{"anchor":"Enumeration-Cases","generated":true,"title":"Enumeration Cases","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/EaseChatUIKitCacheType\/all","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/EaseChatUIKitCacheType\/chat","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/EaseChatUIKitCacheType\/group","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/EaseChatUIKitCacheType\/user"]},{"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/EaseChatUIKitCacheType\/init(rawValue:)"],"anchor":"Initializers","generated":true,"title":"Initializers"},{"anchor":"Default-Implementations","title":"Default Implementations","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/EaseChatUIKitCacheType\/Equatable-Implementations","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/EaseChatUIKitCacheType\/RawRepresentable-Implementations"],"generated":true}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"EaseChatUIKitCacheType"}],"platforms":["iOS"]}]}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/EaseChatUIKitCacheType/chat":{"navigatorTitle":[{"kind":"identifier","text":"EaseChatUIKitCacheTypeChat"}],"kind":"symbol","url":"\/documentation\/shengwangchatuikit\/easechatuikitcachetype\/chat","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"chat"}],"title":"EaseChatUIKitCacheType.chat","abstract":[],"role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/EaseChatUIKitCacheType\/chat"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/EaseChatUIKitCacheType/Equatable-Implementations":{"abstract":[],"kind":"article","url":"\/documentation\/shengwangchatuikit\/easechatuikitcachetype\/equatable-implementations","title":"Equatable Implementations","role":"collectionGroup","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/EaseChatUIKitCacheType\/Equatable-Implementations","type":"topic"},"doc://org.cocoapods.ShengwangChatUIKit/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/SQ"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/EaseChatUIKitCacheType/group":{"abstract":[],"kind":"symbol","url":"\/documentation\/shengwangchatuikit\/easechatuikitcachetype\/group","navigatorTitle":[{"kind":"identifier","text":"EaseChatUIKitCacheTypeGroup"}],"title":"EaseChatUIKitCacheType.group","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/EaseChatUIKitCacheType\/group","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"group"}],"type":"topic"},"doc://org.cocoapods.ShengwangChatUIKit/SY":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/SY","type":"unresolvable","title":"Swift.RawRepresentable"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/EaseChatUIKitCacheType":{"url":"\/documentation\/shengwangchatuikit\/easechatuikitcachetype","kind":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"EaseChatUIKitCacheType"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/EaseChatUIKitCacheType","title":"EaseChatUIKitCacheType","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"EaseChatUIKitCacheType","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/EaseChatUIKitCacheType/init(rawValue:)":{"kind":"symbol","url":"\/documentation\/shengwangchatuikit\/easechatuikitcachetype\/init(rawvalue:)","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/EaseChatUIKitCacheType\/init(rawValue:)","type":"topic","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"},{"text":")","kind":"text"}],"role":"symbol","abstract":[],"title":"init(rawValue:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/EaseChatUIKitCacheType/all":{"abstract":[],"kind":"symbol","url":"\/documentation\/shengwangchatuikit\/easechatuikitcachetype\/all","navigatorTitle":[{"kind":"identifier","text":"EaseChatUIKitCacheTypeAll"}],"title":"EaseChatUIKitCacheType.all","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/EaseChatUIKitCacheType\/all","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"all"}],"type":"topic"},"doc://org.cocoapods.ShengwangChatUIKit/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/SH"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/EaseChatUIKitCacheType/RawRepresentable-Implementations":{"abstract":[],"kind":"article","url":"\/documentation\/shengwangchatuikit\/easechatuikitcachetype\/rawrepresentable-implementations","title":"RawRepresentable Implementations","role":"collectionGroup","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/EaseChatUIKitCacheType\/RawRepresentable-Implementations","type":"topic"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/EaseChatUIKitCacheType/user":{"navigatorTitle":[{"kind":"identifier","text":"EaseChatUIKitCacheTypeUser"}],"kind":"symbol","url":"\/documentation\/shengwangchatuikit\/easechatuikitcachetype\/user","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"user"}],"title":"EaseChatUIKitCacheType.user","abstract":[],"role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/EaseChatUIKitCacheType\/user"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Enumeration","path":"\/metadata\/roleHeading","op":"replace"},{"value":"EaseChatUIKitCacheType","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"enum","op":"replace"},{"value":[{"text":"EaseChatUIKitCacheType","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"EaseChatUIKitCacheType"}]},{"value":[{"generated":true,"title":"Enumeration Cases","anchor":"Enumeration-Cases","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/EaseChatUIKitCacheType\/all","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/EaseChatUIKitCacheType\/chat","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/EaseChatUIKitCacheType\/group","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/EaseChatUIKitCacheType\/user"]}],"path":"\/topicSections","op":"replace"},{"path":"\/relationshipsSections","op":"replace","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"EaseChatUIKitCacheType"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSUInteger","kind":"typeIdentifier","text":"NSUInteger"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1EaseChatUIKitCacheType~1chat\/title","value":"EaseChatUIKitCacheTypeChat"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1EaseChatUIKitCacheType~1chat\/fragments","op":"replace","value":[{"text":"EaseChatUIKitCacheTypeChat","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1EaseChatUIKitCacheType~1group\/title","value":"EaseChatUIKitCacheTypeGroup"},{"value":[{"text":"EaseChatUIKitCacheTypeGroup","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1EaseChatUIKitCacheType~1group\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1EaseChatUIKitCacheType\/title","value":"EaseChatUIKitCacheType"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1EaseChatUIKitCacheType\/fragments","op":"replace","value":[{"text":"EaseChatUIKitCacheType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1EaseChatUIKitCacheType\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"EaseChatUIKitCacheType"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1EaseChatUIKitCacheType~1all\/title","value":"EaseChatUIKitCacheTypeAll"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1EaseChatUIKitCacheType~1all\/fragments","value":[{"text":"EaseChatUIKitCacheTypeAll","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1EaseChatUIKitCacheType~1user\/title","op":"replace","value":"EaseChatUIKitCacheTypeUser"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1EaseChatUIKitCacheType~1user\/fragments","op":"replace","value":[{"kind":"identifier","text":"EaseChatUIKitCacheTypeUser"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}