{"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","kind":"attribute","text":"MainActor"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FileMessageView"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit"]]},"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(cs)UIView"],"type":"inheritsFrom","kind":"relationships"},{"kind":"relationships","title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)NSCoding","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)NSObject","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)CALayerDelegate","doc:\/\/org.cocoapods.ShengwangChatUIKit\/s7CVarArgP","doc:\/\/org.cocoapods.ShengwangChatUIKit\/s8CopyableP","doc:\/\/org.cocoapods.ShengwangChatUIKit\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.ShengwangChatUIKit\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.ShengwangChatUIKit\/SQ","doc:\/\/org.cocoapods.ShengwangChatUIKit\/SH","doc:\/\/org.cocoapods.ShengwangChatUIKit\/s8SendableP","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ThemeSwitchProtocol","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIAccessibilityIdentification","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIAppearance","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIAppearanceContainer","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UICoordinateSpace","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIDynamicItem","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIFocusEnvironment","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIFocusItem","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIFocusItemContainer","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UILargeContentViewerItem","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIResponderStandardEditActions","doc:\/\/org.cocoapods.ShengwangChatUIKit\/5UIKit23UITraitChangeObservableP","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UITraitEnvironment","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIUserActivityRestoring"]}],"topicSections":[{"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/FileMessageView\/init(coder:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/FileMessageView\/init(frame:towards:)"],"anchor":"Initializers","generated":true,"title":"Initializers"},{"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/FileMessageView\/content","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/FileMessageView\/fileIcon","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/FileMessageView\/fileIconView","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/FileMessageView\/fileSize","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/FileMessageView\/fileSizeReceiveColor","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/FileMessageView\/fileSizeSendColor","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/FileMessageView\/towards"],"generated":true},{"anchor":"Instance-Methods","generated":true,"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/FileMessageView\/refresh(entity:)"]},{"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/FileMessageView\/ThemeSwitchProtocol-Implementations"],"anchor":"Default-Implementations","generated":true,"title":"Default Implementations"}],"metadata":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"FileMessageView"}],"title":"FileMessageView","roleHeading":"Class","modules":[{"name":"ShengwangChatUIKit"}],"role":"symbol","externalID":"c:@M@ShengwangChatUIKit@objc(cs)FileMessageView","symbolKind":"class","navigatorTitle":[{"kind":"identifier","text":"FileMessageView"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/filemessageview"]},{"paths":["\/documentation\/shengwangchatuikit\/filemessageview"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/FileMessageView","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"references":{"doc://org.cocoapods.ShengwangChatUIKit/objc(cs)UIView":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(cs)UIView","title":"UIView"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/FileMessageView/towards":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"towards"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BubbleTowards","preciseIdentifier":"c:@M@ShengwangChatUIKit@E@BubbleTowards"}],"title":"towards","url":"\/documentation\/shengwangchatuikit\/filemessageview\/towards","abstract":[],"type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/FileMessageView\/towards"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIPasteConfigurationSupporting"},"doc://org.cocoapods.ShengwangChatUIKit/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/s23CustomStringConvertibleP"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)NSCoding":{"title":"Foundation.NSCoding","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)NSCoding"},"doc://org.cocoapods.ShengwangChatUIKit/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/s28CustomDebugStringConvertibleP"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ThemeSwitchProtocol":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ThemeSwitchProtocol","abstract":[{"type":"text","text":"When the system theme changes, you can use this static method to switch between the light and dark themes of the ease chat UIKit."}],"url":"\/documentation\/shengwangchatuikit\/themeswitchprotocol","type":"topic","kind":"symbol","role":"symbol","title":"ThemeSwitchProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"ThemeSwitchProtocol","kind":"identifier"}],"navigatorTitle":[{"text":"ThemeSwitchProtocol","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/FileMessageView/fileSizeSendColor":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/FileMessageView\/fileSizeSendColor","abstract":[],"type":"topic","role":"symbol","url":"\/documentation\/shengwangchatuikit\/filemessageview\/filesizesendcolor","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"fileSizeSendColor"},{"text":": ","kind":"text"},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"}],"title":"fileSizeSendColor"},"doc://org.cocoapods.ShengwangChatUIKit/5UIKit23UITraitChangeObservableP":{"title":"UIKit.UITraitChangeObservable","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/5UIKit23UITraitChangeObservableP"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://org.cocoapods.ShengwangChatUIKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/SH"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UITraitEnvironment"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/FileMessageView/fileSizeReceiveColor":{"kind":"symbol","url":"\/documentation\/shengwangchatuikit\/filemessageview\/filesizereceivecolor","abstract":[],"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"fileSizeReceiveColor"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/FileMessageView\/fileSizeReceiveColor","role":"symbol","title":"fileSizeReceiveColor"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/FileMessageView":{"url":"\/documentation\/shengwangchatuikit\/filemessageview","navigatorTitle":[{"kind":"identifier","text":"FileMessageView"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FileMessageView","kind":"identifier"}],"title":"FileMessageView","abstract":[],"kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/FileMessageView","type":"topic"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/FileMessageView/fileSize":{"url":"\/documentation\/shengwangchatuikit\/filemessageview\/filesize","kind":"symbol","type":"topic","role":"symbol","title":"fileSize","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/FileMessageView\/fileSize","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"fileSize","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"}]},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UIFocusItemContainer":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIFocusItemContainer","title":"UIKit.UIFocusItemContainer"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)CALayerDelegate":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)CALayerDelegate","title":"QuartzCore.CALayerDelegate"},"doc://org.cocoapods.ShengwangChatUIKit/s8SendableP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/s8SendableP","title":"Swift.Sendable"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/FileMessageView/content":{"kind":"symbol","url":"\/documentation\/shengwangchatuikit\/filemessageview\/content","abstract":[],"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"content"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/FileMessageView\/content","role":"symbol","title":"content"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/FileMessageView/ThemeSwitchProtocol-Implementations":{"title":"ThemeSwitchProtocol Implementations","url":"\/documentation\/shengwangchatuikit\/filemessageview\/themeswitchprotocol-implementations","abstract":[],"type":"topic","kind":"article","role":"collectionGroup","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/FileMessageView\/ThemeSwitchProtocol-Implementations"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UIDynamicItem":{"title":"UIKit.UIDynamicItem","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIDynamicItem"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UICoordinateSpace":{"title":"UIKit.UICoordinateSpace","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UICoordinateSpace"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/FileMessageView/init(frame:towards:)":{"navigatorTitle":[{"text":"initWithFrame:towards:","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/shengwangchatuikit\/filemessageview\/init(frame:towards:)","abstract":[],"type":"topic","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"frame"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect","text":"CGRect"},{"kind":"text","text":", "},{"kind":"externalParam","text":"towards"},{"text":": ","kind":"text"},{"text":"BubbleTowards","preciseIdentifier":"c:@M@ShengwangChatUIKit@E@BubbleTowards","kind":"typeIdentifier"},{"kind":"text","text":")"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/FileMessageView\/init(frame:towards:)","role":"symbol","title":"init(frame:towards:)"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UIFocusItem":{"title":"UIKit.UIFocusItem","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIFocusItem","type":"unresolvable"},"doc://org.cocoapods.ShengwangChatUIKit/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/SQ","type":"unresolvable"},"doc://org.cocoapods.ShengwangChatUIKit/s8CopyableP":{"title":"Swift.Copyable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/s8CopyableP","type":"unresolvable"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UIAccessibilityIdentification":{"title":"UIKit.UIAccessibilityIdentification","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIAccessibilityIdentification","type":"unresolvable"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UILargeContentViewerItem":{"title":"UIKit.UILargeContentViewerItem","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UILargeContentViewerItem","type":"unresolvable"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/FileMessageView/fileIconView":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"fileIconView","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImageView","kind":"typeIdentifier","text":"UIImageView"}],"type":"topic","role":"symbol","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/FileMessageView\/fileIconView","url":"\/documentation\/shengwangchatuikit\/filemessageview\/fileiconview","title":"fileIconView"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UIFocusEnvironment":{"title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIFocusEnvironment","type":"unresolvable"},"doc://org.cocoapods.ShengwangChatUIKit/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/s7CVarArgP","type":"unresolvable"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UIAppearance":{"title":"UIKit.UIAppearance","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIAppearance","type":"unresolvable"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/FileMessageView/init(coder:)":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/FileMessageView\/init(coder:)","navigatorTitle":[{"text":"initWithCoder:","kind":"identifier"}],"type":"topic","kind":"symbol","title":"init(coder:)","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"coder","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSCoder","text":"NSCoder","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[],"url":"\/documentation\/shengwangchatuikit\/filemessageview\/init(coder:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UIUserActivityRestoring":{"title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIUserActivityRestoring","type":"unresolvable"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UIAppearanceContainer":{"title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIAppearanceContainer","type":"unresolvable"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/FileMessageView/refresh(entity:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"refresh","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"entity"},{"kind":"text","text":": "},{"text":"MessageEntity","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)MessageEntity","kind":"typeIdentifier"},{"kind":"text","text":")"}],"title":"refresh(entity:)","url":"\/documentation\/shengwangchatuikit\/filemessageview\/refresh(entity:)","abstract":[],"type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/FileMessageView\/refresh(entity:)","navigatorTitle":[{"kind":"identifier","text":"refreshWithEntity:"}]},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)NSObject"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/FileMessageView/fileIcon":{"title":"fileIcon","type":"topic","url":"\/documentation\/shengwangchatuikit\/filemessageview\/fileicon","kind":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/FileMessageView\/fileIcon","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fileIcon"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImageView","text":"UIImageView"}],"role":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UIPopoverPresentationControllerSourceItem":{"type":"unresolvable","title":"UIKit.UIPopoverPresentationControllerSourceItem","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIPopoverPresentationControllerSourceItem"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIResponderStandardEditActions"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"FileMessageView"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"FileMessageView"}]},{"path":"\/metadata\/navigatorTitle","value":[{"text":"FileMessageView","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","op":"replace","value":[{"anchor":"Instance-Methods","title":"Instance Methods","generated":true,"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/FileMessageView\/init(coder:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/FileMessageView\/init(frame:towards:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/FileMessageView\/refresh(entity:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/FileMessageView\/ThemeSwitchProtocol-Implementations"],"generated":true,"anchor":"Default-Implementations"}]},{"value":[{"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(cs)UIView"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"},{"kind":"relationships","type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ThemeSwitchProtocol"]}],"path":"\/relationshipsSections","op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FileMessageView"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView","text":"UIView"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ThemeSwitchProtocol\/title","value":"ThemeSwitchProtocol","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ThemeSwitchProtocol\/fragments","value":[{"kind":"identifier","text":"ThemeSwitchProtocol"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ThemeSwitchProtocol\/navigatorTitle","value":[{"kind":"identifier","text":"ThemeSwitchProtocol"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1FileMessageView\/title","op":"replace","value":"FileMessageView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1FileMessageView\/fragments","value":[{"kind":"identifier","text":"FileMessageView"}]},{"op":"replace","value":[{"text":"FileMessageView","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1FileMessageView\/navigatorTitle"},{"value":"initWithFrame:towards:","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1FileMessageView~1init(frame:towards:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithFrame:towards:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1FileMessageView~1init(frame:towards:)\/fragments"},{"value":"initWithCoder:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1FileMessageView~1init(coder:)\/title"},{"value":[{"kind":"text","text":"- "},{"text":"initWithCoder:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1FileMessageView~1init(coder:)\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1FileMessageView~1refresh(entity:)\/title","value":"refreshWithEntity:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1FileMessageView~1refresh(entity:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"refreshWithEntity:"}]}]}]}