{"sections":[],"topicSections":[{"title":"Enumeration Cases","generated":true,"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupInfoEditType\/alias","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupInfoEditType\/announcement","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupInfoEditType\/description","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupInfoEditType\/name","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupInfoEditType\/threadName"],"anchor":"Enumeration-Cases"},{"generated":true,"title":"Initializers","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupInfoEditType\/init(rawValue:)"],"anchor":"Initializers"},{"anchor":"Default-Implementations","title":"Default Implementations","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupInfoEditType\/Equatable-Implementations","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupInfoEditType\/RawRepresentable-Implementations"],"generated":true}],"metadata":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GroupInfoEditType","kind":"identifier"}],"symbolKind":"enum","modules":[{"name":"ShengwangChatUIKit"}],"title":"GroupInfoEditType","navigatorTitle":[{"text":"GroupInfoEditType","kind":"identifier"}],"roleHeading":"Enumeration","externalID":"c:@M@ShengwangChatUIKit@E@GroupInfoEditType","role":"symbol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupInfoEditType"}],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/shengwangchatuikit\/groupinfoedittype"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/groupinfoedittype"]}],"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupInfoEditType","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit"]]},"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/SQ","doc:\/\/org.cocoapods.ShengwangChatUIKit\/SH","doc:\/\/org.cocoapods.ShengwangChatUIKit\/SY"],"type":"conformsTo","title":"Conforms To"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://org.cocoapods.ShengwangChatUIKit/SQ":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/GroupInfoEditType/alias":{"type":"topic","navigatorTitle":[{"text":"GroupInfoEditTypeAlias","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/groupinfoedittype\/alias","kind":"symbol","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"alias"}],"abstract":[],"title":"GroupInfoEditType.alias","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupInfoEditType\/alias"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/GroupInfoEditType/name":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"name","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"GroupInfoEditTypeName","kind":"identifier"}],"title":"GroupInfoEditType.name","url":"\/documentation\/shengwangchatuikit\/groupinfoedittype\/name","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupInfoEditType\/name","role":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/GroupInfoEditType":{"kind":"symbol","title":"GroupInfoEditType","abstract":[],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupInfoEditType"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"GroupInfoEditType"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupInfoEditType","url":"\/documentation\/shengwangchatuikit\/groupinfoedittype"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/GroupInfoEditType/threadName":{"type":"topic","abstract":[],"title":"GroupInfoEditType.threadName","navigatorTitle":[{"text":"GroupInfoEditTypeThreadName","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupInfoEditType\/threadName","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"threadName","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/groupinfoedittype\/threadname"},"doc://org.cocoapods.ShengwangChatUIKit/SY":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/SY","title":"Swift.RawRepresentable"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/GroupInfoEditType/init(rawValue:)":{"type":"topic","abstract":[],"title":"init(rawValue:)","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupInfoEditType\/init(rawValue:)","kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"},{"kind":"text","text":")"}],"url":"\/documentation\/shengwangchatuikit\/groupinfoedittype\/init(rawvalue:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/GroupInfoEditType/RawRepresentable-Implementations":{"abstract":[],"role":"collectionGroup","kind":"article","type":"topic","url":"\/documentation\/shengwangchatuikit\/groupinfoedittype\/rawrepresentable-implementations","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupInfoEditType\/RawRepresentable-Implementations","title":"RawRepresentable Implementations"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/SH":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/SH","title":"Swift.Hashable"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/GroupInfoEditType/Equatable-Implementations":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupInfoEditType\/Equatable-Implementations","type":"topic","title":"Equatable Implementations","kind":"article","role":"collectionGroup","url":"\/documentation\/shengwangchatuikit\/groupinfoedittype\/equatable-implementations","abstract":[]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/GroupInfoEditType/announcement":{"type":"topic","abstract":[],"title":"GroupInfoEditType.announcement","navigatorTitle":[{"text":"GroupInfoEditTypeAnnouncement","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupInfoEditType\/announcement","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"announcement","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/groupinfoedittype\/announcement"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/GroupInfoEditType/description":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"description"}],"type":"topic","navigatorTitle":[{"text":"GroupInfoEditTypeDescription","kind":"identifier"}],"title":"GroupInfoEditType.description","url":"\/documentation\/shengwangchatuikit\/groupinfoedittype\/description","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupInfoEditType\/description","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"path":"\/metadata\/title","op":"replace","value":"GroupInfoEditType"},{"value":"enum","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"GroupInfoEditType","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"GroupInfoEditType"}]},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupInfoEditType\/alias","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupInfoEditType\/announcement","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupInfoEditType\/description","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupInfoEditType\/name","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupInfoEditType\/threadName"],"title":"Enumeration Cases","anchor":"Enumeration-Cases","generated":true}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GroupInfoEditType","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSUInteger","text":"NSUInteger"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"GroupInfoEditTypeAlias","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupInfoEditType~1alias\/title"},{"value":[{"kind":"identifier","text":"GroupInfoEditTypeAlias"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupInfoEditType~1alias\/fragments","op":"replace"},{"value":"GroupInfoEditTypeName","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupInfoEditType~1name\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupInfoEditType~1name\/fragments","op":"replace","value":[{"kind":"identifier","text":"GroupInfoEditTypeName"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupInfoEditType\/title","op":"replace","value":"GroupInfoEditType"},{"value":[{"kind":"identifier","text":"GroupInfoEditType"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupInfoEditType\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"GroupInfoEditType"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupInfoEditType\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupInfoEditType~1threadName\/title","value":"GroupInfoEditTypeThreadName","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupInfoEditType~1threadName\/fragments","op":"replace","value":[{"kind":"identifier","text":"GroupInfoEditTypeThreadName"}]},{"op":"replace","value":"GroupInfoEditTypeAnnouncement","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupInfoEditType~1announcement\/title"},{"value":[{"text":"GroupInfoEditTypeAnnouncement","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupInfoEditType~1announcement\/fragments"},{"value":"GroupInfoEditTypeDescription","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupInfoEditType~1description\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupInfoEditType~1description\/fragments","op":"replace","value":[{"kind":"identifier","text":"GroupInfoEditTypeDescription"}]}]}]}