{"variants":[{"paths":["\/documentation\/shengwangchatuikit\/groupchatthreadeventtype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/shengwangchatuikit\/groupchatthreadeventtype"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupChatThreadEventType","interfaceLanguage":"swift"},"topicSections":[{"generated":true,"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupChatThreadEventType\/created","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupChatThreadEventType\/destroyed","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupChatThreadEventType\/updated","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupChatThreadEventType\/userKicked"],"anchor":"Enumeration-Cases","title":"Enumeration Cases"},{"generated":true,"anchor":"Initializers","title":"Initializers","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupChatThreadEventType\/init(rawValue:)"]},{"anchor":"Default-Implementations","generated":true,"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupChatThreadEventType\/Equatable-Implementations","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupChatThreadEventType\/RawRepresentable-Implementations"],"title":"Default Implementations"}],"relationshipsSections":[{"kind":"relationships","title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/SQ","doc:\/\/org.cocoapods.ShengwangChatUIKit\/SH","doc:\/\/org.cocoapods.ShengwangChatUIKit\/SY"]}],"metadata":{"roleHeading":"Enumeration","title":"GroupChatThreadEventType","navigatorTitle":[{"text":"GroupChatThreadEventType","kind":"identifier"}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupChatThreadEventType"}],"externalID":"c:@M@ShengwangChatUIKit@E@GroupChatThreadEventType","modules":[{"name":"ShengwangChatUIKit"}],"symbolKind":"enum"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"GroupChatThreadEventType","kind":"identifier"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit"]]},"sections":[],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/GroupChatThreadEventType/userKicked":{"navigatorTitle":[{"text":"GroupChatThreadEventTypeUserKicked","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/shengwangchatuikit\/groupchatthreadeventtype\/userkicked","abstract":[],"type":"topic","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"userKicked","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupChatThreadEventType\/userKicked","role":"symbol","title":"GroupChatThreadEventType.userKicked"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/GroupChatThreadEventType/init(rawValue:)":{"url":"\/documentation\/shengwangchatuikit\/groupchatthreadeventtype\/init(rawvalue:)","type":"topic","title":"init(rawValue:)","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupChatThreadEventType\/init(rawValue:)","abstract":[],"role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"text":"rawValue","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"text":")","kind":"text"}],"kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/SH"},"doc://org.cocoapods.ShengwangChatUIKit/SY":{"title":"Swift.RawRepresentable","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/SY"},"doc://org.cocoapods.ShengwangChatUIKit/SQ":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/SQ","title":"Swift.Equatable"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/GroupChatThreadEventType/destroyed":{"navigatorTitle":[{"text":"GroupChatThreadEventTypeDestroyed","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/shengwangchatuikit\/groupchatthreadeventtype\/destroyed","abstract":[],"type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"destroyed"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupChatThreadEventType\/destroyed","role":"symbol","title":"GroupChatThreadEventType.destroyed"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/GroupChatThreadEventType/created":{"abstract":[],"url":"\/documentation\/shengwangchatuikit\/groupchatthreadeventtype\/created","title":"GroupChatThreadEventType.created","role":"symbol","navigatorTitle":[{"text":"GroupChatThreadEventTypeCreated","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupChatThreadEventType\/created","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"created","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/GroupChatThreadEventType/updated":{"abstract":[],"url":"\/documentation\/shengwangchatuikit\/groupchatthreadeventtype\/updated","title":"GroupChatThreadEventType.updated","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"GroupChatThreadEventTypeUpdated"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupChatThreadEventType\/updated","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"updated"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/GroupChatThreadEventType/RawRepresentable-Implementations":{"abstract":[],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupChatThreadEventType\/RawRepresentable-Implementations","type":"topic","kind":"article","title":"RawRepresentable Implementations","role":"collectionGroup","url":"\/documentation\/shengwangchatuikit\/groupchatthreadeventtype\/rawrepresentable-implementations"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/GroupChatThreadEventType/Equatable-Implementations":{"kind":"article","title":"Equatable Implementations","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupChatThreadEventType\/Equatable-Implementations","role":"collectionGroup","type":"topic","url":"\/documentation\/shengwangchatuikit\/groupchatthreadeventtype\/equatable-implementations","abstract":[]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/GroupChatThreadEventType":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupChatThreadEventType","title":"GroupChatThreadEventType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"GroupChatThreadEventType","kind":"identifier"}],"type":"topic","abstract":[],"url":"\/documentation\/shengwangchatuikit\/groupchatthreadeventtype","navigatorTitle":[{"text":"GroupChatThreadEventType","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"GroupChatThreadEventType"},{"path":"\/metadata\/symbolKind","op":"replace","value":"enum"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"GroupChatThreadEventType"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"GroupChatThreadEventType"}]},{"op":"replace","path":"\/topicSections","value":[{"anchor":"Enumeration-Cases","title":"Enumeration Cases","generated":true,"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupChatThreadEventType\/created","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupChatThreadEventType\/destroyed","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupChatThreadEventType\/updated","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupChatThreadEventType\/userKicked"]}]},{"op":"replace","value":null,"path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GroupChatThreadEventType"},{"text":": ","kind":"text"},{"text":"NSUInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSUInteger"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupChatThreadEventType~1userKicked\/title","op":"replace","value":"GroupChatThreadEventTypeUserKicked"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupChatThreadEventType~1userKicked\/fragments","value":[{"text":"GroupChatThreadEventTypeUserKicked","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupChatThreadEventType~1destroyed\/title","op":"replace","value":"GroupChatThreadEventTypeDestroyed"},{"op":"replace","value":[{"kind":"identifier","text":"GroupChatThreadEventTypeDestroyed"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupChatThreadEventType~1destroyed\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupChatThreadEventType~1created\/title","value":"GroupChatThreadEventTypeCreated","op":"replace"},{"value":[{"kind":"identifier","text":"GroupChatThreadEventTypeCreated"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupChatThreadEventType~1created\/fragments"},{"value":"GroupChatThreadEventTypeUpdated","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupChatThreadEventType~1updated\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupChatThreadEventType~1updated\/fragments","value":[{"kind":"identifier","text":"GroupChatThreadEventTypeUpdated"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupChatThreadEventType\/title","value":"GroupChatThreadEventType"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupChatThreadEventType\/fragments","op":"replace","value":[{"text":"GroupChatThreadEventType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupChatThreadEventType\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"GroupChatThreadEventType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}