{"kind":"symbol","metadata":{"symbolKind":"protocol","navigatorTitle":[{"text":"GroupServiceListener","kind":"identifier"}],"role":"symbol","modules":[{"name":"ShengwangChatUIKit"}],"roleHeading":"Protocol","externalID":"c:@M@ShengwangChatUIKit@objc(pl)GroupServiceListener","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GroupServiceListener"}],"title":"GroupServiceListener"},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupServiceListener"},"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)NSObject"],"type":"inheritsFrom","kind":"relationships"},{"title":"Conforming Types","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewModel"],"type":"conformingTypes","kind":"relationships"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupServiceListener"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(pl)NSObject","kind":"typeIdentifier","text":"NSObjectProtocol"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/groupservicelistener"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/groupservicelistener"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit"]]},"topicSections":[{"anchor":"Instance-Methods","title":"Instance Methods","generated":true,"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupServiceListener\/onAttributesChangedOfGroupMember(groupId:userId:operatorId:attributes:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupServiceListener\/onCurrentUserJoinedGroup(groupId:invitation:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupServiceListener\/onCurrentUserLeft(groupId:reason:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupServiceListener\/onGroupJoinApplicationApproved(groupId:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupServiceListener\/onGroupJoinApplicationDeclined(groupId:reason:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupServiceListener\/onGroupOwnerUpdated(groupId:ownerId:userId:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupServiceListener\/onInviterAcceptedInvitationOfGroup(groupId:userId:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupServiceListener\/onInviterDeclinedInvitationOfGroup(groupId:userId:reason:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupServiceListener\/onReceivedNewGroupApplication(groupId:userId:reason:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupServiceListener\/onReceivedNewGroupInvitation(groupId:groupName:userId:invitation:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupServiceListener\/onUserJoinedGroup(groupId:userId:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupServiceListener\/onUserLeaveGroup(groupId:userId:)"]}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/GroupServiceListener/onGroupOwnerUpdated(groupId:ownerId:userId:)":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupServiceListener\/onGroupOwnerUpdated(groupId:ownerId:userId:)","abstract":[{"type":"text","text":"The group owner of the current group has changed."}],"navigatorTitle":[{"kind":"identifier","text":"onGroupOwnerUpdatedWithGroupId:ownerId:userId:"}],"type":"topic","role":"symbol","url":"\/documentation\/shengwangchatuikit\/groupservicelistener\/ongroupownerupdated(groupid:ownerid:userid:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onGroupOwnerUpdated","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"groupId"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"ownerId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"userId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":")","kind":"text"}],"title":"onGroupOwnerUpdated(groupId:ownerId:userId:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageListViewModel":{"url":"\/documentation\/shengwangchatuikit\/messagelistviewmodel","title":"MessageListViewModel","role":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewModel","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MessageListViewModel"}],"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MessageListViewModel"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/GroupServiceListener/onCurrentUserJoinedGroup(groupId:invitation:)":{"kind":"symbol","url":"\/documentation\/shengwangchatuikit\/groupservicelistener\/oncurrentuserjoinedgroup(groupid:invitation:)","type":"topic","role":"symbol","abstract":[{"text":"The current user is added to the group.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"onCurrentUserJoinedGroupWithGroupId:invitation:"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"onCurrentUserJoinedGroup","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"groupId"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"invitation"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":")"}],"title":"onCurrentUserJoinedGroup(groupId:invitation:)","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupServiceListener\/onCurrentUserJoinedGroup(groupId:invitation:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/GroupServiceListener/onUserLeaveGroup(groupId:userId:)":{"required":true,"kind":"symbol","url":"\/documentation\/shengwangchatuikit\/groupservicelistener\/onuserleavegroup(groupid:userid:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"onUserLeaveGroup","kind":"identifier"},{"kind":"text","text":"("},{"text":"groupId","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"userId"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"When some user left group."}],"navigatorTitle":[{"kind":"identifier","text":"onUserLeaveGroupWithGroupId:userId:"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupServiceListener\/onUserLeaveGroup(groupId:userId:)","role":"symbol","type":"topic","title":"onUserLeaveGroup(groupId:userId:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/GroupServiceListener/onReceivedNewGroupApplication(groupId:userId:reason:)":{"role":"symbol","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"onReceivedNewGroupApplication"},{"kind":"text","text":"("},{"kind":"externalParam","text":"groupId"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"userId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"reason","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":")","kind":"text"}],"abstract":[{"text":"Received new group invitation","type":"text"}],"title":"onReceivedNewGroupApplication(groupId:userId:reason:)","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupServiceListener\/onReceivedNewGroupApplication(groupId:userId:reason:)","url":"\/documentation\/shengwangchatuikit\/groupservicelistener\/onreceivednewgroupapplication(groupid:userid:reason:)","navigatorTitle":[{"kind":"identifier","text":"onReceivedNewGroupApplicationWithGroupId:userId:reason:"}],"type":"topic"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/GroupServiceListener/onInviterAcceptedInvitationOfGroup(groupId:userId:)":{"abstract":[{"type":"text","text":"Accepted invitation of the group."}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupServiceListener\/onInviterAcceptedInvitationOfGroup(groupId:userId:)","navigatorTitle":[{"kind":"identifier","text":"onInviterAcceptedInvitationOfGroupWithGroupId:userId:"}],"type":"topic","role":"symbol","url":"\/documentation\/shengwangchatuikit\/groupservicelistener\/oninviteracceptedinvitationofgroup(groupid:userid:)","kind":"symbol","required":true,"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"onInviterAcceptedInvitationOfGroup"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"groupId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"userId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"title":"onInviterAcceptedInvitationOfGroup(groupId:userId:)"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)NSObject":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)NSObject","title":"NSObject","type":"unresolvable"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/GroupServiceListener/onUserJoinedGroup(groupId:userId:)":{"navigatorTitle":[{"text":"onUserJoinedGroupWithGroupId:userId:","kind":"identifier"}],"title":"onUserJoinedGroup(groupId:userId:)","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupServiceListener\/onUserJoinedGroup(groupId:userId:)","role":"symbol","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"onUserJoinedGroup","kind":"identifier"},{"kind":"text","text":"("},{"text":"groupId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"userId","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}],"type":"topic","abstract":[{"text":"When some user joined group.","type":"text"}],"url":"\/documentation\/shengwangchatuikit\/groupservicelistener\/onuserjoinedgroup(groupid:userid:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/GroupServiceListener/onGroupJoinApplicationApproved(groupId:)":{"abstract":[{"text":"The application to join the group was approved.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupServiceListener\/onGroupJoinApplicationApproved(groupId:)","navigatorTitle":[{"kind":"identifier","text":"onGroupJoinApplicationApprovedWithGroupId:"}],"type":"topic","role":"symbol","url":"\/documentation\/shengwangchatuikit\/groupservicelistener\/ongroupjoinapplicationapproved(groupid:)","kind":"symbol","required":true,"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"onGroupJoinApplicationApproved","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"groupId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":")","kind":"text"}],"title":"onGroupJoinApplicationApproved(groupId:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/GroupServiceListener/onCurrentUserLeft(groupId:reason:)":{"kind":"symbol","url":"\/documentation\/shengwangchatuikit\/groupservicelistener\/oncurrentuserleft(groupid:reason:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onCurrentUserLeft"},{"kind":"text","text":"("},{"text":"groupId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"reason","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:18ShengwangChatUIKit16GroupLeaveReasona","text":"GroupLeaveReason","kind":"typeIdentifier"},{"kind":"text","text":")"}],"abstract":[{"text":"Current user is removed.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"onCurrentUserLeftWithGroupId:reason:"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupServiceListener\/onCurrentUserLeft(groupId:reason:)","role":"symbol","type":"topic","title":"onCurrentUserLeft(groupId:reason:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/GroupServiceListener":{"url":"\/documentation\/shengwangchatuikit\/groupservicelistener","abstract":[],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"GroupServiceListener"}],"type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupServiceListener","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GroupServiceListener","kind":"identifier"}],"title":"GroupServiceListener"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/GroupServiceListener/onReceivedNewGroupInvitation(groupId:groupName:userId:invitation:)":{"navigatorTitle":[{"text":"onReceivedNewGroupInvitationWithGroupId:groupName:userId:invitation:","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupServiceListener\/onReceivedNewGroupInvitation(groupId:groupName:userId:invitation:)","url":"\/documentation\/shengwangchatuikit\/groupservicelistener\/onreceivednewgroupinvitation(groupid:groupname:userid:invitation:)","abstract":[{"text":"Received new group invitation","type":"text"}],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onReceivedNewGroupInvitation","kind":"identifier"},{"text":"(","kind":"text"},{"text":"groupId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"groupName","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"userId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"invitation"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"role":"symbol","title":"onReceivedNewGroupInvitation(groupId:groupName:userId:invitation:)","required":true,"kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/GroupServiceListener/onGroupJoinApplicationDeclined(groupId:reason:)":{"abstract":[{"type":"text","text":"Application to join the group was rejected"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupServiceListener\/onGroupJoinApplicationDeclined(groupId:reason:)","navigatorTitle":[{"kind":"identifier","text":"onGroupJoinApplicationDeclinedWithGroupId:reason:"}],"type":"topic","role":"symbol","url":"\/documentation\/shengwangchatuikit\/groupservicelistener\/ongroupjoinapplicationdeclined(groupid:reason:)","kind":"symbol","required":true,"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"onGroupJoinApplicationDeclined","kind":"identifier"},{"kind":"text","text":"("},{"text":"groupId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"reason","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"title":"onGroupJoinApplicationDeclined(groupId:reason:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/GroupServiceListener/onAttributesChangedOfGroupMember(groupId:userId:operatorId:attributes:)":{"role":"symbol","required":true,"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onAttributesChangedOfGroupMember","kind":"identifier"},{"text":"(","kind":"text"},{"text":"groupId","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"userId","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"operatorId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"attributes"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SD","text":"Dictionary"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":">)","kind":"text"}],"kind":"symbol","abstract":[{"text":"When attributes changed of some group member.","type":"text"}],"url":"\/documentation\/shengwangchatuikit\/groupservicelistener\/onattributeschangedofgroupmember(groupid:userid:operatorid:attributes:)","title":"onAttributesChangedOfGroupMember(groupId:userId:operatorId:attributes:)","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupServiceListener\/onAttributesChangedOfGroupMember(groupId:userId:operatorId:attributes:)","navigatorTitle":[{"text":"onAttributesChangedOfGroupMemberWithGroupId:userId:operatorId:attributes:","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/GroupServiceListener/onInviterDeclinedInvitationOfGroup(groupId:userId:reason:)":{"kind":"symbol","url":"\/documentation\/shengwangchatuikit\/groupservicelistener\/oninviterdeclinedinvitationofgroup(groupid:userid:reason:)","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"onInviterDeclinedInvitationOfGroup","kind":"identifier"},{"text":"(","kind":"text"},{"text":"groupId","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"userId"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"reason"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":")","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupServiceListener\/onInviterDeclinedInvitationOfGroup(groupId:userId:reason:)","title":"onInviterDeclinedInvitationOfGroup(groupId:userId:reason:)","navigatorTitle":[{"text":"onInviterDeclinedInvitationOfGroupWithGroupId:userId:reason:","kind":"identifier"}],"abstract":[{"type":"text","text":"When a group invitation is rejected"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Protocol","path":"\/metadata\/roleHeading"},{"value":"GroupServiceListener","op":"replace","path":"\/metadata\/title"},{"value":"protocol","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"GroupServiceListener","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":[{"text":"GroupServiceListener","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"path":"\/topicSections","op":"replace","value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupServiceListener\/onAttributesChangedOfGroupMember(groupId:userId:operatorId:attributes:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupServiceListener\/onCurrentUserJoinedGroup(groupId:invitation:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupServiceListener\/onCurrentUserLeft(groupId:reason:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupServiceListener\/onGroupJoinApplicationApproved(groupId:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupServiceListener\/onGroupJoinApplicationDeclined(groupId:reason:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupServiceListener\/onGroupOwnerUpdated(groupId:ownerId:userId:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupServiceListener\/onInviterAcceptedInvitationOfGroup(groupId:userId:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupServiceListener\/onInviterDeclinedInvitationOfGroup(groupId:userId:reason:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupServiceListener\/onReceivedNewGroupApplication(groupId:userId:reason:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupServiceListener\/onReceivedNewGroupInvitation(groupId:groupName:userId:invitation:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupServiceListener\/onUserJoinedGroup(groupId:userId:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupServiceListener\/onUserLeaveGroup(groupId:userId:)"],"generated":true,"anchor":"Instance-Methods"}]},{"op":"replace","value":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)NSObject"]},{"title":"Conforming Types","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewModel"],"type":"conformingTypes","kind":"relationships"}],"path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"text":"GroupServiceListener","kind":"identifier"},{"kind":"text","text":" <"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject"},{"text":">","kind":"text"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupServiceListener~1onGroupOwnerUpdated(groupId:ownerId:userId:)\/title","value":"onGroupOwnerUpdatedWithGroupId:ownerId:userId:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupServiceListener~1onGroupOwnerUpdated(groupId:ownerId:userId:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"onGroupOwnerUpdatedWithGroupId:ownerId:userId:","kind":"identifier"}]},{"op":"replace","value":"MessageListViewModel","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewModel\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewModel\/fragments","value":[{"text":"MessageListViewModel","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewModel\/navigatorTitle","value":[{"text":"MessageListViewModel","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupServiceListener~1onCurrentUserJoinedGroup(groupId:invitation:)\/title","value":"onCurrentUserJoinedGroupWithGroupId:invitation:"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupServiceListener~1onCurrentUserJoinedGroup(groupId:invitation:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onCurrentUserJoinedGroupWithGroupId:invitation:"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupServiceListener~1onUserLeaveGroup(groupId:userId:)\/title","value":"onUserLeaveGroupWithGroupId:userId:","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"onUserLeaveGroupWithGroupId:userId:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupServiceListener~1onUserLeaveGroup(groupId:userId:)\/fragments"},{"op":"replace","value":"onReceivedNewGroupApplicationWithGroupId:userId:reason:","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupServiceListener~1onReceivedNewGroupApplication(groupId:userId:reason:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onReceivedNewGroupApplicationWithGroupId:userId:reason:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupServiceListener~1onReceivedNewGroupApplication(groupId:userId:reason:)\/fragments"},{"value":"onInviterAcceptedInvitationOfGroupWithGroupId:userId:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupServiceListener~1onInviterAcceptedInvitationOfGroup(groupId:userId:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupServiceListener~1onInviterAcceptedInvitationOfGroup(groupId:userId:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"onInviterAcceptedInvitationOfGroupWithGroupId:userId:"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupServiceListener~1onUserJoinedGroup(groupId:userId:)\/title","op":"replace","value":"onUserJoinedGroupWithGroupId:userId:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onUserJoinedGroupWithGroupId:userId:"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupServiceListener~1onUserJoinedGroup(groupId:userId:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupServiceListener~1onGroupJoinApplicationApproved(groupId:)\/title","value":"onGroupJoinApplicationApprovedWithGroupId:"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupServiceListener~1onGroupJoinApplicationApproved(groupId:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"onGroupJoinApplicationApprovedWithGroupId:"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupServiceListener~1onCurrentUserLeft(groupId:reason:)\/title","value":"onCurrentUserLeftWithGroupId:reason:","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"onCurrentUserLeftWithGroupId:reason:"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupServiceListener~1onCurrentUserLeft(groupId:reason:)\/fragments"},{"op":"replace","value":"GroupServiceListener","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupServiceListener\/title"},{"value":[{"text":"GroupServiceListener","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupServiceListener\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupServiceListener\/navigatorTitle","value":[{"text":"GroupServiceListener","kind":"identifier"}],"op":"replace"},{"value":"onReceivedNewGroupInvitationWithGroupId:groupName:userId:invitation:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupServiceListener~1onReceivedNewGroupInvitation(groupId:groupName:userId:invitation:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onReceivedNewGroupInvitationWithGroupId:groupName:userId:invitation:"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupServiceListener~1onReceivedNewGroupInvitation(groupId:groupName:userId:invitation:)\/fragments"},{"value":"onGroupJoinApplicationDeclinedWithGroupId:reason:","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupServiceListener~1onGroupJoinApplicationDeclined(groupId:reason:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupServiceListener~1onGroupJoinApplicationDeclined(groupId:reason:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onGroupJoinApplicationDeclinedWithGroupId:reason:"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupServiceListener~1onAttributesChangedOfGroupMember(groupId:userId:operatorId:attributes:)\/title","value":"onAttributesChangedOfGroupMemberWithGroupId:userId:operatorId:attributes:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupServiceListener~1onAttributesChangedOfGroupMember(groupId:userId:operatorId:attributes:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"onAttributesChangedOfGroupMemberWithGroupId:userId:operatorId:attributes:","kind":"identifier"}],"op":"replace"},{"value":"onInviterDeclinedInvitationOfGroupWithGroupId:userId:reason:","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupServiceListener~1onInviterDeclinedInvitationOfGroup(groupId:userId:reason:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupServiceListener~1onInviterDeclinedInvitationOfGroup(groupId:userId:reason:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"onInviterDeclinedInvitationOfGroupWithGroupId:userId:reason:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}