{"abstract":[{"text":"A protocol that defines the driver for a section index list.","type":"text"}],"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)NSObject"],"title":"Inherits From","type":"inheritsFrom"},{"title":"Conforming Types","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/SectionIndexList"],"kind":"relationships","type":"conformingTypes"}],"topicSections":[{"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ISectionIndexListDriver\/refresh(titles:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ISectionIndexListDriver\/selectItem(indexPath:)"],"generated":true,"title":"Instance Methods","anchor":"Instance-Methods"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"ISectionIndexListDriver","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObjectProtocol","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject"}],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/isectionindexlistdriver"]},{"paths":["\/documentation\/shengwangchatuikit\/isectionindexlistdriver"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit"]]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ISectionIndexListDriver"},"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"ISectionIndexListDriver"}],"externalID":"c:@M@ShengwangChatUIKit@objc(pl)ISectionIndexListDriver","roleHeading":"Protocol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ISectionIndexListDriver"}],"role":"symbol","title":"ISectionIndexListDriver","modules":[{"name":"ShengwangChatUIKit"}],"symbolKind":"protocol"},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ISectionIndexListDriver/selectItem(indexPath:)":{"kind":"symbol","required":true,"title":"selectItem(indexPath:)","navigatorTitle":[{"kind":"identifier","text":"selectItemWithIndexPath:"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ISectionIndexListDriver\/selectItem(indexPath:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"selectItem","kind":"identifier"},{"kind":"text","text":"("},{"text":"indexPath","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation9IndexPathV","text":"IndexPath"},{"text":")","kind":"text"}],"type":"topic","url":"\/documentation\/shengwangchatuikit\/isectionindexlistdriver\/selectitem(indexpath:)","abstract":[{"text":"Selects an item at the specified index path.","type":"text"}]},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)NSObject":{"title":"NSObject","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)NSObject","type":"unresolvable"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/SectionIndexList":{"url":"\/documentation\/shengwangchatuikit\/sectionindexlist","kind":"symbol","type":"topic","navigatorTitle":[{"text":"SectionIndexList","kind":"identifier"}],"abstract":[],"role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/SectionIndexList","title":"SectionIndexList","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SectionIndexList","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ISectionIndexListDriver/refresh(titles:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"refresh","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"titles"},{"kind":"text","text":": ["},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"])"}],"role":"symbol","required":true,"url":"\/documentation\/shengwangchatuikit\/isectionindexlistdriver\/refresh(titles:)","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ISectionIndexListDriver\/refresh(titles:)","title":"refresh(titles:)","kind":"symbol","abstract":[{"text":"Refreshes the titles of the section index list.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"refreshWithTitles:"}],"type":"topic"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ISectionIndexListDriver":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ISectionIndexListDriver","kind":"identifier"}],"navigatorTitle":[{"text":"ISectionIndexListDriver","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/isectionindexlistdriver","type":"topic","abstract":[{"text":"A protocol that defines the driver for a section index list.","type":"text"}],"title":"ISectionIndexListDriver","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ISectionIndexListDriver","role":"symbol","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Protocol","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"ISectionIndexListDriver"},{"path":"\/metadata\/symbolKind","value":"protocol","op":"replace"},{"value":[{"text":"ISectionIndexListDriver","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"ISectionIndexListDriver","kind":"identifier"}]},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ISectionIndexListDriver\/refresh(titles:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ISectionIndexListDriver\/selectItem(indexPath:)"],"generated":true,"title":"Instance Methods","anchor":"Instance-Methods"}],"op":"replace"},{"path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"kind":"relationships","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/SectionIndexList"],"title":"Conforming Types","type":"conformingTypes"}],"op":"replace"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ISectionIndexListDriver"},{"text":" <","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject","text":"NSObject"},{"text":">","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"selectItemWithIndexPath:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ISectionIndexListDriver~1selectItem(indexPath:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ISectionIndexListDriver~1selectItem(indexPath:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"selectItemWithIndexPath:"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1SectionIndexList\/title","value":"SectionIndexList","op":"replace"},{"value":[{"kind":"identifier","text":"SectionIndexList"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1SectionIndexList\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SectionIndexList"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1SectionIndexList\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ISectionIndexListDriver~1refresh(titles:)\/title","value":"refreshWithTitles:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"refreshWithTitles:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ISectionIndexListDriver~1refresh(titles:)\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ISectionIndexListDriver\/title","op":"replace","value":"ISectionIndexListDriver"},{"value":[{"text":"ISectionIndexListDriver","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ISectionIndexListDriver\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"ISectionIndexListDriver"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ISectionIndexListDriver\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}