{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit"]]},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships"},{"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)NSObject","doc:\/\/org.cocoapods.ShengwangChatUIKit\/s7CVarArgP","doc:\/\/org.cocoapods.ShengwangChatUIKit\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.ShengwangChatUIKit\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.ShengwangChatUIKit\/SQ","doc:\/\/org.cocoapods.ShengwangChatUIKit\/SH"],"title":"Conforms To","kind":"relationships","type":"conformsTo"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LanguageConvertor"}],"platforms":["iOS"],"languages":["swift"]}]}],"kind":"symbol","variants":[{"paths":["\/documentation\/shengwangchatuikit\/languageconvertor"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/languageconvertor"]}],"metadata":{"externalID":"c:@M@ShengwangChatUIKit@objc(cs)LanguageConvertor","role":"symbol","roleHeading":"Class","title":"LanguageConvertor","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LanguageConvertor"}],"navigatorTitle":[{"text":"LanguageConvertor","kind":"identifier"}],"modules":[{"name":"ShengwangChatUIKit"}],"symbolKind":"class"},"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/LanguageConvertor","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"A utility class for converting language keys to localized strings."}],"topicSections":[{"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/LanguageConvertor\/shared"],"anchor":"Type-Properties","generated":true,"title":"Type Properties"},{"generated":true,"anchor":"Type-Methods","title":"Type Methods","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/LanguageConvertor\/localValue(key:)"]}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/SQ"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/LanguageConvertor/localValue(key:)":{"type":"topic","role":"symbol","abstract":[],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"localValue","kind":"identifier"},{"text":"(","kind":"text"},{"text":"key","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/LanguageConvertor\/localValue(key:)","title":"localValue(key:)","url":"\/documentation\/shengwangchatuikit\/languageconvertor\/localvalue(key:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/LanguageConvertor/shared":{"url":"\/documentation\/shengwangchatuikit\/languageconvertor\/shared","kind":"symbol","type":"topic","abstract":[],"role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/LanguageConvertor\/shared","title":"shared","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"shared"},{"text":": ","kind":"text"},{"text":"LanguageConvertor","kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)LanguageConvertor"}]},"doc://org.cocoapods.ShengwangChatUIKit/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/SH"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)NSObject"},"doc://org.cocoapods.ShengwangChatUIKit/s23CustomStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/LanguageConvertor":{"navigatorTitle":[{"text":"LanguageConvertor","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/languageconvertor","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LanguageConvertor","kind":"identifier"}],"role":"symbol","title":"LanguageConvertor","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/LanguageConvertor","kind":"symbol","abstract":[{"type":"text","text":"A utility class for converting language keys to localized strings."}]},"doc://org.cocoapods.ShengwangChatUIKit/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://org.cocoapods.ShengwangChatUIKit/s7CVarArgP":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/objc(cs)NSObject":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","value":"LanguageConvertor","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"LanguageConvertor","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"LanguageConvertor","kind":"identifier"}]},{"path":"\/topicSections","op":"replace","value":null},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom"}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"LanguageConvertor","kind":"identifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1LanguageConvertor\/title","value":"LanguageConvertor","op":"replace"},{"value":[{"kind":"identifier","text":"LanguageConvertor"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1LanguageConvertor\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1LanguageConvertor\/navigatorTitle","value":[{"text":"LanguageConvertor","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}