{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"@","kind":"attribute"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"LinkRecognizeTextView","kind":"identifier"}]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/LinkRecognizeTextView","interfaceLanguage":"swift"},"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(cs)UITextView"],"kind":"relationships"},{"kind":"relationships","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)NSCoding","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)NSObject","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)CALayerDelegate","doc:\/\/org.cocoapods.ShengwangChatUIKit\/s7CVarArgP","doc:\/\/org.cocoapods.ShengwangChatUIKit\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.ShengwangChatUIKit\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.ShengwangChatUIKit\/SQ","doc:\/\/org.cocoapods.ShengwangChatUIKit\/SH","doc:\/\/org.cocoapods.ShengwangChatUIKit\/s8SendableP","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIAccessibilityIdentification","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIAppearance","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIAppearanceContainer","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIContentSizeCategoryAdjusting","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UICoordinateSpace","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIDynamicItem","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIFindInteractionDelegate","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIFocusEnvironment","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIFocusItem","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIFocusItemContainer","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIFocusItemScrollableContainer","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIKeyInput","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UILargeContentViewerItem","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UILetterformAwareAdjusting","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIResponderStandardEditActions","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIScrollViewDelegate","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UITextDraggable","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UITextDroppable","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UITextInput","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UITextInputTraits","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UITextPasteConfigurationSupporting","doc:\/\/org.cocoapods.ShengwangChatUIKit\/5UIKit15UITextSearchingP","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UITextViewDelegate","doc:\/\/org.cocoapods.ShengwangChatUIKit\/5UIKit23UITraitChangeObservableP","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UITraitEnvironment","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIUserActivityRestoring"],"type":"conformsTo","title":"Conforms To"}],"sections":[],"variants":[{"paths":["\/documentation\/shengwangchatuikit\/linkrecognizetextview"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/linkrecognizetextview"]}],"kind":"symbol","metadata":{"externalID":"c:@M@ShengwangChatUIKit@objc(cs)LinkRecognizeTextView","navigatorTitle":[{"text":"LinkRecognizeTextView","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"LinkRecognizeTextView","kind":"identifier"}],"title":"LinkRecognizeTextView","role":"symbol","roleHeading":"Class","modules":[{"name":"ShengwangChatUIKit"}],"symbolKind":"class"},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit"]]},"topicSections":[{"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/LinkRecognizeTextView\/init(coder:)"],"anchor":"Initializers","title":"Initializers","generated":true},{"anchor":"Instance-Properties","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/LinkRecognizeTextView\/clickAction","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/LinkRecognizeTextView\/hasURL","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/LinkRecognizeTextView\/longPressAction","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/LinkRecognizeTextView\/selectedRange","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/LinkRecognizeTextView\/selectedTextColor"],"title":"Instance Properties","generated":true},{"generated":true,"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/LinkRecognizeTextView\/canPerformAction(_:withSender:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/LinkRecognizeTextView\/selectAll(_:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/LinkRecognizeTextView\/tapAction(gesture:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/LinkRecognizeTextView\/textViewDidChangeSelection(_:)"],"anchor":"Instance-Methods"}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UIFocusItemContainer":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIFocusItemContainer","title":"UIKit.UIFocusItemContainer"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UITraitEnvironment":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UITraitEnvironment","title":"UIKit.UITraitEnvironment"},"doc://org.cocoapods.ShengwangChatUIKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://org.cocoapods.ShengwangChatUIKit/5UIKit15UITextSearchingP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/5UIKit15UITextSearchingP","title":"UIKit.UITextSearching"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIResponderStandardEditActions","title":"UIKit.UIResponderStandardEditActions"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/LinkRecognizeTextView/longPressAction":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"longPressAction"},{"kind":"text","text":": (() -> "},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")?","kind":"text"}],"type":"topic","abstract":[],"role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/LinkRecognizeTextView\/longPressAction","kind":"symbol","title":"longPressAction","url":"\/documentation\/shengwangchatuikit\/linkrecognizetextview\/longpressaction"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UITextPasteConfigurationSupporting":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UITextPasteConfigurationSupporting","title":"UIKit.UITextPasteConfigurationSupporting"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/LinkRecognizeTextView/selectAll(_:)":{"abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"selectAll","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"?)","kind":"text"}],"role":"symbol","type":"topic","url":"\/documentation\/shengwangchatuikit\/linkrecognizetextview\/selectall(_:)","title":"selectAll(_:)","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/LinkRecognizeTextView\/selectAll(_:)","navigatorTitle":[{"text":"selectAll:","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UIAppearance":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIAppearance","title":"UIKit.UIAppearance"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/LinkRecognizeTextView":{"title":"LinkRecognizeTextView","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"LinkRecognizeTextView","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/shengwangchatuikit\/linkrecognizetextview","type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/LinkRecognizeTextView","navigatorTitle":[{"kind":"identifier","text":"LinkRecognizeTextView"}]},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UIAppearanceContainer":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIAppearanceContainer","title":"UIKit.UIAppearanceContainer"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/LinkRecognizeTextView/textViewDidChangeSelection(_:)":{"title":"textViewDidChangeSelection(_:)","role":"symbol","abstract":[],"kind":"symbol","url":"\/documentation\/shengwangchatuikit\/linkrecognizetextview\/textviewdidchangeselection(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"textViewDidChangeSelection"},{"kind":"text","text":"("},{"text":"UITextView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITextView"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"textViewDidChangeSelection:"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/LinkRecognizeTextView\/textViewDidChangeSelection(_:)"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIActivityItemsConfigurationProviding","title":"UIKit.UIActivityItemsConfigurationProviding"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UIAccessibilityIdentification":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIAccessibilityIdentification","title":"UIKit.UIAccessibilityIdentification"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UITextInputTraits":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UITextInputTraits","title":"UIKit.UITextInputTraits"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/LinkRecognizeTextView/hasURL":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"hasURL"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"type":"topic","role":"symbol","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/LinkRecognizeTextView\/hasURL","url":"\/documentation\/shengwangchatuikit\/linkrecognizetextview\/hasurl","title":"hasURL"},"doc://org.cocoapods.ShengwangChatUIKit/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/s7CVarArgP","title":"Swift.CVarArg"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UIScrollViewDelegate":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIScrollViewDelegate","title":"UIKit.UIScrollViewDelegate"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UILetterformAwareAdjusting":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UILetterformAwareAdjusting","title":"UIKit.UILetterformAwareAdjusting"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)CALayerDelegate":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)CALayerDelegate","title":"QuartzCore.CALayerDelegate"},"doc://org.cocoapods.ShengwangChatUIKit/5UIKit23UITraitChangeObservableP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/5UIKit23UITraitChangeObservableP","title":"UIKit.UITraitChangeObservable"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UIFocusItemScrollableContainer":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIFocusItemScrollableContainer","title":"UIKit.UIFocusItemScrollableContainer"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UICoordinateSpace":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UICoordinateSpace","title":"UIKit.UICoordinateSpace"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UIContentSizeCategoryAdjusting":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIContentSizeCategoryAdjusting","title":"UIKit.UIContentSizeCategoryAdjusting"},"doc://org.cocoapods.ShengwangChatUIKit/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIPasteConfigurationSupporting","title":"UIKit.UIPasteConfigurationSupporting"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UIFocusEnvironment":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIFocusEnvironment","title":"UIKit.UIFocusEnvironment"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/LinkRecognizeTextView/selectedTextColor":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/LinkRecognizeTextView\/selectedTextColor","url":"\/documentation\/shengwangchatuikit\/linkrecognizetextview\/selectedtextcolor","type":"topic","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"selectedTextColor"},{"text":": ","kind":"text"},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"}],"title":"selectedTextColor","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/SH"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UIPopoverPresentationControllerSourceItem":{"title":"UIKit.UIPopoverPresentationControllerSourceItem","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIPopoverPresentationControllerSourceItem"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UITextDraggable":{"title":"UIKit.UITextDraggable","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UITextDraggable"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UIUserActivityRestoring":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIUserActivityRestoring","title":"UIKit.UIUserActivityRestoring","type":"unresolvable"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UIFocusItem":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIFocusItem","title":"UIKit.UIFocusItem","type":"unresolvable"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/LinkRecognizeTextView/tapAction(gesture:)":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/LinkRecognizeTextView\/tapAction(gesture:)","navigatorTitle":[{"text":"tapActionWithGesture:","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/linkrecognizetextview\/tapaction(gesture:)","type":"topic","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"tapAction"},{"text":"(","kind":"text"},{"text":"gesture","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UITapGestureRecognizer","kind":"typeIdentifier","text":"UITapGestureRecognizer"},{"text":")","kind":"text"}],"title":"tapAction(gesture:)","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UILargeContentViewerItem":{"title":"UIKit.UILargeContentViewerItem","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UILargeContentViewerItem"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/LinkRecognizeTextView/init(coder:)":{"abstract":[],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/LinkRecognizeTextView\/init(coder:)","navigatorTitle":[{"text":"initWithCoder:","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/shengwangchatuikit\/linkrecognizetextview\/init(coder:)","kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"coder"},{"text":": ","kind":"text"},{"text":"NSCoder","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSCoder"},{"kind":"text","text":")"}],"title":"init(coder:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UITextViewDelegate":{"title":"UITextViewDelegate","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UITextViewDelegate"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/LinkRecognizeTextView/clickAction":{"title":"clickAction","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/LinkRecognizeTextView\/clickAction","role":"symbol","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"clickAction"},{"text":": (() -> ","kind":"text"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?"}],"type":"topic","abstract":[],"url":"\/documentation\/shengwangchatuikit\/linkrecognizetextview\/clickaction"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UIDynamicItem":{"title":"UIKit.UIDynamicItem","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIDynamicItem"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)NSObject"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UIKeyInput":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIKeyInput","title":"UIKit.UIKeyInput"},"doc://org.cocoapods.ShengwangChatUIKit/SQ":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/SQ","title":"Swift.Equatable"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UITextInput":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UITextInput","title":"UIKit.UITextInput"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/LinkRecognizeTextView/canPerformAction(_:withSender:)":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/LinkRecognizeTextView\/canPerformAction(_:withSender:)","navigatorTitle":[{"kind":"identifier","text":"canPerformAction:withSender:"}],"url":"\/documentation\/shengwangchatuikit\/linkrecognizetextview\/canperformaction(_:withsender:)","type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"canPerformAction"},{"text":"(","kind":"text"},{"text":"Selector","kind":"typeIdentifier","preciseIdentifier":"s:10ObjectiveC8SelectorV"},{"kind":"text","text":", "},{"text":"withSender","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"title":"canPerformAction(_:withSender:)","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UIFindInteractionDelegate":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIFindInteractionDelegate","title":"UIKit.UIFindInteractionDelegate","type":"unresolvable"},"doc://org.cocoapods.ShengwangChatUIKit/s8SendableP":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/s8SendableP","title":"Swift.Sendable","type":"unresolvable"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/LinkRecognizeTextView/selectedRange":{"navigatorTitle":[{"kind":"identifier","text":"selectedRange"}],"url":"\/documentation\/shengwangchatuikit\/linkrecognizetextview\/selectedrange","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"selectedRange","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSRange","preciseIdentifier":"c:@T@NSRange","kind":"typeIdentifier"}],"role":"symbol","title":"selectedRange","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/LinkRecognizeTextView\/selectedRange","kind":"symbol","abstract":[]},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UITextDroppable":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UITextDroppable","title":"UIKit.UITextDroppable","type":"unresolvable"},"doc://org.cocoapods.ShengwangChatUIKit/objc(cs)UITextView":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(cs)UITextView","title":"UITextView","type":"unresolvable"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)NSCoding":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)NSCoding","title":"Foundation.NSCoding","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","value":"LinkRecognizeTextView","op":"replace"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"LinkRecognizeTextView"}],"op":"replace"},{"value":[{"text":"LinkRecognizeTextView","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/LinkRecognizeTextView\/selectedRange"],"generated":true,"title":"Instance Properties","anchor":"Instance-Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/LinkRecognizeTextView\/canPerformAction(_:withSender:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/LinkRecognizeTextView\/init(coder:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/LinkRecognizeTextView\/selectAll(_:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/LinkRecognizeTextView\/tapAction(gesture:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/LinkRecognizeTextView\/textViewDidChangeSelection(_:)"],"anchor":"Instance-Methods","generated":true}],"op":"replace","path":"\/topicSections"},{"op":"replace","value":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(cs)UITextView"],"kind":"relationships"},{"title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UITextViewDelegate"],"kind":"relationships"}],"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LinkRecognizeTextView"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","text":"UITextView","preciseIdentifier":"c:objc(cs)UITextView"}]}]}},{"op":"replace","value":"selectAll:","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1LinkRecognizeTextView~1selectAll(_:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"selectAll:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1LinkRecognizeTextView~1selectAll(_:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1LinkRecognizeTextView\/title","op":"replace","value":"LinkRecognizeTextView"},{"op":"replace","value":[{"kind":"identifier","text":"LinkRecognizeTextView"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1LinkRecognizeTextView\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1LinkRecognizeTextView\/navigatorTitle","value":[{"text":"LinkRecognizeTextView","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1LinkRecognizeTextView~1textViewDidChangeSelection(_:)\/title","op":"replace","value":"textViewDidChangeSelection:"},{"value":[{"text":"- ","kind":"text"},{"text":"textViewDidChangeSelection:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1LinkRecognizeTextView~1textViewDidChangeSelection(_:)\/fragments"},{"value":"tapActionWithGesture:","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1LinkRecognizeTextView~1tapAction(gesture:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"tapActionWithGesture:"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1LinkRecognizeTextView~1tapAction(gesture:)\/fragments","op":"replace"},{"value":"initWithCoder:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1LinkRecognizeTextView~1init(coder:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1LinkRecognizeTextView~1init(coder:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithCoder:"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1LinkRecognizeTextView~1canPerformAction(_:withSender:)\/title","value":"canPerformAction:withSender:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1LinkRecognizeTextView~1canPerformAction(_:withSender:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"canPerformAction:withSender:"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1LinkRecognizeTextView~1selectedRange\/title","value":"selectedRange","op":"replace"},{"op":"replace","value":[{"text":"selectedRange","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1LinkRecognizeTextView~1selectedRange\/fragments"}]}]}