{"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/shengwangchatuikit\/mentionupdate"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/mentionupdate"]}],"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MentionUpdate","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit"]]},"topicSections":[{"title":"Enumeration Cases","anchor":"Enumeration-Cases","generated":true,"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MentionUpdate\/add","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MentionUpdate\/delete"]},{"anchor":"Initializers","title":"Initializers","generated":true,"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MentionUpdate\/init(rawValue:)"]},{"title":"Default Implementations","generated":true,"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MentionUpdate\/Equatable-Implementations","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MentionUpdate\/RawRepresentable-Implementations"],"anchor":"Default-Implementations"}],"metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"MentionUpdate","kind":"identifier"}],"externalID":"c:@M@ShengwangChatUIKit@E@MentionUpdate","role":"symbol","roleHeading":"Enumeration","title":"MentionUpdate","modules":[{"name":"ShengwangChatUIKit"}],"symbolKind":"enum","navigatorTitle":[{"text":"MentionUpdate","kind":"identifier"}]},"kind":"symbol","relationshipsSections":[{"type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/SQ","doc:\/\/org.cocoapods.ShengwangChatUIKit\/SH","doc:\/\/org.cocoapods.ShengwangChatUIKit\/SY"],"kind":"relationships"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"MentionUpdate","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MentionUpdate/Equatable-Implementations":{"abstract":[],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MentionUpdate\/Equatable-Implementations","type":"topic","role":"collectionGroup","url":"\/documentation\/shengwangchatuikit\/mentionupdate\/equatable-implementations","kind":"article","title":"Equatable Implementations"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MentionUpdate/delete":{"navigatorTitle":[{"kind":"identifier","text":"MentionUpdateDelete"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"delete","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/mentionupdate\/delete","abstract":[],"role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MentionUpdate\/delete","title":"MentionUpdate.delete","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/SH":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MentionUpdate/add":{"type":"topic","title":"MentionUpdate.add","navigatorTitle":[{"text":"MentionUpdateAdd","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MentionUpdate\/add","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"add","kind":"identifier"}],"kind":"symbol","role":"symbol","url":"\/documentation\/shengwangchatuikit\/mentionupdate\/add"},"doc://org.cocoapods.ShengwangChatUIKit/SY":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/SY","type":"unresolvable","title":"Swift.RawRepresentable"},"doc://org.cocoapods.ShengwangChatUIKit/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/SQ"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MentionUpdate":{"type":"topic","navigatorTitle":[{"text":"MentionUpdate","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"MentionUpdate","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MentionUpdate","title":"MentionUpdate","url":"\/documentation\/shengwangchatuikit\/mentionupdate","abstract":[],"kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MentionUpdate/init(rawValue:)":{"fragments":[{"kind":"identifier","text":"init"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/shengwangchatuikit\/mentionupdate\/init(rawvalue:)","abstract":[],"role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MentionUpdate\/init(rawValue:)","title":"init(rawValue:)","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MentionUpdate/RawRepresentable-Implementations":{"title":"RawRepresentable Implementations","role":"collectionGroup","type":"topic","kind":"article","abstract":[],"url":"\/documentation\/shengwangchatuikit\/mentionupdate\/rawrepresentable-implementations","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MentionUpdate\/RawRepresentable-Implementations"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Enumeration","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"MentionUpdate","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"MentionUpdate"}]},{"path":"\/metadata\/navigatorTitle","value":[{"text":"MentionUpdate","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/topicSections","value":[{"generated":true,"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MentionUpdate\/add","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MentionUpdate\/delete"],"anchor":"Enumeration-Cases","title":"Enumeration Cases"}]},{"value":null,"op":"replace","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MentionUpdate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSUInteger","text":"NSUInteger"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MentionUpdate~1delete\/title","op":"replace","value":"MentionUpdateDelete"},{"value":[{"text":"MentionUpdateDelete","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MentionUpdate~1delete\/fragments"},{"value":"MentionUpdateAdd","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MentionUpdate~1add\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MentionUpdate~1add\/fragments","value":[{"kind":"identifier","text":"MentionUpdateAdd"}]},{"op":"replace","value":"MentionUpdate","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MentionUpdate\/title"},{"value":[{"kind":"identifier","text":"MentionUpdate"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MentionUpdate\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MentionUpdate\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MentionUpdate"}]}]}]}