{"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewActionEventsDelegate","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessageListViewActionEventsDelegate","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(pl)NSObject","kind":"typeIdentifier","text":"NSObjectProtocol"}],"platforms":["iOS"],"languages":["swift"]}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit"]]},"metadata":{"role":"symbol","title":"MessageListViewActionEventsDelegate","externalID":"c:@M@ShengwangChatUIKit@objc(pl)MessageListViewActionEventsDelegate","symbolKind":"protocol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MessageListViewActionEventsDelegate"}],"modules":[{"name":"ShengwangChatUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"MessageListViewActionEventsDelegate"}],"roleHeading":"Protocol"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/messagelistviewactioneventsdelegate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/messagelistviewactioneventsdelegate"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"topicSections":[{"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewActionEventsDelegate\/onFailureMessageRetrySend(entity:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewActionEventsDelegate\/onInputBoxEventsOccur(action:attributeText:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewActionEventsDelegate\/onMessageAvatarClicked(profile:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewActionEventsDelegate\/onMessageAvatarLongPressed(profile:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewActionEventsDelegate\/onMessageContentClicked(message:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewActionEventsDelegate\/onMessageContentLongPressed(cell:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewActionEventsDelegate\/onMessageListLoadMore()","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewActionEventsDelegate\/onMessageListPullRefresh()","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewActionEventsDelegate\/onMessageMultiSelectBarClicked(operation:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewActionEventsDelegate\/onMessageReactionClicked(reaction:entity:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewActionEventsDelegate\/onMessageReplyClicked(message:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewActionEventsDelegate\/onMessageTopicClicked(entity:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewActionEventsDelegate\/onMessageVisible(entity:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewActionEventsDelegate\/onMoreMessagesClicked()"],"generated":true,"title":"Instance Methods","anchor":"Instance-Methods"}],"relationshipsSections":[{"type":"inheritsFrom","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)NSObject"],"title":"Inherits From","kind":"relationships"},{"kind":"relationships","type":"conformingTypes","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadCreateController","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewModel","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewModel"],"title":"Conforming Types"}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageListViewActionEventsDelegate/onMessageContentClicked(message:)":{"abstract":[{"text":"The method will call on message content clicked.","type":"text"}],"kind":"symbol","url":"\/documentation\/shengwangchatuikit\/messagelistviewactioneventsdelegate\/onmessagecontentclicked(message:)","required":true,"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onMessageContentClicked"},{"text":"(","kind":"text"},{"text":"message","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)MessageEntity","text":"MessageEntity"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"onMessageContentClickedWithMessage:","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewActionEventsDelegate\/onMessageContentClicked(message:)","type":"topic","title":"onMessageContentClicked(message:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageListViewActionEventsDelegate/onFailureMessageRetrySend(entity:)":{"url":"\/documentation\/shengwangchatuikit\/messagelistviewactioneventsdelegate\/onfailuremessageretrysend(entity:)","type":"topic","abstract":[{"text":"The method will call on failure message status view clicked.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onFailureMessageRetrySend"},{"kind":"text","text":"("},{"text":"entity","kind":"externalParam"},{"kind":"text","text":": "},{"text":"MessageEntity","kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)MessageEntity"},{"kind":"text","text":")"}],"title":"onFailureMessageRetrySend(entity:)","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewActionEventsDelegate\/onFailureMessageRetrySend(entity:)","required":true,"navigatorTitle":[{"kind":"identifier","text":"onFailureMessageRetrySendWithEntity:"}],"role":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)NSObject"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageListViewActionEventsDelegate/onMoreMessagesClicked()":{"url":"\/documentation\/shengwangchatuikit\/messagelistviewactioneventsdelegate\/onmoremessagesclicked()","type":"topic","abstract":[{"type":"text","text":"More messages button clicked."}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onMoreMessagesClicked"},{"text":"()","kind":"text"}],"title":"onMoreMessagesClicked()","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewActionEventsDelegate\/onMoreMessagesClicked()","required":true,"navigatorTitle":[{"kind":"identifier","text":"onMoreMessagesClicked"}],"role":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageListViewActionEventsDelegate/onMessageTopicClicked(entity:)":{"type":"topic","required":true,"role":"symbol","title":"onMessageTopicClicked(entity:)","kind":"symbol","abstract":[{"type":"text","text":"Message topic view clicked."}],"navigatorTitle":[{"text":"onMessageTopicClickedWithEntity:","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/messagelistviewactioneventsdelegate\/onmessagetopicclicked(entity:)","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewActionEventsDelegate\/onMessageTopicClicked(entity:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onMessageTopicClicked","kind":"identifier"},{"text":"(","kind":"text"},{"text":"entity","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)MessageEntity","text":"MessageEntity","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageListViewActionEventsDelegate/onMessageVisible(entity:)":{"navigatorTitle":[{"text":"onMessageVisibleWithEntity:","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/messagelistviewactioneventsdelegate\/onmessagevisible(entity:)","type":"topic","required":true,"role":"symbol","title":"onMessageVisible(entity:)","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewActionEventsDelegate\/onMessageVisible(entity:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onMessageVisible","kind":"identifier"},{"text":"(","kind":"text"},{"text":"entity","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)MessageEntity","text":"MessageEntity"},{"text":")","kind":"text"}],"kind":"symbol","abstract":[{"type":"text","text":"Message visible on scroll in screen"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageListViewActionEventsDelegate/onMessageAvatarLongPressed(profile:)":{"navigatorTitle":[{"text":"onMessageAvatarLongPressedWithProfile:","kind":"identifier"}],"abstract":[{"type":"text","text":"The method will call on message avatar long pressed."}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewActionEventsDelegate\/onMessageAvatarLongPressed(profile:)","url":"\/documentation\/shengwangchatuikit\/messagelistviewactioneventsdelegate\/onmessageavatarlongpressed(profile:)","role":"symbol","title":"onMessageAvatarLongPressed(profile:)","required":true,"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"onMessageAvatarLongPressed","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"profile"},{"kind":"text","text":": "},{"text":"ChatUserProfileProtocol","kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(pl)ChatUserProfileProtocol"},{"kind":"text","text":")"}],"kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageListViewActionEventsDelegate/onMessageReplyClicked(message:)":{"url":"\/documentation\/shengwangchatuikit\/messagelistviewactioneventsdelegate\/onmessagereplyclicked(message:)","type":"topic","abstract":[{"type":"text","text":"The method will call on message reply content clicked."}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"onMessageReplyClicked"},{"kind":"text","text":"("},{"text":"message","kind":"externalParam"},{"kind":"text","text":": "},{"text":"MessageEntity","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)MessageEntity","kind":"typeIdentifier"},{"kind":"text","text":")"}],"title":"onMessageReplyClicked(message:)","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewActionEventsDelegate\/onMessageReplyClicked(message:)","required":true,"navigatorTitle":[{"text":"onMessageReplyClickedWithMessage:","kind":"identifier"}],"role":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatThreadCreateController":{"title":"ChatThreadCreateController","abstract":[],"url":"\/documentation\/shengwangchatuikit\/chatthreadcreatecontroller","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadCreateController","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ChatThreadCreateController","kind":"identifier"}],"navigatorTitle":[{"text":"ChatThreadCreateController","kind":"identifier"}],"role":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageListViewActionEventsDelegate/onMessageListLoadMore()":{"navigatorTitle":[{"text":"onMessageListLoadMore","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewActionEventsDelegate\/onMessageListLoadMore()","url":"\/documentation\/shengwangchatuikit\/messagelistviewactioneventsdelegate\/onmessagelistloadmore()","role":"symbol","title":"onMessageListLoadMore()","required":true,"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"onMessageListLoadMore","kind":"identifier"},{"kind":"text","text":"()"}],"kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageListViewActionEventsDelegate/onMessageContentLongPressed(cell:)":{"role":"symbol","abstract":[{"text":"The method will call on message content long pressed.","type":"text"}],"title":"onMessageContentLongPressed(cell:)","navigatorTitle":[{"text":"onMessageContentLongPressedWithCell:","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewActionEventsDelegate\/onMessageContentLongPressed(cell:)","url":"\/documentation\/shengwangchatuikit\/messagelistviewactioneventsdelegate\/onmessagecontentlongpressed(cell:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onMessageContentLongPressed","kind":"identifier"},{"text":"(","kind":"text"},{"text":"cell","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)MessageCell","text":"MessageCell","kind":"typeIdentifier"},{"text":")","kind":"text"}],"required":true,"kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageListViewActionEventsDelegate":{"navigatorTitle":[{"text":"MessageListViewActionEventsDelegate","kind":"identifier"}],"title":"MessageListViewActionEventsDelegate","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewActionEventsDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"MessageListViewActionEventsDelegate","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/messagelistviewactioneventsdelegate","abstract":[],"kind":"symbol","type":"topic"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageListViewModel":{"url":"\/documentation\/shengwangchatuikit\/messagelistviewmodel","title":"MessageListViewModel","role":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewModel","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MessageListViewModel"}],"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MessageListViewModel"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageListViewActionEventsDelegate/onMessageListPullRefresh()":{"url":"\/documentation\/shengwangchatuikit\/messagelistviewactioneventsdelegate\/onmessagelistpullrefresh()","type":"topic","abstract":[{"type":"text","text":"The method will call on message list pull to refreshing."}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"onMessageListPullRefresh","kind":"identifier"},{"text":"()","kind":"text"}],"title":"onMessageListPullRefresh()","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewActionEventsDelegate\/onMessageListPullRefresh()","required":true,"navigatorTitle":[{"kind":"identifier","text":"onMessageListPullRefresh"}],"role":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageListViewActionEventsDelegate/onInputBoxEventsOccur(action:attributeText:)":{"navigatorTitle":[{"kind":"identifier","text":"onInputBoxEventsOccurWithAction:attributeText:"}],"url":"\/documentation\/shengwangchatuikit\/messagelistviewactioneventsdelegate\/oninputboxeventsoccur(action:attributetext:)","type":"topic","required":true,"role":"symbol","title":"onInputBoxEventsOccur(action:attributeText:)","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewActionEventsDelegate\/onInputBoxEventsOccur(action:attributeText:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onInputBoxEventsOccur"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"action"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MessageInputBarActionType","preciseIdentifier":"c:@M@ShengwangChatUIKit@E@MessageInputBarActionType"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"attributeText"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSAttributedString","text":"NSAttributedString","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"kind":"symbol","abstract":[{"type":"text","text":"The method will call on input box event occur."}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageListViewActionEventsDelegate/onMessageAvatarClicked(profile:)":{"navigatorTitle":[{"text":"onMessageAvatarClickedWithProfile:","kind":"identifier"}],"title":"onMessageAvatarClicked(profile:)","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewActionEventsDelegate\/onMessageAvatarClicked(profile:)","required":true,"kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onMessageAvatarClicked","kind":"identifier"},{"kind":"text","text":"("},{"text":"profile","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(pl)ChatUserProfileProtocol","kind":"typeIdentifier","text":"ChatUserProfileProtocol"},{"kind":"text","text":")"}],"type":"topic","abstract":[{"type":"text","text":"The method will call on message avatar clicked"}],"url":"\/documentation\/shengwangchatuikit\/messagelistviewactioneventsdelegate\/onmessageavatarclicked(profile:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatThreadViewModel":{"navigatorTitle":[{"text":"ChatThreadViewModel","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewModel","url":"\/documentation\/shengwangchatuikit\/chatthreadviewmodel","abstract":[],"role":"symbol","kind":"symbol","type":"topic","title":"ChatThreadViewModel","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChatThreadViewModel","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageListViewActionEventsDelegate/onMessageMultiSelectBarClicked(operation:)":{"navigatorTitle":[{"text":"onMessageMultiSelectBarClickedWithOperation:","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/messagelistviewactioneventsdelegate\/onmessagemultiselectbarclicked(operation:)","type":"topic","required":true,"role":"symbol","title":"onMessageMultiSelectBarClicked(operation:)","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewActionEventsDelegate\/onMessageMultiSelectBarClicked(operation:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onMessageMultiSelectBarClicked"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"operation"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@E@MessageMultiSelectedBottomBarOperation","text":"MessageMultiSelectedBottomBarOperation","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","abstract":[{"type":"text","text":"When message multi select bar clicked."}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageListViewActionEventsDelegate/onMessageReactionClicked(reaction:entity:)":{"kind":"symbol","role":"symbol","required":true,"navigatorTitle":[{"kind":"identifier","text":"onMessageReactionClickedWithReaction:entity:"}],"title":"onMessageReactionClicked(reaction:entity:)","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewActionEventsDelegate\/onMessageReactionClicked(reaction:entity:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"onMessageReactionClicked","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"reaction"},{"kind":"text","text":": "},{"text":"MessageReaction","preciseIdentifier":"s:18ShengwangChatUIKit15MessageReactiona","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"entity","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)MessageEntity","text":"MessageEntity","kind":"typeIdentifier"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Message reaction&"},{"code":"...","type":"codeVoice"},{"type":"text","text":" clicked."}],"type":"topic","url":"\/documentation\/shengwangchatuikit\/messagelistviewactioneventsdelegate\/onmessagereactionclicked(reaction:entity:)"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Protocol","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"MessageListViewActionEventsDelegate","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"MessageListViewActionEventsDelegate","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MessageListViewActionEventsDelegate"}],"op":"replace"},{"path":"\/topicSections","op":"replace","value":[{"generated":true,"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewActionEventsDelegate\/onFailureMessageRetrySend(entity:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewActionEventsDelegate\/onInputBoxEventsOccur(action:attributeText:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewActionEventsDelegate\/onMessageAvatarClicked(profile:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewActionEventsDelegate\/onMessageAvatarLongPressed(profile:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewActionEventsDelegate\/onMessageContentClicked(message:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewActionEventsDelegate\/onMessageContentLongPressed(cell:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewActionEventsDelegate\/onMessageListLoadMore()","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewActionEventsDelegate\/onMessageListPullRefresh()","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewActionEventsDelegate\/onMessageMultiSelectBarClicked(operation:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewActionEventsDelegate\/onMessageReactionClicked(reaction:entity:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewActionEventsDelegate\/onMessageReplyClicked(message:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewActionEventsDelegate\/onMessageTopicClicked(entity:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewActionEventsDelegate\/onMessageVisible(entity:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewActionEventsDelegate\/onMoreMessagesClicked()"],"anchor":"Instance-Methods","title":"Instance Methods"}]},{"value":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)NSObject"]},{"kind":"relationships","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadCreateController","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewModel","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewModel"],"type":"conformingTypes","title":"Conforming Types"}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageListViewActionEventsDelegate"},{"text":" <","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject","text":"NSObject"},{"kind":"text","text":">"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewActionEventsDelegate~1onMessageContentClicked(message:)\/title","value":"onMessageContentClickedWithMessage:"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewActionEventsDelegate~1onMessageContentClicked(message:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"onMessageContentClickedWithMessage:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewActionEventsDelegate~1onFailureMessageRetrySend(entity:)\/title","value":"onFailureMessageRetrySendWithEntity:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onFailureMessageRetrySendWithEntity:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewActionEventsDelegate~1onFailureMessageRetrySend(entity:)\/fragments"},{"value":"onMoreMessagesClicked","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewActionEventsDelegate~1onMoreMessagesClicked()\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewActionEventsDelegate~1onMoreMessagesClicked()\/fragments","value":[{"kind":"text","text":"- "},{"text":"onMoreMessagesClicked","kind":"identifier"}]},{"value":"onMessageTopicClickedWithEntity:","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewActionEventsDelegate~1onMessageTopicClicked(entity:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewActionEventsDelegate~1onMessageTopicClicked(entity:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"onMessageTopicClickedWithEntity:","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewActionEventsDelegate~1onMessageVisible(entity:)\/title","value":"onMessageVisibleWithEntity:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"onMessageVisibleWithEntity:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewActionEventsDelegate~1onMessageVisible(entity:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewActionEventsDelegate~1onMessageAvatarLongPressed(profile:)\/title","value":"onMessageAvatarLongPressedWithProfile:"},{"value":[{"text":"- ","kind":"text"},{"text":"onMessageAvatarLongPressedWithProfile:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewActionEventsDelegate~1onMessageAvatarLongPressed(profile:)\/fragments","op":"replace"},{"value":"onMessageReplyClickedWithMessage:","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewActionEventsDelegate~1onMessageReplyClicked(message:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewActionEventsDelegate~1onMessageReplyClicked(message:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"onMessageReplyClickedWithMessage:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadCreateController\/title","op":"replace","value":"ChatThreadCreateController"},{"op":"replace","value":[{"text":"ChatThreadCreateController","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadCreateController\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadCreateController\/navigatorTitle","value":[{"kind":"identifier","text":"ChatThreadCreateController"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewActionEventsDelegate~1onMessageListLoadMore()\/title","value":"onMessageListLoadMore","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onMessageListLoadMore"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewActionEventsDelegate~1onMessageListLoadMore()\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewActionEventsDelegate~1onMessageContentLongPressed(cell:)\/title","value":"onMessageContentLongPressedWithCell:"},{"value":[{"text":"- ","kind":"text"},{"text":"onMessageContentLongPressedWithCell:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewActionEventsDelegate~1onMessageContentLongPressed(cell:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewActionEventsDelegate\/title","value":"MessageListViewActionEventsDelegate"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewActionEventsDelegate\/fragments","op":"replace","value":[{"text":"MessageListViewActionEventsDelegate","kind":"identifier"}]},{"op":"replace","value":[{"text":"MessageListViewActionEventsDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewActionEventsDelegate\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewModel\/title","value":"MessageListViewModel"},{"value":[{"kind":"identifier","text":"MessageListViewModel"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewModel\/fragments"},{"op":"replace","value":[{"text":"MessageListViewModel","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewModel\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewActionEventsDelegate~1onMessageListPullRefresh()\/title","value":"onMessageListPullRefresh"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewActionEventsDelegate~1onMessageListPullRefresh()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"onMessageListPullRefresh","kind":"identifier"}]},{"value":"onInputBoxEventsOccurWithAction:attributeText:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewActionEventsDelegate~1onInputBoxEventsOccur(action:attributeText:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"onInputBoxEventsOccurWithAction:attributeText:"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewActionEventsDelegate~1onInputBoxEventsOccur(action:attributeText:)\/fragments"},{"value":"onMessageAvatarClickedWithProfile:","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewActionEventsDelegate~1onMessageAvatarClicked(profile:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewActionEventsDelegate~1onMessageAvatarClicked(profile:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onMessageAvatarClickedWithProfile:"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadViewModel\/title","op":"replace","value":"ChatThreadViewModel"},{"op":"replace","value":[{"kind":"identifier","text":"ChatThreadViewModel"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadViewModel\/fragments"},{"value":[{"kind":"identifier","text":"ChatThreadViewModel"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadViewModel\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewActionEventsDelegate~1onMessageMultiSelectBarClicked(operation:)\/title","value":"onMessageMultiSelectBarClickedWithOperation:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"onMessageMultiSelectBarClickedWithOperation:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewActionEventsDelegate~1onMessageMultiSelectBarClicked(operation:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewActionEventsDelegate~1onMessageReactionClicked(reaction:entity:)\/title","value":"onMessageReactionClickedWithReaction:entity:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewActionEventsDelegate~1onMessageReactionClicked(reaction:entity:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onMessageReactionClickedWithReaction:entity:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}