{"variants":[{"paths":["\/documentation\/shengwangchatuikit\/messageattachmentmenustyle"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/messageattachmentmenustyle"]}],"kind":"symbol","topicSections":[{"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageAttachmentMenuStyle\/actionSheet","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageAttachmentMenuStyle\/followInput"],"anchor":"Enumeration-Cases","title":"Enumeration Cases","generated":true},{"anchor":"Initializers","generated":true,"title":"Initializers","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageAttachmentMenuStyle\/init(rawValue:)"]},{"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageAttachmentMenuStyle\/Equatable-Implementations","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageAttachmentMenuStyle\/RawRepresentable-Implementations"],"anchor":"Default-Implementations","generated":true,"title":"Default Implementations"}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageAttachmentMenuStyle"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessageAttachmentMenuStyle","kind":"identifier"}],"externalID":"c:@M@ShengwangChatUIKit@E@MessageAttachmentMenuStyle","role":"symbol","roleHeading":"Enumeration","modules":[{"name":"ShengwangChatUIKit"}],"title":"MessageAttachmentMenuStyle","symbolKind":"enum","navigatorTitle":[{"kind":"identifier","text":"MessageAttachmentMenuStyle"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageAttachmentMenuStyle"}],"platforms":["iOS"]}]}],"relationshipsSections":[{"kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/SQ","doc:\/\/org.cocoapods.ShengwangChatUIKit\/SH","doc:\/\/org.cocoapods.ShengwangChatUIKit\/SY"],"title":"Conforms To"}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageAttachmentMenuStyle/actionSheet":{"url":"\/documentation\/shengwangchatuikit\/messageattachmentmenustyle\/actionsheet","abstract":[],"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageAttachmentMenuStyle\/actionSheet","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"actionSheet"}],"navigatorTitle":[{"kind":"identifier","text":"MessageAttachmentMenuStyleActionSheet"}],"role":"symbol","title":"MessageAttachmentMenuStyle.actionSheet"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/SY":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/SY","title":"Swift.RawRepresentable","type":"unresolvable"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageAttachmentMenuStyle":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"MessageAttachmentMenuStyle"}],"url":"\/documentation\/shengwangchatuikit\/messageattachmentmenustyle","kind":"symbol","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageAttachmentMenuStyle"}],"abstract":[],"title":"MessageAttachmentMenuStyle","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageAttachmentMenuStyle"},"doc://org.cocoapods.ShengwangChatUIKit/SQ":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://org.cocoapods.ShengwangChatUIKit/SH":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageAttachmentMenuStyle/RawRepresentable-Implementations":{"url":"\/documentation\/shengwangchatuikit\/messageattachmentmenustyle\/rawrepresentable-implementations","abstract":[],"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageAttachmentMenuStyle\/RawRepresentable-Implementations","kind":"article","role":"collectionGroup","title":"RawRepresentable Implementations"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageAttachmentMenuStyle/init(rawValue:)":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageAttachmentMenuStyle\/init(rawValue:)","title":"init(rawValue:)","kind":"symbol","abstract":[],"role":"symbol","url":"\/documentation\/shengwangchatuikit\/messageattachmentmenustyle\/init(rawvalue:)","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"rawValue"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5UInt8V","text":"UInt8"},{"text":")","kind":"text"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageAttachmentMenuStyle/followInput":{"abstract":[],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageAttachmentMenuStyle\/followInput","navigatorTitle":[{"kind":"identifier","text":"MessageAttachmentMenuStyleFollowInput"}],"type":"topic","role":"symbol","url":"\/documentation\/shengwangchatuikit\/messageattachmentmenustyle\/followinput","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"followInput"}],"title":"MessageAttachmentMenuStyle.followInput"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageAttachmentMenuStyle/Equatable-Implementations":{"url":"\/documentation\/shengwangchatuikit\/messageattachmentmenustyle\/equatable-implementations","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageAttachmentMenuStyle\/Equatable-Implementations","role":"collectionGroup","type":"topic","title":"Equatable Implementations","kind":"article","abstract":[]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"path":"\/metadata\/title","op":"replace","value":"MessageAttachmentMenuStyle"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MessageAttachmentMenuStyle"}],"op":"replace"},{"value":[{"text":"MessageAttachmentMenuStyle","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"op":"replace","value":[{"title":"Enumeration Cases","generated":true,"anchor":"Enumeration-Cases","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageAttachmentMenuStyle\/actionSheet","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageAttachmentMenuStyle\/followInput"]}],"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"replace"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageAttachmentMenuStyle"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@uint8_t","text":"uint8_t","kind":"typeIdentifier"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageAttachmentMenuStyle~1actionSheet\/title","value":"MessageAttachmentMenuStyleActionSheet"},{"value":[{"kind":"identifier","text":"MessageAttachmentMenuStyleActionSheet"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageAttachmentMenuStyle~1actionSheet\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageAttachmentMenuStyle\/title","value":"MessageAttachmentMenuStyle"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageAttachmentMenuStyle\/fragments","value":[{"text":"MessageAttachmentMenuStyle","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageAttachmentMenuStyle\/navigatorTitle","value":[{"kind":"identifier","text":"MessageAttachmentMenuStyle"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageAttachmentMenuStyle~1followInput\/title","value":"MessageAttachmentMenuStyleFollowInput"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageAttachmentMenuStyle~1followInput\/fragments","value":[{"text":"MessageAttachmentMenuStyleFollowInput","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}