{"sections":[],"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/SQ","doc:\/\/org.cocoapods.ShengwangChatUIKit\/SH","doc:\/\/org.cocoapods.ShengwangChatUIKit\/SY"],"title":"Conforms To","type":"conformsTo"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit"]]},"abstract":[{"type":"text","text":"The types of actions that can be triggered by the input bar."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageInputBarActionType"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/messageinputbaractiontype"]},{"paths":["\/documentation\/shengwangchatuikit\/messageinputbaractiontype"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageInputBarActionType"}],"externalID":"c:@M@ShengwangChatUIKit@E@MessageInputBarActionType","role":"symbol","roleHeading":"Enumeration","modules":[{"name":"ShengwangChatUIKit"}],"title":"MessageInputBarActionType","symbolKind":"enum","navigatorTitle":[{"kind":"identifier","text":"MessageInputBarActionType"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MessageInputBarActionType"}]}],"kind":"declarations"}],"topicSections":[{"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageInputBarActionType\/attachment","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageInputBarActionType\/audio","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageInputBarActionType\/cancelMention","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageInputBarActionType\/emojiKeyboard","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageInputBarActionType\/mention","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageInputBarActionType\/send","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageInputBarActionType\/startTyping","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageInputBarActionType\/textKeyboard"],"title":"Enumeration Cases","anchor":"Enumeration-Cases","generated":true},{"anchor":"Initializers","title":"Initializers","generated":true,"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageInputBarActionType\/init(rawValue:)"]},{"anchor":"Default-Implementations","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageInputBarActionType\/Equatable-Implementations","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageInputBarActionType\/RawRepresentable-Implementations"],"title":"Default Implementations","generated":true}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageInputBarActionType/send":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageInputBarActionType\/send","abstract":[],"type":"topic","kind":"symbol","title":"MessageInputBarActionType.send","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"send"}],"url":"\/documentation\/shengwangchatuikit\/messageinputbaractiontype\/send","navigatorTitle":[{"kind":"identifier","text":"MessageInputBarActionTypeSend"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageInputBarActionType/init(rawValue:)":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"text":"rawValue","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"},{"kind":"text","text":")"}],"url":"\/documentation\/shengwangchatuikit\/messageinputbaractiontype\/init(rawvalue:)","abstract":[],"role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageInputBarActionType\/init(rawValue:)","title":"init(rawValue:)","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageInputBarActionType/cancelMention":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageInputBarActionType\/cancelMention","url":"\/documentation\/shengwangchatuikit\/messageinputbaractiontype\/cancelmention","abstract":[],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cancelMention"}],"navigatorTitle":[{"text":"MessageInputBarActionTypeCancelMention","kind":"identifier"}],"type":"topic","title":"MessageInputBarActionType.cancelMention"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageInputBarActionType/audio":{"navigatorTitle":[{"kind":"identifier","text":"MessageInputBarActionTypeAudio"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"audio","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/messageinputbaractiontype\/audio","abstract":[],"role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageInputBarActionType\/audio","title":"MessageInputBarActionType.audio","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageInputBarActionType/attachment":{"abstract":[],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageInputBarActionType\/attachment","navigatorTitle":[{"kind":"identifier","text":"MessageInputBarActionTypeAttachment"}],"type":"topic","role":"symbol","url":"\/documentation\/shengwangchatuikit\/messageinputbaractiontype\/attachment","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"attachment"}],"title":"MessageInputBarActionType.attachment"},"doc://org.cocoapods.ShengwangChatUIKit/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/SQ"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageInputBarActionType/textKeyboard":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageInputBarActionType\/textKeyboard","title":"MessageInputBarActionType.textKeyboard","role":"symbol","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"textKeyboard","kind":"identifier"}],"abstract":[],"url":"\/documentation\/shengwangchatuikit\/messageinputbaractiontype\/textkeyboard","navigatorTitle":[{"text":"MessageInputBarActionTypeTextKeyboard","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageInputBarActionType/emojiKeyboard":{"navigatorTitle":[{"kind":"identifier","text":"MessageInputBarActionTypeEmojiKeyboard"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"emojiKeyboard","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/messageinputbaractiontype\/emojikeyboard","abstract":[],"role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageInputBarActionType\/emojiKeyboard","title":"MessageInputBarActionType.emojiKeyboard","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/SH"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageInputBarActionType":{"navigatorTitle":[{"kind":"identifier","text":"MessageInputBarActionType"}],"abstract":[{"text":"The types of actions that can be triggered by the input bar.","type":"text"}],"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"MessageInputBarActionType","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/messageinputbaractiontype","role":"symbol","title":"MessageInputBarActionType","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageInputBarActionType"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageInputBarActionType/startTyping":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageInputBarActionType\/startTyping","navigatorTitle":[{"text":"MessageInputBarActionTypeStartTyping","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/messageinputbaractiontype\/starttyping","type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"startTyping"}],"title":"MessageInputBarActionType.startTyping","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageInputBarActionType/RawRepresentable-Implementations":{"url":"\/documentation\/shengwangchatuikit\/messageinputbaractiontype\/rawrepresentable-implementations","abstract":[],"role":"collectionGroup","type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageInputBarActionType\/RawRepresentable-Implementations","title":"RawRepresentable Implementations","kind":"article"},"doc://org.cocoapods.ShengwangChatUIKit/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/SY"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageInputBarActionType/mention":{"navigatorTitle":[{"kind":"identifier","text":"MessageInputBarActionTypeMention"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"mention","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/messageinputbaractiontype\/mention","abstract":[],"role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageInputBarActionType\/mention","title":"MessageInputBarActionType.mention","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageInputBarActionType/Equatable-Implementations":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageInputBarActionType\/Equatable-Implementations","url":"\/documentation\/shengwangchatuikit\/messageinputbaractiontype\/equatable-implementations","abstract":[],"kind":"article","role":"collectionGroup","title":"Equatable Implementations","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration"},{"path":"\/metadata\/title","value":"MessageInputBarActionType","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"value":[{"kind":"identifier","text":"MessageInputBarActionType"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"MessageInputBarActionType"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"op":"replace","value":[{"generated":true,"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageInputBarActionType\/attachment","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageInputBarActionType\/audio","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageInputBarActionType\/cancelMention","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageInputBarActionType\/emojiKeyboard","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageInputBarActionType\/mention","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageInputBarActionType\/send","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageInputBarActionType\/startTyping","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageInputBarActionType\/textKeyboard"],"anchor":"Enumeration-Cases","title":"Enumeration Cases"}],"path":"\/topicSections"},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageInputBarActionType"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSUInteger","text":"NSUInteger","kind":"typeIdentifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageInputBarActionType~1send\/title","value":"MessageInputBarActionTypeSend","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageInputBarActionType~1send\/fragments","op":"replace","value":[{"kind":"identifier","text":"MessageInputBarActionTypeSend"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageInputBarActionType~1cancelMention\/title","value":"MessageInputBarActionTypeCancelMention"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageInputBarActionType~1cancelMention\/fragments","value":[{"text":"MessageInputBarActionTypeCancelMention","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"MessageInputBarActionTypeAudio","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageInputBarActionType~1audio\/title"},{"op":"replace","value":[{"kind":"identifier","text":"MessageInputBarActionTypeAudio"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageInputBarActionType~1audio\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageInputBarActionType~1attachment\/title","op":"replace","value":"MessageInputBarActionTypeAttachment"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageInputBarActionType~1attachment\/fragments","op":"replace","value":[{"kind":"identifier","text":"MessageInputBarActionTypeAttachment"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageInputBarActionType~1textKeyboard\/title","value":"MessageInputBarActionTypeTextKeyboard"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageInputBarActionType~1textKeyboard\/fragments","value":[{"text":"MessageInputBarActionTypeTextKeyboard","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageInputBarActionType~1emojiKeyboard\/title","value":"MessageInputBarActionTypeEmojiKeyboard"},{"value":[{"kind":"identifier","text":"MessageInputBarActionTypeEmojiKeyboard"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageInputBarActionType~1emojiKeyboard\/fragments"},{"value":"MessageInputBarActionType","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageInputBarActionType\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageInputBarActionType\/fragments","value":[{"text":"MessageInputBarActionType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageInputBarActionType\/navigatorTitle","value":[{"kind":"identifier","text":"MessageInputBarActionType"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageInputBarActionType~1startTyping\/title","value":"MessageInputBarActionTypeStartTyping"},{"value":[{"kind":"identifier","text":"MessageInputBarActionTypeStartTyping"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageInputBarActionType~1startTyping\/fragments"},{"value":"MessageInputBarActionTypeMention","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageInputBarActionType~1mention\/title"},{"value":[{"text":"MessageInputBarActionTypeMention","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageInputBarActionType~1mention\/fragments","op":"replace"}]}]}