{"sections":[],"metadata":{"title":"Mode","role":"symbol","modules":[{"name":"ShengwangChatUIKit"}],"externalID":"c:@E@Mode","roleHeading":"Structure","symbolKind":"struct","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"Mode","kind":"identifier"}],"navigatorTitle":[{"text":"Mode","kind":"identifier"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Mode"}],"platforms":["iOS"],"languages":["swift"]}]}],"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/Mode","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit"]]},"topicSections":[{"title":"Initializers","generated":true,"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/Mode\/init(_:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/Mode\/init(rawValue:)"],"anchor":"Initializers"},{"generated":true,"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/Mode\/rawValue"],"anchor":"Instance-Properties","title":"Instance Properties"},{"generated":true,"anchor":"Default-Implementations","title":"Default Implementations","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/Mode\/Equatable-Implementations"]}],"relationshipsSections":[{"kind":"relationships","title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/s15BitwiseCopyableP","doc:\/\/org.cocoapods.ShengwangChatUIKit\/SQ","doc:\/\/org.cocoapods.ShengwangChatUIKit\/SY","doc:\/\/org.cocoapods.ShengwangChatUIKit\/s8SendableP"]}],"variants":[{"paths":["\/documentation\/shengwangchatuikit\/mode"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/shengwangchatuikit\/mode"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/SQ":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/SQ","title":"Swift.Equatable"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MR475":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MR475","title":"MR475","abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"MR475","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Mode","kind":"typeIdentifier","preciseIdentifier":"c:@E@Mode"}],"url":"\/documentation\/shengwangchatuikit\/mr475","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MR475"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MR122":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"MR122"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Mode","preciseIdentifier":"c:@E@Mode"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"MR122"}],"title":"MR122","url":"\/documentation\/shengwangchatuikit\/mr122","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MR122","role":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/Mode":{"title":"Mode","role":"symbol","navigatorTitle":[{"text":"Mode","kind":"identifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"Mode","kind":"identifier"}],"kind":"symbol","abstract":[],"url":"\/documentation\/shengwangchatuikit\/mode","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/Mode"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MR67":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MR67","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MR67"},{"text":": ","kind":"text"},{"text":"Mode","kind":"typeIdentifier","preciseIdentifier":"c:@E@Mode"}],"title":"MR67","type":"topic","role":"symbol","url":"\/documentation\/shengwangchatuikit\/mr67","kind":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"MR67"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/Mode/init(_:)":{"type":"topic","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"UInt32","kind":"typeIdentifier","preciseIdentifier":"s:s6UInt32V"},{"text":")","kind":"text"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/Mode\/init(_:)","kind":"symbol","url":"\/documentation\/shengwangchatuikit\/mode\/init(_:)","title":"init(_:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MR515":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MR515","title":"MR515","abstract":[],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MR515","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@Mode","kind":"typeIdentifier","text":"Mode"}],"url":"\/documentation\/shengwangchatuikit\/mr515","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MR515"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/N_MODES":{"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"N_MODES"},{"text":": ","kind":"text"},{"text":"Mode","kind":"typeIdentifier","preciseIdentifier":"c:@E@Mode"}],"abstract":[],"navigatorTitle":[{"text":"N_MODES","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/N_MODES","kind":"symbol","url":"\/documentation\/shengwangchatuikit\/n_modes","title":"N_MODES"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/Mode/rawValue":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/Mode\/rawValue","title":"rawValue","abstract":[],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rawValue","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s6UInt32V","kind":"typeIdentifier","text":"UInt32"}],"url":"\/documentation\/shengwangchatuikit\/mode\/rawvalue","type":"topic"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MR59":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MR59","url":"\/documentation\/shengwangchatuikit\/mr59","type":"topic","role":"symbol","title":"MR59","navigatorTitle":[{"kind":"identifier","text":"MR59"}],"abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MR59","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@Mode","kind":"typeIdentifier","text":"Mode"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/Mode/init(rawValue:)":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/Mode\/init(rawValue:)","abstract":[],"role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s6UInt32V","text":"UInt32","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"init(rawValue:)","url":"\/documentation\/shengwangchatuikit\/mode\/init(rawvalue:)","type":"topic"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/Mode/Equatable-Implementations":{"type":"topic","role":"collectionGroup","abstract":[],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/Mode\/Equatable-Implementations","kind":"article","url":"\/documentation\/shengwangchatuikit\/mode\/equatable-implementations","title":"Equatable Implementations"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MR102":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MR102","title":"MR102","abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"MR102","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Mode","preciseIdentifier":"c:@E@Mode","kind":"typeIdentifier"}],"url":"\/documentation\/shengwangchatuikit\/mr102","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MR102"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MRDTX":{"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"MRDTX","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@Mode","text":"Mode"}],"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"MRDTX"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MRDTX","kind":"symbol","url":"\/documentation\/shengwangchatuikit\/mrdtx","title":"MRDTX"},"doc://org.cocoapods.ShengwangChatUIKit/SY":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/SY","title":"Swift.RawRepresentable"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MR74":{"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"MR74","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Mode","preciseIdentifier":"c:@E@Mode","kind":"typeIdentifier"}],"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"MR74"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MR74","kind":"symbol","url":"\/documentation\/shengwangchatuikit\/mr74","title":"MR74"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MR795":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MR795","title":"MR795","role":"symbol","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MR795"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@Mode","kind":"typeIdentifier","text":"Mode"}],"abstract":[],"url":"\/documentation\/shengwangchatuikit\/mr795","navigatorTitle":[{"kind":"identifier","text":"MR795"}]},"doc://org.cocoapods.ShengwangChatUIKit/s15BitwiseCopyableP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/s15BitwiseCopyableP","title":"Swift.BitwiseCopyable"},"doc://org.cocoapods.ShengwangChatUIKit/s8SendableP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/s8SendableP","title":"Swift.Sendable"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"Mode"},{"path":"\/metadata\/symbolKind","op":"replace","value":"enum"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"Mode"}],"op":"replace"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"Mode","kind":"identifier"}]},{"op":"replace","value":[{"anchor":"Enumeration-Cases","title":"Enumeration Cases","generated":true,"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MR102","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MR122","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MR475","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MR515","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MR59","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MR67","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MR74","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MR795","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MRDTX","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/N_MODES"]}],"path":"\/topicSections"},{"value":null,"op":"replace","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"Mode","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:i","text":"unsigned int","kind":"typeIdentifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MR475\/title","value":"MR475"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MR475\/fragments","value":[{"text":"MR475","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MR122\/title","value":"MR122"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MR122\/fragments","value":[{"kind":"identifier","text":"MR122"}]},{"op":"replace","value":"Mode","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1Mode\/title"},{"value":[{"text":"Mode","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1Mode\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1Mode\/navigatorTitle","op":"replace","value":[{"text":"Mode","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MR67\/title","value":"MR67"},{"value":[{"kind":"identifier","text":"MR67"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MR67\/fragments"},{"value":"MR515","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MR515\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MR515\/fragments","op":"replace","value":[{"kind":"identifier","text":"MR515"}]},{"op":"replace","value":"N_MODES","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1N_MODES\/title"},{"value":[{"kind":"identifier","text":"N_MODES"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1N_MODES\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MR59\/title","value":"MR59","op":"replace"},{"value":[{"kind":"identifier","text":"MR59"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MR59\/fragments","op":"replace"},{"op":"replace","value":"MR102","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MR102\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MR102\/fragments","value":[{"kind":"identifier","text":"MR102"}],"op":"replace"},{"value":"MRDTX","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MRDTX\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MRDTX\/fragments","value":[{"kind":"identifier","text":"MRDTX"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MR74\/title","value":"MR74"},{"op":"replace","value":[{"text":"MR74","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MR74\/fragments"},{"op":"replace","value":"MR795","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MR795\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MR795\/fragments","op":"replace","value":[{"kind":"identifier","text":"MR795"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}