{"metadata":{"roleHeading":"Enumeration","title":"MoreMessagePosition","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"MoreMessagePosition","kind":"identifier"}],"externalID":"c:@M@ShengwangChatUIKit@E@MoreMessagePosition","modules":[{"name":"ShengwangChatUIKit"}],"symbolKind":"enum","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MoreMessagePosition"}]},"relationshipsSections":[{"title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/SQ","doc:\/\/org.cocoapods.ShengwangChatUIKit\/SH","doc:\/\/org.cocoapods.ShengwangChatUIKit\/SY"],"type":"conformsTo"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MoreMessagePosition\/center","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MoreMessagePosition\/left","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MoreMessagePosition\/right"],"generated":true,"anchor":"Enumeration-Cases"},{"generated":true,"title":"Initializers","anchor":"Initializers","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MoreMessagePosition\/init(rawValue:)"]},{"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MoreMessagePosition\/Equatable-Implementations","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MoreMessagePosition\/RawRepresentable-Implementations"],"title":"Default Implementations","generated":true,"anchor":"Default-Implementations"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MoreMessagePosition","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/moremessageposition"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/moremessageposition"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MoreMessagePosition"},"kind":"symbol","references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MoreMessagePosition/Equatable-Implementations":{"title":"Equatable Implementations","abstract":[],"url":"\/documentation\/shengwangchatuikit\/moremessageposition\/equatable-implementations","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MoreMessagePosition\/Equatable-Implementations","kind":"article","type":"topic","role":"collectionGroup"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MoreMessagePosition/RawRepresentable-Implementations":{"role":"collectionGroup","url":"\/documentation\/shengwangchatuikit\/moremessageposition\/rawrepresentable-implementations","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MoreMessagePosition\/RawRepresentable-Implementations","title":"RawRepresentable Implementations","kind":"article","abstract":[],"type":"topic"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MoreMessagePosition/right":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"right"}],"url":"\/documentation\/shengwangchatuikit\/moremessageposition\/right","abstract":[],"kind":"symbol","type":"topic","title":"MoreMessagePosition.right","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MoreMessagePosition\/right","navigatorTitle":[{"text":"MoreMessagePositionRight","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MoreMessagePosition":{"kind":"symbol","navigatorTitle":[{"text":"MoreMessagePosition","kind":"identifier"}],"title":"MoreMessagePosition","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MoreMessagePosition","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MoreMessagePosition"}],"type":"topic","url":"\/documentation\/shengwangchatuikit\/moremessageposition","abstract":[]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MoreMessagePosition/center":{"type":"topic","title":"MoreMessagePosition.center","url":"\/documentation\/shengwangchatuikit\/moremessageposition\/center","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"center","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MoreMessagePosition\/center","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MoreMessagePositionCenter"}],"role":"symbol","abstract":[]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MoreMessagePosition/init(rawValue:)":{"title":"init(rawValue:)","abstract":[],"fragments":[{"kind":"identifier","text":"init"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/shengwangchatuikit\/moremessageposition\/init(rawvalue:)","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MoreMessagePosition\/init(rawValue:)","kind":"symbol","type":"topic","role":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/SY":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/SY","title":"Swift.RawRepresentable","type":"unresolvable"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MoreMessagePosition/left":{"title":"MoreMessagePosition.left","abstract":[],"navigatorTitle":[{"text":"MoreMessagePositionLeft","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"left","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/moremessageposition\/left","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MoreMessagePosition\/left","kind":"symbol","type":"topic","role":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/SH":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/SH","title":"Swift.Hashable"},"doc://org.cocoapods.ShengwangChatUIKit/SQ":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/SQ","title":"Swift.Equatable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"MoreMessagePosition","path":"\/metadata\/title"},{"value":"enum","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"MoreMessagePosition"}],"path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"MoreMessagePosition","kind":"identifier"}]},{"path":"\/topicSections","value":[{"title":"Enumeration Cases","anchor":"Enumeration-Cases","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MoreMessagePosition\/center","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MoreMessagePosition\/left","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MoreMessagePosition\/right"],"generated":true}],"op":"replace"},{"op":"replace","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MoreMessagePosition"},{"text":": ","kind":"text"},{"text":"NSUInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSUInteger"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"value":"MoreMessagePositionRight","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MoreMessagePosition~1right\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MoreMessagePosition~1right\/fragments","value":[{"kind":"identifier","text":"MoreMessagePositionRight"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MoreMessagePosition\/title","value":"MoreMessagePosition","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MoreMessagePosition\/fragments","value":[{"kind":"identifier","text":"MoreMessagePosition"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MoreMessagePosition\/navigatorTitle","value":[{"text":"MoreMessagePosition","kind":"identifier"}],"op":"replace"},{"value":"MoreMessagePositionCenter","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MoreMessagePosition~1center\/title","op":"replace"},{"value":[{"text":"MoreMessagePositionCenter","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MoreMessagePosition~1center\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MoreMessagePosition~1left\/title","value":"MoreMessagePositionLeft","op":"replace"},{"value":[{"kind":"identifier","text":"MoreMessagePositionLeft"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MoreMessagePosition~1left\/fragments"}]}]}