{"variants":[{"paths":["\/documentation\/shengwangchatuikit\/multideviceservice"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/multideviceservice"]}],"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MultiDeviceService","kind":"identifier"},{"kind":"text","text":" : "},{"text":"NSObjectProtocol","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"relationshipsSections":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)NSObject"]},{"type":"conformingTypes","title":"Conforming Types","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MultiDeviceServiceImplement"]}],"metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"MultiDeviceService","kind":"identifier"}],"externalID":"c:@M@ShengwangChatUIKit@objc(pl)MultiDeviceService","modules":[{"name":"ShengwangChatUIKit"}],"roleHeading":"Protocol","symbolKind":"protocol","title":"MultiDeviceService","role":"symbol","navigatorTitle":[{"text":"MultiDeviceService","kind":"identifier"}]},"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MultiDeviceService","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit"]]},"kind":"symbol","topicSections":[{"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MultiDeviceService\/bindMultiDeviceListener(listener:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MultiDeviceService\/unbindMultiDeviceListener(listener:)"],"generated":true,"title":"Instance Methods","anchor":"Instance-Methods"}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MultiDeviceService":{"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MultiDeviceService"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MultiDeviceService","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MultiDeviceService"}],"role":"symbol","title":"MultiDeviceService","url":"\/documentation\/shengwangchatuikit\/multideviceservice","abstract":[]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MultiDeviceServiceImplement":{"abstract":[],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MultiDeviceServiceImplement","url":"\/documentation\/shengwangchatuikit\/multideviceserviceimplement","type":"topic","title":"MultiDeviceServiceImplement","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MultiDeviceServiceImplement","kind":"identifier"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"MultiDeviceServiceImplement","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)NSObject"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MultiDeviceService/bindMultiDeviceListener(listener:)":{"title":"bindMultiDeviceListener(listener:)","type":"topic","url":"\/documentation\/shengwangchatuikit\/multideviceservice\/bindmultidevicelistener(listener:)","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MultiDeviceService\/bindMultiDeviceListener(listener:)","kind":"symbol","abstract":[{"type":"text","text":"Bind multi device changed listener"}],"required":true,"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"bindMultiDeviceListener","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"listener"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(pl)MultiDeviceListener","kind":"typeIdentifier","text":"MultiDeviceListener"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"bindMultiDeviceListenerWithListener:"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MultiDeviceService/unbindMultiDeviceListener(listener:)":{"title":"unbindMultiDeviceListener(listener:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"unbindMultiDeviceListener","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"listener"},{"text":": ","kind":"text"},{"text":"MultiDeviceListener","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(pl)MultiDeviceListener","kind":"typeIdentifier"},{"kind":"text","text":")"}],"url":"\/documentation\/shengwangchatuikit\/multideviceservice\/unbindmultidevicelistener(listener:)","navigatorTitle":[{"text":"unbindMultiDeviceListenerWithListener:","kind":"identifier"}],"abstract":[{"text":"Unbind multi device changed listener","type":"text"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MultiDeviceService\/unbindMultiDeviceListener(listener:)","type":"topic","role":"symbol","kind":"symbol","required":true}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Protocol","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"MultiDeviceService","path":"\/metadata\/title"},{"value":"protocol","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"MultiDeviceService"}]},{"value":[{"text":"MultiDeviceService","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"anchor":"Instance-Methods","title":"Instance Methods","generated":true,"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MultiDeviceService\/bindMultiDeviceListener(listener:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MultiDeviceService\/unbindMultiDeviceListener(listener:)"]}],"path":"\/topicSections"},{"op":"replace","value":[{"type":"inheritsFrom","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)NSObject"],"title":"Inherits From","kind":"relationships"},{"type":"conformingTypes","title":"Conforming Types","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MultiDeviceServiceImplement"]}],"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MultiDeviceService","kind":"identifier"},{"text":" <","kind":"text"},{"preciseIdentifier":"c:objc(pl)NSObject","text":"NSObject","kind":"typeIdentifier"},{"kind":"text","text":">"}],"languages":["occ"]}]}},{"value":"MultiDeviceService","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MultiDeviceService\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MultiDeviceService\/fragments","value":[{"kind":"identifier","text":"MultiDeviceService"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MultiDeviceService\/navigatorTitle","value":[{"text":"MultiDeviceService","kind":"identifier"}]},{"value":"MultiDeviceServiceImplement","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MultiDeviceServiceImplement\/title"},{"op":"replace","value":[{"text":"MultiDeviceServiceImplement","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MultiDeviceServiceImplement\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MultiDeviceServiceImplement\/navigatorTitle","op":"replace","value":[{"text":"MultiDeviceServiceImplement","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MultiDeviceService~1bindMultiDeviceListener(listener:)\/title","op":"replace","value":"bindMultiDeviceListenerWithListener:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MultiDeviceService~1bindMultiDeviceListener(listener:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"bindMultiDeviceListenerWithListener:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MultiDeviceService~1unbindMultiDeviceListener(listener:)\/title","value":"unbindMultiDeviceListenerWithListener:"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MultiDeviceService~1unbindMultiDeviceListener(listener:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"unbindMultiDeviceListenerWithListener:","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}