{"metadata":{"role":"symbol","roleHeading":"Class","externalID":"c:@M@ShengwangChatUIKit@objc(cs)NewContactRequestController","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NewContactRequestController"}],"symbolKind":"class","modules":[{"name":"ShengwangChatUIKit"}],"title":"NewContactRequestController","navigatorTitle":[{"kind":"identifier","text":"NewContactRequestController"}]},"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/NewContactRequestController","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"topicSections":[{"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/NewContactRequestController\/contactService","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/NewContactRequestController\/datas","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/NewContactRequestController\/empty","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/NewContactRequestController\/navigation","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/NewContactRequestController\/requestList"],"anchor":"Instance-Properties","generated":true,"title":"Instance Properties"},{"anchor":"Instance-Methods","title":"Instance Methods","generated":true,"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/NewContactRequestController\/agreeFriendRequest(userId:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/NewContactRequestController\/cellForRowAt(indexPath:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/NewContactRequestController\/createNavigation()","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/NewContactRequestController\/fillDatas()","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/NewContactRequestController\/navigationClick(type:indexPath:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/NewContactRequestController\/pop()","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/NewContactRequestController\/refreshProfiles(profiles:unknownInfoMaps:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/NewContactRequestController\/requestFriendInfo(userId:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/NewContactRequestController\/requestProfiles()","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/NewContactRequestController\/viewDidLoad()"]},{"anchor":"Default-Implementations","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/NewContactRequestController\/ThemeSwitchProtocol-Implementations","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/NewContactRequestController\/UIScrollViewDelegate-Implementations","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/NewContactRequestController\/UITableViewDataSource-Implementations"],"generated":true,"title":"Default Implementations"}],"variants":[{"paths":["\/documentation\/shengwangchatuikit\/newcontactrequestcontroller"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/shengwangchatuikit\/newcontactrequestcontroller"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NewContactRequestController"}],"platforms":["iOS"]}],"kind":"declarations"}],"relationshipsSections":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(cs)UIViewController"]},{"title":"Conforms To","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)NSCoding","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)NSExtensionRequestHandling","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)NSObject","doc:\/\/org.cocoapods.ShengwangChatUIKit\/s7CVarArgP","doc:\/\/org.cocoapods.ShengwangChatUIKit\/s8CopyableP","doc:\/\/org.cocoapods.ShengwangChatUIKit\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.ShengwangChatUIKit\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.ShengwangChatUIKit\/SQ","doc:\/\/org.cocoapods.ShengwangChatUIKit\/SH","doc:\/\/org.cocoapods.ShengwangChatUIKit\/s8SendableP","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ThemeSwitchProtocol","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIAppearanceContainer","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIContentContainer","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIFocusEnvironment","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIResponderStandardEditActions","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIScrollViewDelegate","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIStateRestoring","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UITableViewDataSource","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UITableViewDelegate","doc:\/\/org.cocoapods.ShengwangChatUIKit\/5UIKit23UITraitChangeObservableP","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UITraitEnvironment","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIUserActivityRestoring","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIViewControllerTransitioningDelegate"],"type":"conformsTo","kind":"relationships"}],"sections":[],"references":{"doc://org.cocoapods.ShengwangChatUIKit/5UIKit23UITraitChangeObservableP":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/5UIKit23UITraitChangeObservableP","title":"UIKit.UITraitChangeObservable","type":"unresolvable"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UIActivityItemsConfigurationProviding":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIActivityItemsConfigurationProviding","title":"UIKit.UIActivityItemsConfigurationProviding","type":"unresolvable"},"doc://org.cocoapods.ShengwangChatUIKit/SH":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)NSCoding":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)NSCoding","title":"Foundation.NSCoding","type":"unresolvable"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/NewContactRequestController/initWithNibName:bundle:":{"url":"\/documentation\/shengwangchatuikit\/newcontactrequestcontroller\/initwithnibname:bundle:","title":"initWithNibName:bundle:","kind":"symbol","abstract":[],"role":"symbol","navigatorTitle":[{"text":"initWithNibName:bundle:","kind":"identifier"}],"type":"topic","fragments":[{"kind":"text","text":"- "},{"text":"initWithNibName:bundle:","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/NewContactRequestController\/initWithNibName:bundle:"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UITableViewDelegate":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UITableViewDelegate","title":"UITableViewDelegate","type":"unresolvable"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/NewContactRequestController/datas":{"abstract":[],"title":"datas","type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/NewContactRequestController\/datas","url":"\/documentation\/shengwangchatuikit\/newcontactrequestcontroller\/datas","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"datas"},{"text":": [","kind":"text"},{"text":"NewContactRequest","kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)NewContactRequest"},{"text":"]","kind":"text"}],"role":"symbol","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/NewContactRequestController/viewDidLoad()":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/NewContactRequestController\/viewDidLoad()","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidLoad"},{"text":"()","kind":"text"}],"type":"topic","title":"viewDidLoad()","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"viewDidLoad"}],"abstract":[],"url":"\/documentation\/shengwangchatuikit\/newcontactrequestcontroller\/viewdidload()","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UIPasteConfigurationSupporting":{"title":"UIKit.UIPasteConfigurationSupporting","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIPasteConfigurationSupporting"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/NewContactRequestController/requestFriendInfo(userId:)":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/NewContactRequestController\/requestFriendInfo(userId:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"requestFriendInfo"},{"kind":"text","text":"("},{"text":"userId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":")","kind":"text"}],"type":"topic","title":"requestFriendInfo(userId:)","role":"symbol","navigatorTitle":[{"text":"requestFriendInfoWithUserId:","kind":"identifier"}],"abstract":[],"url":"\/documentation\/shengwangchatuikit\/newcontactrequestcontroller\/requestfriendinfo(userid:)","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/NewContactRequestController/fillDatas()":{"title":"fillDatas()","navigatorTitle":[{"kind":"identifier","text":"fillDatas"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/NewContactRequestController\/fillDatas()","url":"\/documentation\/shengwangchatuikit\/newcontactrequestcontroller\/filldatas()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fillDatas"},{"text":"() -> [","kind":"text"},{"text":"NewContactRequest","kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)NewContactRequest"},{"kind":"text","text":"]"}],"type":"topic","role":"symbol","abstract":[]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/NewContactRequestController/UIScrollViewDelegate-Implementations":{"type":"topic","role":"collectionGroup","title":"UIScrollViewDelegate Implementations","kind":"article","abstract":[],"url":"\/documentation\/shengwangchatuikit\/newcontactrequestcontroller\/uiscrollviewdelegate-implementations","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/NewContactRequestController\/UIScrollViewDelegate-Implementations"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UIViewControllerTransitioningDelegate":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIViewControllerTransitioningDelegate","title":"UIKit.UIViewControllerTransitioningDelegate","type":"unresolvable"},"doc://org.cocoapods.ShengwangChatUIKit/SQ":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/NewContactRequestController/createNavigation()":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/NewContactRequestController\/createNavigation()","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"createNavigation","kind":"identifier"},{"kind":"text","text":"() -> "},{"text":"ChatNavigationBar","kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)ChatNavigationBar"}],"type":"topic","title":"createNavigation()","role":"symbol","navigatorTitle":[{"text":"createNavigation","kind":"identifier"}],"abstract":[],"url":"\/documentation\/shengwangchatuikit\/newcontactrequestcontroller\/createnavigation()","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UITableViewDataSource":{"title":"UITableViewDataSource","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UITableViewDataSource"},"doc://org.cocoapods.ShengwangChatUIKit/s8CopyableP":{"title":"Swift.Copyable","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/s8CopyableP"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/NewContactRequestController/navigation":{"abstract":[],"kind":"symbol","url":"\/documentation\/shengwangchatuikit\/newcontactrequestcontroller\/navigation","title":"navigation","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/NewContactRequestController\/navigation","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"navigation","kind":"identifier"},{"kind":"text","text":": "},{"text":"ChatNavigationBar","kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)ChatNavigationBar"}],"type":"topic"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UIUserActivityRestoring":{"title":"UIKit.UIUserActivityRestoring","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIUserActivityRestoring"},"doc://org.cocoapods.ShengwangChatUIKit/objc(cs)UIViewController":{"title":"UIViewController","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(cs)UIViewController"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)NSExtensionRequestHandling":{"title":"Foundation.NSExtensionRequestHandling","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)NSExtensionRequestHandling"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/NewContactRequestController/contactService":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/NewContactRequestController\/contactService","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"contactService"},{"text":": ","kind":"text"},{"text":"ContactServiceImplement","kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)ContactServiceImplement"}],"type":"topic","title":"contactService","role":"symbol","abstract":[],"url":"\/documentation\/shengwangchatuikit\/newcontactrequestcontroller\/contactservice","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UIFocusEnvironment":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIFocusEnvironment","type":"unresolvable","title":"UIKit.UIFocusEnvironment"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/NewContactRequestController/requestList":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/NewContactRequestController\/requestList","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"requestList","kind":"identifier"},{"kind":"text","text":": "},{"text":"UITableView","preciseIdentifier":"c:objc(cs)UITableView","kind":"typeIdentifier"}],"kind":"symbol","url":"\/documentation\/shengwangchatuikit\/newcontactrequestcontroller\/requestlist","title":"requestList","role":"symbol","abstract":[],"type":"topic"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/NewContactRequestController/navigationClick(type:indexPath:)":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/NewContactRequestController\/navigationClick(type:indexPath:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"navigationClick"},{"text":"(","kind":"text"},{"text":"type","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@E@ChatNavigationBarClickEvent","kind":"typeIdentifier","text":"ChatNavigationBarClickEvent"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"indexPath"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation9IndexPathV","kind":"typeIdentifier","text":"IndexPath"},{"kind":"text","text":"?)"}],"type":"topic","title":"navigationClick(type:indexPath:)","role":"symbol","navigatorTitle":[{"text":"navigationClickWithType:indexPath:","kind":"identifier"}],"abstract":[],"url":"\/documentation\/shengwangchatuikit\/newcontactrequestcontroller\/navigationclick(type:indexpath:)","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ThemeSwitchProtocol":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ThemeSwitchProtocol","abstract":[{"type":"text","text":"When the system theme changes, you can use this static method to switch between the light and dark themes of the ease chat UIKit."}],"url":"\/documentation\/shengwangchatuikit\/themeswitchprotocol","type":"topic","kind":"symbol","role":"symbol","title":"ThemeSwitchProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"ThemeSwitchProtocol","kind":"identifier"}],"navigatorTitle":[{"text":"ThemeSwitchProtocol","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/NewContactRequestController/cellForRowAt(indexPath:)":{"abstract":[],"title":"cellForRowAt(indexPath:)","type":"topic","role":"symbol","url":"\/documentation\/shengwangchatuikit\/newcontactrequestcontroller\/cellforrowat(indexpath:)","kind":"symbol","navigatorTitle":[{"text":"cellForRowAtIndexPath:","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/NewContactRequestController\/cellForRowAt(indexPath:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"cellForRowAt","kind":"identifier"},{"kind":"text","text":"("},{"text":"indexPath","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation9IndexPathV","text":"IndexPath","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"UITableViewCell","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITableViewCell"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/NewContactRequestController/agreeFriendRequest(userId:)":{"url":"\/documentation\/shengwangchatuikit\/newcontactrequestcontroller\/agreefriendrequest(userid:)","abstract":[{"text":"Agrees to a friend request from a user.","type":"text"}],"title":"agreeFriendRequest(userId:)","role":"symbol","navigatorTitle":[{"text":"agreeFriendRequestWithUserId:","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/NewContactRequestController\/agreeFriendRequest(userId:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"agreeFriendRequest","kind":"identifier"},{"kind":"text","text":"("},{"text":"userId","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/NewContactRequestController/initWithCoder:":{"url":"\/documentation\/shengwangchatuikit\/newcontactrequestcontroller\/initwithcoder:","type":"topic","kind":"symbol","navigatorTitle":[{"text":"initWithCoder:","kind":"identifier"}],"abstract":[],"role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/NewContactRequestController\/initWithCoder:","title":"initWithCoder:","fragments":[{"kind":"text","text":"- "},{"text":"initWithCoder:","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/NewContactRequestController/refreshProfiles(profiles:unknownInfoMaps:)":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/NewContactRequestController\/refreshProfiles(profiles:unknownInfoMaps:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"refreshProfiles"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"profiles"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(pl)ChatUserProfileProtocol","kind":"typeIdentifier","text":"ChatUserProfileProtocol"},{"kind":"text","text":"], "},{"text":"unknownInfoMaps","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":" : ","kind":"text"},{"text":"IndexPath","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":"])"}],"title":"refreshProfiles(profiles:unknownInfoMaps:)","type":"topic","role":"symbol","navigatorTitle":[{"text":"refreshProfilesWithProfiles:unknownInfoMaps:","kind":"identifier"}],"abstract":[],"url":"\/documentation\/shengwangchatuikit\/newcontactrequestcontroller\/refreshprofiles(profiles:unknowninfomaps:)","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/s8SendableP":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/s8SendableP","type":"unresolvable","title":"Swift.Sendable"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UITraitEnvironment":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UITraitEnvironment","type":"unresolvable","title":"UIKit.UITraitEnvironment"},"doc://org.cocoapods.ShengwangChatUIKit/s7CVarArgP":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UIScrollViewDelegate":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIScrollViewDelegate","type":"unresolvable","title":"UIKit.UIScrollViewDelegate"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UIAppearanceContainer":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIAppearanceContainer","type":"unresolvable","title":"UIKit.UIAppearanceContainer"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/NewContactRequestController/empty":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"empty"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)EmptyStateView","kind":"typeIdentifier","text":"EmptyStateView"}],"title":"empty","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/NewContactRequestController\/empty","url":"\/documentation\/shengwangchatuikit\/newcontactrequestcontroller\/empty","abstract":[],"kind":"symbol","role":"symbol","type":"topic"},"doc://org.cocoapods.ShengwangChatUIKit/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/s28CustomDebugStringConvertibleP"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)NSObject"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/NewContactRequestController/pop()":{"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"pop"},{"text":"()","kind":"text"}],"type":"topic","title":"pop()","role":"symbol","navigatorTitle":[{"text":"pop","kind":"identifier"}],"abstract":[],"url":"\/documentation\/shengwangchatuikit\/newcontactrequestcontroller\/pop()","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/NewContactRequestController\/pop()"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/NewContactRequestController/ThemeSwitchProtocol-Implementations":{"kind":"article","title":"ThemeSwitchProtocol Implementations","type":"topic","url":"\/documentation\/shengwangchatuikit\/newcontactrequestcontroller\/themeswitchprotocol-implementations","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/NewContactRequestController\/ThemeSwitchProtocol-Implementations","role":"collectionGroup","abstract":[]},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIResponderStandardEditActions"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/NewContactRequestController/requestProfiles()":{"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"requestProfiles"},{"kind":"text","text":"()"}],"type":"topic","title":"requestProfiles()","role":"symbol","navigatorTitle":[{"text":"requestProfiles","kind":"identifier"}],"abstract":[],"url":"\/documentation\/shengwangchatuikit\/newcontactrequestcontroller\/requestprofiles()","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/NewContactRequestController\/requestProfiles()"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/NewContactRequestController/UITableViewDataSource-Implementations":{"abstract":[],"role":"collectionGroup","kind":"article","type":"topic","url":"\/documentation\/shengwangchatuikit\/newcontactrequestcontroller\/uitableviewdatasource-implementations","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/NewContactRequestController\/UITableViewDataSource-Implementations","title":"UITableViewDataSource Implementations"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UIStateRestoring":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIStateRestoring","type":"unresolvable","title":"UIKit.UIStateRestoring"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UIContentContainer":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIContentContainer","type":"unresolvable","title":"UIKit.UIContentContainer"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/NewContactRequestController":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/NewContactRequestController","title":"NewContactRequestController","navigatorTitle":[{"text":"NewContactRequestController","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/newcontactrequestcontroller","role":"symbol","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"NewContactRequestController","kind":"identifier"}],"abstract":[]},"doc://org.cocoapods.ShengwangChatUIKit/s23CustomStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"NewContactRequestController"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"NewContactRequestController","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"NewContactRequestController","kind":"identifier"}]},{"path":"\/topicSections","op":"replace","value":[{"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/NewContactRequestController\/agreeFriendRequest(userId:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/NewContactRequestController\/cellForRowAt(indexPath:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/NewContactRequestController\/createNavigation()","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/NewContactRequestController\/fillDatas()","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/NewContactRequestController\/initWithCoder:","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/NewContactRequestController\/initWithNibName:bundle:","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/NewContactRequestController\/navigationClick(type:indexPath:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/NewContactRequestController\/pop()","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/NewContactRequestController\/refreshProfiles(profiles:unknownInfoMaps:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/NewContactRequestController\/requestFriendInfo(userId:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/NewContactRequestController\/requestProfiles()","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/NewContactRequestController\/viewDidLoad()"],"generated":true},{"generated":true,"title":"Default Implementations","anchor":"Default-Implementations","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/NewContactRequestController\/ThemeSwitchProtocol-Implementations","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/NewContactRequestController\/UIScrollViewDelegate-Implementations","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/NewContactRequestController\/UITableViewDataSource-Implementations"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(cs)UIViewController"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"},{"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ThemeSwitchProtocol","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UITableViewDataSource","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UITableViewDelegate"],"kind":"relationships","type":"conformsTo","title":"Conforms To"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NewContactRequestController"},{"kind":"text","text":" : "},{"text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier"}],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1NewContactRequestController~1viewDidLoad()\/title","value":"viewDidLoad","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"viewDidLoad","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1NewContactRequestController~1viewDidLoad()\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1NewContactRequestController~1requestFriendInfo(userId:)\/title","value":"requestFriendInfoWithUserId:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1NewContactRequestController~1requestFriendInfo(userId:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"requestFriendInfoWithUserId:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1NewContactRequestController~1fillDatas()\/title","value":"fillDatas"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1NewContactRequestController~1fillDatas()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"fillDatas","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1NewContactRequestController~1createNavigation()\/title","value":"createNavigation","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"createNavigation"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1NewContactRequestController~1createNavigation()\/fragments"},{"value":"navigationClickWithType:indexPath:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1NewContactRequestController~1navigationClick(type:indexPath:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1NewContactRequestController~1navigationClick(type:indexPath:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"navigationClickWithType:indexPath:"}]},{"value":"ThemeSwitchProtocol","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ThemeSwitchProtocol\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ThemeSwitchProtocol\/fragments","value":[{"kind":"identifier","text":"ThemeSwitchProtocol"}],"op":"replace"},{"op":"replace","value":[{"text":"ThemeSwitchProtocol","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ThemeSwitchProtocol\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1NewContactRequestController~1cellForRowAt(indexPath:)\/title","value":"cellForRowAtIndexPath:"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1NewContactRequestController~1cellForRowAt(indexPath:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"cellForRowAtIndexPath:","kind":"identifier"}],"op":"replace"},{"value":"agreeFriendRequestWithUserId:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1NewContactRequestController~1agreeFriendRequest(userId:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1NewContactRequestController~1agreeFriendRequest(userId:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"agreeFriendRequestWithUserId:"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1NewContactRequestController~1refreshProfiles(profiles:unknownInfoMaps:)\/title","value":"refreshProfilesWithProfiles:unknownInfoMaps:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1NewContactRequestController~1refreshProfiles(profiles:unknownInfoMaps:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"refreshProfilesWithProfiles:unknownInfoMaps:"}]},{"value":"pop","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1NewContactRequestController~1pop()\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1NewContactRequestController~1pop()\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"pop","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1NewContactRequestController~1requestProfiles()\/title","value":"requestProfiles"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"requestProfiles"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1NewContactRequestController~1requestProfiles()\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1NewContactRequestController\/title","value":"NewContactRequestController"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1NewContactRequestController\/fragments","value":[{"text":"NewContactRequestController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1NewContactRequestController\/navigatorTitle","value":[{"kind":"identifier","text":"NewContactRequestController"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}