{"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(cs)UIViewController"],"type":"inheritsFrom","kind":"relationships"},{"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)NSCoding","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)NSExtensionRequestHandling","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)NSObject","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PresentedViewType","doc:\/\/org.cocoapods.ShengwangChatUIKit\/s7CVarArgP","doc:\/\/org.cocoapods.ShengwangChatUIKit\/s8CopyableP","doc:\/\/org.cocoapods.ShengwangChatUIKit\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.ShengwangChatUIKit\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.ShengwangChatUIKit\/SQ","doc:\/\/org.cocoapods.ShengwangChatUIKit\/SH","doc:\/\/org.cocoapods.ShengwangChatUIKit\/s8SendableP","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ThemeSwitchProtocol","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIAppearanceContainer","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIContentContainer","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIFocusEnvironment","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIResponderStandardEditActions","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIStateRestoring","doc:\/\/org.cocoapods.ShengwangChatUIKit\/5UIKit23UITraitChangeObservableP","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UITraitEnvironment","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIUserActivityRestoring","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIViewControllerTransitioningDelegate"],"title":"Conforms To","kind":"relationships","type":"conformsTo"}],"metadata":{"modules":[{"name":"ShengwangChatUIKit"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PageContainersDialogController"}],"roleHeading":"Class","role":"symbol","navigatorTitle":[{"text":"PageContainersDialogController","kind":"identifier"}],"externalID":"c:@M@ShengwangChatUIKit@objc(cs)PageContainersDialogController","symbolKind":"class","title":"PageContainersDialogController"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit"]]},"abstract":[{"text":"A controller that manages a page container which displays a collection of child view controllers in a paged interface.","type":"text"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PageContainersDialogController"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"content":[{"text":"Overview","type":"heading","anchor":"overview","level":2},{"type":"paragraph","inlineContent":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"presentedViewComponent"},{"type":"text","text":" property is used to set the size of the page container. The "},{"type":"codeVoice","code":"pageTitles"},{"type":"text","text":" property is used to set the titles of the pages in the container. The "},{"type":"codeVoice","code":"childControllers"},{"text":" property is used to set the child view controllers to be displayed in the container.","type":"text"}]},{"type":"paragraph","inlineContent":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"container"},{"type":"text","text":" property is a lazy var that returns a "},{"code":"PageContainer","type":"codeVoice"},{"type":"text","text":" instance with the specified frame, view controllers, and page titles. It also sets the corner radius of the container view."}]}],"kind":"content"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PageContainersDialogController"},"topicSections":[{"title":"Initializers","anchor":"Initializers","generated":true,"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PageContainersDialogController\/init(pageTitles:childControllers:constraintsSize:)"]},{"generated":true,"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PageContainersDialogController\/presentedViewComponent","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PageContainersDialogController\/willRemoveClosure"],"anchor":"Instance-Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PageContainersDialogController\/viewDidLoad()","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PageContainersDialogController\/viewWillDisappear(_:)"],"generated":true,"anchor":"Instance-Methods"},{"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PageContainersDialogController\/ThemeSwitchProtocol-Implementations"],"title":"Default Implementations","anchor":"Default-Implementations","generated":true}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/pagecontainersdialogcontroller"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/pagecontainersdialogcontroller"]}],"kind":"symbol","references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ThemeSwitchProtocol":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ThemeSwitchProtocol","abstract":[{"type":"text","text":"When the system theme changes, you can use this static method to switch between the light and dark themes of the ease chat UIKit."}],"url":"\/documentation\/shengwangchatuikit\/themeswitchprotocol","type":"topic","kind":"symbol","role":"symbol","title":"ThemeSwitchProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"ThemeSwitchProtocol","kind":"identifier"}],"navigatorTitle":[{"text":"ThemeSwitchProtocol","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/SH"},"doc://org.cocoapods.ShengwangChatUIKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/SQ"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UITraitEnvironment"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/PageContainersDialogController":{"abstract":[{"type":"text","text":"A controller that manages a page container which displays a collection of child view controllers in a paged interface."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PageContainersDialogController","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"PageContainersDialogController","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/shengwangchatuikit\/pagecontainersdialogcontroller","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PageContainersDialogController","title":"PageContainersDialogController"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)NSCoding":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)NSCoding","title":"Foundation.NSCoding"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIUserActivityRestoring","title":"UIKit.UIUserActivityRestoring"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/PageContainersDialogController/viewDidLoad()":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PageContainersDialogController\/viewDidLoad()","abstract":[],"type":"topic","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"viewDidLoad","kind":"identifier"},{"text":"()","kind":"text"}],"navigatorTitle":[{"text":"viewDidLoad","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/pagecontainersdialogcontroller\/viewdidload()","title":"viewDidLoad()","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/PageContainersDialogController/init(pageTitles:childControllers:constraintsSize:)":{"abstract":[{"type":"text","text":"Initializes a PageContainersDialogController with the given page titles, child view controllers, and optional constraints size."}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"pageTitles","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"childControllers"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController"},{"kind":"text","text":"], "},{"text":"constraintsSize","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"},{"text":")","kind":"text"}],"role":"symbol","navigatorTitle":[{"text":"initWithPageTitles:childControllers:constraintsSize:","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/shengwangchatuikit\/pagecontainersdialogcontroller\/init(pagetitles:childcontrollers:constraintssize:)","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PageContainersDialogController\/init(pageTitles:childControllers:constraintsSize:)","title":"init(pageTitles:childControllers:constraintsSize:)"},"doc://org.cocoapods.ShengwangChatUIKit/s23CustomStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://org.cocoapods.ShengwangChatUIKit/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UIActivityItemsConfigurationProviding":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIActivityItemsConfigurationProviding","title":"UIKit.UIActivityItemsConfigurationProviding","type":"unresolvable"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)NSObject":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/PresentedViewType":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PresentedViewType","abstract":[],"type":"topic","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PresentedViewType"}],"navigatorTitle":[{"kind":"identifier","text":"PresentedViewType"}],"url":"\/documentation\/shengwangchatuikit\/presentedviewtype","title":"PresentedViewType","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UIResponderStandardEditActions":{"title":"UIKit.UIResponderStandardEditActions","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIResponderStandardEditActions"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/PageContainersDialogController/willRemoveClosure":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PageContainersDialogController\/willRemoveClosure","abstract":[],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"willRemoveClosure","kind":"identifier"},{"text":": (() -> ())?","kind":"text"}],"url":"\/documentation\/shengwangchatuikit\/pagecontainersdialogcontroller\/willremoveclosure","title":"willRemoveClosure","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UIContentContainer":{"type":"unresolvable","title":"UIKit.UIContentContainer","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIContentContainer"},"doc://org.cocoapods.ShengwangChatUIKit/s7CVarArgP":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/PageContainersDialogController/ThemeSwitchProtocol-Implementations":{"abstract":[],"role":"collectionGroup","kind":"article","type":"topic","url":"\/documentation\/shengwangchatuikit\/pagecontainersdialogcontroller\/themeswitchprotocol-implementations","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PageContainersDialogController\/ThemeSwitchProtocol-Implementations","title":"ThemeSwitchProtocol Implementations"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)NSExtensionRequestHandling":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)NSExtensionRequestHandling","title":"Foundation.NSExtensionRequestHandling","type":"unresolvable"},"doc://org.cocoapods.ShengwangChatUIKit/5UIKit23UITraitChangeObservableP":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/5UIKit23UITraitChangeObservableP","title":"UIKit.UITraitChangeObservable","type":"unresolvable"},"doc://org.cocoapods.ShengwangChatUIKit/s8CopyableP":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/s8CopyableP","title":"Swift.Copyable","type":"unresolvable"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UIViewControllerTransitioningDelegate":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIViewControllerTransitioningDelegate","title":"UIKit.UIViewControllerTransitioningDelegate","type":"unresolvable"},"doc://org.cocoapods.ShengwangChatUIKit/objc(cs)UIViewController":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(cs)UIViewController","title":"UIViewController","type":"unresolvable"},"doc://org.cocoapods.ShengwangChatUIKit/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/s8SendableP"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIPasteConfigurationSupporting"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/PageContainersDialogController/presentedViewComponent":{"abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"presentedViewComponent"},{"kind":"text","text":": "},{"text":"PresentedViewComponent","preciseIdentifier":"s:18ShengwangChatUIKit22PresentedViewComponentV","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"role":"symbol","kind":"symbol","type":"topic","url":"\/documentation\/shengwangchatuikit\/pagecontainersdialogcontroller\/presentedviewcomponent","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PageContainersDialogController\/presentedViewComponent","title":"presentedViewComponent"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/PageContainersDialogController/viewWillDisappear(_:)":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PageContainersDialogController\/viewWillDisappear(_:)","abstract":[],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"viewWillDisappear"},{"kind":"text","text":"("},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"viewWillDisappear:"}],"url":"\/documentation\/shengwangchatuikit\/pagecontainersdialogcontroller\/viewwilldisappear(_:)","title":"viewWillDisappear(_:)","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UIStateRestoring":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIStateRestoring","title":"UIKit.UIStateRestoring"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UIAppearanceContainer":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIAppearanceContainer","title":"UIKit.UIAppearanceContainer"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UIFocusEnvironment":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIFocusEnvironment","title":"UIKit.UIFocusEnvironment"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"PageContainersDialogController","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"value":[{"text":"PageContainersDialogController","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"replace","value":[{"text":"PageContainersDialogController","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","value":[{"generated":true,"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PageContainersDialogController\/init(pageTitles:childControllers:constraintsSize:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PageContainersDialogController\/viewDidLoad()","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PageContainersDialogController\/viewWillDisappear(_:)"]},{"title":"Default Implementations","anchor":"Default-Implementations","generated":true,"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PageContainersDialogController\/ThemeSwitchProtocol-Implementations"]}],"op":"replace"},{"op":"replace","path":"\/relationshipsSections","value":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(cs)UIViewController"]},{"kind":"relationships","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ThemeSwitchProtocol"],"title":"Conforms To","type":"conformsTo"}]},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PageContainersDialogController","kind":"identifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ThemeSwitchProtocol\/title","value":"ThemeSwitchProtocol","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ThemeSwitchProtocol\/fragments","op":"replace","value":[{"kind":"identifier","text":"ThemeSwitchProtocol"}]},{"value":[{"text":"ThemeSwitchProtocol","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ThemeSwitchProtocol\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PageContainersDialogController\/title","value":"PageContainersDialogController"},{"value":[{"kind":"identifier","text":"PageContainersDialogController"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PageContainersDialogController\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PageContainersDialogController\/navigatorTitle","value":[{"text":"PageContainersDialogController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PageContainersDialogController~1viewDidLoad()\/title","value":"viewDidLoad"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"viewDidLoad"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PageContainersDialogController~1viewDidLoad()\/fragments"},{"value":"initWithPageTitles:childControllers:constraintsSize:","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PageContainersDialogController~1init(pageTitles:childControllers:constraintsSize:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PageContainersDialogController~1init(pageTitles:childControllers:constraintsSize:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithPageTitles:childControllers:constraintsSize:"}]},{"op":"replace","value":"viewWillDisappear:","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PageContainersDialogController~1viewWillDisappear(_:)\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"viewWillDisappear:"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PageContainersDialogController~1viewWillDisappear(_:)\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}