{"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"@","kind":"attribute"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PinnedMessageCell","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PinnedMessageCell"},"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(cs)UITableViewCell"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"},{"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)NSCoding","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)NSObject","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)CALayerDelegate","doc:\/\/org.cocoapods.ShengwangChatUIKit\/s7CVarArgP","doc:\/\/org.cocoapods.ShengwangChatUIKit\/s8CopyableP","doc:\/\/org.cocoapods.ShengwangChatUIKit\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.ShengwangChatUIKit\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.ShengwangChatUIKit\/SQ","doc:\/\/org.cocoapods.ShengwangChatUIKit\/SH","doc:\/\/org.cocoapods.ShengwangChatUIKit\/s8SendableP","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ThemeSwitchProtocol","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIAccessibilityIdentification","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIAppearance","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIAppearanceContainer","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UICoordinateSpace","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIDynamicItem","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIFocusEnvironment","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIFocusItem","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIFocusItemContainer","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIGestureRecognizerDelegate","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UILargeContentViewerItem","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIResponderStandardEditActions","doc:\/\/org.cocoapods.ShengwangChatUIKit\/5UIKit23UITraitChangeObservableP","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UITraitEnvironment","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit"]]},"metadata":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PinnedMessageCell"}],"roleHeading":"Class","title":"PinnedMessageCell","modules":[{"name":"ShengwangChatUIKit"}],"symbolKind":"class","navigatorTitle":[{"text":"PinnedMessageCell","kind":"identifier"}],"externalID":"c:@M@ShengwangChatUIKit@objc(cs)PinnedMessageCell"},"schemaVersion":{"minor":3,"patch":0,"major":0},"topicSections":[{"generated":true,"anchor":"Initializers","title":"Initializers","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PinnedMessageCell\/init(coder:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PinnedMessageCell\/init(style:reuseIdentifier:)"]},{"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PinnedMessageCell\/confirmRemove","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PinnedMessageCell\/confirmRemoveWidth","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PinnedMessageCell\/container","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PinnedMessageCell\/entity","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PinnedMessageCell\/pinContent","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PinnedMessageCell\/pinTime","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PinnedMessageCell\/pinTitle","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PinnedMessageCell\/remove","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PinnedMessageCell\/removeActionHandler","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PinnedMessageCell\/removeWidth"],"generated":true},{"title":"Instance Methods","generated":true,"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PinnedMessageCell\/confirmRemoveAction()","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PinnedMessageCell\/layoutSubviews()","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PinnedMessageCell\/refresh(entity:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PinnedMessageCell\/removeAction()"],"anchor":"Instance-Methods"},{"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PinnedMessageCell\/ThemeSwitchProtocol-Implementations"],"title":"Default Implementations","generated":true,"anchor":"Default-Implementations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/pinnedmessagecell"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/pinnedmessagecell"]}],"sections":[],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/PinnedMessageCell/remove":{"title":"remove","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PinnedMessageCell\/remove","type":"topic","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"remove"},{"kind":"text","text":": "},{"text":"UIButton","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIButton"}],"url":"\/documentation\/shengwangchatuikit\/pinnedmessagecell\/remove"},"doc://org.cocoapods.ShengwangChatUIKit/objc(cs)UITableViewCell":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(cs)UITableViewCell","title":"UITableViewCell","type":"unresolvable"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UIUserActivityRestoring":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIUserActivityRestoring","title":"UIKit.UIUserActivityRestoring","type":"unresolvable"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/PinnedMessageCell/removeWidth":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PinnedMessageCell\/removeWidth","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeWidth"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"url":"\/documentation\/shengwangchatuikit\/pinnedmessagecell\/removewidth","title":"removeWidth","kind":"symbol","type":"topic","role":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIPasteConfigurationSupporting","title":"UIKit.UIPasteConfigurationSupporting"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/PinnedMessageCell/container":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PinnedMessageCell\/container","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"container"},{"kind":"text","text":": "},{"text":"UIView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView"}],"url":"\/documentation\/shengwangchatuikit\/pinnedmessagecell\/container","title":"container","kind":"symbol","type":"topic","role":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/PinnedMessageCell/pinTitle":{"title":"pinTitle","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PinnedMessageCell\/pinTitle","type":"topic","role":"symbol","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"pinTitle"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"}],"url":"\/documentation\/shengwangchatuikit\/pinnedmessagecell\/pintitle"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UIFocusItem":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIFocusItem","title":"UIKit.UIFocusItem"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/PinnedMessageCell/removeActionHandler":{"title":"removeActionHandler","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PinnedMessageCell\/removeActionHandler","type":"topic","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"removeActionHandler"},{"kind":"text","text":": (("},{"text":"PinnedMessageEntity","kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)PinnedMessageEntity"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"kind":"text","text":")?"}],"url":"\/documentation\/shengwangchatuikit\/pinnedmessagecell\/removeactionhandler"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIActivityItemsConfigurationProviding","title":"UIKit.UIActivityItemsConfigurationProviding"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/PinnedMessageCell/confirmRemove":{"title":"confirmRemove","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PinnedMessageCell\/confirmRemove","type":"topic","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"confirmRemove"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIButton","text":"UIButton"}],"url":"\/documentation\/shengwangchatuikit\/pinnedmessagecell\/confirmremove"},"doc://org.cocoapods.ShengwangChatUIKit/s8CopyableP":{"title":"Swift.Copyable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/s8CopyableP","type":"unresolvable"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)NSObject","type":"unresolvable"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/PinnedMessageCell/confirmRemoveAction()":{"navigatorTitle":[{"kind":"identifier","text":"confirmRemoveAction"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PinnedMessageCell\/confirmRemoveAction()","abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"confirmRemoveAction"},{"text":"()","kind":"text"}],"url":"\/documentation\/shengwangchatuikit\/pinnedmessagecell\/confirmremoveaction()","title":"confirmRemoveAction()","kind":"symbol","type":"topic","role":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UIGestureRecognizerDelegate":{"title":"UIKit.UIGestureRecognizerDelegate","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIGestureRecognizerDelegate","type":"unresolvable"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UICoordinateSpace":{"title":"UIKit.UICoordinateSpace","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UICoordinateSpace","type":"unresolvable"},"doc://org.cocoapods.ShengwangChatUIKit/s8SendableP":{"title":"Swift.Sendable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/s8SendableP","type":"unresolvable"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/PinnedMessageCell/init(coder:)":{"navigatorTitle":[{"text":"initWithCoder:","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PinnedMessageCell\/init(coder:)","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"text":"coder","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder"},{"kind":"text","text":")"}],"url":"\/documentation\/shengwangchatuikit\/pinnedmessagecell\/init(coder:)","title":"init(coder:)","kind":"symbol","type":"topic","role":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/SQ":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)CALayerDelegate":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)CALayerDelegate","type":"unresolvable","title":"QuartzCore.CALayerDelegate"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/PinnedMessageCell/refresh(entity:)":{"title":"refresh(entity:)","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PinnedMessageCell\/refresh(entity:)","type":"topic","role":"symbol","abstract":[],"navigatorTitle":[{"text":"refreshWithEntity:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"refresh"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"entity"},{"text":": ","kind":"text"},{"text":"PinnedMessageEntity","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)PinnedMessageEntity","kind":"typeIdentifier"},{"kind":"text","text":")"}],"url":"\/documentation\/shengwangchatuikit\/pinnedmessagecell\/refresh(entity:)"},"doc://org.cocoapods.ShengwangChatUIKit/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/s7CVarArgP","title":"Swift.CVarArg"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIResponderStandardEditActions","title":"UIKit.UIResponderStandardEditActions"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UILargeContentViewerItem":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UILargeContentViewerItem","title":"UIKit.UILargeContentViewerItem"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)NSCoding":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)NSCoding","title":"Foundation.NSCoding"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/PinnedMessageCell/pinTime":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PinnedMessageCell\/pinTime","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"pinTime","kind":"identifier"},{"kind":"text","text":": "},{"text":"UILabel","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UILabel"}],"url":"\/documentation\/shengwangchatuikit\/pinnedmessagecell\/pintime","title":"pinTime","kind":"symbol","type":"topic","role":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/PinnedMessageCell/ThemeSwitchProtocol-Implementations":{"title":"ThemeSwitchProtocol Implementations","kind":"article","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PinnedMessageCell\/ThemeSwitchProtocol-Implementations","type":"topic","role":"collectionGroup","abstract":[],"url":"\/documentation\/shengwangchatuikit\/pinnedmessagecell\/themeswitchprotocol-implementations"},"doc://org.cocoapods.ShengwangChatUIKit/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/PinnedMessageCell/layoutSubviews()":{"navigatorTitle":[{"text":"layoutSubviews","kind":"identifier"}],"abstract":[],"kind":"symbol","url":"\/documentation\/shengwangchatuikit\/pinnedmessagecell\/layoutsubviews()","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"layoutSubviews","kind":"identifier"},{"text":"()","kind":"text"}],"title":"layoutSubviews()","role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PinnedMessageCell\/layoutSubviews()"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/PinnedMessageCell/init(style:reuseIdentifier:)":{"title":"init(style:reuseIdentifier:)","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PinnedMessageCell\/init(style:reuseIdentifier:)","type":"topic","role":"symbol","abstract":[],"navigatorTitle":[{"text":"initWithStyle:reuseIdentifier:","kind":"identifier"}],"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"style","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UITableViewCell","preciseIdentifier":"c:objc(cs)UITableViewCell"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"CellStyle","preciseIdentifier":"c:@E@UITableViewCellStyle"},{"kind":"text","text":", "},{"text":"reuseIdentifier","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"url":"\/documentation\/shengwangchatuikit\/pinnedmessagecell\/init(style:reuseidentifier:)"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UIAppearance":{"title":"UIKit.UIAppearance","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIAppearance"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UIFocusEnvironment":{"title":"UIKit.UIFocusEnvironment","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIFocusEnvironment"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UITraitEnvironment":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UITraitEnvironment","title":"UIKit.UITraitEnvironment","type":"unresolvable"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UIDynamicItem":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIDynamicItem","title":"UIKit.UIDynamicItem","type":"unresolvable"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/PinnedMessageCell/entity":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PinnedMessageCell\/entity","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"entity","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)PinnedMessageEntity","text":"PinnedMessageEntity"},{"kind":"text","text":"?"}],"url":"\/documentation\/shengwangchatuikit\/pinnedmessagecell\/entity","title":"entity","kind":"symbol","type":"topic","role":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UIFocusItemContainer":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIFocusItemContainer","title":"UIKit.UIFocusItemContainer"},"doc://org.cocoapods.ShengwangChatUIKit/SH":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/SH","title":"Swift.Hashable"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UIPopoverPresentationControllerSourceItem":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIPopoverPresentationControllerSourceItem","title":"UIKit.UIPopoverPresentationControllerSourceItem"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ThemeSwitchProtocol":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ThemeSwitchProtocol","abstract":[{"type":"text","text":"When the system theme changes, you can use this static method to switch between the light and dark themes of the ease chat UIKit."}],"url":"\/documentation\/shengwangchatuikit\/themeswitchprotocol","type":"topic","kind":"symbol","role":"symbol","title":"ThemeSwitchProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"ThemeSwitchProtocol","kind":"identifier"}],"navigatorTitle":[{"text":"ThemeSwitchProtocol","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/5UIKit23UITraitChangeObservableP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/5UIKit23UITraitChangeObservableP","title":"UIKit.UITraitChangeObservable"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UIAppearanceContainer":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIAppearanceContainer","title":"UIKit.UIAppearanceContainer"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UIAccessibilityIdentification":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIAccessibilityIdentification","title":"UIKit.UIAccessibilityIdentification"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/PinnedMessageCell/pinContent":{"title":"pinContent","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PinnedMessageCell\/pinContent","type":"topic","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"pinContent","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UILabel","text":"UILabel","kind":"typeIdentifier"}],"url":"\/documentation\/shengwangchatuikit\/pinnedmessagecell\/pincontent"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/PinnedMessageCell/removeAction()":{"navigatorTitle":[{"kind":"identifier","text":"removeAction"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PinnedMessageCell\/removeAction()","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"removeAction","kind":"identifier"},{"kind":"text","text":"()"}],"url":"\/documentation\/shengwangchatuikit\/pinnedmessagecell\/removeaction()","title":"removeAction()","kind":"symbol","type":"topic","role":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/PinnedMessageCell":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PinnedMessageCell","role":"symbol","url":"\/documentation\/shengwangchatuikit\/pinnedmessagecell","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PinnedMessageCell"}],"title":"PinnedMessageCell","type":"topic","navigatorTitle":[{"text":"PinnedMessageCell","kind":"identifier"}],"kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/PinnedMessageCell/confirmRemoveWidth":{"title":"confirmRemoveWidth","type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PinnedMessageCell\/confirmRemoveWidth","kind":"symbol","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"confirmRemoveWidth","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"url":"\/documentation\/shengwangchatuikit\/pinnedmessagecell\/confirmremovewidth"},"doc://org.cocoapods.ShengwangChatUIKit/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"PinnedMessageCell"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"PinnedMessageCell","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"PinnedMessageCell"}],"op":"replace"},{"op":"replace","value":[{"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PinnedMessageCell\/confirmRemoveAction()","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PinnedMessageCell\/init(coder:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PinnedMessageCell\/init(style:reuseIdentifier:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PinnedMessageCell\/layoutSubviews()","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PinnedMessageCell\/refresh(entity:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PinnedMessageCell\/removeAction()"],"generated":true,"anchor":"Instance-Methods","title":"Instance Methods"},{"generated":true,"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PinnedMessageCell\/ThemeSwitchProtocol-Implementations"],"anchor":"Default-Implementations","title":"Default Implementations"}],"path":"\/topicSections"},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(cs)UITableViewCell"],"title":"Inherits From","type":"inheritsFrom"},{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ThemeSwitchProtocol"],"type":"conformsTo"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"PinnedMessageCell"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UITableViewCell","text":"UITableViewCell","kind":"typeIdentifier"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PinnedMessageCell~1confirmRemoveAction()\/title","value":"confirmRemoveAction"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"confirmRemoveAction"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PinnedMessageCell~1confirmRemoveAction()\/fragments"},{"value":"initWithCoder:","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PinnedMessageCell~1init(coder:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PinnedMessageCell~1init(coder:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithCoder:","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"refreshWithEntity:","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PinnedMessageCell~1refresh(entity:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PinnedMessageCell~1refresh(entity:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"refreshWithEntity:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PinnedMessageCell~1layoutSubviews()\/title","value":"layoutSubviews"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PinnedMessageCell~1layoutSubviews()\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"layoutSubviews"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PinnedMessageCell~1init(style:reuseIdentifier:)\/title","op":"replace","value":"initWithStyle:reuseIdentifier:"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PinnedMessageCell~1init(style:reuseIdentifier:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithStyle:reuseIdentifier:"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ThemeSwitchProtocol\/title","value":"ThemeSwitchProtocol"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ThemeSwitchProtocol\/fragments","op":"replace","value":[{"text":"ThemeSwitchProtocol","kind":"identifier"}]},{"value":[{"text":"ThemeSwitchProtocol","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ThemeSwitchProtocol\/navigatorTitle","op":"replace"},{"value":"removeAction","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PinnedMessageCell~1removeAction()\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PinnedMessageCell~1removeAction()\/fragments","value":[{"kind":"text","text":"- "},{"text":"removeAction","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PinnedMessageCell\/title","op":"replace","value":"PinnedMessageCell"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PinnedMessageCell\/fragments","value":[{"text":"PinnedMessageCell","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PinnedMessageCell\/navigatorTitle","value":[{"text":"PinnedMessageCell","kind":"identifier"}],"op":"replace"}]}]}