{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"A custom presentation controller that manages the transition animations and layout of the presented view controller’s view."}],"relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(cs)UIPresentationController"],"type":"inheritsFrom"},{"kind":"relationships","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)NSObject","doc:\/\/org.cocoapods.ShengwangChatUIKit\/s7CVarArgP","doc:\/\/org.cocoapods.ShengwangChatUIKit\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.ShengwangChatUIKit\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.ShengwangChatUIKit\/SQ","doc:\/\/org.cocoapods.ShengwangChatUIKit\/SH","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIAppearanceContainer","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIContentContainer","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIFocusEnvironment","doc:\/\/org.cocoapods.ShengwangChatUIKit\/5UIKit23UITraitChangeObservableP","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UITraitEnvironment"],"type":"conformsTo","title":"Conforms To"}],"variants":[{"paths":["\/documentation\/shengwangchatuikit\/presentationcontroller"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/shengwangchatuikit\/presentationcontroller"],"traits":[{"interfaceLanguage":"occ"}]}],"topicSections":[{"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PresentationController\/init(presentedViewController:presenting:)"],"generated":true,"title":"Initializers","anchor":"Initializers"},{"anchor":"Instance-Properties","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PresentationController\/frameOfPresentedViewInContainerView"],"generated":true,"title":"Instance Properties"},{"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PresentationController\/dismissalTransitionDidEnd(_:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PresentationController\/dismissalTransitionWillBegin()","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PresentationController\/presentationTransitionDidEnd(_:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PresentationController\/presentationTransitionWillBegin()"],"anchor":"Instance-Methods","generated":true,"title":"Instance Methods"}],"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PresentationController"}]}],"kind":"declarations"},{"kind":"content","content":[{"type":"heading","text":"Overview","anchor":"overview","level":2},{"type":"aside","name":"Note","style":"note","content":[{"inlineContent":[{"text":"This class is a subclass of ","type":"text"},{"type":"codeVoice","code":"UIPresentationController"},{"type":"text","text":"."}],"type":"paragraph"}]},{"type":"aside","style":"note","content":[{"type":"paragraph","inlineContent":[{"text":"FILEPATH","type":"text"}]}],"name":"Author"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"1.0"}]}],"name":"Version","style":"note","type":"aside"}]}],"metadata":{"externalID":"c:@M@ShengwangChatUIKit@objc(cs)PresentationController","modules":[{"name":"ShengwangChatUIKit"}],"title":"PresentationController","symbolKind":"class","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PresentationController"}],"navigatorTitle":[{"kind":"identifier","text":"PresentationController"}],"roleHeading":"Class","role":"symbol"},"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PresentationController","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UIAppearanceContainer":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIAppearanceContainer","title":"UIKit.UIAppearanceContainer"},"doc://org.cocoapods.ShengwangChatUIKit/SH":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/SH","title":"Swift.Hashable"},"doc://org.cocoapods.ShengwangChatUIKit/objc(cs)UIPresentationController":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(cs)UIPresentationController","title":"UIPresentationController"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/PresentationController/presentationTransitionDidEnd(_:)":{"url":"\/documentation\/shengwangchatuikit\/presentationcontroller\/presentationtransitiondidend(_:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"presentationTransitionDidEnd"},{"text":"(","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"presentationTransitionDidEnd(_:)","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PresentationController\/presentationTransitionDidEnd(_:)","abstract":[{"type":"text","text":"已经弹出视图"}],"kind":"symbol","navigatorTitle":[{"text":"presentationTransitionDidEnd:","kind":"identifier"}],"role":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/PresentationController/dismissalTransitionWillBegin()":{"url":"\/documentation\/shengwangchatuikit\/presentationcontroller\/dismissaltransitionwillbegin()","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dismissalTransitionWillBegin","kind":"identifier"},{"text":"()","kind":"text"}],"title":"dismissalTransitionWillBegin()","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PresentationController\/dismissalTransitionWillBegin()","abstract":[],"kind":"symbol","navigatorTitle":[{"text":"dismissalTransitionWillBegin","kind":"identifier"}],"role":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/PresentationController":{"url":"\/documentation\/shengwangchatuikit\/presentationcontroller","kind":"symbol","title":"PresentationController","type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PresentationController","role":"symbol","abstract":[{"text":"A custom presentation controller that manages the transition animations and layout of the presented view controller’s view.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PresentationController","kind":"identifier"}],"navigatorTitle":[{"text":"PresentationController","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/SQ":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/SQ","title":"Swift.Equatable"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/PresentationController/dismissalTransitionDidEnd(_:)":{"url":"\/documentation\/shengwangchatuikit\/presentationcontroller\/dismissaltransitiondidend(_:)","kind":"symbol","title":"dismissalTransitionDidEnd(_:)","type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PresentationController\/dismissalTransitionDidEnd(_:)","role":"symbol","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dismissalTransitionDidEnd","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"dismissalTransitionDidEnd:","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UIFocusEnvironment":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIFocusEnvironment","title":"UIKit.UIFocusEnvironment"},"doc://org.cocoapods.ShengwangChatUIKit/5UIKit23UITraitChangeObservableP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/5UIKit23UITraitChangeObservableP","title":"UIKit.UITraitChangeObservable"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/PresentationController/frameOfPresentedViewInContainerView":{"url":"\/documentation\/shengwangchatuikit\/presentationcontroller\/frameofpresentedviewincontainerview","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"frameOfPresentedViewInContainerView"},{"text":": ","kind":"text"},{"text":"CGRect","preciseIdentifier":"c:@S@CGRect","kind":"typeIdentifier"}],"title":"frameOfPresentedViewInContainerView","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PresentationController\/frameOfPresentedViewInContainerView","abstract":[],"kind":"symbol","navigatorTitle":[{"text":"frameOfPresentedViewInContainerView","kind":"identifier"}],"role":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UIContentContainer":{"title":"UIKit.UIContentContainer","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIContentContainer","type":"unresolvable"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/PresentationController/presentationTransitionWillBegin()":{"url":"\/documentation\/shengwangchatuikit\/presentationcontroller\/presentationtransitionwillbegin()","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"presentationTransitionWillBegin","kind":"identifier"},{"text":"()","kind":"text"}],"title":"presentationTransitionWillBegin()","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PresentationController\/presentationTransitionWillBegin()","abstract":[{"text":"将要弹出时添加背景按钮","type":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"presentationTransitionWillBegin"}],"role":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UITraitEnvironment":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UITraitEnvironment","title":"UIKit.UITraitEnvironment"},"doc://org.cocoapods.ShengwangChatUIKit/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/s7CVarArgP","title":"Swift.CVarArg"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/PresentationController/init(presentedViewController:presenting:)":{"url":"\/documentation\/shengwangchatuikit\/presentationcontroller\/init(presentedviewcontroller:presenting:)","kind":"symbol","title":"init(presentedViewController:presenting:)","type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PresentationController\/init(presentedViewController:presenting:)","role":"symbol","abstract":[],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"presentedViewController","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"presenting","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"},{"text":"?)","kind":"text"}],"navigatorTitle":[{"text":"initWithPresentedViewController:presentingViewController:","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"PresentationController"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"PresentationController","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"PresentationController"}],"op":"replace"},{"path":"\/topicSections","op":"replace","value":[{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PresentationController\/frameOfPresentedViewInContainerView"],"anchor":"Instance-Properties","generated":true},{"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PresentationController\/dismissalTransitionDidEnd(_:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PresentationController\/dismissalTransitionWillBegin()","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PresentationController\/init(presentedViewController:presenting:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PresentationController\/presentationTransitionDidEnd(_:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PresentationController\/presentationTransitionWillBegin()"],"generated":true,"title":"Instance Methods","anchor":"Instance-Methods"}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(cs)UIPresentationController"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PresentationController"},{"text":" : ","kind":"text"},{"text":"UIPresentationController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIPresentationController"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PresentationController~1presentationTransitionDidEnd(_:)\/title","value":"presentationTransitionDidEnd:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"presentationTransitionDidEnd:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PresentationController~1presentationTransitionDidEnd(_:)\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PresentationController~1dismissalTransitionWillBegin()\/title","op":"replace","value":"dismissalTransitionWillBegin"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"dismissalTransitionWillBegin","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PresentationController~1dismissalTransitionWillBegin()\/fragments"},{"op":"replace","value":"PresentationController","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PresentationController\/title"},{"value":[{"text":"PresentationController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PresentationController\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PresentationController\/navigatorTitle","value":[{"text":"PresentationController","kind":"identifier"}]},{"value":"dismissalTransitionDidEnd:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PresentationController~1dismissalTransitionDidEnd(_:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PresentationController~1dismissalTransitionDidEnd(_:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"dismissalTransitionDidEnd:"}]},{"value":"frameOfPresentedViewInContainerView","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PresentationController~1frameOfPresentedViewInContainerView\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PresentationController~1frameOfPresentedViewInContainerView\/fragments","value":[{"text":"frameOfPresentedViewInContainerView","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PresentationController~1presentationTransitionWillBegin()\/title","value":"presentationTransitionWillBegin"},{"value":[{"kind":"text","text":"- "},{"text":"presentationTransitionWillBegin","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PresentationController~1presentationTransitionWillBegin()\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PresentationController~1init(presentedViewController:presenting:)\/title","value":"initWithPresentedViewController:presentingViewController:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithPresentedViewController:presentingViewController:"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PresentationController~1init(presentedViewController:presenting:)\/fragments"}]}]}