{"kind":"symbol","metadata":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PresentationAnimation"}],"externalID":"c:@M@ShengwangChatUIKit@objc(cs)PresentationAnimation","modules":[{"name":"ShengwangChatUIKit"}],"roleHeading":"Class","role":"symbol","title":"PresentationAnimation","symbolKind":"class","navigatorTitle":[{"kind":"identifier","text":"PresentationAnimation"}]},"topicSections":[{"generated":true,"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PresentationAnimation\/init(options:origin:)"],"anchor":"Initializers","title":"Initializers"},{"generated":true,"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PresentationAnimation\/options","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PresentationAnimation\/origin"],"anchor":"Instance-Properties","title":"Instance Properties"},{"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PresentationAnimation\/afterAnimation(animationContext:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PresentationAnimation\/beforeAnimation(animationContext:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PresentationAnimation\/performAnimation(animationContext:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PresentationAnimation\/transformInitialFrame(containerFrame:finalFrame:)"],"generated":true,"title":"Instance Methods","anchor":"Instance-Methods"},{"generated":true,"anchor":"Default-Implementations","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PresentationAnimation\/UIViewControllerAnimatedTransitioning-Implementations"],"title":"Default Implementations"}],"relationshipsSections":[{"type":"inheritsFrom","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships"},{"type":"inheritedBy","title":"Inherited By","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/CrossDissolveAnimation","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/CrossZoomAnimation","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/FlipHorizontalAnimation"]},{"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)NSObject","doc:\/\/org.cocoapods.ShengwangChatUIKit\/s7CVarArgP","doc:\/\/org.cocoapods.ShengwangChatUIKit\/s8CopyableP","doc:\/\/org.cocoapods.ShengwangChatUIKit\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.ShengwangChatUIKit\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.ShengwangChatUIKit\/SQ","doc:\/\/org.cocoapods.ShengwangChatUIKit\/SH","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIViewControllerAnimatedTransitioning"],"kind":"relationships","type":"conformsTo","title":"Conforms To"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PresentationAnimation","kind":"identifier"}]}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit"]]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PresentationAnimation"},"variants":[{"paths":["\/documentation\/shengwangchatuikit\/presentationanimation"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/presentationanimation"]}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/SQ":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/CrossDissolveAnimation":{"type":"topic","abstract":[],"navigatorTitle":[{"text":"CrossDissolveAnimation","kind":"identifier"}],"kind":"symbol","title":"CrossDissolveAnimation","url":"\/documentation\/shengwangchatuikit\/crossdissolveanimation","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CrossDissolveAnimation"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/CrossDissolveAnimation","role":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/PresentationAnimation/options":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"options","kind":"identifier"},{"kind":"text","text":": "},{"text":"AnimationOptions","preciseIdentifier":"s:18ShengwangChatUIKit16AnimationOptionsO","kind":"typeIdentifier"}],"url":"\/documentation\/shengwangchatuikit\/presentationanimation\/options","title":"options","type":"topic","kind":"symbol","abstract":[],"role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PresentationAnimation\/options"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UIViewControllerAnimatedTransitioning":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIViewControllerAnimatedTransitioning","title":"UIViewControllerAnimatedTransitioning","type":"unresolvable"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/PresentationAnimation/transformInitialFrame(containerFrame:finalFrame:)":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PresentationAnimation\/transformInitialFrame(containerFrame:finalFrame:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"transformInitialFrame","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"containerFrame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect","text":"CGRect"},{"kind":"text","text":", "},{"text":"finalFrame","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect","text":"CGRect"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@S@CGRect","text":"CGRect","kind":"typeIdentifier"}],"url":"\/documentation\/shengwangchatuikit\/presentationanimation\/transforminitialframe(containerframe:finalframe:)","title":"transformInitialFrame(containerFrame:finalFrame:)","abstract":[],"role":"symbol","type":"topic"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/PresentationAnimation":{"navigatorTitle":[{"text":"PresentationAnimation","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PresentationAnimation","url":"\/documentation\/shengwangchatuikit\/presentationanimation","abstract":[],"role":"symbol","kind":"symbol","type":"topic","title":"PresentationAnimation","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"PresentationAnimation","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)NSObject":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/PresentationAnimation/performAnimation(animationContext:)":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PresentationAnimation\/performAnimation(animationContext:)","url":"\/documentation\/shengwangchatuikit\/presentationanimation\/performanimation(animationcontext:)","type":"topic","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"performAnimation"},{"kind":"text","text":"("},{"text":"animationContext","kind":"externalParam"},{"kind":"text","text":": "},{"text":"AnimationContext","kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit16AnimationContextV"},{"text":")","kind":"text"}],"title":"performAnimation(animationContext:)","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/PresentationAnimation/origin":{"abstract":[],"kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PresentationAnimation\/origin","url":"\/documentation\/shengwangchatuikit\/presentationanimation\/origin","title":"origin","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"origin"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit18PresentationOriginO","text":"PresentationOrigin"},{"text":"?","kind":"text"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/CrossZoomAnimation":{"navigatorTitle":[{"text":"CrossZoomAnimation","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/CrossZoomAnimation","title":"CrossZoomAnimation","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"CrossZoomAnimation","kind":"identifier"}],"type":"topic","abstract":[],"url":"\/documentation\/shengwangchatuikit\/crosszoomanimation"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/PresentationAnimation/init(options:origin:)":{"title":"init(options:origin:)","kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PresentationAnimation\/init(options:origin:)","abstract":[],"url":"\/documentation\/shengwangchatuikit\/presentationanimation\/init(options:origin:)","type":"topic","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"options"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit16AnimationOptionsO","text":"AnimationOptions"},{"kind":"text","text":", "},{"text":"origin","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PresentationOrigin","kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit18PresentationOriginO"},{"kind":"text","text":"?)"}]},"doc://org.cocoapods.ShengwangChatUIKit/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(cs)NSObject"},"doc://org.cocoapods.ShengwangChatUIKit/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/s7CVarArgP"},"doc://org.cocoapods.ShengwangChatUIKit/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/s23CustomStringConvertibleP"},"doc://org.cocoapods.ShengwangChatUIKit/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/PresentationAnimation/UIViewControllerAnimatedTransitioning-Implementations":{"url":"\/documentation\/shengwangchatuikit\/presentationanimation\/uiviewcontrolleranimatedtransitioning-implementations","type":"topic","role":"collectionGroup","title":"UIViewControllerAnimatedTransitioning Implementations","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PresentationAnimation\/UIViewControllerAnimatedTransitioning-Implementations","kind":"article","abstract":[]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/PresentationAnimation/afterAnimation(animationContext:)":{"type":"topic","url":"\/documentation\/shengwangchatuikit\/presentationanimation\/afteranimation(animationcontext:)","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PresentationAnimation\/afterAnimation(animationContext:)","title":"afterAnimation(animationContext:)","role":"symbol","abstract":[{"text":"动画完成后（做动画完成的清理工作，子类可覆写）","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"afterAnimation"},{"text":"(","kind":"text"},{"text":"animationContext","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:18ShengwangChatUIKit16AnimationContextV","kind":"typeIdentifier","text":"AnimationContext"},{"text":")","kind":"text"}]},"doc://org.cocoapods.ShengwangChatUIKit/SH":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://org.cocoapods.ShengwangChatUIKit/s8CopyableP":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/s8CopyableP","title":"Swift.Copyable","type":"unresolvable"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/PresentationAnimation/beforeAnimation(animationContext:)":{"url":"\/documentation\/shengwangchatuikit\/presentationanimation\/beforeanimation(animationcontext:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"beforeAnimation"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"animationContext"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit16AnimationContextV","text":"AnimationContext"},{"kind":"text","text":")"}],"role":"symbol","title":"beforeAnimation(animationContext:)","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PresentationAnimation\/beforeAnimation(animationContext:)","kind":"symbol","abstract":[]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/FlipHorizontalAnimation":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"FlipHorizontalAnimation"}],"url":"\/documentation\/shengwangchatuikit\/fliphorizontalanimation","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"FlipHorizontalAnimation","kind":"identifier"}],"abstract":[],"title":"FlipHorizontalAnimation","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/FlipHorizontalAnimation"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"PresentationAnimation"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"PresentationAnimation","kind":"identifier"}]},{"value":[{"text":"PresentationAnimation","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PresentationAnimation\/UIViewControllerAnimatedTransitioning-Implementations"],"generated":true,"title":"Default Implementations","anchor":"Default-Implementations"}],"op":"replace","path":"\/topicSections"},{"path":"\/relationshipsSections","value":[{"title":"Inherits From","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom"},{"kind":"relationships","type":"inheritedBy","title":"Inherited By","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/CrossDissolveAnimation","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/CrossZoomAnimation","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/FlipHorizontalAnimation"]},{"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIViewControllerAnimatedTransitioning"],"type":"conformsTo","title":"Conforms To","kind":"relationships"}],"op":"replace"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PresentationAnimation","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}]}],"kind":"declarations"}},{"op":"replace","value":"CrossDissolveAnimation","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1CrossDissolveAnimation\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1CrossDissolveAnimation\/fragments","value":[{"text":"CrossDissolveAnimation","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1CrossDissolveAnimation\/navigatorTitle","value":[{"kind":"identifier","text":"CrossDissolveAnimation"}]},{"value":"PresentationAnimation","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PresentationAnimation\/title"},{"op":"replace","value":[{"kind":"identifier","text":"PresentationAnimation"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PresentationAnimation\/fragments"},{"op":"replace","value":[{"text":"PresentationAnimation","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PresentationAnimation\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1CrossZoomAnimation\/title","value":"CrossZoomAnimation"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1CrossZoomAnimation\/fragments","op":"replace","value":[{"text":"CrossZoomAnimation","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1CrossZoomAnimation\/navigatorTitle","value":[{"kind":"identifier","text":"CrossZoomAnimation"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1FlipHorizontalAnimation\/title","op":"replace","value":"FlipHorizontalAnimation"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1FlipHorizontalAnimation\/fragments","value":[{"text":"FlipHorizontalAnimation","kind":"identifier"}]},{"op":"replace","value":[{"text":"FlipHorizontalAnimation","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1FlipHorizontalAnimation\/navigatorTitle"}]}]}