{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objcMembers"},{"kind":"text","text":" "},{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ReactionDetailCell","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ReactionDetailCell"},"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(cs)UICollectionViewCell"],"title":"Inherits From","type":"inheritsFrom"},{"title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)NSCoding","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)NSObject","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)CALayerDelegate","doc:\/\/org.cocoapods.ShengwangChatUIKit\/s7CVarArgP","doc:\/\/org.cocoapods.ShengwangChatUIKit\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.ShengwangChatUIKit\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.ShengwangChatUIKit\/SQ","doc:\/\/org.cocoapods.ShengwangChatUIKit\/SH","doc:\/\/org.cocoapods.ShengwangChatUIKit\/s8SendableP","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIAccessibilityIdentification","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIAppearance","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIAppearanceContainer","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UICoordinateSpace","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIDynamicItem","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIFocusEnvironment","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIFocusItem","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIFocusItemContainer","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UILargeContentViewerItem","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIResponderStandardEditActions","doc:\/\/org.cocoapods.ShengwangChatUIKit\/5UIKit23UITraitChangeObservableP","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UITraitEnvironment","doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIUserActivityRestoring"],"kind":"relationships"}],"metadata":{"modules":[{"name":"ShengwangChatUIKit"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ReactionDetailCell","kind":"identifier"}],"role":"symbol","title":"ReactionDetailCell","symbolKind":"class","roleHeading":"Class","navigatorTitle":[{"kind":"identifier","text":"ReactionDetailCell"}],"externalID":"c:@M@ShengwangChatUIKit@objc(cs)ReactionDetailCell"},"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit"]]},"topicSections":[{"anchor":"Initializers","title":"Initializers","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ReactionDetailCell\/init(coder:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ReactionDetailCell\/init(frame:)"],"generated":true},{"generated":true,"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ReactionDetailCell\/background"],"anchor":"Instance-Properties"},{"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ReactionDetailCell\/layoutSubviews()","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ReactionDetailCell\/refresh(reaction:)"],"generated":true}],"variants":[{"paths":["\/documentation\/shengwangchatuikit\/reactiondetailcell"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/shengwangchatuikit\/reactiondetailcell"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UIPopoverPresentationControllerSourceItem":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIPopoverPresentationControllerSourceItem","title":"UIKit.UIPopoverPresentationControllerSourceItem","type":"unresolvable"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)CALayerDelegate":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)CALayerDelegate","title":"QuartzCore.CALayerDelegate","type":"unresolvable"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UILargeContentViewerItem":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UILargeContentViewerItem","title":"UIKit.UILargeContentViewerItem","type":"unresolvable"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UIFocusItemContainer":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIFocusItemContainer","title":"UIKit.UIFocusItemContainer","type":"unresolvable"},"doc://org.cocoapods.ShengwangChatUIKit/s8SendableP":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/s8SendableP","title":"Swift.Sendable","type":"unresolvable"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ReactionDetailCell/init(frame:)":{"role":"symbol","navigatorTitle":[{"text":"initWithFrame:","kind":"identifier"}],"title":"init(frame:)","url":"\/documentation\/shengwangchatuikit\/reactiondetailcell\/init(frame:)","abstract":[],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ReactionDetailCell\/init(frame:)","type":"topic","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"frame"},{"kind":"text","text":": "},{"text":"CGRect","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":")"}],"kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/SH":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)NSCoding":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)NSCoding","title":"Foundation.NSCoding","type":"unresolvable"},"doc://org.cocoapods.ShengwangChatUIKit/s23CustomStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UIPasteConfigurationSupporting":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIPasteConfigurationSupporting","title":"UIKit.UIPasteConfigurationSupporting","type":"unresolvable"},"doc://org.cocoapods.ShengwangChatUIKit/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UIAppearance":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIAppearance","title":"UIKit.UIAppearance","type":"unresolvable"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UICoordinateSpace":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UICoordinateSpace","title":"UIKit.UICoordinateSpace","type":"unresolvable"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ReactionDetailCell/refresh(reaction:)":{"url":"\/documentation\/shengwangchatuikit\/reactiondetailcell\/refresh(reaction:)","type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ReactionDetailCell\/refresh(reaction:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"refresh"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"reaction"},{"text":": ","kind":"text"},{"text":"MessageReaction","kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit15MessageReactiona"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"refreshWithReaction:","kind":"identifier"}],"kind":"symbol","abstract":[],"title":"refresh(reaction:)"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)NSObject"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UIAccessibilityIdentification":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIAccessibilityIdentification","type":"unresolvable","title":"UIKit.UIAccessibilityIdentification"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ReactionDetailCell/layoutSubviews()":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ReactionDetailCell\/layoutSubviews()","title":"layoutSubviews()","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"layoutSubviews","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"layoutSubviews"},{"text":"()","kind":"text"}],"url":"\/documentation\/shengwangchatuikit\/reactiondetailcell\/layoutsubviews()","abstract":[]},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UIDynamicItem":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIDynamicItem","type":"unresolvable","title":"UIKit.UIDynamicItem"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UIFocusItem":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIFocusItem","type":"unresolvable","title":"UIKit.UIFocusItem"},"doc://org.cocoapods.ShengwangChatUIKit/objc(cs)UICollectionViewCell":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(cs)UICollectionViewCell","type":"unresolvable","title":"UICollectionViewCell"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ReactionDetailCell/init(coder:)":{"url":"\/documentation\/shengwangchatuikit\/reactiondetailcell\/init(coder:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ReactionDetailCell\/init(coder:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"text":"coder","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSCoder","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSCoder"},{"text":")","kind":"text"}],"title":"init(coder:)","abstract":[],"type":"topic","role":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UITraitEnvironment":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UITraitEnvironment","type":"unresolvable","title":"UIKit.UITraitEnvironment"},"doc://org.cocoapods.ShengwangChatUIKit/s7CVarArgP":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ReactionDetailCell/background":{"url":"\/documentation\/shengwangchatuikit\/reactiondetailcell\/background","type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ReactionDetailCell\/background","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"background","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"background"}],"kind":"symbol","abstract":[],"title":"background"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ReactionDetailCell":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ReactionDetailCell","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ReactionDetailCell","title":"ReactionDetailCell","abstract":[],"role":"symbol","url":"\/documentation\/shengwangchatuikit\/reactiondetailcell","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ReactionDetailCell"}]},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UIUserActivityRestoring":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIUserActivityRestoring","title":"UIKit.UIUserActivityRestoring","type":"unresolvable"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UIResponderStandardEditActions":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIResponderStandardEditActions","title":"UIKit.UIResponderStandardEditActions","type":"unresolvable"},"doc://org.cocoapods.ShengwangChatUIKit/SQ":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UIActivityItemsConfigurationProviding":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIActivityItemsConfigurationProviding","title":"UIKit.UIActivityItemsConfigurationProviding","type":"unresolvable"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UIFocusEnvironment":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIFocusEnvironment","title":"UIKit.UIFocusEnvironment","type":"unresolvable"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)UIAppearanceContainer":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)UIAppearanceContainer","title":"UIKit.UIAppearanceContainer","type":"unresolvable"},"doc://org.cocoapods.ShengwangChatUIKit/5UIKit23UITraitChangeObservableP":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/5UIKit23UITraitChangeObservableP","title":"UIKit.UITraitChangeObservable","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"value":"ReactionDetailCell","op":"replace","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"ReactionDetailCell","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ReactionDetailCell"}],"op":"replace"},{"path":"\/topicSections","op":"replace","value":[{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ReactionDetailCell\/background"],"anchor":"Instance-Properties","generated":true},{"title":"Instance Methods","anchor":"Instance-Methods","generated":true,"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ReactionDetailCell\/init(coder:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ReactionDetailCell\/init(frame:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ReactionDetailCell\/layoutSubviews()","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ReactionDetailCell\/refresh(reaction:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(cs)UICollectionViewCell"],"type":"inheritsFrom","title":"Inherits From"}]},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ReactionDetailCell"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","text":"UICollectionViewCell","preciseIdentifier":"c:objc(cs)UICollectionViewCell"}]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ReactionDetailCell~1init(frame:)\/title","value":"initWithFrame:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithFrame:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ReactionDetailCell~1init(frame:)\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ReactionDetailCell~1refresh(reaction:)\/title","op":"replace","value":"refreshWithReaction:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ReactionDetailCell~1refresh(reaction:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"refreshWithReaction:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ReactionDetailCell~1layoutSubviews()\/title","op":"replace","value":"layoutSubviews"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ReactionDetailCell~1layoutSubviews()\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"layoutSubviews"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ReactionDetailCell~1init(coder:)\/title","value":"initWithCoder:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ReactionDetailCell~1init(coder:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ReactionDetailCell~1background\/title","value":"background"},{"value":[{"text":"background","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ReactionDetailCell~1background\/fragments"},{"value":"ReactionDetailCell","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ReactionDetailCell\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ReactionDetailCell\/fragments","op":"replace","value":[{"text":"ReactionDetailCell","kind":"identifier"}]},{"op":"replace","value":[{"text":"ReactionDetailCell","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ReactionDetailCell\/navigatorTitle"}]}]}