{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit"]]},"metadata":{"title":"SearchHeaderBarActionType","externalID":"c:@M@ShengwangChatUIKit@E@SearchHeaderBarActionType","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"SearchHeaderBarActionType","kind":"identifier"}],"role":"symbol","symbolKind":"enum","modules":[{"name":"ShengwangChatUIKit"}],"navigatorTitle":[{"text":"SearchHeaderBarActionType","kind":"identifier"}],"roleHeading":"Enumeration"},"schemaVersion":{"minor":3,"major":0,"patch":0},"topicSections":[{"generated":true,"anchor":"Enumeration-Cases","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/SearchHeaderBarActionType\/back","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/SearchHeaderBarActionType\/cancel"],"title":"Enumeration Cases"},{"anchor":"Initializers","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/SearchHeaderBarActionType\/init(rawValue:)"],"title":"Initializers","generated":true},{"anchor":"Default-Implementations","title":"Default Implementations","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/SearchHeaderBarActionType\/Equatable-Implementations","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/SearchHeaderBarActionType\/RawRepresentable-Implementations"],"generated":true}],"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/SearchHeaderBarActionType","interfaceLanguage":"swift"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/searchheaderbaractiontype"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/searchheaderbaractiontype"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"SearchHeaderBarActionType","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/SQ","doc:\/\/org.cocoapods.ShengwangChatUIKit\/SH","doc:\/\/org.cocoapods.ShengwangChatUIKit\/SY"],"title":"Conforms To","kind":"relationships","type":"conformsTo"}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/SY":{"title":"Swift.RawRepresentable","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/SY"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/SearchHeaderBarActionType/init(rawValue:)":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/SearchHeaderBarActionType\/init(rawValue:)","abstract":[],"type":"topic","role":"symbol","url":"\/documentation\/shengwangchatuikit\/searchheaderbaractiontype\/init(rawvalue:)","kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Su","kind":"typeIdentifier","text":"UInt"},{"kind":"text","text":")"}],"title":"init(rawValue:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/SearchHeaderBarActionType":{"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SearchHeaderBarActionType"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/SearchHeaderBarActionType","title":"SearchHeaderBarActionType","abstract":[],"role":"symbol","kind":"symbol","url":"\/documentation\/shengwangchatuikit\/searchheaderbaractiontype","navigatorTitle":[{"kind":"identifier","text":"SearchHeaderBarActionType"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/SearchHeaderBarActionType/cancel":{"navigatorTitle":[{"text":"SearchHeaderBarActionTypeCancel","kind":"identifier"}],"kind":"symbol","title":"SearchHeaderBarActionType.cancel","url":"\/documentation\/shengwangchatuikit\/searchheaderbaractiontype\/cancel","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cancel"}],"abstract":[],"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/SearchHeaderBarActionType\/cancel"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/SearchHeaderBarActionType/RawRepresentable-Implementations":{"type":"topic","title":"RawRepresentable Implementations","url":"\/documentation\/shengwangchatuikit\/searchheaderbaractiontype\/rawrepresentable-implementations","abstract":[],"kind":"article","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/SearchHeaderBarActionType\/RawRepresentable-Implementations","role":"collectionGroup"},"doc://org.cocoapods.ShengwangChatUIKit/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/SQ"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/SH"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/SearchHeaderBarActionType/Equatable-Implementations":{"abstract":[],"kind":"article","role":"collectionGroup","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/SearchHeaderBarActionType\/Equatable-Implementations","url":"\/documentation\/shengwangchatuikit\/searchheaderbaractiontype\/equatable-implementations","title":"Equatable Implementations","type":"topic"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/SearchHeaderBarActionType/back":{"role":"symbol","abstract":[],"kind":"symbol","title":"SearchHeaderBarActionType.back","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"back","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/SearchHeaderBarActionType\/back","navigatorTitle":[{"text":"SearchHeaderBarActionTypeBack","kind":"identifier"}],"type":"topic","url":"\/documentation\/shengwangchatuikit\/searchheaderbaractiontype\/back"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"path":"\/metadata\/title","op":"replace","value":"SearchHeaderBarActionType"},{"value":"enum","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"SearchHeaderBarActionType","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"SearchHeaderBarActionType","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"anchor":"Enumeration-Cases","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/SearchHeaderBarActionType\/back","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/SearchHeaderBarActionType\/cancel"],"generated":true,"title":"Enumeration Cases"}],"op":"replace","path":"\/topicSections"},{"value":null,"op":"replace","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"SearchHeaderBarActionType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSUInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSUInteger"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"value":"SearchHeaderBarActionType","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1SearchHeaderBarActionType\/title"},{"value":[{"kind":"identifier","text":"SearchHeaderBarActionType"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1SearchHeaderBarActionType\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1SearchHeaderBarActionType\/navigatorTitle","value":[{"kind":"identifier","text":"SearchHeaderBarActionType"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1SearchHeaderBarActionType~1cancel\/title","value":"SearchHeaderBarActionTypeCancel","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1SearchHeaderBarActionType~1cancel\/fragments","value":[{"kind":"identifier","text":"SearchHeaderBarActionTypeCancel"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1SearchHeaderBarActionType~1back\/title","value":"SearchHeaderBarActionTypeBack","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"SearchHeaderBarActionTypeBack"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1SearchHeaderBarActionType~1back\/fragments"}]}]}