{"topicSections":[{"generated":true,"title":"Enumeration Cases","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/URLPreviewResult\/failure","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/URLPreviewResult\/parsing","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/URLPreviewResult\/success"],"anchor":"Enumeration-Cases"},{"title":"Initializers","generated":true,"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/URLPreviewResult\/init(rawValue:)"],"anchor":"Initializers"},{"title":"Default Implementations","anchor":"Default-Implementations","generated":true,"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/URLPreviewResult\/Equatable-Implementations","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/URLPreviewResult\/RawRepresentable-Implementations"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit"]]},"relationshipsSections":[{"type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/SQ","doc:\/\/org.cocoapods.ShengwangChatUIKit\/SH","doc:\/\/org.cocoapods.ShengwangChatUIKit\/SY"],"kind":"relationships"}],"metadata":{"modules":[{"name":"ShengwangChatUIKit"}],"externalID":"c:@M@ShengwangChatUIKit@E@URLPreviewResult","title":"URLPreviewResult","navigatorTitle":[{"text":"URLPreviewResult","kind":"identifier"}],"roleHeading":"Enumeration","symbolKind":"enum","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"URLPreviewResult"}],"role":"symbol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"URLPreviewResult"}],"platforms":["iOS"]}]}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/URLPreviewResult","interfaceLanguage":"swift"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/urlpreviewresult"]},{"paths":["\/documentation\/shengwangchatuikit\/urlpreviewresult"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/URLPreviewResult/RawRepresentable-Implementations":{"title":"RawRepresentable Implementations","kind":"article","url":"\/documentation\/shengwangchatuikit\/urlpreviewresult\/rawrepresentable-implementations","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/URLPreviewResult\/RawRepresentable-Implementations","abstract":[],"role":"collectionGroup","type":"topic"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/URLPreviewResult/Equatable-Implementations":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/URLPreviewResult\/Equatable-Implementations","kind":"article","role":"collectionGroup","title":"Equatable Implementations","url":"\/documentation\/shengwangchatuikit\/urlpreviewresult\/equatable-implementations","abstract":[]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/URLPreviewResult/failure":{"navigatorTitle":[{"text":"URLPreviewResultFailure","kind":"identifier"}],"abstract":[],"title":"URLPreviewResult.failure","type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/URLPreviewResult\/failure","url":"\/documentation\/shengwangchatuikit\/urlpreviewresult\/failure","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"failure"}],"role":"symbol","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/URLPreviewResult/success":{"url":"\/documentation\/shengwangchatuikit\/urlpreviewresult\/success","navigatorTitle":[{"kind":"identifier","text":"URLPreviewResultSuccess"}],"kind":"symbol","title":"URLPreviewResult.success","type":"topic","abstract":[],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"success"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/URLPreviewResult\/success"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/URLPreviewResult":{"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"URLPreviewResult","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/URLPreviewResult","kind":"symbol","navigatorTitle":[{"text":"URLPreviewResult","kind":"identifier"}],"role":"symbol","title":"URLPreviewResult","url":"\/documentation\/shengwangchatuikit\/urlpreviewresult","abstract":[]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/URLPreviewResult/init(rawValue:)":{"title":"init(rawValue:)","type":"topic","url":"\/documentation\/shengwangchatuikit\/urlpreviewresult\/init(rawvalue:)","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"rawValue"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5UInt8V","text":"UInt8"},{"kind":"text","text":")"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/URLPreviewResult\/init(rawValue:)","abstract":[]},"doc://org.cocoapods.ShengwangChatUIKit/SH":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/SH","title":"Swift.Hashable"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/URLPreviewResult/parsing":{"title":"URLPreviewResult.parsing","type":"topic","url":"\/documentation\/shengwangchatuikit\/urlpreviewresult\/parsing","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"parsing","kind":"identifier"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/URLPreviewResult\/parsing","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"URLPreviewResultParsing"}]},"doc://org.cocoapods.ShengwangChatUIKit/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/SQ"},"doc://org.cocoapods.ShengwangChatUIKit/SY":{"title":"Swift.RawRepresentable","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/SY"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration","op":"replace"},{"path":"\/metadata\/title","value":"URLPreviewResult","op":"replace"},{"value":"enum","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"URLPreviewResult","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"URLPreviewResult","kind":"identifier"}]},{"path":"\/topicSections","op":"replace","value":[{"title":"Enumeration Cases","anchor":"Enumeration-Cases","generated":true,"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/URLPreviewResult\/failure","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/URLPreviewResult\/parsing","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/URLPreviewResult\/success"]}]},{"value":null,"op":"replace","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"URLPreviewResult","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@uint8_t","text":"uint8_t","kind":"typeIdentifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","value":"URLPreviewResultFailure","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1URLPreviewResult~1failure\/title"},{"value":[{"text":"URLPreviewResultFailure","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1URLPreviewResult~1failure\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1URLPreviewResult~1success\/title","value":"URLPreviewResultSuccess"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1URLPreviewResult~1success\/fragments","value":[{"text":"URLPreviewResultSuccess","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1URLPreviewResult\/title","op":"replace","value":"URLPreviewResult"},{"value":[{"text":"URLPreviewResult","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1URLPreviewResult\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1URLPreviewResult\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"URLPreviewResult"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1URLPreviewResult~1parsing\/title","value":"URLPreviewResultParsing"},{"value":[{"kind":"identifier","text":"URLPreviewResultParsing"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1URLPreviewResult~1parsing\/fragments"}]}]}