{"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UserStateChangedListener","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"paths":["\/documentation\/shengwangchatuikit\/userstatechangedlistener"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/shengwangchatuikit\/userstatechangedlistener"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UserStateChangedListener"},{"kind":"text","text":" : "},{"text":"NSObjectProtocol","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject"}],"platforms":["iOS"],"languages":["swift"]}]}],"topicSections":[{"anchor":"Instance-Methods","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UserStateChangedListener\/onSocketConnectionStateChanged(state:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UserStateChangedListener\/onUserAutoLoginCompletion(error:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UserStateChangedListener\/onUserLoginOtherDevice(device:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UserStateChangedListener\/onUserTokenDidExpired()","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UserStateChangedListener\/onUserTokenWillExpired()","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UserStateChangedListener\/userAccountDidForcedToLogout(error:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UserStateChangedListener\/userAccountDidRemoved()","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UserStateChangedListener\/userDidForbidden()"],"generated":true,"title":"Instance Methods"}],"sections":[],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)NSObject"],"type":"inheritsFrom","title":"Inherits From","kind":"relationships"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UserStateChangedListener"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"UserStateChangedListener"}],"modules":[{"name":"ShengwangChatUIKit"}],"roleHeading":"Protocol","externalID":"c:@M@ShengwangChatUIKit@objc(pl)UserStateChangedListener","symbolKind":"protocol","title":"UserStateChangedListener"},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/UserStateChangedListener/userAccountDidRemoved()":{"url":"\/documentation\/shengwangchatuikit\/userstatechangedlistener\/useraccountdidremoved()","kind":"symbol","type":"topic","required":true,"navigatorTitle":[{"text":"userAccountDidRemoved","kind":"identifier"}],"abstract":[{"type":"text","text":"The user account did removed by server."}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UserStateChangedListener\/userAccountDidRemoved()","title":"userAccountDidRemoved()","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"userAccountDidRemoved"},{"kind":"text","text":"()"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/UserStateChangedListener/userAccountDidForcedToLogout(error:)":{"navigatorTitle":[{"text":"userAccountDidForcedToLogoutWithError:","kind":"identifier"}],"role":"symbol","title":"userAccountDidForcedToLogout(error:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"userAccountDidForcedToLogout"},{"kind":"text","text":"("},{"text":"error","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:18ShengwangChatUIKit0B5Errora","kind":"typeIdentifier","text":"ChatError"},{"kind":"text","text":"?)"}],"url":"\/documentation\/shengwangchatuikit\/userstatechangedlistener\/useraccountdidforcedtologout(error:)","abstract":[{"type":"text","text":"The user account logout by server."}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UserStateChangedListener\/userAccountDidForcedToLogout(error:)","required":true,"type":"topic","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/UserStateChangedListener":{"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"UserStateChangedListener","kind":"identifier"}],"navigatorTitle":[{"text":"UserStateChangedListener","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/userstatechangedlistener","type":"topic","abstract":[],"title":"UserStateChangedListener","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UserStateChangedListener","role":"symbol","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/objc(pl)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)NSObject"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/UserStateChangedListener/onUserTokenWillExpired()":{"navigatorTitle":[{"kind":"identifier","text":"onUserTokenWillExpired"}],"role":"symbol","title":"onUserTokenWillExpired()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"onUserTokenWillExpired","kind":"identifier"},{"text":"()","kind":"text"}],"url":"\/documentation\/shengwangchatuikit\/userstatechangedlistener\/onusertokenwillexpired()","abstract":[{"type":"text","text":"User token will expired,when you need to fetch chat token  re-login."}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UserStateChangedListener\/onUserTokenWillExpired()","required":true,"type":"topic","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/UserStateChangedListener/userDidForbidden()":{"url":"\/documentation\/shengwangchatuikit\/userstatechangedlistener\/userdidforbidden()","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"userDidForbidden"},{"text":"()","kind":"text"}],"required":true,"kind":"symbol","abstract":[{"text":"The method called on user did forbid by server.","type":"text"}],"title":"userDidForbidden()","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UserStateChangedListener\/userDidForbidden()","role":"symbol","navigatorTitle":[{"text":"userDidForbidden","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/UserStateChangedListener/onUserTokenDidExpired()":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UserStateChangedListener\/onUserTokenDidExpired()","role":"symbol","required":true,"url":"\/documentation\/shengwangchatuikit\/userstatechangedlistener\/onusertokendidexpired()","type":"topic","title":"onUserTokenDidExpired()","navigatorTitle":[{"kind":"identifier","text":"onUserTokenDidExpired"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onUserTokenDidExpired","kind":"identifier"},{"text":"()","kind":"text"}],"abstract":[{"text":"User token expired,when you need to fetch chat token  re-login.","type":"text"}],"kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/UserStateChangedListener/onSocketConnectionStateChanged(state:)":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UserStateChangedListener\/onSocketConnectionStateChanged(state:)","url":"\/documentation\/shengwangchatuikit\/userstatechangedlistener\/onsocketconnectionstatechanged(state:)","kind":"symbol","navigatorTitle":[{"text":"onSocketConnectionStateChangedWithState:","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"Chatroom socket connection state changed listener."}],"required":true,"title":"onSocketConnectionStateChanged(state:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onSocketConnectionStateChanged"},{"kind":"text","text":"("},{"text":"state","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:18ShengwangChatUIKit15ConnectionStatea","kind":"typeIdentifier","text":"ConnectionState"},{"text":")","kind":"text"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/UserStateChangedListener/onUserLoginOtherDevice(device:)":{"abstract":[{"text":"User login at other device","type":"text"}],"url":"\/documentation\/shengwangchatuikit\/userstatechangedlistener\/onuserloginotherdevice(device:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"onUserLoginOtherDevice","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"device"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UserStateChangedListener\/onUserLoginOtherDevice(device:)","title":"onUserLoginOtherDevice(device:)","required":true,"role":"symbol","navigatorTitle":[{"text":"onUserLoginOtherDeviceWithDevice:","kind":"identifier"}],"kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/UserStateChangedListener/onUserAutoLoginCompletion(error:)":{"navigatorTitle":[{"text":"onUserAutoLoginCompletionWithError:","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UserStateChangedListener\/onUserAutoLoginCompletion(error:)","url":"\/documentation\/shengwangchatuikit\/userstatechangedlistener\/onuserautologincompletion(error:)","abstract":[{"text":"When user auto login completion.","type":"text"}],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onUserAutoLoginCompletion"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"error"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit0B5Errora","text":"ChatError"},{"text":"?)","kind":"text"}],"role":"symbol","title":"onUserAutoLoginCompletion(error:)","required":true,"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Protocol","path":"\/metadata\/roleHeading","op":"replace"},{"value":"UserStateChangedListener","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"UserStateChangedListener"}],"op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"UserStateChangedListener"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UserStateChangedListener\/onSocketConnectionStateChanged(state:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UserStateChangedListener\/onUserAutoLoginCompletion(error:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UserStateChangedListener\/onUserLoginOtherDevice(device:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UserStateChangedListener\/onUserTokenDidExpired()","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UserStateChangedListener\/onUserTokenWillExpired()","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UserStateChangedListener\/userAccountDidForcedToLogout(error:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UserStateChangedListener\/userAccountDidRemoved()","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UserStateChangedListener\/userDidForbidden()"],"generated":true}]},{"op":"replace","path":"\/relationshipsSections","value":[{"title":"Inherits From","kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/objc(pl)NSObject"]}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UserStateChangedListener"},{"text":" <","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject"},{"text":">","kind":"text"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"userAccountDidRemoved","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1UserStateChangedListener~1userAccountDidRemoved()\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"userAccountDidRemoved","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1UserStateChangedListener~1userAccountDidRemoved()\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1UserStateChangedListener~1userAccountDidForcedToLogout(error:)\/title","value":"userAccountDidForcedToLogoutWithError:","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"userAccountDidForcedToLogoutWithError:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1UserStateChangedListener~1userAccountDidForcedToLogout(error:)\/fragments"},{"value":"UserStateChangedListener","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1UserStateChangedListener\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1UserStateChangedListener\/fragments","value":[{"text":"UserStateChangedListener","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1UserStateChangedListener\/navigatorTitle","value":[{"kind":"identifier","text":"UserStateChangedListener"}],"op":"replace"},{"op":"replace","value":"onUserTokenWillExpired","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1UserStateChangedListener~1onUserTokenWillExpired()\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1UserStateChangedListener~1onUserTokenWillExpired()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"onUserTokenWillExpired","kind":"identifier"}]},{"op":"replace","value":"userDidForbidden","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1UserStateChangedListener~1userDidForbidden()\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"userDidForbidden","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1UserStateChangedListener~1userDidForbidden()\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1UserStateChangedListener~1onUserTokenDidExpired()\/title","value":"onUserTokenDidExpired","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"onUserTokenDidExpired"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1UserStateChangedListener~1onUserTokenDidExpired()\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1UserStateChangedListener~1onSocketConnectionStateChanged(state:)\/title","value":"onSocketConnectionStateChangedWithState:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1UserStateChangedListener~1onSocketConnectionStateChanged(state:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onSocketConnectionStateChangedWithState:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1UserStateChangedListener~1onUserLoginOtherDevice(device:)\/title","value":"onUserLoginOtherDeviceWithDevice:"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1UserStateChangedListener~1onUserLoginOtherDevice(device:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onUserLoginOtherDeviceWithDevice:"}]},{"value":"onUserAutoLoginCompletionWithError:","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1UserStateChangedListener~1onUserAutoLoginCompletion(error:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1UserStateChangedListener~1onUserAutoLoginCompletion(error:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"onUserAutoLoginCompletionWithError:","kind":"identifier"}]}]}]}