{"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"actionClosure"},{"kind":"text","text":": (("},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@E@SearchHeaderBarActionType","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/SearchHeaderBarActionType","text":"SearchHeaderBarActionType"},{"text":") -> ())?","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"metadata":{"externalID":"s:18ShengwangChatUIKit15SearchHeaderBarC13actionClosureyAA0deF10ActionTypeOcSgvp","title":"actionClosure","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"actionClosure"},{"kind":"text","text":": (("},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@E@SearchHeaderBarActionType","text":"SearchHeaderBarActionType","kind":"typeIdentifier"},{"text":") -> ())?","kind":"text"}],"role":"symbol","modules":[{"name":"ShengwangChatUIKit"}],"symbolKind":"property","roleHeading":"Instance Property"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/SearchHeaderBar"]]},"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/SearchHeaderBar\/actionClosure","interfaceLanguage":"swift"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/searchheaderbar\/actionclosure"]}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/SearchHeaderBar/actionClosure":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"actionClosure","kind":"identifier"},{"text":": ((","kind":"text"},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@E@SearchHeaderBarActionType","kind":"typeIdentifier","text":"SearchHeaderBarActionType"},{"kind":"text","text":") -> ())?"}],"type":"topic","role":"symbol","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/SearchHeaderBar\/actionClosure","url":"\/documentation\/shengwangchatuikit\/searchheaderbar\/actionclosure","title":"actionClosure"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/SearchHeaderBar":{"title":"SearchHeaderBar","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SearchHeaderBar","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/searchheaderbar","role":"symbol","abstract":[],"type":"topic","navigatorTitle":[{"text":"SearchHeaderBar","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/SearchHeaderBar","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/SearchHeaderBarActionType":{"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SearchHeaderBarActionType"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/SearchHeaderBarActionType","title":"SearchHeaderBarActionType","abstract":[],"role":"symbol","kind":"symbol","url":"\/documentation\/shengwangchatuikit\/searchheaderbaractiontype","navigatorTitle":[{"kind":"identifier","text":"SearchHeaderBarActionType"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SearchHeaderBar","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1SearchHeaderBar\/title"},{"op":"replace","value":[{"text":"SearchHeaderBar","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1SearchHeaderBar\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1SearchHeaderBar\/navigatorTitle","value":[{"kind":"identifier","text":"SearchHeaderBar"}]},{"op":"replace","value":"SearchHeaderBarActionType","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1SearchHeaderBarActionType\/title"},{"value":[{"kind":"identifier","text":"SearchHeaderBarActionType"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1SearchHeaderBarActionType\/fragments","op":"replace"},{"value":[{"text":"SearchHeaderBarActionType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1SearchHeaderBarActionType\/navigatorTitle"}]}]}