{"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/SearchHeaderBar\/init(coder:)","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"required"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"?(","kind":"text"},{"text":"coder","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSCoder","text":"NSCoder","kind":"typeIdentifier"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"metadata":{"roleHeading":"Initializer","title":"init(coder:)","navigatorTitle":[{"text":"initWithCoder:","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"text":"coder","kind":"externalParam"},{"kind":"text","text":": "},{"text":"NSCoder","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSCoder"},{"text":")","kind":"text"}],"externalID":"c:@M@ShengwangChatUIKit@objc(cs)SearchHeaderBar(im)initWithCoder:","modules":[{"name":"ShengwangChatUIKit"}],"symbolKind":"init"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/SearchHeaderBar"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/searchheaderbar\/init(coder:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/searchheaderbar\/init(coder:)"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/SearchHeaderBar":{"title":"SearchHeaderBar","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SearchHeaderBar","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/searchheaderbar","role":"symbol","abstract":[],"type":"topic","navigatorTitle":[{"text":"SearchHeaderBar","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/SearchHeaderBar","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/SearchHeaderBar/init(coder:)":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/SearchHeaderBar\/init(coder:)","role":"symbol","url":"\/documentation\/shengwangchatuikit\/searchheaderbar\/init(coder:)","fragments":[{"kind":"identifier","text":"init"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"coder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSCoder","text":"NSCoder"},{"text":")","kind":"text"}],"abstract":[],"kind":"symbol","type":"topic","title":"init(coder:)","navigatorTitle":[{"text":"initWithCoder:","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"initWithCoder:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithCoder:"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"text":") ","kind":"text"},{"text":"initWithCoder:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSCoder","kind":"typeIdentifier","text":"NSCoder"},{"text":" *) ","kind":"text"},{"text":"coder","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SearchHeaderBar","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1SearchHeaderBar\/title"},{"op":"replace","value":[{"text":"SearchHeaderBar","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1SearchHeaderBar\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1SearchHeaderBar\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SearchHeaderBar"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1SearchHeaderBar~1init(coder:)\/title","op":"replace","value":"initWithCoder:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1SearchHeaderBar~1init(coder:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithCoder:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}