{"abstract":[{"type":"text","text":"When some view Implement the protocol method,you can use "},{"code":"Theme.switchTheme(style: .dark)","type":"codeVoice"},{"type":"text","text":" to switch theme."}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/SearchHeaderBar","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/SearchHeaderBar\/ThemeSwitchProtocol-Implementations"]]},"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/SearchHeaderBar\/switchTheme(style:)","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Instance Method","modules":[{"name":"ShengwangChatUIKit"}],"role":"symbol","title":"switchTheme(style:)","extendedModule":"ShengwangChatUIKit","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"switchTheme"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"style"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"ThemeStyle","preciseIdentifier":"c:@M@ShengwangChatUIKit@E@ThemeStyle"},{"kind":"text","text":")"}],"externalID":"c:@CM@ShengwangChatUIKit@objc(cs)SearchHeaderBar(im)switchThemeWithStyle:","navigatorTitle":[{"text":"switchThemeWithStyle:","kind":"identifier"}],"symbolKind":"method"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","kind":"attribute","text":"MainActor"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"switchTheme"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"style"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ThemeStyle","text":"ThemeStyle","preciseIdentifier":"c:@M@ShengwangChatUIKit@E@ThemeStyle"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ThemeStyle"}]}],"name":"style"}]}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/searchheaderbar\/switchtheme(style:)"]},{"paths":["\/documentation\/shengwangchatuikit\/searchheaderbar\/switchtheme(style:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/Appearance":{"navigatorTitle":[{"kind":"identifier","text":"Appearance"}],"type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/Appearance","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Appearance","kind":"identifier"}],"title":"Appearance","abstract":[{"type":"text","text":"An object containing visual configurations for the whole application."}],"url":"\/documentation\/shengwangchatuikit\/appearance"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/SearchHeaderBar":{"title":"SearchHeaderBar","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SearchHeaderBar","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/searchheaderbar","role":"symbol","abstract":[],"type":"topic","navigatorTitle":[{"text":"SearchHeaderBar","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/SearchHeaderBar","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/SearchHeaderBar/switchTheme(style:)":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/SearchHeaderBar\/switchTheme(style:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"switchTheme","kind":"identifier"},{"kind":"text","text":"("},{"text":"style","kind":"externalParam"},{"kind":"text","text":": "},{"text":"ThemeStyle","kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@E@ThemeStyle"},{"text":")","kind":"text"}],"kind":"symbol","abstract":[{"text":"When some view Implement the protocol method,you can use ","type":"text"},{"type":"codeVoice","code":"Theme.switchTheme(style: .dark)"},{"type":"text","text":" to switch theme."}],"url":"\/documentation\/shengwangchatuikit\/searchheaderbar\/switchtheme(style:)","type":"topic","title":"switchTheme(style:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"switchThemeWithStyle:"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/SearchHeaderBar/ThemeSwitchProtocol-Implementations":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/SearchHeaderBar\/ThemeSwitchProtocol-Implementations","title":"ThemeSwitchProtocol Implementations","role":"collectionGroup","url":"\/documentation\/shengwangchatuikit\/searchheaderbar\/themeswitchprotocol-implementations","abstract":[],"type":"topic","kind":"article"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ThemeStyle":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"ThemeStyle"}],"title":"ThemeStyle","url":"\/documentation\/shengwangchatuikit\/themestyle","abstract":[{"type":"text","text":"Contain light and dark themes of the ease chat UIKit.If you want to switch custom theme,you’ll modify primary&secondary&error&neutral&neutralSpecial hues properties in "},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/Appearance"},{"type":"text","text":".Then call "},{"type":"codeVoice","code":"Theme.switchTheme(style: .custom)"},{"type":"text","text":" method"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ThemeStyle","kind":"symbol","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ThemeStyle"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","value":"switchThemeWithStyle:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"switchThemeWithStyle:"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"switchThemeWithStyle:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ThemeStyle","text":"ThemeStyle","preciseIdentifier":"c:@M@ShengwangChatUIKit@E@ThemeStyle"},{"text":") ","kind":"text"},{"text":"style","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":"Appearance","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1Appearance\/title"},{"value":[{"text":"Appearance","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1Appearance\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1Appearance\/navigatorTitle","value":[{"text":"Appearance","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1SearchHeaderBar\/title","value":"SearchHeaderBar"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1SearchHeaderBar\/fragments","value":[{"text":"SearchHeaderBar","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1SearchHeaderBar\/navigatorTitle","value":[{"kind":"identifier","text":"SearchHeaderBar"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1SearchHeaderBar~1switchTheme(style:)\/title","value":"switchThemeWithStyle:"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1SearchHeaderBar~1switchTheme(style:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"switchThemeWithStyle:","kind":"identifier"}]},{"value":"ThemeStyle","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ThemeStyle\/title","op":"replace"},{"value":[{"kind":"identifier","text":"ThemeStyle"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ThemeStyle\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ThemeStyle\/navigatorTitle","value":[{"text":"ThemeStyle","kind":"identifier"}]}]}]}