{"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/SearchHeaderBar\/textFieldState","interfaceLanguage":"swift"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/searchheaderbar\/textfieldstate"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"textFieldState","kind":"identifier"},{"kind":"text","text":": (("},{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/SearchFieldState","kind":"typeIdentifier","text":"SearchFieldState","preciseIdentifier":"c:@M@ShengwangChatUIKit@E@SearchFieldState"},{"text":") -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?","kind":"text"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/SearchHeaderBar"]]},"metadata":{"modules":[{"name":"ShengwangChatUIKit"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"textFieldState","kind":"identifier"},{"kind":"text","text":": (("},{"text":"SearchFieldState","kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@E@SearchFieldState"},{"text":") -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"kind":"text","text":")?"}],"role":"symbol","title":"textFieldState","symbolKind":"property","roleHeading":"Instance Property","externalID":"s:18ShengwangChatUIKit15SearchHeaderBarC14textFieldStateyAA0dhI0OcSgvp"},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/SearchFieldState":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/SearchFieldState","abstract":[],"url":"\/documentation\/shengwangchatuikit\/searchfieldstate","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SearchFieldState"}],"role":"symbol","navigatorTitle":[{"text":"SearchFieldState","kind":"identifier"}],"title":"SearchFieldState","kind":"symbol","type":"topic"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/SearchHeaderBar":{"title":"SearchHeaderBar","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SearchHeaderBar","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/searchheaderbar","role":"symbol","abstract":[],"type":"topic","navigatorTitle":[{"text":"SearchHeaderBar","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/SearchHeaderBar","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/SearchHeaderBar/textFieldState":{"abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"textFieldState","kind":"identifier"},{"text":": ((","kind":"text"},{"kind":"typeIdentifier","text":"SearchFieldState","preciseIdentifier":"c:@M@ShengwangChatUIKit@E@SearchFieldState"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")?"}],"role":"symbol","type":"topic","url":"\/documentation\/shengwangchatuikit\/searchheaderbar\/textfieldstate","title":"textFieldState","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/SearchHeaderBar\/textFieldState"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1SearchFieldState\/title","op":"replace","value":"SearchFieldState"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1SearchFieldState\/fragments","value":[{"text":"SearchFieldState","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1SearchFieldState\/navigatorTitle","op":"replace","value":[{"text":"SearchFieldState","kind":"identifier"}]},{"value":"SearchHeaderBar","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1SearchHeaderBar\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1SearchHeaderBar\/fragments","value":[{"kind":"identifier","text":"SearchHeaderBar"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1SearchHeaderBar\/navigatorTitle","op":"replace","value":[{"text":"SearchHeaderBar","kind":"identifier"}]}]}]}