{"metadata":{"symbolKind":"method","navigatorTitle":[{"text":"textBubbleSize","kind":"identifier"}],"role":"symbol","modules":[{"name":"ShengwangChatUIKit"}],"roleHeading":"Instance Method","externalID":"c:@M@ShengwangChatUIKit@objc(cs)MessageEntity(im)textBubbleSize","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"textBubbleSize","kind":"identifier"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"c:@S@CGSize","kind":"typeIdentifier","text":"CGSize"}],"title":"textBubbleSize()"},"sections":[],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageEntity\/textBubbleSize()"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/messageentity\/textbubblesize()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/messageentity\/textbubblesize()"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageEntity"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"textBubbleSize","kind":"identifier"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize","text":"CGSize"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageEntity":{"navigatorTitle":[{"text":"MessageEntity","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageEntity","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessageEntity","kind":"identifier"}],"title":"MessageEntity","abstract":[],"url":"\/documentation\/shengwangchatuikit\/messageentity"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageEntity/textBubbleSize()":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageEntity\/textBubbleSize()","url":"\/documentation\/shengwangchatuikit\/messageentity\/textbubblesize()","kind":"symbol","navigatorTitle":[{"text":"textBubbleSize","kind":"identifier"}],"role":"symbol","abstract":[],"title":"textBubbleSize()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"textBubbleSize"},{"kind":"text","text":"() -> "},{"text":"CGSize","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"textBubbleSize"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"textBubbleSize","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"},{"text":") ","kind":"text"},{"kind":"identifier","text":"textBubbleSize"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace"},{"value":"MessageEntity","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageEntity\/title"},{"value":[{"text":"MessageEntity","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageEntity\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageEntity\/navigatorTitle","value":[{"kind":"identifier","text":"MessageEntity"}]},{"op":"replace","value":"textBubbleSize","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageEntity~1textBubbleSize()\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"textBubbleSize","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageEntity~1textBubbleSize()\/fragments"}]}]}