{"metadata":{"roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"urlPreview"}],"title":"urlPreview","role":"symbol","externalID":"c:@M@ShengwangChatUIKit@objc(cs)MessageEntity(py)urlPreview","modules":[{"name":"ShengwangChatUIKit"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"urlPreview"},{"kind":"text","text":": "},{"text":"URLPreviewManager","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)URLPreviewManager","kind":"typeIdentifier"},{"kind":"text","text":"."},{"text":"HTMLContent","kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit17URLPreviewManagerC11HTMLContentC"},{"text":"?","kind":"text"}],"symbolKind":"property"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"urlPreview","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/URLPreviewManager","text":"URLPreviewManager","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)URLPreviewManager"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit17URLPreviewManagerC11HTMLContentC","text":"HTMLContent","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/URLPreviewManager\/HTMLContent"},{"text":"?","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageEntity\/urlPreview"},"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageEntity"]]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/messageentity\/urlpreview"]},{"paths":["\/documentation\/shengwangchatuikit\/messageentity\/urlpreview"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/URLPreviewManager/HTMLContent":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HTMLContent","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/shengwangchatuikit\/urlpreviewmanager\/htmlcontent","type":"topic","title":"URLPreviewManager.HTMLContent","abstract":[],"role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/URLPreviewManager\/HTMLContent","navigatorTitle":[{"text":"HTMLContent","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageEntity":{"navigatorTitle":[{"text":"MessageEntity","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageEntity","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessageEntity","kind":"identifier"}],"title":"MessageEntity","abstract":[],"url":"\/documentation\/shengwangchatuikit\/messageentity"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageEntity/urlPreview":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageEntity\/urlPreview","url":"\/documentation\/shengwangchatuikit\/messageentity\/urlpreview","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"urlPreview"}],"role":"symbol","abstract":[],"title":"urlPreview","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"urlPreview","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)URLPreviewManager","text":"URLPreviewManager"},{"kind":"text","text":"."},{"text":"HTMLContent","kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit17URLPreviewManagerC11HTMLContentC"},{"text":"?","kind":"text"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/URLPreviewManager":{"abstract":[],"navigatorTitle":[{"text":"URLPreviewManager","kind":"identifier"}],"title":"URLPreviewManager","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/URLPreviewManager","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"URLPreviewManager","kind":"identifier"}],"type":"topic","kind":"symbol","url":"\/documentation\/shengwangchatuikit\/urlpreviewmanager"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"value":"urlPreview","path":"\/metadata\/title","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"urlPreview"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"HTMLContent","preciseIdentifier":"c:objc(cs)HTMLContent"},{"kind":"text","text":" * "},{"kind":"identifier","text":"urlPreview"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageEntity\/title","value":"MessageEntity","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"MessageEntity"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageEntity\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageEntity\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MessageEntity"}]},{"value":"urlPreview","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageEntity~1urlPreview\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageEntity~1urlPreview\/fragments","value":[{"text":"urlPreview","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1URLPreviewManager\/title","value":"URLPreviewManager"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1URLPreviewManager\/fragments","value":[{"text":"URLPreviewManager","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1URLPreviewManager\/navigatorTitle","value":[{"kind":"identifier","text":"URLPreviewManager"}]}]}]}