{"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/SearchHeaderBarDisplayStyle\/other"},"sections":[],"variants":[{"paths":["\/documentation\/shengwangchatuikit\/searchheaderbardisplaystyle\/other"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/searchheaderbardisplaystyle\/other"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"other","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/SearchHeaderBarDisplayStyle"]]},"metadata":{"externalID":"c:@M@ShengwangChatUIKit@E@SearchHeaderBarDisplayStyle@SearchHeaderBarDisplayStyleOther","navigatorTitle":[{"kind":"identifier","text":"SearchHeaderBarDisplayStyleOther"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"other","kind":"identifier"}],"role":"symbol","modules":[{"name":"ShengwangChatUIKit"}],"symbolKind":"case","roleHeading":"Case","title":"SearchHeaderBarDisplayStyle.other"},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/SearchHeaderBarDisplayStyle":{"navigatorTitle":[{"text":"SearchHeaderBarDisplayStyle","kind":"identifier"}],"abstract":[],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SearchHeaderBarDisplayStyle"}],"type":"topic","url":"\/documentation\/shengwangchatuikit\/searchheaderbardisplaystyle","kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/SearchHeaderBarDisplayStyle","title":"SearchHeaderBarDisplayStyle"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/SearchHeaderBarDisplayStyle/other":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/SearchHeaderBarDisplayStyle\/other","navigatorTitle":[{"text":"SearchHeaderBarDisplayStyleOther","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/searchheaderbardisplaystyle\/other","type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"other","kind":"identifier"}],"title":"SearchHeaderBarDisplayStyle.other","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SearchHeaderBarDisplayStyleOther","op":"replace","path":"\/metadata\/title"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"text":"SearchHeaderBarDisplayStyleOther","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"SearchHeaderBarDisplayStyleOther","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","value":"SearchHeaderBarDisplayStyle","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1SearchHeaderBarDisplayStyle\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1SearchHeaderBarDisplayStyle\/fragments","value":[{"text":"SearchHeaderBarDisplayStyle","kind":"identifier"}],"op":"replace"},{"value":[{"text":"SearchHeaderBarDisplayStyle","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1SearchHeaderBarDisplayStyle\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1SearchHeaderBarDisplayStyle~1other\/title","value":"SearchHeaderBarDisplayStyleOther"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1SearchHeaderBarDisplayStyle~1other\/fragments","value":[{"text":"SearchHeaderBarDisplayStyleOther","kind":"identifier"}]}]}]}