{"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"PresentedViewType.presentedViewComponent"},{"text":".","type":"text"}],"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageReactionsDetailController\/presentedViewComponent","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageReactionsDetailController"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"roleHeading":"Instance Property","role":"symbol","title":"presentedViewComponent","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"presentedViewComponent","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit22PresentedViewComponentV","text":"PresentedViewComponent"},{"text":"?","kind":"text"}],"externalID":"s:18ShengwangChatUIKit32MessageReactionsDetailControllerC22presentedViewComponentAA09PresentediJ0VSgvp","modules":[{"name":"ShengwangChatUIKit"}],"symbolKind":"property"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","kind":"attribute","text":"MainActor"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"presentedViewComponent"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PresentedViewComponent","text":"PresentedViewComponent","preciseIdentifier":"s:18ShengwangChatUIKit22PresentedViewComponentV"},{"kind":"text","text":"?"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/shengwangchatuikit\/messagereactionsdetailcontroller\/presentedviewcomponent"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageReactionsDetailController":{"navigatorTitle":[{"kind":"identifier","text":"MessageReactionsDetailController"}],"abstract":[],"title":"MessageReactionsDetailController","type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageReactionsDetailController","url":"\/documentation\/shengwangchatuikit\/messagereactionsdetailcontroller","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MessageReactionsDetailController"}],"role":"symbol","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/PresentedViewComponent":{"url":"\/documentation\/shengwangchatuikit\/presentedviewcomponent","abstract":[{"type":"text","text":"presentedView setting"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"PresentedViewComponent"}],"type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PresentedViewComponent","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"PresentedViewComponent","kind":"identifier"}],"title":"PresentedViewComponent"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageReactionsDetailController/presentedViewComponent":{"url":"\/documentation\/shengwangchatuikit\/messagereactionsdetailcontroller\/presentedviewcomponent","title":"presentedViewComponent","role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageReactionsDetailController\/presentedViewComponent","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"presentedViewComponent","kind":"identifier"},{"text":": ","kind":"text"},{"text":"PresentedViewComponent","preciseIdentifier":"s:18ShengwangChatUIKit22PresentedViewComponentV","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"MessageReactionsDetailController","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageReactionsDetailController\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageReactionsDetailController\/fragments","value":[{"text":"MessageReactionsDetailController","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageReactionsDetailController\/navigatorTitle","value":[{"text":"MessageReactionsDetailController","kind":"identifier"}]}]}]}