{"metadata":{"roleHeading":"API Collection","title":"ThemeSwitchProtocol Implementations","role":"collectionGroup","modules":[{"name":"ShengwangChatUIKit"}]},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageReactionsDetailController"]]},"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageReactionsDetailController\/ThemeSwitchProtocol-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","generated":true,"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageReactionsDetailController\/switchTheme(style:)"],"anchor":"Instance-Methods"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/messagereactionsdetailcontroller\/themeswitchprotocol-implementations"]},{"paths":["\/documentation\/shengwangchatuikit\/messagereactionsdetailcontroller\/themeswitchprotocol-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"article","references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageReactionsDetailController/switchTheme(style:)":{"title":"switchTheme(style:)","role":"symbol","url":"\/documentation\/shengwangchatuikit\/messagereactionsdetailcontroller\/switchtheme(style:)","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageReactionsDetailController\/switchTheme(style:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"switchTheme"},{"kind":"text","text":"("},{"kind":"externalParam","text":"style"},{"kind":"text","text":": "},{"text":"ThemeStyle","preciseIdentifier":"c:@M@ShengwangChatUIKit@E@ThemeStyle","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"switchThemeWithStyle:","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"When some view Implement the protocol method,you can use "},{"code":"Theme.switchTheme(style: .dark)","type":"codeVoice"},{"type":"text","text":" to switch theme."}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageReactionsDetailController":{"navigatorTitle":[{"kind":"identifier","text":"MessageReactionsDetailController"}],"abstract":[],"title":"MessageReactionsDetailController","type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageReactionsDetailController","url":"\/documentation\/shengwangchatuikit\/messagereactionsdetailcontroller","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MessageReactionsDetailController"}],"role":"symbol","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageReactionsDetailController\/switchTheme(style:)"],"title":"Instance Methods","anchor":"Instance-Methods","generated":true}],"op":"replace"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":"switchThemeWithStyle:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageReactionsDetailController~1switchTheme(style:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"switchThemeWithStyle:"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageReactionsDetailController~1switchTheme(style:)\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageReactionsDetailController\/title","op":"replace","value":"MessageReactionsDetailController"},{"op":"replace","value":[{"text":"MessageReactionsDetailController","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageReactionsDetailController\/fragments"},{"value":[{"text":"MessageReactionsDetailController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageReactionsDetailController\/navigatorTitle"}]}]}