{"variants":[{"paths":["\/documentation\/shengwangchatuikit\/messagereactionsdetailcontroller\/uitableviewdelegate-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/messagereactionsdetailcontroller\/uitableviewdelegate-implementations"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageReactionsDetailController"]]},"kind":"article","schemaVersion":{"minor":3,"patch":0,"major":0},"topicSections":[{"generated":true,"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageReactionsDetailController\/tableView(_:didSelectRowAt:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageReactionsDetailController\/tableView(_:willDisplay:forRowAt:)"],"anchor":"Instance-Methods","title":"Instance Methods"}],"metadata":{"modules":[{"name":"ShengwangChatUIKit"}],"roleHeading":"API Collection","title":"UITableViewDelegate Implementations","role":"collectionGroup"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageReactionsDetailController\/UITableViewDelegate-Implementations"},"sections":[],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageReactionsDetailController/tableView(_:didSelectRowAt:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"tableView","kind":"identifier"},{"kind":"text","text":"("},{"text":"UITableView","preciseIdentifier":"c:objc(cs)UITableView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didSelectRowAt"},{"kind":"text","text":": "},{"text":"IndexPath","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation9IndexPathV"},{"text":")","kind":"text"}],"url":"\/documentation\/shengwangchatuikit\/messagereactionsdetailcontroller\/tableview(_:didselectrowat:)","kind":"symbol","type":"topic","abstract":[],"title":"tableView(_:didSelectRowAt:)","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageReactionsDetailController\/tableView(_:didSelectRowAt:)","navigatorTitle":[{"kind":"identifier","text":"tableView:didSelectRowAtIndexPath:"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageReactionsDetailController":{"navigatorTitle":[{"kind":"identifier","text":"MessageReactionsDetailController"}],"abstract":[],"title":"MessageReactionsDetailController","type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageReactionsDetailController","url":"\/documentation\/shengwangchatuikit\/messagereactionsdetailcontroller","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MessageReactionsDetailController"}],"role":"symbol","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageReactionsDetailController/tableView(_:willDisplay:forRowAt:)":{"abstract":[],"kind":"symbol","url":"\/documentation\/shengwangchatuikit\/messagereactionsdetailcontroller\/tableview(_:willdisplay:forrowat:)","navigatorTitle":[{"text":"tableView:willDisplayCell:forRowAtIndexPath:","kind":"identifier"}],"title":"tableView(_:willDisplay:forRowAt:)","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageReactionsDetailController\/tableView(_:willDisplay:forRowAt:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"tableView"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UITableView","text":"UITableView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"willDisplay"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UITableViewCell","text":"UITableViewCell","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"forRowAt"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"text":")","kind":"text"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":[{"anchor":"Instance-Methods","title":"Instance Methods","generated":true,"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageReactionsDetailController\/tableView(_:didSelectRowAt:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageReactionsDetailController\/tableView(_:willDisplay:forRowAt:)"]}],"path":"\/topicSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":"tableView:didSelectRowAtIndexPath:","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageReactionsDetailController~1tableView(_:didSelectRowAt:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageReactionsDetailController~1tableView(_:didSelectRowAt:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"tableView:didSelectRowAtIndexPath:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageReactionsDetailController\/title","value":"MessageReactionsDetailController","op":"replace"},{"value":[{"kind":"identifier","text":"MessageReactionsDetailController"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageReactionsDetailController\/fragments","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"MessageReactionsDetailController"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageReactionsDetailController\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageReactionsDetailController~1tableView(_:willDisplay:forRowAt:)\/title","value":"tableView:willDisplayCell:forRowAtIndexPath:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"tableView:willDisplayCell:forRowAtIndexPath:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageReactionsDetailController~1tableView(_:willDisplay:forRowAt:)\/fragments"}]}]}