{"metadata":{"title":"afterAnimation(animationContext:)","roleHeading":"Instance Method","externalID":"s:18ShengwangChatUIKit22CrossDissolveAnimationC05afterF016animationContextyAA0fI0V_tF","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"afterAnimation","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"animationContext"},{"kind":"text","text":": "},{"text":"AnimationContext","preciseIdentifier":"s:18ShengwangChatUIKit16AnimationContextV","kind":"typeIdentifier"},{"text":")","kind":"text"}],"symbolKind":"method","modules":[{"name":"ShengwangChatUIKit"}],"role":"symbol"},"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/CrossDissolveAnimation"]]},"abstract":[{"type":"text","text":"动画完成后（做动画完成的清理工作，子类可覆写）"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/crossdissolveanimation\/afteranimation(animationcontext:)"]}],"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/CrossDissolveAnimation\/afterAnimation(animationContext:)","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"override"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"afterAnimation"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"animationContext"},{"text":": ","kind":"text"},{"text":"AnimationContext","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/AnimationContext","kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit16AnimationContextV"},{"text":")","kind":"text"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"animationContext","content":[{"inlineContent":[{"type":"text","text":"动画上下文"}],"type":"paragraph"}]}]}],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/CrossDissolveAnimation/afterAnimation(animationContext:)":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/CrossDissolveAnimation\/afterAnimation(animationContext:)","role":"symbol","url":"\/documentation\/shengwangchatuikit\/crossdissolveanimation\/afteranimation(animationcontext:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"afterAnimation","kind":"identifier"},{"text":"(","kind":"text"},{"text":"animationContext","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit16AnimationContextV","text":"AnimationContext"},{"text":")","kind":"text"}],"abstract":[{"type":"text","text":"动画完成后（做动画完成的清理工作，子类可覆写）"}],"kind":"symbol","title":"afterAnimation(animationContext:)","type":"topic"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/CrossDissolveAnimation":{"type":"topic","abstract":[],"navigatorTitle":[{"text":"CrossDissolveAnimation","kind":"identifier"}],"kind":"symbol","title":"CrossDissolveAnimation","url":"\/documentation\/shengwangchatuikit\/crossdissolveanimation","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CrossDissolveAnimation"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/CrossDissolveAnimation","role":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/AnimationContext":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"AnimationContext"}],"type":"topic","title":"AnimationContext","url":"\/documentation\/shengwangchatuikit\/animationcontext","navigatorTitle":[{"kind":"identifier","text":"AnimationContext"}],"abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/AnimationContext","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1CrossDissolveAnimation\/title","value":"CrossDissolveAnimation"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1CrossDissolveAnimation\/fragments","value":[{"kind":"identifier","text":"CrossDissolveAnimation"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1CrossDissolveAnimation\/navigatorTitle","value":[{"kind":"identifier","text":"CrossDissolveAnimation"}],"op":"replace"}]}]}