{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/CrossDissolveAnimation\/beforeAnimation(animationContext:)"},"kind":"symbol","metadata":{"roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"beforeAnimation","kind":"identifier"},{"text":"(","kind":"text"},{"text":"animationContext","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:18ShengwangChatUIKit16AnimationContextV","text":"AnimationContext","kind":"typeIdentifier"},{"kind":"text","text":")"}],"title":"beforeAnimation(animationContext:)","role":"symbol","externalID":"s:18ShengwangChatUIKit22CrossDissolveAnimationC06beforeF016animationContextyAA0fI0V_tF","symbolKind":"method","modules":[{"name":"ShengwangChatUIKit"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"beforeAnimation","kind":"identifier"},{"text":"(","kind":"text"},{"text":"animationContext","kind":"externalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/AnimationContext","text":"AnimationContext","kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit16AnimationContextV"},{"text":")","kind":"text"}],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/shengwangchatuikit\/crossdissolveanimation\/beforeanimation(animationcontext:)"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/CrossDissolveAnimation"]]},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/CrossDissolveAnimation/beforeAnimation(animationContext:)":{"type":"topic","abstract":[],"kind":"symbol","title":"beforeAnimation(animationContext:)","url":"\/documentation\/shengwangchatuikit\/crossdissolveanimation\/beforeanimation(animationcontext:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"beforeAnimation","kind":"identifier"},{"text":"(","kind":"text"},{"text":"animationContext","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:18ShengwangChatUIKit16AnimationContextV","text":"AnimationContext","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/CrossDissolveAnimation\/beforeAnimation(animationContext:)","role":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/CrossDissolveAnimation":{"type":"topic","abstract":[],"navigatorTitle":[{"text":"CrossDissolveAnimation","kind":"identifier"}],"kind":"symbol","title":"CrossDissolveAnimation","url":"\/documentation\/shengwangchatuikit\/crossdissolveanimation","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CrossDissolveAnimation"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/CrossDissolveAnimation","role":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/AnimationContext":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"AnimationContext"}],"type":"topic","title":"AnimationContext","url":"\/documentation\/shengwangchatuikit\/animationcontext","navigatorTitle":[{"kind":"identifier","text":"AnimationContext"}],"abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/AnimationContext","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"CrossDissolveAnimation","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1CrossDissolveAnimation\/title"},{"op":"replace","value":[{"kind":"identifier","text":"CrossDissolveAnimation"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1CrossDissolveAnimation\/fragments"},{"value":[{"text":"CrossDissolveAnimation","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1CrossDissolveAnimation\/navigatorTitle"}]}]}