{"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"performAnimation","kind":"identifier"},{"text":"(","kind":"text"},{"text":"animationContext","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AnimationContext","preciseIdentifier":"s:18ShengwangChatUIKit16AnimationContextV","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/AnimationContext"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/crossdissolveanimation\/performanimation(animationcontext:)"]}],"metadata":{"modules":[{"name":"ShengwangChatUIKit"}],"symbolKind":"method","roleHeading":"Instance Method","title":"performAnimation(animationContext:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"performAnimation","kind":"identifier"},{"kind":"text","text":"("},{"text":"animationContext","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:18ShengwangChatUIKit16AnimationContextV","kind":"typeIdentifier","text":"AnimationContext"},{"kind":"text","text":")"}],"externalID":"s:18ShengwangChatUIKit22CrossDissolveAnimationC07performF016animationContextyAA0fI0V_tF","role":"symbol"},"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/CrossDissolveAnimation"]]},"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/CrossDissolveAnimation\/performAnimation(animationContext:)","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/CrossDissolveAnimation":{"type":"topic","abstract":[],"navigatorTitle":[{"text":"CrossDissolveAnimation","kind":"identifier"}],"kind":"symbol","title":"CrossDissolveAnimation","url":"\/documentation\/shengwangchatuikit\/crossdissolveanimation","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CrossDissolveAnimation"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/CrossDissolveAnimation","role":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/CrossDissolveAnimation/performAnimation(animationContext:)":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/CrossDissolveAnimation\/performAnimation(animationContext:)","role":"symbol","url":"\/documentation\/shengwangchatuikit\/crossdissolveanimation\/performanimation(animationcontext:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"performAnimation","kind":"identifier"},{"kind":"text","text":"("},{"text":"animationContext","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AnimationContext","kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit16AnimationContextV"},{"text":")","kind":"text"}],"abstract":[],"kind":"symbol","title":"performAnimation(animationContext:)","type":"topic"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/AnimationContext":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"AnimationContext"}],"type":"topic","title":"AnimationContext","url":"\/documentation\/shengwangchatuikit\/animationcontext","navigatorTitle":[{"kind":"identifier","text":"AnimationContext"}],"abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/AnimationContext","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"CrossDissolveAnimation","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1CrossDissolveAnimation\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1CrossDissolveAnimation\/fragments","op":"replace","value":[{"kind":"identifier","text":"CrossDissolveAnimation"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1CrossDissolveAnimation\/navigatorTitle","value":[{"text":"CrossDissolveAnimation","kind":"identifier"}],"op":"replace"}]}]}