{"metadata":{"symbolKind":"method","title":"fetchParticipants()","roleHeading":"Instance Method","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"fetchParticipants","kind":"identifier"},{"text":"()","kind":"text"}],"externalID":"c:@M@ShengwangChatUIKit@objc(cs)ChatThreadParticipantsController(im)fetchParticipants","modules":[{"name":"ShengwangChatUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"fetchParticipants"}]},"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadParticipantsController"]]},"variants":[{"paths":["\/documentation\/shengwangchatuikit\/chatthreadparticipantscontroller\/fetchparticipants()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/chatthreadparticipantscontroller\/fetchparticipants()"]}],"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadParticipantsController\/fetchParticipants()","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"fetchParticipants","kind":"identifier"},{"kind":"text","text":"()"}],"platforms":["iOS"],"languages":["swift"]}]}],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatThreadParticipantsController/fetchParticipants()":{"url":"\/documentation\/shengwangchatuikit\/chatthreadparticipantscontroller\/fetchparticipants()","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"fetchParticipants"},{"text":"()","kind":"text"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadParticipantsController\/fetchParticipants()","abstract":[],"kind":"symbol","title":"fetchParticipants()","role":"symbol","navigatorTitle":[{"text":"fetchParticipants","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatThreadParticipantsController":{"title":"ChatThreadParticipantsController","kind":"symbol","type":"topic","abstract":[],"url":"\/documentation\/shengwangchatuikit\/chatthreadparticipantscontroller","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ChatThreadParticipantsController","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ChatThreadParticipantsController"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadParticipantsController"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"fetchParticipants"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"fetchParticipants"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"fetchParticipants"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":"fetchParticipants","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadParticipantsController~1fetchParticipants()\/title","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"fetchParticipants","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadParticipantsController~1fetchParticipants()\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadParticipantsController\/title","value":"ChatThreadParticipantsController","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadParticipantsController\/fragments","value":[{"text":"ChatThreadParticipantsController","kind":"identifier"}],"op":"replace"},{"value":[{"text":"ChatThreadParticipantsController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadParticipantsController\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}