{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/chatthreadparticipantscontroller\/participants"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/chatthreadparticipantscontroller\/participants"]}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"participants"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"participants"},{"kind":"text","text":": ["},{"text":"ChatUserProfileProtocol","kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(pl)ChatUserProfileProtocol"},{"text":"]","kind":"text"}],"roleHeading":"Instance Property","modules":[{"name":"ShengwangChatUIKit"}],"title":"participants","externalID":"c:@M@ShengwangChatUIKit@objc(cs)ChatThreadParticipantsController(py)participants","role":"symbol","symbolKind":"property"},"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadParticipantsController"]]},"abstract":[{"type":"text","text":"The array of participants in the group."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadParticipantsController\/participants"},"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"participants","kind":"identifier"},{"kind":"text","text":": ["},{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatUserProfileProtocol","kind":"typeIdentifier","text":"ChatUserProfileProtocol","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(pl)ChatUserProfileProtocol"},{"kind":"text","text":"] { get }"}],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatUserProfileProtocol":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatUserProfileProtocol","abstract":[{"text":"Profile of the ChatUIKit display needed.","type":"text"}],"title":"ChatUserProfileProtocol","type":"topic","kind":"symbol","navigatorTitle":[{"text":"ChatUserProfileProtocol","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"ChatUserProfileProtocol","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/chatuserprofileprotocol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatThreadParticipantsController":{"title":"ChatThreadParticipantsController","kind":"symbol","type":"topic","abstract":[],"url":"\/documentation\/shengwangchatuikit\/chatthreadparticipantscontroller","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ChatThreadParticipantsController","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ChatThreadParticipantsController"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadParticipantsController"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatThreadParticipantsController/participants":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadParticipantsController\/participants","title":"participants","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"participants"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(pl)ChatUserProfileProtocol","kind":"typeIdentifier","text":"ChatUserProfileProtocol"},{"text":"]","kind":"text"}],"abstract":[{"text":"The array of participants in the group.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"participants"}],"url":"\/documentation\/shengwangchatuikit\/chatthreadparticipantscontroller\/participants"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"participants","op":"replace"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"participants","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSArray<id<ChatUserProfileProtocol>>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" * "},{"kind":"identifier","text":"participants"},{"text":";","kind":"text"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatUserProfileProtocol\/title","value":"ChatUserProfileProtocol","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatUserProfileProtocol\/fragments","value":[{"kind":"identifier","text":"ChatUserProfileProtocol"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatUserProfileProtocol\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"ChatUserProfileProtocol"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadParticipantsController\/title","value":"ChatThreadParticipantsController"},{"value":[{"text":"ChatThreadParticipantsController","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadParticipantsController\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadParticipantsController\/navigatorTitle","value":[{"text":"ChatThreadParticipantsController","kind":"identifier"}]},{"value":"participants","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadParticipantsController~1participants\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadParticipantsController~1participants\/fragments","value":[{"text":"participants","kind":"identifier"}],"op":"replace"}]}]}