{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageTopicView"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"required"},{"kind":"text","text":" "},{"text":"init","kind":"keyword"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"coder"},{"text":": ","kind":"text"},{"text":"NSCoder","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSCoder"},{"text":")","kind":"text"}]}]}],"variants":[{"paths":["\/documentation\/shengwangchatuikit\/messagetopicview\/init(coder:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/shengwangchatuikit\/messagetopicview\/init(coder:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageTopicView\/init(coder:)"},"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"title":"init(coder:)","roleHeading":"Initializer","externalID":"c:@M@ShengwangChatUIKit@objc(cs)MessageTopicView(im)initWithCoder:","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"text":"coder","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSCoder","kind":"typeIdentifier","text":"NSCoder"},{"text":")","kind":"text"}],"symbolKind":"init","modules":[{"name":"ShengwangChatUIKit"}],"navigatorTitle":[{"text":"initWithCoder:","kind":"identifier"}],"role":"symbol"},"kind":"symbol","sections":[],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageTopicView/init(coder:)":{"title":"init(coder:)","type":"topic","url":"\/documentation\/shengwangchatuikit\/messagetopicview\/init(coder:)","kind":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageTopicView\/init(coder:)","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"coder"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSCoder","text":"NSCoder","kind":"typeIdentifier"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"role":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageTopicView":{"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageTopicView","abstract":[],"url":"\/documentation\/shengwangchatuikit\/messagetopicview","navigatorTitle":[{"text":"MessageTopicView","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MessageTopicView"}],"role":"symbol","title":"MessageTopicView"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"initWithCoder:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithCoder:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:*Qo","kind":"typeIdentifier","text":"id"},{"text":") ","kind":"text"},{"text":"initWithCoder:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSCoder","kind":"typeIdentifier","text":"NSCoder"},{"text":" *) ","kind":"text"},{"text":"coder","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageTopicView~1init(coder:)\/title","value":"initWithCoder:"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageTopicView~1init(coder:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithCoder:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageTopicView\/title","value":"MessageTopicView","op":"replace"},{"value":[{"kind":"identifier","text":"MessageTopicView"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageTopicView\/fragments"},{"op":"replace","value":[{"text":"MessageTopicView","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageTopicView\/navigatorTitle"}]}]}