{"metadata":{"title":"IConversationListDriver Implementations","role":"collectionGroup","roleHeading":"API Collection","modules":[{"name":"ShengwangChatUIKit"}]},"kind":"article","sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationList\/IConversationListDriver-Implementations","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/shengwangchatuikit\/conversationlist\/iconversationlistdriver-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/shengwangchatuikit\/conversationlist\/iconversationlistdriver-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationList"]]},"topicSections":[{"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationList\/appendThenRefresh(infos:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationList\/occurError()","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationList\/refreshList(infos:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationList\/refreshProfiles(infos:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationList\/showNew(info:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationList\/swipeMenuOperation(info:type:)"],"title":"Instance Methods","generated":true,"anchor":"Instance-Methods"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ConversationList":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationList","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ConversationList"}],"navigatorTitle":[{"text":"ConversationList","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/conversationlist","role":"symbol","kind":"symbol","title":"ConversationList","abstract":[],"type":"topic"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ConversationList/refreshList(infos:)":{"navigatorTitle":[{"kind":"identifier","text":"refreshListWithInfos:"}],"abstract":[{"type":"text","text":"This method can be used when pulling down to refresh."}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationList\/refreshList(infos:)","url":"\/documentation\/shengwangchatuikit\/conversationlist\/refreshlist(infos:)","title":"refreshList(infos:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"refreshList","kind":"identifier"},{"kind":"text","text":"("},{"text":"infos","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)ConversationInfo","text":"ConversationInfo"},{"text":"])","kind":"text"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ConversationList/appendThenRefresh(infos:)":{"navigatorTitle":[{"kind":"identifier","text":"appendThenRefreshWithInfos:"}],"url":"\/documentation\/shengwangchatuikit\/conversationlist\/appendthenrefresh(infos:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"appendThenRefresh"},{"kind":"text","text":"("},{"text":"infos","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"ConversationInfo","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)ConversationInfo"},{"kind":"text","text":"])"}],"role":"symbol","title":"appendThenRefresh(infos:)","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationList\/appendThenRefresh(infos:)","kind":"symbol","abstract":[{"type":"text","text":"When you receive a lot of messages from new contacts, you can call this method for data transfer."}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ConversationList/showNew(info:)":{"abstract":[{"text":"When you received a new contact message,you can call the method.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"showNewWithInfo:"}],"title":"showNew(info:)","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationList\/showNew(info:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showNew"},{"kind":"text","text":"("},{"text":"info","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)ConversationInfo","text":"ConversationInfo"},{"text":")","kind":"text"}],"type":"topic","kind":"symbol","url":"\/documentation\/shengwangchatuikit\/conversationlist\/shownew(info:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ConversationList/occurError()":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationList\/occurError()","url":"\/documentation\/shengwangchatuikit\/conversationlist\/occurerror()","kind":"symbol","navigatorTitle":[{"text":"occurError","kind":"identifier"}],"role":"symbol","abstract":[{"text":"When fetch list occur error.","type":"text"}],"title":"occurError()","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"occurError","kind":"identifier"},{"text":"()","kind":"text"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ConversationList/refreshProfiles(infos:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"refreshProfiles"},{"text":"(","kind":"text"},{"text":"infos","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"ChatUserProfileProtocol","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(pl)ChatUserProfileProtocol"},{"kind":"text","text":"])"}],"type":"topic","role":"symbol","abstract":[{"type":"text","text":"This method can be used when you want refresh some  display info  of datas."}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"refreshProfilesWithInfos:"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationList\/refreshProfiles(infos:)","url":"\/documentation\/shengwangchatuikit\/conversationlist\/refreshprofiles(infos:)","title":"refreshProfiles(infos:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ConversationList/swipeMenuOperation(info:type:)":{"type":"topic","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"swipeMenuOperation"},{"kind":"text","text":"("},{"text":"info","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)ConversationInfo","text":"ConversationInfo","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"type","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@E@UIContextualActionType","kind":"typeIdentifier","text":"UIContextualActionType"},{"text":")","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationList\/swipeMenuOperation(info:type:)","navigatorTitle":[{"kind":"identifier","text":"swipeMenuOperationWithInfo:type:"}],"url":"\/documentation\/shengwangchatuikit\/conversationlist\/swipemenuoperation(info:type:)","kind":"symbol","title":"swipeMenuOperation(info:type:)","abstract":[{"type":"text","text":"Conversation Operation event after clicking the button in the side-sliding menu."}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":[{"anchor":"Instance-Methods","title":"Instance Methods","generated":true,"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationList\/appendThenRefresh(infos:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationList\/occurError()","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationList\/refreshList(infos:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationList\/refreshProfiles(infos:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationList\/showNew(info:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationList\/swipeMenuOperation(info:type:)"]}],"op":"replace","path":"\/topicSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationList\/title","value":"ConversationList"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationList\/fragments","value":[{"kind":"identifier","text":"ConversationList"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationList\/navigatorTitle","value":[{"kind":"identifier","text":"ConversationList"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationList~1refreshList(infos:)\/title","op":"replace","value":"refreshListWithInfos:"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"refreshListWithInfos:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationList~1refreshList(infos:)\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationList~1appendThenRefresh(infos:)\/title","op":"replace","value":"appendThenRefreshWithInfos:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"appendThenRefreshWithInfos:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationList~1appendThenRefresh(infos:)\/fragments"},{"value":"showNewWithInfo:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationList~1showNew(info:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationList~1showNew(info:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"showNewWithInfo:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationList~1occurError()\/title","op":"replace","value":"occurError"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"occurError"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationList~1occurError()\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationList~1refreshProfiles(infos:)\/title","value":"refreshProfilesWithInfos:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"refreshProfilesWithInfos:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationList~1refreshProfiles(infos:)\/fragments"},{"value":"swipeMenuOperationWithInfo:type:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationList~1swipeMenuOperation(info:type:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"swipeMenuOperationWithInfo:type:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationList~1swipeMenuOperation(info:type:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}