{"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"UITableViewDelegate.tableView(_:leadingSwipeActionsConfigurationForRowAt:)"},{"type":"text","text":"."}],"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationList\/tableView(_:leadingSwipeActionsConfigurationForRowAt:)","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationList","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationList\/UITableViewDelegate-Implementations"]]},"metadata":{"roleHeading":"Instance Method","extendedModule":"ShengwangChatUIKit","externalID":"c:@CM@ShengwangChatUIKit@objc(cs)ConversationList(im)tableView:leadingSwipeActionsConfigurationForRowAtIndexPath:","symbolKind":"method","title":"tableView(_:leadingSwipeActionsConfigurationForRowAt:)","modules":[{"name":"ShengwangChatUIKit"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"tableView","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UITableView","kind":"typeIdentifier","text":"UITableView"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"leadingSwipeActionsConfigurationForRowAt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation9IndexPathV","text":"IndexPath"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"UISwipeActionsConfiguration","preciseIdentifier":"c:objc(cs)UISwipeActionsConfiguration"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"tableView:leadingSwipeActionsConfigurationForRowAtIndexPath:"}],"role":"symbol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","kind":"attribute","text":"MainActor"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"tableView","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"tableView"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UITableView","preciseIdentifier":"c:objc(cs)UITableView"},{"text":", ","kind":"text"},{"text":"leadingSwipeActionsConfigurationForRowAt","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"indexPath"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation9IndexPathV","text":"IndexPath"},{"text":") -> ","kind":"text"},{"text":"UISwipeActionsConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UISwipeActionsConfiguration"},{"text":"?","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/shengwangchatuikit\/conversationlist\/tableview(_:leadingswipeactionsconfigurationforrowat:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/shengwangchatuikit\/conversationlist\/tableview(_:leadingswipeactionsconfigurationforrowat:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ConversationList":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationList","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ConversationList"}],"navigatorTitle":[{"text":"ConversationList","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/conversationlist","role":"symbol","kind":"symbol","title":"ConversationList","abstract":[],"type":"topic"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ConversationList/tableView(_:leadingSwipeActionsConfigurationForRowAt:)":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationList\/tableView(_:leadingSwipeActionsConfigurationForRowAt:)","url":"\/documentation\/shengwangchatuikit\/conversationlist\/tableview(_:leadingswipeactionsconfigurationforrowat:)","kind":"symbol","navigatorTitle":[{"text":"tableView:leadingSwipeActionsConfigurationForRowAtIndexPath:","kind":"identifier"}],"role":"symbol","abstract":[],"title":"tableView(_:leadingSwipeActionsConfigurationForRowAt:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"tableView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UITableView","preciseIdentifier":"c:objc(cs)UITableView","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"leadingSwipeActionsConfigurationForRowAt"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation9IndexPathV","text":"IndexPath"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UISwipeActionsConfiguration","text":"UISwipeActionsConfiguration","kind":"typeIdentifier"},{"kind":"text","text":"?"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ConversationList/UITableViewDelegate-Implementations":{"kind":"article","type":"topic","title":"UITableViewDelegate Implementations","url":"\/documentation\/shengwangchatuikit\/conversationlist\/uitableviewdelegate-implementations","role":"collectionGroup","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationList\/UITableViewDelegate-Implementations","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"tableView:leadingSwipeActionsConfigurationForRowAtIndexPath:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"tableView:leadingSwipeActionsConfigurationForRowAtIndexPath:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:objc(cs)UISwipeActionsConfiguration","text":"UISwipeActionsConfiguration","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"tableView:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UITableView","preciseIdentifier":"c:objc(cs)UITableView"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"tableView"},{"text":" ","kind":"text"},{"text":"leadingSwipeActionsConfigurationForRowAtIndexPath:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSIndexPath","text":"NSIndexPath","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"indexPath","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"value":"ConversationList","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationList\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationList\/fragments","value":[{"kind":"identifier","text":"ConversationList"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationList\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"ConversationList"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationList~1tableView(_:leadingSwipeActionsConfigurationForRowAt:)\/title","op":"replace","value":"tableView:leadingSwipeActionsConfigurationForRowAtIndexPath:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"tableView:leadingSwipeActionsConfigurationForRowAtIndexPath:"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationList~1tableView(_:leadingSwipeActionsConfigurationForRowAt:)\/fragments"}]}]}