{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"tableView"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"tableView","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITableView","text":"UITableView"},{"kind":"text","text":", "},{"text":"cellForRowAt","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"indexPath"},{"text":": ","kind":"text"},{"text":"IndexPath","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:objc(cs)UITableViewCell","kind":"typeIdentifier","text":"UITableViewCell"}]}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationList\/tableView(_:cellForRowAt:)","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Instance Method","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"tableView:cellForRowAtIndexPath:"}],"extendedModule":"ShengwangChatUIKit","externalID":"c:@CM@ShengwangChatUIKit@objc(cs)ConversationList(im)tableView:cellForRowAtIndexPath:","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"tableView","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UITableView","text":"UITableView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"cellForRowAt","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation9IndexPathV","text":"IndexPath"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITableViewCell","text":"UITableViewCell"}],"title":"tableView(_:cellForRowAt:)","modules":[{"name":"ShengwangChatUIKit"}]},"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationList","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationList\/UITableViewDataSource-Implementations"]]},"abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"UITableViewDataSource.tableView(_:cellForRowAt:)"},{"type":"text","text":"."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/conversationlist\/tableview(_:cellforrowat:)"]},{"paths":["\/documentation\/shengwangchatuikit\/conversationlist\/tableview(_:cellforrowat:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ConversationList":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationList","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ConversationList"}],"navigatorTitle":[{"text":"ConversationList","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/conversationlist","role":"symbol","kind":"symbol","title":"ConversationList","abstract":[],"type":"topic"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ConversationList/UITableViewDataSource-Implementations":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationList\/UITableViewDataSource-Implementations","title":"UITableViewDataSource Implementations","abstract":[],"role":"collectionGroup","kind":"article","url":"\/documentation\/shengwangchatuikit\/conversationlist\/uitableviewdatasource-implementations"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ConversationList/tableView(_:cellForRowAt:)":{"url":"\/documentation\/shengwangchatuikit\/conversationlist\/tableview(_:cellforrowat:)","kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationList\/tableView(_:cellForRowAt:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"tableView"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UITableView","kind":"typeIdentifier","text":"UITableView"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"cellForRowAt"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation9IndexPathV","kind":"typeIdentifier","text":"IndexPath"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITableViewCell","text":"UITableViewCell"}],"abstract":[],"title":"tableView(_:cellForRowAt:)","navigatorTitle":[{"text":"tableView:cellForRowAtIndexPath:","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"tableView:cellForRowAtIndexPath:","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"tableView:cellForRowAtIndexPath:"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:objc(cs)UITableViewCell","text":"UITableViewCell","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"tableView:","kind":"identifier"},{"kind":"text","text":"("},{"text":"UITableView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITableView"},{"kind":"text","text":" *) "},{"text":"tableView","kind":"internalParam"},{"kind":"text","text":" "},{"text":"cellForRowAtIndexPath:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSIndexPath","preciseIdentifier":"c:objc(cs)NSIndexPath"},{"text":" *) ","kind":"text"},{"text":"indexPath","kind":"internalParam"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace"},{"op":"replace","value":"ConversationList","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationList\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationList\/fragments","op":"replace","value":[{"text":"ConversationList","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationList\/navigatorTitle","value":[{"text":"ConversationList","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationList~1tableView(_:cellForRowAt:)\/title","value":"tableView:cellForRowAtIndexPath:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationList~1tableView(_:cellForRowAt:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"tableView:cellForRowAtIndexPath:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}