{"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationList\/UIScrollViewDelegate-Implementations"},"metadata":{"role":"collectionGroup","roleHeading":"API Collection","title":"UIScrollViewDelegate Implementations","modules":[{"name":"ShengwangChatUIKit"}]},"kind":"article","sections":[],"topicSections":[{"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationList\/scrollViewDidEndDecelerating(_:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationList\/scrollViewDidEndDragging(_:willDecelerate:)"],"generated":true}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationList"]]},"variants":[{"paths":["\/documentation\/shengwangchatuikit\/conversationlist\/uiscrollviewdelegate-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/conversationlist\/uiscrollviewdelegate-implementations"]}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ConversationList":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationList","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ConversationList"}],"navigatorTitle":[{"text":"ConversationList","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/conversationlist","role":"symbol","kind":"symbol","title":"ConversationList","abstract":[],"type":"topic"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ConversationList/scrollViewDidEndDragging(_:willDecelerate:)":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationList\/scrollViewDidEndDragging(_:willDecelerate:)","abstract":[],"url":"\/documentation\/shengwangchatuikit\/conversationlist\/scrollviewdidenddragging(_:willdecelerate:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"scrollViewDidEndDragging"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIScrollView","text":"UIScrollView"},{"kind":"text","text":", "},{"text":"willDecelerate","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":")"}],"role":"symbol","title":"scrollViewDidEndDragging(_:willDecelerate:)","navigatorTitle":[{"kind":"identifier","text":"scrollViewDidEndDragging:willDecelerate:"}],"kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ConversationList/scrollViewDidEndDecelerating(_:)":{"url":"\/documentation\/shengwangchatuikit\/conversationlist\/scrollviewdidenddecelerating(_:)","navigatorTitle":[{"kind":"identifier","text":"scrollViewDidEndDecelerating:"}],"title":"scrollViewDidEndDecelerating(_:)","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationList\/scrollViewDidEndDecelerating(_:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"scrollViewDidEndDecelerating","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UIScrollView","text":"UIScrollView","kind":"typeIdentifier"},{"kind":"text","text":")"}],"type":"topic","kind":"symbol","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":[{"title":"Instance Methods","generated":true,"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationList\/scrollViewDidEndDecelerating(_:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationList\/scrollViewDidEndDragging(_:willDecelerate:)"],"anchor":"Instance-Methods"}],"path":"\/topicSections","op":"replace"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":"ConversationList","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationList\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationList\/fragments","value":[{"kind":"identifier","text":"ConversationList"}]},{"value":[{"text":"ConversationList","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationList\/navigatorTitle"},{"value":"scrollViewDidEndDragging:willDecelerate:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationList~1scrollViewDidEndDragging(_:willDecelerate:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationList~1scrollViewDidEndDragging(_:willDecelerate:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"scrollViewDidEndDragging:willDecelerate:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationList~1scrollViewDidEndDecelerating(_:)\/title","value":"scrollViewDidEndDecelerating:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationList~1scrollViewDidEndDecelerating(_:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"scrollViewDidEndDecelerating:","kind":"identifier"}]}]}]}