{"kind":"article","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationList\/UITableViewDataSource-Implementations"},"topicSections":[{"generated":true,"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationList\/tableView(_:cellForRowAt:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationList\/tableView(_:numberOfRowsInSection:)"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationList"]]},"metadata":{"title":"UITableViewDataSource Implementations","modules":[{"name":"ShengwangChatUIKit"}],"roleHeading":"API Collection","role":"collectionGroup"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/conversationlist\/uitableviewdatasource-implementations"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/conversationlist\/uitableviewdatasource-implementations"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ConversationList":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationList","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ConversationList"}],"navigatorTitle":[{"text":"ConversationList","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/conversationlist","role":"symbol","kind":"symbol","title":"ConversationList","abstract":[],"type":"topic"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ConversationList/tableView(_:numberOfRowsInSection:)":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationList\/tableView(_:numberOfRowsInSection:)","url":"\/documentation\/shengwangchatuikit\/conversationlist\/tableview(_:numberofrowsinsection:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"tableView","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UITableView","preciseIdentifier":"c:objc(cs)UITableView"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"numberOfRowsInSection"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"abstract":[],"type":"topic","kind":"symbol","navigatorTitle":[{"text":"tableView:numberOfRowsInSection:","kind":"identifier"}],"title":"tableView(_:numberOfRowsInSection:)","role":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ConversationList/tableView(_:cellForRowAt:)":{"url":"\/documentation\/shengwangchatuikit\/conversationlist\/tableview(_:cellforrowat:)","kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationList\/tableView(_:cellForRowAt:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"tableView"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UITableView","kind":"typeIdentifier","text":"UITableView"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"cellForRowAt"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation9IndexPathV","kind":"typeIdentifier","text":"IndexPath"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITableViewCell","text":"UITableViewCell"}],"abstract":[],"title":"tableView(_:cellForRowAt:)","navigatorTitle":[{"text":"tableView:cellForRowAtIndexPath:","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":[{"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationList\/tableView(_:cellForRowAt:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationList\/tableView(_:numberOfRowsInSection:)"],"generated":true,"anchor":"Instance-Methods","title":"Instance Methods"}],"path":"\/topicSections","op":"replace"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":"ConversationList","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationList\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationList\/fragments","value":[{"kind":"identifier","text":"ConversationList"}]},{"value":[{"text":"ConversationList","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationList\/navigatorTitle","op":"replace"},{"op":"replace","value":"tableView:numberOfRowsInSection:","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationList~1tableView(_:numberOfRowsInSection:)\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"tableView:numberOfRowsInSection:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationList~1tableView(_:numberOfRowsInSection:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationList~1tableView(_:cellForRowAt:)\/title","value":"tableView:cellForRowAtIndexPath:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"tableView:cellForRowAtIndexPath:"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationList~1tableView(_:cellForRowAt:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}