{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/SearchHistoryMessagesViewController\/tableView(_:cellForRowAt:)"},"metadata":{"modules":[{"name":"ShengwangChatUIKit"}],"externalID":"c:@M@ShengwangChatUIKit@objc(cs)SearchHistoryMessagesViewController(im)tableView:cellForRowAtIndexPath:","navigatorTitle":[{"kind":"identifier","text":"tableView:cellForRowAtIndexPath:"}],"role":"symbol","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"tableView","kind":"identifier"},{"kind":"text","text":"("},{"text":"UITableView","preciseIdentifier":"c:objc(cs)UITableView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"cellForRowAt"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation9IndexPathV","text":"IndexPath","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:objc(cs)UITableViewCell","text":"UITableViewCell","kind":"typeIdentifier"}],"title":"tableView(_:cellForRowAt:)","roleHeading":"Instance Method"},"kind":"symbol","sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/SearchHistoryMessagesViewController"]]},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"UITableViewDataSource.tableView(_:cellForRowAt:)"},{"type":"text","text":"."}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"tableView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"tableView","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UITableView","text":"UITableView","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cellForRowAt"},{"text":" ","kind":"text"},{"text":"indexPath","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"UITableViewCell","preciseIdentifier":"c:objc(cs)UITableViewCell","kind":"typeIdentifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/shengwangchatuikit\/searchhistorymessagesviewcontroller\/tableview(_:cellforrowat:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/searchhistorymessagesviewcontroller\/tableview(_:cellforrowat:)"]}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/SearchHistoryMessagesViewController":{"title":"SearchHistoryMessagesViewController","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/SearchHistoryMessagesViewController","type":"topic","role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SearchHistoryMessagesViewController","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SearchHistoryMessagesViewController"}],"abstract":[],"url":"\/documentation\/shengwangchatuikit\/searchhistorymessagesviewcontroller"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/SearchHistoryMessagesViewController/tableView(_:cellForRowAt:)":{"navigatorTitle":[{"kind":"identifier","text":"tableView:cellForRowAtIndexPath:"}],"abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"tableView"},{"text":"(","kind":"text"},{"text":"UITableView","preciseIdentifier":"c:objc(cs)UITableView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"cellForRowAt","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"IndexPath","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation9IndexPathV"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITableViewCell","text":"UITableViewCell"}],"type":"topic","kind":"symbol","url":"\/documentation\/shengwangchatuikit\/searchhistorymessagesviewcontroller\/tableview(_:cellforrowat:)","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/SearchHistoryMessagesViewController\/tableView(_:cellForRowAt:)","title":"tableView(_:cellForRowAt:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","value":"tableView:cellForRowAtIndexPath:","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"text":"- ","kind":"text"},{"text":"tableView:cellForRowAtIndexPath:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:objc(cs)UITableViewCell","text":"UITableViewCell","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"tableView:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UITableView","preciseIdentifier":"c:objc(cs)UITableView"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"tableView"},{"kind":"text","text":" "},{"text":"cellForRowAtIndexPath:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSIndexPath","text":"NSIndexPath"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"indexPath"},{"text":";","kind":"text"}]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1SearchHistoryMessagesViewController\/title","op":"replace","value":"SearchHistoryMessagesViewController"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1SearchHistoryMessagesViewController\/fragments","value":[{"text":"SearchHistoryMessagesViewController","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"SearchHistoryMessagesViewController"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1SearchHistoryMessagesViewController\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1SearchHistoryMessagesViewController~1tableView(_:cellForRowAt:)\/title","op":"replace","value":"tableView:cellForRowAtIndexPath:"},{"value":[{"kind":"text","text":"- "},{"text":"tableView:cellForRowAtIndexPath:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1SearchHistoryMessagesViewController~1tableView(_:cellForRowAt:)\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}