{"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"tableView"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"tableView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITableView","preciseIdentifier":"c:objc(cs)UITableView"},{"kind":"text","text":", "},{"text":"numberOfRowsInSection","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"section","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/shengwangchatuikit\/searchhistorymessagesviewcontroller\/tableview(_:numberofrowsinsection:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/shengwangchatuikit\/searchhistorymessagesviewcontroller\/tableview(_:numberofrowsinsection:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"modules":[{"name":"ShengwangChatUIKit"}],"roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"tableView","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITableView","text":"UITableView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"numberOfRowsInSection"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":") -> "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"title":"tableView(_:numberOfRowsInSection:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"tableView:numberOfRowsInSection:"}],"externalID":"c:@M@ShengwangChatUIKit@objc(cs)SearchHistoryMessagesViewController(im)tableView:numberOfRowsInSection:","symbolKind":"method"},"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/SearchHistoryMessagesViewController"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/SearchHistoryMessagesViewController\/tableView(_:numberOfRowsInSection:)"},"abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"UITableViewDataSource.tableView(_:numberOfRowsInSection:)"},{"text":".","type":"text"}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/SearchHistoryMessagesViewController/tableView(_:numberOfRowsInSection:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"tableView","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITableView","text":"UITableView"},{"text":", ","kind":"text"},{"text":"numberOfRowsInSection","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"tableView:numberOfRowsInSection:"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/SearchHistoryMessagesViewController\/tableView(_:numberOfRowsInSection:)","role":"symbol","url":"\/documentation\/shengwangchatuikit\/searchhistorymessagesviewcontroller\/tableview(_:numberofrowsinsection:)","abstract":[],"type":"topic","title":"tableView(_:numberOfRowsInSection:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/SearchHistoryMessagesViewController":{"title":"SearchHistoryMessagesViewController","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/SearchHistoryMessagesViewController","type":"topic","role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SearchHistoryMessagesViewController","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SearchHistoryMessagesViewController"}],"abstract":[],"url":"\/documentation\/shengwangchatuikit\/searchhistorymessagesviewcontroller"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"tableView:numberOfRowsInSection:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"tableView:numberOfRowsInSection:"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"text":") ","kind":"text"},{"kind":"identifier","text":"tableView:"},{"kind":"text","text":"("},{"text":"UITableView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITableView"},{"text":" *) ","kind":"text"},{"text":"tableView","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"numberOfRowsInSection:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"section"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"value":"tableView:numberOfRowsInSection:","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1SearchHistoryMessagesViewController~1tableView(_:numberOfRowsInSection:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1SearchHistoryMessagesViewController~1tableView(_:numberOfRowsInSection:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"tableView:numberOfRowsInSection:"}]},{"value":"SearchHistoryMessagesViewController","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1SearchHistoryMessagesViewController\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SearchHistoryMessagesViewController"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1SearchHistoryMessagesViewController\/fragments"},{"value":[{"text":"SearchHistoryMessagesViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1SearchHistoryMessagesViewController\/navigatorTitle"}]}]}