{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/contactlistheaderitem\/actionclosure"]},{"paths":["\/documentation\/shengwangchatuikit\/contactlistheaderitem\/actionclosure"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"title":"actionClosure","navigatorTitle":[{"kind":"identifier","text":"actionClosure"}],"symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"actionClosure"},{"text":": ","kind":"text"},{"text":"ContactListItemActionClosure","preciseIdentifier":"s:18ShengwangChatUIKit28ContactListItemActionClosurea","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"role":"symbol","modules":[{"name":"ShengwangChatUIKit"}],"externalID":"c:@M@ShengwangChatUIKit@objc(cs)ContactListHeaderItem(py)actionClosure","roleHeading":"Instance Property"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"actionClosure","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ContactListItemActionClosure","kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit28ContactListItemActionClosurea","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactListItemActionClosure"},{"kind":"text","text":"?"}]}]}],"abstract":[{"text":"When the cell clicked,callback.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactListHeaderItem\/actionClosure"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactListHeaderItem"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"kind":"symbol","references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ContactListHeaderItem/actionClosure":{"type":"topic","role":"symbol","title":"actionClosure","kind":"symbol","abstract":[{"text":"When the cell clicked,callback.","type":"text"}],"navigatorTitle":[{"text":"actionClosure","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/contactlistheaderitem\/actionclosure","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactListHeaderItem\/actionClosure","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actionClosure","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit28ContactListItemActionClosurea","text":"ContactListItemActionClosure"},{"text":"?","kind":"text"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ContactListHeaderItem":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ContactListHeaderItem","kind":"identifier"}],"type":"topic","abstract":[],"role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactListHeaderItem","kind":"symbol","title":"ContactListHeaderItem","navigatorTitle":[{"text":"ContactListHeaderItem","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/contactlistheaderitem"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ContactListItemActionClosure":{"title":"ContactListItemActionClosure","navigatorTitle":[{"text":"ContactListItemActionClosure","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/contactlistitemactionclosure","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactListItemActionClosure","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"ContactListItemActionClosure","kind":"identifier"}],"abstract":[],"role":"symbol","kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"actionClosure","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"actionClosure","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":" (^"},{"text":"actionClosure","kind":"identifier"},{"kind":"text","text":")("},{"text":"id<ContactListHeaderItemProtocol>","preciseIdentifier":"c:Qo@M@ShengwangChatUIKit@objc(pl)ContactListHeaderItemProtocol","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"kind":"internalParam","text":""},{"kind":"text","text":");"}]}]}},{"op":"replace","value":"actionClosure","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactListHeaderItem~1actionClosure\/title"},{"value":[{"text":"actionClosure","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactListHeaderItem~1actionClosure\/fragments","op":"replace"},{"value":"ContactListHeaderItem","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactListHeaderItem\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactListHeaderItem\/fragments","value":[{"text":"ContactListHeaderItem","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactListHeaderItem\/navigatorTitle","value":[{"kind":"identifier","text":"ContactListHeaderItem"}]}]}]}