{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/contactlistheaderitem\/init(featureidentify:featurename:featureicon:action:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/contactlistheaderitem\/init(featureidentify:featurename:featureicon:action:)"]}],"metadata":{"modules":[{"name":"ShengwangChatUIKit"}],"symbolKind":"init","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"featureIdentify"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"featureName"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"featureIcon"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"},{"kind":"text","text":"?, "},{"text":"action","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:18ShengwangChatUIKit28ContactListItemActionClosurea","kind":"typeIdentifier","text":"ContactListItemActionClosure"},{"text":")","kind":"text"}],"title":"init(featureIdentify:featureName:featureIcon:action:)","roleHeading":"Initializer","navigatorTitle":[{"kind":"identifier","text":"initWithFeatureIdentify:featureName:featureIcon:action:"}],"externalID":"c:@M@ShengwangChatUIKit@objc(cs)ContactListHeaderItem(im)initWithFeatureIdentify:featureName:featureIcon:action:","role":"symbol"},"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactListHeaderItem"]]},"abstract":[{"type":"text","text":"A convenience initializer for creating an "},{"type":"codeVoice","code":"ContactListItem"},{"type":"text","text":" object ."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactListHeaderItem\/init(featureIdentify:featureName:featureIcon:action:)"},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"text":"featureIdentify","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"featureName"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"featureIcon","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier","text":"UIImage"},{"text":"?, ","kind":"text"},{"text":"action","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" "},{"text":"ContactListItemActionClosure","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactListItemActionClosure","preciseIdentifier":"s:18ShengwangChatUIKit28ContactListItemActionClosurea","kind":"typeIdentifier"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The feature name of the contact header item"}]}],"name":"featureName"},{"name":"featureIcon","content":[{"inlineContent":[{"type":"text","text":"The icon of the contact header item"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"The callback on item clicked."}],"type":"paragraph"}],"name":"action"}],"kind":"parameters"}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ContactListHeaderItem/init(featureIdentify:featureName:featureIcon:action:)":{"role":"symbol","abstract":[{"type":"text","text":"A convenience initializer for creating an "},{"code":"ContactListItem","type":"codeVoice"},{"type":"text","text":" object ."}],"kind":"symbol","title":"init(featureIdentify:featureName:featureIcon:action:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"featureIdentify","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"featureName"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"featureIcon"},{"text":": ","kind":"text"},{"text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"action"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ContactListItemActionClosure","preciseIdentifier":"s:18ShengwangChatUIKit28ContactListItemActionClosurea"},{"kind":"text","text":")"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactListHeaderItem\/init(featureIdentify:featureName:featureIcon:action:)","navigatorTitle":[{"kind":"identifier","text":"initWithFeatureIdentify:featureName:featureIcon:action:"}],"type":"topic","url":"\/documentation\/shengwangchatuikit\/contactlistheaderitem\/init(featureidentify:featurename:featureicon:action:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ContactListHeaderItem":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ContactListHeaderItem","kind":"identifier"}],"type":"topic","abstract":[],"role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactListHeaderItem","kind":"symbol","title":"ContactListHeaderItem","navigatorTitle":[{"text":"ContactListHeaderItem","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/contactlistheaderitem"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ContactListItemActionClosure":{"title":"ContactListItemActionClosure","navigatorTitle":[{"text":"ContactListItemActionClosure","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/contactlistitemactionclosure","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactListItemActionClosure","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"ContactListItemActionClosure","kind":"identifier"}],"abstract":[],"role":"symbol","kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"initWithFeatureIdentify:featureName:featureIcon:action:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithFeatureIdentify:featureName:featureIcon:action:","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithFeatureIdentify:"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"featureIdentify"},{"text":" ","kind":"text"},{"text":"featureName:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"featureName","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"featureIcon:"},{"kind":"text","text":"("},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"text":" *) ","kind":"text"},{"text":"featureIcon","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"action:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":" (^","kind":"text"},{"kind":"text","text":")("},{"preciseIdentifier":"c:Qo@M@ShengwangChatUIKit@objc(pl)ContactListHeaderItemProtocol","kind":"typeIdentifier","text":"id<ContactListHeaderItemProtocol>"},{"text":" ","kind":"text"},{"kind":"internalParam","text":""},{"text":")) ","kind":"text"},{"kind":"internalParam","text":"action"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/primaryContentSections\/1","op":"replace","value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The feature name of the contact header item"}]}],"name":"featureName"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The icon of the contact header item"}]}],"name":"featureIcon"},{"name":"action","content":[{"inlineContent":[{"text":"The callback on item clicked.","type":"text"}],"type":"paragraph"}]}]}},{"value":"initWithFeatureIdentify:featureName:featureIcon:action:","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactListHeaderItem~1init(featureIdentify:featureName:featureIcon:action:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactListHeaderItem~1init(featureIdentify:featureName:featureIcon:action:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithFeatureIdentify:featureName:featureIcon:action:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactListHeaderItem\/title","op":"replace","value":"ContactListHeaderItem"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactListHeaderItem\/fragments","value":[{"text":"ContactListHeaderItem","kind":"identifier"}]},{"op":"replace","value":[{"text":"ContactListHeaderItem","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactListHeaderItem\/navigatorTitle"}]}]}