{"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/groupinfoeditviewcontroller\/initwithnibname:bundle:"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupInfoEditViewController"]]},"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:*Qo","kind":"typeIdentifier","text":"id"},{"kind":"text","text":") "},{"text":"initWithNibName:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"nibNameOrNil"},{"text":" ","kind":"text"},{"text":"bundle:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSBundle","kind":"typeIdentifier","text":"NSBundle"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"nibBundleOrNil"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupInfoEditViewController\/initWithNibName:bundle:"},"sections":[],"metadata":{"externalID":"c:@M@ShengwangChatUIKit@objc(cs)GroupInfoEditViewController(im)initWithNibName:bundle:","roleHeading":"Instance Method","modules":[{"name":"ShengwangChatUIKit"}],"title":"initWithNibName:bundle:","role":"symbol","symbolKind":"method","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithNibName:bundle:"}],"navigatorTitle":[{"text":"initWithNibName:bundle:","kind":"identifier"}]},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/GroupInfoEditViewController/initWithNibName:bundle:":{"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"initWithNibName:bundle:"}],"fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithNibName:bundle:"}],"title":"initWithNibName:bundle:","role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupInfoEditViewController\/initWithNibName:bundle:","url":"\/documentation\/shengwangchatuikit\/groupinfoeditviewcontroller\/initwithnibname:bundle:"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/GroupInfoEditViewController":{"navigatorTitle":[{"kind":"identifier","text":"GroupInfoEditViewController"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GroupInfoEditViewController"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupInfoEditViewController","kind":"symbol","url":"\/documentation\/shengwangchatuikit\/groupinfoeditviewcontroller","title":"GroupInfoEditViewController","abstract":[],"type":"topic","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupInfoEditViewController\/title","value":"GroupInfoEditViewController","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupInfoEditViewController\/fragments","value":[{"kind":"identifier","text":"GroupInfoEditViewController"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupInfoEditViewController\/navigatorTitle","op":"replace","value":[{"text":"GroupInfoEditViewController","kind":"identifier"}]}]}]}