{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupInfoEditViewController","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupInfoEditViewController\/UITextViewDelegate-Implementations"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupInfoEditViewController\/textViewDidChange(_:)"},"abstract":[{"text":"Inherited from ","type":"text"},{"code":"UITextViewDelegate.textViewDidChange(_:)","type":"codeVoice"},{"type":"text","text":"."}],"metadata":{"extendedModule":"ShengwangChatUIKit","role":"symbol","modules":[{"name":"ShengwangChatUIKit"}],"externalID":"c:@CM@ShengwangChatUIKit@objc(cs)GroupInfoEditViewController(im)textViewDidChange:","roleHeading":"Instance Method","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"textViewDidChange","kind":"identifier"},{"kind":"text","text":"("},{"text":"UITextView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITextView"},{"kind":"text","text":")"}],"title":"textViewDidChange(_:)","navigatorTitle":[{"text":"textViewDidChange:","kind":"identifier"}]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"textViewDidChange","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"textView","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITextView","text":"UITextView"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/shengwangchatuikit\/groupinfoeditviewcontroller\/textviewdidchange(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/groupinfoeditviewcontroller\/textviewdidchange(_:)"]}],"sections":[],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/GroupInfoEditViewController/textViewDidChange(_:)":{"role":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"textViewDidChange"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UITextView","kind":"typeIdentifier","text":"UITextView"},{"kind":"text","text":")"}],"kind":"symbol","abstract":[],"url":"\/documentation\/shengwangchatuikit\/groupinfoeditviewcontroller\/textviewdidchange(_:)","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupInfoEditViewController\/textViewDidChange(_:)","title":"textViewDidChange(_:)","navigatorTitle":[{"text":"textViewDidChange:","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/GroupInfoEditViewController":{"navigatorTitle":[{"kind":"identifier","text":"GroupInfoEditViewController"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GroupInfoEditViewController"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupInfoEditViewController","kind":"symbol","url":"\/documentation\/shengwangchatuikit\/groupinfoeditviewcontroller","title":"GroupInfoEditViewController","abstract":[],"type":"topic","role":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/GroupInfoEditViewController/UITextViewDelegate-Implementations":{"abstract":[],"title":"UITextViewDelegate Implementations","role":"collectionGroup","kind":"article","type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupInfoEditViewController\/UITextViewDelegate-Implementations","url":"\/documentation\/shengwangchatuikit\/groupinfoeditviewcontroller\/uitextviewdelegate-implementations"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"value":"textViewDidChange:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"textViewDidChange:","kind":"identifier"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"textViewDidChange:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITextView","text":"UITextView"},{"text":" *) ","kind":"text"},{"text":"textView","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"textViewDidChange:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupInfoEditViewController~1textViewDidChange(_:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"textViewDidChange:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupInfoEditViewController~1textViewDidChange(_:)\/fragments"},{"value":"GroupInfoEditViewController","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupInfoEditViewController\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupInfoEditViewController\/fragments","value":[{"text":"GroupInfoEditViewController","kind":"identifier"}]},{"op":"replace","value":[{"text":"GroupInfoEditViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupInfoEditViewController\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}