{"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"paths":["\/documentation\/shengwangchatuikit\/groupinfoeditviewcontroller\/textview(_:shouldchangetextin:replacementtext:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/shengwangchatuikit\/groupinfoeditviewcontroller\/textview(_:shouldchangetextin:replacementtext:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupInfoEditViewController\/textView(_:shouldChangeTextIn:replacementText:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupInfoEditViewController","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupInfoEditViewController\/UITextViewDelegate-Implementations"]]},"kind":"symbol","metadata":{"roleHeading":"Instance Method","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"textView"},{"text":"(","kind":"text"},{"text":"UITextView","preciseIdentifier":"c:objc(cs)UITextView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"shouldChangeTextIn"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSRange","kind":"typeIdentifier","text":"NSRange"},{"kind":"text","text":", "},{"text":"replacementText","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"modules":[{"name":"ShengwangChatUIKit"}],"extendedModule":"ShengwangChatUIKit","navigatorTitle":[{"kind":"identifier","text":"textView:shouldChangeTextInRange:replacementText:"}],"title":"textView(_:shouldChangeTextIn:replacementText:)","externalID":"c:@CM@ShengwangChatUIKit@objc(cs)GroupInfoEditViewController(im)textView:shouldChangeTextInRange:replacementText:","symbolKind":"method"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"textView","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"textView"},{"text":": ","kind":"text"},{"text":"UITextView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITextView"},{"kind":"text","text":", "},{"text":"shouldChangeTextIn","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"range"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSRange","text":"NSRange","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"replacementText","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"text"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"abstract":[{"type":"text","text":"Inherited from "},{"code":"UITextViewDelegate.textView(_:shouldChangeTextIn:replacementText:)","type":"codeVoice"},{"text":".","type":"text"}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/GroupInfoEditViewController/textView(_:shouldChangeTextIn:replacementText:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"textView","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UITextView","text":"UITextView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"shouldChangeTextIn"},{"text":": ","kind":"text"},{"text":"NSRange","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSRange"},{"kind":"text","text":", "},{"text":"replacementText","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"type":"topic","role":"symbol","abstract":[],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"textView:shouldChangeTextInRange:replacementText:"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupInfoEditViewController\/textView(_:shouldChangeTextIn:replacementText:)","url":"\/documentation\/shengwangchatuikit\/groupinfoeditviewcontroller\/textview(_:shouldchangetextin:replacementtext:)","title":"textView(_:shouldChangeTextIn:replacementText:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/GroupInfoEditViewController":{"navigatorTitle":[{"kind":"identifier","text":"GroupInfoEditViewController"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GroupInfoEditViewController"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupInfoEditViewController","kind":"symbol","url":"\/documentation\/shengwangchatuikit\/groupinfoeditviewcontroller","title":"GroupInfoEditViewController","abstract":[],"type":"topic","role":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/GroupInfoEditViewController/UITextViewDelegate-Implementations":{"abstract":[],"title":"UITextViewDelegate Implementations","role":"collectionGroup","kind":"article","type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupInfoEditViewController\/UITextViewDelegate-Implementations","url":"\/documentation\/shengwangchatuikit\/groupinfoeditviewcontroller\/uitextviewdelegate-implementations"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"textView:shouldChangeTextInRange:replacementText:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"textView:shouldChangeTextInRange:replacementText:"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"textView:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UITextView","kind":"typeIdentifier","text":"UITextView"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"textView"},{"text":" ","kind":"text"},{"text":"shouldChangeTextInRange:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@S@_NSRange","kind":"typeIdentifier","text":"NSRange"},{"kind":"text","text":") "},{"kind":"internalParam","text":"range"},{"text":" ","kind":"text"},{"text":"replacementText:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"text"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupInfoEditViewController~1textView(_:shouldChangeTextIn:replacementText:)\/title","op":"replace","value":"textView:shouldChangeTextInRange:replacementText:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"textView:shouldChangeTextInRange:replacementText:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupInfoEditViewController~1textView(_:shouldChangeTextIn:replacementText:)\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupInfoEditViewController\/title","value":"GroupInfoEditViewController","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupInfoEditViewController\/fragments","value":[{"text":"GroupInfoEditViewController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupInfoEditViewController\/navigatorTitle","op":"replace","value":[{"text":"GroupInfoEditViewController","kind":"identifier"}]}]}]}