{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatResponseListener"]]},"metadata":{"modules":[{"name":"ShengwangChatUIKit"}],"symbolKind":"method","required":true,"title":"messagesAlreadyRead(conversationId:)","role":"symbol","externalID":"c:@M@ShengwangChatUIKit@objc(pl)ChatResponseListener(im)messagesAlreadyReadWithConversationId:","roleHeading":"Instance Method","navigatorTitle":[{"text":"messagesAlreadyReadWithConversationId:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"messagesAlreadyRead"},{"text":"(","kind":"text"},{"text":"conversationId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"messagesAlreadyRead"},{"text":"(","kind":"text"},{"text":"conversationId","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The ID of the conversation.","type":"text"}]}],"name":"conversationId"}],"kind":"parameters"}],"kind":"symbol","abstract":[{"text":"Update messages read state on received channel ack.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/chatresponselistener\/messagesalreadyread(conversationid:)"]},{"paths":["\/documentation\/shengwangchatuikit\/chatresponselistener\/messagesalreadyread(conversationid:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatResponseListener\/messagesAlreadyRead(conversationId:)"},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatResponseListener":{"abstract":[],"url":"\/documentation\/shengwangchatuikit\/chatresponselistener","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChatResponseListener"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatResponseListener","role":"symbol","navigatorTitle":[{"text":"ChatResponseListener","kind":"identifier"}],"title":"ChatResponseListener"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatResponseListener/messagesAlreadyRead(conversationId:)":{"role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Update messages read state on received channel ack."}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"messagesAlreadyRead"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"conversationId"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":")","kind":"text"}],"title":"messagesAlreadyRead(conversationId:)","type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatResponseListener\/messagesAlreadyRead(conversationId:)","required":true,"url":"\/documentation\/shengwangchatuikit\/chatresponselistener\/messagesalreadyread(conversationid:)","navigatorTitle":[{"kind":"identifier","text":"messagesAlreadyReadWithConversationId:"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","value":"messagesAlreadyReadWithConversationId:","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"messagesAlreadyReadWithConversationId:"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"text":"messagesAlreadyReadWithConversationId:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"text":"conversationId","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The ID of the conversation."}]}],"name":"conversationId"}]},"op":"replace","path":"\/primaryContentSections\/1"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatResponseListener\/title","value":"ChatResponseListener","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatResponseListener\/fragments","value":[{"text":"ChatResponseListener","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatResponseListener\/navigatorTitle","value":[{"kind":"identifier","text":"ChatResponseListener"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatResponseListener~1messagesAlreadyRead(conversationId:)\/title","op":"replace","value":"messagesAlreadyReadWithConversationId:"},{"value":[{"kind":"text","text":"- "},{"text":"messagesAlreadyReadWithConversationId:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatResponseListener~1messagesAlreadyRead(conversationId:)\/fragments","op":"replace"}]}]}