{"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatResponseListener\/onMessageDidEdited(message:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"When message edited."}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onMessageDidEdited"},{"kind":"text","text":"("},{"text":"message","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ChatMessage","preciseIdentifier":"s:18ShengwangChatUIKit0B7Messagea","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatMessage"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"name":"message","content":[{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatMessage"}]}]}],"kind":"parameters"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatResponseListener"]]},"sections":[],"metadata":{"externalID":"c:@M@ShengwangChatUIKit@objc(pl)ChatResponseListener(im)onMessageDidEditedWithMessage:","navigatorTitle":[{"kind":"identifier","text":"onMessageDidEditedWithMessage:"}],"role":"symbol","required":true,"modules":[{"name":"ShengwangChatUIKit"}],"title":"onMessageDidEdited(message:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onMessageDidEdited"},{"text":"(","kind":"text"},{"text":"message","kind":"externalParam"},{"kind":"text","text":": "},{"text":"ChatMessage","kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit0B7Messagea"},{"text":")","kind":"text"}],"roleHeading":"Instance Method","symbolKind":"method"},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/chatresponselistener\/onmessagedidedited(message:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/chatresponselistener\/onmessagedidedited(message:)"]}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatResponseListener":{"abstract":[],"url":"\/documentation\/shengwangchatuikit\/chatresponselistener","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChatResponseListener"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatResponseListener","role":"symbol","navigatorTitle":[{"text":"ChatResponseListener","kind":"identifier"}],"title":"ChatResponseListener"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatResponseListener/onMessageDidEdited(message:)":{"required":true,"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatResponseListener\/onMessageDidEdited(message:)","url":"\/documentation\/shengwangchatuikit\/chatresponselistener\/onmessagedidedited(message:)","abstract":[{"text":"When message edited.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"onMessageDidEdited"},{"kind":"text","text":"("},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"text":"ChatMessage","kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit0B7Messagea"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"onMessageDidEditedWithMessage:","kind":"identifier"}],"title":"onMessageDidEdited(message:)","role":"symbol","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatMessage":{"url":"\/documentation\/shengwangchatuikit\/chatmessage","abstract":[],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ChatMessage"}],"type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatMessage","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChatMessage"}],"title":"ChatMessage"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","value":"onMessageDidEditedWithMessage:","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"onMessageDidEditedWithMessage:","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"onMessageDidEditedWithMessage:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"AgoraChatMessage","preciseIdentifier":"c:objc(cs)AgoraChatMessage"},{"kind":"text","text":" *) "},{"text":"message","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/primaryContentSections\/1","op":"replace","value":{"kind":"parameters","parameters":[{"name":"message","content":[{"inlineContent":[{"type":"text","text":""},{"type":"reference","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatMessage","isActive":true}],"type":"paragraph"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatResponseListener\/title","value":"ChatResponseListener"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatResponseListener\/fragments","op":"replace","value":[{"text":"ChatResponseListener","kind":"identifier"}]},{"value":[{"text":"ChatResponseListener","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatResponseListener\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatResponseListener~1onMessageDidEdited(message:)\/title","value":"onMessageDidEditedWithMessage:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatResponseListener~1onMessageDidEdited(message:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"onMessageDidEditedWithMessage:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}