{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/chatresponselistener\/onmessagestickiedtop(conversationid:messageid:operation:info:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/chatresponselistener\/onmessagestickiedtop(conversationid:messageid:operation:info:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatResponseListener\/onMessageStickiedTop(conversationId:messageId:operation:info:)"},"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"onMessageStickiedTop","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"conversationId"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"messageId"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"operation","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:18ShengwangChatUIKit19MessagePinOperationa","text":"MessagePinOperation","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"info","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit14MessagePinInfoa","text":"MessagePinInfo"},{"kind":"text","text":")"}],"roleHeading":"Instance Method","modules":[{"name":"ShengwangChatUIKit"}],"symbolKind":"method","role":"symbol","externalID":"c:@M@ShengwangChatUIKit@objc(pl)ChatResponseListener(im)onMessageStickiedTopWithConversationId:messageId:operation:info:","title":"onMessageStickiedTop(conversationId:messageId:operation:info:)","required":true,"navigatorTitle":[{"kind":"identifier","text":"onMessageStickiedTopWithConversationId:messageId:operation:info:"}]},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatResponseListener"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onMessageStickiedTop"},{"text":"(","kind":"text"},{"text":"conversationId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"messageId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"text":"operation","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit19MessagePinOperationa","text":"MessagePinOperation","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessagePinOperation"},{"text":", ","kind":"text"},{"text":"info","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:18ShengwangChatUIKit14MessagePinInfoa","text":"MessagePinInfo","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessagePinInfo","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"]}]},{"parameters":[{"content":[{"inlineContent":[{"text":"ID of the conversation","type":"text"}],"type":"paragraph"}],"name":"conversationId"},{"name":"messageId","content":[{"inlineContent":[{"type":"text","text":"ID of the message."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":""},{"isActive":true,"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessagePinOperation","type":"reference"}],"type":"paragraph"}],"name":"operation"},{"name":"info","content":[{"inlineContent":[{"text":"","type":"text"},{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessagePinInfo","type":"reference","isActive":true}],"type":"paragraph"}]}],"kind":"parameters"}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"text":"When message stickied top the method called.","type":"text"}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatResponseListener/onMessageStickiedTop(conversationId:messageId:operation:info:)":{"required":true,"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatResponseListener\/onMessageStickiedTop(conversationId:messageId:operation:info:)","url":"\/documentation\/shengwangchatuikit\/chatresponselistener\/onmessagestickiedtop(conversationid:messageid:operation:info:)","abstract":[{"type":"text","text":"When message stickied top the method called."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onMessageStickiedTop"},{"kind":"text","text":"("},{"text":"conversationId","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"messageId","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"operation"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit19MessagePinOperationa","text":"MessagePinOperation"},{"kind":"text","text":", "},{"kind":"externalParam","text":"info"},{"kind":"text","text":": "},{"preciseIdentifier":"s:18ShengwangChatUIKit14MessagePinInfoa","kind":"typeIdentifier","text":"MessagePinInfo"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"onMessageStickiedTopWithConversationId:messageId:operation:info:"}],"title":"onMessageStickiedTop(conversationId:messageId:operation:info:)","role":"symbol","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatResponseListener":{"abstract":[],"url":"\/documentation\/shengwangchatuikit\/chatresponselistener","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChatResponseListener"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatResponseListener","role":"symbol","navigatorTitle":[{"text":"ChatResponseListener","kind":"identifier"}],"title":"ChatResponseListener"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessagePinOperation":{"type":"topic","navigatorTitle":[{"text":"MessagePinOperation","kind":"identifier"}],"title":"MessagePinOperation","role":"symbol","kind":"symbol","url":"\/documentation\/shengwangchatuikit\/messagepinoperation","abstract":[],"fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"MessagePinOperation","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessagePinOperation"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessagePinInfo":{"type":"topic","navigatorTitle":[{"text":"MessagePinInfo","kind":"identifier"}],"title":"MessagePinInfo","role":"symbol","kind":"symbol","url":"\/documentation\/shengwangchatuikit\/messagepininfo","abstract":[],"fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessagePinInfo"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessagePinInfo"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"onMessageStickiedTopWithConversationId:messageId:operation:info:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"onMessageStickiedTopWithConversationId:messageId:operation:info:","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"onMessageStickiedTopWithConversationId:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"conversationId","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"messageId:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"messageId","kind":"internalParam"},{"kind":"text","text":" "},{"text":"operation:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"AgoraChatMessagePinOperation","kind":"typeIdentifier","preciseIdentifier":"c:@E@AgoraChatMessagePinOperation"},{"text":") ","kind":"text"},{"text":"operation","kind":"internalParam"},{"kind":"text","text":" "},{"text":"info:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"AgoraChatMessagePinInfo","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AgoraChatMessagePinInfo"},{"text":" *) ","kind":"text"},{"text":"info","kind":"internalParam"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"kind":"parameters","parameters":[{"name":"conversationId","content":[{"inlineContent":[{"text":"ID of the conversation","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"ID of the message."}]}],"name":"messageId"},{"name":"operation","content":[{"inlineContent":[{"type":"text","text":""},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessagePinOperation"}],"type":"paragraph"}]},{"name":"info","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessagePinInfo"}]}]}]},"path":"\/primaryContentSections\/1","op":"replace"},{"value":"onMessageStickiedTopWithConversationId:messageId:operation:info:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatResponseListener~1onMessageStickiedTop(conversationId:messageId:operation:info:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"onMessageStickiedTopWithConversationId:messageId:operation:info:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatResponseListener~1onMessageStickiedTop(conversationId:messageId:operation:info:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatResponseListener\/title","value":"ChatResponseListener"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatResponseListener\/fragments","value":[{"text":"ChatResponseListener","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"ChatResponseListener"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatResponseListener\/navigatorTitle"}]}]}