{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"onMessageStatusDidChanged","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"message"},{"text":": ","kind":"text"},{"text":"ChatMessage","kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit0B7Messagea","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatMessage"},{"text":", ","kind":"text"},{"text":"status","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatMessageStatus","preciseIdentifier":"c:@M@ShengwangChatUIKit@E@ChatMessageStatus","text":"ChatMessageStatus"},{"kind":"text","text":", "},{"text":"error","kind":"externalParam"},{"kind":"text","text":": "},{"text":"ChatError","kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit0B5Errora","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatError"},{"kind":"text","text":"?)"}],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"name":"message","content":[{"inlineContent":[{"type":"text","text":""},{"isActive":true,"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatMessage","type":"reference"}],"type":"paragraph"}]},{"name":"status","content":[{"inlineContent":[{"type":"text","text":""},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatMessageStatus"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"","type":"text"},{"isActive":true,"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatError","type":"reference"}],"type":"paragraph"}],"name":"error"}],"kind":"parameters"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/chatresponselistener\/onmessagestatusdidchanged(message:status:error:)"]},{"paths":["\/documentation\/shengwangchatuikit\/chatresponselistener\/onmessagestatusdidchanged(message:status:error:)"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"When status of message changed.","type":"text"}],"sections":[],"metadata":{"symbolKind":"method","roleHeading":"Instance Method","title":"onMessageStatusDidChanged(message:status:error:)","navigatorTitle":[{"kind":"identifier","text":"onMessageStatusDidChangedWithMessage:status:error:"}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onMessageStatusDidChanged"},{"text":"(","kind":"text"},{"text":"message","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ChatMessage","preciseIdentifier":"s:18ShengwangChatUIKit0B7Messagea","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"status","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ChatMessageStatus","kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@E@ChatMessageStatus"},{"kind":"text","text":", "},{"text":"error","kind":"externalParam"},{"kind":"text","text":": "},{"text":"ChatError","kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit0B5Errora"},{"text":"?)","kind":"text"}],"externalID":"c:@M@ShengwangChatUIKit@objc(pl)ChatResponseListener(im)onMessageStatusDidChangedWithMessage:status:error:","modules":[{"name":"ShengwangChatUIKit"}],"required":true},"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatResponseListener"]]},"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatResponseListener\/onMessageStatusDidChanged(message:status:error:)","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatMessage":{"url":"\/documentation\/shengwangchatuikit\/chatmessage","abstract":[],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ChatMessage"}],"type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatMessage","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChatMessage"}],"title":"ChatMessage"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatMessageStatus":{"title":"ChatMessageStatus","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChatMessageStatus"}],"url":"\/documentation\/shengwangchatuikit\/chatmessagestatus","role":"symbol","abstract":[{"text":"The status of ","type":"text"},{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatMessage","type":"reference","isActive":true},{"type":"text","text":"."}],"type":"topic","navigatorTitle":[{"text":"ChatMessageStatus","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatMessageStatus"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatResponseListener":{"abstract":[],"url":"\/documentation\/shengwangchatuikit\/chatresponselistener","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChatResponseListener"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatResponseListener","role":"symbol","navigatorTitle":[{"text":"ChatResponseListener","kind":"identifier"}],"title":"ChatResponseListener"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatError":{"fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChatError"}],"role":"symbol","navigatorTitle":[{"text":"ChatError","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatError","url":"\/documentation\/shengwangchatuikit\/chaterror","title":"ChatError","kind":"symbol","abstract":[]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatResponseListener/onMessageStatusDidChanged(message:status:error:)":{"kind":"symbol","required":true,"title":"onMessageStatusDidChanged(message:status:error:)","navigatorTitle":[{"kind":"identifier","text":"onMessageStatusDidChangedWithMessage:status:error:"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatResponseListener\/onMessageStatusDidChanged(message:status:error:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"onMessageStatusDidChanged","kind":"identifier"},{"kind":"text","text":"("},{"text":"message","kind":"externalParam"},{"kind":"text","text":": "},{"text":"ChatMessage","kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit0B7Messagea"},{"text":", ","kind":"text"},{"text":"status","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ChatMessageStatus","preciseIdentifier":"c:@M@ShengwangChatUIKit@E@ChatMessageStatus","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"error","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit0B5Errora","text":"ChatError"},{"text":"?)","kind":"text"}],"type":"topic","url":"\/documentation\/shengwangchatuikit\/chatresponselistener\/onmessagestatusdidchanged(message:status:error:)","abstract":[{"text":"When status of message changed.","type":"text"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"onMessageStatusDidChangedWithMessage:status:error:","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"onMessageStatusDidChangedWithMessage:status:error:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"onMessageStatusDidChangedWithMessage:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AgoraChatMessage","text":"AgoraChatMessage"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"message"},{"text":" ","kind":"text"},{"kind":"identifier","text":"status:"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"ChatMessageStatus","kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@E@ChatMessageStatus","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatMessageStatus"},{"kind":"text","text":") "},{"kind":"internalParam","text":"status"},{"kind":"text","text":" "},{"text":"error:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"AgoraChatError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AgoraChatError"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"error"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}},{"value":{"kind":"parameters","parameters":[{"name":"message","content":[{"inlineContent":[{"type":"text","text":""},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatMessage"}],"type":"paragraph"}]},{"name":"status","content":[{"inlineContent":[{"type":"text","text":""},{"isActive":true,"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatMessageStatus","type":"reference"}],"type":"paragraph"}]},{"name":"error","content":[{"inlineContent":[{"text":"","type":"text"},{"type":"reference","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatError","isActive":true}],"type":"paragraph"}]}]},"path":"\/primaryContentSections\/1","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatMessageStatus\/title","op":"replace","value":"ChatMessageStatus"},{"value":[{"text":"ChatMessageStatus","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatMessageStatus\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"ChatMessageStatus"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatMessageStatus\/navigatorTitle"},{"op":"replace","value":"ChatResponseListener","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatResponseListener\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatResponseListener\/fragments","op":"replace","value":[{"text":"ChatResponseListener","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatResponseListener\/navigatorTitle","value":[{"kind":"identifier","text":"ChatResponseListener"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatResponseListener~1onMessageStatusDidChanged(message:status:error:)\/title","op":"replace","value":"onMessageStatusDidChangedWithMessage:status:error:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"onMessageStatusDidChangedWithMessage:status:error:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatResponseListener~1onMessageStatusDidChanged(message:status:error:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}