{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/chatresponselistener\/onmessagedidrecalled(recallinfo:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/chatresponselistener\/onmessagedidrecalled(recallinfo:)"]}],"metadata":{"roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"onMessageDidRecalled"},{"text":"(","kind":"text"},{"text":"recallInfo","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:18ShengwangChatUIKit10RecallInfoa","text":"RecallInfo","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"onMessageDidRecalledWithRecallInfo:"}],"modules":[{"name":"ShengwangChatUIKit"}],"externalID":"c:@M@ShengwangChatUIKit@objc(pl)ChatResponseListener(im)onMessageDidRecalledWithRecallInfo:","required":true,"symbolKind":"method","title":"onMessageDidRecalled(recallInfo:)","role":"symbol"},"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatResponseListener"]]},"abstract":[{"text":"When message recalled.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatResponseListener\/onMessageDidRecalled(recallInfo:)"},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"onMessageDidRecalled"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"recallInfo"},{"kind":"text","text":": "},{"text":"RecallInfo","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/RecallInfo","preciseIdentifier":"s:18ShengwangChatUIKit10RecallInfoa","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"name":"recallInfo","content":[{"inlineContent":[{"type":"text","text":""},{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatMessage","type":"reference","isActive":true}],"type":"paragraph"}]}],"kind":"parameters"}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatMessage":{"url":"\/documentation\/shengwangchatuikit\/chatmessage","abstract":[],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ChatMessage"}],"type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatMessage","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChatMessage"}],"title":"ChatMessage"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatResponseListener/onMessageDidRecalled(recallInfo:)":{"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onMessageDidRecalled"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"recallInfo"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"RecallInfo","preciseIdentifier":"s:18ShengwangChatUIKit10RecallInfoa"},{"text":")","kind":"text"}],"url":"\/documentation\/shengwangchatuikit\/chatresponselistener\/onmessagedidrecalled(recallinfo:)","required":true,"navigatorTitle":[{"text":"onMessageDidRecalledWithRecallInfo:","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatResponseListener\/onMessageDidRecalled(recallInfo:)","abstract":[{"type":"text","text":"When message recalled."}],"kind":"symbol","type":"topic","title":"onMessageDidRecalled(recallInfo:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatResponseListener":{"abstract":[],"url":"\/documentation\/shengwangchatuikit\/chatresponselistener","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChatResponseListener"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatResponseListener","role":"symbol","navigatorTitle":[{"text":"ChatResponseListener","kind":"identifier"}],"title":"ChatResponseListener"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/RecallInfo":{"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"text":"RecallInfo","kind":"identifier"}],"title":"RecallInfo","abstract":[],"type":"topic","kind":"symbol","url":"\/documentation\/shengwangchatuikit\/recallinfo","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/RecallInfo","navigatorTitle":[{"text":"RecallInfo","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"value":"onMessageDidRecalledWithRecallInfo:","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"onMessageDidRecalledWithRecallInfo:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"onMessageDidRecalledWithRecallInfo:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraChatRecallMessageInfo","preciseIdentifier":"c:objc(cs)AgoraChatRecallMessageInfo"},{"text":" *) ","kind":"text"},{"text":"recallInfo","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"recallInfo","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatMessage","type":"reference","isActive":true}]}]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatResponseListener~1onMessageDidRecalled(recallInfo:)\/title","value":"onMessageDidRecalledWithRecallInfo:"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatResponseListener~1onMessageDidRecalled(recallInfo:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"onMessageDidRecalledWithRecallInfo:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatResponseListener\/title","value":"ChatResponseListener"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatResponseListener\/fragments","op":"replace","value":[{"kind":"identifier","text":"ChatResponseListener"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatResponseListener\/navigatorTitle","op":"replace","value":[{"text":"ChatResponseListener","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}