{"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewModel\/bindDriver(driver:create:)"},"abstract":[{"text":"Bind ","type":"text"},{"isActive":true,"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/IMessageListViewDriver","type":"reference"}],"metadata":{"modules":[{"name":"ShengwangChatUIKit"}],"symbolKind":"method","title":"bindDriver(driver:create:)","role":"symbol","externalID":"c:@M@ShengwangChatUIKit@objc(cs)ChatThreadViewModel(im)bindWithDriver:create:","roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"bindWithDriver:create:"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"bindDriver","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"driver"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(pl)IMessageListViewDriver","text":"IMessageListViewDriver"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"create"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":")"}]},"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewModel"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/chatthreadviewmodel\/binddriver(driver:create:)"]},{"paths":["\/documentation\/shengwangchatuikit\/chatthreadviewmodel\/binddriver(driver:create:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(bindWithDriver:create:) "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"bindDriver","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"driver"},{"kind":"text","text":": "},{"text":"IMessageListViewDriver","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(pl)IMessageListViewDriver","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/IMessageListViewDriver"},{"text":", ","kind":"text"},{"text":"create","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":""},{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/IMessageListViewDriver","isActive":true,"type":"reference"}],"type":"paragraph"}],"name":"driver"},{"name":"create","content":[{"inlineContent":[{"type":"text","text":"Whether to create a new thread"}],"type":"paragraph"}]}]}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/IMessageListViewDriver":{"kind":"symbol","role":"symbol","type":"topic","abstract":[],"navigatorTitle":[{"text":"IMessageListViewDriver","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"IMessageListViewDriver","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/imessagelistviewdriver","title":"IMessageListViewDriver","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/IMessageListViewDriver"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatThreadViewModel":{"navigatorTitle":[{"text":"ChatThreadViewModel","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewModel","url":"\/documentation\/shengwangchatuikit\/chatthreadviewmodel","abstract":[],"role":"symbol","kind":"symbol","type":"topic","title":"ChatThreadViewModel","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChatThreadViewModel","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatThreadViewModel/bindDriver(driver:create:)":{"abstract":[{"type":"text","text":"Bind "},{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/IMessageListViewDriver","type":"reference","isActive":true}],"title":"bindDriver(driver:create:)","type":"topic","role":"symbol","url":"\/documentation\/shengwangchatuikit\/chatthreadviewmodel\/binddriver(driver:create:)","kind":"symbol","navigatorTitle":[{"text":"bindWithDriver:create:","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewModel\/bindDriver(driver:create:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"bindDriver","kind":"identifier"},{"text":"(","kind":"text"},{"text":"driver","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(pl)IMessageListViewDriver","kind":"typeIdentifier","text":"IMessageListViewDriver"},{"kind":"text","text":", "},{"kind":"externalParam","text":"create"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"bindWithDriver:create:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"value":[{"kind":"text","text":"- "},{"text":"bindWithDriver:create:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"bindWithDriver:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@ShengwangChatUIKit@objc(pl)IMessageListViewDriver","text":"id<IMessageListViewDriver>"},{"text":") ","kind":"text"},{"text":"driver","kind":"internalParam"},{"kind":"text","text":" "},{"text":"create:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"create"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/primaryContentSections\/1","value":{"parameters":[{"name":"driver","content":[{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/IMessageListViewDriver"}]}]},{"name":"create","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Whether to create a new thread"}]}]}],"kind":"parameters"}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1IMessageListViewDriver\/title","value":"IMessageListViewDriver"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1IMessageListViewDriver\/fragments","value":[{"kind":"identifier","text":"IMessageListViewDriver"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1IMessageListViewDriver\/navigatorTitle","value":[{"text":"IMessageListViewDriver","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadViewModel\/title","value":"ChatThreadViewModel"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadViewModel\/fragments","value":[{"kind":"identifier","text":"ChatThreadViewModel"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadViewModel\/navigatorTitle","value":[{"kind":"identifier","text":"ChatThreadViewModel"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadViewModel~1bindDriver(driver:create:)\/title","op":"replace","value":"bindWithDriver:create:"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadViewModel~1bindDriver(driver:create:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"bindWithDriver:create:","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}