{"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"messageAvatarLongPressed"},{"kind":"text","text":"("},{"text":"profile","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(pl)ChatUserProfileProtocol","text":"ChatUserProfileProtocol","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatUserProfileProtocol"},{"kind":"text","text":")"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/chatthreadviewmodel\/messageavatarlongpressed(profile:)"]},{"paths":["\/documentation\/shengwangchatuikit\/chatthreadviewmodel\/messageavatarlongpressed(profile:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"extendedModule":"ShengwangChatUIKit","modules":[{"name":"ShengwangChatUIKit"}],"roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"messageAvatarLongPressed"},{"text":"(","kind":"text"},{"text":"profile","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ChatUserProfileProtocol","kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(pl)ChatUserProfileProtocol"},{"kind":"text","text":")"}],"title":"messageAvatarLongPressed(profile:)","role":"symbol","navigatorTitle":[{"text":"messageAvatarLongPressedWithProfile:","kind":"identifier"}],"externalID":"c:@CM@ShengwangChatUIKit@objc(cs)ChatThreadViewModel(im)messageAvatarLongPressedWithProfile:","symbolKind":"method"},"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewModel"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewModel\/messageAvatarLongPressed(profile:)"},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatUserProfileProtocol":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatUserProfileProtocol","abstract":[{"text":"Profile of the ChatUIKit display needed.","type":"text"}],"title":"ChatUserProfileProtocol","type":"topic","kind":"symbol","navigatorTitle":[{"text":"ChatUserProfileProtocol","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"ChatUserProfileProtocol","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/chatuserprofileprotocol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatThreadViewModel":{"navigatorTitle":[{"text":"ChatThreadViewModel","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewModel","url":"\/documentation\/shengwangchatuikit\/chatthreadviewmodel","abstract":[],"role":"symbol","kind":"symbol","type":"topic","title":"ChatThreadViewModel","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChatThreadViewModel","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatThreadViewModel/messageAvatarLongPressed(profile:)":{"url":"\/documentation\/shengwangchatuikit\/chatthreadviewmodel\/messageavatarlongpressed(profile:)","type":"topic","title":"messageAvatarLongPressed(profile:)","role":"symbol","navigatorTitle":[{"text":"messageAvatarLongPressedWithProfile:","kind":"identifier"}],"kind":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewModel\/messageAvatarLongPressed(profile:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"messageAvatarLongPressed"},{"text":"(","kind":"text"},{"text":"profile","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChatUserProfileProtocol","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(pl)ChatUserProfileProtocol"},{"text":")","kind":"text"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","value":"messageAvatarLongPressedWithProfile:","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"messageAvatarLongPressedWithProfile:"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"messageAvatarLongPressedWithProfile:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Qo@M@ShengwangChatUIKit@objc(pl)ChatUserProfileProtocol","text":"id<ChatUserProfileProtocol>","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"profile","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatUserProfileProtocol\/title","value":"ChatUserProfileProtocol"},{"value":[{"text":"ChatUserProfileProtocol","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatUserProfileProtocol\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatUserProfileProtocol\/navigatorTitle","op":"replace","value":[{"text":"ChatUserProfileProtocol","kind":"identifier"}]},{"op":"replace","value":"ChatThreadViewModel","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadViewModel\/title"},{"value":[{"text":"ChatThreadViewModel","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadViewModel\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadViewModel\/navigatorTitle","value":[{"kind":"identifier","text":"ChatThreadViewModel"}],"op":"replace"},{"value":"messageAvatarLongPressedWithProfile:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadViewModel~1messageAvatarLongPressed(profile:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadViewModel~1messageAvatarLongPressed(profile:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"messageAvatarLongPressedWithProfile:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}