{"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"title":"MessageListViewActionEventsDelegate Implementations","role":"collectionGroup","roleHeading":"API Collection","modules":[{"name":"ShengwangChatUIKit"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewModel\/MessageListViewActionEventsDelegate-Implementations"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewModel"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/chatthreadviewmodel\/messagelistviewactioneventsdelegate-implementations"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/chatthreadviewmodel\/messagelistviewactioneventsdelegate-implementations"]}],"sections":[],"kind":"article","topicSections":[{"generated":true,"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewModel\/onFailureMessageRetrySend(entity:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewModel\/onInputBoxEventsOccur(action:attributeText:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewModel\/onMessageAvatarClicked(profile:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewModel\/onMessageAvatarLongPressed(profile:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewModel\/onMessageContentClicked(message:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewModel\/onMessageContentLongPressed(cell:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewModel\/onMessageListLoadMore()","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewModel\/onMessageListPullRefresh()","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewModel\/onMessageMultiSelectBarClicked(operation:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewModel\/onMessageReactionClicked(reaction:entity:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewModel\/onMessageReplyClicked(message:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewModel\/onMessageTopicClicked(entity:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewModel\/onMessageVisible(entity:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewModel\/onMoreMessagesClicked()"],"anchor":"Instance-Methods","title":"Instance Methods"}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatThreadViewModel/onMoreMessagesClicked()":{"title":"onMoreMessagesClicked()","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewModel\/onMoreMessagesClicked()","abstract":[{"text":"More messages button clicked.","type":"text"}],"kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/shengwangchatuikit\/chatthreadviewmodel\/onmoremessagesclicked()","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"onMoreMessagesClicked","kind":"identifier"},{"text":"()","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"onMoreMessagesClicked"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatThreadViewModel/onFailureMessageRetrySend(entity:)":{"url":"\/documentation\/shengwangchatuikit\/chatthreadviewmodel\/onfailuremessageretrysend(entity:)","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewModel\/onFailureMessageRetrySend(entity:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"onFailureMessageRetrySendWithEntity:"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onFailureMessageRetrySend"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"entity"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MessageEntity","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)MessageEntity"},{"kind":"text","text":")"}],"type":"topic","title":"onFailureMessageRetrySend(entity:)","kind":"symbol","abstract":[{"text":"The method will call on failure message status view clicked.","type":"text"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatThreadViewModel/onInputBoxEventsOccur(action:attributeText:)":{"kind":"symbol","url":"\/documentation\/shengwangchatuikit\/chatthreadviewmodel\/oninputboxeventsoccur(action:attributetext:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"onInputBoxEventsOccurWithAction:attributeText:"}],"type":"topic","title":"onInputBoxEventsOccur(action:attributeText:)","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewModel\/onInputBoxEventsOccur(action:attributeText:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onInputBoxEventsOccur","kind":"identifier"},{"kind":"text","text":"("},{"text":"action","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@E@MessageInputBarActionType","text":"MessageInputBarActionType","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"attributeText"},{"text":": ","kind":"text"},{"text":"NSAttributedString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSAttributedString"},{"text":"?)","kind":"text"}],"abstract":[{"type":"text","text":"The method will call on input box event occur."}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatThreadViewModel/onMessageMultiSelectBarClicked(operation:)":{"title":"onMessageMultiSelectBarClicked(operation:)","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewModel\/onMessageMultiSelectBarClicked(operation:)","abstract":[{"text":"When message multi select bar clicked.","type":"text"}],"kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/shengwangchatuikit\/chatthreadviewmodel\/onmessagemultiselectbarclicked(operation:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onMessageMultiSelectBarClicked"},{"kind":"text","text":"("},{"text":"operation","kind":"externalParam"},{"kind":"text","text":": "},{"text":"MessageMultiSelectedBottomBarOperation","preciseIdentifier":"c:@M@ShengwangChatUIKit@E@MessageMultiSelectedBottomBarOperation","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"onMessageMultiSelectBarClickedWithOperation:"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatThreadViewModel/onMessageTopicClicked(entity:)":{"abstract":[{"type":"text","text":"Message topic view clicked."}],"type":"topic","title":"onMessageTopicClicked(entity:)","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewModel\/onMessageTopicClicked(entity:)","kind":"symbol","url":"\/documentation\/shengwangchatuikit\/chatthreadviewmodel\/onmessagetopicclicked(entity:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onMessageTopicClicked","kind":"identifier"},{"text":"(","kind":"text"},{"text":"entity","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MessageEntity","kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)MessageEntity"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"onMessageTopicClickedWithEntity:","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatThreadViewModel":{"navigatorTitle":[{"text":"ChatThreadViewModel","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewModel","url":"\/documentation\/shengwangchatuikit\/chatthreadviewmodel","abstract":[],"role":"symbol","kind":"symbol","type":"topic","title":"ChatThreadViewModel","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChatThreadViewModel","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatThreadViewModel/onMessageVisible(entity:)":{"abstract":[{"type":"text","text":"Message visible on scroll in screen"}],"type":"topic","url":"\/documentation\/shengwangchatuikit\/chatthreadviewmodel\/onmessagevisible(entity:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onMessageVisible"},{"text":"(","kind":"text"},{"text":"entity","kind":"externalParam"},{"kind":"text","text":": "},{"text":"MessageEntity","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)MessageEntity","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewModel\/onMessageVisible(entity:)","kind":"symbol","navigatorTitle":[{"text":"onMessageVisibleWithEntity:","kind":"identifier"}],"title":"onMessageVisible(entity:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatThreadViewModel/onMessageAvatarClicked(profile:)":{"url":"\/documentation\/shengwangchatuikit\/chatthreadviewmodel\/onmessageavatarclicked(profile:)","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewModel\/onMessageAvatarClicked(profile:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"onMessageAvatarClickedWithProfile:"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onMessageAvatarClicked"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"profile"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChatUserProfileProtocol","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(pl)ChatUserProfileProtocol"},{"kind":"text","text":")"}],"type":"topic","title":"onMessageAvatarClicked(profile:)","kind":"symbol","abstract":[{"type":"text","text":"The method will call on message avatar clicked"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatThreadViewModel/onMessageContentLongPressed(cell:)":{"title":"onMessageContentLongPressed(cell:)","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewModel\/onMessageContentLongPressed(cell:)","abstract":[{"type":"text","text":"The method will call on message content long pressed."}],"kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/shengwangchatuikit\/chatthreadviewmodel\/onmessagecontentlongpressed(cell:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onMessageContentLongPressed"},{"kind":"text","text":"("},{"text":"cell","kind":"externalParam"},{"kind":"text","text":": "},{"text":"MessageCell","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)MessageCell","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"onMessageContentLongPressedWithCell:"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatThreadViewModel/onMessageReactionClicked(reaction:entity:)":{"url":"\/documentation\/shengwangchatuikit\/chatthreadviewmodel\/onmessagereactionclicked(reaction:entity:)","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewModel\/onMessageReactionClicked(reaction:entity:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"onMessageReactionClickedWithReaction:entity:"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onMessageReactionClicked"},{"kind":"text","text":"("},{"kind":"externalParam","text":"reaction"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit15MessageReactiona","text":"MessageReaction"},{"kind":"text","text":"?, "},{"text":"entity","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)MessageEntity","text":"MessageEntity"},{"text":")","kind":"text"}],"type":"topic","title":"onMessageReactionClicked(reaction:entity:)","kind":"symbol","abstract":[{"text":"Message reaction&","type":"text"},{"code":"...","type":"codeVoice"},{"type":"text","text":" clicked."}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatThreadViewModel/onMessageContentClicked(message:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onMessageContentClicked"},{"text":"(","kind":"text"},{"text":"message","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"MessageEntity","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)MessageEntity"},{"text":")","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewModel\/onMessageContentClicked(message:)","url":"\/documentation\/shengwangchatuikit\/chatthreadviewmodel\/onmessagecontentclicked(message:)","navigatorTitle":[{"text":"onMessageContentClickedWithMessage:","kind":"identifier"}],"type":"topic","title":"onMessageContentClicked(message:)","abstract":[{"text":"The method will call on message content clicked.","type":"text"}],"role":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatThreadViewModel/onMessageListLoadMore()":{"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"onMessageListLoadMore","kind":"identifier"},{"kind":"text","text":"()"}],"title":"onMessageListLoadMore()","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewModel\/onMessageListLoadMore()","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"onMessageListLoadMore"}],"url":"\/documentation\/shengwangchatuikit\/chatthreadviewmodel\/onmessagelistloadmore()"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatThreadViewModel/onMessageListPullRefresh()":{"title":"onMessageListPullRefresh()","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewModel\/onMessageListPullRefresh()","abstract":[{"text":"The method will call on message list pull to refreshing.","type":"text"}],"kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/shengwangchatuikit\/chatthreadviewmodel\/onmessagelistpullrefresh()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onMessageListPullRefresh"},{"text":"()","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"onMessageListPullRefresh"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatThreadViewModel/onMessageReplyClicked(message:)":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewModel\/onMessageReplyClicked(message:)","role":"symbol","kind":"symbol","url":"\/documentation\/shengwangchatuikit\/chatthreadviewmodel\/onmessagereplyclicked(message:)","title":"onMessageReplyClicked(message:)","abstract":[{"text":"The method will call on message reply content clicked.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onMessageReplyClicked"},{"text":"(","kind":"text"},{"text":"message","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"MessageEntity","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)MessageEntity"},{"kind":"text","text":")"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"onMessageReplyClickedWithMessage:"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatThreadViewModel/onMessageAvatarLongPressed(profile:)":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewModel\/onMessageAvatarLongPressed(profile:)","title":"onMessageAvatarLongPressed(profile:)","role":"symbol","kind":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"onMessageAvatarLongPressed"},{"text":"(","kind":"text"},{"text":"profile","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ChatUserProfileProtocol","kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(pl)ChatUserProfileProtocol"},{"text":")","kind":"text"}],"abstract":[{"type":"text","text":"The method will call on message avatar long pressed."}],"url":"\/documentation\/shengwangchatuikit\/chatthreadviewmodel\/onmessageavatarlongpressed(profile:)","navigatorTitle":[{"kind":"identifier","text":"onMessageAvatarLongPressedWithProfile:"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/topicSections","value":[{"generated":true,"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewModel\/onFailureMessageRetrySend(entity:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewModel\/onInputBoxEventsOccur(action:attributeText:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewModel\/onMessageAvatarClicked(profile:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewModel\/onMessageAvatarLongPressed(profile:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewModel\/onMessageContentClicked(message:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewModel\/onMessageContentLongPressed(cell:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewModel\/onMessageListLoadMore()","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewModel\/onMessageListPullRefresh()","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewModel\/onMessageMultiSelectBarClicked(operation:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewModel\/onMessageReactionClicked(reaction:entity:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewModel\/onMessageReplyClicked(message:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewModel\/onMessageTopicClicked(entity:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewModel\/onMessageVisible(entity:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewModel\/onMoreMessagesClicked()"]}],"op":"replace"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadViewModel~1onMoreMessagesClicked()\/title","value":"onMoreMessagesClicked"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadViewModel~1onMoreMessagesClicked()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onMoreMessagesClicked"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadViewModel~1onFailureMessageRetrySend(entity:)\/title","value":"onFailureMessageRetrySendWithEntity:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onFailureMessageRetrySendWithEntity:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadViewModel~1onFailureMessageRetrySend(entity:)\/fragments"},{"value":"onInputBoxEventsOccurWithAction:attributeText:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadViewModel~1onInputBoxEventsOccur(action:attributeText:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadViewModel~1onInputBoxEventsOccur(action:attributeText:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"onInputBoxEventsOccurWithAction:attributeText:","kind":"identifier"}]},{"op":"replace","value":"onMessageMultiSelectBarClickedWithOperation:","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadViewModel~1onMessageMultiSelectBarClicked(operation:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadViewModel~1onMessageMultiSelectBarClicked(operation:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"onMessageMultiSelectBarClickedWithOperation:","kind":"identifier"}]},{"value":"onMessageTopicClickedWithEntity:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadViewModel~1onMessageTopicClicked(entity:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadViewModel~1onMessageTopicClicked(entity:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"onMessageTopicClickedWithEntity:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadViewModel\/title","value":"ChatThreadViewModel","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadViewModel\/fragments","value":[{"text":"ChatThreadViewModel","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadViewModel\/navigatorTitle","value":[{"text":"ChatThreadViewModel","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadViewModel~1onMessageVisible(entity:)\/title","value":"onMessageVisibleWithEntity:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"onMessageVisibleWithEntity:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadViewModel~1onMessageVisible(entity:)\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadViewModel~1onMessageAvatarClicked(profile:)\/title","value":"onMessageAvatarClickedWithProfile:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"onMessageAvatarClickedWithProfile:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadViewModel~1onMessageAvatarClicked(profile:)\/fragments"},{"value":"onMessageContentLongPressedWithCell:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadViewModel~1onMessageContentLongPressed(cell:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadViewModel~1onMessageContentLongPressed(cell:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"onMessageContentLongPressedWithCell:"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadViewModel~1onMessageReactionClicked(reaction:entity:)\/title","value":"onMessageReactionClickedWithReaction:entity:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"onMessageReactionClickedWithReaction:entity:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadViewModel~1onMessageReactionClicked(reaction:entity:)\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadViewModel~1onMessageContentClicked(message:)\/title","op":"replace","value":"onMessageContentClickedWithMessage:"},{"value":[{"kind":"text","text":"- "},{"text":"onMessageContentClickedWithMessage:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadViewModel~1onMessageContentClicked(message:)\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadViewModel~1onMessageListLoadMore()\/title","value":"onMessageListLoadMore","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadViewModel~1onMessageListLoadMore()\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"onMessageListLoadMore","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadViewModel~1onMessageListPullRefresh()\/title","value":"onMessageListPullRefresh"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadViewModel~1onMessageListPullRefresh()\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"onMessageListPullRefresh"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadViewModel~1onMessageReplyClicked(message:)\/title","value":"onMessageReplyClickedWithMessage:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"onMessageReplyClickedWithMessage:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadViewModel~1onMessageReplyClicked(message:)\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadViewModel~1onMessageAvatarLongPressed(profile:)\/title","op":"replace","value":"onMessageAvatarLongPressedWithProfile:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadViewModel~1onMessageAvatarLongPressed(profile:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onMessageAvatarLongPressedWithProfile:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}