{"metadata":{"modules":[{"name":"ShengwangChatUIKit"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"messageDidRecalled","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"recallInfo"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:18ShengwangChatUIKit10RecallInfoa","text":"RecallInfo","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","extendedModule":"ShengwangChatUIKit","title":"messageDidRecalled(recallInfo:)","symbolKind":"method","roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"messageDidRecalledWithRecallInfo:"}],"externalID":"c:@CM@ShengwangChatUIKit@objc(cs)ChatThreadViewModel(im)messageDidRecalledWithRecallInfo:"},"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewModel\/messageDidRecalled(recallInfo:)","interfaceLanguage":"swift"},"sections":[],"variants":[{"paths":["\/documentation\/shengwangchatuikit\/chatthreadviewmodel\/messagedidrecalled(recallinfo:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/shengwangchatuikit\/chatthreadviewmodel\/messagedidrecalled(recallinfo:)"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"Handles the event when a message is recalled.","type":"text"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"messageDidRecalled"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"recallInfo"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/RecallInfo","preciseIdentifier":"s:18ShengwangChatUIKit10RecallInfoa","text":"RecallInfo","kind":"typeIdentifier"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"name":"recallInfo","content":[{"type":"paragraph","inlineContent":[{"text":"The recall information containing the recalled message.","type":"text"}]}]}],"kind":"parameters"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewModel"]]},"kind":"symbol","references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatThreadViewModel":{"navigatorTitle":[{"text":"ChatThreadViewModel","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewModel","url":"\/documentation\/shengwangchatuikit\/chatthreadviewmodel","abstract":[],"role":"symbol","kind":"symbol","type":"topic","title":"ChatThreadViewModel","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChatThreadViewModel","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatThreadViewModel/messageDidRecalled(recallInfo:)":{"abstract":[{"type":"text","text":"Handles the event when a message is recalled."}],"url":"\/documentation\/shengwangchatuikit\/chatthreadviewmodel\/messagedidrecalled(recallinfo:)","title":"messageDidRecalled(recallInfo:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"messageDidRecalledWithRecallInfo:"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewModel\/messageDidRecalled(recallInfo:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"messageDidRecalled","kind":"identifier"},{"text":"(","kind":"text"},{"text":"recallInfo","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RecallInfo","preciseIdentifier":"s:18ShengwangChatUIKit10RecallInfoa"},{"kind":"text","text":")"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/RecallInfo":{"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"text":"RecallInfo","kind":"identifier"}],"title":"RecallInfo","abstract":[],"type":"topic","kind":"symbol","url":"\/documentation\/shengwangchatuikit\/recallinfo","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/RecallInfo","navigatorTitle":[{"text":"RecallInfo","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"messageDidRecalledWithRecallInfo:","path":"\/metadata\/title","op":"replace"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"messageDidRecalledWithRecallInfo:"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"messageDidRecalledWithRecallInfo:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)AgoraChatRecallMessageInfo","text":"AgoraChatRecallMessageInfo","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"recallInfo","kind":"internalParam"},{"text":";","kind":"text"}]}]}},{"path":"\/primaryContentSections\/1","op":"replace","value":{"parameters":[{"name":"recallInfo","content":[{"type":"paragraph","inlineContent":[{"text":"The recall information containing the recalled message.","type":"text"}]}]}],"kind":"parameters"}},{"value":"ChatThreadViewModel","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadViewModel\/title","op":"replace"},{"op":"replace","value":[{"text":"ChatThreadViewModel","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadViewModel\/fragments"},{"value":[{"text":"ChatThreadViewModel","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadViewModel\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadViewModel~1messageDidRecalled(recallInfo:)\/title","value":"messageDidRecalledWithRecallInfo:"},{"value":[{"text":"- ","kind":"text"},{"text":"messageDidRecalledWithRecallInfo:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadViewModel~1messageDidRecalled(recallInfo:)\/fragments","op":"replace"}]}]}