{"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewModel\/onMessageStickiedTop(conversationId:messageId:operation:info:)","interfaceLanguage":"swift"},"metadata":{"symbolKind":"method","title":"onMessageStickiedTop(conversationId:messageId:operation:info:)","externalID":"c:@CM@ShengwangChatUIKit@objc(cs)ChatThreadViewModel(im)onMessageStickiedTopWithConversationId:messageId:operation:info:","extendedModule":"ShengwangChatUIKit","roleHeading":"Instance Method","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"onMessageStickiedTop","kind":"identifier"},{"kind":"text","text":"("},{"text":"conversationId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"messageId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"operation","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"MessagePinOperation","preciseIdentifier":"s:18ShengwangChatUIKit19MessagePinOperationa"},{"kind":"text","text":", "},{"text":"info","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MessagePinInfo","kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit14MessagePinInfoa"},{"text":")","kind":"text"}],"modules":[{"name":"ShengwangChatUIKit"}],"navigatorTitle":[{"text":"onMessageStickiedTopWithConversationId:messageId:operation:info:","kind":"identifier"}]},"abstract":[{"type":"text","text":"When message stickied top the method called."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/chatthreadviewmodel\/onmessagestickiedtop(conversationid:messageid:operation:info:)"]},{"paths":["\/documentation\/shengwangchatuikit\/chatthreadviewmodel\/onmessagestickiedtop(conversationid:messageid:operation:info:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewModel","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewModel\/ChatResponseListener-Implementations"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"onMessageStickiedTop","kind":"identifier"},{"kind":"text","text":"("},{"text":"conversationId","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"messageId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"operation","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessagePinOperation","text":"MessagePinOperation","preciseIdentifier":"s:18ShengwangChatUIKit19MessagePinOperationa"},{"kind":"text","text":", "},{"kind":"externalParam","text":"info"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"MessagePinInfo","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessagePinInfo","preciseIdentifier":"s:18ShengwangChatUIKit14MessagePinInfoa"},{"kind":"text","text":")"}],"platforms":["iOS"]}]},{"parameters":[{"content":[{"inlineContent":[{"text":"ID of the conversation","type":"text"}],"type":"paragraph"}],"name":"conversationId"},{"content":[{"inlineContent":[{"text":"ID of the message.","type":"text"}],"type":"paragraph"}],"name":"messageId"},{"content":[{"inlineContent":[{"type":"text","text":""},{"type":"reference","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessagePinOperation","isActive":true}],"type":"paragraph"}],"name":"operation"},{"name":"info","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"reference","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessagePinInfo","isActive":true}]}]}],"kind":"parameters"}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatThreadViewModel/ChatResponseListener-Implementations":{"kind":"article","abstract":[],"type":"topic","url":"\/documentation\/shengwangchatuikit\/chatthreadviewmodel\/chatresponselistener-implementations","title":"ChatResponseListener Implementations","role":"collectionGroup","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewModel\/ChatResponseListener-Implementations"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessagePinOperation":{"type":"topic","navigatorTitle":[{"text":"MessagePinOperation","kind":"identifier"}],"title":"MessagePinOperation","role":"symbol","kind":"symbol","url":"\/documentation\/shengwangchatuikit\/messagepinoperation","abstract":[],"fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"MessagePinOperation","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessagePinOperation"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatThreadViewModel/onMessageStickiedTop(conversationId:messageId:operation:info:)":{"kind":"symbol","navigatorTitle":[{"text":"onMessageStickiedTopWithConversationId:messageId:operation:info:","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/chatthreadviewmodel\/onmessagestickiedtop(conversationid:messageid:operation:info:)","title":"onMessageStickiedTop(conversationId:messageId:operation:info:)","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewModel\/onMessageStickiedTop(conversationId:messageId:operation:info:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"onMessageStickiedTop","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"conversationId"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"text":"messageId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"operation","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MessagePinOperation","preciseIdentifier":"s:18ShengwangChatUIKit19MessagePinOperationa"},{"kind":"text","text":", "},{"kind":"externalParam","text":"info"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"MessagePinInfo","preciseIdentifier":"s:18ShengwangChatUIKit14MessagePinInfoa"},{"kind":"text","text":")"}],"type":"topic","role":"symbol","abstract":[{"type":"text","text":"When message stickied top the method called."}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatThreadViewModel":{"navigatorTitle":[{"text":"ChatThreadViewModel","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewModel","url":"\/documentation\/shengwangchatuikit\/chatthreadviewmodel","abstract":[],"role":"symbol","kind":"symbol","type":"topic","title":"ChatThreadViewModel","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChatThreadViewModel","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessagePinInfo":{"type":"topic","navigatorTitle":[{"text":"MessagePinInfo","kind":"identifier"}],"title":"MessagePinInfo","role":"symbol","kind":"symbol","url":"\/documentation\/shengwangchatuikit\/messagepininfo","abstract":[],"fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessagePinInfo"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessagePinInfo"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","value":"onMessageStickiedTopWithConversationId:messageId:operation:info:","path":"\/metadata\/title"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onMessageStickiedTopWithConversationId:messageId:operation:info:"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"onMessageStickiedTopWithConversationId:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"conversationId","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"messageId:"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"messageId","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"operation:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@E@AgoraChatMessagePinOperation","text":"AgoraChatMessagePinOperation","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"operation","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"info:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)AgoraChatMessagePinInfo","text":"AgoraChatMessagePinInfo","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"info","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadViewModel~1onMessageStickiedTop(conversationId:messageId:operation:info:)\/title","value":"onMessageStickiedTopWithConversationId:messageId:operation:info:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadViewModel~1onMessageStickiedTop(conversationId:messageId:operation:info:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onMessageStickiedTopWithConversationId:messageId:operation:info:"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadViewModel\/title","value":"ChatThreadViewModel","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadViewModel\/fragments","op":"replace","value":[{"kind":"identifier","text":"ChatThreadViewModel"}]},{"value":[{"text":"ChatThreadViewModel","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadViewModel\/navigatorTitle"}]}]}