{"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"requestGroupDetail","kind":"identifier"},{"text":"()","kind":"text"}],"role":"symbol","symbolKind":"method","modules":[{"name":"ShengwangChatUIKit"}],"title":"requestGroupDetail()","roleHeading":"Instance Method","externalID":"c:@M@ShengwangChatUIKit@objc(cs)ChatThreadViewModel(im)requestGroupDetail","navigatorTitle":[{"kind":"identifier","text":"requestGroupDetail"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"requestGroupDetail","kind":"identifier"},{"kind":"text","text":"()"}],"platforms":["iOS"],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewModel\/requestGroupDetail()","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewModel"]]},"variants":[{"paths":["\/documentation\/shengwangchatuikit\/chatthreadviewmodel\/requestgroupdetail()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/chatthreadviewmodel\/requestgroupdetail()"]}],"kind":"symbol","references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatThreadViewModel/requestGroupDetail()":{"url":"\/documentation\/shengwangchatuikit\/chatthreadviewmodel\/requestgroupdetail()","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"requestGroupDetail","kind":"identifier"},{"text":"()","kind":"text"}],"abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"requestGroupDetail"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewModel\/requestGroupDetail()","title":"requestGroupDetail()","type":"topic"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatThreadViewModel":{"navigatorTitle":[{"text":"ChatThreadViewModel","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewModel","url":"\/documentation\/shengwangchatuikit\/chatthreadviewmodel","abstract":[],"role":"symbol","kind":"symbol","type":"topic","title":"ChatThreadViewModel","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChatThreadViewModel","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"requestGroupDetail"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"requestGroupDetail"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"requestGroupDetail"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadViewModel~1requestGroupDetail()\/title","value":"requestGroupDetail"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadViewModel~1requestGroupDetail()\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"requestGroupDetail","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadViewModel\/title","value":"ChatThreadViewModel"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadViewModel\/fragments","value":[{"kind":"identifier","text":"ChatThreadViewModel"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadViewModel\/navigatorTitle","value":[{"kind":"identifier","text":"ChatThreadViewModel"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}