{"metadata":{"roleHeading":"API Collection","title":"ContactListActionEventsDelegate Implementations","modules":[{"name":"ShengwangChatUIKit"}],"role":"collectionGroup"},"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"paths":["\/documentation\/shengwangchatuikit\/contactviewmodel\/contactlistactioneventsdelegate-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/contactviewmodel\/contactlistactioneventsdelegate-implementations"]}],"kind":"article","hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactViewModel"]]},"sections":[],"topicSections":[{"anchor":"Instance-Methods","generated":true,"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactViewModel\/didSelected(indexPath:profile:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactViewModel\/onContactListEndScrollNeededDisplayInfos(ids:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactViewModel\/onContactListOccurErrorWhenFetchServer()","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactViewModel\/onContactListScroll(indexPath:)"],"title":"Instance Methods"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactViewModel\/ContactListActionEventsDelegate-Implementations"},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ContactViewModel/onContactListScroll(indexPath:)":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactViewModel\/onContactListScroll(indexPath:)","type":"topic","title":"onContactListScroll(indexPath:)","abstract":[{"text":"When contact list scrolled.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onContactListScroll"},{"kind":"text","text":"("},{"kind":"externalParam","text":"indexPath"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":")"}],"url":"\/documentation\/shengwangchatuikit\/contactviewmodel\/oncontactlistscroll(indexpath:)","kind":"symbol","navigatorTitle":[{"text":"onContactListScrollWithIndexPath:","kind":"identifier"}],"role":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ContactViewModel":{"abstract":[{"text":"Bind service and driver","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ContactViewModel","kind":"identifier"}],"navigatorTitle":[{"text":"ContactViewModel","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactViewModel","role":"symbol","title":"ContactViewModel","kind":"symbol","url":"\/documentation\/shengwangchatuikit\/contactviewmodel"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ContactViewModel/onContactListEndScrollNeededDisplayInfos(ids:)":{"abstract":[{"text":"The method will called on conversation list end scroll,then it will ask you for the session nickname and avatar data and then refresh it.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onContactListEndScrollNeededDisplayInfos"},{"kind":"text","text":"("},{"kind":"externalParam","text":"ids"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"])","kind":"text"}],"kind":"symbol","title":"onContactListEndScrollNeededDisplayInfos(ids:)","role":"symbol","url":"\/documentation\/shengwangchatuikit\/contactviewmodel\/oncontactlistendscrollneededdisplayinfos(ids:)","type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactViewModel\/onContactListEndScrollNeededDisplayInfos(ids:)","navigatorTitle":[{"text":"onContactListEndScrollNeededDisplayInfosWithIds:","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ContactViewModel/didSelected(indexPath:profile:)":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactViewModel\/didSelected(indexPath:profile:)","type":"topic","title":"didSelected(indexPath:profile:)","abstract":[{"text":"The method’ll called on contact list cell clicked.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"didSelected"},{"kind":"text","text":"("},{"kind":"externalParam","text":"indexPath"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":", "},{"text":"profile","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChatUserProfileProtocol","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(pl)ChatUserProfileProtocol"},{"kind":"text","text":")"}],"url":"\/documentation\/shengwangchatuikit\/contactviewmodel\/didselected(indexpath:profile:)","kind":"symbol","navigatorTitle":[{"text":"didSelectedWithIndexPath:profile:","kind":"identifier"}],"role":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ContactViewModel/onContactListOccurErrorWhenFetchServer()":{"abstract":[{"text":"When fetch conversations list occur error.Empty view retry button on clicked.The method will call.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onContactListOccurErrorWhenFetchServer"},{"text":"()","kind":"text"}],"kind":"symbol","title":"onContactListOccurErrorWhenFetchServer()","role":"symbol","url":"\/documentation\/shengwangchatuikit\/contactviewmodel\/oncontactlistoccurerrorwhenfetchserver()","type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactViewModel\/onContactListOccurErrorWhenFetchServer()","navigatorTitle":[{"kind":"identifier","text":"onContactListOccurErrorWhenFetchServer"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":[{"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactViewModel\/didSelected(indexPath:profile:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactViewModel\/onContactListEndScrollNeededDisplayInfos(ids:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactViewModel\/onContactListOccurErrorWhenFetchServer()","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactViewModel\/onContactListScroll(indexPath:)"],"title":"Instance Methods","anchor":"Instance-Methods","generated":true}],"path":"\/topicSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactViewModel~1onContactListScroll(indexPath:)\/title","value":"onContactListScrollWithIndexPath:"},{"value":[{"kind":"text","text":"- "},{"text":"onContactListScrollWithIndexPath:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactViewModel~1onContactListScroll(indexPath:)\/fragments"},{"op":"replace","value":"ContactViewModel","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactViewModel\/title"},{"op":"replace","value":[{"kind":"identifier","text":"ContactViewModel"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactViewModel\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactViewModel\/navigatorTitle","op":"replace","value":[{"text":"ContactViewModel","kind":"identifier"}]},{"value":"onContactListEndScrollNeededDisplayInfosWithIds:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactViewModel~1onContactListEndScrollNeededDisplayInfos(ids:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactViewModel~1onContactListEndScrollNeededDisplayInfos(ids:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onContactListEndScrollNeededDisplayInfosWithIds:"}],"op":"replace"},{"value":"didSelectedWithIndexPath:profile:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactViewModel~1didSelected(indexPath:profile:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didSelectedWithIndexPath:profile:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactViewModel~1didSelected(indexPath:profile:)\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactViewModel~1onContactListOccurErrorWhenFetchServer()\/title","op":"replace","value":"onContactListOccurErrorWhenFetchServer"},{"value":[{"kind":"text","text":"- "},{"text":"onContactListOccurErrorWhenFetchServer","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactViewModel~1onContactListOccurErrorWhenFetchServer()\/fragments","op":"replace"}]}]}