{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/contactviewmodel\/contacteventdidchanged(event:userid:extension:)"]},{"paths":["\/documentation\/shengwangchatuikit\/contactviewmodel\/contacteventdidchanged(event:userid:extension:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactViewModel"]]},"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"contactEventDidChanged"},{"kind":"text","text":"("},{"text":"event","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MultiDeviceEvent","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MultiDeviceEvent","kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit16MultiDeviceEventa"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"userId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"extension","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"info"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}]}],"kind":"declarations"}],"metadata":{"roleHeading":"Instance Method","extendedModule":"ShengwangChatUIKit","title":"contactEventDidChanged(event:userId:extension:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"contactEventDidChangedWithEvent:userId:extension:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"contactEventDidChanged","kind":"identifier"},{"text":"(","kind":"text"},{"text":"event","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"MultiDeviceEvent","preciseIdentifier":"s:18ShengwangChatUIKit16MultiDeviceEventa"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"userId"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"extension","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"externalID":"c:@CM@ShengwangChatUIKit@objc(cs)ContactViewModel(im)contactEventDidChangedWithEvent:userId:extension:","modules":[{"name":"ShengwangChatUIKit"}],"symbolKind":"method"},"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactViewModel\/contactEventDidChanged(event:userId:extension:)","interfaceLanguage":"swift"},"sections":[],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MultiDeviceEvent":{"fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MultiDeviceEvent"}],"role":"symbol","url":"\/documentation\/shengwangchatuikit\/multideviceevent","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MultiDeviceEvent","title":"MultiDeviceEvent","kind":"symbol","abstract":[],"navigatorTitle":[{"text":"MultiDeviceEvent","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ContactViewModel":{"abstract":[{"text":"Bind service and driver","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ContactViewModel","kind":"identifier"}],"navigatorTitle":[{"text":"ContactViewModel","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactViewModel","role":"symbol","title":"ContactViewModel","kind":"symbol","url":"\/documentation\/shengwangchatuikit\/contactviewmodel"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ContactViewModel/contactEventDidChanged(event:userId:extension:)":{"abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"contactEventDidChanged","kind":"identifier"},{"text":"(","kind":"text"},{"text":"event","kind":"externalParam"},{"kind":"text","text":": "},{"text":"MultiDeviceEvent","kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit16MultiDeviceEventa"},{"text":", ","kind":"text"},{"text":"userId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"extension","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}],"url":"\/documentation\/shengwangchatuikit\/contactviewmodel\/contacteventdidchanged(event:userid:extension:)","role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactViewModel\/contactEventDidChanged(event:userId:extension:)","title":"contactEventDidChanged(event:userId:extension:)","type":"topic","navigatorTitle":[{"kind":"identifier","text":"contactEventDidChangedWithEvent:userId:extension:"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","value":"contactEventDidChangedWithEvent:userId:extension:","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"contactEventDidChangedWithEvent:userId:extension:","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"contactEventDidChangedWithEvent:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@AgoraChatMultiDevicesEvent","text":"AgoraChatMultiDevicesEvent"},{"kind":"text","text":") "},{"text":"event","kind":"internalParam"},{"kind":"text","text":" "},{"text":"userId:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"userId","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"extension:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"info","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"ContactViewModel","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactViewModel\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactViewModel\/fragments","value":[{"text":"ContactViewModel","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactViewModel\/navigatorTitle","value":[{"kind":"identifier","text":"ContactViewModel"}],"op":"replace"},{"value":"contactEventDidChangedWithEvent:userId:extension:","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactViewModel~1contactEventDidChanged(event:userId:extension:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"contactEventDidChangedWithEvent:userId:extension:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactViewModel~1contactEventDidChanged(event:userId:extension:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}