{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactViewModel"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"notifyCleanNewFriendRequestBadge","kind":"identifier"},{"text":"()","kind":"text"}]}]}],"variants":[{"paths":["\/documentation\/shengwangchatuikit\/contactviewmodel\/notifycleannewfriendrequestbadge()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/shengwangchatuikit\/contactviewmodel\/notifycleannewfriendrequestbadge()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactViewModel\/notifyCleanNewFriendRequestBadge()"},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"notifyCleanNewFriendRequestBadge","kind":"identifier"},{"kind":"text","text":"()"}],"modules":[{"name":"ShengwangChatUIKit"}],"roleHeading":"Instance Method","externalID":"c:@M@ShengwangChatUIKit@objc(cs)ContactViewModel(im)notifyCleanNewFriendRequestBadge","navigatorTitle":[{"text":"notifyCleanNewFriendRequestBadge","kind":"identifier"}],"symbolKind":"method","title":"notifyCleanNewFriendRequestBadge()"},"kind":"symbol","sections":[],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ContactViewModel/notifyCleanNewFriendRequestBadge()":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"notifyCleanNewFriendRequestBadge"},{"kind":"text","text":"()"}],"navigatorTitle":[{"text":"notifyCleanNewFriendRequestBadge","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/contactviewmodel\/notifycleannewfriendrequestbadge()","type":"topic","abstract":[],"title":"notifyCleanNewFriendRequestBadge()","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactViewModel\/notifyCleanNewFriendRequestBadge()","role":"symbol","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ContactViewModel":{"abstract":[{"text":"Bind service and driver","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ContactViewModel","kind":"identifier"}],"navigatorTitle":[{"text":"ContactViewModel","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactViewModel","role":"symbol","title":"ContactViewModel","kind":"symbol","url":"\/documentation\/shengwangchatuikit\/contactviewmodel"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"notifyCleanNewFriendRequestBadge"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"notifyCleanNewFriendRequestBadge"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"kind":"identifier","text":"notifyCleanNewFriendRequestBadge"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactViewModel~1notifyCleanNewFriendRequestBadge()\/title","value":"notifyCleanNewFriendRequestBadge","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactViewModel~1notifyCleanNewFriendRequestBadge()\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"notifyCleanNewFriendRequestBadge","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactViewModel\/title","op":"replace","value":"ContactViewModel"},{"value":[{"kind":"identifier","text":"ContactViewModel"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactViewModel\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"ContactViewModel"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactViewModel\/navigatorTitle"}]}]}