{"metadata":{"externalID":"c:@CM@ShengwangChatUIKit@objc(cs)ContactViewModel(im)processFriendshipDidAddSuccessfulWithUserId:","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"processFriendshipDidAddSuccessful","kind":"identifier"},{"text":"(","kind":"text"},{"text":"userId","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"processFriendshipDidAddSuccessfulWithUserId:","kind":"identifier"}],"symbolKind":"method","extendedModule":"ShengwangChatUIKit","roleHeading":"Instance Method","modules":[{"name":"ShengwangChatUIKit"}],"role":"symbol","title":"processFriendshipDidAddSuccessful(userId:)"},"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactViewModel"]]},"variants":[{"paths":["\/documentation\/shengwangchatuikit\/contactviewmodel\/processfriendshipdidaddsuccessful(userid:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/shengwangchatuikit\/contactviewmodel\/processfriendshipdidaddsuccessful(userid:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactViewModel\/processFriendshipDidAddSuccessful(userId:)","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"processFriendshipDidAddSuccessful","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"userId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ContactViewModel/processFriendshipDidAddSuccessful(userId:)":{"navigatorTitle":[{"kind":"identifier","text":"processFriendshipDidAddSuccessfulWithUserId:"}],"abstract":[],"kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactViewModel\/processFriendshipDidAddSuccessful(userId:)","url":"\/documentation\/shengwangchatuikit\/contactviewmodel\/processfriendshipdidaddsuccessful(userid:)","title":"processFriendshipDidAddSuccessful(userId:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"processFriendshipDidAddSuccessful"},{"text":"(","kind":"text"},{"text":"userId","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ContactViewModel":{"abstract":[{"text":"Bind service and driver","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ContactViewModel","kind":"identifier"}],"navigatorTitle":[{"text":"ContactViewModel","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactViewModel","role":"symbol","title":"ContactViewModel","kind":"symbol","url":"\/documentation\/shengwangchatuikit\/contactviewmodel"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"processFriendshipDidAddSuccessfulWithUserId:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"processFriendshipDidAddSuccessfulWithUserId:","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"processFriendshipDidAddSuccessfulWithUserId:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"userId","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactViewModel~1processFriendshipDidAddSuccessful(userId:)\/title","value":"processFriendshipDidAddSuccessfulWithUserId:"},{"value":[{"kind":"text","text":"- "},{"text":"processFriendshipDidAddSuccessfulWithUserId:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactViewModel~1processFriendshipDidAddSuccessful(userId:)\/fragments"},{"value":"ContactViewModel","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactViewModel\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactViewModel\/fragments","op":"replace","value":[{"text":"ContactViewModel","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactViewModel\/navigatorTitle","value":[{"text":"ContactViewModel","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}