{"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"paths":["\/documentation\/shengwangchatuikit\/contactviewmodel\/processfriendrequestdidreceive(userid:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/contactviewmodel\/processfriendrequestdidreceive(userid:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactViewModel\/processFriendRequestDidReceive(userId:)"},"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactViewModel"]]},"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"processFriendRequestDidReceive","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"userId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":")"}],"extendedModule":"ShengwangChatUIKit","externalID":"c:@CM@ShengwangChatUIKit@objc(cs)ContactViewModel(im)processFriendRequestDidReceiveWithUserId:","navigatorTitle":[{"kind":"identifier","text":"processFriendRequestDidReceiveWithUserId:"}],"roleHeading":"Instance Method","role":"symbol","modules":[{"name":"ShengwangChatUIKit"}],"title":"processFriendRequestDidReceive(userId:)","symbolKind":"method"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"processFriendRequestDidReceive","kind":"identifier"},{"kind":"text","text":"("},{"text":"userId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}]}]}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ContactViewModel":{"abstract":[{"text":"Bind service and driver","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ContactViewModel","kind":"identifier"}],"navigatorTitle":[{"text":"ContactViewModel","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactViewModel","role":"symbol","title":"ContactViewModel","kind":"symbol","url":"\/documentation\/shengwangchatuikit\/contactviewmodel"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ContactViewModel/processFriendRequestDidReceive(userId:)":{"kind":"symbol","title":"processFriendRequestDidReceive(userId:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"processFriendRequestDidReceive","kind":"identifier"},{"kind":"text","text":"("},{"text":"userId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"processFriendRequestDidReceiveWithUserId:"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactViewModel\/processFriendRequestDidReceive(userId:)","abstract":[],"role":"symbol","url":"\/documentation\/shengwangchatuikit\/contactviewmodel\/processfriendrequestdidreceive(userid:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","value":"processFriendRequestDidReceiveWithUserId:","path":"\/metadata\/title"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"processFriendRequestDidReceiveWithUserId:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"processFriendRequestDidReceiveWithUserId:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"userId","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactViewModel\/title","value":"ContactViewModel"},{"value":[{"text":"ContactViewModel","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactViewModel\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactViewModel\/navigatorTitle","value":[{"kind":"identifier","text":"ContactViewModel"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactViewModel~1processFriendRequestDidReceive(userId:)\/title","op":"replace","value":"processFriendRequestDidReceiveWithUserId:"},{"value":[{"kind":"text","text":"- "},{"text":"processFriendRequestDidReceiveWithUserId:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactViewModel~1processFriendRequestDidReceive(userId:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}