{"kind":"symbol","sections":[],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PresentationSegue\/initWithIdentifier:source:destination:"},"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PresentationSegue"]]},"metadata":{"navigatorTitle":[{"text":"initWithIdentifier:source:destination:","kind":"identifier"}],"externalID":"c:@M@ShengwangChatUIKit@objc(cs)PresentationSegue(im)initWithIdentifier:source:destination:","roleHeading":"Instance Method","fragments":[{"text":"- ","kind":"text"},{"text":"initWithIdentifier:source:destination:","kind":"identifier"}],"role":"symbol","title":"initWithIdentifier:source:destination:","modules":[{"name":"ShengwangChatUIKit"}],"symbolKind":"method"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"id","preciseIdentifier":"c:*Qo","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithIdentifier:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"identifier"},{"text":" ","kind":"text"},{"kind":"identifier","text":"source:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController"},{"kind":"text","text":" *) "},{"text":"source","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"destination:","kind":"identifier"},{"kind":"text","text":"("},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"destination"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/presentationsegue\/initwithidentifier:source:destination:"]}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/PresentationSegue":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PresentationSegue","title":"PresentationSegue","url":"\/documentation\/shengwangchatuikit\/presentationsegue","abstract":[],"kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"text":"PresentationSegue","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"PresentationSegue","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/PresentationSegue/initWithIdentifier:source:destination:":{"fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithIdentifier:source:destination:"}],"url":"\/documentation\/shengwangchatuikit\/presentationsegue\/initwithidentifier:source:destination:","abstract":[],"navigatorTitle":[{"text":"initWithIdentifier:source:destination:","kind":"identifier"}],"role":"symbol","kind":"symbol","title":"initWithIdentifier:source:destination:","type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PresentationSegue\/initWithIdentifier:source:destination:"}},"variantOverrides":[{"patch":[{"value":"PresentationSegue","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PresentationSegue\/title"},{"value":[{"kind":"identifier","text":"PresentationSegue"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PresentationSegue\/fragments"},{"value":[{"kind":"identifier","text":"PresentationSegue"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PresentationSegue\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}