{"metadata":{"externalID":"s:18ShengwangChatUIKit14TransitionTypeO6customyAcA21PresentationAnimationC_tcACmF","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"custom"},{"text":"(","kind":"text"},{"text":"animation","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PresentationAnimation","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)PresentationAnimation"},{"kind":"text","text":")"}],"roleHeading":"Case","title":"TransitionType.custom(animation:)","symbolKind":"case","role":"symbol","modules":[{"name":"ShengwangChatUIKit"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/TransitionType"]]},"sections":[],"variants":[{"paths":["\/documentation\/shengwangchatuikit\/transitiontype\/custom(animation:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/TransitionType\/custom(animation:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"custom","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"animation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)PresentationAnimation","text":"PresentationAnimation","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PresentationAnimation"},{"text":")","kind":"text"}],"languages":["swift"]}]}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/TransitionType/custom(animation:)":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/TransitionType\/custom(animation:)","url":"\/documentation\/shengwangchatuikit\/transitiontype\/custom(animation:)","type":"topic","abstract":[],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"custom","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"animation"},{"text":": ","kind":"text"},{"text":"PresentationAnimation","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)PresentationAnimation","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"TransitionType.custom(animation:)","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/PresentationAnimation":{"navigatorTitle":[{"text":"PresentationAnimation","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PresentationAnimation","url":"\/documentation\/shengwangchatuikit\/presentationanimation","abstract":[],"role":"symbol","kind":"symbol","type":"topic","title":"PresentationAnimation","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"PresentationAnimation","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/TransitionType":{"abstract":[],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/TransitionType","url":"\/documentation\/shengwangchatuikit\/transitiontype","role":"symbol","type":"topic","title":"TransitionType","kind":"symbol","navigatorTitle":[{"text":"TransitionType","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"TransitionType","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"PresentationAnimation","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PresentationAnimation\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PresentationAnimation\/fragments","value":[{"text":"PresentationAnimation","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"text":"PresentationAnimation","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PresentationAnimation\/navigatorTitle"}]}]}