{"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/conversationlistcontroller\/addcontact()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/conversationlistcontroller\/addcontact()"]}],"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationListController\/addContact()","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationListController"]]},"metadata":{"title":"addContact()","extendedModule":"ShengwangChatUIKit","modules":[{"name":"ShengwangChatUIKit"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"addContact"},{"kind":"text","text":"()"}],"externalID":"c:@CM@ShengwangChatUIKit@objc(cs)ConversationListController(im)addContact","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"addContact"}]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"addContact","kind":"identifier"},{"text":"()","kind":"text"}]}]},{"kind":"content","content":[{"level":2,"type":"heading","text":"Discussion","anchor":"discussion"},{"inlineContent":[{"text":"This method displays an alert dialog with a text field for the user to enter the contact ID. After the user confirms, the ","type":"text"},{"code":"addContact","type":"codeVoice"},{"type":"text","text":" method of the "},{"type":"codeVoice","code":"contactService"},{"text":" is called to add the contact. If an error occurs during the process, it is logged.","type":"text"}],"type":"paragraph"}]}],"abstract":[{"type":"text","text":"Adds a contact to the conversation list."}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ConversationListController/addContact()":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationListController\/addContact()","role":"symbol","url":"\/documentation\/shengwangchatuikit\/conversationlistcontroller\/addcontact()","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"addContact"},{"text":"()","kind":"text"}],"abstract":[{"text":"Adds a contact to the conversation list.","type":"text"}],"kind":"symbol","type":"topic","title":"addContact()","navigatorTitle":[{"text":"addContact","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ConversationListController":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationListController","kind":"symbol","title":"ConversationListController","abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"ConversationListController"},{"type":"text","text":" class implements a view controller that displays a list of conversations."},{"type":"text","text":" "},{"type":"text","text":"It inherits from "},{"code":"UIViewController","type":"codeVoice"},{"type":"text","text":"."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ConversationListController"}],"role":"symbol","navigatorTitle":[{"text":"ConversationListController","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/conversationlistcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","value":"addContact","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"addContact","kind":"identifier"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"text":") ","kind":"text"},{"kind":"identifier","text":"addContact"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"addContact","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationListController~1addContact()\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationListController~1addContact()\/fragments","value":[{"kind":"text","text":"- "},{"text":"addContact","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationListController\/title","op":"replace","value":"ConversationListController"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationListController\/fragments","op":"replace","value":[{"text":"ConversationListController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationListController\/navigatorTitle","value":[{"text":"ConversationListController","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}