{"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"@","kind":"attribute"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"chatToContact","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"profile"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatUserProfileProtocol","kind":"typeIdentifier","text":"ChatUserProfileProtocol","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(pl)ChatUserProfileProtocol"},{"text":")","kind":"text"}],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The contact profile to chat with.","type":"text"}]}],"name":"profile"}]}],"sections":[],"abstract":[{"text":"Opens a chat with the specified contact profile.","type":"text"}],"metadata":{"roleHeading":"Instance Method","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"chatToContact"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"profile"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(pl)ChatUserProfileProtocol","text":"ChatUserProfileProtocol","kind":"typeIdentifier"},{"kind":"text","text":")"}],"modules":[{"name":"ShengwangChatUIKit"}],"extendedModule":"ShengwangChatUIKit","navigatorTitle":[{"text":"chatToContactWithProfile:","kind":"identifier"}],"title":"chatToContact(profile:)","externalID":"c:@CM@ShengwangChatUIKit@objc(cs)ConversationListController(im)chatToContactWithProfile:","symbolKind":"method"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationListController\/chatToContact(profile:)"},"variants":[{"paths":["\/documentation\/shengwangchatuikit\/conversationlistcontroller\/chattocontact(profile:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/conversationlistcontroller\/chattocontact(profile:)"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationListController"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatUserProfileProtocol":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatUserProfileProtocol","abstract":[{"text":"Profile of the ChatUIKit display needed.","type":"text"}],"title":"ChatUserProfileProtocol","type":"topic","kind":"symbol","navigatorTitle":[{"text":"ChatUserProfileProtocol","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"ChatUserProfileProtocol","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/chatuserprofileprotocol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ConversationListController":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationListController","kind":"symbol","title":"ConversationListController","abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"ConversationListController"},{"type":"text","text":" class implements a view controller that displays a list of conversations."},{"type":"text","text":" "},{"type":"text","text":"It inherits from "},{"code":"UIViewController","type":"codeVoice"},{"type":"text","text":"."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ConversationListController"}],"role":"symbol","navigatorTitle":[{"text":"ConversationListController","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/conversationlistcontroller"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ConversationListController/chatToContact(profile:)":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationListController\/chatToContact(profile:)","role":"symbol","url":"\/documentation\/shengwangchatuikit\/conversationlistcontroller\/chattocontact(profile:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"chatToContact"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"profile"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(pl)ChatUserProfileProtocol","text":"ChatUserProfileProtocol","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[{"text":"Opens a chat with the specified contact profile.","type":"text"}],"kind":"symbol","type":"topic","title":"chatToContact(profile:)","navigatorTitle":[{"text":"chatToContactWithProfile:","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"chatToContactWithProfile:","path":"\/metadata\/title","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"text":"chatToContactWithProfile:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"chatToContactWithProfile:"},{"kind":"text","text":"("},{"text":"id<ChatUserProfileProtocol>","kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@ShengwangChatUIKit@objc(pl)ChatUserProfileProtocol"},{"kind":"text","text":") "},{"kind":"internalParam","text":"profile"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":{"kind":"parameters","parameters":[{"name":"profile","content":[{"type":"paragraph","inlineContent":[{"text":"The contact profile to chat with.","type":"text"}]}]}]},"path":"\/primaryContentSections\/1"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatUserProfileProtocol\/title","value":"ChatUserProfileProtocol","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatUserProfileProtocol\/fragments","op":"replace","value":[{"text":"ChatUserProfileProtocol","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"ChatUserProfileProtocol"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatUserProfileProtocol\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationListController\/title","value":"ConversationListController"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationListController\/fragments","value":[{"kind":"identifier","text":"ConversationListController"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationListController\/navigatorTitle","value":[{"text":"ConversationListController","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationListController~1chatToContact(profile:)\/title","value":"chatToContactWithProfile:"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationListController~1chatToContact(profile:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"chatToContactWithProfile:","kind":"identifier"}]}]}]}