{"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationListController\/createList()","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"role":"symbol","title":"createList()","roleHeading":"Instance Method","navigatorTitle":[{"text":"createList","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"createList","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)ConversationList","text":"ConversationList","kind":"typeIdentifier"}],"externalID":"c:@M@ShengwangChatUIKit@objc(cs)ConversationListController(im)createList","symbolKind":"method","modules":[{"name":"ShengwangChatUIKit"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"@","kind":"attribute"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createList","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"ConversationList","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationList","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)ConversationList","kind":"typeIdentifier"}],"platforms":["iOS"]}]}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/conversationlistcontroller\/createlist()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/conversationlistcontroller\/createlist()"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationListController"]]},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ConversationListController":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationListController","kind":"symbol","title":"ConversationListController","abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"ConversationListController"},{"type":"text","text":" class implements a view controller that displays a list of conversations."},{"type":"text","text":" "},{"type":"text","text":"It inherits from "},{"code":"UIViewController","type":"codeVoice"},{"type":"text","text":"."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ConversationListController"}],"role":"symbol","navigatorTitle":[{"text":"ConversationListController","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/conversationlistcontroller"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ConversationListController/createList()":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createList"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)ConversationList","text":"ConversationList","kind":"typeIdentifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationListController\/createList()","url":"\/documentation\/shengwangchatuikit\/conversationlistcontroller\/createlist()","navigatorTitle":[{"text":"createList","kind":"identifier"}],"type":"topic","title":"createList()","abstract":[],"role":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ConversationList":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationList","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ConversationList"}],"navigatorTitle":[{"text":"ConversationList","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/conversationlist","role":"symbol","kind":"symbol","title":"ConversationList","abstract":[],"type":"topic"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"createList","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"createList","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"ConversationList","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationList","kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)ConversationList"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"createList"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationListController\/title","value":"ConversationListController"},{"op":"replace","value":[{"kind":"identifier","text":"ConversationListController"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationListController\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationListController\/navigatorTitle","value":[{"text":"ConversationListController","kind":"identifier"}]},{"value":"createList","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationListController~1createList()\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"createList"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationListController~1createList()\/fragments"},{"op":"replace","value":"ConversationList","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationList\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationList\/fragments","value":[{"text":"ConversationList","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationList\/navigatorTitle","value":[{"kind":"identifier","text":"ConversationList"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}