{"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/Appearance\/ease_chat_language","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"EaseChatUIKit‘s language type."}],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ease_chat_language"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:18ShengwangChatUIKit12LanguageTypeO","kind":"typeIdentifier","text":"LanguageType"}],"externalID":"s:18ShengwangChatUIKit10AppearanceC18ease_chat_languageAA12LanguageTypeOvpZ","modules":[{"name":"ShengwangChatUIKit"}],"roleHeading":"Type Property","symbolKind":"property","title":"ease_chat_language","role":"symbol"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/Appearance"]]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/appearance\/ease_chat_language"]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"ease_chat_language","kind":"identifier"},{"text":": ","kind":"text"},{"text":"LanguageType","kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit12LanguageTypeO","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/LanguageType"}]}],"kind":"declarations"}],"kind":"symbol","references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/Appearance":{"navigatorTitle":[{"kind":"identifier","text":"Appearance"}],"type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/Appearance","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Appearance","kind":"identifier"}],"title":"Appearance","abstract":[{"type":"text","text":"An object containing visual configurations for the whole application."}],"url":"\/documentation\/shengwangchatuikit\/appearance"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/Appearance/ease_chat_language":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/Appearance\/ease_chat_language","url":"\/documentation\/shengwangchatuikit\/appearance\/ease_chat_language","type":"topic","abstract":[{"type":"text","text":"EaseChatUIKit‘s language type."}],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ease_chat_language","kind":"identifier"},{"kind":"text","text":": "},{"text":"LanguageType","kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit12LanguageTypeO"}],"title":"ease_chat_language","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/LanguageType":{"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"LanguageType"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/LanguageType","title":"LanguageType","navigatorTitle":[{"text":"LanguageType","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/languagetype","abstract":[{"text":"https:\/\/learn.microsoft.com\/en-us\/azure\/ai-services\/translator\/language-support#translation","type":"text"}],"type":"topic","kind":"symbol","role":"symbol"}},"variantOverrides":[{"patch":[{"value":"Appearance","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1Appearance\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1Appearance\/fragments","value":[{"text":"Appearance","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1Appearance\/navigatorTitle","value":[{"kind":"identifier","text":"Appearance"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}