{"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/appearance\/primaryhue"]},{"paths":["\/documentation\/shengwangchatuikit\/appearance\/primaryhue"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/Appearance\/primaryHue","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/Appearance"]]},"metadata":{"roleHeading":"Type Property","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"primaryHue","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"}],"modules":[{"name":"ShengwangChatUIKit"}],"navigatorTitle":[{"text":"primaryHue","kind":"identifier"}],"externalID":"c:@M@ShengwangChatUIKit@objc(cs)Appearance(cpy)primaryHue","title":"primaryHue","symbolKind":"property"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"primaryHue"},{"text":": ","kind":"text"},{"text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"abstract":[{"type":"text","text":"You can change the hue of the base color, and then change the thirteen UIColor objects of the related color series. The UI components that use the relevant color series in the ease chat UIKit will also change accordingly. The default value is 203\/360.0."}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/Appearance/primaryHue":{"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"primaryHue"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"}],"type":"topic","role":"symbol","abstract":[{"type":"text","text":"You can change the hue of the base color, and then change the thirteen UIColor objects of the related color series. The UI components that use the relevant color series in the ease chat UIKit will also change accordingly. The default value is 203\/360.0."}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"primaryHue"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/Appearance\/primaryHue","url":"\/documentation\/shengwangchatuikit\/appearance\/primaryhue","title":"primaryHue"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/Appearance":{"navigatorTitle":[{"kind":"identifier","text":"Appearance"}],"type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/Appearance","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Appearance","kind":"identifier"}],"title":"Appearance","abstract":[{"type":"text","text":"An object containing visual configurations for the whole application."}],"url":"\/documentation\/shengwangchatuikit\/appearance"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Type Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"primaryHue","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"primaryHue","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"class"},{"text":", ","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@CGFloat","text":"CGFloat"},{"text":" ","kind":"text"},{"kind":"identifier","text":"primaryHue"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"primaryHue","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1Appearance~1primaryHue\/title"},{"value":[{"text":"primaryHue","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1Appearance~1primaryHue\/fragments","op":"replace"},{"op":"replace","value":"Appearance","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1Appearance\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1Appearance\/fragments","value":[{"kind":"identifier","text":"Appearance"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1Appearance\/navigatorTitle","value":[{"kind":"identifier","text":"Appearance"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}