{"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/triangleview\/setdirection(direction:color:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/triangleview\/setdirection(direction:color:)"]}],"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","kind":"attribute","text":"MainActor"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setDirection"},{"text":"(","kind":"text"},{"text":"direction","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TriangleDirection","preciseIdentifier":"c:@M@ShengwangChatUIKit@E@TriangleDirection","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/TriangleDirection"},{"text":", ","kind":"text"},{"text":"color","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":")"}],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/TriangleView\/setDirection(direction:color:)","interfaceLanguage":"swift"},"sections":[],"metadata":{"symbolKind":"method","navigatorTitle":[{"text":"setDirectionWithDirection:color:","kind":"identifier"}],"role":"symbol","modules":[{"name":"ShengwangChatUIKit"}],"roleHeading":"Instance Method","externalID":"c:@M@ShengwangChatUIKit@objc(cs)TriangleView(im)setDirectionWithDirection:color:","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setDirection","kind":"identifier"},{"text":"(","kind":"text"},{"text":"direction","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@E@TriangleDirection","kind":"typeIdentifier","text":"TriangleDirection"},{"kind":"text","text":", "},{"kind":"externalParam","text":"color"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"},{"kind":"text","text":")"}],"title":"setDirection(direction:color:)"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/TriangleView"]]},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/TriangleView/setDirection(direction:color:)":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/TriangleView\/setDirection(direction:color:)","abstract":[],"navigatorTitle":[{"text":"setDirectionWithDirection:color:","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/shengwangchatuikit\/triangleview\/setdirection(direction:color:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setDirection"},{"kind":"text","text":"("},{"kind":"externalParam","text":"direction"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@E@TriangleDirection","text":"TriangleDirection","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"color","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"text":")","kind":"text"}],"title":"setDirection(direction:color:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/TriangleDirection":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/TriangleDirection","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"TriangleDirection","kind":"identifier"}],"title":"TriangleDirection","type":"topic","role":"symbol","url":"\/documentation\/shengwangchatuikit\/triangledirection","kind":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"TriangleDirection"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/TriangleView":{"title":"TriangleView","navigatorTitle":[{"text":"TriangleView","kind":"identifier"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/TriangleView","type":"topic","url":"\/documentation\/shengwangchatuikit\/triangleview","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TriangleView"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"setDirectionWithDirection:color:","path":"\/metadata\/title"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"setDirectionWithDirection:color:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"setDirectionWithDirection:"},{"text":"(","kind":"text"},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/TriangleDirection","preciseIdentifier":"c:@M@ShengwangChatUIKit@E@TriangleDirection","kind":"typeIdentifier","text":"TriangleDirection"},{"text":") ","kind":"text"},{"text":"direction","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"color:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":" *) "},{"text":"color","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"value":"setDirectionWithDirection:color:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1TriangleView~1setDirection(direction:color:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1TriangleView~1setDirection(direction:color:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"setDirectionWithDirection:color:","kind":"identifier"}]},{"op":"replace","value":"TriangleDirection","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1TriangleDirection\/title"},{"value":[{"text":"TriangleDirection","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1TriangleDirection\/fragments"},{"op":"replace","value":[{"text":"TriangleDirection","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1TriangleDirection\/navigatorTitle"},{"value":"TriangleView","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1TriangleView\/title"},{"value":[{"kind":"identifier","text":"TriangleView"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1TriangleView\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1TriangleView\/navigatorTitle","value":[{"text":"TriangleView","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}