{"metadata":{"navigatorTitle":[{"kind":"identifier","text":"initWithStyle:reuseIdentifier:"}],"title":"init(style:reuseIdentifier:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"style"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UITableViewCell","kind":"typeIdentifier","text":"UITableViewCell"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@UITableViewCellStyle","text":"CellStyle"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"reuseIdentifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?)","kind":"text"}],"externalID":"c:@M@ShengwangChatUIKit@objc(cs)NewContactRequestCell(im)initWithStyle:reuseIdentifier:","symbolKind":"init","roleHeading":"Initializer","role":"symbol","modules":[{"name":"ShengwangChatUIKit"}]},"kind":"symbol","sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"style","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITableViewCell","text":"UITableViewCell"},{"text":".","kind":"text"},{"text":"CellStyle","kind":"typeIdentifier","preciseIdentifier":"c:@E@UITableViewCellStyle"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"reuseIdentifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?)"}],"languages":["swift"],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/NewContactRequestCell"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/NewContactRequestCell\/init(style:reuseIdentifier:)","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/shengwangchatuikit\/newcontactrequestcell\/init(style:reuseidentifier:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/newcontactrequestcell\/init(style:reuseidentifier:)"]}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/NewContactRequestCell":{"title":"NewContactRequestCell","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NewContactRequestCell"}],"url":"\/documentation\/shengwangchatuikit\/newcontactrequestcell","kind":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/NewContactRequestCell","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"NewContactRequestCell"}],"role":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/NewContactRequestCell/init(style:reuseIdentifier:)":{"abstract":[],"kind":"symbol","url":"\/documentation\/shengwangchatuikit\/newcontactrequestcell\/init(style:reuseidentifier:)","navigatorTitle":[{"text":"initWithStyle:reuseIdentifier:","kind":"identifier"}],"title":"init(style:reuseIdentifier:)","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/NewContactRequestCell\/init(style:reuseIdentifier:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"style"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITableViewCell","preciseIdentifier":"c:objc(cs)UITableViewCell"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@UITableViewCellStyle","text":"CellStyle"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"reuseIdentifier"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"type":"topic"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"initWithStyle:reuseIdentifier:","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithStyle:reuseIdentifier:"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithStyle:"},{"text":"(","kind":"text"},{"text":"UITableViewCellStyle","preciseIdentifier":"c:@E@UITableViewCellStyle","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"style"},{"text":" ","kind":"text"},{"kind":"identifier","text":"reuseIdentifier:"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"reuseIdentifier","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}},{"value":"NewContactRequestCell","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1NewContactRequestCell\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1NewContactRequestCell\/fragments","value":[{"text":"NewContactRequestCell","kind":"identifier"}],"op":"replace"},{"value":[{"text":"NewContactRequestCell","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1NewContactRequestCell\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1NewContactRequestCell~1init(style:reuseIdentifier:)\/title","value":"initWithStyle:reuseIdentifier:"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1NewContactRequestCell~1init(style:reuseIdentifier:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithStyle:reuseIdentifier:"}]}]}]}