{"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationInfo"]]},"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationInfo\/convertStatus(message:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/conversationinfo\/convertstatus(message:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/conversationinfo\/convertstatus(message:)"]}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"convertStatusWithMessage:"}],"symbolKind":"method","externalID":"c:@M@ShengwangChatUIKit@objc(cs)ConversationInfo(im)convertStatusWithMessage:","modules":[{"name":"ShengwangChatUIKit"}],"role":"symbol","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"convertStatus","kind":"identifier"},{"kind":"text","text":"("},{"text":"message","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ChatMessage","preciseIdentifier":"s:18ShengwangChatUIKit0B7Messagea","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@E@ChatMessageStatus","text":"ChatMessageStatus","kind":"typeIdentifier"}],"title":"convertStatus(message:)"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"convertStatus","kind":"identifier"},{"kind":"text","text":"("},{"text":"message","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:18ShengwangChatUIKit0B7Messagea","text":"ChatMessage","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatMessage","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@E@ChatMessageStatus","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatMessageStatus","text":"ChatMessageStatus"}],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatMessageStatus":{"title":"ChatMessageStatus","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChatMessageStatus"}],"url":"\/documentation\/shengwangchatuikit\/chatmessagestatus","role":"symbol","abstract":[{"text":"The status of ","type":"text"},{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatMessage","type":"reference","isActive":true},{"type":"text","text":"."}],"type":"topic","navigatorTitle":[{"text":"ChatMessageStatus","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatMessageStatus"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ConversationInfo/convertStatus(message:)":{"url":"\/documentation\/shengwangchatuikit\/conversationinfo\/convertstatus(message:)","abstract":[],"kind":"symbol","navigatorTitle":[{"text":"convertStatusWithMessage:","kind":"identifier"}],"type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationInfo\/convertStatus(message:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"convertStatus"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"message"},{"text":": ","kind":"text"},{"text":"ChatMessage","kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit0B7Messagea"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@E@ChatMessageStatus","kind":"typeIdentifier","text":"ChatMessageStatus"}],"title":"convertStatus(message:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ConversationInfo":{"title":"ConversationInfo","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ConversationInfo","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/conversationinfo","role":"symbol","abstract":[],"type":"topic","navigatorTitle":[{"text":"ConversationInfo","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationInfo"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatMessage":{"url":"\/documentation\/shengwangchatuikit\/chatmessage","abstract":[],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ChatMessage"}],"type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatMessage","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChatMessage"}],"title":"ChatMessage"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"convertStatusWithMessage:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"convertStatusWithMessage:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatMessageStatus","text":"ChatMessageStatus","preciseIdentifier":"c:@M@ShengwangChatUIKit@E@ChatMessageStatus"},{"kind":"text","text":") "},{"text":"convertStatusWithMessage:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)AgoraChatMessage","kind":"typeIdentifier","text":"AgoraChatMessage"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"message"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatMessageStatus\/title","value":"ChatMessageStatus"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatMessageStatus\/fragments","value":[{"text":"ChatMessageStatus","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatMessageStatus\/navigatorTitle","value":[{"kind":"identifier","text":"ChatMessageStatus"}]},{"value":"convertStatusWithMessage:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationInfo~1convertStatus(message:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationInfo~1convertStatus(message:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"convertStatusWithMessage:"}]},{"value":"ConversationInfo","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationInfo\/title","op":"replace"},{"value":[{"kind":"identifier","text":"ConversationInfo"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationInfo\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationInfo\/navigatorTitle","value":[{"text":"ConversationInfo","kind":"identifier"}]}]}]}