{"abstract":[{"type":"text","text":"Inherited from "},{"code":"ChatUserProfileProtocol.toJsonObject()","type":"codeVoice"},{"type":"text","text":"."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"toJsonObject"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:SD","text":"Dictionary","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":">?","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/conversationinfo\/tojsonobject()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/conversationinfo\/tojsonobject()"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationInfo"]]},"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationInfo\/toJsonObject()","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"roleHeading":"Instance Method","modules":[{"name":"ShengwangChatUIKit"}],"navigatorTitle":[{"text":"toJsonObject","kind":"identifier"}],"externalID":"c:@M@ShengwangChatUIKit@objc(cs)ConversationInfo(im)toJsonObject","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"toJsonObject"},{"text":"() -> ","kind":"text"},{"text":"Dictionary","kind":"typeIdentifier","preciseIdentifier":"s:SD"},{"kind":"text","text":"<"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"keyword","text":"Any"},{"text":">?","kind":"text"}],"title":"toJsonObject()","role":"symbol"},"sections":[],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ConversationInfo/toJsonObject()":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationInfo\/toJsonObject()","url":"\/documentation\/shengwangchatuikit\/conversationinfo\/tojsonobject()","abstract":[],"kind":"symbol","type":"topic","title":"toJsonObject()","navigatorTitle":[{"kind":"identifier","text":"toJsonObject"}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"toJsonObject"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:SD","text":"Dictionary","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":">?","kind":"text"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ConversationInfo":{"title":"ConversationInfo","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ConversationInfo","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/conversationinfo","role":"symbol","abstract":[],"type":"topic","navigatorTitle":[{"text":"ConversationInfo","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationInfo"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"toJsonObject"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"toJsonObject"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:Q$objc(cs)NSDictionary","kind":"typeIdentifier","text":"NSDictionary<NSString *,id>"},{"kind":"text","text":" *) "},{"text":"toJsonObject","kind":"identifier"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"toJsonObject","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationInfo~1toJsonObject()\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationInfo~1toJsonObject()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"toJsonObject"}],"op":"replace"},{"op":"replace","value":"ConversationInfo","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationInfo\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationInfo\/fragments","op":"replace","value":[{"kind":"identifier","text":"ConversationInfo"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationInfo\/navigatorTitle","value":[{"text":"ConversationInfo","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}