{"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UIContextualActionChatUIKit\/init(title:style:actionType:handler:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/uicontextualactionchatuikit\/init(title:style:actiontype:handler:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/uicontextualactionchatuikit\/init(title:style:actiontype:handler:)"]}],"sections":[],"metadata":{"roleHeading":"Initializer","navigatorTitle":[{"text":"initWithTitle:style:actionType:handler:","kind":"identifier"}],"role":"symbol","title":"init(title:style:actionType:handler:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"title","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"style"},{"text":": ","kind":"text"},{"text":"UIContextualAction","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIContextualAction"},{"text":".","kind":"text"},{"text":"Style","preciseIdentifier":"c:@E@UIContextualActionStyle","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"actionType","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIContextualActionType","kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@E@UIContextualActionType"},{"text":", ","kind":"text"},{"text":"handler","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIContextualAction","preciseIdentifier":"c:objc(cs)UIContextualAction"},{"text":".","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@UIContextualActionHandler","text":"Handler"},{"kind":"text","text":")"}],"modules":[{"name":"ShengwangChatUIKit"}],"externalID":"c:@M@ShengwangChatUIKit@objc(cs)UIContextualActionChatUIKit(im)initWithTitle:style:actionType:handler:","symbolKind":"init"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"attribute","text":"@"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"required"},{"text":" ","kind":"text"},{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"title"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"text":"style","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIContextualAction","preciseIdentifier":"c:objc(cs)UIContextualAction"},{"text":".","kind":"text"},{"text":"Style","kind":"typeIdentifier","preciseIdentifier":"c:@E@UIContextualActionStyle"},{"text":", ","kind":"text"},{"text":"actionType","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UIContextualActionType","text":"UIContextualActionType","preciseIdentifier":"c:@M@ShengwangChatUIKit@E@UIContextualActionType"},{"kind":"text","text":", "},{"text":"handler","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","text":"UIContextualAction","preciseIdentifier":"c:objc(cs)UIContextualAction"},{"text":".","kind":"text"},{"text":"Handler","preciseIdentifier":"c:@T@UIContextualActionHandler","kind":"typeIdentifier"},{"kind":"text","text":")"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UIContextualActionChatUIKit"]]},"kind":"symbol","references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/UIContextualActionChatUIKit":{"url":"\/documentation\/shengwangchatuikit\/uicontextualactionchatuikit","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UIContextualActionChatUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"UIContextualActionChatUIKit"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UIContextualActionChatUIKit","type":"topic","title":"UIContextualActionChatUIKit"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/UIContextualActionType":{"navigatorTitle":[{"kind":"identifier","text":"UIContextualActionType"}],"abstract":[],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"UIContextualActionType","kind":"identifier"}],"type":"topic","url":"\/documentation\/shengwangchatuikit\/uicontextualactiontype","kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UIContextualActionType","title":"UIContextualActionType"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/UIContextualActionChatUIKit/init(title:style:actionType:handler:)":{"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"title","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"text":"style","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIContextualAction","text":"UIContextualAction"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@E@UIContextualActionStyle","text":"Style","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"actionType"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@E@UIContextualActionType","text":"UIContextualActionType","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"handler"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIContextualAction","kind":"typeIdentifier","text":"UIContextualAction"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@T@UIContextualActionHandler","text":"Handler","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","abstract":[],"role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UIContextualActionChatUIKit\/init(title:style:actionType:handler:)","title":"init(title:style:actionType:handler:)","navigatorTitle":[{"kind":"identifier","text":"initWithTitle:style:actionType:handler:"}],"url":"\/documentation\/shengwangchatuikit\/uicontextualactionchatuikit\/init(title:style:actiontype:handler:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","value":"initWithTitle:style:actionType:handler:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithTitle:style:actionType:handler:"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","kind":"typeIdentifier","text":"id"},{"text":") ","kind":"text"},{"text":"initWithTitle:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"text":"title","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"style:"},{"kind":"text","text":"("},{"text":"UIContextualActionStyle","preciseIdentifier":"c:@E@UIContextualActionStyle","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"style","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"actionType:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UIContextualActionType","text":"UIContextualActionType","preciseIdentifier":"c:@M@ShengwangChatUIKit@E@UIContextualActionType"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"actionType"},{"kind":"text","text":" "},{"text":"handler:","kind":"identifier"},{"kind":"text","text":"("},{"text":"void (^)(UIContextualAction *, __kindof UIView *, void (^)(_Bool))","kind":"typeIdentifier","preciseIdentifier":"c:BFv(#*$objc(cs)UIContextualAction#*Q$objc(cs)UIView#BFv(#b))"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"handler"},{"kind":"text","text":";"}]}]}},{"op":"replace","value":"UIContextualActionChatUIKit","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1UIContextualActionChatUIKit\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1UIContextualActionChatUIKit\/fragments","value":[{"text":"UIContextualActionChatUIKit","kind":"identifier"}]},{"value":[{"text":"UIContextualActionChatUIKit","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1UIContextualActionChatUIKit\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1UIContextualActionType\/title","value":"UIContextualActionType","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1UIContextualActionType\/fragments","value":[{"text":"UIContextualActionType","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1UIContextualActionType\/navigatorTitle","op":"replace","value":[{"text":"UIContextualActionType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1UIContextualActionChatUIKit~1init(title:style:actionType:handler:)\/title","value":"initWithTitle:style:actionType:handler:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"initWithTitle:style:actionType:handler:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1UIContextualActionChatUIKit~1init(title:style:actionType:handler:)\/fragments","op":"replace"}]}]}