{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/IMessageListViewDriver"]]},"variants":[{"paths":["\/documentation\/shengwangchatuikit\/imessagelistviewdriver\/updatethreadloadmessagesfinished(finished:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/imessagelistviewdriver\/updatethreadloadmessagesfinished(finished:)"]}],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateThreadLoadMessagesFinished"},{"kind":"text","text":"("},{"text":"finished","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":")","kind":"text"}]}]},{"kind":"parameters","parameters":[{"name":"finished","content":[{"inlineContent":[{"type":"text","text":"Bool"}],"type":"paragraph"}]}]}],"metadata":{"modules":[{"name":"ShengwangChatUIKit"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"updateThreadLoadMessagesFinished"},{"kind":"text","text":"("},{"text":"finished","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"role":"symbol","required":true,"title":"updateThreadLoadMessagesFinished(finished:)","symbolKind":"method","roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"updateThreadLoadMessagesFinishedWithFinished:"}],"externalID":"c:@M@ShengwangChatUIKit@objc(pl)IMessageListViewDriver(im)updateThreadLoadMessagesFinishedWithFinished:"},"abstract":[{"type":"text","text":"Update state on chat thread load messages finished."}],"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/IMessageListViewDriver\/updateThreadLoadMessagesFinished(finished:)","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/IMessageListViewDriver/updateThreadLoadMessagesFinished(finished:)":{"url":"\/documentation\/shengwangchatuikit\/imessagelistviewdriver\/updatethreadloadmessagesfinished(finished:)","abstract":[{"type":"text","text":"Update state on chat thread load messages finished."}],"kind":"symbol","navigatorTitle":[{"text":"updateThreadLoadMessagesFinishedWithFinished:","kind":"identifier"}],"type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/IMessageListViewDriver\/updateThreadLoadMessagesFinished(finished:)","required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"updateThreadLoadMessagesFinished"},{"text":"(","kind":"text"},{"text":"finished","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":")","kind":"text"}],"title":"updateThreadLoadMessagesFinished(finished:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/IMessageListViewDriver":{"kind":"symbol","role":"symbol","type":"topic","abstract":[],"navigatorTitle":[{"text":"IMessageListViewDriver","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"IMessageListViewDriver","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/imessagelistviewdriver","title":"IMessageListViewDriver","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/IMessageListViewDriver"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"updateThreadLoadMessagesFinishedWithFinished:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"updateThreadLoadMessagesFinishedWithFinished:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"updateThreadLoadMessagesFinishedWithFinished:"},{"text":"(","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"finished"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/primaryContentSections\/1","value":{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"Bool"}],"type":"paragraph"}],"name":"finished"}],"kind":"parameters"},"op":"replace"},{"value":"updateThreadLoadMessagesFinishedWithFinished:","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1IMessageListViewDriver~1updateThreadLoadMessagesFinished(finished:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1IMessageListViewDriver~1updateThreadLoadMessagesFinished(finished:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"updateThreadLoadMessagesFinishedWithFinished:","kind":"identifier"}]},{"value":"IMessageListViewDriver","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1IMessageListViewDriver\/title","op":"replace"},{"value":[{"kind":"identifier","text":"IMessageListViewDriver"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1IMessageListViewDriver\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"IMessageListViewDriver"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1IMessageListViewDriver\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}