{"kind":"symbol","metadata":{"modules":[{"name":"ShengwangChatUIKit"}],"roleHeading":"Instance Method","navigatorTitle":[{"text":"pop","kind":"identifier"}],"externalID":"c:@M@ShengwangChatUIKit@objc(cs)BlockContactsViewController(im)pop","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"pop"},{"text":"()","kind":"text"}],"title":"pop()","role":"symbol"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/BlockContactsViewController"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"@","kind":"attribute"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"pop"},{"text":"()","kind":"text"}],"platforms":["iOS"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/BlockContactsViewController\/pop()"},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/blockcontactsviewcontroller\/pop()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/blockcontactsviewcontroller\/pop()"]}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/BlockContactsViewController":{"abstract":[],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/BlockContactsViewController","url":"\/documentation\/shengwangchatuikit\/blockcontactsviewcontroller","navigatorTitle":[{"text":"BlockContactsViewController","kind":"identifier"}],"kind":"symbol","title":"BlockContactsViewController","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BlockContactsViewController","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/BlockContactsViewController/pop()":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/BlockContactsViewController\/pop()","navigatorTitle":[{"kind":"identifier","text":"pop"}],"url":"\/documentation\/shengwangchatuikit\/blockcontactsviewcontroller\/pop()","type":"topic","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"pop"},{"kind":"text","text":"()"}],"title":"pop()","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"pop"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"pop","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"pop"},{"text":";","kind":"text"}]}]},"op":"replace"},{"value":"BlockContactsViewController","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1BlockContactsViewController\/title"},{"value":[{"kind":"identifier","text":"BlockContactsViewController"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1BlockContactsViewController\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1BlockContactsViewController\/navigatorTitle","op":"replace","value":[{"text":"BlockContactsViewController","kind":"identifier"}]},{"value":"pop","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1BlockContactsViewController~1pop()\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1BlockContactsViewController~1pop()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"pop"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}