{"kind":"symbol","sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"text":"When some view Implement the protocol method,you can use ","type":"text"},{"code":"Theme.switchTheme(style: .dark)","type":"codeVoice"},{"type":"text","text":" to switch theme."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"switchTheme","kind":"identifier"},{"text":"(","kind":"text"},{"text":"style","kind":"externalParam"},{"kind":"text","text":": "},{"text":"ThemeStyle","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ThemeStyle","kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@E@ThemeStyle"},{"text":")","kind":"text"}]}]},{"kind":"parameters","parameters":[{"name":"style","content":[{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ThemeStyle","isActive":true,"type":"reference"}]}]}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/BlockContactsViewController\/switchTheme(style:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/blockcontactsviewcontroller\/switchtheme(style:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/blockcontactsviewcontroller\/switchtheme(style:)"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/BlockContactsViewController","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/BlockContactsViewController\/ThemeSwitchProtocol-Implementations"]]},"metadata":{"roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"switchTheme","kind":"identifier"},{"text":"(","kind":"text"},{"text":"style","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@E@ThemeStyle","text":"ThemeStyle"},{"text":")","kind":"text"}],"extendedModule":"ShengwangChatUIKit","modules":[{"name":"ShengwangChatUIKit"}],"externalID":"c:@CM@ShengwangChatUIKit@objc(cs)BlockContactsViewController(im)switchThemeWithStyle:","role":"symbol","title":"switchTheme(style:)","symbolKind":"method","navigatorTitle":[{"text":"switchThemeWithStyle:","kind":"identifier"}]},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/Appearance":{"navigatorTitle":[{"kind":"identifier","text":"Appearance"}],"type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/Appearance","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Appearance","kind":"identifier"}],"title":"Appearance","abstract":[{"type":"text","text":"An object containing visual configurations for the whole application."}],"url":"\/documentation\/shengwangchatuikit\/appearance"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/BlockContactsViewController":{"abstract":[],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/BlockContactsViewController","url":"\/documentation\/shengwangchatuikit\/blockcontactsviewcontroller","navigatorTitle":[{"text":"BlockContactsViewController","kind":"identifier"}],"kind":"symbol","title":"BlockContactsViewController","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BlockContactsViewController","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ThemeStyle":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"ThemeStyle"}],"title":"ThemeStyle","url":"\/documentation\/shengwangchatuikit\/themestyle","abstract":[{"type":"text","text":"Contain light and dark themes of the ease chat UIKit.If you want to switch custom theme,you’ll modify primary&secondary&error&neutral&neutralSpecial hues properties in "},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/Appearance"},{"type":"text","text":".Then call "},{"type":"codeVoice","code":"Theme.switchTheme(style: .custom)"},{"type":"text","text":" method"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ThemeStyle","kind":"symbol","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ThemeStyle"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/BlockContactsViewController/switchTheme(style:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"switchTheme"},{"text":"(","kind":"text"},{"text":"style","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"ThemeStyle","preciseIdentifier":"c:@M@ShengwangChatUIKit@E@ThemeStyle"},{"text":")","kind":"text"}],"abstract":[{"text":"When some view Implement the protocol method,you can use ","type":"text"},{"type":"codeVoice","code":"Theme.switchTheme(style: .dark)"},{"text":" to switch theme.","type":"text"}],"type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/BlockContactsViewController\/switchTheme(style:)","kind":"symbol","title":"switchTheme(style:)","navigatorTitle":[{"kind":"identifier","text":"switchThemeWithStyle:"}],"url":"\/documentation\/shengwangchatuikit\/blockcontactsviewcontroller\/switchtheme(style:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/BlockContactsViewController/ThemeSwitchProtocol-Implementations":{"abstract":[],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/BlockContactsViewController\/ThemeSwitchProtocol-Implementations","url":"\/documentation\/shengwangchatuikit\/blockcontactsviewcontroller\/themeswitchprotocol-implementations","kind":"article","title":"ThemeSwitchProtocol Implementations","role":"collectionGroup","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","value":"switchThemeWithStyle:","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"switchThemeWithStyle:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"text":"switchThemeWithStyle:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"ThemeStyle","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ThemeStyle","kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@E@ThemeStyle"},{"kind":"text","text":") "},{"kind":"internalParam","text":"style"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1Appearance\/title","value":"Appearance"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1Appearance\/fragments","value":[{"kind":"identifier","text":"Appearance"}],"op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"Appearance"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1Appearance\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1BlockContactsViewController\/title","value":"BlockContactsViewController","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1BlockContactsViewController\/fragments","value":[{"kind":"identifier","text":"BlockContactsViewController"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1BlockContactsViewController\/navigatorTitle","value":[{"text":"BlockContactsViewController","kind":"identifier"}],"op":"replace"},{"value":"ThemeStyle","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ThemeStyle\/title"},{"op":"replace","value":[{"text":"ThemeStyle","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ThemeStyle\/fragments"},{"value":[{"text":"ThemeStyle","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ThemeStyle\/navigatorTitle"},{"value":"switchThemeWithStyle:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1BlockContactsViewController~1switchTheme(style:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1BlockContactsViewController~1switchTheme(style:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"switchThemeWithStyle:","kind":"identifier"}]}]}]}