{"variants":[{"paths":["\/documentation\/shengwangchatuikit\/reactionusercell\/createcheckbox()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/reactionusercell\/createcheckbox()"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ReactionUserCell"]]},"kind":"symbol","metadata":{"roleHeading":"Instance Method","symbolKind":"method","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"createCheckbox"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"c:objc(cs)UIImageView","kind":"typeIdentifier","text":"UIImageView"}],"externalID":"c:@M@ShengwangChatUIKit@objc(cs)ReactionUserCell(im)createCheckbox","title":"createCheckbox()","navigatorTitle":[{"text":"createCheckbox","kind":"identifier"}],"modules":[{"name":"ShengwangChatUIKit"}]},"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ReactionUserCell\/createCheckbox()","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"attribute","text":"@"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"createCheckbox","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImageView","text":"UIImageView","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ReactionUserCell/createCheckbox()":{"kind":"symbol","url":"\/documentation\/shengwangchatuikit\/reactionusercell\/createcheckbox()","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"createCheckbox","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"UIImageView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImageView"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ReactionUserCell\/createCheckbox()","title":"createCheckbox()","navigatorTitle":[{"kind":"identifier","text":"createCheckbox"}],"abstract":[]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ReactionUserCell":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ReactionUserCell","kind":"identifier"}],"kind":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"ReactionUserCell"}],"url":"\/documentation\/shengwangchatuikit\/reactionusercell","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ReactionUserCell","type":"topic","role":"symbol","title":"ReactionUserCell"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"createCheckbox"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"text":"createCheckbox","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"UIImageView","preciseIdentifier":"c:objc(cs)UIImageView","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"createCheckbox"},{"kind":"text","text":";"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ReactionUserCell~1createCheckbox()\/title","op":"replace","value":"createCheckbox"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"createCheckbox","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ReactionUserCell~1createCheckbox()\/fragments"},{"op":"replace","value":"ReactionUserCell","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ReactionUserCell\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ReactionUserCell\/fragments","op":"replace","value":[{"text":"ReactionUserCell","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"ReactionUserCell"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ReactionUserCell\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}