{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"override"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"frame","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGRect","text":"CGRect","kind":"typeIdentifier"},{"text":")","kind":"text"}]}]}],"variants":[{"paths":["\/documentation\/shengwangchatuikit\/popmenucollectionviewcell\/init(frame:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/shengwangchatuikit\/popmenucollectionviewcell\/init(frame:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PopMenuCollectionViewCell"]]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PopMenuCollectionViewCell\/init(frame:)"},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"metadata":{"symbolKind":"init","title":"init(frame:)","roleHeading":"Initializer","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"frame","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CGRect","text":"CGRect","kind":"typeIdentifier"},{"text":")","kind":"text"}],"modules":[{"name":"ShengwangChatUIKit"}],"externalID":"c:@M@ShengwangChatUIKit@objc(cs)PopMenuCollectionViewCell(im)initWithFrame:","navigatorTitle":[{"kind":"identifier","text":"initWithFrame:"}]},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/PopMenuCollectionViewCell/init(frame:)":{"type":"topic","navigatorTitle":[{"text":"initWithFrame:","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/popmenucollectionviewcell\/init(frame:)","kind":"symbol","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"frame"},{"text":": ","kind":"text"},{"text":"CGRect","preciseIdentifier":"c:@S@CGRect","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[],"title":"init(frame:)","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PopMenuCollectionViewCell\/init(frame:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/PopMenuCollectionViewCell":{"role":"symbol","url":"\/documentation\/shengwangchatuikit\/popmenucollectionviewcell","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"PopMenuCollectionViewCell"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PopMenuCollectionViewCell","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PopMenuCollectionViewCell"}],"kind":"symbol","title":"PopMenuCollectionViewCell"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"initWithFrame:","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithFrame:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"text":"initWithFrame:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":") "},{"kind":"internalParam","text":"frame"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"value":"initWithFrame:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PopMenuCollectionViewCell~1init(frame:)\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithFrame:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PopMenuCollectionViewCell~1init(frame:)\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PopMenuCollectionViewCell\/title","value":"PopMenuCollectionViewCell","op":"replace"},{"op":"replace","value":[{"text":"PopMenuCollectionViewCell","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PopMenuCollectionViewCell\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PopMenuCollectionViewCell\/navigatorTitle","value":[{"kind":"identifier","text":"PopMenuCollectionViewCell"}]}]}]}