{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/popmenucollectionviewcell\/layoutsubviews()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/popmenucollectionviewcell\/layoutsubviews()"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PopMenuCollectionViewCell"]]},"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"text":" ","kind":"text"},{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"layoutSubviews","kind":"identifier"},{"kind":"text","text":"()"}],"platforms":["iOS"],"languages":["swift"]}]}],"metadata":{"roleHeading":"Instance Method","title":"layoutSubviews()","navigatorTitle":[{"kind":"identifier","text":"layoutSubviews"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"layoutSubviews","kind":"identifier"},{"kind":"text","text":"()"}],"externalID":"c:@M@ShengwangChatUIKit@objc(cs)PopMenuCollectionViewCell(im)layoutSubviews","modules":[{"name":"ShengwangChatUIKit"}],"symbolKind":"method"},"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PopMenuCollectionViewCell\/layoutSubviews()","interfaceLanguage":"swift"},"sections":[],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/PopMenuCollectionViewCell/layoutSubviews()":{"abstract":[],"title":"layoutSubviews()","type":"topic","role":"symbol","url":"\/documentation\/shengwangchatuikit\/popmenucollectionviewcell\/layoutsubviews()","kind":"symbol","navigatorTitle":[{"text":"layoutSubviews","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PopMenuCollectionViewCell\/layoutSubviews()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"layoutSubviews"},{"text":"()","kind":"text"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/PopMenuCollectionViewCell":{"role":"symbol","url":"\/documentation\/shengwangchatuikit\/popmenucollectionviewcell","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"PopMenuCollectionViewCell"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PopMenuCollectionViewCell","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PopMenuCollectionViewCell"}],"kind":"symbol","title":"PopMenuCollectionViewCell"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"layoutSubviews"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"layoutSubviews","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"layoutSubviews","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PopMenuCollectionViewCell~1layoutSubviews()\/title","op":"replace","value":"layoutSubviews"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"layoutSubviews","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PopMenuCollectionViewCell~1layoutSubviews()\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PopMenuCollectionViewCell\/title","value":"PopMenuCollectionViewCell"},{"op":"replace","value":[{"kind":"identifier","text":"PopMenuCollectionViewCell"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PopMenuCollectionViewCell\/fragments"},{"value":[{"kind":"identifier","text":"PopMenuCollectionViewCell"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PopMenuCollectionViewCell\/navigatorTitle"}]}]}