{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"refresh"},{"kind":"text","text":"("},{"kind":"externalParam","text":"item"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ActionSheetItemProtocol","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(pl)ActionSheetItemProtocol","text":"ActionSheetItemProtocol"},{"kind":"text","text":")"}],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/popmenucollectionviewcell\/refresh(item:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/popmenucollectionviewcell\/refresh(item:)"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PopMenuCollectionViewCell"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PopMenuCollectionViewCell\/refresh(item:)"},"kind":"symbol","metadata":{"roleHeading":"Instance Method","externalID":"c:@M@ShengwangChatUIKit@objc(cs)PopMenuCollectionViewCell(im)refreshWithItem:","symbolKind":"method","role":"symbol","modules":[{"name":"ShengwangChatUIKit"}],"navigatorTitle":[{"text":"refreshWithItem:","kind":"identifier"}],"title":"refresh(item:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"refresh"},{"kind":"text","text":"("},{"text":"item","kind":"externalParam"},{"kind":"text","text":": "},{"text":"ActionSheetItemProtocol","kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(pl)ActionSheetItemProtocol"},{"text":")","kind":"text"}]},"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/PopMenuCollectionViewCell/refresh(item:)":{"navigatorTitle":[{"text":"refreshWithItem:","kind":"identifier"}],"abstract":[],"kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PopMenuCollectionViewCell\/refresh(item:)","url":"\/documentation\/shengwangchatuikit\/popmenucollectionviewcell\/refresh(item:)","title":"refresh(item:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"refresh"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"item"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(pl)ActionSheetItemProtocol","text":"ActionSheetItemProtocol"},{"text":")","kind":"text"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ActionSheetItemProtocol":{"navigatorTitle":[{"text":"ActionSheetItemProtocol","kind":"identifier"}],"abstract":[{"type":"text","text":"A protocol that defines properties and methods for an action sheet item."}],"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ActionSheetItemProtocol"}],"url":"\/documentation\/shengwangchatuikit\/actionsheetitemprotocol","role":"symbol","title":"ActionSheetItemProtocol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ActionSheetItemProtocol","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/PopMenuCollectionViewCell":{"role":"symbol","url":"\/documentation\/shengwangchatuikit\/popmenucollectionviewcell","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"PopMenuCollectionViewCell"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PopMenuCollectionViewCell","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PopMenuCollectionViewCell"}],"kind":"symbol","title":"PopMenuCollectionViewCell"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"refreshWithItem:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"refreshWithItem:","kind":"identifier"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"refreshWithItem:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"id<ActionSheetItemProtocol>","preciseIdentifier":"c:Qo@M@ShengwangChatUIKit@objc(pl)ActionSheetItemProtocol"},{"kind":"text","text":") "},{"kind":"internalParam","text":"item"},{"kind":"text","text":";"}]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PopMenuCollectionViewCell~1refresh(item:)\/title","value":"refreshWithItem:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"refreshWithItem:"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PopMenuCollectionViewCell~1refresh(item:)\/fragments","op":"replace"},{"value":"ActionSheetItemProtocol","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ActionSheetItemProtocol\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ActionSheetItemProtocol\/fragments","value":[{"kind":"identifier","text":"ActionSheetItemProtocol"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ActionSheetItemProtocol\/navigatorTitle","value":[{"text":"ActionSheetItemProtocol","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"PopMenuCollectionViewCell","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PopMenuCollectionViewCell\/title"},{"value":[{"kind":"identifier","text":"PopMenuCollectionViewCell"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PopMenuCollectionViewCell\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PopMenuCollectionViewCell\/navigatorTitle","value":[{"text":"PopMenuCollectionViewCell","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}