{"metadata":{"roleHeading":"Instance Method","modules":[{"name":"ShengwangChatUIKit"}],"extendedModule":"ShengwangChatUIKit","externalID":"c:@CM@ShengwangChatUIKit@objc(cs)PageContainerTitleBar(im)switchThemeWithStyle:","symbolKind":"method","title":"switchTheme(style:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"switchTheme","kind":"identifier"},{"kind":"text","text":"("},{"text":"style","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@E@ThemeStyle","kind":"typeIdentifier","text":"ThemeStyle"},{"text":")","kind":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"switchThemeWithStyle:"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PageContainerTitleBar\/switchTheme(style:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"switchTheme"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"style"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@E@ThemeStyle","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ThemeStyle","text":"ThemeStyle","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ThemeStyle","type":"reference","isActive":true}]}],"name":"style"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/pagecontainertitlebar\/switchtheme(style:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/pagecontainertitlebar\/switchtheme(style:)"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PageContainerTitleBar","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PageContainerTitleBar\/ThemeSwitchProtocol-Implementations"]]},"abstract":[{"type":"text","text":"When some view Implement the protocol method,you can use "},{"code":"Theme.switchTheme(style: .dark)","type":"codeVoice"},{"type":"text","text":" to switch theme."}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/Appearance":{"navigatorTitle":[{"kind":"identifier","text":"Appearance"}],"type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/Appearance","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Appearance","kind":"identifier"}],"title":"Appearance","abstract":[{"type":"text","text":"An object containing visual configurations for the whole application."}],"url":"\/documentation\/shengwangchatuikit\/appearance"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ThemeStyle":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"ThemeStyle"}],"title":"ThemeStyle","url":"\/documentation\/shengwangchatuikit\/themestyle","abstract":[{"type":"text","text":"Contain light and dark themes of the ease chat UIKit.If you want to switch custom theme,you’ll modify primary&secondary&error&neutral&neutralSpecial hues properties in "},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/Appearance"},{"type":"text","text":".Then call "},{"type":"codeVoice","code":"Theme.switchTheme(style: .custom)"},{"type":"text","text":" method"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ThemeStyle","kind":"symbol","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ThemeStyle"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/PageContainerTitleBar":{"title":"PageContainerTitleBar","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"PageContainerTitleBar"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PageContainerTitleBar","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PageContainerTitleBar"}],"role":"symbol","url":"\/documentation\/shengwangchatuikit\/pagecontainertitlebar"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/PageContainerTitleBar/switchTheme(style:)":{"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"switchThemeWithStyle:"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PageContainerTitleBar\/switchTheme(style:)","abstract":[{"type":"text","text":"When some view Implement the protocol method,you can use "},{"code":"Theme.switchTheme(style: .dark)","type":"codeVoice"},{"type":"text","text":" to switch theme."}],"role":"symbol","title":"switchTheme(style:)","url":"\/documentation\/shengwangchatuikit\/pagecontainertitlebar\/switchtheme(style:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"switchTheme"},{"kind":"text","text":"("},{"kind":"externalParam","text":"style"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@E@ThemeStyle","text":"ThemeStyle","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/PageContainerTitleBar/ThemeSwitchProtocol-Implementations":{"title":"ThemeSwitchProtocol Implementations","abstract":[],"kind":"article","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PageContainerTitleBar\/ThemeSwitchProtocol-Implementations","role":"collectionGroup","url":"\/documentation\/shengwangchatuikit\/pagecontainertitlebar\/themeswitchprotocol-implementations","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"switchThemeWithStyle:","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"value":[{"text":"- ","kind":"text"},{"text":"switchThemeWithStyle:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"switchThemeWithStyle:","kind":"identifier"},{"kind":"text","text":"("},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@E@ThemeStyle","text":"ThemeStyle","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ThemeStyle","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"style","kind":"internalParam"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace"},{"value":"Appearance","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1Appearance\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1Appearance\/fragments","value":[{"text":"Appearance","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1Appearance\/navigatorTitle","value":[{"kind":"identifier","text":"Appearance"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ThemeStyle\/title","value":"ThemeStyle","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ThemeStyle\/fragments","value":[{"text":"ThemeStyle","kind":"identifier"}],"op":"replace"},{"value":[{"text":"ThemeStyle","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ThemeStyle\/navigatorTitle","op":"replace"},{"value":"PageContainerTitleBar","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PageContainerTitleBar\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PageContainerTitleBar\/fragments","value":[{"text":"PageContainerTitleBar","kind":"identifier"}],"op":"replace"},{"value":[{"text":"PageContainerTitleBar","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PageContainerTitleBar\/navigatorTitle"},{"value":"switchThemeWithStyle:","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PageContainerTitleBar~1switchTheme(style:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"switchThemeWithStyle:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PageContainerTitleBar~1switchTheme(style:)\/fragments"}]}]}