{"kind":"article","topicSections":[{"generated":true,"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PageContainerTitleBar\/collectionView(_:didSelectItemAt:)"],"anchor":"Instance-Methods","title":"Instance Methods"}],"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PageContainerTitleBar\/UICollectionViewDelegate-Implementations","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PageContainerTitleBar"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"title":"UICollectionViewDelegate Implementations","roleHeading":"API Collection","role":"collectionGroup","modules":[{"name":"ShengwangChatUIKit"}]},"variants":[{"paths":["\/documentation\/shengwangchatuikit\/pagecontainertitlebar\/uicollectionviewdelegate-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/shengwangchatuikit\/pagecontainertitlebar\/uicollectionviewdelegate-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/PageContainerTitleBar":{"title":"PageContainerTitleBar","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"PageContainerTitleBar"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PageContainerTitleBar","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PageContainerTitleBar"}],"role":"symbol","url":"\/documentation\/shengwangchatuikit\/pagecontainertitlebar"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/PageContainerTitleBar/collectionView(_:didSelectItemAt:)":{"navigatorTitle":[{"text":"collectionView:didSelectItemAtIndexPath:","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/pagecontainertitlebar\/collectionview(_:didselectitemat:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"collectionView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UICollectionView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UICollectionView"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didSelectItemAt"},{"kind":"text","text":": "},{"text":"IndexPath","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation9IndexPathV"},{"text":")","kind":"text"}],"role":"symbol","title":"collectionView(_:didSelectItemAt:)","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PageContainerTitleBar\/collectionView(_:didSelectItemAt:)","kind":"symbol","abstract":[]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":[{"title":"Instance Methods","generated":true,"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PageContainerTitleBar\/collectionView(_:didSelectItemAt:)"],"anchor":"Instance-Methods"}],"path":"\/topicSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PageContainerTitleBar\/title","op":"replace","value":"PageContainerTitleBar"},{"value":[{"text":"PageContainerTitleBar","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PageContainerTitleBar\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PageContainerTitleBar\/navigatorTitle","value":[{"text":"PageContainerTitleBar","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PageContainerTitleBar~1collectionView(_:didSelectItemAt:)\/title","value":"collectionView:didSelectItemAtIndexPath:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PageContainerTitleBar~1collectionView(_:didSelectItemAt:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"collectionView:didSelectItemAtIndexPath:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}