{"kind":"article","topicSections":[{"title":"Instance Methods","generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PageContainerTitleBar\/collectionView(_:cellForItemAt:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PageContainerTitleBar\/collectionView(_:numberOfItemsInSection:)"]}],"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PageContainerTitleBar\/UICollectionViewDataSource-Implementations","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PageContainerTitleBar"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"role":"collectionGroup","title":"UICollectionViewDataSource Implementations","roleHeading":"API Collection","modules":[{"name":"ShengwangChatUIKit"}]},"variants":[{"paths":["\/documentation\/shengwangchatuikit\/pagecontainertitlebar\/uicollectionviewdatasource-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/pagecontainertitlebar\/uicollectionviewdatasource-implementations"]}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/PageContainerTitleBar/collectionView(_:numberOfItemsInSection:)":{"abstract":[],"url":"\/documentation\/shengwangchatuikit\/pagecontainertitlebar\/collectionview(_:numberofitemsinsection:)","title":"collectionView(_:numberOfItemsInSection:)","role":"symbol","navigatorTitle":[{"text":"collectionView:numberOfItemsInSection:","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PageContainerTitleBar\/collectionView(_:numberOfItemsInSection:)","kind":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"collectionView"},{"text":"(","kind":"text"},{"text":"UICollectionView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UICollectionView"},{"text":", ","kind":"text"},{"text":"numberOfItemsInSection","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/PageContainerTitleBar/collectionView(_:cellForItemAt:)":{"abstract":[],"url":"\/documentation\/shengwangchatuikit\/pagecontainertitlebar\/collectionview(_:cellforitemat:)","title":"collectionView(_:cellForItemAt:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"collectionView:cellForItemAtIndexPath:"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PageContainerTitleBar\/collectionView(_:cellForItemAt:)","kind":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"collectionView","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UICollectionView","text":"UICollectionView"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"cellForItemAt"},{"kind":"text","text":": "},{"text":"IndexPath","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation9IndexPathV"},{"text":") -> ","kind":"text"},{"text":"UICollectionViewCell","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UICollectionViewCell"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/PageContainerTitleBar":{"title":"PageContainerTitleBar","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"PageContainerTitleBar"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PageContainerTitleBar","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PageContainerTitleBar"}],"role":"symbol","url":"\/documentation\/shengwangchatuikit\/pagecontainertitlebar"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":[{"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PageContainerTitleBar\/collectionView(_:cellForItemAt:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PageContainerTitleBar\/collectionView(_:numberOfItemsInSection:)"],"title":"Instance Methods","anchor":"Instance-Methods","generated":true}],"op":"replace","path":"\/topicSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":"collectionView:numberOfItemsInSection:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PageContainerTitleBar~1collectionView(_:numberOfItemsInSection:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PageContainerTitleBar~1collectionView(_:numberOfItemsInSection:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"collectionView:numberOfItemsInSection:","kind":"identifier"}],"op":"replace"},{"value":"collectionView:cellForItemAtIndexPath:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PageContainerTitleBar~1collectionView(_:cellForItemAt:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PageContainerTitleBar~1collectionView(_:cellForItemAt:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"collectionView:cellForItemAtIndexPath:","kind":"identifier"}]},{"value":"PageContainerTitleBar","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PageContainerTitleBar\/title"},{"op":"replace","value":[{"kind":"identifier","text":"PageContainerTitleBar"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PageContainerTitleBar\/fragments"},{"value":[{"text":"PageContainerTitleBar","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PageContainerTitleBar\/navigatorTitle"}]}]}