{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ComponentsRegister"]]},"variants":[{"paths":["\/documentation\/shengwangchatuikit\/componentsregister\/chataudiomessagecell"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/componentsregister\/chataudiomessagecell"]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChatAudioMessageCell","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/AudioMessageCell","text":"AudioMessageCell","kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)AudioMessageCell"},{"text":".Type","kind":"text"}],"languages":["swift"]}]}],"metadata":{"roleHeading":"Instance Property","externalID":"c:@M@ShengwangChatUIKit@objc(cs)ComponentsRegister(py)ChatAudioMessageCell","role":"symbol","modules":[{"name":"ShengwangChatUIKit"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"ChatAudioMessageCell","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)AudioMessageCell","text":"AudioMessageCell"},{"text":".Type","kind":"text"}],"navigatorTitle":[{"text":"ChatAudioMessageCell","kind":"identifier"}],"title":"ChatAudioMessageCell","symbolKind":"property"},"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ComponentsRegister\/ChatAudioMessageCell","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ComponentsRegister/ChatAudioMessageCell":{"navigatorTitle":[{"text":"ChatAudioMessageCell","kind":"identifier"}],"title":"ChatAudioMessageCell","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ComponentsRegister\/ChatAudioMessageCell","role":"symbol","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChatAudioMessageCell","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)AudioMessageCell","kind":"typeIdentifier","text":"AudioMessageCell"},{"kind":"text","text":".Type"}],"type":"topic","abstract":[],"url":"\/documentation\/shengwangchatuikit\/componentsregister\/chataudiomessagecell"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/AudioMessageCell":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"AudioMessageCell","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"AudioMessageCell","kind":"identifier"}],"title":"AudioMessageCell","url":"\/documentation\/shengwangchatuikit\/audiomessagecell","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/AudioMessageCell","role":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ComponentsRegister":{"navigatorTitle":[{"kind":"identifier","text":"ComponentsRegister"}],"url":"\/documentation\/shengwangchatuikit\/componentsregister","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ComponentsRegister","abstract":[{"type":"text","text":"An object containing UI components that are used through the EaseChatUIKit SDK."}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ComponentsRegister","kind":"identifier"}],"title":"ComponentsRegister","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"ChatAudioMessageCell"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ChatAudioMessageCell"}]},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":") ","kind":"text"},{"text":"Class","preciseIdentifier":"c:*QO","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChatAudioMessageCell"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ComponentsRegister~1ChatAudioMessageCell\/title","op":"replace","value":"ChatAudioMessageCell"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ComponentsRegister~1ChatAudioMessageCell\/fragments","value":[{"kind":"identifier","text":"ChatAudioMessageCell"}]},{"value":"AudioMessageCell","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1AudioMessageCell\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1AudioMessageCell\/fragments","op":"replace","value":[{"kind":"identifier","text":"AudioMessageCell"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1AudioMessageCell\/navigatorTitle","value":[{"text":"AudioMessageCell","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ComponentsRegister\/title","value":"ComponentsRegister","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ComponentsRegister\/fragments","op":"replace","value":[{"text":"ComponentsRegister","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ComponentsRegister\/navigatorTitle","value":[{"text":"ComponentsRegister","kind":"identifier"}]}]}]}