{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ComponentsRegister\/ChatTextMessageCell"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ComponentsRegister"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChatTextMessageCell"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)TextMessageCell","text":"TextMessageCell","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/TextMessageCell","kind":"typeIdentifier"},{"text":".Type","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/shengwangchatuikit\/componentsregister\/chattextmessagecell"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/componentsregister\/chattextmessagecell"]}],"sections":[],"metadata":{"symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"ChatTextMessageCell","kind":"identifier"},{"text":": ","kind":"text"},{"text":"TextMessageCell","kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)TextMessageCell"},{"kind":"text","text":".Type"}],"navigatorTitle":[{"text":"ChatTextMessageCell","kind":"identifier"}],"role":"symbol","externalID":"c:@M@ShengwangChatUIKit@objc(cs)ComponentsRegister(py)ChatTextMessageCell","title":"ChatTextMessageCell","roleHeading":"Instance Property","modules":[{"name":"ShengwangChatUIKit"}]},"kind":"symbol","references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/TextMessageCell":{"navigatorTitle":[{"text":"TextMessageCell","kind":"identifier"}],"abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"TextMessageCell","kind":"identifier"}],"type":"topic","url":"\/documentation\/shengwangchatuikit\/textmessagecell","kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/TextMessageCell","title":"TextMessageCell"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ComponentsRegister":{"navigatorTitle":[{"kind":"identifier","text":"ComponentsRegister"}],"url":"\/documentation\/shengwangchatuikit\/componentsregister","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ComponentsRegister","abstract":[{"type":"text","text":"An object containing UI components that are used through the EaseChatUIKit SDK."}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ComponentsRegister","kind":"identifier"}],"title":"ComponentsRegister","type":"topic"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ComponentsRegister/ChatTextMessageCell":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ComponentsRegister\/ChatTextMessageCell","abstract":[],"url":"\/documentation\/shengwangchatuikit\/componentsregister\/chattextmessagecell","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChatTextMessageCell"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)TextMessageCell","text":"TextMessageCell","kind":"typeIdentifier"},{"text":".Type","kind":"text"}],"role":"symbol","title":"ChatTextMessageCell","navigatorTitle":[{"text":"ChatTextMessageCell","kind":"identifier"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"ChatTextMessageCell","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"text":"ChatTextMessageCell","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":") "},{"text":"Class","kind":"typeIdentifier","preciseIdentifier":"c:*QO"},{"kind":"text","text":" "},{"text":"ChatTextMessageCell","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1TextMessageCell\/title","op":"replace","value":"TextMessageCell"},{"op":"replace","value":[{"text":"TextMessageCell","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1TextMessageCell\/fragments"},{"value":[{"kind":"identifier","text":"TextMessageCell"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1TextMessageCell\/navigatorTitle"},{"value":"ComponentsRegister","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ComponentsRegister\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"ComponentsRegister"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ComponentsRegister\/fragments"},{"value":[{"kind":"identifier","text":"ComponentsRegister"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ComponentsRegister\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ComponentsRegister~1ChatTextMessageCell\/title","value":"ChatTextMessageCell","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ComponentsRegister~1ChatTextMessageCell\/fragments","value":[{"text":"ChatTextMessageCell","kind":"identifier"}],"op":"replace"}]}]}