{"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"registerCustomizeCellClass","kind":"identifier"},{"text":"(","kind":"text"},{"text":"cellType","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"MessageCell","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)MessageCell","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageCell"},{"text":".Type)","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"cellType","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Inherit from "},{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageCell","isActive":true,"type":"reference"},{"text":" class type.","type":"text"}]}]}]}],"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"registerCustomizeCellClass"},{"text":"(","kind":"text"},{"text":"cellType","kind":"externalParam"},{"kind":"text","text":": "},{"text":"MessageCell","kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)MessageCell"},{"kind":"text","text":".Type)"}],"symbolKind":"method","modules":[{"name":"ShengwangChatUIKit"}],"title":"registerCustomizeCellClass(cellType:)","navigatorTitle":[{"text":"registerCustomizeCellClassWithCellType:","kind":"identifier"}],"roleHeading":"Instance Method","externalID":"c:@M@ShengwangChatUIKit@objc(cs)ComponentsRegister(im)registerCustomizeCellClassWithCellType:","role":"symbol"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/componentsregister\/registercustomizecellclass(celltype:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/componentsregister\/registercustomizecellclass(celltype:)"]}],"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ComponentsRegister\/registerCustomizeCellClass(cellType:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Register customize table view cell method."}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ComponentsRegister"]]},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageCell":{"navigatorTitle":[{"text":"MessageCell","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageCell"}],"title":"MessageCell","abstract":[],"url":"\/documentation\/shengwangchatuikit\/messagecell"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ComponentsRegister/registerCustomizeCellClass(cellType:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"registerCustomizeCellClass","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"cellType"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)MessageCell","kind":"typeIdentifier","text":"MessageCell"},{"text":".Type)","kind":"text"}],"type":"topic","navigatorTitle":[{"text":"registerCustomizeCellClassWithCellType:","kind":"identifier"}],"title":"registerCustomizeCellClass(cellType:)","url":"\/documentation\/shengwangchatuikit\/componentsregister\/registercustomizecellclass(celltype:)","abstract":[{"type":"text","text":"Register customize table view cell method."}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ComponentsRegister\/registerCustomizeCellClass(cellType:)","role":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ComponentsRegister":{"navigatorTitle":[{"kind":"identifier","text":"ComponentsRegister"}],"url":"\/documentation\/shengwangchatuikit\/componentsregister","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ComponentsRegister","abstract":[{"type":"text","text":"An object containing UI components that are used through the EaseChatUIKit SDK."}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ComponentsRegister","kind":"identifier"}],"title":"ComponentsRegister","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","value":"registerCustomizeCellClassWithCellType:","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"registerCustomizeCellClassWithCellType:","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"registerCustomizeCellClassWithCellType:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:*QO","text":"Class"},{"kind":"text","text":") "},{"text":"cellType","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"Inherit from ","type":"text"},{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageCell","type":"reference","isActive":true},{"text":" class type.","type":"text"}],"type":"paragraph"}],"name":"cellType"}]},"op":"replace","path":"\/primaryContentSections\/1"},{"op":"replace","value":"MessageCell","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageCell\/title"},{"value":[{"text":"MessageCell","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageCell\/fragments"},{"value":[{"text":"MessageCell","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageCell\/navigatorTitle"},{"op":"replace","value":"registerCustomizeCellClassWithCellType:","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ComponentsRegister~1registerCustomizeCellClass(cellType:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"registerCustomizeCellClassWithCellType:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ComponentsRegister~1registerCustomizeCellClass(cellType:)\/fragments"},{"value":"ComponentsRegister","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ComponentsRegister\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ComponentsRegister\/fragments","value":[{"text":"ComponentsRegister","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"ComponentsRegister"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ComponentsRegister\/navigatorTitle","op":"replace"}]}]}