{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/AudioMessageView\/init(frame:towards:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/audiomessageview\/init(frame:towards:)"]},{"paths":["\/documentation\/shengwangchatuikit\/audiomessageview\/init(frame:towards:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"required","kind":"keyword"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"frame"},{"kind":"text","text":": "},{"text":"CGRect","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":", "},{"text":"towards","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@E@BubbleTowards","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/BubbleTowards","text":"BubbleTowards","kind":"typeIdentifier"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/AudioMessageView"]]},"metadata":{"roleHeading":"Initializer","modules":[{"name":"ShengwangChatUIKit"}],"title":"init(frame:towards:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"frame","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect","text":"CGRect"},{"text":", ","kind":"text"},{"text":"towards","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"BubbleTowards","preciseIdentifier":"c:@M@ShengwangChatUIKit@E@BubbleTowards"},{"text":")","kind":"text"}],"externalID":"c:@M@ShengwangChatUIKit@objc(cs)AudioMessageView(im)initWithFrame:towards:","symbolKind":"init","navigatorTitle":[{"kind":"identifier","text":"initWithFrame:towards:"}],"role":"symbol"},"kind":"symbol","sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/AudioMessageView/init(frame:towards:)":{"navigatorTitle":[{"text":"initWithFrame:towards:","kind":"identifier"}],"abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"frame"},{"text":": ","kind":"text"},{"text":"CGRect","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":", "},{"text":"towards","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BubbleTowards","preciseIdentifier":"c:@M@ShengwangChatUIKit@E@BubbleTowards"},{"text":")","kind":"text"}],"type":"topic","url":"\/documentation\/shengwangchatuikit\/audiomessageview\/init(frame:towards:)","kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/AudioMessageView\/init(frame:towards:)","title":"init(frame:towards:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/BubbleTowards":{"navigatorTitle":[{"kind":"identifier","text":"BubbleTowards"}],"abstract":[],"kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/BubbleTowards","url":"\/documentation\/shengwangchatuikit\/bubbletowards","title":"BubbleTowards","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"BubbleTowards"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/AudioMessageView":{"kind":"symbol","navigatorTitle":[{"text":"AudioMessageView","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/audiomessageview","title":"AudioMessageView","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/AudioMessageView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AudioMessageView"}],"type":"topic","role":"symbol","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithFrame:towards:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithFrame:towards:","kind":"identifier"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"initWithFrame:","kind":"identifier"},{"kind":"text","text":"("},{"text":"CGRect","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect"},{"text":") ","kind":"text"},{"text":"frame","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"towards:","kind":"identifier"},{"kind":"text","text":"("},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@E@BubbleTowards","text":"BubbleTowards","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/BubbleTowards"},{"text":") ","kind":"text"},{"text":"towards","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1AudioMessageView~1init(frame:towards:)\/title","op":"replace","value":"initWithFrame:towards:"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithFrame:towards:"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1AudioMessageView~1init(frame:towards:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1BubbleTowards\/title","op":"replace","value":"BubbleTowards"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1BubbleTowards\/fragments","value":[{"text":"BubbleTowards","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"BubbleTowards"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1BubbleTowards\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1AudioMessageView\/title","value":"AudioMessageView"},{"value":[{"kind":"identifier","text":"AudioMessageView"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1AudioMessageView\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1AudioMessageView\/navigatorTitle","value":[{"kind":"identifier","text":"AudioMessageView"}]}]}]}