{"metadata":{"title":"init(presentedViewController:presenting:)","navigatorTitle":[{"text":"initWithPresentedViewController:presentingViewController:","kind":"identifier"}],"symbolKind":"init","modules":[{"name":"ShengwangChatUIKit"}],"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"presentedViewController","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"presenting"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController"},{"kind":"text","text":"?)"}],"role":"symbol","externalID":"c:@M@ShengwangChatUIKit@objc(cs)PresentationController(im)initWithPresentedViewController:presentingViewController:","roleHeading":"Initializer"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/presentationcontroller\/init(presentedviewcontroller:presenting:)"]},{"paths":["\/documentation\/shengwangchatuikit\/presentationcontroller\/init(presentedviewcontroller:presenting:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PresentationController\/init(presentedViewController:presenting:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"kind":"keyword","text":"override"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"presentedViewController","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"presenting"},{"text":" ","kind":"text"},{"text":"presentingViewController","kind":"internalParam"},{"kind":"text","text":": "},{"text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier"},{"kind":"text","text":"?)"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PresentationController"]]},"sections":[],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/PresentationController/init(presentedViewController:presenting:)":{"url":"\/documentation\/shengwangchatuikit\/presentationcontroller\/init(presentedviewcontroller:presenting:)","kind":"symbol","title":"init(presentedViewController:presenting:)","type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PresentationController\/init(presentedViewController:presenting:)","role":"symbol","abstract":[],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"presentedViewController","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"presenting","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"},{"text":"?)","kind":"text"}],"navigatorTitle":[{"text":"initWithPresentedViewController:presentingViewController:","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/PresentationController":{"url":"\/documentation\/shengwangchatuikit\/presentationcontroller","kind":"symbol","title":"PresentationController","type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PresentationController","role":"symbol","abstract":[{"text":"A custom presentation controller that manages the transition animations and layout of the presented view controller’s view.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PresentationController","kind":"identifier"}],"navigatorTitle":[{"text":"PresentationController","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"initWithPresentedViewController:presentingViewController:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithPresentedViewController:presentingViewController:","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"initWithPresentedViewController:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"presentedViewController"},{"kind":"text","text":" "},{"text":"presentingViewController:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"presentingViewController"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace"},{"value":"initWithPresentedViewController:presentingViewController:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PresentationController~1init(presentedViewController:presenting:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PresentationController~1init(presentedViewController:presenting:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithPresentedViewController:presentingViewController:"}],"op":"replace"},{"value":"PresentationController","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PresentationController\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PresentationController\/fragments","op":"replace","value":[{"text":"PresentationController","kind":"identifier"}]},{"value":[{"text":"PresentationController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PresentationController\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}