{"abstract":[{"type":"text","text":"将要弹出时添加背景按钮"}],"metadata":{"symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"presentationTransitionWillBegin"}],"role":"symbol","modules":[{"name":"ShengwangChatUIKit"}],"roleHeading":"Instance Method","externalID":"c:@M@ShengwangChatUIKit@objc(cs)PresentationController(im)presentationTransitionWillBegin","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"presentationTransitionWillBegin","kind":"identifier"},{"kind":"text","text":"()"}],"title":"presentationTransitionWillBegin()"},"sections":[],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PresentationController\/presentationTransitionWillBegin()"},"variants":[{"paths":["\/documentation\/shengwangchatuikit\/presentationcontroller\/presentationtransitionwillbegin()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/presentationcontroller\/presentationtransitionwillbegin()"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PresentationController"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"kind":"text","text":" "},{"text":"override","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"presentationTransitionWillBegin","kind":"identifier"},{"text":"()","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/PresentationController/presentationTransitionWillBegin()":{"url":"\/documentation\/shengwangchatuikit\/presentationcontroller\/presentationtransitionwillbegin()","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"presentationTransitionWillBegin","kind":"identifier"},{"text":"()","kind":"text"}],"title":"presentationTransitionWillBegin()","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PresentationController\/presentationTransitionWillBegin()","abstract":[{"text":"将要弹出时添加背景按钮","type":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"presentationTransitionWillBegin"}],"role":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/PresentationController":{"url":"\/documentation\/shengwangchatuikit\/presentationcontroller","kind":"symbol","title":"PresentationController","type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PresentationController","role":"symbol","abstract":[{"text":"A custom presentation controller that manages the transition animations and layout of the presented view controller’s view.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PresentationController","kind":"identifier"}],"navigatorTitle":[{"text":"PresentationController","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"presentationTransitionWillBegin","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"kind":"text","text":"- "},{"text":"presentationTransitionWillBegin","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"presentationTransitionWillBegin","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"presentationTransitionWillBegin","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PresentationController~1presentationTransitionWillBegin()\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PresentationController~1presentationTransitionWillBegin()\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"presentationTransitionWillBegin","kind":"identifier"}]},{"value":"PresentationController","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PresentationController\/title"},{"value":[{"text":"PresentationController","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PresentationController\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PresentationController\/navigatorTitle","value":[{"text":"PresentationController","kind":"identifier"}]}]}]}