{"sections":[],"metadata":{"navigatorTitle":[{"text":"MessageContentDisplayStyleWithReply","kind":"identifier"}],"externalID":"c:@M@ShengwangChatUIKit@E@MessageContentDisplayStyle@MessageContentDisplayStyleWithReply","title":"MessageContentDisplayStyle.withReply","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"withReply","kind":"identifier"}],"modules":[{"name":"ShengwangChatUIKit"}],"role":"symbol","symbolKind":"case","roleHeading":"Case"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageContentDisplayStyle\/withReply"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageContentDisplayStyle"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"withReply"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/messagecontentdisplaystyle\/withreply"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/messagecontentdisplaystyle\/withreply"]}],"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageContentDisplayStyle/withReply":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"withReply"}],"title":"MessageContentDisplayStyle.withReply","abstract":[],"type":"topic","kind":"symbol","url":"\/documentation\/shengwangchatuikit\/messagecontentdisplaystyle\/withreply","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageContentDisplayStyle\/withReply","navigatorTitle":[{"text":"MessageContentDisplayStyleWithReply","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageContentDisplayStyle":{"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"MessageContentDisplayStyle"}],"title":"MessageContentDisplayStyle","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageContentDisplayStyle","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MessageContentDisplayStyle"}],"type":"topic","url":"\/documentation\/shengwangchatuikit\/messagecontentdisplaystyle","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"MessageContentDisplayStyleWithReply"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MessageContentDisplayStyleWithReply"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"MessageContentDisplayStyleWithReply"}]}],"kind":"declarations"},"op":"replace"},{"op":"replace","value":"MessageContentDisplayStyleWithReply","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageContentDisplayStyle~1withReply\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageContentDisplayStyle~1withReply\/fragments","op":"replace","value":[{"text":"MessageContentDisplayStyleWithReply","kind":"identifier"}]},{"value":"MessageContentDisplayStyle","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageContentDisplayStyle\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageContentDisplayStyle\/fragments","value":[{"kind":"identifier","text":"MessageContentDisplayStyle"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageContentDisplayStyle\/navigatorTitle","value":[{"kind":"identifier","text":"MessageContentDisplayStyle"}]}]}]}