{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageContentDisplayStyle"]]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/messagecontentdisplaystyle\/withavatar"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/messagecontentdisplaystyle\/withavatar"]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageContentDisplayStyle\/withAvatar"},"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"symbolKind":"case","roleHeading":"Case","externalID":"c:@M@ShengwangChatUIKit@E@MessageContentDisplayStyle@MessageContentDisplayStyleWithAvatar","modules":[{"name":"ShengwangChatUIKit"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"withAvatar"}],"navigatorTitle":[{"kind":"identifier","text":"MessageContentDisplayStyleWithAvatar"}],"role":"symbol","title":"MessageContentDisplayStyle.withAvatar"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"withAvatar"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageContentDisplayStyle":{"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"MessageContentDisplayStyle"}],"title":"MessageContentDisplayStyle","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageContentDisplayStyle","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MessageContentDisplayStyle"}],"type":"topic","url":"\/documentation\/shengwangchatuikit\/messagecontentdisplaystyle","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageContentDisplayStyle/withAvatar":{"navigatorTitle":[{"text":"MessageContentDisplayStyleWithAvatar","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/messagecontentdisplaystyle\/withavatar","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"withAvatar","kind":"identifier"}],"role":"symbol","title":"MessageContentDisplayStyle.withAvatar","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageContentDisplayStyle\/withAvatar","kind":"symbol","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"value":"MessageContentDisplayStyleWithAvatar","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"MessageContentDisplayStyleWithAvatar","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"MessageContentDisplayStyleWithAvatar","kind":"identifier"}]}]}},{"op":"replace","value":"MessageContentDisplayStyle","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageContentDisplayStyle\/title"},{"value":[{"text":"MessageContentDisplayStyle","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageContentDisplayStyle\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageContentDisplayStyle\/navigatorTitle","value":[{"text":"MessageContentDisplayStyle","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageContentDisplayStyle~1withAvatar\/title","value":"MessageContentDisplayStyleWithAvatar"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageContentDisplayStyle~1withAvatar\/fragments","value":[{"kind":"identifier","text":"MessageContentDisplayStyleWithAvatar"}],"op":"replace"}]}]}