{"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"symbolKind":"case","title":"URLPreviewResult.parsing","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"parsing","kind":"identifier"}],"roleHeading":"Case","navigatorTitle":[{"kind":"identifier","text":"URLPreviewResultParsing"}],"modules":[{"name":"ShengwangChatUIKit"}],"externalID":"c:@M@ShengwangChatUIKit@E@URLPreviewResult@URLPreviewResultParsing"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/URLPreviewResult\/parsing"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"parsing"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/URLPreviewResult"]]},"variants":[{"paths":["\/documentation\/shengwangchatuikit\/urlpreviewresult\/parsing"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/urlpreviewresult\/parsing"]}],"kind":"symbol","sections":[],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/URLPreviewResult":{"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"URLPreviewResult","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/URLPreviewResult","kind":"symbol","navigatorTitle":[{"text":"URLPreviewResult","kind":"identifier"}],"role":"symbol","title":"URLPreviewResult","url":"\/documentation\/shengwangchatuikit\/urlpreviewresult","abstract":[]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/URLPreviewResult/parsing":{"title":"URLPreviewResult.parsing","type":"topic","url":"\/documentation\/shengwangchatuikit\/urlpreviewresult\/parsing","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"parsing","kind":"identifier"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/URLPreviewResult\/parsing","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"URLPreviewResultParsing"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"value":"URLPreviewResultParsing","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"URLPreviewResultParsing","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"URLPreviewResultParsing"}]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1URLPreviewResult\/title","op":"replace","value":"URLPreviewResult"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1URLPreviewResult\/fragments","value":[{"kind":"identifier","text":"URLPreviewResult"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1URLPreviewResult\/navigatorTitle","op":"replace","value":[{"text":"URLPreviewResult","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1URLPreviewResult~1parsing\/title","value":"URLPreviewResultParsing","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1URLPreviewResult~1parsing\/fragments","value":[{"text":"URLPreviewResultParsing","kind":"identifier"}],"op":"replace"}]}]}