{"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/VideoMessageCell\/content"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/videomessagecell\/content"]},{"paths":["\/documentation\/shengwangchatuikit\/videomessagecell\/content"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"lazy"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"content","kind":"identifier"},{"kind":"text","text":": "},{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ImageView","kind":"typeIdentifier","text":"ImageView","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)ImageView"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/VideoMessageCell"]]},"metadata":{"modules":[{"name":"ShengwangChatUIKit"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"content","kind":"identifier"},{"kind":"text","text":": "},{"text":"ImageView","kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)ImageView"}],"role":"symbol","title":"content","symbolKind":"property","roleHeading":"Instance Property","navigatorTitle":[{"text":"content","kind":"identifier"}],"externalID":"c:@M@ShengwangChatUIKit@objc(cs)VideoMessageCell(py)content"},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/VideoMessageCell/content":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/VideoMessageCell\/content","navigatorTitle":[{"text":"content","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/videomessagecell\/content","type":"topic","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"content","kind":"identifier"},{"kind":"text","text":": "},{"text":"ImageView","kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)ImageView"}],"title":"content","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/VideoMessageCell":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"VideoMessageCell"}],"type":"topic","navigatorTitle":[{"text":"VideoMessageCell","kind":"identifier"}],"title":"VideoMessageCell","url":"\/documentation\/shengwangchatuikit\/videomessagecell","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/VideoMessageCell","role":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ImageView":{"title":"ImageView","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ImageView","kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ImageView","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ImageView"}],"abstract":[{"text":"A subclass of ","type":"text"},{"type":"codeVoice","code":"UIImageView"},{"text":" that provides a method for loading an image from a URL.","type":"text"}],"url":"\/documentation\/shengwangchatuikit\/imageview"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"content"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"content"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)ImageView","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ImageView","text":"ImageView","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"kind":"identifier","text":"content"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0"},{"value":"content","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1VideoMessageCell~1content\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1VideoMessageCell~1content\/fragments","value":[{"text":"content","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1VideoMessageCell\/title","value":"VideoMessageCell"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1VideoMessageCell\/fragments","value":[{"text":"VideoMessageCell","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1VideoMessageCell\/navigatorTitle","value":[{"text":"VideoMessageCell","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ImageView\/title","value":"ImageView"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ImageView\/fragments","op":"replace","value":[{"kind":"identifier","text":"ImageView"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ImageView\/navigatorTitle","op":"replace","value":[{"text":"ImageView","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}