{"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/VideoMessageCell\/createPlay()","interfaceLanguage":"swift"},"metadata":{"navigatorTitle":[{"text":"createPlay","kind":"identifier"}],"modules":[{"name":"ShengwangChatUIKit"}],"roleHeading":"Instance Method","symbolKind":"method","title":"createPlay()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"createPlay"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"UIImageView","preciseIdentifier":"c:objc(cs)UIImageView"}],"role":"symbol","externalID":"c:@M@ShengwangChatUIKit@objc(cs)VideoMessageCell(im)createPlay"},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/VideoMessageCell"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"createPlay","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"UIImageView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImageView"}],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/videomessagecell\/createplay()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/videomessagecell\/createplay()"]}],"sections":[],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/VideoMessageCell":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"VideoMessageCell"}],"type":"topic","navigatorTitle":[{"text":"VideoMessageCell","kind":"identifier"}],"title":"VideoMessageCell","url":"\/documentation\/shengwangchatuikit\/videomessagecell","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/VideoMessageCell","role":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/VideoMessageCell/createPlay()":{"title":"createPlay()","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/VideoMessageCell\/createPlay()","url":"\/documentation\/shengwangchatuikit\/videomessagecell\/createplay()","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"createPlay","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImageView","text":"UIImageView","kind":"typeIdentifier"}],"role":"symbol","abstract":[],"navigatorTitle":[{"text":"createPlay","kind":"identifier"}],"kind":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","value":"createPlay","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"createPlay"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"UIImageView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImageView"},{"text":" *) ","kind":"text"},{"text":"createPlay","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1VideoMessageCell\/title","value":"VideoMessageCell","op":"replace"},{"op":"replace","value":[{"text":"VideoMessageCell","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1VideoMessageCell\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1VideoMessageCell\/navigatorTitle","value":[{"text":"VideoMessageCell","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1VideoMessageCell~1createPlay()\/title","op":"replace","value":"createPlay"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1VideoMessageCell~1createPlay()\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"createPlay"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}