{"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/IContactListDriver\/refreshHeader(info:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/IContactListDriver"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"refreshHeader"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"info"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ContactListHeaderItemProtocol","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(pl)ContactListHeaderItemProtocol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactListHeaderItemProtocol"},{"kind":"text","text":")"}],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactListHeaderItemProtocol"}],"type":"paragraph"}],"name":"info"}]}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/icontactlistdriver\/refreshheader(info:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/icontactlistdriver\/refreshheader(info:)"]}],"abstract":[{"text":"The method can be used when you want to refresh header of the contact list.","type":"text"}],"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"refreshHeader","kind":"identifier"},{"text":"(","kind":"text"},{"text":"info","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(pl)ContactListHeaderItemProtocol","kind":"typeIdentifier","text":"ContactListHeaderItemProtocol"},{"text":")","kind":"text"}],"title":"refreshHeader(info:)","role":"symbol","modules":[{"name":"ShengwangChatUIKit"}],"symbolKind":"method","externalID":"c:@M@ShengwangChatUIKit@objc(pl)IContactListDriver(im)refreshHeaderWithInfo:","navigatorTitle":[{"text":"refreshHeaderWithInfo:","kind":"identifier"}],"roleHeading":"Instance Method","required":true},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/IContactListDriver/refreshHeader(info:)":{"role":"symbol","required":true,"kind":"symbol","url":"\/documentation\/shengwangchatuikit\/icontactlistdriver\/refreshheader(info:)","navigatorTitle":[{"text":"refreshHeaderWithInfo:","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/IContactListDriver\/refreshHeader(info:)","abstract":[{"type":"text","text":"The method can be used when you want to refresh header of the contact list."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"refreshHeader"},{"kind":"text","text":"("},{"text":"info","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ContactListHeaderItemProtocol","kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(pl)ContactListHeaderItemProtocol"},{"text":")","kind":"text"}],"title":"refreshHeader(info:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/IContactListDriver":{"abstract":[{"type":"text","text":"A driver protocol of "},{"code":"ContactList","type":"codeVoice"},{"type":"text","text":"."}],"navigatorTitle":[{"kind":"identifier","text":"IContactListDriver"}],"title":"IContactListDriver","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/IContactListDriver","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IContactListDriver","kind":"identifier"}],"type":"topic","url":"\/documentation\/shengwangchatuikit\/icontactlistdriver","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ContactListHeaderItemProtocol":{"navigatorTitle":[{"kind":"identifier","text":"ContactListHeaderItemProtocol"}],"title":"ContactListHeaderItemProtocol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactListHeaderItemProtocol","role":"symbol","abstract":[{"type":"text","text":"A protocol of the contact list item."}],"kind":"symbol","url":"\/documentation\/shengwangchatuikit\/contactlistheaderitemprotocol","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ContactListHeaderItemProtocol","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"refreshHeaderWithInfo:"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"refreshHeaderWithInfo:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"refreshHeaderWithInfo:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"id<ContactListHeaderItemProtocol>","preciseIdentifier":"c:Qo@M@ShengwangChatUIKit@objc(pl)ContactListHeaderItemProtocol"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"info"},{"text":";","kind":"text"}]}]}},{"value":{"kind":"parameters","parameters":[{"name":"info","content":[{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactListHeaderItemProtocol","type":"reference","isActive":true}]}]}]},"path":"\/primaryContentSections\/1","op":"replace"},{"value":"refreshHeaderWithInfo:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1IContactListDriver~1refreshHeader(info:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1IContactListDriver~1refreshHeader(info:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"refreshHeaderWithInfo:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1IContactListDriver\/title","value":"IContactListDriver","op":"replace"},{"value":[{"kind":"identifier","text":"IContactListDriver"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1IContactListDriver\/fragments"},{"value":[{"text":"IContactListDriver","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1IContactListDriver\/navigatorTitle","op":"replace"},{"value":"ContactListHeaderItemProtocol","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactListHeaderItemProtocol\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactListHeaderItemProtocol\/fragments","value":[{"kind":"identifier","text":"ContactListHeaderItemProtocol"}],"op":"replace"},{"value":[{"kind":"identifier","text":"ContactListHeaderItemProtocol"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactListHeaderItemProtocol\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}