{"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupParticipantsOperation"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/groupparticipantsoperation\/mention"]},{"paths":["\/documentation\/shengwangchatuikit\/groupparticipantsoperation\/mention"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"externalID":"c:@M@ShengwangChatUIKit@E@GroupParticipantsOperation@GroupParticipantsOperationMention","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"mention"}],"symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"GroupParticipantsOperationMention"}],"title":"GroupParticipantsOperation.mention","role":"symbol","modules":[{"name":"ShengwangChatUIKit"}],"roleHeading":"Case"},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupParticipantsOperation\/mention"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"mention"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/GroupParticipantsOperation":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GroupParticipantsOperation","kind":"identifier"}],"title":"GroupParticipantsOperation","abstract":[{"type":"text","text":"An enumeration representing the possible operations for group participants."}],"type":"topic","kind":"symbol","url":"\/documentation\/shengwangchatuikit\/groupparticipantsoperation","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupParticipantsOperation","navigatorTitle":[{"text":"GroupParticipantsOperation","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/GroupParticipantsOperation/mention":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupParticipantsOperation\/mention","abstract":[],"navigatorTitle":[{"text":"GroupParticipantsOperationMention","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/shengwangchatuikit\/groupparticipantsoperation\/mention","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"mention"}],"title":"GroupParticipantsOperation.mention"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"GroupParticipantsOperationMention"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"GroupParticipantsOperationMention","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"GroupParticipantsOperationMention"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupParticipantsOperation\/title","value":"GroupParticipantsOperation"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupParticipantsOperation\/fragments","value":[{"text":"GroupParticipantsOperation","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"GroupParticipantsOperation"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupParticipantsOperation\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupParticipantsOperation~1mention\/title","op":"replace","value":"GroupParticipantsOperationMention"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupParticipantsOperation~1mention\/fragments","value":[{"kind":"identifier","text":"GroupParticipantsOperationMention"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}