{"kind":"symbol","variants":[{"paths":["\/documentation\/shengwangchatuikit\/searchhistorymessagecell\/messagecontent"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/shengwangchatuikit\/searchhistorymessagecell\/messagecontent"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"text":"lazy","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"messageContent"},{"text":": ","kind":"text"},{"text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" ","kind":"text"},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"platforms":["iOS"]}]}],"metadata":{"role":"symbol","title":"messageContent","symbolKind":"property","externalID":"c:@M@ShengwangChatUIKit@objc(cs)SearchHistoryMessageCell(py)messageContent","navigatorTitle":[{"text":"messageContent","kind":"identifier"}],"roleHeading":"Instance Property","modules":[{"name":"ShengwangChatUIKit"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"messageContent"},{"text":": ","kind":"text"},{"text":"UILabel","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UILabel"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/SearchHistoryMessageCell"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/SearchHistoryMessageCell\/messageContent"},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/SearchHistoryMessageCell/messageContent":{"kind":"symbol","abstract":[],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"messageContent","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UILabel","text":"UILabel"}],"navigatorTitle":[{"kind":"identifier","text":"messageContent"}],"role":"symbol","url":"\/documentation\/shengwangchatuikit\/searchhistorymessagecell\/messagecontent","title":"messageContent","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/SearchHistoryMessageCell\/messageContent"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/SearchHistoryMessageCell":{"abstract":[],"url":"\/documentation\/shengwangchatuikit\/searchhistorymessagecell","title":"SearchHistoryMessageCell","role":"symbol","navigatorTitle":[{"text":"SearchHistoryMessageCell","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/SearchHistoryMessageCell","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SearchHistoryMessageCell"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"messageContent"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"messageContent"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)UILabel","kind":"typeIdentifier","text":"UILabel"},{"text":" * ","kind":"text"},{"text":"messageContent","kind":"identifier"},{"text":";","kind":"text"}]}]}},{"value":"messageContent","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1SearchHistoryMessageCell~1messageContent\/title"},{"value":[{"kind":"identifier","text":"messageContent"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1SearchHistoryMessageCell~1messageContent\/fragments"},{"value":"SearchHistoryMessageCell","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1SearchHistoryMessageCell\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SearchHistoryMessageCell"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1SearchHistoryMessageCell\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1SearchHistoryMessageCell\/navigatorTitle","value":[{"kind":"identifier","text":"SearchHistoryMessageCell"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}