{"metadata":{"title":"ThemeSwitchProtocol Implementations","role":"collectionGroup","roleHeading":"API Collection","modules":[{"name":"ShengwangChatUIKit"}]},"topicSections":[{"anchor":"Instance-Methods","title":"Instance Methods","generated":true,"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/SearchHistoryMessageCell\/switchTheme(style:)"]}],"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/SearchHistoryMessageCell\/ThemeSwitchProtocol-Implementations","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/SearchHistoryMessageCell"]]},"kind":"article","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/searchhistorymessagecell\/themeswitchprotocol-implementations"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/searchhistorymessagecell\/themeswitchprotocol-implementations"]}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/SearchHistoryMessageCell/switchTheme(style:)":{"navigatorTitle":[{"text":"switchThemeWithStyle:","kind":"identifier"}],"title":"switchTheme(style:)","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/SearchHistoryMessageCell\/switchTheme(style:)","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"switchTheme","kind":"identifier"},{"kind":"text","text":"("},{"text":"style","kind":"externalParam"},{"kind":"text","text":": "},{"text":"ThemeStyle","kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@E@ThemeStyle"},{"kind":"text","text":")"}],"type":"topic","abstract":[{"type":"text","text":"When some view Implement the protocol method,you can use "},{"code":"Theme.switchTheme(style: .dark)","type":"codeVoice"},{"text":" to switch theme.","type":"text"}],"url":"\/documentation\/shengwangchatuikit\/searchhistorymessagecell\/switchtheme(style:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/SearchHistoryMessageCell":{"abstract":[],"url":"\/documentation\/shengwangchatuikit\/searchhistorymessagecell","title":"SearchHistoryMessageCell","role":"symbol","navigatorTitle":[{"text":"SearchHistoryMessageCell","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/SearchHistoryMessageCell","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SearchHistoryMessageCell"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/SearchHistoryMessageCell\/switchTheme(style:)"],"anchor":"Instance-Methods","title":"Instance Methods","generated":true}],"op":"replace"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1SearchHistoryMessageCell~1switchTheme(style:)\/title","value":"switchThemeWithStyle:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"switchThemeWithStyle:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1SearchHistoryMessageCell~1switchTheme(style:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1SearchHistoryMessageCell\/title","value":"SearchHistoryMessageCell"},{"value":[{"text":"SearchHistoryMessageCell","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1SearchHistoryMessageCell\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1SearchHistoryMessageCell\/navigatorTitle","value":[{"text":"SearchHistoryMessageCell","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}