{"variants":[{"paths":["\/documentation\/shengwangchatuikit\/uioptions\/init"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"roleHeading":"Instance Method","role":"symbol","navigatorTitle":[{"text":"init","kind":"identifier"}],"externalID":"c:@M@ShengwangChatUIKit@objc(cs)UIOptions(im)init","symbolKind":"method","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"title":"init","modules":[{"name":"ShengwangChatUIKit"}]},"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UIOptions"]]},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UIOptions\/init"},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"text":"init","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/UIOptions/init":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UIOptions\/init","abstract":[],"url":"\/documentation\/shengwangchatuikit\/uioptions\/init","type":"topic","fragments":[{"kind":"text","text":"- "},{"text":"init","kind":"identifier"}],"role":"symbol","title":"init","navigatorTitle":[{"kind":"identifier","text":"init"}],"kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/UIOptions":{"role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIOptions","kind":"identifier"}],"title":"UIOptions","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UIOptions","type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"UIOptions"}],"url":"\/documentation\/shengwangchatuikit\/uioptions"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1UIOptions\/title","value":"UIOptions","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1UIOptions\/fragments","value":[{"kind":"identifier","text":"UIOptions"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1UIOptions\/navigatorTitle","op":"replace","value":[{"text":"UIOptions","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}