{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupChatThreadEventListener"]]},"metadata":{"symbolKind":"method","roleHeading":"Instance Method","title":"onGroupChatThreadEventOccur(type:event:)","navigatorTitle":[{"kind":"identifier","text":"onGroupChatThreadEventOccurWithType:event:"}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onGroupChatThreadEventOccur"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"type"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@E@GroupChatThreadEventType","kind":"typeIdentifier","text":"GroupChatThreadEventType"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"event"},{"kind":"text","text":": "},{"text":"GroupChatThreadEvent","kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit05GroupB11ThreadEventa"},{"text":")","kind":"text"}],"externalID":"c:@M@ShengwangChatUIKit@objc(pl)GroupChatThreadEventListener(im)onGroupChatThreadEventOccurWithType:event:","modules":[{"name":"ShengwangChatUIKit"}],"required":true},"sections":[],"abstract":[{"text":"Some event occur on group chat thread.","type":"text"}],"variants":[{"paths":["\/documentation\/shengwangchatuikit\/groupchatthreadeventlistener\/ongroupchatthreadeventoccur(type:event:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/groupchatthreadeventlistener\/ongroupchatthreadeventoccur(type:event:)"]}],"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupChatThreadEventListener\/onGroupChatThreadEventOccur(type:event:)","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onGroupChatThreadEventOccur"},{"kind":"text","text":"("},{"text":"type","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"GroupChatThreadEventType","preciseIdentifier":"c:@M@ShengwangChatUIKit@E@GroupChatThreadEventType","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupChatThreadEventType","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"event","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit05GroupB11ThreadEventa","text":"GroupChatThreadEvent","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupChatThreadEvent"},{"kind":"text","text":")"}]}],"kind":"declarations"},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupChatThreadEventType","type":"reference","isActive":true}]}],"name":"type"},{"content":[{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupChatThreadEvent","type":"reference","isActive":true}]}],"name":"event"}],"kind":"parameters"}],"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/GroupChatThreadEventListener/onGroupChatThreadEventOccur(type:event:)":{"abstract":[{"text":"Some event occur on group chat thread.","type":"text"}],"required":true,"navigatorTitle":[{"kind":"identifier","text":"onGroupChatThreadEventOccurWithType:event:"}],"type":"topic","url":"\/documentation\/shengwangchatuikit\/groupchatthreadeventlistener\/ongroupchatthreadeventoccur(type:event:)","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupChatThreadEventListener\/onGroupChatThreadEventOccur(type:event:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onGroupChatThreadEventOccur"},{"text":"(","kind":"text"},{"text":"type","kind":"externalParam"},{"kind":"text","text":": "},{"text":"GroupChatThreadEventType","preciseIdentifier":"c:@M@ShengwangChatUIKit@E@GroupChatThreadEventType","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"event","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:18ShengwangChatUIKit05GroupB11ThreadEventa","text":"GroupChatThreadEvent","kind":"typeIdentifier"},{"kind":"text","text":")"}],"kind":"symbol","role":"symbol","title":"onGroupChatThreadEventOccur(type:event:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/GroupChatThreadEventType":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupChatThreadEventType","title":"GroupChatThreadEventType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"GroupChatThreadEventType","kind":"identifier"}],"type":"topic","abstract":[],"url":"\/documentation\/shengwangchatuikit\/groupchatthreadeventtype","navigatorTitle":[{"text":"GroupChatThreadEventType","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/GroupChatThreadEventListener":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupChatThreadEventListener","kind":"symbol","title":"GroupChatThreadEventListener","role":"symbol","url":"\/documentation\/shengwangchatuikit\/groupchatthreadeventlistener","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"GroupChatThreadEventListener"}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"GroupChatThreadEventListener","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/GroupChatThreadEvent":{"role":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupChatThreadEvent"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupChatThreadEvent","navigatorTitle":[{"text":"GroupChatThreadEvent","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/groupchatthreadevent","kind":"symbol","title":"GroupChatThreadEvent","abstract":[],"type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"onGroupChatThreadEventOccurWithType:event:","path":"\/metadata\/title"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"onGroupChatThreadEventOccurWithType:event:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"onGroupChatThreadEventOccurWithType:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","text":"GroupChatThreadEventType","preciseIdentifier":"c:@M@ShengwangChatUIKit@E@GroupChatThreadEventType","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupChatThreadEventType"},{"kind":"text","text":") "},{"kind":"internalParam","text":"type"},{"text":" ","kind":"text"},{"kind":"identifier","text":"event:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)AgoraChatThreadEvent","kind":"typeIdentifier","text":"AgoraChatThreadEvent"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"event"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/primaryContentSections\/1","op":"replace","value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":""},{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupChatThreadEventType","isActive":true,"type":"reference"}],"type":"paragraph"}],"name":"type"},{"name":"event","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupChatThreadEvent","type":"reference","isActive":true}]}]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupChatThreadEventListener~1onGroupChatThreadEventOccur(type:event:)\/title","value":"onGroupChatThreadEventOccurWithType:event:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupChatThreadEventListener~1onGroupChatThreadEventOccur(type:event:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"onGroupChatThreadEventOccurWithType:event:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupChatThreadEventType\/title","value":"GroupChatThreadEventType"},{"op":"replace","value":[{"text":"GroupChatThreadEventType","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupChatThreadEventType\/fragments"},{"value":[{"kind":"identifier","text":"GroupChatThreadEventType"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupChatThreadEventType\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupChatThreadEventListener\/title","value":"GroupChatThreadEventListener","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupChatThreadEventListener\/fragments","op":"replace","value":[{"text":"GroupChatThreadEventListener","kind":"identifier"}]},{"value":[{"text":"GroupChatThreadEventListener","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupChatThreadEventListener\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}