{"variants":[{"paths":["\/documentation\/shengwangchatuikit\/pagecontainer\/init(frame:viewcontrollers:indicators:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/shengwangchatuikit\/pagecontainer\/init(frame:viewcontrollers:indicators:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"navigatorTitle":[{"text":"initWithFrame:viewControllers:indicators:","kind":"identifier"}],"externalID":"c:@M@ShengwangChatUIKit@objc(cs)PageContainer(im)initWithFrame:viewControllers:indicators:","roleHeading":"Initializer","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"frame"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CGRect","text":"CGRect","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"viewControllers","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"indicators"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"])"}],"role":"symbol","title":"init(frame:viewControllers:indicators:)","modules":[{"name":"ShengwangChatUIKit"}],"symbolKind":"init"},"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"@","kind":"attribute"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"kind":"externalParam","text":"frame"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect","text":"CGRect"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"viewControllers"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"indicators"},{"kind":"text","text":": ["},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"])"}],"platforms":["iOS"],"languages":["swift"]}]},{"parameters":[{"name":"frame","content":[{"inlineContent":[{"type":"text","text":"The frame for the "},{"code":"PageContainer","type":"codeVoice"},{"text":".","type":"text"}],"type":"paragraph"}]},{"name":"viewControllers","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"An array of "},{"type":"codeVoice","code":"UIViewController"},{"text":"s to be displayed in the ","type":"text"},{"type":"codeVoice","code":"PageContainer"},{"text":".","type":"text"}]}]},{"name":"indicators","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"An array of strings representing the indicators for the "},{"type":"codeVoice","code":"PageContainer"},{"type":"text","text":"."}]}]}],"kind":"parameters"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PageContainer"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PageContainer\/init(frame:viewControllers:indicators:)"},"sections":[],"abstract":[{"text":"A convenience initializer for creating a ","type":"text"},{"code":"PageContainer","type":"codeVoice"},{"text":" with a given frame, view controllers, and indicators.","type":"text"}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/PageContainer/init(frame:viewControllers:indicators:)":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"frame","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGRect","text":"CGRect","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"viewControllers"},{"kind":"text","text":": ["},{"text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"indicators"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"])"}],"type":"topic","role":"symbol","abstract":[{"type":"text","text":"A convenience initializer for creating a "},{"code":"PageContainer","type":"codeVoice"},{"type":"text","text":" with a given frame, view controllers, and indicators."}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithFrame:viewControllers:indicators:"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PageContainer\/init(frame:viewControllers:indicators:)","url":"\/documentation\/shengwangchatuikit\/pagecontainer\/init(frame:viewcontrollers:indicators:)","title":"init(frame:viewControllers:indicators:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/PageContainer":{"kind":"symbol","role":"symbol","title":"PageContainer","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PageContainer","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"PageContainer"}],"type":"topic","url":"\/documentation\/shengwangchatuikit\/pagecontainer","abstract":[{"type":"text","text":"A container view controller that manages a UIPageViewController and a PageContainerTitleBar."}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PageContainer"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"initWithFrame:viewControllers:indicators:","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithFrame:viewControllers:indicators:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"initWithFrame:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect","text":"CGRect"},{"kind":"text","text":") "},{"text":"frame","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"viewControllers:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSArray<UIViewController *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"viewControllers"},{"text":" ","kind":"text"},{"kind":"identifier","text":"indicators:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<NSString *>","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"indicators","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/primaryContentSections\/1","op":"replace","value":{"parameters":[{"name":"frame","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The frame for the "},{"type":"codeVoice","code":"PageContainer"},{"type":"text","text":"."}]}]},{"name":"viewControllers","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"An array of "},{"code":"UIViewController","type":"codeVoice"},{"type":"text","text":"s to be displayed in the "},{"type":"codeVoice","code":"PageContainer"},{"text":".","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"An array of strings representing the indicators for the "},{"type":"codeVoice","code":"PageContainer"},{"type":"text","text":"."}],"type":"paragraph"}],"name":"indicators"}],"kind":"parameters"}},{"path":"\/primaryContentSections\/2","value":{"kind":"content","content":[{"type":"heading","anchor":"return-value","text":"Return Value","level":2},{"type":"paragraph","inlineContent":[{"text":"A new ","type":"text"},{"type":"codeVoice","code":"PageContainer"},{"type":"text","text":" instance."}]}]},"op":"add"},{"op":"replace","value":"initWithFrame:viewControllers:indicators:","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PageContainer~1init(frame:viewControllers:indicators:)\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithFrame:viewControllers:indicators:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PageContainer~1init(frame:viewControllers:indicators:)\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PageContainer\/title","op":"replace","value":"PageContainer"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PageContainer\/fragments","value":[{"kind":"identifier","text":"PageContainer"}],"op":"replace"},{"value":[{"kind":"identifier","text":"PageContainer"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PageContainer\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}