{"variants":[{"paths":["\/documentation\/shengwangchatuikit\/pagecontainer\/pageviewcontroller(_:viewcontrollerafter:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/pagecontainer\/pageviewcontroller(_:viewcontrollerafter:)"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PageContainer","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PageContainer\/UIPageViewControllerDataSource-Implementations"]]},"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"UIPageViewControllerDataSource.pageViewController(_:viewControllerAfter:)"},{"text":".","type":"text"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"pageViewController","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"pageViewController","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIPageViewController","text":"UIPageViewController"},{"kind":"text","text":", "},{"text":"viewControllerAfter","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"viewController"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"text":"?","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PageContainer\/pageViewController(_:viewControllerAfter:)"},"metadata":{"roleHeading":"Instance Method","extendedModule":"ShengwangChatUIKit","title":"pageViewController(_:viewControllerAfter:)","role":"symbol","navigatorTitle":[{"text":"pageViewController:viewControllerAfterViewController:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"pageViewController"},{"kind":"text","text":"("},{"text":"UIPageViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIPageViewController"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"viewControllerAfter"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier","text":"UIViewController"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier","text":"UIViewController"},{"kind":"text","text":"?"}],"externalID":"c:@CM@ShengwangChatUIKit@objc(cs)PageContainer(im)pageViewController:viewControllerAfterViewController:","modules":[{"name":"ShengwangChatUIKit"}],"symbolKind":"method"},"sections":[],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/PageContainer/pageViewController(_:viewControllerAfter:)":{"role":"symbol","abstract":[],"kind":"symbol","title":"pageViewController(_:viewControllerAfter:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"pageViewController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIPageViewController","preciseIdentifier":"c:objc(cs)UIPageViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"viewControllerAfter"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier","text":"UIViewController"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PageContainer\/pageViewController(_:viewControllerAfter:)","navigatorTitle":[{"kind":"identifier","text":"pageViewController:viewControllerAfterViewController:"}],"type":"topic","url":"\/documentation\/shengwangchatuikit\/pagecontainer\/pageviewcontroller(_:viewcontrollerafter:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/PageContainer":{"kind":"symbol","role":"symbol","title":"PageContainer","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PageContainer","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"PageContainer"}],"type":"topic","url":"\/documentation\/shengwangchatuikit\/pagecontainer","abstract":[{"type":"text","text":"A container view controller that manages a UIPageViewController and a PageContainerTitleBar."}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PageContainer"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/PageContainer/UIPageViewControllerDataSource-Implementations":{"type":"topic","role":"collectionGroup","abstract":[],"kind":"article","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PageContainer\/UIPageViewControllerDataSource-Implementations","url":"\/documentation\/shengwangchatuikit\/pagecontainer\/uipageviewcontrollerdatasource-implementations","title":"UIPageViewControllerDataSource Implementations"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"pageViewController:viewControllerAfterViewController:","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"pageViewController:viewControllerAfterViewController:"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"pageViewController:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIPageViewController","kind":"typeIdentifier","text":"UIPageViewController"},{"text":" *) ","kind":"text"},{"text":"pageViewController","kind":"internalParam"},{"kind":"text","text":" "},{"text":"viewControllerAfterViewController:","kind":"identifier"},{"kind":"text","text":"("},{"text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"viewController"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PageContainer~1pageViewController(_:viewControllerAfter:)\/title","value":"pageViewController:viewControllerAfterViewController:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PageContainer~1pageViewController(_:viewControllerAfter:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"pageViewController:viewControllerAfterViewController:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PageContainer\/title","op":"replace","value":"PageContainer"},{"value":[{"kind":"identifier","text":"PageContainer"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PageContainer\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PageContainer\/navigatorTitle","value":[{"text":"PageContainer","kind":"identifier"}],"op":"replace"}]}]}