{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/pagecontainer\/pageviewcontroller(_:willtransitionto:)"]},{"paths":["\/documentation\/shengwangchatuikit\/pagecontainer\/pageviewcontroller(_:willtransitionto:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"pageViewController","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"pageViewController","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIPageViewController","text":"UIPageViewController","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"willTransitionTo"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"pendingViewControllers"},{"text":": [","kind":"text"},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":"])"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"extendedModule":"ShengwangChatUIKit","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"pageViewController","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIPageViewController","text":"UIPageViewController"},{"kind":"text","text":", "},{"text":"willTransitionTo","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":"])"}],"title":"pageViewController(_:willTransitionTo:)","modules":[{"name":"ShengwangChatUIKit"}],"role":"symbol","externalID":"c:@CM@ShengwangChatUIKit@objc(cs)PageContainer(im)pageViewController:willTransitionToViewControllers:","roleHeading":"Instance Method","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"pageViewController:willTransitionToViewControllers:"}]},"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PageContainer\/pageViewController(_:willTransitionTo:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PageContainer","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PageContainer\/UIPageViewControllerDelegate-Implementations"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"UIPageViewControllerDelegate.pageViewController(_:willTransitionTo:)"},{"text":".","type":"text"}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/PageContainer":{"kind":"symbol","role":"symbol","title":"PageContainer","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PageContainer","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"PageContainer"}],"type":"topic","url":"\/documentation\/shengwangchatuikit\/pagecontainer","abstract":[{"type":"text","text":"A container view controller that manages a UIPageViewController and a PageContainerTitleBar."}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PageContainer"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/PageContainer/pageViewController(_:willTransitionTo:)":{"url":"\/documentation\/shengwangchatuikit\/pagecontainer\/pageviewcontroller(_:willtransitionto:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"pageViewController:willTransitionToViewControllers:"}],"abstract":[],"role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PageContainer\/pageViewController(_:willTransitionTo:)","title":"pageViewController(_:willTransitionTo:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pageViewController","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIPageViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIPageViewController"},{"text":", ","kind":"text"},{"text":"willTransitionTo","kind":"externalParam"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"},{"text":"])","kind":"text"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/PageContainer/UIPageViewControllerDelegate-Implementations":{"type":"topic","role":"collectionGroup","abstract":[],"kind":"article","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PageContainer\/UIPageViewControllerDelegate-Implementations","url":"\/documentation\/shengwangchatuikit\/pagecontainer\/uipageviewcontrollerdelegate-implementations","title":"UIPageViewControllerDelegate Implementations"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"pageViewController:willTransitionToViewControllers:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"pageViewController:willTransitionToViewControllers:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"pageViewController:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIPageViewController","text":"UIPageViewController"},{"text":" *) ","kind":"text"},{"text":"pageViewController","kind":"internalParam"},{"kind":"text","text":" "},{"text":"willTransitionToViewControllers:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSArray<UIViewController *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"pendingViewControllers"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PageContainer\/title","value":"PageContainer","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PageContainer\/fragments","value":[{"kind":"identifier","text":"PageContainer"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PageContainer\/navigatorTitle","value":[{"kind":"identifier","text":"PageContainer"}],"op":"replace"},{"value":"pageViewController:willTransitionToViewControllers:","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PageContainer~1pageViewController(_:willTransitionTo:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"pageViewController:willTransitionToViewControllers:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PageContainer~1pageViewController(_:willTransitionTo:)\/fragments"}]}]}