{"kind":"symbol","variants":[{"paths":["\/documentation\/shengwangchatuikit\/pagecontainer\/pageviewcontroller(_:viewcontrollerbefore:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/pagecontainer\/pageviewcontroller(_:viewcontrollerbefore:)"]}],"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PageContainer\/pageViewController(_:viewControllerBefore:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"UIPageViewControllerDataSource.pageViewController(_:viewControllerBefore:)"},{"text":".","type":"text"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PageContainer","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PageContainer\/UIPageViewControllerDataSource-Implementations"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"metadata":{"symbolKind":"method","navigatorTitle":[{"text":"pageViewController:viewControllerBeforeViewController:","kind":"identifier"}],"role":"symbol","modules":[{"name":"ShengwangChatUIKit"}],"roleHeading":"Instance Method","externalID":"c:@CM@ShengwangChatUIKit@objc(cs)PageContainer(im)pageViewController:viewControllerBeforeViewController:","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"pageViewController"},{"text":"(","kind":"text"},{"text":"UIPageViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIPageViewController"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"viewControllerBefore"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier","text":"UIViewController"},{"kind":"text","text":"?"}],"extendedModule":"ShengwangChatUIKit","title":"pageViewController(_:viewControllerBefore:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"pageViewController","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"pageViewController","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIPageViewController","text":"UIPageViewController","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"viewControllerBefore","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"viewController"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"text":"?","kind":"text"}]}]}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/PageContainer/UIPageViewControllerDataSource-Implementations":{"type":"topic","role":"collectionGroup","abstract":[],"kind":"article","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PageContainer\/UIPageViewControllerDataSource-Implementations","url":"\/documentation\/shengwangchatuikit\/pagecontainer\/uipageviewcontrollerdatasource-implementations","title":"UIPageViewControllerDataSource Implementations"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/PageContainer/pageViewController(_:viewControllerBefore:)":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PageContainer\/pageViewController(_:viewControllerBefore:)","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"pageViewController:viewControllerBeforeViewController:"}],"type":"topic","role":"symbol","url":"\/documentation\/shengwangchatuikit\/pagecontainer\/pageviewcontroller(_:viewcontrollerbefore:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"pageViewController","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIPageViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIPageViewController"},{"text":", ","kind":"text"},{"text":"viewControllerBefore","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":") -> "},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"},{"text":"?","kind":"text"}],"title":"pageViewController(_:viewControllerBefore:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/PageContainer":{"kind":"symbol","role":"symbol","title":"PageContainer","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PageContainer","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"PageContainer"}],"type":"topic","url":"\/documentation\/shengwangchatuikit\/pagecontainer","abstract":[{"type":"text","text":"A container view controller that manages a UIPageViewController and a PageContainerTitleBar."}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PageContainer"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"pageViewController:viewControllerBeforeViewController:","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"pageViewController:viewControllerBeforeViewController:","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":" *) "},{"text":"pageViewController:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIPageViewController","text":"UIPageViewController","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"pageViewController"},{"text":" ","kind":"text"},{"kind":"identifier","text":"viewControllerBeforeViewController:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController"},{"kind":"text","text":" *) "},{"text":"viewController","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PageContainer~1pageViewController(_:viewControllerBefore:)\/title","value":"pageViewController:viewControllerBeforeViewController:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PageContainer~1pageViewController(_:viewControllerBefore:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"pageViewController:viewControllerBeforeViewController:","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PageContainer\/title","value":"PageContainer"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PageContainer\/fragments","value":[{"kind":"identifier","text":"PageContainer"}]},{"value":[{"text":"PageContainer","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PageContainer\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}