{"metadata":{"roleHeading":"API Collection","role":"collectionGroup","modules":[{"name":"ShengwangChatUIKit"}],"title":"ThemeSwitchProtocol Implementations"},"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PageContainer"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/pagecontainer\/themeswitchprotocol-implementations"]},{"paths":["\/documentation\/shengwangchatuikit\/pagecontainer\/themeswitchprotocol-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PageContainer\/ThemeSwitchProtocol-Implementations","interfaceLanguage":"swift"},"topicSections":[{"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PageContainer\/switchTheme(style:)"],"generated":true,"title":"Instance Methods","anchor":"Instance-Methods"}],"kind":"article","schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/PageContainer/switchTheme(style:)":{"url":"\/documentation\/shengwangchatuikit\/pagecontainer\/switchtheme(style:)","navigatorTitle":[{"text":"switchThemeWithStyle:","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PageContainer\/switchTheme(style:)","type":"topic","title":"switchTheme(style:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"switchTheme","kind":"identifier"},{"text":"(","kind":"text"},{"text":"style","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@E@ThemeStyle","text":"ThemeStyle","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[{"type":"text","text":"When some view Implement the protocol method,you can use "},{"type":"codeVoice","code":"Theme.switchTheme(style: .dark)"},{"type":"text","text":" to switch theme."}],"kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/PageContainer":{"kind":"symbol","role":"symbol","title":"PageContainer","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PageContainer","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"PageContainer"}],"type":"topic","url":"\/documentation\/shengwangchatuikit\/pagecontainer","abstract":[{"type":"text","text":"A container view controller that manages a UIPageViewController and a PageContainerTitleBar."}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PageContainer"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":[{"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PageContainer\/switchTheme(style:)"],"generated":true,"title":"Instance Methods","anchor":"Instance-Methods"}],"path":"\/topicSections","op":"replace"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":"switchThemeWithStyle:","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PageContainer~1switchTheme(style:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PageContainer~1switchTheme(style:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"switchThemeWithStyle:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PageContainer\/title","value":"PageContainer","op":"replace"},{"value":[{"text":"PageContainer","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PageContainer\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"PageContainer"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PageContainer\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}