{"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PageContainer\/UIPageViewControllerDataSource-Implementations","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PageContainer"]]},"kind":"article","sections":[],"topicSections":[{"anchor":"Instance-Methods","generated":true,"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PageContainer\/pageViewController(_:viewControllerAfter:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PageContainer\/pageViewController(_:viewControllerBefore:)"]}],"metadata":{"title":"UIPageViewControllerDataSource Implementations","role":"collectionGroup","roleHeading":"API Collection","modules":[{"name":"ShengwangChatUIKit"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/pagecontainer\/uipageviewcontrollerdatasource-implementations"]},{"paths":["\/documentation\/shengwangchatuikit\/pagecontainer\/uipageviewcontrollerdatasource-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/PageContainer/pageViewController(_:viewControllerAfter:)":{"role":"symbol","abstract":[],"kind":"symbol","title":"pageViewController(_:viewControllerAfter:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"pageViewController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIPageViewController","preciseIdentifier":"c:objc(cs)UIPageViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"viewControllerAfter"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier","text":"UIViewController"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PageContainer\/pageViewController(_:viewControllerAfter:)","navigatorTitle":[{"kind":"identifier","text":"pageViewController:viewControllerAfterViewController:"}],"type":"topic","url":"\/documentation\/shengwangchatuikit\/pagecontainer\/pageviewcontroller(_:viewcontrollerafter:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/PageContainer/pageViewController(_:viewControllerBefore:)":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PageContainer\/pageViewController(_:viewControllerBefore:)","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"pageViewController:viewControllerBeforeViewController:"}],"type":"topic","role":"symbol","url":"\/documentation\/shengwangchatuikit\/pagecontainer\/pageviewcontroller(_:viewcontrollerbefore:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"pageViewController","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIPageViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIPageViewController"},{"text":", ","kind":"text"},{"text":"viewControllerBefore","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":") -> "},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"},{"text":"?","kind":"text"}],"title":"pageViewController(_:viewControllerBefore:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/PageContainer":{"kind":"symbol","role":"symbol","title":"PageContainer","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PageContainer","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"PageContainer"}],"type":"topic","url":"\/documentation\/shengwangchatuikit\/pagecontainer","abstract":[{"type":"text","text":"A container view controller that manages a UIPageViewController and a PageContainerTitleBar."}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PageContainer"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/topicSections","op":"replace","value":[{"title":"Instance Methods","generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PageContainer\/pageViewController(_:viewControllerAfter:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PageContainer\/pageViewController(_:viewControllerBefore:)"]}]},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PageContainer~1pageViewController(_:viewControllerAfter:)\/title","op":"replace","value":"pageViewController:viewControllerAfterViewController:"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PageContainer~1pageViewController(_:viewControllerAfter:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"pageViewController:viewControllerAfterViewController:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PageContainer~1pageViewController(_:viewControllerBefore:)\/title","value":"pageViewController:viewControllerBeforeViewController:"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PageContainer~1pageViewController(_:viewControllerBefore:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"pageViewController:viewControllerBeforeViewController:"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PageContainer\/title","value":"PageContainer"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PageContainer\/fragments","value":[{"kind":"identifier","text":"PageContainer"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PageContainer\/navigatorTitle","value":[{"text":"PageContainer","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}