{"primaryContentSections":[{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","preciseIdentifier":"c:*Qo","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"initWithStyle:","kind":"identifier"},{"kind":"text","text":"("},{"text":"UITableViewCellStyle","preciseIdentifier":"c:@E@UITableViewCellStyle","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"style","kind":"internalParam"},{"kind":"text","text":" "},{"text":"reuseIdentifier:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"reuseIdentifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/actionsheetcell\/initwithstyle:reuseidentifier:"]}],"kind":"symbol","sections":[],"metadata":{"platforms":[{"deprecated":false,"beta":false,"name":"iOS","introducedAt":"3.0","unavailable":false},{"introducedAt":"3.0","deprecated":false,"unavailable":false,"name":"iPadOS","beta":false},{"deprecated":false,"beta":false,"name":"Mac Catalyst","introducedAt":"3.0","unavailable":false}],"role":"symbol","title":"initWithStyle:reuseIdentifier:","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithStyle:reuseIdentifier:"}],"symbolKind":"method","roleHeading":"Instance Method","externalID":"c:@M@ShengwangChatUIKit@objc(cs)ActionSheetCell(im)initWithStyle:reuseIdentifier:","navigatorTitle":[{"kind":"identifier","text":"initWithStyle:reuseIdentifier:"}],"modules":[{"name":"ShengwangChatUIKit"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ActionSheetCell"]]},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ActionSheetCell\/initWithStyle:reuseIdentifier:"},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ActionSheetCell":{"type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ActionSheetCell"}],"url":"\/documentation\/shengwangchatuikit\/actionsheetcell","navigatorTitle":[{"text":"ActionSheetCell","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ActionSheetCell","title":"ActionSheetCell","abstract":[],"role":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ActionSheetCell/initWithStyle:reuseIdentifier:":{"navigatorTitle":[{"kind":"identifier","text":"initWithStyle:reuseIdentifier:"}],"url":"\/documentation\/shengwangchatuikit\/actionsheetcell\/initwithstyle:reuseidentifier:","type":"topic","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithStyle:reuseIdentifier:"}],"role":"symbol","title":"initWithStyle:reuseIdentifier:","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ActionSheetCell\/initWithStyle:reuseIdentifier:","kind":"symbol","abstract":[]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ActionSheetCell\/title","value":"ActionSheetCell","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ActionSheetCell\/fragments","value":[{"kind":"identifier","text":"ActionSheetCell"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ActionSheetCell\/navigatorTitle","op":"replace","value":[{"text":"ActionSheetCell","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}