{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationViewModel\/conversationEventDidChanged(event:conversationId:conversationType:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"conversationEventDidChanged","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"event"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:18ShengwangChatUIKit16MultiDeviceEventa","text":"MultiDeviceEvent","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MultiDeviceEvent","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"conversationId"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"conversationType"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:18ShengwangChatUIKit0B16ConversationTypea","kind":"typeIdentifier","text":"ChatConversationType","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatConversationType"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationViewModel"]]},"sections":[],"metadata":{"externalID":"c:@CM@ShengwangChatUIKit@objc(cs)ConversationViewModel(im)conversationEventDidChangedWithEvent:conversationId:conversationType:","extendedModule":"ShengwangChatUIKit","roleHeading":"Instance Method","role":"symbol","title":"conversationEventDidChanged(event:conversationId:conversationType:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"conversationEventDidChanged"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"event"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit16MultiDeviceEventa","text":"MultiDeviceEvent"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"conversationId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"conversationType","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:18ShengwangChatUIKit0B16ConversationTypea","text":"ChatConversationType","kind":"typeIdentifier"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"conversationEventDidChangedWithEvent:conversationId:conversationType:"}],"modules":[{"name":"ShengwangChatUIKit"}],"symbolKind":"method"},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/conversationviewmodel\/conversationeventdidchanged(event:conversationid:conversationtype:)"]},{"paths":["\/documentation\/shengwangchatuikit\/conversationviewmodel\/conversationeventdidchanged(event:conversationid:conversationtype:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MultiDeviceEvent":{"fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MultiDeviceEvent"}],"role":"symbol","url":"\/documentation\/shengwangchatuikit\/multideviceevent","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MultiDeviceEvent","title":"MultiDeviceEvent","kind":"symbol","abstract":[],"navigatorTitle":[{"text":"MultiDeviceEvent","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatConversationType":{"type":"topic","role":"symbol","title":"ChatConversationType","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatConversationType","abstract":[],"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatConversationType"}],"url":"\/documentation\/shengwangchatuikit\/chatconversationtype","kind":"symbol","navigatorTitle":[{"text":"ChatConversationType","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ConversationViewModel/conversationEventDidChanged(event:conversationId:conversationType:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"conversationEventDidChanged"},{"kind":"text","text":"("},{"kind":"externalParam","text":"event"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:18ShengwangChatUIKit16MultiDeviceEventa","text":"MultiDeviceEvent","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"conversationId"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"conversationType","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:18ShengwangChatUIKit0B16ConversationTypea","text":"ChatConversationType","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationViewModel\/conversationEventDidChanged(event:conversationId:conversationType:)","title":"conversationEventDidChanged(event:conversationId:conversationType:)","navigatorTitle":[{"text":"conversationEventDidChangedWithEvent:conversationId:conversationType:","kind":"identifier"}],"abstract":[],"url":"\/documentation\/shengwangchatuikit\/conversationviewmodel\/conversationeventdidchanged(event:conversationid:conversationtype:)","type":"topic","kind":"symbol","role":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ConversationViewModel":{"url":"\/documentation\/shengwangchatuikit\/conversationviewmodel","type":"topic","role":"symbol","abstract":[{"text":"Bind service and driver","type":"text"}],"title":"ConversationViewModel","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ConversationViewModel","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationViewModel","navigatorTitle":[{"text":"ConversationViewModel","kind":"identifier"}],"kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"conversationEventDidChangedWithEvent:conversationId:conversationType:","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"conversationEventDidChangedWithEvent:conversationId:conversationType:"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"text":"conversationEventDidChangedWithEvent:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@AgoraChatMultiDevicesEvent","text":"AgoraChatMultiDevicesEvent"},{"kind":"text","text":") "},{"text":"event","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"conversationId:"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"conversationId"},{"text":" ","kind":"text"},{"kind":"identifier","text":"conversationType:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"AgoraChatConversationType","preciseIdentifier":"c:@E@AgoraChatConversationType"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"conversationType"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationViewModel~1conversationEventDidChanged(event:conversationId:conversationType:)\/title","value":"conversationEventDidChangedWithEvent:conversationId:conversationType:"},{"value":[{"text":"- ","kind":"text"},{"text":"conversationEventDidChangedWithEvent:conversationId:conversationType:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationViewModel~1conversationEventDidChanged(event:conversationId:conversationType:)\/fragments"},{"op":"replace","value":"ConversationViewModel","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationViewModel\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationViewModel\/fragments","value":[{"text":"ConversationViewModel","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"ConversationViewModel"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationViewModel\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}