{"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"paths":["\/documentation\/shengwangchatuikit\/conversationviewmodel\/conversationlistactioneventsdelegate-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/conversationviewmodel\/conversationlistactioneventsdelegate-implementations"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationViewModel\/ConversationListActionEventsDelegate-Implementations"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationViewModel"]]},"topicSections":[{"anchor":"Instance-Methods","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationViewModel\/onConversationDidSelected(indexPath:info:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationViewModel\/onConversationListEndScrollNeededDisplayInfos(ids:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationViewModel\/onConversationListOccurErrorWhenFetchServer()","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationViewModel\/onConversationListRefresh()","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationViewModel\/onConversationLongPressed(indexPath:info:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationViewModel\/onConversationSwipe(type:info:)"],"generated":true,"title":"Instance Methods"}],"kind":"article","metadata":{"modules":[{"name":"ShengwangChatUIKit"}],"role":"collectionGroup","roleHeading":"API Collection","title":"ConversationListActionEventsDelegate Implementations"},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ConversationViewModel/onConversationDidSelected(indexPath:info:)":{"url":"\/documentation\/shengwangchatuikit\/conversationviewmodel\/onconversationdidselected(indexpath:info:)","type":"topic","title":"onConversationDidSelected(indexPath:info:)","navigatorTitle":[{"kind":"identifier","text":"onConversationDidSelectedWithIndexPath:info:"}],"abstract":[{"text":"Callback on conversation was selected.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationViewModel\/onConversationDidSelected(indexPath:info:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onConversationDidSelected"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"indexPath"},{"text":": ","kind":"text"},{"text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"info"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ConversationInfo","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)ConversationInfo"},{"text":")","kind":"text"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ConversationViewModel/onConversationListOccurErrorWhenFetchServer()":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"onConversationListOccurErrorWhenFetchServer","kind":"identifier"},{"kind":"text","text":"()"}],"navigatorTitle":[{"text":"onConversationListOccurErrorWhenFetchServer","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/conversationviewmodel\/onconversationlistoccurerrorwhenfetchserver()","abstract":[{"type":"text","text":"When fetch conversations list occur error.Empty view retry button on clicked.The method will call."}],"type":"topic","title":"onConversationListOccurErrorWhenFetchServer()","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationViewModel\/onConversationListOccurErrorWhenFetchServer()","role":"symbol","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ConversationViewModel/onConversationSwipe(type:info:)":{"type":"topic","navigatorTitle":[{"text":"onConversationSwipeWithType:info:","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/conversationviewmodel\/onconversationswipe(type:info:)","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onConversationSwipe"},{"text":"(","kind":"text"},{"text":"type","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@E@UIContextualActionType","text":"UIContextualActionType"},{"kind":"text","text":", "},{"text":"info","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ConversationInfo","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)ConversationInfo","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[{"text":"Callback on conversation was swiped.","type":"text"}],"title":"onConversationSwipe(type:info:)","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationViewModel\/onConversationSwipe(type:info:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ConversationViewModel/onConversationListRefresh()":{"title":"onConversationListRefresh()","navigatorTitle":[{"text":"onConversationListRefresh","kind":"identifier"}],"abstract":[{"type":"text","text":"Pull down to refresh"}],"url":"\/documentation\/shengwangchatuikit\/conversationviewmodel\/onconversationlistrefresh()","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"onConversationListRefresh","kind":"identifier"},{"text":"()","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationViewModel\/onConversationListRefresh()","type":"topic","kind":"symbol","role":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ConversationViewModel":{"url":"\/documentation\/shengwangchatuikit\/conversationviewmodel","type":"topic","role":"symbol","abstract":[{"text":"Bind service and driver","type":"text"}],"title":"ConversationViewModel","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ConversationViewModel","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationViewModel","navigatorTitle":[{"text":"ConversationViewModel","kind":"identifier"}],"kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ConversationViewModel/onConversationListEndScrollNeededDisplayInfos(ids:)":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationViewModel\/onConversationListEndScrollNeededDisplayInfos(ids:)","type":"topic","abstract":[{"text":"The method will called on conversation list end scroll,then it will ask you for the session nickname and avatar data and then refresh it.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onConversationListEndScrollNeededDisplayInfos"},{"kind":"text","text":"("},{"kind":"externalParam","text":"ids"},{"kind":"text","text":": ["},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"])"}],"url":"\/documentation\/shengwangchatuikit\/conversationviewmodel\/onconversationlistendscrollneededdisplayinfos(ids:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"onConversationListEndScrollNeededDisplayInfosWithIds:"}],"kind":"symbol","title":"onConversationListEndScrollNeededDisplayInfos(ids:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ConversationViewModel/onConversationLongPressed(indexPath:info:)":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationViewModel\/onConversationLongPressed(indexPath:info:)","navigatorTitle":[{"kind":"identifier","text":"onConversationLongPressedWithIndexPath:info:"}],"url":"\/documentation\/shengwangchatuikit\/conversationviewmodel\/onconversationlongpressed(indexpath:info:)","type":"topic","abstract":[{"type":"text","text":"Callback on conversation was long pressed."}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"onConversationLongPressed","kind":"identifier"},{"text":"(","kind":"text"},{"text":"indexPath","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"IndexPath","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":", "},{"text":"info","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)ConversationInfo","text":"ConversationInfo","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"onConversationLongPressed(indexPath:info:)","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/topicSections","value":[{"generated":true,"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationViewModel\/onConversationDidSelected(indexPath:info:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationViewModel\/onConversationListEndScrollNeededDisplayInfos(ids:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationViewModel\/onConversationListOccurErrorWhenFetchServer()","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationViewModel\/onConversationListRefresh()","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationViewModel\/onConversationLongPressed(indexPath:info:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationViewModel\/onConversationSwipe(type:info:)"],"anchor":"Instance-Methods","title":"Instance Methods"}]},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":"onConversationDidSelectedWithIndexPath:info:","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationViewModel~1onConversationDidSelected(indexPath:info:)\/title","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"onConversationDidSelectedWithIndexPath:info:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationViewModel~1onConversationDidSelected(indexPath:info:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationViewModel~1onConversationListOccurErrorWhenFetchServer()\/title","value":"onConversationListOccurErrorWhenFetchServer"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationViewModel~1onConversationListOccurErrorWhenFetchServer()\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"onConversationListOccurErrorWhenFetchServer"}]},{"value":"onConversationSwipeWithType:info:","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationViewModel~1onConversationSwipe(type:info:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"onConversationSwipeWithType:info:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationViewModel~1onConversationSwipe(type:info:)\/fragments"},{"value":"onConversationListRefresh","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationViewModel~1onConversationListRefresh()\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationViewModel~1onConversationListRefresh()\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"onConversationListRefresh","kind":"identifier"}]},{"op":"replace","value":"ConversationViewModel","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationViewModel\/title"},{"value":[{"text":"ConversationViewModel","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationViewModel\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationViewModel\/navigatorTitle","value":[{"kind":"identifier","text":"ConversationViewModel"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationViewModel~1onConversationListEndScrollNeededDisplayInfos(ids:)\/title","value":"onConversationListEndScrollNeededDisplayInfosWithIds:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"onConversationListEndScrollNeededDisplayInfosWithIds:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationViewModel~1onConversationListEndScrollNeededDisplayInfos(ids:)\/fragments","op":"replace"},{"value":"onConversationLongPressedWithIndexPath:info:","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationViewModel~1onConversationLongPressed(indexPath:info:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"onConversationLongPressedWithIndexPath:info:"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationViewModel~1onConversationLongPressed(indexPath:info:)\/fragments","op":"replace"}]}]}