{"sections":[],"metadata":{"role":"symbol","extendedModule":"ShengwangChatUIKit","roleHeading":"Instance Method","title":"onConversationEventDidChanged(event:conversationId:conversationType:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"onConversationEventDidChanged","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"event"},{"kind":"text","text":": "},{"text":"MultiDeviceEvent","kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit16MultiDeviceEventa"},{"kind":"text","text":", "},{"text":"conversationId","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"conversationType","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ChatConversationType","kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit0B16ConversationTypea"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"onConversationEventDidChangedWithEvent:conversationId:conversationType:","kind":"identifier"}],"externalID":"c:@CM@ShengwangChatUIKit@objc(cs)ConversationViewModel(im)onConversationEventDidChangedWithEvent:conversationId:conversationType:","symbolKind":"method","modules":[{"name":"ShengwangChatUIKit"}]},"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationViewModel\/onConversationEventDidChanged(event:conversationId:conversationType:)","interfaceLanguage":"swift"},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/conversationviewmodel\/onconversationeventdidchanged(event:conversationid:conversationtype:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/conversationviewmodel\/onconversationeventdidchanged(event:conversationid:conversationtype:)"]}],"abstract":[{"type":"text","text":"When a event of conversation changes on other devices"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationViewModel","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationViewModel\/MultiDeviceListener-Implementations"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onConversationEventDidChanged"},{"kind":"text","text":"("},{"text":"event","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MultiDeviceEvent","preciseIdentifier":"s:18ShengwangChatUIKit16MultiDeviceEventa","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MultiDeviceEvent","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"conversationId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"conversationType"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatConversationType","preciseIdentifier":"s:18ShengwangChatUIKit0B16ConversationTypea","kind":"typeIdentifier","text":"ChatConversationType"},{"kind":"text","text":")"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"event","content":[{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"isActive":true,"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MultiDeviceEvent","type":"reference"}]}]},{"name":"conversationId","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The id of the group."}]}]},{"content":[{"inlineContent":[{"type":"text","text":""},{"isActive":true,"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatConversationType","type":"reference"},{"type":"text","text":"."}],"type":"paragraph"}],"name":"conversationType"}]}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MultiDeviceEvent":{"fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MultiDeviceEvent"}],"role":"symbol","url":"\/documentation\/shengwangchatuikit\/multideviceevent","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MultiDeviceEvent","title":"MultiDeviceEvent","kind":"symbol","abstract":[],"navigatorTitle":[{"text":"MultiDeviceEvent","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatConversationType":{"type":"topic","role":"symbol","title":"ChatConversationType","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatConversationType","abstract":[],"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatConversationType"}],"url":"\/documentation\/shengwangchatuikit\/chatconversationtype","kind":"symbol","navigatorTitle":[{"text":"ChatConversationType","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ConversationViewModel":{"url":"\/documentation\/shengwangchatuikit\/conversationviewmodel","type":"topic","role":"symbol","abstract":[{"text":"Bind service and driver","type":"text"}],"title":"ConversationViewModel","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ConversationViewModel","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationViewModel","navigatorTitle":[{"text":"ConversationViewModel","kind":"identifier"}],"kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ConversationViewModel/MultiDeviceListener-Implementations":{"title":"MultiDeviceListener Implementations","role":"collectionGroup","type":"topic","kind":"article","abstract":[],"url":"\/documentation\/shengwangchatuikit\/conversationviewmodel\/multidevicelistener-implementations","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationViewModel\/MultiDeviceListener-Implementations"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ConversationViewModel/onConversationEventDidChanged(event:conversationId:conversationType:)":{"type":"topic","role":"symbol","title":"onConversationEventDidChanged(event:conversationId:conversationType:)","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationViewModel\/onConversationEventDidChanged(event:conversationId:conversationType:)","abstract":[{"type":"text","text":"When a event of conversation changes on other devices"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onConversationEventDidChanged"},{"kind":"text","text":"("},{"kind":"externalParam","text":"event"},{"kind":"text","text":": "},{"preciseIdentifier":"s:18ShengwangChatUIKit16MultiDeviceEventa","kind":"typeIdentifier","text":"MultiDeviceEvent"},{"text":", ","kind":"text"},{"text":"conversationId","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"conversationType","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit0B16ConversationTypea","text":"ChatConversationType"},{"kind":"text","text":")"}],"url":"\/documentation\/shengwangchatuikit\/conversationviewmodel\/onconversationeventdidchanged(event:conversationid:conversationtype:)","kind":"symbol","navigatorTitle":[{"text":"onConversationEventDidChangedWithEvent:conversationId:conversationType:","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"onConversationEventDidChangedWithEvent:conversationId:conversationType:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"onConversationEventDidChangedWithEvent:conversationId:conversationType:"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"onConversationEventDidChangedWithEvent:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@E@AgoraChatMultiDevicesEvent","kind":"typeIdentifier","text":"AgoraChatMultiDevicesEvent"},{"text":") ","kind":"text"},{"text":"event","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"conversationId:"},{"kind":"text","text":"("},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"conversationId","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"conversationType:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@AgoraChatConversationType","text":"AgoraChatConversationType"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"conversationType"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"value":"ConversationViewModel","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationViewModel\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationViewModel\/fragments","value":[{"kind":"identifier","text":"ConversationViewModel"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationViewModel\/navigatorTitle","value":[{"kind":"identifier","text":"ConversationViewModel"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationViewModel~1onConversationEventDidChanged(event:conversationId:conversationType:)\/title","value":"onConversationEventDidChangedWithEvent:conversationId:conversationType:","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"onConversationEventDidChangedWithEvent:conversationId:conversationType:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationViewModel~1onConversationEventDidChanged(event:conversationId:conversationType:)\/fragments"}]}]}