{"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"extendedModule":"ShengwangChatUIKit","navigatorTitle":[{"text":"onConversationLongPressedWithIndexPath:info:","kind":"identifier"}],"roleHeading":"Instance Method","symbolKind":"method","title":"onConversationLongPressed(indexPath:info:)","modules":[{"name":"ShengwangChatUIKit"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onConversationLongPressed"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"indexPath"},{"text":": ","kind":"text"},{"text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"info","kind":"externalParam"},{"kind":"text","text":": "},{"text":"ConversationInfo","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)ConversationInfo","kind":"typeIdentifier"},{"kind":"text","text":")"}],"role":"symbol","externalID":"c:@CM@ShengwangChatUIKit@objc(cs)ConversationViewModel(im)onConversationLongPressedWithIndexPath:info:"},"variants":[{"paths":["\/documentation\/shengwangchatuikit\/conversationviewmodel\/onconversationlongpressed(indexpath:info:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/shengwangchatuikit\/conversationviewmodel\/onconversationlongpressed(indexpath:info:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationViewModel\/onConversationLongPressed(indexPath:info:)","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onConversationLongPressed"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"indexPath"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation9IndexPathV","text":"IndexPath"},{"kind":"text","text":", "},{"kind":"externalParam","text":"info"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)ConversationInfo","text":"ConversationInfo","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationInfo","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"indexPath","content":[{"type":"paragraph","inlineContent":[{"text":"The ","type":"text"},{"code":"IndexPath","type":"codeVoice"},{"type":"text","text":" of long pressed cell."}]}]},{"name":"info","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"reference","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationInfo","isActive":true},{"type":"text","text":" object."}]}]}]}],"abstract":[{"text":"Callback on conversation was long pressed.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationViewModel","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationViewModel\/ConversationListActionEventsDelegate-Implementations"]]},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ConversationViewModel":{"url":"\/documentation\/shengwangchatuikit\/conversationviewmodel","type":"topic","role":"symbol","abstract":[{"text":"Bind service and driver","type":"text"}],"title":"ConversationViewModel","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ConversationViewModel","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationViewModel","navigatorTitle":[{"text":"ConversationViewModel","kind":"identifier"}],"kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ConversationViewModel/ConversationListActionEventsDelegate-Implementations":{"type":"topic","url":"\/documentation\/shengwangchatuikit\/conversationviewmodel\/conversationlistactioneventsdelegate-implementations","title":"ConversationListActionEventsDelegate Implementations","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationViewModel\/ConversationListActionEventsDelegate-Implementations","role":"collectionGroup","kind":"article","abstract":[]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ConversationInfo":{"title":"ConversationInfo","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ConversationInfo","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/conversationinfo","role":"symbol","abstract":[],"type":"topic","navigatorTitle":[{"text":"ConversationInfo","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationInfo"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ConversationViewModel/onConversationLongPressed(indexPath:info:)":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationViewModel\/onConversationLongPressed(indexPath:info:)","navigatorTitle":[{"kind":"identifier","text":"onConversationLongPressedWithIndexPath:info:"}],"url":"\/documentation\/shengwangchatuikit\/conversationviewmodel\/onconversationlongpressed(indexpath:info:)","type":"topic","abstract":[{"type":"text","text":"Callback on conversation was long pressed."}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"onConversationLongPressed","kind":"identifier"},{"text":"(","kind":"text"},{"text":"indexPath","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"IndexPath","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":", "},{"text":"info","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)ConversationInfo","text":"ConversationInfo","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"onConversationLongPressed(indexPath:info:)","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"onConversationLongPressedWithIndexPath:info:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"onConversationLongPressedWithIndexPath:info:","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"onConversationLongPressedWithIndexPath:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSIndexPath","preciseIdentifier":"c:objc(cs)NSIndexPath"},{"text":" *) ","kind":"text"},{"text":"indexPath","kind":"internalParam"},{"kind":"text","text":" "},{"text":"info:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)ConversationInfo","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationInfo","text":"ConversationInfo","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"info","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"value":"ConversationViewModel","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationViewModel\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationViewModel\/fragments","value":[{"kind":"identifier","text":"ConversationViewModel"}]},{"value":[{"kind":"identifier","text":"ConversationViewModel"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationViewModel\/navigatorTitle","op":"replace"},{"value":"ConversationInfo","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationInfo\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationInfo\/fragments","value":[{"text":"ConversationInfo","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"ConversationInfo"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationInfo\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationViewModel~1onConversationLongPressed(indexPath:info:)\/title","op":"replace","value":"onConversationLongPressedWithIndexPath:info:"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationViewModel~1onConversationLongPressed(indexPath:info:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"onConversationLongPressedWithIndexPath:info:","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}