{"variants":[{"paths":["\/documentation\/shengwangchatuikit\/conversationviewmodel\/read(info:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/shengwangchatuikit\/conversationviewmodel\/read(info:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationViewModel"]]},"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"read","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"info"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationInfo","text":"ConversationInfo","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)ConversationInfo"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}]}],"metadata":{"extendedModule":"ShengwangChatUIKit","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"read"},{"text":"(","kind":"text"},{"text":"info","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)ConversationInfo","kind":"typeIdentifier","text":"ConversationInfo"},{"text":")","kind":"text"}],"roleHeading":"Instance Method","modules":[{"name":"ShengwangChatUIKit"}],"symbolKind":"method","role":"symbol","externalID":"c:@CM@ShengwangChatUIKit@objc(cs)ConversationViewModel(im)readWithInfo:","title":"read(info:)","navigatorTitle":[{"kind":"identifier","text":"readWithInfo:"}]},"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationViewModel\/read(info:)","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ConversationViewModel":{"url":"\/documentation\/shengwangchatuikit\/conversationviewmodel","type":"topic","role":"symbol","abstract":[{"text":"Bind service and driver","type":"text"}],"title":"ConversationViewModel","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ConversationViewModel","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationViewModel","navigatorTitle":[{"text":"ConversationViewModel","kind":"identifier"}],"kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ConversationViewModel/read(info:)":{"kind":"symbol","type":"topic","abstract":[],"url":"\/documentation\/shengwangchatuikit\/conversationviewmodel\/read(info:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"read","kind":"identifier"},{"text":"(","kind":"text"},{"text":"info","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ConversationInfo","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)ConversationInfo"},{"text":")","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationViewModel\/read(info:)","title":"read(info:)","navigatorTitle":[{"text":"readWithInfo:","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ConversationInfo":{"title":"ConversationInfo","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ConversationInfo","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/conversationinfo","role":"symbol","abstract":[],"type":"topic","navigatorTitle":[{"text":"ConversationInfo","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationInfo"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"readWithInfo:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"readWithInfo:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"kind":"identifier","text":"readWithInfo:"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationInfo","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)ConversationInfo","text":"ConversationInfo","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"info","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationViewModel\/title","value":"ConversationViewModel"},{"value":[{"text":"ConversationViewModel","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationViewModel\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"ConversationViewModel"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationViewModel\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationViewModel~1read(info:)\/title","value":"readWithInfo:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"readWithInfo:"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationViewModel~1read(info:)\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationInfo\/title","value":"ConversationInfo","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationInfo\/fragments","value":[{"text":"ConversationInfo","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"ConversationInfo"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationInfo\/navigatorTitle"}]}]}