{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationViewModel"]]},"abstract":[{"type":"text","text":"When conversation clicked."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationViewModel\/toChat"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/conversationviewmodel\/tochat"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/conversationviewmodel\/tochat"]}],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"metadata":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"toChat"},{"text":": ((","kind":"text"},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":", "},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)ConversationInfo","text":"ConversationInfo","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")?","kind":"text"}],"roleHeading":"Instance Property","modules":[{"name":"ShengwangChatUIKit"}],"externalID":"c:@M@ShengwangChatUIKit@objc(cs)ConversationViewModel(py)toChat","navigatorTitle":[{"kind":"identifier","text":"toChat"}],"title":"toChat","symbolKind":"property"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"toChat"},{"text":": ((","kind":"text"},{"preciseIdentifier":"s:10Foundation9IndexPathV","text":"IndexPath","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"typeIdentifier","text":"ConversationInfo","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationInfo","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)ConversationInfo"},{"text":") -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?"}],"platforms":["iOS"]}]}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ConversationViewModel/toChat":{"type":"topic","title":"toChat","kind":"symbol","abstract":[{"type":"text","text":"When conversation clicked."}],"role":"symbol","url":"\/documentation\/shengwangchatuikit\/conversationviewmodel\/tochat","navigatorTitle":[{"text":"toChat","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationViewModel\/toChat","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"toChat","kind":"identifier"},{"text":": ((","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation9IndexPathV","text":"IndexPath"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"ConversationInfo","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)ConversationInfo"},{"text":") -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?","kind":"text"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ConversationViewModel":{"url":"\/documentation\/shengwangchatuikit\/conversationviewmodel","type":"topic","role":"symbol","abstract":[{"text":"Bind service and driver","type":"text"}],"title":"ConversationViewModel","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ConversationViewModel","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationViewModel","navigatorTitle":[{"text":"ConversationViewModel","kind":"identifier"}],"kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ConversationInfo":{"title":"ConversationInfo","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ConversationInfo","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/conversationinfo","role":"symbol","abstract":[],"type":"topic","navigatorTitle":[{"text":"ConversationInfo","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationInfo"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"toChat"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"toChat","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"text":" (^","kind":"text"},{"kind":"identifier","text":"toChat"},{"kind":"text","text":")("},{"text":"NSIndexPath","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSIndexPath"},{"text":" * ","kind":"text"},{"kind":"internalParam","text":""},{"text":", ","kind":"text"},{"kind":"typeIdentifier","text":"ConversationInfo","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationInfo","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)ConversationInfo"},{"text":" * ","kind":"text"},{"text":"","kind":"internalParam"},{"text":");","kind":"text"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationViewModel~1toChat\/title","value":"toChat","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationViewModel~1toChat\/fragments","op":"replace","value":[{"text":"toChat","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationViewModel\/title","value":"ConversationViewModel","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationViewModel\/fragments","value":[{"text":"ConversationViewModel","kind":"identifier"}],"op":"replace"},{"value":[{"text":"ConversationViewModel","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationViewModel\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationInfo\/title","value":"ConversationInfo"},{"value":[{"kind":"identifier","text":"ConversationInfo"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationInfo\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"ConversationInfo"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationInfo\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}