{"metadata":{"roleHeading":"Instance Property","symbolKind":"property","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageView"},{"text":": ","kind":"text"},{"text":"ImageView","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)ImageView","kind":"typeIdentifier"}],"externalID":"s:18ShengwangChatUIKit20URLPreviewResultViewC05imageF0AA05ImageF0Cvp","title":"imageView","modules":[{"name":"ShengwangChatUIKit"}]},"kind":"symbol","sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/URLPreviewResultView\/imageView"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/urlpreviewresultview\/imageview"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/URLPreviewResultView"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"imageView","kind":"identifier"},{"kind":"text","text":": "},{"text":"ImageView","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ImageView","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)ImageView","kind":"typeIdentifier"},{"text":" { get }","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/URLPreviewResultView":{"abstract":[],"url":"\/documentation\/shengwangchatuikit\/urlpreviewresultview","title":"URLPreviewResultView","navigatorTitle":[{"kind":"identifier","text":"URLPreviewResultView"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"URLPreviewResultView"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/URLPreviewResultView","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ImageView":{"title":"ImageView","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ImageView","kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ImageView","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ImageView"}],"abstract":[{"text":"A subclass of ","type":"text"},{"type":"codeVoice","code":"UIImageView"},{"text":" that provides a method for loading an image from a URL.","type":"text"}],"url":"\/documentation\/shengwangchatuikit\/imageview"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/URLPreviewResultView/imageView":{"abstract":[],"kind":"symbol","role":"symbol","url":"\/documentation\/shengwangchatuikit\/urlpreviewresultview\/imageview","type":"topic","title":"imageView","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/URLPreviewResultView\/imageView","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"imageView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ImageView","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)ImageView"}]}},"variantOverrides":[{"patch":[{"value":"URLPreviewResultView","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1URLPreviewResultView\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1URLPreviewResultView\/fragments","value":[{"kind":"identifier","text":"URLPreviewResultView"}],"op":"replace"},{"op":"replace","value":[{"text":"URLPreviewResultView","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1URLPreviewResultView\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ImageView\/title","value":"ImageView"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ImageView\/fragments","value":[{"text":"ImageView","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ImageView\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"ImageView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}