{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","kind":"attribute","text":"MainActor"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"show"},{"kind":"text","text":"("},{"text":"with","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"content","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"URLPreviewManager","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/URLPreviewManager","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)URLPreviewManager","kind":"typeIdentifier"},{"text":".","kind":"text"},{"kind":"typeIdentifier","text":"HTMLContent","preciseIdentifier":"s:18ShengwangChatUIKit17URLPreviewManagerC11HTMLContentC","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/URLPreviewManager\/HTMLContent"},{"text":"?)","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"show"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"with"},{"text":": ","kind":"text"},{"text":"URLPreviewManager","kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)URLPreviewManager"},{"text":".","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit17URLPreviewManagerC11HTMLContentC","text":"HTMLContent"},{"text":"?)","kind":"text"}],"externalID":"c:@M@ShengwangChatUIKit@objc(cs)URLPreviewResultView(im)showWith:","modules":[{"name":"ShengwangChatUIKit"}],"roleHeading":"Instance Method","symbolKind":"method","title":"show(with:)","role":"symbol","navigatorTitle":[{"text":"showWith:","kind":"identifier"}]},"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/URLPreviewResultView\/show(with:)","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/URLPreviewResultView"]]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/urlpreviewresultview\/show(with:)"]},{"paths":["\/documentation\/shengwangchatuikit\/urlpreviewresultview\/show(with:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/URLPreviewResultView/show(with:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"show","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"URLPreviewManager","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)URLPreviewManager","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"HTMLContent","kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit17URLPreviewManagerC11HTMLContentC"},{"kind":"text","text":"?)"}],"kind":"symbol","url":"\/documentation\/shengwangchatuikit\/urlpreviewresultview\/show(with:)","type":"topic","title":"show(with:)","abstract":[],"role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/URLPreviewResultView\/show(with:)","navigatorTitle":[{"text":"showWith:","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/URLPreviewManager":{"abstract":[],"navigatorTitle":[{"text":"URLPreviewManager","kind":"identifier"}],"title":"URLPreviewManager","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/URLPreviewManager","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"URLPreviewManager","kind":"identifier"}],"type":"topic","kind":"symbol","url":"\/documentation\/shengwangchatuikit\/urlpreviewmanager"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/URLPreviewManager/HTMLContent":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HTMLContent","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/shengwangchatuikit\/urlpreviewmanager\/htmlcontent","type":"topic","title":"URLPreviewManager.HTMLContent","abstract":[],"role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/URLPreviewManager\/HTMLContent","navigatorTitle":[{"text":"HTMLContent","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/URLPreviewResultView":{"abstract":[],"url":"\/documentation\/shengwangchatuikit\/urlpreviewresultview","title":"URLPreviewResultView","navigatorTitle":[{"kind":"identifier","text":"URLPreviewResultView"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"URLPreviewResultView"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/URLPreviewResultView","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"showWith:","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"showWith:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"showWith:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)HTMLContent","text":"HTMLContent","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"content"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}},{"value":"showWith:","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1URLPreviewResultView~1show(with:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"showWith:"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1URLPreviewResultView~1show(with:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1URLPreviewManager\/title","value":"URLPreviewManager","op":"replace"},{"value":[{"kind":"identifier","text":"URLPreviewManager"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1URLPreviewManager\/fragments"},{"value":[{"text":"URLPreviewManager","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1URLPreviewManager\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1URLPreviewResultView\/title","value":"URLPreviewResultView"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1URLPreviewResultView\/fragments","value":[{"text":"URLPreviewResultView","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1URLPreviewResultView\/navigatorTitle","value":[{"kind":"identifier","text":"URLPreviewResultView"}]}]}]}