{"kind":"article","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UserServiceImplement\/AgoraChatClientDelegate-Implementations"},"topicSections":[{"generated":true,"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UserServiceImplement\/autoLoginDidCompleteWithError(_:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UserServiceImplement\/connectionStateDidChange(_:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UserServiceImplement\/tokenDidExpire(_:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UserServiceImplement\/tokenWillExpire(_:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UserServiceImplement\/userAccountDidForced(toLogout:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UserServiceImplement\/userAccountDidLogin(fromOtherDevice:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UserServiceImplement\/userAccountDidRemoveFromServer()","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UserServiceImplement\/userDidForbidByServer()"],"anchor":"Instance-Methods"}],"sections":[],"variants":[{"paths":["\/documentation\/shengwangchatuikit\/userserviceimplement\/agorachatclientdelegate-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/shengwangchatuikit\/userserviceimplement\/agorachatclientdelegate-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UserServiceImplement"]]},"metadata":{"modules":[{"name":"ShengwangChatUIKit"}],"roleHeading":"API Collection","role":"collectionGroup","title":"AgoraChatClientDelegate Implementations"},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/UserServiceImplement/tokenWillExpire(_:)":{"role":"symbol","type":"topic","title":"tokenWillExpire(_:)","url":"\/documentation\/shengwangchatuikit\/userserviceimplement\/tokenwillexpire(_:)","abstract":[],"navigatorTitle":[{"text":"tokenWillExpire:","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UserServiceImplement\/tokenWillExpire(_:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"tokenWillExpire"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:18ShengwangChatUIKit0B9ErrorCodea","text":"ChatErrorCode","kind":"typeIdentifier"},{"kind":"text","text":")"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/UserServiceImplement/connectionStateDidChange(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"connectionStateDidChange"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:18ShengwangChatUIKit15ConnectionStatea","text":"ConnectionState","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"connectionStateDidChange:"}],"title":"connectionStateDidChange(_:)","url":"\/documentation\/shengwangchatuikit\/userserviceimplement\/connectionstatedidchange(_:)","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UserServiceImplement\/connectionStateDidChange(_:)","role":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/UserServiceImplement/userDidForbidByServer()":{"type":"topic","title":"userDidForbidByServer()","navigatorTitle":[{"text":"userDidForbidByServer","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UserServiceImplement\/userDidForbidByServer()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"userDidForbidByServer"},{"kind":"text","text":"()"}],"kind":"symbol","role":"symbol","url":"\/documentation\/shengwangchatuikit\/userserviceimplement\/userdidforbidbyserver()"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/UserServiceImplement/tokenDidExpire(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"tokenDidExpire","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"s:18ShengwangChatUIKit0B9ErrorCodea","text":"ChatErrorCode","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","type":"topic","role":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UserServiceImplement\/tokenDidExpire(_:)","title":"tokenDidExpire(_:)","navigatorTitle":[{"text":"tokenDidExpire:","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/userserviceimplement\/tokendidexpire(_:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/UserServiceImplement/userAccountDidRemoveFromServer()":{"title":"userAccountDidRemoveFromServer()","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UserServiceImplement\/userAccountDidRemoveFromServer()","url":"\/documentation\/shengwangchatuikit\/userserviceimplement\/useraccountdidremovefromserver()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"userAccountDidRemoveFromServer","kind":"identifier"},{"kind":"text","text":"()"}],"role":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"userAccountDidRemoveFromServer"}],"kind":"symbol","type":"topic"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/UserServiceImplement/userAccountDidLogin(fromOtherDevice:)":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UserServiceImplement\/userAccountDidLogin(fromOtherDevice:)","navigatorTitle":[{"text":"userAccountDidLoginFromOtherDevice:","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/userserviceimplement\/useraccountdidlogin(fromotherdevice:)","type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"userAccountDidLogin","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"fromOtherDevice"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"title":"userAccountDidLogin(fromOtherDevice:)","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/UserServiceImplement/autoLoginDidCompleteWithError(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"autoLoginDidCompleteWithError"},{"kind":"text","text":"("},{"preciseIdentifier":"s:18ShengwangChatUIKit0B5Errora","text":"ChatError","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"type":"topic","navigatorTitle":[{"text":"autoLoginDidCompleteWithError:","kind":"identifier"}],"title":"autoLoginDidCompleteWithError(_:)","url":"\/documentation\/shengwangchatuikit\/userserviceimplement\/autologindidcompletewitherror(_:)","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UserServiceImplement\/autoLoginDidCompleteWithError(_:)","role":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/UserServiceImplement":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UserServiceImplement","kind":"identifier"}],"kind":"symbol","type":"topic","role":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UserServiceImplement","title":"UserServiceImplement","navigatorTitle":[{"kind":"identifier","text":"UserServiceImplement"}],"url":"\/documentation\/shengwangchatuikit\/userserviceimplement"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/UserServiceImplement/userAccountDidForced(toLogout:)":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UserServiceImplement\/userAccountDidForced(toLogout:)","navigatorTitle":[{"text":"userAccountDidForcedToLogout:","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/userserviceimplement\/useraccountdidforced(tologout:)","type":"topic","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"userAccountDidForced","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"toLogout"},{"text":": ","kind":"text"},{"text":"ChatError","preciseIdentifier":"s:18ShengwangChatUIKit0B5Errora","kind":"typeIdentifier"},{"kind":"text","text":"?)"}],"title":"userAccountDidForced(toLogout:)","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","anchor":"Instance-Methods","generated":true,"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UserServiceImplement\/autoLoginDidCompleteWithError(_:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UserServiceImplement\/connectionStateDidChange(_:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UserServiceImplement\/tokenDidExpire(_:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UserServiceImplement\/tokenWillExpire(_:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UserServiceImplement\/userAccountDidForced(toLogout:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UserServiceImplement\/userAccountDidLogin(fromOtherDevice:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UserServiceImplement\/userAccountDidRemoveFromServer()","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UserServiceImplement\/userDidForbidByServer()"]}]},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1UserServiceImplement~1tokenWillExpire(_:)\/title","op":"replace","value":"tokenWillExpire:"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1UserServiceImplement~1tokenWillExpire(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"tokenWillExpire:","kind":"identifier"}],"op":"replace"},{"value":"connectionStateDidChange:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1UserServiceImplement~1connectionStateDidChange(_:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1UserServiceImplement~1connectionStateDidChange(_:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"connectionStateDidChange:","kind":"identifier"}],"op":"replace"},{"value":"userDidForbidByServer","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1UserServiceImplement~1userDidForbidByServer()\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1UserServiceImplement~1userDidForbidByServer()\/fragments","value":[{"kind":"text","text":"- "},{"text":"userDidForbidByServer","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1UserServiceImplement~1tokenDidExpire(_:)\/title","value":"tokenDidExpire:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1UserServiceImplement~1tokenDidExpire(_:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"tokenDidExpire:","kind":"identifier"}]},{"value":"userAccountDidRemoveFromServer","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1UserServiceImplement~1userAccountDidRemoveFromServer()\/title"},{"value":[{"kind":"text","text":"- "},{"text":"userAccountDidRemoveFromServer","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1UserServiceImplement~1userAccountDidRemoveFromServer()\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1UserServiceImplement~1userAccountDidLogin(fromOtherDevice:)\/title","value":"userAccountDidLoginFromOtherDevice:"},{"value":[{"text":"- ","kind":"text"},{"text":"userAccountDidLoginFromOtherDevice:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1UserServiceImplement~1userAccountDidLogin(fromOtherDevice:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1UserServiceImplement~1autoLoginDidCompleteWithError(_:)\/title","value":"autoLoginDidCompleteWithError:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"autoLoginDidCompleteWithError:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1UserServiceImplement~1autoLoginDidCompleteWithError(_:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1UserServiceImplement\/title","value":"UserServiceImplement"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1UserServiceImplement\/fragments","op":"replace","value":[{"kind":"identifier","text":"UserServiceImplement"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1UserServiceImplement\/navigatorTitle","value":[{"text":"UserServiceImplement","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1UserServiceImplement~1userAccountDidForced(toLogout:)\/title","value":"userAccountDidForcedToLogout:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1UserServiceImplement~1userAccountDidForced(toLogout:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"userAccountDidForcedToLogout:"}]}]}]}