{"metadata":{"extendedModule":"ShengwangChatUIKit","roleHeading":"Instance Method","title":"bindUserStateChangedListener(listener:)","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"bindUserStateChangedListenerWithListener:"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"bindUserStateChangedListener"},{"kind":"text","text":"("},{"text":"listener","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(pl)UserStateChangedListener","text":"UserStateChangedListener","kind":"typeIdentifier"},{"text":")","kind":"text"}],"modules":[{"name":"ShengwangChatUIKit"}],"role":"symbol","externalID":"c:@CM@ShengwangChatUIKit@objc(cs)UserServiceImplement(im)bindUserStateChangedListenerWithListener:"},"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UserServiceImplement\/bindUserStateChangedListener(listener:)","interfaceLanguage":"swift"},"abstract":[{"text":"Bind user state changed listener","type":"text"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bindUserStateChangedListener","kind":"identifier"},{"text":"(","kind":"text"},{"text":"listener","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UserStateChangedListener","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UserStateChangedListener","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(pl)UserStateChangedListener"},{"kind":"text","text":")"}]}],"kind":"declarations"},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"UserStateChangedListener","type":"text"}]}],"name":"listener"}],"kind":"parameters"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/userserviceimplement\/binduserstatechangedlistener(listener:)"]},{"paths":["\/documentation\/shengwangchatuikit\/userserviceimplement\/binduserstatechangedlistener(listener:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UserServiceImplement","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UserServiceImplement\/UserServiceProtocol-Implementations"]]},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/UserServiceImplement/UserServiceProtocol-Implementations":{"role":"collectionGroup","kind":"article","abstract":[],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UserServiceImplement\/UserServiceProtocol-Implementations","type":"topic","title":"UserServiceProtocol Implementations","url":"\/documentation\/shengwangchatuikit\/userserviceimplement\/userserviceprotocol-implementations"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/UserServiceImplement/bindUserStateChangedListener(listener:)":{"abstract":[{"type":"text","text":"Bind user state changed listener"}],"kind":"symbol","url":"\/documentation\/shengwangchatuikit\/userserviceimplement\/binduserstatechangedlistener(listener:)","navigatorTitle":[{"kind":"identifier","text":"bindUserStateChangedListenerWithListener:"}],"title":"bindUserStateChangedListener(listener:)","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UserServiceImplement\/bindUserStateChangedListener(listener:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bindUserStateChangedListener"},{"kind":"text","text":"("},{"text":"listener","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UserStateChangedListener","kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(pl)UserStateChangedListener"},{"text":")","kind":"text"}],"type":"topic"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/UserServiceImplement":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UserServiceImplement","kind":"identifier"}],"kind":"symbol","type":"topic","role":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UserServiceImplement","title":"UserServiceImplement","navigatorTitle":[{"kind":"identifier","text":"UserServiceImplement"}],"url":"\/documentation\/shengwangchatuikit\/userserviceimplement"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/UserStateChangedListener":{"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"UserStateChangedListener","kind":"identifier"}],"navigatorTitle":[{"text":"UserStateChangedListener","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/userstatechangedlistener","type":"topic","abstract":[],"title":"UserStateChangedListener","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UserStateChangedListener","role":"symbol","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","value":"bindUserStateChangedListenerWithListener:","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"bindUserStateChangedListenerWithListener:"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"bindUserStateChangedListenerWithListener:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"id<UserStateChangedListener>","preciseIdentifier":"c:Qo@M@ShengwangChatUIKit@objc(pl)UserStateChangedListener"},{"text":") ","kind":"text"},{"text":"listener","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1UserServiceImplement~1bindUserStateChangedListener(listener:)\/title","value":"bindUserStateChangedListenerWithListener:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"bindUserStateChangedListenerWithListener:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1UserServiceImplement~1bindUserStateChangedListener(listener:)\/fragments"},{"value":"UserServiceImplement","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1UserServiceImplement\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1UserServiceImplement\/fragments","op":"replace","value":[{"kind":"identifier","text":"UserServiceImplement"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1UserServiceImplement\/navigatorTitle","value":[{"kind":"identifier","text":"UserServiceImplement"}],"op":"replace"},{"value":"UserStateChangedListener","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1UserStateChangedListener\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1UserStateChangedListener\/fragments","value":[{"text":"UserStateChangedListener","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"UserStateChangedListener"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1UserStateChangedListener\/navigatorTitle","op":"replace"}]}]}