{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"registerEventListener","kind":"identifier"},{"text":"()","kind":"text"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UserServiceImplement"]]},"sections":[],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UserServiceImplement\/registerEventListener()"},"metadata":{"role":"symbol","externalID":"c:@M@ShengwangChatUIKit@objc(cs)UserServiceImplement(im)registerEventListener","symbolKind":"method","navigatorTitle":[{"text":"registerEventListener","kind":"identifier"}],"title":"registerEventListener()","modules":[{"name":"ShengwangChatUIKit"}],"roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"registerEventListener","kind":"identifier"},{"text":"()","kind":"text"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/userserviceimplement\/registereventlistener()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/userserviceimplement\/registereventlistener()"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/UserServiceImplement":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UserServiceImplement","kind":"identifier"}],"kind":"symbol","type":"topic","role":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UserServiceImplement","title":"UserServiceImplement","navigatorTitle":[{"kind":"identifier","text":"UserServiceImplement"}],"url":"\/documentation\/shengwangchatuikit\/userserviceimplement"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/UserServiceImplement/registerEventListener()":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"registerEventListener","kind":"identifier"},{"text":"()","kind":"text"}],"navigatorTitle":[{"text":"registerEventListener","kind":"identifier"}],"role":"symbol","url":"\/documentation\/shengwangchatuikit\/userserviceimplement\/registereventlistener()","kind":"symbol","abstract":[],"title":"registerEventListener()","type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UserServiceImplement\/registerEventListener()"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"registerEventListener"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"registerEventListener","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"registerEventListener"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1UserServiceImplement\/title","value":"UserServiceImplement"},{"value":[{"kind":"identifier","text":"UserServiceImplement"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1UserServiceImplement\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1UserServiceImplement\/navigatorTitle","op":"replace","value":[{"text":"UserServiceImplement","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1UserServiceImplement~1registerEventListener()\/title","value":"registerEventListener","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1UserServiceImplement~1registerEventListener()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"registerEventListener","kind":"identifier"}],"op":"replace"}]}]}