{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UserServiceImplement","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UserServiceImplement\/AgoraChatClientDelegate-Implementations"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UserServiceImplement\/tokenDidExpire(_:)"},"kind":"symbol","abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"AgoraChatClientDelegate.tokenDidExpire(_:)"},{"text":".","type":"text"}],"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tokenDidExpire"},{"kind":"text","text":"("},{"text":"ChatErrorCode","preciseIdentifier":"s:18ShengwangChatUIKit0B9ErrorCodea","kind":"typeIdentifier"},{"text":")","kind":"text"}],"externalID":"c:@CM@ShengwangChatUIKit@objc(cs)UserServiceImplement(im)tokenDidExpire:","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"tokenDidExpire:"}],"role":"symbol","extendedModule":"ShengwangChatUIKit","roleHeading":"Instance Method","title":"tokenDidExpire(_:)","modules":[{"name":"ShengwangChatUIKit"}]},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"tokenDidExpire","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"aErrorCode","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"ChatErrorCode","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatErrorCode","preciseIdentifier":"s:18ShengwangChatUIKit0B9ErrorCodea","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/userserviceimplement\/tokendidexpire(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/userserviceimplement\/tokendidexpire(_:)"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/UserServiceImplement/AgoraChatClientDelegate-Implementations":{"abstract":[],"kind":"article","role":"collectionGroup","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UserServiceImplement\/AgoraChatClientDelegate-Implementations","url":"\/documentation\/shengwangchatuikit\/userserviceimplement\/agorachatclientdelegate-implementations","title":"AgoraChatClientDelegate Implementations","type":"topic"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/UserServiceImplement/tokenDidExpire(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"tokenDidExpire","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"s:18ShengwangChatUIKit0B9ErrorCodea","text":"ChatErrorCode","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","type":"topic","role":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UserServiceImplement\/tokenDidExpire(_:)","title":"tokenDidExpire(_:)","navigatorTitle":[{"text":"tokenDidExpire:","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/userserviceimplement\/tokendidexpire(_:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatErrorCode":{"navigatorTitle":[{"kind":"identifier","text":"ChatErrorCode"}],"abstract":[],"kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatErrorCode","url":"\/documentation\/shengwangchatuikit\/chaterrorcode","title":"ChatErrorCode","type":"topic","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChatErrorCode","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/UserServiceImplement":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UserServiceImplement","kind":"identifier"}],"kind":"symbol","type":"topic","role":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UserServiceImplement","title":"UserServiceImplement","navigatorTitle":[{"kind":"identifier","text":"UserServiceImplement"}],"url":"\/documentation\/shengwangchatuikit\/userserviceimplement"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"tokenDidExpire:","op":"replace"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"tokenDidExpire:"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"tokenDidExpire:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@AgoraChatErrorCode","text":"AgoraChatErrorCode"},{"kind":"text","text":") "},{"text":"aErrorCode","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1UserServiceImplement~1tokenDidExpire(_:)\/title","value":"tokenDidExpire:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"tokenDidExpire:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1UserServiceImplement~1tokenDidExpire(_:)\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1UserServiceImplement\/title","value":"UserServiceImplement","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1UserServiceImplement\/fragments","value":[{"kind":"identifier","text":"UserServiceImplement"}],"op":"replace"},{"value":[{"text":"UserServiceImplement","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1UserServiceImplement\/navigatorTitle","op":"replace"}]}]}