{"metadata":{"extendedModule":"ShengwangChatUIKit","role":"symbol","externalID":"c:@CM@ShengwangChatUIKit@objc(cs)UserServiceImplement(im)userDidForbidByServer","modules":[{"name":"ShengwangChatUIKit"}],"roleHeading":"Instance Method","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"userDidForbidByServer"},{"kind":"text","text":"()"}],"title":"userDidForbidByServer()","navigatorTitle":[{"text":"userDidForbidByServer","kind":"identifier"}]},"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UserServiceImplement","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UserServiceImplement\/AgoraChatClientDelegate-Implementations"]]},"abstract":[{"type":"text","text":"Inherited from "},{"code":"AgoraChatClientDelegate.userDidForbidByServer()","type":"codeVoice"},{"type":"text","text":"."}],"variants":[{"paths":["\/documentation\/shengwangchatuikit\/userserviceimplement\/userdidforbidbyserver()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/userserviceimplement\/userdidforbidbyserver()"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UserServiceImplement\/userDidForbidByServer()"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"userDidForbidByServer"},{"text":"()","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/UserServiceImplement":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UserServiceImplement","kind":"identifier"}],"kind":"symbol","type":"topic","role":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UserServiceImplement","title":"UserServiceImplement","navigatorTitle":[{"kind":"identifier","text":"UserServiceImplement"}],"url":"\/documentation\/shengwangchatuikit\/userserviceimplement"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/UserServiceImplement/AgoraChatClientDelegate-Implementations":{"abstract":[],"kind":"article","role":"collectionGroup","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UserServiceImplement\/AgoraChatClientDelegate-Implementations","url":"\/documentation\/shengwangchatuikit\/userserviceimplement\/agorachatclientdelegate-implementations","title":"AgoraChatClientDelegate Implementations","type":"topic"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/UserServiceImplement/userDidForbidByServer()":{"type":"topic","title":"userDidForbidByServer()","navigatorTitle":[{"text":"userDidForbidByServer","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UserServiceImplement\/userDidForbidByServer()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"userDidForbidByServer"},{"kind":"text","text":"()"}],"kind":"symbol","role":"symbol","url":"\/documentation\/shengwangchatuikit\/userserviceimplement\/userdidforbidbyserver()"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"userDidForbidByServer","path":"\/metadata\/title","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"userDidForbidByServer","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"userDidForbidByServer","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1UserServiceImplement\/title","value":"UserServiceImplement"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1UserServiceImplement\/fragments","op":"replace","value":[{"kind":"identifier","text":"UserServiceImplement"}]},{"value":[{"text":"UserServiceImplement","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1UserServiceImplement\/navigatorTitle"},{"value":"userDidForbidByServer","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1UserServiceImplement~1userDidForbidByServer()\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"userDidForbidByServer"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1UserServiceImplement~1userDidForbidByServer()\/fragments"}]}]}