{"metadata":{"roleHeading":"API Collection","role":"collectionGroup","modules":[{"name":"ShengwangChatUIKit"}],"title":"UserServiceProtocol Implementations"},"kind":"article","topicSections":[{"anchor":"Instance-Methods","generated":true,"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UserServiceImplement\/bindUserStateChangedListener(listener:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UserServiceImplement\/login(userId:token:completion:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UserServiceImplement\/logout(unbindNotificationDeviceToken:completion:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UserServiceImplement\/unBindUserStateChangedListener(listener:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UserServiceImplement\/updateUserInfo(userInfo:completion:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UserServiceImplement\/userInfo(userId:completion:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UserServiceImplement\/userInfos(userIds:completion:)"],"title":"Instance Methods"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UserServiceImplement"]]},"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UserServiceImplement\/UserServiceProtocol-Implementations","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/userserviceimplement\/userserviceprotocol-implementations"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/userserviceimplement\/userserviceprotocol-implementations"]}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/UserServiceImplement/userInfo(userId:completion:)":{"abstract":[{"text":"Get user info by userId.The frequency of api usage for free users is 100 times in 1 second.Upgrading the package can increase the usage.","type":"text"}],"role":"symbol","kind":"symbol","type":"topic","navigatorTitle":[{"text":"userInfoWithUserId:completion:","kind":"identifier"}],"title":"userInfo(userId:completion:)","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UserServiceImplement\/userInfo(userId:completion:)","url":"\/documentation\/shengwangchatuikit\/userserviceimplement\/userinfo(userid:completion:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"userInfo","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"userId"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": ("},{"text":"ChatUserProfileProtocol","kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(pl)ChatUserProfileProtocol"},{"text":"?, ","kind":"text"},{"preciseIdentifier":"s:18ShengwangChatUIKit0B5Errora","text":"ChatError","kind":"typeIdentifier"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")","kind":"text"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/UserServiceImplement/updateUserInfo(userInfo:completion:)":{"title":"updateUserInfo(userInfo:completion:)","abstract":[{"text":"Update user info.The frequency of api usage for free users is 100 times in 1 second.Upgrading the package can increase the usage.","type":"text"}],"navigatorTitle":[{"text":"updateUserInfoWithUserInfo:completion:","kind":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UserServiceImplement\/updateUserInfo(userInfo:completion:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateUserInfo"},{"kind":"text","text":"("},{"kind":"externalParam","text":"userInfo"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(pl)ChatUserProfileProtocol","text":"ChatUserProfileProtocol","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"text":": (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit0B5Errora","text":"ChatError"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"role":"symbol","url":"\/documentation\/shengwangchatuikit\/userserviceimplement\/updateuserinfo(userinfo:completion:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/UserServiceImplement/logout(unbindNotificationDeviceToken:completion:)":{"abstract":[{"text":"Logout SDK","type":"text"}],"kind":"symbol","url":"\/documentation\/shengwangchatuikit\/userserviceimplement\/logout(unbindnotificationdevicetoken:completion:)","navigatorTitle":[{"kind":"identifier","text":"logoutWithUnbindNotificationDeviceToken:completion:"}],"title":"logout(unbindNotificationDeviceToken:completion:)","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UserServiceImplement\/logout(unbindNotificationDeviceToken:completion:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"logout"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"unbindNotificationDeviceToken"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":", ","kind":"text"},{"text":"ChatError","kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit0B5Errora"},{"kind":"text","text":"?) -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"type":"topic"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/UserServiceImplement/unBindUserStateChangedListener(listener:)":{"title":"unBindUserStateChangedListener(listener:)","abstract":[{"text":"Unbind user state changed listener","type":"text"}],"navigatorTitle":[{"text":"unBindUserStateChangedListenerWithListener:","kind":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UserServiceImplement\/unBindUserStateChangedListener(listener:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"unBindUserStateChangedListener","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"listener"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(pl)UserStateChangedListener","text":"UserStateChangedListener"},{"kind":"text","text":")"}],"role":"symbol","url":"\/documentation\/shengwangchatuikit\/userserviceimplement\/unbinduserstatechangedlistener(listener:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/UserServiceImplement/bindUserStateChangedListener(listener:)":{"abstract":[{"type":"text","text":"Bind user state changed listener"}],"kind":"symbol","url":"\/documentation\/shengwangchatuikit\/userserviceimplement\/binduserstatechangedlistener(listener:)","navigatorTitle":[{"kind":"identifier","text":"bindUserStateChangedListenerWithListener:"}],"title":"bindUserStateChangedListener(listener:)","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UserServiceImplement\/bindUserStateChangedListener(listener:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bindUserStateChangedListener"},{"kind":"text","text":"("},{"text":"listener","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UserStateChangedListener","kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(pl)UserStateChangedListener"},{"text":")","kind":"text"}],"type":"topic"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/UserServiceImplement":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UserServiceImplement","kind":"identifier"}],"kind":"symbol","type":"topic","role":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UserServiceImplement","title":"UserServiceImplement","navigatorTitle":[{"kind":"identifier","text":"UserServiceImplement"}],"url":"\/documentation\/shengwangchatuikit\/userserviceimplement"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/UserServiceImplement/login(userId:token:completion:)":{"title":"login(userId:token:completion:)","abstract":[{"type":"text","text":"Login SDK"}],"navigatorTitle":[{"text":"loginWithUserId:token:completion:","kind":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UserServiceImplement\/login(userId:token:completion:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"login","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"userId"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"token"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"text":": (","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":", "},{"text":"ChatError","kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit0B5Errora"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"text":")","kind":"text"}],"role":"symbol","url":"\/documentation\/shengwangchatuikit\/userserviceimplement\/login(userid:token:completion:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/UserServiceImplement/userInfos(userIds:completion:)":{"abstract":[{"text":"Get user info by userIds.The frequency of api usage for free users is 100 times in 1 second.Upgrading the package can increase the usage.","type":"text"}],"kind":"symbol","url":"\/documentation\/shengwangchatuikit\/userserviceimplement\/userinfos(userids:completion:)","navigatorTitle":[{"text":"userInfosWithUserIds:completion:","kind":"identifier"}],"title":"userInfos(userIds:completion:)","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UserServiceImplement\/userInfos(userIds:completion:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"userInfos","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"userIds"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"completion"},{"text":": ([","kind":"text"},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(pl)ChatUserProfileProtocol","kind":"typeIdentifier","text":"ChatUserProfileProtocol"},{"kind":"text","text":"], "},{"kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit0B5Errora","text":"ChatError"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"type":"topic"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":[{"generated":true,"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UserServiceImplement\/bindUserStateChangedListener(listener:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UserServiceImplement\/login(userId:token:completion:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UserServiceImplement\/logout(unbindNotificationDeviceToken:completion:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UserServiceImplement\/unBindUserStateChangedListener(listener:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UserServiceImplement\/updateUserInfo(userInfo:completion:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UserServiceImplement\/userInfo(userId:completion:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UserServiceImplement\/userInfos(userIds:completion:)"],"anchor":"Instance-Methods","title":"Instance Methods"}],"op":"replace","path":"\/topicSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1UserServiceImplement~1userInfo(userId:completion:)\/title","value":"userInfoWithUserId:completion:"},{"value":[{"kind":"text","text":"- "},{"text":"userInfoWithUserId:completion:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1UserServiceImplement~1userInfo(userId:completion:)\/fragments"},{"op":"replace","value":"updateUserInfoWithUserInfo:completion:","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1UserServiceImplement~1updateUserInfo(userInfo:completion:)\/title"},{"value":[{"kind":"text","text":"- "},{"text":"updateUserInfoWithUserInfo:completion:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1UserServiceImplement~1updateUserInfo(userInfo:completion:)\/fragments","op":"replace"},{"op":"replace","value":"logoutWithUnbindNotificationDeviceToken:completion:","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1UserServiceImplement~1logout(unbindNotificationDeviceToken:completion:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1UserServiceImplement~1logout(unbindNotificationDeviceToken:completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"logoutWithUnbindNotificationDeviceToken:completion:","kind":"identifier"}]},{"op":"replace","value":"unBindUserStateChangedListenerWithListener:","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1UserServiceImplement~1unBindUserStateChangedListener(listener:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"unBindUserStateChangedListenerWithListener:"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1UserServiceImplement~1unBindUserStateChangedListener(listener:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1UserServiceImplement~1bindUserStateChangedListener(listener:)\/title","value":"bindUserStateChangedListenerWithListener:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"bindUserStateChangedListenerWithListener:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1UserServiceImplement~1bindUserStateChangedListener(listener:)\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1UserServiceImplement\/title","value":"UserServiceImplement","op":"replace"},{"value":[{"text":"UserServiceImplement","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1UserServiceImplement\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1UserServiceImplement\/navigatorTitle","value":[{"text":"UserServiceImplement","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1UserServiceImplement~1login(userId:token:completion:)\/title","op":"replace","value":"loginWithUserId:token:completion:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"loginWithUserId:token:completion:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1UserServiceImplement~1login(userId:token:completion:)\/fragments"},{"value":"userInfosWithUserIds:completion:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1UserServiceImplement~1userInfos(userIds:completion:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1UserServiceImplement~1userInfos(userIds:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"userInfosWithUserIds:completion:","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}