{"sections":[],"abstract":[{"type":"text","text":"Handles the navigation bar click events."}],"metadata":{"roleHeading":"Instance Method","role":"symbol","navigatorTitle":[{"text":"navigationClickWithType:indexPath:","kind":"identifier"}],"externalID":"c:@M@ShengwangChatUIKit@objc(cs)ContactViewController(im)navigationClickWithType:indexPath:","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"navigationClick","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"type"},{"kind":"text","text":": "},{"text":"ChatNavigationBarClickEvent","preciseIdentifier":"c:@M@ShengwangChatUIKit@E@ChatNavigationBarClickEvent","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"indexPath","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"text":"?)","kind":"text"}],"title":"navigationClick(type:indexPath:)","modules":[{"name":"ShengwangChatUIKit"}]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/contactviewcontroller\/navigationclick(type:indexpath:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/contactviewcontroller\/navigationclick(type:indexpath:)"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactViewController"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactViewController\/navigationClick(type:indexPath:)"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"attribute","text":"@"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"navigationClick"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"type"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatNavigationBarClickEvent","preciseIdentifier":"c:@M@ShengwangChatUIKit@E@ChatNavigationBarClickEvent","text":"ChatNavigationBarClickEvent"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"indexPath"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":"?)"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"type","content":[{"inlineContent":[{"type":"text","text":"The type of navigation bar click event."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"The index path associated with the click event (optional).","type":"text"}],"type":"paragraph"}],"name":"indexPath"}]}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ContactViewController":{"navigatorTitle":[{"kind":"identifier","text":"ContactViewController"}],"abstract":[],"url":"\/documentation\/shengwangchatuikit\/contactviewcontroller","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactViewController","type":"topic","title":"ContactViewController","role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ContactViewController","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ContactViewController/navigationClick(type:indexPath:)":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactViewController\/navigationClick(type:indexPath:)","navigatorTitle":[{"text":"navigationClickWithType:indexPath:","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/contactviewcontroller\/navigationclick(type:indexpath:)","type":"topic","abstract":[{"type":"text","text":"Handles the navigation bar click events."}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"navigationClick","kind":"identifier"},{"kind":"text","text":"("},{"text":"type","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@E@ChatNavigationBarClickEvent","text":"ChatNavigationBarClickEvent","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"indexPath"},{"kind":"text","text":": "},{"text":"IndexPath","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":"?)"}],"title":"navigationClick(type:indexPath:)","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatNavigationBarClickEvent":{"abstract":[],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatNavigationBarClickEvent","navigatorTitle":[{"kind":"identifier","text":"ChatNavigationBarClickEvent"}],"kind":"symbol","url":"\/documentation\/shengwangchatuikit\/chatnavigationbarclickevent","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatNavigationBarClickEvent"}],"title":"ChatNavigationBarClickEvent","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","value":"navigationClickWithType:indexPath:","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"navigationClickWithType:indexPath:"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"text":") ","kind":"text"},{"text":"navigationClickWithType:","kind":"identifier"},{"kind":"text","text":"("},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatNavigationBarClickEvent","preciseIdentifier":"c:@M@ShengwangChatUIKit@E@ChatNavigationBarClickEvent","text":"ChatNavigationBarClickEvent"},{"kind":"text","text":") "},{"kind":"internalParam","text":"type"},{"text":" ","kind":"text"},{"text":"indexPath:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSIndexPath","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSIndexPath"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"indexPath"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"type","content":[{"type":"paragraph","inlineContent":[{"text":"The type of navigation bar click event.","type":"text"}]}]},{"name":"indexPath","content":[{"inlineContent":[{"type":"text","text":"The index path associated with the click event (optional)."}],"type":"paragraph"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactViewController\/title","value":"ContactViewController"},{"op":"replace","value":[{"text":"ContactViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactViewController\/fragments"},{"op":"replace","value":[{"text":"ContactViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactViewController\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactViewController~1navigationClick(type:indexPath:)\/title","value":"navigationClickWithType:indexPath:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"navigationClickWithType:indexPath:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactViewController~1navigationClick(type:indexPath:)\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatNavigationBarClickEvent\/title","op":"replace","value":"ChatNavigationBarClickEvent"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatNavigationBarClickEvent\/fragments","value":[{"text":"ChatNavigationBarClickEvent","kind":"identifier"}],"op":"replace"},{"value":[{"text":"ChatNavigationBarClickEvent","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatNavigationBarClickEvent\/navigatorTitle"}]}]}