{"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"contentAttributes"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"content"},{"text":": ","kind":"text"},{"text":"NSAttributedString","preciseIdentifier":"c:objc(cs)NSAttributedString","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"text":"AlertView","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/AlertView","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)AlertView","kind":"typeIdentifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"modules":[{"name":"ShengwangChatUIKit"}],"roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"contentAttributesWithContent:"}],"externalID":"c:@M@ShengwangChatUIKit@objc(cs)AlertView(im)contentAttributesWithContent:","title":"contentAttributes(content:)","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"contentAttributes"},{"kind":"text","text":"("},{"kind":"externalParam","text":"content"},{"text":": ","kind":"text"},{"text":"NSAttributedString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSAttributedString"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","text":"AlertView","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)AlertView"}],"role":"symbol"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/alertview\/contentattributes(content:)"]},{"paths":["\/documentation\/shengwangchatuikit\/alertview\/contentattributes(content:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/AlertView"]]},"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/AlertView\/contentAttributes(content:)","interfaceLanguage":"swift"},"sections":[],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/AlertView/contentAttributes(content:)":{"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"contentAttributesWithContent:","kind":"identifier"}],"title":"contentAttributes(content:)","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/AlertView\/contentAttributes(content:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"contentAttributes","kind":"identifier"},{"text":"(","kind":"text"},{"text":"content","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSAttributedString","kind":"typeIdentifier","text":"NSAttributedString"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)AlertView","kind":"typeIdentifier","text":"AlertView"}],"abstract":[],"type":"topic","url":"\/documentation\/shengwangchatuikit\/alertview\/contentattributes(content:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/AlertView":{"title":"AlertView","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AlertView","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/alertview","role":"symbol","abstract":[],"type":"topic","navigatorTitle":[{"text":"AlertView","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/AlertView"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"contentAttributesWithContent:"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"contentAttributesWithContent:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"AlertView","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/AlertView","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)AlertView","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"contentAttributesWithContent:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSAttributedString","preciseIdentifier":"c:objc(cs)NSAttributedString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"content","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"value":"contentAttributesWithContent:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1AlertView~1contentAttributes(content:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"contentAttributesWithContent:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1AlertView~1contentAttributes(content:)\/fragments"},{"op":"replace","value":"AlertView","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1AlertView\/title"},{"op":"replace","value":[{"kind":"identifier","text":"AlertView"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1AlertView\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1AlertView\/navigatorTitle","value":[{"text":"AlertView","kind":"identifier"}],"op":"replace"}]}]}