{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/alertview\/leftbuttonradius(cornerradius:)"]}],"metadata":{"roleHeading":"Instance Method","role":"symbol","externalID":"s:18ShengwangChatUIKit9AlertViewC16leftButtonRadius06cornerH0AcA06CornerH0O_tF","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"leftButtonRadius","kind":"identifier"},{"kind":"text","text":"("},{"text":"cornerRadius","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CornerRadius","preciseIdentifier":"s:18ShengwangChatUIKit12CornerRadiusO"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)AlertView","text":"AlertView"}],"title":"leftButtonRadius(cornerRadius:)","modules":[{"name":"ShengwangChatUIKit"}]},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/AlertView\/leftButtonRadius(cornerRadius:)"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/AlertView"]]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@discardableResult"},{"kind":"text","text":" "},{"text":"@","kind":"attribute"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"leftButtonRadius"},{"kind":"text","text":"("},{"text":"cornerRadius","kind":"externalParam"},{"kind":"text","text":": "},{"text":"CornerRadius","kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit12CornerRadiusO","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/CornerRadius"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/AlertView","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)AlertView","text":"AlertView"}]}]}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/AlertView/leftButtonRadius(cornerRadius:)":{"title":"leftButtonRadius(cornerRadius:)","abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"leftButtonRadius","kind":"identifier"},{"kind":"text","text":"("},{"text":"cornerRadius","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CornerRadius","preciseIdentifier":"s:18ShengwangChatUIKit12CornerRadiusO"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)AlertView","kind":"typeIdentifier","text":"AlertView"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/AlertView\/leftButtonRadius(cornerRadius:)","type":"topic","url":"\/documentation\/shengwangchatuikit\/alertview\/leftbuttonradius(cornerradius:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/AlertView":{"title":"AlertView","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AlertView","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/alertview","role":"symbol","abstract":[],"type":"topic","navigatorTitle":[{"text":"AlertView","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/AlertView"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/CornerRadius":{"title":"CornerRadius","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CornerRadius"}],"url":"\/documentation\/shengwangchatuikit\/cornerradius","role":"symbol","abstract":[{"text":"A set of convenience methods for configuring UIView properties, such as corner radius, background color, gradient, content mode, layer properties, user interaction, tag, center, and transform.","type":"text"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"CornerRadius"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/CornerRadius"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1AlertView\/title","value":"AlertView"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1AlertView\/fragments","value":[{"text":"AlertView","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1AlertView\/navigatorTitle","value":[{"kind":"identifier","text":"AlertView"}],"op":"replace"}]}]}