{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/AlertView"]]},"kind":"symbol","sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/alertview\/leftbutton(color:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/alertview\/leftbutton(color:)"]}],"metadata":{"modules":[{"name":"ShengwangChatUIKit"}],"externalID":"c:@M@ShengwangChatUIKit@objc(cs)AlertView(im)leftButtonWithColor:","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"leftButton","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"color"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","text":"AlertView","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)AlertView"}],"role":"symbol","title":"leftButton(color:)","symbolKind":"method","roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"leftButtonWithColor:"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/AlertView\/leftButton(color:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@discardableResult","kind":"attribute"},{"text":" ","kind":"text"},{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","kind":"attribute","text":"MainActor"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"leftButton"},{"text":"(","kind":"text"},{"text":"color","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/AlertView","text":"AlertView","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)AlertView"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/AlertView/leftButton(color:)":{"kind":"symbol","title":"leftButton(color:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"leftButton","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"color"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"text":"?) -> ","kind":"text"},{"text":"AlertView","kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)AlertView"}],"navigatorTitle":[{"text":"leftButtonWithColor:","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/alertview\/leftbutton(color:)","abstract":[],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/AlertView\/leftButton(color:)","role":"symbol","type":"topic"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/AlertView":{"title":"AlertView","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AlertView","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/alertview","role":"symbol","abstract":[],"type":"topic","navigatorTitle":[{"text":"AlertView","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/AlertView"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"value":"leftButtonWithColor:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"leftButtonWithColor:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"AlertView","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/AlertView","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)AlertView"},{"text":" *) ","kind":"text"},{"text":"leftButtonWithColor:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"color"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"value":"leftButtonWithColor:","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1AlertView~1leftButton(color:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1AlertView~1leftButton(color:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"leftButtonWithColor:","kind":"identifier"}],"op":"replace"},{"value":"AlertView","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1AlertView\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1AlertView\/fragments","value":[{"text":"AlertView","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1AlertView\/navigatorTitle","value":[{"text":"AlertView","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}