{"metadata":{"navigatorTitle":[{"kind":"identifier","text":"rightButtonBorderWithColor:"}],"symbolKind":"method","modules":[{"name":"ShengwangChatUIKit"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rightButtonBorder"},{"kind":"text","text":"("},{"kind":"externalParam","text":"color"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"text":"?) -> ","kind":"text"},{"text":"AlertView","kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)AlertView"}],"externalID":"c:@M@ShengwangChatUIKit@objc(cs)AlertView(im)rightButtonBorderWithColor:","roleHeading":"Instance Method","title":"rightButtonBorder(color:)","role":"symbol"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@discardableResult"},{"text":" ","kind":"text"},{"text":"@","kind":"attribute"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"rightButtonBorder"},{"text":"(","kind":"text"},{"text":"color","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"},{"kind":"text","text":"?) -> "},{"text":"AlertView","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/AlertView","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)AlertView","kind":"typeIdentifier"}]}],"kind":"declarations"}],"sections":[],"variants":[{"paths":["\/documentation\/shengwangchatuikit\/alertview\/rightbuttonborder(color:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/shengwangchatuikit\/alertview\/rightbuttonborder(color:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/AlertView\/rightButtonBorder(color:)"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/AlertView"]]},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/AlertView/rightButtonBorder(color:)":{"type":"topic","role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/AlertView\/rightButtonBorder(color:)","title":"rightButtonBorder(color:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"rightButtonBorder","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"color"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","text":"AlertView","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)AlertView"}],"url":"\/documentation\/shengwangchatuikit\/alertview\/rightbuttonborder(color:)","navigatorTitle":[{"text":"rightButtonBorderWithColor:","kind":"identifier"}],"abstract":[]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/AlertView":{"title":"AlertView","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AlertView","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/alertview","role":"symbol","abstract":[],"type":"topic","navigatorTitle":[{"text":"AlertView","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/AlertView"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"rightButtonBorderWithColor:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"rightButtonBorderWithColor:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/AlertView","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)AlertView","text":"AlertView"},{"kind":"text","text":" *) "},{"text":"rightButtonBorderWithColor:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"color","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1AlertView~1rightButtonBorder(color:)\/title","op":"replace","value":"rightButtonBorderWithColor:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1AlertView~1rightButtonBorder(color:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rightButtonBorderWithColor:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1AlertView\/title","value":"AlertView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1AlertView\/fragments","value":[{"text":"AlertView","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"AlertView"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1AlertView\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}