{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/alertview\/textfieldrightview(rightview:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/alertview\/textfieldrightview(rightview:)"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/AlertView"]]},"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@discardableResult","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"attribute","text":"@"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"textFieldRightView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"rightView","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView","text":"UIView"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/AlertView","text":"AlertView","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)AlertView"}],"platforms":["iOS"]}]}],"metadata":{"role":"symbol","symbolKind":"method","title":"textFieldRightView(rightView:)","externalID":"c:@M@ShengwangChatUIKit@objc(cs)AlertView(im)textFieldRightViewWithRightView:","roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"textFieldRightViewWithRightView:"}],"modules":[{"name":"ShengwangChatUIKit"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"textFieldRightView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"rightView","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UIView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)AlertView","text":"AlertView"}]},"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/AlertView\/textFieldRightView(rightView:)","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/AlertView/textFieldRightView(rightView:)":{"type":"topic","role":"symbol","title":"textFieldRightView(rightView:)","kind":"symbol","abstract":[],"navigatorTitle":[{"text":"textFieldRightViewWithRightView:","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/alertview\/textfieldrightview(rightview:)","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/AlertView\/textFieldRightView(rightView:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"textFieldRightView","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"rightView"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIView","kind":"typeIdentifier","text":"UIView"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)AlertView","text":"AlertView"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/AlertView":{"title":"AlertView","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AlertView","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/alertview","role":"symbol","abstract":[],"type":"topic","navigatorTitle":[{"text":"AlertView","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/AlertView"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"textFieldRightViewWithRightView:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"kind":"text","text":"- "},{"text":"textFieldRightViewWithRightView:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"AlertView","kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)AlertView","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/AlertView"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"textFieldRightViewWithRightView:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIView","kind":"typeIdentifier","text":"UIView"},{"text":" *) ","kind":"text"},{"text":"rightView","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"textFieldRightViewWithRightView:","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1AlertView~1textFieldRightView(rightView:)\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"textFieldRightViewWithRightView:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1AlertView~1textFieldRightView(rightView:)\/fragments"},{"value":"AlertView","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1AlertView\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1AlertView\/fragments","value":[{"text":"AlertView","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1AlertView\/navigatorTitle","value":[{"text":"AlertView","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}