{"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactListActionEventsDelegate"]]},"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactListActionEventsDelegate\/didSelected(indexPath:profile:)","interfaceLanguage":"swift"},"abstract":[{"text":"The method’ll called on contact list cell clicked.","type":"text"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"didSelected"},{"kind":"text","text":"("},{"text":"indexPath","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation9IndexPathV","text":"IndexPath","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"profile","kind":"externalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatUserProfileProtocol","kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(pl)ChatUserProfileProtocol","text":"ChatUserProfileProtocol"},{"text":")","kind":"text"}]}],"kind":"declarations"},{"parameters":[{"name":"indexPath","content":[{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"type":"codeVoice","code":"IndexPath"}]}]},{"name":"profile","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Conform to "},{"type":"reference","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatUserProfileProtocol","isActive":true},{"type":"text","text":" object."}]}]}],"kind":"parameters"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/contactlistactioneventsdelegate\/didselected(indexpath:profile:)"]},{"paths":["\/documentation\/shengwangchatuikit\/contactlistactioneventsdelegate\/didselected(indexpath:profile:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"metadata":{"modules":[{"name":"ShengwangChatUIKit"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"didSelected","kind":"identifier"},{"kind":"text","text":"("},{"text":"indexPath","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":", "},{"text":"profile","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(pl)ChatUserProfileProtocol","text":"ChatUserProfileProtocol"},{"kind":"text","text":")"}],"required":true,"symbolKind":"method","roleHeading":"Instance Method","title":"didSelected(indexPath:profile:)","navigatorTitle":[{"kind":"identifier","text":"didSelectedWithIndexPath:profile:"}],"externalID":"c:@M@ShengwangChatUIKit@objc(pl)ContactListActionEventsDelegate(im)didSelectedWithIndexPath:profile:"},"kind":"symbol","references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ContactListActionEventsDelegate":{"title":"ContactListActionEventsDelegate","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactListActionEventsDelegate","type":"topic","url":"\/documentation\/shengwangchatuikit\/contactlistactioneventsdelegate","abstract":[{"type":"text","text":"ContactList action events delegate."}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ContactListActionEventsDelegate","kind":"identifier"}],"navigatorTitle":[{"text":"ContactListActionEventsDelegate","kind":"identifier"}],"kind":"symbol","role":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatUserProfileProtocol":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatUserProfileProtocol","abstract":[{"text":"Profile of the ChatUIKit display needed.","type":"text"}],"title":"ChatUserProfileProtocol","type":"topic","kind":"symbol","navigatorTitle":[{"text":"ChatUserProfileProtocol","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"ChatUserProfileProtocol","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/chatuserprofileprotocol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ContactListActionEventsDelegate/didSelected(indexPath:profile:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"didSelected"},{"text":"(","kind":"text"},{"text":"indexPath","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":", "},{"text":"profile","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ChatUserProfileProtocol","kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(pl)ChatUserProfileProtocol"},{"text":")","kind":"text"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"didSelectedWithIndexPath:profile:"}],"title":"didSelected(indexPath:profile:)","required":true,"url":"\/documentation\/shengwangchatuikit\/contactlistactioneventsdelegate\/didselected(indexpath:profile:)","abstract":[{"text":"The method’ll called on contact list cell clicked.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactListActionEventsDelegate\/didSelected(indexPath:profile:)","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"didSelectedWithIndexPath:profile:","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"didSelectedWithIndexPath:profile:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"text":"didSelectedWithIndexPath:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSIndexPath","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSIndexPath"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"indexPath"},{"text":" ","kind":"text"},{"text":"profile:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Qo@M@ShengwangChatUIKit@objc(pl)ChatUserProfileProtocol","text":"id<ChatUserProfileProtocol>","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"profile","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"op":"replace"},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"code":"IndexPath","type":"codeVoice"}]}],"name":"indexPath"},{"content":[{"type":"paragraph","inlineContent":[{"text":"Conform to ","type":"text"},{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatUserProfileProtocol","isActive":true,"type":"reference"},{"text":" object.","type":"text"}]}],"name":"profile"}]}},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactListActionEventsDelegate\/title","op":"replace","value":"ContactListActionEventsDelegate"},{"value":[{"kind":"identifier","text":"ContactListActionEventsDelegate"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactListActionEventsDelegate\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactListActionEventsDelegate\/navigatorTitle","value":[{"text":"ContactListActionEventsDelegate","kind":"identifier"}]},{"value":"ChatUserProfileProtocol","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatUserProfileProtocol\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatUserProfileProtocol\/fragments","value":[{"text":"ChatUserProfileProtocol","kind":"identifier"}]},{"value":[{"text":"ChatUserProfileProtocol","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatUserProfileProtocol\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactListActionEventsDelegate~1didSelected(indexPath:profile:)\/title","value":"didSelectedWithIndexPath:profile:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"didSelectedWithIndexPath:profile:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactListActionEventsDelegate~1didSelected(indexPath:profile:)\/fragments"}]}]}