{"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"modules":[{"name":"ShengwangChatUIKit"}],"symbolKind":"method","title":"onContactListOccurErrorWhenFetchServer()","role":"symbol","externalID":"c:@M@ShengwangChatUIKit@objc(pl)ContactListActionEventsDelegate(im)onContactListOccurErrorWhenFetchServer","required":true,"roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"onContactListOccurErrorWhenFetchServer","kind":"identifier"},{"kind":"text","text":"()"}],"navigatorTitle":[{"text":"onContactListOccurErrorWhenFetchServer","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactListActionEventsDelegate"]]},"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactListActionEventsDelegate\/onContactListOccurErrorWhenFetchServer()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"When fetch conversations list occur error.Empty view retry button on clicked.The method will call."}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onContactListOccurErrorWhenFetchServer"},{"text":"()","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/contactlistactioneventsdelegate\/oncontactlistoccurerrorwhenfetchserver()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/contactlistactioneventsdelegate\/oncontactlistoccurerrorwhenfetchserver()"]}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ContactListActionEventsDelegate":{"title":"ContactListActionEventsDelegate","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactListActionEventsDelegate","type":"topic","url":"\/documentation\/shengwangchatuikit\/contactlistactioneventsdelegate","abstract":[{"type":"text","text":"ContactList action events delegate."}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ContactListActionEventsDelegate","kind":"identifier"}],"navigatorTitle":[{"text":"ContactListActionEventsDelegate","kind":"identifier"}],"kind":"symbol","role":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ContactListActionEventsDelegate/onContactListOccurErrorWhenFetchServer()":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactListActionEventsDelegate\/onContactListOccurErrorWhenFetchServer()","navigatorTitle":[{"text":"onContactListOccurErrorWhenFetchServer","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/contactlistactioneventsdelegate\/oncontactlistoccurerrorwhenfetchserver()","type":"topic","abstract":[{"text":"When fetch conversations list occur error.Empty view retry button on clicked.The method will call.","type":"text"}],"required":true,"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onContactListOccurErrorWhenFetchServer"},{"text":"()","kind":"text"}],"title":"onContactListOccurErrorWhenFetchServer()","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"onContactListOccurErrorWhenFetchServer"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onContactListOccurErrorWhenFetchServer"}]},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"onContactListOccurErrorWhenFetchServer","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"value":"ContactListActionEventsDelegate","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactListActionEventsDelegate\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactListActionEventsDelegate\/fragments","value":[{"kind":"identifier","text":"ContactListActionEventsDelegate"}],"op":"replace"},{"value":[{"text":"ContactListActionEventsDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactListActionEventsDelegate\/navigatorTitle","op":"replace"},{"op":"replace","value":"onContactListOccurErrorWhenFetchServer","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactListActionEventsDelegate~1onContactListOccurErrorWhenFetchServer()\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactListActionEventsDelegate~1onContactListOccurErrorWhenFetchServer()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"onContactListOccurErrorWhenFetchServer","kind":"identifier"}],"op":"replace"}]}]}