{"abstract":[{"type":"text","text":"When contact list scrolled."}],"metadata":{"symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"onContactListScrollWithIndexPath:"}],"role":"symbol","modules":[{"name":"ShengwangChatUIKit"}],"roleHeading":"Instance Method","externalID":"c:@M@ShengwangChatUIKit@objc(pl)ContactListActionEventsDelegate(im)onContactListScrollWithIndexPath:","required":true,"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"onContactListScroll","kind":"identifier"},{"kind":"text","text":"("},{"text":"indexPath","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation9IndexPathV","kind":"typeIdentifier","text":"IndexPath"},{"kind":"text","text":")"}],"title":"onContactListScroll(indexPath:)"},"sections":[],"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactListActionEventsDelegate\/onContactListScroll(indexPath:)","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/shengwangchatuikit\/contactlistactioneventsdelegate\/oncontactlistscroll(indexpath:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/shengwangchatuikit\/contactlistactioneventsdelegate\/oncontactlistscroll(indexpath:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactListActionEventsDelegate"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onContactListScroll"},{"kind":"text","text":"("},{"kind":"externalParam","text":"indexPath"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"indexPath","content":[{"inlineContent":[{"type":"text","text":""},{"code":"IndexPath","type":"codeVoice"}],"type":"paragraph"}]}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ContactListActionEventsDelegate":{"title":"ContactListActionEventsDelegate","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactListActionEventsDelegate","type":"topic","url":"\/documentation\/shengwangchatuikit\/contactlistactioneventsdelegate","abstract":[{"type":"text","text":"ContactList action events delegate."}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ContactListActionEventsDelegate","kind":"identifier"}],"navigatorTitle":[{"text":"ContactListActionEventsDelegate","kind":"identifier"}],"kind":"symbol","role":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ContactListActionEventsDelegate/onContactListScroll(indexPath:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"onContactListScroll"},{"text":"(","kind":"text"},{"text":"indexPath","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation9IndexPathV","text":"IndexPath"},{"text":")","kind":"text"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"onContactListScrollWithIndexPath:"}],"title":"onContactListScroll(indexPath:)","required":true,"url":"\/documentation\/shengwangchatuikit\/contactlistactioneventsdelegate\/oncontactlistscroll(indexpath:)","abstract":[{"text":"When contact list scrolled.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactListActionEventsDelegate\/onContactListScroll(indexPath:)","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"onContactListScrollWithIndexPath:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"text":"onContactListScrollWithIndexPath:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"text":"onContactListScrollWithIndexPath:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSIndexPath","kind":"typeIdentifier","text":"NSIndexPath"},{"text":" *) ","kind":"text"},{"text":"indexPath","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":""},{"code":"IndexPath","type":"codeVoice"}],"type":"paragraph"}],"name":"indexPath"}]},"op":"replace","path":"\/primaryContentSections\/1"},{"value":"ContactListActionEventsDelegate","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactListActionEventsDelegate\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactListActionEventsDelegate\/fragments","value":[{"text":"ContactListActionEventsDelegate","kind":"identifier"}]},{"value":[{"text":"ContactListActionEventsDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactListActionEventsDelegate\/navigatorTitle"},{"value":"onContactListScrollWithIndexPath:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactListActionEventsDelegate~1onContactListScroll(indexPath:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactListActionEventsDelegate~1onContactListScroll(indexPath:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onContactListScrollWithIndexPath:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}