{"metadata":{"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"title"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"type"},{"text":": ","kind":"text"},{"text":"ActionSheetItemType","kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@E@ActionSheetItemType"},{"text":", ","kind":"text"},{"text":"tag","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"image","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"text":"?)","kind":"text"}],"externalID":"c:@M@ShengwangChatUIKit@objc(cs)ActionSheetItem(im)initWithTitle:type:tag:image:","role":"symbol","roleHeading":"Initializer","modules":[{"name":"ShengwangChatUIKit"}],"title":"init(title:type:tag:image:)","symbolKind":"init","navigatorTitle":[{"text":"initWithTitle:type:tag:image:","kind":"identifier"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"convenience","kind":"keyword"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"title"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"type"},{"kind":"text","text":": "},{"text":"ActionSheetItemType","kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@E@ActionSheetItemType","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ActionSheetItemType"},{"text":", ","kind":"text"},{"text":"tag","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"image","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"text":"? = nil)","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"content","content":[{"type":"heading","level":2,"text":"Discussion","anchor":"discussion"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"title: The title of the action sheet item."}]}]},{"content":[{"inlineContent":[{"text":"type: The type of the action sheet item.","type":"text"}],"type":"paragraph"}]}]}]}],"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ActionSheetItem\/init(title:type:tag:image:)","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ActionSheetItem"]]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/actionsheetitem\/init(title:type:tag:image:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/actionsheetitem\/init(title:type:tag:image:)"]}],"abstract":[{"type":"text","text":"A convenience initializer for creating an "},{"type":"codeVoice","code":"ActionSheetItem"},{"type":"text","text":" object with a title, type, and tag."}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ActionSheetItemType":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ActionSheetItemType","abstract":[{"type":"text","text":"An enumeration representing the type of an action sheet item."}],"title":"ActionSheetItemType","url":"\/documentation\/shengwangchatuikit\/actionsheetitemtype","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ActionSheetItemType"}],"navigatorTitle":[{"kind":"identifier","text":"ActionSheetItemType"}],"kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ActionSheetItem/init(title:type:tag:image:)":{"navigatorTitle":[{"text":"initWithTitle:type:tag:image:","kind":"identifier"}],"abstract":[{"text":"A convenience initializer for creating an ","type":"text"},{"code":"ActionSheetItem","type":"codeVoice"},{"type":"text","text":" object with a title, type, and tag."}],"type":"topic","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"title","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"type","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ActionSheetItemType","preciseIdentifier":"c:@M@ShengwangChatUIKit@E@ActionSheetItemType"},{"text":", ","kind":"text"},{"text":"tag","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"image"},{"text":": ","kind":"text"},{"text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"url":"\/documentation\/shengwangchatuikit\/actionsheetitem\/init(title:type:tag:image:)","role":"symbol","title":"init(title:type:tag:image:)","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ActionSheetItem\/init(title:type:tag:image:)","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ActionSheetItem":{"navigatorTitle":[{"kind":"identifier","text":"ActionSheetItem"}],"abstract":[],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ActionSheetItem"}],"url":"\/documentation\/shengwangchatuikit\/actionsheetitem","role":"symbol","title":"ActionSheetItem","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ActionSheetItem","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"initWithTitle:type:tag:image:","path":"\/metadata\/title","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithTitle:type:tag:image:"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:*Qo","kind":"typeIdentifier","text":"id"},{"text":") ","kind":"text"},{"text":"initWithTitle:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"title","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"type:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ActionSheetItemType","preciseIdentifier":"c:@M@ShengwangChatUIKit@E@ActionSheetItemType","kind":"typeIdentifier","text":"ActionSheetItemType"},{"kind":"text","text":") "},{"kind":"internalParam","text":"type"},{"text":" ","kind":"text"},{"kind":"identifier","text":"tag:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"tag","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"image:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"},{"text":" *) ","kind":"text"},{"text":"image","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"add","path":"\/primaryContentSections\/1","value":{"kind":"content","content":[{"level":2,"type":"heading","anchor":"return-value","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"An "},{"type":"codeVoice","code":"ActionSheetItem"},{"text":" object.","type":"text"}]}]}},{"op":"replace","value":"ActionSheetItemType","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ActionSheetItemType\/title"},{"op":"replace","value":[{"text":"ActionSheetItemType","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ActionSheetItemType\/fragments"},{"value":[{"kind":"identifier","text":"ActionSheetItemType"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ActionSheetItemType\/navigatorTitle"},{"value":"initWithTitle:type:tag:image:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ActionSheetItem~1init(title:type:tag:image:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithTitle:type:tag:image:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ActionSheetItem~1init(title:type:tag:image:)\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ActionSheetItem\/title","value":"ActionSheetItem","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ActionSheetItem\/fragments","value":[{"kind":"identifier","text":"ActionSheetItem"}],"op":"replace"},{"value":[{"kind":"identifier","text":"ActionSheetItem"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ActionSheetItem\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}