{"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"externalID":"c:@M@ShengwangChatUIKit@objc(cs)ActionSheetItem(im)init","navigatorTitle":[{"kind":"identifier","text":"init"}],"fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"init"}],"role":"symbol","modules":[{"name":"ShengwangChatUIKit"}],"symbolKind":"method","roleHeading":"Instance Method","title":"init"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","preciseIdentifier":"c:*Qo","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"init"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ActionSheetItem"]]},"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ActionSheetItem\/init","interfaceLanguage":"occ"},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/actionsheetitem\/init"]}],"sections":[],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ActionSheetItem/init":{"kind":"symbol","abstract":[],"title":"init","url":"\/documentation\/shengwangchatuikit\/actionsheetitem\/init","type":"topic","role":"symbol","fragments":[{"kind":"text","text":"- "},{"text":"init","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"init"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ActionSheetItem\/init"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ActionSheetItem":{"navigatorTitle":[{"kind":"identifier","text":"ActionSheetItem"}],"abstract":[],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ActionSheetItem"}],"url":"\/documentation\/shengwangchatuikit\/actionsheetitem","role":"symbol","title":"ActionSheetItem","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ActionSheetItem","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"ActionSheetItem","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ActionSheetItem\/title"},{"op":"replace","value":[{"kind":"identifier","text":"ActionSheetItem"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ActionSheetItem\/fragments"},{"op":"replace","value":[{"text":"ActionSheetItem","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ActionSheetItem\/navigatorTitle"}]}]}