{"metadata":{"modules":[{"name":"ShengwangChatUIKit"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"mention","kind":"identifier"}],"role":"symbol","title":"MessageInputBarActionType.mention","symbolKind":"case","roleHeading":"Case","navigatorTitle":[{"text":"MessageInputBarActionTypeMention","kind":"identifier"}],"externalID":"c:@M@ShengwangChatUIKit@E@MessageInputBarActionType@MessageInputBarActionTypeMention"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageInputBarActionType\/mention"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/messageinputbaractiontype\/mention"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/messageinputbaractiontype\/mention"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mention","kind":"identifier"}],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageInputBarActionType"]]},"kind":"symbol","references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageInputBarActionType":{"navigatorTitle":[{"kind":"identifier","text":"MessageInputBarActionType"}],"abstract":[{"text":"The types of actions that can be triggered by the input bar.","type":"text"}],"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"MessageInputBarActionType","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/messageinputbaractiontype","role":"symbol","title":"MessageInputBarActionType","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageInputBarActionType"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageInputBarActionType/mention":{"navigatorTitle":[{"kind":"identifier","text":"MessageInputBarActionTypeMention"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"mention","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/messageinputbaractiontype\/mention","abstract":[],"role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageInputBarActionType\/mention","title":"MessageInputBarActionType.mention","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"MessageInputBarActionTypeMention"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","value":[{"text":"MessageInputBarActionTypeMention","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"tokens":[{"text":"MessageInputBarActionTypeMention","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"MessageInputBarActionType","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageInputBarActionType\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageInputBarActionType\/fragments","op":"replace","value":[{"kind":"identifier","text":"MessageInputBarActionType"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageInputBarActionType\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MessageInputBarActionType"}]},{"value":"MessageInputBarActionTypeMention","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageInputBarActionType~1mention\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageInputBarActionType~1mention\/fragments","value":[{"kind":"identifier","text":"MessageInputBarActionTypeMention"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}