{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChoiceItemLayout\/finalLayoutAttributesForDisappearingItem(at:)"},"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"finalLayoutAttributesForDisappearingItem","kind":"identifier"},{"kind":"text","text":"("},{"text":"at","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"itemIndexPath"},{"kind":"text","text":": "},{"text":"IndexPath","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation9IndexPathV"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UICollectionViewLayoutAttributes","text":"UICollectionViewLayoutAttributes","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"languages":["swift"]}]}],"metadata":{"modules":[{"name":"ShengwangChatUIKit"}],"symbolKind":"method","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"finalLayoutAttributesForDisappearingItem"},{"kind":"text","text":"("},{"text":"at","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation9IndexPathV","text":"IndexPath"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UICollectionViewLayoutAttributes","text":"UICollectionViewLayoutAttributes","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"externalID":"c:@M@ShengwangChatUIKit@objc(cs)ChoiceItemLayout(im)finalLayoutAttributesForDisappearingItemAtIndexPath:","title":"finalLayoutAttributesForDisappearingItem(at:)","navigatorTitle":[{"text":"finalLayoutAttributesForDisappearingItemAtIndexPath:","kind":"identifier"}],"role":"symbol"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChoiceItemLayout"]]},"sections":[],"variants":[{"paths":["\/documentation\/shengwangchatuikit\/choiceitemlayout\/finallayoutattributesfordisappearingitem(at:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/choiceitemlayout\/finallayoutattributesfordisappearingitem(at:)"]}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChoiceItemLayout":{"url":"\/documentation\/shengwangchatuikit\/choiceitemlayout","navigatorTitle":[{"kind":"identifier","text":"ChoiceItemLayout"}],"title":"ChoiceItemLayout","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChoiceItemLayout","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChoiceItemLayout"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Choice layout"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChoiceItemLayout/finalLayoutAttributesForDisappearingItem(at:)":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChoiceItemLayout\/finalLayoutAttributesForDisappearingItem(at:)","url":"\/documentation\/shengwangchatuikit\/choiceitemlayout\/finallayoutattributesfordisappearingitem(at:)","role":"symbol","title":"finalLayoutAttributesForDisappearingItem(at:)","abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"finalLayoutAttributesForDisappearingItem"},{"kind":"text","text":"("},{"text":"at","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation9IndexPathV","text":"IndexPath"},{"kind":"text","text":") -> "},{"text":"UICollectionViewLayoutAttributes","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UICollectionViewLayoutAttributes"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"finalLayoutAttributesForDisappearingItemAtIndexPath:","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"finalLayoutAttributesForDisappearingItemAtIndexPath:","op":"replace","path":"\/metadata\/title"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"finalLayoutAttributesForDisappearingItemAtIndexPath:"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"UICollectionViewLayoutAttributes","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UICollectionViewLayoutAttributes"},{"kind":"text","text":" *) "},{"text":"finalLayoutAttributesForDisappearingItemAtIndexPath:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSIndexPath","text":"NSIndexPath","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"itemIndexPath","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"value":"ChoiceItemLayout","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChoiceItemLayout\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChoiceItemLayout\/fragments","value":[{"text":"ChoiceItemLayout","kind":"identifier"}],"op":"replace"},{"value":[{"text":"ChoiceItemLayout","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChoiceItemLayout\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChoiceItemLayout~1finalLayoutAttributesForDisappearingItem(at:)\/title","op":"replace","value":"finalLayoutAttributesForDisappearingItemAtIndexPath:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"finalLayoutAttributesForDisappearingItemAtIndexPath:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChoiceItemLayout~1finalLayoutAttributesForDisappearingItem(at:)\/fragments"}]}]}