{"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"init","kind":"identifier"},{"kind":"text","text":";"}]}],"kind":"declarations"}],"metadata":{"fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"init"}],"title":"init","modules":[{"name":"ShengwangChatUIKit"}],"role":"symbol","symbolKind":"method","externalID":"c:@M@ShengwangChatUIKit@objc(cs)ChoiceItemLayout(im)init","roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"init"}]},"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChoiceItemLayout\/init","interfaceLanguage":"occ"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChoiceItemLayout"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","variants":[{"paths":["\/documentation\/shengwangchatuikit\/choiceitemlayout\/init"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChoiceItemLayout/init":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChoiceItemLayout\/init","url":"\/documentation\/shengwangchatuikit\/choiceitemlayout\/init","role":"symbol","title":"init","abstract":[],"kind":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"navigatorTitle":[{"kind":"identifier","text":"init"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChoiceItemLayout":{"url":"\/documentation\/shengwangchatuikit\/choiceitemlayout","navigatorTitle":[{"kind":"identifier","text":"ChoiceItemLayout"}],"title":"ChoiceItemLayout","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChoiceItemLayout","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChoiceItemLayout"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Choice layout"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChoiceItemLayout\/title","op":"replace","value":"ChoiceItemLayout"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChoiceItemLayout\/fragments","op":"replace","value":[{"text":"ChoiceItemLayout","kind":"identifier"}]},{"value":[{"text":"ChoiceItemLayout","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChoiceItemLayout\/navigatorTitle","op":"replace"}]}]}