{"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialLayoutAttributesForAppearingItem"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"at"},{"kind":"text","text":" "},{"text":"itemIndexPath","kind":"internalParam"},{"kind":"text","text":": "},{"text":"IndexPath","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:objc(cs)UICollectionViewLayoutAttributes","kind":"typeIdentifier","text":"UICollectionViewLayoutAttributes"},{"text":"?","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/choiceitemlayout\/initiallayoutattributesforappearingitem(at:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/choiceitemlayout\/initiallayoutattributesforappearingitem(at:)"]}],"metadata":{"modules":[{"name":"ShengwangChatUIKit"}],"roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"initialLayoutAttributesForAppearingItem"},{"kind":"text","text":"("},{"kind":"externalParam","text":"at"},{"text":": ","kind":"text"},{"text":"IndexPath","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UICollectionViewLayoutAttributes","preciseIdentifier":"c:objc(cs)UICollectionViewLayoutAttributes"},{"text":"?","kind":"text"}],"title":"initialLayoutAttributesForAppearingItem(at:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initialLayoutAttributesForAppearingItemAtIndexPath:"}],"externalID":"c:@M@ShengwangChatUIKit@objc(cs)ChoiceItemLayout(im)initialLayoutAttributesForAppearingItemAtIndexPath:","symbolKind":"method"},"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChoiceItemLayout"]]},"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChoiceItemLayout\/initialLayoutAttributesForAppearingItem(at:)","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChoiceItemLayout/initialLayoutAttributesForAppearingItem(at:)":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChoiceItemLayout\/initialLayoutAttributesForAppearingItem(at:)","url":"\/documentation\/shengwangchatuikit\/choiceitemlayout\/initiallayoutattributesforappearingitem(at:)","role":"symbol","title":"initialLayoutAttributesForAppearingItem(at:)","abstract":[],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"initialLayoutAttributesForAppearingItem","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"at"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation9IndexPathV","text":"IndexPath","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UICollectionViewLayoutAttributes","text":"UICollectionViewLayoutAttributes"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"initialLayoutAttributesForAppearingItemAtIndexPath:"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChoiceItemLayout":{"url":"\/documentation\/shengwangchatuikit\/choiceitemlayout","navigatorTitle":[{"kind":"identifier","text":"ChoiceItemLayout"}],"title":"ChoiceItemLayout","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChoiceItemLayout","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChoiceItemLayout"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Choice layout"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"initialLayoutAttributesForAppearingItemAtIndexPath:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initialLayoutAttributesForAppearingItemAtIndexPath:","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UICollectionViewLayoutAttributes","text":"UICollectionViewLayoutAttributes"},{"kind":"text","text":" *) "},{"text":"initialLayoutAttributesForAppearingItemAtIndexPath:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSIndexPath","text":"NSIndexPath","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"itemIndexPath"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"value":"initialLayoutAttributesForAppearingItemAtIndexPath:","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChoiceItemLayout~1initialLayoutAttributesForAppearingItem(at:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChoiceItemLayout~1initialLayoutAttributesForAppearingItem(at:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initialLayoutAttributesForAppearingItemAtIndexPath:"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChoiceItemLayout\/title","value":"ChoiceItemLayout"},{"value":[{"text":"ChoiceItemLayout","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChoiceItemLayout\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChoiceItemLayout\/navigatorTitle","value":[{"kind":"identifier","text":"ChoiceItemLayout"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}