{"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChoiceItemLayout\/layoutAttributesForItem(at:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChoiceItemLayout"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"roleHeading":"Instance Method","title":"layoutAttributesForItem(at:)","navigatorTitle":[{"kind":"identifier","text":"layoutAttributesForItemAtIndexPath:"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"layoutAttributesForItem","kind":"identifier"},{"text":"(","kind":"text"},{"text":"at","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation9IndexPathV","kind":"typeIdentifier","text":"IndexPath"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UICollectionViewLayoutAttributes","text":"UICollectionViewLayoutAttributes"},{"kind":"text","text":"?"}],"externalID":"c:@M@ShengwangChatUIKit@objc(cs)ChoiceItemLayout(im)layoutAttributesForItemAtIndexPath:","modules":[{"name":"ShengwangChatUIKit"}],"symbolKind":"method"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"text":" ","kind":"text"},{"text":"override","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"layoutAttributesForItem","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"at"},{"text":" ","kind":"text"},{"text":"indexPath","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"UICollectionViewLayoutAttributes","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UICollectionViewLayoutAttributes"},{"text":"?","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/choiceitemlayout\/layoutattributesforitem(at:)"]},{"paths":["\/documentation\/shengwangchatuikit\/choiceitemlayout\/layoutattributesforitem(at:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChoiceItemLayout":{"url":"\/documentation\/shengwangchatuikit\/choiceitemlayout","navigatorTitle":[{"kind":"identifier","text":"ChoiceItemLayout"}],"title":"ChoiceItemLayout","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChoiceItemLayout","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChoiceItemLayout"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Choice layout"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChoiceItemLayout/layoutAttributesForItem(at:)":{"abstract":[],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChoiceItemLayout\/layoutAttributesForItem(at:)","navigatorTitle":[{"text":"layoutAttributesForItemAtIndexPath:","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/shengwangchatuikit\/choiceitemlayout\/layoutattributesforitem(at:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"layoutAttributesForItem"},{"kind":"text","text":"("},{"kind":"externalParam","text":"at"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation9IndexPathV","kind":"typeIdentifier","text":"IndexPath"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UICollectionViewLayoutAttributes","text":"UICollectionViewLayoutAttributes"},{"kind":"text","text":"?"}],"title":"layoutAttributesForItem(at:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"layoutAttributesForItemAtIndexPath:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"layoutAttributesForItemAtIndexPath:","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UICollectionViewLayoutAttributes","text":"UICollectionViewLayoutAttributes"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"layoutAttributesForItemAtIndexPath:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSIndexPath","text":"NSIndexPath"},{"text":" *) ","kind":"text"},{"text":"indexPath","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}},{"op":"replace","value":"ChoiceItemLayout","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChoiceItemLayout\/title"},{"value":[{"kind":"identifier","text":"ChoiceItemLayout"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChoiceItemLayout\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChoiceItemLayout\/navigatorTitle","value":[{"kind":"identifier","text":"ChoiceItemLayout"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChoiceItemLayout~1layoutAttributesForItem(at:)\/title","value":"layoutAttributesForItemAtIndexPath:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"layoutAttributesForItemAtIndexPath:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChoiceItemLayout~1layoutAttributesForItem(at:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}