{"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChoiceItemLayout\/prepare(forCollectionViewUpdates:)","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"roleHeading":"Instance Method","title":"prepare(forCollectionViewUpdates:)","navigatorTitle":[{"kind":"identifier","text":"prepareForCollectionViewUpdates:"}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"prepare","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"forCollectionViewUpdates"},{"text":": [","kind":"text"},{"text":"UICollectionViewUpdateItem","preciseIdentifier":"c:objc(cs)UICollectionViewUpdateItem","kind":"typeIdentifier"},{"kind":"text","text":"])"}],"externalID":"c:@M@ShengwangChatUIKit@objc(cs)ChoiceItemLayout(im)prepareForCollectionViewUpdates:","modules":[{"name":"ShengwangChatUIKit"}],"symbolKind":"method"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChoiceItemLayout"]]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/choiceitemlayout\/prepare(forcollectionviewupdates:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/choiceitemlayout\/prepare(forcollectionviewupdates:)"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"override"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"prepare"},{"text":"(","kind":"text"},{"text":"forCollectionViewUpdates","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"updateItems","kind":"internalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"UICollectionViewUpdateItem","preciseIdentifier":"c:objc(cs)UICollectionViewUpdateItem"},{"kind":"text","text":"])"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChoiceItemLayout":{"url":"\/documentation\/shengwangchatuikit\/choiceitemlayout","navigatorTitle":[{"kind":"identifier","text":"ChoiceItemLayout"}],"title":"ChoiceItemLayout","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChoiceItemLayout","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChoiceItemLayout"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Choice layout"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChoiceItemLayout/prepare(forCollectionViewUpdates:)":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChoiceItemLayout\/prepare(forCollectionViewUpdates:)","abstract":[],"url":"\/documentation\/shengwangchatuikit\/choiceitemlayout\/prepare(forcollectionviewupdates:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"prepare"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"forCollectionViewUpdates"},{"text":": [","kind":"text"},{"text":"UICollectionViewUpdateItem","preciseIdentifier":"c:objc(cs)UICollectionViewUpdateItem","kind":"typeIdentifier"},{"text":"])","kind":"text"}],"role":"symbol","title":"prepare(forCollectionViewUpdates:)","navigatorTitle":[{"text":"prepareForCollectionViewUpdates:","kind":"identifier"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"prepareForCollectionViewUpdates:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"prepareForCollectionViewUpdates:"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"prepareForCollectionViewUpdates:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<UICollectionViewUpdateItem *>","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"updateItems","kind":"internalParam"},{"kind":"text","text":";"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":"ChoiceItemLayout","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChoiceItemLayout\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChoiceItemLayout\/fragments","value":[{"text":"ChoiceItemLayout","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"ChoiceItemLayout"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChoiceItemLayout\/navigatorTitle"},{"value":"prepareForCollectionViewUpdates:","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChoiceItemLayout~1prepare(forCollectionViewUpdates:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChoiceItemLayout~1prepare(forCollectionViewUpdates:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"prepareForCollectionViewUpdates:","kind":"identifier"}]}]}]}