{"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/chatemojiconvertor\/convertemoji(input:ranges:symbol:imagebounds:)"]},{"paths":["\/documentation\/shengwangchatuikit\/chatemojiconvertor\/convertemoji(input:ranges:symbol:imagebounds:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatEmojiConvertor\/convertEmoji(input:ranges:symbol:imageBounds:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatEmojiConvertor"]]},"kind":"symbol","metadata":{"roleHeading":"Instance Method","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"convertEmoji"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"input"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSMutableAttributedString","text":"NSMutableAttributedString"},{"kind":"text","text":", "},{"text":"ranges","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"NSRange","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSRange"},{"text":"], ","kind":"text"},{"text":"symbol","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"text":"imageBounds","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":") -> "},{"text":"NSMutableAttributedString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSMutableAttributedString"}],"modules":[{"name":"ShengwangChatUIKit"}],"navigatorTitle":[{"text":"convertEmojiWithInput:ranges:symbol:imageBounds:","kind":"identifier"}],"externalID":"c:@M@ShengwangChatUIKit@objc(cs)ChatEmojiConvertor(im)convertEmojiWithInput:ranges:symbol:imageBounds:","title":"convertEmoji(input:ranges:symbol:imageBounds:)","symbolKind":"method"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"convertEmoji","kind":"identifier"},{"text":"(","kind":"text"},{"text":"input","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSMutableAttributedString","text":"NSMutableAttributedString","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"ranges","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSRange","text":"NSRange"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"symbol"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"imageBounds"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CGRect","text":"CGRect","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"NSMutableAttributedString","preciseIdentifier":"c:objc(cs)NSMutableAttributedString"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The input attributed string to convert."}],"type":"paragraph"}],"name":"input"},{"name":"ranges","content":[{"inlineContent":[{"text":"The ranges of the input attributed string to convert to emoji images.","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"The symbol to use for the emoji images.","type":"text"}]}],"name":"symbol"}],"kind":"parameters"},{"kind":"content","content":[{"type":"heading","text":"Return Value","anchor":"return-value","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"A new attributed string with the specified ranges replaced with emoji images."}]}]}],"abstract":[{"type":"text","text":"Converts the specified ranges of the input attributed string to emoji images using the provided symbol and returns the resulting attributed string."}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatEmojiConvertor/convertEmoji(input:ranges:symbol:imageBounds:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"convertEmoji","kind":"identifier"},{"kind":"text","text":"("},{"text":"input","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSMutableAttributedString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSMutableAttributedString"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"ranges"},{"kind":"text","text":": ["},{"text":"NSRange","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSRange"},{"kind":"text","text":"], "},{"text":"symbol","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"imageBounds","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGRect","text":"CGRect","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSMutableAttributedString","kind":"typeIdentifier","text":"NSMutableAttributedString"}],"type":"topic","role":"symbol","abstract":[{"type":"text","text":"Converts the specified ranges of the input attributed string to emoji images using the provided symbol and returns the resulting attributed string."}],"kind":"symbol","navigatorTitle":[{"text":"convertEmojiWithInput:ranges:symbol:imageBounds:","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatEmojiConvertor\/convertEmoji(input:ranges:symbol:imageBounds:)","url":"\/documentation\/shengwangchatuikit\/chatemojiconvertor\/convertemoji(input:ranges:symbol:imagebounds:)","title":"convertEmoji(input:ranges:symbol:imageBounds:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatEmojiConvertor":{"navigatorTitle":[{"text":"ChatEmojiConvertor","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/chatemojiconvertor","abstract":[{"type":"text","text":"A class that converts emojis in a given NSMutableAttributedString to their corresponding UIImage."}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatEmojiConvertor","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ChatEmojiConvertor","kind":"identifier"}],"title":"ChatEmojiConvertor"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"convertEmojiWithInput:ranges:symbol:imageBounds:","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"text":"- ","kind":"text"},{"text":"convertEmojiWithInput:ranges:symbol:imageBounds:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"NSMutableAttributedString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSMutableAttributedString"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"convertEmojiWithInput:"},{"text":"(","kind":"text"},{"text":"NSMutableAttributedString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSMutableAttributedString"},{"text":" *) ","kind":"text"},{"text":"input","kind":"internalParam"},{"kind":"text","text":" "},{"text":"ranges:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSArray<NSValue *>","preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"ranges"},{"kind":"text","text":" "},{"kind":"identifier","text":"symbol:"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"symbol","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageBounds:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@S@CGRect","kind":"typeIdentifier","text":"CGRect"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"imageBounds"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/primaryContentSections\/1","op":"replace","value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The input attributed string to convert.","type":"text"}]}],"name":"input"},{"content":[{"inlineContent":[{"type":"text","text":"The ranges of the input attributed string to convert to emoji images."}],"type":"paragraph"}],"name":"ranges"},{"name":"symbol","content":[{"type":"paragraph","inlineContent":[{"text":"The symbol to use for the emoji images.","type":"text"}]}]}]}},{"path":"\/primaryContentSections\/2","value":{"content":[{"type":"heading","anchor":"return-value","text":"Return Value","level":2},{"inlineContent":[{"type":"text","text":"A new attributed string with the specified ranges replaced with emoji images."}],"type":"paragraph"}],"kind":"content"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatEmojiConvertor~1convertEmoji(input:ranges:symbol:imageBounds:)\/title","value":"convertEmojiWithInput:ranges:symbol:imageBounds:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatEmojiConvertor~1convertEmoji(input:ranges:symbol:imageBounds:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"convertEmojiWithInput:ranges:symbol:imageBounds:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatEmojiConvertor\/title","value":"ChatEmojiConvertor"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatEmojiConvertor\/fragments","value":[{"kind":"identifier","text":"ChatEmojiConvertor"}],"op":"replace"},{"op":"replace","value":[{"text":"ChatEmojiConvertor","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatEmojiConvertor\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}