{"sections":[],"abstract":[{"type":"text","text":"The method will call on input box event occur."}],"metadata":{"externalID":"c:@M@ShengwangChatUIKit@objc(pl)MessageListViewActionEventsDelegate(im)onInputBoxEventsOccurWithAction:attributeText:","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"onInputBoxEventsOccur"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"action"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@E@MessageInputBarActionType","kind":"typeIdentifier","text":"MessageInputBarActionType"},{"kind":"text","text":", "},{"text":"attributeText","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSAttributedString","preciseIdentifier":"c:objc(cs)NSAttributedString","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"modules":[{"name":"ShengwangChatUIKit"}],"required":true,"roleHeading":"Instance Method","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"onInputBoxEventsOccurWithAction:attributeText:"}],"title":"onInputBoxEventsOccur(action:attributeText:)","role":"symbol"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/messagelistviewactioneventsdelegate\/oninputboxeventsoccur(action:attributetext:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/messagelistviewactioneventsdelegate\/oninputboxeventsoccur(action:attributetext:)"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewActionEventsDelegate"]]},"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewActionEventsDelegate\/onInputBoxEventsOccur(action:attributeText:)","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onInputBoxEventsOccur"},{"text":"(","kind":"text"},{"text":"action","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"type","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageInputBarActionType","preciseIdentifier":"c:@M@ShengwangChatUIKit@E@MessageInputBarActionType","text":"MessageInputBarActionType","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"attributeText"},{"text":": ","kind":"text"},{"text":"NSAttributedString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSAttributedString"},{"kind":"text","text":"?)"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":""},{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageInputBarActionType","isActive":true,"type":"reference"}],"type":"paragraph"}],"name":"type"}],"kind":"parameters"}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageListViewActionEventsDelegate":{"navigatorTitle":[{"text":"MessageListViewActionEventsDelegate","kind":"identifier"}],"title":"MessageListViewActionEventsDelegate","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewActionEventsDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"MessageListViewActionEventsDelegate","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/messagelistviewactioneventsdelegate","abstract":[],"kind":"symbol","type":"topic"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageInputBarActionType":{"navigatorTitle":[{"kind":"identifier","text":"MessageInputBarActionType"}],"abstract":[{"text":"The types of actions that can be triggered by the input bar.","type":"text"}],"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"MessageInputBarActionType","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/messageinputbaractiontype","role":"symbol","title":"MessageInputBarActionType","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageInputBarActionType"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageListViewActionEventsDelegate/onInputBoxEventsOccur(action:attributeText:)":{"navigatorTitle":[{"kind":"identifier","text":"onInputBoxEventsOccurWithAction:attributeText:"}],"url":"\/documentation\/shengwangchatuikit\/messagelistviewactioneventsdelegate\/oninputboxeventsoccur(action:attributetext:)","type":"topic","required":true,"role":"symbol","title":"onInputBoxEventsOccur(action:attributeText:)","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewActionEventsDelegate\/onInputBoxEventsOccur(action:attributeText:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onInputBoxEventsOccur"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"action"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MessageInputBarActionType","preciseIdentifier":"c:@M@ShengwangChatUIKit@E@MessageInputBarActionType"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"attributeText"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSAttributedString","text":"NSAttributedString","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"kind":"symbol","abstract":[{"type":"text","text":"The method will call on input box event occur."}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"onInputBoxEventsOccurWithAction:attributeText:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"onInputBoxEventsOccurWithAction:attributeText:"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"onInputBoxEventsOccurWithAction:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageInputBarActionType","preciseIdentifier":"c:@M@ShengwangChatUIKit@E@MessageInputBarActionType","text":"MessageInputBarActionType","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"type"},{"kind":"text","text":" "},{"text":"attributeText:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSAttributedString","text":"NSAttributedString"},{"kind":"text","text":" *) "},{"text":"attributeText","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/primaryContentSections\/1","value":{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"reference","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageInputBarActionType","isActive":true}]}],"name":"type"}],"kind":"parameters"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewActionEventsDelegate\/title","value":"MessageListViewActionEventsDelegate"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewActionEventsDelegate\/fragments","value":[{"text":"MessageListViewActionEventsDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewActionEventsDelegate\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MessageListViewActionEventsDelegate"}]},{"value":"MessageInputBarActionType","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageInputBarActionType\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageInputBarActionType\/fragments","value":[{"kind":"identifier","text":"MessageInputBarActionType"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageInputBarActionType\/navigatorTitle","value":[{"kind":"identifier","text":"MessageInputBarActionType"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewActionEventsDelegate~1onInputBoxEventsOccur(action:attributeText:)\/title","value":"onInputBoxEventsOccurWithAction:attributeText:"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewActionEventsDelegate~1onInputBoxEventsOccur(action:attributeText:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onInputBoxEventsOccurWithAction:attributeText:"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}