{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewActionEventsDelegate"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/messagelistviewactioneventsdelegate\/onmessagereactionclicked(reaction:entity:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/messagelistviewactioneventsdelegate\/onmessagereactionclicked(reaction:entity:)"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"Message reaction&"},{"type":"codeVoice","code":"..."},{"type":"text","text":" clicked."}],"metadata":{"modules":[{"name":"ShengwangChatUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"onMessageReactionClickedWithReaction:entity:"}],"roleHeading":"Instance Method","role":"symbol","required":true,"symbolKind":"method","externalID":"c:@M@ShengwangChatUIKit@objc(pl)MessageListViewActionEventsDelegate(im)onMessageReactionClickedWithReaction:entity:","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onMessageReactionClicked","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"reaction"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:18ShengwangChatUIKit15MessageReactiona","text":"MessageReaction","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"entity","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)MessageEntity","text":"MessageEntity"},{"text":")","kind":"text"}],"title":"onMessageReactionClicked(reaction:entity:)"},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewActionEventsDelegate\/onMessageReactionClicked(reaction:entity:)"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onMessageReactionClicked","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"reaction"},{"kind":"text","text":": "},{"preciseIdentifier":"s:18ShengwangChatUIKit15MessageReactiona","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageReaction","text":"MessageReaction"},{"kind":"text","text":"?, "},{"text":"entity","kind":"externalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageEntity","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)MessageEntity","kind":"typeIdentifier","text":"MessageEntity"},{"text":")","kind":"text"}]}],"kind":"declarations"},{"parameters":[{"name":"reaction","content":[{"inlineContent":[{"type":"text","text":""},{"type":"reference","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageReaction","isActive":true},{"type":"text","text":" object,if nil is "},{"type":"codeVoice","code":"..."},{"text":" clicked.","type":"text"}],"type":"paragraph"}]},{"name":"entity","content":[{"inlineContent":[{"type":"text","text":""},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageEntity"}],"type":"paragraph"}]}],"kind":"parameters"}],"sections":[],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageListViewActionEventsDelegate/onMessageReactionClicked(reaction:entity:)":{"kind":"symbol","role":"symbol","required":true,"navigatorTitle":[{"kind":"identifier","text":"onMessageReactionClickedWithReaction:entity:"}],"title":"onMessageReactionClicked(reaction:entity:)","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewActionEventsDelegate\/onMessageReactionClicked(reaction:entity:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"onMessageReactionClicked","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"reaction"},{"kind":"text","text":": "},{"text":"MessageReaction","preciseIdentifier":"s:18ShengwangChatUIKit15MessageReactiona","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"entity","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)MessageEntity","text":"MessageEntity","kind":"typeIdentifier"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Message reaction&"},{"code":"...","type":"codeVoice"},{"type":"text","text":" clicked."}],"type":"topic","url":"\/documentation\/shengwangchatuikit\/messagelistviewactioneventsdelegate\/onmessagereactionclicked(reaction:entity:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageListViewActionEventsDelegate":{"navigatorTitle":[{"text":"MessageListViewActionEventsDelegate","kind":"identifier"}],"title":"MessageListViewActionEventsDelegate","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewActionEventsDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"MessageListViewActionEventsDelegate","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/messagelistviewactioneventsdelegate","abstract":[],"kind":"symbol","type":"topic"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageEntity":{"navigatorTitle":[{"text":"MessageEntity","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageEntity","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessageEntity","kind":"identifier"}],"title":"MessageEntity","abstract":[],"url":"\/documentation\/shengwangchatuikit\/messageentity"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageReaction":{"type":"topic","title":"MessageReaction","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageReaction","kind":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessageReaction","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MessageReaction"}],"url":"\/documentation\/shengwangchatuikit\/messagereaction","role":"symbol","abstract":[]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","value":"onMessageReactionClickedWithReaction:entity:","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"onMessageReactionClickedWithReaction:entity:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"text":"onMessageReactionClickedWithReaction:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraChatMessageReaction","preciseIdentifier":"c:objc(cs)AgoraChatMessageReaction"},{"kind":"text","text":" *) "},{"text":"reaction","kind":"internalParam"},{"kind":"text","text":" "},{"text":"entity:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageEntity","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)MessageEntity","text":"MessageEntity"},{"text":" *) ","kind":"text"},{"text":"entity","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"kind":"parameters","parameters":[{"name":"reaction","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageReaction"},{"text":" object,if nil is ","type":"text"},{"code":"...","type":"codeVoice"},{"type":"text","text":" clicked."}]}]},{"name":"entity","content":[{"inlineContent":[{"type":"text","text":""},{"isActive":true,"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageEntity","type":"reference"}],"type":"paragraph"}]}]},"op":"replace","path":"\/primaryContentSections\/1"},{"value":"onMessageReactionClickedWithReaction:entity:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewActionEventsDelegate~1onMessageReactionClicked(reaction:entity:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewActionEventsDelegate~1onMessageReactionClicked(reaction:entity:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"onMessageReactionClickedWithReaction:entity:","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewActionEventsDelegate\/title","value":"MessageListViewActionEventsDelegate"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewActionEventsDelegate\/fragments","value":[{"kind":"identifier","text":"MessageListViewActionEventsDelegate"}]},{"value":[{"text":"MessageListViewActionEventsDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewActionEventsDelegate\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageEntity\/title","op":"replace","value":"MessageEntity"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageEntity\/fragments","value":[{"kind":"identifier","text":"MessageEntity"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageEntity\/navigatorTitle","value":[{"text":"MessageEntity","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}