{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/messagelistviewactioneventsdelegate\/onmessagelistpullrefresh()"]},{"paths":["\/documentation\/shengwangchatuikit\/messagelistviewactioneventsdelegate\/onmessagelistpullrefresh()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewActionEventsDelegate\/onMessageListPullRefresh()","interfaceLanguage":"swift"},"metadata":{"required":true,"navigatorTitle":[{"kind":"identifier","text":"onMessageListPullRefresh"}],"modules":[{"name":"ShengwangChatUIKit"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onMessageListPullRefresh","kind":"identifier"},{"kind":"text","text":"()"}],"externalID":"c:@M@ShengwangChatUIKit@objc(pl)MessageListViewActionEventsDelegate(im)onMessageListPullRefresh","role":"symbol","symbolKind":"method","roleHeading":"Instance Method","title":"onMessageListPullRefresh()"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewActionEventsDelegate"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onMessageListPullRefresh","kind":"identifier"},{"text":"()","kind":"text"}]}]}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"text":"The method will call on message list pull to refreshing.","type":"text"}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageListViewActionEventsDelegate/onMessageListPullRefresh()":{"url":"\/documentation\/shengwangchatuikit\/messagelistviewactioneventsdelegate\/onmessagelistpullrefresh()","type":"topic","abstract":[{"type":"text","text":"The method will call on message list pull to refreshing."}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"onMessageListPullRefresh","kind":"identifier"},{"text":"()","kind":"text"}],"title":"onMessageListPullRefresh()","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewActionEventsDelegate\/onMessageListPullRefresh()","required":true,"navigatorTitle":[{"kind":"identifier","text":"onMessageListPullRefresh"}],"role":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageListViewActionEventsDelegate":{"navigatorTitle":[{"text":"MessageListViewActionEventsDelegate","kind":"identifier"}],"title":"MessageListViewActionEventsDelegate","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewActionEventsDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"MessageListViewActionEventsDelegate","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/messagelistviewactioneventsdelegate","abstract":[],"kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"onMessageListPullRefresh"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"onMessageListPullRefresh","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"text":"onMessageListPullRefresh","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewActionEventsDelegate~1onMessageListPullRefresh()\/title","value":"onMessageListPullRefresh","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewActionEventsDelegate~1onMessageListPullRefresh()\/fragments","value":[{"kind":"text","text":"- "},{"text":"onMessageListPullRefresh","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewActionEventsDelegate\/title","value":"MessageListViewActionEventsDelegate"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewActionEventsDelegate\/fragments","value":[{"text":"MessageListViewActionEventsDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewActionEventsDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"MessageListViewActionEventsDelegate"}]}]}]}