{"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"onMoreMessagesClicked","kind":"identifier"},{"text":"()","kind":"text"}],"roleHeading":"Instance Method","modules":[{"name":"ShengwangChatUIKit"}],"symbolKind":"method","role":"symbol","externalID":"c:@M@ShengwangChatUIKit@objc(pl)MessageListViewActionEventsDelegate(im)onMoreMessagesClicked","title":"onMoreMessagesClicked()","required":true,"navigatorTitle":[{"text":"onMoreMessagesClicked","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewActionEventsDelegate"]]},"sections":[],"abstract":[{"text":"More messages button clicked.","type":"text"}],"variants":[{"paths":["\/documentation\/shengwangchatuikit\/messagelistviewactioneventsdelegate\/onmoremessagesclicked()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/messagelistviewactioneventsdelegate\/onmoremessagesclicked()"]}],"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewActionEventsDelegate\/onMoreMessagesClicked()","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"onMoreMessagesClicked","kind":"identifier"},{"kind":"text","text":"()"}],"platforms":["iOS"],"languages":["swift"]}]}],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageListViewActionEventsDelegate/onMoreMessagesClicked()":{"url":"\/documentation\/shengwangchatuikit\/messagelistviewactioneventsdelegate\/onmoremessagesclicked()","type":"topic","abstract":[{"type":"text","text":"More messages button clicked."}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onMoreMessagesClicked"},{"text":"()","kind":"text"}],"title":"onMoreMessagesClicked()","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewActionEventsDelegate\/onMoreMessagesClicked()","required":true,"navigatorTitle":[{"kind":"identifier","text":"onMoreMessagesClicked"}],"role":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageListViewActionEventsDelegate":{"navigatorTitle":[{"text":"MessageListViewActionEventsDelegate","kind":"identifier"}],"title":"MessageListViewActionEventsDelegate","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewActionEventsDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"MessageListViewActionEventsDelegate","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/messagelistviewactioneventsdelegate","abstract":[],"kind":"symbol","type":"topic"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"value":"onMoreMessagesClicked","path":"\/metadata\/title","op":"replace"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onMoreMessagesClicked"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"onMoreMessagesClicked","kind":"identifier"},{"kind":"text","text":";"}]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewActionEventsDelegate~1onMoreMessagesClicked()\/title","value":"onMoreMessagesClicked","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewActionEventsDelegate~1onMoreMessagesClicked()\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"onMoreMessagesClicked"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewActionEventsDelegate\/title","value":"MessageListViewActionEventsDelegate","op":"replace"},{"value":[{"kind":"identifier","text":"MessageListViewActionEventsDelegate"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewActionEventsDelegate\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewActionEventsDelegate\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MessageListViewActionEventsDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}