{"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupParticipantsController\/chatGroup","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"chatGroup","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit0B5Groupa","text":"ChatGroup","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatGroup"},{"text":" { get }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupParticipantsController"]]},"sections":[],"metadata":{"externalID":"c:@M@ShengwangChatUIKit@objc(cs)GroupParticipantsController(py)chatGroup","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","title":"chatGroup","modules":[{"name":"ShengwangChatUIKit"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"chatGroup","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"ChatGroup","preciseIdentifier":"s:18ShengwangChatUIKit0B5Groupa"}],"navigatorTitle":[{"kind":"identifier","text":"chatGroup"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/groupparticipantscontroller\/chatgroup"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/groupparticipantscontroller\/chatgroup"]}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatGroup":{"type":"topic","role":"symbol","title":"ChatGroup","kind":"symbol","abstract":[],"navigatorTitle":[{"text":"ChatGroup","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/chatgroup","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatGroup","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"text":"ChatGroup","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/GroupParticipantsController":{"title":"GroupParticipantsController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupParticipantsController"}],"navigatorTitle":[{"text":"GroupParticipantsController","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/shengwangchatuikit\/groupparticipantscontroller","abstract":[{"type":"text","text":"A view controller that displays the participants of a group."}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupParticipantsController","role":"symbol","type":"topic"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/GroupParticipantsController/chatGroup":{"kind":"symbol","url":"\/documentation\/shengwangchatuikit\/groupparticipantscontroller\/chatgroup","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"chatGroup","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ChatGroup","kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit0B5Groupa"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupParticipantsController\/chatGroup","title":"chatGroup","navigatorTitle":[{"kind":"identifier","text":"chatGroup"}],"abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"chatGroup"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"chatGroup"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AgoraChatGroup","text":"AgoraChatGroup"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"chatGroup"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupParticipantsController\/title","op":"replace","value":"GroupParticipantsController"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupParticipantsController\/fragments","value":[{"kind":"identifier","text":"GroupParticipantsController"}],"op":"replace"},{"value":[{"kind":"identifier","text":"GroupParticipantsController"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupParticipantsController\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupParticipantsController~1chatGroup\/title","value":"chatGroup"},{"value":[{"text":"chatGroup","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupParticipantsController~1chatGroup\/fragments","op":"replace"}]}]}