{"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupParticipantsController\/createNavigation()"},"metadata":{"role":"symbol","title":"createNavigation()","symbolKind":"method","externalID":"c:@M@ShengwangChatUIKit@objc(cs)GroupParticipantsController(im)createNavigation","navigatorTitle":[{"kind":"identifier","text":"createNavigation"}],"roleHeading":"Instance Method","modules":[{"name":"ShengwangChatUIKit"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"createNavigation"},{"kind":"text","text":"() -> "},{"text":"ChatNavigationBar","kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)ChatNavigationBar"}]},"sections":[],"kind":"symbol","abstract":[{"text":"Creates and returns a navigation bar for the GroupParticipantsController.","type":"text"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"@","kind":"attribute"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createNavigation","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"ChatNavigationBar","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatNavigationBar","kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)ChatNavigationBar"}],"platforms":["iOS"]}],"kind":"declarations"},{"content":[{"text":"Return Value","type":"heading","level":2,"anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"An instance of EaseChatNavigationBar."}]}],"kind":"content"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupParticipantsController"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/groupparticipantscontroller\/createnavigation()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/groupparticipantscontroller\/createnavigation()"]}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/GroupParticipantsController":{"title":"GroupParticipantsController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupParticipantsController"}],"navigatorTitle":[{"text":"GroupParticipantsController","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/shengwangchatuikit\/groupparticipantscontroller","abstract":[{"type":"text","text":"A view controller that displays the participants of a group."}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupParticipantsController","role":"symbol","type":"topic"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/GroupParticipantsController/createNavigation()":{"title":"createNavigation()","abstract":[{"type":"text","text":"Creates and returns a navigation bar for the GroupParticipantsController."}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"createNavigation"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"createNavigation"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)ChatNavigationBar","kind":"typeIdentifier","text":"ChatNavigationBar"}],"role":"symbol","url":"\/documentation\/shengwangchatuikit\/groupparticipantscontroller\/createnavigation()","type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupParticipantsController\/createNavigation()"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatNavigationBar":{"navigatorTitle":[{"kind":"identifier","text":"ChatNavigationBar"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatNavigationBar"}],"kind":"symbol","abstract":[{"type":"text","text":"Navigation  bar of the ChatUIKit."}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatNavigationBar","url":"\/documentation\/shengwangchatuikit\/chatnavigationbar","type":"topic","title":"ChatNavigationBar","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"createNavigation"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"createNavigation"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatNavigationBar","text":"ChatNavigationBar","kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)ChatNavigationBar"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"createNavigation"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/primaryContentSections\/1","value":{"content":[{"type":"heading","anchor":"return-value","text":"Return Value","level":2},{"inlineContent":[{"type":"text","text":"An instance of EaseChatNavigationBar."}],"type":"paragraph"}],"kind":"content"},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupParticipantsController\/title","op":"replace","value":"GroupParticipantsController"},{"value":[{"kind":"identifier","text":"GroupParticipantsController"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupParticipantsController\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupParticipantsController\/navigatorTitle","value":[{"text":"GroupParticipantsController","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupParticipantsController~1createNavigation()\/title","value":"createNavigation","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupParticipantsController~1createNavigation()\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"createNavigation","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatNavigationBar\/title","op":"replace","value":"ChatNavigationBar"},{"op":"replace","value":[{"text":"ChatNavigationBar","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatNavigationBar\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatNavigationBar\/navigatorTitle","value":[{"text":"ChatNavigationBar","kind":"identifier"}],"op":"replace"}]}]}