{"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupParticipantsController\/init(groupId:operation:)","interfaceLanguage":"swift"},"sections":[],"variants":[{"paths":["\/documentation\/shengwangchatuikit\/groupparticipantscontroller\/init(groupid:operation:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/shengwangchatuikit\/groupparticipantscontroller\/init(groupid:operation:)"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"Initializes a ","type":"text"},{"type":"codeVoice","code":"GroupParticipantsController"},{"type":"text","text":" with the specified group ID and operation."}],"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"required","kind":"keyword"},{"kind":"text","text":" "},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"groupId","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"operation","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@E@GroupParticipantsOperation","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupParticipantsOperation","text":"GroupParticipantsOperation"},{"text":" = .normal)","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"name":"groupId","content":[{"inlineContent":[{"text":"The ID of the group.","type":"text"}],"type":"paragraph"}]},{"name":"operation","content":[{"type":"paragraph","inlineContent":[{"text":"The operation to be performed on the group participants. Default value is ","type":"text"},{"type":"codeVoice","code":".normal"},{"type":"text","text":"."}]}]}],"kind":"parameters"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupParticipantsController"]]},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"initWithGroupId:operation:"}],"role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"groupId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"operation"},{"kind":"text","text":": "},{"text":"GroupParticipantsOperation","kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@E@GroupParticipantsOperation"},{"text":")","kind":"text"}],"roleHeading":"Initializer","modules":[{"name":"ShengwangChatUIKit"}],"symbolKind":"init","title":"init(groupId:operation:)","externalID":"c:@M@ShengwangChatUIKit@objc(cs)GroupParticipantsController(im)initWithGroupId:operation:"},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/GroupParticipantsController":{"title":"GroupParticipantsController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupParticipantsController"}],"navigatorTitle":[{"text":"GroupParticipantsController","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/shengwangchatuikit\/groupparticipantscontroller","abstract":[{"type":"text","text":"A view controller that displays the participants of a group."}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupParticipantsController","role":"symbol","type":"topic"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/GroupParticipantsOperation":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GroupParticipantsOperation","kind":"identifier"}],"title":"GroupParticipantsOperation","abstract":[{"type":"text","text":"An enumeration representing the possible operations for group participants."}],"type":"topic","kind":"symbol","url":"\/documentation\/shengwangchatuikit\/groupparticipantsoperation","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupParticipantsOperation","navigatorTitle":[{"text":"GroupParticipantsOperation","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/GroupParticipantsController/init(groupId:operation:)":{"type":"topic","navigatorTitle":[{"text":"initWithGroupId:operation:","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/groupparticipantscontroller\/init(groupid:operation:)","kind":"symbol","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"groupId"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"operation","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@E@GroupParticipantsOperation","text":"GroupParticipantsOperation"},{"kind":"text","text":")"}],"abstract":[{"text":"Initializes a ","type":"text"},{"code":"GroupParticipantsController","type":"codeVoice"},{"text":" with the specified group ID and operation.","type":"text"}],"title":"init(groupId:operation:)","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupParticipantsController\/init(groupId:operation:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","value":"initWithGroupId:operation:","path":"\/metadata\/title"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithGroupId:operation:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","kind":"typeIdentifier","text":"id"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithGroupId:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"groupId"},{"text":" ","kind":"text"},{"text":"operation:","kind":"identifier"},{"kind":"text","text":"("},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupParticipantsOperation","text":"GroupParticipantsOperation","preciseIdentifier":"c:@M@ShengwangChatUIKit@E@GroupParticipantsOperation"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"operation"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"parameters":[{"name":"groupId","content":[{"type":"paragraph","inlineContent":[{"text":"The ID of the group.","type":"text"}]}]},{"name":"operation","content":[{"type":"paragraph","inlineContent":[{"text":"The operation to be performed on the group participants. Default value is ","type":"text"},{"code":".normal","type":"codeVoice"},{"type":"text","text":"."}]}]}],"kind":"parameters"},"path":"\/primaryContentSections\/1","op":"replace"},{"op":"add","path":"\/primaryContentSections\/2","value":{"content":[{"anchor":"return-value","type":"heading","level":2,"text":"Return Value"},{"inlineContent":[{"text":"An initialized ","type":"text"},{"code":"GroupParticipantsController","type":"codeVoice"},{"text":" instance.","type":"text"}],"type":"paragraph"}],"kind":"content"}},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupParticipantsController\/title","value":"GroupParticipantsController","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupParticipantsController\/fragments","op":"replace","value":[{"text":"GroupParticipantsController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupParticipantsController\/navigatorTitle","op":"replace","value":[{"text":"GroupParticipantsController","kind":"identifier"}]},{"op":"replace","value":"GroupParticipantsOperation","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupParticipantsOperation\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupParticipantsOperation\/fragments","value":[{"text":"GroupParticipantsOperation","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupParticipantsOperation\/navigatorTitle","value":[{"kind":"identifier","text":"GroupParticipantsOperation"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupParticipantsController~1init(groupId:operation:)\/title","value":"initWithGroupId:operation:"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupParticipantsController~1init(groupId:operation:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithGroupId:operation:"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}