{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupParticipantsController\/operation"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupParticipantsController"]]},"kind":"symbol","metadata":{"navigatorTitle":[{"text":"operation","kind":"identifier"}],"modules":[{"name":"ShengwangChatUIKit"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"operation","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"GroupParticipantsOperation","preciseIdentifier":"c:@M@ShengwangChatUIKit@E@GroupParticipantsOperation"}],"externalID":"c:@M@ShengwangChatUIKit@objc(cs)GroupParticipantsController(py)operation","role":"symbol","symbolKind":"property","roleHeading":"Instance Property","title":"operation"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"operation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupParticipantsOperation","preciseIdentifier":"c:@M@ShengwangChatUIKit@E@GroupParticipantsOperation","text":"GroupParticipantsOperation"},{"kind":"text","text":" { get }"}],"languages":["swift"],"platforms":["iOS"]}]}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/groupparticipantscontroller\/operation"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/groupparticipantscontroller\/operation"]}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/GroupParticipantsOperation":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GroupParticipantsOperation","kind":"identifier"}],"title":"GroupParticipantsOperation","abstract":[{"type":"text","text":"An enumeration representing the possible operations for group participants."}],"type":"topic","kind":"symbol","url":"\/documentation\/shengwangchatuikit\/groupparticipantsoperation","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupParticipantsOperation","navigatorTitle":[{"text":"GroupParticipantsOperation","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/GroupParticipantsController":{"title":"GroupParticipantsController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupParticipantsController"}],"navigatorTitle":[{"text":"GroupParticipantsController","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/shengwangchatuikit\/groupparticipantscontroller","abstract":[{"type":"text","text":"A view controller that displays the participants of a group."}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupParticipantsController","role":"symbol","type":"topic"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/GroupParticipantsController/operation":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupParticipantsController\/operation","navigatorTitle":[{"kind":"identifier","text":"operation"}],"abstract":[],"type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"operation","kind":"identifier"},{"kind":"text","text":": "},{"text":"GroupParticipantsOperation","preciseIdentifier":"c:@M@ShengwangChatUIKit@E@GroupParticipantsOperation","kind":"typeIdentifier"}],"title":"operation","url":"\/documentation\/shengwangchatuikit\/groupparticipantscontroller\/operation"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"operation","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"operation"}]},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"GroupParticipantsOperation","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupParticipantsOperation","kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@E@GroupParticipantsOperation"},{"text":" ","kind":"text"},{"text":"operation","kind":"identifier"},{"kind":"text","text":";"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupParticipantsOperation\/title","value":"GroupParticipantsOperation"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupParticipantsOperation\/fragments","value":[{"text":"GroupParticipantsOperation","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupParticipantsOperation\/navigatorTitle","value":[{"kind":"identifier","text":"GroupParticipantsOperation"}],"op":"replace"},{"value":"GroupParticipantsController","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupParticipantsController\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupParticipantsController\/fragments","value":[{"text":"GroupParticipantsController","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupParticipantsController\/navigatorTitle","value":[{"text":"GroupParticipantsController","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupParticipantsController~1operation\/title","value":"operation","op":"replace"},{"value":[{"kind":"identifier","text":"operation"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupParticipantsController~1operation\/fragments"}]}]}