{"sections":[],"metadata":{"title":"init(rawValue:)","symbolKind":"init","roleHeading":"Initializer","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UInt8","preciseIdentifier":"s:s5UInt8V"},{"text":")","kind":"text"}],"modules":[{"name":"ShengwangChatUIKit"}],"role":"symbol","externalID":"s:18ShengwangChatUIKit17TriangleDirectionO8rawValueACSgs5UInt8V_tcfc"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/TriangleDirection\/init(rawValue:)"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/TriangleDirection"]]},"abstract":[{"type":"text","text":"Inherited from "},{"code":"RawRepresentable.init(rawValue:)","type":"codeVoice"},{"text":".","type":"text"}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5UInt8V","text":"UInt8"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/triangledirection\/init(rawvalue:)"]}],"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/TriangleDirection/init(rawValue:)":{"title":"init(rawValue:)","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/TriangleDirection\/init(rawValue:)","role":"symbol","kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5UInt8V","text":"UInt8"},{"text":")","kind":"text"}],"type":"topic","abstract":[],"url":"\/documentation\/shengwangchatuikit\/triangledirection\/init(rawvalue:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/TriangleDirection":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/TriangleDirection","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"TriangleDirection","kind":"identifier"}],"title":"TriangleDirection","type":"topic","role":"symbol","url":"\/documentation\/shengwangchatuikit\/triangledirection","kind":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"TriangleDirection"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1TriangleDirection\/title","value":"TriangleDirection"},{"op":"replace","value":[{"kind":"identifier","text":"TriangleDirection"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1TriangleDirection\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1TriangleDirection\/navigatorTitle","value":[{"kind":"identifier","text":"TriangleDirection"}]}]}]}