{"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/triangledirection\/right"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/triangledirection\/right"]}],"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/TriangleDirection\/right","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/TriangleDirection"]]},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"right"}],"externalID":"c:@M@ShengwangChatUIKit@E@TriangleDirection@TriangleDirectionRight","role":"symbol","roleHeading":"Case","modules":[{"name":"ShengwangChatUIKit"}],"title":"TriangleDirection.right","symbolKind":"case","navigatorTitle":[{"text":"TriangleDirectionRight","kind":"identifier"}]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"right"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/TriangleDirection":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/TriangleDirection","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"TriangleDirection","kind":"identifier"}],"title":"TriangleDirection","type":"topic","role":"symbol","url":"\/documentation\/shengwangchatuikit\/triangledirection","kind":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"TriangleDirection"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/TriangleDirection/right":{"url":"\/documentation\/shengwangchatuikit\/triangledirection\/right","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/TriangleDirection\/right","title":"TriangleDirection.right","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"right"}],"navigatorTitle":[{"kind":"identifier","text":"TriangleDirectionRight"}],"type":"topic","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"TriangleDirectionRight","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"TriangleDirectionRight","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"TriangleDirectionRight"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1TriangleDirection\/title","value":"TriangleDirection"},{"op":"replace","value":[{"kind":"identifier","text":"TriangleDirection"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1TriangleDirection\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1TriangleDirection\/navigatorTitle","op":"replace","value":[{"text":"TriangleDirection","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1TriangleDirection~1right\/title","value":"TriangleDirectionRight","op":"replace"},{"value":[{"text":"TriangleDirectionRight","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1TriangleDirection~1right\/fragments","op":"replace"}]}]}