{"sections":[],"abstract":[{"type":"text","text":"Inherited from "},{"code":"UIDocumentPickerDelegate.documentPicker(_:didPickDocumentsAt:)","type":"codeVoice"},{"text":".","type":"text"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadCreateController","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadCreateController\/UIDocumentPickerDelegate-Implementations"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadCreateController\/documentPicker(_:didPickDocumentsAt:)","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"ShengwangChatUIKit"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"documentPicker","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UIDocumentPickerViewController","text":"UIDocumentPickerViewController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didPickDocumentsAt","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"URL","preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier"},{"text":"])","kind":"text"}],"role":"symbol","extendedModule":"ShengwangChatUIKit","title":"documentPicker(_:didPickDocumentsAt:)","symbolKind":"method","roleHeading":"Instance Method","navigatorTitle":[{"text":"documentPicker:didPickDocumentsAtURLs:","kind":"identifier"}],"externalID":"c:@CM@ShengwangChatUIKit@objc(cs)ChatThreadCreateController(im)documentPicker:didPickDocumentsAtURLs:"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"documentPicker","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"controller"},{"kind":"text","text":": "},{"text":"UIDocumentPickerViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIDocumentPickerViewController"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didPickDocumentsAt"},{"text":" ","kind":"text"},{"text":"urls","kind":"internalParam"},{"kind":"text","text":": ["},{"text":"URL","preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier"},{"kind":"text","text":"])"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/shengwangchatuikit\/chatthreadcreatecontroller\/documentpicker(_:didpickdocumentsat:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/chatthreadcreatecontroller\/documentpicker(_:didpickdocumentsat:)"]}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatThreadCreateController/UIDocumentPickerDelegate-Implementations":{"role":"collectionGroup","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadCreateController\/UIDocumentPickerDelegate-Implementations","url":"\/documentation\/shengwangchatuikit\/chatthreadcreatecontroller\/uidocumentpickerdelegate-implementations","type":"topic","abstract":[],"title":"UIDocumentPickerDelegate Implementations","kind":"article"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatThreadCreateController":{"title":"ChatThreadCreateController","abstract":[],"url":"\/documentation\/shengwangchatuikit\/chatthreadcreatecontroller","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadCreateController","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ChatThreadCreateController","kind":"identifier"}],"navigatorTitle":[{"text":"ChatThreadCreateController","kind":"identifier"}],"role":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatThreadCreateController/documentPicker(_:didPickDocumentsAt:)":{"abstract":[],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadCreateController\/documentPicker(_:didPickDocumentsAt:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"documentPicker","kind":"identifier"},{"kind":"text","text":"("},{"text":"UIDocumentPickerViewController","preciseIdentifier":"c:objc(cs)UIDocumentPickerViewController","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"didPickDocumentsAt","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"])"}],"kind":"symbol","navigatorTitle":[{"text":"documentPicker:didPickDocumentsAtURLs:","kind":"identifier"}],"role":"symbol","title":"documentPicker(_:didPickDocumentsAt:)","type":"topic","url":"\/documentation\/shengwangchatuikit\/chatthreadcreatecontroller\/documentpicker(_:didpickdocumentsat:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","value":"documentPicker:didPickDocumentsAtURLs:","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"documentPicker:didPickDocumentsAtURLs:"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"documentPicker:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIDocumentPickerViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIDocumentPickerViewController"},{"text":" *) ","kind":"text"},{"text":"controller","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"didPickDocumentsAtURLs:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier","text":"NSArray<NSURL *>"},{"text":" *) ","kind":"text"},{"text":"urls","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadCreateController\/title","value":"ChatThreadCreateController"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadCreateController\/fragments","value":[{"text":"ChatThreadCreateController","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadCreateController\/navigatorTitle","value":[{"text":"ChatThreadCreateController","kind":"identifier"}]},{"value":"documentPicker:didPickDocumentsAtURLs:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadCreateController~1documentPicker(_:didPickDocumentsAt:)\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"documentPicker:didPickDocumentsAtURLs:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadCreateController~1documentPicker(_:didPickDocumentsAt:)\/fragments"}]}]}