{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/chatthreadcreatecontroller\/onmessagecontentclicked(message:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/chatthreadcreatecontroller\/onmessagecontentclicked(message:)"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadCreateController","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadCreateController\/MessageListViewActionEventsDelegate-Implementations"]]},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"The method will call on message content clicked."}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onMessageContentClicked"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"text":"MessageEntity","kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)MessageEntity","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageEntity"},{"text":")","kind":"text"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageEntity"}],"type":"paragraph"}],"name":"message"}]}],"metadata":{"roleHeading":"Instance Method","title":"onMessageContentClicked(message:)","extendedModule":"ShengwangChatUIKit","role":"symbol","navigatorTitle":[{"text":"onMessageContentClickedWithMessage:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"onMessageContentClicked","kind":"identifier"},{"kind":"text","text":"("},{"text":"message","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)MessageEntity","text":"MessageEntity","kind":"typeIdentifier"},{"text":")","kind":"text"}],"externalID":"c:@CM@ShengwangChatUIKit@objc(cs)ChatThreadCreateController(im)onMessageContentClickedWithMessage:","modules":[{"name":"ShengwangChatUIKit"}],"symbolKind":"method"},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadCreateController\/onMessageContentClicked(message:)"},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageEntity":{"navigatorTitle":[{"text":"MessageEntity","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageEntity","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessageEntity","kind":"identifier"}],"title":"MessageEntity","abstract":[],"url":"\/documentation\/shengwangchatuikit\/messageentity"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatThreadCreateController/onMessageContentClicked(message:)":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadCreateController\/onMessageContentClicked(message:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"onMessageContentClickedWithMessage:"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onMessageContentClicked","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)MessageEntity","text":"MessageEntity","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","abstract":[{"type":"text","text":"The method will call on message content clicked."}],"url":"\/documentation\/shengwangchatuikit\/chatthreadcreatecontroller\/onmessagecontentclicked(message:)","type":"topic","title":"onMessageContentClicked(message:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatThreadCreateController":{"title":"ChatThreadCreateController","abstract":[],"url":"\/documentation\/shengwangchatuikit\/chatthreadcreatecontroller","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadCreateController","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ChatThreadCreateController","kind":"identifier"}],"navigatorTitle":[{"text":"ChatThreadCreateController","kind":"identifier"}],"role":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatThreadCreateController/MessageListViewActionEventsDelegate-Implementations":{"abstract":[],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadCreateController\/MessageListViewActionEventsDelegate-Implementations","url":"\/documentation\/shengwangchatuikit\/chatthreadcreatecontroller\/messagelistviewactioneventsdelegate-implementations","role":"collectionGroup","type":"topic","title":"MessageListViewActionEventsDelegate Implementations","kind":"article"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"onMessageContentClickedWithMessage:","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"text":"- ","kind":"text"},{"text":"onMessageContentClickedWithMessage:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"onMessageContentClickedWithMessage:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"MessageEntity","kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)MessageEntity","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageEntity"},{"text":" *) ","kind":"text"},{"text":"message","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageEntity\/title","op":"replace","value":"MessageEntity"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageEntity\/fragments","op":"replace","value":[{"kind":"identifier","text":"MessageEntity"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageEntity\/navigatorTitle","op":"replace","value":[{"text":"MessageEntity","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadCreateController~1onMessageContentClicked(message:)\/title","value":"onMessageContentClickedWithMessage:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadCreateController~1onMessageContentClicked(message:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"onMessageContentClickedWithMessage:"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadCreateController\/title","op":"replace","value":"ChatThreadCreateController"},{"value":[{"text":"ChatThreadCreateController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadCreateController\/fragments"},{"value":[{"kind":"identifier","text":"ChatThreadCreateController"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadCreateController\/navigatorTitle","op":"replace"}]}]}