{"abstract":[{"text":"Message topic view clicked.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadCreateController","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadCreateController\/MessageListViewActionEventsDelegate-Implementations"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadCreateController\/onMessageTopicClicked(entity:)"},"variants":[{"paths":["\/documentation\/shengwangchatuikit\/chatthreadcreatecontroller\/onmessagetopicclicked(entity:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/chatthreadcreatecontroller\/onmessagetopicclicked(entity:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"onMessageTopicClicked"},{"kind":"text","text":"("},{"text":"entity","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MessageEntity","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageEntity","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)MessageEntity"},{"kind":"text","text":")"}]}]},{"kind":"parameters","parameters":[{"name":"entity","content":[{"inlineContent":[{"type":"text","text":""},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageEntity"}],"type":"paragraph"}]}]}],"kind":"symbol","sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"title":"onMessageTopicClicked(entity:)","symbolKind":"method","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"onMessageTopicClickedWithEntity:"}],"externalID":"c:@CM@ShengwangChatUIKit@objc(cs)ChatThreadCreateController(im)onMessageTopicClickedWithEntity:","modules":[{"name":"ShengwangChatUIKit"}],"extendedModule":"ShengwangChatUIKit","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onMessageTopicClicked"},{"text":"(","kind":"text"},{"text":"entity","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)MessageEntity","text":"MessageEntity"},{"text":")","kind":"text"}]},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatThreadCreateController/MessageListViewActionEventsDelegate-Implementations":{"abstract":[],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadCreateController\/MessageListViewActionEventsDelegate-Implementations","url":"\/documentation\/shengwangchatuikit\/chatthreadcreatecontroller\/messagelistviewactioneventsdelegate-implementations","role":"collectionGroup","type":"topic","title":"MessageListViewActionEventsDelegate Implementations","kind":"article"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageEntity":{"navigatorTitle":[{"text":"MessageEntity","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageEntity","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessageEntity","kind":"identifier"}],"title":"MessageEntity","abstract":[],"url":"\/documentation\/shengwangchatuikit\/messageentity"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatThreadCreateController":{"title":"ChatThreadCreateController","abstract":[],"url":"\/documentation\/shengwangchatuikit\/chatthreadcreatecontroller","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadCreateController","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ChatThreadCreateController","kind":"identifier"}],"navigatorTitle":[{"text":"ChatThreadCreateController","kind":"identifier"}],"role":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatThreadCreateController/onMessageTopicClicked(entity:)":{"url":"\/documentation\/shengwangchatuikit\/chatthreadcreatecontroller\/onmessagetopicclicked(entity:)","title":"onMessageTopicClicked(entity:)","role":"symbol","navigatorTitle":[{"text":"onMessageTopicClickedWithEntity:","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadCreateController\/onMessageTopicClicked(entity:)","abstract":[{"text":"Message topic view clicked.","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"onMessageTopicClicked","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"entity"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)MessageEntity","text":"MessageEntity"},{"kind":"text","text":")"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"onMessageTopicClickedWithEntity:","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"onMessageTopicClickedWithEntity:","kind":"identifier"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"onMessageTopicClickedWithEntity:","kind":"identifier"},{"kind":"text","text":"("},{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageEntity","text":"MessageEntity","kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)MessageEntity"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"entity"},{"kind":"text","text":";"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"MessageEntity","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageEntity\/title"},{"value":[{"text":"MessageEntity","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageEntity\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageEntity\/navigatorTitle","value":[{"kind":"identifier","text":"MessageEntity"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadCreateController\/title","op":"replace","value":"ChatThreadCreateController"},{"value":[{"text":"ChatThreadCreateController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadCreateController\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadCreateController\/navigatorTitle","value":[{"kind":"identifier","text":"ChatThreadCreateController"}],"op":"replace"},{"op":"replace","value":"onMessageTopicClickedWithEntity:","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadCreateController~1onMessageTopicClicked(entity:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadCreateController~1onMessageTopicClicked(entity:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onMessageTopicClickedWithEntity:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}