{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadCreateController"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"article","metadata":{"modules":[{"name":"ShengwangChatUIKit"}],"role":"collectionGroup","title":"UIDocumentPickerDelegate Implementations","roleHeading":"API Collection"},"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadCreateController\/UIDocumentPickerDelegate-Implementations","interfaceLanguage":"swift"},"sections":[],"topicSections":[{"generated":true,"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadCreateController\/documentPicker(_:didPickDocumentsAt:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadCreateController\/documentPickerWasCancelled(_:)"],"anchor":"Instance-Methods","title":"Instance Methods"}],"variants":[{"paths":["\/documentation\/shengwangchatuikit\/chatthreadcreatecontroller\/uidocumentpickerdelegate-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/chatthreadcreatecontroller\/uidocumentpickerdelegate-implementations"]}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatThreadCreateController/documentPickerWasCancelled(_:)":{"title":"documentPickerWasCancelled(_:)","type":"topic","url":"\/documentation\/shengwangchatuikit\/chatthreadcreatecontroller\/documentpickerwascancelled(_:)","kind":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadCreateController\/documentPickerWasCancelled(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"documentPickerWasCancelled"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIDocumentPickerViewController","text":"UIDocumentPickerViewController"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"documentPickerWasCancelled:"}],"role":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatThreadCreateController/documentPicker(_:didPickDocumentsAt:)":{"abstract":[],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadCreateController\/documentPicker(_:didPickDocumentsAt:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"documentPicker","kind":"identifier"},{"kind":"text","text":"("},{"text":"UIDocumentPickerViewController","preciseIdentifier":"c:objc(cs)UIDocumentPickerViewController","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"didPickDocumentsAt","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"])"}],"kind":"symbol","navigatorTitle":[{"text":"documentPicker:didPickDocumentsAtURLs:","kind":"identifier"}],"role":"symbol","title":"documentPicker(_:didPickDocumentsAt:)","type":"topic","url":"\/documentation\/shengwangchatuikit\/chatthreadcreatecontroller\/documentpicker(_:didpickdocumentsat:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatThreadCreateController":{"title":"ChatThreadCreateController","abstract":[],"url":"\/documentation\/shengwangchatuikit\/chatthreadcreatecontroller","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadCreateController","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ChatThreadCreateController","kind":"identifier"}],"navigatorTitle":[{"text":"ChatThreadCreateController","kind":"identifier"}],"role":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/topicSections","op":"replace","value":[{"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadCreateController\/documentPicker(_:didPickDocumentsAt:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadCreateController\/documentPickerWasCancelled(_:)"],"generated":true,"anchor":"Instance-Methods","title":"Instance Methods"}]},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadCreateController~1documentPickerWasCancelled(_:)\/title","value":"documentPickerWasCancelled:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadCreateController~1documentPickerWasCancelled(_:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"documentPickerWasCancelled:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadCreateController~1documentPicker(_:didPickDocumentsAt:)\/title","value":"documentPicker:didPickDocumentsAtURLs:","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"documentPicker:didPickDocumentsAtURLs:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadCreateController~1documentPicker(_:didPickDocumentsAt:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadCreateController\/title","value":"ChatThreadCreateController"},{"op":"replace","value":[{"kind":"identifier","text":"ChatThreadCreateController"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadCreateController\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadCreateController\/navigatorTitle","value":[{"text":"ChatThreadCreateController","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}