{"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ReactionEmojiCell\/refresh(reaction:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"refresh"},{"kind":"text","text":"("},{"text":"reaction","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/Reaction","text":"Reaction","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)Reaction"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"sections":[],"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"refresh","kind":"identifier"},{"text":"(","kind":"text"},{"text":"reaction","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Reaction","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)Reaction","kind":"typeIdentifier"},{"kind":"text","text":")"}],"symbolKind":"method","modules":[{"name":"ShengwangChatUIKit"}],"roleHeading":"Instance Method","role":"symbol","externalID":"c:@M@ShengwangChatUIKit@objc(cs)ReactionEmojiCell(im)refreshWithReaction:","title":"refresh(reaction:)","navigatorTitle":[{"kind":"identifier","text":"refreshWithReaction:"}]},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ReactionEmojiCell"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/reactionemojicell\/refresh(reaction:)"]},{"paths":["\/documentation\/shengwangchatuikit\/reactionemojicell\/refresh(reaction:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ReactionEmojiCell":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ReactionEmojiCell","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/shengwangchatuikit\/reactionemojicell","type":"topic","title":"ReactionEmojiCell","abstract":[],"role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ReactionEmojiCell","navigatorTitle":[{"text":"ReactionEmojiCell","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/Reaction":{"navigatorTitle":[{"kind":"identifier","text":"Reaction"}],"abstract":[],"kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/Reaction","url":"\/documentation\/shengwangchatuikit\/reaction","title":"Reaction","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Reaction","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ReactionEmojiCell/refresh(reaction:)":{"type":"topic","role":"symbol","title":"refresh(reaction:)","kind":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"refreshWithReaction:"}],"url":"\/documentation\/shengwangchatuikit\/reactionemojicell\/refresh(reaction:)","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ReactionEmojiCell\/refresh(reaction:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"refresh"},{"kind":"text","text":"("},{"text":"reaction","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Reaction","kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)Reaction"},{"kind":"text","text":")"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"value":"refreshWithReaction:","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"kind":"text","text":"- "},{"text":"refreshWithReaction:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"refreshWithReaction:","kind":"identifier"},{"kind":"text","text":"("},{"text":"Reaction","kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)Reaction","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/Reaction"},{"text":" *) ","kind":"text"},{"text":"reaction","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ReactionEmojiCell\/title","value":"ReactionEmojiCell"},{"value":[{"kind":"identifier","text":"ReactionEmojiCell"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ReactionEmojiCell\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ReactionEmojiCell\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"ReactionEmojiCell"}]},{"op":"replace","value":"Reaction","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1Reaction\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1Reaction\/fragments","value":[{"text":"Reaction","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1Reaction\/navigatorTitle","value":[{"text":"Reaction","kind":"identifier"}],"op":"replace"},{"value":"refreshWithReaction:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ReactionEmojiCell~1refresh(reaction:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"refreshWithReaction:"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ReactionEmojiCell~1refresh(reaction:)\/fragments"}]}]}