{"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/presentationanimation\/beforeanimation(animationcontext:)"]}],"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PresentationAnimation\/beforeAnimation(animationContext:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PresentationAnimation"]]},"kind":"symbol","metadata":{"externalID":"s:18ShengwangChatUIKit21PresentationAnimationC06beforeE016animationContextyAA0eH0V_tF","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"beforeAnimation","kind":"identifier"},{"text":"(","kind":"text"},{"text":"animationContext","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:18ShengwangChatUIKit16AnimationContextV","kind":"typeIdentifier","text":"AnimationContext"},{"kind":"text","text":")"}],"role":"symbol","title":"beforeAnimation(animationContext:)","modules":[{"name":"ShengwangChatUIKit"}],"symbolKind":"method"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"beforeAnimation"},{"kind":"text","text":"("},{"kind":"externalParam","text":"animationContext"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:18ShengwangChatUIKit16AnimationContextV","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/AnimationContext","text":"AnimationContext"},{"kind":"text","text":")"}],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/AnimationContext":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"AnimationContext"}],"type":"topic","title":"AnimationContext","url":"\/documentation\/shengwangchatuikit\/animationcontext","navigatorTitle":[{"kind":"identifier","text":"AnimationContext"}],"abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/AnimationContext","role":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/PresentationAnimation/beforeAnimation(animationContext:)":{"url":"\/documentation\/shengwangchatuikit\/presentationanimation\/beforeanimation(animationcontext:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"beforeAnimation"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"animationContext"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit16AnimationContextV","text":"AnimationContext"},{"kind":"text","text":")"}],"role":"symbol","title":"beforeAnimation(animationContext:)","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PresentationAnimation\/beforeAnimation(animationContext:)","kind":"symbol","abstract":[]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/PresentationAnimation":{"navigatorTitle":[{"text":"PresentationAnimation","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PresentationAnimation","url":"\/documentation\/shengwangchatuikit\/presentationanimation","abstract":[],"role":"symbol","kind":"symbol","type":"topic","title":"PresentationAnimation","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"PresentationAnimation","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PresentationAnimation\/title","value":"PresentationAnimation"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PresentationAnimation\/fragments","op":"replace","value":[{"kind":"identifier","text":"PresentationAnimation"}]},{"op":"replace","value":[{"text":"PresentationAnimation","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PresentationAnimation\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}