{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/presentationanimation\/uiviewcontrolleranimatedtransitioning-implementations"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/presentationanimation\/uiviewcontrolleranimatedtransitioning-implementations"]}],"metadata":{"modules":[{"name":"ShengwangChatUIKit"}],"role":"collectionGroup","roleHeading":"API Collection","title":"UIViewControllerAnimatedTransitioning Implementations"},"schemaVersion":{"minor":3,"major":0,"patch":0},"topicSections":[{"anchor":"Instance-Methods","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PresentationAnimation\/animateTransition(using:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PresentationAnimation\/transitionDuration(using:)"],"generated":true,"title":"Instance Methods"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PresentationAnimation"]]},"kind":"article","identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PresentationAnimation\/UIViewControllerAnimatedTransitioning-Implementations","interfaceLanguage":"swift"},"sections":[],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/PresentationAnimation/animateTransition(using:)":{"title":"animateTransition(using:)","abstract":[],"navigatorTitle":[{"text":"animateTransition:","kind":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PresentationAnimation\/animateTransition(using:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"animateTransition","kind":"identifier"},{"text":"(","kind":"text"},{"text":"using","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UIViewControllerContextTransitioning","preciseIdentifier":"c:objc(pl)UIViewControllerContextTransitioning","kind":"typeIdentifier"},{"kind":"text","text":")"}],"role":"symbol","url":"\/documentation\/shengwangchatuikit\/presentationanimation\/animatetransition(using:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/PresentationAnimation/transitionDuration(using:)":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PresentationAnimation\/transitionDuration(using:)","kind":"symbol","title":"transitionDuration(using:)","abstract":[],"url":"\/documentation\/shengwangchatuikit\/presentationanimation\/transitionduration(using:)","navigatorTitle":[{"text":"transitionDuration:","kind":"identifier"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"transitionDuration","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"using"},{"text":": ","kind":"text"},{"text":"UIViewControllerContextTransitioning","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)UIViewControllerContextTransitioning"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/PresentationAnimation":{"navigatorTitle":[{"text":"PresentationAnimation","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PresentationAnimation","url":"\/documentation\/shengwangchatuikit\/presentationanimation","abstract":[],"role":"symbol","kind":"symbol","type":"topic","title":"PresentationAnimation","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"PresentationAnimation","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":[{"generated":true,"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PresentationAnimation\/animateTransition(using:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PresentationAnimation\/transitionDuration(using:)"],"anchor":"Instance-Methods","title":"Instance Methods"}],"path":"\/topicSections","op":"replace"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PresentationAnimation~1animateTransition(using:)\/title","op":"replace","value":"animateTransition:"},{"value":[{"text":"- ","kind":"text"},{"text":"animateTransition:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PresentationAnimation~1animateTransition(using:)\/fragments","op":"replace"},{"op":"replace","value":"transitionDuration:","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PresentationAnimation~1transitionDuration(using:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PresentationAnimation~1transitionDuration(using:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"transitionDuration:","kind":"identifier"}]},{"value":"PresentationAnimation","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PresentationAnimation\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PresentationAnimation\/fragments","value":[{"text":"PresentationAnimation","kind":"identifier"}]},{"value":[{"text":"PresentationAnimation","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PresentationAnimation\/navigatorTitle","op":"replace"}]}]}