{"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/EaseChatUIKitCacheType\/all"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"all","kind":"identifier"}]}]}],"variants":[{"paths":["\/documentation\/shengwangchatuikit\/easechatuikitcachetype\/all"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/easechatuikitcachetype\/all"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/EaseChatUIKitCacheType"]]},"kind":"symbol","metadata":{"navigatorTitle":[{"text":"EaseChatUIKitCacheTypeAll","kind":"identifier"}],"externalID":"c:@M@ShengwangChatUIKit@E@EaseChatUIKitCacheType@EaseChatUIKitCacheTypeAll","title":"EaseChatUIKitCacheType.all","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"all","kind":"identifier"}],"modules":[{"name":"ShengwangChatUIKit"}],"symbolKind":"case","role":"symbol","roleHeading":"Case"},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/EaseChatUIKitCacheType":{"url":"\/documentation\/shengwangchatuikit\/easechatuikitcachetype","kind":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"EaseChatUIKitCacheType"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/EaseChatUIKitCacheType","title":"EaseChatUIKitCacheType","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"EaseChatUIKitCacheType","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/EaseChatUIKitCacheType/all":{"abstract":[],"kind":"symbol","url":"\/documentation\/shengwangchatuikit\/easechatuikitcachetype\/all","navigatorTitle":[{"kind":"identifier","text":"EaseChatUIKitCacheTypeAll"}],"title":"EaseChatUIKitCacheType.all","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/EaseChatUIKitCacheType\/all","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"all"}],"type":"topic"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"value":"EaseChatUIKitCacheTypeAll","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","value":[{"text":"EaseChatUIKitCacheTypeAll","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"EaseChatUIKitCacheTypeAll","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"EaseChatUIKitCacheType","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1EaseChatUIKitCacheType\/title"},{"op":"replace","value":[{"text":"EaseChatUIKitCacheType","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1EaseChatUIKitCacheType\/fragments"},{"value":[{"kind":"identifier","text":"EaseChatUIKitCacheType"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1EaseChatUIKitCacheType\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1EaseChatUIKitCacheType~1all\/title","value":"EaseChatUIKitCacheTypeAll","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1EaseChatUIKitCacheType~1all\/fragments","op":"replace","value":[{"kind":"identifier","text":"EaseChatUIKitCacheTypeAll"}]}]}]}