{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/EaseChatUIKitCacheType"]]},"metadata":{"modules":[{"name":"ShengwangChatUIKit"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"chat"}],"externalID":"c:@M@ShengwangChatUIKit@E@EaseChatUIKitCacheType@EaseChatUIKitCacheTypeChat","title":"EaseChatUIKitCacheType.chat","symbolKind":"case","role":"symbol","roleHeading":"Case","navigatorTitle":[{"text":"EaseChatUIKitCacheTypeChat","kind":"identifier"}]},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"chat","kind":"identifier"}]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/EaseChatUIKitCacheType\/chat","interfaceLanguage":"swift"},"kind":"symbol","variants":[{"paths":["\/documentation\/shengwangchatuikit\/easechatuikitcachetype\/chat"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/shengwangchatuikit\/easechatuikitcachetype\/chat"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/EaseChatUIKitCacheType/chat":{"navigatorTitle":[{"kind":"identifier","text":"EaseChatUIKitCacheTypeChat"}],"kind":"symbol","url":"\/documentation\/shengwangchatuikit\/easechatuikitcachetype\/chat","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"chat"}],"title":"EaseChatUIKitCacheType.chat","abstract":[],"role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/EaseChatUIKitCacheType\/chat"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/EaseChatUIKitCacheType":{"url":"\/documentation\/shengwangchatuikit\/easechatuikitcachetype","kind":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"EaseChatUIKitCacheType"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/EaseChatUIKitCacheType","title":"EaseChatUIKitCacheType","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"EaseChatUIKitCacheType","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"EaseChatUIKitCacheTypeChat"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"op":"replace","value":[{"text":"EaseChatUIKitCacheTypeChat","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"tokens":[{"kind":"identifier","text":"EaseChatUIKitCacheTypeChat"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"EaseChatUIKitCacheTypeChat","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1EaseChatUIKitCacheType~1chat\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1EaseChatUIKitCacheType~1chat\/fragments","value":[{"kind":"identifier","text":"EaseChatUIKitCacheTypeChat"}]},{"value":"EaseChatUIKitCacheType","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1EaseChatUIKitCacheType\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1EaseChatUIKitCacheType\/fragments","op":"replace","value":[{"text":"EaseChatUIKitCacheType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1EaseChatUIKitCacheType\/navigatorTitle","value":[{"kind":"identifier","text":"EaseChatUIKitCacheType"}]}]}]}