{"metadata":{"modules":[{"name":"ShengwangChatUIKit"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"user","kind":"identifier"}],"role":"symbol","title":"EaseChatUIKitCacheType.user","symbolKind":"case","roleHeading":"Case","navigatorTitle":[{"kind":"identifier","text":"EaseChatUIKitCacheTypeUser"}],"externalID":"c:@M@ShengwangChatUIKit@E@EaseChatUIKitCacheType@EaseChatUIKitCacheTypeUser"},"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/EaseChatUIKitCacheType\/user","interfaceLanguage":"swift"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/easechatuikitcachetype\/user"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/easechatuikitcachetype\/user"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"user","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/EaseChatUIKitCacheType"]]},"kind":"symbol","references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/EaseChatUIKitCacheType/user":{"navigatorTitle":[{"kind":"identifier","text":"EaseChatUIKitCacheTypeUser"}],"kind":"symbol","url":"\/documentation\/shengwangchatuikit\/easechatuikitcachetype\/user","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"user"}],"title":"EaseChatUIKitCacheType.user","abstract":[],"role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/EaseChatUIKitCacheType\/user"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/EaseChatUIKitCacheType":{"url":"\/documentation\/shengwangchatuikit\/easechatuikitcachetype","kind":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"EaseChatUIKitCacheType"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/EaseChatUIKitCacheType","title":"EaseChatUIKitCacheType","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"EaseChatUIKitCacheType","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"EaseChatUIKitCacheTypeUser"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"EaseChatUIKitCacheTypeUser","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"EaseChatUIKitCacheTypeUser","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]}},{"value":"EaseChatUIKitCacheTypeUser","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1EaseChatUIKitCacheType~1user\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1EaseChatUIKitCacheType~1user\/fragments","value":[{"text":"EaseChatUIKitCacheTypeUser","kind":"identifier"}]},{"value":"EaseChatUIKitCacheType","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1EaseChatUIKitCacheType\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1EaseChatUIKitCacheType\/fragments","value":[{"kind":"identifier","text":"EaseChatUIKitCacheType"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1EaseChatUIKitCacheType\/navigatorTitle","value":[{"text":"EaseChatUIKitCacheType","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}