{"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"roleHeading":"Instance Method","externalID":"c:@M@ShengwangChatUIKit@objc(pl)ChatService(im)markMessageAsReadWithMessageId:","symbolKind":"method","role":"symbol","modules":[{"name":"ShengwangChatUIKit"}],"navigatorTitle":[{"text":"markMessageAsReadWithMessageId:","kind":"identifier"}],"title":"markMessageAsRead(messageId:)","required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"markMessageAsRead","kind":"identifier"},{"text":"(","kind":"text"},{"text":"messageId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"markMessageAsRead"},{"text":"(","kind":"text"},{"text":"messageId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"messageId","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The id of the message."}]}]}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatService"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/chatservice\/markmessageasread(messageid:)"]},{"paths":["\/documentation\/shengwangchatuikit\/chatservice\/markmessageasread(messageid:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatService\/markMessageAsRead(messageId:)","interfaceLanguage":"swift"},"kind":"symbol","abstract":[{"text":"Mark a message as already read state.","type":"text"}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatService/markMessageAsRead(messageId:)":{"abstract":[{"text":"Mark a message as already read state.","type":"text"}],"url":"\/documentation\/shengwangchatuikit\/chatservice\/markmessageasread(messageid:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"markMessageAsRead"},{"kind":"text","text":"("},{"kind":"externalParam","text":"messageId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatService\/markMessageAsRead(messageId:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"markMessageAsReadWithMessageId:"}],"title":"markMessageAsRead(messageId:)","required":true},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatService":{"navigatorTitle":[{"kind":"identifier","text":"ChatService"}],"abstract":[],"kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatService","url":"\/documentation\/shengwangchatuikit\/chatservice","title":"ChatService","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatService"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"markMessageAsReadWithMessageId:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"markMessageAsReadWithMessageId:"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"markMessageAsReadWithMessageId:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"messageId"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"value":{"kind":"parameters","parameters":[{"name":"messageId","content":[{"type":"paragraph","inlineContent":[{"text":"The id of the message.","type":"text"}]}]}]},"path":"\/primaryContentSections\/1","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatService~1markMessageAsRead(messageId:)\/title","value":"markMessageAsReadWithMessageId:"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatService~1markMessageAsRead(messageId:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"markMessageAsReadWithMessageId:","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"ChatService","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatService\/title"},{"value":[{"kind":"identifier","text":"ChatService"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatService\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatService\/navigatorTitle","value":[{"text":"ChatService","kind":"identifier"}]}]}]}