{"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatService\/removeLocalMessage(messageId:)","interfaceLanguage":"swift"},"abstract":[{"text":"Remove a message from database.","type":"text"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeLocalMessage"},{"text":"(","kind":"text"},{"text":"messageId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]},{"parameters":[{"name":"messageId","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The id of the message."}]}]}],"kind":"parameters"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatService"]]},"metadata":{"symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"removeLocalMessage","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"messageId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":")"}],"required":true,"navigatorTitle":[{"text":"removeLocalMessageWithMessageId:","kind":"identifier"}],"role":"symbol","externalID":"c:@M@ShengwangChatUIKit@objc(pl)ChatService(im)removeLocalMessageWithMessageId:","title":"removeLocalMessage(messageId:)","roleHeading":"Instance Method","modules":[{"name":"ShengwangChatUIKit"}]},"variants":[{"paths":["\/documentation\/shengwangchatuikit\/chatservice\/removelocalmessage(messageid:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/shengwangchatuikit\/chatservice\/removelocalmessage(messageid:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatService":{"navigatorTitle":[{"kind":"identifier","text":"ChatService"}],"abstract":[],"kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatService","url":"\/documentation\/shengwangchatuikit\/chatservice","title":"ChatService","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatService"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatService/removeLocalMessage(messageId:)":{"url":"\/documentation\/shengwangchatuikit\/chatservice\/removelocalmessage(messageid:)","abstract":[{"type":"text","text":"Remove a message from database."}],"kind":"symbol","navigatorTitle":[{"text":"removeLocalMessageWithMessageId:","kind":"identifier"}],"type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatService\/removeLocalMessage(messageId:)","required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"removeLocalMessage","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"messageId"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"removeLocalMessage(messageId:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"value":"removeLocalMessageWithMessageId:","path":"\/metadata\/title","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"removeLocalMessageWithMessageId:","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"removeLocalMessageWithMessageId:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"messageId"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/primaryContentSections\/1","op":"replace","value":{"parameters":[{"name":"messageId","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The id of the message."}]}]}],"kind":"parameters"}},{"op":"replace","value":"ChatService","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatService\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatService\/fragments","value":[{"text":"ChatService","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatService\/navigatorTitle","op":"replace","value":[{"text":"ChatService","kind":"identifier"}]},{"value":"removeLocalMessageWithMessageId:","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatService~1removeLocalMessage(messageId:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatService~1removeLocalMessage(messageId:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"removeLocalMessageWithMessageId:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}