{"abstract":[{"text":"Initializes a PageContainersDialogController with the given page titles, child view controllers, and optional constraints size.","type":"text"}],"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PageContainersDialogController\/init(pageTitles:childControllers:constraintsSize:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PageContainersDialogController"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"initWithPageTitles:childControllers:constraintsSize:"}],"externalID":"c:@M@ShengwangChatUIKit@objc(cs)PageContainersDialogController(im)initWithPageTitles:childControllers:constraintsSize:","roleHeading":"Initializer","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"pageTitles"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"childControllers"},{"text":": [","kind":"text"},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"},{"text":"], ","kind":"text"},{"text":"constraintsSize","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CGSize","kind":"typeIdentifier","text":"CGSize"},{"kind":"text","text":")"}],"role":"symbol","title":"init(pageTitles:childControllers:constraintsSize:)","modules":[{"name":"ShengwangChatUIKit"}],"symbolKind":"init"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"@","kind":"attribute"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"text":" ","kind":"text"},{"text":"required","kind":"keyword"},{"kind":"text","text":" "},{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"kind":"externalParam","text":"pageTitles"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"], "},{"text":"childControllers","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"},{"text":"], ","kind":"text"},{"text":"constraintsSize","kind":"externalParam"},{"kind":"text","text":": "},{"text":"CGSize","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize"},{"text":" = .zero)","kind":"text"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"pageTitles","content":[{"type":"paragraph","inlineContent":[{"text":"An array of strings representing the titles of each page.","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"An array of UIViewControllers representing the child view controllers for each page."}],"type":"paragraph"}],"name":"childControllers"},{"name":"constraintsSize","content":[{"inlineContent":[{"type":"text","text":"An optional CGSize representing the size of the constraints for the presented view component."}],"type":"paragraph"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/pagecontainersdialogcontroller\/init(pagetitles:childcontrollers:constraintssize:)"]},{"paths":["\/documentation\/shengwangchatuikit\/pagecontainersdialogcontroller\/init(pagetitles:childcontrollers:constraintssize:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/PageContainersDialogController":{"abstract":[{"type":"text","text":"A controller that manages a page container which displays a collection of child view controllers in a paged interface."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PageContainersDialogController","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"PageContainersDialogController","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/shengwangchatuikit\/pagecontainersdialogcontroller","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PageContainersDialogController","title":"PageContainersDialogController"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/PageContainersDialogController/init(pageTitles:childControllers:constraintsSize:)":{"abstract":[{"type":"text","text":"Initializes a PageContainersDialogController with the given page titles, child view controllers, and optional constraints size."}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"pageTitles","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"childControllers"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController"},{"kind":"text","text":"], "},{"text":"constraintsSize","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"},{"text":")","kind":"text"}],"role":"symbol","navigatorTitle":[{"text":"initWithPageTitles:childControllers:constraintsSize:","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/shengwangchatuikit\/pagecontainersdialogcontroller\/init(pagetitles:childcontrollers:constraintssize:)","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PageContainersDialogController\/init(pageTitles:childControllers:constraintsSize:)","title":"init(pageTitles:childControllers:constraintsSize:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"initWithPageTitles:childControllers:constraintsSize:","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithPageTitles:childControllers:constraintsSize:"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"id","preciseIdentifier":"c:*Qo","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithPageTitles:"},{"kind":"text","text":"("},{"text":"NSArray<NSString *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"pageTitles"},{"text":" ","kind":"text"},{"text":"childControllers:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSArray<UIViewController *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"childControllers"},{"text":" ","kind":"text"},{"kind":"identifier","text":"constraintsSize:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize","text":"CGSize"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"constraintsSize"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"An array of strings representing the titles of each page.","type":"text"}]}],"name":"pageTitles"},{"name":"childControllers","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"An array of UIViewControllers representing the child view controllers for each page."}]}]},{"name":"constraintsSize","content":[{"inlineContent":[{"type":"text","text":"An optional CGSize representing the size of the constraints for the presented view component."}],"type":"paragraph"}]}]},"path":"\/primaryContentSections\/1","op":"replace"},{"op":"add","path":"\/primaryContentSections\/2","value":{"kind":"content","content":[{"type":"heading","anchor":"return-value","text":"Return Value","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"A PageContainersDialogController instance."}]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PageContainersDialogController\/title","value":"PageContainersDialogController"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PageContainersDialogController\/fragments","value":[{"text":"PageContainersDialogController","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PageContainersDialogController\/navigatorTitle","value":[{"text":"PageContainersDialogController","kind":"identifier"}]},{"op":"replace","value":"initWithPageTitles:childControllers:constraintsSize:","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PageContainersDialogController~1init(pageTitles:childControllers:constraintsSize:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PageContainersDialogController~1init(pageTitles:childControllers:constraintsSize:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithPageTitles:childControllers:constraintsSize:","kind":"identifier"}]}]}]}