{"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"presentedViewComponent"},{"kind":"text","text":": "},{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PresentedViewComponent","kind":"typeIdentifier","text":"PresentedViewComponent","preciseIdentifier":"s:18ShengwangChatUIKit22PresentedViewComponentV"},{"kind":"text","text":"?"}]}],"kind":"declarations"}],"sections":[],"abstract":[{"type":"text","text":"Inherited from "},{"code":"PresentedViewType.presentedViewComponent","type":"codeVoice"},{"text":".","type":"text"}],"metadata":{"roleHeading":"Instance Property","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"presentedViewComponent"},{"kind":"text","text":": "},{"preciseIdentifier":"s:18ShengwangChatUIKit22PresentedViewComponentV","text":"PresentedViewComponent","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"modules":[{"name":"ShengwangChatUIKit"}],"title":"presentedViewComponent","externalID":"s:18ShengwangChatUIKit30PageContainersDialogControllerC22presentedViewComponentAA09PresentediJ0VSgvp","symbolKind":"property"},"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PageContainersDialogController\/presentedViewComponent","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/pagecontainersdialogcontroller\/presentedviewcomponent"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PageContainersDialogController"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/PageContainersDialogController":{"abstract":[{"type":"text","text":"A controller that manages a page container which displays a collection of child view controllers in a paged interface."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PageContainersDialogController","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"PageContainersDialogController","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/shengwangchatuikit\/pagecontainersdialogcontroller","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PageContainersDialogController","title":"PageContainersDialogController"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/PageContainersDialogController/presentedViewComponent":{"abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"presentedViewComponent"},{"kind":"text","text":": "},{"text":"PresentedViewComponent","preciseIdentifier":"s:18ShengwangChatUIKit22PresentedViewComponentV","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"role":"symbol","kind":"symbol","type":"topic","url":"\/documentation\/shengwangchatuikit\/pagecontainersdialogcontroller\/presentedviewcomponent","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PageContainersDialogController\/presentedViewComponent","title":"presentedViewComponent"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/PresentedViewComponent":{"url":"\/documentation\/shengwangchatuikit\/presentedviewcomponent","abstract":[{"type":"text","text":"presentedView setting"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"PresentedViewComponent"}],"type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PresentedViewComponent","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"PresentedViewComponent","kind":"identifier"}],"title":"PresentedViewComponent"}},"variantOverrides":[{"patch":[{"value":"PageContainersDialogController","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PageContainersDialogController\/title","op":"replace"},{"op":"replace","value":[{"text":"PageContainersDialogController","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PageContainersDialogController\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PageContainersDialogController\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"PageContainersDialogController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}