{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/IConversationListDriver\/addActionHandler(actionHandler:)"},"abstract":[{"text":"Add UI actions handler.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"addActionHandler","kind":"identifier"},{"kind":"text","text":"("},{"text":"actionHandler","kind":"externalParam"},{"kind":"text","text":": "},{"text":"ConversationListActionEventsDelegate","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(pl)ConversationListActionEventsDelegate","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationListActionEventsDelegate"},{"text":")","kind":"text"}]}]},{"kind":"parameters","parameters":[{"name":"actionHandler","content":[{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationListActionEventsDelegate"}]}]}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/IConversationListDriver"]]},"kind":"symbol","sections":[],"metadata":{"modules":[{"name":"ShengwangChatUIKit"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"addActionHandler","kind":"identifier"},{"text":"(","kind":"text"},{"text":"actionHandler","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(pl)ConversationListActionEventsDelegate","text":"ConversationListActionEventsDelegate"},{"text":")","kind":"text"}],"role":"symbol","required":true,"title":"addActionHandler(actionHandler:)","symbolKind":"method","roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"addActionHandlerWithActionHandler:"}],"externalID":"c:@M@ShengwangChatUIKit@objc(pl)IConversationListDriver(im)addActionHandlerWithActionHandler:"},"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"paths":["\/documentation\/shengwangchatuikit\/iconversationlistdriver\/addactionhandler(actionhandler:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/iconversationlistdriver\/addactionhandler(actionhandler:)"]}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/IConversationListDriver":{"url":"\/documentation\/shengwangchatuikit\/iconversationlistdriver","title":"IConversationListDriver","role":"symbol","navigatorTitle":[{"text":"IConversationListDriver","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/IConversationListDriver","abstract":[{"text":"ConversationList view driver.","type":"text"}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"IConversationListDriver"}],"kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ConversationListActionEventsDelegate":{"title":"ConversationListActionEventsDelegate","abstract":[{"text":"Session list touch event callback proxy","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"ConversationListActionEventsDelegate"}],"url":"\/documentation\/shengwangchatuikit\/conversationlistactioneventsdelegate","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationListActionEventsDelegate"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationListActionEventsDelegate","type":"topic","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/IConversationListDriver/addActionHandler(actionHandler:)":{"required":true,"kind":"symbol","abstract":[{"text":"Add UI actions handler.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/IConversationListDriver\/addActionHandler(actionHandler:)","type":"topic","url":"\/documentation\/shengwangchatuikit\/iconversationlistdriver\/addactionhandler(actionhandler:)","title":"addActionHandler(actionHandler:)","navigatorTitle":[{"kind":"identifier","text":"addActionHandlerWithActionHandler:"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addActionHandler","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"actionHandler"},{"text":": ","kind":"text"},{"text":"ConversationListActionEventsDelegate","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(pl)ConversationListActionEventsDelegate","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"addActionHandlerWithActionHandler:","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addActionHandlerWithActionHandler:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"text":") ","kind":"text"},{"kind":"identifier","text":"addActionHandlerWithActionHandler:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Qo@M@ShengwangChatUIKit@objc(pl)ConversationListActionEventsDelegate","text":"id<ConversationListActionEventsDelegate>","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"actionHandler"},{"kind":"text","text":";"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"kind":"parameters","parameters":[{"name":"actionHandler","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"isActive":true,"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationListActionEventsDelegate","type":"reference"}]}]}]},"path":"\/primaryContentSections\/1","op":"replace"},{"value":"IConversationListDriver","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1IConversationListDriver\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1IConversationListDriver\/fragments","value":[{"kind":"identifier","text":"IConversationListDriver"}]},{"op":"replace","value":[{"text":"IConversationListDriver","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1IConversationListDriver\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationListActionEventsDelegate\/title","op":"replace","value":"ConversationListActionEventsDelegate"},{"value":[{"text":"ConversationListActionEventsDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationListActionEventsDelegate\/fragments"},{"op":"replace","value":[{"text":"ConversationListActionEventsDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationListActionEventsDelegate\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1IConversationListDriver~1addActionHandler(actionHandler:)\/title","op":"replace","value":"addActionHandlerWithActionHandler:"},{"value":[{"text":"- ","kind":"text"},{"text":"addActionHandlerWithActionHandler:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1IConversationListDriver~1addActionHandler(actionHandler:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}