{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/IConversationListDriver"]]},"metadata":{"roleHeading":"Instance Method","externalID":"c:@M@ShengwangChatUIKit@objc(pl)IConversationListDriver(im)appendThenRefreshWithInfos:","navigatorTitle":[{"kind":"identifier","text":"appendThenRefreshWithInfos:"}],"title":"appendThenRefresh(infos:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"appendThenRefresh"},{"kind":"text","text":"("},{"kind":"externalParam","text":"infos"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"ConversationInfo","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)ConversationInfo"},{"kind":"text","text":"])"}],"symbolKind":"method","required":true,"role":"symbol","modules":[{"name":"ShengwangChatUIKit"}]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"appendThenRefresh","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"infos"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)ConversationInfo","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationInfo","text":"ConversationInfo"},{"kind":"text","text":"])"}],"languages":["swift"],"platforms":["iOS"]}]},{"parameters":[{"name":"infos","content":[{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"isActive":true,"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationInfo","type":"reference"},{"text":" object.","type":"text"}]}]}],"kind":"parameters"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/IConversationListDriver\/appendThenRefresh(infos:)"},"sections":[],"abstract":[{"type":"text","text":"When you receive a lot of messages from new contacts, you can call this method for data transfer."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/iconversationlistdriver\/appendthenrefresh(infos:)"]},{"paths":["\/documentation\/shengwangchatuikit\/iconversationlistdriver\/appendthenrefresh(infos:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/IConversationListDriver":{"url":"\/documentation\/shengwangchatuikit\/iconversationlistdriver","title":"IConversationListDriver","role":"symbol","navigatorTitle":[{"text":"IConversationListDriver","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/IConversationListDriver","abstract":[{"text":"ConversationList view driver.","type":"text"}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"IConversationListDriver"}],"kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ConversationInfo":{"title":"ConversationInfo","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ConversationInfo","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/conversationinfo","role":"symbol","abstract":[],"type":"topic","navigatorTitle":[{"text":"ConversationInfo","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationInfo"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/IConversationListDriver/appendThenRefresh(infos:)":{"required":true,"kind":"symbol","abstract":[{"text":"When you receive a lot of messages from new contacts, you can call this method for data transfer.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/IConversationListDriver\/appendThenRefresh(infos:)","type":"topic","title":"appendThenRefresh(infos:)","url":"\/documentation\/shengwangchatuikit\/iconversationlistdriver\/appendthenrefresh(infos:)","navigatorTitle":[{"kind":"identifier","text":"appendThenRefreshWithInfos:"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"appendThenRefresh","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"infos"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)ConversationInfo","text":"ConversationInfo","kind":"typeIdentifier"},{"text":"])","kind":"text"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"appendThenRefreshWithInfos:"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"appendThenRefreshWithInfos:"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"text":"appendThenRefreshWithInfos:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier","text":"NSArray<ConversationInfo *>"},{"text":" *) ","kind":"text"},{"text":"infos","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace"},{"op":"replace","path":"\/primaryContentSections\/1","value":{"parameters":[{"name":"infos","content":[{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationInfo","type":"reference","isActive":true},{"type":"text","text":" object."}]}]}],"kind":"parameters"}},{"value":"IConversationListDriver","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1IConversationListDriver\/title","op":"replace"},{"value":[{"kind":"identifier","text":"IConversationListDriver"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1IConversationListDriver\/fragments"},{"value":[{"text":"IConversationListDriver","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1IConversationListDriver\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationInfo\/title","value":"ConversationInfo"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationInfo\/fragments","value":[{"text":"ConversationInfo","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationInfo\/navigatorTitle","value":[{"text":"ConversationInfo","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1IConversationListDriver~1appendThenRefresh(infos:)\/title","value":"appendThenRefreshWithInfos:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1IConversationListDriver~1appendThenRefresh(infos:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"appendThenRefreshWithInfos:"}]}]}]}