{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/IConversationListDriver"]]},"metadata":{"roleHeading":"Instance Method","role":"symbol","navigatorTitle":[{"text":"occurError","kind":"identifier"}],"externalID":"c:@M@ShengwangChatUIKit@objc(pl)IConversationListDriver(im)occurError","symbolKind":"method","required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"occurError","kind":"identifier"},{"text":"()","kind":"text"}],"title":"occurError()","modules":[{"name":"ShengwangChatUIKit"}]},"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/IConversationListDriver\/occurError()","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"occurError"},{"text":"()","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"abstract":[{"type":"text","text":"When fetch list occur error."}],"sections":[],"variants":[{"paths":["\/documentation\/shengwangchatuikit\/iconversationlistdriver\/occurerror()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/iconversationlistdriver\/occurerror()"]}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/IConversationListDriver":{"url":"\/documentation\/shengwangchatuikit\/iconversationlistdriver","title":"IConversationListDriver","role":"symbol","navigatorTitle":[{"text":"IConversationListDriver","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/IConversationListDriver","abstract":[{"text":"ConversationList view driver.","type":"text"}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"IConversationListDriver"}],"kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/IConversationListDriver/occurError()":{"type":"topic","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"occurError","kind":"identifier"},{"text":"()","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/IConversationListDriver\/occurError()","url":"\/documentation\/shengwangchatuikit\/iconversationlistdriver\/occurerror()","required":true,"abstract":[{"type":"text","text":"When fetch list occur error."}],"navigatorTitle":[{"text":"occurError","kind":"identifier"}],"title":"occurError()"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"occurError","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"occurError","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"occurError","kind":"identifier"},{"kind":"text","text":";"}]}]},"op":"replace"},{"value":"IConversationListDriver","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1IConversationListDriver\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1IConversationListDriver\/fragments","op":"replace","value":[{"kind":"identifier","text":"IConversationListDriver"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1IConversationListDriver\/navigatorTitle","value":[{"kind":"identifier","text":"IConversationListDriver"}]},{"op":"replace","value":"occurError","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1IConversationListDriver~1occurError()\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1IConversationListDriver~1occurError()\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"occurError"}]}]}]}