{"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/mentionupdate\/delete"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/mentionupdate\/delete"]}],"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MentionUpdate\/delete","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MentionUpdate"]]},"metadata":{"roleHeading":"Case","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"delete","kind":"identifier"}],"modules":[{"name":"ShengwangChatUIKit"}],"navigatorTitle":[{"text":"MentionUpdateDelete","kind":"identifier"}],"externalID":"c:@M@ShengwangChatUIKit@E@MentionUpdate@MentionUpdateDelete","title":"MentionUpdate.delete","symbolKind":"case"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"delete","kind":"identifier"}],"languages":["swift"]}]}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MentionUpdate/delete":{"navigatorTitle":[{"kind":"identifier","text":"MentionUpdateDelete"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"delete","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/mentionupdate\/delete","abstract":[],"role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MentionUpdate\/delete","title":"MentionUpdate.delete","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MentionUpdate":{"type":"topic","navigatorTitle":[{"text":"MentionUpdate","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"MentionUpdate","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MentionUpdate","title":"MentionUpdate","url":"\/documentation\/shengwangchatuikit\/mentionupdate","abstract":[],"kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","value":"MentionUpdateDelete","op":"replace"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"MentionUpdateDelete","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"MentionUpdateDelete","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MentionUpdate~1delete\/title","op":"replace","value":"MentionUpdateDelete"},{"op":"replace","value":[{"text":"MentionUpdateDelete","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MentionUpdate~1delete\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MentionUpdate\/title","op":"replace","value":"MentionUpdate"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MentionUpdate\/fragments","op":"replace","value":[{"kind":"identifier","text":"MentionUpdate"}]},{"op":"replace","value":[{"text":"MentionUpdate","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MentionUpdate\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}