{"metadata":{"roleHeading":"Instance Method","title":"onMessageWillSendFillExtensionInfo()","externalID":"c:@M@ShengwangChatUIKit@objc(pl)MessageListDriverEventsListener(im)onMessageWillSendFillExtensionInfo","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onMessageWillSendFillExtensionInfo"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","text":"Dictionary","preciseIdentifier":"s:SD"},{"text":"<","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"keyword","text":"Any"},{"kind":"text","text":">"}],"required":true,"symbolKind":"method","modules":[{"name":"ShengwangChatUIKit"}],"navigatorTitle":[{"text":"onMessageWillSendFillExtensionInfo","kind":"identifier"}],"role":"symbol"},"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListDriverEventsListener"]]},"abstract":[{"text":"Insert extension info before sending message.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/messagelistdrivereventslistener\/onmessagewillsendfillextensioninfo()"]},{"paths":["\/documentation\/shengwangchatuikit\/messagelistdrivereventslistener\/onmessagewillsendfillextensioninfo()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListDriverEventsListener\/onMessageWillSendFillExtensionInfo()"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"onMessageWillSendFillExtensionInfo","kind":"identifier"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:SD","text":"Dictionary","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":">"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"content","content":[{"level":2,"text":"Return Value","type":"heading","anchor":"return-value"},{"inlineContent":[{"type":"text","text":"Extension info."}],"type":"paragraph"}]}],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageListDriverEventsListener":{"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"MessageListDriverEventsListener","kind":"identifier"}],"type":"topic","abstract":[],"role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListDriverEventsListener","title":"MessageListDriverEventsListener","navigatorTitle":[{"text":"MessageListDriverEventsListener","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/messagelistdrivereventslistener"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageListDriverEventsListener/onMessageWillSendFillExtensionInfo()":{"required":true,"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListDriverEventsListener\/onMessageWillSendFillExtensionInfo()","type":"topic","abstract":[{"text":"Insert extension info before sending message.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"onMessageWillSendFillExtensionInfo","kind":"identifier"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","text":"Dictionary","preciseIdentifier":"s:SD"},{"kind":"text","text":"<"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"Any","kind":"keyword"},{"kind":"text","text":">"}],"url":"\/documentation\/shengwangchatuikit\/messagelistdrivereventslistener\/onmessagewillsendfillextensioninfo()","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"onMessageWillSendFillExtensionInfo"}],"kind":"symbol","title":"onMessageWillSendFillExtensionInfo()"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","value":"onMessageWillSendFillExtensionInfo","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"onMessageWillSendFillExtensionInfo"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"NSDictionary<NSString *,id>","preciseIdentifier":"c:Q$objc(cs)NSDictionary"},{"text":" *) ","kind":"text"},{"text":"onMessageWillSendFillExtensionInfo","kind":"identifier"},{"kind":"text","text":";"}]}]},"op":"replace"},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"content","content":[{"type":"heading","anchor":"return-value","text":"Return Value","level":2},{"type":"paragraph","inlineContent":[{"text":"Extension info.","type":"text"}]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListDriverEventsListener\/title","op":"replace","value":"MessageListDriverEventsListener"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListDriverEventsListener\/fragments","value":[{"kind":"identifier","text":"MessageListDriverEventsListener"}]},{"value":[{"text":"MessageListDriverEventsListener","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListDriverEventsListener\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListDriverEventsListener~1onMessageWillSendFillExtensionInfo()\/title","op":"replace","value":"onMessageWillSendFillExtensionInfo"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListDriverEventsListener~1onMessageWillSendFillExtensionInfo()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onMessageWillSendFillExtensionInfo"}],"op":"replace"}]}]}