{"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListDriverEventsListener\/onMessageMultiSelectBarClicked(operation:)","interfaceLanguage":"swift"},"abstract":[{"text":"When you click a message list multi select bar item,the method will call.","type":"text"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onMessageMultiSelectBarClicked"},{"text":"(","kind":"text"},{"text":"operation","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MessageMultiSelectedBottomBarOperation","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageMultiSelectedBottomBarOperation","preciseIdentifier":"c:@M@ShengwangChatUIKit@E@MessageMultiSelectedBottomBarOperation"},{"kind":"text","text":")"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"operation","content":[{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageMultiSelectedBottomBarOperation"}]}]}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListDriverEventsListener"]]},"sections":[],"metadata":{"externalID":"c:@M@ShengwangChatUIKit@objc(pl)MessageListDriverEventsListener(im)onMessageMultiSelectBarClickedWithOperation:","required":true,"navigatorTitle":[{"text":"onMessageMultiSelectBarClickedWithOperation:","kind":"identifier"}],"role":"symbol","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onMessageMultiSelectBarClicked"},{"kind":"text","text":"("},{"text":"operation","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MessageMultiSelectedBottomBarOperation","preciseIdentifier":"c:@M@ShengwangChatUIKit@E@MessageMultiSelectedBottomBarOperation","kind":"typeIdentifier"},{"kind":"text","text":")"}],"title":"onMessageMultiSelectBarClicked(operation:)","modules":[{"name":"ShengwangChatUIKit"}],"symbolKind":"method"},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/messagelistdrivereventslistener\/onmessagemultiselectbarclicked(operation:)"]},{"paths":["\/documentation\/shengwangchatuikit\/messagelistdrivereventslistener\/onmessagemultiselectbarclicked(operation:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageListDriverEventsListener":{"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"MessageListDriverEventsListener","kind":"identifier"}],"type":"topic","abstract":[],"role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListDriverEventsListener","title":"MessageListDriverEventsListener","navigatorTitle":[{"text":"MessageListDriverEventsListener","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/messagelistdrivereventslistener"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageListDriverEventsListener/onMessageMultiSelectBarClicked(operation:)":{"role":"symbol","abstract":[{"text":"When you click a message list multi select bar item,the method will call.","type":"text"}],"kind":"symbol","title":"onMessageMultiSelectBarClicked(operation:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onMessageMultiSelectBarClicked","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"operation"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@E@MessageMultiSelectedBottomBarOperation","text":"MessageMultiSelectedBottomBarOperation","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListDriverEventsListener\/onMessageMultiSelectBarClicked(operation:)","navigatorTitle":[{"text":"onMessageMultiSelectBarClickedWithOperation:","kind":"identifier"}],"required":true,"type":"topic","url":"\/documentation\/shengwangchatuikit\/messagelistdrivereventslistener\/onmessagemultiselectbarclicked(operation:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageMultiSelectedBottomBarOperation":{"title":"MessageMultiSelectedBottomBarOperation","url":"\/documentation\/shengwangchatuikit\/messagemultiselectedbottombaroperation","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageMultiSelectedBottomBarOperation","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"MessageMultiSelectedBottomBarOperation","kind":"identifier"}],"kind":"symbol","role":"symbol","abstract":[],"navigatorTitle":[{"text":"MessageMultiSelectedBottomBarOperation","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"value":"onMessageMultiSelectBarClickedWithOperation:","op":"replace","path":"\/metadata\/title"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"onMessageMultiSelectBarClickedWithOperation:"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"text":"onMessageMultiSelectBarClickedWithOperation:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@E@MessageMultiSelectedBottomBarOperation","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageMultiSelectedBottomBarOperation","text":"MessageMultiSelectedBottomBarOperation"},{"text":") ","kind":"text"},{"text":"operation","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"operation","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"reference","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageMultiSelectedBottomBarOperation","isActive":true}]}]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListDriverEventsListener\/title","op":"replace","value":"MessageListDriverEventsListener"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListDriverEventsListener\/fragments","value":[{"text":"MessageListDriverEventsListener","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListDriverEventsListener\/navigatorTitle","value":[{"kind":"identifier","text":"MessageListDriverEventsListener"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListDriverEventsListener~1onMessageMultiSelectBarClicked(operation:)\/title","value":"onMessageMultiSelectBarClickedWithOperation:"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListDriverEventsListener~1onMessageMultiSelectBarClicked(operation:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"onMessageMultiSelectBarClickedWithOperation:","kind":"identifier"}]},{"value":"MessageMultiSelectedBottomBarOperation","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageMultiSelectedBottomBarOperation\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageMultiSelectedBottomBarOperation\/fragments","value":[{"kind":"identifier","text":"MessageMultiSelectedBottomBarOperation"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageMultiSelectedBottomBarOperation\/navigatorTitle","value":[{"text":"MessageMultiSelectedBottomBarOperation","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}