{"metadata":{"required":true,"navigatorTitle":[{"text":"onMessageAvatarClickedWithUser:","kind":"identifier"}],"externalID":"c:@M@ShengwangChatUIKit@objc(pl)MessageListDriverEventsListener(im)onMessageAvatarClickedWithUser:","title":"onMessageAvatarClicked(user:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onMessageAvatarClicked","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"user"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(pl)ChatUserProfileProtocol","text":"ChatUserProfileProtocol","kind":"typeIdentifier"},{"kind":"text","text":")"}],"modules":[{"name":"ShengwangChatUIKit"}],"role":"symbol","symbolKind":"method","roleHeading":"Instance Method"},"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListDriverEventsListener"]]},"variants":[{"paths":["\/documentation\/shengwangchatuikit\/messagelistdrivereventslistener\/onmessageavatarclicked(user:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/messagelistdrivereventslistener\/onmessageavatarclicked(user:)"]}],"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListDriverEventsListener\/onMessageAvatarClicked(user:)","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onMessageAvatarClicked"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"user"},{"text":": ","kind":"text"},{"text":"ChatUserProfileProtocol","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(pl)ChatUserProfileProtocol","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatUserProfileProtocol"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatUserProfileProtocol":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatUserProfileProtocol","abstract":[{"text":"Profile of the ChatUIKit display needed.","type":"text"}],"title":"ChatUserProfileProtocol","type":"topic","kind":"symbol","navigatorTitle":[{"text":"ChatUserProfileProtocol","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"ChatUserProfileProtocol","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/chatuserprofileprotocol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageListDriverEventsListener/onMessageAvatarClicked(user:)":{"role":"symbol","navigatorTitle":[{"text":"onMessageAvatarClickedWithUser:","kind":"identifier"}],"title":"onMessageAvatarClicked(user:)","url":"\/documentation\/shengwangchatuikit\/messagelistdrivereventslistener\/onmessageavatarclicked(user:)","kind":"symbol","required":true,"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"onMessageAvatarClicked"},{"text":"(","kind":"text"},{"text":"user","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(pl)ChatUserProfileProtocol","kind":"typeIdentifier","text":"ChatUserProfileProtocol"},{"kind":"text","text":")"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListDriverEventsListener\/onMessageAvatarClicked(user:)","type":"topic","abstract":[]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageListDriverEventsListener":{"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"MessageListDriverEventsListener","kind":"identifier"}],"type":"topic","abstract":[],"role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListDriverEventsListener","title":"MessageListDriverEventsListener","navigatorTitle":[{"text":"MessageListDriverEventsListener","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/messagelistdrivereventslistener"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"onMessageAvatarClickedWithUser:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"text":"- ","kind":"text"},{"text":"onMessageAvatarClickedWithUser:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"onMessageAvatarClickedWithUser:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id<ChatUserProfileProtocol>","preciseIdentifier":"c:Qo@M@ShengwangChatUIKit@objc(pl)ChatUserProfileProtocol","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"user"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","value":"ChatUserProfileProtocol","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatUserProfileProtocol\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatUserProfileProtocol\/fragments","value":[{"kind":"identifier","text":"ChatUserProfileProtocol"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatUserProfileProtocol\/navigatorTitle","value":[{"text":"ChatUserProfileProtocol","kind":"identifier"}]},{"value":"onMessageAvatarClickedWithUser:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListDriverEventsListener~1onMessageAvatarClicked(user:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListDriverEventsListener~1onMessageAvatarClicked(user:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"onMessageAvatarClickedWithUser:"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListDriverEventsListener\/title","value":"MessageListDriverEventsListener","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListDriverEventsListener\/fragments","value":[{"kind":"identifier","text":"MessageListDriverEventsListener"}]},{"value":[{"kind":"identifier","text":"MessageListDriverEventsListener"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListDriverEventsListener\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}