{"metadata":{"modules":[{"name":"ShengwangChatUIKit"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"onUserQuitTopic","kind":"identifier"},{"text":"()","kind":"text"}],"role":"symbol","title":"onUserQuitTopic()","symbolKind":"method","roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"onUserQuitTopic"}],"externalID":"c:@M@ShengwangChatUIKit@objc(pl)MessageListDriverEventsListener(im)onUserQuitTopic"},"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListDriverEventsListener\/onUserQuitTopic()","interfaceLanguage":"swift"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/messagelistdrivereventslistener\/onuserquittopic()"]},{"paths":["\/documentation\/shengwangchatuikit\/messagelistdrivereventslistener\/onuserquittopic()"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"When received quit signal form other device on the chat thread.","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onUserQuitTopic"},{"text":"()","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListDriverEventsListener"]]},"kind":"symbol","references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageListDriverEventsListener":{"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"MessageListDriverEventsListener","kind":"identifier"}],"type":"topic","abstract":[],"role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListDriverEventsListener","title":"MessageListDriverEventsListener","navigatorTitle":[{"text":"MessageListDriverEventsListener","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/messagelistdrivereventslistener"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageListDriverEventsListener/onUserQuitTopic()":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListDriverEventsListener\/onUserQuitTopic()","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"When received quit signal form other device on the chat thread."}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onUserQuitTopic"},{"text":"()","kind":"text"}],"navigatorTitle":[{"text":"onUserQuitTopic","kind":"identifier"}],"title":"onUserQuitTopic()","role":"symbol","url":"\/documentation\/shengwangchatuikit\/messagelistdrivereventslistener\/onuserquittopic()"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"onUserQuitTopic","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onUserQuitTopic"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"onUserQuitTopic","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListDriverEventsListener\/title","value":"MessageListDriverEventsListener"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListDriverEventsListener\/fragments","op":"replace","value":[{"text":"MessageListDriverEventsListener","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"MessageListDriverEventsListener"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListDriverEventsListener\/navigatorTitle"},{"value":"onUserQuitTopic","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListDriverEventsListener~1onUserQuitTopic()\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListDriverEventsListener~1onUserQuitTopic()\/fragments","value":[{"kind":"text","text":"- "},{"text":"onUserQuitTopic","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}