{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(bindWithDriver:searchMessageId:) ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"bindDriver","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"driver"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"IMessageListViewDriver","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/IMessageListViewDriver","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(pl)IMessageListViewDriver"},{"kind":"text","text":", "},{"text":"searchMessageId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":" = \"\")"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"driver","content":[{"inlineContent":[{"text":"","type":"text"},{"type":"reference","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/IMessageListViewDriver","isActive":true}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"If you want to search a message, you can pass id of the message."}],"type":"paragraph"}],"name":"searchMessageId"}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/messagelistviewmodel\/binddriver(driver:searchmessageid:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/messagelistviewmodel\/binddriver(driver:searchmessageid:)"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"roleHeading":"Instance Method","role":"symbol","navigatorTitle":[{"text":"bindWithDriver:searchMessageId:","kind":"identifier"}],"externalID":"c:@M@ShengwangChatUIKit@objc(cs)MessageListViewModel(im)bindWithDriver:searchMessageId:","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bindDriver"},{"kind":"text","text":"("},{"text":"driver","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(pl)IMessageListViewDriver","text":"IMessageListViewDriver"},{"text":", ","kind":"text"},{"text":"searchMessageId","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":")","kind":"text"}],"title":"bindDriver(driver:searchMessageId:)","modules":[{"name":"ShengwangChatUIKit"}]},"abstract":[{"type":"text","text":"Bind "},{"isActive":true,"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/IMessageListViewDriver","type":"reference"}],"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewModel"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewModel\/bindDriver(driver:searchMessageId:)"},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageListViewModel/bindDriver(driver:searchMessageId:)":{"abstract":[{"text":"Bind ","type":"text"},{"isActive":true,"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/IMessageListViewDriver","type":"reference"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bindDriver"},{"kind":"text","text":"("},{"text":"driver","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(pl)IMessageListViewDriver","text":"IMessageListViewDriver"},{"text":", ","kind":"text"},{"text":"searchMessageId","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"role":"symbol","type":"topic","url":"\/documentation\/shengwangchatuikit\/messagelistviewmodel\/binddriver(driver:searchmessageid:)","title":"bindDriver(driver:searchMessageId:)","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewModel\/bindDriver(driver:searchMessageId:)","navigatorTitle":[{"text":"bindWithDriver:searchMessageId:","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/IMessageListViewDriver":{"kind":"symbol","role":"symbol","type":"topic","abstract":[],"navigatorTitle":[{"text":"IMessageListViewDriver","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"IMessageListViewDriver","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/imessagelistviewdriver","title":"IMessageListViewDriver","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/IMessageListViewDriver"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageListViewModel":{"url":"\/documentation\/shengwangchatuikit\/messagelistviewmodel","title":"MessageListViewModel","role":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewModel","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MessageListViewModel"}],"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MessageListViewModel"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"bindWithDriver:searchMessageId:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"bindWithDriver:searchMessageId:"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"text":"bindWithDriver:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@ShengwangChatUIKit@objc(pl)IMessageListViewDriver","text":"id<IMessageListViewDriver>"},{"text":") ","kind":"text"},{"text":"driver","kind":"internalParam"},{"kind":"text","text":" "},{"text":"searchMessageId:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"searchMessageId","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"}},{"value":{"kind":"parameters","parameters":[{"name":"driver","content":[{"inlineContent":[{"type":"text","text":""},{"type":"reference","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/IMessageListViewDriver","isActive":true}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"If you want to search a message, you can pass id of the message."}],"type":"paragraph"}],"name":"searchMessageId"}]},"op":"replace","path":"\/primaryContentSections\/1"},{"op":"replace","value":"bindWithDriver:searchMessageId:","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewModel~1bindDriver(driver:searchMessageId:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewModel~1bindDriver(driver:searchMessageId:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"bindWithDriver:searchMessageId:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1IMessageListViewDriver\/title","value":"IMessageListViewDriver"},{"value":[{"kind":"identifier","text":"IMessageListViewDriver"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1IMessageListViewDriver\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1IMessageListViewDriver\/navigatorTitle","value":[{"kind":"identifier","text":"IMessageListViewDriver"}]},{"op":"replace","value":"MessageListViewModel","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewModel\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewModel\/fragments","value":[{"kind":"identifier","text":"MessageListViewModel"}]},{"op":"replace","value":[{"text":"MessageListViewModel","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewModel\/navigatorTitle"}]}]}