{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewModel"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"bindPinContainerDriver"},{"text":"(","kind":"text"},{"text":"driver","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(pl)IPinnedMessagesContainerDriver","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/IPinnedMessagesContainerDriver","text":"IPinnedMessagesContainerDriver"},{"kind":"text","text":")"}]}],"kind":"declarations"}],"metadata":{"navigatorTitle":[{"text":"bindPinContainerDriverWithDriver:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"bindPinContainerDriver","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"driver"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IPinnedMessagesContainerDriver","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(pl)IPinnedMessagesContainerDriver"},{"kind":"text","text":")"}],"externalID":"c:@M@ShengwangChatUIKit@objc(cs)MessageListViewModel(im)bindPinContainerDriverWithDriver:","role":"symbol","roleHeading":"Instance Method","symbolKind":"method","modules":[{"name":"ShengwangChatUIKit"}],"title":"bindPinContainerDriver(driver:)"},"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewModel\/bindPinContainerDriver(driver:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/messagelistviewmodel\/bindpincontainerdriver(driver:)"]},{"paths":["\/documentation\/shengwangchatuikit\/messagelistviewmodel\/bindpincontainerdriver(driver:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageListViewModel/bindPinContainerDriver(driver:)":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewModel\/bindPinContainerDriver(driver:)","title":"bindPinContainerDriver(driver:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"bindPinContainerDriver","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"driver"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IPinnedMessagesContainerDriver","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(pl)IPinnedMessagesContainerDriver"},{"text":")","kind":"text"}],"role":"symbol","url":"\/documentation\/shengwangchatuikit\/messagelistviewmodel\/bindpincontainerdriver(driver:)","navigatorTitle":[{"kind":"identifier","text":"bindPinContainerDriverWithDriver:"}],"type":"topic","abstract":[],"kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/IPinnedMessagesContainerDriver":{"abstract":[],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"IPinnedMessagesContainerDriver"}],"role":"symbol","navigatorTitle":[{"text":"IPinnedMessagesContainerDriver","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/shengwangchatuikit\/ipinnedmessagescontainerdriver","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/IPinnedMessagesContainerDriver","title":"IPinnedMessagesContainerDriver"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageListViewModel":{"url":"\/documentation\/shengwangchatuikit\/messagelistviewmodel","title":"MessageListViewModel","role":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewModel","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MessageListViewModel"}],"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MessageListViewModel"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","value":"bindPinContainerDriverWithDriver:","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"bindPinContainerDriverWithDriver:"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"bindPinContainerDriverWithDriver:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id<IPinnedMessagesContainerDriver>","preciseIdentifier":"c:Qo@M@ShengwangChatUIKit@objc(pl)IPinnedMessagesContainerDriver","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"driver"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"bindPinContainerDriverWithDriver:","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewModel~1bindPinContainerDriver(driver:)\/title","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"bindPinContainerDriverWithDriver:"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewModel~1bindPinContainerDriver(driver:)\/fragments"},{"value":"IPinnedMessagesContainerDriver","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1IPinnedMessagesContainerDriver\/title"},{"value":[{"kind":"identifier","text":"IPinnedMessagesContainerDriver"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1IPinnedMessagesContainerDriver\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1IPinnedMessagesContainerDriver\/navigatorTitle","op":"replace","value":[{"text":"IPinnedMessagesContainerDriver","kind":"identifier"}]},{"op":"replace","value":"MessageListViewModel","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewModel\/title"},{"op":"replace","value":[{"text":"MessageListViewModel","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewModel\/fragments"},{"value":[{"kind":"identifier","text":"MessageListViewModel"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewModel\/navigatorTitle","op":"replace"}]}]}