{"sections":[],"metadata":{"title":"ChatResponseListener Implementations","modules":[{"name":"ShengwangChatUIKit"}],"role":"collectionGroup","roleHeading":"API Collection"},"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewModel\/ChatResponseListener-Implementations","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewModel"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/messagelistviewmodel\/chatresponselistener-implementations"]},{"paths":["\/documentation\/shengwangchatuikit\/messagelistviewmodel\/chatresponselistener-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"article","schemaVersion":{"major":0,"minor":3,"patch":0},"topicSections":[{"anchor":"Instance-Methods","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewModel\/messagesAlreadyRead(conversationId:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewModel\/onCMDMessageDidReceived(message:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewModel\/onMessageAttachmentStatusChanged(message:error:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewModel\/onMessageDidEdited(message:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewModel\/onMessageDidRecalled(recallInfo:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewModel\/onMessageDidReceived(message:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewModel\/onMessageReactionChanged(changes:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewModel\/onMessageStatusDidChanged(message:status:error:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewModel\/onMessageStickiedTop(conversationId:messageId:operation:info:)"],"title":"Instance Methods","generated":true}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageListViewModel/onCMDMessageDidReceived(message:)":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewModel\/onCMDMessageDidReceived(message:)","kind":"symbol","title":"onCMDMessageDidReceived(message:)","url":"\/documentation\/shengwangchatuikit\/messagelistviewmodel\/oncmdmessagedidreceived(message:)","type":"topic","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onCMDMessageDidReceived","kind":"identifier"},{"text":"(","kind":"text"},{"text":"message","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChatMessage","preciseIdentifier":"s:18ShengwangChatUIKit0B7Messagea"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"onCMDMessageDidReceivedWithMessage:"}],"abstract":[{"type":"text","text":"When cmd message received."}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageListViewModel/onMessageStickiedTop(conversationId:messageId:operation:info:)":{"kind":"symbol","url":"\/documentation\/shengwangchatuikit\/messagelistviewmodel\/onmessagestickiedtop(conversationid:messageid:operation:info:)","role":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onMessageStickiedTop"},{"kind":"text","text":"("},{"text":"conversationId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"messageId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"operation","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:18ShengwangChatUIKit19MessagePinOperationa","text":"MessagePinOperation","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"info","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:18ShengwangChatUIKit14MessagePinInfoa","text":"MessagePinInfo","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewModel\/onMessageStickiedTop(conversationId:messageId:operation:info:)","title":"onMessageStickiedTop(conversationId:messageId:operation:info:)","navigatorTitle":[{"text":"onMessageStickiedTopWithConversationId:messageId:operation:info:","kind":"identifier"}],"abstract":[{"text":"When message stickied top the method called.","type":"text"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageListViewModel/onMessageDidRecalled(recallInfo:)":{"kind":"symbol","url":"\/documentation\/shengwangchatuikit\/messagelistviewmodel\/onmessagedidrecalled(recallinfo:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onMessageDidRecalled","kind":"identifier"},{"kind":"text","text":"("},{"text":"recallInfo","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit10RecallInfoa","text":"RecallInfo"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"onMessageDidRecalledWithRecallInfo:","kind":"identifier"}],"abstract":[{"type":"text","text":"When message recalled."}],"type":"topic","title":"onMessageDidRecalled(recallInfo:)","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewModel\/onMessageDidRecalled(recallInfo:)","role":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageListViewModel/messagesAlreadyRead(conversationId:)":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewModel\/messagesAlreadyRead(conversationId:)","navigatorTitle":[{"text":"messagesAlreadyReadWithConversationId:","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/messagelistviewmodel\/messagesalreadyread(conversationid:)","type":"topic","abstract":[{"type":"text","text":"Update messages read state on received channel ack."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"messagesAlreadyRead"},{"kind":"text","text":"("},{"kind":"externalParam","text":"conversationId"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"title":"messagesAlreadyRead(conversationId:)","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageListViewModel/onMessageDidEdited(message:)":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewModel\/onMessageDidEdited(message:)","abstract":[{"text":"When message edited.","type":"text"}],"navigatorTitle":[{"text":"onMessageDidEditedWithMessage:","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/shengwangchatuikit\/messagelistviewmodel\/onmessagedidedited(message:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"onMessageDidEdited","kind":"identifier"},{"kind":"text","text":"("},{"text":"message","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"ChatMessage","preciseIdentifier":"s:18ShengwangChatUIKit0B7Messagea"},{"kind":"text","text":")"}],"title":"onMessageDidEdited(message:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageListViewModel":{"url":"\/documentation\/shengwangchatuikit\/messagelistviewmodel","title":"MessageListViewModel","role":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewModel","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MessageListViewModel"}],"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MessageListViewModel"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageListViewModel/onMessageStatusDidChanged(message:status:error:)":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewModel\/onMessageStatusDidChanged(message:status:error:)","navigatorTitle":[{"text":"onMessageStatusDidChangedWithMessage:status:error:","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/messagelistviewmodel\/onmessagestatusdidchanged(message:status:error:)","type":"topic","abstract":[{"type":"text","text":"When status of message changed."}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onMessageStatusDidChanged"},{"text":"(","kind":"text"},{"text":"message","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ChatMessage","kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit0B7Messagea"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"status"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@E@ChatMessageStatus","text":"ChatMessageStatus"},{"text":", ","kind":"text"},{"text":"error","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:18ShengwangChatUIKit0B5Errora","text":"ChatError","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"title":"onMessageStatusDidChanged(message:status:error:)","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageListViewModel/onMessageAttachmentStatusChanged(message:error:)":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewModel\/onMessageAttachmentStatusChanged(message:error:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"onMessageAttachmentStatusChangedWithMessage:error:"}],"title":"onMessageAttachmentStatusChanged(message:error:)","kind":"symbol","url":"\/documentation\/shengwangchatuikit\/messagelistviewmodel\/onmessageattachmentstatuschanged(message:error:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"onMessageAttachmentStatusChanged","kind":"identifier"},{"text":"(","kind":"text"},{"text":"message","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ChatMessage","kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit0B7Messagea"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"error"},{"text":": ","kind":"text"},{"text":"ChatError","preciseIdentifier":"s:18ShengwangChatUIKit0B5Errora","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"type":"topic","abstract":[{"type":"text","text":"When status of message attachment changed."}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageListViewModel/onMessageReactionChanged(changes:)":{"title":"onMessageReactionChanged(changes:)","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewModel\/onMessageReactionChanged(changes:)","url":"\/documentation\/shengwangchatuikit\/messagelistviewmodel\/onmessagereactionchanged(changes:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onMessageReactionChanged"},{"kind":"text","text":"("},{"kind":"externalParam","text":"changes"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit21MessageReactionChangea","text":"MessageReactionChange"},{"kind":"text","text":"])"}],"role":"symbol","abstract":[{"text":"When reaction of message changed.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"onMessageReactionChangedWithChanges:"}],"kind":"symbol","type":"topic"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageListViewModel/onMessageDidReceived(message:)":{"kind":"symbol","url":"\/documentation\/shengwangchatuikit\/messagelistviewmodel\/onmessagedidreceived(message:)","role":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onMessageDidReceived","kind":"identifier"},{"text":"(","kind":"text"},{"text":"message","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"ChatMessage","preciseIdentifier":"s:18ShengwangChatUIKit0B7Messagea"},{"text":")","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewModel\/onMessageDidReceived(message:)","title":"onMessageDidReceived(message:)","navigatorTitle":[{"kind":"identifier","text":"onMessageDidReceivedWithMessage:"}],"abstract":[{"text":"When message received.","type":"text"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewModel\/messagesAlreadyRead(conversationId:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewModel\/onCMDMessageDidReceived(message:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewModel\/onMessageAttachmentStatusChanged(message:error:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewModel\/onMessageDidEdited(message:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewModel\/onMessageDidRecalled(recallInfo:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewModel\/onMessageDidReceived(message:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewModel\/onMessageReactionChanged(changes:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewModel\/onMessageStatusDidChanged(message:status:error:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewModel\/onMessageStickiedTop(conversationId:messageId:operation:info:)"],"generated":true,"anchor":"Instance-Methods","title":"Instance Methods"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":"onCMDMessageDidReceivedWithMessage:","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewModel~1onCMDMessageDidReceived(message:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewModel~1onCMDMessageDidReceived(message:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"onCMDMessageDidReceivedWithMessage:","kind":"identifier"}]},{"value":"onMessageStickiedTopWithConversationId:messageId:operation:info:","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewModel~1onMessageStickiedTop(conversationId:messageId:operation:info:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewModel~1onMessageStickiedTop(conversationId:messageId:operation:info:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onMessageStickiedTopWithConversationId:messageId:operation:info:"}],"op":"replace"},{"value":"onMessageDidRecalledWithRecallInfo:","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewModel~1onMessageDidRecalled(recallInfo:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"onMessageDidRecalledWithRecallInfo:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewModel~1onMessageDidRecalled(recallInfo:)\/fragments"},{"value":"messagesAlreadyReadWithConversationId:","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewModel~1messagesAlreadyRead(conversationId:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"messagesAlreadyReadWithConversationId:"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewModel~1messagesAlreadyRead(conversationId:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewModel~1onMessageDidEdited(message:)\/title","value":"onMessageDidEditedWithMessage:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onMessageDidEditedWithMessage:"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewModel~1onMessageDidEdited(message:)\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewModel\/title","value":"MessageListViewModel"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewModel\/fragments","value":[{"kind":"identifier","text":"MessageListViewModel"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewModel\/navigatorTitle","value":[{"kind":"identifier","text":"MessageListViewModel"}]},{"value":"onMessageStatusDidChangedWithMessage:status:error:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewModel~1onMessageStatusDidChanged(message:status:error:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewModel~1onMessageStatusDidChanged(message:status:error:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"onMessageStatusDidChangedWithMessage:status:error:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewModel~1onMessageAttachmentStatusChanged(message:error:)\/title","value":"onMessageAttachmentStatusChangedWithMessage:error:"},{"value":[{"kind":"text","text":"- "},{"text":"onMessageAttachmentStatusChangedWithMessage:error:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewModel~1onMessageAttachmentStatusChanged(message:error:)\/fragments"},{"value":"onMessageReactionChangedWithChanges:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewModel~1onMessageReactionChanged(changes:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewModel~1onMessageReactionChanged(changes:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"onMessageReactionChangedWithChanges:","kind":"identifier"}]},{"value":"onMessageDidReceivedWithMessage:","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewModel~1onMessageDidReceived(message:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"onMessageDidReceivedWithMessage:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewModel~1onMessageDidReceived(message:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}