{"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"chatService"},{"text":": ","kind":"text"},{"text":"ChatService","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatService","kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(pl)ChatService"},{"kind":"text","text":"? { get }"}],"languages":["swift"],"platforms":["iOS"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewModel\/chatService"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewModel"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/messagelistviewmodel\/chatservice"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/messagelistviewmodel\/chatservice"]}],"metadata":{"title":"chatService","symbolKind":"property","modules":[{"name":"ShengwangChatUIKit"}],"navigatorTitle":[{"text":"chatService","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"chatService","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(pl)ChatService","kind":"typeIdentifier","text":"ChatService"},{"text":"?","kind":"text"}],"roleHeading":"Instance Property","externalID":"c:@M@ShengwangChatUIKit@objc(cs)MessageListViewModel(py)chatService","role":"symbol"},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageListViewModel/chatService":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewModel\/chatService","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"chatService"},{"kind":"text","text":": "},{"text":"ChatService","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(pl)ChatService","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"chatService","kind":"identifier"}],"title":"chatService","url":"\/documentation\/shengwangchatuikit\/messagelistviewmodel\/chatservice","kind":"symbol","abstract":[]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatService":{"navigatorTitle":[{"kind":"identifier","text":"ChatService"}],"abstract":[],"kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatService","url":"\/documentation\/shengwangchatuikit\/chatservice","title":"ChatService","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatService"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageListViewModel":{"url":"\/documentation\/shengwangchatuikit\/messagelistviewmodel","title":"MessageListViewModel","role":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewModel","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MessageListViewModel"}],"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MessageListViewModel"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"value":"chatService","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"chatService"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:Qo@M@ShengwangChatUIKit@objc(pl)ChatService","kind":"typeIdentifier","text":"id<ChatService>"},{"text":" ","kind":"text"},{"text":"chatService","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}},{"value":"chatService","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewModel~1chatService\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewModel~1chatService\/fragments","op":"replace","value":[{"text":"chatService","kind":"identifier"}]},{"value":"ChatService","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatService\/title","op":"replace"},{"value":[{"text":"ChatService","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatService\/fragments","op":"replace"},{"value":[{"text":"ChatService","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatService\/navigatorTitle","op":"replace"},{"value":"MessageListViewModel","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewModel\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewModel\/fragments","op":"replace","value":[{"text":"MessageListViewModel","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewModel\/navigatorTitle","value":[{"text":"MessageListViewModel","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}