{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/messagelistviewmodel\/messagedidrecalled(recallinfo:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/messagelistviewmodel\/messagedidrecalled(recallinfo:)"]}],"metadata":{"symbolKind":"method","title":"messageDidRecalled(recallInfo:)","roleHeading":"Instance Method","extendedModule":"ShengwangChatUIKit","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"messageDidRecalled","kind":"identifier"},{"text":"(","kind":"text"},{"text":"recallInfo","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:18ShengwangChatUIKit10RecallInfoa","text":"RecallInfo","kind":"typeIdentifier"},{"kind":"text","text":")"}],"externalID":"c:@CM@ShengwangChatUIKit@objc(cs)MessageListViewModel(im)messageDidRecalledWithRecallInfo:","modules":[{"name":"ShengwangChatUIKit"}],"navigatorTitle":[{"text":"messageDidRecalledWithRecallInfo:","kind":"identifier"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewModel\/messageDidRecalled(recallInfo:)"},"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewModel"]]},"kind":"symbol","sections":[],"abstract":[{"type":"text","text":"Handles the event when a message is recalled."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"messageDidRecalled"},{"text":"(","kind":"text"},{"text":"recallInfo","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/RecallInfo","kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit10RecallInfoa","text":"RecallInfo"},{"text":")","kind":"text"}]}]},{"kind":"parameters","parameters":[{"name":"recallInfo","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The recall information containing the recalled message."}]}]}]}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/RecallInfo":{"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"text":"RecallInfo","kind":"identifier"}],"title":"RecallInfo","abstract":[],"type":"topic","kind":"symbol","url":"\/documentation\/shengwangchatuikit\/recallinfo","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/RecallInfo","navigatorTitle":[{"text":"RecallInfo","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageListViewModel/messageDidRecalled(recallInfo:)":{"url":"\/documentation\/shengwangchatuikit\/messagelistviewmodel\/messagedidrecalled(recallinfo:)","kind":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"messageDidRecalled"},{"kind":"text","text":"("},{"text":"recallInfo","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"RecallInfo","kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit10RecallInfoa"},{"text":")","kind":"text"}],"abstract":[{"type":"text","text":"Handles the event when a message is recalled."}],"title":"messageDidRecalled(recallInfo:)","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewModel\/messageDidRecalled(recallInfo:)","navigatorTitle":[{"text":"messageDidRecalledWithRecallInfo:","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageListViewModel":{"url":"\/documentation\/shengwangchatuikit\/messagelistviewmodel","title":"MessageListViewModel","role":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewModel","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MessageListViewModel"}],"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MessageListViewModel"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"messageDidRecalledWithRecallInfo:","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"messageDidRecalledWithRecallInfo:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"messageDidRecalledWithRecallInfo:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)AgoraChatRecallMessageInfo","text":"AgoraChatRecallMessageInfo","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"recallInfo","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"op":"replace"},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"recallInfo","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The recall information containing the recalled message."}]}]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewModel~1messageDidRecalled(recallInfo:)\/title","op":"replace","value":"messageDidRecalledWithRecallInfo:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"messageDidRecalledWithRecallInfo:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewModel~1messageDidRecalled(recallInfo:)\/fragments"},{"value":"MessageListViewModel","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewModel\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewModel\/fragments","op":"replace","value":[{"text":"MessageListViewModel","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewModel\/navigatorTitle","value":[{"kind":"identifier","text":"MessageListViewModel"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}