{"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewModel\/MessageListViewActionEventsDelegate-Implementations","interfaceLanguage":"swift"},"topicSections":[{"generated":true,"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewModel\/onFailureMessageRetrySend(entity:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewModel\/onInputBoxEventsOccur(action:attributeText:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewModel\/onMessageAvatarClicked(profile:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewModel\/onMessageAvatarLongPressed(profile:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewModel\/onMessageContentClicked(message:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewModel\/onMessageContentLongPressed(cell:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewModel\/onMessageListLoadMore()","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewModel\/onMessageListPullRefresh()","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewModel\/onMessageMultiSelectBarClicked(operation:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewModel\/onMessageReactionClicked(reaction:entity:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewModel\/onMessageReplyClicked(message:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewModel\/onMessageTopicClicked(entity:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewModel\/onMessageVisible(entity:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewModel\/onMoreMessagesClicked()"]}],"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"roleHeading":"API Collection","modules":[{"name":"ShengwangChatUIKit"}],"role":"collectionGroup","title":"MessageListViewActionEventsDelegate Implementations"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewModel"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/messagelistviewmodel\/messagelistviewactioneventsdelegate-implementations"]},{"paths":["\/documentation\/shengwangchatuikit\/messagelistviewmodel\/messagelistviewactioneventsdelegate-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"article","references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageListViewModel/onInputBoxEventsOccur(action:attributeText:)":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewModel\/onInputBoxEventsOccur(action:attributeText:)","url":"\/documentation\/shengwangchatuikit\/messagelistviewmodel\/oninputboxeventsoccur(action:attributetext:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"onInputBoxEventsOccur","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"action"},{"kind":"text","text":": "},{"text":"MessageInputBarActionType","kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@E@MessageInputBarActionType"},{"text":", ","kind":"text"},{"text":"attributeText","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSAttributedString","text":"NSAttributedString","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"type":"topic","abstract":[{"type":"text","text":"The method will call on input box event occur."}],"title":"onInputBoxEventsOccur(action:attributeText:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"onInputBoxEventsOccurWithAction:attributeText:"}],"kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageListViewModel":{"url":"\/documentation\/shengwangchatuikit\/messagelistviewmodel","title":"MessageListViewModel","role":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewModel","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MessageListViewModel"}],"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MessageListViewModel"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageListViewModel/onMessageListLoadMore()":{"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"onMessageListLoadMore","kind":"identifier"},{"text":"()","kind":"text"}],"url":"\/documentation\/shengwangchatuikit\/messagelistviewmodel\/onmessagelistloadmore()","navigatorTitle":[{"kind":"identifier","text":"onMessageListLoadMore"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewModel\/onMessageListLoadMore()","abstract":[],"kind":"symbol","type":"topic","title":"onMessageListLoadMore()"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageListViewModel/onMessageContentClicked(message:)":{"abstract":[{"text":"The method will call on message content clicked.","type":"text"}],"url":"\/documentation\/shengwangchatuikit\/messagelistviewmodel\/onmessagecontentclicked(message:)","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewModel\/onMessageContentClicked(message:)","role":"symbol","navigatorTitle":[{"text":"onMessageContentClickedWithMessage:","kind":"identifier"}],"kind":"symbol","title":"onMessageContentClicked(message:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onMessageContentClicked","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"message"},{"text":": ","kind":"text"},{"text":"MessageEntity","kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)MessageEntity"},{"text":")","kind":"text"}],"type":"topic"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageListViewModel/onFailureMessageRetrySend(entity:)":{"role":"symbol","kind":"symbol","url":"\/documentation\/shengwangchatuikit\/messagelistviewmodel\/onfailuremessageretrysend(entity:)","type":"topic","title":"onFailureMessageRetrySend(entity:)","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewModel\/onFailureMessageRetrySend(entity:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onFailureMessageRetrySend"},{"kind":"text","text":"("},{"text":"entity","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)MessageEntity","text":"MessageEntity","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"onFailureMessageRetrySendWithEntity:"}],"abstract":[{"type":"text","text":"The method will call on failure message status view clicked."}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageListViewModel/onMessageContentLongPressed(cell:)":{"type":"topic","url":"\/documentation\/shengwangchatuikit\/messagelistviewmodel\/onmessagecontentlongpressed(cell:)","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewModel\/onMessageContentLongPressed(cell:)","role":"symbol","navigatorTitle":[{"text":"onMessageContentLongPressedWithCell:","kind":"identifier"}],"kind":"symbol","title":"onMessageContentLongPressed(cell:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"onMessageContentLongPressed","kind":"identifier"},{"text":"(","kind":"text"},{"text":"cell","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MessageCell","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)MessageCell"},{"text":")","kind":"text"}],"abstract":[{"type":"text","text":"The method will call on message content long pressed."}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageListViewModel/onMessageMultiSelectBarClicked(operation:)":{"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"onMessageMultiSelectBarClicked","kind":"identifier"},{"kind":"text","text":"("},{"text":"operation","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@E@MessageMultiSelectedBottomBarOperation","kind":"typeIdentifier","text":"MessageMultiSelectedBottomBarOperation"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"onMessageMultiSelectBarClickedWithOperation:"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewModel\/onMessageMultiSelectBarClicked(operation:)","abstract":[{"text":"When message multi select bar clicked.","type":"text"}],"title":"onMessageMultiSelectBarClicked(operation:)","role":"symbol","type":"topic","url":"\/documentation\/shengwangchatuikit\/messagelistviewmodel\/onmessagemultiselectbarclicked(operation:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageListViewModel/onMessageVisible(entity:)":{"title":"onMessageVisible(entity:)","role":"symbol","url":"\/documentation\/shengwangchatuikit\/messagelistviewmodel\/onmessagevisible(entity:)","abstract":[{"text":"Message visible on scroll in screen","type":"text"}],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"onMessageVisible","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"entity"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)MessageEntity","kind":"typeIdentifier","text":"MessageEntity"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"onMessageVisibleWithEntity:","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewModel\/onMessageVisible(entity:)","type":"topic"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageListViewModel/onMessageListPullRefresh()":{"role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"The method will call on message list pull to refreshing."}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewModel\/onMessageListPullRefresh()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"onMessageListPullRefresh","kind":"identifier"},{"kind":"text","text":"()"}],"navigatorTitle":[{"text":"onMessageListPullRefresh","kind":"identifier"}],"type":"topic","url":"\/documentation\/shengwangchatuikit\/messagelistviewmodel\/onmessagelistpullrefresh()","title":"onMessageListPullRefresh()"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageListViewModel/onMessageReplyClicked(message:)":{"type":"topic","navigatorTitle":[{"text":"onMessageReplyClickedWithMessage:","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/messagelistviewmodel\/onmessagereplyclicked(message:)","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onMessageReplyClicked"},{"kind":"text","text":"("},{"text":"message","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)MessageEntity","text":"MessageEntity","kind":"typeIdentifier"},{"kind":"text","text":")"}],"abstract":[{"text":"The method will call on message reply content clicked.","type":"text"}],"title":"onMessageReplyClicked(message:)","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewModel\/onMessageReplyClicked(message:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageListViewModel/onMessageTopicClicked(entity:)":{"url":"\/documentation\/shengwangchatuikit\/messagelistviewmodel\/onmessagetopicclicked(entity:)","kind":"symbol","type":"topic","navigatorTitle":[{"text":"onMessageTopicClickedWithEntity:","kind":"identifier"}],"abstract":[{"type":"text","text":"Message topic view clicked."}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewModel\/onMessageTopicClicked(entity:)","title":"onMessageTopicClicked(entity:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onMessageTopicClicked"},{"kind":"text","text":"("},{"text":"entity","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)MessageEntity","text":"MessageEntity"},{"text":")","kind":"text"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageListViewModel/onMessageAvatarClicked(profile:)":{"title":"onMessageAvatarClicked(profile:)","type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewModel\/onMessageAvatarClicked(profile:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onMessageAvatarClicked"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"profile"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(pl)ChatUserProfileProtocol","text":"ChatUserProfileProtocol","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"onMessageAvatarClickedWithProfile:","kind":"identifier"}],"abstract":[{"type":"text","text":"The method will call on message avatar clicked"}],"role":"symbol","url":"\/documentation\/shengwangchatuikit\/messagelistviewmodel\/onmessageavatarclicked(profile:)","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageListViewModel/onMessageAvatarLongPressed(profile:)":{"navigatorTitle":[{"text":"onMessageAvatarLongPressedWithProfile:","kind":"identifier"}],"abstract":[{"text":"The method will call on message avatar long pressed.","type":"text"}],"title":"onMessageAvatarLongPressed(profile:)","type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewModel\/onMessageAvatarLongPressed(profile:)","url":"\/documentation\/shengwangchatuikit\/messagelistviewmodel\/onmessageavatarlongpressed(profile:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onMessageAvatarLongPressed"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"profile"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(pl)ChatUserProfileProtocol","text":"ChatUserProfileProtocol"},{"kind":"text","text":")"}],"role":"symbol","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageListViewModel/onMessageReactionClicked(reaction:entity:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"onMessageReactionClicked"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"reaction"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:18ShengwangChatUIKit15MessageReactiona","text":"MessageReaction","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"entity","kind":"externalParam"},{"kind":"text","text":": "},{"text":"MessageEntity","kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)MessageEntity"},{"text":")","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewModel\/onMessageReactionClicked(reaction:entity:)","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Message reaction&"},{"code":"...","type":"codeVoice"},{"text":" clicked.","type":"text"}],"title":"onMessageReactionClicked(reaction:entity:)","url":"\/documentation\/shengwangchatuikit\/messagelistviewmodel\/onmessagereactionclicked(reaction:entity:)","role":"symbol","navigatorTitle":[{"text":"onMessageReactionClickedWithReaction:entity:","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageListViewModel/onMoreMessagesClicked()":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onMoreMessagesClicked","kind":"identifier"},{"text":"()","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewModel\/onMoreMessagesClicked()","abstract":[{"text":"More messages button clicked.","type":"text"}],"type":"topic","kind":"symbol","title":"onMoreMessagesClicked()","url":"\/documentation\/shengwangchatuikit\/messagelistviewmodel\/onmoremessagesclicked()","role":"symbol","navigatorTitle":[{"text":"onMoreMessagesClicked","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":[{"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewModel\/onFailureMessageRetrySend(entity:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewModel\/onInputBoxEventsOccur(action:attributeText:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewModel\/onMessageAvatarClicked(profile:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewModel\/onMessageAvatarLongPressed(profile:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewModel\/onMessageContentClicked(message:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewModel\/onMessageContentLongPressed(cell:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewModel\/onMessageListLoadMore()","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewModel\/onMessageListPullRefresh()","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewModel\/onMessageMultiSelectBarClicked(operation:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewModel\/onMessageReactionClicked(reaction:entity:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewModel\/onMessageReplyClicked(message:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewModel\/onMessageTopicClicked(entity:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewModel\/onMessageVisible(entity:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewModel\/onMoreMessagesClicked()"],"anchor":"Instance-Methods","title":"Instance Methods","generated":true}],"path":"\/topicSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewModel~1onInputBoxEventsOccur(action:attributeText:)\/title","value":"onInputBoxEventsOccurWithAction:attributeText:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewModel~1onInputBoxEventsOccur(action:attributeText:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"onInputBoxEventsOccurWithAction:attributeText:","kind":"identifier"}]},{"value":"MessageListViewModel","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewModel\/title"},{"op":"replace","value":[{"text":"MessageListViewModel","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewModel\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewModel\/navigatorTitle","value":[{"kind":"identifier","text":"MessageListViewModel"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewModel~1onMessageListLoadMore()\/title","value":"onMessageListLoadMore","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"onMessageListLoadMore","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewModel~1onMessageListLoadMore()\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewModel~1onMessageContentClicked(message:)\/title","value":"onMessageContentClickedWithMessage:"},{"value":[{"kind":"text","text":"- "},{"text":"onMessageContentClickedWithMessage:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewModel~1onMessageContentClicked(message:)\/fragments"},{"op":"replace","value":"onFailureMessageRetrySendWithEntity:","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewModel~1onFailureMessageRetrySend(entity:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"onFailureMessageRetrySendWithEntity:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewModel~1onFailureMessageRetrySend(entity:)\/fragments"},{"value":"onMessageContentLongPressedWithCell:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewModel~1onMessageContentLongPressed(cell:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewModel~1onMessageContentLongPressed(cell:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"onMessageContentLongPressedWithCell:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewModel~1onMessageMultiSelectBarClicked(operation:)\/title","value":"onMessageMultiSelectBarClickedWithOperation:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewModel~1onMessageMultiSelectBarClicked(operation:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onMessageMultiSelectBarClickedWithOperation:"}]},{"op":"replace","value":"onMessageVisibleWithEntity:","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewModel~1onMessageVisible(entity:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewModel~1onMessageVisible(entity:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"onMessageVisibleWithEntity:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewModel~1onMessageListPullRefresh()\/title","value":"onMessageListPullRefresh","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"onMessageListPullRefresh","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewModel~1onMessageListPullRefresh()\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewModel~1onMessageReplyClicked(message:)\/title","value":"onMessageReplyClickedWithMessage:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewModel~1onMessageReplyClicked(message:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onMessageReplyClickedWithMessage:"}]},{"value":"onMessageTopicClickedWithEntity:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewModel~1onMessageTopicClicked(entity:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"onMessageTopicClickedWithEntity:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewModel~1onMessageTopicClicked(entity:)\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewModel~1onMessageAvatarClicked(profile:)\/title","value":"onMessageAvatarClickedWithProfile:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"onMessageAvatarClickedWithProfile:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewModel~1onMessageAvatarClicked(profile:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewModel~1onMessageAvatarLongPressed(profile:)\/title","value":"onMessageAvatarLongPressedWithProfile:"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onMessageAvatarLongPressedWithProfile:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewModel~1onMessageAvatarLongPressed(profile:)\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewModel~1onMessageReactionClicked(reaction:entity:)\/title","value":"onMessageReactionClickedWithReaction:entity:","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"onMessageReactionClickedWithReaction:entity:"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewModel~1onMessageReactionClicked(reaction:entity:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewModel~1onMoreMessagesClicked()\/title","value":"onMoreMessagesClicked"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"onMoreMessagesClicked","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewModel~1onMoreMessagesClicked()\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}