{"variants":[{"paths":["\/documentation\/shengwangchatuikit\/messagelistviewmodel\/messagedidreceived(message:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/messagelistviewmodel\/messagedidreceived(message:)"]}],"metadata":{"role":"symbol","title":"messageDidReceived(message:)","symbolKind":"method","navigatorTitle":[{"text":"messageDidReceivedWithMessage:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"messageDidReceived","kind":"identifier"},{"text":"(","kind":"text"},{"text":"message","kind":"externalParam"},{"kind":"text","text":": "},{"text":"ChatMessage","preciseIdentifier":"s:18ShengwangChatUIKit0B7Messagea","kind":"typeIdentifier"},{"kind":"text","text":")"}],"modules":[{"name":"ShengwangChatUIKit"}],"extendedModule":"ShengwangChatUIKit","roleHeading":"Instance Method","externalID":"c:@CM@ShengwangChatUIKit@objc(cs)MessageListViewModel(im)messageDidReceivedWithMessage:"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"messageDidReceived"},{"kind":"text","text":"("},{"text":"message","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ChatMessage","preciseIdentifier":"s:18ShengwangChatUIKit0B7Messagea","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatMessage"},{"text":")","kind":"text"}],"platforms":["iOS"]}]},{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The received ChatMessage object."}],"type":"paragraph"}],"name":"message"}],"kind":"parameters"}],"abstract":[{"type":"text","text":"Handles the received message and performs necessary actions based on the message type."}],"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewModel"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewModel\/messageDidReceived(message:)","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatMessage":{"url":"\/documentation\/shengwangchatuikit\/chatmessage","abstract":[],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ChatMessage"}],"type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatMessage","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChatMessage"}],"title":"ChatMessage"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageListViewModel/messageDidReceived(message:)":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewModel\/messageDidReceived(message:)","type":"topic","abstract":[{"text":"Handles the received message and performs necessary actions based on the message type.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"messageDidReceived","kind":"identifier"},{"text":"(","kind":"text"},{"text":"message","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:18ShengwangChatUIKit0B7Messagea","text":"ChatMessage","kind":"typeIdentifier"},{"kind":"text","text":")"}],"url":"\/documentation\/shengwangchatuikit\/messagelistviewmodel\/messagedidreceived(message:)","role":"symbol","navigatorTitle":[{"text":"messageDidReceivedWithMessage:","kind":"identifier"}],"kind":"symbol","title":"messageDidReceived(message:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageListViewModel":{"url":"\/documentation\/shengwangchatuikit\/messagelistviewmodel","title":"MessageListViewModel","role":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewModel","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MessageListViewModel"}],"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MessageListViewModel"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"messageDidReceivedWithMessage:","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"messageDidReceivedWithMessage:","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"messageDidReceivedWithMessage:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)AgoraChatMessage","text":"AgoraChatMessage","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"message","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"message","content":[{"inlineContent":[{"type":"text","text":"The received ChatMessage object."}],"type":"paragraph"}]}]}},{"value":"messageDidReceivedWithMessage:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewModel~1messageDidReceived(message:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewModel~1messageDidReceived(message:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"messageDidReceivedWithMessage:"}],"op":"replace"},{"value":"MessageListViewModel","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewModel\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewModel\/fragments","value":[{"text":"MessageListViewModel","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewModel\/navigatorTitle","value":[{"text":"MessageListViewModel","kind":"identifier"}],"op":"replace"}]}]}