{"variants":[{"paths":["\/documentation\/shengwangchatuikit\/messagelistviewmodel\/messagereactionclicked(reaction:entity:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/messagelistviewmodel\/messagereactionclicked(reaction:entity:)"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewModel\/messageReactionClicked(reaction:entity:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"messageReactionClicked"},{"kind":"text","text":"("},{"text":"reaction","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MessageReaction","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageReaction","preciseIdentifier":"s:18ShengwangChatUIKit15MessageReactiona"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"entity"},{"text":": ","kind":"text"},{"text":"MessageEntity","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)MessageEntity","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageEntity"},{"kind":"text","text":")"}],"languages":["swift"]}]}],"metadata":{"extendedModule":"ShengwangChatUIKit","navigatorTitle":[{"kind":"identifier","text":"messageReactionClickedWithReaction:entity:"}],"externalID":"c:@CM@ShengwangChatUIKit@objc(cs)MessageListViewModel(im)messageReactionClickedWithReaction:entity:","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"messageReactionClicked"},{"text":"(","kind":"text"},{"text":"reaction","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MessageReaction","preciseIdentifier":"s:18ShengwangChatUIKit15MessageReactiona","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"entity"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)MessageEntity","text":"MessageEntity","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","title":"messageReactionClicked(reaction:entity:)","modules":[{"name":"ShengwangChatUIKit"}],"symbolKind":"method"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewModel"]]},"kind":"symbol","references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageListViewModel/messageReactionClicked(reaction:entity:)":{"url":"\/documentation\/shengwangchatuikit\/messagelistviewmodel\/messagereactionclicked(reaction:entity:)","navigatorTitle":[{"kind":"identifier","text":"messageReactionClickedWithReaction:entity:"}],"role":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"messageReactionClicked","kind":"identifier"},{"kind":"text","text":"("},{"text":"reaction","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MessageReaction","kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit15MessageReactiona"},{"text":"?, ","kind":"text"},{"text":"entity","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MessageEntity","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)MessageEntity"},{"text":")","kind":"text"}],"abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewModel\/messageReactionClicked(reaction:entity:)","title":"messageReactionClicked(reaction:entity:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageListViewModel":{"url":"\/documentation\/shengwangchatuikit\/messagelistviewmodel","title":"MessageListViewModel","role":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewModel","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MessageListViewModel"}],"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MessageListViewModel"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageEntity":{"navigatorTitle":[{"text":"MessageEntity","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageEntity","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessageEntity","kind":"identifier"}],"title":"MessageEntity","abstract":[],"url":"\/documentation\/shengwangchatuikit\/messageentity"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageReaction":{"type":"topic","title":"MessageReaction","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageReaction","kind":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessageReaction","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MessageReaction"}],"url":"\/documentation\/shengwangchatuikit\/messagereaction","role":"symbol","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"messageReactionClickedWithReaction:entity:","op":"replace"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"messageReactionClickedWithReaction:entity:","kind":"identifier"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"text":"messageReactionClickedWithReaction:","kind":"identifier"},{"kind":"text","text":"("},{"text":"AgoraChatMessageReaction","preciseIdentifier":"c:objc(cs)AgoraChatMessageReaction","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"reaction"},{"kind":"text","text":" "},{"text":"entity:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)MessageEntity","text":"MessageEntity","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageEntity"},{"kind":"text","text":" *) "},{"text":"entity","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewModel~1messageReactionClicked(reaction:entity:)\/title","value":"messageReactionClickedWithReaction:entity:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewModel~1messageReactionClicked(reaction:entity:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"messageReactionClickedWithReaction:entity:"}],"op":"replace"},{"value":"MessageListViewModel","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewModel\/title","op":"replace"},{"value":[{"text":"MessageListViewModel","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewModel\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewModel\/navigatorTitle","value":[{"kind":"identifier","text":"MessageListViewModel"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageEntity\/title","value":"MessageEntity","op":"replace"},{"value":[{"kind":"identifier","text":"MessageEntity"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageEntity\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageEntity\/navigatorTitle","value":[{"text":"MessageEntity","kind":"identifier"}],"op":"replace"}]}]}