{"abstract":[{"text":"Current user is removed.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"onCurrentUserLeft","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"groupId"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"reason","kind":"externalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupLeaveReason","kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit16GroupLeaveReasona","text":"GroupLeaveReason"},{"text":")","kind":"text"}],"languages":["swift"]}]},{"parameters":[{"name":"groupId","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"ID of the group."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Reason for removed."}]}],"name":"reason"}],"kind":"parameters"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/messagelistviewmodel\/oncurrentuserleft(groupid:reason:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/messagelistviewmodel\/oncurrentuserleft(groupid:reason:)"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewModel","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewModel\/GroupServiceListener-Implementations"]]},"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewModel\/onCurrentUserLeft(groupId:reason:)","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"metadata":{"roleHeading":"Instance Method","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"onCurrentUserLeftWithGroupId:reason:"}],"extendedModule":"ShengwangChatUIKit","externalID":"c:@CM@ShengwangChatUIKit@objc(cs)MessageListViewModel(im)onCurrentUserLeftWithGroupId:reason:","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onCurrentUserLeft","kind":"identifier"},{"text":"(","kind":"text"},{"text":"groupId","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"reason"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GroupLeaveReason","preciseIdentifier":"s:18ShengwangChatUIKit16GroupLeaveReasona"},{"text":")","kind":"text"}],"title":"onCurrentUserLeft(groupId:reason:)","modules":[{"name":"ShengwangChatUIKit"}]},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageListViewModel/GroupServiceListener-Implementations":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewModel\/GroupServiceListener-Implementations","url":"\/documentation\/shengwangchatuikit\/messagelistviewmodel\/groupservicelistener-implementations","kind":"article","role":"collectionGroup","abstract":[],"title":"GroupServiceListener Implementations"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageListViewModel/onCurrentUserLeft(groupId:reason:)":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewModel\/onCurrentUserLeft(groupId:reason:)","url":"\/documentation\/shengwangchatuikit\/messagelistviewmodel\/oncurrentuserleft(groupid:reason:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"onCurrentUserLeftWithGroupId:reason:"}],"role":"symbol","abstract":[{"text":"Current user is removed.","type":"text"}],"title":"onCurrentUserLeft(groupId:reason:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"onCurrentUserLeft"},{"text":"(","kind":"text"},{"text":"groupId","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"reason"},{"kind":"text","text":": "},{"text":"GroupLeaveReason","preciseIdentifier":"s:18ShengwangChatUIKit16GroupLeaveReasona","kind":"typeIdentifier"},{"kind":"text","text":")"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/GroupLeaveReason":{"navigatorTitle":[{"text":"GroupLeaveReason","kind":"identifier"}],"type":"topic","title":"GroupLeaveReason","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"GroupLeaveReason","kind":"identifier"}],"abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupLeaveReason","url":"\/documentation\/shengwangchatuikit\/groupleavereason","role":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageListViewModel":{"url":"\/documentation\/shengwangchatuikit\/messagelistviewmodel","title":"MessageListViewModel","role":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewModel","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MessageListViewModel"}],"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MessageListViewModel"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"onCurrentUserLeftWithGroupId:reason:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onCurrentUserLeftWithGroupId:reason:"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"onCurrentUserLeftWithGroupId:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"groupId"},{"text":" ","kind":"text"},{"kind":"identifier","text":"reason:"},{"kind":"text","text":"("},{"text":"AgoraChatGroupLeaveReason","kind":"typeIdentifier","preciseIdentifier":"c:@E@AgoraChatGroupLeaveReason"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"reason"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewModel~1onCurrentUserLeft(groupId:reason:)\/title","value":"onCurrentUserLeftWithGroupId:reason:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"onCurrentUserLeftWithGroupId:reason:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewModel~1onCurrentUserLeft(groupId:reason:)\/fragments"},{"value":"MessageListViewModel","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewModel\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewModel\/fragments","value":[{"text":"MessageListViewModel","kind":"identifier"}]},{"value":[{"text":"MessageListViewModel","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewModel\/navigatorTitle"}]}]}