{"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewModel\/onInputBoxEventsOccur(action:attributeText:)","interfaceLanguage":"swift"},"sections":[],"variants":[{"paths":["\/documentation\/shengwangchatuikit\/messagelistviewmodel\/oninputboxeventsoccur(action:attributetext:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/messagelistviewmodel\/oninputboxeventsoccur(action:attributetext:)"]}],"abstract":[{"text":"The method will call on input box event occur.","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"onInputBoxEventsOccur","kind":"identifier"},{"text":"(","kind":"text"},{"text":"action","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"type","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageInputBarActionType","text":"MessageInputBarActionType","preciseIdentifier":"c:@M@ShengwangChatUIKit@E@MessageInputBarActionType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"attributeText"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"NSAttributedString","preciseIdentifier":"c:objc(cs)NSAttributedString"},{"text":"?)","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]},{"parameters":[{"name":"type","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageInputBarActionType","type":"reference","isActive":true}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"NSAttributedString of textfield."}]}],"name":"type"}],"kind":"parameters"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewModel","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewModel\/MessageListViewActionEventsDelegate-Implementations"]]},"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onInputBoxEventsOccur"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"action"},{"kind":"text","text":": "},{"text":"MessageInputBarActionType","kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@E@MessageInputBarActionType"},{"text":", ","kind":"text"},{"text":"attributeText","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSAttributedString","kind":"typeIdentifier","text":"NSAttributedString"},{"text":"?)","kind":"text"}],"symbolKind":"method","modules":[{"name":"ShengwangChatUIKit"}],"title":"onInputBoxEventsOccur(action:attributeText:)","navigatorTitle":[{"text":"onInputBoxEventsOccurWithAction:attributeText:","kind":"identifier"}],"extendedModule":"ShengwangChatUIKit","roleHeading":"Instance Method","externalID":"c:@CM@ShengwangChatUIKit@objc(cs)MessageListViewModel(im)onInputBoxEventsOccurWithAction:attributeText:","role":"symbol"},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageListViewModel/MessageListViewActionEventsDelegate-Implementations":{"kind":"article","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewModel\/MessageListViewActionEventsDelegate-Implementations","title":"MessageListViewActionEventsDelegate Implementations","url":"\/documentation\/shengwangchatuikit\/messagelistviewmodel\/messagelistviewactioneventsdelegate-implementations","type":"topic","role":"collectionGroup","abstract":[]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageListViewModel":{"url":"\/documentation\/shengwangchatuikit\/messagelistviewmodel","title":"MessageListViewModel","role":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewModel","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MessageListViewModel"}],"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MessageListViewModel"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageListViewModel/onInputBoxEventsOccur(action:attributeText:)":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewModel\/onInputBoxEventsOccur(action:attributeText:)","url":"\/documentation\/shengwangchatuikit\/messagelistviewmodel\/oninputboxeventsoccur(action:attributetext:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"onInputBoxEventsOccur","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"action"},{"kind":"text","text":": "},{"text":"MessageInputBarActionType","kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@E@MessageInputBarActionType"},{"text":", ","kind":"text"},{"text":"attributeText","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSAttributedString","text":"NSAttributedString","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"type":"topic","abstract":[{"type":"text","text":"The method will call on input box event occur."}],"title":"onInputBoxEventsOccur(action:attributeText:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"onInputBoxEventsOccurWithAction:attributeText:"}],"kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageInputBarActionType":{"navigatorTitle":[{"kind":"identifier","text":"MessageInputBarActionType"}],"abstract":[{"text":"The types of actions that can be triggered by the input bar.","type":"text"}],"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"MessageInputBarActionType","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/messageinputbaractiontype","role":"symbol","title":"MessageInputBarActionType","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageInputBarActionType"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"onInputBoxEventsOccurWithAction:attributeText:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"onInputBoxEventsOccurWithAction:attributeText:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"onInputBoxEventsOccurWithAction:"},{"text":"(","kind":"text"},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageInputBarActionType","text":"MessageInputBarActionType","preciseIdentifier":"c:@M@ShengwangChatUIKit@E@MessageInputBarActionType"},{"kind":"text","text":") "},{"kind":"internalParam","text":"type"},{"text":" ","kind":"text"},{"kind":"identifier","text":"attributeText:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSAttributedString","text":"NSAttributedString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"attributeText","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewModel\/title","value":"MessageListViewModel"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewModel\/fragments","value":[{"text":"MessageListViewModel","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewModel\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MessageListViewModel"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewModel~1onInputBoxEventsOccur(action:attributeText:)\/title","op":"replace","value":"onInputBoxEventsOccurWithAction:attributeText:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"onInputBoxEventsOccurWithAction:attributeText:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewModel~1onInputBoxEventsOccur(action:attributeText:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageInputBarActionType\/title","value":"MessageInputBarActionType"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageInputBarActionType\/fragments","value":[{"text":"MessageInputBarActionType","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"MessageInputBarActionType"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageInputBarActionType\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}