{"abstract":[{"type":"text","text":"The method will call on message avatar long pressed."}],"metadata":{"extendedModule":"ShengwangChatUIKit","navigatorTitle":[{"kind":"identifier","text":"onMessageAvatarLongPressedWithProfile:"}],"roleHeading":"Instance Method","externalID":"c:@CM@ShengwangChatUIKit@objc(cs)MessageListViewModel(im)onMessageAvatarLongPressedWithProfile:","role":"symbol","symbolKind":"method","modules":[{"name":"ShengwangChatUIKit"}],"title":"onMessageAvatarLongPressed(profile:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onMessageAvatarLongPressed"},{"kind":"text","text":"("},{"text":"profile","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ChatUserProfileProtocol","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(pl)ChatUserProfileProtocol","kind":"typeIdentifier"},{"kind":"text","text":")"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewModel\/onMessageAvatarLongPressed(profile:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"onMessageAvatarLongPressed"},{"text":"(","kind":"text"},{"text":"profile","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatUserProfileProtocol","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(pl)ChatUserProfileProtocol","kind":"typeIdentifier","text":"ChatUserProfileProtocol"},{"text":")","kind":"text"}]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"type":"reference","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatUserProfileProtocol","isActive":true}]}],"name":"profile"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/messagelistviewmodel\/onmessageavatarlongpressed(profile:)"]},{"paths":["\/documentation\/shengwangchatuikit\/messagelistviewmodel\/onmessageavatarlongpressed(profile:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewModel","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewModel\/MessageListViewActionEventsDelegate-Implementations"]]},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageListViewModel/MessageListViewActionEventsDelegate-Implementations":{"kind":"article","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewModel\/MessageListViewActionEventsDelegate-Implementations","title":"MessageListViewActionEventsDelegate Implementations","url":"\/documentation\/shengwangchatuikit\/messagelistviewmodel\/messagelistviewactioneventsdelegate-implementations","type":"topic","role":"collectionGroup","abstract":[]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageListViewModel":{"url":"\/documentation\/shengwangchatuikit\/messagelistviewmodel","title":"MessageListViewModel","role":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewModel","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MessageListViewModel"}],"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MessageListViewModel"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageListViewModel/onMessageAvatarLongPressed(profile:)":{"navigatorTitle":[{"text":"onMessageAvatarLongPressedWithProfile:","kind":"identifier"}],"abstract":[{"text":"The method will call on message avatar long pressed.","type":"text"}],"title":"onMessageAvatarLongPressed(profile:)","type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewModel\/onMessageAvatarLongPressed(profile:)","url":"\/documentation\/shengwangchatuikit\/messagelistviewmodel\/onmessageavatarlongpressed(profile:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onMessageAvatarLongPressed"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"profile"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(pl)ChatUserProfileProtocol","text":"ChatUserProfileProtocol"},{"kind":"text","text":")"}],"role":"symbol","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatUserProfileProtocol":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatUserProfileProtocol","abstract":[{"text":"Profile of the ChatUIKit display needed.","type":"text"}],"title":"ChatUserProfileProtocol","type":"topic","kind":"symbol","navigatorTitle":[{"text":"ChatUserProfileProtocol","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"ChatUserProfileProtocol","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/chatuserprofileprotocol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"onMessageAvatarLongPressedWithProfile:"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"onMessageAvatarLongPressedWithProfile:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"onMessageAvatarLongPressedWithProfile:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@ShengwangChatUIKit@objc(pl)ChatUserProfileProtocol","text":"id<ChatUserProfileProtocol>"},{"kind":"text","text":") "},{"text":"profile","kind":"internalParam"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewModel\/title","op":"replace","value":"MessageListViewModel"},{"value":[{"text":"MessageListViewModel","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewModel\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewModel\/navigatorTitle","value":[{"text":"MessageListViewModel","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewModel~1onMessageAvatarLongPressed(profile:)\/title","value":"onMessageAvatarLongPressedWithProfile:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewModel~1onMessageAvatarLongPressed(profile:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onMessageAvatarLongPressedWithProfile:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatUserProfileProtocol\/title","value":"ChatUserProfileProtocol"},{"value":[{"text":"ChatUserProfileProtocol","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatUserProfileProtocol\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatUserProfileProtocol\/navigatorTitle","value":[{"text":"ChatUserProfileProtocol","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}