{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"willSendMessage"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"attributeText"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSAttributedString","text":"NSAttributedString","kind":"typeIdentifier"},{"text":")","kind":"text"}]}],"kind":"declarations"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/messagelistviewmodel\/willsendmessage(attributetext:)"]},{"paths":["\/documentation\/shengwangchatuikit\/messagelistviewmodel\/willsendmessage(attributetext:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"metadata":{"extendedModule":"ShengwangChatUIKit","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"willSendMessage","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"attributeText"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSAttributedString","kind":"typeIdentifier","text":"NSAttributedString"},{"kind":"text","text":")"}],"roleHeading":"Instance Method","modules":[{"name":"ShengwangChatUIKit"}],"symbolKind":"method","role":"symbol","externalID":"c:@CM@ShengwangChatUIKit@objc(cs)MessageListViewModel(im)willSendMessageWithAttributeText:","title":"willSendMessage(attributeText:)","navigatorTitle":[{"kind":"identifier","text":"willSendMessageWithAttributeText:"}]},"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewModel\/willSendMessage(attributeText:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewModel"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageListViewModel":{"url":"\/documentation\/shengwangchatuikit\/messagelistviewmodel","title":"MessageListViewModel","role":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewModel","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MessageListViewModel"}],"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MessageListViewModel"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageListViewModel/willSendMessage(attributeText:)":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewModel\/willSendMessage(attributeText:)","abstract":[],"url":"\/documentation\/shengwangchatuikit\/messagelistviewmodel\/willsendmessage(attributetext:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"willSendMessage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"attributeText"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSAttributedString","kind":"typeIdentifier","text":"NSAttributedString"},{"text":")","kind":"text"}],"role":"symbol","title":"willSendMessage(attributeText:)","navigatorTitle":[{"text":"willSendMessageWithAttributeText:","kind":"identifier"}],"kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"willSendMessageWithAttributeText:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"willSendMessageWithAttributeText:"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"willSendMessageWithAttributeText:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSAttributedString","text":"NSAttributedString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"attributeText"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","value":"MessageListViewModel","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewModel\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewModel\/fragments","op":"replace","value":[{"text":"MessageListViewModel","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"MessageListViewModel"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewModel\/navigatorTitle"},{"op":"replace","value":"willSendMessageWithAttributeText:","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewModel~1willSendMessage(attributeText:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"willSendMessageWithAttributeText:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewModel~1willSendMessage(attributeText:)\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}