{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/FlipHorizontalAnimation\/performAnimation(animationContext:)"},"metadata":{"symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"performAnimation","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"animationContext"},{"kind":"text","text":": "},{"text":"AnimationContext","preciseIdentifier":"s:18ShengwangChatUIKit16AnimationContextV","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","externalID":"s:18ShengwangChatUIKit23FlipHorizontalAnimationC07performF016animationContextyAA0fI0V_tF","title":"performAnimation(animationContext:)","roleHeading":"Instance Method","modules":[{"name":"ShengwangChatUIKit"}]},"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"paths":["\/documentation\/shengwangchatuikit\/fliphorizontalanimation\/performanimation(animationcontext:)"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/FlipHorizontalAnimation"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"performAnimation","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"animationContext"},{"kind":"text","text":": "},{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/AnimationContext","kind":"typeIdentifier","text":"AnimationContext","preciseIdentifier":"s:18ShengwangChatUIKit16AnimationContextV"},{"text":")","kind":"text"}]}]}],"sections":[],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/AnimationContext":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"AnimationContext"}],"type":"topic","title":"AnimationContext","url":"\/documentation\/shengwangchatuikit\/animationcontext","navigatorTitle":[{"kind":"identifier","text":"AnimationContext"}],"abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/AnimationContext","role":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/FlipHorizontalAnimation/performAnimation(animationContext:)":{"type":"topic","url":"\/documentation\/shengwangchatuikit\/fliphorizontalanimation\/performanimation(animationcontext:)","kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"performAnimation"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"animationContext"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:18ShengwangChatUIKit16AnimationContextV","kind":"typeIdentifier","text":"AnimationContext"},{"text":")","kind":"text"}],"abstract":[],"title":"performAnimation(animationContext:)","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/FlipHorizontalAnimation\/performAnimation(animationContext:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/FlipHorizontalAnimation":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"FlipHorizontalAnimation"}],"url":"\/documentation\/shengwangchatuikit\/fliphorizontalanimation","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"FlipHorizontalAnimation","kind":"identifier"}],"abstract":[],"title":"FlipHorizontalAnimation","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/FlipHorizontalAnimation"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1FlipHorizontalAnimation\/title","value":"FlipHorizontalAnimation"},{"value":[{"text":"FlipHorizontalAnimation","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1FlipHorizontalAnimation\/fragments"},{"value":[{"text":"FlipHorizontalAnimation","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1FlipHorizontalAnimation\/navigatorTitle"}]}]}