{"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"text":"required","kind":"keyword"},{"kind":"text","text":" "},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"towards"},{"text":": ","kind":"text"},{"text":"BubbleTowards","preciseIdentifier":"c:@M@ShengwangChatUIKit@E@BubbleTowards","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/BubbleTowards","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"reuseIdentifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/BubbleTowards","type":"reference","isActive":true},{"type":"text","text":" is towards of the bubble."}]}],"name":"towards"},{"name":"reuseIdentifier","content":[{"inlineContent":[{"type":"text","text":"Cell reuse identifier."}],"type":"paragraph"}]}],"kind":"parameters"}],"metadata":{"roleHeading":"Initializer","navigatorTitle":[{"text":"initWithTowards:reuseIdentifier:","kind":"identifier"}],"role":"symbol","title":"init(towards:reuseIdentifier:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"towards","kind":"externalParam"},{"kind":"text","text":": "},{"text":"BubbleTowards","kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@E@BubbleTowards"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"reuseIdentifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":")","kind":"text"}],"modules":[{"name":"ShengwangChatUIKit"}],"externalID":"c:@M@ShengwangChatUIKit@objc(cs)CustomMessageCell(im)initWithTowards:reuseIdentifier:","symbolKind":"init"},"abstract":[{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageCell","isActive":true,"type":"reference"},{"type":"text","text":" required init method."}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/CustomMessageCell\/init(towards:reuseIdentifier:)"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/CustomMessageCell"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/custommessagecell\/init(towards:reuseidentifier:)"]},{"paths":["\/documentation\/shengwangchatuikit\/custommessagecell\/init(towards:reuseidentifier:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/CustomMessageCell":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/CustomMessageCell","role":"symbol","type":"topic","navigatorTitle":[{"text":"CustomMessageCell","kind":"identifier"}],"title":"CustomMessageCell","abstract":[],"url":"\/documentation\/shengwangchatuikit\/custommessagecell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomMessageCell"}],"kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageCell":{"navigatorTitle":[{"text":"MessageCell","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageCell"}],"title":"MessageCell","abstract":[],"url":"\/documentation\/shengwangchatuikit\/messagecell"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/CustomMessageCell/init(towards:reuseIdentifier:)":{"abstract":[{"type":"reference","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageCell","isActive":true},{"text":" required init method.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/CustomMessageCell\/init(towards:reuseIdentifier:)","navigatorTitle":[{"text":"initWithTowards:reuseIdentifier:","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/shengwangchatuikit\/custommessagecell\/init(towards:reuseidentifier:)","kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"towards","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@E@BubbleTowards","kind":"typeIdentifier","text":"BubbleTowards"},{"kind":"text","text":", "},{"kind":"externalParam","text":"reuseIdentifier"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":")"}],"title":"init(towards:reuseIdentifier:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/BubbleTowards":{"navigatorTitle":[{"kind":"identifier","text":"BubbleTowards"}],"abstract":[],"kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/BubbleTowards","url":"\/documentation\/shengwangchatuikit\/bubbletowards","title":"BubbleTowards","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"BubbleTowards"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","value":"initWithTowards:reuseIdentifier:","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithTowards:reuseIdentifier:","kind":"identifier"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"text":"initWithTowards:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/BubbleTowards","text":"BubbleTowards","preciseIdentifier":"c:@M@ShengwangChatUIKit@E@BubbleTowards"},{"text":") ","kind":"text"},{"text":"towards","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"reuseIdentifier:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"text":"reuseIdentifier","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"value":"CustomMessageCell","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1CustomMessageCell\/title","op":"replace"},{"value":[{"kind":"identifier","text":"CustomMessageCell"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1CustomMessageCell\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1CustomMessageCell\/navigatorTitle","op":"replace","value":[{"text":"CustomMessageCell","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageCell\/title","value":"MessageCell","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageCell\/fragments","value":[{"text":"MessageCell","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageCell\/navigatorTitle","value":[{"text":"MessageCell","kind":"identifier"}]},{"value":"initWithTowards:reuseIdentifier:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1CustomMessageCell~1init(towards:reuseIdentifier:)\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithTowards:reuseIdentifier:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1CustomMessageCell~1init(towards:reuseIdentifier:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1BubbleTowards\/title","value":"BubbleTowards"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1BubbleTowards\/fragments","value":[{"kind":"identifier","text":"BubbleTowards"}]},{"value":[{"kind":"identifier","text":"BubbleTowards"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1BubbleTowards\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}