{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/TranslateTextView\/canPerformAction(_:withSender:)"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/TranslateTextView"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"canPerformAction"},{"kind":"text","text":"("},{"text":"Selector","kind":"typeIdentifier","preciseIdentifier":"s:10ObjectiveC8SelectorV"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"withSender"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"canPerformAction:withSender:","kind":"identifier"}],"role":"symbol","externalID":"c:@M@ShengwangChatUIKit@objc(cs)TranslateTextView(im)canPerformAction:withSender:","title":"canPerformAction(_:withSender:)","roleHeading":"Instance Method","modules":[{"name":"ShengwangChatUIKit"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/translatetextview\/canperformaction(_:withsender:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/translatetextview\/canperformaction(_:withsender:)"]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"kind":"text","text":" "},{"text":"override","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"canPerformAction"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"action","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10ObjectiveC8SelectorV","text":"Selector"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"withSender"},{"kind":"text","text":" "},{"text":"sender","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/TranslateTextView":{"navigatorTitle":[{"text":"TranslateTextView","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/translatetextview","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"TranslateTextView","kind":"identifier"}],"role":"symbol","title":"TranslateTextView","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/TranslateTextView","kind":"symbol","abstract":[]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/TranslateTextView/canPerformAction(_:withSender:)":{"url":"\/documentation\/shengwangchatuikit\/translatetextview\/canperformaction(_:withsender:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"canPerformAction"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"Selector","preciseIdentifier":"s:10ObjectiveC8SelectorV"},{"kind":"text","text":", "},{"text":"withSender","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"navigatorTitle":[{"kind":"identifier","text":"canPerformAction:withSender:"}],"abstract":[],"type":"topic","title":"canPerformAction(_:withSender:)","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/TranslateTextView\/canPerformAction(_:withSender:)","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"canPerformAction:withSender:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"canPerformAction:withSender:"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"canPerformAction:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:e","text":"SEL"},{"text":" *) ","kind":"text"},{"text":"action","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"withSender:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"text":"sender","kind":"internalParam"},{"text":";","kind":"text"}]}]}},{"op":"replace","value":"TranslateTextView","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1TranslateTextView\/title"},{"op":"replace","value":[{"text":"TranslateTextView","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1TranslateTextView\/fragments"},{"value":[{"kind":"identifier","text":"TranslateTextView"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1TranslateTextView\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1TranslateTextView~1canPerformAction(_:withSender:)\/title","value":"canPerformAction:withSender:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1TranslateTextView~1canPerformAction(_:withSender:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"canPerformAction:withSender:","kind":"identifier"}]}]}]}