{"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/TranslateTextView\/initWithFrame:textContainer:","interfaceLanguage":"occ"},"sections":[],"variants":[{"paths":["\/documentation\/shengwangchatuikit\/translatetextview\/initwithframe:textcontainer:"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"initWithFrame:","kind":"identifier"},{"kind":"text","text":"("},{"text":"CGRect","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect"},{"text":") ","kind":"text"},{"text":"frame","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"textContainer:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSTextContainer","text":"NSTextContainer"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"textContainer"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/TranslateTextView"]]},"metadata":{"modules":[{"name":"ShengwangChatUIKit"}],"fragments":[{"text":"- ","kind":"text"},{"text":"initWithFrame:textContainer:","kind":"identifier"}],"role":"symbol","platforms":[{"introducedAt":"7.0","name":"iOS","unavailable":false,"beta":false,"deprecated":false},{"name":"iPadOS","deprecated":false,"introducedAt":"7.0","unavailable":false,"beta":false},{"unavailable":false,"introducedAt":"7.0","deprecated":false,"beta":false,"name":"Mac Catalyst"}],"title":"initWithFrame:textContainer:","symbolKind":"method","roleHeading":"Instance Method","navigatorTitle":[{"text":"initWithFrame:textContainer:","kind":"identifier"}],"externalID":"c:@M@ShengwangChatUIKit@objc(cs)TranslateTextView(im)initWithFrame:textContainer:"},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/TranslateTextView":{"navigatorTitle":[{"text":"TranslateTextView","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/translatetextview","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"TranslateTextView","kind":"identifier"}],"role":"symbol","title":"TranslateTextView","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/TranslateTextView","kind":"symbol","abstract":[]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/TranslateTextView/initWithFrame:textContainer:":{"abstract":[],"fragments":[{"text":"- ","kind":"text"},{"text":"initWithFrame:textContainer:","kind":"identifier"}],"role":"symbol","type":"topic","url":"\/documentation\/shengwangchatuikit\/translatetextview\/initwithframe:textcontainer:","title":"initWithFrame:textContainer:","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/TranslateTextView\/initWithFrame:textContainer:","navigatorTitle":[{"text":"initWithFrame:textContainer:","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1TranslateTextView\/title","value":"TranslateTextView","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1TranslateTextView\/fragments","op":"replace","value":[{"text":"TranslateTextView","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1TranslateTextView\/navigatorTitle","value":[{"kind":"identifier","text":"TranslateTextView"}]}]}]}