{"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MenuItemView\/cover"},"kind":"symbol","sections":[],"metadata":{"modules":[{"name":"ShengwangChatUIKit"}],"symbolKind":"property","title":"cover","role":"symbol","externalID":"s:18ShengwangChatUIKit12MenuItemViewC5coverSo6UIViewCvp","roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cover"},{"kind":"text","text":": "},{"text":"UIView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MenuItemView"]]},"variants":[{"paths":["\/documentation\/shengwangchatuikit\/menuitemview\/cover"],"traits":[{"interfaceLanguage":"swift"}]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"text":"lazy","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cover"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView","text":"UIView"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" ","kind":"text"},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MenuItemView":{"kind":"symbol","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MenuItemView","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MenuItemView","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MenuItemView"}],"url":"\/documentation\/shengwangchatuikit\/menuitemview","title":"MenuItemView"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MenuItemView/cover":{"abstract":[],"title":"cover","type":"topic","role":"symbol","url":"\/documentation\/shengwangchatuikit\/menuitemview\/cover","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MenuItemView\/cover","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cover"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIView","text":"UIView","kind":"typeIdentifier"}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MenuItemView\/title","op":"replace","value":"MenuItemView"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MenuItemView\/fragments","value":[{"kind":"identifier","text":"MenuItemView"}],"op":"replace"},{"value":[{"kind":"identifier","text":"MenuItemView"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MenuItemView\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}