{"kind":"symbol","metadata":{"roleHeading":"Case","title":"MessageCellClickArea.avatar","externalID":"c:@M@ShengwangChatUIKit@E@MessageCellClickArea@MessageCellClickAreaAvatar","navigatorTitle":[{"kind":"identifier","text":"MessageCellClickAreaAvatar"}],"symbolKind":"case","role":"symbol","modules":[{"name":"ShengwangChatUIKit"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"avatar","kind":"identifier"}]},"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"avatar","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageCellClickArea"]]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageCellClickArea\/avatar"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/messagecellclickarea\/avatar"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/messagecellclickarea\/avatar"]}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageCellClickArea/avatar":{"title":"MessageCellClickArea.avatar","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MessageCellClickAreaAvatar"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"avatar"}],"type":"topic","kind":"symbol","url":"\/documentation\/shengwangchatuikit\/messagecellclickarea\/avatar","abstract":[],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageCellClickArea\/avatar"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageCellClickArea":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageCellClickArea"}],"type":"topic","kind":"symbol","abstract":[{"text":"Enum representing the different areas that can be clicked in a message cell.","type":"text"}],"url":"\/documentation\/shengwangchatuikit\/messagecellclickarea","navigatorTitle":[{"text":"MessageCellClickArea","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageCellClickArea","role":"symbol","title":"MessageCellClickArea"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"MessageCellClickAreaAvatar"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"MessageCellClickAreaAvatar","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"MessageCellClickAreaAvatar"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"value":"MessageCellClickAreaAvatar","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageCellClickArea~1avatar\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageCellClickArea~1avatar\/fragments","value":[{"text":"MessageCellClickAreaAvatar","kind":"identifier"}],"op":"replace"},{"value":"MessageCellClickArea","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageCellClickArea\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageCellClickArea\/fragments","op":"replace","value":[{"text":"MessageCellClickArea","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"MessageCellClickArea"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageCellClickArea\/navigatorTitle"}]}]}