{"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageCellClickArea\/cell","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"modules":[{"name":"ShengwangChatUIKit"}],"roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"cell","kind":"identifier"}],"title":"MessageCellClickArea.cell","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MessageCellClickAreaCell"}],"externalID":"c:@M@ShengwangChatUIKit@E@MessageCellClickArea@MessageCellClickAreaCell","symbolKind":"case"},"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageCellClickArea"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/messagecellclickarea\/cell"]},{"paths":["\/documentation\/shengwangchatuikit\/messagecellclickarea\/cell"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cell"}],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageCellClickArea":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageCellClickArea"}],"type":"topic","kind":"symbol","abstract":[{"text":"Enum representing the different areas that can be clicked in a message cell.","type":"text"}],"url":"\/documentation\/shengwangchatuikit\/messagecellclickarea","navigatorTitle":[{"text":"MessageCellClickArea","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageCellClickArea","role":"symbol","title":"MessageCellClickArea"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageCellClickArea/cell":{"type":"topic","role":"symbol","title":"MessageCellClickArea.cell","kind":"symbol","abstract":[],"navigatorTitle":[{"text":"MessageCellClickAreaCell","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/messagecellclickarea\/cell","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageCellClickArea\/cell","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cell"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"path":"\/metadata\/title","value":"MessageCellClickAreaCell","op":"replace"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"MessageCellClickAreaCell"}]},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"MessageCellClickAreaCell","kind":"identifier"}],"platforms":["iOS"]}]},"op":"replace"},{"value":"MessageCellClickArea","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageCellClickArea\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageCellClickArea\/fragments","op":"replace","value":[{"text":"MessageCellClickArea","kind":"identifier"}]},{"op":"replace","value":[{"text":"MessageCellClickArea","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageCellClickArea\/navigatorTitle"},{"value":"MessageCellClickAreaCell","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageCellClickArea~1cell\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageCellClickArea~1cell\/fragments","op":"replace","value":[{"kind":"identifier","text":"MessageCellClickAreaCell"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}