{"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageCellClickArea\/checkbox"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageCellClickArea"]]},"variants":[{"paths":["\/documentation\/shengwangchatuikit\/messagecellclickarea\/checkbox"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/shengwangchatuikit\/messagecellclickarea\/checkbox"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"MessageCellClickAreaCheckbox"}],"externalID":"c:@M@ShengwangChatUIKit@E@MessageCellClickArea@MessageCellClickAreaCheckbox","roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"checkbox"}],"role":"symbol","title":"MessageCellClickArea.checkbox","modules":[{"name":"ShengwangChatUIKit"}],"symbolKind":"case"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"checkbox"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"kind":"symbol","references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageCellClickArea":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageCellClickArea"}],"type":"topic","kind":"symbol","abstract":[{"text":"Enum representing the different areas that can be clicked in a message cell.","type":"text"}],"url":"\/documentation\/shengwangchatuikit\/messagecellclickarea","navigatorTitle":[{"text":"MessageCellClickArea","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageCellClickArea","role":"symbol","title":"MessageCellClickArea"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageCellClickArea/checkbox":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageCellClickArea\/checkbox","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"checkbox"}],"title":"MessageCellClickArea.checkbox","role":"symbol","url":"\/documentation\/shengwangchatuikit\/messagecellclickarea\/checkbox","abstract":[],"type":"topic","kind":"symbol","navigatorTitle":[{"text":"MessageCellClickAreaCheckbox","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"op":"replace","value":"MessageCellClickAreaCheckbox","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"MessageCellClickAreaCheckbox"}],"path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"MessageCellClickAreaCheckbox","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageCellClickArea\/title","value":"MessageCellClickArea","op":"replace"},{"value":[{"text":"MessageCellClickArea","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageCellClickArea\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"MessageCellClickArea"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageCellClickArea\/navigatorTitle","op":"replace"},{"op":"replace","value":"MessageCellClickAreaCheckbox","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageCellClickArea~1checkbox\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageCellClickArea~1checkbox\/fragments","value":[{"text":"MessageCellClickAreaCheckbox","kind":"identifier"}]}]}]}