{"metadata":{"modules":[{"name":"ShengwangChatUIKit"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"reply"}],"role":"symbol","title":"MessageCellClickArea.reply","symbolKind":"case","roleHeading":"Case","navigatorTitle":[{"kind":"identifier","text":"MessageCellClickAreaReply"}],"externalID":"c:@M@ShengwangChatUIKit@E@MessageCellClickArea@MessageCellClickAreaReply"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageCellClickArea\/reply"},"sections":[],"variants":[{"paths":["\/documentation\/shengwangchatuikit\/messagecellclickarea\/reply"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/messagecellclickarea\/reply"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"reply","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageCellClickArea"]]},"kind":"symbol","references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageCellClickArea":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageCellClickArea"}],"type":"topic","kind":"symbol","abstract":[{"text":"Enum representing the different areas that can be clicked in a message cell.","type":"text"}],"url":"\/documentation\/shengwangchatuikit\/messagecellclickarea","navigatorTitle":[{"text":"MessageCellClickArea","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageCellClickArea","role":"symbol","title":"MessageCellClickArea"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageCellClickArea/reply":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageCellClickArea\/reply","navigatorTitle":[{"kind":"identifier","text":"MessageCellClickAreaReply"}],"url":"\/documentation\/shengwangchatuikit\/messagecellclickarea\/reply","type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"reply","kind":"identifier"}],"title":"MessageCellClickArea.reply","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"MessageCellClickAreaReply"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"MessageCellClickAreaReply"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"MessageCellClickAreaReply"}],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageCellClickArea\/title","value":"MessageCellClickArea","op":"replace"},{"value":[{"kind":"identifier","text":"MessageCellClickArea"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageCellClickArea\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageCellClickArea\/navigatorTitle","value":[{"kind":"identifier","text":"MessageCellClickArea"}]},{"op":"replace","value":"MessageCellClickAreaReply","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageCellClickArea~1reply\/title"},{"value":[{"text":"MessageCellClickAreaReply","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageCellClickArea~1reply\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}