{"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/chatuikitoptions\/init"]}],"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatUIKitOptions\/init","interfaceLanguage":"occ"},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"symbolKind":"method","title":"init","roleHeading":"Instance Method","role":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"modules":[{"name":"ShengwangChatUIKit"}],"externalID":"c:@M@ShengwangChatUIKit@objc(cs)ChatUIKitOptions(im)init","navigatorTitle":[{"text":"init","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatUIKitOptions"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"init","kind":"identifier"},{"kind":"text","text":";"}]}]}],"sections":[],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatUIKitOptions":{"type":"topic","role":"symbol","title":"ChatUIKitOptions","kind":"symbol","abstract":[],"navigatorTitle":[{"text":"ChatUIKitOptions","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/chatuikitoptions","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatUIKitOptions","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ChatUIKitOptions","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatUIKitOptions/init":{"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"init"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatUIKitOptions\/init","kind":"symbol","type":"topic","url":"\/documentation\/shengwangchatuikit\/chatuikitoptions\/init","role":"symbol","title":"init","fragments":[{"kind":"text","text":"- "},{"text":"init","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"ChatUIKitOptions","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatUIKitOptions\/title"},{"op":"replace","value":[{"kind":"identifier","text":"ChatUIKitOptions"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatUIKitOptions\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatUIKitOptions\/navigatorTitle","value":[{"text":"ChatUIKitOptions","kind":"identifier"}],"op":"replace"}]}]}