{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatUIKitOptions"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/chatuikitoptions\/option_chat"]},{"paths":["\/documentation\/shengwangchatuikit\/chatuikitoptions\/option_chat"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"externalID":"c:@M@ShengwangChatUIKit@objc(cs)ChatUIKitOptions(py)option_chat","navigatorTitle":[{"kind":"identifier","text":"option_chat"}],"role":"symbol","modules":[{"name":"ShengwangChatUIKit"}],"title":"option_chat","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"option_chat","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChatOptions","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)ChatOptions"}],"roleHeading":"Instance Property","symbolKind":"property"},"abstract":[{"type":"text","text":"The option of chat sdk function."}],"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatUIKitOptions\/option_chat","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"option_chat","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatOptions","text":"ChatOptions","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)ChatOptions"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatUIKitOptions/option_chat":{"abstract":[{"type":"text","text":"The option of chat sdk function."}],"title":"option_chat","type":"topic","role":"symbol","url":"\/documentation\/shengwangchatuikit\/chatuikitoptions\/option_chat","kind":"symbol","navigatorTitle":[{"text":"option_chat","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatUIKitOptions\/option_chat","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"option_chat","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)ChatOptions","text":"ChatOptions"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatOptions":{"type":"topic","kind":"symbol","url":"\/documentation\/shengwangchatuikit\/chatoptions","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatOptions","navigatorTitle":[{"text":"ChatOptions","kind":"identifier"}],"role":"symbol","abstract":[],"title":"ChatOptions","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ChatOptions","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatUIKitOptions":{"type":"topic","role":"symbol","title":"ChatUIKitOptions","kind":"symbol","abstract":[],"navigatorTitle":[{"text":"ChatUIKitOptions","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/chatuikitoptions","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatUIKitOptions","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ChatUIKitOptions","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"option_chat"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"text":"option_chat","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"kind":"text","text":") "},{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatOptions","text":"ChatOptions","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)ChatOptions","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"option_chat","kind":"identifier"},{"kind":"text","text":";"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatUIKitOptions~1option_chat\/title","value":"option_chat","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatUIKitOptions~1option_chat\/fragments","op":"replace","value":[{"kind":"identifier","text":"option_chat"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatOptions\/title","value":"ChatOptions"},{"op":"replace","value":[{"text":"ChatOptions","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatOptions\/fragments"},{"value":[{"text":"ChatOptions","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatOptions\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatUIKitOptions\/title","value":"ChatUIKitOptions","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatUIKitOptions\/fragments","value":[{"kind":"identifier","text":"ChatUIKitOptions"}]},{"value":[{"kind":"identifier","text":"ChatUIKitOptions"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatUIKitOptions\/navigatorTitle"}]}]}