{"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"pullToRefresh","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"view"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)PullRefresher","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PullRefresher","text":"PullRefresher"},{"kind":"text","text":", "},{"text":"progressDidChange","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"progress"},{"kind":"text","text":": "},{"text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PullRefresherDelegate\/pullToRefresh(_:progressDidChange:)"},"variants":[{"paths":["\/documentation\/shengwangchatuikit\/pullrefresherdelegate\/pulltorefresh(_:progressdidchange:)"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PullRefresherDelegate"]]},"kind":"symbol","metadata":{"symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pullToRefresh","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"PullRefresher","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)PullRefresher"},{"text":", ","kind":"text"},{"text":"progressDidChange","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"},{"kind":"text","text":")"}],"required":true,"role":"symbol","externalID":"s:18ShengwangChatUIKit21PullRefresherDelegateP13pullToRefresh_17progressDidChangeyAA0dE0C_14CoreFoundation7CGFloatVtF","title":"pullToRefresh(_:progressDidChange:)","roleHeading":"Instance Method","modules":[{"name":"ShengwangChatUIKit"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/PullRefresherDelegate":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PullRefresherDelegate","navigatorTitle":[{"kind":"identifier","text":"PullRefresherDelegate"}],"url":"\/documentation\/shengwangchatuikit\/pullrefresherdelegate","type":"topic","abstract":[],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PullRefresherDelegate","kind":"identifier"}],"title":"PullRefresherDelegate","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/PullRefresherDelegate/pullToRefresh(_:progressDidChange:)":{"kind":"symbol","url":"\/documentation\/shengwangchatuikit\/pullrefresherdelegate\/pulltorefresh(_:progressdidchange:)","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PullRefresherDelegate\/pullToRefresh(_:progressDidChange:)","type":"topic","required":true,"title":"pullToRefresh(_:progressDidChange:)","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"pullToRefresh"},{"kind":"text","text":"("},{"text":"PullRefresher","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)PullRefresher","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"progressDidChange"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"},{"kind":"text","text":")"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/PullRefresher":{"url":"\/documentation\/shengwangchatuikit\/pullrefresher","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PullRefresher"}],"abstract":[],"role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PullRefresher","title":"PullRefresher","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"PullRefresher","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"PullRefresher","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PullRefresher\/title"},{"value":[{"kind":"identifier","text":"PullRefresher"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PullRefresher\/fragments"},{"value":[{"text":"PullRefresher","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PullRefresher\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}