{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"pullToRefresh"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"view"},{"text":": ","kind":"text"},{"text":"PullRefresher","kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)PullRefresher","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PullRefresher"},{"kind":"text","text":", "},{"kind":"externalParam","text":"stateDidChange"},{"kind":"text","text":" "},{"text":"state","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"PullRefresherState","preciseIdentifier":"s:18ShengwangChatUIKit18PullRefresherStateO","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PullRefresherState","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"]}]}],"metadata":{"required":true,"externalID":"s:18ShengwangChatUIKit21PullRefresherDelegateP13pullToRefresh_14stateDidChangeyAA0dE0C_AA0dE5StateOtF","title":"pullToRefresh(_:stateDidChange:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pullToRefresh","kind":"identifier"},{"kind":"text","text":"("},{"text":"PullRefresher","kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)PullRefresher"},{"kind":"text","text":", "},{"kind":"externalParam","text":"stateDidChange"},{"text":": ","kind":"text"},{"text":"PullRefresherState","kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit18PullRefresherStateO"},{"kind":"text","text":")"}],"modules":[{"name":"ShengwangChatUIKit"}],"role":"symbol","symbolKind":"method","roleHeading":"Instance Method"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/pullrefresherdelegate\/pulltorefresh(_:statedidchange:)"]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PullRefresherDelegate\/pullToRefresh(_:stateDidChange:)"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PullRefresherDelegate"]]},"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/PullRefresherDelegate":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PullRefresherDelegate","navigatorTitle":[{"kind":"identifier","text":"PullRefresherDelegate"}],"url":"\/documentation\/shengwangchatuikit\/pullrefresherdelegate","type":"topic","abstract":[],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PullRefresherDelegate","kind":"identifier"}],"title":"PullRefresherDelegate","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/PullRefresher":{"url":"\/documentation\/shengwangchatuikit\/pullrefresher","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PullRefresher"}],"abstract":[],"role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PullRefresher","title":"PullRefresher","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"PullRefresher","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/PullRefresherDelegate/pullToRefresh(_:stateDidChange:)":{"url":"\/documentation\/shengwangchatuikit\/pullrefresherdelegate\/pulltorefresh(_:statedidchange:)","required":true,"title":"pullToRefresh(_:stateDidChange:)","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PullRefresherDelegate\/pullToRefresh(_:stateDidChange:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"pullToRefresh","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)PullRefresher","text":"PullRefresher"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"stateDidChange"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:18ShengwangChatUIKit18PullRefresherStateO","kind":"typeIdentifier","text":"PullRefresherState"},{"kind":"text","text":")"}],"type":"topic","kind":"symbol","abstract":[]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/PullRefresherState":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PullRefresherState","title":"PullRefresherState","navigatorTitle":[{"kind":"identifier","text":"PullRefresherState"}],"url":"\/documentation\/shengwangchatuikit\/pullrefresherstate","role":"symbol","kind":"symbol","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"PullRefresherState","kind":"identifier"}],"abstract":[]}},"variantOverrides":[{"patch":[{"op":"replace","value":"PullRefresher","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PullRefresher\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PullRefresher\/fragments","value":[{"text":"PullRefresher","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PullRefresher\/navigatorTitle","value":[{"kind":"identifier","text":"PullRefresher"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}