{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PullRefresherDelegate\/pullToRefreshAnimationDidEnd(_:)"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"pullToRefreshAnimationDidEnd"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"view","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"PullRefresher","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PullRefresher","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)PullRefresher"},{"kind":"text","text":")"}]}],"kind":"declarations"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PullRefresherDelegate"]]},"sections":[],"metadata":{"role":"symbol","externalID":"s:18ShengwangChatUIKit21PullRefresherDelegateP28pullToRefreshAnimationDidEndyyAA0dE0CF","roleHeading":"Instance Method","title":"pullToRefreshAnimationDidEnd(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pullToRefreshAnimationDidEnd","kind":"identifier"},{"kind":"text","text":"("},{"text":"PullRefresher","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)PullRefresher","kind":"typeIdentifier"},{"text":")","kind":"text"}],"modules":[{"name":"ShengwangChatUIKit"}],"symbolKind":"method","required":true},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/pullrefresherdelegate\/pulltorefreshanimationdidend(_:)"]}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/PullRefresherDelegate":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PullRefresherDelegate","navigatorTitle":[{"kind":"identifier","text":"PullRefresherDelegate"}],"url":"\/documentation\/shengwangchatuikit\/pullrefresherdelegate","type":"topic","abstract":[],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PullRefresherDelegate","kind":"identifier"}],"title":"PullRefresherDelegate","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/PullRefresherDelegate/pullToRefreshAnimationDidEnd(_:)":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PullRefresherDelegate\/pullToRefreshAnimationDidEnd(_:)","abstract":[],"url":"\/documentation\/shengwangchatuikit\/pullrefresherdelegate\/pulltorefreshanimationdidend(_:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"pullToRefreshAnimationDidEnd"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)PullRefresher","text":"PullRefresher"},{"kind":"text","text":")"}],"role":"symbol","title":"pullToRefreshAnimationDidEnd(_:)","required":true,"kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/PullRefresher":{"url":"\/documentation\/shengwangchatuikit\/pullrefresher","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PullRefresher"}],"abstract":[],"role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PullRefresher","title":"PullRefresher","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"PullRefresher","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PullRefresher\/title","value":"PullRefresher"},{"value":[{"kind":"identifier","text":"PullRefresher"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PullRefresher\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PullRefresher\/navigatorTitle","op":"replace","value":[{"text":"PullRefresher","kind":"identifier"}]}]}]}