{"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PinnedMessagesContainer\/tableView(_:numberOfRowsInSection:)","interfaceLanguage":"swift"},"metadata":{"extendedModule":"ShengwangChatUIKit","role":"symbol","externalID":"c:@CM@ShengwangChatUIKit@objc(cs)PinnedMessagesContainer(im)tableView:numberOfRowsInSection:","roleHeading":"Instance Method","modules":[{"name":"ShengwangChatUIKit"}],"symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"tableView","kind":"identifier"},{"kind":"text","text":"("},{"text":"UITableView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITableView"},{"text":", ","kind":"text"},{"text":"numberOfRowsInSection","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"title":"tableView(_:numberOfRowsInSection:)","navigatorTitle":[{"text":"tableView:numberOfRowsInSection:","kind":"identifier"}]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tableView"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"tableView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITableView","text":"UITableView"},{"kind":"text","text":", "},{"text":"numberOfRowsInSection","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"section"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"languages":["swift"],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PinnedMessagesContainer","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PinnedMessagesContainer\/UITableViewDataSource-Implementations"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/pinnedmessagescontainer\/tableview(_:numberofrowsinsection:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/pinnedmessagescontainer\/tableview(_:numberofrowsinsection:)"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"UITableViewDataSource.tableView(_:numberOfRowsInSection:)"},{"type":"text","text":"."}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/PinnedMessagesContainer/UITableViewDataSource-Implementations":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PinnedMessagesContainer\/UITableViewDataSource-Implementations","title":"UITableViewDataSource Implementations","url":"\/documentation\/shengwangchatuikit\/pinnedmessagescontainer\/uitableviewdatasource-implementations","role":"collectionGroup","kind":"article","type":"topic","abstract":[]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/PinnedMessagesContainer":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PinnedMessagesContainer","title":"PinnedMessagesContainer","navigatorTitle":[{"kind":"identifier","text":"PinnedMessagesContainer"}],"url":"\/documentation\/shengwangchatuikit\/pinnedmessagescontainer","role":"symbol","kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PinnedMessagesContainer","kind":"identifier"}],"abstract":[]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/PinnedMessagesContainer/tableView(_:numberOfRowsInSection:)":{"role":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"tableView"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UITableView","kind":"typeIdentifier","text":"UITableView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"numberOfRowsInSection"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"kind":"symbol","abstract":[],"url":"\/documentation\/shengwangchatuikit\/pinnedmessagescontainer\/tableview(_:numberofrowsinsection:)","title":"tableView(_:numberOfRowsInSection:)","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PinnedMessagesContainer\/tableView(_:numberOfRowsInSection:)","navigatorTitle":[{"text":"tableView:numberOfRowsInSection:","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"tableView:numberOfRowsInSection:"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"tableView:numberOfRowsInSection:"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier","text":"NSInteger"},{"kind":"text","text":") "},{"text":"tableView:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITableView","text":"UITableView"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"tableView"},{"kind":"text","text":" "},{"text":"numberOfRowsInSection:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"section"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace"},{"op":"replace","value":"PinnedMessagesContainer","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PinnedMessagesContainer\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PinnedMessagesContainer\/fragments","op":"replace","value":[{"text":"PinnedMessagesContainer","kind":"identifier"}]},{"op":"replace","value":[{"text":"PinnedMessagesContainer","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PinnedMessagesContainer\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PinnedMessagesContainer~1tableView(_:numberOfRowsInSection:)\/title","value":"tableView:numberOfRowsInSection:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"tableView:numberOfRowsInSection:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PinnedMessagesContainer~1tableView(_:numberOfRowsInSection:)\/fragments"}]}]}