{"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"touchesEnded"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"touches","kind":"internalParam"},{"kind":"text","text":": "},{"text":"Set","kind":"typeIdentifier","preciseIdentifier":"s:Sh"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITouch","text":"UITouch"},{"kind":"text","text":">, "},{"text":"with","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"event"},{"text":": ","kind":"text"},{"text":"UIEvent","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIEvent"},{"kind":"text","text":"?)"}]}]}],"variants":[{"paths":["\/documentation\/shengwangchatuikit\/pinnedmessagescontainer\/touchesended(_:with:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/shengwangchatuikit\/pinnedmessagescontainer\/touchesended(_:with:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"role":"symbol","roleHeading":"Instance Method","modules":[{"name":"ShengwangChatUIKit"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"touchesEnded","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:Sh","kind":"typeIdentifier","text":"Set"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:objc(cs)UITouch","text":"UITouch","kind":"typeIdentifier"},{"kind":"text","text":">, "},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIEvent","preciseIdentifier":"c:objc(cs)UIEvent","kind":"typeIdentifier"},{"kind":"text","text":"?)"}],"navigatorTitle":[{"kind":"identifier","text":"touchesEnded:withEvent:"}],"symbolKind":"method","title":"touchesEnded(_:with:)","externalID":"c:@M@ShengwangChatUIKit@objc(cs)PinnedMessagesContainer(im)touchesEnded:withEvent:"},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PinnedMessagesContainer\/touchesEnded(_:with:)"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PinnedMessagesContainer"]]},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/PinnedMessagesContainer/touchesEnded(_:with:)":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PinnedMessagesContainer\/touchesEnded(_:with:)","title":"touchesEnded(_:with:)","navigatorTitle":[{"text":"touchesEnded:withEvent:","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/pinnedmessagescontainer\/touchesended(_:with:)","role":"symbol","kind":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"touchesEnded","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sh","text":"Set"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:objc(cs)UITouch","text":"UITouch","kind":"typeIdentifier"},{"kind":"text","text":">, "},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIEvent","text":"UIEvent","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"abstract":[]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/PinnedMessagesContainer":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PinnedMessagesContainer","title":"PinnedMessagesContainer","navigatorTitle":[{"kind":"identifier","text":"PinnedMessagesContainer"}],"url":"\/documentation\/shengwangchatuikit\/pinnedmessagescontainer","role":"symbol","kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PinnedMessagesContainer","kind":"identifier"}],"abstract":[]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"touchesEnded:withEvent:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"touchesEnded:withEvent:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"touchesEnded:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSSet","text":"NSSet<UITouch *>","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"touches","kind":"internalParam"},{"kind":"text","text":" "},{"text":"withEvent:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIEvent","kind":"typeIdentifier","text":"UIEvent"},{"kind":"text","text":" *) "},{"text":"event","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PinnedMessagesContainer~1touchesEnded(_:with:)\/title","value":"touchesEnded:withEvent:"},{"value":[{"text":"- ","kind":"text"},{"text":"touchesEnded:withEvent:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PinnedMessagesContainer~1touchesEnded(_:with:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PinnedMessagesContainer\/title","op":"replace","value":"PinnedMessagesContainer"},{"value":[{"text":"PinnedMessagesContainer","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PinnedMessagesContainer\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PinnedMessagesContainer\/navigatorTitle","value":[{"text":"PinnedMessagesContainer","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}