{"sections":[],"metadata":{"externalID":"s:18ShengwangChatUIKit20MessageLongPressMenuC06hiddenG0yyF","roleHeading":"Instance Method","symbolKind":"method","role":"symbol","modules":[{"name":"ShengwangChatUIKit"}],"title":"hiddenMenu()","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"hiddenMenu","kind":"identifier"},{"kind":"text","text":"()"}]},"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageLongPressMenu\/hiddenMenu()","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hiddenMenu","kind":"identifier"},{"text":"()","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/shengwangchatuikit\/messagelongpressmenu\/hiddenmenu()"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageLongPressMenu"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageLongPressMenu/hiddenMenu()":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageLongPressMenu\/hiddenMenu()","title":"hiddenMenu()","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"hiddenMenu","kind":"identifier"},{"text":"()","kind":"text"}],"url":"\/documentation\/shengwangchatuikit\/messagelongpressmenu\/hiddenmenu()","abstract":[]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageLongPressMenu":{"title":"MessageLongPressMenu","navigatorTitle":[{"kind":"identifier","text":"MessageLongPressMenu"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageLongPressMenu","type":"topic","url":"\/documentation\/shengwangchatuikit\/messagelongpressmenu","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MessageLongPressMenu","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageLongPressMenu\/title","value":"MessageLongPressMenu","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageLongPressMenu\/fragments","value":[{"kind":"identifier","text":"MessageLongPressMenu"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageLongPressMenu\/navigatorTitle","value":[{"text":"MessageLongPressMenu","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}