{"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageLongPressMenu\/popArrow","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"popArrow","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)PopMenuArrow","text":"PopMenuArrow"}],"externalID":"s:18ShengwangChatUIKit20MessageLongPressMenuC8popArrowAA03PopgI0Cvp","modules":[{"name":"ShengwangChatUIKit"}],"roleHeading":"Instance Property","symbolKind":"property","title":"popArrow","role":"symbol"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageLongPressMenu"]]},"sections":[],"variants":[{"paths":["\/documentation\/shengwangchatuikit\/messagelongpressmenu\/poparrow"],"traits":[{"interfaceLanguage":"swift"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"text":" ","kind":"text"},{"kind":"keyword","text":"lazy"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"popArrow"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PopMenuArrow","text":"PopMenuArrow","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)PopMenuArrow","kind":"typeIdentifier"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"kind":"symbol","references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/PopMenuArrow":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PopMenuArrow"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PopMenuArrow","title":"PopMenuArrow","abstract":[],"role":"symbol","kind":"symbol","url":"\/documentation\/shengwangchatuikit\/popmenuarrow","navigatorTitle":[{"kind":"identifier","text":"PopMenuArrow"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageLongPressMenu/popArrow":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"popArrow","kind":"identifier"},{"text":": ","kind":"text"},{"text":"PopMenuArrow","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)PopMenuArrow","kind":"typeIdentifier"}],"url":"\/documentation\/shengwangchatuikit\/messagelongpressmenu\/poparrow","abstract":[],"kind":"symbol","title":"popArrow","type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageLongPressMenu\/popArrow"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageLongPressMenu":{"title":"MessageLongPressMenu","navigatorTitle":[{"kind":"identifier","text":"MessageLongPressMenu"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageLongPressMenu","type":"topic","url":"\/documentation\/shengwangchatuikit\/messagelongpressmenu","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MessageLongPressMenu","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"PopMenuArrow","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PopMenuArrow\/title"},{"value":[{"text":"PopMenuArrow","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PopMenuArrow\/fragments"},{"op":"replace","value":[{"text":"PopMenuArrow","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PopMenuArrow\/navigatorTitle"},{"op":"replace","value":"MessageLongPressMenu","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageLongPressMenu\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageLongPressMenu\/fragments","op":"replace","value":[{"text":"MessageLongPressMenu","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageLongPressMenu\/navigatorTitle","value":[{"text":"MessageLongPressMenu","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}