{"metadata":{"role":"collectionGroup","title":"UICollectionViewDelegate Implementations","roleHeading":"API Collection","modules":[{"name":"ShengwangChatUIKit"}]},"topicSections":[{"anchor":"Instance-Methods","title":"Instance Methods","generated":true,"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageLongPressMenu\/collectionView(_:didSelectItemAt:)"]}],"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageLongPressMenu\/UICollectionViewDelegate-Implementations","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageLongPressMenu"]]},"kind":"article","variants":[{"paths":["\/documentation\/shengwangchatuikit\/messagelongpressmenu\/uicollectionviewdelegate-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/messagelongpressmenu\/uicollectionviewdelegate-implementations"]}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageLongPressMenu/collectionView(_:didSelectItemAt:)":{"navigatorTitle":[{"text":"collectionView:didSelectItemAtIndexPath:","kind":"identifier"}],"title":"collectionView(_:didSelectItemAt:)","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageLongPressMenu\/collectionView(_:didSelectItemAt:)","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"collectionView","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UICollectionView","text":"UICollectionView","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didSelectItemAt"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation9IndexPathV","kind":"typeIdentifier","text":"IndexPath"},{"text":")","kind":"text"}],"type":"topic","abstract":[],"url":"\/documentation\/shengwangchatuikit\/messagelongpressmenu\/collectionview(_:didselectitemat:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageLongPressMenu":{"title":"MessageLongPressMenu","navigatorTitle":[{"kind":"identifier","text":"MessageLongPressMenu"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageLongPressMenu","type":"topic","url":"\/documentation\/shengwangchatuikit\/messagelongpressmenu","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MessageLongPressMenu","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":[{"generated":true,"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageLongPressMenu\/collectionView(_:didSelectItemAt:)"]}],"path":"\/topicSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageLongPressMenu~1collectionView(_:didSelectItemAt:)\/title","value":"collectionView:didSelectItemAtIndexPath:"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageLongPressMenu~1collectionView(_:didSelectItemAt:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"collectionView:didSelectItemAtIndexPath:"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageLongPressMenu\/title","value":"MessageLongPressMenu","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"MessageLongPressMenu"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageLongPressMenu\/fragments"},{"value":[{"text":"MessageLongPressMenu","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageLongPressMenu\/navigatorTitle"}]}]}