{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatServiceImplement"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"article","metadata":{"modules":[{"name":"ShengwangChatUIKit"}],"roleHeading":"API Collection","role":"collectionGroup","title":"ChatService Implementations"},"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatServiceImplement\/ChatService-Implementations","interfaceLanguage":"swift"},"topicSections":[{"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatServiceImplement\/bindChatEventsListener(listener:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatServiceImplement\/edit(messageId:text:completion:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatServiceImplement\/fetchChatThreadHistoryMessages(conversationId:start:pageSize:completion:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatServiceImplement\/loadMessages(start:pageSize:searchMessage:completion:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatServiceImplement\/markAllMessagesAsRead()","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatServiceImplement\/markMessageAsRead(messageId:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatServiceImplement\/pinMessage(messageId:completion:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatServiceImplement\/pinnedMessages(conversationId:completion:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatServiceImplement\/reaction(reaction:message:completion:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatServiceImplement\/recall(messageId:completion:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatServiceImplement\/removeHistoryMessages()","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatServiceImplement\/removeLocalMessage(messageId:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatServiceImplement\/searchMessage(keyword:pageSize:userId:completion:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatServiceImplement\/send(message:completion:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatServiceImplement\/translateMessage(message:completion:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatServiceImplement\/unbindChatEventsListener(listener:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatServiceImplement\/unpinMessage(messageId:completion:)"],"generated":true,"anchor":"Instance-Methods","title":"Instance Methods"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/chatserviceimplement\/chatservice-implementations"]},{"paths":["\/documentation\/shengwangchatuikit\/chatserviceimplement\/chatservice-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatServiceImplement/unbindChatEventsListener(listener:)":{"url":"\/documentation\/shengwangchatuikit\/chatserviceimplement\/unbindchateventslistener(listener:)","navigatorTitle":[{"text":"unbindChatEventsListenerWithListener:","kind":"identifier"}],"kind":"symbol","title":"unbindChatEventsListener(listener:)","type":"topic","abstract":[{"type":"text","text":"Unbind message changed listener"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"unbindChatEventsListener"},{"kind":"text","text":"("},{"kind":"externalParam","text":"listener"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(pl)ChatResponseListener","text":"ChatResponseListener","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatServiceImplement\/unbindChatEventsListener(listener:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatServiceImplement/recall(messageId:completion:)":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatServiceImplement\/recall(messageId:completion:)","url":"\/documentation\/shengwangchatuikit\/chatserviceimplement\/recall(messageid:completion:)","abstract":[{"text":"Recall a message succeed.","type":"text"}],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"recall","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"messageId"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"text":": (","kind":"text"},{"text":"ChatError","preciseIdentifier":"s:18ShengwangChatUIKit0B5Errora","kind":"typeIdentifier"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","title":"recall(messageId:completion:)","navigatorTitle":[{"text":"recallWithMessageId:completion:","kind":"identifier"}],"kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatServiceImplement/pinnedMessages(conversationId:completion:)":{"abstract":[{"text":"Get all of the stickied messages.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"pinnedMessages","kind":"identifier"},{"kind":"text","text":"("},{"text":"conversationId","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": (["},{"kind":"typeIdentifier","text":"ChatMessage","preciseIdentifier":"s:18ShengwangChatUIKit0B7Messagea"},{"kind":"text","text":"]?, "},{"kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit0B5Errora","text":"ChatError"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"kind":"text","text":")"}],"title":"pinnedMessages(conversationId:completion:)","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatServiceImplement\/pinnedMessages(conversationId:completion:)","url":"\/documentation\/shengwangchatuikit\/chatserviceimplement\/pinnedmessages(conversationid:completion:)","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"pinnedMessagesWithConversationId:completion:","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatServiceImplement":{"navigatorTitle":[{"text":"ChatServiceImplement","kind":"identifier"}],"abstract":[],"kind":"symbol","url":"\/documentation\/shengwangchatuikit\/chatserviceimplement","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChatServiceImplement"}],"type":"topic","title":"ChatServiceImplement","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatServiceImplement"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatServiceImplement/unpinMessage(messageId:completion:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"unpinMessage","kind":"identifier"},{"kind":"text","text":"("},{"text":"messageId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": (","kind":"text"},{"text":"ChatError","kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit0B5Errora"},{"kind":"text","text":"?) -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"url":"\/documentation\/shengwangchatuikit\/chatserviceimplement\/unpinmessage(messageid:completion:)","abstract":[{"type":"text","text":"Remove the stickied message."}],"kind":"symbol","title":"unpinMessage(messageId:completion:)","type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatServiceImplement\/unpinMessage(messageId:completion:)","navigatorTitle":[{"text":"unpinMessageWithMessageId:completion:","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatServiceImplement/searchMessage(keyword:pageSize:userId:completion:)":{"navigatorTitle":[{"kind":"identifier","text":"searchMessageWithKeyword:pageSize:userId:completion:"}],"title":"searchMessage(keyword:pageSize:userId:completion:)","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatServiceImplement\/searchMessage(keyword:pageSize:userId:completion:)","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"searchMessage"},{"text":"(","kind":"text"},{"text":"keyword","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"pageSize"},{"text":": ","kind":"text"},{"text":"UInt","preciseIdentifier":"s:Su","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"userId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"preciseIdentifier":"s:18ShengwangChatUIKit0B5Errora","text":"ChatError","kind":"typeIdentifier"},{"text":"?, [","kind":"text"},{"preciseIdentifier":"s:18ShengwangChatUIKit0B7Messagea","text":"ChatMessage","kind":"typeIdentifier"},{"text":"]) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")","kind":"text"}],"type":"topic","abstract":[{"type":"text","text":"Search message from database."}],"url":"\/documentation\/shengwangchatuikit\/chatserviceimplement\/searchmessage(keyword:pagesize:userid:completion:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatServiceImplement/markAllMessagesAsRead()":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatServiceImplement\/markAllMessagesAsRead()","url":"\/documentation\/shengwangchatuikit\/chatserviceimplement\/markallmessagesasread()","abstract":[{"text":"Mark all of the history messages as already read.","type":"text"}],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"markAllMessagesAsRead"},{"kind":"text","text":"()"}],"role":"symbol","title":"markAllMessagesAsRead()","navigatorTitle":[{"text":"markAllMessagesAsRead","kind":"identifier"}],"kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatServiceImplement/edit(messageId:text:completion:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"edit","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"messageId"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"text"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"text":"ChatError","kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit0B5Errora"},{"kind":"text","text":"?, "},{"preciseIdentifier":"s:18ShengwangChatUIKit0B7Messagea","text":"ChatMessage","kind":"typeIdentifier"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"url":"\/documentation\/shengwangchatuikit\/chatserviceimplement\/edit(messageid:text:completion:)","title":"edit(messageId:text:completion:)","abstract":[{"text":"Edit text message content.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatServiceImplement\/edit(messageId:text:completion:)","type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"editWithMessageId:text:completion:"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatServiceImplement/send(message:completion:)":{"role":"symbol","kind":"symbol","abstract":[{"text":"Send message to someone.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatServiceImplement\/send(message:completion:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"send","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"message"},{"text":": ","kind":"text"},{"text":"ChatMessage","preciseIdentifier":"s:18ShengwangChatUIKit0B7Messagea","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit0B5Errora","text":"ChatError"},{"text":"?, ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit0B7Messagea","text":"ChatMessage"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"sendWithMessage:completion:"}],"type":"topic","url":"\/documentation\/shengwangchatuikit\/chatserviceimplement\/send(message:completion:)","title":"send(message:completion:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatServiceImplement/loadMessages(start:pageSize:searchMessage:completion:)":{"url":"\/documentation\/shengwangchatuikit\/chatserviceimplement\/loadmessages(start:pagesize:searchmessage:completion:)","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatServiceImplement\/loadMessages(start:pageSize:searchMessage:completion:)","title":"loadMessages(start:pageSize:searchMessage:completion:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"loadMessages"},{"text":"(","kind":"text"},{"text":"start","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"pageSize"},{"kind":"text","text":": "},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"},{"kind":"text","text":", "},{"kind":"externalParam","text":"searchMessage"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": ("},{"text":"ChatError","kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit0B5Errora"},{"kind":"text","text":"?, ["},{"kind":"typeIdentifier","text":"ChatMessage","preciseIdentifier":"s:18ShengwangChatUIKit0B7Messagea"},{"text":"]) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"loadMessagesWithStart:pageSize:searchMessage:completion:"}],"type":"topic","abstract":[{"text":"Load messages from database.","type":"text"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatServiceImplement/bindChatEventsListener(listener:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"bindChatEventsListener","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"listener"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(pl)ChatResponseListener","text":"ChatResponseListener"},{"text":")","kind":"text"}],"kind":"symbol","url":"\/documentation\/shengwangchatuikit\/chatserviceimplement\/bindchateventslistener(listener:)","type":"topic","title":"bindChatEventsListener(listener:)","abstract":[{"type":"text","text":"Bind message changed listener"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatServiceImplement\/bindChatEventsListener(listener:)","navigatorTitle":[{"text":"bindChatEventsListenerWithListener:","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatServiceImplement/fetchChatThreadHistoryMessages(conversationId:start:pageSize:completion:)":{"type":"topic","role":"symbol","title":"fetchChatThreadHistoryMessages(conversationId:start:pageSize:completion:)","kind":"symbol","abstract":[{"text":"Load messages from server.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"fetchChatThreadHistoryMessagesWithConversationId:start:pageSize:completion:"}],"url":"\/documentation\/shengwangchatuikit\/chatserviceimplement\/fetchchatthreadhistorymessages(conversationid:start:pagesize:completion:)","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatServiceImplement\/fetchChatThreadHistoryMessages(conversationId:start:pageSize:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"fetchChatThreadHistoryMessages","kind":"identifier"},{"text":"(","kind":"text"},{"text":"conversationId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"start","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"pageSize"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": ("},{"preciseIdentifier":"s:18ShengwangChatUIKit0B5Errora","kind":"typeIdentifier","text":"ChatError"},{"text":"?, [","kind":"text"},{"preciseIdentifier":"s:18ShengwangChatUIKit0B7Messagea","text":"ChatMessage","kind":"typeIdentifier"},{"text":"]) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatServiceImplement/markMessageAsRead(messageId:)":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatServiceImplement\/markMessageAsRead(messageId:)","url":"\/documentation\/shengwangchatuikit\/chatserviceimplement\/markmessageasread(messageid:)","abstract":[{"text":"Mark a message as already read state.","type":"text"}],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"markMessageAsRead","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"messageId"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":")"}],"role":"symbol","title":"markMessageAsRead(messageId:)","navigatorTitle":[{"text":"markMessageAsReadWithMessageId:","kind":"identifier"}],"kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatServiceImplement/removeLocalMessage(messageId:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"removeLocalMessage","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"messageId"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Remove a message from database."}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatServiceImplement\/removeLocalMessage(messageId:)","type":"topic","kind":"symbol","title":"removeLocalMessage(messageId:)","url":"\/documentation\/shengwangchatuikit\/chatserviceimplement\/removelocalmessage(messageid:)","navigatorTitle":[{"text":"removeLocalMessageWithMessageId:","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatServiceImplement/reaction(reaction:message:completion:)":{"type":"topic","role":"symbol","title":"reaction(reaction:message:completion:)","kind":"symbol","abstract":[{"type":"text","text":"Operation reaction api."}],"navigatorTitle":[{"text":"reactionWithReaction:message:completion:","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/chatserviceimplement\/reaction(reaction:message:completion:)","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatServiceImplement\/reaction(reaction:message:completion:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"reaction"},{"kind":"text","text":"("},{"text":"reaction","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"message","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"ChatMessage","preciseIdentifier":"s:18ShengwangChatUIKit0B7Messagea"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": (","kind":"text"},{"text":"ChatError","preciseIdentifier":"s:18ShengwangChatUIKit0B5Errora","kind":"typeIdentifier"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatServiceImplement/pinMessage(messageId:completion:)":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatServiceImplement\/pinMessage(messageId:completion:)","url":"\/documentation\/shengwangchatuikit\/chatserviceimplement\/pinmessage(messageid:completion:)","abstract":[{"text":"Stickied a message on top.","type":"text"}],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"pinMessage","kind":"identifier"},{"text":"(","kind":"text"},{"text":"messageId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit0B5Errora","text":"ChatError"},{"text":"?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"role":"symbol","title":"pinMessage(messageId:completion:)","navigatorTitle":[{"kind":"identifier","text":"pinMessageWithMessageId:completion:"}],"kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatServiceImplement/translateMessage(message:completion:)":{"navigatorTitle":[{"text":"translateMessageWithMessage:completion:","kind":"identifier"}],"type":"topic","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"translateMessage"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"message"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:18ShengwangChatUIKit0B7Messagea","text":"ChatMessage","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": ("},{"preciseIdentifier":"s:18ShengwangChatUIKit0B5Errora","kind":"typeIdentifier","text":"ChatError"},{"kind":"text","text":"?, "},{"text":"ChatMessage","kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit0B7Messagea"},{"text":"?) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"kind":"text","text":")"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatServiceImplement\/translateMessage(message:completion:)","url":"\/documentation\/shengwangchatuikit\/chatserviceimplement\/translatemessage(message:completion:)","title":"translateMessage(message:completion:)","abstract":[{"type":"text","text":"Translate the message text."}],"kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatServiceImplement/removeHistoryMessages()":{"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"removeHistoryMessages"}],"title":"removeHistoryMessages()","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatServiceImplement\/removeHistoryMessages()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeHistoryMessages"},{"text":"()","kind":"text"}],"abstract":[{"type":"text","text":"Remove all of the history messages from database."}],"type":"topic","url":"\/documentation\/shengwangchatuikit\/chatserviceimplement\/removehistorymessages()"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/topicSections","value":[{"generated":true,"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatServiceImplement\/bindChatEventsListener(listener:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatServiceImplement\/edit(messageId:text:completion:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatServiceImplement\/fetchChatThreadHistoryMessages(conversationId:start:pageSize:completion:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatServiceImplement\/loadMessages(start:pageSize:searchMessage:completion:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatServiceImplement\/markAllMessagesAsRead()","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatServiceImplement\/markMessageAsRead(messageId:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatServiceImplement\/pinMessage(messageId:completion:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatServiceImplement\/pinnedMessages(conversationId:completion:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatServiceImplement\/reaction(reaction:message:completion:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatServiceImplement\/recall(messageId:completion:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatServiceImplement\/removeHistoryMessages()","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatServiceImplement\/removeLocalMessage(messageId:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatServiceImplement\/searchMessage(keyword:pageSize:userId:completion:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatServiceImplement\/send(message:completion:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatServiceImplement\/translateMessage(message:completion:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatServiceImplement\/unbindChatEventsListener(listener:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatServiceImplement\/unpinMessage(messageId:completion:)"],"anchor":"Instance-Methods","title":"Instance Methods"}],"op":"replace"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":"unbindChatEventsListenerWithListener:","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatServiceImplement~1unbindChatEventsListener(listener:)\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"unbindChatEventsListenerWithListener:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatServiceImplement~1unbindChatEventsListener(listener:)\/fragments"},{"op":"replace","value":"recallWithMessageId:completion:","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatServiceImplement~1recall(messageId:completion:)\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"recallWithMessageId:completion:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatServiceImplement~1recall(messageId:completion:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatServiceImplement~1pinnedMessages(conversationId:completion:)\/title","value":"pinnedMessagesWithConversationId:completion:"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatServiceImplement~1pinnedMessages(conversationId:completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"pinnedMessagesWithConversationId:completion:"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatServiceImplement\/title","value":"ChatServiceImplement","op":"replace"},{"value":[{"kind":"identifier","text":"ChatServiceImplement"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatServiceImplement\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatServiceImplement\/navigatorTitle","value":[{"text":"ChatServiceImplement","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatServiceImplement~1unpinMessage(messageId:completion:)\/title","value":"unpinMessageWithMessageId:completion:"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatServiceImplement~1unpinMessage(messageId:completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"unpinMessageWithMessageId:completion:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatServiceImplement~1searchMessage(keyword:pageSize:userId:completion:)\/title","value":"searchMessageWithKeyword:pageSize:userId:completion:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatServiceImplement~1searchMessage(keyword:pageSize:userId:completion:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"searchMessageWithKeyword:pageSize:userId:completion:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatServiceImplement~1markAllMessagesAsRead()\/title","value":"markAllMessagesAsRead","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"markAllMessagesAsRead"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatServiceImplement~1markAllMessagesAsRead()\/fragments"},{"value":"editWithMessageId:text:completion:","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatServiceImplement~1edit(messageId:text:completion:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"editWithMessageId:text:completion:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatServiceImplement~1edit(messageId:text:completion:)\/fragments"},{"value":"sendWithMessage:completion:","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatServiceImplement~1send(message:completion:)\/title","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"sendWithMessage:completion:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatServiceImplement~1send(message:completion:)\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatServiceImplement~1loadMessages(start:pageSize:searchMessage:completion:)\/title","value":"loadMessagesWithStart:pageSize:searchMessage:completion:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatServiceImplement~1loadMessages(start:pageSize:searchMessage:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"loadMessagesWithStart:pageSize:searchMessage:completion:"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatServiceImplement~1bindChatEventsListener(listener:)\/title","op":"replace","value":"bindChatEventsListenerWithListener:"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatServiceImplement~1bindChatEventsListener(listener:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"bindChatEventsListenerWithListener:","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"fetchChatThreadHistoryMessagesWithConversationId:start:pageSize:completion:","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatServiceImplement~1fetchChatThreadHistoryMessages(conversationId:start:pageSize:completion:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatServiceImplement~1fetchChatThreadHistoryMessages(conversationId:start:pageSize:completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"fetchChatThreadHistoryMessagesWithConversationId:start:pageSize:completion:","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatServiceImplement~1markMessageAsRead(messageId:)\/title","value":"markMessageAsReadWithMessageId:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatServiceImplement~1markMessageAsRead(messageId:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"markMessageAsReadWithMessageId:","kind":"identifier"}]},{"value":"removeLocalMessageWithMessageId:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatServiceImplement~1removeLocalMessage(messageId:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatServiceImplement~1removeLocalMessage(messageId:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"removeLocalMessageWithMessageId:"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatServiceImplement~1reaction(reaction:message:completion:)\/title","value":"reactionWithReaction:message:completion:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatServiceImplement~1reaction(reaction:message:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"reactionWithReaction:message:completion:"}]},{"value":"pinMessageWithMessageId:completion:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatServiceImplement~1pinMessage(messageId:completion:)\/title"},{"value":[{"kind":"text","text":"- "},{"text":"pinMessageWithMessageId:completion:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatServiceImplement~1pinMessage(messageId:completion:)\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatServiceImplement~1translateMessage(message:completion:)\/title","value":"translateMessageWithMessage:completion:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"translateMessageWithMessage:completion:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatServiceImplement~1translateMessage(message:completion:)\/fragments"},{"op":"replace","value":"removeHistoryMessages","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatServiceImplement~1removeHistoryMessages()\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatServiceImplement~1removeHistoryMessages()\/fragments","value":[{"kind":"text","text":"- "},{"text":"removeHistoryMessages","kind":"identifier"}],"op":"replace"}]}]}