{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatServiceImplement","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatServiceImplement\/AgoraChatManagerDelegate-Implementations"]]},"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatServiceImplement\/messageReactionDidChange(_:)","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"symbolKind":"method","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"messageReactionDidChange","kind":"identifier"},{"text":"([","kind":"text"},{"kind":"typeIdentifier","text":"MessageReactionChange","preciseIdentifier":"s:18ShengwangChatUIKit21MessageReactionChangea"},{"kind":"text","text":"])"}],"modules":[{"name":"ShengwangChatUIKit"}],"extendedModule":"ShengwangChatUIKit","navigatorTitle":[{"text":"messageReactionDidChange:","kind":"identifier"}],"externalID":"c:@CM@ShengwangChatUIKit@objc(cs)ChatServiceImplement(im)messageReactionDidChange:","role":"symbol","title":"messageReactionDidChange(_:)"},"variants":[{"paths":["\/documentation\/shengwangchatuikit\/chatserviceimplement\/messagereactiondidchange(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/shengwangchatuikit\/chatserviceimplement\/messagereactiondidchange(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"messageReactionDidChange","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"changes"},{"text":": [","kind":"text"},{"text":"MessageReactionChange","kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit21MessageReactionChangea","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageReactionChange"},{"kind":"text","text":"])"}],"platforms":["iOS"]}]}],"abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"AgoraChatManagerDelegate.messageReactionDidChange(_:)"},{"type":"text","text":"."}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatServiceImplement/messageReactionDidChange(_:)":{"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"messageReactionDidChange"},{"text":"([","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit21MessageReactionChangea","text":"MessageReactionChange"},{"kind":"text","text":"])"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatServiceImplement\/messageReactionDidChange(_:)","navigatorTitle":[{"text":"messageReactionDidChange:","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/chatserviceimplement\/messagereactiondidchange(_:)","abstract":[],"kind":"symbol","title":"messageReactionDidChange(_:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatServiceImplement/AgoraChatManagerDelegate-Implementations":{"abstract":[],"type":"topic","url":"\/documentation\/shengwangchatuikit\/chatserviceimplement\/agorachatmanagerdelegate-implementations","role":"collectionGroup","title":"AgoraChatManagerDelegate Implementations","kind":"article","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatServiceImplement\/AgoraChatManagerDelegate-Implementations"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatServiceImplement":{"navigatorTitle":[{"text":"ChatServiceImplement","kind":"identifier"}],"abstract":[],"kind":"symbol","url":"\/documentation\/shengwangchatuikit\/chatserviceimplement","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChatServiceImplement"}],"type":"topic","title":"ChatServiceImplement","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatServiceImplement"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageReactionChange":{"navigatorTitle":[{"text":"MessageReactionChange","kind":"identifier"}],"abstract":[],"url":"\/documentation\/shengwangchatuikit\/messagereactionchange","kind":"symbol","role":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MessageReactionChange"}],"type":"topic","title":"MessageReactionChange","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageReactionChange"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"messageReactionDidChange:","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"messageReactionDidChange:"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"messageReactionDidChange:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<AgoraChatMessageReactionChange *>","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"changes"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"op":"replace"},{"value":"messageReactionDidChange:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatServiceImplement~1messageReactionDidChange(_:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatServiceImplement~1messageReactionDidChange(_:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"messageReactionDidChange:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatServiceImplement\/title","op":"replace","value":"ChatServiceImplement"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatServiceImplement\/fragments","op":"replace","value":[{"text":"ChatServiceImplement","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"ChatServiceImplement"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatServiceImplement\/navigatorTitle"}]}]}