{"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatServiceImplement\/onConversationRead(_:to:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"code":"AgoraChatManagerDelegate.onConversationRead(_:to:)","type":"codeVoice"},{"text":".","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onConversationRead"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"from","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"to"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":")"}],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatServiceImplement","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatServiceImplement\/AgoraChatManagerDelegate-Implementations"]]},"kind":"symbol","sections":[],"metadata":{"symbolKind":"method","title":"onConversationRead(_:to:)","roleHeading":"Instance Method","extendedModule":"ShengwangChatUIKit","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onConversationRead"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"to","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}],"modules":[{"name":"ShengwangChatUIKit"}],"externalID":"c:@CM@ShengwangChatUIKit@objc(cs)ChatServiceImplement(im)onConversationRead:to:","navigatorTitle":[{"kind":"identifier","text":"onConversationRead:to:"}]},"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/chatserviceimplement\/onconversationread(_:to:)"]},{"paths":["\/documentation\/shengwangchatuikit\/chatserviceimplement\/onconversationread(_:to:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatServiceImplement":{"navigatorTitle":[{"text":"ChatServiceImplement","kind":"identifier"}],"abstract":[],"kind":"symbol","url":"\/documentation\/shengwangchatuikit\/chatserviceimplement","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChatServiceImplement"}],"type":"topic","title":"ChatServiceImplement","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatServiceImplement"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatServiceImplement/AgoraChatManagerDelegate-Implementations":{"abstract":[],"type":"topic","url":"\/documentation\/shengwangchatuikit\/chatserviceimplement\/agorachatmanagerdelegate-implementations","role":"collectionGroup","title":"AgoraChatManagerDelegate Implementations","kind":"article","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatServiceImplement\/AgoraChatManagerDelegate-Implementations"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatServiceImplement/onConversationRead(_:to:)":{"url":"\/documentation\/shengwangchatuikit\/chatserviceimplement\/onconversationread(_:to:)","navigatorTitle":[{"text":"onConversationRead:to:","kind":"identifier"}],"kind":"symbol","title":"onConversationRead(_:to:)","type":"topic","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onConversationRead"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"to"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":")"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatServiceImplement\/onConversationRead(_:to:)"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","value":"onConversationRead:to:","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"text":"- ","kind":"text"},{"text":"onConversationRead:to:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"text":"onConversationRead:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"from","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"to:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"to"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"value":"ChatServiceImplement","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatServiceImplement\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatServiceImplement\/fragments","value":[{"text":"ChatServiceImplement","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"ChatServiceImplement"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatServiceImplement\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatServiceImplement~1onConversationRead(_:to:)\/title","value":"onConversationRead:to:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatServiceImplement~1onConversationRead(_:to:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onConversationRead:to:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}