{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/chatserviceimplement\/onmessagepinchanged(_:conversationid:operation:pininfo:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/chatserviceimplement\/onmessagepinchanged(_:conversationid:operation:pininfo:)"]}],"metadata":{"title":"onMessagePinChanged(_:conversationId:operation:pinInfo:)","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"onMessagePinChanged"},{"kind":"text","text":"("},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"conversationId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"operation"},{"kind":"text","text":": "},{"text":"MessagePinOperation","kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit19MessagePinOperationa"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"pinInfo"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit14MessagePinInfoa","text":"MessagePinInfo"},{"text":")","kind":"text"}],"modules":[{"name":"ShengwangChatUIKit"}],"navigatorTitle":[{"text":"onMessagePinChanged:conversationId:operation:pinInfo:","kind":"identifier"}],"role":"symbol","extendedModule":"ShengwangChatUIKit","symbolKind":"method","externalID":"c:@CM@ShengwangChatUIKit@objc(cs)ChatServiceImplement(im)onMessagePinChanged:conversationId:operation:pinInfo:"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatServiceImplement","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatServiceImplement\/AgoraChatManagerDelegate-Implementations"]]},"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatServiceImplement\/onMessagePinChanged(_:conversationId:operation:pinInfo:)","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"AgoraChatManagerDelegate.onMessagePinChanged(_:conversationId:operation:pinInfo:)"},{"type":"text","text":"."}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onMessagePinChanged"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"messageId","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"conversationId"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"operation","kind":"externalParam"},{"kind":"text","text":" "},{"text":"pinOperation","kind":"internalParam"},{"kind":"text","text":": "},{"text":"MessagePinOperation","preciseIdentifier":"s:18ShengwangChatUIKit19MessagePinOperationa","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessagePinOperation"},{"kind":"text","text":", "},{"text":"pinInfo","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MessagePinInfo","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessagePinInfo","preciseIdentifier":"s:18ShengwangChatUIKit14MessagePinInfoa","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessagePinOperation":{"type":"topic","navigatorTitle":[{"text":"MessagePinOperation","kind":"identifier"}],"title":"MessagePinOperation","role":"symbol","kind":"symbol","url":"\/documentation\/shengwangchatuikit\/messagepinoperation","abstract":[],"fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"MessagePinOperation","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessagePinOperation"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessagePinInfo":{"type":"topic","navigatorTitle":[{"text":"MessagePinInfo","kind":"identifier"}],"title":"MessagePinInfo","role":"symbol","kind":"symbol","url":"\/documentation\/shengwangchatuikit\/messagepininfo","abstract":[],"fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessagePinInfo"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessagePinInfo"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatServiceImplement/onMessagePinChanged(_:conversationId:operation:pinInfo:)":{"type":"topic","role":"symbol","title":"onMessagePinChanged(_:conversationId:operation:pinInfo:)","kind":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"onMessagePinChanged:conversationId:operation:pinInfo:"}],"url":"\/documentation\/shengwangchatuikit\/chatserviceimplement\/onmessagepinchanged(_:conversationid:operation:pininfo:)","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatServiceImplement\/onMessagePinChanged(_:conversationId:operation:pinInfo:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"onMessagePinChanged","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"conversationId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"operation"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit19MessagePinOperationa","text":"MessagePinOperation"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"pinInfo"},{"text":": ","kind":"text"},{"text":"MessagePinInfo","kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit14MessagePinInfoa"},{"text":")","kind":"text"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatServiceImplement":{"navigatorTitle":[{"text":"ChatServiceImplement","kind":"identifier"}],"abstract":[],"kind":"symbol","url":"\/documentation\/shengwangchatuikit\/chatserviceimplement","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChatServiceImplement"}],"type":"topic","title":"ChatServiceImplement","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatServiceImplement"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatServiceImplement/AgoraChatManagerDelegate-Implementations":{"abstract":[],"type":"topic","url":"\/documentation\/shengwangchatuikit\/chatserviceimplement\/agorachatmanagerdelegate-implementations","role":"collectionGroup","title":"AgoraChatManagerDelegate Implementations","kind":"article","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatServiceImplement\/AgoraChatManagerDelegate-Implementations"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"onMessagePinChanged:conversationId:operation:pinInfo:","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onMessagePinChanged:conversationId:operation:pinInfo:"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"onMessagePinChanged:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"messageId","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"conversationId:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"conversationId","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"operation:"},{"text":"(","kind":"text"},{"text":"AgoraChatMessagePinOperation","kind":"typeIdentifier","preciseIdentifier":"c:@E@AgoraChatMessagePinOperation"},{"text":") ","kind":"text"},{"text":"pinOperation","kind":"internalParam"},{"kind":"text","text":" "},{"text":"pinInfo:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AgoraChatMessagePinInfo","text":"AgoraChatMessagePinInfo"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"pinInfo"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"onMessagePinChanged:conversationId:operation:pinInfo:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatServiceImplement~1onMessagePinChanged(_:conversationId:operation:pinInfo:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"onMessagePinChanged:conversationId:operation:pinInfo:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatServiceImplement~1onMessagePinChanged(_:conversationId:operation:pinInfo:)\/fragments"},{"value":"ChatServiceImplement","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatServiceImplement\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatServiceImplement\/fragments","op":"replace","value":[{"kind":"identifier","text":"ChatServiceImplement"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatServiceImplement\/navigatorTitle","value":[{"text":"ChatServiceImplement","kind":"identifier"}]}]}]}