{"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatServiceImplement\/removeHistoryMessages()","interfaceLanguage":"swift"},"abstract":[{"text":"Remove all of the history messages from database.","type":"text"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"removeHistoryMessages"},{"text":"()","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatServiceImplement","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatServiceImplement\/ChatService-Implementations"]]},"sections":[],"metadata":{"externalID":"c:@CM@ShengwangChatUIKit@objc(cs)ChatServiceImplement(im)removeHistoryMessages","extendedModule":"ShengwangChatUIKit","roleHeading":"Instance Method","role":"symbol","title":"removeHistoryMessages()","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeHistoryMessages"},{"text":"()","kind":"text"}],"navigatorTitle":[{"text":"removeHistoryMessages","kind":"identifier"}],"modules":[{"name":"ShengwangChatUIKit"}],"symbolKind":"method"},"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/chatserviceimplement\/removehistorymessages()"]},{"paths":["\/documentation\/shengwangchatuikit\/chatserviceimplement\/removehistorymessages()"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatServiceImplement/removeHistoryMessages()":{"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"removeHistoryMessages"}],"title":"removeHistoryMessages()","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatServiceImplement\/removeHistoryMessages()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeHistoryMessages"},{"text":"()","kind":"text"}],"abstract":[{"type":"text","text":"Remove all of the history messages from database."}],"type":"topic","url":"\/documentation\/shengwangchatuikit\/chatserviceimplement\/removehistorymessages()"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatServiceImplement":{"navigatorTitle":[{"text":"ChatServiceImplement","kind":"identifier"}],"abstract":[],"kind":"symbol","url":"\/documentation\/shengwangchatuikit\/chatserviceimplement","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChatServiceImplement"}],"type":"topic","title":"ChatServiceImplement","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatServiceImplement"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatServiceImplement/ChatService-Implementations":{"url":"\/documentation\/shengwangchatuikit\/chatserviceimplement\/chatservice-implementations","abstract":[],"kind":"article","type":"topic","role":"collectionGroup","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatServiceImplement\/ChatService-Implementations","title":"ChatService Implementations"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"removeHistoryMessages"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"removeHistoryMessages"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"removeHistoryMessages","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","value":"removeHistoryMessages","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatServiceImplement~1removeHistoryMessages()\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"removeHistoryMessages","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatServiceImplement~1removeHistoryMessages()\/fragments"},{"value":"ChatServiceImplement","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatServiceImplement\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatServiceImplement\/fragments","value":[{"text":"ChatServiceImplement","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatServiceImplement\/navigatorTitle","value":[{"text":"ChatServiceImplement","kind":"identifier"}],"op":"replace"}]}]}