{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/uicontextualactiontype\/more"]},{"paths":["\/documentation\/shengwangchatuikit\/uicontextualactiontype\/more"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UIContextualActionType"]]},"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"more","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UIContextualActionType\/more","interfaceLanguage":"swift"},"sections":[],"metadata":{"roleHeading":"Case","title":"UIContextualActionType.more","externalID":"c:@M@ShengwangChatUIKit@E@UIContextualActionType@UIContextualActionTypeMore","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"more","kind":"identifier"}],"symbolKind":"case","modules":[{"name":"ShengwangChatUIKit"}],"navigatorTitle":[{"text":"UIContextualActionTypeMore","kind":"identifier"}],"role":"symbol"},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/UIContextualActionType/more":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UIContextualActionType\/more","navigatorTitle":[{"text":"UIContextualActionTypeMore","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/uicontextualactiontype\/more","type":"topic","abstract":[],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"more","kind":"identifier"}],"title":"UIContextualActionType.more","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/UIContextualActionType":{"navigatorTitle":[{"kind":"identifier","text":"UIContextualActionType"}],"abstract":[],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"UIContextualActionType","kind":"identifier"}],"type":"topic","url":"\/documentation\/shengwangchatuikit\/uicontextualactiontype","kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UIContextualActionType","title":"UIContextualActionType"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"UIContextualActionTypeMore"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"UIContextualActionTypeMore","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"UIContextualActionTypeMore"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1UIContextualActionType~1more\/title","op":"replace","value":"UIContextualActionTypeMore"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1UIContextualActionType~1more\/fragments","op":"replace","value":[{"text":"UIContextualActionTypeMore","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1UIContextualActionType\/title","op":"replace","value":"UIContextualActionType"},{"op":"replace","value":[{"text":"UIContextualActionType","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1UIContextualActionType\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1UIContextualActionType\/navigatorTitle","value":[{"kind":"identifier","text":"UIContextualActionType"}]}]}]}