{"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UIContextualActionType\/unmute","interfaceLanguage":"swift"},"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unmute","kind":"identifier"}],"symbolKind":"case","modules":[{"name":"ShengwangChatUIKit"}],"title":"UIContextualActionType.unmute","navigatorTitle":[{"kind":"identifier","text":"UIContextualActionTypeUnmute"}],"roleHeading":"Case","externalID":"c:@M@ShengwangChatUIKit@E@UIContextualActionType@UIContextualActionTypeUnmute","role":"symbol"},"variants":[{"paths":["\/documentation\/shengwangchatuikit\/uicontextualactiontype\/unmute"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/uicontextualactiontype\/unmute"]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"unmute","kind":"identifier"}]}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UIContextualActionType"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/UIContextualActionType":{"navigatorTitle":[{"kind":"identifier","text":"UIContextualActionType"}],"abstract":[],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"UIContextualActionType","kind":"identifier"}],"type":"topic","url":"\/documentation\/shengwangchatuikit\/uicontextualactiontype","kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UIContextualActionType","title":"UIContextualActionType"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/UIContextualActionType/unmute":{"navigatorTitle":[{"text":"UIContextualActionTypeUnmute","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UIContextualActionType\/unmute","url":"\/documentation\/shengwangchatuikit\/uicontextualactiontype\/unmute","title":"UIContextualActionType.unmute","abstract":[],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"unmute","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"UIContextualActionTypeUnmute","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"UIContextualActionTypeUnmute"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"UIContextualActionTypeUnmute","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"UIContextualActionType","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1UIContextualActionType\/title"},{"value":[{"text":"UIContextualActionType","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1UIContextualActionType\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"UIContextualActionType"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1UIContextualActionType\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1UIContextualActionType~1unmute\/title","op":"replace","value":"UIContextualActionTypeUnmute"},{"value":[{"kind":"identifier","text":"UIContextualActionTypeUnmute"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1UIContextualActionType~1unmute\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}