{"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MultiDeviceServiceImplement\/multiDevicesGroupEventDidReceive(_:groupId:ext:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"multiDevicesGroupEventDidReceive","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"aEvent"},{"text":": ","kind":"text"},{"text":"MultiDeviceEvent","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MultiDeviceEvent","preciseIdentifier":"s:18ShengwangChatUIKit16MultiDeviceEventa"},{"text":", ","kind":"text"},{"text":"groupId","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"aGroupId"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"ext"},{"text":" ","kind":"text"},{"text":"aExt","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"?)","kind":"text"}]}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MultiDeviceServiceImplement","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MultiDeviceServiceImplement\/AgoraChatMultiDevicesDelegate-Implementations"]]},"variants":[{"paths":["\/documentation\/shengwangchatuikit\/multideviceserviceimplement\/multidevicesgroupeventdidreceive(_:groupid:ext:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/multideviceserviceimplement\/multidevicesgroupeventdidreceive(_:groupid:ext:)"]}],"abstract":[{"type":"text","text":"Inherited from "},{"code":"AgoraChatMultiDevicesDelegate.multiDevicesGroupEventDidReceive(_:groupId:ext:)","type":"codeVoice"},{"text":".","type":"text"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"extendedModule":"ShengwangChatUIKit","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"multiDevicesGroupEventDidReceive"},{"kind":"text","text":"("},{"preciseIdentifier":"s:18ShengwangChatUIKit16MultiDeviceEventa","text":"MultiDeviceEvent","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"groupId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"ext","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Any","kind":"keyword"},{"text":"?)","kind":"text"}],"navigatorTitle":[{"text":"multiDevicesGroupEventDidReceive:groupId:ext:","kind":"identifier"}],"role":"symbol","externalID":"c:@CM@ShengwangChatUIKit@objc(cs)MultiDeviceServiceImplement(im)multiDevicesGroupEventDidReceive:groupId:ext:","title":"multiDevicesGroupEventDidReceive(_:groupId:ext:)","roleHeading":"Instance Method","modules":[{"name":"ShengwangChatUIKit"}]},"kind":"symbol","references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MultiDeviceServiceImplement":{"abstract":[],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MultiDeviceServiceImplement","url":"\/documentation\/shengwangchatuikit\/multideviceserviceimplement","type":"topic","title":"MultiDeviceServiceImplement","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MultiDeviceServiceImplement","kind":"identifier"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"MultiDeviceServiceImplement","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MultiDeviceServiceImplement/AgoraChatMultiDevicesDelegate-Implementations":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MultiDeviceServiceImplement\/AgoraChatMultiDevicesDelegate-Implementations","role":"collectionGroup","url":"\/documentation\/shengwangchatuikit\/multideviceserviceimplement\/agorachatmultidevicesdelegate-implementations","abstract":[],"kind":"article","title":"AgoraChatMultiDevicesDelegate Implementations","type":"topic"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MultiDeviceServiceImplement/multiDevicesGroupEventDidReceive(_:groupId:ext:)":{"title":"multiDevicesGroupEventDidReceive(_:groupId:ext:)","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MultiDeviceServiceImplement\/multiDevicesGroupEventDidReceive(_:groupId:ext:)","type":"topic","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"multiDevicesGroupEventDidReceive"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:18ShengwangChatUIKit16MultiDeviceEventa","text":"MultiDeviceEvent","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"groupId"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"ext","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"?)"}],"abstract":[],"kind":"symbol","navigatorTitle":[{"text":"multiDevicesGroupEventDidReceive:groupId:ext:","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/multideviceserviceimplement\/multidevicesgroupeventdidreceive(_:groupid:ext:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MultiDeviceEvent":{"fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MultiDeviceEvent"}],"role":"symbol","url":"\/documentation\/shengwangchatuikit\/multideviceevent","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MultiDeviceEvent","title":"MultiDeviceEvent","kind":"symbol","abstract":[],"navigatorTitle":[{"text":"MultiDeviceEvent","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"multiDevicesGroupEventDidReceive:groupId:ext:","op":"replace"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"multiDevicesGroupEventDidReceive:groupId:ext:","kind":"identifier"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"multiDevicesGroupEventDidReceive:","kind":"identifier"},{"kind":"text","text":"("},{"text":"AgoraChatMultiDevicesEvent","kind":"typeIdentifier","preciseIdentifier":"c:@E@AgoraChatMultiDevicesEvent"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"aEvent"},{"text":" ","kind":"text"},{"text":"groupId:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"aGroupId","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ext:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"aExt","kind":"internalParam"},{"text":";","kind":"text"}]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MultiDeviceServiceImplement\/title","value":"MultiDeviceServiceImplement","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MultiDeviceServiceImplement\/fragments","value":[{"text":"MultiDeviceServiceImplement","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"MultiDeviceServiceImplement"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MultiDeviceServiceImplement\/navigatorTitle"},{"op":"replace","value":"multiDevicesGroupEventDidReceive:groupId:ext:","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MultiDeviceServiceImplement~1multiDevicesGroupEventDidReceive(_:groupId:ext:)\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"multiDevicesGroupEventDidReceive:groupId:ext:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MultiDeviceServiceImplement~1multiDevicesGroupEventDidReceive(_:groupId:ext:)\/fragments"}]}]}