{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MultiDeviceServiceImplement","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MultiDeviceServiceImplement\/AgoraChatMultiDevicesDelegate-Implementations"]]},"abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"AgoraChatMultiDevicesDelegate.multiDevicesConversationEvent(_:conversationId:conversationType:)"},{"text":".","type":"text"}],"kind":"symbol","sections":[],"variants":[{"paths":["\/documentation\/shengwangchatuikit\/multideviceserviceimplement\/multidevicesconversationevent(_:conversationid:conversationtype:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/shengwangchatuikit\/multideviceserviceimplement\/multidevicesconversationevent(_:conversationid:conversationtype:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"roleHeading":"Instance Method","extendedModule":"ShengwangChatUIKit","title":"multiDevicesConversationEvent(_:conversationId:conversationType:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"multiDevicesConversationEvent:conversationId:conversationType:"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"multiDevicesConversationEvent","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:18ShengwangChatUIKit16MultiDeviceEventa","text":"MultiDeviceEvent","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"conversationId"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"conversationType"},{"kind":"text","text":": "},{"text":"ChatConversationType","kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit0B16ConversationTypea"},{"text":")","kind":"text"}],"externalID":"c:@CM@ShengwangChatUIKit@objc(cs)MultiDeviceServiceImplement(im)multiDevicesConversationEvent:conversationId:conversationType:","modules":[{"name":"ShengwangChatUIKit"}],"symbolKind":"method"},"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MultiDeviceServiceImplement\/multiDevicesConversationEvent(_:conversationId:conversationType:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"multiDevicesConversationEvent"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"event","kind":"internalParam"},{"kind":"text","text":": "},{"text":"MultiDeviceEvent","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MultiDeviceEvent","preciseIdentifier":"s:18ShengwangChatUIKit16MultiDeviceEventa"},{"kind":"text","text":", "},{"text":"conversationId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"conversationType"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"ChatConversationType","preciseIdentifier":"s:18ShengwangChatUIKit0B16ConversationTypea","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatConversationType"},{"kind":"text","text":")"}]}]}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MultiDeviceServiceImplement/AgoraChatMultiDevicesDelegate-Implementations":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MultiDeviceServiceImplement\/AgoraChatMultiDevicesDelegate-Implementations","role":"collectionGroup","url":"\/documentation\/shengwangchatuikit\/multideviceserviceimplement\/agorachatmultidevicesdelegate-implementations","abstract":[],"kind":"article","title":"AgoraChatMultiDevicesDelegate Implementations","type":"topic"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatConversationType":{"type":"topic","role":"symbol","title":"ChatConversationType","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatConversationType","abstract":[],"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatConversationType"}],"url":"\/documentation\/shengwangchatuikit\/chatconversationtype","kind":"symbol","navigatorTitle":[{"text":"ChatConversationType","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MultiDeviceServiceImplement":{"abstract":[],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MultiDeviceServiceImplement","url":"\/documentation\/shengwangchatuikit\/multideviceserviceimplement","type":"topic","title":"MultiDeviceServiceImplement","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MultiDeviceServiceImplement","kind":"identifier"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"MultiDeviceServiceImplement","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MultiDeviceServiceImplement/multiDevicesConversationEvent(_:conversationId:conversationType:)":{"type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"multiDevicesConversationEvent:conversationId:conversationType:"}],"kind":"symbol","title":"multiDevicesConversationEvent(_:conversationId:conversationType:)","url":"\/documentation\/shengwangchatuikit\/multideviceserviceimplement\/multidevicesconversationevent(_:conversationid:conversationtype:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"multiDevicesConversationEvent","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit16MultiDeviceEventa","text":"MultiDeviceEvent"},{"kind":"text","text":", "},{"text":"conversationId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"conversationType","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:18ShengwangChatUIKit0B16ConversationTypea","kind":"typeIdentifier","text":"ChatConversationType"},{"kind":"text","text":")"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MultiDeviceServiceImplement\/multiDevicesConversationEvent(_:conversationId:conversationType:)","role":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MultiDeviceEvent":{"fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MultiDeviceEvent"}],"role":"symbol","url":"\/documentation\/shengwangchatuikit\/multideviceevent","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MultiDeviceEvent","title":"MultiDeviceEvent","kind":"symbol","abstract":[],"navigatorTitle":[{"text":"MultiDeviceEvent","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"multiDevicesConversationEvent:conversationId:conversationType:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"multiDevicesConversationEvent:conversationId:conversationType:","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"multiDevicesConversationEvent:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@E@AgoraChatMultiDevicesEvent","kind":"typeIdentifier","text":"AgoraChatMultiDevicesEvent"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"event"},{"text":" ","kind":"text"},{"text":"conversationId:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"conversationId"},{"text":" ","kind":"text"},{"text":"conversationType:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@E@AgoraChatConversationType","text":"AgoraChatConversationType","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"internalParam","text":"conversationType"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","value":"MultiDeviceServiceImplement","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MultiDeviceServiceImplement\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MultiDeviceServiceImplement\/fragments","value":[{"text":"MultiDeviceServiceImplement","kind":"identifier"}]},{"value":[{"text":"MultiDeviceServiceImplement","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MultiDeviceServiceImplement\/navigatorTitle"},{"op":"replace","value":"multiDevicesConversationEvent:conversationId:conversationType:","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MultiDeviceServiceImplement~1multiDevicesConversationEvent(_:conversationId:conversationType:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MultiDeviceServiceImplement~1multiDevicesConversationEvent(_:conversationId:conversationType:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"multiDevicesConversationEvent:conversationId:conversationType:","kind":"identifier"}]}]}]}