{"variants":[{"paths":["\/documentation\/shengwangchatuikit\/multideviceserviceimplement\/multideviceservice-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/multideviceserviceimplement\/multideviceservice-implementations"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MultiDeviceServiceImplement"]]},"kind":"article","schemaVersion":{"minor":3,"patch":0,"major":0},"topicSections":[{"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MultiDeviceServiceImplement\/bindMultiDeviceListener(listener:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MultiDeviceServiceImplement\/unbindMultiDeviceListener(listener:)"],"anchor":"Instance-Methods","title":"Instance Methods","generated":true}],"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MultiDeviceServiceImplement\/MultiDeviceService-Implementations","interfaceLanguage":"swift"},"sections":[],"metadata":{"modules":[{"name":"ShengwangChatUIKit"}],"roleHeading":"API Collection","title":"MultiDeviceService Implementations","role":"collectionGroup"},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MultiDeviceServiceImplement":{"abstract":[],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MultiDeviceServiceImplement","url":"\/documentation\/shengwangchatuikit\/multideviceserviceimplement","type":"topic","title":"MultiDeviceServiceImplement","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MultiDeviceServiceImplement","kind":"identifier"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"MultiDeviceServiceImplement","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MultiDeviceServiceImplement/bindMultiDeviceListener(listener:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bindMultiDeviceListener","kind":"identifier"},{"text":"(","kind":"text"},{"text":"listener","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MultiDeviceListener","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(pl)MultiDeviceListener"},{"kind":"text","text":")"}],"url":"\/documentation\/shengwangchatuikit\/multideviceserviceimplement\/bindmultidevicelistener(listener:)","abstract":[{"text":"Bind multi device changed listener","type":"text"}],"type":"topic","kind":"symbol","title":"bindMultiDeviceListener(listener:)","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MultiDeviceServiceImplement\/bindMultiDeviceListener(listener:)","navigatorTitle":[{"kind":"identifier","text":"bindMultiDeviceListenerWithListener:"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MultiDeviceServiceImplement/unbindMultiDeviceListener(listener:)":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MultiDeviceServiceImplement\/unbindMultiDeviceListener(listener:)","url":"\/documentation\/shengwangchatuikit\/multideviceserviceimplement\/unbindmultidevicelistener(listener:)","abstract":[{"text":"Unbind multi device changed listener","type":"text"}],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"unbindMultiDeviceListener"},{"kind":"text","text":"("},{"text":"listener","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MultiDeviceListener","kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(pl)MultiDeviceListener"},{"text":")","kind":"text"}],"role":"symbol","title":"unbindMultiDeviceListener(listener:)","navigatorTitle":[{"kind":"identifier","text":"unbindMultiDeviceListenerWithListener:"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":[{"anchor":"Instance-Methods","title":"Instance Methods","generated":true,"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MultiDeviceServiceImplement\/bindMultiDeviceListener(listener:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MultiDeviceServiceImplement\/unbindMultiDeviceListener(listener:)"]}],"path":"\/topicSections","op":"replace"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":"MultiDeviceServiceImplement","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MultiDeviceServiceImplement\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MultiDeviceServiceImplement\/fragments","op":"replace","value":[{"kind":"identifier","text":"MultiDeviceServiceImplement"}]},{"value":[{"text":"MultiDeviceServiceImplement","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MultiDeviceServiceImplement\/navigatorTitle"},{"value":"bindMultiDeviceListenerWithListener:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MultiDeviceServiceImplement~1bindMultiDeviceListener(listener:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MultiDeviceServiceImplement~1bindMultiDeviceListener(listener:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"bindMultiDeviceListenerWithListener:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MultiDeviceServiceImplement~1unbindMultiDeviceListener(listener:)\/title","value":"unbindMultiDeviceListenerWithListener:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MultiDeviceServiceImplement~1unbindMultiDeviceListener(listener:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"unbindMultiDeviceListenerWithListener:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}