{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/TextEditorView"]]},"abstract":[{"type":"text","text":"占位 text 行数"}],"metadata":{"title":"placeholderNumberOfLines","roleHeading":"Instance Property","symbolKind":"property","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"placeholderNumberOfLines","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"}],"modules":[{"name":"ShengwangChatUIKit"}],"externalID":"s:18ShengwangChatUIKit14TextEditorViewC24placeholderNumberOfLinesSuvp"},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"placeholderNumberOfLines","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Su","kind":"typeIdentifier","text":"UInt"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"text":" }","kind":"text"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/texteditorview\/placeholdernumberoflines"]}],"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/TextEditorView\/placeholderNumberOfLines","interfaceLanguage":"swift"},"sections":[],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/TextEditorView":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"TextEditorView","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/TextEditorView","kind":"symbol","navigatorTitle":[{"text":"TextEditorView","kind":"identifier"}],"role":"symbol","title":"TextEditorView","url":"\/documentation\/shengwangchatuikit\/texteditorview","abstract":[{"type":"text","text":"自适应输入框"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/TextEditorView/placeholderNumberOfLines":{"role":"symbol","kind":"symbol","url":"\/documentation\/shengwangchatuikit\/texteditorview\/placeholdernumberoflines","title":"placeholderNumberOfLines","abstract":[{"type":"text","text":"占位 text 行数"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"placeholderNumberOfLines","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Su","text":"UInt"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/TextEditorView\/placeholderNumberOfLines","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1TextEditorView\/title","value":"TextEditorView"},{"value":[{"text":"TextEditorView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1TextEditorView\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1TextEditorView\/navigatorTitle","value":[{"text":"TextEditorView","kind":"identifier"}],"op":"replace"}]}]}