{"metadata":{"modules":[{"name":"ShengwangChatUIKit"}],"symbolKind":"method","navigatorTitle":[{"text":"updateConstraints","kind":"identifier"}],"roleHeading":"Instance Method","title":"updateConstraints()","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"updateConstraints","kind":"identifier"},{"kind":"text","text":"()"}],"externalID":"c:@M@ShengwangChatUIKit@objc(cs)TextEditorView(im)updateConstraints"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"updateConstraints","kind":"identifier"},{"text":"()","kind":"text"}]}],"kind":"declarations"}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/TextEditorView\/updateConstraints()"},"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/TextEditorView"]]},"kind":"symbol","variants":[{"paths":["\/documentation\/shengwangchatuikit\/texteditorview\/updateconstraints()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/texteditorview\/updateconstraints()"]}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/TextEditorView":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"TextEditorView","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/TextEditorView","kind":"symbol","navigatorTitle":[{"text":"TextEditorView","kind":"identifier"}],"role":"symbol","title":"TextEditorView","url":"\/documentation\/shengwangchatuikit\/texteditorview","abstract":[{"type":"text","text":"自适应输入框"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/TextEditorView/updateConstraints()":{"title":"updateConstraints()","role":"symbol","navigatorTitle":[{"text":"updateConstraints","kind":"identifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"updateConstraints","kind":"identifier"},{"kind":"text","text":"()"}],"kind":"symbol","abstract":[],"url":"\/documentation\/shengwangchatuikit\/texteditorview\/updateconstraints()","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/TextEditorView\/updateConstraints()"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"updateConstraints"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"value":[{"text":"- ","kind":"text"},{"text":"updateConstraints","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"updateConstraints"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1TextEditorView\/title","value":"TextEditorView"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1TextEditorView\/fragments","op":"replace","value":[{"text":"TextEditorView","kind":"identifier"}]},{"op":"replace","value":[{"text":"TextEditorView","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1TextEditorView\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1TextEditorView~1updateConstraints()\/title","op":"replace","value":"updateConstraints"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1TextEditorView~1updateConstraints()\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"updateConstraints","kind":"identifier"}]}]}]}