{"variants":[{"paths":["\/documentation\/shengwangchatuikit\/groupserviceimplement\/agorachatthreadmanagerdelegate-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/groupserviceimplement\/agorachatthreadmanagerdelegate-implementations"]}],"metadata":{"roleHeading":"API Collection","title":"AgoraChatThreadManagerDelegate Implementations","role":"collectionGroup","modules":[{"name":"ShengwangChatUIKit"}]},"kind":"article","topicSections":[{"anchor":"Instance-Methods","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupServiceImplement\/onChatThreadCreate(_:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupServiceImplement\/onChatThreadDestroy(_:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupServiceImplement\/onChatThreadUpdate(_:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupServiceImplement\/onUserKickOutOfChatThread(_:)"],"title":"Instance Methods","generated":true}],"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupServiceImplement"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupServiceImplement\/AgoraChatThreadManagerDelegate-Implementations"},"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/GroupServiceImplement/onUserKickOutOfChatThread(_:)":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupServiceImplement\/onUserKickOutOfChatThread(_:)","navigatorTitle":[{"text":"onUserKickOutOfChatThread:","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/groupserviceimplement\/onuserkickoutofchatthread(_:)","type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"onUserKickOutOfChatThread","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"GroupChatThreadEvent","preciseIdentifier":"s:18ShengwangChatUIKit05GroupB11ThreadEventa"},{"text":")","kind":"text"}],"title":"onUserKickOutOfChatThread(_:)","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/GroupServiceImplement/onChatThreadUpdate(_:)":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupServiceImplement\/onChatThreadUpdate(_:)","navigatorTitle":[{"kind":"identifier","text":"onChatThreadUpdate:"}],"url":"\/documentation\/shengwangchatuikit\/groupserviceimplement\/onchatthreadupdate(_:)","type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onChatThreadUpdate"},{"kind":"text","text":"("},{"text":"GroupChatThreadEvent","kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit05GroupB11ThreadEventa"},{"text":")","kind":"text"}],"title":"onChatThreadUpdate(_:)","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/GroupServiceImplement/onChatThreadDestroy(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onChatThreadDestroy","kind":"identifier"},{"text":"(","kind":"text"},{"text":"GroupChatThreadEvent","kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit05GroupB11ThreadEventa"},{"kind":"text","text":")"}],"type":"topic","role":"symbol","abstract":[],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"onChatThreadDestroy:"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupServiceImplement\/onChatThreadDestroy(_:)","url":"\/documentation\/shengwangchatuikit\/groupserviceimplement\/onchatthreaddestroy(_:)","title":"onChatThreadDestroy(_:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/GroupServiceImplement/onChatThreadCreate(_:)":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupServiceImplement\/onChatThreadCreate(_:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onChatThreadCreate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"GroupChatThreadEvent","kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit05GroupB11ThreadEventa"},{"text":")","kind":"text"}],"url":"\/documentation\/shengwangchatuikit\/groupserviceimplement\/onchatthreadcreate(_:)","navigatorTitle":[{"text":"onChatThreadCreate:","kind":"identifier"}],"title":"onChatThreadCreate(_:)","abstract":[],"role":"symbol","type":"topic"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/GroupServiceImplement":{"type":"topic","url":"\/documentation\/shengwangchatuikit\/groupserviceimplement","kind":"symbol","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"GroupServiceImplement","kind":"identifier"}],"title":"GroupServiceImplement","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupServiceImplement","navigatorTitle":[{"text":"GroupServiceImplement","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/topicSections","op":"replace","value":[{"anchor":"Instance-Methods","generated":true,"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupServiceImplement\/onChatThreadCreate(_:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupServiceImplement\/onChatThreadDestroy(_:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupServiceImplement\/onChatThreadUpdate(_:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupServiceImplement\/onUserKickOutOfChatThread(_:)"]}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":"onUserKickOutOfChatThread:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupServiceImplement~1onUserKickOutOfChatThread(_:)\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"onUserKickOutOfChatThread:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupServiceImplement~1onUserKickOutOfChatThread(_:)\/fragments"},{"value":"onChatThreadUpdate:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupServiceImplement~1onChatThreadUpdate(_:)\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"onChatThreadUpdate:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupServiceImplement~1onChatThreadUpdate(_:)\/fragments"},{"op":"replace","value":"onChatThreadDestroy:","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupServiceImplement~1onChatThreadDestroy(_:)\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"onChatThreadDestroy:"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupServiceImplement~1onChatThreadDestroy(_:)\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupServiceImplement~1onChatThreadCreate(_:)\/title","value":"onChatThreadCreate:"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupServiceImplement~1onChatThreadCreate(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onChatThreadCreate:"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupServiceImplement\/title","value":"GroupServiceImplement","op":"replace"},{"value":[{"kind":"identifier","text":"GroupServiceImplement"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupServiceImplement\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupServiceImplement\/navigatorTitle","value":[{"text":"GroupServiceImplement","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}