{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupServiceImplement"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"paths":["\/documentation\/shengwangchatuikit\/groupserviceimplement\/agorachatgroupmanagerdelegate-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/groupserviceimplement\/agorachatgroupmanagerdelegate-implementations"]}],"sections":[],"kind":"article","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupServiceImplement\/AgoraChatGroupManagerDelegate-Implementations"},"topicSections":[{"generated":true,"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupServiceImplement\/didJoin(_:inviter:message:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupServiceImplement\/didLeave(_:reason:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupServiceImplement\/groupInvitationDidAccept(_:invitee:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupServiceImplement\/groupInvitationDidDecline(_:invitee:reason:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupServiceImplement\/groupInvitationDidReceive(_:groupName:inviter:message:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupServiceImplement\/groupOwnerDidUpdate(_:newOwner:oldOwner:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupServiceImplement\/joinGroupRequestDidApprove(_:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupServiceImplement\/joinGroupRequestDidDecline(_:reason:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupServiceImplement\/joinGroupRequestDidReceive(_:user:reason:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupServiceImplement\/onAttributesChangedOfGroupMember(_:userId:attributes:operatorId:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupServiceImplement\/userDidJoin(_:user:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupServiceImplement\/userDidLeave(_:user:)"],"title":"Instance Methods","anchor":"Instance-Methods"}],"metadata":{"role":"collectionGroup","modules":[{"name":"ShengwangChatUIKit"}],"title":"AgoraChatGroupManagerDelegate Implementations","roleHeading":"API Collection"},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/GroupServiceImplement/groupInvitationDidDecline(_:invitee:reason:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"groupInvitationDidDecline"},{"kind":"text","text":"("},{"text":"ChatGroup","kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit0B5Groupa"},{"kind":"text","text":", "},{"kind":"externalParam","text":"invitee"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"reason","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?)","kind":"text"}],"kind":"symbol","title":"groupInvitationDidDecline(_:invitee:reason:)","type":"topic","url":"\/documentation\/shengwangchatuikit\/groupserviceimplement\/groupinvitationdiddecline(_:invitee:reason:)","abstract":[],"role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupServiceImplement\/groupInvitationDidDecline(_:invitee:reason:)","navigatorTitle":[{"text":"groupInvitationDidDecline:invitee:reason:","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/GroupServiceImplement/userDidJoin(_:user:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"userDidJoin","kind":"identifier"},{"text":"(","kind":"text"},{"text":"ChatGroup","kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit0B5Groupa"},{"text":", ","kind":"text"},{"text":"user","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"userDidJoinGroup:user:","kind":"identifier"}],"role":"symbol","url":"\/documentation\/shengwangchatuikit\/groupserviceimplement\/userdidjoin(_:user:)","kind":"symbol","title":"userDidJoin(_:user:)","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupServiceImplement\/userDidJoin(_:user:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/GroupServiceImplement/userDidLeave(_:user:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"userDidLeave"},{"text":"(","kind":"text"},{"text":"ChatGroup","kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit0B5Groupa"},{"text":", ","kind":"text"},{"text":"user","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"kind":"symbol","title":"userDidLeave(_:user:)","type":"topic","url":"\/documentation\/shengwangchatuikit\/groupserviceimplement\/userdidleave(_:user:)","abstract":[],"role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupServiceImplement\/userDidLeave(_:user:)","navigatorTitle":[{"text":"userDidLeaveGroup:user:","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/GroupServiceImplement":{"type":"topic","url":"\/documentation\/shengwangchatuikit\/groupserviceimplement","kind":"symbol","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"GroupServiceImplement","kind":"identifier"}],"title":"GroupServiceImplement","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupServiceImplement","navigatorTitle":[{"text":"GroupServiceImplement","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/GroupServiceImplement/joinGroupRequestDidReceive(_:user:reason:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"joinGroupRequestDidReceive","kind":"identifier"},{"text":"(","kind":"text"},{"text":"ChatGroup","kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit0B5Groupa"},{"text":", ","kind":"text"},{"text":"user","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"text":"reason","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?)"}],"navigatorTitle":[{"text":"joinGroupRequestDidReceive:user:reason:","kind":"identifier"}],"role":"symbol","url":"\/documentation\/shengwangchatuikit\/groupserviceimplement\/joingrouprequestdidreceive(_:user:reason:)","kind":"symbol","title":"joinGroupRequestDidReceive(_:user:reason:)","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupServiceImplement\/joinGroupRequestDidReceive(_:user:reason:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/GroupServiceImplement/onAttributesChangedOfGroupMember(_:userId:attributes:operatorId:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"onAttributesChangedOfGroupMember"},{"kind":"text","text":"("},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"userId"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"attributes","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":" : ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"]?, ","kind":"text"},{"text":"operatorId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"kind":"symbol","title":"onAttributesChangedOfGroupMember(_:userId:attributes:operatorId:)","type":"topic","url":"\/documentation\/shengwangchatuikit\/groupserviceimplement\/onattributeschangedofgroupmember(_:userid:attributes:operatorid:)","abstract":[],"role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupServiceImplement\/onAttributesChangedOfGroupMember(_:userId:attributes:operatorId:)","navigatorTitle":[{"text":"onAttributesChangedOfGroupMember:userId:attributes:operatorId:","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/GroupServiceImplement/didJoin(_:inviter:message:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"didJoin","kind":"identifier"},{"kind":"text","text":"("},{"text":"ChatGroup","kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit0B5Groupa"},{"text":", ","kind":"text"},{"text":"inviter","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"message","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?)","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"didJoinGroup:inviter:message:"}],"role":"symbol","url":"\/documentation\/shengwangchatuikit\/groupserviceimplement\/didjoin(_:inviter:message:)","kind":"symbol","title":"didJoin(_:inviter:message:)","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupServiceImplement\/didJoin(_:inviter:message:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/GroupServiceImplement/groupOwnerDidUpdate(_:newOwner:oldOwner:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"groupOwnerDidUpdate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"ChatGroup","kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit0B5Groupa"},{"text":", ","kind":"text"},{"text":"newOwner","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"oldOwner","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"kind":"symbol","title":"groupOwnerDidUpdate(_:newOwner:oldOwner:)","type":"topic","url":"\/documentation\/shengwangchatuikit\/groupserviceimplement\/groupownerdidupdate(_:newowner:oldowner:)","abstract":[],"role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupServiceImplement\/groupOwnerDidUpdate(_:newOwner:oldOwner:)","navigatorTitle":[{"text":"groupOwnerDidUpdate:newOwner:oldOwner:","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/GroupServiceImplement/groupInvitationDidAccept(_:invitee:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"groupInvitationDidAccept","kind":"identifier"},{"kind":"text","text":"("},{"text":"ChatGroup","kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit0B5Groupa"},{"text":", ","kind":"text"},{"text":"invitee","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"groupInvitationDidAccept:invitee:","kind":"identifier"}],"role":"symbol","url":"\/documentation\/shengwangchatuikit\/groupserviceimplement\/groupinvitationdidaccept(_:invitee:)","kind":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupServiceImplement\/groupInvitationDidAccept(_:invitee:)","type":"topic","title":"groupInvitationDidAccept(_:invitee:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/GroupServiceImplement/groupInvitationDidReceive(_:groupName:inviter:message:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"groupInvitationDidReceive","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"groupName","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"inviter","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"url":"\/documentation\/shengwangchatuikit\/groupserviceimplement\/groupinvitationdidreceive(_:groupname:inviter:message:)","abstract":[],"kind":"symbol","type":"topic","title":"groupInvitationDidReceive(_:groupName:inviter:message:)","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupServiceImplement\/groupInvitationDidReceive(_:groupName:inviter:message:)","navigatorTitle":[{"kind":"identifier","text":"groupInvitationDidReceive:groupName:inviter:message:"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/GroupServiceImplement/joinGroupRequestDidDecline(_:reason:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"joinGroupRequestDidDecline","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"text":"reason","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?)"}],"navigatorTitle":[{"text":"joinGroupRequestDidDecline:reason:","kind":"identifier"}],"role":"symbol","url":"\/documentation\/shengwangchatuikit\/groupserviceimplement\/joingrouprequestdiddecline(_:reason:)","kind":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupServiceImplement\/joinGroupRequestDidDecline(_:reason:)","type":"topic","title":"joinGroupRequestDidDecline(_:reason:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/GroupServiceImplement/didLeave(_:reason:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"didLeave","kind":"identifier"},{"text":"(","kind":"text"},{"text":"ChatGroup","kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit0B5Groupa"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"reason"},{"kind":"text","text":": "},{"text":"GroupLeaveReason","kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit16GroupLeaveReasona"},{"kind":"text","text":")"}],"url":"\/documentation\/shengwangchatuikit\/groupserviceimplement\/didleave(_:reason:)","abstract":[],"kind":"symbol","type":"topic","title":"didLeave(_:reason:)","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupServiceImplement\/didLeave(_:reason:)","navigatorTitle":[{"kind":"identifier","text":"didLeaveGroup:reason:"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/GroupServiceImplement/joinGroupRequestDidApprove(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"joinGroupRequestDidApprove","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"s:18ShengwangChatUIKit0B5Groupa","kind":"typeIdentifier","text":"ChatGroup"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"joinGroupRequestDidApprove:","kind":"identifier"}],"role":"symbol","url":"\/documentation\/shengwangchatuikit\/groupserviceimplement\/joingrouprequestdidapprove(_:)","kind":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupServiceImplement\/joinGroupRequestDidApprove(_:)","type":"topic","title":"joinGroupRequestDidApprove(_:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/topicSections","op":"replace","value":[{"generated":true,"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupServiceImplement\/didJoin(_:inviter:message:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupServiceImplement\/didLeave(_:reason:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupServiceImplement\/groupInvitationDidAccept(_:invitee:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupServiceImplement\/groupInvitationDidDecline(_:invitee:reason:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupServiceImplement\/groupInvitationDidReceive(_:groupName:inviter:message:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupServiceImplement\/groupOwnerDidUpdate(_:newOwner:oldOwner:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupServiceImplement\/joinGroupRequestDidApprove(_:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupServiceImplement\/joinGroupRequestDidDecline(_:reason:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupServiceImplement\/joinGroupRequestDidReceive(_:user:reason:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupServiceImplement\/onAttributesChangedOfGroupMember(_:userId:attributes:operatorId:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupServiceImplement\/userDidJoin(_:user:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupServiceImplement\/userDidLeave(_:user:)"],"anchor":"Instance-Methods","title":"Instance Methods"}]},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupServiceImplement~1groupInvitationDidDecline(_:invitee:reason:)\/title","value":"groupInvitationDidDecline:invitee:reason:"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupServiceImplement~1groupInvitationDidDecline(_:invitee:reason:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"groupInvitationDidDecline:invitee:reason:"}],"op":"replace"},{"op":"replace","value":"userDidJoinGroup:user:","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupServiceImplement~1userDidJoin(_:user:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupServiceImplement~1userDidJoin(_:user:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"userDidJoinGroup:user:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupServiceImplement~1userDidLeave(_:user:)\/title","value":"userDidLeaveGroup:user:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupServiceImplement~1userDidLeave(_:user:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"userDidLeaveGroup:user:","kind":"identifier"}]},{"value":"GroupServiceImplement","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupServiceImplement\/title"},{"value":[{"text":"GroupServiceImplement","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupServiceImplement\/fragments","op":"replace"},{"op":"replace","value":[{"text":"GroupServiceImplement","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupServiceImplement\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupServiceImplement~1joinGroupRequestDidReceive(_:user:reason:)\/title","op":"replace","value":"joinGroupRequestDidReceive:user:reason:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"joinGroupRequestDidReceive:user:reason:"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupServiceImplement~1joinGroupRequestDidReceive(_:user:reason:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupServiceImplement~1onAttributesChangedOfGroupMember(_:userId:attributes:operatorId:)\/title","op":"replace","value":"onAttributesChangedOfGroupMember:userId:attributes:operatorId:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onAttributesChangedOfGroupMember:userId:attributes:operatorId:"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupServiceImplement~1onAttributesChangedOfGroupMember(_:userId:attributes:operatorId:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupServiceImplement~1didJoin(_:inviter:message:)\/title","value":"didJoinGroup:inviter:message:"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupServiceImplement~1didJoin(_:inviter:message:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"didJoinGroup:inviter:message:","kind":"identifier"}],"op":"replace"},{"value":"groupOwnerDidUpdate:newOwner:oldOwner:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupServiceImplement~1groupOwnerDidUpdate(_:newOwner:oldOwner:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupServiceImplement~1groupOwnerDidUpdate(_:newOwner:oldOwner:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"groupOwnerDidUpdate:newOwner:oldOwner:","kind":"identifier"}]},{"value":"groupInvitationDidAccept:invitee:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupServiceImplement~1groupInvitationDidAccept(_:invitee:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"groupInvitationDidAccept:invitee:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupServiceImplement~1groupInvitationDidAccept(_:invitee:)\/fragments"},{"value":"groupInvitationDidReceive:groupName:inviter:message:","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupServiceImplement~1groupInvitationDidReceive(_:groupName:inviter:message:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupServiceImplement~1groupInvitationDidReceive(_:groupName:inviter:message:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"groupInvitationDidReceive:groupName:inviter:message:"}]},{"op":"replace","value":"joinGroupRequestDidDecline:reason:","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupServiceImplement~1joinGroupRequestDidDecline(_:reason:)\/title"},{"value":[{"kind":"text","text":"- "},{"text":"joinGroupRequestDidDecline:reason:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupServiceImplement~1joinGroupRequestDidDecline(_:reason:)\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupServiceImplement~1didLeave(_:reason:)\/title","value":"didLeaveGroup:reason:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupServiceImplement~1didLeave(_:reason:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"didLeaveGroup:reason:"}]},{"op":"replace","value":"joinGroupRequestDidApprove:","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupServiceImplement~1joinGroupRequestDidApprove(_:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupServiceImplement~1joinGroupRequestDidApprove(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"joinGroupRequestDidApprove:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}