{"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupServiceImplement","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupServiceImplement\/GroupService-Implementations"]]},"metadata":{"title":"createGroup(subject:description:inviterIds:message:option:completion:)","roleHeading":"Instance Method","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"createGroup","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"subject"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"description","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"inviterIds"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"], "},{"text":"message","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"option","kind":"externalParam"},{"kind":"text","text":": "},{"text":"ChatGroupOption","preciseIdentifier":"s:18ShengwangChatUIKit0B11GroupOptiona","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit0B5Groupa","text":"ChatGroup"},{"kind":"text","text":"?, "},{"text":"ChatError","preciseIdentifier":"s:18ShengwangChatUIKit0B5Errora","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}],"extendedModule":"ShengwangChatUIKit","navigatorTitle":[{"text":"createGroupWithSubject:description:inviterIds:message:option:completion:","kind":"identifier"}],"role":"symbol","modules":[{"name":"ShengwangChatUIKit"}],"externalID":"c:@CM@ShengwangChatUIKit@objc(cs)GroupServiceImplement(im)createGroupWithSubject:description:inviterIds:message:option:completion:"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupServiceImplement\/createGroup(subject:description:inviterIds:message:option:completion:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"createGroup"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"subject"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"text":"description","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"inviterIds","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"option"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"ChatGroupOption","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatGroupOption","preciseIdentifier":"s:18ShengwangChatUIKit0B11GroupOptiona"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"attribute"},{"kind":"text","text":" ("},{"preciseIdentifier":"s:18ShengwangChatUIKit0B5Groupa","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatGroup","text":"ChatGroup"},{"text":"?, ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatError","text":"ChatError","preciseIdentifier":"s:18ShengwangChatUIKit0B5Errora"},{"text":"?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"platforms":["iOS"]}]},{"parameters":[{"name":"subject","content":[{"type":"paragraph","inlineContent":[{"text":"Group’s subject.","type":"text"}]}]},{"name":"description","content":[{"inlineContent":[{"text":"Group’s description.","type":"text"}],"type":"paragraph"}]},{"name":"inviterIds","content":[{"type":"paragraph","inlineContent":[{"text":"Array of user IDs of users invited by the group owner.","type":"text"}]}]},{"name":"message","content":[{"inlineContent":[{"type":"text","text":"Invitation extension"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"","type":"text"},{"isActive":true,"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatGroupOption","type":"reference"}],"type":"paragraph"}],"name":"option"},{"content":[{"inlineContent":[{"type":"text","text":"The request callback contains the group object and error information. If successful, a non-empty group object will be returned. If failed, a non-empty group object will be returned."}],"type":"paragraph"}],"name":"completion"}],"kind":"parameters"}],"variants":[{"paths":["\/documentation\/shengwangchatuikit\/groupserviceimplement\/creategroup(subject:description:inviterids:message:option:completion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/groupserviceimplement\/creategroup(subject:description:inviterids:message:option:completion:)"]}],"abstract":[{"text":"Create a group.","type":"text"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/GroupServiceImplement/createGroup(subject:description:inviterIds:message:option:completion:)":{"abstract":[{"type":"text","text":"Create a group."}],"title":"createGroup(subject:description:inviterIds:message:option:completion:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"createGroup"},{"text":"(","kind":"text"},{"text":"subject","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"description"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"inviterIds","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"message"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"option","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ChatGroupOption","kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit0B11GroupOptiona"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": (","kind":"text"},{"preciseIdentifier":"s:18ShengwangChatUIKit0B5Groupa","text":"ChatGroup","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"ChatError","preciseIdentifier":"s:18ShengwangChatUIKit0B5Errora"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"createGroupWithSubject:description:inviterIds:message:option:completion:"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupServiceImplement\/createGroup(subject:description:inviterIds:message:option:completion:)","url":"\/documentation\/shengwangchatuikit\/groupserviceimplement\/creategroup(subject:description:inviterids:message:option:completion:)","kind":"symbol","role":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatError":{"fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChatError"}],"role":"symbol","navigatorTitle":[{"text":"ChatError","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatError","url":"\/documentation\/shengwangchatuikit\/chaterror","title":"ChatError","kind":"symbol","abstract":[]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/GroupServiceImplement":{"type":"topic","url":"\/documentation\/shengwangchatuikit\/groupserviceimplement","kind":"symbol","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"GroupServiceImplement","kind":"identifier"}],"title":"GroupServiceImplement","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupServiceImplement","navigatorTitle":[{"text":"GroupServiceImplement","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/GroupServiceImplement/GroupService-Implementations":{"url":"\/documentation\/shengwangchatuikit\/groupserviceimplement\/groupservice-implementations","type":"topic","kind":"article","abstract":[],"role":"collectionGroup","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupServiceImplement\/GroupService-Implementations","title":"GroupService Implementations"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatGroupOption":{"abstract":[],"url":"\/documentation\/shengwangchatuikit\/chatgroupoption","title":"ChatGroupOption","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ChatGroupOption"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatGroupOption","kind":"symbol","type":"topic","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChatGroupOption","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatGroup":{"type":"topic","role":"symbol","title":"ChatGroup","kind":"symbol","abstract":[],"navigatorTitle":[{"text":"ChatGroup","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/chatgroup","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatGroup","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"text":"ChatGroup","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"value":"createGroupWithSubject:description:inviterIds:message:option:completion:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"createGroupWithSubject:description:inviterIds:message:option:completion:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"createGroupWithSubject:"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"subject","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"description:"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"description","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"inviterIds:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier","text":"NSArray<NSString *>"},{"kind":"text","text":" *) "},{"text":"inviterIds","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"message:"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"message","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"option:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"AgoraChatGroupOptions","preciseIdentifier":"c:objc(cs)AgoraChatGroupOptions"},{"kind":"text","text":" *) "},{"text":"option","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"completion:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":" (^","kind":"text"},{"text":")(","kind":"text"},{"kind":"typeIdentifier","text":"AgoraChatGroup","preciseIdentifier":"c:objc(cs)AgoraChatGroup"},{"text":" * ","kind":"text"},{"text":"","kind":"internalParam"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AgoraChatError","text":"AgoraChatError"},{"text":" * ","kind":"text"},{"text":"","kind":"internalParam"},{"text":")) ","kind":"text"},{"kind":"internalParam","text":"completion"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":"createGroupWithSubject:description:inviterIds:message:option:completion:","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupServiceImplement~1createGroup(subject:description:inviterIds:message:option:completion:)\/title","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"createGroupWithSubject:description:inviterIds:message:option:completion:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupServiceImplement~1createGroup(subject:description:inviterIds:message:option:completion:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupServiceImplement\/title","value":"GroupServiceImplement"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupServiceImplement\/fragments","value":[{"kind":"identifier","text":"GroupServiceImplement"}],"op":"replace"},{"op":"replace","value":[{"text":"GroupServiceImplement","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupServiceImplement\/navigatorTitle"}]}]}