{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupServiceImplement\/groupInvitationDidDecline(_:invitee:reason:)"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"AgoraChatGroupManagerDelegate.groupInvitationDidDecline(_:invitee:reason:)"},{"type":"text","text":"."}],"metadata":{"extendedModule":"ShengwangChatUIKit","modules":[{"name":"ShengwangChatUIKit"}],"roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"groupInvitationDidDecline"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:18ShengwangChatUIKit0B5Groupa","kind":"typeIdentifier","text":"ChatGroup"},{"text":", ","kind":"text"},{"text":"invitee","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"reason"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?)","kind":"text"}],"title":"groupInvitationDidDecline(_:invitee:reason:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"groupInvitationDidDecline:invitee:reason:"}],"externalID":"c:@CM@ShengwangChatUIKit@objc(cs)GroupServiceImplement(im)groupInvitationDidDecline:invitee:reason:","symbolKind":"method"},"variants":[{"paths":["\/documentation\/shengwangchatuikit\/groupserviceimplement\/groupinvitationdiddecline(_:invitee:reason:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/shengwangchatuikit\/groupserviceimplement\/groupinvitationdiddecline(_:invitee:reason:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"groupInvitationDidDecline"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"aGroup"},{"kind":"text","text":": "},{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatGroup","preciseIdentifier":"s:18ShengwangChatUIKit0B5Groupa","text":"ChatGroup","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"invitee","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"aInvitee"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"reason","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"aReason"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupServiceImplement","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupServiceImplement\/AgoraChatGroupManagerDelegate-Implementations"]]},"sections":[],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/GroupServiceImplement/groupInvitationDidDecline(_:invitee:reason:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"groupInvitationDidDecline"},{"kind":"text","text":"("},{"text":"ChatGroup","kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit0B5Groupa"},{"kind":"text","text":", "},{"kind":"externalParam","text":"invitee"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"reason","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?)","kind":"text"}],"kind":"symbol","title":"groupInvitationDidDecline(_:invitee:reason:)","type":"topic","url":"\/documentation\/shengwangchatuikit\/groupserviceimplement\/groupinvitationdiddecline(_:invitee:reason:)","abstract":[],"role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupServiceImplement\/groupInvitationDidDecline(_:invitee:reason:)","navigatorTitle":[{"text":"groupInvitationDidDecline:invitee:reason:","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/GroupServiceImplement":{"type":"topic","url":"\/documentation\/shengwangchatuikit\/groupserviceimplement","kind":"symbol","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"GroupServiceImplement","kind":"identifier"}],"title":"GroupServiceImplement","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupServiceImplement","navigatorTitle":[{"text":"GroupServiceImplement","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/GroupServiceImplement/AgoraChatGroupManagerDelegate-Implementations":{"abstract":[],"kind":"article","role":"collectionGroup","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupServiceImplement\/AgoraChatGroupManagerDelegate-Implementations","url":"\/documentation\/shengwangchatuikit\/groupserviceimplement\/agorachatgroupmanagerdelegate-implementations","title":"AgoraChatGroupManagerDelegate Implementations","type":"topic"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatGroup":{"type":"topic","role":"symbol","title":"ChatGroup","kind":"symbol","abstract":[],"navigatorTitle":[{"text":"ChatGroup","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/chatgroup","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatGroup","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"text":"ChatGroup","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"groupInvitationDidDecline:invitee:reason:","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"value":[{"text":"- ","kind":"text"},{"text":"groupInvitationDidDecline:invitee:reason:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"groupInvitationDidDecline:"},{"text":"(","kind":"text"},{"text":"AgoraChatGroup","preciseIdentifier":"c:objc(cs)AgoraChatGroup","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"aGroup"},{"text":" ","kind":"text"},{"text":"invitee:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"text":"aInvitee","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"reason:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"aReason"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupServiceImplement~1groupInvitationDidDecline(_:invitee:reason:)\/title","value":"groupInvitationDidDecline:invitee:reason:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupServiceImplement~1groupInvitationDidDecline(_:invitee:reason:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"groupInvitationDidDecline:invitee:reason:","kind":"identifier"}]},{"op":"replace","value":"GroupServiceImplement","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupServiceImplement\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupServiceImplement\/fragments","op":"replace","value":[{"kind":"identifier","text":"GroupServiceImplement"}]},{"value":[{"text":"GroupServiceImplement","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupServiceImplement\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}