{"sections":[],"abstract":[{"text":"Inherited from ","type":"text"},{"code":"AgoraChatThreadManagerDelegate.onUserKickOutOfChatThread(_:)","type":"codeVoice"},{"type":"text","text":"."}],"metadata":{"navigatorTitle":[{"text":"onUserKickOutOfChatThread:","kind":"identifier"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"onUserKickOutOfChatThread","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"s:18ShengwangChatUIKit05GroupB11ThreadEventa","text":"GroupChatThreadEvent","kind":"typeIdentifier"},{"kind":"text","text":")"}],"roleHeading":"Instance Method","modules":[{"name":"ShengwangChatUIKit"}],"extendedModule":"ShengwangChatUIKit","title":"onUserKickOutOfChatThread(_:)","symbolKind":"method","externalID":"c:@CM@ShengwangChatUIKit@objc(cs)GroupServiceImplement(im)onUserKickOutOfChatThread:"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/groupserviceimplement\/onuserkickoutofchatthread(_:)"]},{"paths":["\/documentation\/shengwangchatuikit\/groupserviceimplement\/onuserkickoutofchatthread(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupServiceImplement","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupServiceImplement\/AgoraChatThreadManagerDelegate-Implementations"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupServiceImplement\/onUserKickOutOfChatThread(_:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onUserKickOutOfChatThread","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"event","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:18ShengwangChatUIKit05GroupB11ThreadEventa","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupChatThreadEvent","text":"GroupChatThreadEvent"},{"kind":"text","text":")"}]}]}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/GroupServiceImplement/onUserKickOutOfChatThread(_:)":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupServiceImplement\/onUserKickOutOfChatThread(_:)","navigatorTitle":[{"text":"onUserKickOutOfChatThread:","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/groupserviceimplement\/onuserkickoutofchatthread(_:)","type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"onUserKickOutOfChatThread","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"GroupChatThreadEvent","preciseIdentifier":"s:18ShengwangChatUIKit05GroupB11ThreadEventa"},{"text":")","kind":"text"}],"title":"onUserKickOutOfChatThread(_:)","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/GroupServiceImplement/AgoraChatThreadManagerDelegate-Implementations":{"url":"\/documentation\/shengwangchatuikit\/groupserviceimplement\/agorachatthreadmanagerdelegate-implementations","type":"topic","role":"collectionGroup","title":"AgoraChatThreadManagerDelegate Implementations","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupServiceImplement\/AgoraChatThreadManagerDelegate-Implementations","kind":"article","abstract":[]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/GroupServiceImplement":{"type":"topic","url":"\/documentation\/shengwangchatuikit\/groupserviceimplement","kind":"symbol","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"GroupServiceImplement","kind":"identifier"}],"title":"GroupServiceImplement","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupServiceImplement","navigatorTitle":[{"text":"GroupServiceImplement","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/GroupChatThreadEvent":{"role":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupChatThreadEvent"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupChatThreadEvent","navigatorTitle":[{"text":"GroupChatThreadEvent","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/groupchatthreadevent","kind":"symbol","title":"GroupChatThreadEvent","abstract":[],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"onUserKickOutOfChatThread:","path":"\/metadata\/title","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"onUserKickOutOfChatThread:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"onUserKickOutOfChatThread:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)AgoraChatThreadEvent","kind":"typeIdentifier","text":"AgoraChatThreadEvent"},{"text":" *) ","kind":"text"},{"text":"event","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupServiceImplement~1onUserKickOutOfChatThread(_:)\/title","value":"onUserKickOutOfChatThread:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"onUserKickOutOfChatThread:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupServiceImplement~1onUserKickOutOfChatThread(_:)\/fragments"},{"op":"replace","value":"GroupServiceImplement","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupServiceImplement\/title"},{"op":"replace","value":[{"text":"GroupServiceImplement","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupServiceImplement\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupServiceImplement\/navigatorTitle","value":[{"kind":"identifier","text":"GroupServiceImplement"}]}]}]}