{"variants":[{"paths":["\/documentation\/shengwangchatuikit\/groupserviceimplement\/setmemberattributes(attributes:groupid:userid:completion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/shengwangchatuikit\/groupserviceimplement\/setmemberattributes(attributes:groupid:userid:completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"role":"symbol","extendedModule":"ShengwangChatUIKit","modules":[{"name":"ShengwangChatUIKit"}],"symbolKind":"method","navigatorTitle":[{"text":"setMemberAttributesWithAttributes:groupId:userId:completion:","kind":"identifier"}],"externalID":"c:@CM@ShengwangChatUIKit@objc(cs)GroupServiceImplement(im)setMemberAttributesWithAttributes:groupId:userId:completion:","title":"setMemberAttributes(attributes:groupId:userId:completion:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"setMemberAttributes","kind":"identifier"},{"kind":"text","text":"("},{"text":"attributes","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Dictionary","kind":"typeIdentifier","preciseIdentifier":"s:SD"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":">, ","kind":"text"},{"text":"groupId","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"userId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": ("},{"text":"ChatError","kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit0B5Errora"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"roleHeading":"Instance Method"},"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupServiceImplement","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupServiceImplement\/GroupService-Implementations"]]},"abstract":[{"type":"text","text":"Set custom properties for group members. (You and administrators and above can call this method)"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupServiceImplement\/setMemberAttributes(attributes:groupId:userId:completion:)"},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"setMemberAttributes","kind":"identifier"},{"text":"(","kind":"text"},{"text":"attributes","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Dictionary","kind":"typeIdentifier","preciseIdentifier":"s:SD"},{"kind":"text","text":"<"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":">, "},{"text":"groupId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"userId"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"text":" (","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatError","kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit0B5Errora","text":"ChatError"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")","kind":"text"}]}]},{"kind":"parameters","parameters":[{"name":"attributes","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Attributes map."}]}]},{"content":[{"inlineContent":[{"type":"text","text":"ID of the group."}],"type":"paragraph"}],"name":"groupId"},{"name":"userId","content":[{"inlineContent":[{"type":"text","text":"ID of the user."}],"type":"paragraph"}]},{"name":"completion","content":[{"inlineContent":[{"type":"text","text":"The request callback contains the group object and error information. If successful, a empty error object will be returned. If failed, a non-empty group object will be returned."}],"type":"paragraph"}]}]}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/GroupServiceImplement/setMemberAttributes(attributes:groupId:userId:completion:)":{"title":"setMemberAttributes(attributes:groupId:userId:completion:)","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupServiceImplement\/setMemberAttributes(attributes:groupId:userId:completion:)","url":"\/documentation\/shengwangchatuikit\/groupserviceimplement\/setmemberattributes(attributes:groupid:userid:completion:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setMemberAttributes"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"attributes"},{"text":": ","kind":"text"},{"text":"Dictionary","kind":"typeIdentifier","preciseIdentifier":"s:SD"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":">, ","kind":"text"},{"text":"groupId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"userId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": ("},{"preciseIdentifier":"s:18ShengwangChatUIKit0B5Errora","text":"ChatError","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"kind":"text","text":")"}],"role":"symbol","abstract":[{"text":"Set custom properties for group members. (You and administrators and above can call this method)","type":"text"}],"navigatorTitle":[{"text":"setMemberAttributesWithAttributes:groupId:userId:completion:","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/GroupServiceImplement/GroupService-Implementations":{"url":"\/documentation\/shengwangchatuikit\/groupserviceimplement\/groupservice-implementations","type":"topic","kind":"article","abstract":[],"role":"collectionGroup","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupServiceImplement\/GroupService-Implementations","title":"GroupService Implementations"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatError":{"fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChatError"}],"role":"symbol","navigatorTitle":[{"text":"ChatError","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatError","url":"\/documentation\/shengwangchatuikit\/chaterror","title":"ChatError","kind":"symbol","abstract":[]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/GroupServiceImplement":{"type":"topic","url":"\/documentation\/shengwangchatuikit\/groupserviceimplement","kind":"symbol","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"GroupServiceImplement","kind":"identifier"}],"title":"GroupServiceImplement","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupServiceImplement","navigatorTitle":[{"text":"GroupServiceImplement","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"setMemberAttributesWithAttributes:groupId:userId:completion:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"setMemberAttributesWithAttributes:groupId:userId:completion:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"setMemberAttributesWithAttributes:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Q$objc(cs)NSDictionary","kind":"typeIdentifier","text":"NSDictionary<NSString *,NSString *>"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"attributes"},{"text":" ","kind":"text"},{"kind":"identifier","text":"groupId:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"groupId"},{"text":" ","kind":"text"},{"kind":"identifier","text":"userId:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"userId"},{"kind":"text","text":" "},{"text":"completion:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":" (^","kind":"text"},{"text":")(","kind":"text"},{"text":"AgoraChatError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AgoraChatError"},{"text":" * ","kind":"text"},{"text":"","kind":"internalParam"},{"kind":"text","text":")) "},{"text":"completion","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupServiceImplement~1setMemberAttributes(attributes:groupId:userId:completion:)\/title","value":"setMemberAttributesWithAttributes:groupId:userId:completion:"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupServiceImplement~1setMemberAttributes(attributes:groupId:userId:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"setMemberAttributesWithAttributes:groupId:userId:completion:","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupServiceImplement\/title","value":"GroupServiceImplement"},{"value":[{"kind":"identifier","text":"GroupServiceImplement"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupServiceImplement\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupServiceImplement\/navigatorTitle","value":[{"text":"GroupServiceImplement","kind":"identifier"}],"op":"replace"}]}]}