{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"navigationClick"},{"text":"(","kind":"text"},{"text":"type","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ChatNavigationBarClickEvent","preciseIdentifier":"c:@M@ShengwangChatUIKit@E@ChatNavigationBarClickEvent","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatNavigationBarClickEvent","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"indexPath"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation9IndexPathV","text":"IndexPath","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/shengwangchatuikit\/joinedgroupsviewcontroller\/navigationclick(type:indexpath:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/shengwangchatuikit\/joinedgroupsviewcontroller\/navigationclick(type:indexpath:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/JoinedGroupsViewController"]]},"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/JoinedGroupsViewController\/navigationClick(type:indexPath:)","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"metadata":{"roleHeading":"Instance Method","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"navigationClickWithType:indexPath:"}],"externalID":"c:@M@ShengwangChatUIKit@objc(cs)JoinedGroupsViewController(im)navigationClickWithType:indexPath:","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"navigationClick"},{"kind":"text","text":"("},{"text":"type","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@E@ChatNavigationBarClickEvent","text":"ChatNavigationBarClickEvent","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"indexPath"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation9IndexPathV","text":"IndexPath","kind":"typeIdentifier"},{"kind":"text","text":"?)"}],"title":"navigationClick(type:indexPath:)","modules":[{"name":"ShengwangChatUIKit"}]},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/JoinedGroupsViewController":{"title":"JoinedGroupsViewController","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"JoinedGroupsViewController"}],"url":"\/documentation\/shengwangchatuikit\/joinedgroupsviewcontroller","role":"symbol","abstract":[],"type":"topic","navigatorTitle":[{"text":"JoinedGroupsViewController","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/JoinedGroupsViewController","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatNavigationBarClickEvent":{"abstract":[],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatNavigationBarClickEvent","navigatorTitle":[{"kind":"identifier","text":"ChatNavigationBarClickEvent"}],"kind":"symbol","url":"\/documentation\/shengwangchatuikit\/chatnavigationbarclickevent","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatNavigationBarClickEvent"}],"title":"ChatNavigationBarClickEvent","type":"topic"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/JoinedGroupsViewController/navigationClick(type:indexPath:)":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/JoinedGroupsViewController\/navigationClick(type:indexPath:)","role":"symbol","url":"\/documentation\/shengwangchatuikit\/joinedgroupsviewcontroller\/navigationclick(type:indexpath:)","title":"navigationClick(type:indexPath:)","kind":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"navigationClick"},{"text":"(","kind":"text"},{"text":"type","kind":"externalParam"},{"kind":"text","text":": "},{"text":"ChatNavigationBarClickEvent","kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@E@ChatNavigationBarClickEvent"},{"text":", ","kind":"text"},{"text":"indexPath","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation9IndexPathV","text":"IndexPath","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"type":"topic","navigatorTitle":[{"text":"navigationClickWithType:indexPath:","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"navigationClickWithType:indexPath:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"navigationClickWithType:indexPath:","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"text":"navigationClickWithType:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatNavigationBarClickEvent","text":"ChatNavigationBarClickEvent","preciseIdentifier":"c:@M@ShengwangChatUIKit@E@ChatNavigationBarClickEvent"},{"kind":"text","text":") "},{"text":"type","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"indexPath:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSIndexPath","text":"NSIndexPath","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"indexPath","kind":"internalParam"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"JoinedGroupsViewController","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1JoinedGroupsViewController\/title"},{"value":[{"text":"JoinedGroupsViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1JoinedGroupsViewController\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1JoinedGroupsViewController\/navigatorTitle","value":[{"kind":"identifier","text":"JoinedGroupsViewController"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatNavigationBarClickEvent\/title","value":"ChatNavigationBarClickEvent","op":"replace"},{"value":[{"kind":"identifier","text":"ChatNavigationBarClickEvent"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatNavigationBarClickEvent\/fragments","op":"replace"},{"value":[{"text":"ChatNavigationBarClickEvent","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatNavigationBarClickEvent\/navigatorTitle"},{"op":"replace","value":"navigationClickWithType:indexPath:","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1JoinedGroupsViewController~1navigationClick(type:indexPath:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1JoinedGroupsViewController~1navigationClick(type:indexPath:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"navigationClickWithType:indexPath:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}