{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"attribute","text":"@"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"refreshGroup"},{"text":"(","kind":"text"},{"text":"groupId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"name","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"refreshGroupWithGroupId:name:"}],"externalID":"c:@CM@ShengwangChatUIKit@objc(cs)JoinedGroupsViewController(im)refreshGroupWithGroupId:name:","title":"refreshGroup(groupId:name:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"refreshGroup","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"groupId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"text":"name","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}],"modules":[{"name":"ShengwangChatUIKit"}],"role":"symbol","extendedModule":"ShengwangChatUIKit","roleHeading":"Instance Method"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/JoinedGroupsViewController"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/JoinedGroupsViewController\/refreshGroup(groupId:name:)"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/joinedgroupsviewcontroller\/refreshgroup(groupid:name:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/joinedgroupsviewcontroller\/refreshgroup(groupid:name:)"]}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/JoinedGroupsViewController/refreshGroup(groupId:name:)":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"refreshGroupWithGroupId:name:"}],"url":"\/documentation\/shengwangchatuikit\/joinedgroupsviewcontroller\/refreshgroup(groupid:name:)","kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"refreshGroup","kind":"identifier"},{"text":"(","kind":"text"},{"text":"groupId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"name","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}],"abstract":[],"title":"refreshGroup(groupId:name:)","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/JoinedGroupsViewController\/refreshGroup(groupId:name:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/JoinedGroupsViewController":{"title":"JoinedGroupsViewController","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"JoinedGroupsViewController"}],"url":"\/documentation\/shengwangchatuikit\/joinedgroupsviewcontroller","role":"symbol","abstract":[],"type":"topic","navigatorTitle":[{"text":"JoinedGroupsViewController","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/JoinedGroupsViewController","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"refreshGroupWithGroupId:name:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"refreshGroupWithGroupId:name:","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"text":"refreshGroupWithGroupId:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"groupId"},{"text":" ","kind":"text"},{"text":"name:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"name","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":"refreshGroupWithGroupId:name:","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1JoinedGroupsViewController~1refreshGroup(groupId:name:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1JoinedGroupsViewController~1refreshGroup(groupId:name:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"refreshGroupWithGroupId:name:"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1JoinedGroupsViewController\/title","value":"JoinedGroupsViewController","op":"replace"},{"value":[{"text":"JoinedGroupsViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1JoinedGroupsViewController\/fragments","op":"replace"},{"op":"replace","value":[{"text":"JoinedGroupsViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1JoinedGroupsViewController\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}