{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"@","kind":"attribute"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeGroup"},{"text":"(","kind":"text"},{"text":"notification","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Notification","preciseIdentifier":"s:10Foundation12NotificationV"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"metadata":{"role":"symbol","title":"removeGroup(notification:)","symbolKind":"method","externalID":"c:@M@ShengwangChatUIKit@objc(cs)JoinedGroupsViewController(im)removeGroupWithNotification:","navigatorTitle":[{"kind":"identifier","text":"removeGroupWithNotification:"}],"roleHeading":"Instance Method","modules":[{"name":"ShengwangChatUIKit"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"removeGroup"},{"text":"(","kind":"text"},{"text":"notification","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Notification","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation12NotificationV"},{"text":")","kind":"text"}]},"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/JoinedGroupsViewController\/removeGroup(notification:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/JoinedGroupsViewController"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/joinedgroupsviewcontroller\/removegroup(notification:)"]},{"paths":["\/documentation\/shengwangchatuikit\/joinedgroupsviewcontroller\/removegroup(notification:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/JoinedGroupsViewController/removeGroup(notification:)":{"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"removeGroup"},{"text":"(","kind":"text"},{"text":"notification","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Notification","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation12NotificationV"},{"kind":"text","text":")"}],"abstract":[],"role":"symbol","type":"topic","navigatorTitle":[{"text":"removeGroupWithNotification:","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/JoinedGroupsViewController\/removeGroup(notification:)","title":"removeGroup(notification:)","url":"\/documentation\/shengwangchatuikit\/joinedgroupsviewcontroller\/removegroup(notification:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/JoinedGroupsViewController":{"title":"JoinedGroupsViewController","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"JoinedGroupsViewController"}],"url":"\/documentation\/shengwangchatuikit\/joinedgroupsviewcontroller","role":"symbol","abstract":[],"type":"topic","navigatorTitle":[{"text":"JoinedGroupsViewController","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/JoinedGroupsViewController","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"removeGroupWithNotification:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"removeGroupWithNotification:"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"removeGroupWithNotification:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSNotification","text":"NSNotification","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"notification","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"value":"removeGroupWithNotification:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1JoinedGroupsViewController~1removeGroup(notification:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1JoinedGroupsViewController~1removeGroup(notification:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"removeGroupWithNotification:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1JoinedGroupsViewController\/title","op":"replace","value":"JoinedGroupsViewController"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1JoinedGroupsViewController\/fragments","op":"replace","value":[{"kind":"identifier","text":"JoinedGroupsViewController"}]},{"op":"replace","value":[{"kind":"identifier","text":"JoinedGroupsViewController"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1JoinedGroupsViewController\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}