{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"optional"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"noDisturbEventNotify","kind":"identifier"},{"kind":"text","text":"("},{"text":"jsonString","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"jsonString","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Json"}]}]}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MultiDeviceListener\/noDisturbEventNotify(jsonString:)","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"ShengwangChatUIKit"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"noDisturbEventNotify","kind":"identifier"},{"text":"(","kind":"text"},{"text":"jsonString","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"role":"symbol","required":true,"title":"noDisturbEventNotify(jsonString:)","symbolKind":"method","roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"noDisturbEventNotifyWithJsonString:"}],"externalID":"c:@M@ShengwangChatUIKit@objc(pl)MultiDeviceListener(im)noDisturbEventNotifyWithJsonString:"},"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MultiDeviceListener"]]},"abstract":[{"text":"Notifications after Do Not Disturb is set on other devices","type":"text"}],"variants":[{"paths":["\/documentation\/shengwangchatuikit\/multidevicelistener\/nodisturbeventnotify(jsonstring:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/multidevicelistener\/nodisturbeventnotify(jsonstring:)"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MultiDeviceListener/noDisturbEventNotify(jsonString:)":{"required":true,"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"noDisturbEventNotify","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"jsonString"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"url":"\/documentation\/shengwangchatuikit\/multidevicelistener\/nodisturbeventnotify(jsonstring:)","abstract":[{"type":"text","text":"Notifications after Do Not Disturb is set on other devices"}],"kind":"symbol","title":"noDisturbEventNotify(jsonString:)","type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MultiDeviceListener\/noDisturbEventNotify(jsonString:)","navigatorTitle":[{"kind":"identifier","text":"noDisturbEventNotifyWithJsonString:"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MultiDeviceListener":{"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MultiDeviceListener"}],"abstract":[],"type":"topic","title":"MultiDeviceListener","url":"\/documentation\/shengwangchatuikit\/multidevicelistener","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"MultiDeviceListener","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MultiDeviceListener"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"noDisturbEventNotifyWithJsonString:","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"noDisturbEventNotifyWithJsonString:"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"noDisturbEventNotifyWithJsonString:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"text":"jsonString","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/primaryContentSections\/1","value":{"parameters":[{"name":"jsonString","content":[{"inlineContent":[{"text":"Json","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MultiDeviceListener~1noDisturbEventNotify(jsonString:)\/title","value":"noDisturbEventNotifyWithJsonString:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MultiDeviceListener~1noDisturbEventNotify(jsonString:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"noDisturbEventNotifyWithJsonString:"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MultiDeviceListener\/title","op":"replace","value":"MultiDeviceListener"},{"value":[{"text":"MultiDeviceListener","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MultiDeviceListener\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"MultiDeviceListener"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MultiDeviceListener\/navigatorTitle"}]}]}