{"sections":[],"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"onConversationEventDidChanged","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"event"},{"kind":"text","text":": "},{"text":"MultiDeviceEvent","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MultiDeviceEvent","preciseIdentifier":"s:18ShengwangChatUIKit16MultiDeviceEventa"},{"kind":"text","text":", "},{"text":"conversationId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"conversationType"},{"text":": ","kind":"text"},{"text":"ChatConversationType","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatConversationType","preciseIdentifier":"s:18ShengwangChatUIKit0B16ConversationTypea","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"]}]},{"parameters":[{"name":"event","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MultiDeviceEvent"}]}]},{"name":"conversationId","content":[{"inlineContent":[{"text":"The id of the group.","type":"text"}],"type":"paragraph"}]},{"name":"conversationType","content":[{"inlineContent":[{"type":"text","text":""},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatConversationType"},{"type":"text","text":"."}],"type":"paragraph"}]}],"kind":"parameters"}],"abstract":[{"text":"When a event of conversation changes on other devices","type":"text"}],"variants":[{"paths":["\/documentation\/shengwangchatuikit\/multidevicelistener\/onconversationeventdidchanged(event:conversationid:conversationtype:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/multidevicelistener\/onconversationeventdidchanged(event:conversationid:conversationtype:)"]}],"metadata":{"modules":[{"name":"ShengwangChatUIKit"}],"externalID":"c:@M@ShengwangChatUIKit@objc(pl)MultiDeviceListener(im)onConversationEventDidChangedWithEvent:conversationId:conversationType:","navigatorTitle":[{"kind":"identifier","text":"onConversationEventDidChangedWithEvent:conversationId:conversationType:"}],"symbolKind":"method","role":"symbol","roleHeading":"Instance Method","title":"onConversationEventDidChanged(event:conversationId:conversationType:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"onConversationEventDidChanged","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"event"},{"kind":"text","text":": "},{"text":"MultiDeviceEvent","kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit16MultiDeviceEventa"},{"kind":"text","text":", "},{"text":"conversationId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"conversationType","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:18ShengwangChatUIKit0B16ConversationTypea","text":"ChatConversationType","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MultiDeviceListener"]]},"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MultiDeviceListener\/onConversationEventDidChanged(event:conversationId:conversationType:)","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatConversationType":{"type":"topic","role":"symbol","title":"ChatConversationType","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatConversationType","abstract":[],"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatConversationType"}],"url":"\/documentation\/shengwangchatuikit\/chatconversationtype","kind":"symbol","navigatorTitle":[{"text":"ChatConversationType","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MultiDeviceEvent":{"fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MultiDeviceEvent"}],"role":"symbol","url":"\/documentation\/shengwangchatuikit\/multideviceevent","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MultiDeviceEvent","title":"MultiDeviceEvent","kind":"symbol","abstract":[],"navigatorTitle":[{"text":"MultiDeviceEvent","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MultiDeviceListener/onConversationEventDidChanged(event:conversationId:conversationType:)":{"type":"topic","url":"\/documentation\/shengwangchatuikit\/multidevicelistener\/onconversationeventdidchanged(event:conversationid:conversationtype:)","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MultiDeviceListener\/onConversationEventDidChanged(event:conversationId:conversationType:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onConversationEventDidChanged","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"event"},{"kind":"text","text":": "},{"text":"MultiDeviceEvent","kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit16MultiDeviceEventa"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"conversationId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"conversationType"},{"kind":"text","text":": "},{"text":"ChatConversationType","preciseIdentifier":"s:18ShengwangChatUIKit0B16ConversationTypea","kind":"typeIdentifier"},{"kind":"text","text":")"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"onConversationEventDidChangedWithEvent:conversationId:conversationType:","kind":"identifier"}],"title":"onConversationEventDidChanged(event:conversationId:conversationType:)","abstract":[{"text":"When a event of conversation changes on other devices","type":"text"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MultiDeviceListener":{"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MultiDeviceListener"}],"abstract":[],"type":"topic","title":"MultiDeviceListener","url":"\/documentation\/shengwangchatuikit\/multidevicelistener","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"MultiDeviceListener","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MultiDeviceListener"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","value":"onConversationEventDidChangedWithEvent:conversationId:conversationType:","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onConversationEventDidChangedWithEvent:conversationId:conversationType:"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"onConversationEventDidChangedWithEvent:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@E@AgoraChatMultiDevicesEvent","text":"AgoraChatMultiDevicesEvent","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"event","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"conversationId:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"conversationId"},{"kind":"text","text":" "},{"kind":"identifier","text":"conversationType:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraChatConversationType","preciseIdentifier":"c:@E@AgoraChatConversationType"},{"text":") ","kind":"text"},{"text":"conversationType","kind":"internalParam"},{"text":";","kind":"text"}]}]},"op":"replace"},{"path":"\/primaryContentSections\/1","op":"replace","value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"reference","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MultiDeviceEvent","isActive":true}]}],"name":"event"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The id of the group."}]}],"name":"conversationId"},{"content":[{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatConversationType","type":"reference","isActive":true},{"type":"text","text":"."}]}],"name":"conversationType"}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MultiDeviceListener~1onConversationEventDidChanged(event:conversationId:conversationType:)\/title","value":"onConversationEventDidChangedWithEvent:conversationId:conversationType:"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MultiDeviceListener~1onConversationEventDidChanged(event:conversationId:conversationType:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onConversationEventDidChangedWithEvent:conversationId:conversationType:"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MultiDeviceListener\/title","value":"MultiDeviceListener","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MultiDeviceListener\/fragments","value":[{"kind":"identifier","text":"MultiDeviceListener"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MultiDeviceListener\/navigatorTitle","value":[{"kind":"identifier","text":"MultiDeviceListener"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}