{"abstract":[{"type":"text","text":"Remove UI action handler."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"removeActionHandler","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"actionHandler"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(pl)ContactListActionEventsDelegate","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactListActionEventsDelegate","text":"ContactListActionEventsDelegate","kind":"typeIdentifier"},{"kind":"text","text":")"}],"platforms":["iOS"]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"isActive":true,"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactListActionEventsDelegate","type":"reference"}]}],"name":"actionHandler"}],"kind":"parameters"}],"variants":[{"paths":["\/documentation\/shengwangchatuikit\/contactview\/removeactionhandler(actionhandler:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/shengwangchatuikit\/contactview\/removeactionhandler(actionhandler:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactView","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactView\/IContactListDriver-Implementations"]]},"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactView\/removeActionHandler(actionHandler:)","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"removeActionHandler","kind":"identifier"},{"text":"(","kind":"text"},{"text":"actionHandler","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(pl)ContactListActionEventsDelegate","kind":"typeIdentifier","text":"ContactListActionEventsDelegate"},{"text":")","kind":"text"}],"symbolKind":"method","modules":[{"name":"ShengwangChatUIKit"}],"title":"removeActionHandler(actionHandler:)","navigatorTitle":[{"kind":"identifier","text":"removeActionHandlerWithActionHandler:"}],"extendedModule":"ShengwangChatUIKit","roleHeading":"Instance Method","externalID":"c:@CM@ShengwangChatUIKit@objc(cs)ContactView(im)removeActionHandlerWithActionHandler:","role":"symbol"},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ContactView/IContactListDriver-Implementations":{"abstract":[],"type":"topic","url":"\/documentation\/shengwangchatuikit\/contactview\/icontactlistdriver-implementations","role":"collectionGroup","title":"IContactListDriver Implementations","kind":"article","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactView\/IContactListDriver-Implementations"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ContactListActionEventsDelegate":{"title":"ContactListActionEventsDelegate","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactListActionEventsDelegate","type":"topic","url":"\/documentation\/shengwangchatuikit\/contactlistactioneventsdelegate","abstract":[{"type":"text","text":"ContactList action events delegate."}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ContactListActionEventsDelegate","kind":"identifier"}],"navigatorTitle":[{"text":"ContactListActionEventsDelegate","kind":"identifier"}],"kind":"symbol","role":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ContactView":{"type":"topic","url":"\/documentation\/shengwangchatuikit\/contactview","title":"ContactView","role":"symbol","kind":"symbol","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ContactView","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactView","navigatorTitle":[{"kind":"identifier","text":"ContactView"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ContactView/removeActionHandler(actionHandler:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"removeActionHandler","kind":"identifier"},{"text":"(","kind":"text"},{"text":"actionHandler","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(pl)ContactListActionEventsDelegate","text":"ContactListActionEventsDelegate"},{"text":")","kind":"text"}],"type":"topic","navigatorTitle":[{"text":"removeActionHandlerWithActionHandler:","kind":"identifier"}],"title":"removeActionHandler(actionHandler:)","url":"\/documentation\/shengwangchatuikit\/contactview\/removeactionhandler(actionhandler:)","abstract":[{"text":"Remove UI action handler.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactView\/removeActionHandler(actionHandler:)","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","value":"removeActionHandlerWithActionHandler:","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"removeActionHandlerWithActionHandler:","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"removeActionHandlerWithActionHandler:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Qo@M@ShengwangChatUIKit@objc(pl)ContactListActionEventsDelegate","text":"id<ContactListActionEventsDelegate>","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"actionHandler","kind":"internalParam"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace"},{"op":"replace","value":{"parameters":[{"name":"actionHandler","content":[{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactListActionEventsDelegate","isActive":true,"type":"reference"}]}]}],"kind":"parameters"},"path":"\/primaryContentSections\/1"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactListActionEventsDelegate\/title","value":"ContactListActionEventsDelegate","op":"replace"},{"value":[{"text":"ContactListActionEventsDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactListActionEventsDelegate\/fragments"},{"value":[{"text":"ContactListActionEventsDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactListActionEventsDelegate\/navigatorTitle"},{"op":"replace","value":"ContactView","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactView\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactView\/fragments","value":[{"kind":"identifier","text":"ContactView"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactView\/navigatorTitle","value":[{"text":"ContactView","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactView~1removeActionHandler(actionHandler:)\/title","value":"removeActionHandlerWithActionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactView~1removeActionHandler(actionHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"removeActionHandlerWithActionHandler:"}]}]}]}