{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"tableView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"tableView","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UITableView","kind":"typeIdentifier","text":"UITableView"},{"kind":"text","text":", "},{"text":"viewForFooterInSection","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"section","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIView","text":"UIView","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"platforms":["iOS"],"languages":["swift"]}]}],"kind":"symbol","metadata":{"externalID":"c:@CM@ShengwangChatUIKit@objc(cs)ContactView(im)tableView:viewForFooterInSection:","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"tableView","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITableView","text":"UITableView"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"viewForFooterInSection"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:objc(cs)UIView","text":"UIView","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"symbolKind":"method","navigatorTitle":[{"text":"tableView:viewForFooterInSection:","kind":"identifier"}],"title":"tableView(_:viewForFooterInSection:)","extendedModule":"ShengwangChatUIKit","role":"symbol","modules":[{"name":"ShengwangChatUIKit"}],"roleHeading":"Instance Method"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/contactview\/tableview(_:viewforfooterinsection:)"]},{"paths":["\/documentation\/shengwangchatuikit\/contactview\/tableview(_:viewforfooterinsection:)"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"Inherited from ","type":"text"},{"code":"UITableViewDelegate.tableView(_:viewForFooterInSection:)","type":"codeVoice"},{"type":"text","text":"."}],"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactView","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactView\/UITableViewDelegate-Implementations"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactView\/tableView(_:viewForFooterInSection:)","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ContactView/tableView(_:viewForFooterInSection:)":{"abstract":[],"title":"tableView(_:viewForFooterInSection:)","type":"topic","role":"symbol","url":"\/documentation\/shengwangchatuikit\/contactview\/tableview(_:viewforfooterinsection:)","kind":"symbol","navigatorTitle":[{"text":"tableView:viewForFooterInSection:","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactView\/tableView(_:viewForFooterInSection:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"tableView"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UITableView","text":"UITableView","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"viewForFooterInSection","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIView","text":"UIView","kind":"typeIdentifier"},{"kind":"text","text":"?"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ContactView":{"type":"topic","url":"\/documentation\/shengwangchatuikit\/contactview","title":"ContactView","role":"symbol","kind":"symbol","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ContactView","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactView","navigatorTitle":[{"kind":"identifier","text":"ContactView"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ContactView/UITableViewDelegate-Implementations":{"url":"\/documentation\/shengwangchatuikit\/contactview\/uitableviewdelegate-implementations","type":"topic","role":"collectionGroup","title":"UITableViewDelegate Implementations","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactView\/UITableViewDelegate-Implementations","kind":"article","abstract":[]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"tableView:viewForFooterInSection:"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"tableView:viewForFooterInSection:"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"UIView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView"},{"text":" *) ","kind":"text"},{"text":"tableView:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UITableView","text":"UITableView","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"tableView","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"viewForFooterInSection:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"section"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","value":"tableView:viewForFooterInSection:","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactView~1tableView(_:viewForFooterInSection:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactView~1tableView(_:viewForFooterInSection:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"tableView:viewForFooterInSection:","kind":"identifier"}]},{"value":"ContactView","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactView\/title","op":"replace"},{"value":[{"text":"ContactView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactView\/fragments"},{"value":[{"kind":"identifier","text":"ContactView"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactView\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}