{"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactView\/UITableViewDataSource-Implementations","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/shengwangchatuikit\/contactview\/uitableviewdatasource-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/contactview\/uitableviewdatasource-implementations"]}],"topicSections":[{"title":"Instance Methods","anchor":"Instance-Methods","generated":true,"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactView\/numberOfSections(in:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactView\/tableView(_:cellForRowAt:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactView\/tableView(_:numberOfRowsInSection:)"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactView"]]},"sections":[],"kind":"article","metadata":{"roleHeading":"API Collection","role":"collectionGroup","modules":[{"name":"ShengwangChatUIKit"}],"title":"UITableViewDataSource Implementations"},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ContactView":{"type":"topic","url":"\/documentation\/shengwangchatuikit\/contactview","title":"ContactView","role":"symbol","kind":"symbol","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ContactView","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactView","navigatorTitle":[{"kind":"identifier","text":"ContactView"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ContactView/numberOfSections(in:)":{"type":"topic","role":"symbol","title":"numberOfSections(in:)","kind":"symbol","abstract":[],"navigatorTitle":[{"text":"numberOfSectionsInTableView:","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/contactview\/numberofsections(in:)","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactView\/numberOfSections(in:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"numberOfSections","kind":"identifier"},{"text":"(","kind":"text"},{"text":"in","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITableView","text":"UITableView"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ContactView/tableView(_:cellForRowAt:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"tableView"},{"text":"(","kind":"text"},{"text":"UITableView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITableView"},{"text":", ","kind":"text"},{"text":"cellForRowAt","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation9IndexPathV","text":"IndexPath"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"UITableViewCell","preciseIdentifier":"c:objc(cs)UITableViewCell"}],"url":"\/documentation\/shengwangchatuikit\/contactview\/tableview(_:cellforrowat:)","abstract":[],"kind":"symbol","type":"topic","title":"tableView(_:cellForRowAt:)","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactView\/tableView(_:cellForRowAt:)","navigatorTitle":[{"kind":"identifier","text":"tableView:cellForRowAtIndexPath:"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ContactView/tableView(_:numberOfRowsInSection:)":{"type":"topic","url":"\/documentation\/shengwangchatuikit\/contactview\/tableview(_:numberofrowsinsection:)","title":"tableView(_:numberOfRowsInSection:)","role":"symbol","kind":"symbol","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"tableView","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITableView","text":"UITableView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"numberOfRowsInSection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactView\/tableView(_:numberOfRowsInSection:)","navigatorTitle":[{"text":"tableView:numberOfRowsInSection:","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactView\/numberOfSections(in:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactView\/tableView(_:cellForRowAt:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactView\/tableView(_:numberOfRowsInSection:)"],"generated":true,"anchor":"Instance-Methods","title":"Instance Methods"}]},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactView\/title","value":"ContactView","op":"replace"},{"value":[{"text":"ContactView","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactView\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactView\/navigatorTitle","value":[{"text":"ContactView","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactView~1numberOfSections(in:)\/title","value":"numberOfSectionsInTableView:"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"numberOfSectionsInTableView:"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactView~1numberOfSections(in:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactView~1tableView(_:cellForRowAt:)\/title","op":"replace","value":"tableView:cellForRowAtIndexPath:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactView~1tableView(_:cellForRowAt:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"tableView:cellForRowAtIndexPath:","kind":"identifier"}]},{"value":"tableView:numberOfRowsInSection:","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactView~1tableView(_:numberOfRowsInSection:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactView~1tableView(_:numberOfRowsInSection:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"tableView:numberOfRowsInSection:","kind":"identifier"}]}]}]}