{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ThemeStyle\/dark"},"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ThemeStyle"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dark"}],"platforms":["iOS"]}]}],"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"dark","kind":"identifier"}],"externalID":"c:@M@ShengwangChatUIKit@E@ThemeStyle@ThemeStyleDark","role":"symbol","roleHeading":"Case","symbolKind":"case","modules":[{"name":"ShengwangChatUIKit"}],"title":"ThemeStyle.dark","navigatorTitle":[{"text":"ThemeStyleDark","kind":"identifier"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/themestyle\/dark"]},{"paths":["\/documentation\/shengwangchatuikit\/themestyle\/dark"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ThemeStyle/dark":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ThemeStyle\/dark","abstract":[],"navigatorTitle":[{"text":"ThemeStyleDark","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/shengwangchatuikit\/themestyle\/dark","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"dark"}],"title":"ThemeStyle.dark"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/Appearance":{"navigatorTitle":[{"kind":"identifier","text":"Appearance"}],"type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/Appearance","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Appearance","kind":"identifier"}],"title":"Appearance","abstract":[{"type":"text","text":"An object containing visual configurations for the whole application."}],"url":"\/documentation\/shengwangchatuikit\/appearance"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ThemeStyle":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"ThemeStyle"}],"title":"ThemeStyle","url":"\/documentation\/shengwangchatuikit\/themestyle","abstract":[{"type":"text","text":"Contain light and dark themes of the ease chat UIKit.If you want to switch custom theme,you’ll modify primary&secondary&error&neutral&neutralSpecial hues properties in "},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/Appearance"},{"type":"text","text":".Then call "},{"type":"codeVoice","code":"Theme.switchTheme(style: .custom)"},{"type":"text","text":" method"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ThemeStyle","kind":"symbol","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ThemeStyle"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"ThemeStyleDark"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"ThemeStyleDark","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"identifier","text":"ThemeStyleDark"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"value":"ThemeStyleDark","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ThemeStyle~1dark\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ThemeStyle~1dark\/fragments","value":[{"text":"ThemeStyleDark","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1Appearance\/title","op":"replace","value":"Appearance"},{"value":[{"kind":"identifier","text":"Appearance"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1Appearance\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1Appearance\/navigatorTitle","value":[{"kind":"identifier","text":"Appearance"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ThemeStyle\/title","value":"ThemeStyle"},{"op":"replace","value":[{"kind":"identifier","text":"ThemeStyle"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ThemeStyle\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ThemeStyle\/navigatorTitle","value":[{"kind":"identifier","text":"ThemeStyle"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}