{"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ThemeStyle"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/themestyle\/light"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/themestyle\/light"]}],"metadata":{"symbolKind":"case","title":"ThemeStyle.light","roleHeading":"Case","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"light","kind":"identifier"}],"modules":[{"name":"ShengwangChatUIKit"}],"externalID":"c:@M@ShengwangChatUIKit@E@ThemeStyle@ThemeStyleLight","navigatorTitle":[{"text":"ThemeStyleLight","kind":"identifier"}]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"light"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ThemeStyle\/light"},"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ThemeStyle/light":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ThemeStyle\/light","url":"\/documentation\/shengwangchatuikit\/themestyle\/light","kind":"symbol","navigatorTitle":[{"text":"ThemeStyleLight","kind":"identifier"}],"role":"symbol","abstract":[],"title":"ThemeStyle.light","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"light"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/Appearance":{"navigatorTitle":[{"kind":"identifier","text":"Appearance"}],"type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/Appearance","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Appearance","kind":"identifier"}],"title":"Appearance","abstract":[{"type":"text","text":"An object containing visual configurations for the whole application."}],"url":"\/documentation\/shengwangchatuikit\/appearance"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ThemeStyle":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"ThemeStyle"}],"title":"ThemeStyle","url":"\/documentation\/shengwangchatuikit\/themestyle","abstract":[{"type":"text","text":"Contain light and dark themes of the ease chat UIKit.If you want to switch custom theme,you’ll modify primary&secondary&error&neutral&neutralSpecial hues properties in "},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/Appearance"},{"type":"text","text":".Then call "},{"type":"codeVoice","code":"Theme.switchTheme(style: .custom)"},{"type":"text","text":" method"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ThemeStyle","kind":"symbol","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ThemeStyle"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"ThemeStyleLight","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"ThemeStyleLight","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"ThemeStyleLight"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"ThemeStyleLight","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ThemeStyle~1light\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ThemeStyle~1light\/fragments","value":[{"text":"ThemeStyleLight","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1Appearance\/title","value":"Appearance","op":"replace"},{"op":"replace","value":[{"text":"Appearance","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1Appearance\/fragments"},{"value":[{"text":"Appearance","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1Appearance\/navigatorTitle"},{"value":"ThemeStyle","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ThemeStyle\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ThemeStyle\/fragments","op":"replace","value":[{"kind":"identifier","text":"ThemeStyle"}]},{"value":[{"text":"ThemeStyle","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ThemeStyle\/navigatorTitle"}]}]}