{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"alreadyChat"},{"text":"()","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"content","content":[{"type":"heading","anchor":"discussion","text":"Discussion","level":2},{"inlineContent":[{"text":"This method is called when the user wants to open the chat conversation for the current group. It performs the following steps:","type":"text"}],"type":"paragraph"},{"type":"orderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"Acknowledges the conversation read by calling "},{"code":"ackConversationRead","type":"codeVoice"},{"type":"text","text":" method of the shared "},{"type":"codeVoice","code":"ChatClient"},{"type":"text","text":" instance."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Checks if the previous view controller in the navigation stack is "},{"type":"codeVoice","code":"MessageListController"},{"type":"text","text":"."}]},{"items":[{"content":[{"inlineContent":[{"text":"If it is, pops to the view controller before that and then pushes a new instance of ","type":"text"},{"code":"ComponentsRegister.shared.MessageViewController","type":"codeVoice"},{"type":"text","text":" with the conversation ID and chat type set to "},{"code":".group","type":"codeVoice"},{"text":".","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"If it is not, directly pushes a new instance of ","type":"text"},{"code":"ComponentsRegister.shared.MessageViewController","type":"codeVoice"},{"type":"text","text":" with the conversation ID and chat type set to "},{"code":".group","type":"codeVoice"},{"text":".","type":"text"}],"type":"paragraph"}]}],"type":"unorderedList"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"If the navigation stack is empty, checks if the presenting view controller is "},{"type":"codeVoice","code":"MessageListController"},{"type":"text","text":"."}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"If it is, dismisses the presenting view controller and then presents a new instance of ","type":"text"},{"type":"codeVoice","code":"ComponentsRegister.shared.MessageViewController"},{"type":"text","text":" with the conversation ID and chat type set to "},{"code":".group","type":"codeVoice"},{"text":".","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"If it is not, presents a new instance of "},{"type":"codeVoice","code":"ComponentsRegister.shared.MessageViewController"},{"type":"text","text":" with the conversation ID and chat type set to "},{"code":".group","type":"codeVoice"},{"text":" using the full screen modal presentation style.","type":"text"}],"type":"paragraph"}]}]}]},{"content":[{"inlineContent":[{"text":"If there is no presenting view controller, creates a new instance of ","type":"text"},{"code":"ComponentsRegister.shared.MessageViewController","type":"codeVoice"},{"type":"text","text":" with the conversation ID and chat type set to "},{"code":".group","type":"codeVoice"},{"type":"text","text":" and navigates to it using "},{"code":"ControllerStack.toDestination","type":"codeVoice"},{"text":" method.","type":"text"}],"type":"paragraph"}]}]}]}],"abstract":[{"type":"text","text":"Opens the chat conversation for the current group."}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/groupinfoviewcontroller\/alreadychat()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/groupinfoviewcontroller\/alreadychat()"]}],"metadata":{"navigatorTitle":[{"text":"alreadyChat","kind":"identifier"}],"externalID":"c:@M@ShengwangChatUIKit@objc(cs)GroupInfoViewController(im)alreadyChat","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"alreadyChat","kind":"identifier"},{"kind":"text","text":"()"}],"role":"symbol","title":"alreadyChat()","modules":[{"name":"ShengwangChatUIKit"}],"symbolKind":"method"},"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupInfoViewController\/alreadyChat()","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupInfoViewController"]]},"sections":[],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/GroupInfoViewController/alreadyChat()":{"kind":"symbol","navigatorTitle":[{"text":"alreadyChat","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/groupinfoviewcontroller\/alreadychat()","abstract":[{"text":"Opens the chat conversation for the current group.","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"alreadyChat","kind":"identifier"},{"kind":"text","text":"()"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupInfoViewController\/alreadyChat()","role":"symbol","title":"alreadyChat()"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/GroupInfoViewController":{"role":"symbol","url":"\/documentation\/shengwangchatuikit\/groupinfoviewcontroller","navigatorTitle":[{"text":"GroupInfoViewController","kind":"identifier"}],"title":"GroupInfoViewController","type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupInfoViewController","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"GroupInfoViewController","kind":"identifier"}],"abstract":[]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","value":"alreadyChat","path":"\/metadata\/title"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"alreadyChat"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"alreadyChat","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupInfoViewController~1alreadyChat()\/title","op":"replace","value":"alreadyChat"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"alreadyChat"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupInfoViewController~1alreadyChat()\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupInfoViewController\/title","value":"GroupInfoViewController","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupInfoViewController\/fragments","value":[{"text":"GroupInfoViewController","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupInfoViewController\/navigatorTitle","value":[{"text":"GroupInfoViewController","kind":"identifier"}],"op":"replace"}]}]}