{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupInfoViewController"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"chatGroup","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"ChatGroup","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatGroup","preciseIdentifier":"s:18ShengwangChatUIKit0B5Groupa"}],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"chatGroup","kind":"identifier"},{"kind":"text","text":": "},{"text":"ChatGroup","preciseIdentifier":"s:18ShengwangChatUIKit0B5Groupa","kind":"typeIdentifier"}],"externalID":"s:18ShengwangChatUIKit23GroupInfoViewControllerC04chatD0So05AgorabD0Cvp","roleHeading":"Instance Property","role":"symbol","modules":[{"name":"ShengwangChatUIKit"}],"title":"chatGroup","symbolKind":"property"},"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupInfoViewController\/chatGroup","interfaceLanguage":"swift"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/groupinfoviewcontroller\/chatgroup"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/GroupInfoViewController":{"role":"symbol","url":"\/documentation\/shengwangchatuikit\/groupinfoviewcontroller","navigatorTitle":[{"text":"GroupInfoViewController","kind":"identifier"}],"title":"GroupInfoViewController","type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupInfoViewController","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"GroupInfoViewController","kind":"identifier"}],"abstract":[]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/GroupInfoViewController/chatGroup":{"abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"chatGroup","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit0B5Groupa","text":"ChatGroup"}],"role":"symbol","kind":"symbol","type":"topic","url":"\/documentation\/shengwangchatuikit\/groupinfoviewcontroller\/chatgroup","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupInfoViewController\/chatGroup","title":"chatGroup"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatGroup":{"type":"topic","role":"symbol","title":"ChatGroup","kind":"symbol","abstract":[],"navigatorTitle":[{"text":"ChatGroup","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/chatgroup","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatGroup","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"text":"ChatGroup","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"GroupInfoViewController","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupInfoViewController\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupInfoViewController\/fragments","op":"replace","value":[{"text":"GroupInfoViewController","kind":"identifier"}]},{"value":[{"text":"GroupInfoViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupInfoViewController\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}