{"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupInfoViewController\/disband()"},"abstract":[{"type":"text","text":"Disbands the group."},{"text":" ","type":"text"},{"type":"text","text":"This method shows an alert to confirm the disbanding of the group. If the user confirms, it calls the "},{"code":"disband","type":"codeVoice"},{"type":"text","text":" method of the "},{"code":"service","type":"codeVoice"},{"text":" object to disband the group. After successful disbanding, it posts a notification with the group ID and pops the current view controller from the navigation stack. If there is an error during the disbanding process, it logs the error message.","type":"text"}],"metadata":{"symbolKind":"method","title":"disband()","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"disband","kind":"identifier"},{"kind":"text","text":"()"}],"externalID":"c:@M@ShengwangChatUIKit@objc(cs)GroupInfoViewController(im)disband","modules":[{"name":"ShengwangChatUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"disband"}],"roleHeading":"Instance Method"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/groupinfoviewcontroller\/disband()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/groupinfoviewcontroller\/disband()"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"attribute","text":"@"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"disband","kind":"identifier"},{"text":"()","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupInfoViewController"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/GroupInfoViewController":{"role":"symbol","url":"\/documentation\/shengwangchatuikit\/groupinfoviewcontroller","navigatorTitle":[{"text":"GroupInfoViewController","kind":"identifier"}],"title":"GroupInfoViewController","type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupInfoViewController","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"GroupInfoViewController","kind":"identifier"}],"abstract":[]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/GroupInfoViewController/disband()":{"kind":"symbol","navigatorTitle":[{"text":"disband","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/groupinfoviewcontroller\/disband()","abstract":[{"text":"Disbands the group.","type":"text"},{"text":" ","type":"text"},{"text":"This method shows an alert to confirm the disbanding of the group. If the user confirms, it calls the ","type":"text"},{"type":"codeVoice","code":"disband"},{"text":" method of the ","type":"text"},{"type":"codeVoice","code":"service"},{"text":" object to disband the group. After successful disbanding, it posts a notification with the group ID and pops the current view controller from the navigation stack. If there is an error during the disbanding process, it logs the error message.","type":"text"}],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"disband"},{"text":"()","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupInfoViewController\/disband()","role":"symbol","title":"disband()"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","value":"disband","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"disband","kind":"identifier"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"disband"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupInfoViewController\/title","value":"GroupInfoViewController"},{"value":[{"kind":"identifier","text":"GroupInfoViewController"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupInfoViewController\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupInfoViewController\/navigatorTitle","value":[{"kind":"identifier","text":"GroupInfoViewController"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupInfoViewController~1disband()\/title","value":"disband","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"disband"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupInfoViewController~1disband()\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}