{"sections":[],"abstract":[{"text":"Fills the alias (nickname) for the group details button.","type":"text"}],"metadata":{"modules":[{"name":"ShengwangChatUIKit"}],"roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"fillAliasWithNickname:"}],"externalID":"c:@M@ShengwangChatUIKit@objc(cs)GroupInfoViewController(im)fillAliasWithNickname:","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fillAlias"},{"kind":"text","text":"("},{"text":"nickname","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":")"}],"title":"fillAlias(nickname:)","role":"symbol"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/groupinfoviewcontroller\/fillalias(nickname:)"]},{"paths":["\/documentation\/shengwangchatuikit\/groupinfoviewcontroller\/fillalias(nickname:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupInfoViewController"]]},"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupInfoViewController\/fillAlias(nickname:)","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"fillAlias","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"nickname"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":")"}],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"name":"nickname","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The nickname to be filled as the alias."}]}]}],"kind":"parameters"}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/GroupInfoViewController/fillAlias(nickname:)":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"fillAliasWithNickname:"}],"url":"\/documentation\/shengwangchatuikit\/groupinfoviewcontroller\/fillalias(nickname:)","abstract":[{"type":"text","text":"Fills the alias (nickname) for the group details button."}],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fillAlias","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"nickname"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupInfoViewController\/fillAlias(nickname:)","role":"symbol","title":"fillAlias(nickname:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/GroupInfoViewController":{"role":"symbol","url":"\/documentation\/shengwangchatuikit\/groupinfoviewcontroller","navigatorTitle":[{"text":"GroupInfoViewController","kind":"identifier"}],"title":"GroupInfoViewController","type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupInfoViewController","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"GroupInfoViewController","kind":"identifier"}],"abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","value":"fillAliasWithNickname:","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"fillAliasWithNickname:","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"fillAliasWithNickname:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"nickname"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/primaryContentSections\/1","op":"replace","value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"The nickname to be filled as the alias.","type":"text"}],"type":"paragraph"}],"name":"nickname"}]}},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupInfoViewController~1fillAlias(nickname:)\/title","value":"fillAliasWithNickname:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupInfoViewController~1fillAlias(nickname:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"fillAliasWithNickname:"}],"op":"replace"},{"value":"GroupInfoViewController","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupInfoViewController\/title"},{"value":[{"text":"GroupInfoViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupInfoViewController\/fragments"},{"value":[{"text":"GroupInfoViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupInfoViewController\/navigatorTitle"}]}]}