{"abstract":[{"text":"Handles the callback for editing group information.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","kind":"attribute","text":"MainActor"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"handleEditCallback","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"text"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"type","kind":"externalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupInfoEditType","text":"GroupInfoEditType","kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@E@GroupInfoEditType"},{"text":")","kind":"text"}],"languages":["swift"]}]},{"parameters":[{"name":"text","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The edited text."}]}]},{"name":"type","content":[{"type":"paragraph","inlineContent":[{"text":"The type of information being edited.","type":"text"}]}]}],"kind":"parameters"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/groupinfoviewcontroller\/handleeditcallback(text:type:)"]},{"paths":["\/documentation\/shengwangchatuikit\/groupinfoviewcontroller\/handleeditcallback(text:type:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupInfoViewController\/handleEditCallback(text:type:)"},"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"handleEditCallback","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"text"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"type","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"GroupInfoEditType","kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@E@GroupInfoEditType"},{"text":")","kind":"text"}],"extendedModule":"ShengwangChatUIKit","externalID":"c:@CM@ShengwangChatUIKit@objc(cs)GroupInfoViewController(im)handleEditCallbackWithText:type:","role":"symbol","roleHeading":"Instance Method","navigatorTitle":[{"text":"handleEditCallbackWithText:type:","kind":"identifier"}],"symbolKind":"method","modules":[{"name":"ShengwangChatUIKit"}],"title":"handleEditCallback(text:type:)"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupInfoViewController"]]},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/GroupInfoViewController/handleEditCallback(text:type:)":{"type":"topic","url":"\/documentation\/shengwangchatuikit\/groupinfoviewcontroller\/handleeditcallback(text:type:)","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupInfoViewController\/handleEditCallback(text:type:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"handleEditCallback","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"text"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"type","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@E@GroupInfoEditType","text":"GroupInfoEditType","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"handleEditCallbackWithText:type:"}],"title":"handleEditCallback(text:type:)","kind":"symbol","role":"symbol","abstract":[{"text":"Handles the callback for editing group information.","type":"text"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/GroupInfoEditType":{"kind":"symbol","title":"GroupInfoEditType","abstract":[],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupInfoEditType"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"GroupInfoEditType"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupInfoEditType","url":"\/documentation\/shengwangchatuikit\/groupinfoedittype"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/GroupInfoViewController":{"role":"symbol","url":"\/documentation\/shengwangchatuikit\/groupinfoviewcontroller","navigatorTitle":[{"text":"GroupInfoViewController","kind":"identifier"}],"title":"GroupInfoViewController","type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupInfoViewController","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"GroupInfoViewController","kind":"identifier"}],"abstract":[]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"handleEditCallbackWithText:type:","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"handleEditCallbackWithText:type:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"handleEditCallbackWithText:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"text"},{"kind":"text","text":" "},{"kind":"identifier","text":"type:"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupInfoEditType","preciseIdentifier":"c:@M@ShengwangChatUIKit@E@GroupInfoEditType","text":"GroupInfoEditType"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"type"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/primaryContentSections\/1","value":{"parameters":[{"content":[{"inlineContent":[{"text":"The edited text.","type":"text"}],"type":"paragraph"}],"name":"text"},{"name":"type","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The type of information being edited."}]}]}],"kind":"parameters"}},{"value":"handleEditCallbackWithText:type:","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupInfoViewController~1handleEditCallback(text:type:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupInfoViewController~1handleEditCallback(text:type:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"handleEditCallbackWithText:type:"}],"op":"replace"},{"value":"GroupInfoEditType","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupInfoEditType\/title","op":"replace"},{"value":[{"text":"GroupInfoEditType","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupInfoEditType\/fragments","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"GroupInfoEditType"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupInfoEditType\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupInfoViewController\/title","op":"replace","value":"GroupInfoViewController"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupInfoViewController\/fragments","value":[{"text":"GroupInfoViewController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupInfoViewController\/navigatorTitle","op":"replace","value":[{"text":"GroupInfoViewController","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}