{"sections":[],"metadata":{"title":"memberOptions","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"memberOptions"},{"text":": [","kind":"text"},{"text":"ActionSheetItem","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)ActionSheetItem","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"externalID":"s:18ShengwangChatUIKit23GroupInfoViewControllerC13memberOptionsSayAA15ActionSheetItemCGvp","symbolKind":"property","roleHeading":"Instance Property","role":"symbol","modules":[{"name":"ShengwangChatUIKit"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupInfoViewController\/memberOptions"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupInfoViewController"]]},"abstract":[{"type":"text","text":"A private array that stores the member options for the group."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"memberOptions"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ActionSheetItem","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)ActionSheetItem","text":"ActionSheetItem"},{"kind":"text","text":"]"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"content","content":[{"text":"Discussion","anchor":"discussion","level":2,"type":"heading"},{"type":"paragraph","inlineContent":[{"text":"Each member option is represented by an ","type":"text"},{"code":"ActionSheetItem","type":"codeVoice"},{"type":"text","text":" object, which contains the title, type, and tag of the option."}]},{"inlineContent":[{"text":"Example usage:","type":"text"}],"type":"paragraph"},{"code":["private var memberOptions = [ActionSheetItem(title: \"group_details_extend_button_leave\".chat.localize, type: .destructive, tag: \"quit_group\")]"],"syntax":null,"type":"codeListing"}]}],"variants":[{"paths":["\/documentation\/shengwangchatuikit\/groupinfoviewcontroller\/memberoptions"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/GroupInfoViewController":{"role":"symbol","url":"\/documentation\/shengwangchatuikit\/groupinfoviewcontroller","navigatorTitle":[{"text":"GroupInfoViewController","kind":"identifier"}],"title":"GroupInfoViewController","type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupInfoViewController","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"GroupInfoViewController","kind":"identifier"}],"abstract":[]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ActionSheetItem":{"navigatorTitle":[{"kind":"identifier","text":"ActionSheetItem"}],"abstract":[],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ActionSheetItem"}],"url":"\/documentation\/shengwangchatuikit\/actionsheetitem","role":"symbol","title":"ActionSheetItem","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ActionSheetItem","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/GroupInfoViewController/memberOptions":{"type":"topic","url":"\/documentation\/shengwangchatuikit\/groupinfoviewcontroller\/memberoptions","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupInfoViewController\/memberOptions","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"memberOptions","kind":"identifier"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"ActionSheetItem","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)ActionSheetItem"},{"kind":"text","text":"]"}],"title":"memberOptions","kind":"symbol","role":"symbol","abstract":[{"text":"A private array that stores the member options for the group.","type":"text"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"GroupInfoViewController","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupInfoViewController\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupInfoViewController\/fragments","value":[{"text":"GroupInfoViewController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupInfoViewController\/navigatorTitle","value":[{"text":"GroupInfoViewController","kind":"identifier"}]},{"op":"replace","value":"ActionSheetItem","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ActionSheetItem\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ActionSheetItem\/fragments","value":[{"text":"ActionSheetItem","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ActionSheetItem\/navigatorTitle","value":[{"text":"ActionSheetItem","kind":"identifier"}]}]}]}