{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ForwardTargetCell\/actionClosure"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"actionClosure","kind":"identifier"},{"kind":"text","text":": (("},{"text":"ForwardTargetCell","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ForwardTargetCell","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)ForwardTargetCell"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"text":")?","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ForwardTargetCell"]]},"sections":[],"metadata":{"externalID":"c:@M@ShengwangChatUIKit@objc(cs)ForwardTargetCell(py)actionClosure","role":"symbol","roleHeading":"Instance Property","title":"actionClosure","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"actionClosure"},{"text":": ((","kind":"text"},{"text":"ForwardTargetCell","kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)ForwardTargetCell"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"text":")?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"actionClosure"}],"modules":[{"name":"ShengwangChatUIKit"}],"symbolKind":"property"},"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/forwardtargetcell\/actionclosure"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/forwardtargetcell\/actionclosure"]}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ForwardTargetCell/actionClosure":{"url":"\/documentation\/shengwangchatuikit\/forwardtargetcell\/actionclosure","navigatorTitle":[{"text":"actionClosure","kind":"identifier"}],"kind":"symbol","title":"actionClosure","type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"actionClosure"},{"text":": ((","kind":"text"},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)ForwardTargetCell","text":"ForwardTargetCell","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"text":")?","kind":"text"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ForwardTargetCell\/actionClosure"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ForwardTargetCell":{"url":"\/documentation\/shengwangchatuikit\/forwardtargetcell","title":"ForwardTargetCell","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ForwardTargetCell"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ForwardTargetCell","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ForwardTargetCell","kind":"identifier"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","value":"actionClosure","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"actionClosure"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"kind":"text","text":") "},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":" (^"},{"text":"actionClosure","kind":"identifier"},{"text":")(","kind":"text"},{"text":"ForwardTargetCell","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ForwardTargetCell","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)ForwardTargetCell","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"text":"","kind":"internalParam"},{"text":");","kind":"text"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ForwardTargetCell~1actionClosure\/title","op":"replace","value":"actionClosure"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ForwardTargetCell~1actionClosure\/fragments","value":[{"text":"actionClosure","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ForwardTargetCell\/title","op":"replace","value":"ForwardTargetCell"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ForwardTargetCell\/fragments","value":[{"text":"ForwardTargetCell","kind":"identifier"}]},{"value":[{"text":"ForwardTargetCell","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ForwardTargetCell\/navigatorTitle"}]}]}