{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactListHeaderItemProtocol"]]},"abstract":[{"type":"text","text":"When the cell clicked,callback."}],"kind":"symbol","sections":[],"variants":[{"paths":["\/documentation\/shengwangchatuikit\/contactlistheaderitemprotocol\/actionclosure"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/contactlistheaderitemprotocol\/actionclosure"]}],"metadata":{"symbolKind":"property","roleHeading":"Instance Property","title":"actionClosure","navigatorTitle":[{"text":"actionClosure","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"actionClosure"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit28ContactListItemActionClosurea","text":"ContactListItemActionClosure"},{"kind":"text","text":"?"}],"externalID":"c:@M@ShengwangChatUIKit@objc(pl)ContactListHeaderItemProtocol(py)actionClosure","modules":[{"name":"ShengwangChatUIKit"}],"required":true},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactListHeaderItemProtocol\/actionClosure","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"actionClosure","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactListItemActionClosure","text":"ContactListItemActionClosure","preciseIdentifier":"s:18ShengwangChatUIKit28ContactListItemActionClosurea"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}]}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ContactListHeaderItemProtocol/actionClosure":{"required":true,"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actionClosure","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:18ShengwangChatUIKit28ContactListItemActionClosurea","text":"ContactListItemActionClosure","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"actionClosure","abstract":[{"type":"text","text":"When the cell clicked,callback."}],"type":"topic","kind":"symbol","url":"\/documentation\/shengwangchatuikit\/contactlistheaderitemprotocol\/actionclosure","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactListHeaderItemProtocol\/actionClosure","navigatorTitle":[{"text":"actionClosure","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ContactListHeaderItemProtocol":{"navigatorTitle":[{"kind":"identifier","text":"ContactListHeaderItemProtocol"}],"title":"ContactListHeaderItemProtocol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactListHeaderItemProtocol","role":"symbol","abstract":[{"type":"text","text":"A protocol of the contact list item."}],"kind":"symbol","url":"\/documentation\/shengwangchatuikit\/contactlistheaderitemprotocol","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ContactListHeaderItemProtocol","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ContactListItemActionClosure":{"title":"ContactListItemActionClosure","navigatorTitle":[{"text":"ContactListItemActionClosure","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/contactlistitemactionclosure","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactListItemActionClosure","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"ContactListItemActionClosure","kind":"identifier"}],"abstract":[],"role":"symbol","kind":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"op":"replace","value":"actionClosure","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"actionClosure"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":" (^","kind":"text"},{"kind":"identifier","text":"actionClosure"},{"text":")(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@ShengwangChatUIKit@objc(pl)ContactListHeaderItemProtocol","text":"id<ContactListHeaderItemProtocol>"},{"text":" ","kind":"text"},{"text":"","kind":"internalParam"},{"kind":"text","text":");"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactListHeaderItemProtocol~1actionClosure\/title","value":"actionClosure","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"actionClosure"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactListHeaderItemProtocol~1actionClosure\/fragments"},{"value":"ContactListHeaderItemProtocol","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactListHeaderItemProtocol\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactListHeaderItemProtocol\/fragments","value":[{"text":"ContactListHeaderItemProtocol","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"ContactListHeaderItemProtocol"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactListHeaderItemProtocol\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}