{"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ActionSheetItemType\/destructive","interfaceLanguage":"swift"},"sections":[],"metadata":{"roleHeading":"Case","title":"ActionSheetItemType.destructive","externalID":"c:@M@ShengwangChatUIKit@E@ActionSheetItemType@ActionSheetItemTypeDestructive","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"destructive","kind":"identifier"}],"symbolKind":"case","modules":[{"name":"ShengwangChatUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"ActionSheetItemTypeDestructive"}],"role":"symbol"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ActionSheetItemType"]]},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"destructive","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/actionsheetitemtype\/destructive"]},{"paths":["\/documentation\/shengwangchatuikit\/actionsheetitemtype\/destructive"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ActionSheetItemType/destructive":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ActionSheetItemType\/destructive","type":"topic","abstract":[],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"destructive"}],"url":"\/documentation\/shengwangchatuikit\/actionsheetitemtype\/destructive","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ActionSheetItemTypeDestructive"}],"kind":"symbol","title":"ActionSheetItemType.destructive"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ActionSheetItemType":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ActionSheetItemType","abstract":[{"type":"text","text":"An enumeration representing the type of an action sheet item."}],"title":"ActionSheetItemType","url":"\/documentation\/shengwangchatuikit\/actionsheetitemtype","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ActionSheetItemType"}],"navigatorTitle":[{"kind":"identifier","text":"ActionSheetItemType"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"ActionSheetItemTypeDestructive"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ActionSheetItemTypeDestructive"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"ActionSheetItemTypeDestructive"}],"platforms":["iOS"]}]}},{"value":"ActionSheetItemTypeDestructive","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ActionSheetItemType~1destructive\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ActionSheetItemType~1destructive\/fragments","value":[{"kind":"identifier","text":"ActionSheetItemTypeDestructive"}]},{"value":"ActionSheetItemType","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ActionSheetItemType\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ActionSheetItemType\/fragments","value":[{"kind":"identifier","text":"ActionSheetItemType"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ActionSheetItemType\/navigatorTitle","value":[{"kind":"identifier","text":"ActionSheetItemType"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}