{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactInfoViewController\/addAction()"},"abstract":[{"text":"Adds a contact to the user’s contact list.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","kind":"attribute","text":"MainActor"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"addAction","kind":"identifier"},{"text":"()","kind":"text"}]}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactInfoViewController"]]},"sections":[],"metadata":{"externalID":"c:@M@ShengwangChatUIKit@objc(cs)ContactInfoViewController(im)addAction","role":"symbol","roleHeading":"Instance Method","title":"addAction()","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"addAction","kind":"identifier"},{"kind":"text","text":"()"}],"navigatorTitle":[{"kind":"identifier","text":"addAction"}],"modules":[{"name":"ShengwangChatUIKit"}],"symbolKind":"method"},"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/contactinfoviewcontroller\/addaction()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/contactinfoviewcontroller\/addaction()"]}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ContactInfoViewController/addAction()":{"role":"symbol","abstract":[{"type":"text","text":"Adds a contact to the user’s contact list."}],"kind":"symbol","title":"addAction()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"addAction"},{"kind":"text","text":"()"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactInfoViewController\/addAction()","navigatorTitle":[{"text":"addAction","kind":"identifier"}],"type":"topic","url":"\/documentation\/shengwangchatuikit\/contactinfoviewcontroller\/addaction()"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ContactInfoViewController":{"role":"symbol","url":"\/documentation\/shengwangchatuikit\/contactinfoviewcontroller","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ContactInfoViewController"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactInfoViewController","type":"topic","abstract":[{"type":"text","text":"This is the documentation comment for the "},{"code":"ContactInfoViewController","type":"codeVoice"},{"type":"text","text":" class."}],"navigatorTitle":[{"kind":"identifier","text":"ContactInfoViewController"}],"kind":"symbol","title":"ContactInfoViewController"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"addAction"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"addAction"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"addAction","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactInfoViewController~1addAction()\/title","value":"addAction"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"addAction","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactInfoViewController~1addAction()\/fragments"},{"value":"ContactInfoViewController","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactInfoViewController\/title"},{"value":[{"text":"ContactInfoViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactInfoViewController\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactInfoViewController\/navigatorTitle","value":[{"kind":"identifier","text":"ContactInfoViewController"}]}]}]}