{"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"roleHeading":"Instance Property","title":"blockListExist","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"blockListExist"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":" : "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":"]"}],"externalID":"s:18ShengwangChatUIKit25ContactInfoViewControllerC14blockListExistSDySSSbGvp","modules":[{"name":"ShengwangChatUIKit"}],"symbolKind":"property"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactInfoViewController"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactInfoViewController\/blockListExist"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:18ShengwangChatUIKit11UserDefaultV","kind":"attribute","text":"UserDefault","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UserDefault"},{"text":" ","kind":"text"},{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"blockListExist"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":"] { "},{"text":"get","kind":"keyword"},{"kind":"text","text":" "},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/shengwangchatuikit\/contactinfoviewcontroller\/blocklistexist"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ContactInfoViewController":{"role":"symbol","url":"\/documentation\/shengwangchatuikit\/contactinfoviewcontroller","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ContactInfoViewController"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactInfoViewController","type":"topic","abstract":[{"type":"text","text":"This is the documentation comment for the "},{"code":"ContactInfoViewController","type":"codeVoice"},{"type":"text","text":" class."}],"navigatorTitle":[{"kind":"identifier","text":"ContactInfoViewController"}],"kind":"symbol","title":"ContactInfoViewController"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ContactInfoViewController/blockListExist":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactInfoViewController\/blockListExist","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"blockListExist","kind":"identifier"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":" : ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":"]"}],"url":"\/documentation\/shengwangchatuikit\/contactinfoviewcontroller\/blocklistexist","title":"blockListExist","abstract":[],"role":"symbol","type":"topic"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/UserDefault":{"kind":"symbol","navigatorTitle":[{"text":"UserDefault","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/userdefault","title":"UserDefault","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UserDefault","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"UserDefault"}],"type":"topic","role":"symbol","abstract":[]}},"variantOverrides":[{"patch":[{"value":"ContactInfoViewController","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactInfoViewController\/title"},{"op":"replace","value":[{"kind":"identifier","text":"ContactInfoViewController"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactInfoViewController\/fragments"},{"value":[{"kind":"identifier","text":"ContactInfoViewController"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactInfoViewController\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}