{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"fetchAllContactIds","kind":"identifier"},{"text":"()","kind":"text"}]}]},{"content":[{"level":2,"type":"heading","text":"Discussion","anchor":"discussion"},{"type":"paragraph","inlineContent":[{"text":"This method first checks if there are any locally stored contacts. If there are, it updates the ","type":"text"},{"type":"codeVoice","code":"contacts"},{"text":" array with the locally stored contacts and calls the ","type":"text"},{"code":"setup()","type":"codeVoice"},{"type":"text","text":" method. If there are no locally stored contacts, it fetches the contacts from the server using the "},{"type":"codeVoice","code":"getContactsFromServer(completion:)"},{"type":"text","text":" method of the "},{"type":"codeVoice","code":"ChatClient"},{"text":"’s ","type":"text"},{"type":"codeVoice","code":"contactManager"},{"text":". Once the contacts are fetched, it updates the ","type":"text"},{"code":"contacts","type":"codeVoice"},{"type":"text","text":" array and calls the "},{"code":"setup()","type":"codeVoice"},{"type":"text","text":" method."}]}],"kind":"content"}],"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fetchAllContactIds"},{"kind":"text","text":"()"}],"externalID":"c:@M@ShengwangChatUIKit@objc(cs)ContactInfoViewController(im)fetchAllContactIds","role":"symbol","roleHeading":"Instance Method","title":"fetchAllContactIds()","modules":[{"name":"ShengwangChatUIKit"}],"symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"fetchAllContactIds"}]},"abstract":[{"text":"Fetches all contact IDs and updates the contacts array.","type":"text"}],"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactInfoViewController\/fetchAllContactIds()","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactInfoViewController"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/contactinfoviewcontroller\/fetchallcontactids()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/contactinfoviewcontroller\/fetchallcontactids()"]}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ContactInfoViewController/fetchAllContactIds()":{"navigatorTitle":[{"kind":"identifier","text":"fetchAllContactIds"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fetchAllContactIds"},{"text":"()","kind":"text"}],"url":"\/documentation\/shengwangchatuikit\/contactinfoviewcontroller\/fetchallcontactids()","abstract":[{"text":"Fetches all contact IDs and updates the contacts array.","type":"text"}],"role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactInfoViewController\/fetchAllContactIds()","title":"fetchAllContactIds()","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ContactInfoViewController":{"role":"symbol","url":"\/documentation\/shengwangchatuikit\/contactinfoviewcontroller","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ContactInfoViewController"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactInfoViewController","type":"topic","abstract":[{"type":"text","text":"This is the documentation comment for the "},{"code":"ContactInfoViewController","type":"codeVoice"},{"type":"text","text":" class."}],"navigatorTitle":[{"kind":"identifier","text":"ContactInfoViewController"}],"kind":"symbol","title":"ContactInfoViewController"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"fetchAllContactIds"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"fetchAllContactIds"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"fetchAllContactIds","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactInfoViewController~1fetchAllContactIds()\/title","op":"replace","value":"fetchAllContactIds"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactInfoViewController~1fetchAllContactIds()\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"fetchAllContactIds"}]},{"value":"ContactInfoViewController","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactInfoViewController\/title","op":"replace"},{"value":[{"kind":"identifier","text":"ContactInfoViewController"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactInfoViewController\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactInfoViewController\/navigatorTitle","value":[{"text":"ContactInfoViewController","kind":"identifier"}],"op":"replace"}]}]}