{"abstract":[{"type":"text","text":"This method is responsible for handling the header actions in the ContactInfoViewController."},{"text":" ","type":"text"},{"type":"text","text":"It checks if there is a chat action item available in the contact’s detail extension action items."},{"text":" ","type":"text"},{"text":"If found, it sets the action closure to invoke the ","type":"text"},{"code":"alreadyChat()","type":"codeVoice"},{"type":"text","text":" method when the action is triggered."}],"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactInfoViewController\/headerActions()","interfaceLanguage":"swift"},"metadata":{"symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"headerActions","kind":"identifier"},{"text":"()","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"headerActions"}],"role":"symbol","externalID":"c:@M@ShengwangChatUIKit@objc(cs)ContactInfoViewController(im)headerActions","title":"headerActions()","roleHeading":"Instance Method","modules":[{"name":"ShengwangChatUIKit"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactInfoViewController"]]},"variants":[{"paths":["\/documentation\/shengwangchatuikit\/contactinfoviewcontroller\/headeractions()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/contactinfoviewcontroller\/headeractions()"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"headerActions","kind":"identifier"},{"text":"()","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ContactInfoViewController/headerActions()":{"title":"headerActions()","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactInfoViewController\/headerActions()","url":"\/documentation\/shengwangchatuikit\/contactinfoviewcontroller\/headeractions()","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"headerActions"},{"text":"()","kind":"text"}],"role":"symbol","abstract":[{"text":"This method is responsible for handling the header actions in the ContactInfoViewController.","type":"text"},{"text":" ","type":"text"},{"text":"It checks if there is a chat action item available in the contact’s detail extension action items.","type":"text"},{"type":"text","text":" "},{"text":"If found, it sets the action closure to invoke the ","type":"text"},{"type":"codeVoice","code":"alreadyChat()"},{"text":" method when the action is triggered.","type":"text"}],"navigatorTitle":[{"text":"headerActions","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ContactInfoViewController":{"role":"symbol","url":"\/documentation\/shengwangchatuikit\/contactinfoviewcontroller","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ContactInfoViewController"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactInfoViewController","type":"topic","abstract":[{"type":"text","text":"This is the documentation comment for the "},{"code":"ContactInfoViewController","type":"codeVoice"},{"type":"text","text":" class."}],"navigatorTitle":[{"kind":"identifier","text":"ContactInfoViewController"}],"kind":"symbol","title":"ContactInfoViewController"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"headerActions"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"headerActions","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"headerActions","kind":"identifier"},{"text":";","kind":"text"}]}]}},{"value":"headerActions","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactInfoViewController~1headerActions()\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactInfoViewController~1headerActions()\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"headerActions"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactInfoViewController\/title","op":"replace","value":"ContactInfoViewController"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactInfoViewController\/fragments","op":"replace","value":[{"kind":"identifier","text":"ContactInfoViewController"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactInfoViewController\/navigatorTitle","value":[{"kind":"identifier","text":"ContactInfoViewController"}],"op":"replace"}]}]}