{"abstract":[{"type":"text","text":"Handles the navigation click events in the ContactInfoViewController."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"@","kind":"attribute"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"navigationClick","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"type"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatNavigationBarClickEvent","text":"ChatNavigationBarClickEvent","preciseIdentifier":"c:@M@ShengwangChatUIKit@E@ChatNavigationBarClickEvent"},{"kind":"text","text":", "},{"text":"indexPath","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"text":"?)","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]},{"parameters":[{"content":[{"inlineContent":[{"text":"The type of navigation click event.","type":"text"}],"type":"paragraph"}],"name":"type"},{"content":[{"inlineContent":[{"text":"The optional index path associated with the event.","type":"text"}],"type":"paragraph"}],"name":"indexPath"}],"kind":"parameters"}],"variants":[{"paths":["\/documentation\/shengwangchatuikit\/contactinfoviewcontroller\/navigationclick(type:indexpath:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/contactinfoviewcontroller\/navigationclick(type:indexpath:)"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactInfoViewController"]]},"kind":"symbol","metadata":{"modules":[{"name":"ShengwangChatUIKit"}],"roleHeading":"Instance Method","navigatorTitle":[{"text":"navigationClickWithType:indexPath:","kind":"identifier"}],"externalID":"c:@M@ShengwangChatUIKit@objc(cs)ContactInfoViewController(im)navigationClickWithType:indexPath:","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"navigationClick","kind":"identifier"},{"text":"(","kind":"text"},{"text":"type","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@E@ChatNavigationBarClickEvent","text":"ChatNavigationBarClickEvent","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"indexPath"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation9IndexPathV","text":"IndexPath","kind":"typeIdentifier"},{"kind":"text","text":"?)"}],"title":"navigationClick(type:indexPath:)","role":"symbol"},"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactInfoViewController\/navigationClick(type:indexPath:)","interfaceLanguage":"swift"},"sections":[],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ContactInfoViewController/navigationClick(type:indexPath:)":{"navigatorTitle":[{"kind":"identifier","text":"navigationClickWithType:indexPath:"}],"title":"navigationClick(type:indexPath:)","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactInfoViewController\/navigationClick(type:indexPath:)","role":"symbol","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"navigationClick"},{"kind":"text","text":"("},{"kind":"externalParam","text":"type"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@E@ChatNavigationBarClickEvent","text":"ChatNavigationBarClickEvent","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"indexPath","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":"?)"}],"type":"topic","abstract":[{"type":"text","text":"Handles the navigation click events in the ContactInfoViewController."}],"url":"\/documentation\/shengwangchatuikit\/contactinfoviewcontroller\/navigationclick(type:indexpath:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatNavigationBarClickEvent":{"abstract":[],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatNavigationBarClickEvent","navigatorTitle":[{"kind":"identifier","text":"ChatNavigationBarClickEvent"}],"kind":"symbol","url":"\/documentation\/shengwangchatuikit\/chatnavigationbarclickevent","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatNavigationBarClickEvent"}],"title":"ChatNavigationBarClickEvent","type":"topic"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ContactInfoViewController":{"role":"symbol","url":"\/documentation\/shengwangchatuikit\/contactinfoviewcontroller","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ContactInfoViewController"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactInfoViewController","type":"topic","abstract":[{"type":"text","text":"This is the documentation comment for the "},{"code":"ContactInfoViewController","type":"codeVoice"},{"type":"text","text":" class."}],"navigatorTitle":[{"kind":"identifier","text":"ContactInfoViewController"}],"kind":"symbol","title":"ContactInfoViewController"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"navigationClickWithType:indexPath:","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"navigationClickWithType:indexPath:"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"text":"navigationClickWithType:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatNavigationBarClickEvent","text":"ChatNavigationBarClickEvent","preciseIdentifier":"c:@M@ShengwangChatUIKit@E@ChatNavigationBarClickEvent"},{"kind":"text","text":") "},{"text":"type","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"indexPath:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSIndexPath","text":"NSIndexPath"},{"kind":"text","text":" *) "},{"text":"indexPath","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"value":{"kind":"parameters","parameters":[{"name":"type","content":[{"inlineContent":[{"type":"text","text":"The type of navigation click event."}],"type":"paragraph"}]},{"name":"indexPath","content":[{"type":"paragraph","inlineContent":[{"text":"The optional index path associated with the event.","type":"text"}]}]}]},"op":"replace","path":"\/primaryContentSections\/1"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactInfoViewController~1navigationClick(type:indexPath:)\/title","value":"navigationClickWithType:indexPath:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactInfoViewController~1navigationClick(type:indexPath:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"navigationClickWithType:indexPath:"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatNavigationBarClickEvent\/title","op":"replace","value":"ChatNavigationBarClickEvent"},{"op":"replace","value":[{"text":"ChatNavigationBarClickEvent","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatNavigationBarClickEvent\/fragments"},{"value":[{"text":"ChatNavigationBarClickEvent","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatNavigationBarClickEvent\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactInfoViewController\/title","value":"ContactInfoViewController","op":"replace"},{"value":[{"text":"ContactInfoViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactInfoViewController\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactInfoViewController\/navigatorTitle","value":[{"kind":"identifier","text":"ContactInfoViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}