{"metadata":{"roleHeading":"Instance Method","navigatorTitle":[{"text":"tableView:numberOfRowsInSection:","kind":"identifier"}],"role":"symbol","title":"tableView(_:numberOfRowsInSection:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"tableView"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UITableView","text":"UITableView","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"numberOfRowsInSection","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"modules":[{"name":"ShengwangChatUIKit"}],"externalID":"c:@CM@ShengwangChatUIKit@objc(cs)ContactInfoViewController(im)tableView:numberOfRowsInSection:","symbolKind":"method","extendedModule":"ShengwangChatUIKit"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"tableView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"tableView","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"UITableView","preciseIdentifier":"c:objc(cs)UITableView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"numberOfRowsInSection"},{"kind":"text","text":" "},{"text":"section","kind":"internalParam"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"languages":["swift"]}]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactInfoViewController\/tableView(_:numberOfRowsInSection:)"},"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactInfoViewController","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactInfoViewController\/UITableViewDataSource-Implementations"]]},"kind":"symbol","variants":[{"paths":["\/documentation\/shengwangchatuikit\/contactinfoviewcontroller\/tableview(_:numberofrowsinsection:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/contactinfoviewcontroller\/tableview(_:numberofrowsinsection:)"]}],"abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"UITableViewDataSource.tableView(_:numberOfRowsInSection:)"},{"type":"text","text":"."}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ContactInfoViewController/UITableViewDataSource-Implementations":{"title":"UITableViewDataSource Implementations","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactInfoViewController\/UITableViewDataSource-Implementations","role":"collectionGroup","kind":"article","type":"topic","abstract":[],"url":"\/documentation\/shengwangchatuikit\/contactinfoviewcontroller\/uitableviewdatasource-implementations"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ContactInfoViewController":{"role":"symbol","url":"\/documentation\/shengwangchatuikit\/contactinfoviewcontroller","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ContactInfoViewController"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactInfoViewController","type":"topic","abstract":[{"type":"text","text":"This is the documentation comment for the "},{"code":"ContactInfoViewController","type":"codeVoice"},{"type":"text","text":" class."}],"navigatorTitle":[{"kind":"identifier","text":"ContactInfoViewController"}],"kind":"symbol","title":"ContactInfoViewController"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ContactInfoViewController/tableView(_:numberOfRowsInSection:)":{"navigatorTitle":[{"kind":"identifier","text":"tableView:numberOfRowsInSection:"}],"url":"\/documentation\/shengwangchatuikit\/contactinfoviewcontroller\/tableview(_:numberofrowsinsection:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"tableView","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITableView","text":"UITableView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"numberOfRowsInSection"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"role":"symbol","title":"tableView(_:numberOfRowsInSection:)","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactInfoViewController\/tableView(_:numberOfRowsInSection:)","kind":"symbol","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"tableView:numberOfRowsInSection:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"tableView:numberOfRowsInSection:"}]},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"NSInteger","preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"tableView:"},{"kind":"text","text":"("},{"text":"UITableView","preciseIdentifier":"c:objc(cs)UITableView","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"tableView","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"numberOfRowsInSection:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSInteger","preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"section","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"value":"ContactInfoViewController","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactInfoViewController\/title","op":"replace"},{"value":[{"kind":"identifier","text":"ContactInfoViewController"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactInfoViewController\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactInfoViewController\/navigatorTitle","op":"replace","value":[{"text":"ContactInfoViewController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactInfoViewController~1tableView(_:numberOfRowsInSection:)\/title","value":"tableView:numberOfRowsInSection:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactInfoViewController~1tableView(_:numberOfRowsInSection:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"tableView:numberOfRowsInSection:","kind":"identifier"}]}]}]}