{"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationAppearance\/init"},"metadata":{"modules":[{"name":"ShengwangChatUIKit"}],"roleHeading":"Instance Method","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"title":"init","role":"symbol","navigatorTitle":[{"text":"init","kind":"identifier"}],"externalID":"c:@M@ShengwangChatUIKit@objc(cs)ConversationAppearance(im)init","symbolKind":"method"},"variants":[{"paths":["\/documentation\/shengwangchatuikit\/conversationappearance\/init"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"text":"init","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationAppearance"]]},"sections":[],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ConversationAppearance/init":{"abstract":[],"fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationAppearance\/init","url":"\/documentation\/shengwangchatuikit\/conversationappearance\/init","title":"init","role":"symbol","navigatorTitle":[{"text":"init","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ConversationAppearance":{"navigatorTitle":[{"kind":"identifier","text":"ConversationAppearance"}],"abstract":[],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ConversationAppearance","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/conversationappearance","role":"symbol","title":"ConversationAppearance","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationAppearance"}},"variantOverrides":[{"patch":[{"value":"ConversationAppearance","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationAppearance\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationAppearance\/fragments","value":[{"text":"ConversationAppearance","kind":"identifier"}]},{"value":[{"text":"ConversationAppearance","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationAppearance\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}