{"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/conversationappearance\/swiperightactions"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationAppearance\/swipeRightActions"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationAppearance"]]},"kind":"symbol","metadata":{"externalID":"s:18ShengwangChatUIKit22ConversationAppearanceC17swipeRightActionsSayAA22UIContextualActionTypeOGvp","roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"swipeRightActions"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"UIContextualActionType","preciseIdentifier":"c:@M@ShengwangChatUIKit@E@UIContextualActionType"},{"kind":"text","text":"]"}],"role":"symbol","title":"swipeRightActions","modules":[{"name":"ShengwangChatUIKit"}],"symbolKind":"property"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"swipeRightActions"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UIContextualActionType","text":"UIContextualActionType","preciseIdentifier":"c:@M@ShengwangChatUIKit@E@UIContextualActionType"},{"text":"]","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"abstract":[{"text":"Menu items that appear after swiping right in a conversation.You can choose to have just some of the features or all of them.","type":"text"},{"isActive":true,"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UIContextualActionType","type":"reference"}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ConversationAppearance":{"navigatorTitle":[{"kind":"identifier","text":"ConversationAppearance"}],"abstract":[],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ConversationAppearance","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/conversationappearance","role":"symbol","title":"ConversationAppearance","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationAppearance"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/UIContextualActionType":{"navigatorTitle":[{"kind":"identifier","text":"UIContextualActionType"}],"abstract":[],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"UIContextualActionType","kind":"identifier"}],"type":"topic","url":"\/documentation\/shengwangchatuikit\/uicontextualactiontype","kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UIContextualActionType","title":"UIContextualActionType"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ConversationAppearance/swipeRightActions":{"url":"\/documentation\/shengwangchatuikit\/conversationappearance\/swiperightactions","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"swipeRightActions","kind":"identifier"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@E@UIContextualActionType","text":"UIContextualActionType"},{"text":"]","kind":"text"}],"role":"symbol","title":"swipeRightActions","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ConversationAppearance\/swipeRightActions","kind":"symbol","abstract":[{"text":"Menu items that appear after swiping right in a conversation.You can choose to have just some of the features or all of them.","type":"text"},{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UIContextualActionType","isActive":true,"type":"reference"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationAppearance\/title","value":"ConversationAppearance","op":"replace"},{"value":[{"kind":"identifier","text":"ConversationAppearance"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationAppearance\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ConversationAppearance\/navigatorTitle","value":[{"kind":"identifier","text":"ConversationAppearance"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1UIContextualActionType\/title","op":"replace","value":"UIContextualActionType"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1UIContextualActionType\/fragments","value":[{"kind":"identifier","text":"UIContextualActionType"}]},{"op":"replace","value":[{"text":"UIContextualActionType","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1UIContextualActionType\/navigatorTitle"}]}]}