{"kind":"symbol","metadata":{"externalID":"c:@M@ShengwangChatUIKit@E@ChatTopicOptions@ChatTopicOptionsLeave","navigatorTitle":[{"text":"ChatTopicOptionsLeave","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"leave","kind":"identifier"}],"role":"symbol","modules":[{"name":"ShengwangChatUIKit"}],"symbolKind":"case","roleHeading":"Case","title":"ChatTopicOptions.leave"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatTopicOptions"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"leave"}],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatTopicOptions\/leave"},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/chattopicoptions\/leave"]},{"paths":["\/documentation\/shengwangchatuikit\/chattopicoptions\/leave"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatTopicOptions":{"role":"symbol","kind":"symbol","abstract":[],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"ChatTopicOptions","kind":"identifier"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatTopicOptions"}],"url":"\/documentation\/shengwangchatuikit\/chattopicoptions","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatTopicOptions","title":"ChatTopicOptions"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatTopicOptions/leave":{"navigatorTitle":[{"text":"ChatTopicOptionsLeave","kind":"identifier"}],"abstract":[],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"leave","kind":"identifier"}],"type":"topic","url":"\/documentation\/shengwangchatuikit\/chattopicoptions\/leave","kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatTopicOptions\/leave","title":"ChatTopicOptions.leave"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"ChatTopicOptionsLeave","op":"replace"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"value":[{"text":"ChatTopicOptionsLeave","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"ChatTopicOptionsLeave"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatTopicOptions\/title","value":"ChatTopicOptions"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatTopicOptions\/fragments","value":[{"text":"ChatTopicOptions","kind":"identifier"}],"op":"replace"},{"value":[{"text":"ChatTopicOptions","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatTopicOptions\/navigatorTitle","op":"replace"},{"value":"ChatTopicOptionsLeave","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatTopicOptions~1leave\/title","op":"replace"},{"value":[{"text":"ChatTopicOptionsLeave","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatTopicOptions~1leave\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}