{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/chatuserprofileprovidertype\/group"]},{"paths":["\/documentation\/shengwangchatuikit\/chatuserprofileprovidertype\/group"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"symbolKind":"case","title":"ChatUserProfileProviderType.group","roleHeading":"Case","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"group","kind":"identifier"}],"externalID":"c:@M@ShengwangChatUIKit@E@ChatUserProfileProviderType@ChatUserProfileProviderTypeGroup","modules":[{"name":"ShengwangChatUIKit"}],"navigatorTitle":[{"text":"ChatUserProfileProviderTypeGroup","kind":"identifier"}]},"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatUserProfileProviderType"]]},"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatUserProfileProviderType\/group","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"group","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatUserProfileProviderType":{"type":"topic","kind":"symbol","abstract":[],"role":"symbol","url":"\/documentation\/shengwangchatuikit\/chatuserprofileprovidertype","title":"ChatUserProfileProviderType","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatUserProfileProviderType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"ChatUserProfileProviderType","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ChatUserProfileProviderType"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatUserProfileProviderType/group":{"navigatorTitle":[{"kind":"identifier","text":"ChatUserProfileProviderTypeGroup"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"group"}],"title":"ChatUserProfileProviderType.group","url":"\/documentation\/shengwangchatuikit\/chatuserprofileprovidertype\/group","abstract":[],"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatUserProfileProviderType\/group","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"value":"ChatUserProfileProviderTypeGroup","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"ChatUserProfileProviderTypeGroup"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"ChatUserProfileProviderTypeGroup","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatUserProfileProviderType\/title","value":"ChatUserProfileProviderType","op":"replace"},{"value":[{"kind":"identifier","text":"ChatUserProfileProviderType"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatUserProfileProviderType\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatUserProfileProviderType\/navigatorTitle","value":[{"kind":"identifier","text":"ChatUserProfileProviderType"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatUserProfileProviderType~1group\/title","op":"replace","value":"ChatUserProfileProviderTypeGroup"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatUserProfileProviderType~1group\/fragments","value":[{"text":"ChatUserProfileProviderTypeGroup","kind":"identifier"}]}]}]}