{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupParticipantCell\/init(displayStyle:identifier:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"@","kind":"attribute"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"text":" ","kind":"text"},{"kind":"keyword","text":"required"},{"kind":"text","text":" "},{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"kind":"externalParam","text":"displayStyle"},{"text":": ","kind":"text"},{"text":"ContactDisplayStyle","preciseIdentifier":"c:@M@ShengwangChatUIKit@E@ContactDisplayStyle","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactDisplayStyle","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"identifier","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?)","kind":"text"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupParticipantCell"]]},"variants":[{"paths":["\/documentation\/shengwangchatuikit\/groupparticipantcell\/init(displaystyle:identifier:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/shengwangchatuikit\/groupparticipantcell\/init(displaystyle:identifier:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","sections":[],"metadata":{"title":"init(displayStyle:identifier:)","role":"symbol","roleHeading":"Initializer","navigatorTitle":[{"text":"initWithDisplayStyle:identifier:","kind":"identifier"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"displayStyle","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@E@ContactDisplayStyle","text":"ContactDisplayStyle"},{"text":", ","kind":"text"},{"text":"identifier","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?)"}],"symbolKind":"init","externalID":"c:@M@ShengwangChatUIKit@objc(cs)GroupParticipantCell(im)initWithDisplayStyle:identifier:","modules":[{"name":"ShengwangChatUIKit"}]},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ContactDisplayStyle":{"navigatorTitle":[{"text":"ContactDisplayStyle","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactDisplayStyle","abstract":[],"url":"\/documentation\/shengwangchatuikit\/contactdisplaystyle","role":"symbol","kind":"symbol","type":"topic","title":"ContactDisplayStyle","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ContactDisplayStyle","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/GroupParticipantCell":{"type":"topic","role":"symbol","title":"GroupParticipantCell","kind":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"GroupParticipantCell"}],"url":"\/documentation\/shengwangchatuikit\/groupparticipantcell","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupParticipantCell","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GroupParticipantCell","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/GroupParticipantCell/init(displayStyle:identifier:)":{"title":"init(displayStyle:identifier:)","role":"symbol","navigatorTitle":[{"text":"initWithDisplayStyle:identifier:","kind":"identifier"}],"type":"topic","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"displayStyle"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@E@ContactDisplayStyle","text":"ContactDisplayStyle","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?)","kind":"text"}],"kind":"symbol","abstract":[],"url":"\/documentation\/shengwangchatuikit\/groupparticipantcell\/init(displaystyle:identifier:)","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupParticipantCell\/init(displayStyle:identifier:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"value":"initWithDisplayStyle:identifier:","path":"\/metadata\/title","op":"replace"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithDisplayStyle:identifier:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"initWithDisplayStyle:","kind":"identifier"},{"kind":"text","text":"("},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactDisplayStyle","text":"ContactDisplayStyle","preciseIdentifier":"c:@M@ShengwangChatUIKit@E@ContactDisplayStyle"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"displayStyle"},{"kind":"text","text":" "},{"text":"identifier:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"identifier","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"ContactDisplayStyle","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactDisplayStyle\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactDisplayStyle\/fragments","op":"replace","value":[{"text":"ContactDisplayStyle","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactDisplayStyle\/navigatorTitle","value":[{"kind":"identifier","text":"ContactDisplayStyle"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupParticipantCell\/title","op":"replace","value":"GroupParticipantCell"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupParticipantCell\/fragments","value":[{"text":"GroupParticipantCell","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupParticipantCell\/navigatorTitle","value":[{"kind":"identifier","text":"GroupParticipantCell"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupParticipantCell~1init(displayStyle:identifier:)\/title","value":"initWithDisplayStyle:identifier:"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithDisplayStyle:identifier:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupParticipantCell~1init(displayStyle:identifier:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}