{"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/EmptyStateView\/init(coder:)","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/EmptyStateView"]]},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"externalID":"c:@M@ShengwangChatUIKit@objc(cs)EmptyStateView(im)initWithCoder:","roleHeading":"Initializer","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"text":"coder","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder"},{"kind":"text","text":")"}],"role":"symbol","title":"init(coder:)","modules":[{"name":"ShengwangChatUIKit"}],"symbolKind":"init"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@","kind":"attribute"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"kind":"keyword","text":"required"},{"kind":"text","text":" "},{"text":"init","kind":"keyword"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"coder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder"},{"text":")","kind":"text"}],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/emptystateview\/init(coder:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/emptystateview\/init(coder:)"]}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/EmptyStateView":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/EmptyStateView","abstract":[],"url":"\/documentation\/shengwangchatuikit\/emptystateview","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"EmptyStateView"}],"role":"symbol","title":"EmptyStateView","navigatorTitle":[{"text":"EmptyStateView","kind":"identifier"}],"kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/EmptyStateView/init(coder:)":{"navigatorTitle":[{"text":"initWithCoder:","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/emptystateview\/init(coder:)","type":"topic","fragments":[{"kind":"identifier","text":"init"},{"text":"?(","kind":"text"},{"text":"coder","kind":"externalParam"},{"kind":"text","text":": "},{"text":"NSCoder","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSCoder"},{"text":")","kind":"text"}],"role":"symbol","title":"init(coder:)","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/EmptyStateView\/init(coder:)","kind":"symbol","abstract":[]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"initWithCoder:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithCoder:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"kind":"text","text":") "},{"text":"initWithCoder:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSCoder","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSCoder"},{"text":" *) ","kind":"text"},{"text":"coder","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"value":"EmptyStateView","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1EmptyStateView\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1EmptyStateView\/fragments","value":[{"text":"EmptyStateView","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1EmptyStateView\/navigatorTitle","op":"replace","value":[{"text":"EmptyStateView","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1EmptyStateView~1init(coder:)\/title","value":"initWithCoder:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1EmptyStateView~1init(coder:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithCoder:","kind":"identifier"}],"op":"replace"}]}]}