{"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/EaseChatThread"]]},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/EaseChatThread\/init"},"metadata":{"modules":[{"name":"ShengwangChatUIKit"}],"title":"init","roleHeading":"Instance Method","role":"symbol","navigatorTitle":[{"text":"init","kind":"identifier"}],"externalID":"c:@M@ShengwangChatUIKit@objc(cs)EaseChatThread(im)init","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"init"}],"symbolKind":"method"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"init"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}],"variants":[{"paths":["\/documentation\/shengwangchatuikit\/easechatthread\/init"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/EaseChatThread":{"type":"topic","title":"EaseChatThread","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"EaseChatThread","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/easechatthread","navigatorTitle":[{"text":"EaseChatThread","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/EaseChatThread","kind":"symbol","abstract":[],"role":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/EaseChatThread/init":{"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/EaseChatThread\/init","role":"symbol","kind":"symbol","abstract":[],"title":"init","type":"topic","url":"\/documentation\/shengwangchatuikit\/easechatthread\/init","navigatorTitle":[{"kind":"identifier","text":"init"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1EaseChatThread\/title","value":"EaseChatThread"},{"value":[{"kind":"identifier","text":"EaseChatThread"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1EaseChatThread\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1EaseChatThread\/navigatorTitle","value":[{"kind":"identifier","text":"EaseChatThread"}]}]}]}