{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/chatuserprofileprotocol\/tojsonobject()"]},{"paths":["\/documentation\/shengwangchatuikit\/chatuserprofileprotocol\/tojsonobject()"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatUserProfileProtocol"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatUserProfileProtocol\/toJsonObject()"},"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"symbolKind":"method","title":"toJsonObject()","required":true,"roleHeading":"Instance Method","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"toJsonObject","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:SD","text":"Dictionary","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"Any","kind":"keyword"},{"kind":"text","text":">?"}],"externalID":"c:@M@ShengwangChatUIKit@objc(pl)ChatUserProfileProtocol(im)toJsonObject","modules":[{"name":"ShengwangChatUIKit"}],"navigatorTitle":[{"text":"toJsonObject","kind":"identifier"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"toJsonObject","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:SD","kind":"typeIdentifier","text":"Dictionary"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":">?"}],"languages":["swift"],"platforms":["iOS"]}]}],"kind":"symbol","references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatUserProfileProtocol/toJsonObject()":{"navigatorTitle":[{"text":"toJsonObject","kind":"identifier"}],"required":true,"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatUserProfileProtocol\/toJsonObject()","type":"topic","url":"\/documentation\/shengwangchatuikit\/chatuserprofileprotocol\/tojsonobject()","abstract":[],"role":"symbol","title":"toJsonObject()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"toJsonObject"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:SD","text":"Dictionary"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":">?"}],"kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatUserProfileProtocol":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatUserProfileProtocol","abstract":[{"text":"Profile of the ChatUIKit display needed.","type":"text"}],"title":"ChatUserProfileProtocol","type":"topic","kind":"symbol","navigatorTitle":[{"text":"ChatUserProfileProtocol","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"ChatUserProfileProtocol","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/chatuserprofileprotocol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"toJsonObject"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"toJsonObject"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"NSDictionary<NSString *,id>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSDictionary"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"toJsonObject"},{"kind":"text","text":";"}]}]}},{"value":"toJsonObject","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatUserProfileProtocol~1toJsonObject()\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"toJsonObject"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatUserProfileProtocol~1toJsonObject()\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatUserProfileProtocol\/title","value":"ChatUserProfileProtocol"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatUserProfileProtocol\/fragments","value":[{"text":"ChatUserProfileProtocol","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatUserProfileProtocol\/navigatorTitle","value":[{"kind":"identifier","text":"ChatUserProfileProtocol"}]}]}]}