{"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UIKit\/UIScrollView"]]},"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UIKit\/UIScrollView\/PullRefresher","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"PullRefresher","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PullRefresher","kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)PullRefresher","text":"PullRefresher"},{"kind":"text","text":"? { "},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/uikit\/uiscrollview\/pullrefresher"]}],"metadata":{"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"PullRefresher","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)PullRefresher","text":"PullRefresher","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"roleHeading":"Instance Property","modules":[{"relatedModules":["UIKit"],"name":"ShengwangChatUIKit"}],"extendedModule":"UIKit","title":"PullRefresher","symbolKind":"property","externalID":"s:So12UIScrollViewC18ShengwangChatUIKitE13PullRefresherAcDCSgvp"},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/UIKit/UIScrollView":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"UIScrollView"}],"url":"\/documentation\/shengwangchatuikit\/uikit\/uiscrollview","title":"UIScrollView","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UIKit\/UIScrollView","fragments":[{"text":"extension","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIScrollView","preciseIdentifier":"c:objc(cs)UIScrollView","kind":"identifier"}],"type":"topic","role":"symbol","abstract":[]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/PullRefresher":{"url":"\/documentation\/shengwangchatuikit\/pullrefresher","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PullRefresher"}],"abstract":[],"role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PullRefresher","title":"PullRefresher","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"PullRefresher","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/UIKit/UIScrollView/PullRefresher":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UIKit\/UIScrollView\/PullRefresher","url":"\/documentation\/shengwangchatuikit\/uikit\/uiscrollview\/pullrefresher","type":"topic","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PullRefresher","kind":"identifier"},{"text":": ","kind":"text"},{"text":"PullRefresher","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)PullRefresher","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"PullRefresher","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","type":"topic","abstract":[],"url":"\/documentation\/shengwangchatuikit\/uikit","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/UIKit"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PullRefresher\/title","value":"PullRefresher"},{"op":"replace","value":[{"text":"PullRefresher","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PullRefresher\/fragments"},{"value":[{"text":"PullRefresher","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PullRefresher\/navigatorTitle"}]}]}