{"metadata":{"symbolKind":"method","role":"symbol","modules":[{"name":"ShengwangChatUIKit"}],"roleHeading":"Instance Method","externalID":"s:18ShengwangChatUIKit18CrossZoomAnimationC06beforeF016animationContextyAA0fI0V_tF","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"beforeAnimation","kind":"identifier"},{"kind":"text","text":"("},{"text":"animationContext","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit16AnimationContextV","text":"AnimationContext"},{"text":")","kind":"text"}],"title":"beforeAnimation(animationContext:)"},"kind":"symbol","sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/CrossZoomAnimation\/beforeAnimation(animationContext:)"},"variants":[{"paths":["\/documentation\/shengwangchatuikit\/crosszoomanimation\/beforeanimation(animationcontext:)"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/CrossZoomAnimation"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"override","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"beforeAnimation","kind":"identifier"},{"kind":"text","text":"("},{"text":"animationContext","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:18ShengwangChatUIKit16AnimationContextV","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/AnimationContext","text":"AnimationContext"},{"kind":"text","text":")"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/CrossZoomAnimation/beforeAnimation(animationContext:)":{"url":"\/documentation\/shengwangchatuikit\/crosszoomanimation\/beforeanimation(animationcontext:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"beforeAnimation","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"animationContext"},{"kind":"text","text":": "},{"text":"AnimationContext","preciseIdentifier":"s:18ShengwangChatUIKit16AnimationContextV","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/CrossZoomAnimation\/beforeAnimation(animationContext:)","role":"symbol","type":"topic","title":"beforeAnimation(animationContext:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/CrossZoomAnimation":{"navigatorTitle":[{"text":"CrossZoomAnimation","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/CrossZoomAnimation","title":"CrossZoomAnimation","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"CrossZoomAnimation","kind":"identifier"}],"type":"topic","abstract":[],"url":"\/documentation\/shengwangchatuikit\/crosszoomanimation"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/AnimationContext":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"AnimationContext"}],"type":"topic","title":"AnimationContext","url":"\/documentation\/shengwangchatuikit\/animationcontext","navigatorTitle":[{"kind":"identifier","text":"AnimationContext"}],"abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/AnimationContext","role":"symbol"}},"variantOverrides":[{"patch":[{"value":"CrossZoomAnimation","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1CrossZoomAnimation\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1CrossZoomAnimation\/fragments","value":[{"text":"CrossZoomAnimation","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"text":"CrossZoomAnimation","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1CrossZoomAnimation\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}