{"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ForwardTargetState\/forwarded","interfaceLanguage":"swift"},"sections":[],"metadata":{"symbolKind":"case","navigatorTitle":[{"text":"ForwardTargetStateForwarded","kind":"identifier"}],"role":"symbol","modules":[{"name":"ShengwangChatUIKit"}],"roleHeading":"Case","externalID":"c:@M@ShengwangChatUIKit@E@ForwardTargetState@ForwardTargetStateForwarded","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"forwarded","kind":"identifier"}],"title":"ForwardTargetState.forwarded"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"forwarded","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ForwardTargetState"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/forwardtargetstate\/forwarded"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/forwardtargetstate\/forwarded"]}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ForwardTargetState/forwarded":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"forwarded","kind":"identifier"}],"type":"topic","title":"ForwardTargetState.forwarded","url":"\/documentation\/shengwangchatuikit\/forwardtargetstate\/forwarded","navigatorTitle":[{"text":"ForwardTargetStateForwarded","kind":"identifier"}],"abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ForwardTargetState\/forwarded","role":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ForwardTargetState":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ForwardTargetState","navigatorTitle":[{"kind":"identifier","text":"ForwardTargetState"}],"url":"\/documentation\/shengwangchatuikit\/forwardtargetstate","type":"topic","abstract":[],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ForwardTargetState"}],"title":"ForwardTargetState","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"ForwardTargetStateForwarded"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"value":[{"text":"ForwardTargetStateForwarded","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"ForwardTargetStateForwarded","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ForwardTargetState~1forwarded\/title","value":"ForwardTargetStateForwarded"},{"op":"replace","value":[{"text":"ForwardTargetStateForwarded","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ForwardTargetState~1forwarded\/fragments"},{"op":"replace","value":"ForwardTargetState","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ForwardTargetState\/title"},{"value":[{"text":"ForwardTargetState","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ForwardTargetState\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ForwardTargetState\/navigatorTitle","value":[{"text":"ForwardTargetState","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}