{"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/chatthreadlistcontroller\/handlethreadrequest(result:error:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/chatthreadlistcontroller\/handlethreadrequest(result:error:)"]}],"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadListController\/handleThreadRequest(result:error:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadListController"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","kind":"attribute","text":"MainActor"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"handleThreadRequest"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"result"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/CursorResult","text":"CursorResult","kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit12CursorResulta"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit05GroupB6Threada","text":"GroupChatThread","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupChatThread"},{"kind":"text","text":">?, "},{"kind":"externalParam","text":"error"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatError","text":"ChatError","preciseIdentifier":"s:18ShengwangChatUIKit0B5Errora","kind":"typeIdentifier"},{"kind":"text","text":"?)"}],"platforms":["iOS"],"languages":["swift"]}]}],"metadata":{"symbolKind":"method","title":"handleThreadRequest(result:error:)","roleHeading":"Instance Method","role":"symbol","modules":[{"name":"ShengwangChatUIKit"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"handleThreadRequest"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"result"},{"kind":"text","text":": "},{"text":"CursorResult","kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit12CursorResulta"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:18ShengwangChatUIKit05GroupB6Threada","kind":"typeIdentifier","text":"GroupChatThread"},{"kind":"text","text":">?, "},{"text":"error","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit0B5Errora","text":"ChatError"},{"kind":"text","text":"?)"}],"navigatorTitle":[{"text":"handleThreadRequestWithResult:error:","kind":"identifier"}],"externalID":"c:@M@ShengwangChatUIKit@objc(cs)ChatThreadListController(im)handleThreadRequestWithResult:error:"},"sections":[],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatThreadListController":{"type":"topic","title":"ChatThreadListController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChatThreadListController"}],"url":"\/documentation\/shengwangchatuikit\/chatthreadlistcontroller","navigatorTitle":[{"kind":"identifier","text":"ChatThreadListController"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadListController","kind":"symbol","abstract":[],"role":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/CursorResult":{"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"CursorResult"}],"title":"CursorResult","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/CursorResult","role":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"text":"CursorResult","kind":"identifier"}],"type":"topic","kind":"symbol","url":"\/documentation\/shengwangchatuikit\/cursorresult"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatThreadListController/handleThreadRequest(result:error:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"handleThreadRequest","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"result"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit12CursorResulta","text":"CursorResult"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:18ShengwangChatUIKit05GroupB6Threada","kind":"typeIdentifier","text":"GroupChatThread"},{"text":">?, ","kind":"text"},{"text":"error","kind":"externalParam"},{"kind":"text","text":": "},{"text":"ChatError","preciseIdentifier":"s:18ShengwangChatUIKit0B5Errora","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"kind":"symbol","url":"\/documentation\/shengwangchatuikit\/chatthreadlistcontroller\/handlethreadrequest(result:error:)","type":"topic","title":"handleThreadRequest(result:error:)","abstract":[],"role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadListController\/handleThreadRequest(result:error:)","navigatorTitle":[{"text":"handleThreadRequestWithResult:error:","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatError":{"fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChatError"}],"role":"symbol","navigatorTitle":[{"text":"ChatError","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatError","url":"\/documentation\/shengwangchatuikit\/chaterror","title":"ChatError","kind":"symbol","abstract":[]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/GroupChatThread":{"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"GroupChatThread"}],"title":"GroupChatThread","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupChatThread","role":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GroupChatThread","kind":"identifier"}],"type":"topic","kind":"symbol","url":"\/documentation\/shengwangchatuikit\/groupchatthread"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","value":"handleThreadRequestWithResult:error:","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"handleThreadRequestWithResult:error:"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"handleThreadRequestWithResult:"},{"text":"(","kind":"text"},{"text":"AgoraChatCursorResult<AgoraChatThread *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)AgoraChatCursorResult"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"result"},{"text":" ","kind":"text"},{"text":"error:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"AgoraChatError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AgoraChatError"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"error"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"ChatThreadListController","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadListController\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadListController\/fragments","value":[{"kind":"identifier","text":"ChatThreadListController"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadListController\/navigatorTitle","value":[{"kind":"identifier","text":"ChatThreadListController"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadListController~1handleThreadRequest(result:error:)\/title","value":"handleThreadRequestWithResult:error:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadListController~1handleThreadRequest(result:error:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"handleThreadRequestWithResult:error:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}