{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadListController"]]},"topicSections":[{"generated":true,"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadListController\/scrollViewDidEndDecelerating(_:)"]}],"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadListController\/UIScrollViewDelegate-Implementations","interfaceLanguage":"swift"},"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"modules":[{"name":"ShengwangChatUIKit"}],"title":"UIScrollViewDelegate Implementations","roleHeading":"API Collection","role":"collectionGroup"},"kind":"article","variants":[{"paths":["\/documentation\/shengwangchatuikit\/chatthreadlistcontroller\/uiscrollviewdelegate-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/shengwangchatuikit\/chatthreadlistcontroller\/uiscrollviewdelegate-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatThreadListController/scrollViewDidEndDecelerating(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"scrollViewDidEndDecelerating","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIScrollView","kind":"typeIdentifier","text":"UIScrollView"},{"kind":"text","text":")"}],"role":"symbol","navigatorTitle":[{"text":"scrollViewDidEndDecelerating:","kind":"identifier"}],"title":"scrollViewDidEndDecelerating(_:)","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadListController\/scrollViewDidEndDecelerating(_:)","abstract":[],"type":"topic","url":"\/documentation\/shengwangchatuikit\/chatthreadlistcontroller\/scrollviewdidenddecelerating(_:)","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatThreadListController":{"type":"topic","title":"ChatThreadListController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChatThreadListController"}],"url":"\/documentation\/shengwangchatuikit\/chatthreadlistcontroller","navigatorTitle":[{"kind":"identifier","text":"ChatThreadListController"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadListController","kind":"symbol","abstract":[],"role":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":[{"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadListController\/scrollViewDidEndDecelerating(_:)"],"title":"Instance Methods","anchor":"Instance-Methods","generated":true}],"path":"\/topicSections","op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":"scrollViewDidEndDecelerating:","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadListController~1scrollViewDidEndDecelerating(_:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"scrollViewDidEndDecelerating:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadListController~1scrollViewDidEndDecelerating(_:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadListController\/title","op":"replace","value":"ChatThreadListController"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadListController\/fragments","value":[{"text":"ChatThreadListController","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadListController\/navigatorTitle","value":[{"text":"ChatThreadListController","kind":"identifier"}]}]}]}