{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/alertviewcontroller\/presentedviewcomponent"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/AlertViewController"]]},"metadata":{"role":"symbol","symbolKind":"property","externalID":"s:18ShengwangChatUIKit19AlertViewControllerC09presentedE9ComponentAA09PresentedeH0VSgvp","title":"presentedViewComponent","roleHeading":"Instance Property","modules":[{"name":"ShengwangChatUIKit"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"presentedViewComponent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit22PresentedViewComponentV","text":"PresentedViewComponent"},{"text":"?","kind":"text"}]},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"presentedViewComponent","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PresentedViewComponent","text":"PresentedViewComponent","preciseIdentifier":"s:18ShengwangChatUIKit22PresentedViewComponentV"},{"text":"?","kind":"text"}]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"Inherited from "},{"code":"PresentedViewType.presentedViewComponent","type":"codeVoice"},{"text":".","type":"text"}],"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/AlertViewController\/presentedViewComponent","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/AlertViewController/presentedViewComponent":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/AlertViewController\/presentedViewComponent","role":"symbol","url":"\/documentation\/shengwangchatuikit\/alertviewcontroller\/presentedviewcomponent","title":"presentedViewComponent","kind":"symbol","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"presentedViewComponent"},{"kind":"text","text":": "},{"preciseIdentifier":"s:18ShengwangChatUIKit22PresentedViewComponentV","kind":"typeIdentifier","text":"PresentedViewComponent"},{"kind":"text","text":"?"}],"type":"topic"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/AlertViewController":{"title":"AlertViewController","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/AlertViewController","role":"symbol","url":"\/documentation\/shengwangchatuikit\/alertviewcontroller","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AlertViewController"}],"navigatorTitle":[{"text":"AlertViewController","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/PresentedViewComponent":{"url":"\/documentation\/shengwangchatuikit\/presentedviewcomponent","abstract":[{"type":"text","text":"presentedView setting"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"PresentedViewComponent"}],"type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PresentedViewComponent","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"PresentedViewComponent","kind":"identifier"}],"title":"PresentedViewComponent"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1AlertViewController\/title","value":"AlertViewController"},{"value":[{"kind":"identifier","text":"AlertViewController"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1AlertViewController\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1AlertViewController\/navigatorTitle","op":"replace","value":[{"text":"AlertViewController","kind":"identifier"}]}]}]}