{"variants":[{"paths":["\/documentation\/shengwangchatuikit\/detailinfolistcell\/init(style:reuseidentifier:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/detailinfolistcell\/init(style:reuseidentifier:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/DetailInfoListCell\/init(style:reuseIdentifier:)"},"kind":"symbol","sections":[],"metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"style","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITableViewCell","text":"UITableViewCell"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@E@UITableViewCellStyle","kind":"typeIdentifier","text":"CellStyle"},{"text":", ","kind":"text"},{"text":"reuseIdentifier","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"initWithStyle:reuseIdentifier:"}],"modules":[{"name":"ShengwangChatUIKit"}],"title":"init(style:reuseIdentifier:)","roleHeading":"Initializer","externalID":"c:@M@ShengwangChatUIKit@objc(cs)DetailInfoListCell(im)initWithStyle:reuseIdentifier:","role":"symbol","symbolKind":"init"},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"override"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"text":"style","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UITableViewCell","preciseIdentifier":"c:objc(cs)UITableViewCell","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"CellStyle","kind":"typeIdentifier","preciseIdentifier":"c:@E@UITableViewCellStyle"},{"text":", ","kind":"text"},{"text":"reuseIdentifier","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?)","kind":"text"}]}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/DetailInfoListCell"]]},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/DetailInfoListCell":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/DetailInfoListCell","navigatorTitle":[{"kind":"identifier","text":"DetailInfoListCell"}],"url":"\/documentation\/shengwangchatuikit\/detailinfolistcell","type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"DetailInfoListCell","kind":"identifier"}],"title":"DetailInfoListCell","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/DetailInfoListCell/init(style:reuseIdentifier:)":{"abstract":[],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/DetailInfoListCell\/init(style:reuseIdentifier:)","navigatorTitle":[{"text":"initWithStyle:reuseIdentifier:","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/shengwangchatuikit\/detailinfolistcell\/init(style:reuseidentifier:)","kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"style","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UITableViewCell","text":"UITableViewCell","kind":"typeIdentifier"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@UITableViewCellStyle","text":"CellStyle"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"reuseIdentifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?)","kind":"text"}],"title":"init(style:reuseIdentifier:)"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","value":"initWithStyle:reuseIdentifier:","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithStyle:reuseIdentifier:"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","preciseIdentifier":"c:*Qo","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithStyle:"},{"text":"(","kind":"text"},{"text":"UITableViewCellStyle","preciseIdentifier":"c:@E@UITableViewCellStyle","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"style","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"reuseIdentifier:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"reuseIdentifier","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":"DetailInfoListCell","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1DetailInfoListCell\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1DetailInfoListCell\/fragments","value":[{"kind":"identifier","text":"DetailInfoListCell"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1DetailInfoListCell\/navigatorTitle","value":[{"kind":"identifier","text":"DetailInfoListCell"}],"op":"replace"},{"value":"initWithStyle:reuseIdentifier:","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1DetailInfoListCell~1init(style:reuseIdentifier:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1DetailInfoListCell~1init(style:reuseIdentifier:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"initWithStyle:reuseIdentifier:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}