{"kind":"symbol","sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"cancel","kind":"identifier"}]}]}],"variants":[{"paths":["\/documentation\/shengwangchatuikit\/searchheaderbaractiontype\/cancel"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/searchheaderbaractiontype\/cancel"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/SearchHeaderBarActionType"]]},"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/SearchHeaderBarActionType\/cancel","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"SearchHeaderBarActionTypeCancel"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"cancel"}],"externalID":"c:@M@ShengwangChatUIKit@E@SearchHeaderBarActionType@SearchHeaderBarActionTypeCancel","role":"symbol","roleHeading":"Case","symbolKind":"case","modules":[{"name":"ShengwangChatUIKit"}],"title":"SearchHeaderBarActionType.cancel"},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/SearchHeaderBarActionType":{"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SearchHeaderBarActionType"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/SearchHeaderBarActionType","title":"SearchHeaderBarActionType","abstract":[],"role":"symbol","kind":"symbol","url":"\/documentation\/shengwangchatuikit\/searchheaderbaractiontype","navigatorTitle":[{"kind":"identifier","text":"SearchHeaderBarActionType"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/SearchHeaderBarActionType/cancel":{"navigatorTitle":[{"text":"SearchHeaderBarActionTypeCancel","kind":"identifier"}],"kind":"symbol","title":"SearchHeaderBarActionType.cancel","url":"\/documentation\/shengwangchatuikit\/searchheaderbaractiontype\/cancel","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cancel"}],"abstract":[],"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/SearchHeaderBarActionType\/cancel"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"value":"SearchHeaderBarActionTypeCancel","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"SearchHeaderBarActionTypeCancel","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"SearchHeaderBarActionTypeCancel","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1SearchHeaderBarActionType\/title","value":"SearchHeaderBarActionType"},{"value":[{"kind":"identifier","text":"SearchHeaderBarActionType"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1SearchHeaderBarActionType\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SearchHeaderBarActionType"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1SearchHeaderBarActionType\/navigatorTitle"},{"op":"replace","value":"SearchHeaderBarActionTypeCancel","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1SearchHeaderBarActionType~1cancel\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1SearchHeaderBarActionType~1cancel\/fragments","value":[{"kind":"identifier","text":"SearchHeaderBarActionTypeCancel"}],"op":"replace"}]}]}