{"kind":"article","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/SearchHeaderBarActionType\/Equatable-Implementations"},"topicSections":[{"anchor":"Operators","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/SearchHeaderBarActionType\/!=(_:_:)"],"title":"Operators","generated":true}],"metadata":{"title":"Equatable Implementations","role":"collectionGroup","modules":[{"name":"ShengwangChatUIKit"}],"roleHeading":"API Collection"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/SearchHeaderBarActionType"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/searchheaderbaractiontype\/equatable-implementations"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/SearchHeaderBarActionType/!=(_:_:)":{"kind":"symbol","url":"\/documentation\/shengwangchatuikit\/searchheaderbaractiontype\/!=(_:_:)","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"!="},{"kind":"text","text":" "},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"Self"},{"text":", ","kind":"text"},{"kind":"typeIdentifier","text":"Self"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/SearchHeaderBarActionType\/!=(_:_:)","title":"!=(_:_:)","abstract":[]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/SearchHeaderBarActionType":{"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SearchHeaderBarActionType"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/SearchHeaderBarActionType","title":"SearchHeaderBarActionType","abstract":[],"role":"symbol","kind":"symbol","url":"\/documentation\/shengwangchatuikit\/searchheaderbaractiontype","navigatorTitle":[{"kind":"identifier","text":"SearchHeaderBarActionType"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1SearchHeaderBarActionType\/title","value":"SearchHeaderBarActionType","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1SearchHeaderBarActionType\/fragments","value":[{"kind":"identifier","text":"SearchHeaderBarActionType"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1SearchHeaderBarActionType\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SearchHeaderBarActionType"}]}]}]}