{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actionSheet","kind":"identifier"}],"languages":["swift"]}]}],"metadata":{"modules":[{"name":"ShengwangChatUIKit"}],"roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actionSheet","kind":"identifier"}],"title":"MessageAttachmentMenuStyle.actionSheet","role":"symbol","navigatorTitle":[{"text":"MessageAttachmentMenuStyleActionSheet","kind":"identifier"}],"externalID":"c:@M@ShengwangChatUIKit@E@MessageAttachmentMenuStyle@MessageAttachmentMenuStyleActionSheet","symbolKind":"case"},"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageAttachmentMenuStyle\/actionSheet","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageAttachmentMenuStyle"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/messageattachmentmenustyle\/actionsheet"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/messageattachmentmenustyle\/actionsheet"]}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageAttachmentMenuStyle":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"MessageAttachmentMenuStyle"}],"url":"\/documentation\/shengwangchatuikit\/messageattachmentmenustyle","kind":"symbol","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageAttachmentMenuStyle"}],"abstract":[],"title":"MessageAttachmentMenuStyle","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageAttachmentMenuStyle"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageAttachmentMenuStyle/actionSheet":{"url":"\/documentation\/shengwangchatuikit\/messageattachmentmenustyle\/actionsheet","abstract":[],"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageAttachmentMenuStyle\/actionSheet","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"actionSheet"}],"navigatorTitle":[{"kind":"identifier","text":"MessageAttachmentMenuStyleActionSheet"}],"role":"symbol","title":"MessageAttachmentMenuStyle.actionSheet"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"value":"MessageAttachmentMenuStyleActionSheet","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"MessageAttachmentMenuStyleActionSheet","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"MessageAttachmentMenuStyleActionSheet","kind":"identifier"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageAttachmentMenuStyle\/title","value":"MessageAttachmentMenuStyle"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageAttachmentMenuStyle\/fragments","op":"replace","value":[{"kind":"identifier","text":"MessageAttachmentMenuStyle"}]},{"value":[{"text":"MessageAttachmentMenuStyle","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageAttachmentMenuStyle\/navigatorTitle"},{"value":"MessageAttachmentMenuStyleActionSheet","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageAttachmentMenuStyle~1actionSheet\/title"},{"op":"replace","value":[{"text":"MessageAttachmentMenuStyleActionSheet","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageAttachmentMenuStyle~1actionSheet\/fragments"}]}]}