{"metadata":{"symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"MessageAttachmentMenuStyleFollowInput"}],"role":"symbol","modules":[{"name":"ShengwangChatUIKit"}],"roleHeading":"Case","externalID":"c:@M@ShengwangChatUIKit@E@MessageAttachmentMenuStyle@MessageAttachmentMenuStyleFollowInput","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"followInput"}],"title":"MessageAttachmentMenuStyle.followInput"},"sections":[],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageAttachmentMenuStyle\/followInput"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/messageattachmentmenustyle\/followinput"]},{"paths":["\/documentation\/shengwangchatuikit\/messageattachmentmenustyle\/followinput"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageAttachmentMenuStyle"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"followInput","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageAttachmentMenuStyle/followInput":{"abstract":[],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageAttachmentMenuStyle\/followInput","navigatorTitle":[{"kind":"identifier","text":"MessageAttachmentMenuStyleFollowInput"}],"type":"topic","role":"symbol","url":"\/documentation\/shengwangchatuikit\/messageattachmentmenustyle\/followinput","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"followInput"}],"title":"MessageAttachmentMenuStyle.followInput"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageAttachmentMenuStyle":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"MessageAttachmentMenuStyle"}],"url":"\/documentation\/shengwangchatuikit\/messageattachmentmenustyle","kind":"symbol","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageAttachmentMenuStyle"}],"abstract":[],"title":"MessageAttachmentMenuStyle","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageAttachmentMenuStyle"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"MessageAttachmentMenuStyleFollowInput"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"MessageAttachmentMenuStyleFollowInput","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"MessageAttachmentMenuStyleFollowInput"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageAttachmentMenuStyle~1followInput\/title","value":"MessageAttachmentMenuStyleFollowInput","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"MessageAttachmentMenuStyleFollowInput"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageAttachmentMenuStyle~1followInput\/fragments"},{"value":"MessageAttachmentMenuStyle","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageAttachmentMenuStyle\/title"},{"op":"replace","value":[{"text":"MessageAttachmentMenuStyle","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageAttachmentMenuStyle\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageAttachmentMenuStyle\/navigatorTitle","value":[{"text":"MessageAttachmentMenuStyle","kind":"identifier"}]}]}]}