{"variants":[{"paths":["\/documentation\/shengwangchatuikit\/messageinputemojiview\/uicollectionviewdatasource-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/shengwangchatuikit\/messageinputemojiview\/uicollectionviewdatasource-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageInputEmojiView\/UICollectionViewDataSource-Implementations","interfaceLanguage":"swift"},"kind":"article","metadata":{"role":"collectionGroup","modules":[{"name":"ShengwangChatUIKit"}],"roleHeading":"API Collection","title":"UICollectionViewDataSource Implementations"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageInputEmojiView"]]},"topicSections":[{"generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageInputEmojiView\/collectionView(_:cellForItemAt:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageInputEmojiView\/collectionView(_:numberOfItemsInSection:)"],"title":"Instance Methods"}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageInputEmojiView/collectionView(_:numberOfItemsInSection:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"collectionView","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UICollectionView","text":"UICollectionView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"numberOfItemsInSection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"type":"topic","abstract":[],"role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageInputEmojiView\/collectionView(_:numberOfItemsInSection:)","title":"collectionView(_:numberOfItemsInSection:)","navigatorTitle":[{"kind":"identifier","text":"collectionView:numberOfItemsInSection:"}],"url":"\/documentation\/shengwangchatuikit\/messageinputemojiview\/collectionview(_:numberofitemsinsection:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageInputEmojiView":{"navigatorTitle":[{"text":"MessageInputEmojiView","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/messageinputemojiview","title":"MessageInputEmojiView","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MessageInputEmojiView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageInputEmojiView","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageInputEmojiView/collectionView(_:cellForItemAt:)":{"type":"topic","abstract":[],"url":"\/documentation\/shengwangchatuikit\/messageinputemojiview\/collectionview(_:cellforitemat:)","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageInputEmojiView\/collectionView(_:cellForItemAt:)","title":"collectionView(_:cellForItemAt:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"collectionView","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UICollectionView","text":"UICollectionView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"cellForItemAt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":") -> "},{"text":"UICollectionViewCell","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UICollectionViewCell"}],"navigatorTitle":[{"kind":"identifier","text":"collectionView:cellForItemAtIndexPath:"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":[{"generated":true,"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageInputEmojiView\/collectionView(_:cellForItemAt:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageInputEmojiView\/collectionView(_:numberOfItemsInSection:)"],"anchor":"Instance-Methods","title":"Instance Methods"}],"path":"\/topicSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageInputEmojiView~1collectionView(_:numberOfItemsInSection:)\/title","value":"collectionView:numberOfItemsInSection:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"collectionView:numberOfItemsInSection:"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageInputEmojiView~1collectionView(_:numberOfItemsInSection:)\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageInputEmojiView\/title","value":"MessageInputEmojiView","op":"replace"},{"value":[{"text":"MessageInputEmojiView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageInputEmojiView\/fragments"},{"value":[{"kind":"identifier","text":"MessageInputEmojiView"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageInputEmojiView\/navigatorTitle","op":"replace"},{"value":"collectionView:cellForItemAtIndexPath:","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageInputEmojiView~1collectionView(_:cellForItemAt:)\/title","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"collectionView:cellForItemAtIndexPath:"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageInputEmojiView~1collectionView(_:cellForItemAt:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}