{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"fillDatas","kind":"identifier"},{"text":"() -> [","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/NewContactRequest","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)NewContactRequest","text":"NewContactRequest"},{"kind":"text","text":"]"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","metadata":{"modules":[{"name":"ShengwangChatUIKit"}],"symbolKind":"method","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fillDatas","kind":"identifier"},{"text":"() -> [","kind":"text"},{"kind":"typeIdentifier","text":"NewContactRequest","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)NewContactRequest"},{"kind":"text","text":"]"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"fillDatas"}],"externalID":"c:@M@ShengwangChatUIKit@objc(cs)NewContactRequestController(im)fillDatas","title":"fillDatas()"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/newcontactrequestcontroller\/filldatas()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/newcontactrequestcontroller\/filldatas()"]}],"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/NewContactRequestController"]]},"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/NewContactRequestController\/fillDatas()","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/NewContactRequestController":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/NewContactRequestController","title":"NewContactRequestController","navigatorTitle":[{"text":"NewContactRequestController","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/newcontactrequestcontroller","role":"symbol","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"NewContactRequestController","kind":"identifier"}],"abstract":[]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/NewContactRequest":{"type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"NewContactRequest","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/newcontactrequest","abstract":[],"title":"NewContactRequest","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/NewContactRequest","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"NewContactRequest","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/NewContactRequestController/fillDatas()":{"title":"fillDatas()","navigatorTitle":[{"kind":"identifier","text":"fillDatas"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/NewContactRequestController\/fillDatas()","url":"\/documentation\/shengwangchatuikit\/newcontactrequestcontroller\/filldatas()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fillDatas"},{"text":"() -> [","kind":"text"},{"text":"NewContactRequest","kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)NewContactRequest"},{"kind":"text","text":"]"}],"type":"topic","role":"symbol","abstract":[]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"fillDatas","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"fillDatas","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<NewContactRequest *>"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"fillDatas"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","value":"NewContactRequestController","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1NewContactRequestController\/title"},{"op":"replace","value":[{"kind":"identifier","text":"NewContactRequestController"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1NewContactRequestController\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1NewContactRequestController\/navigatorTitle","value":[{"kind":"identifier","text":"NewContactRequestController"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1NewContactRequest\/title","value":"NewContactRequest"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1NewContactRequest\/fragments","value":[{"kind":"identifier","text":"NewContactRequest"}],"op":"replace"},{"value":[{"text":"NewContactRequest","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1NewContactRequest\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1NewContactRequestController~1fillDatas()\/title","op":"replace","value":"fillDatas"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1NewContactRequestController~1fillDatas()\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"fillDatas"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}