{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/newcontactrequestcontroller\/requestfriendinfo(userid:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/newcontactrequestcontroller\/requestfriendinfo(userid:)"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/NewContactRequestController"]]},"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","kind":"attribute","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestFriendInfo"},{"kind":"text","text":"("},{"kind":"externalParam","text":"userId"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"metadata":{"roleHeading":"Instance Method","title":"requestFriendInfo(userId:)","extendedModule":"ShengwangChatUIKit","role":"symbol","navigatorTitle":[{"text":"requestFriendInfoWithUserId:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"requestFriendInfo","kind":"identifier"},{"text":"(","kind":"text"},{"text":"userId","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"externalID":"c:@CM@ShengwangChatUIKit@objc(cs)NewContactRequestController(im)requestFriendInfoWithUserId:","modules":[{"name":"ShengwangChatUIKit"}],"symbolKind":"method"},"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/NewContactRequestController\/requestFriendInfo(userId:)","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/NewContactRequestController":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/NewContactRequestController","title":"NewContactRequestController","navigatorTitle":[{"text":"NewContactRequestController","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/newcontactrequestcontroller","role":"symbol","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"NewContactRequestController","kind":"identifier"}],"abstract":[]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/NewContactRequestController/requestFriendInfo(userId:)":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/NewContactRequestController\/requestFriendInfo(userId:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"requestFriendInfo"},{"kind":"text","text":"("},{"text":"userId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":")","kind":"text"}],"type":"topic","title":"requestFriendInfo(userId:)","role":"symbol","navigatorTitle":[{"text":"requestFriendInfoWithUserId:","kind":"identifier"}],"abstract":[],"url":"\/documentation\/shengwangchatuikit\/newcontactrequestcontroller\/requestfriendinfo(userid:)","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"requestFriendInfoWithUserId:","op":"replace"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"requestFriendInfoWithUserId:"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"text":") ","kind":"text"},{"text":"requestFriendInfoWithUserId:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"userId","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1NewContactRequestController\/title","value":"NewContactRequestController"},{"op":"replace","value":[{"text":"NewContactRequestController","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1NewContactRequestController\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1NewContactRequestController\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"NewContactRequestController"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1NewContactRequestController~1requestFriendInfo(userId:)\/title","value":"requestFriendInfoWithUserId:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"requestFriendInfoWithUserId:"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1NewContactRequestController~1requestFriendInfo(userId:)\/fragments"}]}]}