{"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/NewContactRequestController\/requestList","interfaceLanguage":"swift"},"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"requestList","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UITableView","text":"UITableView","kind":"typeIdentifier"}],"roleHeading":"Instance Property","modules":[{"name":"ShengwangChatUIKit"}],"symbolKind":"property","role":"symbol","externalID":"s:18ShengwangChatUIKit27NewContactRequestControllerC11requestListSo11UITableViewCvp","title":"requestList"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/NewContactRequestController"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"kind":"text","text":" "},{"text":"lazy","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestList"},{"text":": ","kind":"text"},{"text":"UITableView","preciseIdentifier":"c:objc(cs)UITableView","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}]}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/shengwangchatuikit\/newcontactrequestcontroller\/requestlist"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/NewContactRequestController":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/NewContactRequestController","title":"NewContactRequestController","navigatorTitle":[{"text":"NewContactRequestController","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/newcontactrequestcontroller","role":"symbol","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"NewContactRequestController","kind":"identifier"}],"abstract":[]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/NewContactRequestController/requestList":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/NewContactRequestController\/requestList","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"requestList","kind":"identifier"},{"kind":"text","text":": "},{"text":"UITableView","preciseIdentifier":"c:objc(cs)UITableView","kind":"typeIdentifier"}],"kind":"symbol","url":"\/documentation\/shengwangchatuikit\/newcontactrequestcontroller\/requestlist","title":"requestList","role":"symbol","abstract":[],"type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"NewContactRequestController","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1NewContactRequestController\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1NewContactRequestController\/fragments","value":[{"kind":"identifier","text":"NewContactRequestController"}],"op":"replace"},{"op":"replace","value":[{"text":"NewContactRequestController","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1NewContactRequestController\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}