{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactListHeaderStyle"]]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/contactlistheaderstyle\/addgroupparticipant"]},{"paths":["\/documentation\/shengwangchatuikit\/contactlistheaderstyle\/addgroupparticipant"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactListHeaderStyle\/addGroupParticipant","interfaceLanguage":"swift"},"metadata":{"role":"symbol","title":"ContactListHeaderStyle.addGroupParticipant","roleHeading":"Case","externalID":"c:@M@ShengwangChatUIKit@E@ContactListHeaderStyle@ContactListHeaderStyleAddGroupParticipant","navigatorTitle":[{"kind":"identifier","text":"ContactListHeaderStyleAddGroupParticipant"}],"modules":[{"name":"ShengwangChatUIKit"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"addGroupParticipant","kind":"identifier"}],"symbolKind":"case"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"addGroupParticipant","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ContactListHeaderStyle/addGroupParticipant":{"title":"ContactListHeaderStyle.addGroupParticipant","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"addGroupParticipant"}],"url":"\/documentation\/shengwangchatuikit\/contactlistheaderstyle\/addgroupparticipant","role":"symbol","abstract":[],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"ContactListHeaderStyleAddGroupParticipant"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactListHeaderStyle\/addGroupParticipant"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ContactListHeaderStyle":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ContactListHeaderStyle","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ContactListHeaderStyle"}],"type":"topic","abstract":[{"text":"The header display style of the ","type":"text"},{"code":"ContactList","type":"codeVoice"},{"type":"text","text":"."}],"title":"ContactListHeaderStyle","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactListHeaderStyle","url":"\/documentation\/shengwangchatuikit\/contactlistheaderstyle"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"ContactListHeaderStyleAddGroupParticipant","op":"replace"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"ContactListHeaderStyleAddGroupParticipant","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"ContactListHeaderStyleAddGroupParticipant"}]}]}},{"value":"ContactListHeaderStyleAddGroupParticipant","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactListHeaderStyle~1addGroupParticipant\/title","op":"replace"},{"value":[{"kind":"identifier","text":"ContactListHeaderStyleAddGroupParticipant"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactListHeaderStyle~1addGroupParticipant\/fragments"},{"op":"replace","value":"ContactListHeaderStyle","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactListHeaderStyle\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactListHeaderStyle\/fragments","value":[{"text":"ContactListHeaderStyle","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactListHeaderStyle\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"ContactListHeaderStyle"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}