{"variants":[{"paths":["\/documentation\/shengwangchatuikit\/contactlistheaderstyle\/newchat"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/shengwangchatuikit\/contactlistheaderstyle\/newchat"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactListHeaderStyle\/newChat"},"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"newChat","kind":"identifier"}],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactListHeaderStyle"]]},"metadata":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"newChat"}],"externalID":"c:@M@ShengwangChatUIKit@E@ContactListHeaderStyle@ContactListHeaderStyleNewChat","role":"symbol","roleHeading":"Case","title":"ContactListHeaderStyle.newChat","modules":[{"name":"ShengwangChatUIKit"}],"symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"ContactListHeaderStyleNewChat"}]},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ContactListHeaderStyle":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ContactListHeaderStyle","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ContactListHeaderStyle"}],"type":"topic","abstract":[{"text":"The header display style of the ","type":"text"},{"code":"ContactList","type":"codeVoice"},{"type":"text","text":"."}],"title":"ContactListHeaderStyle","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactListHeaderStyle","url":"\/documentation\/shengwangchatuikit\/contactlistheaderstyle"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ContactListHeaderStyle/newChat":{"title":"ContactListHeaderStyle.newChat","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"newChat","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/contactlistheaderstyle\/newchat","role":"symbol","abstract":[],"type":"topic","navigatorTitle":[{"text":"ContactListHeaderStyleNewChat","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactListHeaderStyle\/newChat"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"ContactListHeaderStyleNewChat","op":"replace"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"ContactListHeaderStyleNewChat"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"ContactListHeaderStyleNewChat","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]}},{"value":"ContactListHeaderStyle","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactListHeaderStyle\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactListHeaderStyle\/fragments","op":"replace","value":[{"kind":"identifier","text":"ContactListHeaderStyle"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactListHeaderStyle\/navigatorTitle","value":[{"text":"ContactListHeaderStyle","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactListHeaderStyle~1newChat\/title","value":"ContactListHeaderStyleNewChat","op":"replace"},{"op":"replace","value":[{"text":"ContactListHeaderStyleNewChat","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactListHeaderStyle~1newChat\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}