{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/contactserviceimplement\/contactserviceprotocol-implementations"]},{"paths":["\/documentation\/shengwangchatuikit\/contactserviceimplement\/contactserviceprotocol-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"role":"collectionGroup","roleHeading":"API Collection","title":"ContactServiceProtocol Implementations","modules":[{"name":"ShengwangChatUIKit"}]},"kind":"article","topicSections":[{"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactServiceImplement\/addContact(userId:invitation:completion:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactServiceImplement\/addUserToBlackList(userId:completion:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactServiceImplement\/agreeFriendRequest(from:completion:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactServiceImplement\/bindContactEventListener(listener:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactServiceImplement\/contacts(completion:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactServiceImplement\/declineFriendRequest(from:completion:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactServiceImplement\/deviceIdsOnOtherPlatformOfCurrentUser(completion:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactServiceImplement\/registerEmergencyListener(listener:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactServiceImplement\/removeContact(userId:removeChannel:completion:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactServiceImplement\/removeUserFromBlackList(userId:completion:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactServiceImplement\/setRemark(userId:remark:completion:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactServiceImplement\/unbindContactEventListener(listener:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactServiceImplement\/unregisterEmergencyListener(listener:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactServiceImplement\/userBlackList(completion:)"],"anchor":"Instance-Methods","generated":true,"title":"Instance Methods"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactServiceImplement"]]},"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactServiceImplement\/ContactServiceProtocol-Implementations","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ContactServiceImplement/addUserToBlackList(userId:completion:)":{"role":"symbol","title":"addUserToBlackList(userId:completion:)","type":"topic","url":"\/documentation\/shengwangchatuikit\/contactserviceimplement\/addusertoblacklist(userid:completion:)","abstract":[{"text":"Add user to black list.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"addUserToBlackListWithUserId:completion:"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactServiceImplement\/addUserToBlackList(userId:completion:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"addUserToBlackList","kind":"identifier"},{"text":"(","kind":"text"},{"text":"userId","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"text":"ChatError","kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit0B5Errora"},{"text":"?, ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":") -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ContactServiceImplement/agreeFriendRequest(from:completion:)":{"abstract":[{"text":"Agree friend request.","type":"text"}],"title":"agreeFriendRequest(from:completion:)","type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactServiceImplement\/agreeFriendRequest(from:completion:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"agreeFriendRequest"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"from"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"text":"ChatError","preciseIdentifier":"s:18ShengwangChatUIKit0B5Errora","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/shengwangchatuikit\/contactserviceimplement\/agreefriendrequest(from:completion:)","navigatorTitle":[{"text":"agreeFriendRequestFrom:completion:","kind":"identifier"}],"role":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ContactServiceImplement/userBlackList(completion:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"userBlackList","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": (","kind":"text"},{"kind":"typeIdentifier","text":"ChatError","preciseIdentifier":"s:18ShengwangChatUIKit0B5Errora"},{"kind":"text","text":"?, ["},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"]) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"kind":"text","text":")"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactServiceImplement\/userBlackList(completion:)","title":"userBlackList(completion:)","navigatorTitle":[{"text":"userBlackListWithCompletion:","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/contactserviceimplement\/userblacklist(completion:)","abstract":[{"type":"text","text":"Get friend blacklist list"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ContactServiceImplement":{"title":"ContactServiceImplement","abstract":[],"url":"\/documentation\/shengwangchatuikit\/contactserviceimplement","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ContactServiceImplement","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ContactServiceImplement"}],"role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactServiceImplement"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ContactServiceImplement/contacts(completion:)":{"title":"contacts(completion:)","abstract":[{"text":"Fetch contacts form server.","type":"text"}],"url":"\/documentation\/shengwangchatuikit\/contactserviceimplement\/contacts(completion:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"contacts","kind":"identifier"},{"kind":"text","text":"("},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"ChatError","kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit0B5Errora"},{"text":"?, [","kind":"text"},{"kind":"typeIdentifier","text":"Contact","preciseIdentifier":"s:18ShengwangChatUIKit7Contacta"},{"kind":"text","text":"]) -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"kind":"symbol","navigatorTitle":[{"text":"contactsWithCompletion:","kind":"identifier"}],"role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactServiceImplement\/contacts(completion:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ContactServiceImplement/unregisterEmergencyListener(listener:)":{"abstract":[{"type":"text","text":"Unregister emergency listener"}],"type":"topic","title":"unregisterEmergencyListener(listener:)","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactServiceImplement\/unregisterEmergencyListener(listener:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"unregisterEmergencyListener","kind":"identifier"},{"text":"(","kind":"text"},{"text":"listener","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ContactEmergencyListener","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(pl)ContactEmergencyListener"},{"text":")","kind":"text"}],"url":"\/documentation\/shengwangchatuikit\/contactserviceimplement\/unregisteremergencylistener(listener:)","navigatorTitle":[{"kind":"identifier","text":"unregisterEmergencyListenerWithListener:"}],"role":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ContactServiceImplement/unbindContactEventListener(listener:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"unbindContactEventListener"},{"text":"(","kind":"text"},{"text":"listener","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(pl)ContactEventsResponse","text":"ContactEventsResponse"},{"text":")","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactServiceImplement\/unbindContactEventListener(listener:)","title":"unbindContactEventListener(listener:)","navigatorTitle":[{"text":"unbindContactEventListenerWithListener:","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/contactserviceimplement\/unbindcontacteventlistener(listener:)","abstract":[{"type":"text","text":"Unbind contacts state changed listener"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ContactServiceImplement/deviceIdsOnOtherPlatformOfCurrentUser(completion:)":{"title":"deviceIdsOnOtherPlatformOfCurrentUser(completion:)","role":"symbol","navigatorTitle":[{"text":"deviceIdsOnOtherPlatformOfCurrentUserWithCompletion:","kind":"identifier"}],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"deviceIdsOnOtherPlatformOfCurrentUser"},{"text":"(","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"kind":"typeIdentifier","text":"ChatError","preciseIdentifier":"s:18ShengwangChatUIKit0B5Errora"},{"kind":"text","text":"?, ["},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"]) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"kind":"symbol","abstract":[{"type":"text","text":"Get the device ID array of all current user logins except the current device."}],"url":"\/documentation\/shengwangchatuikit\/contactserviceimplement\/deviceidsonotherplatformofcurrentuser(completion:)","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactServiceImplement\/deviceIdsOnOtherPlatformOfCurrentUser(completion:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ContactServiceImplement/registerEmergencyListener(listener:)":{"type":"topic","role":"symbol","title":"registerEmergencyListener(listener:)","kind":"symbol","abstract":[{"type":"text","text":"Register emergency listener"}],"navigatorTitle":[{"kind":"identifier","text":"registerEmergencyListenerWithListener:"}],"url":"\/documentation\/shengwangchatuikit\/contactserviceimplement\/registeremergencylistener(listener:)","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactServiceImplement\/registerEmergencyListener(listener:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"registerEmergencyListener","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"listener"},{"text":": ","kind":"text"},{"text":"ContactEmergencyListener","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(pl)ContactEmergencyListener","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ContactServiceImplement/removeContact(userId:removeChannel:completion:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"removeContact","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"userId"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"removeChannel","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": ("},{"preciseIdentifier":"s:18ShengwangChatUIKit0B5Errora","text":"ChatError","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactServiceImplement\/removeContact(userId:removeChannel:completion:)","title":"removeContact(userId:removeChannel:completion:)","navigatorTitle":[{"text":"removeContactWithUserId:removeChannel:completion:","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/contactserviceimplement\/removecontact(userid:removechannel:completion:)","abstract":[{"type":"text","text":"Remove contact."}],"type":"topic","kind":"symbol","role":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ContactServiceImplement/addContact(userId:invitation:completion:)":{"navigatorTitle":[{"text":"addContactWithUserId:invitation:completion:","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/contactserviceimplement\/addcontact(userid:invitation:completion:)","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactServiceImplement\/addContact(userId:invitation:completion:)","abstract":[{"text":"Add contact.","type":"text"}],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"addContact"},{"text":"(","kind":"text"},{"text":"userId","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"invitation"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit0B5Errora","text":"ChatError"},{"kind":"text","text":"?, "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"kind":"text","text":")"}],"title":"addContact(userId:invitation:completion:)","type":"topic"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ContactServiceImplement/bindContactEventListener(listener:)":{"role":"symbol","title":"bindContactEventListener(listener:)","type":"topic","url":"\/documentation\/shengwangchatuikit\/contactserviceimplement\/bindcontacteventlistener(listener:)","abstract":[{"type":"text","text":"Bind contacts changed listener"}],"navigatorTitle":[{"text":"bindContactEventListenerWithListener:","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactServiceImplement\/bindContactEventListener(listener:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"bindContactEventListener","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"listener"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(pl)ContactEventsResponse","text":"ContactEventsResponse"},{"text":")","kind":"text"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ContactServiceImplement/declineFriendRequest(from:completion:)":{"role":"symbol","kind":"symbol","abstract":[{"text":"Decline friend request.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactServiceImplement\/declineFriendRequest(from:completion:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"declineFriendRequest"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"ChatError","kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit0B5Errora"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"declineFriendRequestFrom:completion:"}],"type":"topic","url":"\/documentation\/shengwangchatuikit\/contactserviceimplement\/declinefriendrequest(from:completion:)","title":"declineFriendRequest(from:completion:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ContactServiceImplement/setRemark(userId:remark:completion:)":{"role":"symbol","title":"setRemark(userId:remark:completion:)","type":"topic","url":"\/documentation\/shengwangchatuikit\/contactserviceimplement\/setremark(userid:remark:completion:)","abstract":[{"type":"text","text":"Set remark to the friend."}],"navigatorTitle":[{"text":"setRemarkWithUserId:remark:completion:","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactServiceImplement\/setRemark(userId:remark:completion:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"setRemark","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"userId"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"remark","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": ("},{"preciseIdentifier":"s:18ShengwangChatUIKit0B5Errora","text":"ChatError","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"Contact","preciseIdentifier":"s:18ShengwangChatUIKit7Contacta","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ContactServiceImplement/removeUserFromBlackList(userId:completion:)":{"role":"symbol","kind":"symbol","abstract":[{"text":"Remove user from black list.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactServiceImplement\/removeUserFromBlackList(userId:completion:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"removeUserFromBlackList","kind":"identifier"},{"kind":"text","text":"("},{"text":"userId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": (","kind":"text"},{"text":"ChatError","kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit0B5Errora"},{"text":"?, ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"removeUserFromBlackListWithUserId:completion:","kind":"identifier"}],"type":"topic","url":"\/documentation\/shengwangchatuikit\/contactserviceimplement\/removeuserfromblacklist(userid:completion:)","title":"removeUserFromBlackList(userId:completion:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":[{"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactServiceImplement\/addContact(userId:invitation:completion:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactServiceImplement\/addUserToBlackList(userId:completion:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactServiceImplement\/agreeFriendRequest(from:completion:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactServiceImplement\/bindContactEventListener(listener:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactServiceImplement\/contacts(completion:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactServiceImplement\/declineFriendRequest(from:completion:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactServiceImplement\/deviceIdsOnOtherPlatformOfCurrentUser(completion:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactServiceImplement\/registerEmergencyListener(listener:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactServiceImplement\/removeContact(userId:removeChannel:completion:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactServiceImplement\/removeUserFromBlackList(userId:completion:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactServiceImplement\/setRemark(userId:remark:completion:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactServiceImplement\/unbindContactEventListener(listener:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactServiceImplement\/unregisterEmergencyListener(listener:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactServiceImplement\/userBlackList(completion:)"],"generated":true,"title":"Instance Methods","anchor":"Instance-Methods"}],"path":"\/topicSections","op":"replace"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactServiceImplement~1addUserToBlackList(userId:completion:)\/title","value":"addUserToBlackListWithUserId:completion:"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactServiceImplement~1addUserToBlackList(userId:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addUserToBlackListWithUserId:completion:"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactServiceImplement~1agreeFriendRequest(from:completion:)\/title","op":"replace","value":"agreeFriendRequestFrom:completion:"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactServiceImplement~1agreeFriendRequest(from:completion:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"agreeFriendRequestFrom:completion:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactServiceImplement~1userBlackList(completion:)\/title","op":"replace","value":"userBlackListWithCompletion:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactServiceImplement~1userBlackList(completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"userBlackListWithCompletion:"}]},{"value":"ContactServiceImplement","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactServiceImplement\/title"},{"value":[{"kind":"identifier","text":"ContactServiceImplement"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactServiceImplement\/fragments"},{"op":"replace","value":[{"text":"ContactServiceImplement","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactServiceImplement\/navigatorTitle"},{"op":"replace","value":"contactsWithCompletion:","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactServiceImplement~1contacts(completion:)\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"contactsWithCompletion:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactServiceImplement~1contacts(completion:)\/fragments"},{"value":"unregisterEmergencyListenerWithListener:","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactServiceImplement~1unregisterEmergencyListener(listener:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactServiceImplement~1unregisterEmergencyListener(listener:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"unregisterEmergencyListenerWithListener:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactServiceImplement~1unbindContactEventListener(listener:)\/title","value":"unbindContactEventListenerWithListener:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"unbindContactEventListenerWithListener:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactServiceImplement~1unbindContactEventListener(listener:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactServiceImplement~1deviceIdsOnOtherPlatformOfCurrentUser(completion:)\/title","value":"deviceIdsOnOtherPlatformOfCurrentUserWithCompletion:"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactServiceImplement~1deviceIdsOnOtherPlatformOfCurrentUser(completion:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"deviceIdsOnOtherPlatformOfCurrentUserWithCompletion:"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactServiceImplement~1registerEmergencyListener(listener:)\/title","op":"replace","value":"registerEmergencyListenerWithListener:"},{"value":[{"kind":"text","text":"- "},{"text":"registerEmergencyListenerWithListener:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactServiceImplement~1registerEmergencyListener(listener:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactServiceImplement~1removeContact(userId:removeChannel:completion:)\/title","value":"removeContactWithUserId:removeChannel:completion:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"removeContactWithUserId:removeChannel:completion:"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactServiceImplement~1removeContact(userId:removeChannel:completion:)\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactServiceImplement~1addContact(userId:invitation:completion:)\/title","op":"replace","value":"addContactWithUserId:invitation:completion:"},{"value":[{"text":"- ","kind":"text"},{"text":"addContactWithUserId:invitation:completion:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactServiceImplement~1addContact(userId:invitation:completion:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactServiceImplement~1bindContactEventListener(listener:)\/title","value":"bindContactEventListenerWithListener:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactServiceImplement~1bindContactEventListener(listener:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"bindContactEventListenerWithListener:"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactServiceImplement~1declineFriendRequest(from:completion:)\/title","value":"declineFriendRequestFrom:completion:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactServiceImplement~1declineFriendRequest(from:completion:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"declineFriendRequestFrom:completion:"}]},{"op":"replace","value":"setRemarkWithUserId:remark:completion:","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactServiceImplement~1setRemark(userId:remark:completion:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactServiceImplement~1setRemark(userId:remark:completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"setRemarkWithUserId:remark:completion:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactServiceImplement~1removeUserFromBlackList(userId:completion:)\/title","value":"removeUserFromBlackListWithUserId:completion:"},{"value":[{"text":"- ","kind":"text"},{"text":"removeUserFromBlackListWithUserId:completion:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactServiceImplement~1removeUserFromBlackList(userId:completion:)\/fragments"}]}]}