{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactServiceImplement","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactServiceImplement\/AgoraChatContactManagerDelegate-Implementations"]]},"metadata":{"roleHeading":"Instance Method","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"friendRequestDidApproveByUser:"}],"extendedModule":"ShengwangChatUIKit","externalID":"c:@CM@ShengwangChatUIKit@objc(cs)ContactServiceImplement(im)friendRequestDidApproveByUser:","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"friendRequestDidApprove","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"byUser"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"friendRequestDidApprove(byUser:)","modules":[{"name":"ShengwangChatUIKit"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactServiceImplement\/friendRequestDidApprove(byUser:)"},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"friendRequestDidApprove"},{"text":"(","kind":"text"},{"text":"byUser","kind":"externalParam"},{"kind":"text","text":" "},{"text":"aUsername","kind":"internalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"abstract":[{"text":"Inherited from ","type":"text"},{"code":"AgoraChatContactManagerDelegate.friendRequestDidApprove(byUser:)","type":"codeVoice"},{"type":"text","text":"."}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/contactserviceimplement\/friendrequestdidapprove(byuser:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/contactserviceimplement\/friendrequestdidapprove(byuser:)"]}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ContactServiceImplement/friendRequestDidApprove(byUser:)":{"navigatorTitle":[{"kind":"identifier","text":"friendRequestDidApproveByUser:"}],"abstract":[],"role":"symbol","url":"\/documentation\/shengwangchatuikit\/contactserviceimplement\/friendrequestdidapprove(byuser:)","title":"friendRequestDidApprove(byUser:)","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactServiceImplement\/friendRequestDidApprove(byUser:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"friendRequestDidApprove","kind":"identifier"},{"kind":"text","text":"("},{"text":"byUser","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"kind":"symbol","type":"topic"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ContactServiceImplement":{"title":"ContactServiceImplement","abstract":[],"url":"\/documentation\/shengwangchatuikit\/contactserviceimplement","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ContactServiceImplement","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ContactServiceImplement"}],"role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactServiceImplement"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ContactServiceImplement/AgoraChatContactManagerDelegate-Implementations":{"abstract":[],"role":"collectionGroup","kind":"article","type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactServiceImplement\/AgoraChatContactManagerDelegate-Implementations","title":"AgoraChatContactManagerDelegate Implementations","url":"\/documentation\/shengwangchatuikit\/contactserviceimplement\/agorachatcontactmanagerdelegate-implementations"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"friendRequestDidApproveByUser:","path":"\/metadata\/title","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"friendRequestDidApproveByUser:"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"friendRequestDidApproveByUser:"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"aUsername","kind":"internalParam"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"friendRequestDidApproveByUser:","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactServiceImplement~1friendRequestDidApprove(byUser:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactServiceImplement~1friendRequestDidApprove(byUser:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"friendRequestDidApproveByUser:"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactServiceImplement\/title","value":"ContactServiceImplement","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactServiceImplement\/fragments","value":[{"text":"ContactServiceImplement","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactServiceImplement\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"ContactServiceImplement"}]}]}]}