{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactServiceImplement","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactServiceImplement\/ContactServiceProtocol-Implementations"]]},"sections":[],"metadata":{"symbolKind":"method","navigatorTitle":[{"text":"unregisterEmergencyListenerWithListener:","kind":"identifier"}],"externalID":"c:@CM@ShengwangChatUIKit@objc(cs)ContactServiceImplement(im)unregisterEmergencyListenerWithListener:","title":"unregisterEmergencyListener(listener:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"unregisterEmergencyListener","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"listener"},{"text":": ","kind":"text"},{"text":"ContactEmergencyListener","kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(pl)ContactEmergencyListener"},{"text":")","kind":"text"}],"role":"symbol","modules":[{"name":"ShengwangChatUIKit"}],"extendedModule":"ShengwangChatUIKit","roleHeading":"Instance Method"},"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"type":"text","text":"Unregister emergency listener"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/contactserviceimplement\/unregisteremergencylistener(listener:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/contactserviceimplement\/unregisteremergencylistener(listener:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"unregisterEmergencyListener","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"listener"},{"kind":"text","text":": "},{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactEmergencyListener","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(pl)ContactEmergencyListener","kind":"typeIdentifier","text":"ContactEmergencyListener"},{"text":")","kind":"text"}]}]},{"kind":"parameters","parameters":[{"name":"listener","content":[{"inlineContent":[{"type":"text","text":""},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactEmergencyListener"}],"type":"paragraph"}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactServiceImplement\/unregisterEmergencyListener(listener:)"},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ContactServiceImplement/ContactServiceProtocol-Implementations":{"role":"collectionGroup","type":"topic","url":"\/documentation\/shengwangchatuikit\/contactserviceimplement\/contactserviceprotocol-implementations","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactServiceImplement\/ContactServiceProtocol-Implementations","title":"ContactServiceProtocol Implementations","abstract":[],"kind":"article"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ContactServiceImplement":{"title":"ContactServiceImplement","abstract":[],"url":"\/documentation\/shengwangchatuikit\/contactserviceimplement","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ContactServiceImplement","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ContactServiceImplement"}],"role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactServiceImplement"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ContactEmergencyListener":{"navigatorTitle":[{"kind":"identifier","text":"ContactEmergencyListener"}],"abstract":[],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ContactEmergencyListener"}],"type":"topic","url":"\/documentation\/shengwangchatuikit\/contactemergencylistener","kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactEmergencyListener","title":"ContactEmergencyListener"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ContactServiceImplement/unregisterEmergencyListener(listener:)":{"abstract":[{"type":"text","text":"Unregister emergency listener"}],"type":"topic","title":"unregisterEmergencyListener(listener:)","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactServiceImplement\/unregisterEmergencyListener(listener:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"unregisterEmergencyListener","kind":"identifier"},{"text":"(","kind":"text"},{"text":"listener","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ContactEmergencyListener","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(pl)ContactEmergencyListener"},{"text":")","kind":"text"}],"url":"\/documentation\/shengwangchatuikit\/contactserviceimplement\/unregisteremergencylistener(listener:)","navigatorTitle":[{"kind":"identifier","text":"unregisterEmergencyListenerWithListener:"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"unregisterEmergencyListenerWithListener:","op":"replace"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"unregisterEmergencyListenerWithListener:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"unregisterEmergencyListenerWithListener:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@ShengwangChatUIKit@objc(pl)ContactEmergencyListener","text":"id<ContactEmergencyListener>"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"listener"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactServiceImplement\/title","value":"ContactServiceImplement","op":"replace"},{"op":"replace","value":[{"text":"ContactServiceImplement","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactServiceImplement\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactServiceImplement\/navigatorTitle","op":"replace","value":[{"text":"ContactServiceImplement","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactEmergencyListener\/title","value":"ContactEmergencyListener","op":"replace"},{"value":[{"text":"ContactEmergencyListener","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactEmergencyListener\/fragments"},{"value":[{"text":"ContactEmergencyListener","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactEmergencyListener\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactServiceImplement~1unregisterEmergencyListener(listener:)\/title","value":"unregisterEmergencyListenerWithListener:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactServiceImplement~1unregisterEmergencyListener(listener:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"unregisterEmergencyListenerWithListener:","kind":"identifier"}]}]}]}