{"sections":[],"abstract":[{"type":"text","text":"Opens the audio dialog for recording and sending voice messages."}],"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewController\/audioDialog()","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewController"]]},"metadata":{"roleHeading":"Instance Method","role":"symbol","symbolKind":"method","extendedModule":"ShengwangChatUIKit","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"audioDialog"},{"text":"()","kind":"text"}],"externalID":"c:@CM@ShengwangChatUIKit@objc(cs)ChatThreadViewController(im)audioDialog","title":"audioDialog()","navigatorTitle":[{"text":"audioDialog","kind":"identifier"}],"modules":[{"name":"ShengwangChatUIKit"}]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"@","kind":"attribute"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"audioDialog","kind":"identifier"},{"text":"()","kind":"text"}]}],"kind":"declarations"},{"kind":"content","content":[{"type":"heading","anchor":"discussion","text":"Discussion","level":2},{"type":"paragraph","inlineContent":[{"text":"This method stops any currently playing audio, presents a custom audio recording view, and sends the recorded audio message using the view model’s ","type":"text"},{"code":"sendMessage","type":"codeVoice"},{"text":" method.","type":"text"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The audio recording view is an instance of "},{"type":"codeVoice","code":"MessageAudioRecordView"},{"type":"text","text":" and is presented as a custom dialog using "},{"type":"codeVoice","code":"DialogManager.shared.showCustomDialog"},{"type":"text","text":"."}]}],"style":"note","name":"Note","type":"aside"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The recorded audio message is sent as a text message with the file path of the recorded audio and the duration of the recording as extension information."}]}],"type":"aside","name":"Note","style":"note"}]}],"variants":[{"paths":["\/documentation\/shengwangchatuikit\/chatthreadviewcontroller\/audiodialog()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/chatthreadviewcontroller\/audiodialog()"]}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatThreadViewController":{"url":"\/documentation\/shengwangchatuikit\/chatthreadviewcontroller","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ChatThreadViewController"}],"abstract":[],"role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewController","title":"ChatThreadViewController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChatThreadViewController","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatThreadViewController/audioDialog()":{"kind":"symbol","url":"\/documentation\/shengwangchatuikit\/chatthreadviewcontroller\/audiodialog()","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"audioDialog","kind":"identifier"},{"text":"()","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewController\/audioDialog()","title":"audioDialog()","navigatorTitle":[{"text":"audioDialog","kind":"identifier"}],"abstract":[{"type":"text","text":"Opens the audio dialog for recording and sending voice messages."}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"audioDialog","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"audioDialog","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"audioDialog","kind":"identifier"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"value":"ChatThreadViewController","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadViewController\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadViewController\/fragments","value":[{"text":"ChatThreadViewController","kind":"identifier"}]},{"value":[{"text":"ChatThreadViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadViewController\/navigatorTitle"},{"op":"replace","value":"audioDialog","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadViewController~1audioDialog()\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadViewController~1audioDialog()\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"audioDialog","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}