{"metadata":{"symbolKind":"method","navigatorTitle":[{"text":"filterActions","kind":"identifier"}],"role":"symbol","modules":[{"name":"ShengwangChatUIKit"}],"roleHeading":"Instance Method","externalID":"c:@CM@ShengwangChatUIKit@objc(cs)ChatThreadViewController(im)filterActions","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"filterActions"},{"text":"() -> [","kind":"text"},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(pl)ActionSheetItemProtocol","kind":"typeIdentifier","text":"ActionSheetItemProtocol"},{"kind":"text","text":"]"}],"extendedModule":"ShengwangChatUIKit","title":"filterActions()"},"sections":[],"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewController\/filterActions()","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/shengwangchatuikit\/chatthreadviewcontroller\/filteractions()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/chatthreadviewcontroller\/filteractions()"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewController"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","kind":"attribute","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"filterActions"},{"kind":"text","text":"() -> ["},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(pl)ActionSheetItemProtocol","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ActionSheetItemProtocol","text":"ActionSheetItemProtocol"},{"text":"]","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatThreadViewController/filterActions()":{"abstract":[],"title":"filterActions()","type":"topic","role":"symbol","url":"\/documentation\/shengwangchatuikit\/chatthreadviewcontroller\/filteractions()","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"filterActions"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewController\/filterActions()","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"filterActions","kind":"identifier"},{"text":"() -> [","kind":"text"},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(pl)ActionSheetItemProtocol","text":"ActionSheetItemProtocol","kind":"typeIdentifier"},{"text":"]","kind":"text"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatThreadViewController":{"url":"\/documentation\/shengwangchatuikit\/chatthreadviewcontroller","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ChatThreadViewController"}],"abstract":[],"role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewController","title":"ChatThreadViewController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChatThreadViewController","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ActionSheetItemProtocol":{"navigatorTitle":[{"text":"ActionSheetItemProtocol","kind":"identifier"}],"abstract":[{"type":"text","text":"A protocol that defines properties and methods for an action sheet item."}],"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ActionSheetItemProtocol"}],"url":"\/documentation\/shengwangchatuikit\/actionsheetitemprotocol","role":"symbol","title":"ActionSheetItemProtocol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ActionSheetItemProtocol","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"filterActions","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"filterActions","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"NSArray<id<ActionSheetItemProtocol>>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"filterActions"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadViewController~1filterActions()\/title","op":"replace","value":"filterActions"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadViewController~1filterActions()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"filterActions","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"ChatThreadViewController","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadViewController\/title"},{"value":[{"kind":"identifier","text":"ChatThreadViewController"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadViewController\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadViewController\/navigatorTitle","value":[{"kind":"identifier","text":"ChatThreadViewController"}]},{"op":"replace","value":"ActionSheetItemProtocol","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ActionSheetItemProtocol\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ActionSheetItemProtocol\/fragments","value":[{"text":"ActionSheetItemProtocol","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"ActionSheetItemProtocol"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ActionSheetItemProtocol\/navigatorTitle"}]}]}