{"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"leaveTopic","kind":"identifier"},{"text":"()","kind":"text"}],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/shengwangchatuikit\/chatthreadviewcontroller\/leavetopic()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/chatthreadviewcontroller\/leavetopic()"]}],"metadata":{"roleHeading":"Instance Method","externalID":"c:@CM@ShengwangChatUIKit@objc(cs)ChatThreadViewController(im)leaveTopic","symbolKind":"method","role":"symbol","modules":[{"name":"ShengwangChatUIKit"}],"extendedModule":"ShengwangChatUIKit","navigatorTitle":[{"kind":"identifier","text":"leaveTopic"}],"title":"leaveTopic()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"leaveTopic","kind":"identifier"},{"text":"()","kind":"text"}]},"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewController"]]},"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewController\/leaveTopic()","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatThreadViewController":{"url":"\/documentation\/shengwangchatuikit\/chatthreadviewcontroller","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ChatThreadViewController"}],"abstract":[],"role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewController","title":"ChatThreadViewController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChatThreadViewController","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatThreadViewController/leaveTopic()":{"title":"leaveTopic()","type":"topic","url":"\/documentation\/shengwangchatuikit\/chatthreadviewcontroller\/leavetopic()","kind":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewController\/leaveTopic()","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"leaveTopic","kind":"identifier"},{"text":"()","kind":"text"}],"navigatorTitle":[{"text":"leaveTopic","kind":"identifier"}],"role":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"leaveTopic"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"leaveTopic"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"leaveTopic"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":"ChatThreadViewController","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadViewController\/title"},{"op":"replace","value":[{"text":"ChatThreadViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadViewController\/fragments"},{"value":[{"kind":"identifier","text":"ChatThreadViewController"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadViewController\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadViewController~1leaveTopic()\/title","value":"leaveTopic"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadViewController~1leaveTopic()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"leaveTopic","kind":"identifier"}]}]}]}