{"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"article","identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewController\/MessageListDriverEventsListener-Implementations","interfaceLanguage":"swift"},"topicSections":[{"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewController\/onChatThreadUpdated(chatThread:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewController\/onInputBoxEventsOccur(action:attributeText:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewController\/onMessageAttachmentLoading(loading:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewController\/onMessageAvatarClicked(user:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewController\/onMessageBubbleClicked(message:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewController\/onMessageBubbleLongPressed(cell:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewController\/onMessageMoreReactionAreaClicked(entity:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewController\/onMessageMultiSelectBarClicked(operation:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewController\/onMessageTopicAreaClicked(entity:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewController\/onMessageWillSendFillExtensionInfo()","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewController\/onUserQuitTopic()"],"title":"Instance Methods","generated":true,"anchor":"Instance-Methods"}],"sections":[],"metadata":{"title":"MessageListDriverEventsListener Implementations","role":"collectionGroup","modules":[{"name":"ShengwangChatUIKit"}],"roleHeading":"API Collection"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewController"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/chatthreadviewcontroller\/messagelistdrivereventslistener-implementations"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/chatthreadviewcontroller\/messagelistdrivereventslistener-implementations"]}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatThreadViewController/onUserQuitTopic()":{"url":"\/documentation\/shengwangchatuikit\/chatthreadviewcontroller\/onuserquittopic()","abstract":[{"text":"When received quit signal form other device on the chat thread.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"onUserQuitTopic","kind":"identifier"}],"type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewController\/onUserQuitTopic()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onUserQuitTopic","kind":"identifier"},{"text":"()","kind":"text"}],"title":"onUserQuitTopic()"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatThreadViewController/onChatThreadUpdated(chatThread:)":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewController\/onChatThreadUpdated(chatThread:)","url":"\/documentation\/shengwangchatuikit\/chatthreadviewcontroller\/onchatthreadupdated(chatthread:)","kind":"symbol","navigatorTitle":[{"text":"onChatThreadUpdatedWithChatThread:","kind":"identifier"}],"role":"symbol","abstract":[{"text":"You can update chat thread on the method called.","type":"text"}],"title":"onChatThreadUpdated(chatThread:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onChatThreadUpdated","kind":"identifier"},{"text":"(","kind":"text"},{"text":"chatThread","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:18ShengwangChatUIKit05GroupB6Threada","text":"GroupChatThread","kind":"typeIdentifier"},{"kind":"text","text":")"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatThreadViewController/onMessageAttachmentLoading(loading:)":{"url":"\/documentation\/shengwangchatuikit\/chatthreadviewcontroller\/onmessageattachmentloading(loading:)","abstract":[{"type":"text","text":"When you click a attachment message,we’ll download the attachment,the method also called."}],"kind":"symbol","navigatorTitle":[{"text":"onMessageAttachmentLoadingWithLoading:","kind":"identifier"}],"type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewController\/onMessageAttachmentLoading(loading:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onMessageAttachmentLoading","kind":"identifier"},{"text":"(","kind":"text"},{"text":"loading","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"title":"onMessageAttachmentLoading(loading:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatThreadViewController/onMessageMoreReactionAreaClicked(entity:)":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewController\/onMessageMoreReactionAreaClicked(entity:)","url":"\/documentation\/shengwangchatuikit\/chatthreadviewcontroller\/onmessagemorereactionareaclicked(entity:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"onMessageMoreReactionAreaClickedWithEntity:"}],"role":"symbol","abstract":[{"text":"When you click a message’s reaction ,the method will call.","type":"text"}],"title":"onMessageMoreReactionAreaClicked(entity:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onMessageMoreReactionAreaClicked","kind":"identifier"},{"text":"(","kind":"text"},{"text":"entity","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)MessageEntity","text":"MessageEntity","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatThreadViewController/onMessageTopicAreaClicked(entity:)":{"url":"\/documentation\/shengwangchatuikit\/chatthreadviewcontroller\/onmessagetopicareaclicked(entity:)","abstract":[{"text":"When you click a message’s topic area ,the method will call.","type":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"onMessageTopicAreaClickedWithEntity:"}],"type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewController\/onMessageTopicAreaClicked(entity:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onMessageTopicAreaClicked","kind":"identifier"},{"text":"(","kind":"text"},{"text":"entity","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MessageEntity","kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)MessageEntity"},{"text":")","kind":"text"}],"title":"onMessageTopicAreaClicked(entity:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatThreadViewController/onMessageBubbleClicked(message:)":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewController\/onMessageBubbleClicked(message:)","url":"\/documentation\/shengwangchatuikit\/chatthreadviewcontroller\/onmessagebubbleclicked(message:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"onMessageBubbleClickedWithMessage:"}],"role":"symbol","abstract":[],"title":"onMessageBubbleClicked(message:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onMessageBubbleClicked","kind":"identifier"},{"text":"(","kind":"text"},{"text":"message","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)MessageEntity","text":"MessageEntity","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatThreadViewController/onMessageWillSendFillExtensionInfo()":{"url":"\/documentation\/shengwangchatuikit\/chatthreadviewcontroller\/onmessagewillsendfillextensioninfo()","abstract":[{"type":"text","text":"Insert extension info before sending message."}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"onMessageWillSendFillExtensionInfo"}],"type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewController\/onMessageWillSendFillExtensionInfo()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onMessageWillSendFillExtensionInfo","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:SD","text":"Dictionary","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"Any","kind":"keyword"},{"kind":"text","text":">"}],"title":"onMessageWillSendFillExtensionInfo()"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatThreadViewController/onInputBoxEventsOccur(action:attributeText:)":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewController\/onInputBoxEventsOccur(action:attributeText:)","url":"\/documentation\/shengwangchatuikit\/chatthreadviewcontroller\/oninputboxeventsoccur(action:attributetext:)","kind":"symbol","navigatorTitle":[{"text":"onInputBoxEventsOccurWithAction:attributeText:","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"The method will call on input menu bar actioned."}],"title":"onInputBoxEventsOccur(action:attributeText:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"onInputBoxEventsOccur","kind":"identifier"},{"text":"(","kind":"text"},{"text":"action","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@E@MessageInputBarActionType","text":"MessageInputBarActionType","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"attributeText","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSAttributedString","text":"NSAttributedString","kind":"typeIdentifier"},{"kind":"text","text":"?)"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatThreadViewController":{"url":"\/documentation\/shengwangchatuikit\/chatthreadviewcontroller","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ChatThreadViewController"}],"abstract":[],"role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewController","title":"ChatThreadViewController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChatThreadViewController","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatThreadViewController/onMessageMultiSelectBarClicked(operation:)":{"type":"topic","abstract":[{"type":"text","text":"When you click a message list multi select bar item,the method will call."}],"kind":"symbol","url":"\/documentation\/shengwangchatuikit\/chatthreadviewcontroller\/onmessagemultiselectbarclicked(operation:)","title":"onMessageMultiSelectBarClicked(operation:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"onMessageMultiSelectBarClicked"},{"kind":"text","text":"("},{"kind":"externalParam","text":"operation"},{"kind":"text","text":": "},{"text":"MessageMultiSelectedBottomBarOperation","kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@E@MessageMultiSelectedBottomBarOperation"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"onMessageMultiSelectBarClickedWithOperation:"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewController\/onMessageMultiSelectBarClicked(operation:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatThreadViewController/onMessageAvatarClicked(user:)":{"url":"\/documentation\/shengwangchatuikit\/chatthreadviewcontroller\/onmessageavatarclicked(user:)","abstract":[],"kind":"symbol","navigatorTitle":[{"text":"onMessageAvatarClickedWithUser:","kind":"identifier"}],"type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewController\/onMessageAvatarClicked(user:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onMessageAvatarClicked"},{"text":"(","kind":"text"},{"text":"user","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(pl)ChatUserProfileProtocol","text":"ChatUserProfileProtocol","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"onMessageAvatarClicked(user:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatThreadViewController/onMessageBubbleLongPressed(cell:)":{"url":"\/documentation\/shengwangchatuikit\/chatthreadviewcontroller\/onmessagebubblelongpressed(cell:)","type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewController\/onMessageBubbleLongPressed(cell:)","kind":"symbol","navigatorTitle":[{"text":"onMessageBubbleLongPressedWithCell:","kind":"identifier"}],"role":"symbol","abstract":[],"title":"onMessageBubbleLongPressed(cell:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onMessageBubbleLongPressed","kind":"identifier"},{"text":"(","kind":"text"},{"text":"cell","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)MessageCell","text":"MessageCell","kind":"typeIdentifier"},{"kind":"text","text":")"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"anchor":"Instance-Methods","title":"Instance Methods","generated":true,"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewController\/onChatThreadUpdated(chatThread:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewController\/onInputBoxEventsOccur(action:attributeText:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewController\/onMessageAttachmentLoading(loading:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewController\/onMessageAvatarClicked(user:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewController\/onMessageBubbleClicked(message:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewController\/onMessageBubbleLongPressed(cell:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewController\/onMessageMoreReactionAreaClicked(entity:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewController\/onMessageMultiSelectBarClicked(operation:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewController\/onMessageTopicAreaClicked(entity:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewController\/onMessageWillSendFillExtensionInfo()","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewController\/onUserQuitTopic()"]}]},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadViewController~1onUserQuitTopic()\/title","value":"onUserQuitTopic","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadViewController~1onUserQuitTopic()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"onUserQuitTopic","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadViewController~1onChatThreadUpdated(chatThread:)\/title","value":"onChatThreadUpdatedWithChatThread:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"onChatThreadUpdatedWithChatThread:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadViewController~1onChatThreadUpdated(chatThread:)\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadViewController~1onMessageAttachmentLoading(loading:)\/title","value":"onMessageAttachmentLoadingWithLoading:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadViewController~1onMessageAttachmentLoading(loading:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"onMessageAttachmentLoadingWithLoading:","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadViewController~1onMessageMoreReactionAreaClicked(entity:)\/title","value":"onMessageMoreReactionAreaClickedWithEntity:"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadViewController~1onMessageMoreReactionAreaClicked(entity:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"onMessageMoreReactionAreaClickedWithEntity:"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadViewController~1onMessageTopicAreaClicked(entity:)\/title","value":"onMessageTopicAreaClickedWithEntity:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadViewController~1onMessageTopicAreaClicked(entity:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"onMessageTopicAreaClickedWithEntity:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadViewController~1onMessageBubbleClicked(message:)\/title","value":"onMessageBubbleClickedWithMessage:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"onMessageBubbleClickedWithMessage:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadViewController~1onMessageBubbleClicked(message:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadViewController~1onMessageWillSendFillExtensionInfo()\/title","op":"replace","value":"onMessageWillSendFillExtensionInfo"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadViewController~1onMessageWillSendFillExtensionInfo()\/fragments","value":[{"kind":"text","text":"- "},{"text":"onMessageWillSendFillExtensionInfo","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadViewController~1onInputBoxEventsOccur(action:attributeText:)\/title","value":"onInputBoxEventsOccurWithAction:attributeText:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadViewController~1onInputBoxEventsOccur(action:attributeText:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"onInputBoxEventsOccurWithAction:attributeText:","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadViewController\/title","value":"ChatThreadViewController"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadViewController\/fragments","value":[{"text":"ChatThreadViewController","kind":"identifier"}]},{"value":[{"text":"ChatThreadViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadViewController\/navigatorTitle"},{"value":"onMessageMultiSelectBarClickedWithOperation:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadViewController~1onMessageMultiSelectBarClicked(operation:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onMessageMultiSelectBarClickedWithOperation:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadViewController~1onMessageMultiSelectBarClicked(operation:)\/fragments"},{"op":"replace","value":"onMessageAvatarClickedWithUser:","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadViewController~1onMessageAvatarClicked(user:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"onMessageAvatarClickedWithUser:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadViewController~1onMessageAvatarClicked(user:)\/fragments"},{"value":"onMessageBubbleLongPressedWithCell:","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadViewController~1onMessageBubbleLongPressed(cell:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"onMessageBubbleLongPressedWithCell:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadViewController~1onMessageBubbleLongPressed(cell:)\/fragments"}]}]}