{"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewController\/navigationClick(type:indexPath:)","interfaceLanguage":"swift"},"metadata":{"externalID":"c:@CM@ShengwangChatUIKit@objc(cs)ChatThreadViewController(im)navigationClickWithType:indexPath:","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"navigationClickWithType:indexPath:"}],"role":"symbol","extendedModule":"ShengwangChatUIKit","modules":[{"name":"ShengwangChatUIKit"}],"title":"navigationClick(type:indexPath:)","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"navigationClick","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"type"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@E@ChatNavigationBarClickEvent","text":"ChatNavigationBarClickEvent"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"indexPath"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"text":"?)","kind":"text"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewController"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"navigationClick"},{"kind":"text","text":"("},{"text":"type","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ChatNavigationBarClickEvent","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatNavigationBarClickEvent","preciseIdentifier":"c:@M@ShengwangChatUIKit@E@ChatNavigationBarClickEvent","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"indexPath","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation9IndexPathV","text":"IndexPath","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"level":2,"anchor":"discussion","type":"heading","text":"Discussion"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"type: The type of navigation bar click event."}]}]},{"content":[{"inlineContent":[{"text":"indexPath: The index path associated with the event (optional).","type":"text"}],"type":"paragraph"}]}],"type":"unorderedList"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"Handles the navigation bar click events."}],"variants":[{"paths":["\/documentation\/shengwangchatuikit\/chatthreadviewcontroller\/navigationclick(type:indexpath:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/shengwangchatuikit\/chatthreadviewcontroller\/navigationclick(type:indexpath:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"kind":"symbol","references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatThreadViewController":{"url":"\/documentation\/shengwangchatuikit\/chatthreadviewcontroller","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ChatThreadViewController"}],"abstract":[],"role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewController","title":"ChatThreadViewController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChatThreadViewController","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatThreadViewController/navigationClick(type:indexPath:)":{"abstract":[{"text":"Handles the navigation bar click events.","type":"text"}],"title":"navigationClick(type:indexPath:)","type":"topic","role":"symbol","url":"\/documentation\/shengwangchatuikit\/chatthreadviewcontroller\/navigationclick(type:indexpath:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"navigationClickWithType:indexPath:"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewController\/navigationClick(type:indexPath:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"navigationClick","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"type"},{"text":": ","kind":"text"},{"text":"ChatNavigationBarClickEvent","preciseIdentifier":"c:@M@ShengwangChatUIKit@E@ChatNavigationBarClickEvent","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"indexPath","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation9IndexPathV","text":"IndexPath"},{"text":"?)","kind":"text"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatNavigationBarClickEvent":{"abstract":[],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatNavigationBarClickEvent","navigatorTitle":[{"kind":"identifier","text":"ChatNavigationBarClickEvent"}],"kind":"symbol","url":"\/documentation\/shengwangchatuikit\/chatnavigationbarclickevent","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatNavigationBarClickEvent"}],"title":"ChatNavigationBarClickEvent","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"navigationClickWithType:indexPath:","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"navigationClickWithType:indexPath:"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"navigationClickWithType:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatNavigationBarClickEvent","preciseIdentifier":"c:@M@ShengwangChatUIKit@E@ChatNavigationBarClickEvent","kind":"typeIdentifier","text":"ChatNavigationBarClickEvent"},{"kind":"text","text":") "},{"text":"type","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"indexPath:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSIndexPath","text":"NSIndexPath","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"indexPath"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"ChatThreadViewController","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadViewController\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadViewController\/fragments","value":[{"text":"ChatThreadViewController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadViewController\/navigatorTitle","value":[{"text":"ChatThreadViewController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadViewController~1navigationClick(type:indexPath:)\/title","op":"replace","value":"navigationClickWithType:indexPath:"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadViewController~1navigationClick(type:indexPath:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"navigationClickWithType:indexPath:"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatNavigationBarClickEvent\/title","value":"ChatNavigationBarClickEvent","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"ChatNavigationBarClickEvent"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatNavigationBarClickEvent\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatNavigationBarClickEvent\/navigatorTitle","value":[{"text":"ChatNavigationBarClickEvent","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}