{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"onInputBoxEventsOccur","kind":"identifier"},{"text":"(","kind":"text"},{"text":"action","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"type"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@E@MessageInputBarActionType","kind":"typeIdentifier","text":"MessageInputBarActionType","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageInputBarActionType"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"attributeText"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSAttributedString","preciseIdentifier":"c:objc(cs)NSAttributedString"},{"text":"?)","kind":"text"}]}]},{"parameters":[{"name":"type","content":[{"inlineContent":[{"type":"text","text":""},{"type":"reference","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageInputBarActionType","isActive":true}],"type":"paragraph"}]},{"name":"attributeText","content":[{"inlineContent":[{"text":"Text view’s attributeText","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"}],"kind":"symbol","metadata":{"modules":[{"name":"ShengwangChatUIKit"}],"extendedModule":"ShengwangChatUIKit","roleHeading":"Instance Method","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"onInputBoxEventsOccur"},{"kind":"text","text":"("},{"kind":"externalParam","text":"action"},{"kind":"text","text":": "},{"text":"MessageInputBarActionType","kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@E@MessageInputBarActionType"},{"text":", ","kind":"text"},{"text":"attributeText","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSAttributedString","text":"NSAttributedString"},{"kind":"text","text":"?)"}],"role":"symbol","navigatorTitle":[{"text":"onInputBoxEventsOccurWithAction:attributeText:","kind":"identifier"}],"externalID":"c:@CM@ShengwangChatUIKit@objc(cs)ChatThreadViewController(im)onInputBoxEventsOccurWithAction:attributeText:","title":"onInputBoxEventsOccur(action:attributeText:)"},"variants":[{"paths":["\/documentation\/shengwangchatuikit\/chatthreadviewcontroller\/oninputboxeventsoccur(action:attributetext:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/chatthreadviewcontroller\/oninputboxeventsoccur(action:attributetext:)"]}],"abstract":[{"type":"text","text":"The method will call on input menu bar actioned."}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewController","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewController\/MessageListDriverEventsListener-Implementations"]]},"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewController\/onInputBoxEventsOccur(action:attributeText:)","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatThreadViewController/MessageListDriverEventsListener-Implementations":{"url":"\/documentation\/shengwangchatuikit\/chatthreadviewcontroller\/messagelistdrivereventslistener-implementations","kind":"article","type":"topic","abstract":[],"role":"collectionGroup","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewController\/MessageListDriverEventsListener-Implementations","title":"MessageListDriverEventsListener Implementations"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatThreadViewController":{"url":"\/documentation\/shengwangchatuikit\/chatthreadviewcontroller","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ChatThreadViewController"}],"abstract":[],"role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewController","title":"ChatThreadViewController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChatThreadViewController","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageInputBarActionType":{"navigatorTitle":[{"kind":"identifier","text":"MessageInputBarActionType"}],"abstract":[{"text":"The types of actions that can be triggered by the input bar.","type":"text"}],"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"MessageInputBarActionType","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/messageinputbaractiontype","role":"symbol","title":"MessageInputBarActionType","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageInputBarActionType"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatThreadViewController/onInputBoxEventsOccur(action:attributeText:)":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewController\/onInputBoxEventsOccur(action:attributeText:)","url":"\/documentation\/shengwangchatuikit\/chatthreadviewcontroller\/oninputboxeventsoccur(action:attributetext:)","kind":"symbol","navigatorTitle":[{"text":"onInputBoxEventsOccurWithAction:attributeText:","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"The method will call on input menu bar actioned."}],"title":"onInputBoxEventsOccur(action:attributeText:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"onInputBoxEventsOccur","kind":"identifier"},{"text":"(","kind":"text"},{"text":"action","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@E@MessageInputBarActionType","text":"MessageInputBarActionType","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"attributeText","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSAttributedString","text":"NSAttributedString","kind":"typeIdentifier"},{"kind":"text","text":"?)"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"onInputBoxEventsOccurWithAction:attributeText:"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"text":"onInputBoxEventsOccurWithAction:attributeText:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"text":"onInputBoxEventsOccurWithAction:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@E@MessageInputBarActionType","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageInputBarActionType","text":"MessageInputBarActionType"},{"kind":"text","text":") "},{"kind":"internalParam","text":"type"},{"kind":"text","text":" "},{"text":"attributeText:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSAttributedString","kind":"typeIdentifier","text":"NSAttributedString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"attributeText"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadViewController\/title","value":"ChatThreadViewController","op":"replace"},{"value":[{"kind":"identifier","text":"ChatThreadViewController"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadViewController\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadViewController\/navigatorTitle","value":[{"kind":"identifier","text":"ChatThreadViewController"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageInputBarActionType\/title","value":"MessageInputBarActionType","op":"replace"},{"value":[{"text":"MessageInputBarActionType","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageInputBarActionType\/fragments","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"MessageInputBarActionType"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageInputBarActionType\/navigatorTitle"},{"value":"onInputBoxEventsOccurWithAction:attributeText:","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadViewController~1onInputBoxEventsOccur(action:attributeText:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"onInputBoxEventsOccurWithAction:attributeText:"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadViewController~1onInputBoxEventsOccur(action:attributeText:)\/fragments","op":"replace"}]}]}