{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewController\/onUserQuitTopic()"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@","kind":"attribute"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onUserQuitTopic","kind":"identifier"},{"kind":"text","text":"()"}],"languages":["swift"]}]}],"sections":[],"variants":[{"paths":["\/documentation\/shengwangchatuikit\/chatthreadviewcontroller\/onuserquittopic()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/chatthreadviewcontroller\/onuserquittopic()"]}],"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewController","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewController\/MessageListDriverEventsListener-Implementations"]]},"metadata":{"symbolKind":"method","roleHeading":"Instance Method","role":"symbol","modules":[{"name":"ShengwangChatUIKit"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onUserQuitTopic"},{"kind":"text","text":"()"}],"title":"onUserQuitTopic()","navigatorTitle":[{"kind":"identifier","text":"onUserQuitTopic"}],"extendedModule":"ShengwangChatUIKit","externalID":"c:@CM@ShengwangChatUIKit@objc(cs)ChatThreadViewController(im)onUserQuitTopic"},"abstract":[{"type":"text","text":"When received quit signal form other device on the chat thread."}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatThreadViewController/MessageListDriverEventsListener-Implementations":{"url":"\/documentation\/shengwangchatuikit\/chatthreadviewcontroller\/messagelistdrivereventslistener-implementations","kind":"article","type":"topic","abstract":[],"role":"collectionGroup","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewController\/MessageListDriverEventsListener-Implementations","title":"MessageListDriverEventsListener Implementations"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatThreadViewController":{"url":"\/documentation\/shengwangchatuikit\/chatthreadviewcontroller","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ChatThreadViewController"}],"abstract":[],"role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewController","title":"ChatThreadViewController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChatThreadViewController","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatThreadViewController/onUserQuitTopic()":{"url":"\/documentation\/shengwangchatuikit\/chatthreadviewcontroller\/onuserquittopic()","abstract":[{"text":"When received quit signal form other device on the chat thread.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"onUserQuitTopic","kind":"identifier"}],"type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewController\/onUserQuitTopic()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onUserQuitTopic","kind":"identifier"},{"text":"()","kind":"text"}],"title":"onUserQuitTopic()"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"onUserQuitTopic"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onUserQuitTopic"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"onUserQuitTopic","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadViewController\/title","op":"replace","value":"ChatThreadViewController"},{"value":[{"kind":"identifier","text":"ChatThreadViewController"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadViewController\/fragments","op":"replace"},{"value":[{"text":"ChatThreadViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadViewController\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadViewController~1onUserQuitTopic()\/title","value":"onUserQuitTopic"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadViewController~1onUserQuitTopic()\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"onUserQuitTopic"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}