{"variants":[{"paths":["\/documentation\/shengwangchatuikit\/chatthreadviewcontroller\/qlpreviewcontrollerdatasource-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/chatthreadviewcontroller\/qlpreviewcontrollerdatasource-implementations"]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewController\/QLPreviewControllerDataSource-Implementations"},"metadata":{"modules":[{"name":"ShengwangChatUIKit"}],"title":"QLPreviewControllerDataSource Implementations","role":"collectionGroup","roleHeading":"API Collection"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewController"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"article","topicSections":[{"anchor":"Instance-Methods","title":"Instance Methods","generated":true,"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewController\/numberOfPreviewItems(in:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewController\/previewController(_:previewItemAt:)"]}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatThreadViewController/numberOfPreviewItems(in:)":{"navigatorTitle":[{"kind":"identifier","text":"numberOfPreviewItemsInPreviewController:"}],"url":"\/documentation\/shengwangchatuikit\/chatthreadviewcontroller\/numberofpreviewitems(in:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"numberOfPreviewItems","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"in"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)QLPreviewController","kind":"typeIdentifier","text":"QLPreviewController"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"role":"symbol","title":"numberOfPreviewItems(in:)","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewController\/numberOfPreviewItems(in:)","kind":"symbol","abstract":[]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatThreadViewController/previewController(_:previewItemAt:)":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewController\/previewController(_:previewItemAt:)","url":"\/documentation\/shengwangchatuikit\/chatthreadviewcontroller\/previewcontroller(_:previewitemat:)","role":"symbol","title":"previewController(_:previewItemAt:)","abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"previewController","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)QLPreviewController","text":"QLPreviewController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"previewItemAt"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"QLPreviewItem","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)QLPreviewItem"}],"navigatorTitle":[{"text":"previewController:previewItemAtIndex:","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatThreadViewController":{"url":"\/documentation\/shengwangchatuikit\/chatthreadviewcontroller","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ChatThreadViewController"}],"abstract":[],"role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewController","title":"ChatThreadViewController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChatThreadViewController","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/topicSections","value":[{"anchor":"Instance-Methods","title":"Instance Methods","generated":true,"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewController\/numberOfPreviewItems(in:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewController\/previewController(_:previewItemAt:)"]}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadViewController~1numberOfPreviewItems(in:)\/title","value":"numberOfPreviewItemsInPreviewController:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"numberOfPreviewItemsInPreviewController:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadViewController~1numberOfPreviewItems(in:)\/fragments"},{"op":"replace","value":"previewController:previewItemAtIndex:","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadViewController~1previewController(_:previewItemAt:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"previewController:previewItemAtIndex:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadViewController~1previewController(_:previewItemAt:)\/fragments"},{"value":"ChatThreadViewController","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadViewController\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadViewController\/fragments","op":"replace","value":[{"text":"ChatThreadViewController","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"ChatThreadViewController"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadViewController\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}