{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/chatthreadviewcontroller\/selectfile()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/chatthreadviewcontroller\/selectfile()"]}],"kind":"symbol","metadata":{"navigatorTitle":[{"text":"selectFile","kind":"identifier"}],"roleHeading":"Instance Method","modules":[{"name":"ShengwangChatUIKit"}],"extendedModule":"ShengwangChatUIKit","externalID":"c:@CM@ShengwangChatUIKit@objc(cs)ChatThreadViewController(im)selectFile","role":"symbol","title":"selectFile()","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"selectFile","kind":"identifier"},{"text":"()","kind":"text"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewController"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"attribute","text":"@"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"selectFile"},{"text":"()","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"content","content":[{"type":"heading","anchor":"discussion","text":"Discussion","level":2},{"type":"paragraph","inlineContent":[{"text":"The document picker supports various file types including content, text, source code, images, PDFs, Keynote files, Word documents, Excel spreadsheets, PowerPoint presentations, and generic data files.","type":"text"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"The selected file will be handled by the ","type":"text"},{"type":"codeVoice","code":"UIDocumentPickerDelegate"},{"type":"text","text":" methods implemented in the "},{"code":"MessageListController","type":"codeVoice"},{"type":"text","text":"."}]}],"name":"Note","style":"note","type":"aside"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewController\/selectFile()"},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"text":"Opens a document picker to allow the user to select a file.","type":"text"}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatThreadViewController":{"url":"\/documentation\/shengwangchatuikit\/chatthreadviewcontroller","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ChatThreadViewController"}],"abstract":[],"role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewController","title":"ChatThreadViewController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChatThreadViewController","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatThreadViewController/selectFile()":{"navigatorTitle":[{"text":"selectFile","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewController\/selectFile()","abstract":[{"type":"text","text":"Opens a document picker to allow the user to select a file."}],"title":"selectFile()","role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/shengwangchatuikit\/chatthreadviewcontroller\/selectfile()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"selectFile"},{"text":"()","kind":"text"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"selectFile","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"selectFile"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"selectFile","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"ChatThreadViewController","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadViewController\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadViewController\/fragments","op":"replace","value":[{"text":"ChatThreadViewController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadViewController\/navigatorTitle","value":[{"text":"ChatThreadViewController","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadViewController~1selectFile()\/title","op":"replace","value":"selectFile"},{"value":[{"text":"- ","kind":"text"},{"text":"selectFile","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadViewController~1selectFile()\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}