{"metadata":{"extendedModule":"ShengwangChatUIKit","navigatorTitle":[{"text":"showMessageLongPressedDialogWithCell:","kind":"identifier"}],"externalID":"c:@CM@ShengwangChatUIKit@objc(cs)ChatThreadViewController(im)showMessageLongPressedDialogWithCell:","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"showMessageLongPressedDialog","kind":"identifier"},{"kind":"text","text":"("},{"text":"cell","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)MessageCell","text":"MessageCell"},{"text":")","kind":"text"}],"role":"symbol","title":"showMessageLongPressedDialog(cell:)","modules":[{"name":"ShengwangChatUIKit"}],"symbolKind":"method"},"abstract":[{"type":"text","text":"Shows a long-pressed dialog for a given chat message."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewController\/showMessageLongPressedDialog(cell:)"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"showMessageLongPressedDialog","kind":"identifier"},{"kind":"text","text":"("},{"text":"cell","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)MessageCell","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageCell","text":"MessageCell"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"content","content":[{"type":"heading","text":"Discussion","level":2,"anchor":"discussion"},{"items":[{"content":[{"inlineContent":[{"type":"text","text":"message: The chat message for which the dialog is shown."}],"type":"paragraph"}]}],"type":"unorderedList"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"paths":["\/documentation\/shengwangchatuikit\/chatthreadviewcontroller\/showmessagelongpresseddialog(cell:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/chatthreadviewcontroller\/showmessagelongpresseddialog(cell:)"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewController"]]},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageCell":{"navigatorTitle":[{"text":"MessageCell","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageCell"}],"title":"MessageCell","abstract":[],"url":"\/documentation\/shengwangchatuikit\/messagecell"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatThreadViewController":{"url":"\/documentation\/shengwangchatuikit\/chatthreadviewcontroller","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ChatThreadViewController"}],"abstract":[],"role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewController","title":"ChatThreadViewController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChatThreadViewController","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatThreadViewController/showMessageLongPressedDialog(cell:)":{"title":"showMessageLongPressedDialog(cell:)","abstract":[{"type":"text","text":"Shows a long-pressed dialog for a given chat message."}],"navigatorTitle":[{"text":"showMessageLongPressedDialogWithCell:","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewController\/showMessageLongPressedDialog(cell:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"showMessageLongPressedDialog","kind":"identifier"},{"kind":"text","text":"("},{"text":"cell","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MessageCell","kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)MessageCell"},{"text":")","kind":"text"}],"role":"symbol","url":"\/documentation\/shengwangchatuikit\/chatthreadviewcontroller\/showmessagelongpresseddialog(cell:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"showMessageLongPressedDialogWithCell:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"showMessageLongPressedDialogWithCell:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"showMessageLongPressedDialogWithCell:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)MessageCell","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageCell","text":"MessageCell"},{"text":" *) ","kind":"text"},{"text":"cell","kind":"internalParam"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageCell\/title","value":"MessageCell"},{"op":"replace","value":[{"text":"MessageCell","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageCell\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageCell\/navigatorTitle","value":[{"kind":"identifier","text":"MessageCell"}],"op":"replace"},{"op":"replace","value":"ChatThreadViewController","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadViewController\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadViewController\/fragments","value":[{"kind":"identifier","text":"ChatThreadViewController"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadViewController\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"ChatThreadViewController"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadViewController~1showMessageLongPressedDialog(cell:)\/title","op":"replace","value":"showMessageLongPressedDialogWithCell:"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadViewController~1showMessageLongPressedDialog(cell:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"showMessageLongPressedDialogWithCell:"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}