{"sections":[],"kind":"article","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewController\/UIDocumentPickerDelegate-Implementations"},"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewController"]]},"metadata":{"title":"UIDocumentPickerDelegate Implementations","role":"collectionGroup","modules":[{"name":"ShengwangChatUIKit"}],"roleHeading":"API Collection"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/chatthreadviewcontroller\/uidocumentpickerdelegate-implementations"]},{"paths":["\/documentation\/shengwangchatuikit\/chatthreadviewcontroller\/uidocumentpickerdelegate-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"topicSections":[{"anchor":"Instance-Methods","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewController\/documentPicker(_:didPickDocumentsAt:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewController\/documentPickerWasCancelled(_:)"],"title":"Instance Methods","generated":true}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatThreadViewController":{"url":"\/documentation\/shengwangchatuikit\/chatthreadviewcontroller","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ChatThreadViewController"}],"abstract":[],"role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewController","title":"ChatThreadViewController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChatThreadViewController","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatThreadViewController/documentPicker(_:didPickDocumentsAt:)":{"navigatorTitle":[{"text":"documentPicker:didPickDocumentsAtURLs:","kind":"identifier"}],"abstract":[],"kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewController\/documentPicker(_:didPickDocumentsAt:)","url":"\/documentation\/shengwangchatuikit\/chatthreadviewcontroller\/documentpicker(_:didpickdocumentsat:)","title":"documentPicker(_:didPickDocumentsAt:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"documentPicker","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIDocumentPickerViewController","kind":"typeIdentifier","text":"UIDocumentPickerViewController"},{"text":", ","kind":"text"},{"text":"didPickDocumentsAt","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"URL","preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier"},{"kind":"text","text":"])"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatThreadViewController/documentPickerWasCancelled(_:)":{"abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"documentPickerWasCancelled"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIDocumentPickerViewController","text":"UIDocumentPickerViewController","kind":"typeIdentifier"},{"kind":"text","text":")"}],"title":"documentPickerWasCancelled(_:)","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewController\/documentPickerWasCancelled(_:)","url":"\/documentation\/shengwangchatuikit\/chatthreadviewcontroller\/documentpickerwascancelled(_:)","role":"symbol","navigatorTitle":[{"text":"documentPickerWasCancelled:","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewController\/documentPicker(_:didPickDocumentsAt:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatThreadViewController\/documentPickerWasCancelled(_:)"],"title":"Instance Methods","generated":true,"anchor":"Instance-Methods"}],"op":"replace"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":"ChatThreadViewController","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadViewController\/title"},{"value":[{"kind":"identifier","text":"ChatThreadViewController"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadViewController\/fragments"},{"value":[{"text":"ChatThreadViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadViewController\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadViewController~1documentPicker(_:didPickDocumentsAt:)\/title","value":"documentPicker:didPickDocumentsAtURLs:"},{"value":[{"kind":"text","text":"- "},{"text":"documentPicker:didPickDocumentsAtURLs:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadViewController~1documentPicker(_:didPickDocumentsAt:)\/fragments"},{"value":"documentPickerWasCancelled:","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadViewController~1documentPickerWasCancelled(_:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"documentPickerWasCancelled:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatThreadViewController~1documentPickerWasCancelled(_:)\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}