{"kind":"article","topicSections":[{"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/CommonReactionView\/collectionView(_:cellForItemAt:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/CommonReactionView\/collectionView(_:numberOfItemsInSection:)"],"generated":true,"anchor":"Instance-Methods","title":"Instance Methods"}],"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/CommonReactionView\/UICollectionViewDataSource-Implementations","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/CommonReactionView"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"role":"collectionGroup","title":"UICollectionViewDataSource Implementations","roleHeading":"API Collection","modules":[{"name":"ShengwangChatUIKit"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/commonreactionview\/uicollectionviewdatasource-implementations"]},{"paths":["\/documentation\/shengwangchatuikit\/commonreactionview\/uicollectionviewdatasource-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/CommonReactionView":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"CommonReactionView","kind":"identifier"}],"role":"symbol","url":"\/documentation\/shengwangchatuikit\/commonreactionview","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/CommonReactionView","title":"CommonReactionView","kind":"symbol","abstract":[],"navigatorTitle":[{"text":"CommonReactionView","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/CommonReactionView/collectionView(_:cellForItemAt:)":{"kind":"symbol","title":"collectionView(_:cellForItemAt:)","role":"symbol","url":"\/documentation\/shengwangchatuikit\/commonreactionview\/collectionview(_:cellforitemat:)","navigatorTitle":[{"text":"collectionView:cellForItemAtIndexPath:","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/CommonReactionView\/collectionView(_:cellForItemAt:)","abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"collectionView"},{"kind":"text","text":"("},{"text":"UICollectionView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UICollectionView"},{"kind":"text","text":", "},{"text":"cellForItemAt","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation9IndexPathV","text":"IndexPath"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UICollectionViewCell","text":"UICollectionViewCell","kind":"typeIdentifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/CommonReactionView/collectionView(_:numberOfItemsInSection:)":{"navigatorTitle":[{"kind":"identifier","text":"collectionView:numberOfItemsInSection:"}],"title":"collectionView(_:numberOfItemsInSection:)","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/CommonReactionView\/collectionView(_:numberOfItemsInSection:)","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"collectionView","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UICollectionView","preciseIdentifier":"c:objc(cs)UICollectionView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"numberOfItemsInSection"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"type":"topic","abstract":[],"url":"\/documentation\/shengwangchatuikit\/commonreactionview\/collectionview(_:numberofitemsinsection:)"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/CommonReactionView\/collectionView(_:cellForItemAt:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/CommonReactionView\/collectionView(_:numberOfItemsInSection:)"],"title":"Instance Methods","anchor":"Instance-Methods","generated":true}]},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":"CommonReactionView","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1CommonReactionView\/title"},{"value":[{"kind":"identifier","text":"CommonReactionView"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1CommonReactionView\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1CommonReactionView\/navigatorTitle","value":[{"text":"CommonReactionView","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1CommonReactionView~1collectionView(_:cellForItemAt:)\/title","value":"collectionView:cellForItemAtIndexPath:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1CommonReactionView~1collectionView(_:cellForItemAt:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"collectionView:cellForItemAtIndexPath:","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1CommonReactionView~1collectionView(_:numberOfItemsInSection:)\/title","value":"collectionView:numberOfItemsInSection:"},{"value":[{"text":"- ","kind":"text"},{"text":"collectionView:numberOfItemsInSection:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1CommonReactionView~1collectionView(_:numberOfItemsInSection:)\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}