{"metadata":{"symbolKind":"method","navigatorTitle":[{"text":"onGroupOwnerUpdatedWithGroupId:ownerId:userId:","kind":"identifier"}],"role":"symbol","modules":[{"name":"ShengwangChatUIKit"}],"roleHeading":"Instance Method","externalID":"c:@M@ShengwangChatUIKit@objc(pl)GroupServiceListener(im)onGroupOwnerUpdatedWithGroupId:ownerId:userId:","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"onGroupOwnerUpdated","kind":"identifier"},{"kind":"text","text":"("},{"text":"groupId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"ownerId","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"text":"userId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":")"}],"title":"onGroupOwnerUpdated(groupId:ownerId:userId:)"},"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupServiceListener\/onGroupOwnerUpdated(groupId:ownerId:userId:)","interfaceLanguage":"swift"},"kind":"symbol","abstract":[{"type":"text","text":"The group owner of the current group has changed."}],"variants":[{"paths":["\/documentation\/shengwangchatuikit\/groupservicelistener\/ongroupownerupdated(groupid:ownerid:userid:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/groupservicelistener\/ongroupownerupdated(groupid:ownerid:userid:)"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupServiceListener"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onGroupOwnerUpdated"},{"text":"(","kind":"text"},{"text":"groupId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"ownerId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"userId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}]}]},{"kind":"parameters","parameters":[{"name":"groupId","content":[{"type":"paragraph","inlineContent":[{"text":"ID of the group.","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"ID of the group owner.","type":"text"}]}],"name":"ownerId"},{"name":"userId","content":[{"inlineContent":[{"text":"ID of the user.","type":"text"}],"type":"paragraph"}]}]}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/GroupServiceListener/onGroupOwnerUpdated(groupId:ownerId:userId:)":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupServiceListener\/onGroupOwnerUpdated(groupId:ownerId:userId:)","abstract":[{"type":"text","text":"The group owner of the current group has changed."}],"navigatorTitle":[{"kind":"identifier","text":"onGroupOwnerUpdatedWithGroupId:ownerId:userId:"}],"type":"topic","role":"symbol","url":"\/documentation\/shengwangchatuikit\/groupservicelistener\/ongroupownerupdated(groupid:ownerid:userid:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onGroupOwnerUpdated","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"groupId"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"ownerId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"userId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":")","kind":"text"}],"title":"onGroupOwnerUpdated(groupId:ownerId:userId:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/GroupServiceListener":{"url":"\/documentation\/shengwangchatuikit\/groupservicelistener","abstract":[],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"GroupServiceListener"}],"type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupServiceListener","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GroupServiceListener","kind":"identifier"}],"title":"GroupServiceListener"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"onGroupOwnerUpdatedWithGroupId:ownerId:userId:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"onGroupOwnerUpdatedWithGroupId:ownerId:userId:","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"onGroupOwnerUpdatedWithGroupId:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"groupId","kind":"internalParam"},{"kind":"text","text":" "},{"text":"ownerId:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"ownerId"},{"kind":"text","text":" "},{"kind":"identifier","text":"userId:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"userId"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"parameters":[{"name":"groupId","content":[{"type":"paragraph","inlineContent":[{"text":"ID of the group.","type":"text"}]}]},{"name":"ownerId","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"ID of the group owner."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"ID of the user.","type":"text"}]}],"name":"userId"}],"kind":"parameters"},"path":"\/primaryContentSections\/1","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupServiceListener~1onGroupOwnerUpdated(groupId:ownerId:userId:)\/title","value":"onGroupOwnerUpdatedWithGroupId:ownerId:userId:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupServiceListener~1onGroupOwnerUpdated(groupId:ownerId:userId:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"onGroupOwnerUpdatedWithGroupId:ownerId:userId:","kind":"identifier"}],"op":"replace"},{"value":"GroupServiceListener","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupServiceListener\/title"},{"value":[{"kind":"identifier","text":"GroupServiceListener"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupServiceListener\/fragments"},{"op":"replace","value":[{"text":"GroupServiceListener","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupServiceListener\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}