{"abstract":[{"type":"text","text":"Accepted invitation of the group."}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupServiceListener\/onInviterAcceptedInvitationOfGroup(groupId:userId:)"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupServiceListener"]]},"metadata":{"modules":[{"name":"ShengwangChatUIKit"}],"roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"onInviterAcceptedInvitationOfGroup"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"groupId"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"userId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"title":"onInviterAcceptedInvitationOfGroup(groupId:userId:)","role":"symbol","required":true,"navigatorTitle":[{"kind":"identifier","text":"onInviterAcceptedInvitationOfGroupWithGroupId:userId:"}],"externalID":"c:@M@ShengwangChatUIKit@objc(pl)GroupServiceListener(im)onInviterAcceptedInvitationOfGroupWithGroupId:userId:","symbolKind":"method"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/groupservicelistener\/oninviteracceptedinvitationofgroup(groupid:userid:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/groupservicelistener\/oninviteracceptedinvitationofgroup(groupid:userid:)"]}],"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"onInviterAcceptedInvitationOfGroup","kind":"identifier"},{"text":"(","kind":"text"},{"text":"groupId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"text":"userId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"groupId","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"ID of the group."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"ID of the user."}]}],"name":"userId"}]}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/GroupServiceListener":{"url":"\/documentation\/shengwangchatuikit\/groupservicelistener","abstract":[],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"GroupServiceListener"}],"type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupServiceListener","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GroupServiceListener","kind":"identifier"}],"title":"GroupServiceListener"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/GroupServiceListener/onInviterAcceptedInvitationOfGroup(groupId:userId:)":{"abstract":[{"type":"text","text":"Accepted invitation of the group."}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupServiceListener\/onInviterAcceptedInvitationOfGroup(groupId:userId:)","navigatorTitle":[{"kind":"identifier","text":"onInviterAcceptedInvitationOfGroupWithGroupId:userId:"}],"type":"topic","role":"symbol","url":"\/documentation\/shengwangchatuikit\/groupservicelistener\/oninviteracceptedinvitationofgroup(groupid:userid:)","kind":"symbol","required":true,"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"onInviterAcceptedInvitationOfGroup"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"groupId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"userId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"title":"onInviterAcceptedInvitationOfGroup(groupId:userId:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","value":"onInviterAcceptedInvitationOfGroupWithGroupId:userId:","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"onInviterAcceptedInvitationOfGroupWithGroupId:userId:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"onInviterAcceptedInvitationOfGroupWithGroupId:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"groupId","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"userId:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"userId","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"kind":"parameters","parameters":[{"name":"groupId","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"ID of the group."}]}]},{"name":"userId","content":[{"inlineContent":[{"text":"ID of the user.","type":"text"}],"type":"paragraph"}]}]},"op":"replace","path":"\/primaryContentSections\/1"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupServiceListener\/title","value":"GroupServiceListener","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupServiceListener\/fragments","value":[{"text":"GroupServiceListener","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupServiceListener\/navigatorTitle","value":[{"kind":"identifier","text":"GroupServiceListener"}]},{"value":"onInviterAcceptedInvitationOfGroupWithGroupId:userId:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupServiceListener~1onInviterAcceptedInvitationOfGroup(groupId:userId:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"onInviterAcceptedInvitationOfGroupWithGroupId:userId:"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupServiceListener~1onInviterAcceptedInvitationOfGroup(groupId:userId:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}