{"abstract":[{"text":"When some user left group.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onUserLeaveGroup"},{"text":"(","kind":"text"},{"text":"groupId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"userId"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"languages":["swift"]}]},{"parameters":[{"name":"groupId","content":[{"inlineContent":[{"type":"text","text":"ID of the group."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"ID of the user."}],"type":"paragraph"}],"name":"userId"}],"kind":"parameters"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/groupservicelistener\/onuserleavegroup(groupid:userid:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/groupservicelistener\/onuserleavegroup(groupid:userid:)"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupServiceListener"]]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupServiceListener\/onUserLeaveGroup(groupId:userId:)"},"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"metadata":{"role":"symbol","roleHeading":"Instance Method","navigatorTitle":[{"text":"onUserLeaveGroupWithGroupId:userId:","kind":"identifier"}],"externalID":"c:@M@ShengwangChatUIKit@objc(pl)GroupServiceListener(im)onUserLeaveGroupWithGroupId:userId:","symbolKind":"method","required":true,"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onUserLeaveGroup"},{"text":"(","kind":"text"},{"text":"groupId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"userId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"title":"onUserLeaveGroup(groupId:userId:)","modules":[{"name":"ShengwangChatUIKit"}]},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/GroupServiceListener":{"url":"\/documentation\/shengwangchatuikit\/groupservicelistener","abstract":[],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"GroupServiceListener"}],"type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupServiceListener","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GroupServiceListener","kind":"identifier"}],"title":"GroupServiceListener"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/GroupServiceListener/onUserLeaveGroup(groupId:userId:)":{"required":true,"kind":"symbol","url":"\/documentation\/shengwangchatuikit\/groupservicelistener\/onuserleavegroup(groupid:userid:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"onUserLeaveGroup","kind":"identifier"},{"kind":"text","text":"("},{"text":"groupId","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"userId"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"When some user left group."}],"navigatorTitle":[{"kind":"identifier","text":"onUserLeaveGroupWithGroupId:userId:"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupServiceListener\/onUserLeaveGroup(groupId:userId:)","role":"symbol","type":"topic","title":"onUserLeaveGroup(groupId:userId:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"onUserLeaveGroupWithGroupId:userId:","path":"\/metadata\/title","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"onUserLeaveGroupWithGroupId:userId:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"text":") ","kind":"text"},{"kind":"identifier","text":"onUserLeaveGroupWithGroupId:"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"groupId","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"userId:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"text":"userId","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"value":{"kind":"parameters","parameters":[{"name":"groupId","content":[{"inlineContent":[{"text":"ID of the group.","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"ID of the user.","type":"text"}]}],"name":"userId"}]},"op":"replace","path":"\/primaryContentSections\/1"},{"value":"GroupServiceListener","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupServiceListener\/title","op":"replace"},{"value":[{"text":"GroupServiceListener","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupServiceListener\/fragments","op":"replace"},{"value":[{"text":"GroupServiceListener","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupServiceListener\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupServiceListener~1onUserLeaveGroup(groupId:userId:)\/title","value":"onUserLeaveGroupWithGroupId:userId:"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupServiceListener~1onUserLeaveGroup(groupId:userId:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"onUserLeaveGroupWithGroupId:userId:","kind":"identifier"}],"op":"replace"}]}]}