{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupParticipantsSelectCell"]]},"kind":"symbol","sections":[],"variants":[{"paths":["\/documentation\/shengwangchatuikit\/groupparticipantsselectcell\/layoutsubviews()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/shengwangchatuikit\/groupparticipantsselectcell\/layoutsubviews()"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"modules":[{"name":"ShengwangChatUIKit"}],"externalID":"c:@M@ShengwangChatUIKit@objc(cs)GroupParticipantsSelectCell(im)layoutSubviews","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"layoutSubviews","kind":"identifier"},{"text":"()","kind":"text"}],"role":"symbol","title":"layoutSubviews()","symbolKind":"method","roleHeading":"Instance Method","navigatorTitle":[{"text":"layoutSubviews","kind":"identifier"}]},"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupParticipantsSelectCell\/layoutSubviews()","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","kind":"attribute","text":"MainActor"},{"kind":"text","text":" "},{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"layoutSubviews","kind":"identifier"},{"text":"()","kind":"text"}]}]}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/GroupParticipantsSelectCell":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupParticipantsSelectCell","navigatorTitle":[{"text":"GroupParticipantsSelectCell","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/groupparticipantsselectcell","type":"topic","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GroupParticipantsSelectCell"}],"title":"GroupParticipantsSelectCell","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/GroupParticipantsSelectCell/layoutSubviews()":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/GroupParticipantsSelectCell\/layoutSubviews()","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"layoutSubviews","kind":"identifier"},{"text":"()","kind":"text"}],"kind":"symbol","url":"\/documentation\/shengwangchatuikit\/groupparticipantsselectcell\/layoutsubviews()","title":"layoutSubviews()","role":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"layoutSubviews"}],"type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","value":"layoutSubviews","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"layoutSubviews"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"layoutSubviews","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"value":"GroupParticipantsSelectCell","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupParticipantsSelectCell\/title"},{"value":[{"text":"GroupParticipantsSelectCell","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupParticipantsSelectCell\/fragments","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"GroupParticipantsSelectCell"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupParticipantsSelectCell\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupParticipantsSelectCell~1layoutSubviews()\/title","value":"layoutSubviews"},{"value":[{"text":"- ","kind":"text"},{"text":"layoutSubviews","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1GroupParticipantsSelectCell~1layoutSubviews()\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}