{"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactSearchResultController"]]},"sections":[],"metadata":{"role":"symbol","title":"searchHeader","symbolKind":"property","externalID":"c:@M@ShengwangChatUIKit@objc(cs)ContactSearchResultController(py)searchHeader","roleHeading":"Instance Property","navigatorTitle":[{"text":"searchHeader","kind":"identifier"}],"modules":[{"name":"ShengwangChatUIKit"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"searchHeader"},{"text":": ","kind":"text"},{"text":"SearchHeaderBar","kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)SearchHeaderBar"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"kind":"keyword","text":"lazy"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"searchHeader","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)SearchHeaderBar","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/SearchHeaderBar","text":"SearchHeaderBar"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/shengwangchatuikit\/contactsearchresultcontroller\/searchheader"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/shengwangchatuikit\/contactsearchresultcontroller\/searchheader"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactSearchResultController\/searchHeader","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/SearchHeaderBar":{"title":"SearchHeaderBar","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SearchHeaderBar","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/searchheaderbar","role":"symbol","abstract":[],"type":"topic","navigatorTitle":[{"text":"SearchHeaderBar","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/SearchHeaderBar","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ContactSearchResultController":{"type":"topic","role":"symbol","title":"ContactSearchResultController","kind":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"ContactSearchResultController"}],"url":"\/documentation\/shengwangchatuikit\/contactsearchresultcontroller","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactSearchResultController","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ContactSearchResultController","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ContactSearchResultController/searchHeader":{"url":"\/documentation\/shengwangchatuikit\/contactsearchresultcontroller\/searchheader","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"searchHeader","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)SearchHeaderBar","kind":"typeIdentifier","text":"SearchHeaderBar"}],"title":"searchHeader","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"searchHeader"}],"abstract":[],"role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactSearchResultController\/searchHeader"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"searchHeader","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"searchHeader","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)SearchHeaderBar","text":"SearchHeaderBar","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/SearchHeaderBar"},{"kind":"text","text":" * "},{"text":"searchHeader","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1SearchHeaderBar\/title","op":"replace","value":"SearchHeaderBar"},{"value":[{"kind":"identifier","text":"SearchHeaderBar"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1SearchHeaderBar\/fragments","op":"replace"},{"value":[{"text":"SearchHeaderBar","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1SearchHeaderBar\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactSearchResultController\/title","value":"ContactSearchResultController","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactSearchResultController\/fragments","op":"replace","value":[{"kind":"identifier","text":"ContactSearchResultController"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactSearchResultController\/navigatorTitle","op":"replace","value":[{"text":"ContactSearchResultController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactSearchResultController~1searchHeader\/title","op":"replace","value":"searchHeader"},{"value":[{"kind":"identifier","text":"searchHeader"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactSearchResultController~1searchHeader\/fragments","op":"replace"}]}]}