{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactSearchResultController"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/contactsearchresultcontroller\/tableview(_:didselectrowat:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/contactsearchresultcontroller\/tableview(_:didselectrowat:)"]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactSearchResultController\/tableView(_:didSelectRowAt:)"},"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"UITableViewDelegate.tableView(_:didSelectRowAt:)"},{"text":".","type":"text"}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"tableView","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"tableView"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITableView","text":"UITableView"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didSelectRowAt"},{"kind":"text","text":" "},{"text":"indexPath","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"symbolKind":"method","externalID":"c:@M@ShengwangChatUIKit@objc(cs)ContactSearchResultController(im)tableView:didSelectRowAtIndexPath:","title":"tableView(_:didSelectRowAt:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"tableView","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UITableView","preciseIdentifier":"c:objc(cs)UITableView"},{"kind":"text","text":", "},{"text":"didSelectRowAt","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"IndexPath","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":")"}],"role":"symbol","modules":[{"name":"ShengwangChatUIKit"}],"navigatorTitle":[{"text":"tableView:didSelectRowAtIndexPath:","kind":"identifier"}],"roleHeading":"Instance Method"},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ContactSearchResultController/tableView(_:didSelectRowAt:)":{"navigatorTitle":[{"text":"tableView:didSelectRowAtIndexPath:","kind":"identifier"}],"abstract":[],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"tableView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UITableView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITableView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didSelectRowAt"},{"kind":"text","text":": "},{"text":"IndexPath","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation9IndexPathV"},{"text":")","kind":"text"}],"url":"\/documentation\/shengwangchatuikit\/contactsearchresultcontroller\/tableview(_:didselectrowat:)","role":"symbol","title":"tableView(_:didSelectRowAt:)","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactSearchResultController\/tableView(_:didSelectRowAt:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ContactSearchResultController":{"type":"topic","role":"symbol","title":"ContactSearchResultController","kind":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"ContactSearchResultController"}],"url":"\/documentation\/shengwangchatuikit\/contactsearchresultcontroller","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactSearchResultController","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ContactSearchResultController","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"tableView:didSelectRowAtIndexPath:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"tableView:didSelectRowAtIndexPath:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"tableView:"},{"kind":"text","text":"("},{"text":"UITableView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITableView"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"tableView"},{"text":" ","kind":"text"},{"kind":"identifier","text":"didSelectRowAtIndexPath:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSIndexPath","preciseIdentifier":"c:objc(cs)NSIndexPath"},{"kind":"text","text":" *) "},{"text":"indexPath","kind":"internalParam"},{"kind":"text","text":";"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactSearchResultController~1tableView(_:didSelectRowAt:)\/title","value":"tableView:didSelectRowAtIndexPath:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"tableView:didSelectRowAtIndexPath:"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactSearchResultController~1tableView(_:didSelectRowAt:)\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactSearchResultController\/title","op":"replace","value":"ContactSearchResultController"},{"value":[{"text":"ContactSearchResultController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactSearchResultController\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactSearchResultController\/navigatorTitle","value":[{"text":"ContactSearchResultController","kind":"identifier"}]}]}]}