{"kind":"article","schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactSearchResultController\/ThemeSwitchProtocol-Implementations"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactSearchResultController"]]},"sections":[],"metadata":{"modules":[{"name":"ShengwangChatUIKit"}],"roleHeading":"API Collection","title":"ThemeSwitchProtocol Implementations","role":"collectionGroup"},"topicSections":[{"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactSearchResultController\/switchTheme(style:)"],"generated":true,"title":"Instance Methods","anchor":"Instance-Methods"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/contactsearchresultcontroller\/themeswitchprotocol-implementations"]},{"paths":["\/documentation\/shengwangchatuikit\/contactsearchresultcontroller\/themeswitchprotocol-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ContactSearchResultController/switchTheme(style:)":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactSearchResultController\/switchTheme(style:)","type":"topic","abstract":[{"type":"text","text":"When some view Implement the protocol method,you can use "},{"code":"Theme.switchTheme(style: .dark)","type":"codeVoice"},{"type":"text","text":" to switch theme."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"switchTheme","kind":"identifier"},{"text":"(","kind":"text"},{"text":"style","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ThemeStyle","kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@E@ThemeStyle"},{"text":")","kind":"text"}],"url":"\/documentation\/shengwangchatuikit\/contactsearchresultcontroller\/switchtheme(style:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"switchThemeWithStyle:"}],"kind":"symbol","title":"switchTheme(style:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ContactSearchResultController":{"type":"topic","role":"symbol","title":"ContactSearchResultController","kind":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"ContactSearchResultController"}],"url":"\/documentation\/shengwangchatuikit\/contactsearchresultcontroller","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactSearchResultController","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ContactSearchResultController","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/topicSections","value":[{"anchor":"Instance-Methods","title":"Instance Methods","generated":true,"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactSearchResultController\/switchTheme(style:)"]}]},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":"switchThemeWithStyle:","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactSearchResultController~1switchTheme(style:)\/title"},{"value":[{"kind":"text","text":"- "},{"text":"switchThemeWithStyle:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactSearchResultController~1switchTheme(style:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactSearchResultController\/title","value":"ContactSearchResultController"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactSearchResultController\/fragments","value":[{"kind":"identifier","text":"ContactSearchResultController"}]},{"value":[{"text":"ContactSearchResultController","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactSearchResultController\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}