{"kind":"symbol","sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListType\/history"},"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListType"]]},"metadata":{"roleHeading":"Case","navigatorTitle":[{"kind":"identifier","text":"MessageListTypeHistory"}],"title":"MessageListType.history","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"history"}],"externalID":"c:@M@ShengwangChatUIKit@E@MessageListType@MessageListTypeHistory","modules":[{"name":"ShengwangChatUIKit"}],"symbolKind":"case"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"history","kind":"identifier"}],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/messagelisttype\/history"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/messagelisttype\/history"]}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageListType/history":{"type":"topic","abstract":[],"navigatorTitle":[{"text":"MessageListTypeHistory","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/messagelisttype\/history","kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListType\/history","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"history","kind":"identifier"}],"title":"MessageListType.history"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageListType":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"MessageListType","kind":"identifier"}],"role":"symbol","url":"\/documentation\/shengwangchatuikit\/messagelisttype","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListType","title":"MessageListType","kind":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"MessageListType"}],"type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"MessageListTypeHistory","path":"\/metadata\/title","op":"replace"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MessageListTypeHistory"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"MessageListTypeHistory"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListType~1history\/title","op":"replace","value":"MessageListTypeHistory"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListType~1history\/fragments","value":[{"text":"MessageListTypeHistory","kind":"identifier"}],"op":"replace"},{"value":"MessageListType","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListType\/title","op":"replace"},{"value":[{"text":"MessageListType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListType\/fragments"},{"value":[{"text":"MessageListType","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListType\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}