{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListType\/thread"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"thread","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListType"]]},"kind":"symbol","sections":[],"metadata":{"navigatorTitle":[{"text":"MessageListTypeThread","kind":"identifier"}],"modules":[{"name":"ShengwangChatUIKit"}],"symbolKind":"case","roleHeading":"Case","title":"MessageListType.thread","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"thread","kind":"identifier"}],"externalID":"c:@M@ShengwangChatUIKit@E@MessageListType@MessageListTypeThread","role":"symbol"},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/messagelisttype\/thread"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/messagelisttype\/thread"]}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageListType/thread":{"kind":"symbol","title":"MessageListType.thread","navigatorTitle":[{"text":"MessageListTypeThread","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"thread","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListType\/thread","url":"\/documentation\/shengwangchatuikit\/messagelisttype\/thread","type":"topic","abstract":[]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageListType":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"MessageListType","kind":"identifier"}],"role":"symbol","url":"\/documentation\/shengwangchatuikit\/messagelisttype","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListType","title":"MessageListType","kind":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"MessageListType"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"MessageListTypeThread","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"MessageListTypeThread"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"MessageListTypeThread"}]}],"kind":"declarations"},"op":"replace"},{"value":"MessageListTypeThread","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListType~1thread\/title"},{"value":[{"kind":"identifier","text":"MessageListTypeThread"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListType~1thread\/fragments"},{"op":"replace","value":"MessageListType","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListType\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListType\/fragments","value":[{"kind":"identifier","text":"MessageListType"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListType\/navigatorTitle","value":[{"text":"MessageListType","kind":"identifier"}],"op":"replace"}]}]}