{"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/contactemergencytype\/agree"]},{"paths":["\/documentation\/shengwangchatuikit\/contactemergencytype\/agree"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"agree"}]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactEmergencyType\/agree","interfaceLanguage":"swift"},"sections":[],"metadata":{"externalID":"c:@M@ShengwangChatUIKit@E@ContactEmergencyType@ContactEmergencyTypeAgree","navigatorTitle":[{"kind":"identifier","text":"ContactEmergencyTypeAgree"}],"role":"symbol","modules":[{"name":"ShengwangChatUIKit"}],"title":"ContactEmergencyType.agree","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"agree"}],"roleHeading":"Case","symbolKind":"case"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactEmergencyType"]]},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ContactEmergencyType":{"role":"symbol","abstract":[],"navigatorTitle":[{"text":"ContactEmergencyType","kind":"identifier"}],"title":"ContactEmergencyType","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"ContactEmergencyType","kind":"identifier"}],"type":"topic","kind":"symbol","url":"\/documentation\/shengwangchatuikit\/contactemergencytype","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactEmergencyType"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ContactEmergencyType/agree":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactEmergencyType\/agree","url":"\/documentation\/shengwangchatuikit\/contactemergencytype\/agree","kind":"symbol","navigatorTitle":[{"text":"ContactEmergencyTypeAgree","kind":"identifier"}],"role":"symbol","abstract":[],"title":"ContactEmergencyType.agree","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"agree","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"ContactEmergencyTypeAgree"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"ContactEmergencyTypeAgree","kind":"identifier"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"ContactEmergencyTypeAgree","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"value":"ContactEmergencyType","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactEmergencyType\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactEmergencyType\/fragments","value":[{"text":"ContactEmergencyType","kind":"identifier"}]},{"value":[{"text":"ContactEmergencyType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactEmergencyType\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactEmergencyType~1agree\/title","op":"replace","value":"ContactEmergencyTypeAgree"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactEmergencyType~1agree\/fragments","value":[{"text":"ContactEmergencyTypeAgree","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}