{"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageInputBar\/emoji","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"emoji"},{"text":": ","kind":"text"},{"text":"MessageInputEmojiView","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)MessageInputEmojiView","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageInputEmojiView"},{"text":"? { get }","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageInputBar"]]},"sections":[],"metadata":{"symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"emoji"},{"kind":"text","text":": "},{"text":"MessageInputEmojiView","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)MessageInputEmojiView","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"emoji","kind":"identifier"}],"role":"symbol","roleHeading":"Instance Property","modules":[{"name":"ShengwangChatUIKit"}],"externalID":"c:@M@ShengwangChatUIKit@objc(cs)MessageInputBar(py)emoji","title":"emoji"},"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/messageinputbar\/emoji"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/messageinputbar\/emoji"]}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageInputBar":{"abstract":[],"title":"MessageInputBar","kind":"symbol","url":"\/documentation\/shengwangchatuikit\/messageinputbar","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MessageInputBar","kind":"identifier"}],"navigatorTitle":[{"text":"MessageInputBar","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageInputBar"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageInputEmojiView":{"navigatorTitle":[{"text":"MessageInputEmojiView","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/messageinputemojiview","title":"MessageInputEmojiView","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MessageInputEmojiView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageInputEmojiView","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageInputBar/emoji":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"emoji"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)MessageInputEmojiView","kind":"typeIdentifier","text":"MessageInputEmojiView"},{"text":"?","kind":"text"}],"type":"topic","url":"\/documentation\/shengwangchatuikit\/messageinputbar\/emoji","navigatorTitle":[{"kind":"identifier","text":"emoji"}],"title":"emoji","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageInputBar\/emoji","role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"value":"emoji","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"value":[{"text":"emoji","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"text":"MessageInputEmojiView","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)MessageInputEmojiView","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageInputEmojiView"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"emoji"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageInputBar\/title","value":"MessageInputBar"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageInputBar\/fragments","value":[{"kind":"identifier","text":"MessageInputBar"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageInputBar\/navigatorTitle","value":[{"text":"MessageInputBar","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageInputEmojiView\/title","value":"MessageInputEmojiView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageInputEmojiView\/fragments","value":[{"kind":"identifier","text":"MessageInputEmojiView"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageInputEmojiView\/navigatorTitle","value":[{"kind":"identifier","text":"MessageInputEmojiView"}],"op":"replace"},{"op":"replace","value":"emoji","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageInputBar~1emoji\/title"},{"op":"replace","value":[{"kind":"identifier","text":"emoji"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageInputBar~1emoji\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}