{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/messageinputbar\/textviewdidendediting(_:)"]},{"paths":["\/documentation\/shengwangchatuikit\/messageinputbar\/textviewdidendediting(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageInputBar","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageInputBar\/UITextViewDelegate-Implementations"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"role":"symbol","roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"textViewDidEndEditing:"}],"extendedModule":"ShengwangChatUIKit","externalID":"c:@CM@ShengwangChatUIKit@objc(cs)MessageInputBar(im)textViewDidEndEditing:","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"textViewDidEndEditing"},{"text":"(","kind":"text"},{"text":"UITextView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITextView"},{"text":")","kind":"text"}],"title":"textViewDidEndEditing(_:)","modules":[{"name":"ShengwangChatUIKit"}]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","kind":"attribute","text":"MainActor"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"textViewDidEndEditing"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"textView"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UITextView","text":"UITextView","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"abstract":[{"text":"Inherited from ","type":"text"},{"code":"UITextViewDelegate.textViewDidEndEditing(_:)","type":"codeVoice"},{"type":"text","text":"."}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageInputBar\/textViewDidEndEditing(_:)"},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageInputBar/UITextViewDelegate-Implementations":{"type":"topic","url":"\/documentation\/shengwangchatuikit\/messageinputbar\/uitextviewdelegate-implementations","title":"UITextViewDelegate Implementations","abstract":[],"kind":"article","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageInputBar\/UITextViewDelegate-Implementations","role":"collectionGroup"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageInputBar/textViewDidEndEditing(_:)":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageInputBar\/textViewDidEndEditing(_:)","navigatorTitle":[{"text":"textViewDidEndEditing:","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/messageinputbar\/textviewdidendediting(_:)","type":"topic","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"textViewDidEndEditing"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"UITextView","preciseIdentifier":"c:objc(cs)UITextView"},{"text":")","kind":"text"}],"title":"textViewDidEndEditing(_:)","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageInputBar":{"abstract":[],"title":"MessageInputBar","kind":"symbol","url":"\/documentation\/shengwangchatuikit\/messageinputbar","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MessageInputBar","kind":"identifier"}],"navigatorTitle":[{"text":"MessageInputBar","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageInputBar"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"textViewDidEndEditing:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"textViewDidEndEditing:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"textViewDidEndEditing:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UITextView","text":"UITextView","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"textView","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"value":"textViewDidEndEditing:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageInputBar~1textViewDidEndEditing(_:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"textViewDidEndEditing:"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageInputBar~1textViewDidEndEditing(_:)\/fragments"},{"value":"MessageInputBar","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageInputBar\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageInputBar\/fragments","value":[{"text":"MessageInputBar","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageInputBar\/navigatorTitle","op":"replace","value":[{"text":"MessageInputBar","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}