{"kind":"article","sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageInputBar\/UITextViewDelegate-Implementations","interfaceLanguage":"swift"},"topicSections":[{"generated":true,"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageInputBar\/textView(_:shouldChangeTextIn:replacementText:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageInputBar\/textViewDidBeginEditing(_:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageInputBar\/textViewDidChange(_:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageInputBar\/textViewDidChangeSelection(_:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageInputBar\/textViewDidEndEditing(_:)"],"title":"Instance Methods","anchor":"Instance-Methods"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/messageinputbar\/uitextviewdelegate-implementations"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/messageinputbar\/uitextviewdelegate-implementations"]}],"metadata":{"roleHeading":"API Collection","title":"UITextViewDelegate Implementations","role":"collectionGroup","modules":[{"name":"ShengwangChatUIKit"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageInputBar"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageInputBar/textViewDidChangeSelection(_:)":{"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageInputBar\/textViewDidChangeSelection(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"textViewDidChangeSelection","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UITextView","kind":"typeIdentifier","text":"UITextView"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"textViewDidChangeSelection:","kind":"identifier"}],"title":"textViewDidChangeSelection(_:)","url":"\/documentation\/shengwangchatuikit\/messageinputbar\/textviewdidchangeselection(_:)","abstract":[],"role":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageInputBar/textViewDidChange(_:)":{"navigatorTitle":[{"kind":"identifier","text":"textViewDidChange:"}],"title":"textViewDidChange(_:)","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageInputBar\/textViewDidChange(_:)","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"textViewDidChange"},{"kind":"text","text":"("},{"text":"UITextView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITextView"},{"text":")","kind":"text"}],"type":"topic","abstract":[],"url":"\/documentation\/shengwangchatuikit\/messageinputbar\/textviewdidchange(_:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageInputBar/textViewDidBeginEditing(_:)":{"navigatorTitle":[{"text":"textViewDidBeginEditing:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"textViewDidBeginEditing"},{"text":"(","kind":"text"},{"text":"UITextView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITextView"},{"kind":"text","text":")"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageInputBar\/textViewDidBeginEditing(_:)","url":"\/documentation\/shengwangchatuikit\/messageinputbar\/textviewdidbeginediting(_:)","type":"topic","abstract":[],"kind":"symbol","role":"symbol","title":"textViewDidBeginEditing(_:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageInputBar":{"abstract":[],"title":"MessageInputBar","kind":"symbol","url":"\/documentation\/shengwangchatuikit\/messageinputbar","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MessageInputBar","kind":"identifier"}],"navigatorTitle":[{"text":"MessageInputBar","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageInputBar"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageInputBar/textViewDidEndEditing(_:)":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageInputBar\/textViewDidEndEditing(_:)","navigatorTitle":[{"text":"textViewDidEndEditing:","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/messageinputbar\/textviewdidendediting(_:)","type":"topic","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"textViewDidEndEditing"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"UITextView","preciseIdentifier":"c:objc(cs)UITextView"},{"text":")","kind":"text"}],"title":"textViewDidEndEditing(_:)","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageInputBar/textView(_:shouldChangeTextIn:replacementText:)":{"abstract":[],"title":"textView(_:shouldChangeTextIn:replacementText:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"textView"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UITextView","kind":"typeIdentifier","text":"UITextView"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"shouldChangeTextIn"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSRange","kind":"typeIdentifier","text":"NSRange"},{"kind":"text","text":", "},{"text":"replacementText","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"type":"topic","url":"\/documentation\/shengwangchatuikit\/messageinputbar\/textview(_:shouldchangetextin:replacementtext:)","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageInputBar\/textView(_:shouldChangeTextIn:replacementText:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"textView:shouldChangeTextInRange:replacementText:"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/topicSections","value":[{"anchor":"Instance-Methods","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageInputBar\/textView(_:shouldChangeTextIn:replacementText:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageInputBar\/textViewDidBeginEditing(_:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageInputBar\/textViewDidChange(_:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageInputBar\/textViewDidChangeSelection(_:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageInputBar\/textViewDidEndEditing(_:)"],"generated":true,"title":"Instance Methods"}],"op":"replace"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageInputBar~1textViewDidChangeSelection(_:)\/title","value":"textViewDidChangeSelection:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageInputBar~1textViewDidChangeSelection(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"textViewDidChangeSelection:"}]},{"value":"textViewDidChange:","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageInputBar~1textViewDidChange(_:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"textViewDidChange:"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageInputBar~1textViewDidChange(_:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageInputBar~1textViewDidBeginEditing(_:)\/title","op":"replace","value":"textViewDidBeginEditing:"},{"value":[{"kind":"text","text":"- "},{"text":"textViewDidBeginEditing:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageInputBar~1textViewDidBeginEditing(_:)\/fragments"},{"value":"MessageInputBar","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageInputBar\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageInputBar\/fragments","op":"replace","value":[{"text":"MessageInputBar","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageInputBar\/navigatorTitle","value":[{"text":"MessageInputBar","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageInputBar~1textViewDidEndEditing(_:)\/title","op":"replace","value":"textViewDidEndEditing:"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"textViewDidEndEditing:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageInputBar~1textViewDidEndEditing(_:)\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageInputBar~1textView(_:shouldChangeTextIn:replacementText:)\/title","value":"textView:shouldChangeTextInRange:replacementText:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"textView:shouldChangeTextInRange:replacementText:"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageInputBar~1textView(_:shouldChangeTextIn:replacementText:)\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}