{"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"towards","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/BubbleTowards","kind":"typeIdentifier","text":"BubbleTowards","preciseIdentifier":"c:@M@ShengwangChatUIKit@E@BubbleTowards"},{"text":" { get }","kind":"text"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/shengwangchatuikit\/contactcardview\/towards"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"symbolKind":"property","roleHeading":"Instance Property","modules":[{"name":"ShengwangChatUIKit"}],"title":"towards","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"towards"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@E@BubbleTowards","text":"BubbleTowards"}],"externalID":"s:18ShengwangChatUIKit15ContactCardViewC7towardsAA13BubbleTowardsOvp"},"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactCardView"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactCardView\/towards"},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ContactCardView":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ContactCardView","kind":"identifier"}],"kind":"symbol","abstract":[],"type":"topic","url":"\/documentation\/shengwangchatuikit\/contactcardview","title":"ContactCardView","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactCardView","navigatorTitle":[{"kind":"identifier","text":"ContactCardView"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/BubbleTowards":{"navigatorTitle":[{"kind":"identifier","text":"BubbleTowards"}],"abstract":[],"kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/BubbleTowards","url":"\/documentation\/shengwangchatuikit\/bubbletowards","title":"BubbleTowards","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"BubbleTowards"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ContactCardView/towards":{"abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"towards","kind":"identifier"},{"text":": ","kind":"text"},{"text":"BubbleTowards","preciseIdentifier":"c:@M@ShengwangChatUIKit@E@BubbleTowards","kind":"typeIdentifier"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactCardView\/towards","kind":"symbol","url":"\/documentation\/shengwangchatuikit\/contactcardview\/towards","role":"symbol","type":"topic","title":"towards"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactCardView\/title","op":"replace","value":"ContactCardView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactCardView\/fragments","value":[{"kind":"identifier","text":"ContactCardView"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactCardView\/navigatorTitle","value":[{"kind":"identifier","text":"ContactCardView"}],"op":"replace"},{"op":"replace","value":"BubbleTowards","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1BubbleTowards\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1BubbleTowards\/fragments","value":[{"kind":"identifier","text":"BubbleTowards"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1BubbleTowards\/navigatorTitle","value":[{"kind":"identifier","text":"BubbleTowards"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}