{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"attributedText","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSAttributedString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSAttributedString"},{"text":"! { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/shengwangchatuikit\/placeholdertextview\/attributedtext"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/placeholdertextview\/attributedtext"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PlaceHolderTextView"]]},"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PlaceHolderTextView\/attributedText","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"navigatorTitle":[{"text":"attributedText","kind":"identifier"}],"roleHeading":"Instance Property","externalID":"c:@M@ShengwangChatUIKit@objc(cs)PlaceHolderTextView(py)attributedText","modules":[{"name":"ShengwangChatUIKit"}],"role":"symbol","symbolKind":"property","title":"attributedText","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"attributedText","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSAttributedString","preciseIdentifier":"c:objc(cs)NSAttributedString","kind":"typeIdentifier"},{"text":"!","kind":"text"}]},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/PlaceHolderTextView":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PlaceHolderTextView","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PlaceHolderTextView","kind":"identifier"}],"navigatorTitle":[{"text":"PlaceHolderTextView","kind":"identifier"}],"abstract":[{"text":"A subclass of UITextView that provides a placeholder text when the text view is empty.","type":"text"}],"url":"\/documentation\/shengwangchatuikit\/placeholdertextview","type":"topic","role":"symbol","title":"PlaceHolderTextView"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/PlaceHolderTextView/attributedText":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"attributedText","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSAttributedString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSAttributedString"},{"kind":"text","text":"!"}],"type":"topic","role":"symbol","abstract":[],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"attributedText"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PlaceHolderTextView\/attributedText","url":"\/documentation\/shengwangchatuikit\/placeholdertextview\/attributedtext","title":"attributedText"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"attributedText","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"value":[{"text":"attributedText","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":") "},{"text":"NSAttributedString","preciseIdentifier":"c:objc(cs)NSAttributedString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"attributedText","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PlaceHolderTextView\/title","op":"replace","value":"PlaceHolderTextView"},{"value":[{"text":"PlaceHolderTextView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PlaceHolderTextView\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PlaceHolderTextView\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"PlaceHolderTextView"}]},{"value":"attributedText","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PlaceHolderTextView~1attributedText\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PlaceHolderTextView~1attributedText\/fragments","op":"replace","value":[{"kind":"identifier","text":"attributedText"}]}]}]}