{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListView\/IMessageListViewDriver-Implementations"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/messagelistview\/imessagelistviewdriver-implementations"]},{"paths":["\/documentation\/shengwangchatuikit\/messagelistview\/imessagelistviewdriver-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"topicSections":[{"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListView\/dataSource","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListView\/firstMessageId","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListView\/replyMessageId","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListView\/scrolledBottom"],"generated":true},{"generated":true,"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListView\/addMentionUserToField(user:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListView\/endRefreshing()","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListView\/highlightMessage(message:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListView\/insertMessages(messages:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListView\/processMessage(operation:message:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListView\/readAllMessages()","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListView\/refreshMessages(messages:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListView\/reloadReaction(message:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListView\/reloadTopic(message:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListView\/showMessage(message:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListView\/stopAudioMessagesPlay()","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListView\/updateAudioMessageStatus(message:play:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListView\/updateGroupMessageChatThreadChanged(message:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListView\/updateMessageAttachmentStatus(message:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListView\/updateMessageStatus(message:status:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListView\/updateThreadLoadMessagesFinished(finished:)"],"anchor":"Instance-Methods"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"modules":[{"name":"ShengwangChatUIKit"}],"roleHeading":"API Collection","role":"collectionGroup","title":"IMessageListViewDriver Implementations"},"sections":[],"kind":"article","hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListView"]]},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageListView/scrolledBottom":{"url":"\/documentation\/shengwangchatuikit\/messagelistview\/scrolledbottom","title":"scrolledBottom","role":"symbol","navigatorTitle":[{"text":"scrolledBottom","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListView\/scrolledBottom","abstract":[{"text":"Whether scroll view is scrolled to bottom.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"scrolledBottom","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageListView/processMessage(operation:message:)":{"kind":"symbol","url":"\/documentation\/shengwangchatuikit\/messagelistview\/processmessage(operation:message:)","abstract":[{"text":"Process messages according to operation type.","type":"text"}],"role":"symbol","title":"processMessage(operation:message:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"processMessage"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"operation"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@E@MessageOperation","text":"MessageOperation","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"message","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:18ShengwangChatUIKit0B7Messagea","text":"ChatMessage","kind":"typeIdentifier"},{"kind":"text","text":")"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListView\/processMessage(operation:message:)","navigatorTitle":[{"text":"processMessageWithOperation:message:","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageListView/updateThreadLoadMessagesFinished(finished:)":{"navigatorTitle":[{"kind":"identifier","text":"updateThreadLoadMessagesFinishedWithFinished:"}],"title":"updateThreadLoadMessagesFinished(finished:)","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListView\/updateThreadLoadMessagesFinished(finished:)","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"updateThreadLoadMessagesFinished","kind":"identifier"},{"kind":"text","text":"("},{"text":"finished","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","abstract":[{"text":"Update state on chat thread load messages finished.","type":"text"}],"url":"\/documentation\/shengwangchatuikit\/messagelistview\/updatethreadloadmessagesfinished(finished:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageListView/insertMessages(messages:)":{"type":"topic","navigatorTitle":[{"text":"insertMessagesWithMessages:","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListView\/insertMessages(messages:)","kind":"symbol","title":"insertMessages(messages:)","abstract":[{"text":"Message list pull to load more db messages.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"insertMessages"},{"kind":"text","text":"("},{"text":"messages","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"ChatMessage","kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit0B7Messagea"},{"kind":"text","text":"])"}],"url":"\/documentation\/shengwangchatuikit\/messagelistview\/insertmessages(messages:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageListView/updateMessageStatus(message:status:)":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListView\/updateMessageStatus(message:status:)","role":"symbol","title":"updateMessageStatus(message:status:)","abstract":[{"text":"Update message.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"updateMessageStatus","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"message"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit0B7Messagea","text":"ChatMessage"},{"text":", ","kind":"text"},{"text":"status","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@E@ChatMessageStatus","text":"ChatMessageStatus","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/shengwangchatuikit\/messagelistview\/updatemessagestatus(message:status:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"updateMessageStatusWithMessage:status:"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageListView/endRefreshing()":{"kind":"symbol","url":"\/documentation\/shengwangchatuikit\/messagelistview\/endrefreshing()","abstract":[{"text":"Update state on chat thread load messages finished.","type":"text"}],"role":"symbol","title":"endRefreshing()","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"endRefreshing","kind":"identifier"},{"text":"()","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListView\/endRefreshing()","navigatorTitle":[{"text":"endRefreshing","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageListView/refreshMessages(messages:)":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListView\/refreshMessages(messages:)","role":"symbol","title":"refreshMessages(messages:)","abstract":[{"text":"Message list on first load show db messages .","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"refreshMessages"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"messages"},{"text":": [","kind":"text"},{"text":"ChatMessage","kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit0B7Messagea"},{"text":"])","kind":"text"}],"url":"\/documentation\/shengwangchatuikit\/messagelistview\/refreshmessages(messages:)","kind":"symbol","navigatorTitle":[{"text":"refreshMessagesWithMessages:","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageListView/showMessage(message:)":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListView\/showMessage(message:)","role":"symbol","url":"\/documentation\/shengwangchatuikit\/messagelistview\/showmessage(message:)","title":"showMessage(message:)","kind":"symbol","abstract":[{"text":"Display new message.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"showMessage","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"message"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"ChatMessage","preciseIdentifier":"s:18ShengwangChatUIKit0B7Messagea"},{"kind":"text","text":")"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"showMessageWithMessage:"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageListView/stopAudioMessagesPlay()":{"kind":"symbol","role":"symbol","title":"stopAudioMessagesPlay()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"stopAudioMessagesPlay"},{"kind":"text","text":"()"}],"navigatorTitle":[{"kind":"identifier","text":"stopAudioMessagesPlay"}],"type":"topic","url":"\/documentation\/shengwangchatuikit\/messagelistview\/stopaudiomessagesplay()","abstract":[{"type":"text","text":"Stop audio messages play."}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListView\/stopAudioMessagesPlay()"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageListView/highlightMessage(message:)":{"kind":"symbol","url":"\/documentation\/shengwangchatuikit\/messagelistview\/highlightmessage(message:)","abstract":[{"type":"text","text":"Highlight message on message list."}],"role":"symbol","title":"highlightMessage(message:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"highlightMessage","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"message"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit0B7Messagea","text":"ChatMessage"},{"kind":"text","text":")"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListView\/highlightMessage(message:)","navigatorTitle":[{"kind":"identifier","text":"highlightMessageWithMessage:"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageListView/firstMessageId":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListView\/firstMessageId","role":"symbol","title":"firstMessageId","abstract":[{"type":"text","text":"Latest message id."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"firstMessageId"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"url":"\/documentation\/shengwangchatuikit\/messagelistview\/firstmessageid","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"firstMessageId"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageListView/dataSource":{"kind":"symbol","url":"\/documentation\/shengwangchatuikit\/messagelistview\/datasource","abstract":[],"role":"symbol","title":"dataSource","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dataSource"},{"kind":"text","text":": ["},{"text":"ChatMessage","preciseIdentifier":"s:18ShengwangChatUIKit0B7Messagea","kind":"typeIdentifier"},{"kind":"text","text":"]"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListView\/dataSource","navigatorTitle":[{"kind":"identifier","text":"dataSource"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageListView/updateGroupMessageChatThreadChanged(message:)":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListView\/updateGroupMessageChatThreadChanged(message:)","role":"symbol","title":"updateGroupMessageChatThreadChanged(message:)","abstract":[{"type":"text","text":"Chat thread of the group message on changed."}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateGroupMessageChatThreadChanged"},{"kind":"text","text":"("},{"text":"message","kind":"externalParam"},{"kind":"text","text":": "},{"text":"ChatMessage","preciseIdentifier":"s:18ShengwangChatUIKit0B7Messagea","kind":"typeIdentifier"},{"kind":"text","text":")"}],"url":"\/documentation\/shengwangchatuikit\/messagelistview\/updategroupmessagechatthreadchanged(message:)","kind":"symbol","navigatorTitle":[{"text":"updateGroupMessageChatThreadChangedWithMessage:","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageListView/replyMessageId":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListView\/replyMessageId","role":"symbol","title":"replyMessageId","abstract":[{"type":"text","text":"Reply message id."}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"replyMessageId","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"url":"\/documentation\/shengwangchatuikit\/messagelistview\/replymessageid","kind":"symbol","navigatorTitle":[{"text":"replyMessageId","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageListView/reloadTopic(message:)":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListView\/reloadTopic(message:)","url":"\/documentation\/shengwangchatuikit\/messagelistview\/reloadtopic(message:)","type":"topic","navigatorTitle":[{"kind":"identifier","text":"reloadTopicWithMessage:"}],"abstract":[{"type":"text","text":"Reload topic content"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"reloadTopic","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"message"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit0B7Messagea","text":"ChatMessage"},{"kind":"text","text":")"}],"kind":"symbol","role":"symbol","title":"reloadTopic(message:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageListView/reloadReaction(message:)":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListView\/reloadReaction(message:)","role":"symbol","title":"reloadReaction(message:)","abstract":[{"type":"text","text":"Reload reaction content."}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"reloadReaction"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"text":"ChatMessage","preciseIdentifier":"s:18ShengwangChatUIKit0B7Messagea","kind":"typeIdentifier"},{"kind":"text","text":")"}],"url":"\/documentation\/shengwangchatuikit\/messagelistview\/reloadreaction(message:)","kind":"symbol","navigatorTitle":[{"text":"reloadReactionWithMessage:","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageListView/addMentionUserToField(user:)":{"type":"topic","role":"symbol","title":"addMentionUserToField(user:)","kind":"symbol","abstract":[{"type":"text","text":"Add mention user to textfield on needed."}],"navigatorTitle":[{"text":"addMentionUserToFieldWithUser:","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/messagelistview\/addmentionusertofield(user:)","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListView\/addMentionUserToField(user:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"addMentionUserToField","kind":"identifier"},{"text":"(","kind":"text"},{"text":"user","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"ChatUserProfileProtocol","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(pl)ChatUserProfileProtocol"},{"text":")","kind":"text"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageListView/readAllMessages()":{"kind":"symbol","url":"\/documentation\/shengwangchatuikit\/messagelistview\/readallmessages()","role":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"readAllMessages"},{"kind":"text","text":"()"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListView\/readAllMessages()","title":"readAllMessages()","navigatorTitle":[{"kind":"identifier","text":"readAllMessages"}],"abstract":[{"type":"text","text":"Update message on message list."}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageListView/updateMessageAttachmentStatus(message:)":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListView\/updateMessageAttachmentStatus(message:)","navigatorTitle":[{"text":"updateMessageAttachmentStatusWithMessage:","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Update status on message attachment state changed."}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateMessageAttachmentStatus"},{"text":"(","kind":"text"},{"text":"message","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ChatMessage","preciseIdentifier":"s:18ShengwangChatUIKit0B7Messagea","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"updateMessageAttachmentStatus(message:)","kind":"symbol","url":"\/documentation\/shengwangchatuikit\/messagelistview\/updatemessageattachmentstatus(message:)","role":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageListView":{"abstract":[],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MessageListView"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListView","navigatorTitle":[{"kind":"identifier","text":"MessageListView"}],"title":"MessageListView","role":"symbol","kind":"symbol","url":"\/documentation\/shengwangchatuikit\/messagelistview"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageListView/updateAudioMessageStatus(message:play:)":{"kind":"symbol","url":"\/documentation\/shengwangchatuikit\/messagelistview\/updateaudiomessagestatus(message:play:)","role":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"updateAudioMessageStatus","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"preciseIdentifier":"s:18ShengwangChatUIKit0B7Messagea","kind":"typeIdentifier","text":"ChatMessage"},{"text":", ","kind":"text"},{"text":"play","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListView\/updateAudioMessageStatus(message:play:)","title":"updateAudioMessageStatus(message:play:)","navigatorTitle":[{"text":"updateAudioMessageStatusWithMessage:play:","kind":"identifier"}],"abstract":[{"type":"text","text":"Update audio message  on play status changed."}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":[{"title":"Instance Properties","generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListView\/dataSource","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListView\/firstMessageId","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListView\/replyMessageId","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListView\/scrolledBottom"]},{"generated":true,"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListView\/addMentionUserToField(user:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListView\/endRefreshing()","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListView\/highlightMessage(message:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListView\/insertMessages(messages:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListView\/processMessage(operation:message:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListView\/readAllMessages()","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListView\/refreshMessages(messages:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListView\/reloadReaction(message:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListView\/reloadTopic(message:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListView\/showMessage(message:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListView\/stopAudioMessagesPlay()","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListView\/updateAudioMessageStatus(message:play:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListView\/updateGroupMessageChatThreadChanged(message:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListView\/updateMessageAttachmentStatus(message:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListView\/updateMessageStatus(message:status:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListView\/updateThreadLoadMessagesFinished(finished:)"],"title":"Instance Methods","anchor":"Instance-Methods"}],"path":"\/topicSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":"scrolledBottom","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListView~1scrolledBottom\/title"},{"value":[{"kind":"identifier","text":"scrolledBottom"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListView~1scrolledBottom\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListView~1processMessage(operation:message:)\/title","value":"processMessageWithOperation:message:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListView~1processMessage(operation:message:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"processMessageWithOperation:message:","kind":"identifier"}]},{"op":"replace","value":"updateThreadLoadMessagesFinishedWithFinished:","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListView~1updateThreadLoadMessagesFinished(finished:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListView~1updateThreadLoadMessagesFinished(finished:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"updateThreadLoadMessagesFinishedWithFinished:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListView~1insertMessages(messages:)\/title","op":"replace","value":"insertMessagesWithMessages:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"insertMessagesWithMessages:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListView~1insertMessages(messages:)\/fragments"},{"value":"updateMessageStatusWithMessage:status:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListView~1updateMessageStatus(message:status:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListView~1updateMessageStatus(message:status:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"updateMessageStatusWithMessage:status:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListView~1endRefreshing()\/title","value":"endRefreshing"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"endRefreshing"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListView~1endRefreshing()\/fragments"},{"value":"refreshMessagesWithMessages:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListView~1refreshMessages(messages:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"refreshMessagesWithMessages:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListView~1refreshMessages(messages:)\/fragments"},{"value":"showMessageWithMessage:","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListView~1showMessage(message:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"showMessageWithMessage:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListView~1showMessage(message:)\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListView~1stopAudioMessagesPlay()\/title","value":"stopAudioMessagesPlay","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListView~1stopAudioMessagesPlay()\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"stopAudioMessagesPlay"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListView~1highlightMessage(message:)\/title","value":"highlightMessageWithMessage:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListView~1highlightMessage(message:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"highlightMessageWithMessage:"}]},{"value":"firstMessageId","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListView~1firstMessageId\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListView~1firstMessageId\/fragments","value":[{"kind":"identifier","text":"firstMessageId"}],"op":"replace"},{"value":"dataSource","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListView~1dataSource\/title","op":"replace"},{"value":[{"text":"dataSource","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListView~1dataSource\/fragments"},{"value":"updateGroupMessageChatThreadChangedWithMessage:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListView~1updateGroupMessageChatThreadChanged(message:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"updateGroupMessageChatThreadChangedWithMessage:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListView~1updateGroupMessageChatThreadChanged(message:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListView~1replyMessageId\/title","op":"replace","value":"replyMessageId"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListView~1replyMessageId\/fragments","value":[{"kind":"identifier","text":"replyMessageId"}]},{"value":"reloadTopicWithMessage:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListView~1reloadTopic(message:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListView~1reloadTopic(message:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"reloadTopicWithMessage:","kind":"identifier"}]},{"op":"replace","value":"reloadReactionWithMessage:","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListView~1reloadReaction(message:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListView~1reloadReaction(message:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"reloadReactionWithMessage:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListView~1addMentionUserToField(user:)\/title","op":"replace","value":"addMentionUserToFieldWithUser:"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListView~1addMentionUserToField(user:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"addMentionUserToFieldWithUser:","kind":"identifier"}]},{"op":"replace","value":"readAllMessages","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListView~1readAllMessages()\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListView~1readAllMessages()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"readAllMessages"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListView~1updateMessageAttachmentStatus(message:)\/title","value":"updateMessageAttachmentStatusWithMessage:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListView~1updateMessageAttachmentStatus(message:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"updateMessageAttachmentStatusWithMessage:"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListView\/title","op":"replace","value":"MessageListView"},{"value":[{"kind":"identifier","text":"MessageListView"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListView\/fragments"},{"value":[{"kind":"identifier","text":"MessageListView"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListView\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListView~1updateAudioMessageStatus(message:play:)\/title","value":"updateAudioMessageStatusWithMessage:play:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"updateAudioMessageStatusWithMessage:play:"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListView~1updateAudioMessageStatus(message:play:)\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}