{"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListView\/removeEventHandler(actionHandler:)","interfaceLanguage":"swift"},"abstract":[{"text":"Remove UI action handler.","type":"text"}],"metadata":{"modules":[{"name":"ShengwangChatUIKit"}],"roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"removeEventHandler","kind":"identifier"},{"kind":"text","text":"("},{"text":"actionHandler","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MessageListViewActionEventsDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(pl)MessageListViewActionEventsDelegate"},{"text":")","kind":"text"}],"title":"removeEventHandler(actionHandler:)","role":"symbol","navigatorTitle":[{"text":"removeEventHandlerWithActionHandler:","kind":"identifier"}],"externalID":"c:@M@ShengwangChatUIKit@objc(cs)MessageListView(im)removeEventHandlerWithActionHandler:","symbolKind":"method"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/messagelistview\/removeeventhandler(actionhandler:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/messagelistview\/removeeventhandler(actionhandler:)"]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeEventHandler"},{"kind":"text","text":"("},{"text":"actionHandler","kind":"externalParam"},{"kind":"text","text":": "},{"text":"MessageListViewActionEventsDelegate","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewActionEventsDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(pl)MessageListViewActionEventsDelegate"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewActionEventsDelegate"}]}],"name":"actionHandler"}],"kind":"parameters"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListView"]]},"sections":[],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageListView/removeEventHandler(actionHandler:)":{"abstract":[{"text":"Remove UI action handler.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListView\/removeEventHandler(actionHandler:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeEventHandler"},{"text":"(","kind":"text"},{"text":"actionHandler","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(pl)MessageListViewActionEventsDelegate","text":"MessageListViewActionEventsDelegate"},{"text":")","kind":"text"}],"type":"topic","title":"removeEventHandler(actionHandler:)","navigatorTitle":[{"text":"removeEventHandlerWithActionHandler:","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/messagelistview\/removeeventhandler(actionhandler:)","role":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageListView":{"abstract":[],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MessageListView"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListView","navigatorTitle":[{"kind":"identifier","text":"MessageListView"}],"title":"MessageListView","role":"symbol","kind":"symbol","url":"\/documentation\/shengwangchatuikit\/messagelistview"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageListViewActionEventsDelegate":{"navigatorTitle":[{"text":"MessageListViewActionEventsDelegate","kind":"identifier"}],"title":"MessageListViewActionEventsDelegate","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewActionEventsDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"MessageListViewActionEventsDelegate","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/messagelistviewactioneventsdelegate","abstract":[],"kind":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"removeEventHandlerWithActionHandler:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"removeEventHandlerWithActionHandler:"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"removeEventHandlerWithActionHandler:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Qo@M@ShengwangChatUIKit@objc(pl)MessageListViewActionEventsDelegate","kind":"typeIdentifier","text":"id<MessageListViewActionEventsDelegate>"},{"kind":"text","text":") "},{"text":"actionHandler","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}},{"value":{"kind":"parameters","parameters":[{"name":"actionHandler","content":[{"inlineContent":[{"type":"text","text":""},{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListViewActionEventsDelegate","type":"reference","isActive":true}],"type":"paragraph"}]}]},"op":"replace","path":"\/primaryContentSections\/1"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListView~1removeEventHandler(actionHandler:)\/title","op":"replace","value":"removeEventHandlerWithActionHandler:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"removeEventHandlerWithActionHandler:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListView~1removeEventHandler(actionHandler:)\/fragments"},{"value":"MessageListView","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListView\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListView\/fragments","op":"replace","value":[{"text":"MessageListView","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListView\/navigatorTitle","value":[{"text":"MessageListView","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewActionEventsDelegate\/title","op":"replace","value":"MessageListViewActionEventsDelegate"},{"op":"replace","value":[{"text":"MessageListViewActionEventsDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewActionEventsDelegate\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListViewActionEventsDelegate\/navigatorTitle","value":[{"text":"MessageListViewActionEventsDelegate","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}