{"metadata":{"title":"replyBar","roleHeading":"Instance Property","symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"replyBar","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MessageInputReplyView","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)MessageInputReplyView","kind":"typeIdentifier"}],"role":"symbol","externalID":"s:18ShengwangChatUIKit15MessageListViewC8replyBarAA0d10InputReplyF0Cvp","modules":[{"name":"ShengwangChatUIKit"}]},"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"lazy","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"replyBar","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageInputReplyView","kind":"typeIdentifier","text":"MessageInputReplyView","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)MessageInputReplyView"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListView\/replyBar","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListView"]]},"variants":[{"paths":["\/documentation\/shengwangchatuikit\/messagelistview\/replybar"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageListView/replyBar":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"replyBar","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)MessageInputReplyView","text":"MessageInputReplyView","kind":"typeIdentifier"}],"url":"\/documentation\/shengwangchatuikit\/messagelistview\/replybar","abstract":[],"title":"replyBar","type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListView\/replyBar","role":"symbol","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageInputReplyView":{"kind":"symbol","url":"\/documentation\/shengwangchatuikit\/messageinputreplyview","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageInputReplyView"}],"navigatorTitle":[{"kind":"identifier","text":"MessageInputReplyView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageInputReplyView","title":"MessageInputReplyView","role":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageListView":{"abstract":[],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MessageListView"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListView","navigatorTitle":[{"kind":"identifier","text":"MessageListView"}],"title":"MessageListView","role":"symbol","kind":"symbol","url":"\/documentation\/shengwangchatuikit\/messagelistview"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageInputReplyView\/title","op":"replace","value":"MessageInputReplyView"},{"value":[{"text":"MessageInputReplyView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageInputReplyView\/fragments"},{"value":[{"text":"MessageInputReplyView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageInputReplyView\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListView\/title","value":"MessageListView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListView\/fragments","value":[{"text":"MessageListView","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListView\/navigatorTitle","value":[{"kind":"identifier","text":"MessageListView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}