{"variants":[{"paths":["\/documentation\/shengwangchatuikit\/messagelistview\/scrollviewdidscrolltotop(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/shengwangchatuikit\/messagelistview\/scrollviewdidscrolltotop(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"Inherited from "},{"code":"UIScrollViewDelegate.scrollViewDidScrollToTop(_:)","type":"codeVoice"},{"text":".","type":"text"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","kind":"attribute","text":"MainActor"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"scrollViewDidScrollToTop"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"scrollView","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"UIScrollView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIScrollView"},{"text":")","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"title":"scrollViewDidScrollToTop(_:)","role":"symbol","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"scrollViewDidScrollToTop:"}],"modules":[{"name":"ShengwangChatUIKit"}],"roleHeading":"Instance Method","externalID":"c:@M@ShengwangChatUIKit@objc(cs)MessageListView(im)scrollViewDidScrollToTop:","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"scrollViewDidScrollToTop"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIScrollView","text":"UIScrollView"},{"kind":"text","text":")"}]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListView\/scrollViewDidScrollToTop(_:)"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListView"]]},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageListView":{"abstract":[],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MessageListView"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListView","navigatorTitle":[{"kind":"identifier","text":"MessageListView"}],"title":"MessageListView","role":"symbol","kind":"symbol","url":"\/documentation\/shengwangchatuikit\/messagelistview"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageListView/scrollViewDidScrollToTop(_:)":{"kind":"symbol","url":"\/documentation\/shengwangchatuikit\/messagelistview\/scrollviewdidscrolltotop(_:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"scrollViewDidScrollToTop:"}],"type":"topic","title":"scrollViewDidScrollToTop(_:)","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListView\/scrollViewDidScrollToTop(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"scrollViewDidScrollToTop"},{"kind":"text","text":"("},{"text":"UIScrollView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIScrollView"},{"text":")","kind":"text"}],"abstract":[]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"scrollViewDidScrollToTop:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"scrollViewDidScrollToTop:","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"scrollViewDidScrollToTop:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIScrollView","text":"UIScrollView","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"scrollView","kind":"internalParam"},{"kind":"text","text":";"}]}]}},{"op":"replace","value":"MessageListView","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListView\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListView\/fragments","value":[{"text":"MessageListView","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListView\/navigatorTitle","op":"replace","value":[{"text":"MessageListView","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListView~1scrollViewDidScrollToTop(_:)\/title","value":"scrollViewDidScrollToTop:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"scrollViewDidScrollToTop:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListView~1scrollViewDidScrollToTop(_:)\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}