{"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"navigatorTitle":[{"text":"MessageBubbleDisplayStyleWithArrow","kind":"identifier"}],"externalID":"c:@M@ShengwangChatUIKit@E@MessageBubbleDisplayStyle@MessageBubbleDisplayStyleWithArrow","title":"MessageBubbleDisplayStyle.withArrow","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"withArrow"}],"modules":[{"name":"ShengwangChatUIKit"}],"symbolKind":"case","role":"symbol","roleHeading":"Case"},"sections":[],"variants":[{"paths":["\/documentation\/shengwangchatuikit\/messagebubbledisplaystyle\/witharrow"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/messagebubbledisplaystyle\/witharrow"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageBubbleDisplayStyle"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"withArrow","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageBubbleDisplayStyle\/withArrow","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageBubbleDisplayStyle":{"type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"MessageBubbleDisplayStyle","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageBubbleDisplayStyle","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MessageBubbleDisplayStyle"}],"role":"symbol","title":"MessageBubbleDisplayStyle","url":"\/documentation\/shengwangchatuikit\/messagebubbledisplaystyle","abstract":[]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageBubbleDisplayStyle/withArrow":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageBubbleDisplayStyle\/withArrow","url":"\/documentation\/shengwangchatuikit\/messagebubbledisplaystyle\/witharrow","role":"symbol","title":"MessageBubbleDisplayStyle.withArrow","abstract":[],"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"withArrow","kind":"identifier"}],"navigatorTitle":[{"text":"MessageBubbleDisplayStyleWithArrow","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"MessageBubbleDisplayStyleWithArrow","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"MessageBubbleDisplayStyleWithArrow","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"MessageBubbleDisplayStyleWithArrow","kind":"identifier"}],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageBubbleDisplayStyle\/title","value":"MessageBubbleDisplayStyle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageBubbleDisplayStyle\/fragments","value":[{"text":"MessageBubbleDisplayStyle","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageBubbleDisplayStyle\/navigatorTitle","value":[{"kind":"identifier","text":"MessageBubbleDisplayStyle"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageBubbleDisplayStyle~1withArrow\/title","value":"MessageBubbleDisplayStyleWithArrow","op":"replace"},{"op":"replace","value":[{"text":"MessageBubbleDisplayStyleWithArrow","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageBubbleDisplayStyle~1withArrow\/fragments"}]}]}