{"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/messagebubbledisplaystyle\/withmulticorner"]},{"paths":["\/documentation\/shengwangchatuikit\/messagebubbledisplaystyle\/withmulticorner"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","metadata":{"role":"symbol","externalID":"c:@M@ShengwangChatUIKit@E@MessageBubbleDisplayStyle@MessageBubbleDisplayStyleWithMultiCorner","roleHeading":"Case","title":"MessageBubbleDisplayStyle.withMultiCorner","modules":[{"name":"ShengwangChatUIKit"}],"symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"withMultiCorner"}],"navigatorTitle":[{"text":"MessageBubbleDisplayStyleWithMultiCorner","kind":"identifier"}]},"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageBubbleDisplayStyle\/withMultiCorner","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageBubbleDisplayStyle"]]},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"withMultiCorner"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageBubbleDisplayStyle/withMultiCorner":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageBubbleDisplayStyle\/withMultiCorner","url":"\/documentation\/shengwangchatuikit\/messagebubbledisplaystyle\/withmulticorner","role":"symbol","title":"MessageBubbleDisplayStyle.withMultiCorner","abstract":[],"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"withMultiCorner","kind":"identifier"}],"navigatorTitle":[{"text":"MessageBubbleDisplayStyleWithMultiCorner","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageBubbleDisplayStyle":{"type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"MessageBubbleDisplayStyle","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageBubbleDisplayStyle","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MessageBubbleDisplayStyle"}],"role":"symbol","title":"MessageBubbleDisplayStyle","url":"\/documentation\/shengwangchatuikit\/messagebubbledisplaystyle","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"value":"MessageBubbleDisplayStyleWithMultiCorner","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"MessageBubbleDisplayStyleWithMultiCorner","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"MessageBubbleDisplayStyleWithMultiCorner","kind":"identifier"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageBubbleDisplayStyle~1withMultiCorner\/title","value":"MessageBubbleDisplayStyleWithMultiCorner"},{"value":[{"text":"MessageBubbleDisplayStyleWithMultiCorner","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageBubbleDisplayStyle~1withMultiCorner\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageBubbleDisplayStyle\/title","value":"MessageBubbleDisplayStyle"},{"op":"replace","value":[{"text":"MessageBubbleDisplayStyle","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageBubbleDisplayStyle\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageBubbleDisplayStyle\/navigatorTitle","value":[{"kind":"identifier","text":"MessageBubbleDisplayStyle"}],"op":"replace"}]}]}