{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/multideviceservice\/bindmultidevicelistener(listener:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/multideviceservice\/bindmultidevicelistener(listener:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bindMultiDeviceListener"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"listener"},{"kind":"text","text":": "},{"text":"MultiDeviceListener","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(pl)MultiDeviceListener","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MultiDeviceListener"},{"kind":"text","text":")"}]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"reference","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MultiDeviceListener","isActive":true}]}],"name":"listener"}],"kind":"parameters"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MultiDeviceService"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MultiDeviceService\/bindMultiDeviceListener(listener:)"},"kind":"symbol","metadata":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"bindMultiDeviceListener"},{"text":"(","kind":"text"},{"text":"listener","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MultiDeviceListener","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(pl)MultiDeviceListener"},{"kind":"text","text":")"}],"externalID":"c:@M@ShengwangChatUIKit@objc(pl)MultiDeviceService(im)bindMultiDeviceListenerWithListener:","required":true,"navigatorTitle":[{"kind":"identifier","text":"bindMultiDeviceListenerWithListener:"}],"roleHeading":"Instance Method","role":"symbol","modules":[{"name":"ShengwangChatUIKit"}],"title":"bindMultiDeviceListener(listener:)","symbolKind":"method"},"abstract":[{"text":"Bind multi device changed listener","type":"text"}],"sections":[],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MultiDeviceListener":{"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MultiDeviceListener"}],"abstract":[],"type":"topic","title":"MultiDeviceListener","url":"\/documentation\/shengwangchatuikit\/multidevicelistener","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"MultiDeviceListener","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MultiDeviceListener"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MultiDeviceService":{"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MultiDeviceService"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MultiDeviceService","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MultiDeviceService"}],"role":"symbol","title":"MultiDeviceService","url":"\/documentation\/shengwangchatuikit\/multideviceservice","abstract":[]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MultiDeviceService/bindMultiDeviceListener(listener:)":{"title":"bindMultiDeviceListener(listener:)","type":"topic","url":"\/documentation\/shengwangchatuikit\/multideviceservice\/bindmultidevicelistener(listener:)","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MultiDeviceService\/bindMultiDeviceListener(listener:)","kind":"symbol","abstract":[{"type":"text","text":"Bind multi device changed listener"}],"required":true,"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"bindMultiDeviceListener","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"listener"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(pl)MultiDeviceListener","kind":"typeIdentifier","text":"MultiDeviceListener"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"bindMultiDeviceListenerWithListener:"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"bindMultiDeviceListenerWithListener:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"bindMultiDeviceListenerWithListener:","kind":"identifier"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"bindMultiDeviceListenerWithListener:"},{"kind":"text","text":"("},{"text":"id<MultiDeviceListener>","kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@ShengwangChatUIKit@objc(pl)MultiDeviceListener"},{"text":") ","kind":"text"},{"text":"listener","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/primaryContentSections\/1","op":"replace","value":{"parameters":[{"name":"listener","content":[{"inlineContent":[{"type":"text","text":""},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MultiDeviceListener"}],"type":"paragraph"}]}],"kind":"parameters"}},{"value":"MultiDeviceListener","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MultiDeviceListener\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"MultiDeviceListener"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MultiDeviceListener\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MultiDeviceListener\/navigatorTitle","value":[{"text":"MultiDeviceListener","kind":"identifier"}]},{"value":"MultiDeviceService","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MultiDeviceService\/title"},{"value":[{"kind":"identifier","text":"MultiDeviceService"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MultiDeviceService\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MultiDeviceService\/navigatorTitle","value":[{"text":"MultiDeviceService","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MultiDeviceService~1bindMultiDeviceListener(listener:)\/title","value":"bindMultiDeviceListenerWithListener:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MultiDeviceService~1bindMultiDeviceListener(listener:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"bindMultiDeviceListenerWithListener:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}