{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatNavigationBar","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatNavigationBar\/UICollectionViewDataSource-Implementations"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"collectionView","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"collectionView"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UICollectionView","text":"UICollectionView"},{"text":", ","kind":"text"},{"text":"numberOfItemsInSection","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"section","kind":"internalParam"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/chatnavigationbar\/collectionview(_:numberofitemsinsection:)"]},{"paths":["\/documentation\/shengwangchatuikit\/chatnavigationbar\/collectionview(_:numberofitemsinsection:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatNavigationBar\/collectionView(_:numberOfItemsInSection:)"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"UICollectionViewDataSource.collectionView(_:numberOfItemsInSection:)"},{"type":"text","text":"."}],"metadata":{"title":"collectionView(_:numberOfItemsInSection:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"collectionView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UICollectionView","preciseIdentifier":"c:objc(cs)UICollectionView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"numberOfItemsInSection"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"modules":[{"name":"ShengwangChatUIKit"}],"externalID":"c:@CM@ShengwangChatUIKit@objc(cs)ChatNavigationBar(im)collectionView:numberOfItemsInSection:","extendedModule":"ShengwangChatUIKit","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"collectionView:numberOfItemsInSection:"}],"role":"symbol","roleHeading":"Instance Method"},"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatNavigationBar/UICollectionViewDataSource-Implementations":{"kind":"article","title":"UICollectionViewDataSource Implementations","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatNavigationBar\/UICollectionViewDataSource-Implementations","abstract":[],"role":"collectionGroup","type":"topic","url":"\/documentation\/shengwangchatuikit\/chatnavigationbar\/uicollectionviewdatasource-implementations"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatNavigationBar/collectionView(_:numberOfItemsInSection:)":{"type":"topic","role":"symbol","title":"collectionView(_:numberOfItemsInSection:)","kind":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"collectionView:numberOfItemsInSection:"}],"url":"\/documentation\/shengwangchatuikit\/chatnavigationbar\/collectionview(_:numberofitemsinsection:)","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatNavigationBar\/collectionView(_:numberOfItemsInSection:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"collectionView"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UICollectionView","text":"UICollectionView"},{"kind":"text","text":", "},{"text":"numberOfItemsInSection","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatNavigationBar":{"navigatorTitle":[{"kind":"identifier","text":"ChatNavigationBar"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatNavigationBar"}],"kind":"symbol","abstract":[{"type":"text","text":"Navigation  bar of the ChatUIKit."}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatNavigationBar","url":"\/documentation\/shengwangchatuikit\/chatnavigationbar","type":"topic","title":"ChatNavigationBar","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"collectionView:numberOfItemsInSection:","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"collectionView:numberOfItemsInSection:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"text":") ","kind":"text"},{"kind":"identifier","text":"collectionView:"},{"kind":"text","text":"("},{"text":"UICollectionView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UICollectionView"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"collectionView"},{"kind":"text","text":" "},{"text":"numberOfItemsInSection:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"text":") ","kind":"text"},{"text":"section","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatNavigationBar~1collectionView(_:numberOfItemsInSection:)\/title","value":"collectionView:numberOfItemsInSection:"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"collectionView:numberOfItemsInSection:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatNavigationBar~1collectionView(_:numberOfItemsInSection:)\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatNavigationBar\/title","value":"ChatNavigationBar","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatNavigationBar\/fragments","value":[{"kind":"identifier","text":"ChatNavigationBar"}],"op":"replace"},{"op":"replace","value":[{"text":"ChatNavigationBar","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatNavigationBar\/navigatorTitle"}]}]}