{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/chatnavigationbar\/init(coder:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/chatnavigationbar\/init(coder:)"]}],"metadata":{"roleHeading":"Initializer","navigatorTitle":[{"text":"initWithCoder:","kind":"identifier"}],"title":"init(coder:)","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"text":"coder","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSCoder","text":"NSCoder"},{"kind":"text","text":")"}],"externalID":"c:@M@ShengwangChatUIKit@objc(cs)ChatNavigationBar(im)initWithCoder:","modules":[{"name":"ShengwangChatUIKit"}],"symbolKind":"init"},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatNavigationBar\/init(coder:)"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatNavigationBar"]]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"text":"required","kind":"keyword"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"coder"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder"},{"kind":"text","text":")"}]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatNavigationBar/init(coder:)":{"kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"coder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder"},{"text":")","kind":"text"}],"abstract":[],"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatNavigationBar\/init(coder:)","url":"\/documentation\/shengwangchatuikit\/chatnavigationbar\/init(coder:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"title":"init(coder:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatNavigationBar":{"navigatorTitle":[{"kind":"identifier","text":"ChatNavigationBar"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatNavigationBar"}],"kind":"symbol","abstract":[{"type":"text","text":"Navigation  bar of the ChatUIKit."}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatNavigationBar","url":"\/documentation\/shengwangchatuikit\/chatnavigationbar","type":"topic","title":"ChatNavigationBar","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"initWithCoder:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"initWithCoder:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSCoder","text":"NSCoder"},{"text":" *) ","kind":"text"},{"text":"coder","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"value":"initWithCoder:","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatNavigationBar~1init(coder:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithCoder:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatNavigationBar~1init(coder:)\/fragments"},{"op":"replace","value":"ChatNavigationBar","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatNavigationBar\/title"},{"value":[{"kind":"identifier","text":"ChatNavigationBar"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatNavigationBar\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatNavigationBar\/navigatorTitle","value":[{"text":"ChatNavigationBar","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}