{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"override"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"kind":"externalParam","text":"frame"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGRect","kind":"typeIdentifier","text":"CGRect"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","variants":[{"paths":["\/documentation\/shengwangchatuikit\/chatnavigationbar\/init(frame:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/shengwangchatuikit\/chatnavigationbar\/init(frame:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"modules":[{"name":"ShengwangChatUIKit"}],"symbolKind":"init","navigatorTitle":[{"text":"initWithFrame:","kind":"identifier"}],"roleHeading":"Initializer","title":"init(frame:)","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"frame","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CGRect","text":"CGRect","kind":"typeIdentifier"},{"text":")","kind":"text"}],"externalID":"c:@M@ShengwangChatUIKit@objc(cs)ChatNavigationBar(im)initWithFrame:"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatNavigationBar"]]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatNavigationBar\/init(frame:)"},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatNavigationBar/init(frame:)":{"title":"init(frame:)","abstract":[],"navigatorTitle":[{"text":"initWithFrame:","kind":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatNavigationBar\/init(frame:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"frame","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGRect","kind":"typeIdentifier","text":"CGRect"},{"text":")","kind":"text"}],"role":"symbol","url":"\/documentation\/shengwangchatuikit\/chatnavigationbar\/init(frame:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatNavigationBar":{"navigatorTitle":[{"kind":"identifier","text":"ChatNavigationBar"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatNavigationBar"}],"kind":"symbol","abstract":[{"type":"text","text":"Navigation  bar of the ChatUIKit."}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatNavigationBar","url":"\/documentation\/shengwangchatuikit\/chatnavigationbar","type":"topic","title":"ChatNavigationBar","role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"initWithFrame:"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithFrame:","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithFrame:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect","text":"CGRect"},{"kind":"text","text":") "},{"text":"frame","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"initWithFrame:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatNavigationBar~1init(frame:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatNavigationBar~1init(frame:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithFrame:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatNavigationBar\/title","value":"ChatNavigationBar","op":"replace"},{"value":[{"text":"ChatNavigationBar","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatNavigationBar\/fragments","op":"replace"},{"value":[{"text":"ChatNavigationBar","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatNavigationBar\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}