{"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatNavigationBar\/init(show:showLeftItem:textAlignment:placeHolder:avatarURL:rightImages:hiddenAvatar:nearStatusBar:)","interfaceLanguage":"swift"},"abstract":[{"text":"EaseChatNavigationBar init method with right items kind of images.","type":"text"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"@","kind":"attribute"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"text":" ","kind":"text"},{"text":"convenience","kind":"keyword"},{"kind":"text","text":" "},{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"kind":"externalParam","text":"show"},{"kind":"text","text":" "},{"text":"frame","kind":"internalParam"},{"kind":"text","text":": "},{"text":"CGRect","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":" = CGRect(x: 0, y: 0, width: ScreenWidth, height: NavigationHeight), "},{"text":"showLeftItem","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"textAlignment","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSTextAlignment","preciseIdentifier":"c:@E@NSTextAlignment"},{"text":" = .center, ","kind":"text"},{"text":"placeHolder","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"text":"? = nil, ","kind":"text"},{"text":"avatarURL","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"rightImages"},{"kind":"text","text":": ["},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"] = [], "},{"text":"hiddenAvatar","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":" = false, "},{"kind":"externalParam","text":"nearStatusBar"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":" = true)","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"Whether show left button or not.","type":"text"}],"type":"paragraph"}],"name":"showLeftItem"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Title and subtitle text alignment."}]}],"name":"textAlignment"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Avatar default image."}]}],"name":"placeHolder"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Avatar url."}]}],"name":"avatarURL"},{"content":[{"inlineContent":[{"text":"Right buttons kind of ","type":"text"},{"code":"[UIImage]","type":"codeVoice"},{"type":"text","text":"."}],"type":"paragraph"}],"name":"rightImages"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Whether hide avatar or not."}]}],"name":"hiddenAvatar"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatNavigationBar"]]},"sections":[],"metadata":{"role":"symbol","externalID":"c:@M@ShengwangChatUIKit@objc(cs)ChatNavigationBar(im)initWithShow:showLeftItem:textAlignment:placeHolder:avatarURL:rightImages:hiddenAvatar:nearStatusBar:","roleHeading":"Initializer","title":"init(show:showLeftItem:textAlignment:placeHolder:avatarURL:rightImages:hiddenAvatar:nearStatusBar:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"show","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CGRect","kind":"typeIdentifier","text":"CGRect"},{"text":", ","kind":"text"},{"text":"showLeftItem","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"text":"textAlignment","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@NSTextAlignment","kind":"typeIdentifier","text":"NSTextAlignment"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"placeHolder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"avatarURL"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"rightImages","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"},{"kind":"text","text":"], "},{"text":"hiddenAvatar","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"nearStatusBar"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"initWithShow:showLeftItem:textAlignment:placeHolder:avatarURL:rightImages:hiddenAvatar:nearStatusBar:","kind":"identifier"}],"modules":[{"name":"ShengwangChatUIKit"}],"symbolKind":"init"},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/chatnavigationbar\/init(show:showleftitem:textalignment:placeholder:avatarurl:rightimages:hiddenavatar:nearstatusbar:)"]},{"paths":["\/documentation\/shengwangchatuikit\/chatnavigationbar\/init(show:showleftitem:textalignment:placeholder:avatarurl:rightimages:hiddenavatar:nearstatusbar:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatNavigationBar":{"navigatorTitle":[{"kind":"identifier","text":"ChatNavigationBar"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatNavigationBar"}],"kind":"symbol","abstract":[{"type":"text","text":"Navigation  bar of the ChatUIKit."}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatNavigationBar","url":"\/documentation\/shengwangchatuikit\/chatnavigationbar","type":"topic","title":"ChatNavigationBar","role":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatNavigationBar/init(show:showLeftItem:textAlignment:placeHolder:avatarURL:rightImages:hiddenAvatar:nearStatusBar:)":{"role":"symbol","abstract":[{"type":"text","text":"EaseChatNavigationBar init method with right items kind of images."}],"kind":"symbol","title":"init(show:showLeftItem:textAlignment:placeHolder:avatarURL:rightImages:hiddenAvatar:nearStatusBar:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"show","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect","text":"CGRect"},{"kind":"text","text":", "},{"kind":"externalParam","text":"showLeftItem"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"textAlignment"},{"kind":"text","text":": "},{"text":"NSTextAlignment","preciseIdentifier":"c:@E@NSTextAlignment","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"placeHolder","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"avatarURL","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"text":"rightImages","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"hiddenAvatar"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"text":"nearStatusBar","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":")","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatNavigationBar\/init(show:showLeftItem:textAlignment:placeHolder:avatarURL:rightImages:hiddenAvatar:nearStatusBar:)","navigatorTitle":[{"kind":"identifier","text":"initWithShow:showLeftItem:textAlignment:placeHolder:avatarURL:rightImages:hiddenAvatar:nearStatusBar:"}],"type":"topic","url":"\/documentation\/shengwangchatuikit\/chatnavigationbar\/init(show:showleftitem:textalignment:placeholder:avatarurl:rightimages:hiddenavatar:nearstatusbar:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"initWithShow:showLeftItem:textAlignment:placeHolder:avatarURL:rightImages:hiddenAvatar:nearStatusBar:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithShow:showLeftItem:textAlignment:placeHolder:avatarURL:rightImages:hiddenAvatar:nearStatusBar:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"id","preciseIdentifier":"c:*Qo","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithShow:"},{"text":"(","kind":"text"},{"text":"CGRect","preciseIdentifier":"c:@S@CGRect","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"frame","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"showLeftItem:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"text":") ","kind":"text"},{"text":"showLeftItem","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"textAlignment:"},{"kind":"text","text":"("},{"text":"NSTextAlignment","kind":"typeIdentifier","preciseIdentifier":"c:@E@NSTextAlignment"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"textAlignment"},{"text":" ","kind":"text"},{"kind":"identifier","text":"placeHolder:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"placeHolder"},{"text":" ","kind":"text"},{"text":"avatarURL:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"avatarURL","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"rightImages:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSArray<UIImage *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"rightImages"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hiddenAvatar:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"hiddenAvatar"},{"text":" ","kind":"text"},{"text":"nearStatusBar:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"text":"nearStatusBar","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"value":{"kind":"parameters","parameters":[{"name":"showLeftItem","content":[{"inlineContent":[{"type":"text","text":"Whether show left button or not."}],"type":"paragraph"}]},{"name":"textAlignment","content":[{"type":"paragraph","inlineContent":[{"text":"Title and subtitle text alignment.","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Avatar default image.","type":"text"}]}],"name":"placeHolder"},{"content":[{"type":"paragraph","inlineContent":[{"text":"Avatar url.","type":"text"}]}],"name":"avatarURL"},{"name":"rightImages","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Right buttons kind of "},{"type":"codeVoice","code":"[UIImage]"},{"text":".","type":"text"}]}]},{"name":"hiddenAvatar","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Whether hide avatar or not."}]}]}]},"path":"\/primaryContentSections\/1","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatNavigationBar\/title","value":"ChatNavigationBar"},{"value":[{"text":"ChatNavigationBar","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatNavigationBar\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatNavigationBar\/navigatorTitle","op":"replace","value":[{"text":"ChatNavigationBar","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatNavigationBar~1init(show:showLeftItem:textAlignment:placeHolder:avatarURL:rightImages:hiddenAvatar:nearStatusBar:)\/title","op":"replace","value":"initWithShow:showLeftItem:textAlignment:placeHolder:avatarURL:rightImages:hiddenAvatar:nearStatusBar:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatNavigationBar~1init(show:showLeftItem:textAlignment:placeHolder:avatarURL:rightImages:hiddenAvatar:nearStatusBar:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithShow:showLeftItem:textAlignment:placeHolder:avatarURL:rightImages:hiddenAvatar:nearStatusBar:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}