{"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"extendedModule":"ShengwangChatUIKit","externalID":"c:@CM@ShengwangChatUIKit@objc(cs)MessageReactionView(im)collectionView:layout:sizeForItemAtIndexPath:","navigatorTitle":[{"kind":"identifier","text":"collectionView:layout:sizeForItemAtIndexPath:"}],"role":"symbol","modules":[{"name":"ShengwangChatUIKit"}],"title":"collectionView(_:layout:sizeForItemAt:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"collectionView"},{"text":"(","kind":"text"},{"text":"UICollectionView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UICollectionView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"layout"},{"kind":"text","text":": "},{"text":"UICollectionViewLayout","preciseIdentifier":"c:objc(cs)UICollectionViewLayout","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"sizeForItemAt"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation9IndexPathV","text":"IndexPath","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"CGSize","preciseIdentifier":"c:@S@CGSize","kind":"typeIdentifier"}],"roleHeading":"Instance Method","symbolKind":"method"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"collectionView"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"collectionView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UICollectionView","text":"UICollectionView"},{"kind":"text","text":", "},{"text":"layout","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"collectionViewLayout","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UICollectionViewLayout","kind":"typeIdentifier","text":"UICollectionViewLayout"},{"text":", ","kind":"text"},{"text":"sizeForItemAt","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"indexPath"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation9IndexPathV","text":"IndexPath"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize","text":"CGSize"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageReactionView\/collectionView(_:layout:sizeForItemAt:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"code":"UICollectionViewDelegateFlowLayout.collectionView(_:layout:sizeForItemAt:)","type":"codeVoice"},{"type":"text","text":"."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/messagereactionview\/collectionview(_:layout:sizeforitemat:)"]},{"paths":["\/documentation\/shengwangchatuikit\/messagereactionview\/collectionview(_:layout:sizeforitemat:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageReactionView","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageReactionView\/UICollectionViewDelegateFlowLayout-Implementations"]]},"kind":"symbol","references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageReactionView":{"abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MessageReactionView","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"MessageReactionView","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/shengwangchatuikit\/messagereactionview","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageReactionView","title":"MessageReactionView"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageReactionView/collectionView(_:layout:sizeForItemAt:)":{"title":"collectionView(_:layout:sizeForItemAt:)","abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"collectionView"},{"kind":"text","text":"("},{"text":"UICollectionView","preciseIdentifier":"c:objc(cs)UICollectionView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"layout","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UICollectionViewLayout","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UICollectionViewLayout"},{"kind":"text","text":", "},{"text":"sizeForItemAt","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"IndexPath","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation9IndexPathV"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize","text":"CGSize"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageReactionView\/collectionView(_:layout:sizeForItemAt:)","navigatorTitle":[{"text":"collectionView:layout:sizeForItemAtIndexPath:","kind":"identifier"}],"type":"topic","url":"\/documentation\/shengwangchatuikit\/messagereactionview\/collectionview(_:layout:sizeforitemat:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageReactionView/UICollectionViewDelegateFlowLayout-Implementations":{"url":"\/documentation\/shengwangchatuikit\/messagereactionview\/uicollectionviewdelegateflowlayout-implementations","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageReactionView\/UICollectionViewDelegateFlowLayout-Implementations","type":"topic","kind":"article","role":"collectionGroup","abstract":[],"title":"UICollectionViewDelegateFlowLayout Implementations"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"collectionView:layout:sizeForItemAtIndexPath:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"collectionView:layout:sizeForItemAtIndexPath:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:@S@CGSize","text":"CGSize","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"collectionView:"},{"kind":"text","text":"("},{"text":"UICollectionView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UICollectionView"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"collectionView"},{"text":" ","kind":"text"},{"text":"layout:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UICollectionViewLayout","preciseIdentifier":"c:objc(cs)UICollectionViewLayout","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"collectionViewLayout"},{"kind":"text","text":" "},{"kind":"identifier","text":"sizeForItemAtIndexPath:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSIndexPath","kind":"typeIdentifier","text":"NSIndexPath"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"indexPath"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageReactionView\/title","value":"MessageReactionView","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageReactionView\/fragments","value":[{"text":"MessageReactionView","kind":"identifier"}]},{"op":"replace","value":[{"text":"MessageReactionView","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageReactionView\/navigatorTitle"},{"op":"replace","value":"collectionView:layout:sizeForItemAtIndexPath:","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageReactionView~1collectionView(_:layout:sizeForItemAt:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageReactionView~1collectionView(_:layout:sizeForItemAt:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"collectionView:layout:sizeForItemAtIndexPath:"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}