{"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageReactionView\/UICollectionViewDelegateFlowLayout-Implementations","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageReactionView"]]},"topicSections":[{"title":"Instance Methods","anchor":"Instance-Methods","generated":true,"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageReactionView\/collectionView(_:layout:minimumInteritemSpacingForSectionAt:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageReactionView\/collectionView(_:layout:minimumLineSpacingForSectionAt:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageReactionView\/collectionView(_:layout:sizeForItemAt:)"]}],"metadata":{"roleHeading":"API Collection","role":"collectionGroup","modules":[{"name":"ShengwangChatUIKit"}],"title":"UICollectionViewDelegateFlowLayout Implementations"},"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"article","variants":[{"paths":["\/documentation\/shengwangchatuikit\/messagereactionview\/uicollectionviewdelegateflowlayout-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/messagereactionview\/uicollectionviewdelegateflowlayout-implementations"]}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageReactionView/collectionView(_:layout:minimumLineSpacingForSectionAt:)":{"title":"collectionView(_:layout:minimumLineSpacingForSectionAt:)","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"collectionView","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UICollectionView","preciseIdentifier":"c:objc(cs)UICollectionView"},{"text":", ","kind":"text"},{"text":"layout","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UICollectionViewLayout","text":"UICollectionViewLayout"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"minimumLineSpacingForSectionAt"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageReactionView\/collectionView(_:layout:minimumLineSpacingForSectionAt:)","navigatorTitle":[{"kind":"identifier","text":"collectionView:layout:minimumLineSpacingForSectionAtIndex:"}],"type":"topic","url":"\/documentation\/shengwangchatuikit\/messagereactionview\/collectionview(_:layout:minimumlinespacingforsectionat:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageReactionView/collectionView(_:layout:minimumInteritemSpacingForSectionAt:)":{"kind":"symbol","navigatorTitle":[{"text":"collectionView:layout:minimumInteritemSpacingForSectionAtIndex:","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/messagereactionview\/collectionview(_:layout:minimuminteritemspacingforsectionat:)","title":"collectionView(_:layout:minimumInteritemSpacingForSectionAt:)","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageReactionView\/collectionView(_:layout:minimumInteritemSpacingForSectionAt:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"collectionView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UICollectionView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UICollectionView"},{"kind":"text","text":", "},{"text":"layout","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UICollectionViewLayout","text":"UICollectionViewLayout","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"minimumInteritemSpacingForSectionAt","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"type":"topic","role":"symbol","abstract":[]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageReactionView":{"abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MessageReactionView","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"MessageReactionView","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/shengwangchatuikit\/messagereactionview","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageReactionView","title":"MessageReactionView"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageReactionView/collectionView(_:layout:sizeForItemAt:)":{"title":"collectionView(_:layout:sizeForItemAt:)","abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"collectionView"},{"kind":"text","text":"("},{"text":"UICollectionView","preciseIdentifier":"c:objc(cs)UICollectionView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"layout","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UICollectionViewLayout","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UICollectionViewLayout"},{"kind":"text","text":", "},{"text":"sizeForItemAt","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"IndexPath","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation9IndexPathV"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize","text":"CGSize"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageReactionView\/collectionView(_:layout:sizeForItemAt:)","navigatorTitle":[{"text":"collectionView:layout:sizeForItemAtIndexPath:","kind":"identifier"}],"type":"topic","url":"\/documentation\/shengwangchatuikit\/messagereactionview\/collectionview(_:layout:sizeforitemat:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":[{"generated":true,"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageReactionView\/collectionView(_:layout:minimumInteritemSpacingForSectionAt:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageReactionView\/collectionView(_:layout:minimumLineSpacingForSectionAt:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageReactionView\/collectionView(_:layout:sizeForItemAt:)"]}],"op":"replace","path":"\/topicSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageReactionView~1collectionView(_:layout:minimumLineSpacingForSectionAt:)\/title","value":"collectionView:layout:minimumLineSpacingForSectionAtIndex:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"collectionView:layout:minimumLineSpacingForSectionAtIndex:"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageReactionView~1collectionView(_:layout:minimumLineSpacingForSectionAt:)\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageReactionView~1collectionView(_:layout:minimumInteritemSpacingForSectionAt:)\/title","value":"collectionView:layout:minimumInteritemSpacingForSectionAtIndex:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageReactionView~1collectionView(_:layout:minimumInteritemSpacingForSectionAt:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"collectionView:layout:minimumInteritemSpacingForSectionAtIndex:","kind":"identifier"}],"op":"replace"},{"value":"MessageReactionView","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageReactionView\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageReactionView\/fragments","op":"replace","value":[{"kind":"identifier","text":"MessageReactionView"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageReactionView\/navigatorTitle","value":[{"kind":"identifier","text":"MessageReactionView"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageReactionView~1collectionView(_:layout:sizeForItemAt:)\/title","op":"replace","value":"collectionView:layout:sizeForItemAtIndexPath:"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageReactionView~1collectionView(_:layout:sizeForItemAt:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"collectionView:layout:sizeForItemAtIndexPath:"}]}]}]}