{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageReactionView"]]},"kind":"article","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/messagereactionview\/uicollectionviewdatasource-implementations"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/messagereactionview\/uicollectionviewdatasource-implementations"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageReactionView\/UICollectionViewDataSource-Implementations","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"ShengwangChatUIKit"}],"role":"collectionGroup","roleHeading":"API Collection","title":"UICollectionViewDataSource Implementations"},"topicSections":[{"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageReactionView\/collectionView(_:cellForItemAt:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageReactionView\/collectionView(_:numberOfItemsInSection:)"],"generated":true,"anchor":"Instance-Methods","title":"Instance Methods"}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageReactionView":{"abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MessageReactionView","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"MessageReactionView","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/shengwangchatuikit\/messagereactionview","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageReactionView","title":"MessageReactionView"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageReactionView/collectionView(_:cellForItemAt:)":{"title":"collectionView(_:cellForItemAt:)","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"collectionView:cellForItemAtIndexPath:"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageReactionView\/collectionView(_:cellForItemAt:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"collectionView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UICollectionView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UICollectionView"},{"text":", ","kind":"text"},{"text":"cellForItemAt","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation9IndexPathV","text":"IndexPath"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UICollectionViewCell","text":"UICollectionViewCell","kind":"typeIdentifier"}],"role":"symbol","url":"\/documentation\/shengwangchatuikit\/messagereactionview\/collectionview(_:cellforitemat:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageReactionView/collectionView(_:numberOfItemsInSection:)":{"url":"\/documentation\/shengwangchatuikit\/messagereactionview\/collectionview(_:numberofitemsinsection:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"collectionView:numberOfItemsInSection:"}],"title":"collectionView(_:numberOfItemsInSection:)","type":"topic","kind":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageReactionView\/collectionView(_:numberOfItemsInSection:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"collectionView"},{"text":"(","kind":"text"},{"text":"UICollectionView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UICollectionView"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"numberOfItemsInSection"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/topicSections","op":"replace","value":[{"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageReactionView\/collectionView(_:cellForItemAt:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageReactionView\/collectionView(_:numberOfItemsInSection:)"],"title":"Instance Methods","anchor":"Instance-Methods","generated":true}]},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageReactionView\/title","value":"MessageReactionView","op":"replace"},{"value":[{"text":"MessageReactionView","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageReactionView\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageReactionView\/navigatorTitle","value":[{"kind":"identifier","text":"MessageReactionView"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageReactionView~1collectionView(_:cellForItemAt:)\/title","value":"collectionView:cellForItemAtIndexPath:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageReactionView~1collectionView(_:cellForItemAt:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"collectionView:cellForItemAtIndexPath:","kind":"identifier"}]},{"value":"collectionView:numberOfItemsInSection:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageReactionView~1collectionView(_:numberOfItemsInSection:)\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"collectionView:numberOfItemsInSection:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageReactionView~1collectionView(_:numberOfItemsInSection:)\/fragments"}]}]}