{"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"collectionView"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"collectionView","kind":"internalParam"},{"kind":"text","text":": "},{"text":"UICollectionView","preciseIdentifier":"c:objc(cs)UICollectionView","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"didSelectItemAt","kind":"externalParam"},{"kind":"text","text":" "},{"text":"indexPath","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation9IndexPathV","text":"IndexPath"},{"text":")","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"collectionView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UICollectionView","preciseIdentifier":"c:objc(cs)UICollectionView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didSelectItemAt","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation9IndexPathV","text":"IndexPath","kind":"typeIdentifier"},{"text":")","kind":"text"}],"modules":[{"name":"ShengwangChatUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"collectionView:didSelectItemAtIndexPath:"}],"externalID":"c:@CM@ShengwangChatUIKit@objc(cs)MessageReactionsController(im)collectionView:didSelectItemAtIndexPath:","extendedModule":"ShengwangChatUIKit","title":"collectionView(_:didSelectItemAt:)","role":"symbol","roleHeading":"Instance Method"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageReactionsController","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageReactionsController\/UICollectionViewDelegate-Implementations"]]},"abstract":[{"text":"Inherited from ","type":"text"},{"code":"UICollectionViewDelegate.collectionView(_:didSelectItemAt:)","type":"codeVoice"},{"text":".","type":"text"}],"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageReactionsController\/collectionView(_:didSelectItemAt:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/messagereactionscontroller\/collectionview(_:didselectitemat:)"]},{"paths":["\/documentation\/shengwangchatuikit\/messagereactionscontroller\/collectionview(_:didselectitemat:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageReactionsController":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageReactionsController","navigatorTitle":[{"kind":"identifier","text":"MessageReactionsController"}],"url":"\/documentation\/shengwangchatuikit\/messagereactionscontroller","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessageReactionsController","kind":"identifier"}],"kind":"symbol","abstract":[],"title":"MessageReactionsController","type":"topic"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageReactionsController/collectionView(_:didSelectItemAt:)":{"type":"topic","kind":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageReactionsController\/collectionView(_:didSelectItemAt:)","role":"symbol","url":"\/documentation\/shengwangchatuikit\/messagereactionscontroller\/collectionview(_:didselectitemat:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"collectionView"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UICollectionView","text":"UICollectionView","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didSelectItemAt"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation9IndexPathV","text":"IndexPath"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"collectionView:didSelectItemAtIndexPath:","kind":"identifier"}],"title":"collectionView(_:didSelectItemAt:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageReactionsController/UICollectionViewDelegate-Implementations":{"abstract":[],"title":"UICollectionViewDelegate Implementations","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageReactionsController\/UICollectionViewDelegate-Implementations","role":"collectionGroup","type":"topic","kind":"article","url":"\/documentation\/shengwangchatuikit\/messagereactionscontroller\/uicollectionviewdelegate-implementations"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"collectionView:didSelectItemAtIndexPath:","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"text":"collectionView:didSelectItemAtIndexPath:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"collectionView:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UICollectionView","kind":"typeIdentifier","text":"UICollectionView"},{"kind":"text","text":" *) "},{"text":"collectionView","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"didSelectItemAtIndexPath:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSIndexPath","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSIndexPath"},{"text":" *) ","kind":"text"},{"text":"indexPath","kind":"internalParam"},{"kind":"text","text":";"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageReactionsController\/title","value":"MessageReactionsController"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageReactionsController\/fragments","value":[{"text":"MessageReactionsController","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageReactionsController\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MessageReactionsController"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageReactionsController~1collectionView(_:didSelectItemAt:)\/title","value":"collectionView:didSelectItemAtIndexPath:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageReactionsController~1collectionView(_:didSelectItemAt:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"collectionView:didSelectItemAtIndexPath:","kind":"identifier"}]}]}]}