{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"kind":"keyword","text":"required"},{"text":" ","kind":"text"},{"kind":"keyword","text":"init"},{"kind":"text","text":"?("},{"text":"coder","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSCoder","text":"NSCoder","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"]}]}],"metadata":{"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"coder"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSCoder","text":"NSCoder"},{"kind":"text","text":")"}],"externalID":"c:@M@ShengwangChatUIKit@objc(cs)MessageReactionsController(im)initWithCoder:","modules":[{"name":"ShengwangChatUIKit"}],"roleHeading":"Initializer","symbolKind":"init","title":"init(coder:)","role":"symbol","navigatorTitle":[{"text":"initWithCoder:","kind":"identifier"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageReactionsController\/init(coder:)"},"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageReactionsController"]]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/messagereactionscontroller\/init(coder:)"]},{"paths":["\/documentation\/shengwangchatuikit\/messagereactionscontroller\/init(coder:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageReactionsController/init(coder:)":{"navigatorTitle":[{"text":"initWithCoder:","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageReactionsController\/init(coder:)","title":"init(coder:)","role":"symbol","kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"coder","kind":"externalParam"},{"kind":"text","text":": "},{"text":"NSCoder","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSCoder"},{"kind":"text","text":")"}],"type":"topic","abstract":[],"url":"\/documentation\/shengwangchatuikit\/messagereactionscontroller\/init(coder:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageReactionsController":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageReactionsController","navigatorTitle":[{"kind":"identifier","text":"MessageReactionsController"}],"url":"\/documentation\/shengwangchatuikit\/messagereactionscontroller","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessageReactionsController","kind":"identifier"}],"kind":"symbol","abstract":[],"title":"MessageReactionsController","type":"topic"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithCoder:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:*Qo","kind":"typeIdentifier","text":"id"},{"text":") ","kind":"text"},{"text":"initWithCoder:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSCoder","text":"NSCoder","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"coder"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"initWithCoder:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageReactionsController~1init(coder:)\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithCoder:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageReactionsController~1init(coder:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageReactionsController\/title","value":"MessageReactionsController"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageReactionsController\/fragments","value":[{"kind":"identifier","text":"MessageReactionsController"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageReactionsController\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MessageReactionsController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}