{"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageReactionsController\/UICollectionViewDataSource-Implementations","interfaceLanguage":"swift"},"kind":"article","hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageReactionsController"]]},"sections":[],"topicSections":[{"anchor":"Instance-Methods","title":"Instance Methods","generated":true,"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageReactionsController\/collectionView(_:cellForItemAt:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageReactionsController\/collectionView(_:numberOfItemsInSection:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageReactionsController\/numberOfSections(in:)"]}],"metadata":{"title":"UICollectionViewDataSource Implementations","role":"collectionGroup","roleHeading":"API Collection","modules":[{"name":"ShengwangChatUIKit"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/messagereactionscontroller\/uicollectionviewdatasource-implementations"]},{"paths":["\/documentation\/shengwangchatuikit\/messagereactionscontroller\/uicollectionviewdatasource-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageReactionsController/collectionView(_:numberOfItemsInSection:)":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageReactionsController\/collectionView(_:numberOfItemsInSection:)","navigatorTitle":[{"text":"collectionView:numberOfItemsInSection:","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/messagereactionscontroller\/collectionview(_:numberofitemsinsection:)","type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"collectionView","kind":"identifier"},{"kind":"text","text":"("},{"text":"UICollectionView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UICollectionView"},{"kind":"text","text":", "},{"text":"numberOfItemsInSection","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":") -> ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"title":"collectionView(_:numberOfItemsInSection:)","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageReactionsController/numberOfSections(in:)":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageReactionsController\/numberOfSections(in:)","url":"\/documentation\/shengwangchatuikit\/messagereactionscontroller\/numberofsections(in:)","abstract":[],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"numberOfSections"},{"text":"(","kind":"text"},{"text":"in","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UICollectionView","preciseIdentifier":"c:objc(cs)UICollectionView"},{"text":") -> ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"role":"symbol","title":"numberOfSections(in:)","navigatorTitle":[{"text":"numberOfSectionsInCollectionView:","kind":"identifier"}],"kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageReactionsController/collectionView(_:cellForItemAt:)":{"url":"\/documentation\/shengwangchatuikit\/messagereactionscontroller\/collectionview(_:cellforitemat:)","kind":"symbol","type":"topic","navigatorTitle":[{"text":"collectionView:cellForItemAtIndexPath:","kind":"identifier"}],"abstract":[],"role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageReactionsController\/collectionView(_:cellForItemAt:)","title":"collectionView(_:cellForItemAt:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"collectionView","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UICollectionView","text":"UICollectionView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"cellForItemAt","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation9IndexPathV","text":"IndexPath"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:objc(cs)UICollectionViewCell","kind":"typeIdentifier","text":"UICollectionViewCell"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageReactionsController":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageReactionsController","navigatorTitle":[{"kind":"identifier","text":"MessageReactionsController"}],"url":"\/documentation\/shengwangchatuikit\/messagereactionscontroller","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessageReactionsController","kind":"identifier"}],"kind":"symbol","abstract":[],"title":"MessageReactionsController","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageReactionsController\/collectionView(_:cellForItemAt:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageReactionsController\/collectionView(_:numberOfItemsInSection:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageReactionsController\/numberOfSections(in:)"]}]},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageReactionsController~1collectionView(_:numberOfItemsInSection:)\/title","value":"collectionView:numberOfItemsInSection:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageReactionsController~1collectionView(_:numberOfItemsInSection:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"collectionView:numberOfItemsInSection:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageReactionsController~1numberOfSections(in:)\/title","op":"replace","value":"numberOfSectionsInCollectionView:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageReactionsController~1numberOfSections(in:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"numberOfSectionsInCollectionView:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageReactionsController~1collectionView(_:cellForItemAt:)\/title","value":"collectionView:cellForItemAtIndexPath:"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageReactionsController~1collectionView(_:cellForItemAt:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"collectionView:cellForItemAtIndexPath:","kind":"identifier"}]},{"value":"MessageReactionsController","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageReactionsController\/title"},{"op":"replace","value":[{"kind":"identifier","text":"MessageReactionsController"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageReactionsController\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageReactionsController\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MessageReactionsController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}