{"abstract":[{"text":"Creates a loading view.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"attribute","text":"@"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"createLoading"},{"kind":"text","text":"() -> "},{"text":"LoadingView","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)LoadingView","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/LoadingView","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"content","content":[{"level":2,"text":"Return Value","anchor":"return-value","type":"heading"},{"type":"paragraph","inlineContent":[{"text":"A ","type":"text"},{"type":"codeVoice","code":"LoadingView"},{"text":" instance.","type":"text"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/messagelistcontroller\/createloading()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/messagelistcontroller\/createloading()"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListController"]]},"kind":"symbol","metadata":{"roleHeading":"Instance Method","role":"symbol","navigatorTitle":[{"text":"createLoading","kind":"identifier"}],"externalID":"c:@M@ShengwangChatUIKit@objc(cs)MessageListController(im)createLoading","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"createLoading","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"LoadingView","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)LoadingView","kind":"typeIdentifier"}],"title":"createLoading()","modules":[{"name":"ShengwangChatUIKit"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListController\/createLoading()"},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageListController/createLoading()":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListController\/createLoading()","navigatorTitle":[{"kind":"identifier","text":"createLoading"}],"url":"\/documentation\/shengwangchatuikit\/messagelistcontroller\/createloading()","type":"topic","abstract":[{"type":"text","text":"Creates a loading view."}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"createLoading","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"LoadingView","kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)LoadingView"}],"title":"createLoading()","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/LoadingView":{"abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"LoadingView","kind":"identifier"}],"role":"symbol","url":"\/documentation\/shengwangchatuikit\/loadingview","title":"LoadingView","kind":"symbol","type":"topic","navigatorTitle":[{"text":"LoadingView","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/LoadingView"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageListController":{"navigatorTitle":[{"text":"MessageListController","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/messagelistcontroller","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListController","abstract":[],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MessageListController"}],"title":"MessageListController","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"createLoading","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"createLoading"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/LoadingView","kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)LoadingView","text":"LoadingView"},{"text":" *) ","kind":"text"},{"text":"createLoading","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":{"kind":"content","content":[{"level":2,"text":"Return Value","anchor":"return-value","type":"heading"},{"type":"paragraph","inlineContent":[{"text":"A ","type":"text"},{"type":"codeVoice","code":"LoadingView"},{"text":" instance.","type":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/1"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListController~1createLoading()\/title","value":"createLoading"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListController~1createLoading()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"createLoading","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1LoadingView\/title","value":"LoadingView"},{"value":[{"text":"LoadingView","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1LoadingView\/fragments","op":"replace"},{"value":[{"text":"LoadingView","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1LoadingView\/navigatorTitle","op":"replace"},{"op":"replace","value":"MessageListController","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListController\/title"},{"value":[{"text":"MessageListController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListController\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListController\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MessageListController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}