{"variants":[{"paths":["\/documentation\/shengwangchatuikit\/messagelistcontroller\/deletemessages(messages:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/shengwangchatuikit\/messagelistcontroller\/deletemessages(messages:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListController"]]},"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"deleteMessages","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"messages"},{"text":": [","kind":"text"},{"text":"ChatMessage","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatMessage","preciseIdentifier":"s:18ShengwangChatUIKit0B7Messagea"},{"text":"])","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"roleHeading":"Instance Method","extendedModule":"ShengwangChatUIKit","title":"deleteMessages(messages:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"deleteMessagesWithMessages:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"deleteMessages","kind":"identifier"},{"kind":"text","text":"("},{"text":"messages","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:18ShengwangChatUIKit0B7Messagea","text":"ChatMessage","kind":"typeIdentifier"},{"text":"])","kind":"text"}],"externalID":"c:@CM@ShengwangChatUIKit@objc(cs)MessageListController(im)deleteMessagesWithMessages:","modules":[{"name":"ShengwangChatUIKit"}],"symbolKind":"method"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListController\/deleteMessages(messages:)"},"sections":[],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatMessage":{"url":"\/documentation\/shengwangchatuikit\/chatmessage","abstract":[],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ChatMessage"}],"type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatMessage","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChatMessage"}],"title":"ChatMessage"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageListController":{"navigatorTitle":[{"text":"MessageListController","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/messagelistcontroller","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListController","abstract":[],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MessageListController"}],"title":"MessageListController","type":"topic"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageListController/deleteMessages(messages:)":{"url":"\/documentation\/shengwangchatuikit\/messagelistcontroller\/deletemessages(messages:)","navigatorTitle":[{"kind":"identifier","text":"deleteMessagesWithMessages:"}],"title":"deleteMessages(messages:)","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListController\/deleteMessages(messages:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"deleteMessages","kind":"identifier"},{"text":"(","kind":"text"},{"text":"messages","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"ChatMessage","kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit0B7Messagea"},{"kind":"text","text":"])"}],"type":"topic","kind":"symbol","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"value":"deleteMessagesWithMessages:","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"deleteMessagesWithMessages:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"deleteMessagesWithMessages:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<AgoraChatMessage *>","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"messages","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListController\/title","value":"MessageListController","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListController\/fragments","value":[{"text":"MessageListController","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"MessageListController"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListController\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListController~1deleteMessages(messages:)\/title","value":"deleteMessagesWithMessages:"},{"value":[{"kind":"text","text":"- "},{"text":"deleteMessagesWithMessages:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListController~1deleteMessages(messages:)\/fragments","op":"replace"}]}]}