{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListController\/feedback(with:)"},"kind":"symbol","sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/messagelistcontroller\/feedback(with:)"]},{"paths":["\/documentation\/shengwangchatuikit\/messagelistcontroller\/feedback(with:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListController"]]},"metadata":{"title":"feedback(with:)","externalID":"c:@CM@ShengwangChatUIKit@objc(cs)MessageListController(im)feedbackWith:","extendedModule":"ShengwangChatUIKit","role":"symbol","symbolKind":"method","modules":[{"name":"ShengwangChatUIKit"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"feedback"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"text":": ","kind":"text"},{"text":"UIImpactFeedbackGenerator","preciseIdentifier":"c:objc(cs)UIImpactFeedbackGenerator","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@E@UIImpactFeedbackStyle","text":"FeedbackStyle","kind":"typeIdentifier"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"feedbackWith:","kind":"identifier"}],"roleHeading":"Instance Method"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"feedback","kind":"identifier"},{"kind":"text","text":"("},{"text":"with","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"style"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImpactFeedbackGenerator","text":"UIImpactFeedbackGenerator","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@E@UIImpactFeedbackStyle","text":"FeedbackStyle","kind":"typeIdentifier"},{"text":")","kind":"text"}]}]}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageListController/feedback(with:)":{"title":"feedback(with:)","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListController\/feedback(with:)","url":"\/documentation\/shengwangchatuikit\/messagelistcontroller\/feedback(with:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"feedback","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImpactFeedbackGenerator","text":"UIImpactFeedbackGenerator","kind":"typeIdentifier"},{"text":".","kind":"text"},{"kind":"typeIdentifier","text":"FeedbackStyle","preciseIdentifier":"c:@E@UIImpactFeedbackStyle"},{"text":")","kind":"text"}],"role":"symbol","abstract":[],"navigatorTitle":[{"text":"feedbackWith:","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageListController":{"navigatorTitle":[{"text":"MessageListController","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/messagelistcontroller","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListController","abstract":[],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MessageListController"}],"title":"MessageListController","type":"topic"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"value":"feedbackWith:","op":"replace","path":"\/metadata\/title"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"feedbackWith:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"feedbackWith:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@E@UIImpactFeedbackStyle","text":"UIImpactFeedbackStyle","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"style"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","value":"feedbackWith:","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListController~1feedback(with:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListController~1feedback(with:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"feedbackWith:"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListController\/title","value":"MessageListController","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListController\/fragments","op":"replace","value":[{"text":"MessageListController","kind":"identifier"}]},{"op":"replace","value":[{"text":"MessageListController","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListController\/navigatorTitle"}]}]}