{"kind":"symbol","metadata":{"symbolKind":"method","navigatorTitle":[{"text":"imagePickerController:didFinishPickingMediaWithInfo:","kind":"identifier"}],"role":"symbol","modules":[{"name":"ShengwangChatUIKit"}],"roleHeading":"Instance Method","externalID":"c:@CM@ShengwangChatUIKit@objc(cs)MessageListController(im)imagePickerController:didFinishPickingMediaWithInfo:","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"imagePickerController"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"UIImagePickerController","preciseIdentifier":"c:objc(cs)UIImagePickerController"},{"text":", ","kind":"text"},{"text":"didFinishPickingMediaWithInfo","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"UIImagePickerController","preciseIdentifier":"c:objc(cs)UIImagePickerController"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@T@UIImagePickerControllerInfoKey","text":"InfoKey","kind":"typeIdentifier"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"text":"])","kind":"text"}],"extendedModule":"ShengwangChatUIKit","title":"imagePickerController(_:didFinishPickingMediaWithInfo:)"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListController\/imagePickerController(_:didFinishPickingMediaWithInfo:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/messagelistcontroller\/imagepickercontroller(_:didfinishpickingmediawithinfo:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/messagelistcontroller\/imagepickercontroller(_:didfinishpickingmediawithinfo:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","kind":"attribute","text":"MainActor"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"imagePickerController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"picker"},{"kind":"text","text":": "},{"text":"UIImagePickerController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImagePickerController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didFinishPickingMediaWithInfo"},{"text":" ","kind":"text"},{"text":"info","kind":"internalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImagePickerController","text":"UIImagePickerController","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"InfoKey","kind":"typeIdentifier","preciseIdentifier":"c:@T@UIImagePickerControllerInfoKey"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"])"}]}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListController","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListController\/UIImagePickerControllerDelegate-Implementations"]]},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"UIImagePickerControllerDelegate.imagePickerController(_:didFinishPickingMediaWithInfo:)"},{"text":".","type":"text"}],"sections":[],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageListController":{"navigatorTitle":[{"text":"MessageListController","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/messagelistcontroller","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListController","abstract":[],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MessageListController"}],"title":"MessageListController","type":"topic"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageListController/imagePickerController(_:didFinishPickingMediaWithInfo:)":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListController\/imagePickerController(_:didFinishPickingMediaWithInfo:)","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"imagePickerController:didFinishPickingMediaWithInfo:"}],"type":"topic","role":"symbol","url":"\/documentation\/shengwangchatuikit\/messagelistcontroller\/imagepickercontroller(_:didfinishpickingmediawithinfo:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"imagePickerController"},{"kind":"text","text":"("},{"text":"UIImagePickerController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImagePickerController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didFinishPickingMediaWithInfo"},{"kind":"text","text":": ["},{"text":"UIImagePickerController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImagePickerController"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@T@UIImagePickerControllerInfoKey","text":"InfoKey","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"])","kind":"text"}],"title":"imagePickerController(_:didFinishPickingMediaWithInfo:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageListController/UIImagePickerControllerDelegate-Implementations":{"type":"topic","url":"\/documentation\/shengwangchatuikit\/messagelistcontroller\/uiimagepickercontrollerdelegate-implementations","kind":"article","role":"collectionGroup","abstract":[],"title":"UIImagePickerControllerDelegate Implementations","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListController\/UIImagePickerControllerDelegate-Implementations"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"imagePickerController:didFinishPickingMediaWithInfo:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"imagePickerController:didFinishPickingMediaWithInfo:"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"imagePickerController:"},{"kind":"text","text":"("},{"text":"UIImagePickerController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImagePickerController"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"picker"},{"kind":"text","text":" "},{"kind":"identifier","text":"didFinishPickingMediaWithInfo:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Q$objc(cs)NSDictionary","kind":"typeIdentifier","text":"NSDictionary<NSString *,id>"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"info"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"MessageListController","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListController\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListController\/fragments","value":[{"kind":"identifier","text":"MessageListController"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListController\/navigatorTitle","value":[{"kind":"identifier","text":"MessageListController"}]},{"value":"imagePickerController:didFinishPickingMediaWithInfo:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListController~1imagePickerController(_:didFinishPickingMediaWithInfo:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListController~1imagePickerController(_:didFinishPickingMediaWithInfo:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"imagePickerController:didFinishPickingMediaWithInfo:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}