{"metadata":{"modules":[{"name":"ShengwangChatUIKit"}],"title":"MessageListDriverEventsListener Implementations","role":"collectionGroup","roleHeading":"API Collection"},"sections":[],"kind":"article","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListController\/MessageListDriverEventsListener-Implementations"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/messagelistcontroller\/messagelistdrivereventslistener-implementations"]},{"paths":["\/documentation\/shengwangchatuikit\/messagelistcontroller\/messagelistdrivereventslistener-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListController"]]},"topicSections":[{"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListController\/onInputBoxEventsOccur(action:attributeText:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListController\/onMessageAttachmentLoading(loading:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListController\/onMessageAvatarClicked(user:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListController\/onMessageBubbleClicked(message:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListController\/onMessageBubbleLongPressed(cell:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListController\/onMessageMoreReactionAreaClicked(entity:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListController\/onMessageMultiSelectBarClicked(operation:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListController\/onMessageTopicAreaClicked(entity:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListController\/onMessageWillSendFillExtensionInfo()","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListController\/onOtherPartyTypingText()"],"anchor":"Instance-Methods","title":"Instance Methods","generated":true}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageListController/onMessageAttachmentLoading(loading:)":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListController\/onMessageAttachmentLoading(loading:)","abstract":[{"type":"text","text":"When you click a attachment message,we’ll download the attachment,the method also called."}],"navigatorTitle":[{"text":"onMessageAttachmentLoadingWithLoading:","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/shengwangchatuikit\/messagelistcontroller\/onmessageattachmentloading(loading:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onMessageAttachmentLoading"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"loading"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"title":"onMessageAttachmentLoading(loading:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageListController/onMessageMoreReactionAreaClicked(entity:)":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListController\/onMessageMoreReactionAreaClicked(entity:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"onMessageMoreReactionAreaClicked","kind":"identifier"},{"text":"(","kind":"text"},{"text":"entity","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MessageEntity","kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)MessageEntity"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"onMessageMoreReactionAreaClickedWithEntity:","kind":"identifier"}],"abstract":[{"type":"text","text":"When you click a message’s reaction ,the method will call."}],"url":"\/documentation\/shengwangchatuikit\/messagelistcontroller\/onmessagemorereactionareaclicked(entity:)","type":"topic","role":"symbol","title":"onMessageMoreReactionAreaClicked(entity:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageListController/onInputBoxEventsOccur(action:attributeText:)":{"role":"symbol","abstract":[{"type":"text","text":"The method will call on input menu bar actioned."}],"kind":"symbol","title":"onInputBoxEventsOccur(action:attributeText:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onInputBoxEventsOccur"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"action"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@E@MessageInputBarActionType","text":"MessageInputBarActionType","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"attributeText"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSAttributedString","text":"NSAttributedString","kind":"typeIdentifier"},{"kind":"text","text":"?)"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListController\/onInputBoxEventsOccur(action:attributeText:)","navigatorTitle":[{"text":"onInputBoxEventsOccurWithAction:attributeText:","kind":"identifier"}],"type":"topic","url":"\/documentation\/shengwangchatuikit\/messagelistcontroller\/oninputboxeventsoccur(action:attributetext:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageListController/onMessageMultiSelectBarClicked(operation:)":{"abstract":[{"type":"text","text":"When you click a message list multi select bar item,the method will call."}],"url":"\/documentation\/shengwangchatuikit\/messagelistcontroller\/onmessagemultiselectbarclicked(operation:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onMessageMultiSelectBarClicked","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"operation"},{"text":": ","kind":"text"},{"text":"MessageMultiSelectedBottomBarOperation","preciseIdentifier":"c:@M@ShengwangChatUIKit@E@MessageMultiSelectedBottomBarOperation","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListController\/onMessageMultiSelectBarClicked(operation:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"onMessageMultiSelectBarClickedWithOperation:"}],"title":"onMessageMultiSelectBarClicked(operation:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageListController/onMessageBubbleLongPressed(cell:)":{"abstract":[],"title":"onMessageBubbleLongPressed(cell:)","type":"topic","role":"symbol","url":"\/documentation\/shengwangchatuikit\/messagelistcontroller\/onmessagebubblelongpressed(cell:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"onMessageBubbleLongPressedWithCell:"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListController\/onMessageBubbleLongPressed(cell:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"onMessageBubbleLongPressed","kind":"identifier"},{"kind":"text","text":"("},{"text":"cell","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)MessageCell","text":"MessageCell"},{"text":")","kind":"text"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageListController/onOtherPartyTypingText()":{"navigatorTitle":[{"kind":"identifier","text":"onOtherPartyTypingText"}],"kind":"symbol","abstract":[{"text":"When other party begin typing text.The method will called.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"onOtherPartyTypingText","kind":"identifier"},{"text":"()","kind":"text"}],"type":"topic","role":"symbol","url":"\/documentation\/shengwangchatuikit\/messagelistcontroller\/onotherpartytypingtext()","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListController\/onOtherPartyTypingText()","title":"onOtherPartyTypingText()"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageListController":{"navigatorTitle":[{"text":"MessageListController","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/messagelistcontroller","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListController","abstract":[],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MessageListController"}],"title":"MessageListController","type":"topic"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageListController/onMessageBubbleClicked(message:)":{"abstract":[],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListController\/onMessageBubbleClicked(message:)","navigatorTitle":[{"text":"onMessageBubbleClickedWithMessage:","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/shengwangchatuikit\/messagelistcontroller\/onmessagebubbleclicked(message:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onMessageBubbleClicked"},{"text":"(","kind":"text"},{"text":"message","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)MessageEntity","text":"MessageEntity","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"onMessageBubbleClicked(message:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageListController/onMessageWillSendFillExtensionInfo()":{"navigatorTitle":[{"kind":"identifier","text":"onMessageWillSendFillExtensionInfo"}],"kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onMessageWillSendFillExtensionInfo","kind":"identifier"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SD","text":"Dictionary"},{"kind":"text","text":"<"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":">","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListController\/onMessageWillSendFillExtensionInfo()","type":"topic","abstract":[{"text":"Insert extension info before sending message.","type":"text"}],"url":"\/documentation\/shengwangchatuikit\/messagelistcontroller\/onmessagewillsendfillextensioninfo()","title":"onMessageWillSendFillExtensionInfo()"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageListController/onMessageAvatarClicked(user:)":{"abstract":[],"title":"onMessageAvatarClicked(user:)","type":"topic","role":"symbol","url":"\/documentation\/shengwangchatuikit\/messagelistcontroller\/onmessageavatarclicked(user:)","kind":"symbol","navigatorTitle":[{"text":"onMessageAvatarClickedWithUser:","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListController\/onMessageAvatarClicked(user:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"onMessageAvatarClicked"},{"text":"(","kind":"text"},{"text":"user","kind":"externalParam"},{"kind":"text","text":": "},{"text":"ChatUserProfileProtocol","kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(pl)ChatUserProfileProtocol"},{"text":")","kind":"text"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageListController/onMessageTopicAreaClicked(entity:)":{"role":"symbol","abstract":[{"text":"When you click a message’s topic area ,the method will call.","type":"text"}],"kind":"symbol","title":"onMessageTopicAreaClicked(entity:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"onMessageTopicAreaClicked","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"entity"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)MessageEntity","text":"MessageEntity"},{"text":")","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListController\/onMessageTopicAreaClicked(entity:)","navigatorTitle":[{"kind":"identifier","text":"onMessageTopicAreaClickedWithEntity:"}],"type":"topic","url":"\/documentation\/shengwangchatuikit\/messagelistcontroller\/onmessagetopicareaclicked(entity:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":[{"title":"Instance Methods","generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListController\/onInputBoxEventsOccur(action:attributeText:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListController\/onMessageAttachmentLoading(loading:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListController\/onMessageAvatarClicked(user:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListController\/onMessageBubbleClicked(message:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListController\/onMessageBubbleLongPressed(cell:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListController\/onMessageMoreReactionAreaClicked(entity:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListController\/onMessageMultiSelectBarClicked(operation:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListController\/onMessageTopicAreaClicked(entity:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListController\/onMessageWillSendFillExtensionInfo()","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListController\/onOtherPartyTypingText()"]}],"path":"\/topicSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":"onMessageAttachmentLoadingWithLoading:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListController~1onMessageAttachmentLoading(loading:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListController~1onMessageAttachmentLoading(loading:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"onMessageAttachmentLoadingWithLoading:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListController~1onMessageMoreReactionAreaClicked(entity:)\/title","value":"onMessageMoreReactionAreaClickedWithEntity:"},{"value":[{"text":"- ","kind":"text"},{"text":"onMessageMoreReactionAreaClickedWithEntity:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListController~1onMessageMoreReactionAreaClicked(entity:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListController~1onInputBoxEventsOccur(action:attributeText:)\/title","value":"onInputBoxEventsOccurWithAction:attributeText:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"onInputBoxEventsOccurWithAction:attributeText:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListController~1onInputBoxEventsOccur(action:attributeText:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListController~1onMessageMultiSelectBarClicked(operation:)\/title","value":"onMessageMultiSelectBarClickedWithOperation:"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListController~1onMessageMultiSelectBarClicked(operation:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onMessageMultiSelectBarClickedWithOperation:"}],"op":"replace"},{"value":"onMessageBubbleLongPressedWithCell:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListController~1onMessageBubbleLongPressed(cell:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListController~1onMessageBubbleLongPressed(cell:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onMessageBubbleLongPressedWithCell:"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListController~1onOtherPartyTypingText()\/title","value":"onOtherPartyTypingText","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"onOtherPartyTypingText","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListController~1onOtherPartyTypingText()\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListController\/title","op":"replace","value":"MessageListController"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListController\/fragments","value":[{"text":"MessageListController","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"MessageListController"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListController\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListController~1onMessageBubbleClicked(message:)\/title","op":"replace","value":"onMessageBubbleClickedWithMessage:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListController~1onMessageBubbleClicked(message:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"onMessageBubbleClickedWithMessage:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListController~1onMessageWillSendFillExtensionInfo()\/title","value":"onMessageWillSendFillExtensionInfo","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListController~1onMessageWillSendFillExtensionInfo()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onMessageWillSendFillExtensionInfo"}],"op":"replace"},{"op":"replace","value":"onMessageAvatarClickedWithUser:","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListController~1onMessageAvatarClicked(user:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListController~1onMessageAvatarClicked(user:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"onMessageAvatarClickedWithUser:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListController~1onMessageTopicAreaClicked(entity:)\/title","value":"onMessageTopicAreaClickedWithEntity:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"onMessageTopicAreaClickedWithEntity:"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListController~1onMessageTopicAreaClicked(entity:)\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}