{"variants":[{"paths":["\/documentation\/shengwangchatuikit\/messagelistcontroller\/previewcontroller(_:previewitemat:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/messagelistcontroller\/previewcontroller(_:previewitemat:)"]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","kind":"attribute","text":"MainActor"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"previewController","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"controller"},{"kind":"text","text":": "},{"text":"QLPreviewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)QLPreviewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"previewItemAt"},{"kind":"text","text":" "},{"text":"index","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":") -> "},{"text":"QLPreviewItem","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)QLPreviewItem"}],"languages":["swift"],"platforms":["iOS"]}]}],"metadata":{"extendedModule":"ShengwangChatUIKit","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"previewController","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"QLPreviewController","preciseIdentifier":"c:objc(cs)QLPreviewController"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"previewItemAt"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:objc(pl)QLPreviewItem","text":"QLPreviewItem","kind":"typeIdentifier"}],"title":"previewController(_:previewItemAt:)","modules":[{"name":"ShengwangChatUIKit"}],"role":"symbol","externalID":"c:@CM@ShengwangChatUIKit@objc(cs)MessageListController(im)previewController:previewItemAtIndex:","roleHeading":"Instance Method","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"previewController:previewItemAtIndex:"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListController\/previewController(_:previewItemAt:)"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListController","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListController\/QLPreviewControllerDataSource-Implementations"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"QLPreviewControllerDataSource.previewController(_:previewItemAt:)"},{"text":".","type":"text"}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageListController":{"navigatorTitle":[{"text":"MessageListController","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/messagelistcontroller","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListController","abstract":[],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MessageListController"}],"title":"MessageListController","type":"topic"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageListController/QLPreviewControllerDataSource-Implementations":{"type":"topic","role":"collectionGroup","abstract":[],"kind":"article","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListController\/QLPreviewControllerDataSource-Implementations","url":"\/documentation\/shengwangchatuikit\/messagelistcontroller\/qlpreviewcontrollerdatasource-implementations","title":"QLPreviewControllerDataSource Implementations"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageListController/previewController(_:previewItemAt:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"previewController","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"QLPreviewController","preciseIdentifier":"c:objc(cs)QLPreviewController"},{"text":", ","kind":"text"},{"text":"previewItemAt","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:objc(pl)QLPreviewItem","text":"QLPreviewItem","kind":"typeIdentifier"}],"title":"previewController(_:previewItemAt:)","abstract":[],"type":"topic","kind":"symbol","url":"\/documentation\/shengwangchatuikit\/messagelistcontroller\/previewcontroller(_:previewitemat:)","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListController\/previewController(_:previewItemAt:)","navigatorTitle":[{"kind":"identifier","text":"previewController:previewItemAtIndex:"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"previewController:previewItemAtIndex:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"previewController:previewItemAtIndex:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"id<QLPreviewItem>","preciseIdentifier":"c:Qoobjc(pl)QLPreviewItem"},{"kind":"text","text":") "},{"text":"previewController:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"QLPreviewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)QLPreviewController"},{"kind":"text","text":" *) "},{"text":"controller","kind":"internalParam"},{"kind":"text","text":" "},{"text":"previewItemAtIndex:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"kind":"text","text":") "},{"text":"index","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListController\/title","op":"replace","value":"MessageListController"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListController\/fragments","value":[{"text":"MessageListController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListController\/navigatorTitle","value":[{"text":"MessageListController","kind":"identifier"}]},{"op":"replace","value":"previewController:previewItemAtIndex:","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListController~1previewController(_:previewItemAt:)\/title"},{"value":[{"kind":"text","text":"- "},{"text":"previewController:previewItemAtIndex:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListController~1previewController(_:previewItemAt:)\/fragments"}]}]}