{"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"viewContact","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"body"},{"kind":"text","text":": "},{"preciseIdentifier":"s:18ShengwangChatUIKit0B17CustomMessageBodya","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatCustomMessageBody","text":"ChatCustomMessageBody","kind":"typeIdentifier"},{"kind":"text","text":")"}]}],"kind":"declarations"},{"kind":"content","content":[{"type":"heading","level":2,"text":"Discussion","anchor":"discussion"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"body: The custom message body containing contact information."}]}]}],"type":"unorderedList"}]}],"metadata":{"externalID":"c:@CM@ShengwangChatUIKit@objc(cs)MessageListController(im)viewContactWithBody:","navigatorTitle":[{"text":"viewContactWithBody:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"viewContact","kind":"identifier"},{"text":"(","kind":"text"},{"text":"body","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:18ShengwangChatUIKit0B17CustomMessageBodya","text":"ChatCustomMessageBody","kind":"typeIdentifier"},{"kind":"text","text":")"}],"extendedModule":"ShengwangChatUIKit","role":"symbol","modules":[{"name":"ShengwangChatUIKit"}],"symbolKind":"method","roleHeading":"Instance Method","title":"viewContact(body:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/messagelistcontroller\/viewcontact(body:)"]},{"paths":["\/documentation\/shengwangchatuikit\/messagelistcontroller\/viewcontact(body:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListController\/viewContact(body:)","interfaceLanguage":"swift"},"abstract":[{"text":"Opens the contact view for the given custom message body.","type":"text"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListController"]]},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatCustomMessageBody":{"url":"\/documentation\/shengwangchatuikit\/chatcustommessagebody","abstract":[],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ChatCustomMessageBody"}],"type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatCustomMessageBody","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatCustomMessageBody"}],"title":"ChatCustomMessageBody"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageListController":{"navigatorTitle":[{"text":"MessageListController","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/messagelistcontroller","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListController","abstract":[],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MessageListController"}],"title":"MessageListController","type":"topic"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageListController/viewContact(body:)":{"navigatorTitle":[{"kind":"identifier","text":"viewContactWithBody:"}],"abstract":[{"type":"text","text":"Opens the contact view for the given custom message body."}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewContact"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"body"},{"text":": ","kind":"text"},{"text":"ChatCustomMessageBody","kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit0B17CustomMessageBodya"},{"kind":"text","text":")"}],"type":"topic","kind":"symbol","url":"\/documentation\/shengwangchatuikit\/messagelistcontroller\/viewcontact(body:)","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListController\/viewContact(body:)","title":"viewContact(body:)"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"viewContactWithBody:","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewContactWithBody:"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"viewContactWithBody:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AgoraChatCustomMessageBody","text":"AgoraChatCustomMessageBody"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"body"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","value":"MessageListController","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListController\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListController\/fragments","value":[{"text":"MessageListController","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListController\/navigatorTitle","value":[{"text":"MessageListController","kind":"identifier"}]},{"op":"replace","value":"viewContactWithBody:","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListController~1viewContact(body:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListController~1viewContact(body:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"viewContactWithBody:"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}