{"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListController\/viewDetail()","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"@","kind":"attribute"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"viewDetail","kind":"identifier"},{"text":"()","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"kind":"symbol","metadata":{"extendedModule":"ShengwangChatUIKit","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"viewDetail"},{"kind":"text","text":"()"}],"externalID":"c:@CM@ShengwangChatUIKit@objc(cs)MessageListController(im)viewDetail","modules":[{"name":"ShengwangChatUIKit"}],"role":"symbol","roleHeading":"Instance Method","title":"viewDetail()","symbolKind":"method","navigatorTitle":[{"text":"viewDetail","kind":"identifier"}]},"abstract":[{"text":"This method is called to view the detail of a chat message.","type":"text"},{"text":" ","type":"text"},{"text":"It determines the type of chat (individual or group) and presents the appropriate view controller accordingly.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"If the previous view controller in the navigation stack is either "},{"type":"codeVoice","code":"GroupInfoViewController"},{"type":"text","text":" or "},{"type":"codeVoice","code":"ContactInfoViewController"},{"type":"text","text":", it pops the current view controller."},{"text":" ","type":"text"},{"type":"text","text":"If the chat type is individual, it presents the "},{"code":"ContactInfoController","type":"codeVoice"},{"type":"text","text":" with the given profile."},{"text":" ","type":"text"},{"text":"If the chat type is group, it presents the ","type":"text"},{"code":"GroupInfoController","type":"codeVoice"},{"text":" with the given group ID and updates the navigation title with the group name.","type":"text"},{"text":" ","type":"text"},{"text":"If there is no previous view controller in the navigation stack, it checks if the presenting view controller is either ","type":"text"},{"code":"GroupInfoViewController","type":"codeVoice"},{"text":" or ","type":"text"},{"type":"codeVoice","code":"ContactInfoViewController"},{"text":" and dismisses it.","type":"text"},{"text":" ","type":"text"},{"text":"If the chat type is individual, it presents the ","type":"text"},{"type":"codeVoice","code":"ContactInfoController"},{"type":"text","text":" with the given profile."},{"type":"text","text":" "},{"type":"text","text":"If the chat type is group, it presents the "},{"code":"GroupInfoController","type":"codeVoice"},{"type":"text","text":" with the given group ID and updates the navigation title with the group name."}],"variants":[{"paths":["\/documentation\/shengwangchatuikit\/messagelistcontroller\/viewdetail()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/messagelistcontroller\/viewdetail()"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListController"]]},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageListController":{"navigatorTitle":[{"text":"MessageListController","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/messagelistcontroller","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListController","abstract":[],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MessageListController"}],"title":"MessageListController","type":"topic"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageListController/viewDetail()":{"type":"topic","role":"symbol","title":"viewDetail()","kind":"symbol","abstract":[{"text":"This method is called to view the detail of a chat message.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"It determines the type of chat (individual or group) and presents the appropriate view controller accordingly."},{"text":" ","type":"text"},{"type":"text","text":"If the previous view controller in the navigation stack is either "},{"type":"codeVoice","code":"GroupInfoViewController"},{"type":"text","text":" or "},{"type":"codeVoice","code":"ContactInfoViewController"},{"text":", it pops the current view controller.","type":"text"},{"text":" ","type":"text"},{"text":"If the chat type is individual, it presents the ","type":"text"},{"type":"codeVoice","code":"ContactInfoController"},{"text":" with the given profile.","type":"text"},{"text":" ","type":"text"},{"text":"If the chat type is group, it presents the ","type":"text"},{"code":"GroupInfoController","type":"codeVoice"},{"text":" with the given group ID and updates the navigation title with the group name.","type":"text"},{"text":" ","type":"text"},{"text":"If there is no previous view controller in the navigation stack, it checks if the presenting view controller is either ","type":"text"},{"code":"GroupInfoViewController","type":"codeVoice"},{"type":"text","text":" or "},{"code":"ContactInfoViewController","type":"codeVoice"},{"type":"text","text":" and dismisses it."},{"text":" ","type":"text"},{"type":"text","text":"If the chat type is individual, it presents the "},{"type":"codeVoice","code":"ContactInfoController"},{"type":"text","text":" with the given profile."},{"type":"text","text":" "},{"type":"text","text":"If the chat type is group, it presents the "},{"type":"codeVoice","code":"GroupInfoController"},{"text":" with the given group ID and updates the navigation title with the group name.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"viewDetail"}],"url":"\/documentation\/shengwangchatuikit\/messagelistcontroller\/viewdetail()","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageListController\/viewDetail()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"viewDetail","kind":"identifier"},{"kind":"text","text":"()"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","value":"viewDetail","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"viewDetail","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"viewDetail","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"MessageListController","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListController\/title"},{"op":"replace","value":[{"kind":"identifier","text":"MessageListController"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListController\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListController\/navigatorTitle","op":"replace","value":[{"text":"MessageListController","kind":"identifier"}]},{"value":"viewDetail","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListController~1viewDetail()\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageListController~1viewDetail()\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"viewDetail"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}