{"metadata":{"roleHeading":"Initializer","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"coder"},{"kind":"text","text":": "},{"text":"NSCoder","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSCoder"},{"kind":"text","text":")"}],"modules":[{"name":"ShengwangChatUIKit"}],"navigatorTitle":[{"text":"initWithCoder:","kind":"identifier"}],"title":"init(coder:)","externalID":"c:@M@ShengwangChatUIKit@objc(cs)PinnedMessageCell(im)initWithCoder:","symbolKind":"init"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"required","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"coder"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSCoder","kind":"typeIdentifier","text":"NSCoder"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}]}],"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PinnedMessageCell\/init(coder:)","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PinnedMessageCell"]]},"kind":"symbol","variants":[{"paths":["\/documentation\/shengwangchatuikit\/pinnedmessagecell\/init(coder:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/pinnedmessagecell\/init(coder:)"]}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/PinnedMessageCell":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PinnedMessageCell","role":"symbol","url":"\/documentation\/shengwangchatuikit\/pinnedmessagecell","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PinnedMessageCell"}],"title":"PinnedMessageCell","type":"topic","navigatorTitle":[{"text":"PinnedMessageCell","kind":"identifier"}],"kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/PinnedMessageCell/init(coder:)":{"navigatorTitle":[{"text":"initWithCoder:","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PinnedMessageCell\/init(coder:)","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"text":"coder","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder"},{"kind":"text","text":")"}],"url":"\/documentation\/shengwangchatuikit\/pinnedmessagecell\/init(coder:)","title":"init(coder:)","kind":"symbol","type":"topic","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"initWithCoder:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"initWithCoder:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSCoder","text":"NSCoder","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"coder","kind":"internalParam"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0"},{"value":"PinnedMessageCell","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PinnedMessageCell\/title"},{"value":[{"kind":"identifier","text":"PinnedMessageCell"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PinnedMessageCell\/fragments"},{"op":"replace","value":[{"text":"PinnedMessageCell","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PinnedMessageCell\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PinnedMessageCell~1init(coder:)\/title","value":"initWithCoder:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PinnedMessageCell~1init(coder:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithCoder:"}],"op":"replace"}]}]}