{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageBubbleWithArrow\/towards"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","kind":"attribute","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"towards"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@E@BubbleTowards","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/BubbleTowards","text":"BubbleTowards"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageBubbleWithArrow"]]},"sections":[],"metadata":{"externalID":"c:@M@ShengwangChatUIKit@objc(cs)MessageBubbleWithArrow(py)towards","navigatorTitle":[{"kind":"identifier","text":"towards"}],"role":"symbol","modules":[{"name":"ShengwangChatUIKit"}],"title":"towards","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"towards","kind":"identifier"},{"text":": ","kind":"text"},{"text":"BubbleTowards","kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@E@BubbleTowards"}],"roleHeading":"Instance Property","symbolKind":"property"},"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/messagebubblewitharrow\/towards"]},{"paths":["\/documentation\/shengwangchatuikit\/messagebubblewitharrow\/towards"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/BubbleTowards":{"navigatorTitle":[{"kind":"identifier","text":"BubbleTowards"}],"abstract":[],"kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/BubbleTowards","url":"\/documentation\/shengwangchatuikit\/bubbletowards","title":"BubbleTowards","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"BubbleTowards"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageBubbleWithArrow":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageBubbleWithArrow","navigatorTitle":[{"text":"MessageBubbleWithArrow","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/messagebubblewitharrow","type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MessageBubbleWithArrow"}],"title":"MessageBubbleWithArrow","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageBubbleWithArrow/towards":{"url":"\/documentation\/shengwangchatuikit\/messagebubblewitharrow\/towards","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageBubbleWithArrow\/towards","type":"topic","navigatorTitle":[{"text":"towards","kind":"identifier"}],"role":"symbol","abstract":[],"title":"towards","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"towards","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@E@BubbleTowards","text":"BubbleTowards","kind":"typeIdentifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"towards"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"towards","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@E@BubbleTowards","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/BubbleTowards","text":"BubbleTowards"},{"kind":"text","text":" "},{"kind":"identifier","text":"towards"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"value":"BubbleTowards","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1BubbleTowards\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1BubbleTowards\/fragments","value":[{"kind":"identifier","text":"BubbleTowards"}],"op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"BubbleTowards"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1BubbleTowards\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageBubbleWithArrow\/title","op":"replace","value":"MessageBubbleWithArrow"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageBubbleWithArrow\/fragments","value":[{"text":"MessageBubbleWithArrow","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageBubbleWithArrow\/navigatorTitle","value":[{"text":"MessageBubbleWithArrow","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageBubbleWithArrow~1towards\/title","value":"towards"},{"value":[{"kind":"identifier","text":"towards"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageBubbleWithArrow~1towards\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}