{"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/FileMessageView"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"article","variants":[{"paths":["\/documentation\/shengwangchatuikit\/filemessageview\/themeswitchprotocol-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/filemessageview\/themeswitchprotocol-implementations"]}],"topicSections":[{"generated":true,"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/FileMessageView\/switchTheme(style:)"],"anchor":"Instance-Methods"}],"metadata":{"role":"collectionGroup","roleHeading":"API Collection","title":"ThemeSwitchProtocol Implementations","modules":[{"name":"ShengwangChatUIKit"}]},"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/FileMessageView\/ThemeSwitchProtocol-Implementations","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/FileMessageView/switchTheme(style:)":{"url":"\/documentation\/shengwangchatuikit\/filemessageview\/switchtheme(style:)","title":"switchTheme(style:)","kind":"symbol","navigatorTitle":[{"text":"switchThemeWithStyle:","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"switchTheme"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"style"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ThemeStyle","preciseIdentifier":"c:@M@ShengwangChatUIKit@E@ThemeStyle"},{"text":")","kind":"text"}],"abstract":[{"text":"When some view Implement the protocol method,you can use ","type":"text"},{"type":"codeVoice","code":"Theme.switchTheme(style: .dark)"},{"type":"text","text":" to switch theme."}],"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/FileMessageView\/switchTheme(style:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/FileMessageView":{"url":"\/documentation\/shengwangchatuikit\/filemessageview","navigatorTitle":[{"kind":"identifier","text":"FileMessageView"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FileMessageView","kind":"identifier"}],"title":"FileMessageView","abstract":[],"kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/FileMessageView","type":"topic"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/topicSections","value":[{"anchor":"Instance-Methods","title":"Instance Methods","generated":true,"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/FileMessageView\/switchTheme(style:)"]}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":"switchThemeWithStyle:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1FileMessageView~1switchTheme(style:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1FileMessageView~1switchTheme(style:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"switchThemeWithStyle:","kind":"identifier"}]},{"value":"FileMessageView","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1FileMessageView\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1FileMessageView\/fragments","op":"replace","value":[{"text":"FileMessageView","kind":"identifier"}]},{"op":"replace","value":[{"text":"FileMessageView","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1FileMessageView\/navigatorTitle"}]}]}