{"metadata":{"modules":[{"name":"ShengwangChatUIKit"}],"externalID":"s:18ShengwangChatUIKit17LanguageConvertorC6sharedACvpZ","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"shared"},{"text":": ","kind":"text"},{"text":"LanguageConvertor","kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)LanguageConvertor"}],"role":"symbol","roleHeading":"Type Property","symbolKind":"property","title":"shared"},"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/LanguageConvertor\/shared","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/languageconvertor\/shared"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/LanguageConvertor"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"shared"},{"text":": ","kind":"text"},{"text":"LanguageConvertor","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/LanguageConvertor","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)LanguageConvertor","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/LanguageConvertor":{"navigatorTitle":[{"text":"LanguageConvertor","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/languageconvertor","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LanguageConvertor","kind":"identifier"}],"role":"symbol","title":"LanguageConvertor","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/LanguageConvertor","kind":"symbol","abstract":[{"type":"text","text":"A utility class for converting language keys to localized strings."}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/LanguageConvertor/shared":{"url":"\/documentation\/shengwangchatuikit\/languageconvertor\/shared","kind":"symbol","type":"topic","abstract":[],"role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/LanguageConvertor\/shared","title":"shared","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"shared"},{"text":": ","kind":"text"},{"text":"LanguageConvertor","kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(cs)LanguageConvertor"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"LanguageConvertor","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1LanguageConvertor\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1LanguageConvertor\/fragments","op":"replace","value":[{"text":"LanguageConvertor","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1LanguageConvertor\/navigatorTitle","value":[{"kind":"identifier","text":"LanguageConvertor"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}