{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/agorachat\/agorachatmessage"]}],"metadata":{"symbolKind":"extension","title":"AgoraChatMessage","extendedModule":"AgoraChat","roleHeading":"Extended Class","role":"symbol","fragments":[{"text":"extension","kind":"keyword"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit0B7Messagea","text":"ChatMessage"}],"externalID":"s:e:c:@CM@ShengwangChatUIKit@@objc(cs)AgoraChatMessage(py)user","modules":[{"relatedModules":["AgoraChat"],"name":"ShengwangChatUIKit"}],"navigatorTitle":[{"text":"AgoraChatMessage","kind":"identifier"}]},"kind":"symbol","topicSections":[{"anchor":"Instance-Properties","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/AgoraChat\/AgoraChatMessage\/alertMessageThreadId","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/AgoraChat\/AgoraChatMessage\/contentSize","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/AgoraChat\/AgoraChatMessage\/edited","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/AgoraChat\/AgoraChatMessage\/hasQuote","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/AgoraChat\/AgoraChatMessage\/mention","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/AgoraChat\/AgoraChatMessage\/quoteMessage","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/AgoraChat\/AgoraChatMessage\/quoteMessageId","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/AgoraChat\/AgoraChatMessage\/replyIcon","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/AgoraChat\/AgoraChatMessage\/showContent","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/AgoraChat\/AgoraChatMessage\/showDate","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/AgoraChat\/AgoraChatMessage\/showDetailDate","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/AgoraChat\/AgoraChatMessage\/showType","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/AgoraChat\/AgoraChatMessage\/translation","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/AgoraChat\/AgoraChatMessage\/user"],"title":"Instance Properties","generated":true}],"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/AgoraChat"]]},"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/AgoraChat\/AgoraChatMessage","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"extension","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"s:18ShengwangChatUIKit0B7Messagea","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatMessage","text":"ChatMessage","kind":"typeIdentifier"}]}]}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/AgoraChat/AgoraChatMessage/hasQuote":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"hasQuote","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"url":"\/documentation\/shengwangchatuikit\/agorachat\/agorachatmessage\/hasquote","abstract":[{"text":"When you send a text message. Quote the message.","type":"text"}],"role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/AgoraChat\/AgoraChatMessage\/hasQuote","title":"hasQuote","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/AgoraChat/AgoraChatMessage/translation":{"url":"\/documentation\/shengwangchatuikit\/agorachat\/agorachatmessage\/translation","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"translation","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?","kind":"text"}],"role":"symbol","title":"translation","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/AgoraChat\/AgoraChatMessage\/translation","kind":"symbol","abstract":[{"text":"Translation of the text message.","type":"text"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatMessage":{"url":"\/documentation\/shengwangchatuikit\/chatmessage","abstract":[],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ChatMessage"}],"type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatMessage","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChatMessage"}],"title":"ChatMessage"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/AgoraChat/AgoraChatMessage/showDetailDate":{"type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/AgoraChat\/AgoraChatMessage\/showDetailDate","abstract":[{"type":"text","text":"Message display date on chat cell."}],"role":"symbol","url":"\/documentation\/shengwangchatuikit\/agorachat\/agorachatmessage\/showdetaildate","title":"showDetailDate","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"showDetailDate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/AgoraChat/AgoraChatMessage/showDate":{"kind":"symbol","url":"\/documentation\/shengwangchatuikit\/agorachat\/agorachatmessage\/showdate","role":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"showDate","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/AgoraChat\/AgoraChatMessage\/showDate","title":"showDate","abstract":[{"type":"text","text":"Message display date on conversation list cell."}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/AgoraChat/AgoraChatMessage/replyIcon":{"url":"\/documentation\/shengwangchatuikit\/agorachat\/agorachatmessage\/replyicon","type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/AgoraChat\/AgoraChatMessage\/replyIcon","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"replyIcon","kind":"identifier"},{"kind":"text","text":": "},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"?"}],"kind":"symbol","abstract":[],"title":"replyIcon"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/AgoraChat/AgoraChatMessage/alertMessageThreadId":{"title":"alertMessageThreadId","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/AgoraChat\/AgoraChatMessage\/alertMessageThreadId","role":"symbol","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"alertMessageThreadId"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"type":"topic","abstract":[],"url":"\/documentation\/shengwangchatuikit\/agorachat\/agorachatmessage\/alertmessagethreadid"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/AgoraChat/AgoraChatMessage/showContent":{"role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Message show content."}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/AgoraChat\/AgoraChatMessage\/showContent","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"showContent"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"type":"topic","title":"showContent","url":"\/documentation\/shengwangchatuikit\/agorachat\/agorachatmessage\/showcontent"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/AgoraChat":{"abstract":[],"title":"AgoraChat","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/AgoraChat","role":"collection","type":"topic","kind":"symbol","url":"\/documentation\/shengwangchatuikit\/agorachat"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/AgoraChat/AgoraChatMessage/quoteMessage":{"abstract":[{"text":"When you send a text message. Quote the message.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"quoteMessage"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit0B7Messagea","text":"ChatMessage"},{"kind":"text","text":"?"}],"title":"quoteMessage","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/AgoraChat\/AgoraChatMessage\/quoteMessage","url":"\/documentation\/shengwangchatuikit\/agorachat\/agorachatmessage\/quotemessage","kind":"symbol","role":"symbol","type":"topic"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/AgoraChat/AgoraChatMessage/quoteMessageId":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"quoteMessageId","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"title":"quoteMessageId","abstract":[{"text":"When you send a text message. Quote the message.","type":"text"}],"type":"topic","kind":"symbol","url":"\/documentation\/shengwangchatuikit\/agorachat\/agorachatmessage\/quotemessageid","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/AgoraChat\/AgoraChatMessage\/quoteMessageId"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/AgoraChat/AgoraChatMessage/user":{"abstract":[{"isActive":true,"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatUserProfileProtocol","type":"reference"}],"title":"user","type":"topic","role":"symbol","url":"\/documentation\/shengwangchatuikit\/agorachat\/agorachatmessage\/user","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/AgoraChat\/AgoraChatMessage\/user","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"user","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(pl)ChatUserProfileProtocol","text":"ChatUserProfileProtocol"},{"kind":"text","text":"?"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/AgoraChat/AgoraChatMessage/mention":{"kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Text message if you were mentioned,the property isn’t empty."}],"url":"\/documentation\/shengwangchatuikit\/agorachat\/agorachatmessage\/mention","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"mention"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"type":"topic","title":"mention","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/AgoraChat\/AgoraChatMessage\/mention"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/AgoraChat/AgoraChatMessage/edited":{"url":"\/documentation\/shengwangchatuikit\/agorachat\/agorachatmessage\/edited","role":"symbol","type":"topic","abstract":[{"text":"Whether message edited or not.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/AgoraChat\/AgoraChatMessage\/edited","title":"edited","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"edited","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/AgoraChat/AgoraChatMessage/contentSize":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/AgoraChat\/AgoraChatMessage\/contentSize","abstract":[],"kind":"symbol","url":"\/documentation\/shengwangchatuikit\/agorachat\/agorachatmessage\/contentsize","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"contentSize"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGSize","text":"CGSize","kind":"typeIdentifier"}],"title":"contentSize"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/AgoraChat/AgoraChatMessage/showType":{"role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Message show type on the conversation list."}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/AgoraChat\/AgoraChatMessage\/showType","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"showType"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"type":"topic","title":"showType","url":"\/documentation\/shengwangchatuikit\/agorachat\/agorachatmessage\/showtype"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatUserProfileProtocol":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatUserProfileProtocol","abstract":[{"text":"Profile of the ChatUIKit display needed.","type":"text"}],"title":"ChatUserProfileProtocol","type":"topic","kind":"symbol","navigatorTitle":[{"text":"ChatUserProfileProtocol","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"ChatUserProfileProtocol","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/chatuserprofileprotocol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/AgoraChat/AgoraChatMessage":{"fragments":[{"text":"extension","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChatMessage","kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit0B7Messagea"}],"kind":"symbol","url":"\/documentation\/shengwangchatuikit\/agorachat\/agorachatmessage","type":"topic","title":"AgoraChatMessage","abstract":[],"role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/AgoraChat\/AgoraChatMessage","navigatorTitle":[{"text":"AgoraChatMessage","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatUserProfileProtocol\/title","value":"ChatUserProfileProtocol"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatUserProfileProtocol\/fragments","value":[{"text":"ChatUserProfileProtocol","kind":"identifier"}]},{"value":[{"text":"ChatUserProfileProtocol","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatUserProfileProtocol\/navigatorTitle"}]}]}