{"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/shengwangchatuikit\/searchblockcontactcontroller\/uisearchcontrollerdelegate-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/shengwangchatuikit\/searchblockcontactcontroller\/uisearchcontrollerdelegate-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/SearchBlockContactController"]]},"kind":"article","metadata":{"modules":[{"name":"ShengwangChatUIKit"}],"role":"collectionGroup","title":"UISearchControllerDelegate Implementations","roleHeading":"API Collection"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/SearchBlockContactController\/UISearchControllerDelegate-Implementations"},"topicSections":[{"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/SearchBlockContactController\/didDismissSearchController(_:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/SearchBlockContactController\/didPresentSearchController(_:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/SearchBlockContactController\/presentSearchController(_:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/SearchBlockContactController\/willDismissSearchController(_:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/SearchBlockContactController\/willPresentSearchController(_:)"],"anchor":"Instance-Methods","title":"Instance Methods","generated":true}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/SearchBlockContactController/didPresentSearchController(_:)":{"type":"topic","role":"symbol","title":"didPresentSearchController(_:)","kind":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"didPresentSearchController:"}],"url":"\/documentation\/shengwangchatuikit\/searchblockcontactcontroller\/didpresentsearchcontroller(_:)","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/SearchBlockContactController\/didPresentSearchController(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didPresentSearchController"},{"text":"(","kind":"text"},{"text":"UISearchController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UISearchController"},{"kind":"text","text":")"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/SearchBlockContactController/willPresentSearchController(_:)":{"url":"\/documentation\/shengwangchatuikit\/searchblockcontactcontroller\/willpresentsearchcontroller(_:)","type":"topic","title":"willPresentSearchController(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"willPresentSearchController"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UISearchController","kind":"typeIdentifier","text":"UISearchController"},{"kind":"text","text":")"}],"role":"symbol","kind":"symbol","abstract":[],"navigatorTitle":[{"text":"willPresentSearchController:","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/SearchBlockContactController\/willPresentSearchController(_:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/SearchBlockContactController":{"abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SearchBlockContactController"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SearchBlockContactController"}],"kind":"symbol","type":"topic","url":"\/documentation\/shengwangchatuikit\/searchblockcontactcontroller","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/SearchBlockContactController","title":"SearchBlockContactController"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/SearchBlockContactController/didDismissSearchController(_:)":{"title":"didDismissSearchController(_:)","abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didDismissSearchController"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UISearchController","kind":"typeIdentifier","text":"UISearchController"},{"text":")","kind":"text"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/SearchBlockContactController\/didDismissSearchController(_:)","navigatorTitle":[{"text":"didDismissSearchController:","kind":"identifier"}],"type":"topic","url":"\/documentation\/shengwangchatuikit\/searchblockcontactcontroller\/diddismisssearchcontroller(_:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/SearchBlockContactController/presentSearchController(_:)":{"type":"topic","title":"presentSearchController(_:)","url":"\/documentation\/shengwangchatuikit\/searchblockcontactcontroller\/presentsearchcontroller(_:)","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/SearchBlockContactController\/presentSearchController(_:)","abstract":[],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"presentSearchController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UISearchController","text":"UISearchController"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"presentSearchController:"}],"role":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/SearchBlockContactController/willDismissSearchController(_:)":{"title":"willDismissSearchController(_:)","abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"willDismissSearchController"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UISearchController","kind":"typeIdentifier","text":"UISearchController"},{"text":")","kind":"text"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/SearchBlockContactController\/willDismissSearchController(_:)","navigatorTitle":[{"text":"willDismissSearchController:","kind":"identifier"}],"type":"topic","url":"\/documentation\/shengwangchatuikit\/searchblockcontactcontroller\/willdismisssearchcontroller(_:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":[{"title":"Instance Methods","generated":true,"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/SearchBlockContactController\/didDismissSearchController(_:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/SearchBlockContactController\/didPresentSearchController(_:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/SearchBlockContactController\/presentSearchController(_:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/SearchBlockContactController\/willDismissSearchController(_:)","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/SearchBlockContactController\/willPresentSearchController(_:)"],"anchor":"Instance-Methods"}],"path":"\/topicSections","op":"replace"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1SearchBlockContactController~1didPresentSearchController(_:)\/title","value":"didPresentSearchController:"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1SearchBlockContactController~1didPresentSearchController(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didPresentSearchController:"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1SearchBlockContactController~1willPresentSearchController(_:)\/title","value":"willPresentSearchController:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1SearchBlockContactController~1willPresentSearchController(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"willPresentSearchController:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1SearchBlockContactController\/title","value":"SearchBlockContactController"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1SearchBlockContactController\/fragments","value":[{"kind":"identifier","text":"SearchBlockContactController"}]},{"value":[{"text":"SearchBlockContactController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1SearchBlockContactController\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1SearchBlockContactController~1didDismissSearchController(_:)\/title","op":"replace","value":"didDismissSearchController:"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1SearchBlockContactController~1didDismissSearchController(_:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"didDismissSearchController:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1SearchBlockContactController~1presentSearchController(_:)\/title","value":"presentSearchController:"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1SearchBlockContactController~1presentSearchController(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"presentSearchController:"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1SearchBlockContactController~1willDismissSearchController(_:)\/title","value":"willDismissSearchController:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1SearchBlockContactController~1willDismissSearchController(_:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"willDismissSearchController:","kind":"identifier"}]}]}]}