{"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"UISearchControllerDelegate.willPresentSearchController(_:)"},{"text":".","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/searchblockcontactcontroller\/willpresentsearchcontroller(_:)"]},{"paths":["\/documentation\/shengwangchatuikit\/searchblockcontactcontroller\/willpresentsearchcontroller(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"title":"willPresentSearchController(_:)","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"willPresentSearchController","kind":"identifier"},{"kind":"text","text":"("},{"text":"UISearchController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UISearchController"},{"text":")","kind":"text"}],"role":"symbol","roleHeading":"Instance Method","modules":[{"name":"ShengwangChatUIKit"}],"navigatorTitle":[{"text":"willPresentSearchController:","kind":"identifier"}],"externalID":"c:@CM@ShengwangChatUIKit@objc(cs)SearchBlockContactController(im)willPresentSearchController:","extendedModule":"ShengwangChatUIKit"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","kind":"attribute","text":"MainActor"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"willPresentSearchController"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"searchController"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UISearchController","text":"UISearchController","kind":"typeIdentifier"},{"kind":"text","text":")"}]}]}],"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/SearchBlockContactController\/willPresentSearchController(_:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/SearchBlockContactController","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/SearchBlockContactController\/UISearchControllerDelegate-Implementations"]]},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/SearchBlockContactController/willPresentSearchController(_:)":{"url":"\/documentation\/shengwangchatuikit\/searchblockcontactcontroller\/willpresentsearchcontroller(_:)","type":"topic","title":"willPresentSearchController(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"willPresentSearchController"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UISearchController","kind":"typeIdentifier","text":"UISearchController"},{"kind":"text","text":")"}],"role":"symbol","kind":"symbol","abstract":[],"navigatorTitle":[{"text":"willPresentSearchController:","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/SearchBlockContactController\/willPresentSearchController(_:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/SearchBlockContactController":{"abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SearchBlockContactController"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SearchBlockContactController"}],"kind":"symbol","type":"topic","url":"\/documentation\/shengwangchatuikit\/searchblockcontactcontroller","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/SearchBlockContactController","title":"SearchBlockContactController"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/SearchBlockContactController/UISearchControllerDelegate-Implementations":{"abstract":[],"role":"collectionGroup","kind":"article","type":"topic","url":"\/documentation\/shengwangchatuikit\/searchblockcontactcontroller\/uisearchcontrollerdelegate-implementations","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/SearchBlockContactController\/UISearchControllerDelegate-Implementations","title":"UISearchControllerDelegate Implementations"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"willPresentSearchController:"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"willPresentSearchController:","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"willPresentSearchController:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UISearchController","kind":"typeIdentifier","text":"UISearchController"},{"kind":"text","text":" *) "},{"text":"searchController","kind":"internalParam"},{"kind":"text","text":";"}]}]},"op":"replace"},{"value":"willPresentSearchController:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1SearchBlockContactController~1willPresentSearchController(_:)\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"willPresentSearchController:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1SearchBlockContactController~1willPresentSearchController(_:)\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1SearchBlockContactController\/title","op":"replace","value":"SearchBlockContactController"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1SearchBlockContactController\/fragments","value":[{"kind":"identifier","text":"SearchBlockContactController"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1SearchBlockContactController\/navigatorTitle","value":[{"kind":"identifier","text":"SearchBlockContactController"}],"op":"replace"}]}]}