{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageInputExtensionView"]]},"metadata":{"modules":[{"name":"ShengwangChatUIKit"}],"roleHeading":"Instance Method","symbolKind":"method","role":"symbol","externalID":"c:@M@ShengwangChatUIKit@objc(cs)MessageInputExtensionView(im)hitTest:withEvent:","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"hitTest","kind":"identifier"},{"text":"(","kind":"text"},{"text":"CGPoint","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGPoint"},{"text":", ","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIEvent","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIEvent"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"hitTest:withEvent:","kind":"identifier"}],"title":"hitTest(_:with:)"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"hitTest","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"point","kind":"internalParam"},{"kind":"text","text":": "},{"text":"CGPoint","preciseIdentifier":"c:@S@CGPoint","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"with","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"event","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UIEvent","preciseIdentifier":"c:objc(cs)UIEvent"},{"kind":"text","text":"?) -> "},{"text":"UIView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView"},{"text":"?","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/messageinputextensionview\/hittest(_:with:)"]},{"paths":["\/documentation\/shengwangchatuikit\/messageinputextensionview\/hittest(_:with:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageInputExtensionView\/hitTest(_:with:)","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageInputExtensionView/hitTest(_:with:)":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageInputExtensionView\/hitTest(_:with:)","url":"\/documentation\/shengwangchatuikit\/messageinputextensionview\/hittest(_:with:)","role":"symbol","kind":"symbol","title":"hitTest(_:with:)","abstract":[],"navigatorTitle":[{"text":"hitTest:withEvent:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"hitTest","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@S@CGPoint","kind":"typeIdentifier","text":"CGPoint"},{"kind":"text","text":", "},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIEvent","text":"UIEvent"},{"kind":"text","text":"?) -> "},{"text":"UIView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView"},{"text":"?","kind":"text"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageInputExtensionView":{"abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MessageInputExtensionView","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MessageInputExtensionView"}],"kind":"symbol","type":"topic","url":"\/documentation\/shengwangchatuikit\/messageinputextensionview","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageInputExtensionView","title":"MessageInputExtensionView"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"hitTest:withEvent:","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"hitTest:withEvent:"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"text":" *) ","kind":"text"},{"text":"hitTest:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"CGPoint","preciseIdentifier":"c:@S@CGPoint","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"point","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"withEvent:"},{"text":"(","kind":"text"},{"text":"UIEvent","preciseIdentifier":"c:objc(cs)UIEvent","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"event","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageInputExtensionView~1hitTest(_:with:)\/title","op":"replace","value":"hitTest:withEvent:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"hitTest:withEvent:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageInputExtensionView~1hitTest(_:with:)\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageInputExtensionView\/title","value":"MessageInputExtensionView","op":"replace"},{"value":[{"text":"MessageInputExtensionView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageInputExtensionView\/fragments"},{"value":[{"text":"MessageInputExtensionView","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageInputExtensionView\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}