{"topicSections":[{"generated":true,"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatHistoryViewController\/switchTheme(style:)"]}],"metadata":{"roleHeading":"API Collection","role":"collectionGroup","modules":[{"name":"ShengwangChatUIKit"}],"title":"ThemeSwitchProtocol Implementations"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatHistoryViewController"]]},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatHistoryViewController\/ThemeSwitchProtocol-Implementations"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/chathistoryviewcontroller\/themeswitchprotocol-implementations"]},{"paths":["\/documentation\/shengwangchatuikit\/chathistoryviewcontroller\/themeswitchprotocol-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"article","references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatHistoryViewController/switchTheme(style:)":{"url":"\/documentation\/shengwangchatuikit\/chathistoryviewcontroller\/switchtheme(style:)","abstract":[{"text":"When some view Implement the protocol method,you can use ","type":"text"},{"type":"codeVoice","code":"Theme.switchTheme(style: .dark)"},{"text":" to switch theme.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"switchThemeWithStyle:","kind":"identifier"}],"type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatHistoryViewController\/switchTheme(style:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"switchTheme","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"style"},{"text":": ","kind":"text"},{"text":"ThemeStyle","kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@E@ThemeStyle"},{"text":")","kind":"text"}],"title":"switchTheme(style:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatHistoryViewController":{"title":"ChatHistoryViewController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChatHistoryViewController","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/chathistoryviewcontroller","role":"symbol","abstract":[],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatHistoryViewController"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatHistoryViewController"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/topicSections","op":"replace","value":[{"generated":true,"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatHistoryViewController\/switchTheme(style:)"],"anchor":"Instance-Methods"}]},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":"switchThemeWithStyle:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatHistoryViewController~1switchTheme(style:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"switchThemeWithStyle:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatHistoryViewController~1switchTheme(style:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatHistoryViewController\/title","value":"ChatHistoryViewController"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatHistoryViewController\/fragments","op":"replace","value":[{"kind":"identifier","text":"ChatHistoryViewController"}]},{"value":[{"kind":"identifier","text":"ChatHistoryViewController"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatHistoryViewController\/navigatorTitle","op":"replace"}]}]}