{"kind":"article","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatHistoryViewController\/UITableViewDelegate-Implementations"},"metadata":{"title":"UITableViewDelegate Implementations","modules":[{"name":"ShengwangChatUIKit"}],"role":"collectionGroup","roleHeading":"API Collection"},"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/chathistoryviewcontroller\/uitableviewdelegate-implementations"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/chathistoryviewcontroller\/uitableviewdelegate-implementations"]}],"topicSections":[{"anchor":"Instance-Methods","identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatHistoryViewController\/tableView(_:heightForRowAt:)"],"generated":true,"title":"Instance Methods"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatHistoryViewController"]]},"sections":[],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatHistoryViewController":{"title":"ChatHistoryViewController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChatHistoryViewController","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/chathistoryviewcontroller","role":"symbol","abstract":[],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatHistoryViewController"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatHistoryViewController"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatHistoryViewController/tableView(_:heightForRowAt:)":{"type":"topic","kind":"symbol","title":"tableView(_:heightForRowAt:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"tableView"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITableView","text":"UITableView"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"heightForRowAt"},{"kind":"text","text":": "},{"text":"IndexPath","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":") -> "},{"text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"tableView:heightForRowAtIndexPath:","kind":"identifier"}],"abstract":[],"url":"\/documentation\/shengwangchatuikit\/chathistoryviewcontroller\/tableview(_:heightforrowat:)","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatHistoryViewController\/tableView(_:heightForRowAt:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/topicSections","op":"replace","value":[{"identifiers":["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatHistoryViewController\/tableView(_:heightForRowAt:)"],"generated":true,"title":"Instance Methods","anchor":"Instance-Methods"}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatHistoryViewController\/title","value":"ChatHistoryViewController","op":"replace"},{"value":[{"kind":"identifier","text":"ChatHistoryViewController"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatHistoryViewController\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"ChatHistoryViewController"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatHistoryViewController\/navigatorTitle","op":"replace"},{"value":"tableView:heightForRowAtIndexPath:","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatHistoryViewController~1tableView(_:heightForRowAt:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"tableView:heightForRowAtIndexPath:"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatHistoryViewController~1tableView(_:heightForRowAt:)\/fragments","op":"replace"}]}]}