{"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/chatappearance\/messagelongpressmenustyle"]},{"paths":["\/documentation\/shengwangchatuikit\/chatappearance\/messagelongpressmenustyle"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatAppearance\/messageLongPressMenuStyle","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatAppearance"]]},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"messageLongPressMenuStyle"}],"externalID":"c:@M@ShengwangChatUIKit@objc(cs)ChatAppearance(py)messageLongPressMenuStyle","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"messageLongPressMenuStyle","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@E@MessageLongPressMenuStyle","kind":"typeIdentifier","text":"MessageLongPressMenuStyle"}],"role":"symbol","title":"messageLongPressMenuStyle","modules":[{"name":"ShengwangChatUIKit"}],"symbolKind":"property"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"messageLongPressMenuStyle","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@E@MessageLongPressMenuStyle","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageLongPressMenuStyle","text":"MessageLongPressMenuStyle"}]}]}],"abstract":[{"type":"text","text":"Choose to show the message long press menu style."}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatAppearance/messageLongPressMenuStyle":{"url":"\/documentation\/shengwangchatuikit\/chatappearance\/messagelongpressmenustyle","navigatorTitle":[{"text":"messageLongPressMenuStyle","kind":"identifier"}],"title":"messageLongPressMenuStyle","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatAppearance\/messageLongPressMenuStyle","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"messageLongPressMenuStyle","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MessageLongPressMenuStyle","preciseIdentifier":"c:@M@ShengwangChatUIKit@E@MessageLongPressMenuStyle","kind":"typeIdentifier"}],"type":"topic","kind":"symbol","abstract":[{"text":"Choose to show the message long press menu style.","type":"text"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatAppearance":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ChatAppearance","kind":"identifier"}],"type":"topic","abstract":[],"role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatAppearance","title":"ChatAppearance","navigatorTitle":[{"kind":"identifier","text":"ChatAppearance"}],"url":"\/documentation\/shengwangchatuikit\/chatappearance"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageLongPressMenuStyle":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"MessageLongPressMenuStyle","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/messagelongpressmenustyle","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageLongPressMenuStyle","kind":"symbol","navigatorTitle":[{"text":"MessageLongPressMenuStyle","kind":"identifier"}],"role":"symbol","type":"topic","title":"MessageLongPressMenuStyle","abstract":[]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"messageLongPressMenuStyle"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"messageLongPressMenuStyle","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":") ","kind":"text"},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@E@MessageLongPressMenuStyle","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageLongPressMenuStyle","text":"MessageLongPressMenuStyle"},{"text":" ","kind":"text"},{"kind":"identifier","text":"messageLongPressMenuStyle"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatAppearance~1messageLongPressMenuStyle\/title","value":"messageLongPressMenuStyle"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatAppearance~1messageLongPressMenuStyle\/fragments","value":[{"kind":"identifier","text":"messageLongPressMenuStyle"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatAppearance\/title","value":"ChatAppearance","op":"replace"},{"value":[{"text":"ChatAppearance","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatAppearance\/fragments"},{"op":"replace","value":[{"text":"ChatAppearance","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatAppearance\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageLongPressMenuStyle\/title","value":"MessageLongPressMenuStyle","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageLongPressMenuStyle\/fragments","value":[{"text":"MessageLongPressMenuStyle","kind":"identifier"}],"op":"replace"},{"value":[{"text":"MessageLongPressMenuStyle","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageLongPressMenuStyle\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}