{"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"paths":["\/documentation\/shengwangchatuikit\/chatappearance\/moremessagealertposition"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/shengwangchatuikit\/chatappearance\/moremessagealertposition"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatAppearance\/moreMessageAlertPosition","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatAppearance"]]},"kind":"symbol","metadata":{"navigatorTitle":[{"text":"moreMessageAlertPosition","kind":"identifier"}],"externalID":"c:@M@ShengwangChatUIKit@objc(cs)ChatAppearance(py)moreMessageAlertPosition","roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"moreMessageAlertPosition"},{"text":": ","kind":"text"},{"text":"MoreMessagePosition","kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@E@MoreMessagePosition"}],"role":"symbol","title":"moreMessageAlertPosition","modules":[{"name":"ShengwangChatUIKit"}],"symbolKind":"property"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"moreMessageAlertPosition","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MoreMessagePosition","text":"MoreMessagePosition","preciseIdentifier":"c:@M@ShengwangChatUIKit@E@MoreMessagePosition"}]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"The alert position on received lots of messages."}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatAppearance/moreMessageAlertPosition":{"navigatorTitle":[{"text":"moreMessageAlertPosition","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/chatappearance\/moremessagealertposition","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"moreMessageAlertPosition"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@E@MoreMessagePosition","text":"MoreMessagePosition"}],"role":"symbol","title":"moreMessageAlertPosition","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatAppearance\/moreMessageAlertPosition","kind":"symbol","abstract":[{"type":"text","text":"The alert position on received lots of messages."}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatAppearance":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ChatAppearance","kind":"identifier"}],"type":"topic","abstract":[],"role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatAppearance","title":"ChatAppearance","navigatorTitle":[{"kind":"identifier","text":"ChatAppearance"}],"url":"\/documentation\/shengwangchatuikit\/chatappearance"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MoreMessagePosition":{"kind":"symbol","navigatorTitle":[{"text":"MoreMessagePosition","kind":"identifier"}],"title":"MoreMessagePosition","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MoreMessagePosition","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MoreMessagePosition"}],"type":"topic","url":"\/documentation\/shengwangchatuikit\/moremessageposition","abstract":[]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"op":"replace","value":"moreMessageAlertPosition","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"value":[{"text":"moreMessageAlertPosition","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MoreMessagePosition","text":"MoreMessagePosition","preciseIdentifier":"c:@M@ShengwangChatUIKit@E@MoreMessagePosition"},{"text":" ","kind":"text"},{"kind":"identifier","text":"moreMessageAlertPosition"},{"text":";","kind":"text"}]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatAppearance~1moreMessageAlertPosition\/title","op":"replace","value":"moreMessageAlertPosition"},{"value":[{"text":"moreMessageAlertPosition","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatAppearance~1moreMessageAlertPosition\/fragments"},{"op":"replace","value":"ChatAppearance","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatAppearance\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatAppearance\/fragments","value":[{"text":"ChatAppearance","kind":"identifier"}]},{"value":[{"text":"ChatAppearance","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatAppearance\/navigatorTitle","op":"replace"},{"op":"replace","value":"MoreMessagePosition","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MoreMessagePosition\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MoreMessagePosition\/fragments","value":[{"text":"MoreMessagePosition","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"text":"MoreMessagePosition","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MoreMessagePosition\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}