{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatAppearance"]]},"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatAppearance\/newMessageSoundPath","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Instance Property","role":"symbol","title":"newMessageSoundPath","modules":[{"name":"ShengwangChatUIKit"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"newMessageSoundPath"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"externalID":"c:@M@ShengwangChatUIKit@objc(cs)ChatAppearance(py)newMessageSoundPath","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"newMessageSoundPath"}]},"abstract":[{"text":"New message tone audio path","type":"text"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"newMessageSoundPath"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/chatappearance\/newmessagesoundpath"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/chatappearance\/newmessagesoundpath"]}],"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatAppearance/newMessageSoundPath":{"role":"symbol","navigatorTitle":[{"text":"newMessageSoundPath","kind":"identifier"}],"abstract":[{"text":"New message tone audio path","type":"text"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatAppearance\/newMessageSoundPath","url":"\/documentation\/shengwangchatuikit\/chatappearance\/newmessagesoundpath","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"newMessageSoundPath","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"type":"topic","title":"newMessageSoundPath"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatAppearance":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ChatAppearance","kind":"identifier"}],"type":"topic","abstract":[],"role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatAppearance","title":"ChatAppearance","navigatorTitle":[{"kind":"identifier","text":"ChatAppearance"}],"url":"\/documentation\/shengwangchatuikit\/chatappearance"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"newMessageSoundPath"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"text":"newMessageSoundPath","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"newMessageSoundPath"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatAppearance~1newMessageSoundPath\/title","value":"newMessageSoundPath","op":"replace"},{"value":[{"text":"newMessageSoundPath","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatAppearance~1newMessageSoundPath\/fragments","op":"replace"},{"op":"replace","value":"ChatAppearance","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatAppearance\/title"},{"value":[{"kind":"identifier","text":"ChatAppearance"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatAppearance\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatAppearance\/navigatorTitle","value":[{"text":"ChatAppearance","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}