{"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatAppearance"]]},"metadata":{"roleHeading":"Instance Property","modules":[{"name":"ShengwangChatUIKit"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"receiveTextColor"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"}],"navigatorTitle":[{"text":"receiveTextColor","kind":"identifier"}],"role":"symbol","title":"receiveTextColor","externalID":"c:@M@ShengwangChatUIKit@objc(cs)ChatAppearance(py)receiveTextColor","symbolKind":"property"},"abstract":[{"text":"The color of the recipient of the text message.","type":"text"}],"variants":[{"paths":["\/documentation\/shengwangchatuikit\/chatappearance\/receivetextcolor"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/shengwangchatuikit\/chatappearance\/receivetextcolor"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatAppearance\/receiveTextColor"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"receiveTextColor","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"set"},{"text":" }","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatAppearance":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ChatAppearance","kind":"identifier"}],"type":"topic","abstract":[],"role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatAppearance","title":"ChatAppearance","navigatorTitle":[{"kind":"identifier","text":"ChatAppearance"}],"url":"\/documentation\/shengwangchatuikit\/chatappearance"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatAppearance/receiveTextColor":{"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"receiveTextColor"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatAppearance\/receiveTextColor","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"receiveTextColor"}],"role":"symbol","title":"receiveTextColor","url":"\/documentation\/shengwangchatuikit\/chatappearance\/receivetextcolor","abstract":[{"type":"text","text":"The color of the recipient of the text message."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"receiveTextColor"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"text":"receiveTextColor","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"text":" * ","kind":"text"},{"text":"receiveTextColor","kind":"identifier"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatAppearance\/title","value":"ChatAppearance"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatAppearance\/fragments","value":[{"text":"ChatAppearance","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"ChatAppearance"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatAppearance\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatAppearance~1receiveTextColor\/title","value":"receiveTextColor"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatAppearance~1receiveTextColor\/fragments","op":"replace","value":[{"text":"receiveTextColor","kind":"identifier"}]}]}]}