{"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoPlaceHolder"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"text":"?","kind":"text"}]}]}],"metadata":{"title":"videoPlaceHolder","navigatorTitle":[{"text":"videoPlaceHolder","kind":"identifier"}],"role":"symbol","modules":[{"name":"ShengwangChatUIKit"}],"externalID":"c:@M@ShengwangChatUIKit@objc(cs)ChatAppearance(py)videoPlaceHolder","symbolKind":"property","roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"videoPlaceHolder"},{"text":": ","kind":"text"},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"text":"?","kind":"text"}]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatAppearance\/videoPlaceHolder"},"abstract":[{"type":"text","text":"Default placeholder image for video messages."}],"variants":[{"paths":["\/documentation\/shengwangchatuikit\/chatappearance\/videoplaceholder"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/chatappearance\/videoplaceholder"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatAppearance"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatAppearance/videoPlaceHolder":{"type":"topic","role":"symbol","title":"videoPlaceHolder","kind":"symbol","abstract":[{"text":"Default placeholder image for video messages.","type":"text"}],"navigatorTitle":[{"text":"videoPlaceHolder","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/chatappearance\/videoplaceholder","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatAppearance\/videoPlaceHolder","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"videoPlaceHolder","kind":"identifier"},{"kind":"text","text":": "},{"text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatAppearance":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ChatAppearance","kind":"identifier"}],"type":"topic","abstract":[],"role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatAppearance","title":"ChatAppearance","navigatorTitle":[{"kind":"identifier","text":"ChatAppearance"}],"url":"\/documentation\/shengwangchatuikit\/chatappearance"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"videoPlaceHolder"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"videoPlaceHolder","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"kind":"text","text":") "},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":" * "},{"kind":"identifier","text":"videoPlaceHolder"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"videoPlaceHolder","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatAppearance~1videoPlaceHolder\/title"},{"value":[{"text":"videoPlaceHolder","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatAppearance~1videoPlaceHolder\/fragments","op":"replace"},{"value":"ChatAppearance","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatAppearance\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatAppearance\/fragments","value":[{"kind":"identifier","text":"ChatAppearance"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatAppearance\/navigatorTitle","op":"replace","value":[{"text":"ChatAppearance","kind":"identifier"}]}]}]}