{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageOperation"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageOperation\/copy"},"variants":[{"paths":["\/documentation\/shengwangchatuikit\/messageoperation\/copy"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/shengwangchatuikit\/messageoperation\/copy"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"externalID":"c:@M@ShengwangChatUIKit@E@MessageOperation@MessageOperationCopy","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"copy","kind":"identifier"}],"symbolKind":"case","navigatorTitle":[{"text":"MessageOperationCopy","kind":"identifier"}],"title":"MessageOperation.copy","role":"symbol","modules":[{"name":"ShengwangChatUIKit"}],"roleHeading":"Case"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"copy","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageOperation":{"role":"symbol","kind":"symbol","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"MessageOperation","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MessageOperation"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageOperation","url":"\/documentation\/shengwangchatuikit\/messageoperation","abstract":[],"title":"MessageOperation"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageOperation/copy":{"kind":"symbol","abstract":[],"title":"MessageOperation.copy","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MessageOperationCopy"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"copy","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageOperation\/copy","type":"topic","url":"\/documentation\/shengwangchatuikit\/messageoperation\/copy"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"MessageOperationCopy"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"MessageOperationCopy"}]},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"MessageOperationCopy","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageOperation\/title","value":"MessageOperation"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageOperation\/fragments","value":[{"text":"MessageOperation","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"text":"MessageOperation","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageOperation\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageOperation~1copy\/title","op":"replace","value":"MessageOperationCopy"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageOperation~1copy\/fragments","value":[{"text":"MessageOperationCopy","kind":"identifier"}],"op":"replace"}]}]}