{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatNavigationBarClickEvent"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatNavigationBarClickEvent\/avatar"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/chatnavigationbarclickevent\/avatar"]},{"paths":["\/documentation\/shengwangchatuikit\/chatnavigationbarclickevent\/avatar"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"metadata":{"modules":[{"name":"ShengwangChatUIKit"}],"externalID":"c:@M@ShengwangChatUIKit@E@ChatNavigationBarClickEvent@ChatNavigationBarClickEventAvatar","symbolKind":"case","role":"symbol","title":"ChatNavigationBarClickEvent.avatar","roleHeading":"Case","navigatorTitle":[{"kind":"identifier","text":"ChatNavigationBarClickEventAvatar"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"avatar","kind":"identifier"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"avatar","kind":"identifier"}]}]}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatNavigationBarClickEvent/avatar":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatNavigationBarClickEvent\/avatar","url":"\/documentation\/shengwangchatuikit\/chatnavigationbarclickevent\/avatar","role":"symbol","title":"ChatNavigationBarClickEvent.avatar","abstract":[],"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"avatar","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ChatNavigationBarClickEventAvatar"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatNavigationBarClickEvent":{"abstract":[],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatNavigationBarClickEvent","navigatorTitle":[{"kind":"identifier","text":"ChatNavigationBarClickEvent"}],"kind":"symbol","url":"\/documentation\/shengwangchatuikit\/chatnavigationbarclickevent","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatNavigationBarClickEvent"}],"title":"ChatNavigationBarClickEvent","type":"topic"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"value":"ChatNavigationBarClickEventAvatar","path":"\/metadata\/title","op":"replace"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"ChatNavigationBarClickEventAvatar","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"ChatNavigationBarClickEventAvatar","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatNavigationBarClickEvent~1avatar\/title","value":"ChatNavigationBarClickEventAvatar"},{"value":[{"kind":"identifier","text":"ChatNavigationBarClickEventAvatar"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatNavigationBarClickEvent~1avatar\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatNavigationBarClickEvent\/title","value":"ChatNavigationBarClickEvent","op":"replace"},{"value":[{"kind":"identifier","text":"ChatNavigationBarClickEvent"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatNavigationBarClickEvent\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatNavigationBarClickEvent\/navigatorTitle","value":[{"text":"ChatNavigationBarClickEvent","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}