{"metadata":{"title":"contentHeightConstraint","roleHeading":"Instance Property","externalID":"c:@M@ShengwangChatUIKit@objc(cs)MessageEditor(py)contentHeightConstraint","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"contentHeightConstraint"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSLayoutConstraint","text":"NSLayoutConstraint","kind":"typeIdentifier"},{"kind":"text","text":"!"}],"symbolKind":"property","modules":[{"name":"ShengwangChatUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"contentHeightConstraint"}],"role":"symbol"},"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageEditor"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/messageeditor\/contentheightconstraint"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/messageeditor\/contentheightconstraint"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageEditor\/contentHeightConstraint"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"contentHeightConstraint"},{"text":": ","kind":"text"},{"text":"NSLayoutConstraint","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSLayoutConstraint"},{"text":"! { get }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageEditor/contentHeightConstraint":{"title":"contentHeightConstraint","url":"\/documentation\/shengwangchatuikit\/messageeditor\/contentheightconstraint","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"contentHeightConstraint"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"NSLayoutConstraint","preciseIdentifier":"c:objc(cs)NSLayoutConstraint"},{"text":"!","kind":"text"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageEditor\/contentHeightConstraint","role":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"contentHeightConstraint"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageEditor":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessageEditor","kind":"identifier"}],"role":"symbol","url":"\/documentation\/shengwangchatuikit\/messageeditor","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageEditor","title":"MessageEditor","kind":"symbol","abstract":[],"navigatorTitle":[{"text":"MessageEditor","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"value":"contentHeightConstraint","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","value":[{"text":"contentHeightConstraint","kind":"identifier"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSLayoutConstraint","text":"NSLayoutConstraint"},{"kind":"text","text":" * "},{"text":"contentHeightConstraint","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"value":"contentHeightConstraint","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageEditor~1contentHeightConstraint\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageEditor~1contentHeightConstraint\/fragments","op":"replace","value":[{"kind":"identifier","text":"contentHeightConstraint"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageEditor\/title","value":"MessageEditor","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageEditor\/fragments","op":"replace","value":[{"text":"MessageEditor","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageEditor\/navigatorTitle","value":[{"text":"MessageEditor","kind":"identifier"}]}]}]}