{"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/LinkRecognizeTextView\/canPerformAction(_:withSender:)","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/shengwangchatuikit\/linkrecognizetextview\/canperformaction(_:withsender:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/linkrecognizetextview\/canperformaction(_:withsender:)"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/LinkRecognizeTextView"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"kind":"text","text":" "},{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"canPerformAction"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"action","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Selector","preciseIdentifier":"s:10ObjectiveC8SelectorV","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"withSender"},{"kind":"text","text":" "},{"text":"sender","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"canPerformAction","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"Selector","preciseIdentifier":"s:10ObjectiveC8SelectorV"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"withSender"},{"kind":"text","text":": "},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"title":"canPerformAction(_:withSender:)","modules":[{"name":"ShengwangChatUIKit"}],"role":"symbol","symbolKind":"method","externalID":"c:@M@ShengwangChatUIKit@objc(cs)LinkRecognizeTextView(im)canPerformAction:withSender:","roleHeading":"Instance Method","navigatorTitle":[{"text":"canPerformAction:withSender:","kind":"identifier"}]},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/LinkRecognizeTextView":{"title":"LinkRecognizeTextView","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"LinkRecognizeTextView","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/shengwangchatuikit\/linkrecognizetextview","type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/LinkRecognizeTextView","navigatorTitle":[{"kind":"identifier","text":"LinkRecognizeTextView"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/LinkRecognizeTextView/canPerformAction(_:withSender:)":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/LinkRecognizeTextView\/canPerformAction(_:withSender:)","navigatorTitle":[{"kind":"identifier","text":"canPerformAction:withSender:"}],"url":"\/documentation\/shengwangchatuikit\/linkrecognizetextview\/canperformaction(_:withsender:)","type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"canPerformAction"},{"text":"(","kind":"text"},{"text":"Selector","kind":"typeIdentifier","preciseIdentifier":"s:10ObjectiveC8SelectorV"},{"kind":"text","text":", "},{"text":"withSender","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"title":"canPerformAction(_:withSender:)","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"canPerformAction:withSender:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"canPerformAction:withSender:","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":") "},{"text":"canPerformAction:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SEL","preciseIdentifier":"c:e","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"action"},{"kind":"text","text":" "},{"text":"withSender:","kind":"identifier"},{"kind":"text","text":"("},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"sender","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1LinkRecognizeTextView\/title","value":"LinkRecognizeTextView"},{"value":[{"kind":"identifier","text":"LinkRecognizeTextView"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1LinkRecognizeTextView\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1LinkRecognizeTextView\/navigatorTitle","value":[{"text":"LinkRecognizeTextView","kind":"identifier"}],"op":"replace"},{"value":"canPerformAction:withSender:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1LinkRecognizeTextView~1canPerformAction(_:withSender:)\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"canPerformAction:withSender:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1LinkRecognizeTextView~1canPerformAction(_:withSender:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}