{"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/LinkRecognizeTextView"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/linkrecognizetextview\/selectedrange"]},{"paths":["\/documentation\/shengwangchatuikit\/linkrecognizetextview\/selectedrange"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"text":"override","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"selectedRange","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSRange","text":"NSRange"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"kind":"text","text":" }"}]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/LinkRecognizeTextView\/selectedRange","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"selectedRange"}],"symbolKind":"property","modules":[{"name":"ShengwangChatUIKit"}],"role":"symbol","title":"selectedRange","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"selectedRange","kind":"identifier"},{"kind":"text","text":": "},{"text":"NSRange","preciseIdentifier":"c:@T@NSRange","kind":"typeIdentifier"}],"externalID":"c:@M@ShengwangChatUIKit@objc(cs)LinkRecognizeTextView(py)selectedRange","roleHeading":"Instance Property"},"kind":"symbol","references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/LinkRecognizeTextView/selectedRange":{"navigatorTitle":[{"kind":"identifier","text":"selectedRange"}],"url":"\/documentation\/shengwangchatuikit\/linkrecognizetextview\/selectedrange","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"selectedRange","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSRange","preciseIdentifier":"c:@T@NSRange","kind":"typeIdentifier"}],"role":"symbol","title":"selectedRange","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/LinkRecognizeTextView\/selectedRange","kind":"symbol","abstract":[]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/LinkRecognizeTextView":{"title":"LinkRecognizeTextView","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"LinkRecognizeTextView","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/shengwangchatuikit\/linkrecognizetextview","type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/LinkRecognizeTextView","navigatorTitle":[{"kind":"identifier","text":"LinkRecognizeTextView"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"selectedRange"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"selectedRange"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@S@_NSRange","text":"NSRange","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"kind":"identifier","text":"selectedRange"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"value":"selectedRange","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1LinkRecognizeTextView~1selectedRange\/title","op":"replace"},{"op":"replace","value":[{"text":"selectedRange","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1LinkRecognizeTextView~1selectedRange\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1LinkRecognizeTextView\/title","op":"replace","value":"LinkRecognizeTextView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1LinkRecognizeTextView\/fragments","value":[{"text":"LinkRecognizeTextView","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"LinkRecognizeTextView"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1LinkRecognizeTextView\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}