{"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"selectedTextColor","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"}],"platforms":["iOS"]}]}],"sections":[],"metadata":{"roleHeading":"Instance Property","role":"symbol","title":"selectedTextColor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"selectedTextColor","kind":"identifier"},{"kind":"text","text":": "},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"}],"modules":[{"name":"ShengwangChatUIKit"}],"externalID":"s:18ShengwangChatUIKit21LinkRecognizeTextViewC08selectedF5ColorSo7UIColorCvp","symbolKind":"property"},"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/LinkRecognizeTextView\/selectedTextColor","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/linkrecognizetextview\/selectedtextcolor"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/LinkRecognizeTextView"]]},"kind":"symbol","references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/LinkRecognizeTextView/selectedTextColor":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/LinkRecognizeTextView\/selectedTextColor","url":"\/documentation\/shengwangchatuikit\/linkrecognizetextview\/selectedtextcolor","type":"topic","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"selectedTextColor"},{"text":": ","kind":"text"},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"}],"title":"selectedTextColor","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/LinkRecognizeTextView":{"title":"LinkRecognizeTextView","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"LinkRecognizeTextView","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/shengwangchatuikit\/linkrecognizetextview","type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/LinkRecognizeTextView","navigatorTitle":[{"kind":"identifier","text":"LinkRecognizeTextView"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1LinkRecognizeTextView\/title","value":"LinkRecognizeTextView","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"LinkRecognizeTextView"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1LinkRecognizeTextView\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1LinkRecognizeTextView\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"LinkRecognizeTextView"}]}]}]}