{"variants":[{"paths":["\/documentation\/shengwangchatuikit\/linkrecognizetextview\/textviewdidchangeselection(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/linkrecognizetextview\/textviewdidchangeselection(_:)"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/LinkRecognizeTextView"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"symbolKind":"method","role":"symbol","externalID":"c:@M@ShengwangChatUIKit@objc(cs)LinkRecognizeTextView(im)textViewDidChangeSelection:","title":"textViewDidChangeSelection(_:)","roleHeading":"Instance Method","modules":[{"name":"ShengwangChatUIKit"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"textViewDidChangeSelection"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"UITextView","preciseIdentifier":"c:objc(cs)UITextView"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"textViewDidChangeSelection:","kind":"identifier"}]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"textViewDidChangeSelection","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"textView","kind":"internalParam"},{"kind":"text","text":": "},{"text":"UITextView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITextView"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"UITextViewDelegate.textViewDidChangeSelection(_:)"},{"type":"text","text":"."}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/LinkRecognizeTextView\/textViewDidChangeSelection(_:)"},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/LinkRecognizeTextView/textViewDidChangeSelection(_:)":{"title":"textViewDidChangeSelection(_:)","role":"symbol","abstract":[],"kind":"symbol","url":"\/documentation\/shengwangchatuikit\/linkrecognizetextview\/textviewdidchangeselection(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"textViewDidChangeSelection"},{"kind":"text","text":"("},{"text":"UITextView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITextView"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"textViewDidChangeSelection:"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/LinkRecognizeTextView\/textViewDidChangeSelection(_:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/LinkRecognizeTextView":{"title":"LinkRecognizeTextView","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"LinkRecognizeTextView","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/shengwangchatuikit\/linkrecognizetextview","type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/LinkRecognizeTextView","navigatorTitle":[{"kind":"identifier","text":"LinkRecognizeTextView"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"textViewDidChangeSelection:","path":"\/metadata\/title","op":"replace"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"textViewDidChangeSelection:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"textViewDidChangeSelection:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UITextView","text":"UITextView","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"textView","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1LinkRecognizeTextView~1textViewDidChangeSelection(_:)\/title","value":"textViewDidChangeSelection:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1LinkRecognizeTextView~1textViewDidChangeSelection(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"textViewDidChangeSelection:"}]},{"value":"LinkRecognizeTextView","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1LinkRecognizeTextView\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1LinkRecognizeTextView\/fragments","value":[{"kind":"identifier","text":"LinkRecognizeTextView"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1LinkRecognizeTextView\/navigatorTitle","op":"replace","value":[{"text":"LinkRecognizeTextView","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}