{"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"addActionHandler"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"actionHandler"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(pl)PinnedMessagesContainerDelegate","text":"PinnedMessagesContainerDelegate","kind":"typeIdentifier"},{"text":")","kind":"text"}],"required":true,"navigatorTitle":[{"kind":"identifier","text":"addActionHandlerWithActionHandler:"}],"modules":[{"name":"ShengwangChatUIKit"}],"title":"addActionHandler(actionHandler:)","symbolKind":"method","roleHeading":"Instance Method","role":"symbol","externalID":"c:@M@ShengwangChatUIKit@objc(pl)IPinnedMessagesContainerDriver(im)addActionHandlerWithActionHandler:"},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/IPinnedMessagesContainerDriver"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/IPinnedMessagesContainerDriver\/addActionHandler(actionHandler:)"},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Add action events listener of "},{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PinnedMessagesContainer","isActive":true,"type":"reference"},{"type":"text","text":"."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addActionHandler","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"actionHandler"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PinnedMessagesContainerDelegate","text":"PinnedMessagesContainerDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(pl)PinnedMessagesContainerDelegate"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}]},{"parameters":[{"name":"actionHandler","content":[{"inlineContent":[{"type":"text","text":"The object of conform "},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PinnedMessagesContainerDelegate"},{"text":".","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"}],"variants":[{"paths":["\/documentation\/shengwangchatuikit\/ipinnedmessagescontainerdriver\/addactionhandler(actionhandler:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/ipinnedmessagescontainerdriver\/addactionhandler(actionhandler:)"]}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/PinnedMessagesContainer":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PinnedMessagesContainer","title":"PinnedMessagesContainer","navigatorTitle":[{"kind":"identifier","text":"PinnedMessagesContainer"}],"url":"\/documentation\/shengwangchatuikit\/pinnedmessagescontainer","role":"symbol","kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PinnedMessagesContainer","kind":"identifier"}],"abstract":[]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/IPinnedMessagesContainerDriver/addActionHandler(actionHandler:)":{"abstract":[{"type":"text","text":"Add action events listener of "},{"type":"reference","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PinnedMessagesContainer","isActive":true},{"text":".","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"addActionHandler"},{"text":"(","kind":"text"},{"text":"actionHandler","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(pl)PinnedMessagesContainerDelegate","text":"PinnedMessagesContainerDelegate"},{"kind":"text","text":")"}],"role":"symbol","type":"topic","url":"\/documentation\/shengwangchatuikit\/ipinnedmessagescontainerdriver\/addactionhandler(actionhandler:)","required":true,"title":"addActionHandler(actionHandler:)","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/IPinnedMessagesContainerDriver\/addActionHandler(actionHandler:)","navigatorTitle":[{"kind":"identifier","text":"addActionHandlerWithActionHandler:"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/IPinnedMessagesContainerDriver":{"abstract":[],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"IPinnedMessagesContainerDriver"}],"role":"symbol","navigatorTitle":[{"text":"IPinnedMessagesContainerDriver","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/shengwangchatuikit\/ipinnedmessagescontainerdriver","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/IPinnedMessagesContainerDriver","title":"IPinnedMessagesContainerDriver"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/PinnedMessagesContainerDelegate":{"abstract":[],"url":"\/documentation\/shengwangchatuikit\/pinnedmessagescontainerdelegate","title":"PinnedMessagesContainerDelegate","role":"symbol","navigatorTitle":[{"text":"PinnedMessagesContainerDelegate","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PinnedMessagesContainerDelegate","kind":"symbol","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"PinnedMessagesContainerDelegate","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"addActionHandlerWithActionHandler:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"addActionHandlerWithActionHandler:"}]},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"addActionHandlerWithActionHandler:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id<PinnedMessagesContainerDelegate>","preciseIdentifier":"c:Qo@M@ShengwangChatUIKit@objc(pl)PinnedMessagesContainerDelegate","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"actionHandler","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The object of conform ","type":"text"},{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/PinnedMessagesContainerDelegate","isActive":true,"type":"reference"},{"text":".","type":"text"}]}],"name":"actionHandler"}]},"op":"replace","path":"\/primaryContentSections\/1"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PinnedMessagesContainer\/title","value":"PinnedMessagesContainer"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PinnedMessagesContainer\/fragments","op":"replace","value":[{"kind":"identifier","text":"PinnedMessagesContainer"}]},{"value":[{"kind":"identifier","text":"PinnedMessagesContainer"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PinnedMessagesContainer\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1IPinnedMessagesContainerDriver~1addActionHandler(actionHandler:)\/title","value":"addActionHandlerWithActionHandler:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1IPinnedMessagesContainerDriver~1addActionHandler(actionHandler:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"addActionHandlerWithActionHandler:","kind":"identifier"}]},{"value":"IPinnedMessagesContainerDriver","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1IPinnedMessagesContainerDriver\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1IPinnedMessagesContainerDriver\/fragments","value":[{"text":"IPinnedMessagesContainerDriver","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1IPinnedMessagesContainerDriver\/navigatorTitle","value":[{"kind":"identifier","text":"IPinnedMessagesContainerDriver"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PinnedMessagesContainerDelegate\/title","value":"PinnedMessagesContainerDelegate"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PinnedMessagesContainerDelegate\/fragments","op":"replace","value":[{"text":"PinnedMessagesContainerDelegate","kind":"identifier"}]},{"op":"replace","value":[{"text":"PinnedMessagesContainerDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1PinnedMessagesContainerDelegate\/navigatorTitle"}]}]}