{"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@","kind":"attribute"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"text":" ","kind":"text"},{"text":"override","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"viewDidAppear"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"animated","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/SearchConversationsController"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","variants":[{"paths":["\/documentation\/shengwangchatuikit\/searchconversationscontroller\/viewdidappear(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/searchconversationscontroller\/viewdidappear(_:)"]}],"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/SearchConversationsController\/viewDidAppear(_:)","interfaceLanguage":"swift"},"sections":[],"metadata":{"role":"symbol","roleHeading":"Instance Method","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"viewDidAppear:"}],"title":"viewDidAppear(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"viewDidAppear","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"externalID":"c:@M@ShengwangChatUIKit@objc(cs)SearchConversationsController(im)viewDidAppear:","modules":[{"name":"ShengwangChatUIKit"}]},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/SearchConversationsController/viewDidAppear(_:)":{"role":"symbol","kind":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/SearchConversationsController\/viewDidAppear(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"viewDidAppear"},{"text":"(","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"viewDidAppear:"}],"type":"topic","url":"\/documentation\/shengwangchatuikit\/searchconversationscontroller\/viewdidappear(_:)","title":"viewDidAppear(_:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/SearchConversationsController":{"type":"topic","role":"symbol","title":"SearchConversationsController","kind":"symbol","abstract":[],"navigatorTitle":[{"text":"SearchConversationsController","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/searchconversationscontroller","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/SearchConversationsController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SearchConversationsController"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"viewDidAppear:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"viewDidAppear:"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"viewDidAppear:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"text":") ","kind":"text"},{"text":"animated","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1SearchConversationsController~1viewDidAppear(_:)\/title","op":"replace","value":"viewDidAppear:"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1SearchConversationsController~1viewDidAppear(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"viewDidAppear:"}],"op":"replace"},{"op":"replace","value":"SearchConversationsController","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1SearchConversationsController\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1SearchConversationsController\/fragments","op":"replace","value":[{"text":"SearchConversationsController","kind":"identifier"}]},{"op":"replace","value":[{"text":"SearchConversationsController","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1SearchConversationsController\/navigatorTitle"}]}]}