{"abstract":[{"type":"text","text":"Clean register views."}],"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/Theme\/unregisterSwitchThemeViews()","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/Theme"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"navigatorTitle":[{"text":"unregisterSwitchThemeViews","kind":"identifier"}],"externalID":"c:@M@ShengwangChatUIKit@objc(cs)Theme(cm)unregisterSwitchThemeViews","roleHeading":"Type Method","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"unregisterSwitchThemeViews","kind":"identifier"},{"text":"()","kind":"text"}],"role":"symbol","title":"unregisterSwitchThemeViews()","modules":[{"name":"ShengwangChatUIKit"}],"symbolKind":"method"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"unregisterSwitchThemeViews"},{"kind":"text","text":"()"}]}]}],"variants":[{"paths":["\/documentation\/shengwangchatuikit\/theme\/unregisterswitchthemeviews()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/shengwangchatuikit\/theme\/unregisterswitchthemeviews()"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/Theme":{"type":"topic","abstract":[{"type":"text","text":"The theme switching class is used for users to switch themes or register some user’s own views that comply with the ThemeSwitchProtocol protocol."},{"text":" ","type":"text"},{"type":"text","text":"How to use?"},{"type":"text","text":" "},{"text":"A view conform ThemeSwitchProtocol.Then Implement protocol methods.When you want switch theme that light and dark themes provided by default chatroom UIKit  ","type":"text"},{"type":"codeVoice","code":"theme"},{"type":"text","text":" ."},{"text":" ","type":"text"},{"type":"text","text":"Call "},{"type":"codeVoice","code":"Theme.switchTheme(style: .dark)"},{"type":"text","text":" method"},{"type":"text","text":" "},{"text":"A view conform ThemeSwitchProtocol.Then Implement protocol methods.When you want switch themes provided by customer .","type":"text"}],"navigatorTitle":[{"text":"Theme","kind":"identifier"}],"kind":"symbol","title":"Theme","url":"\/documentation\/shengwangchatuikit\/theme","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Theme"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/Theme","role":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/Theme/unregisterSwitchThemeViews()":{"navigatorTitle":[{"text":"unregisterSwitchThemeViews","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/theme\/unregisterswitchthemeviews()","type":"topic","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"unregisterSwitchThemeViews"},{"text":"()","kind":"text"}],"role":"symbol","title":"unregisterSwitchThemeViews()","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/Theme\/unregisterSwitchThemeViews()","kind":"symbol","abstract":[{"type":"text","text":"Clean register views."}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Type Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"unregisterSwitchThemeViews"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"unregisterSwitchThemeViews"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"unregisterSwitchThemeViews","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1Theme\/title","value":"Theme"},{"value":[{"kind":"identifier","text":"Theme"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1Theme\/fragments"},{"op":"replace","value":[{"text":"Theme","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1Theme\/navigatorTitle"},{"value":"unregisterSwitchThemeViews","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1Theme~1unregisterSwitchThemeViews()\/title"},{"value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"unregisterSwitchThemeViews"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1Theme~1unregisterSwitchThemeViews()\/fragments"}]}]}