{"variants":[{"paths":["\/documentation\/shengwangchatuikit\/isectionindexlistdriver\/selectitem(indexpath:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/isectionindexlistdriver\/selectitem(indexpath:)"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ISectionIndexListDriver"]]},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"text":"Selects an item at the specified index path.","type":"text"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"selectItem","kind":"identifier"},{"text":"(","kind":"text"},{"text":"indexPath","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"text":")","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"name":"indexPath","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The index path of the item to be selected."}]}]}],"kind":"parameters"}],"metadata":{"symbolKind":"method","roleHeading":"Instance Method","title":"selectItem(indexPath:)","navigatorTitle":[{"kind":"identifier","text":"selectItemWithIndexPath:"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"selectItem","kind":"identifier"},{"kind":"text","text":"("},{"text":"indexPath","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation9IndexPathV","kind":"typeIdentifier","text":"IndexPath"},{"kind":"text","text":")"}],"externalID":"c:@M@ShengwangChatUIKit@objc(pl)ISectionIndexListDriver(im)selectItemWithIndexPath:","modules":[{"name":"ShengwangChatUIKit"}],"required":true},"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ISectionIndexListDriver\/selectItem(indexPath:)","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ISectionIndexListDriver":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ISectionIndexListDriver","kind":"identifier"}],"navigatorTitle":[{"text":"ISectionIndexListDriver","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/isectionindexlistdriver","type":"topic","abstract":[{"text":"A protocol that defines the driver for a section index list.","type":"text"}],"title":"ISectionIndexListDriver","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ISectionIndexListDriver","role":"symbol","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ISectionIndexListDriver/selectItem(indexPath:)":{"kind":"symbol","required":true,"title":"selectItem(indexPath:)","navigatorTitle":[{"kind":"identifier","text":"selectItemWithIndexPath:"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ISectionIndexListDriver\/selectItem(indexPath:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"selectItem","kind":"identifier"},{"kind":"text","text":"("},{"text":"indexPath","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation9IndexPathV","text":"IndexPath"},{"text":")","kind":"text"}],"type":"topic","url":"\/documentation\/shengwangchatuikit\/isectionindexlistdriver\/selectitem(indexpath:)","abstract":[{"text":"Selects an item at the specified index path.","type":"text"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"selectItemWithIndexPath:","path":"\/metadata\/title","op":"replace"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"selectItemWithIndexPath:","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"selectItemWithIndexPath:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSIndexPath","text":"NSIndexPath"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"indexPath"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"indexPath","content":[{"inlineContent":[{"text":"The index path of the item to be selected.","type":"text"}],"type":"paragraph"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ISectionIndexListDriver\/title","op":"replace","value":"ISectionIndexListDriver"},{"op":"replace","value":[{"kind":"identifier","text":"ISectionIndexListDriver"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ISectionIndexListDriver\/fragments"},{"value":[{"kind":"identifier","text":"ISectionIndexListDriver"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ISectionIndexListDriver\/navigatorTitle"},{"op":"replace","value":"selectItemWithIndexPath:","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ISectionIndexListDriver~1selectItem(indexPath:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ISectionIndexListDriver~1selectItem(indexPath:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"selectItemWithIndexPath:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}