{"abstract":[{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageCell","isActive":true,"type":"reference"},{"type":"text","text":" required init method."}],"metadata":{"symbolKind":"init","navigatorTitle":[{"kind":"identifier","text":"initWithTowards:reuseIdentifier:"}],"role":"symbol","modules":[{"name":"ShengwangChatUIKit"}],"roleHeading":"Initializer","externalID":"c:@M@ShengwangChatUIKit@objc(cs)AlertMessageCell(im)initWithTowards:reuseIdentifier:","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"towards"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"BubbleTowards","preciseIdentifier":"c:@M@ShengwangChatUIKit@E@BubbleTowards"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"reuseIdentifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"init(towards:reuseIdentifier:)"},"sections":[],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/AlertMessageCell\/init(towards:reuseIdentifier:)"},"variants":[{"paths":["\/documentation\/shengwangchatuikit\/alertmessagecell\/init(towards:reuseidentifier:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/shengwangchatuikit\/alertmessagecell\/init(towards:reuseidentifier:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/AlertMessageCell"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"required","kind":"keyword"},{"kind":"text","text":" "},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"towards","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"BubbleTowards","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/BubbleTowards","preciseIdentifier":"c:@M@ShengwangChatUIKit@E@BubbleTowards","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"reuseIdentifier","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":")","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"name":"towards","content":[{"inlineContent":[{"text":"","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/BubbleTowards"},{"text":" is towards of the bubble.","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Cell reuse identifier."}]}],"name":"reuseIdentifier"}],"kind":"parameters"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/BubbleTowards":{"navigatorTitle":[{"kind":"identifier","text":"BubbleTowards"}],"abstract":[],"kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/BubbleTowards","url":"\/documentation\/shengwangchatuikit\/bubbletowards","title":"BubbleTowards","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"BubbleTowards"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/MessageCell":{"navigatorTitle":[{"text":"MessageCell","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageCell"}],"title":"MessageCell","abstract":[],"url":"\/documentation\/shengwangchatuikit\/messagecell"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/AlertMessageCell/init(towards:reuseIdentifier:)":{"navigatorTitle":[{"text":"initWithTowards:reuseIdentifier:","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/AlertMessageCell\/init(towards:reuseIdentifier:)","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"towards","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"BubbleTowards","kind":"typeIdentifier","preciseIdentifier":"c:@M@ShengwangChatUIKit@E@BubbleTowards"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"reuseIdentifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"init(towards:reuseIdentifier:)","abstract":[{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/MessageCell"},{"type":"text","text":" required init method."}],"url":"\/documentation\/shengwangchatuikit\/alertmessagecell\/init(towards:reuseidentifier:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/AlertMessageCell":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/AlertMessageCell","abstract":[],"url":"\/documentation\/shengwangchatuikit\/alertmessagecell","type":"topic","kind":"symbol","role":"symbol","title":"AlertMessageCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AlertMessageCell"}],"navigatorTitle":[{"text":"AlertMessageCell","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"value":"initWithTowards:reuseIdentifier:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithTowards:reuseIdentifier:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"id","preciseIdentifier":"c:*Qo","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithTowards:"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"BubbleTowards","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/BubbleTowards","preciseIdentifier":"c:@M@ShengwangChatUIKit@E@BubbleTowards","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"towards"},{"text":" ","kind":"text"},{"text":"reuseIdentifier:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"reuseIdentifier"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1BubbleTowards\/title","value":"BubbleTowards","op":"replace"},{"value":[{"kind":"identifier","text":"BubbleTowards"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1BubbleTowards\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1BubbleTowards\/navigatorTitle","value":[{"kind":"identifier","text":"BubbleTowards"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageCell\/title","op":"replace","value":"MessageCell"},{"value":[{"kind":"identifier","text":"MessageCell"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageCell\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1MessageCell\/navigatorTitle","value":[{"text":"MessageCell","kind":"identifier"}]},{"value":"initWithTowards:reuseIdentifier:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1AlertMessageCell~1init(towards:reuseIdentifier:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1AlertMessageCell~1init(towards:reuseIdentifier:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithTowards:reuseIdentifier:","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1AlertMessageCell\/title","value":"AlertMessageCell"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1AlertMessageCell\/fragments","value":[{"text":"AlertMessageCell","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1AlertMessageCell\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"AlertMessageCell"}]}]}]}