{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/FontTheme"]]},"kind":"symbol","sections":[],"variants":[{"paths":["\/documentation\/shengwangchatuikit\/fonttheme\/bodyextrasmall"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/fonttheme\/bodyextrasmall"]}],"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"bodyExtraSmall","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIFont","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIFont"}],"roleHeading":"Instance Property","modules":[{"name":"ShengwangChatUIKit"}],"symbolKind":"property","role":"symbol","externalID":"c:@M@ShengwangChatUIKit@objc(cs)FontTheme(py)bodyExtraSmall","title":"bodyExtraSmall","navigatorTitle":[{"text":"bodyExtraSmall","kind":"identifier"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/FontTheme\/bodyExtraSmall"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"bodyExtraSmall","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIFont","text":"UIFont","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/FontTheme/bodyExtraSmall":{"type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"bodyExtraSmall"}],"kind":"symbol","title":"bodyExtraSmall","url":"\/documentation\/shengwangchatuikit\/fonttheme\/bodyextrasmall","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"bodyExtraSmall","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIFont","preciseIdentifier":"c:objc(cs)UIFont","kind":"typeIdentifier"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/FontTheme\/bodyExtraSmall","role":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/FontTheme":{"url":"\/documentation\/shengwangchatuikit\/fonttheme","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FontTheme"}],"abstract":[],"role":"symbol","navigatorTitle":[{"text":"FontTheme","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/FontTheme","title":"FontTheme","type":"topic"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"value":"bodyExtraSmall","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"text":"bodyExtraSmall","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"UIFont","preciseIdentifier":"c:objc(cs)UIFont"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"bodyExtraSmall"},{"kind":"text","text":";"}]}]}},{"op":"replace","value":"bodyExtraSmall","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1FontTheme~1bodyExtraSmall\/title"},{"value":[{"kind":"identifier","text":"bodyExtraSmall"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1FontTheme~1bodyExtraSmall\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1FontTheme\/title","value":"FontTheme","op":"replace"},{"op":"replace","value":[{"text":"FontTheme","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1FontTheme\/fragments"},{"value":[{"text":"FontTheme","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1FontTheme\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}