{"abstract":[{"text":"Inherited from ","type":"text"},{"code":"AgoraChatContactManagerDelegate.friendRequestDidReceive(fromUser:message:)","type":"codeVoice"},{"type":"text","text":"."}],"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatUIKitClient\/friendRequestDidReceive(fromUser:message:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatUIKitClient","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatUIKitClient\/AgoraChatContactManagerDelegate-Implementations"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"friendRequestDidReceive"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"fromUser"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"message","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?)"}],"externalID":"c:@CM@ShengwangChatUIKit@objc(cs)ChatUIKitClient(im)friendRequestDidReceiveFromUser:message:","role":"symbol","roleHeading":"Instance Method","extendedModule":"ShengwangChatUIKit","title":"friendRequestDidReceive(fromUser:message:)","modules":[{"name":"ShengwangChatUIKit"}],"symbolKind":"method","navigatorTitle":[{"text":"friendRequestDidReceiveFromUser:message:","kind":"identifier"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"friendRequestDidReceive"},{"kind":"text","text":"("},{"kind":"externalParam","text":"fromUser"},{"kind":"text","text":" "},{"text":"aUsername","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"message"},{"kind":"text","text":" "},{"kind":"internalParam","text":"aMessage"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?)"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/shengwangchatuikit\/chatuikitclient\/friendrequestdidreceive(fromuser:message:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/chatuikitclient\/friendrequestdidreceive(fromuser:message:)"]}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatUIKitClient/friendRequestDidReceive(fromUser:message:)":{"role":"symbol","kind":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatUIKitClient\/friendRequestDidReceive(fromUser:message:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"friendRequestDidReceive","kind":"identifier"},{"text":"(","kind":"text"},{"text":"fromUser","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"message","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?)","kind":"text"}],"navigatorTitle":[{"text":"friendRequestDidReceiveFromUser:message:","kind":"identifier"}],"type":"topic","url":"\/documentation\/shengwangchatuikit\/chatuikitclient\/friendrequestdidreceive(fromuser:message:)","title":"friendRequestDidReceive(fromUser:message:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatUIKitClient":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ChatUIKitClient","kind":"identifier"}],"type":"topic","abstract":[],"navigatorTitle":[{"text":"ChatUIKitClient","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatUIKitClient","role":"symbol","title":"ChatUIKitClient","url":"\/documentation\/shengwangchatuikit\/chatuikitclient"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatUIKitClient/AgoraChatContactManagerDelegate-Implementations":{"kind":"article","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatUIKitClient\/AgoraChatContactManagerDelegate-Implementations","url":"\/documentation\/shengwangchatuikit\/chatuikitclient\/agorachatcontactmanagerdelegate-implementations","type":"topic","title":"AgoraChatContactManagerDelegate Implementations","abstract":[],"role":"collectionGroup"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","value":"friendRequestDidReceiveFromUser:message:","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"friendRequestDidReceiveFromUser:message:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"friendRequestDidReceiveFromUser:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"aUsername"},{"text":" ","kind":"text"},{"text":"message:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"aMessage","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","value":"friendRequestDidReceiveFromUser:message:","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatUIKitClient~1friendRequestDidReceive(fromUser:message:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatUIKitClient~1friendRequestDidReceive(fromUser:message:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"friendRequestDidReceiveFromUser:message:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatUIKitClient\/title","value":"ChatUIKitClient"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatUIKitClient\/fragments","value":[{"kind":"identifier","text":"ChatUIKitClient"}]},{"op":"replace","value":[{"kind":"identifier","text":"ChatUIKitClient"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ChatUIKitClient\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}