{"abstract":[{"text":"Bind contacts changed listener","type":"text"}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactServiceProtocol\/bindContactEventListener(listener:)"},"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bindContactEventListener"},{"kind":"text","text":"("},{"text":"listener","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(pl)ContactEventsResponse","text":"ContactEventsResponse","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"bindContactEventListenerWithListener:"}],"symbolKind":"method","title":"bindContactEventListener(listener:)","modules":[{"name":"ShengwangChatUIKit"}],"required":true,"role":"symbol","roleHeading":"Instance Method","externalID":"c:@M@ShengwangChatUIKit@objc(pl)ContactServiceProtocol(im)bindContactEventListenerWithListener:"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactServiceProtocol"]]},"variants":[{"paths":["\/documentation\/shengwangchatuikit\/contactserviceprotocol\/bindcontacteventlistener(listener:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/contactserviceprotocol\/bindcontacteventlistener(listener:)"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"bindContactEventListener"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"listener"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactEventsResponse","kind":"typeIdentifier","text":"ContactEventsResponse","preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(pl)ContactEventsResponse"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"name":"listener","content":[{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"type":"reference","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactEventsResponse","isActive":true}]}]}],"kind":"parameters"}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ContactServiceProtocol":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"ContactServiceProtocol","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactServiceProtocol","navigatorTitle":[{"text":"ContactServiceProtocol","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/contactserviceprotocol","title":"ContactServiceProtocol","abstract":[],"kind":"symbol","type":"topic","role":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ContactServiceProtocol/bindContactEventListener(listener:)":{"abstract":[{"type":"text","text":"Bind contacts changed listener"}],"title":"bindContactEventListener(listener:)","kind":"symbol","url":"\/documentation\/shengwangchatuikit\/contactserviceprotocol\/bindcontacteventlistener(listener:)","role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactServiceProtocol\/bindContactEventListener(listener:)","required":true,"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bindContactEventListener"},{"kind":"text","text":"("},{"text":"listener","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ShengwangChatUIKit@objc(pl)ContactEventsResponse","text":"ContactEventsResponse","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"bindContactEventListenerWithListener:","kind":"identifier"}]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ContactEventsResponse":{"abstract":[],"kind":"symbol","url":"\/documentation\/shengwangchatuikit\/contacteventsresponse","navigatorTitle":[{"text":"ContactEventsResponse","kind":"identifier"}],"title":"ContactEventsResponse","role":"symbol","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactEventsResponse","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"ContactEventsResponse","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"bindContactEventListenerWithListener:","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"bindContactEventListenerWithListener:"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"bindContactEventListenerWithListener:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@ShengwangChatUIKit@objc(pl)ContactEventsResponse","text":"id<ContactEventsResponse>"},{"text":") ","kind":"text"},{"text":"listener","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/primaryContentSections\/1","op":"replace","value":{"kind":"parameters","parameters":[{"name":"listener","content":[{"inlineContent":[{"text":"","type":"text"},{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactEventsResponse","isActive":true,"type":"reference"}],"type":"paragraph"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactServiceProtocol\/title","value":"ContactServiceProtocol"},{"value":[{"text":"ContactServiceProtocol","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactServiceProtocol\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactServiceProtocol\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"ContactServiceProtocol"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactServiceProtocol~1bindContactEventListener(listener:)\/title","value":"bindContactEventListenerWithListener:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactServiceProtocol~1bindContactEventListener(listener:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"bindContactEventListenerWithListener:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactEventsResponse\/title","value":"ContactEventsResponse"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactEventsResponse\/fragments","value":[{"text":"ContactEventsResponse","kind":"identifier"}]},{"value":[{"text":"ContactEventsResponse","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactEventsResponse\/navigatorTitle"}]}]}