{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"contacts","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"attribute"},{"kind":"text","text":" ("},{"text":"ChatError","kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit0B5Errora","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatError"},{"text":"?, [","kind":"text"},{"text":"Contact","preciseIdentifier":"s:18ShengwangChatUIKit7Contacta","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/Contact","kind":"typeIdentifier"},{"kind":"text","text":"]) -> "},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"Callback, if successful it will return a string array of user id, if it fails it will return an error."}],"type":"paragraph"}],"name":"completion"}]}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/shengwangchatuikit\/contactserviceprotocol\/contacts(completion:)"]},{"paths":["\/documentation\/shengwangchatuikit\/contactserviceprotocol\/contacts(completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"Fetch contacts form server.","type":"text"}],"sections":[],"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"contacts"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"preciseIdentifier":"s:18ShengwangChatUIKit0B5Errora","text":"ChatError","kind":"typeIdentifier"},{"kind":"text","text":"?, ["},{"text":"Contact","preciseIdentifier":"s:18ShengwangChatUIKit7Contacta","kind":"typeIdentifier"},{"kind":"text","text":"]) -> "},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")","kind":"text"}],"roleHeading":"Instance Method","modules":[{"name":"ShengwangChatUIKit"}],"symbolKind":"method","role":"symbol","externalID":"c:@M@ShengwangChatUIKit@objc(pl)ContactServiceProtocol(im)contactsWithCompletion:","title":"contacts(completion:)","required":true,"navigatorTitle":[{"kind":"identifier","text":"contactsWithCompletion:"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactServiceProtocol"]]},"identifier":{"url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactServiceProtocol\/contacts(completion:)","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ContactServiceProtocol":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"ContactServiceProtocol","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactServiceProtocol","navigatorTitle":[{"text":"ContactServiceProtocol","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/contactserviceprotocol","title":"ContactServiceProtocol","abstract":[],"kind":"symbol","type":"topic","role":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ContactServiceProtocol/contacts(completion:)":{"abstract":[{"type":"text","text":"Fetch contacts form server."}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"contacts","kind":"identifier"},{"text":"(","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": ("},{"preciseIdentifier":"s:18ShengwangChatUIKit0B5Errora","text":"ChatError","kind":"typeIdentifier"},{"text":"?, [","kind":"text"},{"kind":"typeIdentifier","text":"Contact","preciseIdentifier":"s:18ShengwangChatUIKit7Contacta"},{"text":"]) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"required":true,"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"contactsWithCompletion:"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactServiceProtocol\/contacts(completion:)","title":"contacts(completion:)","url":"\/documentation\/shengwangchatuikit\/contactserviceprotocol\/contacts(completion:)"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatError":{"fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChatError"}],"role":"symbol","navigatorTitle":[{"text":"ChatError","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatError","url":"\/documentation\/shengwangchatuikit\/chaterror","title":"ChatError","kind":"symbol","abstract":[]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/Contact":{"title":"Contact","abstract":[],"url":"\/documentation\/shengwangchatuikit\/contact","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"Contact","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Contact"}],"role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/Contact"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","value":"contactsWithCompletion:","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"contactsWithCompletion:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"contactsWithCompletion:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":" (^"},{"kind":"text","text":")("},{"text":"AgoraChatError","preciseIdentifier":"c:objc(cs)AgoraChatError","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"","kind":"internalParam"},{"text":", ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<AgoraChatContact *>"},{"text":" * ","kind":"text"},{"text":"","kind":"internalParam"},{"text":")) ","kind":"text"},{"text":"completion","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"kind":"parameters","parameters":[{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"text":"Callback, if successful it will return a string array of user id, if it fails it will return an error.","type":"text"}]}]}]},"op":"replace","path":"\/primaryContentSections\/1"},{"value":"ContactServiceProtocol","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactServiceProtocol\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactServiceProtocol\/fragments","value":[{"text":"ContactServiceProtocol","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactServiceProtocol\/navigatorTitle","op":"replace","value":[{"text":"ContactServiceProtocol","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactServiceProtocol~1contacts(completion:)\/title","value":"contactsWithCompletion:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactServiceProtocol~1contacts(completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"contactsWithCompletion:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}