{"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"paths":["\/documentation\/shengwangchatuikit\/contactserviceprotocol\/deviceidsonotherplatformofcurrentuser(completion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/shengwangchatuikit\/contactserviceprotocol\/deviceidsonotherplatformofcurrentuser(completion:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactServiceProtocol\/deviceIdsOnOtherPlatformOfCurrentUser(completion:)"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactServiceProtocol"]]},"kind":"symbol","metadata":{"roleHeading":"Instance Method","externalID":"c:@M@ShengwangChatUIKit@objc(pl)ContactServiceProtocol(im)deviceIdsOnOtherPlatformOfCurrentUserWithCompletion:","symbolKind":"method","modules":[{"name":"ShengwangChatUIKit"}],"title":"deviceIdsOnOtherPlatformOfCurrentUser(completion:)","required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"deviceIdsOnOtherPlatformOfCurrentUser"},{"kind":"text","text":"("},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:18ShengwangChatUIKit0B5Errora","text":"ChatError"},{"text":"?, [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"]) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"deviceIdsOnOtherPlatformOfCurrentUserWithCompletion:"}],"role":"symbol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"deviceIdsOnOtherPlatformOfCurrentUser"},{"kind":"text","text":"("},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"attribute"},{"kind":"text","text":" ("},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatError","text":"ChatError","preciseIdentifier":"s:18ShengwangChatUIKit0B5Errora"},{"text":"?, [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"]) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"languages":["swift"]}]},{"parameters":[{"name":"completion","content":[{"inlineContent":[{"type":"text","text":"Callback, if successful it will return a string array of user id, if it fails it will return an error."}],"type":"paragraph"}]}],"kind":"parameters"}],"abstract":[{"type":"text","text":"Get the device ID array of all current user logins except the current device."}],"references":{"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit","title":"ShengwangChatUIKit","abstract":[],"role":"collection","url":"\/documentation\/shengwangchatuikit","kind":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ChatError":{"fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChatError"}],"role":"symbol","navigatorTitle":[{"text":"ChatError","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ChatError","url":"\/documentation\/shengwangchatuikit\/chaterror","title":"ChatError","kind":"symbol","abstract":[]},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ContactServiceProtocol":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"ContactServiceProtocol","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactServiceProtocol","navigatorTitle":[{"text":"ContactServiceProtocol","kind":"identifier"}],"url":"\/documentation\/shengwangchatuikit\/contactserviceprotocol","title":"ContactServiceProtocol","abstract":[],"kind":"symbol","type":"topic","role":"symbol"},"doc://org.cocoapods.ShengwangChatUIKit/documentation/ShengwangChatUIKit/ContactServiceProtocol/deviceIdsOnOtherPlatformOfCurrentUser(completion:)":{"identifier":"doc:\/\/org.cocoapods.ShengwangChatUIKit\/documentation\/ShengwangChatUIKit\/ContactServiceProtocol\/deviceIdsOnOtherPlatformOfCurrentUser(completion:)","abstract":[{"type":"text","text":"Get the device ID array of all current user logins except the current device."}],"title":"deviceIdsOnOtherPlatformOfCurrentUser(completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"deviceIdsOnOtherPlatformOfCurrentUser","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": (","kind":"text"},{"preciseIdentifier":"s:18ShengwangChatUIKit0B5Errora","text":"ChatError","kind":"typeIdentifier"},{"kind":"text","text":"?, ["},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"]) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"deviceIdsOnOtherPlatformOfCurrentUserWithCompletion:"}],"role":"symbol","required":true,"url":"\/documentation\/shengwangchatuikit\/contactserviceprotocol\/deviceidsonotherplatformofcurrentuser(completion:)","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"deviceIdsOnOtherPlatformOfCurrentUserWithCompletion:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"deviceIdsOnOtherPlatformOfCurrentUserWithCompletion:","kind":"identifier"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"text":"deviceIdsOnOtherPlatformOfCurrentUserWithCompletion:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":" (^"},{"text":")(","kind":"text"},{"preciseIdentifier":"c:objc(cs)AgoraChatError","text":"AgoraChatError","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"text":"","kind":"internalParam"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"NSArray<NSString *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" * ","kind":"text"},{"text":"","kind":"internalParam"},{"kind":"text","text":")) "},{"text":"completion","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":{"kind":"parameters","parameters":[{"name":"completion","content":[{"inlineContent":[{"type":"text","text":"Callback, if successful it will return a string array of user id, if it fails it will return an error."}],"type":"paragraph"}]}]},"path":"\/primaryContentSections\/1","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactServiceProtocol\/title","value":"ContactServiceProtocol","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactServiceProtocol\/fragments","value":[{"text":"ContactServiceProtocol","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactServiceProtocol\/navigatorTitle","value":[{"text":"ContactServiceProtocol","kind":"identifier"}]},{"op":"replace","value":"deviceIdsOnOtherPlatformOfCurrentUserWithCompletion:","path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactServiceProtocol~1deviceIdsOnOtherPlatformOfCurrentUser(completion:)\/title"},{"value":[{"kind":"text","text":"- "},{"text":"deviceIdsOnOtherPlatformOfCurrentUserWithCompletion:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ShengwangChatUIKit~1documentation~1ShengwangChatUIKit~1ContactServiceProtocol~1deviceIdsOnOtherPlatformOfCurrentUser(completion:)\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}